### ISSUE TITLE
Transparency mode two passes one side behaves differently for multiple meshes

### ISSUE THREAD

**Issue by obeletski** [google/filament#1000]
We are using TransparencyMode::TWO_PASSES_ONE_SIDE to force transparency over model on some steps of user interaction. The idea is to make all meshes of the e.g gltf model transparent without introducing additional details of the model that are hidden with original materials definitions (in other words do not reveal parts of the model that were covered by opaque mesh). That related to my previous question #777.

We applied transparency for gltf models loaded with gltf_viewer on Linux desktop and realized that TransparencyMode::TWO_PASSES_ONE_SIDE behaves differently for models that contain single mesh vs. multiple meshes.

In case of single mesh things behave as we were hoping, while for complex models inner elements started to appear in the view.

That is one of the model that we were experimenting with:https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/2CylinderEngine

We modified code of MaterialGenerator.cpp:

    builder.blending(MaterialBuilder::BlendingMode::TRANSPARENT);
    builder.transparencyMode(TransparencyMode::TWO_PASSES_ONE_SIDE);

and shader:

        material.baseColor.a = 0.5;
        material.baseColor.rgb *= material.baseColor.a;

**Comment by romainguy** [comment]
It doesn't behave differently, it's an effect that works per draw-call. So if you have meshes embedded inside other meshes, they will indeed be visible. What you want would require a more complex solution.
