### ISSUE TITLE
material-builder sample on Android missing x86_64/libfilamat.a

### ISSUE THREAD

**Issue by obeletski** [google/filament#1001]
Please help to build material-builder sample. One library is still missing.

~/open/filament/android/samples/material-builder$ ./gradlew assemble

> Task :filamat-android:externalNativeBuildRelease FAILED
Build filamat-jni x86_64
ninja: error: '/home/user/open/filament/out/android-release/filament/lib/x86_64/libfilamat.a', needed by '../../../../build/intermediates/cmake/release/obj/x86_64/libfilamat-jni.so', missing and no known rule to make it

**Comment by romainguy** [comment]
You have to build it first with `buiild.sh -i -p android release`.

**Comment by bejado** [comment]
Since `filamat` takes a little longer to build, it's hidden behind a flag- you'll need to add the `-l` flag to the `build.sh` script:

```
    -l
        Add filamat support to the Android build.
```

So the final command is:

```
build.sh -i -l -p android release
```

**Comment by romainguy** [comment]
Good point I forgot about that flag, thanks for the clarification! Maybe we should emphasize this a little bit in the `README.md` or maybe we should add a `README.md` in the material-builder sample and filamat-android.

**Comment by romainguy** [comment]
Note that you may need to delete your CMake output directory first for the flag to be taken into account.

**Comment by romainguy** [comment]
We had a bug in the headers which would cause filamat to not compile. I'm uploading a PR that always compiles filamat from now on so we can catch these issues. This also means the `-l` flag isn't required anymore.
