### ISSUE TITLE
Latency with setImage

### ISSUE THREAD

**Issue by heitaoflower** [google/filament#1002]
Hi guys, I am want to upload video image each frame.

looks like this  code snippet which will be called each frame.

`cv::cvtColor(frame.clone(), frame, cv::COLOR_BGR2RGB);

				app.frameData->fill(frame.data);

				if (app.tex != nullptr)
				{
					Texture::PixelBufferDescriptor desc(app.frameData->buffer, size_t(width * height * 3),
						Texture::Format::RGB, Texture::Type::UBYTE);

					app.tex->setImage(*engine, 0, std::move(desc));
				}`

however I found that the presentation in screen always appears obvious latency, I just wondering if you guys can share some educated options with me,  thanks.

**Comment by romainguy** [comment]
`setImage` will schedule the texture upload on the render thread, which should happen before the end of the frame. Other than that, there's no other built-in latency, so it might just be the CPU outpacing the GPU when producing frames?

**Comment by heitaoflower** [comment]
Oh, Thanks, you are right, I recall that the render was implemented with command-buffer,  it is a potent symbol for  multi-thread.

so I need to redress the balance.
