### ISSUE TITLE
Implement ShadowMap for multiple lights

### ISSUE THREAD

**Issue by MHDante** [google/filament#1018]
Hi there. Filament currently estimates shadows for a single directional light. Would it be possible to extend this implementation to support shadows on both multiple and different types of lights? I understand that this comes at the performance cost of additional shadowmap passes, so perhaps it should be enabled through configuration.

**Comment by romainguy** [comment]
We want to add support for spot light shadows, as well as cascaded shadow maps for the directional light, etc. We've been talking recently with @pixelflinger on what would be the best approach (atlas, texture arrays, etc.).

**Comment by pixelflinger** [comment]
The curent thinking would be to add 2-4 cascades for the directional light, and support 4 spot-lights, with no support for point-lights and no cascades.

**Comment by romainguy** [comment]
Work for shadowed spotlights is ongoing. It should be available soonish.

**Comment by romainguy** [comment]
Spot light shadows are now supported.
