### ISSUE TITLE
Seems to be F_Schlick misprint in shaders generated 

### ISSUE THREAD

**Issue by GeorgeSarkisyan** [google/filament#1029]
**Describe the bug**

In Filament.html document:
vec3 F_Schlick(float VoH, vec3 f0, float f90) {
    return f0 + (vec3(f90) - f0) * pow(1.0 - VoH, 5.0);
}

In the shaders generated:

vec3 F_Schlick(const vec3 f0, float f90, float VoH) {
    // Schlick 1994, "An Inexpensive BRDF Model for Physically-Based Rendering"
    float f = pow5(1.0 - VoH);
    return f + f0 * (f90 - f);
}

seems that f0 and f are swapped

No difference when f90 = 1.0 but in general this matters

**Comment by romainguy** [comment]
Which shader are you talking about? This implementation is not in the engine: https://github.com/google/filament/blob/master/shaders/src/brdf.fs#L141

**Comment by romainguy** [comment]
Filament.html does use this formulation but it specifically uses f90=1 to justify it. Let me know if the incorrect code still appears anywhere else.

**Comment by GeorgeSarkisyan** [comment]
Ok. Looks like I have rather old code. The problem I was talking about you already have fixed here:
 96d3846 Fix Schlick Fresnel when f90 < 1

**Comment by romainguy** [comment]
Oh yeah that was fixed a while ago. That code was never called with an f90 not set to 1.0 though (if I remember correctly).
