### ISSUE TITLE
Web: Depth culling issues with multiple renderables

### ISSUE THREAD

**Issue by John-DeCorato-HZ** [google/filament#1030]
Adding multiple objects to the scene seems to result in incorrect depth culling. In a simple example, I'm creating two triangles and setting their materials to basic opaque unlit materials. These are the two triangles:
```javascript
// triangle 1
let verts1 = [
  0, 1, 0,
  -1, -1, 1,
  1, -1, 1
];
let inds1 = [0, 1, 2];
// triangle 2
let verts2 = [
  0, 2, -1,
  -1, -0, -1,
  1, -0, -1
];
let inds2 = [0, 1, 2];
```

This is the result when rendering with the following material:
```
material {
    name : Unlit,
    shadingModel : unlit,
    parameters : [
        { type: float3, name: baseColor }
    ]
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor.rgb = materialParams.baseColor;
    }
}
```
![broken_depth](https://user-images.githubusercontent.com/20100243/54843682-3a62cb00-4c92-11e9-8d06-de80ba669849.png)

Creating a new material with the transparent flag enabled and setting either one of the triangles to that new material results in this image.
![working_depth](https://user-images.githubusercontent.com/20100243/54843724-54041280-4c92-11e9-9920-8b91fa576af9.png)

Setting both to the transparent material results in the first image.

**Comment by romainguy** [comment]
Which one is triangle 1 in those screenshots, the blue one or the red one?

Also, do you provide the bounding boxes for your objects? The sorting algorithm for transparents uses the bounding boxes.

**Comment by John-DeCorato-HZ** [comment]
Triangle 1 is the red triangle, triangle 2 is the blue.

Bounding boxes are calculated for both of them and are provided. I can get them for you if you'd like.

The camera setup is as follows:
```javascript
let mat = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 5, 1];
this.camera.setModelMatrix(mat4.fromValues(mat));
this.camera.setProjectionFov(45, 1.0, 0.1, 100.0, 
    Filament.Camera$Fov.VERTICAL);
this.view.setScene(this.scene);
this.view.setClearColor([0.1, 0.1, 0.1, 1.0]);
this.renderer.render(this.swapChain, this.view);
```

**Comment by romainguy** [comment]
What do you get if you remove your call to `camera.setModelMatrix`?

**Comment by John-DeCorato-HZ** [comment]
I removed the call and got this result:
![no camera matrix](https://user-images.githubusercontent.com/20100243/54848898-c9c2ab00-4c9f-11e9-85c4-061bdfc00a1a.png)

Replacing it with a lookAt call has the same error.

**Comment by John-DeCorato-HZ** [comment]
I'm trying to reproduce this in a simpler code snippet and I cannot easily do so. I'll scour my own code again and see if I can isolate things.

**Comment by John-DeCorato-HZ** [comment]
Ah, I figured out the difference. I had done `view.setPostProcessingEnabled(false)` to (what I assumed it does) turn off tone mapping. It appears to have broken the depth testing for the main render pass. Is this expected?

**Comment by romainguy** [comment]
Ah yes indeed. There's currently an issue when disabling post processing: you lose the depth buffer.

**Comment by prideout** [comment]
Hi @John-DeCorato-HZ , I think you need to replace

`const engine = Filament.Engine.create(this.canvas);`

with:

`const engine = Filament.Engine.create(this.canvas, {depth: true});`

This is somewhat documented [here](https://google.github.io/filament/webgl/reference.html#Engine).

Does this help?

**Comment by John-DeCorato-HZ** [comment]
Yes, that fixed it. Thank you!
