### ISSUE TITLE
Android FBX support

### ISSUE THREAD

**Issue by firetrap** [google/filament#1034]
First of all congratulations for the good documentation and awesome project you guys made.
I've build and run your transparent-view (Android sample) with success and after that tried to load a simple fbx model but with no effort.
Can you give me some highlights or some sample how we can do it?
Thank you, keep the good work.

**Comment by prideout** [comment]
Thanks for the kind words!  Currently our preferred last-mile format for 3D models is glTF, would that work for you?

**Comment by firetrap** [comment]
Yes glTF will also work. There are too many formats in the 3D market this should be an issue for you guys to support them all. Do you have any sample or docs with glTF?

**Comment by romainguy** [comment]
There's a library called gltfio in our source tree, but we don't have Java bindings for it yet. You can also use the filamesh tool to convert fbx, obj, etc. to our runtime efficient filamesh format and use the mesh loader class from the Android samples. Note however that this format doesn't support animations and only mesh data (you get the names of the materials but it doesn't store material definitions).

**Comment by prideout** [comment]
Agreed with Ben that we should close this, we plan on exposing Java bindings for gltfio, and have no plans for supporting FBX.
