### ISSUE TITLE
iOS example of Filament with ARKit

### ISSUE THREAD

**Issue by luanbach** [google/filament#1046]
I'm looking to use Filament in an AR app on iOS and was wondering how to use it with ARKit, with the environment lighting, anchor and scaling etc. I'm after an example if that's possible.

**Comment by bejado** [comment]
I have plans to add a sample. Given an `ARFrame`, It should be straightforward to use `camera.projectionMatrix` to position Filament's camera along with the transforms in `anchors` to position objects. Filament doesn't have the concept of ambient lighting, but you could use `lightEstimate` to control the IBL intensity.

The piece of the puzzle that's missing at the moment is efficiently rendering the camera feed through Filament. We need the ability to use the `capturedImage` (a `CVPixelBufferRef`) as a Filament texture to enable rendering the camera backdrop.

**Comment by luanbach** [comment]
Is it possible to add a shader to write the camera texture ?

**Comment by romainguy** [comment]
To customize how the camera stream is displayed you mean? We're working on adding support for external textures on iOS to display the camera stream.

**Comment by luanbach** [comment]
That sounds good. In the short term I was thinking of creating a giant polygon and render the ARFrame texture onto it, does that sounds reasonable ?

**Comment by romainguy** [comment]
That's how we do it on Android. A full screen triangle in device space and we just map a texture on it with a custom material. It's very similar to how the skybox works.

**Comment by luanbach** [comment]
> I have plans to add a sample. Given an `ARFrame`, It should be straightforward to use `camera.projectionMatrix` to position Filament's camera along with the transforms in `anchors` to position objects. Filament doesn't have the concept of ambient lighting, but you could use `lightEstimate` to control the IBL intensity.

Do you have an example of how to scale and position the Mesh/Entity object ?

**Comment by romainguy** [comment]
Here's an example from our sample apps:

```
    auto& tcm = engine->getTransformManager();
    auto ei = tcm.getInstance(myRenderable);
    tcm.setTransform(ei, mat4f{ mat3f(scale), float3(0.0f, 0.0f, -4.0f) } *
            tcm.getWorldTransform(ei));
```

This scales and translates `myRenderable`.

**Comment by bejado** [comment]
@luanbach See #1124.
