### ISSUE TITLE
On iOS, the Engine object crashed on destroying its children

### ISSUE THREAD

**Issue by luanbach** [google/filament#1061]
**Describe the bug**
I'm having problems with cleaning up the Filament rendering/runtime when switching views.
The Engine is crashing when I call destroy on the renderable.

**To Reproduce**
I've attached a modified hello-pbr example that shows the problem.
Run the hello-pbr-Metal target
Click the Load Filament button
Go Back after the renderer has started
Click on the Load button again

[hello-pbr.zip](https://github.com/google/filament/files/3028666/hello-pbr.zip)

**Expected behavior**
Should be able to delete and recreate Filament views.

**Desktop (please complete the following information):**
 - OS: iOS
 - Backend: Vulkan

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: 12.2

**Additional context**
Crash log
```
utils::PreconditionPanic
in void utils::JobSystem::adopt():455
in file ../../libs/utils/src/JobSystem.cpp
reason: Called adopt on a thread owned by another JobSystem (0x10872c910), this=0x10b444910!
#0 0   hello-pbr-Metal                     0x0000000104c2e080 _ZN5utils9CallStack6updateEm + 32
#1 0   hello-pbr-Metal                     0x0000000104c4254c _ZN5utils6TPanicINS_17PreconditionPanicEEC2EPKcS4_iNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 192
#2 0   hello-pbr-Metal                     0x0000000104c43be0 _ZN5utils17PreconditionPanicCI2NS_6TPanicIS0_EEEPKcS3_iNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE + 68
#3 0   hello-pbr-Metal                     0x0000000104c42028 _ZN5utils17PreconditionPanicCI1NS_6TPanicIS0_EEEPKcS3_iNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE + 52
#4 0   hello-pbr-Metal                     0x0000000104c41e00 _ZN5utils6TPanicINS_17PreconditionPanicEE5panicEPKcS4_iS4_z + 240
#5 0   hello-pbr-Metal                     0x0000000104c3c1b4 _ZN5utils9JobSystem5adoptEv + 132
#6 0   hello-pbr-Metal                     0x0000000104adabc8 _ZN8filament7details7FEngineC2ENS_7backend7BackendEPNS2_8PlatformEPv + 1128
#7 0   hello-pbr-Metal                     0x0000000104ad9c78 _ZN8filament7details7FEngineC1ENS_7backend7BackendEPNS2_8PlatformEPv + 56
#8 0   hello-pbr-Metal                     0x0000000104ad9aa0 _ZN8filament7details7FEngine6createENS_7backend7BackendEPNS2_8PlatformEPv + 88
#9 0   hello-pbr-Metal                     0x0000000104ae0acc _ZN8filament6Engine6createENS_7backend7BackendEPNS1_8PlatformEPv + 44
#10 0   hello-pbr-Metal                     0x0000000104a86288 _ZN11FilamentApp10initializeEv + 76
#11 0   hello-pbr-Metal                     0x0000000104a8b9c4 -[FilamentView initWithCoder:] + 472
#12 0   UIKitCore                           0x00000001dfc60410 <redacted> + 252
#13 0   UIFoundation                        0x00000001bdcfb8a0 <redacted> + 748
#14 0   UIFoundation                        0x00000001bdc99b18 <redacted> + 320
#15 0   UIKitCore                           0x00000001dfc64a94 <redacted> + 192
#16 0   UIFoundation                        0x00000001bdcfb8a0 <redacted> + 748
#17 0   UIFoundation                        0x00000001bdcfbae4 <redacted> + 1328
```

Callstack
```
#0	0x00000001027a6774 in filament::details::FMaterialInstance::getMaterial() const at /Users/luanbach/dev/filament/filament/src/details/MaterialInstance.h:73
#1	0x0000000102795670 in filament::details::FEngine::destroy(filament::details::FMaterialInstance const*) at /Users/luanbach/dev/filament/filament/src/Engine.cpp:737
#2	0x0000000102795628 in filament::Engine::destroy(filament::MaterialInstance const*) at /Users/luanbach/dev/filament/filament/src/Engine.cpp:882
#3	0x000000010273ac94 in FilamentApp::~FilamentApp() at /Users/luanbach/dev/filament/ios/samples/hello-pbr/hello-pbr/FilamentApp.cpp:105
#4	0x000000010273ae88 in FilamentApp::~FilamentApp() at /Users/luanbach/dev/filament/ios/samples/hello-pbr/hello-pbr/FilamentApp.cpp:104
#5	0x000000010273fdb0 in ::-[FilamentView dealloc]() at /Users/luanbach/dev/filament/ios/samples/hello-pbr/hello-pbr/FilamentView.mm:71
#6	0x00000001b2602f7c in objc_release ()
```

**Comment by romainguy** [comment]
Looks like we're trying to initialize several times?

**Comment by bejado** [comment]
It's possible this is a bug on our side. The `FilamentView` in the sample project wasn't designed to be instantiated and destroyed over and over again and there may be an issue there. Like Romain said, the engine is getting initialized multiple times inside of `FilamentApp::initialize`, which may cause issues if there is another engine instance (in another `FilamentApp`) running simultaneously.

**Comment by luanbach** [comment]
That was what I thought. Hence I was trying to shut down the engine gracefully by unlinking the display and removing its objects before removing the engine object. It didn't get as far as freeing up all the pointers.

**Comment by bejado** [comment]
The issue is that the navigation controller does not dealloc `FilamentView` when the "back" button is tapped. When "Load Filament" is tapped for the second time, _another_ `FilamentView` is instantiated before the first one has a chance to shutdown.

You might want to use the [`viewWillAppear` and `viewDidDisappear`](https://stackoverflow.com/questions/2210290/uinavigationcontroller-when-does-a-pushed-view-receive-the-dealloc-message) methods instead to manage the engine's lifecycle.

**Comment by luanbach** [comment]
That is a good point. I actually had viewDidDissapear ready, can't remember why I thought it wouldn't make any difference.

**Comment by bejado** [comment]
That should fix the crash at least, but in general, creating and destroying a Filament engine is expensive. A better design might be one that keeps a single engine alive for the entire lifetime of the app.

**Comment by luanbach** [comment]
> That should fix the crash at least, but in general, creating and destroying a Filament engine is expensive. A better design might be one that keeps a single engine alive for the entire lifetime of the app.

What do I need to think about if I re-init the Engine? At the minimum I think I have to recreate the swapchain and the view ?

**Comment by bejado** [comment]
If you keep a single engine instance for the whole app, then the only thing you need to recreate is the swapchain because it's tied to a specific `CAEAGLLayer` or `CAMetalLayer`.

**Comment by luanbach** [comment]
Thank you for the help.
