### ISSUE TITLE
Can't use "lookAt"

### ISSUE THREAD

**Issue by lukkio88** [google/filament#1062]
Hi there,

I'm trying to set up a very simple scene, and the relevant bit is that I want to setup an ortographic projection + a certain pose of the camera.

With this in mind, I've some code that no matter how I set up the model camera I cannot see any change at all.

If I change the parameters of the orthogonal projection I see changes related to such projection but no matter what I do with the model matrix I cannot manage to see any changes.

The step I have at the moment are

 ```
float3 upVector{0.0f,10.0f,0.0f};
    float3 cameraEye = baricenter;
    float3 un_norm_d = float3(0.0f,0.0f,100.0f*delta_y);
    float3 cameraCenter = baricenter - un_norm_d;

    mat4f modelMat = mat4f::lookAt(cameraEye,cameraCenter,upVector);
    camera.setModelMatrix(modelMat);

    //setting orthographic projection
    float3 minBoundScene = g_sun_cg_scene->boundingBoxScene.minBound;
    float3 maxBoundScene = g_sun_cg_scene->boundingBoxScene.maxBound;

    camera.setCustomProjection(mat4::ortho(
            minBoundScene[0],maxBoundScene[0],
            minBoundScene[1],maxBoundScene[1],
            -1000.0f,1000.0f),-1000.0f,1000.0f);
```

Then I iterate through all my renderable objects and I setup their position in world space.
Is there maybe something I'm missing about the order I use to specify the camera parameters?

**Comment by romainguy** [comment]
We use `lookAt` in our sample apps without any issue. How do you position your objects and how do you try to move the camera?

**Comment by lukkio88** [comment]
Can you mention a specific example where the function is used? The objects are positioned with the following call:

`auto ei = transformManager.getInstance(renderable);
        transformManager.setTransform(ei,mat4f{getRotMatrix(obj.m_Pose.angle, obj.m_Pose.axis),
                                                obj.m_Pose.translation});`

And this was working. Can you point out a specific sample I can use as a reference?

**Comment by lukkio88** [comment]
Just to be more specific, and I don't know if this matters. I'm setting the camera in the "setup" function.

**Comment by lukkio88** [comment]
Also is it my impression or the roles of `eye` and `camera` are different in the two `lookAt` functions?

Compare

```
/*
 * Returns a matrix representing the pose of a virtual camera looking towards -Z in its
 * local Y-up coordinate system. "eye" is where the camera is located, "center" is the points its
 * looking at and "up" defines where the Y axis of the camera's local coordinate system is.
 */
template <typename T>
template <typename A, typename B, typename C>
constexpr TMat44<T> TMat44<T>::lookAt(const TVec3<A>& eye, const TVec3<B>& center, const TVec3<C>& up) {
   //bla bla
}
```

Vs
```

/** Sets the camera's view matrix
*
* @param eye       The point in world space the camera is looking at.
* @param center    The position of the camera in world space.
* @param up        A unit vector denoting the camera's "up" direction.
*/
void lookAt(const filament::math::float3& eye,
                const filament::math::float3& center,
                const filament::math::float3& up = { 0, 1, 0 }) noexcept;
```

Both taken from your code. From the comments it seems to me that `eye` and `camera` are used in different ways.

Can you confirm?

**Comment by nitronoid** [comment]
Looking at the source, the camera `lookAt` function calls the mat4 function, so that must be a documentation flaw. https://github.com/google/filament/blob/ca7f942b7b92383b1aa873f73dd5fa556c816884/filament/src/Camera.cpp#L170-L172
 In my own code, I use eye as the camera position and center as the target it is looking at, which gives me the correct result. Did you try swapping those two parameters?

**Comment by romainguy** [comment]
The documentation is wrong. Eye is the camera position and center the point it's looking at. And one calls the other indeed.

**Comment by lukkio88** [comment]
Eye of which function? `mat4::lookAt` or `FCamera::lookAt`? The latter seems to be equal to `Camera::lookAt`

**Comment by romainguy** [comment]
The one from camera apparently.

**Comment by pixelflinger** [comment]
Good catch! in `Camera.h` the documentation for `eye` and `center` is swapped.

**Comment by pixelflinger** [comment]
@lukkio88 it's preferable to use `setProjection(Camera::Projection::ORTHO, ...)` instead of `setCustomProjection()` -- that being said, it should work.

**Comment by romainguy** [comment]
The documentation should be fixed now

**Comment by theCodes7** [comment]
lookat is not taking effect while using in Android. Any thought on that? 
` public void lookAt(double eyeX, double eyeY, double eyeZ,
            double centerX, double centerY, double centerZ, double upX, double upY, double upZ) `

**Comment by romainguy** [comment]
I used it a couple of hours ago on Android, it was working fine. What issue are you running into?

**Comment by theCodes7** [comment]
Okay, if I am using any modelViewer. How can it be applied?`viewer?.camera?.lookAt(
                    0.0, 0.0, 0.0,
                    direction.x.toDouble(), 0.3, direction.z.toDouble(),
                    0.0, 1.0, 0.0
                )` resulting in the no effect.

**Comment by prideout** [comment]
Your lookAt is getting overridden by the `ModelViewer` helper class, which does certain things for you, including management of the view matrix.  If you'd like, you can pass in a custom camera manipulator object when constructing your model viewer instance.

If you need more control than what ModelViewer and the camera manipulator give you, you can create your own copy of the ModelViewer class and modify it how you see fit.
