### ISSUE TITLE
Rendering to flat file image

### ISSUE THREAD

**Issue by sleroux** [google/filament#1065]
Hey there!

I'm looking to use Filament to render a glTF scene into an image on disk instead of using a windowed viewer application. From the sample code I can see how I could load in my scene and render a single frame from the camera but I couldn't seem to find any way of taking the rendered result in the `View` object and outputting it into an image. Does filament offer an API for doing this?

**Comment by romainguy** [comment]
You can use the readPixels() method on Renderer to achieve this.

**Comment by romainguy** [comment]
Let us know if you need anything more, thanks!
