### ISSUE TITLE
Using filament along with ARCore (using Sceneform)giving conflicts

### ISSUE THREAD

**Issue by Raki** [google/filament#1067]
We are using filament to render 3D content in our android and iOS app. We got very good results because of filament, thank you so much this wonderful library. 

Now we trying to add support of ARCore to our android app, but when we integrate ARCore into our app it is conflicting with filament . It is giving following error

`Error: Program type already present: com.google.android.filament.AndroidPlatform`

We tried by removing filament .aar dependency hoping that we can access the same from sceneform as sceneform internally uses filament. But filament is not being initialized if we remove .aar dependency.

Is our approach is wrong ? using filament and ARCore with sceneform in the same app

**Comment by romainguy** [comment]
Are you trying to use ARCore or Sceneform? ARCore doesn't use Filament but Sceneform does.

**Comment by Raki** [comment]
@romainguy  , sorry for the typo. Yes we are using sceneform to render in ARCore.

**Comment by romainguy** [comment]
My recommendation would be to either use only Sceneform or to use Filament+ARCore. Are there specific features of Filament not available in Sceneform that you need?

**Comment by SomenathMondal1993** [comment]
@romainguy , I have multiple .obj files (body, hair, apparel, shoes) that I want to download dynamically in the app and render immediately. I want a similar experience in AR as well. Is Filament + ARCore the best way forward? Could you give some tips how to proceed?

**Comment by Raki** [comment]
@romainguy thank you for the suggestion. No ,I didn't find any of our required features of filament missing in sceneform,it is good for us. For AR part, requirement is simple so modifying the samples of ARCore solved our purpose, so I just tried integrating that into our application. Anyways I will try with filament+ARCore.  Thank you.

**Comment by romainguy** [comment]
@Raki If Sceneform has everything you want, you might want to use it instead of Filament+ARCore as it will do a lot of the work for you (tracking of objects, setting up the camera, etc.).

@SomenathMondal1993 Filament + ARCore will work for your use case. We don't provide an OBJ loader library (yet), but we do have a glTF loader (no Java bindings yet though, you'd have to make your own or use native code). There are tons of OBJ loaders out there though.

**Comment by Raki** [comment]
@romainguy, understood. Thank you very much.

**Comment by manugomez95** [comment]
Hi, I have this problem and I do need both Sceneform and Filament (since I create a custom mesh with it). Are there any news on this?

**Comment by romainguy** [comment]
Sceneform uses Filament already. You can either file feature requests with Sceneform or use ARCore directly with Filament.

**Comment by jaccen** [comment]
hi  @Raki 
have you resolved the problem ?
i alse meet this problem ,i want to use arcore + filement,
will u please share your experience？ my email jaccen2007@163.com

**Comment by SandeepKumarUdarapu97** [comment]
I need to play with filament through React-native is this possible.
