### ISSUE TITLE
Support for KHR_materials_pbrSpecularGlossiness in glTF I/O

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1068]
I'm not actually using the GLTF importer that @prideout has written, but it's a very valuable reference for translating the GLTF spec to the Filament engine in my own importer. Are then any plans to support the [KHR_materials_pbrSpecularGlossiness](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness) extension?

I'm guessing that _diffuse_ would map to _baseColor_ and _glossiness_ would map to _1 - roughness_, but is there a suitable mapping for _specular_?

**Comment by romainguy** [comment]
There is a mapping for specular, yes. You can find it in our MeshAssimp.cpp file (when we load .obj meshes). Specular color will be more complicated.

**Comment by prideout** [comment]
Note to self, here's a good test model, it seems to use specular glossiness without a fallback:

https://sketchfab.com/3d-models/racing-bicycle-223901fe94de4d55b6324e7d7e273469

**Comment by prideout** [comment]
I made a PR but it doesn't implement this extension correctly.  A correct implementation would require adding a new shading model to Filament (in addition to cloth, ss, etc) that does something like this:

```
pixel.diffuseColor = baseColor.rgb * (1.0 - max(specularTint.r, specularTint.g, specularTint.b));
pixel.f0 = specularTint;
```

Discussed a little with @romainguy, we think this is a weird model that doesn't seem very physically based (maybe artists like it??)

For now, I'm inclined to close this issue unless there is a compelling need.

**Comment by prideout** [comment]
Update: due to popular demand we'll probably go ahead and add a new shading model to Filament itself.
