### ISSUE TITLE
Nvidia Nsight crash

### ISSUE THREAD

**Issue by sienaiwun** [google/filament#1087]
**Describe the bug**
I build filament using LLVM, VS2017, Windows 10 and I want to see how it works via NSight. However, I meet a Nsight crash when I launch the material_sandbox.exe

**To Reproduce**
1. Compile filament following the guide of VS2017. 
2. Use Nsight to Launch material_sandbox.exe. set argument as cloth.obj (with its absolute path)
3. Nsight crash happens

**Expected behavior**
I want to use Nsight to do graphics debugging of filament

**Desktop (please complete the following information):**
 - OS: Win10
 - GPU: NVIDIA GTX 1050
 - Backend: OpenGL

**Comment by sienaiwun** [comment]
I use Nsight 5.5

**Comment by romainguy** [comment]
Hi, does the app crash without nsight? If not it sounds like an nsight issue.

**Comment by bejado** [comment]
I haven't used Nsight with Filament, but I have had success using [RenderDoc](https://renderdoc.org/) on Windows if you're interested in debugging frames.

**Comment by sienaiwun** [comment]
It does not crash without nsight. 
I can use Renderdoc as well. However, pixel history and shader debugging are not available, maybe because Filament uses OpenGL.
