### ISSUE TITLE
Access to the mesh data structure

### ISSUE THREAD

**Issue by lukkio88** [google/filament#1089]
Hi all,

When I load a mesh using something like

```
std::unique_ptr<MeshAssimp> m_Mesh;
//bla bla
m_Mesh->addFromFile(...)
```

Is there a way for me to access both the single vertices (like an iterator) and the related adjacency info?

Like if I wanted to write

```
for(auto v : mesh->vertices) 
   for(auto w : mesh->neigh(v))
       doSomething(v,w);
```

How can I access to the relevant info? I can see MeshAssimp has a data member getRenderables, I would assume I need to use this some how.

Can you tell me how to do it?

**Comment by romainguy** [comment]
MeshAssimp is a simple example of how to use Assimp, it is not meant for general mesh manipulation. In particular it does not keep any adjacency information. You'd have to modify it yourself to achieve this.
