### ISSUE TITLE
Access to VertexBuffer and layout

### ISSUE THREAD

**Issue by lukkio88** [google/filament#1090]
Related to this: https://github.com/google/filament/issues/1089

I can see the MeshAssimp has both vertex buffer and index buffer (as private data members)
Is it possible to get access to these somehow without modifying the existing class (including the vertex layout)?

Thank you

**Comment by romainguy** [comment]
Like mentioned in the previous issue, MeshAssimp is a fairly simple example of how to use Assimp and it's not a public API of filament. Feel free to copy it or change it however you'd like.
