### ISSUE TITLE
Android textured-object sample fails with Vulkan

### ISSUE THREAD

**Issue by prideout** [google/filament#1096]
`hello-triangle` works fine but `textured-object` fails on a Pixel 3 during `vkCreateGraphicsPipelines` and the Adreno driver reports that this is due to a shader link error.

**Comment by prideout** [comment]
The failure does not occur if post-processing is disabled so it reminds me a little of #732

**Comment by prideout** [comment]
Does not occur with Mali, this appears to be specific to Adreno.

It works on Adreno if I remove dithering from the post-process fragment shader.

**Comment by prideout** [comment]
When using a debug of version of Filament (and changing the Android projects to use that instead of release), this disables shader optimizations, but the issue still crops up. In fact is occurs in more places, including the `Skybox RGBM` material (variant = 0x0).

**Comment by prideout** [comment]
We have confirmed that this an Adreno bug and have notified Qualcomm.  Leaving this issue open until we have a workaround.

**Comment by prideout** [comment]
This will be fixed in Android Q, in the meantime I think we should use VLACHOS dithering when Vulkan is enabled.

**Comment by romainguy** [comment]
We switched to Vlachos/interleaved gradient noise everywhere now. Triangle dithering was causing flickers with msaa.
