### ISSUE TITLE
Web PointLights not working

### ISSUE THREAD

**Issue by John-DeCorato-HZ** [google/filament#1115]
Trying to use PointLights in the web version and I'm getting a black screen. Not sure if I'm initializing the point light incorrectly or if there's another issue. The scene knows that there is a light inside of it.

Code for generating the light.
```javascript
createPointLight(lightData) {
    let Filament = window.Filament;
    let LightType = Filament.LightManager$Type;

    let light = Filament.EntityManager.get().create();
    Filament.LightManager.Builder(LightType.POINT)
        .color(lightData.color)
        .intensity(lightData.intensity)
        .falloff(10)
        .position(lightData.position)
        .build(this.engine, light);
        return light;
}
```

Point Light Data
```
{
    position = [0, 0, 20],
    intensity = 1000,
    color = [1.0, 1.0, 1.0]
}
```

Equivalent Data inside of a ThreeJS scene. ~~Ignore the energy conservation issues in the top right~~
<img width="537" alt="Screen Shot 2019-04-19 at 9 58 29 AM" src="https://user-images.githubusercontent.com/20100243/56434512-bb10e900-6289-11e9-8415-4a72cb27185a.png">

**Comment by prideout** [comment]
Shadows need to be disabled in Chrome 73.  What do you see in the Developer Console?

**Comment by John-DeCorato-HZ** [comment]
I'm not getting anything in the Developer Console. Unfortunately this code is inside of a rather large project, but I can try and repro in something smaller.

**Comment by prideout** [comment]
Thanks, I'll try modifying one of our samples to repro.  It's strange, thought, that you're seeing absolutely nothing in your console, you should at least see "FEngine (32 bits) created" after creating the Filament engine.

**Comment by John-DeCorato-HZ** [comment]
Ah apologies, I thought you meant anything related to lights.

My console output is this

```
FEngine (32 bits) created at 0x52a6b0 (threading is disabled)
```

That is the only output that isn't debug info that I'm using for my application.

**Comment by romainguy** [comment]
You should also check the intensity of the lights and or the camera exposure settings. Filament uses physical units only and the default exposure is set for a sunny day outdoors.

**Comment by John-DeCorato-HZ** [comment]
I cranked up the intensity to ludicrous amounts already and had no results. I'd imagine a point light 3 meters away from a sphere at 1000 lx should still provide some illumination, but even setting it to something wild like 100000 lx still did nothing.

**Comment by romainguy** [comment]
Point lights are expressed in lumens, not lux. A 1,000 lumens isn't that much. But yeah it doesn't sound like that's your issue.

**Comment by romainguy** [comment]
Tracking in #1119
