### ISSUE TITLE
Web: Filament.wasm import issues

### ISSUE THREAD

**Issue by John-DeCorato-HZ** [google/filament#1116]
Filament will always attempt to load the .wasm file from the root directory instead of from the same folder that filament.js is in, if you include it using an import statement. This *seems* like a bug.

Easy to repro:

```
import * as Filament from '/libs/filament.js'
```

**Comment by prideout** [comment]
Hmm, that does sound like a bug, but might be hard to fix since emscripten generates the wasm-loading code for us. We have a webpack sample in the source tree that demonstrates the usage of `import`, if that's helpful.

**Comment by John-DeCorato-HZ** [comment]
I think that ends up working because it copies over the wasm into the output directory, and it does work when including the container file in a subfolder through an html tag. I'm doing that as a workaround for now after webpacking my project.

I figured this would be a nasty to figure out. I'll also take a look. >_>

**Comment by prideout** [comment]
@John-DeCorato-HZ happy to accept a pull request but this isn't something we have the expertise for.  Closing.
