### ISSUE TITLE
Point lights behave strangely

### ISSUE THREAD

**Issue by prideout** [google/filament#1119]
This can be reproduced with macOS / OpenGL by doing:

`lightbulb -m third_party/models/shader_ball/shader_ball.obj`

![lights](https://user-images.githubusercontent.com/1288904/56449001-38a81980-62c9-11e9-9698-12ee54ecce9b.gif)

**Comment by romainguy** [comment]
Looks like froxelization is broken again ^^

**Comment by John-DeCorato-HZ** [comment]
Still having issues on web. Was it working on your end?

**Comment by prideout** [comment]
Checking...

**Comment by prideout** [comment]
@John-DeCorato-HZ I was able to get point lights to show up with a fresh WebGL build after hacking on our suzanne demo:

https://github.com/google/filament/compare/pr/test_pt_light

![Screen Shot 2019-04-22 at 11 18 47 AM](https://user-images.githubusercontent.com/1288904/56516993-b13cef00-64f0-11e9-93d7-831948765133.png)

(Clear color is always black, but that's a separate issue.)

**Comment by John-DeCorato-HZ** [comment]
Ah, I'm getting them now. I'm surprised the intensity needs to be that high. Am I misunderstanding the unit of measurement? That's a 10^7 value higher than what I'd expect the lumen input to be for that light.

**Comment by romainguy** [comment]
The default exposure is for the sun at ~noon, so 100,000 lux or so. You'll need a strong intensity in lumens to match this indeed.

**Comment by John-DeCorato-HZ** [comment]
Okay, thanks.
