### ISSUE TITLE
filament.js at unpkg.com is not up-to-date

### ISSUE THREAD

**Issue by cx20** [google/filament#1121]
**Describe the bug**
The tutorial of triangle says to use `filament.js` from `unpkg.com`.
https://google.github.io/filament/webgl/tutorial_triangle.html

```html
<script src="//unpkg.com/filament/filament.js"></script>
```
However, I think that version of `filament.js` is not the latest.
If you use that version, an error will be output to the browser console.

```
filament.js:6 
Uncaught (in promise) TypeError: Incorrect number of tuple elements for Box: expected=2, actual=undefined
    at Object.toWireType (filament.js:6)
    at RenderableManager$Builder$boundingBox [as boundingBox] (eval at new_ (filament.js:6), <anonymous>:8:26)
    at new App ((index):100)
    at Object.onReady ((index):136)
    at filament.js:6
    at filament.js:6
```

**To Reproduce**

OK : Using [filaments.js](https://github.com/google/filament/blob/master/docs/webgl/filament.js) on github
https://jsfiddle.net/cx20/o46zbxq8/
![image](https://user-images.githubusercontent.com/1833979/56458952-295bc580-63c8-11e9-9fc4-12fe9e3ab2c7.png)

NG : Using [filaments.js](https://unpkg.com/filament@1.1.0/filament.js) on unpkg.com
https://jsfiddle.net/cx20/dfwpnkxm/
![image](https://user-images.githubusercontent.com/1833979/56458955-337dc400-63c8-11e9-99ef-622c63cf28b1.png)

**Expected behavior**

It was assumed that a blue triangle would be displayed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome/73.0.3683.103
 - GPU: Intel HD Graphics 520 
 - Backend: ANGLE (WebGL)

**Comment by prideout** [comment]
Right, we need to update the npm package.  Will do.

**Comment by prideout** [comment]
Okay, we've updated the npm package.  Note that you will need to recompile all materials with the latest version of `matc` (which is why the jsfiddle is still broken)

**Comment by cx20** [comment]
I confirmed that the sample in jsfiddle is displayed by recompiling the material file with `matc`.

OK : Using [filaments.js](https://unpkg.com/filament@1.2.0/filament.js) on unpkg.com
https://jsfiddle.net/cx20/dfwpnkxm/
![image](https://user-images.githubusercontent.com/1833979/56655584-34676c00-66ce-11e9-9019-d3810a15e7c7.png)

**Comment by cx20** [comment]
Currently, the latest version of Filament is `v1.9.0`, but the [version of unpkg.com](https://www.npmjs.com/package/filament) seems to remain `v1.8.1`.

**Comment by prideout** [comment]
@cx20 I just pushed v1.9.0, apologies for the delay.
