### ISSUE TITLE
why cannot use GLSurfaceView on Android? 

### ISSUE THREAD

**Issue by xyflora** [google/filament#1136]
now i am trying to build filament to my own project. As my project is based on GLSurfaceView. 

I found that the screen turns back if i use
`private SurfaceView mSurfaceView;`
`mSurfaceView = new GLSurfaceView(this);`
 to replace initial 
`private SurfaceView mSurfaceView;`
`mSurfaceView = new SurfaceView(this);`
（it works well before the replacement）

I wonder how to let filament draw on a GLSurfaceView? or How to add the model to my own GLSurfaceView in which has set EGL Context.

**Comment by romainguy** [comment]
`GLSurfaceView` is a `SurfaceView` but it creates its own render thread and OpenGL context, which will conflict with Filament. Since Filament takes care of all the rendering you do not need a `GLSurfaceView`.

**Comment by xyflora** [comment]
got it! can i have some way to let filament drawn in my OpenGL context?

**Comment by xyflora** [comment]
> `GLSurfaceView` is a `SurfaceView` but it creates its own render thread and OpenGL context, which will conflict with Filament. Since Filament takes care of all the rendering you do not need a `GLSurfaceView`.

got it! can i have some way to let filament drawn in my OpenGL context?

**Comment by romainguy** [comment]
Unfortunately no, Filament needs to own the GL context (if only to do state tracking). You can however use external textures to have Filament or your renderer render into a texture and then use that texture in the other renderer.

**Comment by xyflora** [comment]
> Unfortunately no, Filament needs to own the GL context (if only to do state tracking). You can however use external textures to have Filament or your renderer render into a texture and then use that texture in the other renderer.

I wonder is any possible that i can transfer my context to filament when i create the engine, because i note that the author leaves a entrance for a shared context in
 `Engine::create(Backend backend, Platform* platform, void* sharedGLContext)` 
but it seems that this parameter doesn't be used during the creating process. 
I am confused with the author's intention to design such a parameter.

**Comment by romainguy** [comment]
The shared EGL context is used to share textures with an existing context. It is not meant for public use currently.

**Comment by xyflora** [comment]
> The shared EGL context is used to share textures with an existing context. It is not meant for public use currently.

I have another question. As you said before, it's possible to have Filament render into a texture and then use that texture in the other renderer. So can I understand it like that... Supposing I constructed a scene where filament could do render job, then It could return an output texture that could be used in my own renderer
