### ISSUE TITLE
GPU Blend Shape Using VertexAttribute

### ISSUE THREAD

**Issue by lyLoveSharon** [google/filament#1149]
Can I use an extra VertexAttribute?
I want to implement gpu blend shape using VertexAttribute
Similar to WebGLMorphtargets in three.js

**Comment by prideout** [comment]
This is not yet implemented but we do have plans to extend Filament to support support morphing  similar to how we already support skinning.  We plan on supporting up to 4 sets of positions + 4 sets of tangents.

**Comment by romainguy** [comment]
Custom vertex attributes is also something we'd like to add at some point.

**Comment by kylelin47** [comment]
Do you have any suggestions for implementing morph targets using Filament with its current feature set? Or is it just not feasible

**Comment by prideout** [comment]
We're going to start implementing this feature very soon.
