### ISSUE TITLE
Bloom, SSR and Temporal Anti-Aliasing

### ISSUE THREAD

**Issue by nxrighthere** [google/filament#1164]
I see that these effects are planned, but would like to keep tracking this via an issue if you don't mind. Since work on the SSAO is ongoing, maybe you will keep the post-processing train on rails. 😺

**Comment by romainguy** [comment]
Bloom is definitely planned, TAA might not be a priority for a while.

**Comment by Steve132** [comment]
One thing I'd like to see in a bloom engine is the ability to use/customize/shade the point-spread function.      There are various ways of doing this and they can degrade/be not available on mobile.

**Comment by romainguy** [comment]
Bloom is now implemented, as is screen-space refraction (not reflection). For anti-aliasing we will stick with FXAA and MSAA for the time being, TAA imposes requirements we're not ready to take on ourselves nor ready to impose on users. I'll close this request for now.

**Comment by romainguy** [comment]
TAA is now available (although not complete, we don't use motion vectors yet).
