### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by whatisor** [google/filament#1166]
**Describe the bug**
Code review: 
I found that runStaticCodeAnalysis not only "Analysis", but also find properties and generate shader code.
This creates a bit confusing. Should we change function name or separate functions?
Thank you.

**Comment by romainguy** [comment]
Finding the properties is part of the static analysis and it doesn't generate the final code but uses "peek" to produce a version of the code that can be analyzed.

**Comment by whatisor** [comment]
Thank @romainguy , it seems it updates mProperties which decides content of shader code?
I think extracting property should be separated, how do you think?

**Comment by romainguy** [comment]
That's part of the static analysis so we know what properties the material writes to. filamat's code could use a *****lot***** of cleanup, and this is far from being one of the important ones. Not to say this particular function can't be improved but I think there are much higher priorities (the rest of Materialbuilder for instance).
