### ISSUE TITLE
gltf geometry reflected on x-axis

### ISSUE THREAD

**Issue by LeoAtreides** [google/filament#1195]
1) Description 

In Augmented Face runtime, meshes are reflected in x-axis.

2) Step to reproduce
 
1.  Import glft file in Android Studio
2.  Inspect object in Viewer
3.  Load in app and observe
4.  Note that the object is reflected in x-axis

3) Expected behavior

Geometry should not be reflected on x-axis. 

This behaviour does not occur in Arkit with XCode viewer and runtime.

4) Screenshots

![correct-reflection](https://user-images.githubusercontent.com/3842697/57929331-ec8dcc00-78aa-11e9-9ade-2118a541b299.png)

![incorrect_reflection](https://user-images.githubusercontent.com/3842697/57929305-da139280-78aa-11e9-843d-9f377f09b354.jpg)

5 ) Tested Platform is Android

6) Test device is Samsung S8

**Comment by LeoAtreides** [comment]
source file for debugging 

[gltf.zip](https://github.com/google/filament/files/3191565/gltf.zip)

**Comment by romainguy** [comment]
Thank you for reporting this issue but this GitHub project is just the renderer used by Sceneform. For glTF loading issues or Augmented Face runtime issues, please use https://github.com/google-ar/sceneform-android-sdk/issues instead.

**Comment by LeoAtreides** [comment]
I'll re-post there. The .sfa file makes that precise separation of the api's somewhat obscure.

**Comment by romainguy** [comment]
.sfa files are also specific to Sceneform but I agree. Only custom materials are a Filament API directly exposed in Sceneform.
