### ISSUE TITLE
[filament][v1.2.0]can't open to the app.

### ISSUE THREAD

**Issue by 44asad** [google/filament#1199]
### Actual Behaviour

App fail to install in my device.
### Expected Behaviour

I expected that i can install and use the app successfully.
### Step to reproduce
* Download the app 
* click the app to install
* see the error
### Information
* App version:v1.2.0
* Os:Android 6.0.1
* Device:Samsung j5
### Recording of the bug
https://youtu.be/0SFzdVqf6xg

**Comment by romainguy** [comment]
Thanks for the report  This is not an app but a library for developers. What you downloaded isn't meant to and cannot be opened on a phone
