### ISSUE TITLE
setColorParameter with an 4-element array seems not work

### ISSUE THREAD

**Issue by comma-deng** [google/filament#1202]
**Describe the bug**

My mat file:
```
material {
    name : "simple material",
    parameters : [
        { type : float4, name : baseColor }
    ],
    shadingModel : unlit,
    doubleSided : true
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = materialParams.baseColor;
    }
}
```

When I try to pass a 4-element array to the baseColor parameter in my js:
```
const simple_mat = engine.createMaterial('res/simple.filamat');
const simple_mat_inst = simple_mat.getDefaultInstance();
// pass a 4-element array
simple_mat_inst.setColorParameter('baseColor', Filament.RgbaType.LINEAR, [0.3, 0, 0, 0.1]);
```
my browser report an error:
`TypeError: Incorrect number of tuple elements for float3: expected=3, actual=4`

but if I change the 4-element array into a 3-element array,it works:
```
const simple_mat = engine.createMaterial('res/simple.filamat');
const simple_mat_inst = simple_mat.getDefaultInstance();
// pass a 3-element array
simple_mat_inst.setColorParameter('baseColor', Filament.RgbaType.LINEAR, [0.3, 0, 0]);
```

I think with Filament.RgbaType,the function should accept a 4-element array : [r,g,b,a] ,but in fact it only accept 3 elements. 
So how can I pass  4 elements to the baseColor parameter?Is it a bug?

**Comment by romainguy** [comment]
This looks like a bug in the JS bindings. Thanks for the report.
