### ISSUE TITLE
Dynamic textures or dynamic vertices

### ISSUE THREAD

**Issue by CgGraphic** [google/filament#1203]
Hi, I'm currently writing an ar application using java and c++ on Android following the IBL demo.

I want to show the camera image and point clouds provided by other algorithms.

So my framework is

```mChoreographer.postFrameCallback(this);
        if (mUiHelper.isReadyToRender()) {
                if (mRenderer.beginFrame(mSwapChain)) {
                    // the actual image and point cloud update in c++
                     DrawFrame();
                    //mEngine.flushAndWait();
                    mRenderer.render(mView);
                    mRenderer.endFrame();
                }
            }
```

```
// For each frame
// get the YUV buffer and point cloud buffer (In c++ code)
// update image with filament's Texture->setImage(...)
// Update pointcloud with filaments VertexBuffer->setBufferAt
DrawFrame()
{
     char * y = getYImage() // get the Y data
    char * uv = getUVImage() // get the uv Data
    float * point_cloud = GePointCloudData() // get point cloud data

     Texture::PixelBufferDescriptor  buf_y(y, mSize,
                    Texture::Format::R, Texture::Type::UBYTE);
     fCameraTexY->setImage(*mFilaEngine, 0, std::move(buf_y));
     Texture::PixelBufferDescriptor buf_uv(uv, mSize / 2,
                    Texture::Format::RG, Texture::Type::UBYTE);
      fCameraTexUV->setImage(*mFilaEngine, 0, std::move(buf_uv));

      // set pointcloud
       mVertexBuffer->setBufferAt(
			mEngine, 0, filament::VertexBuffer::BufferDescriptor(point_cloud , mSize* sizeof(filament::math::float4)));
```

 
But the problem is that:

1. if I don't add the mEngine.flushAndWait(), the rendered camera background feels like tearing frequently.

2. the mEngine.FlushAndWait().  fix the tearing but the performance decreases a lot.

**So, how to fix this problem?**

I looked  into the source code:

```
void FTexture::setImage(FEngine& engine, size_t level,
        Texture::PixelBufferDescriptor&& buffer, const FaceOffsets& faceOffsets)
```

It seems that the Filament defers the actual GL API invocation into the render thread. But since I don't see data copy here,  the buffer can be changed multiple times in worker threads? is this correct?

Is there any synchronous mechanism there that it signals the worker thread a buffer is submitted to GPU?

**Comment by romainguy** [comment]
You can do two things:
- the PixelBufferDescriptor can take a callback to be notified when the texture upload is complete
- you can create hard fences and wait on them or query them to know when a command is done executing on the GPU

The first solution is probably the easiest in your case and it won't require blocking the main thread. You could copy the point cloud data and use the descriptor callback to free the copy.

BufferDescriptors for vertices also let you specify a callback.

Btw I would recommend putting all that code outside of beginFrame(). begin/endFrame should only contain render submissions.

**Comment by CgGraphic** [comment]
Thanks, I have tried both ways and put the *DrawFrame* code outside. 

It solves the tearing effect. But the performance is *Very slow*.  

without the hard fence, the *DrawFrame* can have about 43 FPS .  

But the rendered camera sequence is still very slow.  The mRenderer.render(mView) seems only rendered **10-15** FPS. 

I suspect that the CPU is outpacing the Filament render thread, so a lot frame is canceled by
*if(mRenderer.beginFrame(mSwapChain))*

**Is that right?**

But the whole work is updating the YUV video stream to texture and draw a full-screen quad with Yuv->RGB shader. 

I profiler the APP with both the android profiler and gapid. It seems that the hotspot function in FEngine::Loop is  **glTexSubImage2D**
![android_studio](https://user-images.githubusercontent.com/8565304/58154013-2bed5b80-7ca3-11e9-9d02-080c59596a35.png)

But I have a former raw OpenGL es implementation and it works very well. 

The only difference seems that we use GL_Luminance and GL_LUMINACEN_ALPAHA for Y and UV texture in raw opengl es, and we use GL_R_SNORM and GL_RG in filament texture.

So any thoughts of what's going wrong? 
or any tools or filament configuration that I can dive deep into this problem (I see systrace, but failed to open it )?

**Comment by romainguy** [comment]
Wouldn't `GL_R_UNORM` be closer to what `GL_LUMINANCE` do? I wonder if the driver performs additional conversions that are unnecessary.

Where is your YUV data coming from? Is there any chance you could be using an external texture instead?

**Comment by pixelflinger** [comment]
mh... The fastest way would be to use the callback (not the fences, because they'll block your thread) -- can you explain how you're using the callback? All you should be doing in the callback is free your buffer.

If your getYImage()/getUVImage() API is not able to output individual buffers, you'll have to make a copy yourself in a new buffer and free that buffer in the callback. Does that make sense?

Ideally, your getYImage() would use buffers in a pool (e.g. 3 or 4), they would fill the buffer, return it to you, you would pass this buffer to filament and "free" (i.e. return to the pool) in the callback. This way you avoid extra copies.

Have you been able to measure how much time each glTexSubImage2D takes? And what's the size of the data you're passing to it? (I just want to see if the time sounds reasonable, ballpark).

**Comment by CgGraphic** [comment]
> Wouldn't `GL_R_UNORM` be closer to what `GL_LUMINANCE` do? I wonder if the driver performs additional conversions that are unnecessary.
> 
> Where is your YUV data coming from? Is there any chance you could be using an external texture instead?

will try different GL types soon.

YUV data are from camera preview.   I also looked into the Scenefrom source code, External texture seems a neat solution, but not applicable in some cases, so will try normal texture first.

**Comment by CgGraphic** [comment]
> mh... The fastest way would be to use the callback (not the fences, because they'll block your thread) -- can you explain how you're using the callback? All you should be doing in the callback is free your buffer.
> 
> If your getYImage()/getUVImage() API is not able to output individual buffers, you'll have to make a copy yourself in a new buffer and free that buffer in the callback. Does that make sense?
> 
> Ideally, your getYImage() would use buffers in a pool (e.g. 3 or 4), they would fill the buffer, return it to you, you would pass this buffer to filament and "free" (i.e. return to the pool) in the callback. This way you avoid extra copies.
> 
> Have you been able to measure how much time each glTexSubImage2D takes? And what's the size of the data you're passing to it? (I just want to see if the time sounds reasonable, ballpark).

For each frame in the **DrawFrame** code, I new temporary buffers and copy the YUV data. and register a free function at the callback (since the DrawFrame is relatively quick, the extra new operation seems fine as a test code).

To diagnose, I use a unordered_set<void *> to record the data allocation and free.
```
std::unordered_set<void *> Ys;

void release_data(void * data)
{
      Ys.erase(data);
      free(data);
}

void DrawFrame()
{
      void * Y = GetYImage()  // The camera preview size is 1280*720
      Ys.insert(Y);
      // set pixbufferdescriptor and bind the release_data function
}
```
Since the CPU is faster than GPU, the size of the unordered_set  is increasing. from 1 to 20s.

I also tried to add latent fences for each memory allocation. That is, create hard fence when **setImage*,*, only WaitAndDestroy after 3-4 frames. This method may control the size of the unordered_set, but the render thread is also slow.

The camera preview size is 1280*720 *(1(Y) + 0.5(uv)) bytes and the display is 1080*2340. and I haven't been able to measure the actual performance of glTexSubImage2D.  

But if I didn't setImage every frame, the filament runs reasonably fast, that is, 60/30 Fps fro mRender.render(view)

One thing may impact the render performance is that in my previous opengl es implementation, i do YUV ->RGB in 1280*720 RGBA framebuffer.   

In the gapid i see that filament renders to full display(1080*2340) R16F framebuffer, also some post-processings are added.  

But again, I don't think this will be a major issue.

Will focus on why glTexSubImage2D takes so much time.

**Comment by romainguy** [comment]
You can control the rendering resolution by setting a fixed size on the `SurfaceView` or `TextureView` you use for rendering and/or by enabling dynamic resolution on your Filament `View` object.

Waiting on the hard fences will block your thread until the GPU is done processing all the work submitted prior to that fence. Make sure this is not the problem.

**Comment by CgGraphic** [comment]
RG8_SNORM is the cause.

Using RG8_SNORM, the glTexSubImage2D is very slow in my device (XiaoMI mix 3).

Change it to RG8 fix the performance issue.

**Comment by romainguy** [comment]
Good to know, thank you! SNORM probably forces the driver to go through all the elements to normalize them.
