### ISSUE TITLE
Metal backend on iOS seems to be crashing with ubershader material provider

### ISSUE THREAD

**Issue by stomanovski** [google/filament#1209]
I am following the sample code related to loading GLTF models directly on my iOS device. From what I have found so far the only way to do this on mobile is to use createUbershaderLoader and pass the result to the AssetLoader. The other option - createMaterialGenerator seems to be available only on the desktop targets. 

Using the ubershader with OpenGL backend works fine, but when I switch to Metal I get a flavor of this assert and then a crash:

validateFunctionArguments:3531: failed assertion `Fragment Function(main0): missing sampler binding at index 6 for materialParams_baseColorMapSmplr[0].'

The problem seems to be unrelated to specific gltf file. I tried with several - I got the same assert.

The Metal backend works fine with .filamesh and .filamat files but In this case I am not using  the ubershader and the asset loader.

So my question is: is this a known bug with the uberhader and Metal and is there any workaround which doesn't involve falling back to using .filamesh and .filamat data?

 - Device: iPhone XR
 - OS: iOS 12.1
 - Backend: Metal

[cubo.zip](https://github.com/google/filament/files/3200498/cubo.zip)

**Comment by bejado** [comment]
Thanks for the report. @prideout can correct me on this, but`createMaterialGenerator` should work on mobile too. To use it, you'll also need to link against the [`filamat` library](https://github.com/google/filament/tree/master/libs/filamat) . Nonetheless, `createUbershaderLoader` should work with Metal. I'll take a closer look.

**Comment by bejado** [comment]
Ah, I now see that we only build [`gltfio_core`](https://github.com/google/filament/blob/master/libs/gltfio/CMakeLists.txt#L120) on mobile, so we are in fact limited to `createUbershaderLoader`.

**Comment by bejado** [comment]
@stomanovski This should be fixed now, please pull and rebuild. Let us know if you have any other issues.

**Comment by stomanovski** [comment]
Thank you @bejado! Loading GLTF assets with Metal works. One of my test cases is setting:

**Comment by stomanovski** [comment]
With the latest code GLTF assets work on Metal now - thank you @bejado ! 

I think there is still metal specific issue though. When I call view->setPostProcessingEnabled(false) my app crashes with this assert:

validateDepthStencilState:3794: failed assertion `MTLDepthStencilDescriptor sets depth test but MTLRenderPassDescriptor has a nil depthAttachment texture'

The OpenGL backend correctly renders in both cases. With the default value (true) Metal works fine as well.

Kudos to the filament team for being so quick on fixing issues!

**Comment by stomanovski** [comment]
@romainguy Let me know if you want me to file a separate bug for this.

**Comment by bejado** [comment]
@stomanovski Thanks, I've opened up a separate issue for that: #1215

**Comment by bejado** [comment]
@stomanovski As a temporary workaround, you can leave post processing enabled but disable all passes:

```
view->setAntiAliasing(View::AntiAliasing::NONE);
view->setToneMapping(View::ToneMapping::LINEAR);
view->setDithering(View::Dithering::NONE);
view->setAmbientOcclusion(View::AmbientOcclusions::NONE);
```

**Comment by stomanovski** [comment]
Thank you @bejado! This looks like good workaround for my case.
