### ISSUE TITLE
Metal crash when post processing is disabled

### ISSUE THREAD

**Issue by bejado** [google/filament#1215]
When post processing is disabled, Metal crashes on iOS with the following:

```
validateDepthStencilState:3794: failed assertion `MTLDepthStencilDescriptor sets depth test but MTLRenderPassDescriptor has a nil depthAttachment texture'
```

Note that this only happens when running from Xcode with Metal API validation.

Reproduce on desktop by adding

```
view->setPostProcessingEnabled(false);
```

To material_sandbox (it's not enough to simply uncheck the PP passes through imgui, PP has to be explicitly disabled). Both Metal and OpenGL backends only render the skybox. It looks like this bug has existed for some time.

Workaround:
Enable post processing (`setPostProcessingEnabled(true)`, which is the default), but disable all passes:
```
view->setAntiAliasing(View::AntiAliasing::NONE);
view->setToneMapping(View::ToneMapping::LINEAR);
view->setDithering(View::Dithering::NONE);
view->setAmbientOcclusion(View::AmbientOcclusions::NONE);
```

**Comment by romainguy** [comment]
Is this issue still relevant?

**Comment by bejado** [comment]
It still reproduces, yes. This is really a bug at a higher level than Metal / iOS, it just happens to crash when running in Xcode. The root issue is that the default framebuffer does not have a depth buffer, and so does not render the scene correctly.

**Comment by romainguy** [comment]
We now always have a depth buffer by default.
