### ISSUE TITLE
Backend sees bindSamplers called with SSAO texture, even after texture is destroyed

### ISSUE THREAD

**Issue by bejado** [google/filament#1223]
Filament is destroying a texture, then attempting to bind a sampler group that references it. This should be an invalid use of the Driver API.

For example:

```
createTexture( 100 )
bindSamplers( /* a sampler referencing texture 100 */ )
draw
...
destroyTexture( 100 )      <-- done automatically by the frame graph
bindSamplers( /* a sampler referencing texture 100 */ )
draw         <-- error in the Metal backend, as texture 100 has been deleted
```

This happens with the SSAO texture. In the color pass inside `Renderer.cpp`, `view.prepareSSAO(ssao)` binds the SSAO texture to the per view sampler group, but never unbinds it. During the next render pass, Filament will attempt to upload the sampler group (which still has the deleted texture handle) to the driver.

#1222 is a workaround that explicitly unbinds the SSAO texture.

This happens because the SSAO texture is managed by the frame graph which destroys it once the pass finishes. Somehow, either automatically or through a new frame graph API, we need a way to unbind textures from any sampler groups that reference them at the end of a pass.

@pixelflinger

**Comment by romainguy** [comment]
Is this still valid?
