### ISSUE TITLE
Potential memory leaks 

### ISSUE THREAD

**Issue by farziengineer** [google/filament#1237]
https://github.com/google/filament/blob/fc0d587b40d12af30f0091c9d10f254caf9d0e4d/third_party/libassimp/code/MDLMaterialLoader.cpp#L79

https://github.com/google/filament/blob/fc0d587b40d12af30f0091c9d10f254caf9d0e4d/third_party/libassimp/code/MDLMaterialLoader.cpp#L143

https://github.com/google/filament/blob/fc0d587b40d12af30f0091c9d10f254caf9d0e4d/third_party/libassimp/code/MDLMaterialLoader.cpp#L818

Memory allocated on heap using new but not deleted. Can we add a 
```python
delete var_name
```
at the end of function

**Comment by romainguy** [comment]
These objects are added to arrays and/or kept around, they shouldn't be deleted.
