### ISSUE TITLE
Displacement support

### ISSUE THREAD

**Issue by nitronoid** [google/filament#1251]
I couldn't find this referenced by any other issues, or in the material documentation so I thought I'd ask. 

Is there any (planned) support for geometry displacement using a height map? I have experimented with tessellation and geometry shaders to actually deform the geometry, rather than using a normal map to fake it, and wondered if this method is supported by filament?

This video shows a good demo of what I mean: https://www.youtube.com/watch?v=GeQiYxbkWrw

**Comment by romainguy** [comment]
We don't support tessellation and geometry shaders but you can write a custom vertex shader to do displacement if your source mesh is already sufficiently tessellated. If you look in samples/sample_full_pbr.cpp you can also find an example of parallax occlusion mapping.

**Comment by nitronoid** [comment]
Is the reason they're unsupported due to lack of support on some of your target platforms? Thanks for the POM sample I'll have a look!

**Comment by romainguy** [comment]
It's just extra work and it hasn't been a priority, especially on mobile targets.

**Comment by prideout** [comment]
Note that Filament **does** allow you customize your vertex shader, so if your geometry is tessellated sufficiently then you can make texture lookups in there and displace the verts appropriately.  Care should be taken to adjust the lighting normal appropriately.

Personally I think we should close this issue since tessellation / geometry shaders out of scope for Filament in the foreseeable future.

**Comment by romainguy** [comment]
Closing this for now. We may revisit in the future but tessellation is not on our roadmap for the time being.

**Comment by dandingol03** [comment]
parallax mapping is not equal to displacement. Displace mapping will change the vertex position.
` parallax mapping `:
![image](https://user-images.githubusercontent.com/13013579/174703526-25857e29-b394-4300-bdeb-8a7326687974.png)
`displace mapping`:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/13013579/174704381-88f3c6ed-11b4-4663-916e-12ebba814fbe.png">
