### ISSUE TITLE
loadClassExtensions does not seem to work when importing WASM Filament dynamically 

### ISSUE THREAD

**Issue by griffin2000** [google/filament#1257]
loadClassExtensions doesn not seem to work when importing the Filament WASM module dynamically (using Babel).

So this static import works fine:
```
import { 
  init,
  Engine,
} from './filament/filament';
init([], ()=>{
          
    const engine=Engine.create(canvas);
    console.log(engine);
});

```

But when importing dynamically, although the WASM module loads, and init is called, none of the types (e.g. Engine) exist in the module.  So I assume loadClassExtensions hasn't been called successfully? This code will fail as filamentModule.Engine is undefined:
```
    const filamentModuleProm = import( './filament/filament');
      filamentModuleProm.then( (filamentModule)=>{
        filamentModule.init([], ()=>{
          
          const engine=filamentModule.Engine.create(canvas);
          console.log(engine);
       });
    });

```

**Comment by prideout** [comment]
Not familiar with Babel but I just now successfully tried out dynamic import by replacing `web/samples/webpack/src/app.ts` with:

```js
const promise = import('filament');

promise.then(function(MyModule) {
    MyModule.init([], () => {
        console.info('hi', MyModule.Engine);
    });
  });
```

I also added `"lib": ["es2015", "dom"],` to `tsconfig.json`.  After reloading the page, the console output looks good.

**Comment by prideout** [comment]
Given that I was able to use dynamic imports in the aforementioned experiment, I don't think this is a Filament bug, closing.
