### ISSUE TITLE
Filamesh always using 16 bit index buffer

### ISSUE THREAD

**Issue by koenigvonamburu** [google/filament#1272]
**Describe the bug**
The filamesh MeshWriter seems to use a 16 bit index buffer even if there are more than 2^16 vertices.

This is probably related to the following check in [MeshWriter.cpp](https://github.com/google/filament/blob/f93046308c7a6b18302e6c3d671464741adfa36a/tools/filamesh/src/MeshWriter.cpp#L93)
```c++
bool MeshWriter::serialize(ostream& out, Mesh& mesh) {
    const uint32_t maxint = numeric_limits<uint32_t>::max();
    const bool hasIndex16 = mesh.vertexCount < maxint;
    [...]
}
```
Shouldn´t this check for `mesh.vertexCount < numeric_limits<uint16_t>::max()` ?

**To Reproduce**
1. Write a mesh with more than 2^16 vertices

**Expected behavior**
32 bit indices should be used if required.

**Comment by romainguy** [comment]
Thanks! Looks like the bug was introduced when `filamesh` was split in `libfilameshio` and `filamesh`. Uploading a fix soon.
