### ISSUE TITLE
Floating point normal map produces incorrect results

### ISSUE THREAD

**Issue by nitronoid** [google/filament#1276]
**Describe the bug**
When using a float array as a normal map, the result displays obvious artifacts.

**To Reproduce**
I'm using this to load my normal map:
```cpp
  int width, height, nchannels;
  auto raw_image =
    stbi_loadf("assets/tex/normal.png", &width, &height, &nchannels, 0);

  auto normal = filament::Texture::Builder()
      .width(width)
      .height(height)
      .levels(0xff)
      .format(filament::Texture::InternalFormat::RGBA32F)
      .build(*engine);

  filament::Texture::PixelBufferDescriptor buffer(
    raw_image,
    width*height*4,
    filament::Texture::Format::RGBA,
    filament::Texture::Type::FLOAT,
    (filament::Texture::PixelBufferDescriptor::Callback)&stbi_image_free);

  normal->setImage(*engine, 0, std::move(buffer));
  normal->generateMipmaps(*engine);
  filament::TextureSampler sampler(
    filament::TextureSampler::MinFilter::LINEAR_MIPMAP_LINEAR,
    filament::TextureSampler::MagFilter::LINEAR);
  material_instance->setParameter("normal", normal, sampler);
```

**Expected behavior**
Should produce the same output as loading an unsigned byte array:
```cpp
  int width, height, nchannels;
  auto raw_image =
    stbi_load("assets/tex/normal.png", &width, &height, &nchannels, 0);

  auto normal = filament::Texture::Builder()
      .width(width)
      .height(height)
      .levels(0xff)
      .format(filament::Texture::InternalFormat::RGBA8)
      .build(*engine);

  filament::Texture::PixelBufferDescriptor buffer(
    raw_image,
    width*height*4,
    filament::Texture::Format::RGBA,
    filament::Texture::Type::UBYTE,
    (filament::Texture::PixelBufferDescriptor::Callback)&stbi_image_free);

  normal->setImage(*engine, 0, std::move(buffer));
  normal->generateMipmaps(*engine);
  filament::TextureSampler sampler(
    filament::TextureSampler::MinFilter::LINEAR_MIPMAP_LINEAR,
    filament::TextureSampler::MagFilter::LINEAR);
  m_impl->material_instance->setParameter("normal", normal, sampler);
```

**Screenshots**
This is what I get using a byte array.
![working](https://user-images.githubusercontent.com/22621071/59217825-b9dba880-8bb6-11e9-8a2f-1bff3f939e0d.png)

This is what I get with a float array.
![not_working1](https://user-images.githubusercontent.com/22621071/59217811-b1836d80-8bb6-11e9-9bbd-2a55638f52d8.png)
![not_working2](https://user-images.githubusercontent.com/22621071/59217818-b6482180-8bb6-11e9-838f-f6cda11b1747.png)

**Desktop (please complete the following information):**
 - OS: RHEL-7
 - GPU: Quadro M4000
 - Backend: OpenGL

I'm aware I can just use the byte array, but my final intent is to use a float array which is already in memory, and I would prefer if I didn't have to convert that array to unsigned bytes.

P.s. The normal map I'm using is the one provided for the Suzanne mesh in the samples.

**Comment by romainguy** [comment]
Thanks for the report. STB's `stbi_loadf` applies a gamma conversion on the data, which is *not* what you want in this case. If the source is an 8 bit PNG file there is no benefit in using a float texture here.

**Comment by prideout** [comment]
What Romain said, but also your PixelBifferDescriptor is 4x too small.

**Comment by nitronoid** [comment]
Thank you for your responses, undoing the gamma correction, and increasing the pixel buffer size fixed things! :) @prideout Just so I'm sure, I had to increase the size by four as it is the sizeof a float?

**Comment by prideout** [comment]
Correct.  (btw maybe STB lets you set gamma to 1.0)

**Comment by nitronoid** [comment]
Maybe, however this was just a test. My real use case will only involve arrays of floats calculated at run-time and already in memory, so I won't have to use stb at all. Thanks for your help!
