### ISSUE TITLE
Ubsan failure: Division by zero ShadowMap/Camera::inverseProjection

### ISSUE THREAD

**Issue by jwmcglynn** [google/filament#1281]
**Describe the bug**
When running ubsan, there is a divide-by-zero related to ShadowMap projection matrix calculation.

Stack:
```
runtime error: division by zero
filament::math::details::TMat44<float> filament::details::inverseProjection<float>(filament::math::details::TMat44<float> const&) 
filament::Camera::inverseProjection(filament::math::details::TMat44<float> const&)
filament::details::FView::prepareCamera(filament::details::CameraInfo const&, filament::Viewport const&)
filament::details::ShadowMap::render(filament::backend::CommandStream&, filament::details::RenderPass&, filament::details::FView&)
```

This is the projection matrix (transposed during print), which is triggering the ubsan failure in Camera.cpp's inverseProjection, on `const T B = 1 / p[1][1]`
```
m[0] = < 28.498219, -28.498219, 0.000000, 0.000000 >
m[1] = < 0.000000, 0.000000, -31.798628, 0.000000 >
m[2] = < -28.498219, -28.498219, 0.000000, 0.000000 >
m[3] = < -0.000000, -2.849822, -0.877637, 1.000000 >
```

This matrix is computed by ShadowMap::computeShadowCameraDirectional, which constructs the model matrix with mat4::lookAt:

```
// lightPosition = < 0.000000, 0.000000, 0.000000 >
// dir = < 0.000000, -1.000000, 0.000000 >
const mat4f M = mat4f::lookAt(lightPosition, lightPosition + dir, float3{ 0, 1, 0 });

// M = 
// < -1.000000, 0.000000, 0.000000, 0.000000 >
// < 0.000000, 0.000000, 1.000000, 0.000000 >
// < -0.000000, 1.000000, -0.000000, 0.000000 >
// < 0.000000, 0.000000, 0.000000, 1.000000 >
```

This rotation is propagated through the calculations, Mv -> LMpMv -> WLMpMv -> S, and then set as a custom projection on the camera.  In ShadowMap::render, FView::prepareCamera computes the inverse, which then fails ubsan.

**To Reproduce**

I unfortunately don't have an isolated repro, let me know if it's required.  I can also share an google-internal repro command privately.

**Comment by pixelflinger** [comment]
wow. cool. thanks for finding/filing this.

**Comment by pixelflinger** [comment]
@jwmcglynn  this is when running which test?

**Comment by jwmcglynn** [comment]
@pixelflinger This is for a Sceneform test
