### ISSUE TITLE
Unexpected behaviors on Samsung Galaxy S5

### ISSUE THREAD

**Issue by 61315** [google/filament#1284]
**Describe the bug**
`image-based-lighting` android sample is giving blank screen on Samsung Galaxy S5.
No specific error message was presented on logcat.

**To Reproduce**
1. Clone the master branch `c886d5b` and run build command
```
$ git clone https://github.com/google/filament
$ ./build.sh -p desktop -i release
$ ./build.sh -p android release
```
2. Open the image-based-lighting android sample project and run on device

**Expected behavior**
Application should create image-based lights and load complex meshes.

**Screenshots**
![black](https://user-images.githubusercontent.com/46559594/59273761-eb767180-8c93-11e9-9380-5057ce8f9e4b.png)

This is the one that goes without `scene.skybox`
![something](https://user-images.githubusercontent.com/46559594/59273767-ed403500-8c93-11e9-845b-09cac31aed3b.png)

**Desktop:**
 - OS: macOS Mojave 10.14.4
 - GPU: Intel HD Graphics 4000

**Smartphone:**
 - Device: Samsung Galaxy S5
 - OS: Android Marshmallow 6.0.1
 - GL ES Info
===== GL Information =====
vendor    : Qualcomm
version   : OpenGL ES 3.0 V@140.0 AU@  (GIT@Ia10634f51b)
renderer  : **Adreno (TM) 330**
===== System Information =====
mfgr      : samsung
brand     : samsung
model     : SM-G900I
release   : 6.0.1
build     : MMB29M.G900IZTS1CQD1

**Additional context**
Same project works fine on Samsung Galaxy S7 Edge which uses **Mali-T880** GPU.

Once I comment out the line 137 `scene.skybox = ibl.skybox` in android/samples/image-based-lighting/app/src/main/java/com/google/android/filament/ibl/MainActivity.kt, the mesh shader_ball is presented fine with red clear coat material.

I guess it's another GPU specific problem then? #780 Any work around on this would be much appreciated. I already implemented most of the filament engine on my android application but given this issue I might have to go back to another 3d rendering engine. I assume filament team doesn't have legacy devices on their hands which makes it harder for you guys to track down the issue. https://github.com/google/filament/issues/780#issuecomment-463593892 I'm also afraid filament team will be able to get an answer from GPU vendor in a short time. https://github.com/google/filament/issues/1096#issuecomment-486732083  If so, would you please keep a **list of unsupported devices** for developers? Unless Sceneform(which also utilize filament) team lower their minimum API to 23 or below, filament is my last shot for 'doable' mobile PBR 3d engine. Thanks for the amazing job, many thanks to you guys :)

**Comment by romainguy** [comment]
It looks like a driver issue on Adreno 330 (quite an old GPU at that point and it's not the first time we have issues with the 3xx series). One of the issues is that we're unlikely to get support from Qualcomm about older GPUs.

Knowing that the skybox is part of the problem is helpful. And also surprising because it's one of the simplest things we render (it's just a full screen triangle with an unlit shader). Are you able to compile FIlament yourself by any chance? There are a couple of things we could try as workarounds.

**Comment by 61315** [comment]
Test above was done with filament-20190426-android.aar actually, sorry for confusion, but yes the sample image-based-lighting renders shader_ball fine with setClearColor applied background when I comment out the skybox setting.
![Screenshot_2019-06-13-22-03-18](https://user-images.githubusercontent.com/46559594/59437339-607caf00-8e2c-11e9-8f7f-5a0d42c6dcfa.png)


I clean built the current master branch (8cb3834) today and none of the android example was working properly on Galaxy S5 only giving black screen even the hello-triangle example project. Every sample project works fine on Galaxy S7 Edge tho.

Tried some tinkering on image-based-lighting project with various options toggling on/off-options and whatnot, there was no progress it was just a complete black screen navigation bar presenting only. I also tried the hello-triangle project setting it's clear color to green but it was just black screen again. I tried the aar artifact from https://filament-build.storage.googleapis.com/badges/build_link_android.html and it made no difference.

Thing I noticed was this error message saying something about shader compilation failure
([android-gs5-filament-1.txt](https://github.com/google/filament/files/3286302/android-gs5-filament-1.txt)) but I'm not sure if it's related.
 
Yes, I can build Filament using build command `$ ./build.sh -p desktop -i release` on my mac if this is what you mean. If not, you can give me specific instructions to apply the workaround. Thank you.

**Comment by romainguy** [comment]
The failing shader is the new SSAO pass that's not enabled in the Android demos.

Here's what you could try:
– In the file `skyboxRGBM.mat` (in `filament/src/materials`), try to remove the big `if` block to see if it fixes the issue
– Otherwise, in `Engine.cpp`, find `sFullScreenTriangleVertices` and set all the Z values to `0.9999_h` instead of `1.0_h`

Complete shots in the dark but given how we draw the skybox I can't think of many other places where it could fail.

**Comment by 61315** [comment]
**skyboxRGBM.mat**
```
//if (materialParams.showSun && frameUniforms.sun.w >= 0.0f) {
//            vec3 direction = normalize(variable_eyeDirection.xyz);
//            vec3 sun = frameUniforms.lightColorIntensity.rgb * frameUniforms.lightColorIntensity.a;
//            float cosAngle = dot(direction, frameUniforms.lightDirection);
//            float x = (cosAngle - frameUniforms.sun.x) * frameUniforms.sun.z;
//            float gradient = pow(1.0 - saturate(x), frameUniforms.sun.w);
//            sky += sun * gradient;
//}
```

**Engine.cpp**
```
static const half4 sFullScreenTriangleVertices[3] = {
        { -1.0_h, -1.0_h, 0.9999_h, 1.0_h },
        {  3.0_h, -1.0_h, 0.9999_h, 1.0_h },
        { -1.0_h,  3.0_h, 0.9999_h, 1.0_h }
};
```



![filament_SMG900I_workarounds_result01](https://user-images.githubusercontent.com/46559594/59502808-afcce900-8ed9-11e9-9d83-edd4662e14b5.png)

It's from sceneform-1.9pr2 release source only, latest build (8cb3834) is giving black screen no matter what.

**Comment by pixelflinger** [comment]
@61315, would you be able to capture a trace with gapid and post it here?
Only a couple frames are needed.
https://github.com/google/gapid/releases

**Comment by romainguy** [comment]
Have you tried compiling in debug mode btw? It enables a bunch of checks and disable shaders optimizations which could be the cause.

**Comment by 61315** [comment]
- Device: samsung SM-G900I - Android 6.0.1 API 23 - Qualcom Adreno (TM) 330
- API: OpenGLES
- Stop After: 7 Frames
  - [x] Trace From Beginning
  - [ ] Disable Buffering
  - [ ] Clear package cache
  - [x] Hide Unknown Extensions
  - [x] Disable pre-compiled shaders
- `android:debuggable="true"`
### sceneform-1.9pr2
image-based-lighting sample

**Skybox**|**isPostProcessingEnabled**|**filament build mode**|**gapid trace**
:-----:|:-----:|:-----:|:-----:
NONE|false|DEBUG|- 
ibl.skybox|false|DEBUG|- 
NONE|true|DEBUG|- 
ibl.skybox|true|DEBUG|- 
NONE|false|RELEASE|[1921.gfxtrace](https://drive.google.com/open?id=1DyiRXJZtWq1dSkTucdPgm9FwCJjscE-g)
ibl.skybox|false|RELEASE|[1917.gfxtrace](https://drive.google.com/open?id=1--dAFtO1WHyG---1PYUDdkq_jFpDSbmr)
NONE|true|RELEASE|[1912.gfxtrace](https://drive.google.com/open?id=1QeNO0zuL6qMfRtzJVxtnMGB8wNqx4G5S)
ibl.skybox|true|RELEASE|[1900.gfxtrace](https://drive.google.com/open?id=1bPGZ2J-oTxSESSKk1K0E7Scgo5xHeSp2)

Graphics API Debugger doesn't show me the framebuffer used by filament for some reason, it's just a list of commands. gapid works fine with Galaxy S5 + other app or Galaxy S7 Edge + Filament, am I missing something?

**Comment by pixelflinger** [comment]
Yes it looks like the gapid traces above have captured frames in a context that's not filament's and stopped before any filament rendering. You might have to increase the number of frame after which it stops.

The crash is scary, it's deep inside the GL driver.

**Comment by 61315** [comment]
![preview050719](https://user-images.githubusercontent.com/46559594/60730116-59eedc80-9f7f-11e9-916b-ed7b68cbbc1f.gif)
kinda works, trouble applying emissive, in hurry, will sum this up soon, sorry for the delay.
