### ISSUE TITLE
SSAO doesn't work on integrated Intel GPU

### ISSUE THREAD

**Issue by romainguy** [google/filament#1288]
**Describe the bug**
Run `gltf_viewer` with FlightHelmet on a MacBook Pro with integrated Intel GPU (make sure you are not using the discrete GPU if testing on a 15"). SSAO creates a lot of artifacts on screen. It looks like self shadowing.

**Screenshots**
<img width="1136" alt="Screen Shot 2019-06-11 at 4 34 35 PM" src="https://user-images.githubusercontent.com/869684/59313716-f2d35600-8c66-11e9-8fbe-de1ddb7555b9.png">
<img width="1136" alt="Screen Shot 2019-06-11 at 4 34 48 PM" src="https://user-images.githubusercontent.com/869684/59313717-f2d35600-8c66-11e9-9799-8e7c90d45afe.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - GPU: Intel iris Plus  Graphics 655
 - Backend: OpenGL

**Comment by nitronoid** [comment]
I also have this issue (or similar), however I'm experiencing it on two NVIDIA GPU's. It only happends when using the OpenGL backend.
![ssao_bug_1](https://user-images.githubusercontent.com/22621071/59352287-31751900-8d18-11e9-8fd5-68ff941991e6.png)
![ssao_bug_2](https://user-images.githubusercontent.com/22621071/59352288-31751900-8d18-11e9-9103-f846c8c4faaa.png)

**Comment by romainguy** [comment]
Thanks @nitronoid. Are those discrete GPUs?

**Comment by nitronoid** [comment]
@romainguy Sorry I'm not familiar with the term, but yes I think so. Quadro M3000M and Quadro K2200.

**Comment by nitronoid** [comment]
@romainguy Just saw the tags on this issue and wanted to clarify, I'm not using macos. I get these artifacts on RHEL-7 and Fedora 29.

**Comment by romainguy** [comment]
Thanks, good to know it's not OS specific.
