### ISSUE TITLE
The win32 implementation of getCanonicalPath doesn't work the same as the base implementation

### ISSUE THREAD

**Issue by Stof25** [google/filament#13]
Win32 implementation calls the Windows SDK function PathCanonicalize but it only works correctly when called with a fully qualified path it seems.

Example : the README for Windows says to test the compiled code with
`./samples/material_sandbox --ibl=../samples/envs/office ../assets/models/sphere/sphere.obj`

This results directly in calling getCanonicalPath with `../samples/envs/office` which then returns `samples/envs/office` and then the IBL isn't found.

The same issue applies directly to the path for the obj file to open.

Workaround : pass absolute paths. This doesn't work for the IBL though because of another issue later on with path concatenation.

**Comment by bejado** [comment]
Thanks for reporting these issues- seems like valid bugs. Will take a look.
