### ISSUE TITLE
Android Material problem with baseColor

### ISSUE THREAD

**Issue by drtyhlpr** [google/filament#1307]
**Problem description**
I experience a problem with material "baseColor" after I swiched to filament-master from filament-20190423-android. I am using the latest git sources from yesterday and built the latest android aar on linux and required bin tools on windows (cmgen.exe, matc.exe, filamesh.exe). I am using the default clear_coat material with ibl (without additional normal maps or textures). The material names match the object material name and the problem also exists when only using the default material.

**Bug description**
After successful building my project without any errors (materials, meshes and environment map are generated if required) the app starts and reacts without further problems but the material colors are wrong. The displayed material "only" color ranges from black to red. ibl/skybox based reflections work fine and there are no visible display/material errors but the wrong base color. 

```
readUncompressedAsset("materials/clear_coat.filamat").let {
m1 = Material.Builder().payload(it, it.remaining()).build(engine)
m2 = Material.Builder().payload(it, it.remaining()).build(engine)
...
}

setParameter("baseColor", Colors.RgbType.SRGB, 1.0f, 0.85f, 0.57f)
setParameter("baseColor", Colors.RgbType.SRGB, 0.05f, 0.05f, 0.05f)
...
```
setParameter on baseColor does not change the color of the Material as expected (was working fine with filament-20190423-android). changing the r,g,b values only results in a more red or black material (lower value = black, higher value = red).  using linear colors results in the same problem.

I tried different solutions but nothing worked and I am out of ideas.

- Have there been any recent changes to material basecolor parameter and or android bindings?
- Any idea about the materials red to black color?

**Comment by drtyhlpr** [comment]
```
        val matPackage = MaterialBuilder()
            .platform(MaterialBuilder.Platform.MOBILE)
            .name("Clear coat2")
            .shading(MaterialBuilder.Shading.LIT)
            .uniformParameter(MaterialBuilder.UniformType.FLOAT3, "baseColor")
            .optimization(MaterialBuilder.Optimization.NONE)
            .material("void material(inout MaterialInputs material) {\n" +
                    "    prepareMaterial(material);\n" +
                    //"    material.baseColor.rgb = materialParams.baseColor;\n" +
                    "    material.baseColor.rgb = vec3(0.8);\n" +
                    "    material.roughness = 0.65;\n" +
                    "    material.metallic = 1.0;\n" +
                    "    material.clearCoat = 1.0;\n" +
                    "}\n")

            .build()
```
hmm setting the baseColor.rgb static and using material builder works fine.

**Comment by romainguy** [comment]
Thanks for the report. Do you have screenshots by any chance? I'm not sure I understand what the issue is. What do you mean by the baseColor is wrong?

**Comment by romainguy** [comment]
I think I figured it out, there was a change made recently to support arrays of 1 element (which wasn't possible before) but the Java bindings relied on arrays of 1 element being treated as non-arrays. I'm uploading a fix. Thanks for finding this bug!

**Comment by erolgobel17** [comment]
This changes addresses issue google#1307. We recently fixed the way we support arrays
of parameters to allow arrays of 1 element. Previously single elements (e.g. float)
were treated as an array of 1 element and the other way around. Unfortunately our
Java bindings relied on this behavior to set colors. This change simply directly
calls the float3 and float4 variants of setParameter() when setting a color.
