### ISSUE TITLE
add aar to a new  android peoject ,some errors

### ISSUE THREAD

**Issue by jaccen** [google/filament#1309]
new a android poject, and new module->import aar---->filament-20190313-android
there are some problems~~ 
**Describe the bug**
> Task :app:checkArm8DebugDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkArm8DebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.filament.AndroidPlatform found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Box found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.BuildConfig found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Camera found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Camera$Fov found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Camera$Projection found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Colors found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Colors$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Colors$Conversion found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Colors$LinearColor found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Colors$RgbType found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Colors$RgbaType found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Engine found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Engine$Backend found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Entity found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.EntityInstance found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.EntityManager found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.EntityManager$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.EntityManager$Holder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Fence found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Fence$FenceStatus found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Fence$Mode found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Fence$Type found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Filament found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndexBuffer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndexBuffer$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndexBuffer$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndexBuffer$Builder$BuilderFinalizer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndexBuffer$Builder$IndexType found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndirectLight found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndirectLight$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndirectLight$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.IndirectLight$Builder$BuilderFinalizer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.LightManager found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.LightManager$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.LightManager$Builder$BuilderFinalizer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.LightManager$ShadowOptions found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.LightManager$Type found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$BlendingMode found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$CullingMode found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$Interpolation found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$Parameter found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$Parameter$Precision found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$Parameter$Type found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$Shading found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Material$VertexDomain found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.MaterialInstance found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.MaterialInstance$BooleanElement found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.MaterialInstance$FloatElement found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.MaterialInstance$IntElement found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.MathUtils found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.NativeSurface found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.NioUtils found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.NioUtils$BufferType found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Platform found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Platform$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Platform$UnknownPlatform found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.RenderableManager found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.RenderableManager$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.RenderableManager$Builder$BuilderFinalizer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.RenderableManager$PrimitiveType found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Renderer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Scene found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Skybox found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Skybox$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Skybox$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Skybox$Builder$BuilderFinalizer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Stream found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Stream$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Stream$Builder$BuilderFinalizer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.SwapChain found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$Builder$BuilderFinalizer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$CompressedFormat found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$CubemapFace found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$Format found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$InternalFormat found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$PixelBufferDescriptor found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$Sampler found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Texture$Type found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.TextureSampler found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.TextureSampler$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.TextureSampler$CompareFunction found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.TextureSampler$CompareMode found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.TextureSampler$MagFilter found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.TextureSampler$MinFilter found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.TextureSampler$WrapMode found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.TransformManager found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.VertexBuffer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.VertexBuffer$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.VertexBuffer$AttributeType found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.VertexBuffer$Builder found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.VertexBuffer$Builder$BuilderFinalizer found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.VertexBuffer$QuatTangentContext found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.VertexBuffer$QuatType found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.VertexBuffer$VertexAttribute found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.View found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.View$AntiAliasing found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.View$DepthPrepass found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.View$Dithering found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.View$DynamicResolutionOptions found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.View$QualityLevel found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.View$RenderQuality found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.Viewport found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.TextureHelper found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.TextureHelper$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.UiHelper found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.UiHelper$1 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.UiHelper$2 found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.UiHelper$ContextErrorPolicy found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.UiHelper$RenderSurface found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.UiHelper$RendererCallback found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.UiHelper$SurfaceViewHandler found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  Duplicate class com.google.android.filament.android.UiHelper$TextureViewHandler found in modules classes.jar (filament-20190313-android.aar) and classes.jar (filament-android-release.aar)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
According to the error you've added two Filament AARs to your project:

filament-20190313-android.aar
filament-release-android.aar

Remove one of them to fix the problem.

**Comment by lucagrana** [comment]
@romainguy from where I have to remove one of them?
