### ISSUE TITLE
Don't compile materials for all APIs everywhere

### ISSUE THREAD

**Issue by romainguy** [google/filament#1314]
In:
- `libfilament`
- `libfilagui`
- `libgltfio`
- All Android samples
- All C++ samples

We compile materials with `-a all` (in Filament if Vulkan or Metal support is on). This creates materials that are much bigger than they should be (iOS/macOS end up with Vulkan shaders, Android/Linux with Metal shaders).

We should fix this.

Part of the problem is that `matc` doesn't allow to specify 2 or 3 target APIs, either one or all of them. We should simply change `matc` to accept multiple `-a` flags (including `-a all`).

**Comment by bejado** [comment]
I can start work on the `matc` / `libfilamat` side of things. Ideally [`MaterialBuilder::TargetApi`](https://github.com/google/filament/blob/master/libs/filamat/include/filamat/MaterialBuilder.h#L52) can be updated to be a bitfield so `filamat` clients can take advantage of this too.

**Comment by prideout** [comment]
Good point.  Note that the C++ `TargetApi` type is used internally in a few places that expect there to be one and only one type, so we would need to add asserts to those places to ensure that only 1 bit is set on those places.

Alternatively we could rename the public-facing type to `TargetApiFlags` (which would perhaps alias to uint32_t)  and privately define an internal `TargetApi` that would be an actual enum.

**Comment by romainguy** [comment]
We'll need to fix the Android samples who compile materials for all APIs at the moment.
