### ISSUE TITLE
Support RenderTarget in Renderer:readPixels

### ISSUE THREAD

**Issue by Zefz** [google/filament#1315]
**Is your feature request related to a problem? Please describe.**
PR #1275 introduced support for rendering to offscreen targets. Readback of the result from GPU back to CPU is possible by using the underlying driver:

```
    filament::details::upcast(engine).getDriverApi().readPixels(
            filament::details::upcast(offscreenRenderTarget)->getHwHandle(),
            width, height, format, type, buffer);

```

**Describe the solution you'd like**
filament::Renderer provides the public readPixels function, but it only supports readback from the current SwapChain. Add an argument to select for what pixel data we are trying to readback (e.g a specific texture or a rendertarget).

The signature of
```
    void readPixels(uint32_t xoffset, uint32_t yoffset, uint32_t width, uint32_t height,
            backend::PixelBufferDescriptor&& buffer);
```

should be something like

```
    void readPixels(uint32_t xoffset, uint32_t yoffset, uint32_t width, uint32_t height,
            backend::PixelBufferDescriptor&& buffer, filament::Texture *texture);
```

**Describe alternatives you've considered**
An alternative solution would be to somehow get raw pixel data from a Texture to copy through the CPU. But it needs to go through the renderer anyways as this will require communication with the GPU.

**OS and backend**
I've tested that this works as expected with the OpenGL backend

**Comment by prideout** [comment]
Seems reasonable!  I'll discuss with the team and look into this.  ReadPIxels is super slow -- out of curiosity what are you using it for?

**Comment by prideout** [comment]
@zefz it's a little tricky because the client application would need to call our top-level render() function in order to resolve the offscreen render target.

We provide ReadPixels for debug purposes only, we don't like it because it stalls the pipeline.  In the long term we might provide an asynchronous PBO-based solutions.

If you have a compelling use case then let us know, it will help us prioritize.

**Comment by Zefz** [comment]
Yes I am aware it's a very slow process, but as far as I know it is the only way to access copy pixel data directly from a rendered view to either feed into a computer vision algorithm (e.g OpenCV) or to store an image to the disk (like taking a screenshot from a view that is not the SwapChain).

This image shows how we develop a stereo vision navigation algorithm using filament to render multiple cameras to a single entity and the main camera observing the scene.
![stereo_vision](https://user-images.githubusercontent.com/1359524/59742898-01c19600-926f-11e9-8fe5-b1329828cf4d.png)

**Comment by prideout** [comment]
This looks like a cool app!  Here's how to unblock you in the short term.  If you're using offscreen render targets, somewhere in your app you already have something like this:

```
        if (renderer->beginFrame(window->getSwapChain())) {
            for (filament::View* offscreenView : mOffscreenViews) {
                renderer->render(offscreenView);
            }
            for (auto const& view : mSwapChainViews) {
                renderer->render(view->getView());
            }
            renderer->endFrame();
        }
```

To use ReadPixels on a particular render target, temporarily substitute the `mSwapChainViews` with a single view that draws a nonlit quad whose basecolor is the texture that corresponds to the render target of interest.  After that, issue a ReadPixels as you normally would.

**Comment by Zefz** [comment]
Thanks! I will look into it.

**Comment by prideout** [comment]
Since this is doable with the current API (although admittedly awkward), I'm closing this ticket for now.
