### ISSUE TITLE
OpenGL Shader crash on Mali-T760 (RK3288)

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1320]
The unoptimized vertex shader crashes when a MaterialInstance is instantiated. If the vertex shader is extracted using matinfo and compiled with the Mali offline compiler it fails with a segmentation fault.
```
$ malisc -d  Mali-T600_r11p0-00rel0 -c Mali-T760 --vertex unoptimized.vs
Arm Mali Offline Compiler v6.4.0
(C) Copyright 2007-2018 Arm, Ltd.
All rights reserved.

No core revision specified, using "r1p0" as default.

Segmentation fault: 11
```
If the default driver version is used (Mali-Gxx_r11p0-00rel0 at time of writing) the compilation succeeds.

I whittled down the shader to the following minimum reproduce:
```
#version 300 es

invariant gl_Position;

struct MaterialVertexInputs {
    vec4 worldPosition;
};

void main() {
    MaterialVertexInputs material;
    gl_Position = material.worldPosition;
}
```

**Comment by rawnsley** [comment]
I got some [useful feedback from ARM](https://community.arm.com/developer/tools-software/graphics/f/discussions/13543/segmentation-fault-when-accessing-simple-stuct/36572). The filament shader only does this when setting _gl_Position_ so I was able to work around the problem by [calling a property accessor for worldPosition instead](https://github.com/rawnsley/filament/commit/52bdf3cdb6281cc7839a9addd3028f123adfa8f1). I've not made a pull request because this change probably hurts performance and I'm not sure of the canonical way to make it conditional or if you want to bother given the limited number of devices affected.

**Comment by romainguy** [comment]
Thanks! Based on ARM's feedback I'm not sure why the workaround works. Note that your change doesn't hurt performance, functions/function calls don't exist in shaders after they are compiled.

**Comment by rawnsley** [comment]
My best guess is that it prevents the compiler from trying an optimization step that otherwise causes a crash, but I really don't know enough about GLSL internals. You can also do something like _gl_Position = min(material.worldPosition, vec4(1e+38))_

**Comment by romainguy** [comment]
I'll go with your getter solution, but this will only work for non-optimized shaders. Optimized shaders may have the issue depending on what the optimizer does.
