### ISSUE TITLE
Support for UNSIGNED_BYTE indicies in gltfio

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1326]
The GLTF spec allows for [UNSIGNED_BYTE types](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#indicescomponenttype-white_check_mark), but it's not currently supported.

[Here's an example](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough) from the GLTF samples that renders poorly:

<img width="1016" alt="Screenshot 2019-06-20 at 16 12 23" src="https://user-images.githubusercontent.com/303516/59860912-bc3cc000-9377-11e9-9e3d-f35f373e37c5.png">

The parse must have choked somewhere along the line. If you remove the offending nodes from the scene (2 and 3) it renders fine except for the billboards:

<img width="1023" alt="Screenshot 2019-06-20 at 16 26 20" src="https://user-images.githubusercontent.com/303516/59861136-2bb2af80-9378-11e9-91f5-d2eeb2937835.png">

**Comment by prideout** [comment]
Thanks for the report!  This is indeed a bug although the diagnosis is incorrect.  gltfio automatically converts uint8 indices.  Rather than removing the label nodes, you can remove their NORMAL attributes, and the problem clears up.

**Comment by rawnsley** [comment]
Ah. That's the problem I have with my GLTF library so I was projecting :-)

**Comment by prideout** [comment]
This is a really interesting bug, I think it might be in Filament itself rather than gltfio.  I will keep digging.
