### ISSUE TITLE
depthWrite doesn't always default to false

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1336]
The documentation says that depthWrite defaults to false, but its default value is actually [dictated by the blending mode](https://github.com/google/filament/blob/master/filament/src/Material.cpp#L180).

The upshot of this is that you sometimes have to set it explicitly to true when dealing with transparent materials.

**Comment by romainguy** [comment]
The header file has the correct documentation. I'm updating `Materials.md.html` right now.
