### ISSUE TITLE
is there any project  use filament.aar for android with java?

### ISSUE THREAD

**Issue by jaccen** [google/filament#1340]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**OS and backend**
Is this feature OS/backend specific? If so, explain why.

**Comment by romainguy** [comment]
There are several samples in `android/samples`. They compile Filament instead of using the AAR but all you have to do is link against the AAR instead.

**Comment by jaccen** [comment]
but the examples use kt， i want use filament as a lib in my java project，is there any doc or project example？
