### ISSUE TITLE
is there anyone who use filament as a lib for another android project？

### ISSUE THREAD

**Issue by jaccen** [google/filament#1341]
is there anyone who use filament as a lib for another android project？
my required：
    (1) use filament  as a lib for my another project
    (2)my android project  use java not kt;
    (3)have some exaples or doc for use filament 

or through CMakeList add filament sources to my project.

anyone who can give me a tutorials?

**Comment by romainguy** [comment]
You can find several samples for Android in `android/samples`. These samples include the library project directly, instead you'll want to add the AAR as a library (see https://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst for instance).

The samples are written in Kotlin but call the Java APIs, there's nothing fundamentally different there.
