### ISSUE TITLE
Instantiating multiple Filament scenes at once (Android)

### ISSUE THREAD

**Issue by drummeric** [google/filament#1344]
**Describe the bug**
I'm trying to render 2 Filament views at the same time on Android. For now, they're just displaying the same mesh with a different background color. They reuse the same Engine, but each view has its own UiHelper, Choreographer, Renderer, Scene, View, Camera, Mesh, SwapChain, etc. However, I keep getting an error which I assume is due to some sort of memory issue, but I'm not entirely sure how to investigate it:
> A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x14 in tid 9656 (FEngine::loop), pid 9479

Have you seen this error before? Does it sound like I am taking the correct approach to rendering two Filament views, or should/can I be reusing even more resources?

**Expected behavior**
I expect that I can render two Filament scenes at the same time (and likely reuse a majority of the resources if possible)

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Android Pie 9.0

**Additional context**
I'm rendering this view as a React Native Android view.

**Comment by romainguy** [comment]
Could you show us the entire crash please? If I understand correctly you're rendering Filament in two different `Surface/TextureView`? Rendering multiple scenes is definitely supported (you can do it in the same `Surface/TextureView` by the way).

**Comment by drummeric** [comment]
When I debug my application in Android Studio, the entire application just quits and all I see in the logs is the error that I posted:
> A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x14 in tid 9656 (FEngine::loop), pid 9479

I'll spend some more time to see if I can get a better crash log though.

You're understanding is correct; I am rendering Filament in two different TextureViews.

**Comment by romainguy** [comment]
Do you need to use two `TextureView` (also, why not `SurfaceView`? It'll be more efficient) or could you render two `filament.View` in the same `TextureView` instead? (also more efficient)

**Comment by drummeric** [comment]
We're building a React Native app to work on both iOS and Android. The two views that I'm implementing for Android are already implemented and working for iOS (using a different 3D library) and we already have all of the React hooks in place. It seems it would be easiest to align with our iOS solution and keep the two separate views on Android. That way, I don't have to rewrite a bunch of the iOS logic as well to get everything into one view. But I can certainly pursue this option if the separate view solution isn't feasible.

I've noticed this issue does not happen until I add a mesh to the scene. If I don't add any mesh to the scenes, I'm able to render both views with different backgrounds at the same time. However, when I display just a single view with the mesh, it renders just fine (which leads me to believe the mesh rendering logic itself has no issues).

**Comment by romainguy** [comment]
What you're trying to do should work but it's quite wasteful, that's why I was asking whether you could use a single `TextureView` instead (or even `SurfaceView` to be even more efficient).

**Comment by romainguy** [comment]
Here's a test app I just wrote that sets up two `SurfaceView`.

Each uses a separate `View`, `Scene`, `Renderer` and `SwapChain`. They do share the same mesh (`Material`, `VertexBuffer` and `IndexBuffer`) but they both use different renderables. You can change `setupScenes()` to make both `SurfaceView` render the same scene and it works as well. You can also share the same `Renderable` in both scenes and it works too.

I can't do much more without more precise logs from you. What version of Filament are you using?

![test](https://user-images.githubusercontent.com/869684/60054037-46459b00-968e-11e9-988b-09cad132aaf7.png)

[MainActivity.kt.txt](https://github.com/google/filament/files/3322672/MainActivity.kt.txt)

**Comment by drummeric** [comment]
Thanks for the sample! This is super helpful. Looking at your code, the major difference is that I'm building brand new VertexBuffers and IndexBuffers for each scene, and it seems like that might be causing the issue. When I reuse the same Renderable (and therefore buffers) in both scenes, it renders both scenes without any issues. That solution will probably work for our use case (and will be more efficient than rebuilding the vertex and index buffers anyways), so you can feel free to mark this issue as resolved.

It seems like my issue might not have been with rendering two scenes at once, but rendering two different meshes/buffers in the same Engine. Do you need to tell the Engine that you're providing it two distinct sets of buffers when you create the Renderables? My guess is that I'm somehow overriding the first buffer when I create the second buffer (or something like that). Also, I'm using Filament-1.9.0.

**Comment by romainguy** [comment]
That is really weird, I would have expected issues to come from sharing, not from creating multiple buffers. We have multiple test apps (loading glTF files for instance) that create multiple index/vertex buffers without issues. Are both buffers created in the exact same way? I just changed my test app to recreate the index and vertex buffers in the second scene and it works just fine.
