### ISSUE TITLE
Control visibility of renderables

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1354]
My Filament renderables mirror the scene graph structure in my application, so for instance changes to a models transform is passed through to the corresponding entity in Filament's TransformManager.

Is there a similar way I could toggle the visibility of renderables in Filament to match my scene graph? It seems like the only option is to add and remove them from the scene and I feel I might be missing a trick.

**Comment by romainguy** [comment]
You can control the visibility by setting the `layerMask` on a `Renderable` (see `RenderableManager::setLayerMask`). You can then control which layers are visible in a `View` with `View::setVisibleLayers`. The layer mask and the visible layers set are bit fields.

For instance: https://github.com/google/filament/blob/master/samples/app/FilamentApp.cpp#L99. You can see the `mainView` uses `0x4` as the visible layers. Down below `cameraCube` is associated with layer `0x2`, making it invisible in the main view. `godView` even further down however uses the visible layer mask `0x6`, making both regular objects and `cameraCube` visible. The result looks like this (`mainView` is the bottom left, `godView` is the top right):

<img width="1376" alt="Screen Shot 2019-06-28 at 9 08 17 AM" src="https://user-images.githubusercontent.com/869684/60355865-4e4e5500-9984-11e9-976d-f8e109b6cc25.png">

**Comment by Realitian** [comment]
Hi, @romainguy 
there is no way to control for 100 of objects?
using `View::setVisibleLayers`, only 8 of objects can be control because of using 8 bit values?

**Comment by Realitian** [comment]
I confused, the Layer count will be count of the viewports?

**Comment by romainguy** [comment]
Many objects can be in the same layer.

**Comment by sundaranandram** [comment]
the setVisibleLayers doesnt seem to be exposed to the javascript API

**Comment by prideout** [comment]
@sundaranandram I'll fix that today.

**Comment by sundaranandram** [comment]
awesome, thanks!
