### ISSUE TITLE
Error compiling filament with  libc++abi-dev-8 

### ISSUE THREAD

**Issue by aindigo** [google/filament#1360]
**Describe the bug**
Compilation does not end due the following error:
```
$ ./build.sh release
...
...
 FAILED: libs/math/test_math
: && /usr/bin/clang++  -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -Wl,--gc-sections libs/math/CMakeFiles/test_math.dir/tests/test_fast.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_half.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_mat.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_vec.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_quat.cpp.o  -o libs/math/test_math  -static-libgcc -static-libstdc++ -Wl,-Bstatic -lc++ -lc++abi libs/math/libmath.a third_party/libgtest/tnt/libgtest.a -Wl,-Bdynamic -static-libgcc -static-libstdc++ -Wl,-Bstatic -lc++ -lc++abi -Wl,-Bdynamic -pthread && :
/usr/bin/ld: /usr/lib/llvm-8/bin/../lib/libc++abi.a: error adding symbols: file format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
**To Reproduce**
1. clone repository 
2. run ./build.sh release in filament directory

**Expected behavior**
Compilation success.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10
 - Compiler : Clang 8 (libc++-8)
 - GPU: nvidia 1060 GTX
 - Backend: Vulkan

* Im using llvm ppa for clang8

**Comment by romainguy** [comment]
The issue doesn't seem related to Filament. Your linker doesn't recognize your libc++.a file? What's llvm ppa btw?

**Comment by aindigo** [comment]
Im using the packages from the llvm project repository.

https://apt.llvm.org/

**Comment by romainguy** [comment]
Those are the packages we use on Ubuntu 14 in our CI.

**Comment by aindigo** [comment]
its a problem with the libraries, i tried to compile a simple program with the same flags for static compilation with libc++ and libc++abi  ,  and googling , it happened before.
 ill try to compile it with libc++ compiled from source.

**Comment by aindigo** [comment]
I was able to compile it with the llvm+clang from the tar.xz from the llvm site.  i think is a problem with the file, its corrupted or something. (clang-8)

**Comment by romainguy** [comment]
Thank you!
