### ISSUE TITLE
Crash: signal 4 (SIGILL), code 1 (ILL_ILLOPC) libfilament-jni.so

### ISSUE THREAD

**Issue by agGitHub** [google/filament#1361]
**Describe the bug**
I use Sceneform in my Android app. For some users, I have got the following crash:

signal 4 (SIGILL), code 1 (ILL_ILLOPC)
libfilament-jni.so
pid: 0, tid: 0 >>> com.mycompany.myapp <<<
backtrace:
  #00  pc 0000000000052eae  /data/app/com.mycompany.myapp-PuYPm-sE_PEw==/lib/arm/libfilament-jni.so

**To Reproduce**
Random crash. Only on Android 9 devices (not on Android 8).

**Expected behavior**
No crash :)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Android 9.x
 - GPU: don't know
 - Backend: ?

**Smartphone (please complete the following information):**
 - Device: don't know
 - OS: Android 9.x

**Additional context**
The filament library is used via Sceneform in my app.

**Comment by pocketutilities** [comment]
is there any solution for this issue? I still face this.
