### ISSUE TITLE
createFrence() sometimes crashes on Android 9

### ISSUE THREAD

**Issue by agGitHub** [google/filament#1362]
**Describe the bug**
I use Sceneform in my Android app. For some users, I have got the following crash:

signal 4 (SIGILL), code 1 (ILL_ILLOPC)
filament::Engine::createFence(filament::Fence::Type)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.mycompany.myapp <<<

backtrace:
  #00  pc 0000000000033a50  /data/app/com.mycompany.myapp-gnlxhlx-lA==/lib/arm/libfilament-jni.so (filament::Engine::createFence(filament::Fence::Type)+48)

**To Reproduce**
Random crash. Only on Android 9 devices (not on Android 8).

**Expected behavior**
No crash :)

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: don't know
 - OS: Android 9.x (no crash on Android 8.x devices)

**Additional context**
The filament library is used via Sceneform in my app.

**Comment by romainguy** [comment]
Thanks for the report. Do you have more information? Devices on which the crashes occur, longer logs, etc.?

**Comment by pixelflinger** [comment]
`ILL_ILLOPC` is an illegal opcode in the `mcr` instruction. This can happen because of insufficient privileges -- but I don't even know who is generating this `mcr` instruction or why it would happen "sometimes".

@agGitHub do you have the fill stack trace?

**Comment by romainguy** [comment]
We fixed this recently.
