### ISSUE TITLE
needless vector copy is made

### ISSUE THREAD

**Issue by greg7mdp** [google/filament#1366]
In `MeshAssimp.cpp`, we have the following code:

```
        auto ps = new State<half4>(std::move(asset.positions));
        auto ns = new State<short4>(std::move(asset.tangents));
        auto t0s = new State<ushort2>(std::move(asset.texCoords0));
        auto t1s = new State<ushort2>(std::move(asset.texCoords1));
        auto is = new State<uint32_t>(std::move(asset.indices));
```

which seems to indicate that the intent is for the vectors to be moved. However for the move to occur, I believe that the `State` move constructor should also have a std::move, as in:

![image](https://user-images.githubusercontent.com/1496907/60466974-3cd6a880-9c23-11e9-9e4f-2a6ac116338e.png)

**Comment by prideout** [comment]
I think this is a good catch, thanks!

By the way, if you are using MeshAssimp to load glTF files, we recommend switching to our gltfio library.

**Comment by romainguy** [comment]
The second `std::move` is not necessary since it's an r-value reference already at this point.

**Comment by greg7mdp** [comment]
@romainguy,  As soon as it is bound to a variable, it is not a rvalue reference anymore. You can step into it in the debugger and you'll see it invokes the vector copy constructor.

**Comment by greg7mdp** [comment]
@prideout, thanks for the suggestion. I'm just trying to understand the code by stepping through the material_sandbox sample. I'd like to integrate filament into an engineering software, so I already have a mesh and I am trying to figure out how to send it to filament.

**Comment by romainguy** [comment]
My bad, thanks for the clarification!

**Comment by greg7mdp** [comment]
sure. Thanks for filament :-)

**Comment by prideout** [comment]
@greg7mdp understood.   If you're loading raw mesh data, our simplest example of that in C++ is probably `vk_hellotriangle.cpp` in the samples directory, although it's a bit reductio ad absurdum.

**Comment by romainguy** [comment]
@greg7mdp The code in https://github.com/google/filament/blob/master/samples/app/Cube.cpp might be a little easier to follow if you want a simple example. A `Renderable` is made of `n` "primitives". A primitive is effectively a sub-mesh. Each primitive can have a material instance associate to it (a material instance is a `Material` + values for the material's parameters). Each primitive also has 1 or more attribues associated with it (the `geometry()` calls in `Renderable::Builder`). And make sure you set a bounding box too!

**Comment by greg7mdp** [comment]
@prideout, thanks a million, very helpful. I'll look at these instead (you are right I'm getting somewhat lost in material_sandbox)
