### ISSUE TITLE
Android - Toolchain parse error

### ISSUE THREAD

**Issue by EverCG** [google/filament#1367]
For anyone facing the following issue...

When producing android builds on Windows host, a parse error might occur due to the $ENV{ANDROID_HOME} line in each android toolchain file. The problem here is this line generates environment path string in Windows style while CMAKE still accepts the Unix style path.

When running on Windows host, (following steps from [here](https://github.com/google/filament/blob/master/android/Windows.md))add lines to convert environment path from windows style to Unix in following toolchain files

1) toolchain-aarch64-linux-android.cmake
2) toolchain-arm7-linux-android.cmake
3) toolchain-x86_64-linux-android.cmake
4) toolchain-x86-linux-android.cmake

**Example**
Look for line 30

Change 

`# toolchain`
`string(TOLOWER ${CMAKE_HOST_SYSTEM_NAME} HOST_NAME_L)`
`set(TOOLCHAIN $ENV{ANDROID_HOME}/ndk-bundle/toolchains/llvm/prebuilt/${HOST_NAME_L}-x86_64/)`

To

`# toolchain`
`string(TOLOWER ${CMAKE_HOST_SYSTEM_NAME} HOST_NAME_L)`
`file(TO_CMAKE_PATH $ENV{ANDROID_HOME} ANDROID_HOME_UNIX)`
`set(TOOLCHAIN ${ANDROID_HOME_UNIX}/ndk-bundle/toolchains/llvm/prebuilt/${HOST_NAME_L}-x86_64/)`

Hope it helps 😄

**Comment by romainguy** [comment]
Thanks!
