### ISSUE TITLE
Engine::destroy() taking **engine is atypical and annoying

### ISSUE THREAD

**Issue by gpyalt** [google/filament#1376]
This is not a bug per-say, more an interface design issue.  I wanted to mention it, but you may close it if you want.

All the non-static Destroy methods of the Engine class take a single pointer, like `void destroy (const Renderer *p)`. But  the static `Engine::destroy (Engine **engine)` takes a **ptr.

I get it that it is so the pointer can be nulled, but why the inconsistency with the other destroy(). Also this make it not possible to use a unique_ptr with a custom deleter to store the engine pointer. I would like to do the following:

```
class X
{
    using EnginePtr = unique_ptr<Engine, std::function<void (Engine *)>>;
    EnginePtr _engine;
}

_engine = EnginePtr(Engine::create(), [](Engine *e) { Engine::destroy(e); });
```

but that is not possible because the unique_ptr deleter takes a regular (not double) pointer.

**Comment by romainguy** [comment]
This method does null the pointer indeed, I can't remember why it was done this way. @pixelflinger can clarify. We could provide a variant that only takes an `Engine*` that wouldn't null the pointer.

**Comment by gpyalt** [comment]
Yes, I think having the variant would be nice and allow using unique_ptr! Thanks!

**Comment by gpyalt** [comment]
Looks like there was a change at one time, which was made for the member functions but not the static one. The example in `https://github.com/google/filament/blob/master/filament/include/filament/Engine.h` shows the code calling the various destroy functions with **pointers, which does not work anymore:

```
engine->destroy(&view);
engine->destroy(&scene);
engine->destroy(&renderer);
engine->destroy(&swapChain);
engine::destroy(&engine); // clears engine*
```
