### ISSUE TITLE
Integration with Basis Universal GPU Texture Codec

### ISSUE THREAD

**Issue by MatushkaRossiya** [google/filament#1378]
**Is your feature request related to a problem? Please describe.**
Minimizing textures size for on-disk storage and network transport (downloading, patching, etc), while supporting each platform's preferred compressed GPU texture format for optimal rendering performance.

**Describe the solution you'd like**
Integration of Filament with recently open-sourced and backed by Google Basis Texture Codec.

**Describe alternatives you've considered**
Compressing texture files with LZ4.

**OS and backend**
Thanks to Basis multiplatform support it should be transparent to end-users.

**Comment by romainguy** [comment]
We have to think about whether it makes sense to be directly in Filament. There's technically no reason why it cannot be done in the app or as a separate library (like our glTF loader for instance).

**Comment by prideout** [comment]
Our mipgen tool can be used to compress textures and it does not yet have basis support, that's something we can consider adding.

**Comment by donmccurdy** [comment]
Just FYI, this documentation may be helpful for supporting KTX and Basis Universal: https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/KTXDeveloperGuide.md. It's a fairly new document, please let us know if you have any issues with it.

/cc @lexaknyazev (author)

**Comment by romainguy** [comment]
Thanks @donmccurdy!

**Comment by romainguy** [comment]
@prideout Is there still more work to do here?

**Comment by prideout** [comment]
@romainguy this work is complete, this issue is basically a dup #4771, I forgot to close these issues.
