### ISSUE TITLE
using opacity maps

### ISSUE THREAD

**Issue by sfrankel** [google/filament#1379]
Is there a C++ code sample for how I can use an opacity map to set an object's transparency?

I note from extending sample code that I can add a 4th term to a material's basecolor attribute to set transparency to a specific value; eg:  
material.baseColor.rgba = vec4(0.9805, 0.8438, 0.7188, 0.25); // 25% transparency

What's the best way to use one channel of a dedicated map to set spatially varying transparency?

TIA
Scott

**Comment by romainguy** [comment]
You can simply do `material.baseColor.a = texture(...).r;`. Remember that Filament uses premultiplied alpha so you need to do `material.baseColor.rgb *= material.baseColor.a;` afterwards.

**Comment by sfrankel** [comment]
Hi @romainguy 
Thanks for the tip!  All makes sense... except the premult step isn't producing results I'd expect.

For example, when I include the premult step, the render output is properly opaque where the opacityMap is white, but *black* where my opacityMap is black.  I'd expect those black areas to be transparent.

Note that I'm building the material inline in my C++ code:
    .parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "basecolorMap")
    .parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "opacityMap")
...
        material.baseColor.rgb = baseColor;
        material.baseColor.a = texture(materialParams_opacityMap, uv).r;
        material.baseColor.rgb *= material.baseColor.a;
...

Am I missing something?  Thanks again!
Scott

**Comment by romainguy** [comment]
Did you enable the proper blending mode on the material?

**Comment by kaustubh-seachange** [comment]
@sfrankel @romainguy Would you provide additional info how the blending mode could be changed on the material.
