### ISSUE TITLE
glTF models are black with WebGL + SwiftShader

### ISSUE THREAD

**Issue by prideout** [google/filament#1380]
Filament clients who use puppeteer are hitting an issue where models look black when the GPU is disabled.  This can be reproduced by simply adding the `--disable-gpu` argument to the Chrome invocation:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-gpu http://127.0.0.1:8080/helmet.html
```

The debugger output does not reveal anything obviously wrong.  Other Filament demos seem fine, like `parquet.html`.

<img width="1201" alt="Screen Shot 2019-07-08 at 2 40 04 PM" src="https://user-images.githubusercontent.com/1288904/60846876-a3b11000-a195-11e9-9fc1-d0bd445139be.png">

**Comment by prideout** [comment]
The bug goes away if I add `-g` to matc or if I simplify Filament's core shading in any number of ways.  At this point it really seems like the bug existing within Chrome's `--disable-gpu` functionality (which is presumably based on SwiftShader) so I sent mail to the Chrome team.

**Comment by prideout** [comment]
The current Canary build does not allow WebGL 2.0 when disable-gpu is enabled, which makes it difficult to know if the issue still exists in upcoming versions of Chrome.

**Comment by chikul** [comment]
> The bug goes away if I add `-g` to matc or if I simplify Filament's core shading in any number of ways. At this point it really seems like the bug existing within Chrome's `--disable-gpu` functionality (which is presumably based on SwiftShader) so I sent mail to the Chrome team.

Hello,

did they ever come back to you with a reply? It's still broken. Also could you please elaborate on how can I fix this with matc -g option? I want to render quite complex gltf models in headless mode with filament, but currently, it seems like a dead-end to me.

Any help is very appreciated!

Thanks!
