### ISSUE TITLE
Crash in lightbulb sample using Vulkan on Ubuntu 18.04

### ISSUE THREAD

**Issue by amesgames** [google/filament#1411]
**Describe the bug**
Running the lightbulb sample on Ubuntu 18.04 hangs my entire computer for several seconds after first showing the the model in the window, then crashes with a vkQueueSubmit error in VulkanDriver::commit. This occurs with the cube, shapes, and monkey sample assets.

No other sample crashes this way. I have tested material_sandbox and many of the samples prefixed with vk_.

**To Reproduce**
1. Build in Debug on Ubuntu 18.04
2. Run lightbulb using `./samples/lightbulb -a vulkan ./samples/assets/models/shapes/shapes.obj` from `out/cmake-debug`.

**Expected behavior**
No crash.

**Screenshots**
[Screenshot](https://pasteboard.co/IodyZ8R.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU: GeForce RTX 2080
 - Backend: Vulkan

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A

**Additional context**
Complete standard output:
~/projects/filament/out/cmake-debug/samples/assets/models/monkey$ ../../../lightbulb -a vulkan monkey.obj 
FEngine (64 bits) created at 0x7fd746fe6010 (threading is enabled)
FEngine resolved backend: Vulkan
Selected physical device 'GeForce RTX 2080' from 1 physical devices. (vendor 0x0x10de, device 0x0x1e87, api 0x0x401063, driver 0x0x6b868000)
vkCreateSwapchain: 1024x640, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 3
utils::PostconditionPanic
in void filament::backend::VulkanDriver::commit(Handle<filament::backend::HwSwapChain>):858
in file filament/backend/src/vulkan/VulkanDriver.cpp
reason: vkQueueSubmit error.
#0 ../../../lightbulb() [0x60d30d]
#1 ../../../lightbulb() [0x623dc5]
#2 ../../../lightbulb() [0x623230]
#3 ../../../lightbulb() [0x6230f5]
#4 ../../../lightbulb() [0xa9eccf]
#5 ../../../lightbulb() [0xac1b16]
#6 ../../../lightbulb() [0xac1a5d]
#7 ../../../lightbulb() [0xa9ea48]
#8 ../../../lightbulb() [0xa9a234]
#9 ../../../lightbulb() [0xa702c0]
#10 ../../../lightbulb() [0xa7007e]
#11 ../../../lightbulb() [0x4d8676]
#12 ../../../lightbulb() [0x4d53d4]
#13 ../../../lightbulb() [0x4ed26d]
#14 /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fd74ca276db]
terminating with uncaught exception of type utils::PostconditionPanic
Aborted (core dumped)

**Comment by amesgames** [comment]
I tested this on v1.3.0 tag and HEAD of master branch as of today.

**Comment by prideout** [comment]
Closed in favor of #1450
