### ISSUE TITLE
any example to use setExternalStream on android 

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1418]
hi guys
    Filament is great. We just migrate our app from libgdx to Filament. Because we need to preprocess texture by gles. So it maybe  improve perfomance by sharing texture  Texture.setExternalStream . We tried to figure out how to use the method,but always get black image. 
 The following steps  we had a try :
        1. create engine with shared eglcontext
        2. create external texture , surfacetexture and Surface with shared eglcontext makecurrent
        3. create new context and surface by eglCreateWindowSurface with the Surface created above          
             3.1) draw on this new context
             3.2) call swapbuffer on finish drawing
        4. make shared eglcontext current 
        5. wait onFrameAvailable,and update external texture,and
                 5.1)   set external texuture id to Filament streambuilder 
                 5.2) and we also tried another way by setting Surface  to Filament streambuilder                
        6. build filament texture with stream and draw filament ,get black bitmap

   So  a example  to use setExternalStream will be very helplful.   
   Thanks in advance!

**Comment by romainguy** [comment]
All you need to do is create a `Stream` by passing the `SurfaceTexture` to `Stream.Builder.stream(…)`. Then you can set the `Stream` on your `Texture` using `setExternalStream(…)`. You don't need to use a shared `EGLContext` nor pass the external texture id to Filament.
If you really want to do the latter, you need to create a `Stream` by passing the external texture id, width and height to the `Stream.Builder`. Then set the stream on your texture with `setExternalStream(…)`. Make sure your shared texture has the target `GL_TEXTURE_EXTERNAL_OES`.

We recommend the first approach as the second one will cause a texture copy on every update (which is sometimes what you want).

In either case you don't have to call `updateTexImage()` on the `SurfaceTexture`, Filament will take care of it for you.
