### ISSUE TITLE
OSX: can't figure out how to use the java JNI library, throws java.lang.UnsatisfiedLinkError: com.google.android.filament.Engine.nCreateEngine(J)J

### ISSUE THREAD

**Issue by ikatson** [google/filament#142]
**Describe the bug**
Can't figure out how to use the JNI library. Trying to create "Engine" throws java.lang.UnsatisfiedLinkError.

**To Reproduce**

1. Download filament binaries to "filament" folder.
2. Create a file ```MyMain.class``` with this content
    ```
    import com.google.android.filament.*;

    public class MyMain {
        public static void main(String[] args) {
            Engine engine = Engine.create();
        }
    }
    ```

3. Compile

    ```
    javac -cp filament/lib/filament-java.jar MyMain.java
    ```

4. Run

    ```
    java -cp filament/lib/filament-java.jar:./ -Djava.library.path=$PWD/filament/lib/x86_64/ MyMain
    ```

**Expected behavior**
The app would not crash. However, this output is produced:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.google.android.filament.Engine.nCreateEngine(J)J
        at com.google.android.filament.Engine.nCreateEngine(Native Method)
        at com.google.android.filament.Engine.create(Engine.java:36)
        at MyMain.main(MyMain.java:5)
```

**Desktop (please complete the following information):**
 - OS: OSX 10.12.6
 - java: tried both 10 and 1.8, current version is ```"1.8.0_144"```

**Additional context**
Tried setting LD_LIBRARY_PATH to filament/lib/x86_64/ and putting those *dylib files into /usr/local/lib, nothing helped. 
Also tried compiling filament from sources instead of downloading the binaries, same result.

**Comment by bejado** [comment]
Hey @ikatson, try adding
```
System.loadLibrary("filament-jni");
```
before your call to `Engine.create()`

**Comment by ikatson** [comment]
It helped @bejado , thanks!

**Comment by bejado** [comment]
@romainguy Yeah, I like the idea of automatically loading the library. Alternatively the `Engine` class could always try to load the library and issue a warning if it fails, assuming the client will then correctly call `loadLibrary` manually.

**Comment by romainguy** [comment]
Oh wait we already have a way. Simply call `Filament.init()`. I should update the README to indicate this step is required.

**Comment by bejado** [comment]
Ah yes, forgot about `Filament.init()` :)

**Comment by romainguy** [comment]
See PR #143

**Comment by salvf** [comment]
First of all excuse my bad English.
I followed your instructions and didn't work for me. 
**Desktop**

- OS: Windows 10
- JDK: Oracle 1.8_111

I'm using Netbeans IDE so I added in the in the properties project Run->VM Options: `-Djava.library.path ="C:\Users\user\Desktop\filament1.2\lib\x86_64"`, also this path was added in the environment variable "PATH", 
### **Code:**
```
26  System.setProperty("java.library.path","C:\\Users\\user\\Desktop\\filament1.2\\lib\\x86_64");
27  Filament.init();
28  Engine e = Engine.create();
```
_I wrote the line 26 after changed the VM Options and see that didn´t solve the problem._

### **Error:**
```
 Exception in thread "main" java.lang.UnsatisfiedLinkError: no filament-jni in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.android.filament.Filament.<clinit>(Filament.java:22)
	at jfilament.JFilament.main(JFilament.java:27)
```

**Comment by bejado** [comment]
@salvf What are the contents of the `filament1.2\lib\x86_64` folder?

You could also try removing the extra space in VM Options:
```
-Djava.library.path="C:\Users\user\Desktop\filament1.2\lib\x86_64"
```

**Comment by salvf** [comment]
this is the content of the `filament1.2\lib\x86_64` folder
![image](https://user-images.githubusercontent.com/19564452/58519302-922d1f00-8178-11e9-8c31-9d230dc9728e.png)

the content of the `filament1.2\lib` folder
![image](https://user-images.githubusercontent.com/19564452/58520027-96a70700-817b-11e9-906b-0b67d531bc94.png)

I removed the extra spaces but it still doesn't work

![image](https://user-images.githubusercontent.com/19564452/58519583-edabdc80-8179-11e9-8dbe-4f63bb863006.png)
