### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by SuhailAlhegry** [google/filament#1420]
Trying to build a project on windows with the release build fails with `unresolved external symbol...` linker errors.

Steps to reproduce:
1. Download the release
2. Creat an empty c++ project using visual studio 2019
3. Change the platform toolset to target visual studio 2017 (v141) build tools
4. Add the includes and link the libraries
5. Try to build

Screenshot:
https://pasteboard.co/IoBozrR.png

Specs:
 - OS: Windows
 - Compiler: Visual Studio BuildTools

**Comment by bejado** [comment]
Make sure you have the libraries listed in this order:

```
filament.lib
backend.lib
bluegl.lib
filabridge.lib
filaflat.lib
utils.lib
geometry.lib
smol-v.lib
opengl32.lib
```

Are you making OpenGL calls in other parts of your program? Seems you might be experiencing the same issue as #652. See the most recent comments for a workaround.

**Comment by SuhailAlhegry** [comment]
@bejado let me check that, brb.

**Comment by SuhailAlhegry** [comment]
After rearranging the the libraries, I found out that there isn't a library of the name `opengl32.lib` am I missing something?

**Comment by bejado** [comment]
`opengl32.lib` isn't provided by Filament, it's provided by Windows. You may need to install the Windows SDK. 

https://stackoverflow.com/questions/22231740/opengl32-lib-not-linking-properly

**Comment by SuhailAlhegry** [comment]
After resolving all linkage problems, I encountered another error -I think it's supposed to be a warning..?, but it's preventing compilation-:
`C4146 unary minus operator applied to unsigned type, result still unsigned` at file `PixelBufferDescriptor.h`  at line [122](https://github.com/google/filament/blob/90792e7032b3464957d5c30e12a71de86309a974/filament/backend/include/backend/PixelBufferDescriptor.h#L122)

ignoring the error with a `#pragma` results in another error that prevents `main` from compiling:

`LNK2019	unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)`

**Comment by bejado** [comment]
It's hard to say without seeing the rest of your project. Did you try switching the subsystem to Windows? Then you should define `WinMain` in place of `main`.

**Comment by SuhailAlhegry** [comment]
I tried switching the subsystem to every possible subsystem. I think the problem is very similar to #1274. I also tried building the source directly, but with no luck.

**Comment by bejado** [comment]
Are you calling OpenGL directly anywhere in your project?
