### ISSUE TITLE
Question: How to get node names in gltf on Android

### ISSUE THREAD

**Issue by flyingonly** [google/filament#1425]
Since I need to change some parameters of the materialInstance related to some specific nodes, I want to get the name information of the node. However as far as I know, the gltfio library changes the nodes to filament entities, and I couldn't find a way to get the name info. Meanwhile, the material names related to these nodes always turn out to be "ubershader". 
For now, the only way I found to change the parameters of the specific node is using the index in the nodes part in gltf file. Is there a better way to find a specific node?

**Comment by romainguy** [comment]
I believe gltfio uses the name component manager to copy the glTF names to Filament entities. Check `utils::NameComponentManager`. You can also look at the source of gltfio's SimpleViewer or the source of the gltf_viewer sample. That sample shows the names of all glTF nodes.

**Comment by flyingonly** [comment]
Thanks for the reply! I have read the code, and i think I just need to modify the jni code to reach the NameComponentManager or otherwise just add a function to get the name of the entities. That will certainly be a solution, btw I just wonder with the current release version of aar, any chance to reach the same info?

**Comment by prideout** [comment]
Ah, we need to either (1) provide JNI bindings for NameComponentManager or (2) or provide a utility method in `FilamentAsset` that does this for you.  I think the latter might be more convenient.
