### ISSUE TITLE
Displaced nodes when loading skinned model in gltf_viewer

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1426]
The attached model [BotBobo.zip](https://github.com/google/filament/files/3411478/BotBobo.zip) is an articulated robot avatar and apparently loads without error, but the nodes get scattered by the skin mapping. If you remove the skin definition from the _Bot_Skinned_ mesh and _Bot_Skinned_ node, the model looks fine.

For reference, these models are used as avatars in [Mozilla Hubs](https://hubs.mozilla.com/).

Here's how it looks in [glTF Viewer](https://gltf-viewer.donmccurdy.com/):

<img width="793" alt="Screenshot 2019-07-19 at 15 31 24" src="https://user-images.githubusercontent.com/303516/61542919-658bda00-aa3a-11e9-9bbe-c851ccbba8a6.png">

And here's how it looks in gltf_viewer:

<img width="664" alt="Screenshot 2019-07-19 at 15 30 37" src="https://user-images.githubusercontent.com/303516/61542931-6d4b7e80-aa3a-11e9-9d3e-c99c5a13ca5c.png">

**Comment by prideout** [comment]
Thanks for the report!  I will investigate.

**Comment by prideout** [comment]
Hmm the model looks ok with me on macOS, see attached.  I wonder if you're using an old build?  I think we fixed a skinning bug last week.

![Screen Shot 2019-07-19 at 9 33 02 AM](https://user-images.githubusercontent.com/1288904/61550792-483e1800-aa08-11e9-853e-3f5862b44925.png)

**Comment by rawnsley** [comment]
I'm about a month behind. I'll update and double check once I'm back at my computer. Thanks for looking at it so quickly.

**Comment by rawnsley** [comment]
Confirmed fixed in the latest build.
