### ISSUE TITLE
A mistake in the geometric shadowing term?

### ISSUE THREAD

**Issue by honzukka** [google/filament#1434]
**Describe the bug**
In the Filament documentation, section 4.4.2., equation 15 (https://google.github.io/filament/Filament.md.html#materialsystem/specularbrdf/geometricshadowing(specularg)), the _geometric normals_ are being used. However, the GGX paper (Walter et al, Microfacet Models for Refraction through Rough Surfaces, 2007) suggests that the _microfacet normals_ (i.e. the halfway vectors) should be used instead.

This would also make the formula drastically simpler, so my questions are: Have you thought about this? Which normal is the correct one to use here?

**Comment by romainguy** [comment]
The microfacet normal `m` is unknown which is why `n` is used there. The halfway vector `h` is used in the NDF as a way to statically estimate how many microfacets will reflect light towards the viewer.
