### ISSUE TITLE
FTexture::generateMipmaps assertion is too restrictive

### ISSUE THREAD

**Issue by bejado** [google/filament#1435]
The assert inside `FTexture::generateMipmaps` is too restrictive:

```
// The OpenGL spec for GenerateMipmap stipulates that it returns INVALID_OPERATION unless
// the sized internal format is both color-renderable and texture-filterable.
if (!ASSERT_POSTCONDITION_NON_FATAL(isColorRenderable(engine, mFormat),
        "Texture format must be color renderable")) {
    return;
}
```

Metal is able to reshape texture formats into 3 components. We should probably move this assertion into the OpenGL driver.

**Comment by bejado** [comment]
@pixelflinger thoughts on moving it to the OpenGL driver?

**Comment by romainguy** [comment]
Instead of moving it to the driver could we add an `isMipmappable()` or something that would return a value driver-specific?

**Comment by bejado** [comment]
Yeah, I think that could work too.
