### ISSUE TITLE
skinned model load incorrectly after morph supported

### ISSUE THREAD

**Issue by Yzou-NaO** [google/filament#1440]
**Describe the bug**
[RiggedFigure](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure)
The skinning and animation are incorrect in **gltf_viewer** after supporting morph.

**Comment by prideout** [comment]
Thanks for the bug but gltfio does not yet support morphing. The Filament core will support morphing as soon as I merge #1427.

**Comment by prideout** [comment]
With pending changes, this test model seems to animate correctly for a few seconds then stops, I will look into that.

**Comment by prideout** [comment]
I've confirmed that 90c17cc caused a regression, currently investigating.  The `skinningEnabled` uniform seems to get clobbered after a few seconds of animation.
