### ISSUE TITLE
Question: correct way to update vertex buffer data

### ISSUE THREAD

**Issue by kpeeters** [google/filament#1445]
In order to feed updated vertex position data into filament, I currently do

    vertex_buffer->setBufferAt(*engine, 0, 
             filament::VertexBuffer::BufferDescriptor(data, size) );

Here `data` is a fixed buffer which does not change in location and size between invocations of the above line (only the content changes). This seems to work fine and allows me to have a dynamically changing mesh. However, recent discussion in https://github.com/google/filament/issues/1279 suggests that this may be an unintended side-effect. 

Am I doing this right, or is there a better way to update vertex buffer data without re-creating the entire `VertexBuffer`?

**Comment by prideout** [comment]
It's perfectly fine to call `setBufferAt` to mutate a vertex buffer.  What's under debate in #1279 is something different, which is the ability to change a particular renderable from vertex buffer A to vertex buffer B.
