### ISSUE TITLE
cant build with Debug instead of Release on Windows with VS2017

### ISSUE THREAD

**Issue by zbzdys** [google/filament#1446]
**Describe the bug**
VS build Debug mode sandbox failed with error "redefinition of operator=="; besides, i enabled vulkan support

**To Reproduce**
1. make directory out/cmake-release

2. cmake ../.. -T"LLVM" -G "Visual Studio 15 2017 Win64" -DCMAKE_CXX_COMPILER:PATH="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_LINKER:PATH="C:/Program Files/LLVM/bin/lld-link.exe" -DFILAMENT_SUPPORTS_VULKAN=ON

3. msbuild  TNT.sln /t:material_sandbox /m /p:configuration=Debug

**Expected behavior**
It should be compiled successfully as Release mode

**Screenshots**
![image](https://user-images.githubusercontent.com/18547591/61988761-75b64180-b058-11e9-9892-74b3b72a8a0f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 x64 1903
 - GPU: [e.g. NVIDIA GTX 1080] NVIDIA GTX 1080TI with driver 431
 - Backend: [OpenGL/Vulkan] Vulkan

**Comment by bejado** [comment]
1. What version of Clang are you using?
2. Can you copy the full error from `msbuild`?

**Comment by zbzdys** [comment]
Clang: 8.0.0

commands:
mkdir out/cmake-release and cd

cmake ../.. -T"LLVM" -G "Visual Studio 15 2017 Win64" -DCMAKE_CXX_COMPILER:PATH="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_LINKER:PATH="C:/Program Files/LLVM/bin/lld-link.exe" -DFILAMENT_SUPPORTS_VULKAN=ON

msbuild  TNT.sln /t:material_sandbox /m /p:configuration=Debug

also i noticed that the definition and previous definition is the same line(105 and 111 too). It seems that if i write the friend function implementation outside, the redefinition error gone. but still a lot duplicate symbol stbi_** in material_sandbox.dir\Debug\stb.obj and in stb.lib(stb.obj).

`	{
...
        template<typename T, typename U>
	friend bool
		operator==(const STLAlignedAllocator<T>& rhs, const STLAlignedAllocator<U>& lhs);

	template<typename T, typename U>
	friend bool
		operator!=(const STLAlignedAllocator<T>& rhs, const STLAlignedAllocator<U>& lhs);
};

template<typename T, typename U>
bool
operator==(const STLAlignedAllocator<T>& rhs, const STLAlignedAllocator<U>& lhs) {
	return true;
}

template<typename T, typename U>
bool
operator!=(const STLAlignedAllocator<T>& rhs, const STLAlignedAllocator<U>& lhs) {
	return false;
}`

here is the msbuild log, thanks a lot

[msbuild.log](https://github.com/google/filament/files/3439938/msbuild.log)

**Comment by zbzdys** [comment]
Also in the Building with Ninja on Windows section, it should be :

cmake ..\.. -G Ninja 

instead of

cmake .. -G Ninja

**Comment by bejado** [comment]
Seems like a valid issue you're running into. I won't have access to a Windows machine until next week, but in the meantime you could try to build with Clang 7, as that's what our CI uses.

**Comment by zbzdys** [comment]
Confirmed clang 7.1.0 debug mode no operator== redefinition problem.

But still lots of duplicate symbol:

lld-link.exe : error : duplicate symbol: stbi_failure_reason in material_sandbox.dir\Debug\stb.obj and in stb.lib(stb.obj) [D:\workspace\tmp\vs_test\filament\out\cmake-release\samples\material_sandbox.vcxproj]
         lld-link.exe : error : duplicate symbol: stbi_image_free in material_sandbox.dir\Debug\stb.obj and in stb.lib(stb.obj) [D:\workspace\tmp\vs_test\filament\out\cmake-release\samples\material_sandbox.vcxproj]
         lld-link.exe : error : duplicate symbol: stbi_set_flip_vertically_on_load in material_sandbox.dir\Debug\stb.obj and in stb.lib(stb.obj) [D:\workspace\tmp\vs_test\filament\out\cmake-release\samples\material_sandbox.vcxproj]
         lld-link.exe : error : duplicate symbol: stbi_load in material_sandbox.dir\Debug\stb.obj and in stb.lib(stb.obj) [D:\workspace\tmp\vs_test\filament\out\cmake-release\samples\material_sandbox.vcxproj]
         lld-link.exe : error : duplicate symbol: stbi_load_from_file in material_sandbox.dir\Debug\stb.obj and in stb.lib(stb.obj) [D:\workspace\tmp\vs_test\filament\out\cmake-release\samples\material_sandbox.vcxproj]

**Comment by zbzdys** [comment]
in addition, does this message mean something?

filament\samples\material_sandbox.cpp(337): warning : unused variable 'debug' [-Wunused-variable]
clang-cl.exe : warning : argument unused during compilation: '/std:c++14' [-Wunused-command-line-argument]

**Comment by zbzdys** [comment]
I find that stb_image.h is included in stb.c, and stb.c is contained in many projects like material_sanbox and sample-app.

material_sandbox seems rely on sample-app and needs sample-app.lib in its additional dependicies, so many apis like stbi_image_free get duplicated.

I'm unfamiliar with building, still dont know why release mode is ok but debug mode failed.

I want to make some step-by-step debug so I need debug mode. Thanks!

**Comment by zbzdys** [comment]
I solved the duplicate symbol problem.

stb.c in third_party/stb/stb.c is included as source file by sample-app and material_sandbox, besides, sample-app is relied by material_sandbox. Actually, it is the same file stb.c, which used by project stb, that leads to this duplicate symbol problem. Remove stb.c from material_sandbox and sample-app, instead being their source file, then problem solved.

I dont know why Release mode doesn't show this problem, maybe there are some optimization steps.

After solving this problem, it runs to another problem:
Assertion failed: 0, file D:\workspace\tmp\vs_test_vulkan\filament\third_party\imgui\imgui_draw.cpp, line 1537

still looking into it

**Comment by zbzdys** [comment]
Finally, i can debug step by step.

The last problem is the current directory is not the same at release and debug mode.

FilamentApp.cpp line 160:

mImGuiHelper = std::make_unique<ImGuiHelper>(mEngine, window->mUiView->getView(), utils::Path::getCurrentDirectory()
            /*getRootPath()*/ + "assets/fonts/Roboto-Medium.ttf");

This will help solve the problem under debug mode. Thanks!
