### ISSUE TITLE
Android Vulkan failed to run

### ISSUE THREAD

**Issue by zbzdys** [google/filament#1447]
**Describe the bug**
I have built filament with vulkan support and the android apk installed successfully. But it cant create vulkan instance with the android samples like textured object or image based light.

**To Reproduce**
1. Build filament with vulkan support to get tools and files needed by android samples like libfilament.a
2. build android apk with Engine.backend.Vulkan and vulkan extra flags
3. install and run the app

**Expected behavior**
I have run textured object and image based light samples successfully with opengl es, the default backend.
Now i try vulkan, evertything is ok but the app crashes when running. I know you are stilling testing vulkan, so i'll just give you a testcase.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2] Huawei P20 Pro
 - OS: [e.g. Android Pie 9.0] Android pie9.0

**Additional context**
07-27 10:41:18.925 11767 11872 D vulkan  : searching for layers in '/data/app/com.google.android.filament.textured-c0EZ3_JoWK6QNHPHwKOYZg==/lib/arm64'
07-27 10:41:18.925 11767 11872 D vulkan  : searching for layers in '/data/app/com.google.android.filament.textured-c0EZ3_JoWK6QNHPHwKOYZg==/base.apk!/lib/arm64-v8a'
......
07-27 10:41:18.927 11767 11872 E Filament: Panic
07-27 10:41:18.927 11767 11872 E Filament: in filament::backend::VulkanDriver::VulkanDriver(filament::backend::VulkanPlatform *, const char *const *, uint32_t):150
07-27 10:41:18.927 11767 11872 E Filament: reason: Unable to create Vulkan instance.
07-27 10:41:18.927 11767 11872 E Filament:
07-27 10:41:18.927   648   648 D Layer   : Skip in Layer::computeScreenBounds 1
--------- beginning of crash
07-27 10:41:18.927 11767 11872 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 11872 (lament.textured), pid 11767 (lament.textured)
07-27 10:41:18.928   648   648 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 13 lines
07-27 10:41:18.928   648   648 D Layer   : Skip in Layer::computeScreenBounds 1
07-27 10:41:18.944   648   648 D Layer   : Skip in Layer::computeScreenBounds 1
07-27 10:41:18.944   648   648 D Layer   : Skip in Layer::computeScreenBounds 1
07-27 10:41:18.944   648   648 D Layer   : Skip in Layer::computeScreenBounds 1
07-27 10:41:18.945   648   648 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 5 lines
07-27 10:41:18.945   648   648 D Layer   : Skip in Layer::computeScreenBounds 1
07-27 10:41:18.945   648   648 D Layer   : Skip in Layer::computeScreenBounds 1
07-27 10:41:18.945   648   648 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 3 lines
07-27 10:41:18.945   648   648 D Layer   : Skip in Layer::computeScreenBounds 1

**Comment by prideout** [comment]
Interesting, I think you successfully built both Filament and the app with Vulkan enabled so this might be a real bug that is specific to the Huawei P20 Pro.

Are you able to try out the demo with any other devices?  Are you able to run non-Filament Vulkan samples on the Huawei, e.g. the SaschaWillems demos?

**Comment by zbzdys** [comment]
Other device test: no

non-filament vulkan app: yes

filament sample without vulkan: yes

**Comment by zbzdys** [comment]
I will update today's work, this time i try to build filament aar first but cant. My previous method doesn't have this step, because it seems the samples only need files like libfilament.a instead of aar file.

Now the problem is that i cant build arm64-v8a aar file and get some error messages like:
In function `filament::PlatformVkAndroid::createVkSurfaceKHR(void*, void*, unsigned int*, unsigned int*)':
PlatformVkAndroid.cpp:(.text._ZN8filament17PlatformVkAndroid18createVkSurfaceKHREPvS1_PjS2_+0x30): undefined reference to `vkCreateAndroidSurfaceKHR'

  PlatformVkAndroid.cpp:(.text._ZN8filament17PlatformVkAndroid18createVkSurfaceKHREPvS1_PjS2_+0x48): undefined reference to `vkCreateAndroidSurfaceKHR'

====================

Here is my new command:

cmake ..\.. -G Ninja -DCMAKE_CXX_COMPILER:PATH="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_LINKER:PATH="C:/Program Files/LLVM/bin/lld-link.exe" -DFILAMENT_SUPPORTS_VULKAN=ON -DCMAKE_INSTALL_PREFIX=..\release\filament -DCMAKE_BUILD_TYPE=Release -DENABLE_JAVA=NO

Generate with Ninja, vulkan on and java off, build type Release

then type:
ninja

build them all successfully(with matc and other tools)

then mkdir out\cmake-android-release-aarch64 and:

cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\android-release\filament -DCMAKE_TOOLCHAIN_FILE=..\..\build\toolchain-aarch64-linux-android.cmake -DFILAMENT_SUPPORTS_VULKAN=ON ..\..

then:
ninja install

before build the aar file, i add abiFilters 'arm64-v8a' to filament-android build.gradle.

build log is here:
[build.log](https://github.com/google/filament/files/3441303/build.log)

**Comment by zbzdys** [comment]
complete rebuild with/without vulkan shows that -DFILAMENT_SUPPORTS_VULKAN=ON makes the build failed, now i dont know why i could build the vulkan samples but only crashed when running. Now cant build samples with vulkan, cant get an apk or filament aar file.

**Comment by romainguy** [comment]
I can compile Filament's AAR with Vulkan support enabled with master (on macOS).

**Comment by prideout** [comment]
Today on master, I can build Filament and its demos with Vulkan enabled although I hit #1096 at run time.  @zbzdys you might need to do a clean.

**Comment by zbzdys** [comment]
@prideout did you use Windows to build? what version is your clang? i find out that to build windows version, clang8 causes operator== redefinition problem in memaligh.h, but clang7 is  fine. #1446 

Now i install clang7 and build the platform tools with it. when build for android, the build toolchain uses ndk prebuilt aarch64-linux-android21-clang which is version 8.0.7

maybe somecode abouot vulkan is incompatible with Clang8 or Windows.

**Comment by zbzdys** [comment]
I read build.sh to get the info about vulkan building.

when generating platform tools, i added -DFILAMENT_SUPPORTS_VULKAN=ON ;
and cmake-android-release-aarch64, add it too;
but i forgot add -Pextra_cmake_args=-DFILAMENT_SUPPORTS_VULKAN=ON to gradlew when building for aar.

Problem solved, it's not a clang version or compatible problem.

Here is my summary for android build on Windows with Vulkan enabled:
1. mkdir out/cmake-release in the filament root directory

2. cd out/cmake-release and run:
cmake ..\\.. -G Ninja -DCMAKE_CXX_COMPILER:PATH="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_LINKER:PATH="C:/Program Files/LLVM/bin/lld-link.exe" -DFILAMENT_SUPPORTS_VULKAN=ON -DCMAKE_INSTALL_PREFIX=..\release\filament -DCMAKE_BUILD_TYPE=Release -DENABLE_JAVA=NO

3.then run:
ninja
(I need filamesh.exe when run samples so the original "ninja matc resgen cmgen" is not enough)

4.mkdir out/cmake-android-release-aarch64 in the filament root directory

5. run:
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\android-release\filament -DCMAKE_TOOLCHAIN_FILE=..\\..\\build\toolchain-aarch64-linux-android.cmake -DFILAMENT_SUPPORTS_VULKAN=ON ..\\..

6.then run:
ninja install

7.goto filament root directory, then go to android/filament-android, add:
ndk {
            abiFilters 'arm64-v8a'
        }
to section defaultConfig for i only test armv8-64a

8.then at this directory run:
gradlew -Pfilament_dist_dir=..\\..\out\android-release\filament assembleRelease -Pextra_cmake_args=-DFILAMENT_SUPPORTS_VULKAN=ON
successfully build
