### ISSUE TITLE
Texture.setExternalStream not work on vivo android 5.1

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1448]
**Describe the bug**
  To construct Texture by Stream built with SurfaceTexture, it works fine in pixel android 9.0,but get black bitmap on vivo x7 android 5.1.1
   Based our investigate, we found it seems SurfaceTexture.updateTexImage not work in Filament native code on updateStreams.

**Comment by romainguy** [comment]
Do you get anything in the logs when the issue happen?

**Comment by geroge-d** [comment]
we have built a debug version of Filamant to do this test,but no any related log print. there are some clues below:
1. set OnFrameAvailableListener  to SurfaceTexture. On finish rendering frame, call swapBuffer, this listener was just  callbacked at the first time. so we guess filament maybe not call updateTexImage in the right way for android 5.1.1
2. we test it on  android 6.0,7.0,9.0. it only occurs on android 5.1

**Comment by romainguy** [comment]
Filament tries to invoke `updateTexImage` on external streams on every frame. We do this at the beginning of each frame: go through all external streams, if the stream is a native stream, call `updateTexImage` on it. Note that `onFrameAvailable` is not invoked after `updateTexImage`, it indicates that you should call `updateTexImage`.

**Comment by geroge-d** [comment]
we also tried this way.  Call updateTexImage after onFrameAvailable is called,but we get the black image.

I think we have no method in Java end ,that make Filament eglcontext  current,because filament attach new texture,  created in Filament elgcontext,  to SurfaceTexture on native code.

**Comment by romainguy** [comment]
You're not supposed to call updateTexImage yourself, Filament will do it.

**Comment by pixelflinger** [comment]
@geroge-d what do you mean by "does not work"? does it crash? Is it just black?

Do you see this message in the logs "Using ASurfaceTexture" when you run on Android 5 vs. Android  6?

**Comment by geroge-d** [comment]
1. get black image.
2. don't see any log like this on running on  Android 5

**Comment by rawnsley** [comment]
I'm seeing a similar bug. On an Android 7.0 device my video stream works fine, but on an Android 5.1 (Mali) device the output is just green. I am able to play this video file in a pure OpenGL application (no Filament) so the device is definitely capable of decoding it.

I don't see "Using ASurfaceTexture" in the log either and looking at that part of the code I guess I would only see it on Android SDK 28+ devices.

Adding extra logging into OpenGLDriver::beginFrame confirms that it is calling into ExternalStreamManagerAndroid::updateTexImage and that this is being called regularly.

In case it's relevant ExternalStreamManagerAndroid is using _nativeUpdateTexImage_, but I get the same result if I force it to use _updateTexImage_.

**Comment by kpeeters** [comment]
> You're not supposed to call updateTexImage yourself, Filament will do it.

@romainguy Is this still true? On an Adreno-510 on API 24, I get black textures if I do not call `updateTexImage` myself.

**Comment by romainguy** [comment]
We do call `updateTexImage()` yes.

**Comment by kpeeters** [comment]
That comment seriously confused me, but a look at `OpenGLDriver.cpp` cleared things up. Just in case someone else runs into something related: filament only seems to call `updateTexImage()` for `NATIVE` streams, not for `TEXTURE_ID` streams.

**Comment by pixelflinger** [comment]
Why this is not working is still a mystery, but realistically this won't be investigated further.
Not Actionable.
