### ISSUE TITLE
Possibility of use WebGL instead of WebGL2 on Apple platform.

### ISSUE THREAD

**Issue by cbjhong** [google/filament#1455]
How many of possibility of use WebGL instead of WebGL2 on apple platform?
Can you let me know about the list of WebGL2 extensions what used in filament webgl part?
If there is not much, then I would like to try to make webgl 1.0 version of filament.
If filament can be run on safari, then it would be great.
Cheers!

**Comment by romainguy** [comment]
Making a WebGL 1.0 version of Filament would require a substantial amount of work. Filament relies on GLES 3.0 for many features (seamless cubemaps, texture LOD indexing, UBOs, floating point textures, etc.) and while some of those features are available as GLES 2.0/WebGL 1.0 extensions they may not all be. The management of uniforms in particular would require extensive work. You are welcome to give it a try but this is unfortunately not on our list of priorities. Targeting WebGPU seems a like a more interesting goal.
