### ISSUE TITLE
Build using Mesa/Software emulation enabled for GPU-less devices

### ISSUE THREAD

**Issue by sleroux** [google/filament#1463]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
More so a question than a feature but is it possible to build Filament using Mesa and it's software emulation abilities to run on machines without GPUs?

**Comment by prideout** [comment]
It should be possible to use a SwiftShader driver since it supports ES 3.0.  Out of curiosity, what are you interested in using Filament for?

**Comment by romainguy** [comment]
I don't know about Mesa specifically but any implementation that's OpenGL 4.1 should be compatible. We use SwiftShader (another software implementation) internally at Google to run tests on machines without GPUs.

**Comment by sleroux** [comment]
> It should be possible to use a SwiftShader driver since it supports ES 3.0. Out of curiosity, what are you interested in using Filament for?

Just to clarify, when you're building with SwiftShader/ES 3.0, are you making use of the experimental `USE_EXTERNAL_GLES3` flag that is defined in the CMake files? I'm curious about passing in the SwiftShader libs into Filament's build scripts.

**Comment by prideout** [comment]
Yep, we use that flag internally at Google to build with SwiftShader.  One gotcha is that you might need to provide a stub implementation for glTexStorage2DMultisample because SwiftShader does not support it even though it claims to support 3.1.

**Comment by sleroux** [comment]
My apologizes for necro'ing this closed issue but last question: When you're linking in the SwiftShader drivers along with the USE_EXTERNAL_GLES3 flag, are you modifying the rpath as well to the CMake scripts to locate the drivers? Just trying to connect the last piece of the puzzle by connecting the two libraries.

For context, I'm looking to do a similar thing as running filament on a cloud-based VM that doesn't have a GPU for testing and as a stop-gap for some light rendering until we can provision some devices with GPUs.

**Comment by prideout** [comment]
@AdrianAtGoogle might know the answer to your question, which might be that we staticly link it or something crazy like that :)

**Comment by sleroux** [comment]
I've been digging more into this issue and I'm 92% confident I'm linking in EGLESv3 correctly from SwiftShader when compiling with USE_EXTERNAL_GLES3 enabled but keep getting a segfault when executing sample apps. It looks like this line is the culprit:

https://github.com/google/filament/blob/master/filament/backend/src/Platform.cpp#L112

I would imagine it should be returning PlatformEGL if we are using Open GL ES externally? Unless I'm completely missing something :/

**Comment by prideout** [comment]
Be sure to pass an instance of your custom `Platform` class into the second optional argument of Engine::create.

**Comment by prideout** [comment]
e.g. you could define a type like `class PlatformSwiftshader : public filament::backend::OpenGLPlatform`, which @AdrianAtGoogle has done internally.

**Comment by sleroux** [comment]
Since `OpenGLPlatform` is an interface class, is it possible to reuse an existing Open GL ES platform implementation for `PlatformSwiftShader` or would I need to write custom implementations for the virtual methods?

**Comment by prideout** [comment]
I've attached a small example implementation (cpp + h), it might need some fixups but should give you the basic idea.

[PlatformSwiftshader.zip](https://github.com/google/filament/files/3493308/PlatformSwiftshader.zip)
