### ISSUE TITLE
getWorldPosition() is view dependent

### ISSUE THREAD

**Issue by prideout** [google/filament#1485]
When called from the fragment shader, `getWorldPosition()` does not return a world-space coordinate as its name would suggest.

One way to repro this in `gltf_viewer` is to add a user-defined clip plane by adding:

```cpp
shader += "if (getWorldPosition().x > 0.0) discard;\n";
```

to the bottom of `shaderFromKey`, then running the app with no arguments and tumbling the camera.

**Comment by prideout** [comment]
This issue was likely introduced with 81e3ac18cebfd451e0053f26e3b8b64a9637de4b

The issue goes away if I set `camera_at_origin` to false in `Engine.h`

**Comment by romainguy** [comment]
It's a world position relative to the camera ^^ It's probably caused by the changes Mathias made to improve precision far from the world origin (the camera becomes the origin).

**Comment by prideout** [comment]
Yep.  :) 

This issue is harmless but I came across it while writing a demo that applies a custom clipping plane (like [this](https://prideout.net/assets/thumbnails/ClipPlanesBig-masked.png)).

I think we can easily "fix" this (as well as`getWorldCameraPosition`) while keeping our move-the-world-to-camera trick for precision.  I'll give it a try.

**Comment by romainguy** [comment]
Sounds good. Just be careful because shading is done in this "world" space. If you change getWorldPosition somehow other things may have to change too (light positions etc.).
