### ISSUE TITLE
"No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/filament#15]
I just wanted to try out the sample, but I got this error:

![image](https://user-images.githubusercontent.com/5357526/43690580-fb8bd51a-9914-11e8-8ce2-7793deb30d5d.png)

**Comment by romainguy** [comment]
It opens properly for me on several machines. Do you have an NDK properly installed and setup?

**Comment by romainguy** [comment]
It should be. I have no idea what the problem is here, we don't even support the MIPS ABI (and it's not part of the NDK anymore I believe).

**Comment by AndroidDeveloperLB** [comment]
Is it possible that it's because I'm using Windows OS?
Or that I have AMD CPU ?

**Comment by romainguy** [comment]
Those have nothing to do with MIPS so I doubt they're related.

BTW did you follow the other instructions in the README and built the native libraries with cmake already? These are necessary before you can build the AAR.

**Comment by banshee** [comment]
I had the same problem (a very unexpected "No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android") when I opened an old project, and fixed it by updating some build settings:

```
diff --git a/AndroidStudioHolder/app/build.gradle b/AndroidStudioHolder/app/build.gradle
index c42f8710..8bc8b1aa 100644
--- a/AndroidStudioHolder/app/build.gradle
+++ b/AndroidStudioHolder/app/build.gradle
@@ -2,7 +2,7 @@ apply plugin: 'com.android.application'
 
 android {
     compileSdkVersion 26
-    buildToolsVersion '26.0.2'
+    buildToolsVersion '28.0.2'
 
     defaultConfig {
         applicationId "com.digium.SwitchvoxSoftphone"
diff --git a/AndroidStudioHolder/build.gradle b/AndroidStudioHolder/build.gradle
index 70e20276..8295018f 100644
--- a/AndroidStudioHolder/build.gradle
+++ b/AndroidStudioHolder/build.gradle
@@ -6,7 +6,7 @@ buildscript {
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.0.1'
+        classpath 'com.android.tools.build:gradle:3.3.0-alpha05'
         classpath 'com.google.gms:google-services:3.1.0'
 
         // NOTE: Do not place your application dependencies here; they belong
diff --git a/AndroidStudioHolder/gradle/wrapper/gradle-wrapper.properties b/AndroidStudioHolder/gradle/wrapper/gradle-wrapper.properties
index 790c9505..4e61a125 100644
--- a/AndroidStudioHolder/gradle/wrapper/gradle-wrapper.properties
+++ b/AndroidStudioHolder/gradle/wrapper/gradle-wrapper.properties
@@ -1,6 +1,6 @@
-#Tue Sep 05 11:15:44 PDT 2017
+#Mon Aug 13 15:32:30 PDT 2018
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.9-all.zip

```

**Comment by AndroidDeveloperLB** [comment]
@romainguy You are correct. I was sure it's just NDK that's needed. Seems it's a lot more.
Closing this as I don't have time for this. Sorry.
Thank you for the good work.

**Comment by stark25795** [comment]
Find your own local android-sdk, if you download the relevant sdk of ndk, there will be a folder called "ndk-bundle"

![image](https://user-images.githubusercontent.com/13508067/44529778-848aca80-a70a-11e8-9f8f-ae38d910cb6d.png)

There is a folder called "toolchains" inside.
![image](https://user-images.githubusercontent.com/13508067/44529814-99675e00-a70a-11e8-92ca-9286c932c092.png)

We noticed that there are no mips64el related files inside.
![image](https://user-images.githubusercontent.com/13508067/44529819-9ec4a880-a70a-11e8-8128-e041fb4b2282.png)

The solution is as follows:

[Click here ](https://developer.android.com/ndk/downloads/?hl=zh-en)to download the NDK package separately through the browser.
After unzipping, open the "toolchains" folder, compare it with the android-sdk->ndk-bundle->toolchains folder, find the missing folder, copy the past
3. Recompile, the problem is solved.
Hope it helps you mate

**Comment by AndroidDeveloperLB** [comment]
@romainguy Seems "mips64el-linux-android" is missing because it got deprecated:
https://issuetracker.google.com/issues/112810603
https://issuetracker.google.com/issues/112779429

https://developer.android.com/ndk/guides/abis#sa

> Note: Historically the NDK supported 32-bit and 64-bit MIPS, but support was removed in NDK r17.

Please avoid using unsupported architectures.

@stark25795 The latest version doesn't have it, because of what I wrote above:
![image](https://user-images.githubusercontent.com/5357526/44530843-045b6980-a6f8-11e8-83cb-d144b4cd7c6c.png)

**Comment by AndroidDeveloperLB** [comment]
@romainguy So... please remove it from the sample too :)

**Comment by romainguy** [comment]
It's not in the samples.

**Comment by AndroidDeveloperLB** [comment]
So how did I get this error (look at first post) ?

**Comment by mimers** [comment]
@AndroidDeveloperLB  It seems like the old version of android gradle plugin(<3.3.+) was trying to access mips toolchain without checking if it exists. Upgrade the plugin version to 3.3-alpha may adopt to your r18-rc  NDK toolchains(as @banshee posted).

**Comment by kles4enko** [comment]
for me, upgrade the Android Gradle plugin version to 3.1.3+ works.

**Comment by AndroidDeveloperLB** [comment]
@chris118 What worked? Which sample worked for you?
I think I tried them all. What did you do?

**Comment by adrianodelvigna** [comment]
@AndroidDeveloperLB, I had the same problem with another project. I followed the instructions from [Android Plugin for Gradle release notes](https://developer.android.com/studio/releases/gradle-plugin); you may try to change your Project Structure settings as (check **bold** for the changes):

- Gradle version: **4.4**
- Android Plugin Version: **3.1.0**
- Android Plugin Repository: jcenter, **google()**
- Default Library Repository: jcenter

![image](https://user-images.githubusercontent.com/6507814/45751717-92d4e500-bbe9-11e8-8e91-ea30a7b90313.png)

I resync'ed Gradle then rebuilt the project successfully.

In time, here are my Android Studio details:

```
Android Studio 3.1.4
Build #AI-173.4907809, built on July 23, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.6
```

**Comment by AndroidDeveloperLB** [comment]
On which sample?
I tried now on "hello-triangle", "image-based-lighting", and "lit-cube" , and all show this error now:

`SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`

Thing is, it points to a correct place, so it should be fine...

![image](https://user-images.githubusercontent.com/5357526/45774055-aec1a080-bc54-11e8-9111-bb5f71be4c1d.png)

**Comment by romainguy** [comment]
@AndroidDeveloperLB You need a `local.properties` in `android/filament-android` too.

**Comment by AndroidDeveloperLB** [comment]
@romainguy It doesn't let me open the project as one with all 3 samples with `filament-android` , so I can't have it all :

![image](https://user-images.githubusercontent.com/5357526/45774586-04e31380-bc56-11e8-8096-098a187fcc29.png)

Also, I think the samples don't use this, no?

I now tried to open each of them separately, and it still doesn't help. Tells me "module not specified", but I can't even choose the module  :

![image](https://user-images.githubusercontent.com/5357526/45775673-2c87ab00-bc59-11e8-841f-972596a6db95.png)

**Comment by romainguy** [comment]
`filament-android` is a library required by each sample. Just copy your local.properties in `filament-android` then open a sample.

**Comment by AndroidDeveloperLB** [comment]
@romainguy Copy it? Copy it to where? 
As I've shown now, when I open the sample after I've opened the `filament-android`, it doesn't let me run anything, as it can't find the module to run. Look:

![image](https://user-images.githubusercontent.com/5357526/45776483-ade03d00-bc5b-11e8-9723-f98190ac41d0.png)

**Comment by romainguy** [comment]
Copy that file inside the filament-android directory.

**Comment by AndroidDeveloperLB** [comment]
Copy it to where?
The content seems fine on both projects.
It leads to a correct path.

**Comment by danielpunct** [comment]
Uninstalling the NDK worked for me ( had the problem from Unity )

**Comment by douglasdcc** [comment]
@stark25795 your solution was great. Thanks, buddy!

**Comment by cqllzp** [comment]
I solved this！miss mips64el-linux-android-4.9 mipsel-linux-android-4.9

**Comment by ktiniatros** [comment]
Btw you don't really need to find the actual mips64el-linux-android-4.9 mipsel-linux-android-4.9 contents. You can just create a folder with the same name and copy contents from another architecture.

**Comment by SrgGroot** [comment]
I've been working on getting this solved for a good few days now. I got it working on android after I broke it trying to use an npm package called 'react-native-splash-screen'. 

Upgrading my gradle version in the top-level project build gradle to version 3.1.3 solved the problem in my situation. I should mention that before I tried that, I deleted the android folder and rebuilt it because I kept getting some weird errors with 'react-native-firebase' that I had installed and uninstalled earlier.

**Comment by landon-hillyard** [comment]
I have been battling this error for a week now. Could you elaborate on how exactly you upgraded your gradle version. Pretty new in Android Studio so any extra clarity is much appreciated.

**Comment by SrgGroot** [comment]
@landon-hillyard I have tried so many things I can't even remember how I got it to work. 
Things I've tried:

- Delete android and node modules folder, run 'npm install' and 'react-native upgrade' to rebuild those folders.
- Go into 'Project Structure' (top right, folder icon with three blue squares) and then go to 'project' then put in your grade version and android plugin version.
- Check the top level build.gradle that the version is 3.1.3 like I said in my comment above yours.
- Check around in your other build.gradle and settings.gradle files to make sure you don't have any version conflicts.

This is a really weird bug and I'm by no means an expert. Took me three days to figure this one out. As I said before I'm working on a React Native project on iOS and Android. The reason why I had to mess with android studio at all was to add the splash screen and app icons. I also had some naming conflicts with 'rn-bridge', however, I want to keep things on topic for this thread.

**Comment by landon-hillyard** [comment]
@SrgGroot Thanks for your suggestions. Attached are the changes I made. No luck. Still have. 
"No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android"
![capture1](https://user-images.githubusercontent.com/43597100/46224622-b5fb4500-c30b-11e8-9fea-8df2815ee0c3.JPG)
![image](https://user-images.githubusercontent.com/43597100/46224681-e4792000-c30b-11e8-8d98-a918712111ae.png)
![image](https://user-images.githubusercontent.com/43597100/46224696-f35fd280-c30b-11e8-906f-eeb6bfeb0cff.png)
![image](https://user-images.githubusercontent.com/43597100/46224726-05417580-c30c-11e8-96fc-d5e18c0bb4ea.png)
![image](https://user-images.githubusercontent.com/43597100/46224777-24d89e00-c30c-11e8-910c-55be112d6c3e.png)
![image](https://user-images.githubusercontent.com/43597100/46224929-8d277f80-c30c-11e8-8aa1-d52e09497b89.png)

If there are any other suggestions or insights, any help is appreciated. 
Should I manually change the version in my build.gradle file?

**Comment by SrgGroot** [comment]
Yeah try that.

Did you delete and rebuild the android and node_modules directories?

**Comment by landon-hillyard** [comment]
Tried updating the classpath. Got this result. 
![image](https://user-images.githubusercontent.com/43597100/46225844-556e0700-c30f-11e8-9470-533fd6eb3246.png)
Sorry where are the android and node_modules directories? 
![image](https://user-images.githubusercontent.com/43597100/46225921-949c5800-c30f-11e8-94d6-398783e69134.png)

**Comment by landon-hillyard** [comment]
I think I figured it out. See below. 
![image](https://user-images.githubusercontent.com/43597100/46231393-9ae70000-c320-11e8-880a-b5d0ba7cf275.png)
Uncheck NDK. Then Apply. No longer get the missing NDK toolchains error. Now I am missing a library, but that is a separate issue.

**Comment by kjknair** [comment]
Update the android tools version in project-level `build.gradle`.

**Comment by friederbluemle** [comment]
This is a very annoying problem with an old version of the Android Gradle plugin that only surfaced recently due to mips support being removed from the Android SDK. As stated above, it has _nothing_ to do with the **filament** project.

Without downloading or copying anything, you can "fix" the error by simply creating an empty directory where the older version expects it:

    mkdir -p $ANDROID_HOME/ndk-bundle/toolchains/mips64el-linux-android/prebuilt/linux-x86_64

Obviously, `$ANDROID_HOME` points to the root of the Android SDK installation here. **If you are using MacOS**, replace `linux-x86_64` with `darwin-x86_64` in the command above. On Windows use `windows-x86_64`.

**Comment by fera10** [comment]
I am using Windows, and creating the empty folders fixed the problem.
Exactly I created the following directories: \mips64el-linux-android\prebuilt\windows-x86_64
Under my $ANDROID_HOME which in my case is C:\Users\myusername\AppData\Local\Android\sdk\ndk-bundle\toolchains\
I run the application again and this time no more errors.
Thanks for the help

**Comment by CharlesStover** [comment]
For those of you using stark's solution of downloading an older NDK and merging the two versions, the one you will need is **16c**.

**Comment by MNGsulochana** [comment]
Try to update the studio..If u r trying to upload old project then update the gradle as manually to the latest

**Comment by yrizk** [comment]
tried what @MNGsulochana said and yeah AS version 3.2 is working

**Comment by petru-sabadac** [comment]
Linux & Mac
`cd  ~/Library/Android/sdk/ndk-bundle/toolchains

ln -s aarch64-linux-android-4.9 mips64el-linux-android

ln -s arm-linux-androideabi-4.9 mipsel-linux-android`

**Comment by Dborah** [comment]
This worked for me. Thanks @petru-sabadac :)

**Comment by angeloraso** [comment]
@friederbluemle this works for me. Thanks!

**Comment by duyhungws** [comment]
This worked for me. Thanks @petru-sabadac

**Comment by RichieDevereux** [comment]
### I had the same problem with a tutorial from Codelabs..

[https://codelabs.developers.google.com/codelabs/constraint-layout/index.html?index=..%2F..%2Fio2018#0](url)

When I imported the project to Android Studio 3.14 & 3.2
I got..."No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el

Tried lots of ways and found the easy way.
Just uninstall NDK tools  from SDK tools. Uncheck and click ok
Sync project with Gradle files.
It will then bring up update box to update Gradle..update.
Wait to update.
Done.
I actually got this answer from a Chinese site, thankfully Google does great translation.

**Comment by tomalsg** [comment]
@petru-sabadac this works for me. Thanks!

**Comment by livepk** [comment]
If you Found error 👍 
No toolchains found in the NDK toolchains folder for ABI with prefix: mipsel-linux-android

Then go to gradle-wrapper.properties and change distibutionUrl to letest gradel 
i change
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip 
to
distributionUrl=https\://services.gradle.org/distributions/gradle-4.9-all.zip

**Comment by shoarma** [comment]
i think i fixed the problem. i just went to the website to download the ndk and clicked download older version.
![ndk old version](https://user-images.githubusercontent.com/44223362/47067678-72994580-d1ea-11e8-89e0-8d60ecc8eaad.PNG)

and i pressed the second download on there (december 2017)
![ndk old downlaod](https://user-images.githubusercontent.com/44223362/47067785-c310a300-d1ea-11e8-916b-585e39a8580b.PNG)

in that download are the mipsel and mip64el folders you want.

after you copied them in your android studio folder i did a gradle sync and the errors went away, after that android studio will ask you to update somthing (in my case) DON'T UPDATE THAT!!! i did it and now i'm stuck with other errors

**Comment by friederbluemle** [comment]
@shoarma You might have missed the message I posted above - there is no need to download or install anything!

**Comment by rkatos** [comment]
Thanks to all who worked this out! Adding the empty mips architecture files worked for m.

**Comment by linguyen** [comment]
Thank you! It works finally. Adding empty files as @friederbluemle mentioned.

**Comment by vovan4ik123** [comment]
Conversation with authot of SDL2:
I:
Hello.
I try use it for android.
And SDL require mips64el-linux-android and mipsel-linux-android   from NDK.
But NDK now have not this file.
From NDK developers:
Note: Historically the NDK supported 32-bit and 64-bit MIPS, but support was removed in NDK r17.
Can you update your source code for android?
Bye.

Sam Lantinga :
Yes, this is fixed for the 2.0.9 release, which will hopefully happen on Monday or Tuesday.

**Comment by Tellemioy** [comment]
> 
> 
> I just wanted to try out the sample, but I got this error:
> 
> ![image](https://user-images.githubusercontent.com/5357526/43690580-fb8bd51a-9914-11e8-8ce2-7793deb30d5d.png)



> 
> ### I had the same problem with a tutorial from Codelabs..
> 
> [https://codelabs.developers.google.com/codelabs/constraint-layout/index.html?index=..%2F..%2Fio2018#0](url)
> 
> When I imported the project to Android Studio 3.14 & 3.2
> I got..."No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el
> 
> Tried lots of ways and found the easy way.
> Just uninstall NDK tools from SDK tools. Uncheck and click ok
> Sync project with Gradle files.
> It will then bring up update box to update Gradle..update.
> Wait to update.
> Done.
> I actually got this answer from a Chinese site, thankfully Google does great translation.

This is the solution guys it just helped me out thanks man.

**Comment by RichieDevereux** [comment]
> This is the solution guys it just helped me out thanks man.@RichieDevereux
I tried lots of peoples answers and ended up sorting it myself after long searching.
Frustrating when you are doing tutorials. I've had a few problems with Codelabs tuts and find a solution somehow. I will don't think I will ever need the NDK so it's gone.
Good you sorted it out.

**Comment by loulansuiye** [comment]
> Is it possible that it's because I'm using Windows OS?
> Or that I have AMD CPU ?

even though I compile it on ubuntu 1604 ,it still report that problem!

**Comment by smiron** [comment]
> @romainguy You are correct. I was sure it's just NDK that's needed. Seems it's a lot more.
> Closing this as I don't have time for this. Sorry.
> Thank you for the good work.

Worst argument I have ever seen to close an issue

**Comment by romainguy** [comment]
This comment was from the original reporter. Also note that most of the comments here have nothing to do with this project.

**Comment by AndroidDeveloperLB** [comment]
> I am using Windows, and creating the empty folders fixed the problem.
> Exactly I created the following directories: \mips64el-linux-android\prebuilt\windows-x86_64
> Under my $ANDROID_HOME which in my case is C:\Users\myusername\AppData\Local\Android\sdk\ndk-bundle\toolchains
> I run the application again and this time no more errors.
> Thanks for the help

I still got an issue with this. It says:

```
* What went wrong:
A problem occurred configuring project ':filament-android'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```
However, all folders are actually positioned fine:

![image](https://user-images.githubusercontent.com/5357526/48287239-e25cc200-e470-11e8-84c9-1320595d50cc.png)

**Comment by kjanard** [comment]
If your old project didn't use NDK, just remove it from Android SDK Manager and reopen your project again. It work for me.

**Comment by AndroidDeveloperLB** [comment]
@kjanard Which old project? I just cloned the repository here, and wanted to try out one of the samples (the triangle in this case).
And what do you mean by "remove it" ? Wouldn't this mean I won't be able to build C/C++ code in all projects?

**Comment by kjanard** [comment]
Sorry, my mistake. I didn't read an issue carefully and clearly. Your post just popped up when I search about non-ndk project.

**Comment by kjanard** [comment]
@AndroidDeveloperLB Sorry, my mistake. I didn't read an issue carefully and clearly. Your post just popped up when I search about non-ndk project.

**Comment by chrisws** [comment]
I encountered this issue with generated project files from cocos2dx.

Here's what worked for me
1. Change this in build.gradle:
from:
    classpath 'com.android.tools.build:gradle:3.0.0'
to:
    classpath 'com.android.tools.build:gradle:3.2.1'

2. Overwriting gradle* from another working project

**Comment by tomeroto** [comment]
> Linux & Mac
> **cd ~/Library/Android/sdk/ndk-bundle/toolchains ln -s aarch64-linux-android-4.9 mips64el-linux-android ln -s arm-linux-androideabi-4.9 mipsel-linux-android**

its worked! thanks

**Comment by jwu92610** [comment]
Thanks @petru-sabadac :)  It worked for me with similar steps in Windows 10 as follows.

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 8, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Right click the "Start Icon" of Windows 10 and select "Command Prompt (Admin)", and then

mklink /D mips64el-linux-android aarch64-linux-android-4.9
mklink /D mipsel-linux-android arm-linux-androideabi-4.9

**Comment by newlighty** [comment]
hi remove ndk  show the sdk folder for this project and i put commit for
this that work for me try it out and let me know if it works

**Comment by prvinuch** [comment]
I just unchecked the NDK from SDK Tools and it worked for me...  I think there is no need yet for NDK.

**Comment by RichieDevereux** [comment]
> I just unchecked the NDK from SDK Tools and it worked for me... I think there is no need yet for NDK.

there is if you design games.

**Comment by pundirbhupendra** [comment]
i face same problem then i upgrade gradle version 3.0.1 to  classpath 'com.android.tools.build:gradle:3.2.1' it work for me..

**Comment by friederbluemle** [comment]
This thread just keeps growing and growing and the issue is completely unrelated to the project it's in. There are obviously multiple solutions to get rid of the error, but there is one fix that does **not involve downloading or copying anything** that can be seen by scrolling up to https://github.com/google/filament/issues/15#issuecomment-426259512

I wish there was a way to "pin" a comment and/or prevent people from commenting "me too"... Maybe this thread should be closed with a final conclusion?

**Comment by Xardas365** [comment]
i haved the same problem in cordova.

You need to edit the gradle version to the latest in this files.

`platforms/android/app/build.gradle
platforms/android/cordova/lib/builders/GradleBuilder.js
platforms/android/cordova/lib/builders/StudioBuilder.js`

In build.gradle find this part of the code.
`task wrapper(type: Wrapper) {
    gradleVersion = '4.10.2'
}`

In GradleBuilder.js find this part of the code.
`var distributionUrl = process.env['CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL'] || 'https\\://services.gradle.org/distributions/gradle-4.10.2-all.zip';`

In StudioBuilder.js find this part of the code.
`var distributionUrl = process.env['CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL'] || 'https\\://services.gradle.org/distributions/gradle-4.10.2-all.zip';`



Source: https://stackoverflow.com/questions/49321000/minimum-supported-gradle-version-is-4-1-current-version-is-3-3/52967069#52967069

**Comment by AleksandrHovhannisyan** [comment]
Nothing here worked for me, but here are the steps I followed to fix it on my end (while trying to build the [SimpleCalc project](https://codelabs.developers.google.com/codelabs/android-training-using-debugger/index.html?index=..%2F..%2Fandroid-training#2) from Codelabs):

1. Tap the Shift key twice, click **Include non-project items**, type "SDK", and scroll until you find **SDK Manager**. Click it.
2. Go to the **SDK Tools** tab.
3. Uncheck **NDK** and click **Apply**.
4. Exit the SDK Manager when this is finished.
5. Expand the **Gradle Scripts** directory of your project.
6. Double-click on **build.gradle** to open a script that's executed to sync your project.
7. Make sure your `classpath` is defined as follows: `classpath 'com.android.tools.build:gradle:3.2.1'` (or, if 3.2.1 is not the latest Gradle version when you're reading this, replace it accordingly).
8. Find the `repositories` section of the script under `buildscript`, and make sure you add `google()` on a new line within the curly braces, if it does not already exist.
9. Go to **File > Sync Project with Gradle Files**.

Then, **Build > Make Project**. If all went well, this should work for you.

**Comment by rogerkamal** [comment]
I'm still facing same issue since a long time.
Please Help. I've tried every solution above.
It still showing "No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android"

**Comment by simonkuang** [comment]
Notice the file `android-ndk-r17-beta2/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/NOTICE-MIPS64`. The content of the file is below.

> This mips64el-linux-android-4.9 directory exists to make the NDK compatible with the Android
SDK's Gradle plugin, version 3.0.1 and earlier, which expects the NDK
to have a MIPS64 toolchain directory.

So, i can say, using Android SDK's Gradle plugin above 3.0.1, or create even a directory marked with 'mipsel' and 'mips64el', can both resolve the problem. The latter method is below.

```bash
cd <path-to-ndk>

OS_=$(uname -s | tr [A-Z] [a-z])
mkdir -p toolchains/mipsel-linux-android-4.9/prebuilt/${OS_}-x86_64
touch toolchains/mipsel-linux-android-4.9/prebuilt/${OS_}-x86_64/NOTICE-MIPS
mkdir -p toolchains/mips64el-linux-android-4.9/prebuilt/${OS_}-x86_64
touch toolchains/mips64el-linux-android-4.9/prebuilt/${OS_}-x86_64/NOTICE-MIPS64
```
