### ISSUE TITLE
UberShader can't render doubleSided model

### ISSUE THREAD

**Issue by Yzou-NaO** [google/filament#1512]
**Describe the bug**
UberShader can't render doubleSided model.
[Two Sided Plane](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TwoSidedPlane)

**Screenshots**
![image](https://user-images.githubusercontent.com/39986511/62921496-7a5e5200-bddb-11e9-96de-cd68622c3e7c.png)

![image](https://user-images.githubusercontent.com/39986511/62921430-484cf000-bddb-11e9-9bd1-e1581c67e3ac.png)

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by prideout** [comment]
Thanks for the report, I'll look into it.

**Comment by Yzou-NaO** [comment]
I think KHR_materials_pbrSpecularGlossiness can't be rendered as well.
![image](https://user-images.githubusercontent.com/39986511/62993189-f498e000-be88-11e9-936c-ac535610373c.png)
test model: [SpecGlossVsMetalRough](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough)

**Comment by prideout** [comment]
Thanks.  MaterialGenerator mode is more feature complete than UbershaderLoader right now, but we can fix this up.

**Comment by prideout** [comment]
Fixed by #1568
