### ISSUE TITLE
Support for negative scale values in transform

### ISSUE THREAD

**Issue by flyingonly** [google/filament#1520]
We have met problems with rendering gltf files when we have negative scale values in it or we set negative scale values with TransformManager. It appears to be caused by the triangle faces aren't reversed.
So will it be supported that the winding order of the mesh triangle faces to be reversed when the determinant of the transform is a negative value?

**Comment by prideout** [comment]
I don't quite understand.  Is this an issue with lighting or with backface culling?

**Comment by flyingonly** [comment]
Sorry for not making it clear. And I think the issue is about the surface orientation. 
The origin gltf file shows like this:
![image](https://user-images.githubusercontent.com/9585829/63067635-76990f80-bf42-11e9-94d3-fd6550b17381.png)
Then I set the scale of the node to -1, 1, 1, It appears to be:
![image](https://user-images.githubusercontent.com/9585829/63067651-8e709380-bf42-11e9-9952-1009bf14bd51.png)
I think this is caused by backface culling and set the material to double sided true and it turns out to be:
![image](https://user-images.githubusercontent.com/9585829/63067678-ac3df880-bf42-11e9-8fb5-969a62bc917f.png)
And it should be exactly flip in x-axis with the origin, but the result is not simply mirrored. It appears to be that the inside face of the object comes out with the negative scale.
In the document of the gltf 2.0 there is the following description:
![image](https://user-images.githubusercontent.com/9585829/63067832-70576300-bf43-11e9-947d-c422526e55f7.png)
Is this explanation clearer for you?

**Comment by prideout** [comment]
Thanks, I understand now.  This is not part of the core spec, nor tested in any conformance models (AFAIK), but we might be able to support it.  Out of curiosity have you tried this with other engines?

**Comment by flyingonly** [comment]
I have tested the negative scale in visual code gltf preview. The Babylon.js and Three.js can handle the value correctly, while the cesium has the same problem I showed above.

**Comment by flyingonly** [comment]
Btw, I have found that View has a function setFrontFaceWindingInverted, which can partly solve this problem. I just need to decide whether the determinate of the transform matrix is negative, then modify the setting with this. However changing this will affect all items in the view, will it be a method to limit the affect to only the instance with the transformation which needs the reversed winding order.
