### ISSUE TITLE
add Java bindings for gltfio::Animator

### ISSUE THREAD

**Issue by atul109** [google/filament#1529]
I couldn't find any coding documentation or samples to list or play animations of a .glb file.
`getAnimationCount()`  is missing in FilamentAsset
Build using the gltfio-20190808-android.aar and filament-20190808-android.aar but
[gltfio android](https://github.com/google/filament/tree/master/android/gltfio-android/src/main/java/com/google/android/filament/gltfio) does not contain Animator

Does filament support raycast as in Sceneform to select and scale multiple models?

**Comment by prideout** [comment]
The C++ layer has an "Animator" object which is used by our gltf_viewer sample.  However it looks like we have not yet provided JNI bindings for that, I'll fix that.

No, Filament does not support picking.
