### ISSUE TITLE
Shader : how can use atan2 function?

### ISSUE THREAD

**Issue by Realitian** [google/filament#1531]
In Material's fragment shader, I failed to compile when I use atan2 function.
Can you let me know any reference for the list of available shader functions?
Cheers.

**Comment by romainguy** [comment]
You can use any function provided by OpenGL ES 3.0. See https://www.khronos.org/registry/OpenGL-Refpages/es3.0/ or https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf

**Comment by prideout** [comment]
Also note that GLSL provides a two-argument overload for the `atan` function, which is equivalent to atan2.

**Comment by Realitian** [comment]
Thanks!

**Comment by timi-liuliang** [comment]
[ATan2](https://github.com/timi-liuliang/echo/blob/master/engine/core/render/base/editor/shader/node/math/shader_node_atan2.cpp)
```glsl
float ATan2(vec2 dir)
{
	float angle = asin(dir.x) > 0 ? acos(dir.y) : -acos(dir.y);
	return angle;
}
```
Here are the [tests](https://github.com/timi-liuliang/echo/blob/master/tests/unittest/math/ATan2Test.cpp)
