### ISSUE TITLE
crash on create rendertarget on android

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1533]
**Describe the bug**
crash on creating render target on some huawei android device. the log below

Filament: OpenGL framebuffer error 0x8cd6 (GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT) in "void filament::OpenGLDriver::framebufferTexture(const backend::TargetBufferInfo &, const filament::OpenGLDriver::GLRenderTarget *, GLenum)" at line 1216
libc++abi: terminating

our code below:
color = Texture.Builder()
                    .width(width)
                    .height(height)
                    .levels(1)
                    .usage(Texture.Usage.COLOR_ATTACHMENT or Texture.Usage.SAMPLEABLE)
                    .format(Texture.InternalFormat.RGBA16F)
                    .build(engine)
            view.isPostProcessingEnabled = true
            if ( hasDepth){
                val depthbit:Texture.InternalFormat
                if ( depthBufferBits == 32){
                    depthbit = Texture.InternalFormat.DEPTH32F
                }
                else if ( depthBufferBits == 24){
                    depthbit = Texture.InternalFormat.DEPTH24
                }
                else{
                    depthbit = Texture.InternalFormat.DEPTH16
                }
                depth = Texture.Builder()
                        .width(width).height(height).levels(1)
                        .usage(Texture.Usage.DEPTH_ATTACHMENT)
                        .format(depthbit)
                        .build(engine)
               view.renderTarget = RenderTarget.Builder()
                       .texture(RenderTarget.AttachmentPoint.COLOR, color)
                       .texture(RenderTarget.AttachmentPoint.DEPTH, depth)
                       .build(engine)
                view.antiAliasing = View.AntiAliasing.FXAA
                view.sampleCount = 4
                view.toneMapping = View.ToneMapping.ACES

            }
            else{
                view.toneMapping = View.ToneMapping.ACES

                depth = null
               view.sampleCount = 1;
               view.renderTarget = RenderTarget.Builder()
                       .texture(RenderTarget.AttachmentPoint.COLOR, color)
                       .build(engine)

           }

**Comment by geroge-d** [comment]
FYI 
 I built a debug version for testing this issue. =
Device:
  CRASH DEVICE: HUAWEI CRR-UL00 UNROOT
Opengles version 3.1

**Comment by geroge-d** [comment]
Run the sample gltf-bloom crashed on the same device

**Comment by romainguy** [comment]
Which version of Filament are you using?

**Comment by geroge-d** [comment]
it occur in  1.30,1.31

**Comment by geroge-d** [comment]
detailed gpu information:
I/Filament: ARM
    Mali-T624
    OpenGL ES 3.1 v1.r8p0-01dev0.4078cee201ea91f87ad24a89593523d2
    OpenGL ES GLSL ES 3.10
    OS version: 23
    GL_MAX_RENDERBUFFER_SIZE = 8192
    GL_MAX_UNIFORM_BLOCK_SIZE = 16384
    GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 16

**Comment by geroge-d** [comment]
We did some tests,found that it may be caused by not unbinding framebuffer to system,like  bindFramebuffer(GL_FRAMEBUFFER, 0);

**Comment by geroge-d** [comment]
hi guys!
  Any progress on this issue ? Because our app get stuck because of this issue, so any hint to fix this issue is much appreciated

**Comment by geroge-d** [comment]
you guys can find similar test device on this cloudtest site:   http://www.testin.net/

**Comment by geroge-d** [comment]
we found the issue caused by wrong width ,but don't how to fix, you guys can see the attachmen ,that show different width and height between createRenderTargetS and createRenderTargetR
![1](https://user-images.githubusercontent.com/53041249/64097724-95e3c980-cd97-11e9-936b-5b9a8cf51789.png)
![2](https://user-images.githubusercontent.com/53041249/64097731-9bd9aa80-cd97-11e9-98a4-caa101d46d25.png)

**Comment by geroge-d** [comment]
any suggestion to fix or do unit test for specific device is much appreciated. because we cannot  release our app until this issue is fixed

**Comment by geroge-d** [comment]
filament use a lot complex c++11 template tricks , so it is difficult to fix this issue for us not familiar with c++11 template. so please give us some clues ,thanks in advance

**Comment by geroge-d** [comment]
We already positioned this issue.  it is very strange behavior.
First image is the stacktrace of createRenderTargetR
![1](https://user-images.githubusercontent.com/53041249/64104963-e06d4200-cda7-11e9-9096-ba937bbf103c.png)
Secode image is during the function trampoline. all the parameters are correct
![2](https://user-images.githubusercontent.com/53041249/64105068-14e0fe00-cda8-11e9-9edb-de6f4c02bed5.png)
Third image is during createRenderTargetR, all the parameters are wrong!
![3](https://user-images.githubusercontent.com/53041249/64105139-32ae6300-cda8-11e9-940e-c6b603cdec0c.png)

**Comment by geroge-d** [comment]
it may be caused by the parameter of  enum type  . we 'are doing testing, if any progress, i'll update

**Comment by geroge-d** [comment]
hi @prideout 
Float rendering support is mandatory in OpenGL ES 3.2. It is not required for OpenGL ES 3.0 / 3.1 / 3.1 + AEP.
 Based our test, this isusse is caused by device not support float texture.

**Comment by prideout** [comment]
Nice find!  The bloom demo requires support for RGBA16F but Filament itself does not.  Therefore this is not a Filament issue, correct?

**Comment by romainguy** [comment]
RGBA16F is our default render target format.

**Comment by prideout** [comment]
Ah right, and to further refresh my memory, ES 3.0 requires support for RGBA16F / RGB16F / R11F_G11F_B10F as *textures* but does support them as render targets, which is why we check for `EXT_color_buffer_half_float`.

**Comment by geroge-d** [comment]
Filament use RGBA16F  as render target , despite  tested device is not support EXT_color_buffer_half_float

I print the logs of extension state:
 E/Filament: EXT_color_buffer_half_float:0

**Comment by geroge-d** [comment]
I just fixed it by this way, but i don't know whether this fix has any side-effects or not? Could you please review this following codes ?
First step:  change OpenGLDriver::isRenderTargetFormatSupported
Second step: change FRenderer::getHdrFormat

`bool OpenGLDriver::isRenderTargetFormatSupported(TextureFormat format) {
    switch (format) {
         ....
        // Half-float formats, requires extension.
        case TextureFormat::RGB16F:
            return ext.EXT_color_buffer_half_float;

        // Float formats from GL_EXT_color_buffer_float, assumed supported.
        case TextureFormat::R16F:
        case TextureFormat::RG16F:
        case TextureFormat::RGBA16F:
        case TextureFormat::R32F:
        case TextureFormat::RG32F:
        case TextureFormat::RGBA32F:
        case TextureFormat::R11F_G11F_B10F:
            return ext.EXT_color_buffer_half_float;

        default:
            return false;
    }
}`

`backend::TextureFormat FRenderer::getHdrFormat(const View& view) const noexcept {
    const bool translucent = mSwapChain->isTransparent();
    if (translucent)  return !mIsRGB16FSupported ? backend::TextureFormat::RGBA8
                                                 : backend::TextureFormat::RGBA16F;

    switch (view.getRenderQuality().hdrColorBuffer) {
        case View::QualityLevel::LOW:
        case View::QualityLevel::MEDIUM:
            return backend::TextureFormat::R11F_G11F_B10F;
        case View::QualityLevel::HIGH:
        case View::QualityLevel::ULTRA:
            return !mIsRGB16FSupported ? backend::TextureFormat::RGBA8
                                       : backend::TextureFormat::RGBA16F;
    }
}`

**Comment by romainguy** [comment]
The same would have to be done for the low/medium quality setting. This will also clip HDR values so tone mapping should probably be disabled.

**Comment by pixelflinger** [comment]
As far as I understand the Khronos extensions:
- `GL_EXT_color_buffer_float` requires ES3.0 and adds support for rendering into *all* `RGBA` float formats, 16-bits and 32-bits. However, `RGB32F` and `RGB16F` are still texture only. Strangely `RGB_11_11_10` is supported.
- `GL_EXT_color_buffer_half_float` is an ES2.0 extension and gives rendering access to half-float formats. This extension says nothing about `RGB_11_11_10`.

@geroge-d could you check if your drivers have the following extensions:
- `GL_EXT_color_buffer_float`
- `GL_APPLE_color_buffer_packed_float`
- `GL_NV_packed_float `

Could you also check wether using `backend::TextureFormat::R11F_G11F_B10F` works?

**Comment by geroge-d** [comment]
I think Filament should export a method to java render object,so that java app can check whether this format as render target is supported by Filament

**Comment by romainguy** [comment]
It's not needed anymore, we'll automatically pick a supported format.
