### ISSUE TITLE
iOS AR example viewMatrix

### ISSUE THREAD

**Issue by Realitian** [google/filament#1534]
Hi, @bejado
Thanks for adding iOS AR example.
btw, how can make it work in portrait mode?
Actually, I tried to run it in portrait mode (my all UI made in portrait mode), but example was landscape right mode.
I couldn't setup the matrix in portrait mode.
I tried to change camera.transform with [camera viewMatrixForOrientation:UIInterfaceOrientationPortrait], but the object wasn't be stable.
Can you give me any idea?
Thank in advance!

**Comment by bejado** [comment]
Hey @Realitian, yes this is definitely possible.

To start, you'll need to switch to portrait mode orientation in the project settings:

![Screen Shot 2019-08-20 at 11 29 40 AM](https://user-images.githubusercontent.com/5298046/63374051-e55cdb00-c33d-11e9-89bf-9781154555aa.png)

Then inside of `session:didUpdateFrame:`:

1. Flip the width and height when constructing the viewport:

```
-    CGSize viewport = CGSizeMake(nativeBounds.size.height, nativeBounds.size.width);
+    CGSize viewport = CGSizeMake(nativeBounds.size.width, nativeBounds.size.height);
```

2. Replace `UIInterfaceOrientationLandscapeRight` with `UIInterfaceOrientationPortrait`:

```
-            [frame displayTransformForOrientation:UIInterfaceOrientationLandscapeRight
+            [frame displayTransformForOrientation:UIInterfaceOrientationPortrait
```

```
-            [frame.camera projectionMatrixForOrientation:UIInterfaceOrientationLandscapeRight
+            [frame.camera projectionMatrixForOrientation:UIInterfaceOrientationPortrait
```

3. The tricky part is the view matrix. We need to take the inverse of the one given to us by `viewMatrixForOrientation`. The inverse of the view matrix is the camera transformation matrix, which is what we pass to Filament:

```
+    auto viewMatrix = [frame.camera viewMatrixForOrientation:UIInterfaceOrientationPortrait];
+    auto cameraTransformMatrix = simd_inverse(viewMatrix);
+
     // frame.camera.transform gives a camera transform matrix assuming a landscape-right orientation.
     // For simplicity, the app's orientation is locked to UIInterfaceOrientationLandscapeRight.
     app->render(FilamentApp::FilamentArFrame {
         .cameraImage = (void*) frame.capturedImage,
         .cameraTextureTransform = textureTransform,
         .projection = FILAMENT_MAT4_FROM_SIMD(projection),
-        .view = FILAMENT_MAT4F_FROM_SIMD(frame.camera.transform)
+        .view = FILAMENT_MAT4F_FROM_SIMD(cameraTransformMatrix)
     });
```

Let me know if that works for you!

**Comment by Realitian** [comment]
yes, it works!!!
Thanks a lot.

**Comment by JoJoBiscuit** [comment]
> Hey @Realitian, yes this is definitely possible.
> 
> To start, you'll need to switch to portrait mode orientation in the project settings:
> 
> ![Screen Shot 2019-08-20 at 11 29 40 AM](https://user-images.githubusercontent.com/5298046/63374051-e55cdb00-c33d-11e9-89bf-9781154555aa.png)
> 
> Then inside of `session:didUpdateFrame:`:
> 
> 1. Flip the width and height when constructing the viewport:
> 
> ```
> -    CGSize viewport = CGSizeMake(nativeBounds.size.height, nativeBounds.size.width);
> +    CGSize viewport = CGSizeMake(nativeBounds.size.width, nativeBounds.size.height);
> ```
> 
> 1. Replace `UIInterfaceOrientationLandscapeRight` with `UIInterfaceOrientationPortrait`:
> 
> ```
> -            [frame displayTransformForOrientation:UIInterfaceOrientationLandscapeRight
> +            [frame displayTransformForOrientation:UIInterfaceOrientationPortrait
> ```
> 
> ```
> -            [frame.camera projectionMatrixForOrientation:UIInterfaceOrientationLandscapeRight
> +            [frame.camera projectionMatrixForOrientation:UIInterfaceOrientationPortrait
> ```
> 
> 1. The tricky part is the view matrix. We need to take the inverse of the one given to us by `viewMatrixForOrientation`. The inverse of the view matrix is the camera transformation matrix, which is what we pass to Filament:
> 
> ```
> +    auto viewMatrix = [frame.camera viewMatrixForOrientation:UIInterfaceOrientationPortrait];
> +    auto cameraTransformMatrix = simd_inverse(viewMatrix);
> +
>      // frame.camera.transform gives a camera transform matrix assuming a landscape-right orientation.
>      // For simplicity, the app's orientation is locked to UIInterfaceOrientationLandscapeRight.
>      app->render(FilamentApp::FilamentArFrame {
>          .cameraImage = (void*) frame.capturedImage,
>          .cameraTextureTransform = textureTransform,
>          .projection = FILAMENT_MAT4_FROM_SIMD(projection),
> -        .view = FILAMENT_MAT4F_FROM_SIMD(frame.camera.transform)
> +        .view = FILAMENT_MAT4F_FROM_SIMD(cameraTransformMatrix)
>      });
> ```
> 
> Let me know if that works for you!



> Hey @Realitian, yes this is definitely possible.
> 
> To start, you'll need to switch to portrait mode orientation in the project settings:
> 
> ![Screen Shot 2019-08-20 at 11 29 40 AM](https://user-images.githubusercontent.com/5298046/63374051-e55cdb00-c33d-11e9-89bf-9781154555aa.png)
> 
> Then inside of `session:didUpdateFrame:`:
> 
> 1. Flip the width and height when constructing the viewport:
> 
> ```
> -    CGSize viewport = CGSizeMake(nativeBounds.size.height, nativeBounds.size.width);
> +    CGSize viewport = CGSizeMake(nativeBounds.size.width, nativeBounds.size.height);
> ```
> 
> 1. Replace `UIInterfaceOrientationLandscapeRight` with `UIInterfaceOrientationPortrait`:
> 
> ```
> -            [frame displayTransformForOrientation:UIInterfaceOrientationLandscapeRight
> +            [frame displayTransformForOrientation:UIInterfaceOrientationPortrait
> ```
> 
> ```
> -            [frame.camera projectionMatrixForOrientation:UIInterfaceOrientationLandscapeRight
> +            [frame.camera projectionMatrixForOrientation:UIInterfaceOrientationPortrait
> ```
> 
> 1. The tricky part is the view matrix. We need to take the inverse of the one given to us by `viewMatrixForOrientation`. The inverse of the view matrix is the camera transformation matrix, which is what we pass to Filament:
> 
> ```
> +    auto viewMatrix = [frame.camera viewMatrixForOrientation:UIInterfaceOrientationPortrait];
> +    auto cameraTransformMatrix = simd_inverse(viewMatrix);
> +
>      // frame.camera.transform gives a camera transform matrix assuming a landscape-right orientation.
>      // For simplicity, the app's orientation is locked to UIInterfaceOrientationLandscapeRight.
>      app->render(FilamentApp::FilamentArFrame {
>          .cameraImage = (void*) frame.capturedImage,
>          .cameraTextureTransform = textureTransform,
>          .projection = FILAMENT_MAT4_FROM_SIMD(projection),
> -        .view = FILAMENT_MAT4F_FROM_SIMD(frame.camera.transform)
> +        .view = FILAMENT_MAT4F_FROM_SIMD(cameraTransformMatrix)
>      });
> ```
> 
> Let me know if that works for you!

Thanks a lot.

**Comment by noseeevil** [comment]
@bejado

Thanks a lot!
