### ISSUE TITLE
Setting position using x, y, z and rotation using Quaternion and Euler angle

### ISSUE THREAD

**Issue by atul109** [google/filament#1535]
When trying to set position and rotation using rotation matrix obtained from OpenCV, there is unexpected sudden changes orientation (usually when rotation matrix values flip signs)

As per my observation the transform matrix used in filament have translation as 4th row
                        1.0f,  0.0f, 0.0f, 0.0f,
                        0.0f,  1.0f, 0.0f, 0.0f,
                        0.0f,  0.0f, 1.0f, 0.0f,
                         x,       y,      z,    1.0f

Some other libraries have translation as fourth column
                        1.0f,  0.0f, 0.0f,  x,
                        0.0f,  1.0f, 0.0f,  y,
                        0.0f,  0.0f, 1.0f,  z,
                        0.0f,  0.0f, 0.0f,  1.0f

Requesting feature to set rotation as Quaternion or Euler angles, and position as x, y, z.
 It is a lot easier than using matrices, is there any other way to set the orientation and position of an entity?

**Comment by romainguy** [comment]
Filament uses column major matrices, not row major matrices. Which means the 4th column is the translation.. Our matrix API provides several utility functions to create matrices from Euler angles, quaternions, etc. I recommend you use those (for instance `mat4::rotation(angle, rotationAxis)` or `mat4(myQuaternion)`).

**Comment by atul109** [comment]
This is from gltf-bloom sample of android to rotate model,  modified fourth row's first value to get translation in x direction and similar results for y and z.       
```
 tm.setTransform(tm.getInstance(filamentAsset.root),
                    floatArrayOf(
                            cos(v),  0.0f,    -sin(v),    0.0f,
                            0.0f,      1.0f,     0.0f     0.0f,
                            sin(v),   0.0f,    cos(v),    0.0f,
                            v,        -1.7f,     0.0f,    1.0f
                    ))
```
Where as if you change the fourth column it is resulting in scale change in respective axis.
![SmartSelect_20190821-105120_gltf bloom](https://user-images.githubusercontent.com/16425237/63405396-4e0e8b00-c404-11e9-95a0-14830c914ca0.gif)

**Comment by romainguy** [comment]
You are mistaking the ASCII column for the in-memory column. Filament expects matrices in column-major order, so when you pass a matrix by writing `floatArrayOf(a, b, c, d...)` the values a, b, c and d are those of the first column, not the first row. If you are using Filament from Kotlin you could try to use the math library I wrote: https://github.com/romainguy/kotlin-math They'll give you the features you want and it uses column major order as well.
