### ISSUE TITLE
Not able to migration filament with ARcore?

### ISSUE THREAD

**Issue by Realitian** [google/filament#1551]
Hi,
I tried to use filament as a rendering middleware for arcore.
But, I failed due to I can't create filament engine with GLSurfaceView.
I know as arcore session runs on GLSurfaceView, but the filament engine run on SurfaceView.
Unfortunate exclusively, the arcore don't allow creation in SurfaceView, and filament don't allow creation in GLSurfaceView.
because I have customized 3d rendering framework upon filament in c++, so I want to use it in android ar applications.
I need to run filament and arcore in native c++, but how I can run both successfully?
Thank you in advance for let me know the way.
Cheers!

**Comment by romainguy** [comment]
GLSurfaceView is a SurfaceView. What APIs in ARCore need a GLSurfaceView? The ARCore session doesn't require a GLSurfaceView. It's definitely possible to use both since Sceneform is built on top of ARCore + Filament.

**Comment by Realitian** [comment]
I created arcore session and called update in SurfaceView, and I got following log.

ArStatusErrorSpace::AR_ERROR_MISSING_GL_CONTEXT:  at third_party/arcore/ar/core/session.cc:915

I tried to call arcore session.update as following code snippet.
...
Choreographer.FrameCallback {
        override fun doFrame(frameTimeNanos: Long) {

            val frame = session!!.update()
}
...

**Comment by romainguy** [comment]
You probably need a GL context for ARCore to produce camera frames into, but you don't need a GLSurfaceView for that. The texture name you use with ARCore can be shared with Filament (you'll need to share your GL context with Filament).

We should write an ARCore test app that shows how to do all this.

@bendoherty @prideout
