### ISSUE TITLE
Shader skinned position error

### ISSUE THREAD

**Issue by iamjinge** [google/filament#1552]
In [getter.vs](https://github.com/google/filament/blob/876534330af9b4ebb35b9ae9045dbb2d15629892/shaders/src/getters.vs#L36). When I scale a bone node in only y dimension, the model will render as a wrong shape, which is different from the output of Unity.

1. origin code. Output is wrong.
```glsl
vec3 mulBoneVertex(vec3 v, uint i) {
    vec4 q = bonesUniforms.bones[i + 0u];
    vec3 t = bonesUniforms.bones[i + 1u].xyz;
    vec3 s = bonesUniforms.bones[i + 2u].xyz;

    // apply the non-uniform scales
    v *= s;
    // apply the rigid transform (valid only for unit quaternions)
    v += 2.0 * cross(q.xyz, cross(q.xyz, v) + q.w * v);
    // apply the translation
    v += t;

    return v;
}
```
2. ignore `q` in origin code, just return `v * s + t`. Output is wrong, and looks the same as 1.
```glsl
vec3 mulBoneVertex(vec3 v, uint i) {
    vec4 q = bonesUniforms.bones[i + 0u];
    vec3 t = bonesUniforms.bones[i + 1u].xyz;
    vec3 s = bonesUniforms.bones[i + 2u].xyz;
    return v * s + t;
}
```
3. change input to 3x3 mat for rotation, 3 float for translation and 3 float for scale. Then return `r * (v * s) + t`. Output is **right**.

In `RenderableManager.cpp`
```cpp
out->q.xyzw = m[0];
out->t = m[1];
out->s = m[2];
out->ns = m[3];
out->q.w = s[0];
out->t.w = s[1];
out->s.w = s[2];
```
In `getter.vs`
```glsl
vec4 m0 = bonesUniforms.bones[i + 0u];
vec4 m1 = bonesUniforms.bones[i + 1u];
vec4 m2 = bonesUniforms.bones[i + 2u];
vec3 t = bonesUniforms.bones[i + 3u].xyz;
mat3 r = mat3(m0.xyz, m1.xyz, m2.xyz);
vec3 s = vec3(m0.w, m1.w, m2.w);
return r * (v * s) + t;
```
4. transform `q` to 3x3 rotation. Output is wrong, and looks the same as 1.

I have checked all equations and tests, but found no error.

**Comment by prideout** [comment]
Do you have a glTF model that exhibits the issue?

**Comment by prideout** [comment]
@iamjinge it would help if you could provide a glTF file that reproduces the issue.

**Comment by pixelflinger** [comment]
@prideout yes, we're supposed to support non-uniform scales.

**Comment by pixelflinger** [comment]
@iamjinge are you sure that the transform you are using doesn't contain a *skew*? Because that is not allowed.

I have written  a basic test that checks the math and uniform scales seem to work as expected.

**Comment by pixelflinger** [comment]
@iamjinge actually, nevermind, I can reproduce the problem.

**Comment by romainguy** [comment]
Is this still an issue?
