### ISSUE TITLE
Binary release v1.3.2 missing `matdbg.lib`

### ISSUE THREAD

**Issue by linuxaged** [google/filament#1576]
`filament.lib` depends on `matdbg.lib`, but `matdbg.lib` is not packaged in `filament-20190827-windows.tgz`

	filament.lib(Engine.cpp.obj):-1: error: LNK2019: unresolved external symbol "public: __cdecl filament::matdbg::DebugServer::DebugServer(enum filament::matdbg::ServerMode,int)" (??0DebugServer@matdbg@filament@@QEAA@W4ServerMode@12@H@Z) referenced in function "int `private: __cdecl filament::details::FEngine::FEngine(enum details::backend::Backend,class details::Backend::Platform *,void *)'::`1'::dtor$38" (?dtor$38@?0???0FEngine@details@filament@@AEAA@W4Backend@backend@2@PEAVPlatform@42@PEAX@Z@4HA)
	filament.lib(Material.cpp.obj):-1: error: LNK2019: unresolved external symbol "public: void __cdecl filament::matdbg::DebugServer::addMaterial(class utils::CString const &,void const *,unsigned __int64,void *)" (?addMaterial@DebugServer@matdbg@filament@@QEAAXAEBVCString@utils@@PEBX_KPEAX@Z) referenced in function "public: class filament::Material * __cdecl filament::Material::Builder::build(class filament::Engine &)" (?build@Builder@Material@filament@@QEAAPEAV23@AEAVEngine@3@@Z)

**Comment by prideout** [comment]
Gah, my fault.  The releases do not enable DebugSever but on desktop there is still a link time dependency, so yes this lib needs to be distributed.

**Comment by romainguy** [comment]
That should only be true for debug builds right? Release builds should not need the extra library at all.

**Comment by prideout** [comment]
Correct, there should be no dependency.  Note that release builds *do* build the library, but only as a dependency of matinfo, not of filament.

Given the conditional in `filament/CMakeLists.txt`, I still don't understand how this is happening.

**Comment by romainguy** [comment]
Windows builds contain release and debug builds btw. We don't do this on other platforms.

**Comment by prideout** [comment]
Ah that explains it, thanks Romain.  TIL that "nm" on mac works with Windows binaries:

```
prideout $ nm ./lib/x86_64/mdd/filament.lib | grep DebugServer
         U ??0DebugServer@matdbg@filament@@QEAA@W4ServerMode@12@H@Z
         U ?addMaterial@DebugServer@matdbg@filament@@QEAAXAEBVCString@utils@@PEBX_KPEAX@Z
prideout $ nm ./lib/x86_64/mt/filament.lib | grep DebugServer
prideout $
```
