### ISSUE TITLE
GPU vertex morphing in Java

### ISSUE THREAD

**Issue by kylelin47** [google/filament#1578]
Hey,

I'm trying to morph between vertices in Filament on Android. I see that I can set morphing to enabled, and set morph weights, but am a bit unsure on how to set up the renderable to actually contain the morph targets of interest.

It looks to me that it would be done through setting up the VertexBuffer with additional attributes (MORPH_POSITION_x, MORPH_TANGENT_x) but those attributes don't appear to be available; what am I missing here?

**Comment by prideout** [comment]
Use `VertexAttribute::CUSTOM0` etc.

In the C++ header we have aliases set up:

    MORPH_POSITION_0 = CUSTOM0,
    MORPH_POSITION_1 = CUSTOM1,

See `MaterialEnums.h`.  We should probably do this for Java too...if Java allows aliases in enums?

**Comment by kylelin47** [comment]
Where is `VertexAttribute::CUSTOM0` defined?

I only see these attributes: https://github.com/google/filament/blob/master/android/filament-android/src/main/java/com/google/android/filament/VertexBuffer.java#L33-L41

**Comment by kylelin47** [comment]
Thanks for the quick response! Wouldn't you need to account for the [unused slot](https://github.com/google/filament/blob/6a5cc2f3dee6cd5ba56d27726938e655cffb83b5/libs/filabridge/include/filament/MaterialEnums.h#L118) though? Or is there some code that accounts for that.

**Comment by prideout** [comment]
Oh god, good catch.  Will fix.

**Comment by matthong45** [comment]
@prideout when can we expect the next stable build to be cut with this fix?

**Comment by prideout** [comment]
@matthong45 We should be cutting a new release soon, hopefully tomorrow.
