### ISSUE TITLE
How to use gltfio::animator with WebGL

### ISSUE THREAD

**Issue by cx20** [google/filament#1583]
**Is your feature request related to a problem? Please describe.**
I want to display a model of glTF animation in filament.
However, I can't find a sample, so I don't know what code to write to animate the model.

**Describe the solution you'd like**
I would like a sample to do glTF animation with WebGL.
![](https://github.com/cx20/gltf-test/blob/master/sampleModels/BoxAnimated/screenshot/screenshot.gif?raw=true) ![](https://github.com/cx20/gltf-test/blob/master/sampleModels/RiggedSimple/screenshot/screenshot.gif?raw=true)

**Describe alternatives you've considered**
I tried the following code: There was no error, but it was not animated.
```js
render(timestamp) {
    if (!start) start = timestamp;
    var progress = timestamp - start;
    var animator = this.asset.getAnimator();
    animator.applyAnimation(0, progress);
    animator.updateBoneMatrices();
    this.renderer.render(this.swapChain, this.view);
    window.requestAnimationFrame(this.render);
}
```

**OS and backend**
- OS : Windows 10
- Browser : Chrome 76
- Backend : ANGLE (WebGL)

**Comment by prideout** [comment]
Hm, that looks correct.  (One gotcha is that you should *not* call releaseSourceData before getting the animator object.)

I'll add a JavaScript sample, maybe that'll help.

**Comment by romainguy** [comment]
Isn't this missing begin/endFrame?

**Comment by prideout** [comment]
The `render` utility in JavaScript does begin / end for you.

**Comment by cx20** [comment]
I'm sorry I used it wrong. Now it works.
Animations can now be made by calling the render loop after the model has been loaded.
[filament + BoxAnimated.gltf result:](https://cx20.github.io/gltf-test/examples/filament/index.html?category=sampleModels&model=BoxAnimated&scale=0.5&type=glTF)
[filament + RiggedSimple.gltf result:](https://cx20.github.io/gltf-test/examples/filament/index.html?category=sampleModels&model=RiggedSimple&scale=0.2&type=glTF)

**Comment by prideout** [comment]
Nice!  I'll close this bug and make a note to myself to provide an animated example.  I'll probably just replace the existing Helmet demo with BusterDrone.
