### ISSUE TITLE
Unclear how  getWorldCameraPosition()  and  getWorldPosition() work in fragment shaders

### ISSUE THREAD

**Issue by molysgaard** [google/filament#1586]
**Describe the bug**
I am trying to write a fragment shader that computes the euclidean distance from the camera to the fragment in fillament API world coordinates.

**To Reproduce**
My material is as follows:
```
void material(inout MaterialInputs material) {
    prepareMaterial(material);

    float3 fragPos = getWorldPosition(); // xyz position of the current fragment
    float3 camPos = getWorldCameraPosition();
    float depth = clamp(length(fragPos-camPos), 0.0, 20.0);
    material.baseColor.rgb = vec3(depth,depth,depth)/20.0; // Because textures have values between 0.0 and 1.0 we predivide by 20.0 to get 20 units of range. Then when we read back the texture to the CPU we multiply by 20.0 to get the true depth in filament API world coordinate units.
}
```

**Expected behavior**
When placing the camera a fixed distance away from a flat plane, the distance values calculated by the fragment shader should be equal to 1/20 of the distance between the point on the plane corresponding to the pixel, and the position of the camera.

**Screenshots**
Here you see what actually is returned. The green widget is the camera (don't worry about the orientation of the green widget, it is not perfectly aligned with the actual OpenGL viewport). On the left you can see a black and white texture showing the fragment shader output. The red markers show the depth from the fragment shader projected back into 3D space. Image number 2 shows where the ground plane is.
The markers seem spherical, while they should form a plane.

![markers](https://i.imgur.com/8oFsOO9.png)
![plane](https://i.imgur.com/GT9Qxt8.png)

My guess is that the fragment shader is computing distances in some other space than the world space, but it is not really appearent from the fragment shader how that would happen. Would be happy for any help!

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - GPU: NVIDIA GTX 1050 Mobile
 - Backend: OpenGL

**Comment by molysgaard** [comment]
Here is another example that shows the effect even more clearly.

The camera (green widget) is placed above a plane this is 100 units wide and long. It is viewing along the plane.
On the left you can see the depth map generated from the fragment shader. It is clear that the maximum distance (completely white) is reached much further away than the 20 units. When projecting this depth map back into the world the red points show the distance.

To me it seems like the fragment shader computes distance in some sort of reciprocal distance space where there is much more resolution for distance closer to the camera than further away. This is in contrast to the stated API used in the fragment shader that, at least for me, seems like it is using world coordinates.

![](https://i.imgur.com/LwbYj6V.png)
![](https://i.imgur.com/3w5baWs.png)
In this last image i have hidden the plane to show the projected depth markers.
![](https://i.imgur.com/aDpjnkY.png)

**Comment by romainguy** [comment]
What is the depth map in your last example? If it is `gl_FragDepth` or a read-back of the depth buffer, then yes, you'll see that the precision is not evenly distributed. If you want linear depth you can search online, there are many resources explaining how to get that value. It has however nothing to do with the world position APIs provided in the fragment shader.

It is completely expected to see those "spherical markers" since you only compute a simple Euclidean distance. When the camera is facing straight at a flat wall and centered relative to the wall, the distance from the camera to the center of the wall will be shorter than the distance to the edges of the wall. If you don't want to or can't use the linear depth solution I mentioned above you could get the distance from the wall to the camera *plane*:

```
        vec3 d = fragmentPosition - cameraPosition;
        vec3 forward = normalize(-getWorldFromViewMatrix().xyz;
        float distance = dot(d, forward));
```

**Comment by prideout** [comment]
Also be sure to add in `getWorldOffset()` as per the [materials guide](https://google.github.io/filament/Materials.html).

**Comment by romainguy** [comment]
That is only needed to get absolute positions. It’s not necessary to compute distances.
