### ISSUE TITLE
Some animated glTFs fail to load the .bin file

### ISSUE THREAD

**Issue by cx20** [google/filament#1593]
**Describe the bug**
I tried to load the following animation glTF file with filament.
[AnimatedTriangle.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedTriangle)
[SimpleSkin.gltf](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_019_SimpleSkin.md)
However, an error was output to the console and the model was not displayed.

```
filament.js:formatted:1205 
Unable to load animation.bin
put_char	@	filament.js:formatted:1205
write	@	filament.js:formatted:1124
write	@	filament.js:formatted:3323
doWritev	@	filament.js:formatted:4344
___syscall146	@	filament.js:formatted:4425
(anonymous)	@	wasm-0066135e-1970:72
(anonymous)	@	wasm-0066135e-2000:49
(anonymous)	@	wasm-0066135e-2031:11
(anonymous)	@	wasm-0066135e-2030:9
(anonymous)	@	wasm-0066135e-1527:25
(anonymous)	@	wasm-0066135e-1652:539
(anonymous)	@	wasm-0066135e-501:34
(anonymous)	@	wasm-0066135e-735:10
Module.dynCall_iiii	@	filament.js:formatted:10150
dynCall_iiii_85	@	VM2137:4
gltfio$ResourceLoader$loadResources	@	VM2267:9
finalize	@	filament.js:formatted:10620
(anonymous)	@	index.js:95
```

**To Reproduce**

[filament + AnimatedTriangle.gltf result:](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=AnimatedTriangle&scale=1&type=glTF)
[filament + SimpleSkin.gltf result:](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=SimpleSkin&scale=1&type=glTF)

**Expected behavior**
I expect the animated glTF model to load and display correctly.

**Screenshots**
There is no reference screen because nothing is displayed.

**Desktop (please complete the following information):**
- OS: Windows 10 Version 1903 (OS Build 18362.295)
- GPU: Intel HD Graphics 520
- Backend: ANGLE
- Browser: Chrome 76

**Comment by prideout** [comment]
Thanks for these bug reports, they are great!  Currently the wasm build does not load external buffers that are used solely for animation because they are not included in the buffer descriptor list.  I'll fix this.
