### ISSUE TITLE
How to change Spot Light properties dynamically in web ?

### ISSUE THREAD

**Issue by Raki** [google/filament#1599]
I am trying change properties of spot light like position, falloff, color...etc... at runtime.
But , I can see there is no documentation for `LightManager` in filament javascript api.
I tried with the object return by `engine.getLightManager()` , but no luck.
Am I missing something completely or Was it left out intentionally ?

**Comment by prideout** [comment]
Ah, we need the `getInstance` in LightManager is missing.  I'll fix this.
