### ISSUE TITLE
How to use cmgen to blur an environment map without downscale? Keep the original size

### ISSUE THREAD

**Issue by but0n** [google/filament#1608]
Hi, I need some blurred environment maps as the skybox of my scene, I tried to use command `./cmgen --type=equirect --size=2048 --ibl-ld=test ~/Downloads/spruit_sunrise_4k.hdr`, but it will downscale the image for each roughness level.

How to avoid this? How to generate those image in a particular size?

**Comment by romainguy** [comment]
Don't use `--ibl-ld`, use `--extract-blur=X --extract=directory` instead, where X is a roughness value from `0.0` to `1.0` to control the blur amount. I like to use ~`0.09` myself. You can also combine `--extract-blur` with `-x` to generate the both the roughness levels for the indirect light and the blurred background:

`cmgen -x ~/Desktop/filament_res/env/ --extract-blur=0.08 ~/Documents/Filament/hdr/river.hdr`

**Comment by but0n** [comment]
Thanks for your reply, I tried use command: `./cmgen -f=hdr --type=equirect -x test --extract-blur=0.08 spruit_sunrise_4k.hdr`, but those output files is always rgb32f format even I specified output file format with `-f`.
My purpose is to generate several 4k images in different blur level.

**Comment by but0n** [comment]
@romainguy Oops, my mistake, now the output file format is correct with `-f hdr`, but the downscale problem still:
![image](https://user-images.githubusercontent.com/7625588/64578227-5af21f00-d3b1-11e9-891e-67961f4fedac.png)

**Comment by but0n** [comment]
Though, now I'm using command `./cmgen -f hdr -s 2048 --type=equirect --extract=test --extract-blur=0.08 spruit_sunrise_4k.hdr` to generate blurred image with 4k resolution. Problem solved.

**Comment by romainguy** [comment]
That's because `-x` is a feature to do everything with one flag so it always generates mip level. `--extract=` instead of `-x` is what you want if you want just one high resolution level.

**Comment by but0n** [comment]
@romainguy 
Hi, I got another problem, when I use png file as input, the color of output files looks weird:

![image](https://user-images.githubusercontent.com/7625588/64748714-aa695400-d545-11e9-995f-f8c7ee5becaa.png)

Another problem is there will be some stripes after blur, how to fix this?
![image](https://user-images.githubusercontent.com/7625588/64935574-a0688d80-d884-11e9-94bd-0989767a90df.png)
![image](https://user-images.githubusercontent.com/7625588/64935578-a2325100-d884-11e9-832d-bdde4d7597e4.png)
![image](https://user-images.githubusercontent.com/7625588/64935580-a3637e00-d884-11e9-9a16-450ce448d4de.png)

**Comment by romainguy** [comment]
The color issue is just an encoding bug: we save the image as sRGB but it contains linear data. It should be an easy fix.

As for the "striping" it's simply banding and I would expect this kind of issue from a bandwidth limited like PNG.

Just to be clear: `cmgen`'s main purpose is to process and output HDR data with high bit depth.

**Comment by romainguy** [comment]
The fix should be here: https://github.com/google/filament/pull/1646

**Comment by dandingol03** [comment]
@but0n Hi, how to render skybox with cubemap whose format is `png`.
