### ISSUE TITLE
crash on destroy Filament

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1618]
**Describe the bug**
crash on destry Filament. Log and Stacktrace below:
 A/libc: invalid address or address of corrupt block 0x5596e4cd30 passed to dlfree
![1](https://user-images.githubusercontent.com/53041249/64594306-585bed80-d3e2-11e9-90e5-82b25f40c405.png)

**Smartphone (please complete the following information):**
 - Device: android 5.1.1,vivo X7
 - OS: android 5.1.1

**Comment by romainguy** [comment]
Do you have more information? What is your destroy sequence in your code? We need to reproduce the issue.

**Comment by pixelflinger** [comment]
This looks like a double-free. Could you double-check that you're not destroying the Engine twice?

**Comment by geroge-d** [comment]
I 'll test it later,give you guys more information.

**Comment by geroge-d** [comment]
destroy it by wrong order
