### ISSUE TITLE
Vulkan and Metal: lucy_bloom is upside down

### ISSUE THREAD

**Issue by prideout** [google/filament#1626]
Other samples are fine, this is probably related to the new RenderTarget API.

**Comment by bejado** [comment]
I think if you convert the bloom / blue shaders to post-process, it should fix the issue.

**Comment by prideout** [comment]
Nice I'll give it a shot!  I didn't realize that the new post-process functionality was public, maybe we should update `Materials.md.html`?

**Comment by bejado** [comment]
Ohh, that’s a good point, it’s not fully “public” yet so maybe we should
hold off on updating. But at least we can validate it fixes the issue until
our documentation is updated.

**Comment by prideout** [comment]
Actually the bloom in the demo might not have high enough quality to integrate with the Filament core (e.g. we would need to look at test cases with small bright highlights, spheres with 0 roughness, etc) so this should probably wait for the user-accessible pp API.

**Comment by romainguy** [comment]
For a built-in version I would definitely like to have proper HDR support and a stable bloom. Actually a next step at some point would be to support full blown effects. A post process effect might require several passes (bloom) and having a way to describe this would be awesome. It's tedious and error prone to write this kind of code by hand.
