### ISSUE TITLE
DriverAPI: introduce a timestamp query API.

### ISSUE THREAD

**Issue by prideout** [google/filament#1629]
Filament currently uses fences to determine frame time (e.g. to support frame skipping) but in Vulkan, each fence is associated with a specific submission of a Vk command buffer.  Moreover we triple-buffer the Vk command buffers on some platforms.  Fences are not the correct mechanism.

To fix this, we should add query objects to the driver API, and change the frame skipper to use these if possible.  For starters, queries should perhaps only support timestamps. However we should consider making them extensible for the future.

Timestamps are supported in the Vulkan core, and on OpenGL they are supported via `EXT_disjoint_timer_query`. I believe Metal can support similar functionality via its counter sampling API.

**Comment by romainguy** [comment]
On OpenGL what we'd want to use are Android's EGL timestamp extensions.

**Comment by prideout** [comment]
See #2325

**Comment by romainguy** [comment]
Is this still required with @pixelflinger's recent changes?
