### ISSUE TITLE
Build failure on Fedora 30

### ISSUE THREAD

**Issue by draz-wi** [google/filament#1637]
**Describe the bug**
When compiling Filament I get the error `/usr/bin/ld: cannot find -lgcc_s`

**To Reproduce**
I followed the steps as outlined in the README, I have installed all the recommended packages including. The cmake command runs fine. When I run ninja, building stops at around the 61st file with the error `/usr/bin/ld: cannot find -lgcc_s
` being raised

**Ninja Output:**
```
[61/1203] Linking CXX shared library libs/utils/libbenchmark_utils_callee.so
FAILED: libs/utils/libbenchmark_utils_callee.so 
: && /usr/bin/clang++ -fPIC -stdlib=libc++ -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fcolor-diagnostics -O2 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -Wl,--gc-sections -Wl,-Bsymbolic-functions -shared -Wl,-soname,libbenchmark_utils_callee.so -o libs/utils/libbenchmark_utils_callee.so libs/utils/CMakeFiles/benchmark_utils_callee.dir/benchmark/benchmark_callee.cpp.o  -static-libgcc -static-libstdc++ -Wl,-Bstatic -lc++ -lc++abi -Wl,-Bdynamic && :
/usr/bin/ld: cannot find -lgcc_s
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
[70/1203] Building CXX object libs/utils/CMakeFiles/test_utils.dir/test/test_Path.cpp.o
ninja: build stopped: subcommand failed.
```

**Desktop:**
 - OS: Fedora 30
 - GPU: [e.g. NVIDIA MX150]

**Comment by bejado** [comment]
I'm not too familiar with Linux dependencies, but [this](https://askubuntu.com/questions/346377/cannot-find-lgcc-s) might help.

**Comment by draz-wi** [comment]
> I'm not too familiar with Linux dependencies, but [this](https://askubuntu.com/questions/346377/cannot-find-lgcc-s) might help.

I have just tried that but the problem persists even after creating the symbolic link.

**Comment by mp3guy** [comment]
Just wondering why this was closed? Currently still on issue on F32 with Clang-9

**Comment by mp3guy** [comment]
Solution appears to be `-DUSE_STATIC_LIBCXX=false`
