### ISSUE TITLE
iOS MetalKit & ARKit example's problem

### ISSUE THREAD

**Issue by Realitian** [google/filament#1647]
I think current iOS ar sample has a problem.
it calls the render function in ar session didUpdateFrame callback.
it will affect the tracking performance.
I would like to calls the render function in MTKView's draw callback.
But, unfortunately it failed call render in MTKView draw callback.(black screen and error messages).
Can you describe why cannot call the filament render in MTKView draw callback?
Cheers.

**Comment by bejado** [comment]
What were the error messages? Filament manages it’s own Metal context / objects and is not designed to work with a MTKView.

**Comment by romainguy** [comment]
Note that the render function doesn't do the actual rendering, this happens on a different thread. The render function should be very cheap in the ar case.

**Comment by bejado** [comment]
This might be a synchronization issue. Note that `ARSession` calls `didUpdateFrame` on the main dispatch queue (see [`delegateQueue`](https://developer.apple.com/documentation/arkit/arsession/2875726-delegatequeue?language=objc)). I'm not sure what queue `MTKView.draw` gets called on.

**Comment by Realitian** [comment]
the error message is here.
==========================
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)

**Comment by Realitian** [comment]
If I don't add FullScreenTriangle(https://github.com/google/filament/blob/master/ios/samples/hello-ar/hello-ar/FilamentArView/FullScreenTriangle.h), then it works with MTKViewDelegate.
But, with FullScreenTriangle it don't work in MTKViewDelegate.

**Comment by bejado** [comment]
It's hard to say what the issue is without seeing the rest of your project. Why do you need to use a `MTKView`? The samples use a simple `UIView` subclass that overwrites `layerClass` to return a `CAMetalLayer` (see [`FilamentView`](https://github.com/google/filament/blob/master/ios/samples/hello-ar/hello-ar/FilamentArView/FilamentView.m)).

My best guess is that the error is related to the camera feed. You can try replacing [`mCameraFeedTexture`](https://github.com/google/filament/blob/master/ios/samples/hello-ar/hello-ar/FilamentArView/FullScreenTriangle.cpp#L63) with a placeholder texture and see if that works.

**Comment by Realitian** [comment]
Yes, I attached the sample code for that.
[hello-ar.zip](https://github.com/google/filament/files/3625510/hello-ar.zip)
And the reason to use MTKView is simple, just I wanted to follow the standard ARkit-metal architecture provided by Apple.

**Comment by bejado** [comment]
The errors you see are because `drawInMTKView` is called before any camera frames have been captured. You can add the following if check at the beginning of `drawInMTKView` to prevent rendering before a camera frame is ready:

```
- (void)drawInMTKView:(nonnull MTKView *)view {
    ARFrame *frame = self.session.currentFrame;
    
    if (!frame.capturedImage) {
        return;
    }

    ...
}
```

**Comment by Realitian** [comment]
It works.
Thanks for your comment.
