### ISSUE TITLE
Issue in Android on windows setup

### ISSUE THREAD

**Issue by rash1994** [google/filament#1657]
I am building filament for android in windows, using LLVM and using following command to build it:

 cmake ..\.. -T"LLVM" -G "Visual Studio 15 2017 Win64" -DCMAKE_CXX_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER:PATH="C:\Program Files\LLVM\bin\lld-link.exe" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=D:\filament\build\toolchain-x86_64-linux-android.cmake

and getting following error,

-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe
CMake Error at D:/filament/build/toolchain-x86_64-linux-android.cmake:32 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  D:/filament/out/cmake-android-release-x86/CMakeFiles/3.14.4/CMakeSystem.cmake:6 (include)
  D:/filament/out/cmake-android-release-x86/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

CMake Error at D:/filament/build/toolchain-x86_64-linux-android.cmake:38 (list):
  list GET given empty list
Call Stack (most recent call first):
  D:/filament/out/cmake-android-release-x86/CMakeFiles/3.14.4/CMakeSystem.cmake:6 (include)
  D:/filament/out/cmake-android-release-x86/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

CMake Error at D:/filament/build/toolchain-x86_64-linux-android.cmake:39 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  D:/filament/out/cmake-android-release-x86/CMakeFiles/3.14.4/CMakeSystem.cmake:6 (include)
  D:/filament/out/cmake-android-release-x86/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

CMake Error at C:/Users/KIKSAR/Anaconda3/envs/dlib2/Lib/site-packages/cmake/data/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:44 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:9 (project)

-- Configuring incomplete, errors occurred!
See also "D:/filament/out/cmake-android-release-x86/CMakeFiles/CMakeOutput.log".

**Comment by romainguy** [comment]
Make sure you have an ANDROID_HOME env variable defined pointing to the Android SDK. Make also sure you have installed the "NDK Side by side" component.

**Comment by rash1994** [comment]
I did not have NDK side by side. Installing it solved the issue.
Thanks!
