### ISSUE TITLE
Multiscattering documentation clarification

### ISSUE THREAD

**Issue by tombsar** [google/filament#167]
The documentation for multiscattering energy compensation (https://google.github.io/filament/Filament.md.html#toc4.7.2) gives the following as equation 30:
```
f(l,v) = f_r(l,v) + \fNormal \left( \frac{1}{r} - 1 \right) f_r(l,v)
```

(source line: https://github.com/google/filament/blob/master/docs/Filament.md.html#L573)

From the context of the section (particularly equation 28) I believe the subscripts are incorrect, and the equation should instead read:
```
f_r(l,v) = f_{ss}(l,v) + \fNormal \left( \frac{1}{r} - 1 \right) f_{ss}(l,v)
```

**Comment by romainguy** [comment]
You are correct, thanks! I changed the subscripts after writing the section and I apparently left out an equation.

**Comment by tombsar** [comment]
I actually have several more minor corrections/nitpicks for the document. Would you prefer me to make a new issue for each section, bundle them together into a single issue, or submit a PR with my proposed changes?

**Comment by romainguy** [comment]
Whatever is easier for you. I'm happy to make the changes if you list them in an issue.
