### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Simoncl** [google/filament#1672]
I get the following error building the IOS lib. The MacOS builds fine.

filament-master/third_party/OpenImageDenoise/mkl-dnn/src/cpu/jit_utils/jitprofiling/jitprofiling.c
filament-master/third_party/OpenImageDenoise/mkl-dnn/src/cpu/jit_utils/jitprofiling/ittnotify_config.h

error: implicit declaration of function '__TBB_machine_fetchadd4'
      is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return __TBB_machine_fetchadd4(ptr, 1) + 1L;

**Comment by romainguy** [comment]
Weird, we shouldn't be building OpenImageDenoise for iOS.

@prideout any idea?

**Comment by bejado** [comment]
@Simoncl what version of MacOS are you using to compile?

**Comment by Simoncl** [comment]
Version 10.14.6

**Comment by Simoncl** [comment]
I ran the following 
./build.sh -p desktop -I release 
Then
./build.sh -p ios release
The desktop build completed fine.

**Comment by bejado** [comment]
Looks like we do build OpenImageDenoise on iOS if we find the embree and TBB libraries. I don't have embree which is why I can't reproduce (same goes for CI I'd imagine).

**Comment by bejado** [comment]
Temporarily you could change that if condition to:

```
if (embree_FOUND AND NOT ANDROID AND NOT IOS)
```

@prideout can advise what the correct fix is.

**Comment by Simoncl** [comment]
What file is that option living in? Sorry new to the code base. Appreciate the help

**Comment by bejado** [comment]
Sure thing. It's in the root [`CMakeLists.txt`](https://github.com/google/filament/blob/master/CMakeLists.txt#L74).

**Comment by romainguy** [comment]
We shouldn't build open image denoise, it's used by the AO Baker which only runs on host. We should just move the relevant lines in the root CMake to.only build this lib on host.

**Comment by Simoncl** [comment]
made the change and it's built with no errors:)

**Comment by Simoncl** [comment]
Just one more question. Are the generated Xcode projects are just supposed to build? Or am I required to link to the filament lib and headers. Currently my generated Xcode projects do not build.

**Comment by bejado** [comment]
Yes they should build. What's the error?

**Comment by Simoncl** [comment]
when including 
#include "CameraManipulator.h"
It can't find #include <math/vec2.h>

**Comment by Simoncl** [comment]
It's generating all the exciting stuff like SH coefficients and .filament files just not finding #include <math/vec2.h>

**Comment by bejado** [comment]
@Simoncl Please make sure you're passing the `-i` flag to the `build.sh` script to it installs Filament to the correct folder. The command should be:

```
./build.sh -p -i ios release
```

Since you're building Filament in release mode, you need to make sure you're building the Xcode projects in release as well.

You can check and ensure that Filament is installed:

```
$ cd <filament-root>
$ ls out/ios-release/filament/include/
backend    filamat    filament   filameshio geometry   gltfio     ibl        image      math       rays       utils
```
