### ISSUE TITLE
get blank image on set worldPosition.z = 0 in vertex block

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1675]
**Describe the bug**
I want to draw an image, using the code below, it work great . But when i set worldPosition.z  = 0 in vertex block, i get a blank image. Could you please tell what i miss? thanks in advance!

material {
    name : "Image 2dmode_normal",
    parameters : [
        {
           type : sampler2d,
           name : texture
        },
      
        {
            type:float,
            name:alpha
        }
    ],
    requires : [
            uv0
        ],
      blending : fade,
      flipUV : false,
      depthWrite : false,
      depthCulling : false,
      culling : none,
      shadingModel : unlit
}
vertex {
    void materialVertex(inout MaterialVertexInputs material) {
     material.worldPosition =float4(material.worldPosition.x,material.worldPosition.y,0.0,material.worldPosition.w)
    }
}
fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        float4 texel = texture(materialParams_texture, getUV0());
        
        float4 outputColor =float4(texel.rgb * materialParams.alpha, texel.a * materialParams.alpha);
         material.baseColor = outputColor;
    }
}

**Smartphone (please complete the following information):**
 - Device: huawei mate
 - OS: android 6.0

**Comment by prideout** [comment]
Normally that's used as an input variable rather than an output.  Also it is more of a "view-space position" than a world-space position (look for `getWorldOffset` in our materials document).

If you want to flatten your geometry it might be better to scale it using `TransformManager`, or set a custom projection matrix in `Camera`.
