### ISSUE TITLE
How can implement billboarding?

### ISSUE THREAD

**Issue by Realitian** [google/filament#1677]
Hi,
Filament has any functionality what can set pre transform matrix or post transform matrix?
Exactly same thing to AutoTransform schema in OpenSceneGraph.
Actually I tried to make billboard object in filament, but I couldn't insert rotation matrix for billboard pre multi view matrix.
I want to make below matrix transform:
matRot * matView * matObject
(matRot : what I want to insert, for only specific object but not whole scene. 
matView : camera matrix what can be set by calling Camera::setModelMatrix.
matObject : object matrix what can be set by calling TransformManager::setTransform)

**Comment by pixelflinger** [comment]
Couldn't you do this in the custom vertex shader of your billboard material?

**Comment by roxlu** [comment]
Is there a more efficient way than this:
```glsl
material {
    name : color,
    shadingModel : lit,
    blending: opaque,
    doubleSided: true,
    vertexDomain: object,
    parameters : [
        { type: float3, name: albedo },
        { type: float, name: roughness },
        { type: float, name: metallic },
        { type: float, name: alpha }
    ],
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        float s = 0.5 + sin(getUserTime().x) * 0.5;
        material.baseColor.rgb = vec3(1 , 1.0, s * 10.0); 
    }
}

vertex {
    void materialVertex(inout MaterialVertexInputs material) {

        /* Billboarding for Filament */
        vec4 p = getPosition();
        mat4 view_from_world = getViewFromWorldMatrix();
        mat4 world_from_view = getWorldFromViewMatrix();
        mat4 world_from_model = getWorldFromModelMatrix(); 
        material.worldPosition = world_from_view * ((view_from_world * world_from_model * vec4(0, 0, 0, 1)) + vec4(p.x, p.y, 0, 0)); 
                
        /* ... or we can use a one liner */
        material.worldPosition = getWorldFromViewMatrix() * ((getViewFromWorldMatrix() * getWorldFromModelMatrix() * vec4(0, 0, 0, 1)) + vec4(p.x, p.y, 0, 0));
    }
}


```

**Comment by dandingol03** [comment]
> Is there a more efficient way than this:
> 
> ```glsl
> material {
>     name : color,
>     shadingModel : lit,
>     blending: opaque,
>     doubleSided: true,
>     vertexDomain: object,
>     parameters : [
>         { type: float3, name: albedo },
>         { type: float, name: roughness },
>         { type: float, name: metallic },
>         { type: float, name: alpha }
>     ],
> }
> 
> fragment {
>     void material(inout MaterialInputs material) {
>         prepareMaterial(material);
>         float s = 0.5 + sin(getUserTime().x) * 0.5;
>         material.baseColor.rgb = vec3(1 , 1.0, s * 10.0); 
>     }
> }
> 
> vertex {
>     void materialVertex(inout MaterialVertexInputs material) {
> 
>         /* Billboarding for Filament */
>         vec4 p = getPosition();
>         mat4 view_from_world = getViewFromWorldMatrix();
>         mat4 world_from_view = getWorldFromViewMatrix();
>         mat4 world_from_model = getWorldFromModelMatrix(); 
>         material.worldPosition = world_from_view * ((view_from_world * world_from_model * vec4(0, 0, 0, 1)) + vec4(p.x, p.y, 0, 0)); 
>                 
>         /* ... or we can use a one liner */
>         material.worldPosition = getWorldFromViewMatrix() * ((getViewFromWorldMatrix() * getWorldFromModelMatrix() * vec4(0, 0, 0, 1)) + vec4(p.x, p.y, 0, 0));
>     }
> }
> ```

does this work?

**Comment by dandingol03** [comment]
> Hi, Filament has any functionality what can set pre transform matrix or post transform matrix? Exactly same thing to AutoTransform schema in OpenSceneGraph. Actually I tried to make billboard object in filament, but I couldn't insert rotation matrix for billboard pre multi view matrix. I want to make below matrix transform: matRot * matView * matObject (matRot : what I want to insert, for only specific object but not whole scene. matView : camera matrix what can be set by calling Camera::setModelMatrix. matObject : object matrix what can be set by calling TransformManager::setTransform)

How is your implemention going about the billboard shader
