### ISSUE TITLE
Customized transform of vertex in vertexShader

### ISSUE THREAD

**Issue by Realitian** [google/filament#1685]
How can implement customized transform of vertex in material, something like vertex animation?
I couldn't find any example of vertex transform, anybody can share example material file for that?
Cheers!

**Comment by romainguy** [comment]
It's documented here:

https://google.github.io/filament/Materials.html

Specifically you can use the `worldPosition` field of the `MaterialVertexInputs` structure to modify the vertex position from the shader. Note that it's meant for simple animations and not as a way to implement skinning or blend shapes (which are supported by the engine directly).

**Comment by romainguy** [comment]
Here's an example:

```
vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        material.worldPosition.x += sin(getWorldPosition().y * 3.0 + getTime().x * 5.0) * 0.1;
    }
}
```

**Comment by Realitian** [comment]
Hmm, I tried to change vertex position defined in device domain.
But I see below code does not work.
Can you explain what I had mistake?

// pseudo code for shift vertex position (defined device domain) by texPos.  

material {
    vertexDomain : device,
    variables : [
         vertex
    ],
    parameters : [
	{
	    type : float4,
            name : textPos
        }
    ]
}

vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        material.worldPosition.xy = getPosition().xy + materialParams.textPos.xy;
        material.worldPosition.zw = materialParams.textPos.zw;
    }
}

**Comment by romainguy** [comment]
It's the one thing we don't support yet. It was however requested and it's my next task :)

**Comment by prideout** [comment]
Device domain is tricky since different backends have different definitions of clip space.

**Comment by BStringhamVRSK** [comment]
@romainguy Is transformation of vertices in the **Device** domain available now?
I am trying to set up some user interface elements (icons), and I was hoping to have all of them use the same vertex buffer, but transform them to the correct screen position and scale in the vertex buffer.  
Currently, it appears that modifying the vertex buffer may be the only solution?

**Comment by romainguy** [comment]
You can set the `material.clipSpaceTransform` property in your vertex shader. It works no matter what domain you use, it will always be applied on  the clip space coordinates.

**Comment by romainguy** [comment]
See `Material vertex inputs` section at https://google.github.io/filament/Materials.html.

**Comment by BStringhamVRSK** [comment]
Ah, of course.  Thank you.

**Comment by BStringhamVRSK** [comment]
I encountered a strange problem that I'm not sure how to fix.  Here is the code in my vertex shader, which is intended to scale and position a UI icon on the screen.  It works fine on one machine, but fails on a different one.  On the machine that fails, the X scale factor works, but the Y does not, which stretches the icon vertically.  I am putting the matrix values in directly, is there some problem with that?  Or, is the matrix format perhaps different on one machine vs. the other?
```
vertex {

    void materialVertex(inout MaterialVertexInputs material) {
		material.clipSpaceTransform[0][0] = materialParams.clipSpaceTrans.x;	// X scale
		material.clipSpaceTransform[1][1] = materialParams.clipSpaceTrans.y;	// Y scale
		material.clipSpaceTransform[3][0] = materialParams.clipSpaceTrans.z;	// X translate
		material.clipSpaceTransform[3][1] = materialParams.clipSpaceTrans.w;	// Y translate
    }
}
```
<img width="168" alt="IconStretch" src="https://user-images.githubusercontent.com/40642629/74864382-b8997880-530c-11ea-885c-c318dd83f591.PNG">

**Comment by prideout** [comment]
Are both of your two machines using the backend?  i.e. are they both using OpenGL?  To double check you can look at your console, you should see a message that looks like this:

    Filament library loaded.
    FEngine (64 bits) created at 0x10fe87000 (threading is enabled)
    FEngine resolved backend: OpenGL

**Comment by BStringhamVRSK** [comment]
I don't see those messages on either machine, but we are in a .NET environment, so perhaps they are getting suppressed?  I believe it is using OpenGL.  I will try explicitly setting the backend to OpenGL to see if that makes a difference.

**Comment by prideout** [comment]
Well it is likely they are both using OpenGL.  This is a really strange machine-to-machine difference.  Also, make sure that the materials are getting compiled the same way on the two machines, using the same version of matc etc.  Hmm....

**Comment by BStringhamVRSK** [comment]
I get the same result when explicitly setting OpenGL as backend.  The materials should be both using 1.4.5 to build.
I wish RenderDoc would let me debug the shader so I could see the actual values in the matrix.  I wonder if I need to set the rest of the matrix to identity values?  I could try that.

**Comment by BStringhamVRSK** [comment]
Here is the disassembled vertex shader.  What I suspect is happening, is that (on the misbehaving machine) when those matrix copies/assignments are happening, it is only getting the first row of the matrix and the rest becomes identity.  The net result would be that my X scale gets copied all the way down, and the final Y translate gets assigned before the matrix is used in final multiply (matrix _297).

That matches what I'm seeing when it runs.

```
void main()
{
mat4 _197 = frameUniforms.worldFromViewMatrix * frameUniforms.viewFromClipMatrix;
mat4 _273 = mat4(vec4(1.0, 0.0, 0.0, 0.0), vec4(0.0, 1.0, 0.0, 0.0), vec4(0.0, 0.0, 1.0, 0.0), vec4(0.0, 0.0, 0.0, 1.0));
_273[0].x = materialParams.clipSpaceTrans.x;
mat4 _275 = _273;
_275[1].y = materialParams.clipSpaceTrans.y;
mat4 _277 = _275;
_277[3].x = materialParams.clipSpaceTrans.z;
mat4 _279 = _277;
_279[3].y = materialParams.clipSpaceTrans.w;
vertex_uv01 = vec2(mesh_uv0.x, 1.0 - mesh_uv0.y);
vertex_worldPosition = ((_197[0] * mesh_position.x) + ((_197[1] * mesh_position.y) + ((_197[2] * mesh_position.z) + _197[3]))).xyz;
gl_Position = mesh_position;
gl_Position = _279 * gl_Position;
}

```

**Comment by prideout** [comment]
Looks like a bug on the part of the GPU vendor.  Out of curiosity what GPU is this?  To work around it, you can try adding the -g or -S option to your matc invocation.

**Comment by BStringhamVRSK** [comment]
The failing machine is using an NVidia 2070 Super.  You're probably right that the NVidia optimizer may be getting too aggressive.

The -g option does work, as expected.  Thanks.

**Comment by romainguy** [comment]
`-g` disables Filament's offline optimizer. It would be good to verify whether the issue is on our side in `spirv-opt` or in the Nvidia drivers.

**Comment by BStringhamVRSK** [comment]
Do you want me to send you my material file?  Or, could I test it here somehow?  I also tried -S, but that had no effect.
