### ISSUE TITLE
Java sample apps not compiling

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1687]
I think the [removal of the Fences](https://github.com/google/filament/commit/b81ff060aed9ffdc18d7b9163d5d81d5ce0b6e0b) from the Java SDK may have broken the build for [some of the sample apps](https://github.com/google/filament/blob/master/android/samples/lit-cube/app/src/main/java/com/google/android/filament/litcube/MainActivity.kt#L346).

**Comment by romainguy** [comment]
Indeed, thanks.
