### ISSUE TITLE
In v 1.3.2 when linking for osx, libmatdbg.a is unable to find symbols

### ISSUE THREAD

**Issue by kevintan82** [google/filament#1689]
Hi, 

When linking against the lib files that have been compiled from source, I am encountering the below errors. 

I am able to compile successfully when setting the target to Release.

I have read a previous issue, where libmatdbg.a was missing from desktop debug builds.

May I know if this is an issue with the release, or if this is a pebkac problem where I have not included an appropriate lib in my build script.

Thank you for your time.
*Update* didnt put in the correct output previously, my apologies
Undefined symbols for architecture x86_64:
  "_MATDBG_RESOURCES_INDEX_OFFSET", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "_MATDBG_RESOURCES_INDEX_SIZE", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "_MATDBG_RESOURCES_PACKAGE", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "_MATDBG_RESOURCES_SCRIPT_OFFSET", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "_MATDBG_RESOURCES_SCRIPT_SIZE", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "_MATDBG_RESOURCES_STYLE_OFFSET", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "_MATDBG_RESOURCES_STYLE_SIZE", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "CivetServer::addHandler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, CivetHandler*)", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "CivetServer::addWebSocketHandler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, CivetWebSocketHandler*)", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "CivetServer::CivetServer(char const**, CivetCallbacks const*, void const*)", referenced from:
      filament::matdbg::DebugServer::DebugServer(filament::backend::Backend, int) in libmatdbg.a(DebugServer.cpp.o)
  "spirv_cross::CompilerGLSL::init()", referenced from:
      spirv_cross::CompilerGLSL::CompilerGLSL(std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >) in libmatdbg.a(ShaderExtractor.cpp.o)
  "CivetHandler::handleHead(CivetServer*, mg_connection*)", referenced from:
      vtable for filament::matdbg::FileRequestHandler in libmatdbg.a(DebugServer.cpp.o)
      vtable for filament::matdbg::RestRequestHandler in libmatdbg.a(DebugServer.cpp.o)
  "CivetHandler::handlePost(CivetServer*, mg_connection*)", referenced from:
      vtable for filament::matdbg::FileRequestHandler in libmatdbg.a(DebugServer.cpp.o)
      vtable for filament::matdbg::RestRequestHandler in libmatdbg.a(DebugServer.cpp.o)
  "CivetHandler::handlePatch(CivetServer*, mg_connection*)", referenced from:
      vtable for filament::matdbg::FileRequestHandler in libmatdbg.a(DebugServer.cpp.o)
      vtable for filament::matdbg::RestRequestHandler in libmatdbg.a(DebugServer.cpp.o)
  "CivetHandler::handleDelete(CivetServer*, mg_connection*)", referenced from:
      vtable for filament::matdbg::FileRequestHandler in libmatdbg.a(DebugServer.cpp.o)
      vtable for filament::matdbg::RestRequestHandler in libmatdbg.a(DebugServer.cpp.o)
  "CivetHandler::handleOptions(CivetServer*, mg_connection*)", referenced from:
      vtable for filament::matdbg::FileRequestHandler in libmatdbg.a(DebugServer.cpp.o)
      vtable for filament::matdbg::RestRequestHandler in libmatdbg.a(DebugServer.cpp.o)
  "CivetHandler::handlePut(CivetServer*, mg_connection*)", referenced from:
      vtable for filament::matdbg::FileRequestHandler in libmatdbg.a(DebugServer.cpp.o)
      vtable for filament::matdbg::RestRequestHandler in libmatdbg.a(DebugServer.cpp.o)
  "typeinfo for CivetHandler", referenced from:
      typeinfo for filament::matdbg::FileRequestHandler in libmatdbg.a(DebugServer.cpp.o)
      typeinfo for filament::matdbg::RestRequestHandler in libmatdbg.a(DebugServer.cpp.o)
  "typeinfo for CivetWebSocketHandler", referenced from:
      typeinfo for filament::matdbg::WebSocketHandler in libmatdbg.a(DebugServer.cpp.o)
  "vtable for CivetHandler", referenced from:
      CivetHandler::CivetHandler() in libmatdbg.a(DebugServer.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for CivetWebSocketHandler", referenced from:
      CivetWebSocketHandler::CivetWebSocketHandler() in libmatdbg.a(DebugServer.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "_mg_get_request_info", referenced from:
      filament::matdbg::FileRequestHandler::handleGet(CivetServer*, mg_connection*) in libmatdbg.a(DebugServer.cpp.o)
      filament::matdbg::RestRequestHandler::handleGet(CivetServer*, mg_connection*) in libmatdbg.a(DebugServer.cpp.o)
  "_mg_get_var", referenced from:
      filament::matdbg::RestRequestHandler::handleGet(CivetServer*, mg_connection*) in libmatdbg.a(DebugServer.cpp.o)
  "_mg_printf", referenced from:
      filament::matdbg::FileRequestHandler::handleGet(CivetServer*, mg_connection*) in libmatdbg.a(DebugServer.cpp.o)
      filament::matdbg::RestRequestHandler::handleGet(CivetServer*, mg_connection*) in libmatdbg.a(DebugServer.cpp.o)
  "_mg_websocket_write", referenced from:
      filament::matdbg::WebSocketHandler::notify(filament::matdbg::DebugServer::MaterialRecord const&) in libmatdbg.a(DebugServer.cpp.o)
  "_mg_write", referenced from:
      filament::matdbg::FileRequestHandler::handleGet(CivetServer*, mg_connection*) in libmatdbg.a(DebugServer.cpp.o)
      filament::matdbg::RestRequestHandler::handleGet(CivetServer*, mg_connection*) in libmatdbg.a(DebugServer.cpp.o)

**Comment by prideout** [comment]
To rephrase the issue as I understand it: you're seeing these errors when building a client application against Filament libraries that were built in the debug configuration using source from the `v1.3.2` tag.

It also sounds like you're not using CMake for your client application, so please ensure that `matdbg_resources` and `civetweb` are being linked.
