### ISSUE TITLE
how to share depth texture between RenderTargets?

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1700]
I create different render targets,and want to share depth texture among them. But it fail to share, and i checked the source code, found the following code ( src/renderer.cpp). So do Filament have any possible way to share a depth texture between render target ?

 // We only honor the view's color buffer clear flags, depth/stencil are handled by the framefraph
    uint8_t viewClearFlags = view.getClearFlags() & (uint8_t)TargetBufferFlags::ALL;
    TargetBufferFlags clearFlags = (TargetBufferFlags(viewClearFlags) & TargetBufferFlags::COLOR)
                                   | TargetBufferFlags::DEPTH;

**Comment by romainguy** [comment]
Did you disable the depth clear on your `View`?

**Comment by geroge-d** [comment]
yes, i disable it by this way   view.setClearTargets(true,false,false).  And then , i disable depth prepass,by view.depthPrepass = View.DepthPrepass.DISABLED

**Comment by geroge-d** [comment]
I think Filament don't honor the view's depth clearflag, based on investigating in Filament source code

**Comment by romainguy** [comment]
What issue are you running into exactly? And how do you attach the depth buffer to your render targets?

**Comment by geroge-d** [comment]
yes , very sure. the shared depth  is refreshed by the filament. the code create render target below:
if ( sharedDepth == null){
                    clearDepth = true
                    val depthbit:Texture.InternalFormat
                    if ( depthBufferBits == 32){
                        depthbit = Texture.InternalFormat.DEPTH32F
                    }
                    else if ( depthBufferBits == 24){
                        depthbit = Texture.InternalFormat.DEPTH24
                    }
                    else{
                        depthbit = Texture.InternalFormat.DEPTH16
                    }
                    depth = Texture.Builder()
                            .width(width).height(height).levels(1)
                            .usage(Texture.Usage.DEPTH_ATTACHMENT )
                            .format(depthbit)
                            .build(engine)
                }
                else{
                    clearDepth = false
                    depth = sharedDepth
                }

                view.depthPrepass = View.DepthPrepass.DISABLED
                view.dithering = View.Dithering.TEMPORAL
                view.isPostProcessingEnabled = true
                if ( hasAnti){
                    view.antiAliasing = View.AntiAliasing.FXAA
                    view.sampleCount = 4
                }
                else{
                    view.antiAliasing = View.AntiAliasing.NONE
                    view.sampleCount = 1
                }
                view.toneMapping = View.ToneMapping.ACES

               view.renderTarget = RenderTarget.Builder()
                       .texture(RenderTarget.AttachmentPoint.COLOR, color)
                       .texture(RenderTarget.AttachmentPoint.DEPTH, depth)
                       .build(engine)

**Comment by geroge-d** [comment]
Could you please give me a hint why to ignore view clear flag for depth buffer in the method FRenderer::renderJob.
The code blew is the place where filament ignore the view depth clear flag 
 TargetBufferFlags clearFlags = (TargetBufferFlags(viewClearFlags) & TargetBufferFlags::COLOR)
                                   | TargetBufferFlags::DEPTH;

**Comment by ymhdcat** [comment]
Hello, I am also facing the same issue when trying to share depth texture between render targets. Could anyone share some hint how to achieve this? Thanks.

**Comment by geroge-d** [comment]
@pixelflinger hi ,could you please give some information about how to share depth buffer between render pass. thanks in advance

**Comment by prideout** [comment]
Depth is unconditionally cleared for every `RenderTarget`.

Color clears for offscreen targets had an issue which will be fixed in the following PR.

https://github.com/google/filament/pull/3276

**Comment by pixelflinger** [comment]
We now keep the depth target if it also has the SAMPLEABLE usage bit set.
