### ISSUE TITLE
Frame drops on Qualcomm XR1 (Adreno 615)

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1702]
[I'm looking for a steer on how to investigate this issue. It feels like a bug somewhere in the driver perhaps, but it may equally be a bug in my understanding.]

I'm running the textured-object sample on a Qualcomm XR1 device and I'm seeing about 60 FPS out of a possible 73. The _beginFrame_ method is returning false in the case of the dropped frames and if I [run systrace](https://github.com/google/filament/files/3658468/mynewtrace.html.zip) it appears the **FrameEngine::loop** is spending a long time in the _execute_ function, but this is where my understand becomes a bit hazy. Is this where it sends commands to the GPU via the driver module? If so, I would have expected that to be quick.

Running the same code on a SD 845 phone (which has an Adreno 630 GPU) I don't get any frame drops. I can see the same long execute period in systrace, but it's quick enough not to blow the frame budget.

I see no frame drops on the Exynos 8895 (Mali-G71), which is technically inferior in every way, but is able to deliver 73 FPS with no drops. I can't get a comparison systrace as I don't have root access.

The only other rooted chipset I have access to is the RK3288, which manages about 47 FPS and also spends time in the FrameEngine::loop, but in this case I can see it is stuck in eglSwapBuffers > queueBuffer.

**Comment by romainguy** [comment]
Are you scheduling frames at vsync? Where does your possible 73 fps come from btw? It's oddly specific.

**Comment by rawnsley** [comment]
The panel in the device is 73Hz and I'm running the textured-object demo pretty much as is except for the following crude modification to dump frame information:

    // FPS Counters
    var frameCount = 0
    var renderedFrames = 0
    var lastReportTimeNanos = 0L

    inner class FrameCallback : Choreographer.FrameCallback {
        override fun doFrame(frameTimeNanos: Long) {
            // Schedule the next frame
            choreographer.postFrameCallback(this)

            // This check guarantees that we have a swap chain
            if (uiHelper.isReadyToRender) {
                // If beginFrame() returns false you should skip the frame
                // This means you are sending frames too quickly to the GPU
                if (renderer.beginFrame(swapChain!!)) {
                    renderer.render(view)
                    renderer.endFrame()
                    ++renderedFrames
                }
            }
            ++frameCount
            if(frameTimeNanos - lastReportTimeNanos > 1_000_000_000) {
                Log.i("APP", "FPS: $renderedFrames / $frameCount")
                lastReportTimeNanos = frameTimeNanos
                frameCount = 0
                renderedFrames = 0
            }
        }
    }

**Comment by romainguy** [comment]
Is Choreographer invoked at 73 fps? The execute function is where filament talks to the GPU, it's typically the slow part. What's likely is that you are just waiting for the GPU to be done for the previous frame. A good solution is to turn on dynamic resolution to adapt the work load to the device's capabilities.

**Comment by rawnsley** [comment]
Yes, the Choreographer is invoked at 73 FPS reliably.

Dynamic resolution is an option, but it feels like these GPUs should eat the textured-object sample for breakfast. They bench over ten times faster than the RK3288 on things like GLBench for example.

**Comment by romainguy** [comment]
What resolution are you rendering at? You should also check for thermal throttling etc.

**Comment by rawnsley** [comment]
Resolution 2560 x 1440.

CPU speed was my first thought actually because it bit me on the RK3288 - frames would gradually get slower as the CPU ran down. I'm pretty sure it's not that in this case as I've fixed the scheduler to "performance" for both the big and little cores. In runs before I made the change I could see the CPU speed changing in systrace, but actually the effect on the result wasn't significant. Once I changed to _performance_ systrace stopped reporting the rate (because it didn't change?), but ADB showed it was at max.

**Comment by rawnsley** [comment]
I dug into the FrameEngine::loop code in more detail by changing [this line](https://github.com/google/filament/blob/master/filament/backend/src/opengl/OpenGLDriver.cpp#L54) to be:

`#   define DEBUG_MARKER() SYSTRACE_CALL();
`

These debug markers are already strategically placed in areas of interest and the additional systrace output highlighted the main problem area: _glClear_ is taking a long time. In some cases over 12ms, which nearly the whole frame budget.

When I checked the code I noticed (with some excitement) that there are two paths for clearing the viewport: _clearWithGeometryPipe_ and _clearWithRasterPipe_. The former being specifically to address Adreno related performance issues. It isn't being actually being called in this case because _respectScissor_ is false, but even when I forced it to take that path the performance was no better. Both systraces [are attached](https://github.com/google/filament/files/3662917/systraces.zip) for reference.

Am I reading this wrong or is the Adreno 615 really that slow at clearing the viewport? Could it be a driver bug?

**Comment by romainguy** [comment]
I doubt it's a performance bug, it's probably that the GPU is taking too long to render the frames and the first operation that actually does something is waiting on a buffer to be released.

**Comment by rawnsley** [comment]
If I issue a _glFlush_ just before the _glClear_, the flush is very quick (<1ms) and the clear is still slow. Does this rule out pending operations causing the problem?

**Comment by romainguy** [comment]
The flush doesn't guarantee that it'll wait for an available buffer.

**Comment by rawnsley** [comment]
What if you started the buffer clear as soon as you have swapped buffers for the previous frame to get a jump on the rendering of the next frame? It doesn't even really start sending commands until a third of the frame is rendered. I realise I might be simplifying the situation somewhat.

Unrelated to that, but possibly useful for testing: this is the same GPU that is in the Pixel 3a in case you have one hanging around the office.

**Comment by romainguy** [comment]
We don't know if the app will want to clear though. Also it doesn't help at all since it'll block until the GPU is done. And the GPU won't be done faster.

**Comment by pixelflinger** [comment]
Note that our "frameskipper" assumes 16.6ms frames, but with your 73Hz display, it's 13.6, I wonder if this causes problems. For example, if the GPU takes 15ms, we're going to think that it finished in time, but in fact it didn't.

We noticed that glClear seems to be handled  specially in qualcomm's drivers -- this is usually where the driver tries to get a new buffer from the system, and that can block if none is available (for instance if the CPU runs ahead of the GPU).

It seems to me that for some reason, the GPU runs behind.

I have a theory though -- Qualcomm does some aggressive GPU clock scaling in order to consume less power while still "fitting" within 16ms. So the less you do with the GPU the slower it runs, but they try to keep it fast enough to hit 60fps. Problem is... your display runs at 73Hz and I wonder if your driver has been adjusted for that. It's possible that in your case, the GPU is too aggressively clocked down and tries to hit 60fps no matter what you do; it'll always be too slow.
If I'm right, this would be a driver / device configuration bug.

**Comment by rawnsley** [comment]
@pixelflinger @romainguy They are all good suggestions and I'll look into them. It seems that the problem is unlikely to be a Filament bug so I'll close this issue. Thanks for your help.
