### ISSUE TITLE
Unexplained "sqr" function in documentation

### ISSUE THREAD

**Issue by tombsar** [google/filament#171]
Section 4.10.1, listing 15 (https://google.github.io/filament/Filament.md.html#listing_anisotropicbrdf) makes use of a function `sqr` which is not explained in the text. Please consider changing this code example to be more explicit; my first guess was that it was a typo for `sqrt`, rather than a utility function for squaring the value.

(Additionally, it looks as though the function is actually called `sq` in the codebase).

**Comment by tombsar** [comment]
I suggest either `pow2` (consistent with `pow5`), or re-writing the code snippet to avoid its usage altogether.

**Comment by romainguy** [comment]
I'll add a comment in the code snippet explaining what `sq` does.
