### ISSUE TITLE
Rendering transparent materials (e.g. windows)

### ISSUE THREAD

**Issue by roxlu** [google/filament#1710]
I'm wondering what the recommended approach is to render a glass (window) material? 
 
I've read the section on "5.5.1 Transparency" which shows two calls to `evaluateDiffuseLighting()` and `evaluateSpecularLighting()` and I assume these are user supplied functions. 

I also see a  `using BlendingMode = filament::BlendingMode;` in `Material.h` and a `getTransparencyMode()`.  I was looking for a`setTransparencyMode()` but I think that is not the correct approach ;-)

What is the recommended way to create a transparent material from code?

**Comment by romainguy** [comment]
The documentation for materials is at https://google.github.io/filament/Materials.md.html

You can also look at the documentation of the filamat library if you want to generate materials at runtime.
