### ISSUE TITLE
Release 1.4.0 is missing Windows assets (filament-20190930-windows.tgz)

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#1711]
The new 1.4.0 release seems to have assets for all platforms except Windows.  I don't see the expected **filament-20190930-windows.tgz**

**Comment by prideout** [comment]
We know :)  We're investigating

**Comment by prideout** [comment]
Fixed, the release now has `filament-20191001-windows.tgz`

This was built from 769f1db011fa4d2fbe6526abb3589bb9e9e2154f.
