### ISSUE TITLE
AnimatedTriangle.gltf does not rotate correctly

### ISSUE THREAD

**Issue by cx20** [google/filament#1716]
**Describe the bug**
I tried to create a display sample of [glTF model](https://github.com/cx20/gltf-test/tree/master/tutorialModels/AnimatedTriangle/glTF) by filament v1.4.0 with [gltf-test](https://github.com/cx20/gltf-test).
However, the model does not seem to rotate as expected.

**To Reproduce**
[glTF/AnimatedTriangle.gltf + filament result:](https://rawcdn.githack.com/cx20/gltf-test/9ea9bec9e1255b80e207c730baa39a70d2b32514/examples/filament/index.html?category=tutorialModels&model=AnimatedTriangle&scale=1&type=glTF)
![AnimatedTriangle](https://user-images.githubusercontent.com/1833979/65970033-bf7c3780-e4a0-11e9-8ac1-67fe447bd363.gif)

**Expected behavior**
![expected_screenshot](https://user-images.githubusercontent.com/1833979/65970076-d02cad80-e4a0-11e9-9c90-ead5bbc0991e.gif)

This model is expected to rotate seamlessly.
https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_006_SimpleAnimation.md

**Desktop (please complete the following information):**
 - OS: Windows 10 + Chrome 77
 - GPU: Intel HD Graphics 520
 - Backend: WebGL/ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)

**Comment by prideout** [comment]
Thanks!  This is probably occurring in the last .25 seconds, when we slerp between the last quat and the first quat -- we aren't taking the shortest path between these two orientations.

This is my fault: when I fixed a NaN issue, I probably broke this corner case.  We take an `abs` at the top of our slerp implementation, which obviates the check at the bottom.  Will fix and add a unit test.

**Comment by cx20** [comment]
Thanks, I have confirmed that AnimatedTriangle.gltf rotates correctly with the latest version of Filament.
[glTF/AnimateTriangle.gltf + filament result:](https://rawcdn.githack.com/cx20/gltf-test/cc0716570ccf1fc9b96f6bb9b8d3285d19aa8b08/examples/filament/index.html?category=tutorialModels&model=AnimatedTriangle&scale=1&type=glTF)

![AnimatedTriangle](https://user-images.githubusercontent.com/1833979/66049140-ce78ed80-e565-11e9-91e1-7be23ed0d6a2.gif)

I updated the status of [gltf-test](https://github.com/cx20/gltf-test#simple-models-for-testing-individual-features).
![image](https://user-images.githubusercontent.com/1833979/66049094-b903c380-e565-11e9-8807-b4dd65900d88.png)
