### ISSUE TITLE
Matc and Matinfo don't seem to work on windows

### ISSUE THREAD

**Issue by Steve132** [google/filament#1728]
**Describe the bug**
It doesn't seem to be possible to use matc/matinfo on windows 10 x64.   The file generated by matc cannot be opened with matinfo.  Perhaps the file is being written/read in binary?

**To Reproduce**
1. Download and extract [windows build x64 release 1.40](https://github.com/google/filament/releases/download/v1.4.0/filament-20191001-windows.tgz)
2. Download [a sample material](https://github.com/google/filament/blob/master/samples/materials/sandboxLit.mat)
3.  

    > bin\matc.exe -o sandboxLit.filamat sandboxLit.mat
    > bin\matinfo.exe sandboxLit.filamat
    Could not read the source material.

**Expected behavior**
I expected output of any kind from matinfo

**Screenshots**
The above text reproduces the issue

**Desktop (please complete the following information):**
 - OS: Windows 10 Home x64
 - GPU: NV 770m (but it's a tool issue)
 - Backend: (Both, but it's a tool issue)

**Comment by romainguy** [comment]
Files generated by `matc` are binary, not plain text. Could you send me the `sandboxLit.filamat` file generated by your `matc` please?

**Comment by bejado** [comment]
Strange, but I'm able to reproduce with several of our sample app materials.

**Comment by Steve132** [comment]
Yep that's the fix I meant!  The file was binary and it was opening as text.
