### ISSUE TITLE
BoxAnimated.gltf animation is different from the expected

### ISSUE THREAD

**Issue by cx20** [google/filament#1730]
**Describe the bug**
I tried to display [BoxAnimated.gltf](https://github.com/cx20/gltf-test/tree/master/sampleModels/BoxAnimated) with the latest version of Filament.
However, the box rotation seems a little different from the expected result.

![image](https://user-images.githubusercontent.com/1833979/66051088-501e4a80-e569-11e9-9831-8c62c1b1126c.png)

**To Reproduce**
[glTF/BoxAnimated.gltf + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/9b59833bbfe09b2025477b33b1b58cd96d390e91/examples/filament/index.html?category=sampleModels&model=BoxAnimated&scale=0.5&type=glTF)
![BoxAnimated](https://user-images.githubusercontent.com/1833979/66050420-27e21c00-e568-11e9-8960-1ad7f6ea4bda.gif)

**Expected behavior**
![BoxAnimated_screenshot](https://user-images.githubusercontent.com/1833979/66050474-3fb9a000-e568-11e9-9be3-b49822c855c3.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 + Chrome 77
 - GPU: Intel HD Graphics 520
 - Backend: WebGL/ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)

**Comment by romainguy** [comment]
@cx20 A fix for rotations went in yesterday, have you been able to try with a recent build from the master branch?

**Comment by cx20** [comment]
@romainguy I used the following linked modules for testing.
![image](https://user-images.githubusercontent.com/1833979/66059295-c4abb600-e576-11e9-8dc5-9129616263d5.png)
https://filament-build.storage.googleapis.com/badges/build_link_web.html

**Comment by cx20** [comment]
Since the rotation of [AnimatedTriangle.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedTriangle) is displayed correctly in the latest version of Filament, there seems to be another problem with the display of [BoxAnimated.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxAnimated).

**Comment by cx20** [comment]
It is unclear whether this is related to this problem, but the animation of [InterpolationTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/InterpolationTest) is also incorrect.
[glTF/InterpolationTest.gltf + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/9b59833bbfe09b2025477b33b1b58cd96d390e91/examples/filament/index.html?category=tutorialModels&model=InterpolationTest&scale=0.2&type=glTF)
![InterpolationTest](https://user-images.githubusercontent.com/1833979/66061569-afd12180-e57a-11e9-843e-4fc0df925222.gif)

Expected result:
![InterpolationTest_screenshot](https://user-images.githubusercontent.com/1833979/66061639-cecfb380-e57a-11e9-996b-ac6a9c69332e.gif)

**Comment by rawnsley** [comment]
> It is unclear whether this is related to this problem, but the animation of [InterpolationTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/InterpolationTest) is also incorrect.
> [glTF/InterpolationTest.gltf + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/9b59833bbfe09b2025477b33b1b58cd96d390e91/examples/filament/index.html?category=tutorialModels&model=InterpolationTest&scale=0.2&type=glTF)
> ![InterpolationTest](https://user-images.githubusercontent.com/1833979/66061569-afd12180-e57a-11e9-843e-4fc0df925222.gif)
> 
> Expected result:
> ![InterpolationTest_screenshot](https://user-images.githubusercontent.com/1833979/66061639-cecfb380-e57a-11e9-996b-ac6a9c69332e.gif)

It looks like only the first animation is running. You have to activate all of them to see the expected result.

**Comment by cx20** [comment]
> It looks like only the first animation is running. You have to activate all of them to see the expected result.

@rawnsley  Thanks. I confirmed that there are multiple animations in InterpolationTest.gltf in [Babylon.js Inspector](https://sandbox.babylonjs.com).
![image](https://user-images.githubusercontent.com/1833979/66128334-a1414380-e628-11e9-8bcd-c4f95973d748.png)

I want to find out how to activate multiple animations in Filament.

**Comment by cx20** [comment]
There was no problem with the display of [InterpolationTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/InterpolationTest). My usage was wrong.
[glTF/InterpolationTest.gltf + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/ac9715656447fac03ec2f18334e112f419d6114e/examples/filament/index.html?category=tutorialModels&model=InterpolationTest&scale=0.2&type=glTF)
![InterpolationTest](https://user-images.githubusercontent.com/1833979/66136556-a0171300-e636-11e9-8c71-92993cbe1299.gif)

**Comment by prideout** [comment]
> I want to find out how to activate multiple animations in Filament.

The SimpleViewer demo uses radio buttons instead of checkboxes, but any client app can apply multiple animations by calling `gltfio::Animator::applyAnimation` multiple times, once for each animation.

**Comment by cx20** [comment]
@prideout Thanks. I found a place using animation in SimpleViewer.
https://github.com/google/filament/blob/master/libs/gltfio/include/gltfio/SimpleViewer.h#L317-L319

BTW, I want to run SimpleViewer. Can I download EXE? Do I have to build it myself?

**Comment by prideout** [comment]
To play with SimpleViewer, you'll need to perform a native build by following the instructions in our root-level README.  The actual generated executable is `out/cmake-release/samples/gltf_viewer`.

**Comment by cx20** [comment]
I tried checking the data structure of [BoxAnimated.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxAnimated).
It seems that the rotation is correct between `1.25` seconds and `2.5` seconds.
![image](https://user-images.githubusercontent.com/1833979/66157603-1891ca00-e65f-11e9-996b-25f8179aeaf6.png)

I think that Filament is not correct because it continues to rotate after `2.5` seconds.
![BoxAnimated](https://user-images.githubusercontent.com/1833979/66050420-27e21c00-e568-11e9-8960-1ad7f6ea4bda.gif)

**Comment by prideout** [comment]
Nice catch, thanks for another excellent bug report!

It's true that `Animator` currently assumes that all samplers are looping, I'll fix this.

**Comment by cx20** [comment]
I have confirmed that the latest version of Filament has solved the problem of model rotation.
[BoxAnimated.gltf + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/c341a2a10c88f0af40fb6aafa9fc0554659318d3/examples/filament/index.html?category=sampleModels&model=BoxAnimated&scale=0.5&type=glTF)
![BoxAnimated](https://user-images.githubusercontent.com/1833979/66250656-85e94c00-e780-11e9-9277-21945624826d.gif)
