### ISSUE TITLE
Refraction

### ISSUE THREAD

**Issue by malik-ashter** [google/filament#1731]
**Is your feature request related to a problem? Please describe.**
Hello everyone. I am creating a gemstone using filament in Android. But I cant find anything related to refraction in the material guide. Can you please tell me if it is possibel at the moment to add refraction to the object and how can I add it?

**Describe the solution you'd like**
If it is not possible at the moment, do you have any plan to add it?

**Describe alternatives you've considered**

**OS and backend**
Android

**Comment by romainguy** [comment]
This feature is currently not supported, we need to finish work on the frame graph first. You can however do it yourself if you want by using an opaque material and sampling your background cubemap for instance using the reflected vector.

**Comment by romainguy** [comment]
Refraction is now supported. The feature isn't entirely finished yet as we only support refraction of the cubemap but screen-space refraction is coming. See https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/blendingandtransparency:refractionmode and https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/blendingandtransparency:refractiontype.
