### ISSUE TITLE
Bear model does not display correctly

### ISSUE THREAD

**Issue by cx20** [google/filament#1749]
**Describe the bug**
I tried to display a [bear model](https://sketchfab.com/3d-models/bear-on-balloons-f2f13a8630004b1c82730d8b9ffa0e1f) in Filament.
However, the bear model disappears gradually.

**To Reproduce**
[Bear model + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/c341a2a10c88f0af40fb6aafa9fc0554659318d3/examples/filament/index.html?url=https://cdn.rawgit.com/cx20/jsdo-static-contents/8a3e977a/models/gltf/2.0/BearOnBalloons/scene.gltf&scale=0.5)
![BearOnBalloons gif](https://user-images.githubusercontent.com/1833979/66257018-1a7a9b00-e7cf-11e9-8214-a7dd64b5e255.gif)

**Expected behavior**
![image](https://user-images.githubusercontent.com/1833979/66257110-fe2b2e00-e7cf-11e9-9e8b-2ca2af9268cd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 + Chrome 77
 - GPU: Intel HD Graphics 520
 - Backend: WebGL/ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)

**Comment by cx20** [comment]
I traced WebGL using [Spectro.js](https://spector.babylonjs.com) of Chrome extension, I noticed that there was a place where `null` was passed to the uniform variable.

![image](https://user-images.githubusercontent.com/1833979/66332671-37020900-e970-11e9-9b2c-4a96ff15f171.png)

I commented out the `updateBoneMatrices()` function call as a test and confirmed that the model was displayed without disappearing.
```js
//this.animator.updateBoneMatrices();
```

![image](https://user-images.githubusercontent.com/1833979/66332175-12596180-e96f-11e9-9547-3c5e860d6028.png)

This phenomenon seems to be a problem of skinning animation processing.

**Comment by prideout** [comment]
Thanks for another great bug report.  Turns out that our `slerp` function is producing NaN's again. 😭 

(Interesting that C++ NaN's are showing up as null in JavaScript-land.)

**Comment by cx20** [comment]
Thanks! I have confirmed that this issue has been resolved in the latest version of Filament.
[Bear model + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/c283ae4d6a220b40dea64a2bc44938f40e02bb3e/examples/filament/index.html?url=https://cdn.rawgit.com/cx20/jsdo-static-contents/8a3e977a/models/gltf/2.0/BearOnBalloons/scene.gltf&scale=0.5)
![BearOnBalloons](https://user-images.githubusercontent.com/1833979/66487803-e7dee400-eae7-11e9-9ccb-83f36d0fd788.gif)
