### ISSUE TITLE
MatDbg link error on PC - Unresolved external symbols MATDBG_RESOURCES_*

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#1759]
Beginning with version 1.4.0, getting link errors when linking against release 1.4.0 libraries (debug configuration).  See attached file (FilamentLinkErrors.txt) for link error text.

The linker is looking for (among others) these symbols:
   MATDBG_RESOURCES_INDEX_SIZE
   MATDBG_RESOURCES_INDEX_OFFSET
   MATDBG_RESOURCES_PACKAGE
   MATDBG_RESOURCES_SCRIPT_SIZE
   MATDBG_RESOURCES_SCRIPT_OFFSET
   ... and more

Additionally, it is missing some CivetServer::addHandler() and other CivetServer functions.

If I were to build the libraries myself (which I'm currently not doing) and define SERVE_FROM_SOURCE_TREE, it might change the nature of things, but I haven't looked into what else might be required.

Not sure how to resolve this, so I am rolling back to a previous release for now.

 - OS: Windows 10
 - Backend: OpenGL

[FilamentLinkErrors.txt](https://github.com/google/filament/files/3704781/FilamentLinkErrors.txt)

**Comment by prideout** [comment]
Are you linking in `matdbg.lib`?  It's included in the mdd and mtd folders.

**Comment by BStringhamVRSK** [comment]
I am linking matdbg.lib.  It's that library that generates the first set of missing link symbols.  I've tried to see if I've made a mistake on my end (and maybe I have), but I can't find one.

**Comment by bejado** [comment]
Thanks for the report, I'm able to reproduce on Windows. Note that `matdbg` is only present in debug builds so you should be be able to link against either of the release variants for the time-being.

**Comment by bejado** [comment]
Note that this isn't Windows-specific, these link errors occur on any platform when linking against debug builds of Filament.

**Comment by bejado** [comment]
@BStringhamVRSK The issue should be fixed now, but you'll need to wait until the next release to get updated binaries.

**Comment by BStringhamVRSK** [comment]
That was quick!  Thank you.
By the way, is there a forum site somewhere where Filament users can talk about things that don't rise to the level of bugs?

**Comment by bejado** [comment]
None that I'm aware of, but feel free to open an issue for any other problems you face.
