### ISSUE TITLE
Camera problem with small scale in filament.js

### ISSUE THREAD

**Issue by elalish** [google/filament#1766]
**Describe the bug**
For small scenes, when I set the near value to something small, I'm getting the camera zooming in (narrowing the field of view?). Perhaps a precision issue or some kind of clamp?

**To Reproduce**
1) Load the khronos-BoomBox (which is on the order of 0.01 in size).
2) Put the camera a x=0.03, looking at the origin, verticalFov=45 degrees.
3) Put the far plane at 1 and the near plane and 0.01 and see expected framing (the whole object).
4) Put the far plane at 0.06 and the near plane at 0.06/1000, and note how the framing has changed, even though the near and far plane still surround the object.

**Expected behavior**
The framing of the shot should not depend on the near and far plane values.

**Screenshots**
Correct:
![image](https://user-images.githubusercontent.com/1649964/66614221-0216d180-eb7d-11e9-8e8a-1d5fc7a1a059.png)
Incorrect:
![image](https://user-images.githubusercontent.com/1649964/66614297-4d30e480-eb7d-11e9-9a22-3f92cff46445.png)

**Comment by romainguy** [comment]
0.06/1000 won't fit in fp16 but we don't use the projection matrix in fp16 computations in the shader. I don't recall us doing anything special with the near and far plane. Do you have shadow maps on btw? They're the only thing that looks at near/far planes.

**Comment by elalish** [comment]
No shadow maps, just an IBL. Is there a matrix inversion somewhere that could be losing precision?


________________________________

**Comment by romainguy** [comment]
We do invert it but it's done with doubles. @pixelflinger is the right person to investigate.

**Comment by romainguy** [comment]
Found the problem, we currently limit the near plane to 1mm:

```if (UTILS_UNLIKELY(projection == Projection::PERSPECTIVE && near < 1.0 / 1024.0)) {
        near = 1.0 / 1024.0; // about 1mm
    }```

But we don't validate far after we clamp near.

**Comment by elalish** [comment]
@pixelflinger Interesting; thanks for adding the warning anyway. I guess this means I shouldn't try to render a protein model in meters, which is what glTF mandates.

**Comment by elalish** [comment]
Ah, I see now, near can be arbitrarily close to zero. Awesome, thanks!
