### ISSUE TITLE
BUILD_DEMO option doesn't work: error in meshoptimizer

### ISSUE THREAD

**Issue by Reedbeta** [google/filament#1770]
Building on Windows using MSVC 19 backend. If I turn on 'BUILD_DEMO' in CMake, then I get the following error trying to generate project files:

```
CMake Error at third_party/meshoptimizer/CMakeLists.txt:37 (add_executable):
  Cannot find source file:

    demo/main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at third_party/meshoptimizer/CMakeLists.txt:37 (add_executable):
  No SOURCES given to target: demo
```

**Comment by romainguy** [comment]
What's `BUILD_DEMO` for? It's not one of our build options.

**Comment by Reedbeta** [comment]
Well, it shows up in CMake when I load the filament directory.

![image](https://user-images.githubusercontent.com/1578730/66724301-2ff85200-edd9-11e9-8eda-f24e810cd12d.png)

**Comment by romainguy** [comment]
Looks like it came from meshoptimizer. @bejado, @prideout can you get rid of this please? In general only options that start with FILAMENT_ are ours.

**Comment by bejado** [comment]
We could consider adding a section to our README that enumerates all of Filament-specific CMake options. There's a lot of "junk" CMake options from our dependencies.
