### ISSUE TITLE
Vulkan backend doesn't compile in MSVC

### ISSUE THREAD

**Issue by Reedbeta** [google/filament#1772]
I have a fresh clone of the Filament repo and I enabled FILAMENT_SUPPORTS_VULKAN in the CMake options. I'm using MSVC 2019 16.2.5, building in Debug from TNT.sln. I'm getting a lot of errors in the Vulkan backend around uses of designated initializers. I've attached the complete build log for the 'backend' project: [backend_vulkan_build_log.txt](https://github.com/google/filament/files/3722908/backend_vulkan_build_log.txt)

**Comment by romainguy** [comment]
Thanks! It's the kind of stuff we had to fix to get the rest of the codebase to compile with msvc.

**Comment by prideout** [comment]
I'll take a look at these, I think they show up as squiggles in VSCode.
