### ISSUE TITLE
ibl seems clearer in gltf-viewer than true device

### ISSUE THREAD

**Issue by beibei1998** [google/filament#1774]
hi
I run hello-gltf on my iphone 11 and gltf_viewer (without any options) on my mac, but it seems that the reflected ibls are not the same clear. ???

screenshot of gltf_viewer:
![image](https://user-images.githubusercontent.com/43979867/66752680-8ee6c580-eec4-11e9-9c11-0b52d9bcace2.png)

screenshot of iphone11
![IMG_90856EA03613-1](https://user-images.githubusercontent.com/43979867/66752744-c48bae80-eec4-11e9-8987-34a6eb632d2b.jpeg)

**Comment by bejado** [comment]
@beibei1998 Sorry, I'm not sure what the issue is. Please feel free to reopen with more details.

**Comment by beibei1998** [comment]
what I want to ask is that why it seems different between gltf_viewer and true device about the environment that reflected by the model. You can see that they are not the same clear.
