### ISSUE TITLE
Get OpenGL texture id from Texture instance

### ISSUE THREAD

**Issue by kaelsass** [google/filament#1784]
**Is your feature request related to a problem? Please describe.**
I'd like to create a Texture as color attachment of a render target and get the texture id from the Texture after render. Is there any way that I could get OpenGL texture id from Texture class instance?

**Comment by romainguy** [comment]
Filament supports multiple backends, not just OpenGL. In addition, all GL code runs on an internal private thread. For those two reasons it wouldn't make sense for Filament to give access to the GL texture id. Could you explain what you are trying to do?
