### ISSUE TITLE
ibl render seems diffrent between gltf_viewer and ios device 

### ISSUE THREAD

**Issue by beibei1998** [google/filament#1785]
details about #1774 :
what I want to ask is that why it seems different between gltf_viewer and true device about the environment that reflected by the model. You can see that they are not the same clear.

**Comment by beibei1998** [comment]
Is ibl compressed somewhere for iOS? or the format different?

**Comment by beibei1998** [comment]
and I have set the backend of gltf_viewer = metal

**Comment by romainguy** [comment]
I'm sorry but I still don't understand what you mean by "they are not the same clear".

**Comment by beibei1998** [comment]
sorry，i mean the clarity of the ibl reflected by the helmet is different. Observe the top of helmet carefully, u can tell the clarity difference of the environment reflected by the helmet easily.

**Comment by romainguy** [comment]
It's hard to tell the difference in your screenshots. We use the same resolution of IBL on all platforms (256^3) so it seems surprising there would be any difference at all.

**Comment by bejado** [comment]
Both the iOS sample and gltf_viewer are using the same IBL file: `third_party/environments/venetian_crossroads_2k.hdr`.

**Comment by beibei1998** [comment]
I have solved the problem by setting IBL_INTEGRATION=IBL_INTEGRATION_IMPORTANCE_SAMPLING in IndirectLight.cpp and then rebuilding...
It seems very clear on mobile phone now...

**Comment by beibei1998** [comment]
![IMG_A02EE0D6083E-1](https://user-images.githubusercontent.com/43979867/67092716-87842c80-f1e2-11e9-8455-2ea251a5c338.jpeg)
