### ISSUE TITLE
How to create multiple instance within multiple iOS MTKView?

### ISSUE THREAD

**Issue by Realitian** [google/filament#1792]
I tried to create multi instance (engine, view, scene) within multiple ios MtkView, but it failed due to following error: 
`in void utils::JobSystem::adopt():482
reason: Called adopt on a thread owned by another JobSystem (0x10d038960), this=0x11faec960!`
I guess filament restricts it's creation as one.
but, I wanted to create 3d view list in ios list viewcontroller.
How I can do it?

**Comment by romainguy** [comment]
Filament allows multiple engines, views, etc. I would however recommend you has only one engine if possible.

**Comment by Realitian** [comment]
Thanks for your recommendation.
I tested it and uploading here.
https://github.com/Realitian/filament_twoview_ios
Cheers.
