### ISSUE TITLE
cmgen usage

### ISSUE THREAD

**Issue by Realitian** [google/filament#1797]
If I have 6 hdr cubemap env map images, then how can generate IBL and skybox ktx files?
The sample used Equirectangular env map image as input, but I am not sure how can use 6 cube map images(pos/neg[x][y][z].hdr)?
Thank you in advance for let me know it.

**Comment by Realitian** [comment]
just made tool for converting from separated cross cube map to equirectangular cube map image.

**Comment by romainguy** [comment]
cmgen also accepts single file cross images.
