### ISSUE TITLE
cannot use compressed ibl texture for ios 

### ISSUE THREAD

**Issue by beibei1998** [google/filament#1798]
I found that all the compressed formats (etc, astc, dxt, pvrtc2) of ibl texture are not supported by metal. Does this mean I cannot use compressed ibl file for iOS?
But dxt, astc are supported formats of OpenGL.

**Comment by romainguy** [comment]
Metal supports ETC2, ASTC and PVRTC (and others too).

**Comment by beibei1998** [comment]
Will it be fixed in the next version of filament?
Or I need to fix it by myself if I need to use compressed texture?

**Comment by bejado** [comment]
@beibei1998 Which compressed format are you trying to use?

**Comment by beibei1998** [comment]
Thank you very much!
I have done the update and rebuilt. I used the cmgen to generate compressed ibl of etc2. But when I run the hello-gltf and change the ibl, it says:
 validateReplaceRegion:183: failed assertion `rowBytes(0) must be >= (1024).' 
and then crashed?
Are there any tips about generating compressed ibl?
below are the options I used:
 --format=ktx --size=512 --extract-blur=0.1 --compression=etc_srgb8_alpha_rgba_100

**Comment by bejado** [comment]
That sounds like a problem with the Metal backend, I'll take a closer look.

**Comment by beibei1998** [comment]
I have temporarily solved the problem by setting **bytesPerPixel** and **faceWidth** in the **MetalTexture::loadCubeImage** to change rowBytes to apply texture of etc2 (etc2_eac_rgba8).

**Comment by romainguy** [comment]
@bejado is this issue still valid?

**Comment by bejado** [comment]
This should be fixed—the Metal backend now supports ETC compression.
