### ISSUE TITLE
community support / getting started?

### ISSUE THREAD

**Issue by dakom** [google/filament#1806]
This isn't really an "issue" - so feel free to close immediately :)

In the meantime...

1. Is there a recommended place for asking one-off and getting-started type questions?
2. Are there tutorials available for using filament in VR environments?
3. Are there tutorials that discuss how to mix filament with other rendering needs, like maybe for switching to another shader for a particle emitter?

Thanks!

**Comment by prideout** [comment]
It's fine to ask questions using GitHub Issues.  Filament can be used to render particles, we have a demo for it (`point_sprites.cpp`).  We have tutorials for JavaScript clients, and plan on writing some for Java / C++.

**Comment by dakom** [comment]
Thanks!

I see the VR question is being dealt with [here](https://github.com/google/filament/issues/435) so I'll leave that for now :)

I have another getting started question:

What is the recommended workflow for getting a scene from Blender into Filament?

The JS tutorials convert a OBJ to filamesh, convert materials, and then imperatively create lights/cameras. But what if I set up a scene in Blender - do I export each object and texture image and then copy values over to code, or is there an easier way to like export a glTF or something and batch convert everything filament needs?

**Comment by prideout** [comment]
The newest version of Blender has a built-in gltf exporter, you can export (either gltf or glb) and use our `gltfio` library to load it into Filament.  See our `gltf_viewer` (c++) and `gltf-bloom` (kotlin) samples.

The filamesh format is useful for simple applications, but we should probably update our tutorials to use a glTF-based workflow.

**Comment by dakom** [comment]
my target is specifically webgl for now. does the gltfio library fit into that flow somehow?

would be great to see updated javascript tutorials that work with gltf :)

also - don't additional material settings get lost when using gltf? I see @romainguy requested clearcoat for a future gltf version [here](https://github.com/KhronosGroup/glTF/issues/1442), for example

**Comment by prideout** [comment]
For now you can look at the `helmet.html` sample to see how to use gltfio from JavaScript.

You're correct that Filament's material model isn't designed around glTF, but personally I'd still recommend glTF for your asset workflow, unless you're building something that needs customized shading.
