### ISSUE TITLE
ninja: error: loading 'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by igaurab** [google/filament#1810]
**Describe the bug**
I am trying to build filament for android using `./build.sh -p android release`.
I am getting the error `ninja: error: loading 'build.ninja': No such file or directory`
I have installed ninja using the apt install

**Screenshots**
![Screenshot from 2019-10-25 12-47-18](https://user-images.githubusercontent.com/28226423/67550220-a1af9480-f725-11e9-8e53-3a5a65a80ae4.png)

I also tried building manually. But got the following error message:
![filament-maual-build](https://user-images.githubusercontent.com/28226423/67550317-e1767c00-f725-11e9-807e-a81449432af5.png)

**Desktop (please complete the following information):**
 - OS:Linux Mint 19
 - GPU: Intel

**Comment by prideout** [comment]
Do `rm -rf out` and try again.
