### ISSUE TITLE
CString is 10x slower than std::string

### ISSUE THREAD

**Issue by anycad** [google/filament#1816]
I tested CString and std::string and found that CString is much slower than std::string when constructing and assiging.   Why do you use CString instead of std::string ?

**Benchmark**

Run on (8 X 2112 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 262K (x4)
  L3 Unified 8388K (x1)
----------------------------------------------------------
Benchmark                Time             CPU   Iterations
----------------------------------------------------------
BM_STRING             7.04 ns         7.15 ns     89600000
BM_CSTRING            69.4 ns         68.0 ns      8960000
BM_STRING_COPY        7.30 ns         7.32 ns     89600000
BM_CSTRING_COPY       70.9 ns         71.1 ns     11200000

**Testing Code**

`
static void BM_CSTRING(benchmark::State& state)
{
    for (auto _ : state) {
        using namespace utils;

        CString x("112121");
        x.c_str_safe();
    }

}
static void BM_STRING(benchmark::State& state)
{
    for (auto _ : state) {
        std::string x("112121");
        x.c_str();
    }
}

static void BM_CSTRING_COPY(benchmark::State& state)
{
    using namespace utils;
    CString x("112121");
    CString y;

    for (auto _ : state) {

        y = x;
    }

}
static void BM_STRING_COPY(benchmark::State& state)
{
    std::string x("112121");
    std::string y;
    for (auto _ : state) {

        y = x;
    }
}
BENCHMARK(BM_STRING);
BENCHMARK(BM_CSTRING);
BENCHMARK(BM_STRING_COPY);
BENCHMARK(BM_CSTRING_COPY);
BENCHMARK_MAIN();
`

**Comment by romainguy** [comment]
CString produces a lot less code than std:: string which is desirable for us since one of our goals is to keep the binary as small as possible. One of the reasons is because we don't have a short string optimization which is pretty much what you are benchmarking for. Unless this causes performance bottlenecks in the render loop this is not something we'll fix.
