### ISSUE TITLE
how to create ibl dynamiclly by using code?

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1817]
Hi guys
    We want to render dynamic scenes as IBL,but don't find any class or function , but cmgen executable program.
   Could you please give me a clue about it ? thanks in advance!

**Comment by romainguy** [comment]
You can use [`Texture::generatePrefilterMipmap()`](https://github.com/google/filament/blob/master/filament/include/filament/Texture.h#L405) to filter an IBL at runtime. Note that this is currently done on the CPU and intended to be used for low-resolution IBLs. You can also render to a texture with Filament so you should be able to render all 6 faces of a cubemap then do the filtering.

Dynamic IBLs/local probes is something we want to implement eventually, it just hasn't been a priority so far. In particular we'd like prefiltering to be done on the GPU and amortized over multiple frames.

**Comment by pixelflinger** [comment]
If you use `Texture::generatePrefilterMipmap()`, you will also have to generate the spherical harmonics yourself somehow -- we don not have a helper for that right now.

**Comment by geroge-d** [comment]
very appreciate. I'll give a try

**Comment by DrDrake** [comment]
Regarding spherical harmonics I think it may be possible to use something like this http://codeflow.org/entries/2012/aug/25/webgl-deferred-irradiance-volumes/ (shader for sh generation is here https://github.com/pyalot/webgl-deferred-irradiance-volumes/blob/master/src/illumination/harmonics.shader)

**Comment by romainguy** [comment]
You don't need this, we have a `libibl` you can use that's part of Filament now.

**Comment by DrDrake** [comment]
It will be done on CPU?

**Comment by DrDrake** [comment]
Regarding GPU implementation of environment map prefiltering in one of my project I've implement variation of this https://placeholderart.wordpress.com/2015/07/28/implementation-notes-runtime-environment-map-filtering-for-image-based-lighting/ method.

**Comment by romainguy** [comment]
Spherical harmonics are not required anymore btw, and you can use `libibl` to do the prefiltering.
