### ISSUE TITLE
Screen space ambient occlusion?

### ISSUE THREAD

**Issue by roxlu** [google/filament#1820]
I'm trying to enable SSAO and wondering what else I have to enable to get it working. Currently I have a `View` (`fila_view`) use the following:

```c++
ao.radius = 1.0;
fila_view->setAmbientOcclusionOptions(ao);
fila_view->setAmbientOcclusion(filament::View::AmbientOcclusion::SSAO);
fila_view->setPostProcessingEnabled(true);
```

**Comment by romainguy** [comment]
That's all you have to do. You don't need to enable post processing, it's on by default.

**Comment by roxlu** [comment]
Thanks @romainguy 

Do you maybe have an idea why there  is no difference in when I enable / disable AO? 

_AO Enabled:_
![filament-ao-1](https://user-images.githubusercontent.com/358809/67802954-68ac5280-fa8c-11e9-91dd-a61bed2a1343.png)

_AO Disabled:_
![filament-ao-2](https://user-images.githubusercontent.com/358809/67803010-7d88e600-fa8c-11e9-8e77-41ff499b5a8b.png)

_AO in Blender:_
![blender-ao](https://user-images.githubusercontent.com/358809/67803054-90031f80-fa8c-11e9-91bd-317d20a87b51.png)

**Comment by romainguy** [comment]
Do you mind attaching the model and IBL you are using please?

**Comment by roxlu** [comment]
@romainguy I've shared the files via e-mail.

**Comment by gitzoran** [comment]
Any wisdom for the masses? I am testing SSAO in v1.4.3 with single IBL light and default AO options. Absolutely no difference if view->setAmbientOcclusion() is called with NONE or SSAO. Stepping through the Renderer.cpp and PostProcessManager.cpp in a debugger, it seems that the code is at least attempting to do the SSAO pass.

**Comment by romainguy** [comment]
You probably need to tweak the SSAO parameters. You can easily see AO on/off in material_sandbox or gltf_viewer.

**Comment by gitzoran** [comment]
I did try the material_sandbox, enabled SSAO, moved all the sliders, and saw no difference as well. I attributed that to the app using a directional light (since the IBL light sliders also have no influence at all). Wrong assumption?

**Comment by romainguy** [comment]
SSAO will affect the IBL but not the directional light. Here's an example, with SSAO:
<img width="1136" alt="Screen Shot 2020-03-30 at 10 29 31 AM" src="https://user-images.githubusercontent.com/869684/77943025-65063d00-7271-11ea-84f3-90c61caa306f.png">

Without SSAO:
<img width="1136" alt="Screen Shot 2020-03-30 at 10 29 34 AM" src="https://user-images.githubusercontent.com/869684/77943040-69caf100-7271-11ea-9c39-b2377d1c54a3.png">

**Comment by gitzoran** [comment]
@romainguy Thank you for the quick and to-the-point response! It is very much appreciated.

I was able to replicate your results using the gltf_viewer, and later on, using the material_sandbox. At first, I did not realize that material_sandbox does not have an IBL light by default, and then tried using IBL images that were not properly converted with cmgen. Using "venetian_crossroads_2k" or "pillars_2k" IBL from the repo made all the difference. E.g. on Windows:

  ```
cd filament/out
  samples/Release/material_sandbox.exe --ibl=../docs/webgl/pillars_2k ../assets/models/cloth/cloth.obj
```

**Comment by gitzoran** [comment]
Taking a closer look at your images, I was expecting that the difference between no SSAO and SSAO would look similar to an ambient occlusion map. The difference image is too dark to see, but the inverted image is instructive (bright ares are the most darkened by SSAO):

<img width="379" alt="diffInverted" src="https://user-images.githubusercontent.com/5241437/78289642-54ef9700-74d7-11ea-8d3b-c5f5f35c8063.png">


Somewhat surprising is the SSAO effect on the unobstructed (convex) areas on the helmet near the temples and around the goggles. Even more surprising is the effect on the oxygen mask ribbed hose. Ridges are much more affected than the grooves. I would expect the opposite. Here is a closeup from:

  `samples/Release/gltf_viewer.exe ../third_party/models/FlightHelmet/FlightHelmet.gltf`

Perameter settings are visible in the images.

No SSAO:
![hoseNoSAOO](https://user-images.githubusercontent.com/5241437/78289729-76e91980-74d7-11ea-8abf-9956a0de79ee.jpg)

SAOO:
![hoseSAOO](https://user-images.githubusercontent.com/5241437/78289759-849e9f00-74d7-11ea-8257-87af799710d4.jpg)

Difference inverted, luminance only, sRBG:
![hoseDiffInvertedLuminance](https://user-images.githubusercontent.com/5241437/78289787-8cf6da00-74d7-11ea-8602-9dc26b5da40f.jpg)

**Comment by romainguy** [comment]
It's a screen space effect, it does the same thing as a static AO map except it has to deal with the limitations of doing it in screen space (including the fact that we do it at quarter resolution). It won't work well for small details. Note that you can tweak various settings for SSAO (max occluder distance search etc.).

**Comment by gitzoran** [comment]
Aah, the quarter resolution might explain the extreme pixelation and aliasing (jagged silhouettes) introduced by SSAO in the image below. Is there a setting to improve resolution? Quality is more important than speed in this case.

![pixelatedSSAO](https://user-images.githubusercontent.com/5241437/78290857-3e4a3f80-74d9-11ea-8b11-33d527b8b88b.jpg)

**Comment by romainguy** [comment]
The APIs give you control over quality. You can run the effect at full resolution and increase the number of samples.

```
    struct AmbientOcclusionOptions {
        float radius = 0.3f;    //!< Ambient Occlusion radius in meters, between 0 and ~10.
        float power = 1.0f;     //!< Controls ambient occlusion's contrast. Must be positive.
        float bias = 0.0005f;   //!< Self-occlusion bias in meters. Use to avoid self-occlusion. Between 0 and a few mm.
        float resolution = 0.5; //!< How each dimension of the AO buffer is scaled. Must be positive and <= 1.
        float intensity = 1.0;  //!< Strength of the Ambient Occlusion effect.
        QualityLevel quality = QualityLevel::LOW; //!< affects # of samples used for AO.
    };
```

**Comment by gitzoran** [comment]
Ah, resolution = 1.0 did the trick. Thank you!
