### ISSUE TITLE
Build fails on macos Catalina due to resgen segfault

### ISSUE THREAD

**Issue by ccamporesi** [google/filament#1823]
**Describe the bug**
After an update on MacOS to Catalina the build process fails. It seems most of the executables are segfaulting as well 

**To Reproduce**
Prereq: Macbook pro 2019 
1. clone git repository master
2. call ./build.sh
3. wait until crash 

**Expected behavior**
resgen should not be segfaulting

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15
 - GPU:Radeon Pro Vega 20 4 GB - Intel UHD Graphics 630 1536 MB
 - Backend: [OpenGL/Vulkan]

**Additional context**

**Comment by prideout** [comment]
Time for me to install Catalina.  Meanwhile, a call stack would be helpful -- you could trying building in debug config (`./build.sh debug`).

**Comment by ccamporesi** [comment]
Thanks for the quick reply and awesome renderer!
It seems the debug build is proceeding correctly while release does not. Just to make sure I cleanup the build repo and done it twice to confirm the issue. 
During the debug build I don't see the `Aggregating shaders` being called, so I tried to launch the resgen command for aggregating shaders from the debug build manually and it succeeded.

**Comment by EvsChen** [comment]
The same problem for me. My call stack is attached here, when running `ninja`
<details>
<summary>Output</summary>
[649/1167] Generating matdbg_resources.bin, matdbg...es.S, matdbg_resources.apple.S, matdbg_resources.h
FAILED: libs/matdbg/matdbg_resources.bin libs/matdbg/matdbg_resources.S libs/matdbg/matdbg_resources.apple.S libs/matdbg/matdbg_resources.h
cd /Users/elvischen/filament/out/cmake-release/libs/matdbg && /Users/elvischen/filament/out/cmake-release/tools/resgen/resgen -t -x /Users/elvischen/filament/out/cmake-release/libs/matdbg -p matdbg_resources /Users/elvischen/filament/libs/matdbg/web/style.css /Users/elvischen/filament/libs/matdbg/web/script.js /Users/elvischen/filament/libs/matdbg/web/index.html
/bin/sh: line 1: 88510 Segmentation fault: 11  /Users/elvischen/filament/out/cmake-release/tools/resgen/resgen -t -x /Users/elvischen/filament/out/cmake-release/libs/matdbg -p matdbg_resources /Users/elvischen/filament/libs/matdbg/web/style.css /Users/elvischen/filament/libs/matdbg/web/script.js /Users/elvischen/filament/libs/matdbg/web/index.html
[662/1167] Building CXX object third_party/libassi...p.dir/__/code/Importer/StepFile/StepFileGen1.cpp.o
ninja: build stopped: subcommand failed.
</details>

**Comment by prideout** [comment]
Thanks!  I'm installing Catalina on my personal machine and will take a look soon.

**Comment by prideout** [comment]
I can repro.
