### ISSUE TITLE
Default material renders black in filament.js

### ISSUE THREAD

**Issue by elalish** [google/filament#1828]
**Describe the bug**
glTFs with no material specified (therefore getting the default) are rendered as black, but should be grey.

**To Reproduce**
Load khronos-Triangle in filament.js

**Expected behavior**
See our fidelity test results here: https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html, for instance:
![image](https://user-images.githubusercontent.com/1649964/67972237-83d1ac00-fbcb-11e9-9ddf-8d5cb1224532.png)
model-viewer matches the screenshot supplied by khronos, while Filament is black.

Tested on Filament v1.4.1, but does not appear to be a regression.

**Comment by prideout** [comment]
Interesting, this is probably a real bug, recent versions of the glTF spec say "[the default material] will be black _unless some lighting is present in the scene_."  I'll look into it.  Thanks for the bug report!

**Comment by prideout** [comment]
Note to self: cgltf does does automatically set `baseColorFactor` to [1,1,1,1] as per the spec.

**Comment by elalish** [comment]
As a note, this scene is lit only with IBL, no spotlight.
