### ISSUE TITLE
khronos-Monster is offset in filament.js

### ISSUE THREAD

**Issue by elalish** [google/filament#1829]
**Describe the bug**
Exactly one model in the entire khronos glTF 2.0 test suite appears to be offset in filament.js. Note everything here lines up except khronos-Monster: https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html

**To Reproduce**
1) Load khronos-Monster
2) Put the camera at (0, 0, 100), looking at the origin
3) Note the model appears offset to the left and slightly up.

**Expected behavior**
The model should be centered horizontally (in X).

**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/1649964/67973266-70274500-fbcd-11e9-85cc-4ee0e42139ba.png)
Filament.js:
![image](https://user-images.githubusercontent.com/1649964/67973295-7ddcca80-fbcd-11e9-8bbe-adaf46ded9b8.png)

Tested on v1.4.1, but does not appear to be a regression.

**Comment by prideout** [comment]
Note that your screenshots are using the model's rest pose, which is significantly different from its orientation with animation applied.

The center of the asset's rest pose AABB appears to be at (-4.07, 16.08, 3.90), both according to its min/max annotations and according to Filament's built-in AABB computation.  This is also consistent with what I see after importing the model into Blender and clearing out the pose data.

By the way our glTF web sample does not auto-translate the model into the unit cube at the origin, although our `gltf_viewer` native app lets you control this behavior via the `-s` argument.

So, I think this isn't a bug...but thanks for the report.  Keep 'em coming.
