### ISSUE TITLE
khronos-TextureTransformTest fails on Chrome Linux with filament.js

### ISSUE THREAD

**Issue by elalish** [google/filament#1830]
**Describe the bug**
This is a regression in v1.4.1, as compared to v1.4.0. This test still renders fine on Chrome on MacOS, but loses texture now on Chrome Linux. They both have a set of console warnings about the meshes missing normals.

**To Reproduce**
Load khronos-TextureTransformTest in filament.js and render on Chrome Linux.
If that does not reproduce the issue, then very specifically you can build `<model-viewer>` from master and serve it locally, then go to http://127.0.0.1:8000/test/fidelity/renderers/filament/ and select khronos-TextureTransformTest from the drop-down.

**Expected behavior**
The result used to look like this:
![image](https://user-images.githubusercontent.com/1649964/67975115-c6e24e00-fbd0-11e9-9df8-6eb4c82812a9.png)
But now looks like this:
![image](https://user-images.githubusercontent.com/1649964/67975132-cea1f280-fbd0-11e9-9a76-c9042bf1a718.png)

**Desktop (please complete the following information):**
 - OS: gLinux
 - GPU: NVIDIA Quadro p1000
 - Backend: WebGL

**Comment by romainguy** [comment]
Philip were you able to repro?

**Comment by prideout** [comment]
I don't have access to my Linux machine right now, will give it a try when I have a chance.

**Comment by prideout** [comment]
```
npm install ; npm run build; npm run update-screenshots
npm run dev

**Comment by prideout** [comment]
@elalish, see my screenshot -- maybe you ran into a transient Chrome issue?  Closing for now, feel free to reopen.
