### ISSUE TITLE
When scale model with negative x, y or z, object normal is wrong

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1835]
when i scale model with negative x, the render result is wrong. it seams the Filament doesn't scale the normal value correctly

**Comment by romainguy** [comment]
Can you elaborate on what's wrong about it and what you expect the result to be!

**Comment by geroge-d** [comment]
I rendered a quad with image texture by lit model,set its four vertices normal with (0,0,1), and scale it with nagetive x , it is darker than the rendered result without any scale.  And then i reverse the normal to (0,0,-1),render it  again, with nagetive scale x, it show normaly.

**Comment by prideout** [comment]
If you scale by -1 then we'll reverse the triangle winding as per #1520, so you'll need to have `doubleSided` enabled in your material.  Does the problem still occur if you enable `doubleSided`?

**Comment by geroge-d** [comment]
> If you scale by -1 then we'll reverse the triangle winding as per #1520, so you'll need to have `doubleSided` enabled in your material. Does the problem still occur if you enable `doubleSided`?

Because our  app special requirement, we cannot enable doubleSided . We implement a workaround by reversing normal  on nagetive scale

**Comment by prideout** [comment]
Thanks, sounds like you're unblocked so I'll close this for now.  If our planar symmetry feature is causing problems, we might consider making it optional in the future -- however I think it's a fairly standard practice.
