### ISSUE TITLE
The Suzanne example doesn't work on OSX

### ISSUE THREAD

**Issue by marcofugaro** [google/filament#184]
**Describe the bug**
Suzanne example doesn't work on latest OSX. On any browser.

In the console:

![image](https://user-images.githubusercontent.com/7217420/44839961-58a6a200-ac40-11e8-9305-52aa1e956827.png)

**To Reproduce**
Open this link 
http://github.prideout.net/filament/web/suzanne.html on a OSX machine

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/7217420/44840084-a4f1e200-ac40-11e8-90d6-84dc90a20112.png)

**Comment by marcofugaro** [comment]
Sorry, it was my adblocker

**Comment by marcofugaro** [comment]
Actually it works 1 in 5 times, also disabling my adblocker

**Comment by marcofugaro** [comment]
it wasn't my adblocker, confirmed

**Comment by romainguy** [comment]
Does http://github.prideout.net/filament/web/suzanne.html work for you? It runs fine on Chrome 68 on macOS for me (not Safari).

**Comment by prideout** [comment]
I'll check for a race condition between the 3D canvas and 2D canvas initialization.  Meanwhile note that the demo requires Chrome 68.

**Comment by marcofugaro** [comment]
Yup yup, my chrome is updated. This bug is independent from browser also.

**Comment by prideout** [comment]
Hi @marcofugaro,

Regarding Chrome, I'm at a loss since we don't have an in-house repro. We use a specific element id when creating the context, and we only create the context once (in `Module.postRun`), and we only create it as a WebGL 2.0 context (never as a different type).

Maybe a Chrome extension or other tab somehow interfering.  Do *any* WebGL 2.0 examples for you?  For example, try [this page](http://webglsamples.org/WebGL2Samples/).

Regarding other browsers: we fixed a Firefox issue (not yet published) and Safari does not support WebGL 2.0 yet.

**Comment by marcofugaro** [comment]
Hey @prideout, tried yout suzanne on a clean chrome instance and the issue doesn't happen. It was probably one of my extensions. Yes the other webgl2 examples work fine.

Alright, yes on firefox there is still a blank page.

**Comment by robertoranon** [comment]
Hi, 
  for me it works on Chrome 68 on Mac but ONLY if developer tools are closed. If I open the developer tools, and try to reload Susanne, I get errors. I'm on a freshly compiled build from source code I just pulled from the repository.

**Comment by robertoranon** [comment]
Ok, nevermind: it was one of two webgl inspector extensions I was using. Deleted them, and now it's working fine.

**Comment by marcofugaro** [comment]
Yeah I had the webgl inspector extension as well

**Comment by JonathanLehner** [comment]
the url is not working.
how can I run the web examples?

**Comment by prideout** [comment]
@JonathanLehner does [this URL](https://google.github.io/filament/webgl/demo_suzanne.html) work?  what do you see your Developer Tools console?   If needed please file a new bug.
