### ISSUE TITLE
matc crash in mac

### ISSUE THREAD

**Issue by Realitian** [google/filament#1854]
release version of matc crashes in mac with Segmetation fault: 11
but, the debug version works.

**Comment by bejado** [comment]
Can you share the material definition file you're attempting to compile?

**Comment by romainguy** [comment]
Which version of filament causes the issue? Can you find the crash in macOS' Console and show it here please?

**Comment by Realitian** [comment]
The version was 6b415273bacbf75f18f7863092baa6e32b1030b3
When I build it in filament itself for Mac version, it was crashed.

The log is here.

Process:               matc [9481]
Path:                  /Users/USER/Documents/*/matc
Identifier:            matc
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [541]
Responsible:           Terminal [538]
User ID:               501

Date/Time:             2019-11-07 02:38:02.961 +0800
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Anonymous UUID:        F09D787C-D26C-8B7F-8239-520E86BDE72E


Time Awake Since Boot: 6600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [9481]

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libdyld.dylib                 	0x00007fff6e001386 stack_not_16_byte_aligned_error + 0
1   ???                           	0x00000001072804a0 vtable for glslang::TInputScanner + 16

**Comment by romainguy** [comment]
@prideout isnt this the same clang bug that resgen suffered from?

**Comment by romainguy** [comment]
This bug is specific to the compiler that ships with macOS Catalina. It should be fixed if you switch to a recent version (yours dates from early August, we fixed that bug in the past couple of weeks).

**Comment by prideout** [comment]
Yes this was likely fixed with #1837, which could happen anywhere (not just resgen)
