### ISSUE TITLE
Compatible issue in vivo Y53 Android 6.0.1

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1857]
Please see log below:
11-08 17:14:31.765 E/Filament(26908): COMPILE ERROR:
11-08 17:14:31.765 E/Filament(26908): Fragment shader compilation failed.
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:90: 'Error' : Cannot offset into the vector
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:90: 'Error' : Cannot offset into the vector
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:90: '=' :  cannot convert from '3-component vector of float' to 'float'
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:93: 'Error' : Cannot offset into the vector
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:93: 'Error' : Cannot offset into the vector
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:93: 'Error' : Cannot offset into the vector
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:93: 'constructor' : too many arguments
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:93: 'Error' : Cannot offset into the vector
11-08 17:14:31.765 E/Filament(26908): ERROR: 0:93: '*' :  w
11-08 17:14:31.765 E/Filament(26908): 1:   #version 300 es
11-08 17:14:31.765 E/Filament(26908): 2:   precision mediump float;
11-08 17:14:31.765 E/Filament(26908): 3:   precision mediump int;
11-08 17:14:31.765 E/Filament(26908): 4:   struct PostProcessInputs
11-08 17:14:31.765 E/Filament(26908): 5:   {
11-08 17:14:31.765 E/Filament(26908): 6:   vec4 color;
11-08 17:14:31.765 E/Filament(26908): 7:   };
11-08 17:14:31.765 E/Filament(26908): 8:   const vec3 _172[16] = vec3[](vec3(-0.40120899677276611328125, 0.9159870147705078125, 0.031720198690891265869140625), vec3(0.84313297271728515625, -0.537703990936279296875, 0.087920702993869781494140625), vec3(0.4575429856777191162109375, 0.889187991619110107421875, 0.01769370026886463165283203125), vec3(0.976761996746063232421875, -0.21432499587535858154296875, 0.093010701239109039306640625), vec3(-0.05964539945125579833984375, 0.998220026493072509765625, 0.026174999773502349853515625), vec3(0.704176008701324462890625, 0.710025012493133544921875, 0.107385002076625823974609375), vec3(-0.707961022853851318359375, 0.70625102519989013671875, 0.03754340112209320068359375), vec3(0.9094259738922119140625, 0.4158659875392913818359375, 0.102259002625942230224609375), vec3(0.924619972705841064453125, 0.38089001178741455078125, 0.0063620698638260364532470703125), vec3(-0.09386239945888519287109375, 0.995585024356842041015625, 0.0267156995832920074462890625), vec3(-0.905196011066436767578125, -0.4249930083751678466796875, 0.0562839992344379425048828125), vec3(0.19610400497913360595703125, 0.980583012104034423828125, 0.115615002810955047607421875), vec3(-0.7520020008087158203125, -0.65916097164154052734375, 0.0605199001729488372802734375), vec3(-0.575920999050140380859375, 0.81750500202178955078125, 0.1269100010395050048828125), vec3(0.7945950031280517578125, -0.607140004634857177734375, 0.086689300835132598876953125), vec3(0.1788440048694610595703125, 0.983877003192901611328125, 0.115860998630523681640625));
11-08 17:14:31.765 E/Filament(26908): 9:   const vec3 _317[7] = vec3[](vec3(0.9663259983062744140625, 0.257322013378143310546875, 0.0769231021404266357421875), vec3(-0.697179973125457763671875, 0.716895997524261474609375, 0.23076899349689483642578125), vec3(0.975223004817962646484375, 0.2212260067462921142578125, 0.384615004062652587890625), vec3(0.982770979404449462890625, 0.18482600152492523193359375, 0.538461983203887939453125), vec3(-0.6130549907684326171875, 0.79004001617431640625, 0.692308008670806884765625), vec3(0.997237026691436767578125, 0.074288897216320037841796875, 0.8461539745330810546875), vec3(1.0, -1.1602700169532909058034420013428e-06, 1.0));
11-08 17:14:31.765 E/Filament(26908): 10:   layout(std140) uniform FrameUniforms
11-08 17:14:31.765 E/Filament(26908): 11:   {
11-08 17:14:31.765 E/Filament(26908): 12:   highp mat4 viewFromWorldMatrix;
11-08 17:14:31.765 E/Filament(26908): 13:   highp mat4 worldFromViewMatrix;
11-08 17:14:31.765 E/Filament(26908): 14:   highp mat4 clipFromViewMatrix;
11-08 17:14:31.765 E/Filament(26908): 15:   highp mat4 viewFromClipMatrix;
11-08 17:14:31.765 E/Filament(26908): 16:   highp mat4 clipFromWorldMatrix;
11-08 17:14:31.765 E/Filament(26908): 17:   highp mat4 worldFromClipMatrix;
11-08 17:14:31.765 E/Filament(26908): 18:   highp mat4 lightFromWorldMatrix;
11-08 17:14:31.765 E/Filament(26908): 19:   highp vec4 resolution;
11-08 17:14:31.765 E/Filament(26908): 20:   highp vec3 cameraPosition;
11-08 17:14:31.765 E/Filament(26908): 21:   highp float time;
11-08 17:14:31.765 E/Filament(26908): 22:   vec4 lightColorIntensity;
11-08 17:14:31.765 E/Filament(26908): 23:   vec4 sun;
11-08 17:14:31.765 E/Filament(26908): 24:   vec3 lightDirection;
11-08 17:14:31.765 E/Filament(26908): 25:   uint fParamsX;
11-08 17:14:31.765 E/Filament(26908): 26:   vec3 shadowBias;
11-08 17:14:31.765 E/Filament(26908): 27:   float oneOverFroxelDimensionY;
11-08 17:14:31.765 E/Filament(26908): 28:   vec4 zParams;
11-08 17:14:31.765 E/Filament(26908): 29:   uvec2 fParams;
11-08 17:14:31.765 E/Filament(26908): 30:   vec2 origin;
11-08 17:14:31.765 E/Filament(26908): 31:   float oneOverFroxelDimension;
11-08 17:14:31.765 E/Filament(26908): 32:   float iblLuminance;
11-08 17:14:31.765 E/Filament(26908): 33:   float exposure;
11-08 17:14:31.765 E/Filament(26908): 34:   float ev100;
11-08 17:14:31.765 E/Filament(26908): 35:   vec3 iblSH[9];
11-08 17:14:31.765 E/Filament(26908): 36:   vec4 userTime;
11-08 17:14:31.765 E/Filament(26908): 37:   vec2 iblMaxMipLevel;
11-08 17:14:31.765 E/Filament(26908): 38:   vec2 padding0;
11-08 17:14:31.765 E/Filament(26908): 39:   vec3 worldOffset;
11-08 17:14:31.765 E/Filament(26908): 40:   float padding1;
11-08 17:14:31.765 E/Filament(26908): 41:   vec4 padding2[15];
11-08 17:14:31.765 E/Filament(26908): 42:   } frameUniforms;
11-08 17:14:31.765 E/Filament(26908): 43:   layout(std140) uniform MaterialParams
11-08 17:14:31.765 E/Filament(26908): 44:   {
11-08 17:14:31.765 E/Filament(26908): 45:   vec4 resolution;
11-08 17:14:31.765 E/Filament(26908): 46:   float radius;
11-08 17:14:31.765 E/Filament(26908): 47:   float invRadiusSquared;
11-08 17:14:31.765 E/Filament(26908): 48:   float projectionScaleRadius;
11-08 17:14:31.765 E/Filament(26908): 49:   float bias;
11-08 17:14:31.765 E/Filament(26908): 50:   float power;
11-08 17:14:31.765 E/Filament(26908): 51:   int maxLevel;
11-08 17:14:31.765 E/Filament(26908): 52:   } materialParams;
11-08 17:14:31.765 E/Filament(26908): 53:   uniform highp sampler2D materialParams_depth;
11-08 17:14:31.765 E/Filament(26908): 54:   in highp vec4 variable_vertex;
11-08 17:14:31.765 E/Filament(26908): 55:   layout(location = 0) out vec4 fragColor;
11-08 17:14:31.765 E/Filament(26908): 56:   in highp vec2 vertex_uv;
11-08 17:14:31.765 E/Filament(26908): 57:   PostProcessInputs _1080;
11-08 17:14:31.765 E/Filament(26908): 58:   vec2 _1087;
11-08 17:14:31.765 E/Filament(26908): 59:   void main()
11-08 17:14:31.765 E/Filament(26908): 60:   {
11-08 17:14:31.765 E/Filament(26908): 61:   PostProcessInputs _1033 = _1080;
11-08 17:14:31.765 E/Filament(26908): 62:   _1033.color = vec4(1.0);
11-08 17:14:31.765 E/Filament(26908): 63:   highp float _649 = -frameUniforms.clipFromViewMatrix[3].z;
11-08 17:14:31.765 E/Filament(26908): 64:   highp float _655 = _649 / min(-5.9604644775390625e-08, ((texture(materialParams_depth, variable_vertex.xy, 0.0).x * 2.0) - 1.0) + frameUniforms.clipFromViewMatrix[2].z);
11-08 17:14:31.765 E/Filament(26908): 65:   vec2 _664 = (variable_vertex.xy * 2.0) - vec2(1.0);
11-08 17:14:31.765 E/Filament(26908): 66:   highp vec2 _1039 = _1087;
11-08 17:14:31.765 E/Filament(26908): 67:   _1039.x = _664.x * frameUniforms.viewFromClipMatrix[0].x;
11-08 17:14:31.765 E/Filament(26908): 68:   highp vec2 _1043 = _1039;
11-08 17:14:31.765 E/Filament(26908): 69:   _1043.y = _664.y * frameUniforms.viewFromClipMatrix[1].y;
11-08 17:14:31.765 E/Filament(26908): 70:   highp vec3 _685 = vec3(_1043 * (-_655), _655);
11-08 17:14:31.765 E/Filament(26908): 71:   vec2 _703 = variable_vertex.xy + vec2(materialParams.resolution.z, 0.0);
11-08 17:14:31.765 E/Filament(26908): 72:   vec2 _707 = variable_vertex.xy + vec2(0.0, materialParams.resolution.w);
11-08 17:14:31.765 E/Filament(26908): 73:   highp float _744 = _649 / min(-5.9604644775390625e-08, ((texture(materialParams_depth, _703, 0.0).x * 2.0) - 1.0) + frameUniforms.clipFromViewMatrix[2].z);
11-08 17:14:31.765 E/Filament(26908): 74:   vec2 _753 = (_703 * 2.0) - vec2(1.0);
11-08 17:14:31.765 E/Filament(26908): 75:   highp vec2 _1049 = _1087;
11-08 17:14:31.765 E/Filament(26908): 76:   _1049.x = _753.x * frameUniforms.viewFromClipMatrix[0].x;
11-08 17:14:31.765 E/Filament(26908): 77:   highp vec2 _1053 = _1049;
11-08 17:14:31.765 E/Filament(26908): 78:   _1053.y = _753.y * frameUniforms.viewFromClipMatrix[1].y;
11-08 17:14:31.765 E/Filament(26908): 79:   highp float _799 = _649 / min(-5.9604644775390625e-08, ((texture(materialParams_depth, _707, 0.0).x * 2.0) - 1.0) + frameUniforms.clipFromViewMatrix[2].z);
11-08 17:14:31.765 E/Filament(26908): 80:   vec2 _808 = (_707 * 2.0) - vec2(1.0);
11-08 17:14:31.765 E/Filament(26908): 81:   highp vec2 _1059 = _1087;
11-08 17:14:31.765 E/Filament(26908): 82:   _1059.x = _808.x * frameUniforms.viewFromClipMatrix[0].x;
11-08 17:14:31.765 E/Filament(26908): 83:   highp vec2 _1063 = _1059;
11-08 17:14:31.765 E/Filament(26908): 84:   _1063.y = _808.y * frameUniforms.viewFromClipMatrix[1].y;
11-08 17:14:31.765 E/Filament(26908): 85:   uint _848 = (uint(gl_FragCoord.x) & 3u) + ((uint(gl_FragCoord.y) & 3u) * 4u);
11-08 17:14:31.765 E/Filament(26908): 86:   float _1082;
11-08 17:14:31.765 E/Filament(26908): 87:   _1082 = 0.0;
11-08 17:14:31.765 E/Filament(26908): 88:   for (uint _1081 = 0u; _1081 < 7u; )
11-08 17:14:31.765 E/Filament(26908): 89:   {
11-08 17:14:31.765 E/Filament(26908): 90:   float _962 = _317[_1081].z + _172[_848].z;
11-08 17:14:31.765 E/Filament(26908): 91:   float _969 = _962 * _962;
11-08 17:14:31.765 E/Filament(26908): 92:   float _877 = max(1.0, _969 * (-(materialParams.projectionScaleRadius / _655)));
11-08 17:14:31.765 E/Filament(26908): 93:   ivec2 _883 = ivec2(variable_vertex.xy * materialParams.resolution.xy) + ivec2(vec3(mat2(vec2(_172[_848].xy), vec2(-_172[_848].y, _172[_848].x)) * _317[_1081].xy, _969).xy * _877);
11-08 17:14:31.765 E/Filament(26908): 94:   int _898 = clamp(int(floor(log2(_877))) - 3, 0, materialParams.maxLevel);
11-08 17:14:31.765 E/Filament(26908): 95:   highp float _998 = _649 / min(-5.9604644775390625e-08, ((texelFetch(materialParams_depth, clamp(_883 >> ivec2(_898), ivec2(0), textureSize(materialParams_depth, _898) - ivec2(1)), _898).x * 2.0) - 1.0) + frameUniforms.clipFromViewMatrix[2].z);
11-08 17:14:31.765 E/Filament(26908): 96:   vec2 _1007 = (((vec2(_883) + vec2(0.5)) * materialParams.resolution.zw) * 2.0) - vec2(1.0);
11-08 17:14:31.765 E/Filament(26908): 97:   highp vec2 _1072 = _1087;
11-08 17:14:31.765 E/Filament(26908): 98:   _1072.x = _1007.x * frameUniforms.viewFromClipMatrix[0].x;
11-08 17:14:31.765 E/Filament(26908): 99:   highp vec2 _1076 = _1072;
11-08 17:14:31.765 E/Filament(26908): 100:   _1076.y = _1007.y * frameUniforms.viewFromClipMatrix[1].y;
11-08 17:14:31.765 E/Filament(26908): 101:   highp vec3 _916 = vec3(_1076 * (-_998), _998) - _685;
11-08 17:14:31.765 E/Filament(26908): 102:   float _919 = dot(_916, _916);
11-08 17:14:31.765 E/Filament(26908): 103:   _1082 += ((clamp(1.0 - (_919 * materialParams.invRadiusSquared), 0.0, 1.0) * max(0.0, dot(_916, normalize(cross(vec3(_1053 * (-_744), _744) - _685, vec3(_1063 * (-_799), _799) - _685))) - materialParams.bias)) / (_919 + 0.014999999664723873138427734375));
11-08 17:14:31.765 E/Filament(26908): 104:   _1081++;
11-08 17:14:31.765 E/Filament(26908): 105:   continue;
11-08 17:14:31.765 E/Filament(26908): 106:   }
11-08 17:14:31.765 E/Filament(26908): 107:   float _624 = 1.0 - (_1082 * 0.14285714924335479736328125);
11-08 17:14:31.765 E/Filament(26908): 108:   PostProcessInputs _1078 = _1033;
11-08 17:14:31.765 E/Filament(26908): 109:   _1078.color.x = mix(_624, _624 * _624, materialParams.power);
11-08 17:14:31.765 E/Filament(26908): 110:   fragColor = _1078.color;
11-08 17:14:31.765 E/Filament(26908): 111:   }

**Comment by romainguy** [comment]
I'm not sure what we can do here, it looks like a shader compiler/driver bug. It's complaining about indexing into the SAO pattern array.

**Comment by romainguy** [comment]
Please try with more recent versions of Filament
