### ISSUE TITLE
mac os release build failed

### ISSUE THREAD

**Issue by oahc09** [google/filament#1860]
**Describe the bug**

**./build.sh debug run success, 
but ./build.sh release run failed**

[822/1165] Generating matdbg_resources.bin, matdbg_resources.S, matdbg_resources.apple.S, matdbg_resources.h
FAILED: libs/matdbg/matdbg_resources.bin libs/matdbg/matdbg_resources.S libs/matdbg/matdbg_resources.apple.S libs/matdbg/matdbg_resources.h 
cd /Users/caohao/Documents/GoogleFilament/filamentOriginal/out/cmake-release/libs/matdbg && /Users/caohao/Documents/GoogleFilament/filamentOriginal/out/cmake-release/tools/resgen/resgen -t -x /Users/caohao/Documents/GoogleFilament/filamentOriginal/out/cmake-release/libs/matdbg -p matdbg_resources /Users/caohao/Documents/GoogleFilament/filamentOriginal/libs/matdbg/web/style.css /Users/caohao/Documents/GoogleFilament/filamentOriginal/libs/matdbg/web/script.js /Users/caohao/Documents/GoogleFilament/filamentOriginal/libs/matdbg/web/index.html
/bin/sh: line 1: 45096 Segmentation fault: 11  /Users/caohao/Documents/GoogleFilament/filamentOriginal/out/cmake-release/tools/resgen/resgen -t -x /Users/caohao/Documents/GoogleFilament/filamentOriginal/out/cmake-release/libs/matdbg -p matdbg_resources /Users/caohao/Documents/GoogleFilament/filamentOriginal/libs/matdbg/web/style.css /Users/caohao/Documents/GoogleFilament/filamentOriginal/libs/matdbg/web/script.js /Users/caohao/Documents/GoogleFilament/filamentOriginal/libs/matdbg/web/index.html
[839/1165] Building CXX object third_party/libassimp/tnt/CMakeFiles/assimp.dir/__/code/Importer/StepFile/StepFileGen1.cpp.o
ninja: build stopped: subcommand failed.

MacOS  10.15.1
Filament V1.4.0

/ INFO
Building release in out/cmake-release...
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Embree not found, pipeline features are disabled.
-- The ASM compiler identification is Clang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
-- DFG LUT size set to 128x128
-- No Vulkan SDK was found, using prebuilt MoltenVK.
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Found Java: /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/bin/java (found version "1.8.0_212") 
-- Found JNI: /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/jre/lib/libjawt.dylib  
-- No Vulkan SDK was found, using prebuilt MoltenVK.
-- Configuring done
-- Generating done

/ INFO

**Comment by prideout** [comment]
This is a dup of #1823 and was fixed with #1837.  Can you confirm whether you have that commit in your tree?

**Comment by oahc09** [comment]
> This is a dup of #1823 and was fixed with #1837. Can you confirm whether you have that commit in your tree?

I refer to #1837 change the cmakelist.txt, now build release success, thanks very much.
