### ISSUE TITLE
Khronos-VC lighting looks wrong in filament.js

### ISSUE THREAD

**Issue by elalish** [google/filament#1870]
**Describe the bug**
It looks like some material property is not being respected in Khronos-VC.

**To Reproduce**
1. Load Khronos-VC from the glTF samples
2. Apply a generic IBL, but no direct lights.

**Screenshots**
You can see the difference here, and the model-viewer one matches the glTF screenshot included with the file: 
![image](https://user-images.githubusercontent.com/1649964/68702760-31cf4580-053e-11ea-9c6e-ae7bf9a3f826.png)
You can also inspect the difference near the bottom of this page: https://modelviewer.dev/test/fidelity/results-viewer.html

**Comment by prideout** [comment]
Hm, I'm not able to repro with our native viewer in either ubershader or matgen mode.  It looks fine.  I'll try it with web next.

**Comment by prideout** [comment]
Ok I can repro but only on web.  I wonder if the web app is processing the IBL incorrectly.

<img width="1247" alt="Screen Shot 2019-11-14 at 11 02 22 AM" src="https://user-images.githubusercontent.com/1288904/68887712-4fcbb000-06ce-11ea-82e5-8882ba073b87.png">

**Comment by romainguy** [comment]
Since we use R11G11B10F encoded as RGBA8888 could it be due to alpha premultiplication when the IBL images are decoded?

**Comment by prideout** [comment]
I verified that web and native go through the same IBL loading path via KtxLoader.  Really weird.  I can force the native case to look like web by forcing `specularAO` to 1.

**Comment by prideout** [comment]
I'm taking another look at this.  Really weird one.

**Comment by prideout** [comment]
The rendering difference between web and desktop is explained by specular AO, which we currently disable on mobile devices and on web.

I'm not sure if specular AO also explains the difference between Filament and ThreeJS, but I can't find anything suspicious.

I think it's probably fine to enable specular AO for web, so I'll just make a PR for that and move on.

**Comment by prideout** [comment]
Closing, we ultimately merged 237e0ee3 which makes us more aligned with ThreeJS, even though this term is mentioned nowhere in the glTF spec.
