### ISSUE TITLE
How can load gltf model asynchronously and add the loader progress in c++? 

### ISSUE THREAD

**Issue by Realitian** [google/filament#1876]
Hi
I have a quite big glb model and it took some seconds to load it using `gltfio::ResourceLoader::loadResources`.
Anybody knows how to load it asynchronously in a thread and add the load callback to get progress of loading in c++?
Please share your experience with it.
Thanks in advance for you help.

**Comment by prideout** [comment]
ResourceLoader is a bit under-engineered right now, we should add callbacks and threading.  We have this note in its comment block:

```
 \todo The GPU upload is asynchronous but the load-from-disk and image decode is not.
```

If loading from disk is what's slow (as opposed to the STB decode), you can do the following:

1. Call `getResourceUris` on the asset.
2. Create the ResourceLoader but do not call `loadResources` yet.
3. Do the loading yourself in other threads and call `addResourceData` along the way.
4.  After the threads join, call `loadResources` to finalize the resources.

However this won't help with vertex buffer data or with STB decoding, which will still be synchronized.

**Comment by prideout** [comment]
Sorry I missed that this is a GLB model.  It's likely that the STB image decoder is what's slow.  :-\

**Comment by prideout** [comment]
After thinking about this -- since the image decoding is likely the slow part, we might be able to add threading for this without any API changes.

If you're able to attach the GLB file to the issue that would help with our optimization efforts.

**Comment by Realitian** [comment]
I tried to add callback of loading progress and tested for glb files.
I could get loading progress percent and had rendered it by calling 
`renderer->beginFrame(swapChain);
 renderer->render(view);
 renderer->endFrame();`
in the callback.
if it can be helpful, I am happy.

**Comment by prideout** [comment]
Thanks!  We'll add this in soon.

**Comment by prideout** [comment]
I'd like a solution that also helps web applications that wish to amortize the decode across frames. Since they are single-threaded, callbacks would not help.  I'm working out a plan right now.
