### ISSUE TITLE
Linking with filament: -fPIE/-fPIC issue

### ISSUE THREAD

**Issue by roxlu** [google/filament#1881]
I've just downloaded the prebuilt libraries for linux and tried to link them in my project which gave me this error: 

```
/usr/bin/ld: filament-prefix/src/filament/lib/x86_64//libimage.a(KtxBundle.cpp.o): 
relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; 
recompile with -fPIE
```

If I understand that error correctly, it's telling me to recompile libimage.a with -fPIE. I had a discussion with someone who explained me -fPIE is an alias for -fPIC. After some reading up I found a [StackOverflow post with a command that allows you to check if an object/library was compiled with -fPIC](https://stackoverflow.com/questions/1340402/how-can-i-tell-with-something-like-objdump-if-an-object-file-has-been-built-wi). It seems libimage.a was compiled with -fPIC which makes me wonder why I get that error (especially if -fPIE is an alias for -fPIC). 

I did a couple of tests, enabling/disabling POSITION_INDEPENDENT_CODE in my CMakelists.txt but nothing solved the issue. 

I was able to compile and link filament by using the filament repository as an external project and building it from source:

```cmake
ExternalProject_Add(
    filament
    GIT_REPOSITORY https://github.com/google/filament.git
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
)
``` 

I'm trying to figure out why I can't use the prebuilt libraries? Any thoughts? Maybe it's because of compiler defaults? (Using clang 9)

**Comment by prideout** [comment]
Looks like the CMakeLists for libs/image is missing the following line:

```
target_compile_options(${TARGET} PRIVATE  $<$<PLATFORM_ID:Linux>:-fPIC>)
```

I *think* this will help you out in our future releases.  Sorry for trouble.

**Comment by kpeeters** [comment]
Can this be added please so we don't have to do it by hand at every new release? Or is there a problem doing this in general?

**Comment by romainguy** [comment]
We should already be using -fPIC everywhere.

**Comment by kpeeters** [comment]
1.8.0 doesn't. Adding that line in 1.8.0 fixes the problem.

**Comment by romainguy** [comment]
That's an oversight we need to fix then.

**Comment by kpeeters** [comment]
For the record: I encountered this with filament built from source myself; no idea if you do something different for the binary releases, but in any case, would be nice to have fixed. Thanks.

**Comment by prideout** [comment]
According to `find libs/ -name "CMakeLists.txt" | xargs grep -l install`, these are our installable libraries:

```
libs/filaflat/CMakeLists.txt
libs/bluegl/CMakeLists.txt
libs/utils/CMakeLists.txt
libs/math/CMakeLists.txt
libs/bluevk/CMakeLists.txt
libs/gltfio/CMakeLists.txt
libs/image/CMakeLists.txt
libs/filabridge/CMakeLists.txt
libs/ibl/CMakeLists.txt
libs/matdbg/CMakeLists.txt
libs/camutils/CMakeLists.txt
libs/geometry/CMakeLists.txt
libs/filameshio/CMakeLists.txt
libs/mathio/CMakeLists.txt
libs/filamat/CMakeLists.txt
```

We should make it so that they all have:

```
if (MSVC)
    target_compile_options(${TARGET} PRIVATE $<$<CONFIG:Release>:/fp:fast>)
else()
    target_compile_options(${TARGET} PRIVATE $<$<CONFIG:Release>:-ffast-math>)
    target_compile_options(${TARGET} PRIVATE -Wno-deprecated-register)
endif()

target_compile_options(${TARGET} PRIVATE $<$<PLATFORM_ID:Linux>:-fPIC>)
```

I might fix this by creating a macro in our root-level CMake file for the above snippet.

**Comment by prideout** [comment]
On second thought, maybe the root-level CMake file should simply set up CMAKE_CXX_FLAGS and CMAKE_CXX_FLAGS_RELEASE (which it already does for some flags, but not for these).  This would guarantee consistency across all our subprojects.

I'll give it a try.

**Comment by 100espressos** [comment]
Similarly, [CMAKE_POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html)=1 sets the default [POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html) property.
