### ISSUE TITLE
Could not download the nightly/edge build

### ISSUE THREAD

**Issue by yongtang** [google/filament#1889]
**Describe the bug**

In README.md, it was specified that:
> If you prefer to live on the edge, you can download a continuous build by clicking one of the build badges above.

However, when clicking the badge it does not return a download, just the picture of the badge.

**To Reproduce**
1. Click the badge of the continuous build in README.md

**Expected behavior**

Don't know if this is a linking issue, or nightly/edge builds are not provided any more. If nightly/edge builds are not available anymore I think it would make sense to update the README.md?

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
na/

**Additional context**
n/a

**Comment by yongtang** [comment]
It looks like the link was modified in PR #1850, I created a branch to add the download link back:
https://github.com/google/filament/compare/master...yongtang:link

However, I am not very familiar with GitHub workflow and filament's CI internal. Don't know if the links in the diff are still relevant, or the download location have changed?

If the download location can be confirmed I can create a PR for that.

**Comment by romainguy** [comment]
We're in the middle of changing our CI which is why the links are broken. We hope to have them back on but failing that we'll update the readme. @bejado

**Comment by bejado** [comment]
I'll update the README. For now we recommend using the latest release build.

**Comment by yongtang** [comment]
Thanks @bejado for the update 👍 . Wondering if there is any plan to release next version of filament in the near future?

In particular I am looking into headless SwapChain feature (#1838 and #1885) which are not yet included in the current release.

**Comment by romainguy** [comment]
We'll probably cut a new release fairly soon.
