### ISSUE TITLE
Filament + GLFW: how to share context and managing swapchain

### ISSUE THREAD

**Issue by roxlu** [google/filament#1894]
How can we use Filament with GLFW and custom GL code when draw calls are not part of the filament command buffer?

A typical GLFW render and event loop looks like:

```c
while (!glfwWindowShouldClose(window)) {
   glViewport(0, 0, width, height);
   glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
   // perform draw calls 
   glfwSwapBuffers(window);
   glfwPollEvents();
}    
```
Filament uses something similar:

```c++
void renderLoop(Renderer* renderer, SwapChain* swapChain) {
    do {
        if (renderer->beginFrame(swapChain)) {
            renderer->render(mView); // handles command buffer
            renderer->endFrame();
        }
    } while (!quit());
}

```

If I'm correct, the `render()` call will handle the command buffer and when ready it swaps the swap chain.  How would this work when you want to make your own draw calls that are not managed by Filament? These draw commands will be handled out of the flow and therefore possibly not executed at the right time. 

I've experimented with the following code:

```c++
while (true) {

    /* Custom GL draw calls (UV pattern) */
    glViewport(0, 0, win_w, win_h);
    glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    sprite_ctx.updateSprites();
    sprite_ctx.draw(); /* will execute GL draw calls. */
    
    /* Filament render loop. (`ctx` is a thin wrapper around Filament::Renderer) */
    if (0 == ctx.beginFrame()) {
      floors.draw();
      ctx.endFrame();
    }

    glfwSwapBuffers(win);
    glfwPollEvents();
}
```

The above code results in flickering which is most likely caused by synchronisation issues between the swap-chain/back buffers. I've created a recording that shows the issue: https://imgur.com/a/GmZUN7q

It should render a UV pattern in the background and a 3D render on top of it (I'm using the transparent flag when creating the filament swap chain).

**Comment by romainguy** [comment]
Filament is not designed to let you use custom GL calls (Filament may not even use GL). All GL code in filament runs on a dedicated thread you don't have access to. At the very least you should be making the context current on your current thread before calling GL. But that would also mess with Filament's internal state tracking.

**Comment by roxlu** [comment]
@romainguy thanks for your reply. 

I want to use Filament in a specific case that uses GL. I'm initializing Filament with a shared GL context and that works great. Now I'm looking for a solution to use the rendered output in an existing GL application.

Maybe, I can render into a FBO and use that texture in my existing application. Would that be a good approach?
