### ISSUE TITLE
Dynamic resolution causes huge memory spikes

### ISSUE THREAD

**Issue by ansman** [google/filament#1898]
**Describe the bug**
When dynamic resolution is enabled on Android the memory usage fluctuates greatly. Usually the app even crashes after a while due to memory running out.

**Screenshots**
Without dynamic resolution:
<img width="1984" alt="Screen Shot 2019-11-19 at 14 37 43" src="https://user-images.githubusercontent.com/102883/69179830-2e0d6700-0ada-11ea-8426-192590456eb6.png">

With dynamic resolution:
<img width="1876" alt="Screen Shot 2019-11-19 at 14 35 08" src="https://user-images.githubusercontent.com/102883/69179849-3796cf00-0ada-11ea-97f6-cf72817dddb4.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Android
 - GPU: [e.g. NVIDIA GTX 1080] Adreno 630
 - Backend: [OpenGL/Vulkan] OpenGL

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2] Pixel 3XL
 - OS: [e.g. Android Pie 9.0] Android 10

**Comment by romainguy** [comment]
I would expect the memory fluctuation but we should not run out of memory :/

**Comment by pixelflinger** [comment]
Could we get a log of the crash? Is it a crash or an assert?
Also is this with MSAA on or off?
What are the parameters of dynamic resolution used?


Currently the cache of render targets gc is not very advanced. It will remove old entries after about (0.5s, it's actually after 30 allocations) until it's not larger than 64 MiB. However, it does not do that aggressively, i.e. it only removes entries that are 30 allocations old or more.
We should probably be more aggressive at purging, but also be less aggressive at allocating.

**Comment by ansman** [comment]
I actually can't reproduce it now, here is how I enabled it:
```kotlin
        val options = View.DynamicResolutionOptions()
        options.enabled = true
        view.dynamicResolutionOptions = options
```

I'm using the default value for MSAA.

**Comment by pixelflinger** [comment]
@ansman okay, please reopen this if the problem reappears
