### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by JonathanLehner** [google/filament#1901]
How can I change the background image? Is it possible to use live video as background, like in Google street view? I would like to render virtual objects in AR on top of the camera stream.

**Comment by romainguy** [comment]
Filament does not render a background image by default. We provide a `Skybox` API to do this, and you can feed it an external texture (like the camera stream or a video). You can look at `android/samples/hello-camera` for an example of how to do this.

**Comment by JonathanLehner** [comment]
How to do this with web?

**Comment by prideout** [comment]
I don't think WebGL supports external textures but you could enable `alpha` in the WebGL canvas and do anything you want in a background element.

**Comment by JonathanLehner** [comment]
const options = {
      majorVersion: 2,
      minorVersion: 0,
      antialias: false,
      depth: true,
      alpha: true,
      premultipliedAlpha: false,
      preserveDrawingBuffer: true
    };
    this.engine = Filament.Engine.create(canvas, options);

I tried like this but it still doesn't seem to work

**Comment by JonathanLehner** [comment]
It works if I do gl.clear after rendering. But then it only shows the color and the Object is gone..
    this.renderer.render(this.swapChain, this.view);

    var filament_canvas = document.getElementById('filament_canvas');
    var gl = filament_canvas.getContext('webgl2', {alpha: true, premultipliedAlpha: false});
    gl.clearColor(0,0.1,0,0.5);
    gl.enable(gl.BLEND);
    gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT | gl.ACCUM_BUFFER_BIT | gl.STENCIL_BUFFER_BIT);

**Comment by romainguy** [comment]
Did you set the clear color in the filament view object to clear alpha properly?

**Comment by JonathanLehner** [comment]
yes. I used this.view.setClearColor([0,1,0,0]). it does change the background color but it ignores the alpha value

**Comment by JonathanLehner** [comment]
I just modified the suzanne example. It is easy to replicate
