### ISSUE TITLE
Matching transparency from Blender

### ISSUE THREAD

**Issue by roxlu** [google/filament#1911]
Sorry if this is too much "off topic", but I'm wondering how to create a filament material that matches the transparency settings/material in Blender; i.e. how can I match Filament as closely as possible with Eevee.  Is there a mapping between the settings in Blender and Filament?

For example, would it be possible to match these settings: 

![screenshot-arch680-2019 11 24 10 38 54](https://user-images.githubusercontent.com/358809/69492827-bb203980-0ea7-11ea-925e-d5f9a4ef1eb4.png)

**Comment by romainguy** [comment]
I don't know where the green tint is coming from. Most settings are the same since blender and filament both follow Disney's principled BRDF. The thing that's missing is refraction in Filament but fortunately for you we've started implementing it a few days ago.

**Comment by roxlu** [comment]
That's amazing, looking forward to give that a try.
