### ISSUE TITLE
Missing support for Shared OpenGL Context on Windows?

### ISSUE THREAD

**Issue by roxlu** [google/filament#1912]
Just getting my feet wet with shared contexts on Windows and I maybe I'm wrong here, but it seems that the `sharedGLContext` is ignored in [PlatformWGL.cpp](https://github.com/google/filament/blob/master/filament/backend/src/opengl/PlatformWGL.cpp#L73) and it should be passed into `wglCreateContextAttribs()`. Or am I wrong here? 

[WGL_ARB_create_context](https://www.khronos.org/registry/OpenGL/extensions/ARB/WGL_ARB_create_context.txt)

**Comment by romainguy** [comment]
@bejado

**Comment by bejado** [comment]
I think you're right, good catch.

**Comment by shd8698766** [comment]
What's strange wglCreateContextAttribs is a exclusive Windows function (starts with wgl) but you can't find this function in the Microsoft docs.
