### ISSUE TITLE
How can control transparency of whole model ( loaded from gltf ) ?

### ISSUE THREAD

**Issue by Realitian** [google/filament#1918]
Hi all,
How can I control the transparency of whole gltf model?
I tried to change the UberShader internally, but it was difficult to make work.
Anybody give me method who know it.

**Comment by prideout** [comment]
You can call `getMaterialInstances` on the `FilamentAsset` and set the `baseColorFactor` parameter on each instance using the alpha value of your choice.

**Comment by romainguy** [comment]
Note that the "fade" blending mode is the best way to fade an object.

**Comment by prideout** [comment]
That's a good point, currently gltfio does not allow users to swap out the material easily; to perform the fade effect they would need to call setMaterialInstance rather than merely changing the parameter that I indicated.

 We can try to make this easier via callbacks.

**Comment by prideout** [comment]
Another way of achieving this effect is to draw the mesh into a RenderTarget, then fade-in a full-screen quad.  This would (a) allow you to avoid hacking the glTF material, and (b) avoid depth-testing issues.
