### ISSUE TITLE
Crash on windows GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#1924]
Hey guys,

So I am working on an app that is using filament. I started on this project a year ago and integrated into my app which basically uses modified Suzanne sample app code. I had some problems initially with reading from buffer and painting on my app using readpixel and pixelBufferDescriptor but I figured that out and my app is no longer crashing and copying the buffer nicely to my app thanks to help from you guys. I noticed that you guys had added ambient occlusion to filament which I had requested as a feature a while back and I wanted to try that on my app.
I got the latest source again yesterday, did a debug build and replaced all the static libs  along with include headers, materials and textures in my app and also updated the modified code in FilamentApp.cpp since it was last pulled a year ago.  But now when I run my app right after endframe() is called I get this error as shown in the screenshot. error is GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE

![Annotation 2019-12-01 202613](https://user-images.githubusercontent.com/36080456/69924642-75044080-147a-11ea-9af3-0a947bf7bb72.png)

Any idea why is it crashing ? I noticed drivers were changed to backend so I made sure I added backend.lib and also added the public headers to my includes. Not sure what I am missing. If I missed some lib or headers I would probably get a linker or compiler error which I have resolved it all.

**Comment by thirdmenson** [comment]
I found the culprit. `view->setSampleCount(32);`  I used to be able to set the sample count to 32 but now even if I try 16 I get the same crash.

**Comment by romainguy** [comment]
I'm surprised 32 is even supported by any driver out there. What do you get with 4? If it still crashes it means we have a bug with MSAA on Windows.

**Comment by thirdmenson** [comment]
so year ago when anti aliasing was turned on it didn't look that good, so I bumped up the sample count high to 32 and that made it look nice and sharp. Now it seems even with 4 it looks good so that works for me.

Another problem I am having is this fix https://github.com/google/filament/issues/1441#issuecomment-555283398 that I applied to the year old build worked but now that I got the latest build, I tried applying the same fix, rebuild filament.lib and the alpha values are incorrect again so images doesn't show as transparent. @bejado 

Also previously I was finally able to solve my crash problem when i used readpixel to read data from filament buffer to my app buffer by blocking the current thread until the readpixel is done by calling fence::waitAndDestroy like this 
`Texture::PixelBufferDescriptor pb(image_data, area * 4, Texture::Format::RGBA, Texture::Type::UBYTE);
renderer->readPixels(0, 0, winwidth, winheight, std::move(pb));
Fence::waitAndDestroy(mEngine->createFence(Fence::Type::SOFT), Fence::Mode::FLUSH);`

Now I noticed Type::SOFT was moved into FFence.h and createFence by default uses Type::SOFT ,so  I tried this to block the current thread until the reading pixel is done `Fence::waitAndDestroy(mEngine->createFence(), Fence::Mode::FLUSH);`  
But now it's not blocking the current thread until the reading is done and I am back to seeing crashes again. How do I properly block the current thread now  until the read pixel is all done?

**Comment by romainguy** [comment]
MSAA can be pretty expensive especially with a high sample count (note that in practice only powers of 2 are supported, so using 14 either means 8 or 16 internally, I don't remember which one we round to). I would recommend using both FXAA and MSAA together by the way, as FXAA can help with shading aliasing which MSAA does not address.

For your `readPixels` issue please file a different bug with all the relevant information. Note that you don't need to use a fence, you can instead rely on the callback from the `PixelBufferDescriptor` to know when the read is done.
