### ISSUE TITLE
New Fence not blocking thread until readpixels operation is done.

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#1925]
Hey guys,

So I am working on an app that is using filament. I started on this project a year ago and integrated into my app which basically uses modified Suzanne sample app code. I had some problems initially with reading from buffer and painting on my app using readpixel and pixelBufferDescriptor but I figured that out and my app is no longer crashing and copying the buffer nicely to my app thanks to help from you guys. I noticed that you guys had added ambient occlusion to filament which I had requested as a feature a while back and I wanted to try that on my app.

I solved the crash when I  readpixel to read data from filament buffer to my app buffer by blocking the current thread until the readpixel is done by calling fence::waitAndDestroy like this

`Texture::PixelBufferDescriptor pb(image_data, area * 4, Texture::Format::RGBA, Texture::Type::UBYTE), [](void* buffer, size_t size, void* user) {
					CaptureState* state = static_cast<CaptureState*>(user);
                                        // Copy filament buffer to my app buffer
				}, currentState);
renderer->readPixels(0, 0, winwidth, winheight, std::move(pb)); Fence::waitAndDestroy(mEngine->createFence(Fence::Type::SOFT), Fence::Mode::FLUSH);`

Now I noticed Type::SOFT was moved into FFence.h and createFence by default uses Type::SOFT ,so I tried this to block the current thread until the reading pixel is done Fence::waitAndDestroy(mEngine->createFence(), Fence::Mode::FLUSH);
But now it's not blocking the current thread until the reading is done and I am back to seeing crashes again. I do use the PixelBufferDescriptor callback to know when read is done and that's where I do the copying from filament buffer to my app buffer. The problem is I need to block this current filament thread until reading is done otherwise after endframe() the program execution continues and exits my app thread ( same thread as filament) and pixelbufferdescriptor callback is only invoked on the next render callback from my app. So essentially the program ends up copying older frame data to the next frame buffer in my app and this eventually causes crash. How do I properly block the current thread now until the read pixel is all done? I have a feeling this is due to Fence changes.

**Comment by bejado** [comment]
Try using `mEngine->flushAndWait()` instead of `Fence::waitAndDestroy`.

FYI we do something similar in `filament/test/filament_rendering_test.cpp`. We render, issue a `readPixels` and then call `flushAndWait` to block until the callback has executed.

**Comment by thirdmenson** [comment]
Thank you so much that worked !!! 

Another problem I am having is this fix that you pointed me to not so long ago https://github.com/google/filament/issues/1441#issuecomment-555283398 that I applied to the year old build worked then but now that I got the latest build, I tried applying the same fix, rebuild filament.lib and the alpha values are incorrect again so images doesn't show as transparent. @bejado

**Comment by bejado** [comment]
That fix still works for me with the latest release. Have you made sure you're clearing the screen with `0, 0, 0, 0` and creating the `SwapChain` with the `SwapChain::CONFIG_TRANSPARENT` flag?

**Comment by thirdmenson** [comment]
Yeah I made sure again I am clearing screen like this
 `view = engine.createView();
  view->setClearColor(math::float4(0.0f, 0.0f, 0.0f, 0.0f));
  view->setName(name.c_str());`

creating swapchain like this 
`       void* nativeWindow = ::getNativeWindow(mWindow);
	mSwapChain = mFilamentApp->mEngine->createSwapChain(nativeWindow, 
        SwapChain::CONFIG_TRANSPARENT);`

and I show and hide my ibl environment background like this,
`	if (bSkyboxChecked) {
		IBL* ibl = FilamentApp::get().getIBL();
		FilamentApp::get().getScene()->setSkybox(ibl->getSkybox());
	} 
	else {
		FilamentApp::get().getScene()->setSkybox(NULL);
	}`

Maybe clearing skybox like that doesn't clear the background in alpha anymore ?

**Comment by bejado** [comment]
That all seems right to me. You can take a look at my branch, [bjd/windows-transparency](https://github.com/google/filament/compare/bjd/windows-transparency) to see how I'm testing. Try building and running the `gltf_viewer` sample. I've added a `readPixels` call which will read from the framebuffer and log the bottom-left pixel values. Note how the alpha value changes from 0 to 255 if you right click and drag the model to the bottom left of the screen.

**Comment by thirdmenson** [comment]
I thought you said we need to set the clear color to 0 0 0 0, why would you set the alpha to 1 ?
`window->mDepthView->getView()->setClearColor({0, 0, 0, 1});`
But regardless if it set it to 0 or 1 or clear the way I did it, I am not getting transparent value.

**Comment by bejado** [comment]
That line of code is for clearing the depth view, which isn't used in the `gltf_viewer` sample. The actual clear color is set here:

```
view->setClearColor(LinearColorA{ 0 });
```

If you run the sample, does it output the correct alpha values?

**Comment by thirdmenson** [comment]
Yes running the sample does give me correct alpha values. 
It is working now when I copied filament buffer using nested for loops, for some reason the apps copying utilities seems to ignore alpha, but that's not filament's issue. 
Thanks for your help !

**Comment by bejado** [comment]
Glad it's working now.
