### ISSUE TITLE
[Feature Request] glTF's KHR_draco_mesh_compression extension

### ISSUE THREAD

**Issue by cx20** [google/filament#1932]
**Is your feature request related to a problem? Please describe.**
I think other major WebGL libraries support glTF's `KHR_draco_mesh_compression` extension.
The Draco format is an excellent compression format.
I have a sample I want to display, but I am sad that I can't display it with filament.

**Describe the solution you'd like**
Please support glTF's `KHR_draco_mesh_compression` extension.
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_draco_mesh_compression

**Comment by prideout** [comment]
This is something that we can look into soon.  Romain already has an upstream PR:
https://github.com/jkuhlmann/cgltf/pull/106

**Comment by prideout** [comment]
Status update: we're actively working on this (and, thanks to Romain, the cgltf side is done) however we're doing some internal refactoring first.

More specifically, the old "bindings" concept (used to send information from AssetLoader to ResourceLoader) is really getting in the way, it is private now but I want to remove it entirely and just talk to cgltf directly.  After that, the Draco support should be easy to finish up.

**Comment by cx20** [comment]
@prideout Thank you for supporting Draco. Can I use it with WebGL?

**Comment by prideout** [comment]
It is not yet included in the WebGL build but I will add it.

**Comment by cx20** [comment]
@prideout Thanks! I have confirmed that Filament `1.5.0` can display Draco format files.

[Filament v1.5.0 + Draco format result:](https://cx20.github.io/gltf-test/examples/filament/index.html?url=https://rawcdn.githack.com/mrdoob/three.js/dev/examples/models/gltf/LittlestTokyo.glb&scale=0.01)
![image](https://user-images.githubusercontent.com/1833979/78024833-01c0fb80-7394-11ea-94c0-12f751c15b7a.png)

And it passed the test of each format by [gltf-test](https://github.com/cx20/gltf-test#format-tests). Congratulations.
![image](https://user-images.githubusercontent.com/1833979/78025159-7d22ad00-7394-11ea-870d-02e6903dcffd.png)
