### ISSUE TITLE
HDR image fails to decode in cmgen

### ISSUE THREAD

**Issue by elalish** [google/filament#1937]
**Describe the bug**
I created an hdr image in photoshop and it decodes and works just fine in Filament. However, I then edited that image in GIMP and resaved it as .hdr and it no longer decodes. I believe the image is valid because it opens in other programs that load .hdr. I've sent the problem file to @prideout 

**To Reproduce**
1. run `cmgen --format=ktx -x . spot1Lux.hdr`

**Expected behavior**
Successful generation of KTX IBL texture.

**Screenshots**
The error reported is: `Runtime error while decoding HDR: invalid scanline (magic)`

**Desktop (please complete the following information):**
 - OS: gLinux

**Comment by romainguy** [comment]
Can you attach the offending hdr file please? According to the error one of the scanlines doesn't start with the magic bytes `0x0202`.

**Comment by prideout** [comment]
Attached.  Radiance scanlines can be RLE or non-RLE.  If the scanline does not start with 0x0202 then it's non-RLE.  Let me fix this, it should be easy.

[spot1Lux.hdr.zip](https://github.com/google/filament/files/3929144/spot1Lux.hdr.zip)

**Comment by romainguy** [comment]
Oh wow, I remember we tried to find non RLE files and couldn't find any.
