### ISSUE TITLE
Multiple Scattering implementation

### ISSUE THREAD

**Issue by DrDrake** [google/filament#1938]
Hi guys,
As I understood from the code of your shaders and your excellent documentation, you have an implementation of multiple scattering for some cases. However, I would like to ask if you plan to modify it somehow taking into account new publications on this topic? For example, some of the publications by Stephen McAuley seemed very interesting to me:
[Advances in Rendering, Graphics Research and Video Game Production](http://i3dsymposium.github.io/2019/keynotes/I3D2019_keynote_StephenMcAuley.pdf)
[A Journey Through Implementing Multiscattering BRDFs and Area Lights](http://advances.realtimerendering.com/s2019/A%20Journey%20Through%20Implementing%20Multiscattering%20BRDFs%20and%20Area%20Lights.pptx)

**Comment by romainguy** [comment]
I've already studied those publications and we're not going to change our multiscattering implementation at this time. There's no good reason to do so especially considering how cheap the current version is.
