### ISSUE TITLE
Build FAILED on Win10 by msvc 2019 16.4.0

### ISSUE THREAD

**Issue by locobrain** [google/filament#1939]
Build FAILED on Win 10 by msvc 2019 16.4.0, the error message follow:

6>Done building project "textures.vcxproj".
5>SurfaceOrientation.cpp
5>.\filament-1.4.3\libs\math\include\math/TVecHelpers.h(54,24): error C2938: 'std::enable_if_t<false,void>' : Failed to specialize alias template
5>.\filament-1.4.3\libs\math\include\math/TVecHelpers.h(54): message : see reference to alias template instantiation 'std::enable_if_t<false,void>' being compiled
5>.\filament-1.4.3\libs\math\include\math/vec2.h(96): message : see reference to alias template instantiation 'filament::math::details::enable_if_arithmetic_t<filament::math::half,int,int,int>' being compiled
5>.\filament-1.4.3\libs\math\include\math/vec2.h(101,15): error C2976: 'filament::math::vec2': too few template arguments
5>.\filament-1.4.3\libs\math\include\math/vec2.h(97): message : see declaration of 'filament::math::vec2'
5>.\filament-1.4.3\libs\math\include\math/vec3.h(121,15): error C2976: 'filament::math::vec3': too few template arguments
5>.\filament-1.4.3\libs\math\include\math/vec3.h(117): message : see declaration of 'filament::math::vec3'
5>.\filament-1.4.3\libs\math\include\math/vec4.h(119,15): error C2976: 'filament::math::vec4': too few template arguments
5>.\filament-1.4.3\libs\math\include\math/vec4.h(115): message : see declaration of 'filament::math::vec4'

**Comment by bejado** [comment]
Looks like this was introduced with the recent 16.4.0 release of MSVC, otherwise our CI should have caught this.

**Comment by BStringhamVRSK** [comment]
I can confirm that 16.4.0 seems to be the cause.  One of my team members just installed 16.4.0 and is seeing the same.

**Comment by bejado** [comment]
You can apply the patch in #1943 to unblock yourself for now. Note that I was forced to delete and re-generate my cmake build directory after upgrading Visual Studio.
