### ISSUE TITLE
Precompiled jar is java 9

### ISSUE THREAD

**Issue by nedtwigg** [google/filament#194]
**Describe the bug**
The precompiled jar is java 9.

**To Reproduce**
1. Download the public release.
2. The jar is class file version 53 (Java 9)

**Expected behavior**
If you're not using java 9-specific features, it would be nice to downgrade to java 8. [Java 8 still has ~85% marketshare as of May 2018](https://www.baeldung.com/java-in-2018).

**Comment by romainguy** [comment]
That's a bug, it should be Java 8.

**Comment by romainguy** [comment]
BTW in which of the archives do you see a Java 9 jar? (Windows, Linux or macOS)

**Comment by nedtwigg** [comment]
Windows.
