### ISSUE TITLE
filament.js has a problem with setIndirectLight(null)

### ISSUE THREAD

**Issue by elalish** [google/filament#1940]
**Describe the bug**
I'm getting strange behavior when switching a scene between directional light and indirect light.

**To Reproduce**
1. Pull this PR of model-viewer: https://github.com/GoogleWebComponents/model-viewer/pull/916
2. `npm install`, `npm run build`, `npm run dev`
3. Go to http://127.0.0.1:8000/test/fidelity/renderers/filament/
4. Select DirectionalLightTest - it should work
5. Select something else, e.g. FurnaceTest - also works
6. Select DirectionalLightTest again - it renders the spheres white
7. Select something else, e.g. FurnaceTest - works
8. Select DirectionalLightTest again - works again, and from now on.

There are no console errors during any of these steps. If this doesn't repro, reload and try again but skipping step 4.

Note the changes in the PR are where this error occurs, relating to creating and destroying lights.

**Expected behavior**
DirectionalLightTest should work the same each time.

**Screenshots**
Working:
![image](https://user-images.githubusercontent.com/1649964/70260703-b3815000-1745-11ea-835b-35b986b52f9a.png)
Not working:
![image](https://user-images.githubusercontent.com/1649964/70260811-ecb9c000-1745-11ea-8c0b-536846814ad8.png)

**Comment by prideout** [comment]
Almost all the model viewer tests don't work for me because it can't find `/ktx/lightroom_14b/lightroom_14b_ibl.ktx` or `./ktx/grey/grey_ibl.ktx`

**Comment by elalish** [comment]
Sorry, I forgot to mention you should run `npm run update-screenshots` first. That causes the IBLs to be generated.

**Comment by prideout** [comment]
I understand what's going on.  First, note that Filament always performs IBL math, regardless of whether the scene has an IBL.  This helps us reduce our shader variant count.

When you create a brand new scene, Filament automatically provides a default IBL with intensity=1.  When you set the IBL and Skybox to null, Filament uses intensity=30000.

The "not working" screenshot is the null IBL (intensity=30000), the "working" screenshot is the default IBL (intensity=1).

I think we should change Filament's behavior to be less surprising when clients pass null, so I'll propose a change to my colleagues.  Meanwhile you can work around this by simply never removing the IBL, just change its intensity to 1 to effectively disable it.

**Comment by elalish** [comment]
So the default IBL is an ambient light at the intensity of the sun? That seems a little extreme? If I want the scene illuminated by only a directional light, shouldn't I set the IBL intensity to zero instead of one? When passing null, I would expect to get the same result as intensity zero, though I guess if someone failed to set up any lights it's nice to have a default ambient light.

**Comment by prideout** [comment]
In practice the intensity of the default IBL doesn't matter because we bind a black 1x1 texture.

The actual bug in your case was that Filament was failing to bind the black 1x1 texture.  I was overlooking this when I wrote the last comment -- sorry for the confusion.

Regarding 1 vs 0, they're practically the same but I wasn't sure if 0 was legal.  I think you're right, you can probably just use 0.
