### ISSUE TITLE
Support equirectangular coordinate output for cmgen

### ISSUE THREAD

**Issue by syoyo** [google/filament#195]
**Is your feature request related to a problem? Please describe.**

`cmgen` supports reading equiangular envmap but does not support exporting processed envmap image as equiangular coordinate.

Equirectangular(longitude-latitude) coordinate is handy than cubemap since it only requires single file storage and can be easily further processed with image processing tools like imagemagick, gimp, etc.

**Describe the solution you'd like**

Add equirectangular coordinate output.
We may better to rename `cmgen` to `iblgen` or more general naming if we support equirectangular.

**Describe alternatives you've considered**

Even though we can use/write another tool which converts cubemap to equirectangular, making equirectangular output as a built-in feature of `cmgen` would be nice.

**OS and backend**

OS/Backend independent.

**Comment by romainguy** [comment]
That's a good idea. It wouldn't be difficult to add such support I believe.

**Comment by TimvanScherpenzeel** [comment]
Another very useful format are octahedral maps as discussed in [chapter 16 of WebGL Insights](https://webglinsights.github.io/downloads/WebGL-Insights-Chapter-16.pdf). The main advantage of octahedral maps is the lack of seams and distortion.

By using this technique we can work around the following WebGL issues as mentioned in this [ticket](https://github.com/pex-gl/pex-renderer/issues/8) that still stand as of today in my experience:
- textureCubeLod is still not supported in Firefox on OSX
- seamless cubemap filtering is not available in WebGL 1
- most importantly we can't render to HDR CubeMap mipmap levels > 0 on iOS

One implementation is mentioned in [this thread](https://github.com/mrdoob/three.js/issues/5847#issuecomment-138801193).

The excellent paper that is referenced in the thread is the following (the link in the thread is dead):
https://pdfs.semanticscholar.org/fcb9/a6dbdf7b4c31f94e481cf101c83b73ea6410.pdf

A tooling implementation of octahedral maps can be found in [CMFT](https://github.com/dariomanesku/cmft/search?q=octant&unscoped_q=octant).

I understand that WebGL is not a supported target of Filament but having it as an option would be very beneficial.

**Comment by romainguy** [comment]
WebGL is a target now but WebGL 2 which follows OpenGLES 3.0 which means it provides seamless cubemap sampling. We are not planning on supporting WebGL 1 at this point. Note however that `cmgen` contains code to generate cubemaps with seam fixups built-in. It's not as good as octahedral maps but it helps. That said I'd be more than happy to accept contributions to support octahedral maps. We just can't really justify doing it ourselves at this time :/

**Comment by pixelflinger** [comment]
Fixed in #317

**Comment by syoyo** [comment]
Thank you!
