### ISSUE TITLE
cmgen with ibl-is-mipmap + EXR PIZ output crashes  

### ISSUE THREAD

**Issue by syoyo** [google/filament#196]
**Describe the bug**

cmgen crashes inside of TinyEXR in some situation due to out-of-bounds access(detectable by ASAN)

**To Reproduce**

1. Generate `sunsky.exr`  using `skygen`
2. Generate is-mipmap in `cmgen` with EXR as output format.

```
$ ./cmgen --ibl-is-mipmap=is -f exr sunsky.exr
Crash
```

**Solution**

The reason is the size of temporary buffer for PIZ compression is not sufficient.
 
I don't know what is conservative&good value for it but I have increased temporary buffer size heuristically as in this commit:

https://github.com/syoyo/tinyexr/commit/05df598a45a2e6166611288eb0a1acb96d9c2903

At least I've confirmed it now works well.

Better solution is updating `tinyexr.h` file in `Filament` repo.

**Comment by romainguy** [comment]
Thank you, I will update to a newer version of tinyexr!
