### ISSUE TITLE
Matching Alpha Blending (transparency) from Blender

### ISSUE THREAD

**Issue by roxlu** [google/filament#1971]
Recently I posted #1911 which is somewhat relevant. But here, I'm actually just trying to figure out how to get a transparent material that looks similar to the screenshot of Blender.

What transparency settings will give me the same result?

![image](https://user-images.githubusercontent.com/358809/70718440-80fcc780-1cf0-11ea-8877-0993d13099a2.png)

Material properties:
```
color: 1.00, 1.00, 1.00
roughness: 0.37
metallic: 0.00
transmission: 0.94
alpha: 0.66
```

Material
```glsl
void material(inout MaterialInputs material) {
   prepareMaterial(material);
   material.baseColor.rgb = materialParams.albedo;
   material.baseColor.a = materialParams.alpha;
   material.metallic = materialParams.metallic;
   material.roughness = materialParams.roughness;
}
```

I've tested tested with all the different Blending modes but none of them gave me a similar result. Am I doing something wrong?

**FADE**
![image](https://user-images.githubusercontent.com/358809/70717936-a0dfbb80-1cef-11ea-90c5-8be3639664e9.png)

**TRANSPARENT**
![image](https://user-images.githubusercontent.com/358809/70717994-b654e580-1cef-11ea-92c7-0a4a7a328216.png)

**MASKED**
![image](https://user-images.githubusercontent.com/358809/70718085-dab0c200-1cef-11ea-92b5-bc1483787c40.png)

**MULTIPLY**
![image](https://user-images.githubusercontent.com/358809/70718121-ed2afb80-1cef-11ea-8fde-16514034afdc.png)

**ADD**
![image](https://user-images.githubusercontent.com/358809/70718160-ffa53500-1cef-11ea-88f3-64f79ea7c52a.png)

**SCREEN**
![image](https://user-images.githubusercontent.com/358809/70718235-1e0b3080-1cf0-11ea-95a7-55792b5281aa.png)

**Comment by romainguy** [comment]
I don't know what the combination of transmission and alpha does in Blender. But on the Filament side I believe setting alpha to 1 - transmission should be pretty close. Note that Filament expects pre-multiplied colors, so you need to ensure your multiply color.rgb by color.a either in the shader or by using the appropriate color type when you set the parameter.

**Comment by roxlu** [comment]
Thanks @romainguy  , **I wasn't using pre-multiplied colors**. Once I multiplied the rgb by the alpha things started to look a lot better.  I'm using the color, metallic, roughness and alpha from the BSDF node for the Filament material. I'm setting the reflectance parameter to 0.5, which is also default I believe. See below for a comparison.

![image](https://user-images.githubusercontent.com/358809/70745724-b91dfd80-1d24-11ea-89b3-965d7f0e4218.png)


**TRANSPARENT**
![image](https://user-images.githubusercontent.com/358809/70745530-3a28c500-1d24-11ea-93ba-f70b591d1f1d.png)

**ADD**
![image](https://user-images.githubusercontent.com/358809/70745611-70664480-1d24-11ea-831c-5aab49327478.png)

**MASKED**
![image](https://user-images.githubusercontent.com/358809/70745641-8247e780-1d24-11ea-8c9c-c822ddac47be.png)

**FADE**
![image](https://user-images.githubusercontent.com/358809/70745680-9a1f6b80-1d24-11ea-8884-6e42529a8853.png)

**MULTIPLY**
![image](https://user-images.githubusercontent.com/358809/70745779-e1a5f780-1d24-11ea-9051-f0537d4ffb1a.png)

**SCREEN**
![image](https://user-images.githubusercontent.com/358809/70745808-f1bdd700-1d24-11ea-8aeb-4204a28cdf17.png)

While creating this experiment I noticed (unrelated to the transparency) that my skybox doesn't align with the skybox in Blender. I rotated it by some degrees but isn't there a standard alignment/rotation for skyboxes?

**Comment by romainguy** [comment]
Also remember that Filament shaders expect colors in linear space, so make sure you convert from sRGB to linear (again you can use the appropriate rgb type when setting the parameter or use filament::Color for conversions).

Note that you don't need to do the alpha multiplication in the shader. You can do this instead:

```
materialInstance->setParameter("albedo", RgbaType::sRGB, albedo);
```

This will both pre-multiply and convert to sRGB (pre-multiplication needs to be done in linear space to be correct).
