### ISSUE TITLE
error: undefined reference to 'filament::JNI_OnLoad(_JavaVM*, void*)'

### ISSUE THREAD

**Issue by dilemmacc** [google/filament#1983]
android/filament-android/src/main/cpp/Filament.cpp:38: error: undefined reference to 'filament::JNI_OnLoad(_JavaVM*, void*)'

**Comment by prideout** [comment]
Can we have a few more details?  Are you using our `build.sh` script, are you building from a Mac or Windows, etc.

**Comment by dilemmacc** [comment]
> Can we have a few more details? Are you using our `build.sh` script, are you building from a Mac or Windows, etc.

ok, and thx.
I built from a Mac.
filament build version is 1.4.3.
use your public build.sh script

**Comment by dilemmacc** [comment]
If I wanna to build an android sample apk, do I have to build my "out" folder? Can I use aar included to build it?

**Comment by romainguy** [comment]
You can use the included AARs if you match the versions. It looks like you tried to build Filament's JNI library without building Filament itself first (use `build.sh -i -p desktop,android release` to build everything together).
