### ISSUE TITLE
How to make UI Layer?

### ISSUE THREAD

**Issue by Realitian** [google/filament#1984]
Hi all,
I want to create 2D View overlayered 3d scene.
I think it is possible to create View, Scene, Camera and then set camera projection as Ortho.
but if I render 3d view and 2d view sequentially. then 3d view had been erased by 2d view.

```
if (swapChain && renderer->beginFrame(swapChain)) {
     renderer->render(view);
     renderer->render(uiView);
     renderer->endFrame();
}
```

In order to render uiView over 3d view transparently, what I should do in next?
Thank in advance.

**Comment by prideout** [comment]
You're on the right track.  This is what we do in `FilamentApp.cpp`:

```
uiView->setClearTargets(false, false, false);
uiView->setRenderTarget(View::TargetBufferFlags::DEPTH_AND_STENCIL);
uiView->setPostProcessingEnabled(false);
uiView->setShadowsEnabled(false);
```

**Comment by Realitian** [comment]
Hi, @prideout 
I did same thing as `FilamentApp.cpp:`
but, as just I mentioned, it was erasing the first View, I want to know the way to make transparency View overlapped to others.

**Comment by prideout** [comment]
Ah, I think we don't support overlapping views right now except via RenderTarget.  In other words, you can do:

```
RenderTarget* uiRenderTarget = RenderTarget::Builder()
        .texture(RenderTarget::COLOR, myUiTexture)
        .build(*engine);

uiView->setRenderTarget(uiRenderTarget);
```

For this to work, you'll also need to add a screen-aligned to your primary scene which uses `myUiTexture`.  See `lucy_bloom.cpp` for an example of the RenderTarget API.
