### ISSUE TITLE
can aar be imported is I want to use it in an android project?

### ISSUE THREAD

**Issue by dilemmacc** [google/filament#1985]
I wanna to run an android/sample/hello-camera project.
My action step is as follows:
1、import filament.aar, filamat.aar, gltfio.aar;
2、assemble and build it;
3、install the apk.
4、but crash happened: 
 E/memtrack: Couldn't load memtrack module
 E/Filament: Panic
    in static filament::MaterialParser *filament::details::FMaterial::createParser(backend::Backend, const void *, size_t):487
E/Filament: --------- beginning of crash
 A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 20962 (lament.hellocam), pid 20962 (lament.hellocam)

**Comment by romainguy** [comment]
Thanks for the report but we'll need a complete stack trace. It looks like GPU hardware could not be initialized. Are you using an emulator?
