### ISSUE TITLE
How to use glTF's embedded camera with WebGL?

### ISSUE THREAD

**Issue by cx20** [google/filament#1988]
**Is your feature request related to a problem? Please describe.**
I know that [Project Polly](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly) and [Khronos Virtual City](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VC) models have built-in cool cameras.

[![image](https://user-images.githubusercontent.com/1833979/71208729-0aae2580-22ed-11ea-8ea9-2eb5f420b3b5.png)](https://www.youtube.com/watch?v=l7TB1O51X_M)

**Describe the solution you'd like**
I think it would be cool to use these cameras with Filament.
The following are examples of glTF embeded cameras used by other libraries.
[three.js + Project Polly example](https://cx20.github.io/jsdo.it-archives/cx20/Cnr2/)
[Hilo3d + VC camera example](https://cx20.github.io/gltf-test/examples/Hilo3d/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)

**Describe alternatives you've considered**
I tried investigating how to access the glTF model's embedded camera in Filament, but I didn't understand.

**Comment by prideout** [comment]
This is a sensible feature request.  gltfio currently ignores glTF cameras, mostly because we simply haven't encountered any yet.

We could either expose the camera parameters, or we could create an actual `filament::Camera` entity for each glTF camera.  Not sure yet which would make more sense.

**Comment by prideout** [comment]
I wonder what viewers should do when the aspect ratio of the glTF camera does not match the viewport.  I guess they could either clobber it or use letterboxing.

**Comment by cx20** [comment]
Personally, I don't think you need to apply the glTF camera aspect ratio to the viewer. 
I tried to check other viewers. It seems that many viewers do not apply the aspect ratio of glTF cameras.

|Viewer                                         |Library          |Use aspect radio|
|:----------------------------------------------|:---------------:|:--------------:|
|https://gltf-viewer.donmccurdy.com/            |three.js         |Yes             |
|https://sandbox.babylonjs.com/                 |Babylon.js       |No              |
|https://github.khronos.org/glTF-Sample-Viewer/ |Khronos example  |No              |
|https://github.com/javagl/JglTF                |jgltf            |No              |

**Comment by bejado** [comment]
Preliminary support added: #2663. Will update JS bindings soon as well.

**Comment by cx20** [comment]
@bejado  Thanks for adding support for the glTF embedded camera.
However, when the camera is set on some models ([Duck](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck), [VC](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VC), etc.), the model is not displayed. 
Below are the test results.

|Model                                                                                |Sample                                                                                                                       |Result            |Note                                        |
|:------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------:|:----------------:|:-------------------------------------------|
|[Cameras](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cameras)|[Link](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=Cameras&scale=1&type=glTF)|:white_check_mark:|                                            |
|[Duck](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck)      |[Link](https://cx20.github.io/gltf-test/examples/filament/index.html?model=Duck&scale=1)                                     |:x:               |camera is working but model is not displayed|
|[Virtual City](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VC)|[Link](https://cx20.github.io/gltf-test/examples/filament/index.html?model=VC&scale=0.2)                                     |:x:               |camera is working but model is not displayed|
|[Polly](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly)     |[Link](https://cx20.github.io/gltf-test/examples/filament/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/64017da8f49a618dbeec8ff80f6053cbcb715ad5/polly/project_polly.gltf)|:white_check_mark:|camera is working but there is a problem displaying the model. #2714|

Is it a usage problem?
After loading the model, I set the camera as follows.

```javascript
const cameras = asset.getCameraEntities();
if (cameras.length > 0) {
    const index = Math.floor(Math.random() * cameras.length);
    const c = engine.getCameraComponent(cameras[index]);
    c.setScaling([1, window.innerWidth / window.innerHeight, 1, 1]);
    this.view.setCamera(c);
}
```

**Comment by bejado** [comment]
@cx20 your code looks fine. I’ve been investigating some near/far plane issues with our implementation of glTF camera, perhaps that’s what’s causing the issue. I’ll take a look.. thanks for the additional repro cases.

**Comment by cx20** [comment]
@bejado Thank you for your advice. As you advised, when I changed the near value, the model was displayed.

Duck.gltf's near was `1.0`.
```json
"perspective": {
    "aspectRatio": 1.5,
    "yfov": 0.6605925559997559,
    "zfar": 10000.0,
    "znear": 1.0
},
```
I tried updating the value of near from `1.0` to `0.001` after the model was loaded.
```javascript
const c = engine.getCameraComponent(cameras[index]);
const aspect = window.innerWidth / window.innerHeight;
const fov = aspect < 1 ? Fov.HORIZONTAL : Fov.VERTICAL;
c.setScaling([1, aspect, 1, 1]);
// Adjust by overwriting fov/near/far values
// Change near from 1.0 to 0.001
c.setProjectionFov(60, 1, 0.001, 10000.0, fov);
this.view.setCamera(c);
```
The model is now displayed.
![image](https://user-images.githubusercontent.com/1833979/85217126-39a27280-b3c8-11ea-9e34-32e747900ea7.png)

**Comment by bejado** [comment]
@cx20 Another issue with glTF Viewer has been fixed in #2735. This fixes what appeared to be a near plane issue. You should now be able to load Duck and Virtual City as-is.

**Comment by cx20** [comment]
@bejado Thanks! I've confirmed with the latest version of Filament that Duck and VIrtual City can display without adjusting near/far.

**Comment by cx20** [comment]
@bejado I compared the glTF embedded camera with other libraries.
In Filament I think the camera is a bit closer to the model.

Babylon.js + TransmissionTest.gltf result:
![image](https://user-images.githubusercontent.com/1833979/87155744-75a96300-c2f6-11ea-918b-a14e7c144abc.png)

[Filament + TransmissionTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/11287247c2cdd23f0856f94f2fdeb1ab9bad617f/examples/filament/index.html?category=tutorialModels&model=TransmissionTest&scale=3&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/87155804-94a7f500-c2f6-11ea-810c-13b475f84630.png)

**Comment by romainguy** [comment]
Can you compare at the same viewport size?

**Comment by bejado** [comment]
@cx20 Do you have a link to the glTF file you're using?

**Comment by cx20** [comment]
@bejado  Refer to the following location for `TransmissionTest.gltf`.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/KHR_materials_transmission_test_model/2.0/TransmissionTest

**Comment by cx20** [comment]
@romainguy As you advised, I tried to make the viewports the same size. The results seem to be almost identical for the squares. A difference is seen in the case of the wide size.

| |Babylon.js|Filament|
|-------|-------|-------|
|Square|![image](https://user-images.githubusercontent.com/1833979/87211234-81774280-c353-11ea-923b-9836f5d8e3b7.png)|![image](https://user-images.githubusercontent.com/1833979/87211244-8936e700-c353-11ea-82ba-823d74dbf33c.png)|
|Wide|![image](https://user-images.githubusercontent.com/1833979/87211249-918f2200-c353-11ea-9e9a-3498b274cc39.png)|![image](https://user-images.githubusercontent.com/1833979/87211254-97850300-c353-11ea-92d7-cc53d66489fc.png)|

**Comment by romainguy** [comment]
It seems like a problem of vertical vs horizontal FoV.

**Comment by romainguy** [comment]
In Filament you can choose which one, I assume our glTF implementation picks the wrong one.

**Comment by cx20** [comment]
I don't know what is the correct answer, but I think this glTF model's built-in camera is designed to fit on the screen.

**Comment by romainguy** [comment]
Yeah that would make sense. That just means we need to flip our axis :) @bejado can you check the spec vs our implementation please?

**Comment by bejado** [comment]
We had our axis right, but I was setting the scaling wrong :) Thanks for pointing this out @cx20

**Comment by cx20** [comment]
@bejado Thanks! I modified my sample code based on your modification and the model fits the screen.

```javascript
const aspect = window.innerWidth / window.innerHeight;
//c.setScaling([1, aspect, 1, 1]);   // before
c.setScaling([1 / aspect, 1, 1, 1]); // after
```

[Filament + TransmittionTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/947df43761e7af1df541421cda5e3728ee0c580d/examples/filament/index.html?category=tutorialModels&model=TransmissionTest&scale=3&type=glTF)
| |Babylon.js|Filament|
|-------|-------|-------|
|Wide|![image](https://user-images.githubusercontent.com/1833979/87211249-918f2200-c353-11ea-9e9a-3498b274cc39.png)|![image](https://user-images.githubusercontent.com/1833979/87425388-815b9900-c618-11ea-99e3-d44131e882f7.png)|
