### ISSUE TITLE
.Net Compatability 

### ISSUE THREAD

**Issue by deltamish** [google/filament#1993]
How to use the API from .Net ? 

I tried following approach 
http://tom-shelton.net/index.php/2008/12/11/creating-a-managed-wrapper-for-a-lib-file/

But I feel its too time taking as I will have to take a look into all the probable classes and function that might be called and expose them. 

Any other ideas sis greatly appreciated. 

Cheers ;)

**Comment by prideout** [comment]
I believe .NET 5 has support for Java interop, that might be something you could try exploring.

**Comment by amerkoleci** [comment]
Probably filament needs C api/layer, then there can be pinvoked

**Comment by romainguy** [comment]
This should be addressed by #139 then when we get around to it.
