### ISSUE TITLE
Standalone backend rendering

### ISSUE THREAD

**Issue by amerkoleci** [google/filament#2001]
**Is your feature request related to a problem? Please describe.**
Just new feature request.

**Describe the solution you'd like**
I think would be good to have backend (rendering) to be standalone as to be easy to integrate in other engines/framework.

**Describe alternatives you've considered**
Maybe having a guide how backend works would be good, how to create shaders, how is vulkan integration done? Is it tight with JobSystem? how renderings happens? How to implement new backend D3D11/D3D12?

**OS and backend**
All

**Comment by romainguy** [comment]
We already keep our backend library separated but it is not our goal to maintain a public API/documentation/etc. for it at the moment. We discussed this but we just don't have the resources for this considering it is not the main goal of the project. The backends themselves are fairly straightforward, most of the complexity lies in Filament itself (that's where the frame graph lives, where the job system is used, etc.). The goal of the backends is to provide high-level abstractions over low-level graphics APIs. They do not know anything about lighting, materials, forward vs deferred rendering, etc.
