### ISSUE TITLE
Backend enum in Java is out-of-sync with C definition

### ISSUE THREAD

**Issue by danlehmann** [google/filament#2005]
**Describe the bug**
Both Java and C have an enum to specify the backend. They are supposed to match, as Engine.java uses ordinal() to pass the integer value down.

The Java enum is missing METAL however.

**To Reproduce**
Using Engine.Backend.NOOP from Java causes Filament to load the METAL backend.

**Expected behavior**
It should call the NOOP backend.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - GPU: NVIDIA GTX 980
 - Backend: NOOP / METAL

**Additional context**
Java definition (Engine.java):
public enum Backend {
        /**
         * Automatically selects an appropriate driver for the platform.
         */
        DEFAULT,
        /**
         * Selects the OpenGL ES driver.
         */
        OPENGL,
        /**
         * Selects the experimental Vulkan driver.
         */
        VULKAN,
        /**
         * Selects the no-op driver for testing purposes.
         */
        NOOP,
    }

C definition (DriverEnums.h):
enum class Backend : uint8_t {
    DEFAULT = 0,  //!< Automatically selects an appropriate driver for the platform.
    OPENGL = 1,   //!< Selects the OpenGL driver (which supports OpenGL ES as well).
    VULKAN = 2,   //!< Selects the Vulkan driver if the platform supports it.
    METAL = 3,    //!< Selects the Metal driver if the platform supports it.
    NOOP = 4,     //!< Selects the no-op driver for testing purposes.
};

**Comment by danlehmann** [comment]
I have a patch pending to fix this, but according to the contributor guide I should start with an issue, so here it is :-)

**Comment by romainguy** [comment]
Oops great catch. We'd be happy to take your patch :)

**Comment by romainguy** [comment]
@bejado

**Comment by danlehmann** [comment]
https://github.com/google/filament/pull/2006
