### ISSUE TITLE
Request for headless swapChain support with Vulkan

### ISSUE THREAD

**Issue by danlehmann** [google/filament#2007]
**Is your feature request related to a problem? Please describe.**
I am building an app that is rendering a given scene from lots of different viewpoints. The rendered images are then passed back to the CPU and further used there. They are not displayed on-screen. My main goal is to maximize the throughput of images/second.

Using the OpenGL backend, this works:
val nativeSurface = new NativeSurface(width, height)
val swapChain = engine.createSwapChainFromNativeSurface(nativeSurface, 0)
// render..
renderer.readPixels(...)

This also works:
val swapChain = engine.createSwapChain(width, height, 0)
// render..
renderer.readPixels(...)

Trying the same thing with Vulkan fails in both cases. Trying to create a NativeSurface fails with this error:
java: symbol lookup error: /tmp/nativelib-loader_16935058711867175538/libfilament-jni.so: undefined symbol: glXChooseFBConfig

Trying without a NativeSurface fails like this:
UNASSIGNED-GeneralParameterError-RequiredParameter(ERROR / SPEC): msgNum: 0 - vkAcquireNextImageKHR: required parameter swapchain specified as VK_NULL_HANDLE
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-vkAcquireNextImageKHR-swapchain-parameter(ERROR / SPEC): msgNum: 0 - Invalid SwapchainKHR Object 0x0. The Vulkan spec states: swapchain must be a valid VkSwapchainKHR handle (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-swapchain-parameter)
    Objects: 1
        [0] 0, type: 1000001000, name: NULL
VUID-vkAcquireNextImageKHR-semaphore-01780(ERROR / SPEC): msgNum: 0 - vkAcquireNextImageKHR: Semaphore and fence cannot both be VK_NULL_HANDLE. There would be no way to determine the completion of this operation. The Vulkan spec states: semaphore and fence must not both be equal to VK_NULL_HANDLE (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01780)
    Objects: 1
        [0] 0x7f8b5441fb90, type: 3, name: NULL

**Describe the solution you'd like**
It would be great if the Vulkan backend had the same functionality as the OpenGL backend.

**OS and backend **
I reproduced this on Ubuntu 19.10.

The second issue can be easily reproduced without java, by tweaking filament_rendering_test.cpp (pass Backend::VULKAN into Engine::create()). I am seeing the exact same issue here.

**Comment by romainguy** [comment]
Looks like part of the issue is that `new NativeSurface()` from Java always attempts to call into GLX (see `android/filament-android/src/main/cpp/nativewindow/Linux.cpp`). `NativeSurface` is only used on desktop, not Android, so it was never designed with Vulkan in mind.

Now why creating a swap chain without a native surface crashes, I have no idea. That's for @prideout to figure out :)

**Comment by prideout** [comment]
This issue should now be fixed, we've added the missing functionality to the Vulkan backend in recent weeks.
