### ISSUE TITLE
Using the Vulkan backend, resizing a Java app crashes

### ISSUE THREAD

**Issue by danlehmann** [google/filament#2008]
**Describe the bug**
My JVM application uses Filament using the Vulkan backend to draw content in a FilamentCanvas. Things work well until I resize the component at which point I am seeing this error:
N5utils18PostconditionPanicE
in void filament::backend::VulkanDriver::commit(Handle<filament::backend::HwSwapChain>):900
reason: Stale / resized swap chain not yet supported.
#0 /tmp/nativelib-loader_7364687860388792411/libfilament-jni.so(_ZN5utils6TPanicINS_18PostconditionPanicEE5panicEPKcS4_iS4_z+0x150) [0x7f5cb62a1b20]
// snip
terminating with uncaught exception of type utils::PostconditionPanic

**To Reproduce**
I am on Ubuntu 19.10, in case that matters.

Any JVM app using FilamentCanvas should show the same error. However, I am seeing the same error in the vk_animation test app, without Java being involved. Simply launch and resize the window and observe the crash.

**Expected behavior**
No crash :-)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - GPU: NVIDIA GTX 980
 - Backend: Vulkan

**Comment by prideout** [comment]
This is a dup of #334
