### ISSUE TITLE
Division by zero in FScene::computeLightRanges

### ISSUE THREAD

**Issue by syoyo** [google/filament#201]
**Describe the bug**

https://github.com/google/filament/blob/master/filament/src/Scene.cpp#L264

This may trigger division-by-zero error(`f.w = 0.0`), resulting possible unexpected behavior when building light trees.

**To Reproduce**

Enable UBSAN.  then,

```
./samples/material_sandbox -i ../../samples/envs/uv2 ../../assets/models/sphere/sphere.obj
```

**Expected behavior**

Add division-by-zero check. Set `inf` to zrange if required.

**Comment by syoyo** [comment]
Also found another Division-by-zero error in CubemapIBL.cpp: 

https://github.com/google/filament/blob/master/tools/cmgen/src/CubemapIBL.cpp#L61

**Comment by romainguy** [comment]
In the second case I don't think the division by 0 can ever happen: `f` is 0 only if `(a - 1) * ((a + 1) * (NoH * NoH))` is `-1` but `a` is always in the range `0..1`.

**Comment by syoyo** [comment]
For the second case, it could be reproducable with

```
$ ./cmgen -x ibls uv4

Level 0, roughness = 0.000, roughness(lin) = 0.000
../../tools/cmgen/src/CubemapIBL.cpp:62:20: runtime error: division by zero
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../tools/cmgen/src/CubemapIBL.cpp:62:20 in 
...
```

It happens only in a singular situation(`NoH = 1.000, linearRoughness = 0.000` input)

**Comment by romainguy** [comment]
Of course, you're right. We should probably just clamp roughness like we do at runtime.
