### ISSUE TITLE
Enabling true VSync with SwapInterval

### ISSUE THREAD

**Issue by stasgora** [google/filament#2014]
I'm trying to achieve a proper v-sync with Filament (not by sleeping for a hard-coded amount of time like in the examples). Since I'm using GLFW for creating a window I looked at how it's done there [```glfwSwapInterval()```](https://www.glfw.org/docs/latest/group__context.html#ga6d4e0cdf151b5e579bd67f13202994ed) and than tried to do something similar using Filaments internal context (take a look at my [test](https://github.com/stasgora/filament/commit/f6588ab09a27f97390447e73338951f2d24e0e2f) for GLX).

However in spite of calling the same gl methods, swapping buffers only waits for the next refresh when using the glfw functions. Could you tell me why is that and what would I need to do to get v-sync working?
Looking at other issues I found this #636 and would gladly see it implemented with a simple flag an application can set as suggested recently.

**Comment by romainguy** [comment]
What do you mean by "wapping buffers only waits for the next refresh when using the glfw functions"?

**Comment by romainguy** [comment]
This will be addressed by #636 .

**Comment by prideout** [comment]
This is something we want to look into soon, it's a pretty big hole in Filament's functionality for desktop platforms.

**Comment by stasgora** [comment]
> What do you mean by "wapping buffers only waits for the next refresh when using the glfw functions"?

I meant that after calling the `glfwSwapInterval(1)` and then continuously `glfwSwapBuffers`, the loop runs at 60fps as expected but calling the underlying `SwapIntervalMESA(1)` from PlatformGLX didn't make any difference - main loop was still running as fast as it could.

Thought it would be that simple but it's great you plan on properly implementing it soon.
