### ISSUE TITLE
Can filament run on flutter?

### ISSUE THREAD

**Issue by dilemmacc** [google/filament#2036]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**OS and backend**
Is this feature OS/backend specific? If so, explain why.

**Comment by romainguy** [comment]
The way Filament works it should be able to work with Flutter as part of a SurfaceView or SurfaceTexture. I don't know Flutter enough to know exactly how the integration works but it's no different than with camera, WebView or Google Maps. You'd have to write a shim similar to UiHelper most likely.

**Comment by maheshmnj** [comment]
I think this will make your day Take a look at this tweet https://twitter.com/JamesBlasco/status/1265643189492428802
