### ISSUE TITLE
Allow other views to draw over Filament surface in not opaque mode

### ISSUE THREAD

**Issue by vberezkin** [google/filament#2037]
**Describe the bug**
Filament in not opaque mode brings itself to front and not allow other views to draw over it

**To Reproduce**
1. Place Filament SurfaceView in FrameLayout or RelativeLayout as first View and call setOpaque(false) on it.
2. Other views are hidden by Filament content.

**Expected behavior**
Other views should be drawn over filament SurfaceView

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Android 10

**Additional context**
To Fix it just replace view.setZOrderOnTop(true) with view.setZOrderMediaOverlay(true) in https://github.com/google/filament/blob/2854c0627dc63aad78fdb4620d2bfdff9d068b9f/android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java#L344

**Comment by romainguy** [comment]
Thanks for the report, but this is not the correct fix, at least not for all situations. The current API was implemented to draw Filament blended over regular Android views. Switching to `setZOrderMediaOverlay()` would break that. The correct solution is to add `setMediaOverlay(boolean)` to `UiHelper` — or something similar — so the app can decide which behavior it wants.
