### ISSUE TITLE
Dockerfile build

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2052]
We need a Dockerfile which can build everything, especially the webgl stuff.

**Comment by romainguy** [comment]
Could you explain a little more what you mean please? I don't know what a Dockerfile is (I assume it's for Docker but beyond that). Specifically what do you mean by "everything"? Do you need to build iOS, Android, webgl, Linux, Windows and macOS binaries? Filament should be fairly easy to build in CI already given the script we provide (build.sh).

**Comment by dandingol03** [comment]
> Could you explain a little more what you mean please? I don't know what a Dockerfile is (I assume it's for Docker but beyond that). Specifically what do you mean by "everything"? Do you need to build iOS, Android, webgl, Linux, Windows and macOS binaries? Filament should be fairly easy to build in CI already given the script we provide (build.sh).

i  need linux docker file

**Comment by zhubinsheng** [comment]
> i need linux docker file

i need linux docker file
