### ISSUE TITLE
./build.sh -p android release fail

### ISSUE THREAD

**Issue by chesed71** [google/filament#2053]
**Describe the bug**
./build.sh -p android release failed as below error.
I am using current up-to-date master branch. 
It seems it doesn't know what 'release' means.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kyungsoohong/workspace/filament/android/filament-android/build.gradle' line: 59

* What went wrong:
A problem occurred configuring project ':filament-android'.
> Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

**To Reproduce**
1. ./build.sh -p android release

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - GPU: 
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
Make sure you have Android Studio 3.6 RC1 installed, the latest SDK and run a clean build first with ./build.sh -c. Alternatively de delete all the build/ directories in Android/ and subfolders. You will also need Filament's tip of tree.

**Comment by chesed71** [comment]
Thanks!
