### ISSUE TITLE
An error occurs in createTextureFromJpeg() of Filament v1.4.x

### ISSUE THREAD

**Issue by cx20** [google/filament#2055]
**Describe the bug**
I updated the library used in the my sample from Filament `v1.3.2` to `v1.4.x`, and now I get an error.
Is it because the usage has changed?

```
filament.js:6 
Uncaught (in promise) TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
    at Object.Filament._createTextureFromJpeg (filament.js:6)
    at Engine.Filament.Engine.createTextureFromJpeg (filament.js:6)
    at new App (index.js:152)
    at Object.onReady (index.js:207)
    at filament.js:6
    at filament.js:6
```

**To Reproduce**
[Filament v1.4.4 sample:](https://rawcdn.githack.com/cx20/webgl-test/6352e82acd9aa94e8a52ec94f4715c42d7ff8cbd/examples/filament/texture/index.html)
![image](https://user-images.githubusercontent.com/1833979/72736294-cad6a880-3be0-11ea-867f-da8c5c6a0db9.png)

**Expected behavior**
[Filament v1.3.2 sample:](https://rawcdn.githack.com/cx20/webgl-test/1d6959cb9418c2a4ee734c86a2a00d89d3595763/examples/filament/texture/index.html)
![image](https://user-images.githubusercontent.com/1833979/72736265-bc888c80-3be0-11ea-8480-cab663db4b9e.png)

**Desktop (please complete the following information):**
- OS: Windows 10 + Chrome 79
- GPU: Intel HD Graphics 520
- Backend: WebGL/ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)

**Comment by prideout** [comment]
We have a JPEG decoder in our wasm bundle (via gltfio) and that's what we should be using here.  I'll fix this and ensure that it gets tested in one of our samples.

(This broke when we added JPEG support to gltfio for web in fb9cf43768a82e975dfba85f0a62f713c0a17c2f  because gltfio requires a byte buffer rather than a DOM image.)

**Comment by cx20** [comment]
Thanks! I have confirmed that `createTextureFromJpeg()` works with the latest version of Filament.
[Filament latest result:](https://rawcdn.githack.com/cx20/webgl-test/4c14647d217c69577c02651dd686f22e03fb67df/examples/filament/texture/index.html)
![image](https://user-images.githubusercontent.com/1833979/72846143-55073580-3ce3-11ea-800e-38ec48e7fd4a.png)
