### ISSUE TITLE
Option to configure `CommandBufferQueue` size.

### ISSUE THREAD

**Issue by roxlu** [google/filament#2057]
I'm rendering a scene with ~3000 items that share ~100 meshes and it seems that the `CommandBufferQueue` is running out of space.  In `Allocators.h` I see the buffer sizes, but I'm wondering how to change the size; or maybe there is another way to render 3000 items?

**Comment by romainguy** [comment]
I talked to @pixelflinger and this is pretty much what we wanted to add. It was just never a priority so far. We'd love a test scene if you have one (a glTF file would work great if that's not a problem for you).

**Comment by pixelflinger** [comment]
I had to increase `CONFIG_PER_RENDER_PASS_ARENA_SIZE` to 3 MiB, `CONFIG_PER_FRAME_COMMANDS_SIZE` to 2 MiB and `CONFIG_MIN_COMMAND_BUFFERS_SIZE` to 3 MiB to be able to render a ~3400 items scene.

We will make this user-settable at Engine creation time eventually.  Also maybe we could increase the defaults a bit.

**Comment by roxlu** [comment]
I want to look into this and wondering how we can make the buffer sizes configurable. I've looked into some files and found the following buffer sizes which should be configurable. In [Allocators.h](https://github.com/google/filament/blob/main/filament/src/details/Allocators.h ) we have: 

-  `CONFIG_PER_RENDER_PASS_ARENA_SIZE`
- `CONFIG_PER_FRAME_COMMANDS_SIZE`
- `CONFIG_MIN_COMMAND_BUFFERS_SIZE`

And in [OpenGLDriver.cpp](https://github.com/google/filament/blob/main/filament/backend/src/opengl/OpenGLDriver.cpp#L136) we have:

- `mHandleArena("Handles", 2U * 1024U * 1024U),`

I didn't find other other buffer sizes which should be configurable; but there might be more. 

@pixelflinger and @romainguy what are you thoughts on this? Should we create `Builders` for these too?

**Comment by roxlu** [comment]
@romainguy what about using #defines so you can at least configure them? This could be added in 5min and we have a solution that works for now.
