### ISSUE TITLE
Best way to render mutable vertex buffer size object?

### ISSUE THREAD

**Issue by xu-xionglong** [google/filament#2059]
I was used to using native OpenGL which supports sending a mutable size cpu buffer to gpu directly by glVertexAttribPointer. The api for operating vertex data in filament is VertexBuffer and the vertex size should be specified during construction. 
Should I recreate a new VertexBuffer whenever the size is changed or create a VertexBuffer with a    
big capacity and update parts of the buffer in runtime?  I prefer the second solution but I can't find the method to draw only parts of a VertexBuffer.

**Comment by romainguy** [comment]
The second solution is what you are looking for. When you call `geometry()` on `RenderableManager::Builder` you can specify the offset and count for the indices to use in the index buffer. You can also use `setGeometryAt()` to change those values for an existing renderable
