### ISSUE TITLE
webgl build broken

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2066]
./build.sh -p webgl release

SimpleTriangle.bin creates an error during the build. appears to be missing.

**Comment by prideout** [comment]
Works for me, the file landed here:

`./out/cmake-webgl-release/web/samples/SimpleTriangle.bin`

**Comment by prideout** [comment]
The `animation.html` sample works too, for me anyway.  I'm using macOS.  What is your host platform?  Can you paste some of your build output?

**Comment by prideout** [comment]
Looks like the GitHub Actions is broken, but for a different reason:

```
../../filament/src/Texture.cpp:131:9: error: value of type 'filament::backend::TextureUsage' is not contextually convertible to 'bool'
        assert(mUsage & TextureUsage::SAMPLEABLE);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/runners/2.164.0/work/filament/filament/build/web/emsdk/upstream/emscripten/system/include/libc/assert.h:8:27: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                          ^~~
../../filament/src/Texture.cpp:131:9: error: invalid operands to binary expression ('filament::backend::TextureUsage' and 'int')
        assert(mUsage & TextureUsage::SAMPLEABLE);
```

**Comment by unicomp21** [comment]
this is probably overkill, I created a pull request for the repro

https://github.com/google/filament/issues/2066

**Comment by romainguy** [comment]
From the PR the failure happens with git checkout -b v1.4.4. Looks like it's fine in the master branch.

**Comment by unicomp21** [comment]
[623/627] Building CXX object filament/CMakeFiles/filament.dir/src/View.cpp.o
[624/627] Linking CXX static library filament/libfilament.a
[625/627] Linking CXX static library libs/filameshio/libfilameshio.a
[626/627] Building CXX object tools/filamesh/CMakeFiles/filamesh.dir/src/main.cpp.o
[627/627] Linking CXX executable tools/filamesh/filamesh
Building WebGL release...
Setting environment variables:
EMSDK = /tmp/emsdk

Embree not found, pipeline features are disabled.
-- The ASM compiler identification is Clang
-- Found assembler: /tmp/emsdk/upstream/emscripten/emcc
-- DFG LUT size set to 64x64
-- Configuring done
CMake Error in web/samples/CMakeLists.txt:
  Cannot find source file:

    /tmp/filament/third_party/models/AnimatedTriangle/SimpleTriangle.bin

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


-- Generating done
-- Build files have been written to: /tmp/filament/out/cmake-webgl-release
The command '/bin/sh -c ./build.sh -p webgl release' returned a non-zero code: 1
jdavis@jdavis-Inspiron-3185:~/repo/github/filament/docker$

**Comment by unicomp21** [comment]
It happens on master too ^
When doing a docker build on ubuntu 19.10

**Comment by romainguy** [comment]
It's a silly case sensitivity issue. The file is called simpleTriangle not SimpleTriangle. @prideout

**Comment by unicomp21** [comment]
Nice catch @romainguy !

The Dockerfile I provided, think it would be cool if there was something similar in the repo for build.sh, to assist those who like driving their builds w/ docker.

**Comment by romainguy** [comment]
We don't know anything about Docker and I don't think we'd want to take on maintaining yet another build file.

**Comment by unicomp21** [comment]
Understood, but it ain't that hard to pick up ;)
