### ISSUE TITLE
Support boost fibers on webassembly

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2068]
**Is your feature request related to a problem? Please describe.**
Within c++ on webassembly we have no coroutine support.

**Describe the solution you'd like**
Clang can now target webassembly, we should be able to now support boost fibers.

**Describe alternatives you've considered**
Emscripten Asyncify is another option, but boost fibers is part of a standard.

**OS and backend**
This is webassembly specific.

**Comment by romainguy** [comment]
Does this require adding a dependency to boost?

**Comment by unicomp21** [comment]
Yeah, I guess that's a no no?

**Comment by romainguy** [comment]
In general we don't take dependencies at all in Filament (only in the host tools). We did make two exceptions for a Vulkan memory allocator and for a fast hashmap. Boost is definitely not something we want to depend on.

**Comment by unicomp21** [comment]
Isn't coroutine support kinda fundamental to a graphics/game engine?

**Comment by romainguy** [comment]
Filament already uses a job system to multithread pretty much every aspect of its operation. It's single threaded when we compile to WASM currently and we'll switch to WebAssembly Threads once they are widely supported. They're already available in Chrome 75. @prideout
