### ISSUE TITLE
Rendering multiple instances of the same `filamesh::MeshReader::Mesh`?

### ISSUE THREAD

**Issue by roxlu** [google/filament#2091]
When I use the `filamesh` util to create a `.filamesh` file and the `filamesh::MeshReader` to load this mesh, it creates the vertex and index buffers together with a `utils::Entity` which represents a renderable:

```c++
struct Mesh {
    utils::Entity renderable;
    filament::VertexBuffer* vertexBuffer = nullptr;
    filament::IndexBuffer* indexBuffer = nullptr;
};
```

When I want to create multiple instances of this mesh (e.g. rendering many trees of the same mesh) what is the recommended approach? Do I load the mesh, keep it around and create new renderable entities for each instance I want to draw? 

If this is the case you would need to copy the properties of the entity. Some can be retrieved via the getters in `RenderableManager.h`  like `getPrimitiveCount()`, `getMaterialIntanceAt()`.

But how would I get the values for the calls to `setGeometryAt()`?  The `utils::Entity` aka renderable does not have getters that allow me to retrieve all the necessary information and the `filamesh::MeshReader` doesn't keep the necessary info either.  

```c++
void setGeometryAt(Instance instance, size_t primitiveIndex,
        PrimitiveType type, VertexBuffer* vertices, IndexBuffer* indices,
        size_t offset, size_t count) noexcept;

```
This seems to be somewhat related to `gltfio` and this issue: https://github.com/google/filament/issues/1513.

**Comment by romainguy** [comment]
This is just a simple helper API for samples or simple apps, it’s not meant to do more than it provides. You would indeed have to create multiple renderables. To do so you’d need to expose the information about each part. Note that the filamesh format is fully documented in the readme file of the filamesh tool if you want to create your own more advanced loader.

**Comment by prideout** [comment]
If you craft a glTF and create multiple `node` objects that reference the same `mesh` object, gltfio will do the right thing by sharing the same VertexBuffers and IndexBuffers amongst several renderables.  That other issue you referenced is more about efficiently instancing the entire glTF asset.

**Comment by roxlu** [comment]
OK thanks.
