### ISSUE TITLE
Consider moving bitangent construction to fragment shader.

### ISSUE THREAD

**Issue by prideout** [google/filament#2092]
We currently reconstruct the bitangent in `main.vs` but popular normal map baking tools expect this to occur in the fragment shader.  More info in [this](https://medium.com/@bgolus/generating-perfect-normal-maps-for-unity-f929e673fc57) article. See especially "comments from the original mikktspace.h".

To verify the correctness of normal mapping, it might be worth crafting a test model.

On a related note, we should consider adding a mikktspace option to `SurfaceOrientation`, since this is the industry standard; however this would be slow since it produces an unindexed mesh.

**Comment by romainguy** [comment]
BTW I realize I already did the other important bit of not using normalized vectors: https://github.com/google/filament/pull/1813

**Comment by prideout** [comment]
One benefit of this would be freeing up some varyings for other uses.
