### ISSUE TITLE
Does lookAt returns a left handed matrix 😲 ?

### ISSUE THREAD

**Issue by roxlu** [google/filament#2094]
While writing this issue, I've got the strong feeling that I'm wrong and Filamant is correct ... but as always I'm up for a lesson. The docs, section _8.6 Coordinate Systems_ describes that Filament uses a right handed coordinate system +X = right, +Y = up, +Z = forward. *Normally a camera looks into the negative Z right?* Is this the difference with other right handed libs: that we look into the positive Z?  

When I create a basic lookat matrix like using the code below, I get this result:

```
 1.00,  0.00,  -0.00,  0.00
-0.00,  1.00,  -0.00,  0.00 
 0.00,  0.00,   1.00,  15.00
 0.00,  0.00,   0.00,  1.00
``` 

Using this test case. 

```c++
#include <stdio.h>
#include <stdlib.h>
#include <math/mat4.h>

static void print_mat4(const char* title, filament::math::mat4& m);

int main(int argc, char* argv[]) {

  filament::math::mat4 m;
  filament::math::float3 p(0.0, 0.0, 15.0);
  filament::math::float3 t(0.0, 0.0, 0.0);
  filament::math::float3 u(0.0, 1.0, 0.0);

  m = m.lookAt(p, t, u);

  print_mat4("lookat", m);

  return 0;
}

static void print_mat4(const char* title, filament::math::mat4& mat) {

  printf("Matrix: %s.\n", title);

  double* m = (double*)&mat[0][0];

  printf("%2.2f, %2.2f, %2.2f, %2.2f\n", m[0], m[4], m[8], m[12]);
  printf("%2.2f, %2.2f, %2.2f, %2.2f\n", m[1], m[5], m[9], m[13]);
  printf("%2.2f, %2.2f, %2.2f, %2.2f\n", m[2], m[6], m[10], m[14]);
  printf("%2.2f, %2.2f, %2.2f, %2.2f\n", m[3], m[7], m[11], m[15]);
}
```

I've got a little repository where I compare different math libraries.  These are the results of other libraries using the same eye/target/up vectors.

```
Lookat matrices test with the GLM library (right handed)
---------------------------------------------------------
 1.00, -0.00,  0.00, -0.00
 0.00,  1.00,  0.00, -0.00
-0.00, -0.00,  1.00, -15.00
 0.00,  0.00,  0.00,  1.00

Lookat matrices test with the Songho library
----------------------------------------------
[  -1.00000    0.00000    0.00000    0.00000]
[   0.00000    1.00000    0.00000    0.00000]
[   0.00000    0.00000   -1.00000   15.00000]
[   0.00000    0.00000    0.00000    1.00000]

Lookat matrices test with the linmath library (right handed)
-------------------------------------------------------------
 1.00, -0.00,  0.00,  0.00
 0.00,  1.00,  0.00,  0.00
-0.00, -0.00,  1.00, -15.00
 0.00,  0.00,  0.00,  1.00

Lookat matrices test with the mathfu library (right handed) 
--------------------------------------------------------------
 1.00, -0.00, -0.00,  0.00
 0.00,  1.00,  0.00, -0.00
-0.00, -0.00,  1.00, -15.00
 0.00,  0.00,  0.00,  1.00
```

**Comment by romainguy** [comment]
The docs say:
"Filament's Camera looks towards its local -Z axis. That is, when placing a camera in the world without any transform applied to it, the camera looks down the world's -Z axis."

I'm not sure where you got the info that +Z is forward.

**Comment by roxlu** [comment]
@romainguy I was a confused because of the result of the lookat function and because the caption under figure says +Z, but thanks for clearing that up.

But when the system is right handed and the camera looks along the negative Z shouldn’t the result be -15?

**Comment by romainguy** [comment]
I see where the confusion comes from. Our `lookAt` returns the post (or model matrix/transform) of the camera, not what's commonly called the view matrix. If you want the view matrix, take the inverse of what `lookAt` computes and you'll get the same result as glm for instance.

```
print_mat4("lookat", inverse(m));
```

```
1.00, 0.00, 0.00, -0.00
0.00, 1.00, 0.00, -0.00
0.00, 0.00, 1.00, -15.00
0.00, 0.00, 0.00, 1.00
```

**Comment by roxlu** [comment]
Thanks doesn't it make more sense to follow the convention regarding this?

**Comment by romainguy** [comment]
I would dispute it's an actual convention but more importantly Filament APIs expect model matrices, not "view" matrices. We do have a `Camera::getViewMatrix()` for convenience and for people used to this terminology but you never set the view matrix yourself. You either call `Camera::lookAt()` or `Camera::setModelMatrix()` (all the former does is `setModelMatrix(mat4f::lookAt(eye, center, up))` anyway).

**Comment by roxlu** [comment]
Ah I see, thanks for explaining!
