### ISSUE TITLE
Can mipgen handle 8bit grayscale + alpha PNG images?

### ISSUE THREAD

**Issue by roxlu** [google/filament#2098]
I'm using `./mipgen --compress=astc_fast_ldr_4x4 [input] [output]` with a 8-bit grayscale + alpha PNG image and the result looks like the left object with the "gradient" bars. On the right you can see another object that uses the same image but then converted using this command: `convert mat-40cm.png -type TrueColorMatte -define png:color-type=6 mat-40-truecolor.png`

![image](https://user-images.githubusercontent.com/358809/73861739-bed42300-483d-11ea-9cba-727334a83226.png)

I haven't  looked into mipgen, but I know that libpng supports converting [from grayscale to rgb. ](https://github.com/kas1e/Irrlicht/blob/master/source/Irrlicht/CImageLoaderPNG.cpp#L184)

This is the 8bit grayscale image that causes this issue (hopefully the image won't be converted by github, but probably will). I'm happy to share it via email. 

![mat-40cm](https://user-images.githubusercontent.com/358809/73862285-a7e20080-483e-11ea-9ca6-ff007a6e3982.png)

**Comment by prideout** [comment]
Does this bug only happen when using ASTC compression?

**Comment by roxlu** [comment]
Just tested with `s3tc_rgba_dxt5`  which gives me the same result.

**Comment by roxlu** [comment]
I just noticed that the bands appear when I zoom in: https://imgur.com/a/fTrR5K9 
and in that video the culling of these meshes with the bands seems to be off (?) ...  I also noticed that the transparency of the red cube changes when I spin around;  not sure if that's to be expected.

**Comment by romainguy** [comment]
The transparency of the cube doesn't change, you are just seeing the specular reflections (which are not affected by alpha unless you set the blending mode to `fade`).

**Comment by romainguy** [comment]
Looks like the meshes with bands just have inverted normals.

**Comment by roxlu** [comment]
> Looks like the meshes with bands just have inverted normals (which can currently happen if you use a negative scale factor).

Wow, how do you see that?  This was indeed the case; somehow the normals were flipped in Blender.  I fixed them and now  that issue is solved: 

![image](https://user-images.githubusercontent.com/358809/73876667-ac66e300-4857-11ea-9eaa-5753fae2f425.png)

**Comment by roxlu** [comment]
> The transparency of the cube doesn't change, you are just seeing the specular reflections (which are not affected by alpha unless you set the blending mode to

I thought something like that was the case, though I'm using "fade" as blending. 

```glsl
material {
    name : color,
    shadingModel : lit,
    blending: fade,
    parameters : [
        { type : float3, name : albedo },
        { type: float, name: roughness },
        { type: float, name: metallic },
        { type: float, name: alpha }
    ],
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor.rgb = materialParams.albedo * materialParams.alpha;
        material.baseColor.a = materialParams.alpha;
        material.roughness = materialParams.roughness;
        material.metallic = materialParams.metallic;
    }
}
````

**Comment by romainguy** [comment]
This is now fixed, sorry for the wait!
