### ISSUE TITLE
Spherical harmonic indirect lighting appears to be inverted along Y axis compared to Skybox

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#2103]
Diffuse lighting from indirect lighting appears to be inverted along the Y axis, compared to the Skybox cube map from which the spherical harmonic values were derived.

To test this (using library version 1.4.5), we used the debug cube map found in section 8.6.3 (Figure 89) of the "Physically Based Rendering in Filament" documentation.  We used cmgen to create the SH values.
The diffuse lighting for surfaces facing the +/-X and +/-Z axes look correct, but +/-Y faces are getting the opposite lighting.  The cube map in the skybox appears to render correctly, and the specular reflections from the skybox seem correct.  The problem seems to be the SH values (or how they are interpreted by Filament).

Given that there are several steps to set up this lighting/skybox combo, it is possible that we are doing something wrong, but I have tried to confirm each step of the process.

 - OS: Windows 10
 - GPU: AMD FirePro D500 (FireGL V)
 - Backend: OpenGL

**Comment by romainguy** [comment]
I can't repro your issue. I just tested with the same env map (from `assets/environments/debug`) and it looks correct (blue light coming from above, green from below).

How did you use `cmgen`? Here are the commands I used:

```
./out/cmake-release/tools/cmgen/cmgen -x ~/Desktop/ assets/environments/debug/debug.png
```

and

```
./out/cmake-release/samples/material_sandbox -i ~/Desktop/debug/ assets/models/sphere/sphere.obj
```

Result:

<img width="1136" alt="Screen Shot 2020-02-06 at 11 11 21 AM" src="https://user-images.githubusercontent.com/869684/73970092-6b131980-48d1-11ea-9652-bf610ebad45e.png">

**Comment by romainguy** [comment]
BTW you don't have to use SH anymore with Filament 1.4.5. If you don't specify SH Filament will pull diffuse lighting from the 16x16 mip level instead. It is useful with extremely high dynamic range IBLs (30 stops for instance) as it better encodes strong directional lighting but the result may not always be as good as with SH on untextured, high roughness objects like a white sphere.

**Comment by BStringhamVRSK** [comment]
Our command line is this:
`cmgen.exe --sh=bands --sh-output=SHOUT.txt debug.png`

Maybe I shouldn't be using --sh=bands?

**Comment by romainguy** [comment]
Ah no it's because FIlament expects its SH to be pre-optimized by folding as many constant computations as possible in them. Use `--sh-shader` when invoking `cmgen` (implied by `-x`). A good way to test if you are using the right flags is to test with `assets/environments/white_furnace`. If you use the right flags the SH should be similar to these:

```
( 1.000000000000000,  1.000000000000000,  1.000000000000000); // L00, irradiance, pre-scaled base
(-0.000000029081750, -0.000000029081750, -0.000000029081750); // L1-1, irradiance, pre-scaled base
( 0.000000000000000,  0.000000000000000,  0.000000000000000); // L10, irradiance, pre-scaled base
(-0.000000060320701, -0.000000060320701, -0.000000060320701); // L11, irradiance, pre-scaled base
( 0.000000000000000,  0.000000000000000,  0.000000000000000); // L2-2, irradiance, pre-scaled base
(-0.000000149214443, -0.000000149214443, -0.000000149214443); // L2-1, irradiance, pre-scaled base
( 0.000001189041427,  0.000001189041427,  0.000001189041427); // L20, irradiance, pre-scaled base
( 0.000000000274918,  0.000000000274918,  0.000000000274918); // L21, irradiance, pre-scaled base
( 0.000000683613393,  0.000000683613393,  0.000000683613393); // L22, irradiance, pre-scaled base
```

The first band is set to 1, all the other bands to 0. If you are not using the right flags, the first band will be set to something around 3.5.

```./out/cmake-release/tools/cmgen/cmgen --sh-shader --sh=3 assets/environments/white_furnace/white_furnace.exr```

**Comment by BStringhamVRSK** [comment]
Ok.  Good to know!  I will test this out soon and let you know.  We are in the middle of a test cycle, so it might be a couple of days before I can get back to it.
Thanks for the heads-up on using SH vs 16x16 mips, too.
