### ISSUE TITLE
How to extend shader in real time？

### ISSUE THREAD

**Issue by 2080717101** [google/filament#2112]
Hello, I am curious about the shadingModel in sandboxLit.mat. How does LitModel (lit, unlit, subsurface, cloth, specularGlossiness) make use of main.fs and main.vs ? I've noticed that matc-tool could transfer .mat to .fiamat, which .fiamat could be identified by the engine. 
    So, if I want to change .fs a little, what do I need to do to see the new results? Can you give me any ideas? 
    Thank you very much.

**Comment by romainguy** [comment]
If you change those files you need to rebuilt libfilamat and matc (and maybe libfilament). They are not meant to be modified at runtime. If you want to generate materials at runtime use libfilamat. What do you need to change?

**Comment by 2080717101** [comment]
Thanks again.
Actually, I want to output the directlight diffuse/specular, indirectlight diffuse/specular（ibl specular） separately, by changing the return functions (like surfaceShading) in shader.

**Comment by romainguy** [comment]
Yeah then you'll have to recompile all the libraries mentioned above and recompile your filamat files from mat files.

**Comment by 2080717101** [comment]
Thanks again.
I'll try.

**Comment by 2080717101** [comment]
Hello, I want to know what the light_iblDFG texture looks like in the PrefilteredDFG_LUT function? I noticed that it was generated by the engine in realtime from the file filament\generated\data\dfg.inc.
I've tried to use SystemLUT_IBR_Shader to generate this map in Unity. The specific algorithm is as follows.
RG channel is written by this 
```
half2 IBL_Defualt_SpecularIntegrated(half Roughness, half NoV) {
    half3 V;
    V.x = sqrt(1 - NoV * NoV);
    V.y = 0;
    V.z = NoV;
    half2 r = 0;
    const uint NumSamples = 64;
    for (uint i = 0; i < NumSamples; i++) {
        half2 E = Hammersley(i, NumSamples, HaltonSequence(i)); 
        half4 H = ImportanceSampleGGX(E, Roughness);
        half3 L = 2 * dot(V, H) * H.xyz - V;

        half VoH = saturate(dot(V, H.xyz));
        half NoL = saturate(L.z);
        half NoH = saturate(H.z);

        if (NoL > 0) {
            half G = IBL_PBR_Specular_G(NoL, NoV, Roughness);
            half Gv = G * VoH / NoH;
            half Fc = pow(1 - VoH, 5);
            //r.x += Gv * (1 - Fc);
            r.x += Gv * Fc;
            r.y += Gv;
        }
    }
    return r / NumSamples;
}
```
B channel is written by this 
```
half IBL_Defualt_DiffuseIntegrated(half Roughness, half NoV) {
    half3 V;
    V.x = sqrt(1 - NoV * NoV);
    V.y = 0;
    V.z = NoV;

    half r = 0; 
	const uint NumSamples = 2048;

    for (uint i = 0; i < NumSamples; i++) {
        half2 E = Hammersley( i, NumSamples, HaltonSequence(i) ); 
        half4 H = CosineSampleHemisphere(E);
        half3 L = 2 * dot(V, H.xyz) * H.xyz - V;

        half NoL = saturate(L.b);
        half LoH = saturate( dot(L, H.xyz) );
        
        if (NoL > 0) {
            half Diffuse = IBL_PBR_Diffuse(LoH, NoL, NoV, Roughness);
            r += Diffuse;
        }
    }
    return r / NumSamples;
}
```
The result look like that
![image](https://user-images.githubusercontent.com/18326271/74410675-97e8a300-4e74-11ea-969b-68452040fe99.png)
![image](https://user-images.githubusercontent.com/18326271/74410678-99b26680-4e74-11ea-979f-a391b5c7f3e7.png)
![image](https://user-images.githubusercontent.com/18326271/74410651-8bfce100-4e74-11ea-97ea-74322f7d6ff0.png)
![image](https://user-images.githubusercontent.com/18326271/74410630-830c0f80-4e74-11ea-8381-f85fbd1c8a2a.png)

But when I use this LUT, result looks strenge.Do I miss anything? Thank you very much.

**Comment by romainguy** [comment]
I don’t understand what you are trying to do. Are you trying to use unity’s LUT in Filament? We generate our LUT with our custom tool called cmgen.

**Comment by 2080717101** [comment]
Thanks for reply.
I want to use this filament's LUT in my unity project, but I don't know how to generate it.

**Comment by romainguy** [comment]
Use the cmgen tool that’s in Filament’s tree. Use —help to see which option to use to generate the DFG LUT. Unity probably already has its own DFG LUT though so I’m not sure how useful that is.

**Comment by 2080717101** [comment]
Thanks again. I’ll try.
