### ISSUE TITLE
Jagged Shadows: advice on shadows for large scene?

### ISSUE THREAD

**Issue by roxlu** [google/filament#2113]
I've got a scene that I created in Blender. The scene fits inside a box a box of about 1500m in Blender Units. When I render this scene with Filament the shadows  are jagged.  I've seen the `ShadowOptions` in `LightManager.h` but I'm not sure what properties will be good for a scene like this. Any advice on what properties I might want to try?

![image](https://user-images.githubusercontent.com/358809/74172608-d3932b00-4c30-11ea-8b06-1645e13d6383.png)

![image](https://user-images.githubusercontent.com/358809/74172635-df7eed00-4c30-11ea-8199-7eebbb429ff4.png)

![image](https://user-images.githubusercontent.com/358809/74171919-a2662b00-4c2f-11ea-9a78-6f1705735649.png)

The ShadowOptions:

```c++
     */
    struct ShadowOptions {
        /** Size of the shadow map in texels. Must be a power-of-two. */
        uint32_t mapSize = 1024;

        /** Constant bias in world units (e.g. meters) by which shadows are moved away from the
         * light. 1mm by default.
         */
        float constantBias = 0.001f;

        /** Amount by which the maximum sampling error is scaled. The resulting value is used
         * to move the shadow away from the fragment normal. Should be 1.0.
         */
        float normalBias = 1.0f;

        /** Distance from the camera after which shadows are clipped. this is used to clip
         * shadows that are too far and wouldn't contribute to the scene much, improving
         * performance and quality. This value is always positive.
         * Use 0.0f to use the camera far distance.
         */
        float shadowFar = 0.0f;

        /** Optimize the quality of shadows from this distance from the camera. Shadows will
         * be rendered in front of this distance, but the quality may not be optimal.
         * This value is always positive. Use 0.0f to use the camera near distance.
         * The default of 1m works well with many scenes. The quality of shadows may drop
         * rapidly when this value decreases.
         */
        float shadowNearHint = 1.0f;

        /** Optimize the quality of shadows in front of this distance from the camera. Shadows
         * will be rendered behind this distance, but the quality may not be optimal.
         * This value is always positive. Use std::numerical_limits<float>::infinity() to
         * use the camera far distance.
         */
        float shadowFarHint = 100.0f;

        /**
         * Controls whether the shadow map should be optimized for resolution or stability.
         * When set to true, all resolution enhancing features that can affect stability are
         * disabling, resulting in significantly lower resolution shadows, albeit stable ones.
         */
        bool stable = false;

        /**
         * Constant bias in depth-resolution units by which shadows are moved away from the
         * light. The default value of 0.5 is used to round depth values up.
         * Generally this value shouldn't be changed or at least be small and positive.
         */
        float polygonOffsetConstant = 0.5f;

        /**
         * Bias based on the change in depth in depth-resolution units by which shadows are moved
         * away from the light. The default value of 2.0 works well with SHADOW_SAMPLING_PCF_LOW.
         * Generally this value is between 0.5 and the size in texel of the PCF filter.
         * Setting this value correctly is essential for LISPSM shadow-maps.
         */
        float polygonOffsetSlope = 2.0f;
    };

```

**Comment by romainguy** [comment]
Increase the shadow map resolution and reduce the `shadowFarHint`. The real solution will be when we implement cascaded shadow maps.

**Comment by roxlu** [comment]
Thanks @romainguy. I did a couple of tests but none of the changes seem to have any effect. I know that the bounding boxes have an influence on this, so I verified my bounding boxes with the `RenderableManager::computeAABB()` and they are the same.  I tested with a sunlight with an intensity of 8, 10, 18,  pure white color and a direction of (0.10, -0.80, 0.40).   

Are there other relevant settings/configs I might need to change?

```c++
shadow_cfg.shadowFar = 1000.0;
shadow_cfg.shadowFarHint = 20.0f;
shadow_cfg.mapSize = 4096;
```
![image](https://user-images.githubusercontent.com/358809/74180371-ab5ef880-4c3f-11ea-8b1d-99e58bc64712.png)

```c++
/*shadow_cfg.shadowFar = 1000.0;*/
shadow_cfg.shadowFarHint = 20.0f;
shadow_cfg.mapSize = 4096;
```

![image](https://user-images.githubusercontent.com/358809/74180475-df3a1e00-4c3f-11ea-8fa5-f89d08e28bb0.png)

```c++
shadow_cfg.shadowFarHint = 40.0f;
shadow_cfg.mapSize = 4096;
```
![image](https://user-images.githubusercontent.com/358809/74180545-08f34500-4c40-11ea-81aa-0df9e9f28865.png)

```c++
shadow_cfg.shadowFarHint = 60.0f;
shadow_cfg.mapSize = 4096;
```

![image](https://user-images.githubusercontent.com/358809/74180632-2b855e00-4c40-11ea-884d-34775099d415.png)

```c++
shadow_cfg.shadowFarHint = 80.0f;
shadow_cfg.mapSize = 4096;
```
![image](https://user-images.githubusercontent.com/358809/74180726-4e177700-4c40-11ea-8c50-df604c71e753.png)

**Comment by romainguy** [comment]
Sorry I meant you want a shadowFar and a shadowFarHint that are closer to the camera. Otherwise just make sure your bounding boxes are as tight as possible.
