### ISSUE TITLE
No implementation found for long Manipulator.nCreateBuilder()

### ISSUE THREAD

**Issue by Yud07** [google/filament#2127]
I created a modified version of the ModelViewer class from the utils and removed the glb components. The app builds just fine but it errors at runtime when attempting to instantiate the camera manipulator with error: 

java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.filament.utils.Manipulator.nCreateBuilder() (tried Java_com_google_android_filament_utils_Manipulator_nCreateBuilder and Java_com_google_android_filament_utils_Manipulator_nCreateBuilder__)

dependencies {
    ...
    implementation 'com.google.android.filament:filament-android:1.4.5'
    implementation 'com.google.android.filament:filamat-android-full:1.4.5'
    implementation 'com.google.android.filament:filament-utils-android:1.4.5'
}

...
import com.google.android.filament.utils.Manipulator
...
class ModelViewer {
    ...
    private val cameraManipulator: Manipulator
   ...
    constructor(surfaceView: SurfaceView) {
        cameraManipulator = Manipulator.Builder()
                .targetPosition(0.0f, 0.0f, -4.0f)
                .viewport(surfaceView.width, surfaceView.height)
                .build(Manipulator.Mode.ORBIT)

        gestureDetector = GestureDetector(surfaceView, cameraManipulator)
        uiHelper.renderCallback = SurfaceCallback()
        uiHelper.attachTo(surfaceView)
        addDetachListener(surfaceView)
    }
    ...
}

 - OS: Windows
 - Backend: Android Studio 3.6

 - Device: Samsung Galaxy S9
 - OS: Android Pie 9.0

**Comment by prideout** [comment]
Are you calling `Utils.init()`?

**Comment by Yud07** [comment]
That solved it, thanks! I mistakenly thought Filament.init() would've invoked Utils.init() rather than the other way around.

**Comment by djhuertasg** [comment]
I have a question, why do you create a ExampleApplication class for the Utils.init?
You can add: companion object { init { Utils.init() }  } to the ArActivity class and it runs ok
Thank you in advance
