### ISSUE TITLE
Compilation failure of filament Android library on macOS

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2130]
I'm getting the following build fail ([full text](https://github.com/google/filament/files/4198613/build-fail.txt)):

```
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/rupert/GitHub/LearnHub/filament/android/samples/sample-gltf-bloom/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':samples:sample-gltf-bloom'.
> Failed to apply plugin [class 'FilamentToolsPlugin']
   > No such property: filament_tools_dir for class: FilamentToolsPlugin
```
In case it's relevant, I normally do a clean compile from the command line using the following command:

`git clean -fdx; ./build.sh -p desktop -i release; ./build.sh -p android -i release
`

I narrowed down the change where it started to [this commit](https://github.com/google/filament/commit/d9ee2fa10d712effa9d75910460504003ea39f77).

I'm running on macOS Version 10.15.2.

**Comment by romainguy** [comment]
Make sure you have Android Studio 3.6 and do a clean build first (build.sh -c).

**Comment by rawnsley** [comment]
I still get the same problem. I've installed Android Studio 3.6 RC 3, checked for updates, rebooted my Mac, cleaned the build, and run a git clean for good measure.

Am I missing some other update? I'll confess I'm not exactly sure where all the build tools live.

**Comment by romainguy** [comment]
The only place where we check this property is properly guarded:

```
        if (project.hasProperty("filament_tools_dir")) {
            project.ext.filamentToolsPath = project.file("$filament_tools_dir")
        }
```

Your build logs also mention a missing `compileSdkVersion` but it is present in the gradle file.

What version of Filament are you trying to build? Would you mind trying a brand new checkout?

**Comment by rawnsley** [comment]
A brand new checkout on the master branch has the same problem. I can see the property check as well and no other references except in a tungsten folder, but that's an assignment.

**Comment by romainguy** [comment]
One last thing to try: rm -rf ~/.gradle

**Comment by rawnsley** [comment]
OK that fixed it! That also explains why I saw some hysteresis going back-and-forth looking for the check-in that "broke" the build.

Thank you for your help.

**Comment by rawnsley** [comment]
This problem has cropped up again in a slightly different context and I seem to have made it go away by changing the accessor slightly. I replaced...

```
        if (project.hasProperty("filament_tools_dir")) {
            project.ext.filamentToolsPath = project.file("$filament_tools_dir")
        }
```
...with...

```
        if (project.hasProperty("filament_tools_dir")) {
            project.ext.filamentToolsPath = project.file(project.property("filament_tools_dir"))
        }
```
Matching _project.hasProperty_ with _project.property_ rather than relying on the $ property lookup syntax.

**Comment by romainguy** [comment]
Thanks, that's a great catch. I must have introduced that regression during the move to a Gradle plugin.
