### ISSUE TITLE
Add iOS simulator to releases

### ISSUE THREAD

**Issue by an-kumar** [google/filament#2144]
It would be great to add the simulator build to the releases. Currently it’s the only platform not provided (as far as I can tell), and it’s very useful — would be great to not have to build filament at all and just use the provided releases, but the simulator build is too valuable to give up.

Are there any issues with this I’m not seeing?

**Comment by bejado** [comment]
The only downside is that it increases the build time for releases, but I think this is a reasonable tradeoff. Note that at the moment, only the OpenGL backend has been tested with the iOS simulator.

**Comment by an-kumar** [comment]
Yeah, that’s fine, it’s still very useful for development.
