### ISSUE TITLE
macOS build of v1.4.5 unable to exit cleanly when in OpenGL mode

### ISSUE THREAD

**Issue by yongtang** [google/filament#2159]
**Describe the bug**

I was playing with Filament on macOS, and noticed that with OpenGL mode, the program could not exit cleanly (hangs). If I switch to Metal mode the program exited fine. See next sections for details.

Since Metal works fine, this issue may not be as high. Though ideally it would be good to see OpenGL works as well. Or maybe I am missing some of the steps in OpenGL mode?

**To Reproduce**
1. A sample code is located on https://github.com/yongtang/demo
2. Install Bazel 2.0 on macOS:
   ```sh
   curl -OL https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-installer-darwin-x86_64.sh
   sudo bash -x -e bazel-2.0.0-installer-darwin-x86_64.sh
   ```
3. Build with the following command:
   ```
   bazel build -s --verbose_failures //...
   ```
4. Run binary with the following, and notice the program will not exit:
   ```
   % bazel-bin/demo                         
   Filament library loaded.
   FEngine (64 bits) created at 0x102880000 (threading is enabled)
   FEngine resolved backend: OpenGL
   Hello, world!
   ^C
   % 
   ```

5. Open demo.cc, and change to Metal mode by the following:
   ```
   filament::Engine* pEngine = filament::Engine::create(filament::backend::Backend::METAL);
   ```
6. Build with bazel again:
   ```
   bazel build -s --verbose_failures //...
   ```
7. Run binary again and notice the program exit fine:
   ```
   % bazel-bin/demo
   Filament library loaded.
   FEngine (64 bits) created at 0x10a1ae000 (threading is enabled)
   FEngine resolved backend: Metal
   Hello, world!
   %
   ```

**Expected behavior**

Ideally in OpenGL mode, the program could exit cleanly.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GPU: Intel UHD Graphics 630 1536 MB
 - Backend: OpenGL (note Metal works fine)

**Comment by romainguy** [comment]
I can repro. @pixelflinger, just add a new sample containing the code at https://github.com/yongtang/demo/blob/master/demo.cc. After running it, the sample is stuck in:

`filament::PlatformCocoaGL::makeCurrent(filament::backend::Platform::SwapChain*, filament::backend::Platform::SwapChain*)`

**Comment by romainguy** [comment]
@yongtang Note that Filament will exit cleanly if you render into a visible window. The bug only happens in your specific case (we run OpenGL tests on macOS daily).

**Comment by pixelflinger** [comment]
Yeah, I think this one will be tricky -- this is because of the hack we had to do on macos where we send a message to the main thread. In the case of tests, the main thread never runs.

**Comment by yongtang** [comment]
Thanks @pixelflinger @romainguy for the fix ! I dowloaded the artifact from the build in #2173 and now the program works as expected. 👍
