### ISSUE TITLE
Android fails to load library on older devices

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2176]
When initializing the library on an Android 22 device I get an error like this:

```
Java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "llibfilament-jni.so" (built with --hash-style=gnu?)
   at java.lang.Runtime.loadLibrary(Runtime.java:365)
   at java.lang.System.loadLibrary(System.java:526)
...
```

Following [this suggestion](https://stackoverflow.com/a/59649817/671393) I tried compiling with targetSdk = 22 and the problem went away. It would appear that _hash-style=both_ should to be added to the compiler options if we want to maintain backwards compatibility.

**Comment by romainguy** [comment]
Lowering the target SDK is not an option for us, however `-Wl,--hash-style=both` (or `sysv`) is an acceptable solution.

**Comment by romainguy** [comment]
Let me know if this doesn't fix the problem

**Comment by rawnsley** [comment]
The good news is that it fixes the problem (although the linker throws some warnings about unused parameters). The bad news is that compiling for API 23+ brings back [this other runtime link error](https://github.com/google/filament/issues/594).

The [official advice](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#available-in-api-level-23) suggests that you can avoid it by not using atfork or pthread_atfork, but they are not used directly in the main code base as far as I can see.

**Comment by romainguy** [comment]
Weird I’m not getting compilation warnings. Note that the targetSdk is set to 21 for the native code (via the -D flag). This hasn't changed.

**Comment by rawnsley** [comment]
I'm building from to command line on MacOS. Here's an example warning:

```
> Task :filament-android:externalNativeBuildRelease
Build filament-jni_armeabi-v7a
ninja: Entering directory `/Users/rupert/GitHub/LearnHub/filament/android/filament-android/.cxx/cmake/release/armeabi-v7a'
[1/27] Building CXX object CMakeFiles/filament-jni.dir/src/main/cpp/Filament.cpp.o
clang++: warning: -Wl,--hash-style=both: 'linker' input unused [-Wunused-command-line-argument]
[2/27] Building CXX object CMakeFiles/filament-jni-obj.dir/src/main/cpp/EntityManager.cpp.o
clang++: warning: -Wl,--hash-style=both: 'linker' input unused [-Wunused-command-line-argument]
[3/27] Building CXX object CMakeFiles/filament-jni-obj.dir/src/main/cpp/Colors.cpp.o
clang++: warning: -Wl,--hash-style=both: 'linker' input unused [-Wunused-command-line-argument]
```
Regarding the targetSdk: where is it set to 21? In android/build.gradle buildscript.ext.versions sets the variable targetSdk to 29 and then it appears to be used everywhere, i.e. for targetSdkVersion and -DANDROID_PLATFORM.

**Comment by romainguy** [comment]
Ah, if it's used for `-DANDROID_PLATFORM` it's a mistake, it should be 21 there. I'll fix it. You shouldn't get these warnings since I added `-Wno-unused-command-line-argument` (precisely to suppress those).

**Comment by romainguy** [comment]
Alright I checked in a fix, let me know if that fixes the issue.

**Comment by rawnsley** [comment]
I expect this will fix it, but I'm getting an unrelated compilation error on the master branch at the moment:

../../../../src/main/cpp/SurfaceOrientation.cpp:153: error: undefined reference to 'filament::geometry::SurfaceOrientation::getQuats(filament::math::details::TQuaternion<filament::math::half>*, unsigned int, unsigned int) const'

Possibly the one you are trying to [fix here](https://github.com/google/filament/commit/81e7f619eb6dfcbe226813cd5de939e1f33d3dfd). This fix doesn't work for me, but I notice the GitHub build test passes now so it might be something on my side still.

**Comment by romainguy** [comment]
That error still makes no sense to me. Changing the API level has nothing to do with this. My fix was simply to use a newer NDK. I wasn't able to reproduce the compilation failure on my machine and the only difference was I am using NDK 21.

**Comment by rawnsley** [comment]
I think the compilation error came somewhere between tag 1.4.5 and this change. I'll try and narrow it down and figure out what's going wrong.

**Comment by rawnsley** [comment]
False alarm! I has not noticed that my NDK was out of date. Updating from 20.0.5594570 to 21.0.6113669 made the compilation problem go away. Apologies for the confusion.

I can confirm that the library now loads properly at runtime.
