### ISSUE TITLE
Material compiler exception when using Optimization::NONE on Android

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2184]
Turning off optimization in the material compiler throws exceptions during the GLSL compilation at runtime. For example:

```
E/Filament: COMPILE ERROR: 
    0:1134: L0001: Unknown character '"'(34)
    0:1134: L0001: Unknown character '"'(34)
    1:   #version 300 es
    2:   
    ...
```
I triggered this error by including the _-g_ parameter on the command line for _matc_ in the MaterialCompiler build task and running the lit-cube sample on Android.

It's not a real problem in this example, but compiling with optimization is not an option when using the lite version of filamat.

**Comment by romainguy** [comment]
I cannot reproduce either by running `matc` manually or by changing the samples to use `-g` when compiling the materials. Looks like the bug might be in the device's shader compiler itself?

**Comment by bejado** [comment]
The only place we use `"` inside shaders is within comments. I'm wondering if somehow a comment isn't getting stripped properly, or a specific OGL driver is getting tripped up.

**Comment by romainguy** [comment]
Looking at this:
`0:1134: L0001:`

It could be that the shader is sent to the driver on a single line?

**Comment by bejado** [comment]
Actually, inside `light_indirect.fs` we do use quotes outside of a comment:

```
#error "invalid REFRACTION_TYPE"
```

I'd bet its a finicky driver complaining about the use of quotes there.

**Comment by romainguy** [comment]
I suggest we ditch this then. Just remove the #else and the #error. It doesn't give us much anyway.

**Comment by rawnsley** [comment]
I can confirm it's only failing on the Mali-T and compiles fine on an Adreno device. I've attached the filamat and the extracted GLSL that's failing at line 1141. As @bejado suspected it seems to be the quotes in the error message.

[Archive.zip](https://github.com/google/filament/files/4268379/Archive.zip)
