### ISSUE TITLE
memory error when using opengl on win10 x64 with msvc 2019

### ISSUE THREAD

**Issue by BillyUSA** [google/filament#2190]
![error callstack](https://user-images.githubusercontent.com/11308319/75683236-bacae200-5cd1-11ea-97f1-dcd6bb500ed1.png)

**Comment by romainguy** [comment]
Does this happen by just running the point sprites sample app or do you do something else?

**Comment by BillyUSA** [comment]
just running the point sprites sample app, crash point is random. other app such as material_sandbox also happen this error. 
Git clone source , cmake gen solution ,then build ,run ,error happen.

**Comment by crazycoderx2** [comment]
The one error is here:
https://github.com/google/filament/blob/73e0facaeddf8f079b3f7f5dff5fb8173b46577d/samples/gltf_viewer.cpp#L317
Using c_str() for temporary object.
But it's not the only one.

**Comment by romainguy** [comment]
Good catch! @prideout

**Comment by prideout** [comment]
As per the ResourceLoader documentation, the string pointer not retained, instead its contents are immediately copied.

We should probably do some ASAN testing, I haven't done that it in a while.

**Comment by crazycoderx2** [comment]
I've got gtlf_viewer working by reverting:
9358c7313e7db106d8c073923e27235e75a38c55
651ccb183edd671032e9991f91fab128502e14b6
079056cfbc0033ca86bf1948cfc907ad25b6764b

**Comment by prideout** [comment]
I see some ASAN failures with macOS, let me fix those up, maybe it will fix your issue.

**Comment by prideout** [comment]
Aside from the usual issues we see in glslang, the only ASAN failure that I see is due to the transient string lifetime issue that you found.  I'll go ahead and fix that (my fault).

**Comment by bejado** [comment]
I can confirm that 651ccb18 appears to introduce the issue. The commit before works just fine, but anything including and after 651ccb18 has the memory crash, though I can't imagine why. We suspect it might be a red herring.

**Comment by bejado** [comment]
I added the following assert to IndirectLight.h. Note that `FIndirectLight` contains a `math::mat3f mRotation` member variable.

```
// Should not fail.
static_assert(sizeof(math::mat3f) == 4 * 3 * 3);
```

On certain files this fails, but succeeds on others:

```
View.cpp: fails
IndirectLight.cpp: fails
Engine.cpp: succeeds
Skybox.cpp: succeeds
```

My working hypothesis is that this has to do with the include order between `mathfwd.h` and *actual* math includes, like `<math/mat4.h>`. If `mathfwd.h` comes before an actual math header, then MSVC is not able to correctly deduce the size of `mat3`. This fails silently, but leads to memory corruption issues in ctors / dtors of classes with math member variables.

**Comment by romainguy** [comment]
We've had similar issues with msvc before.
