### ISSUE TITLE
Filament crash when using Motorola Moto G7 Play

### ISSUE THREAD

**Issue by sqaaa** [google/filament#2197]
Hello everybody! We're using sceneform for rendering 3d objects in our android app. So we have a native filament crash right after render started to work and few seconds passed.

**To Reproduce**
Just start app with rendering with sceneform

**Expected behavior**
No crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/11176780/75749891-f1394900-5d33-11ea-9fae-bf579c573d6a.png)

**Desktop (please complete the following information):**
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
sceneform version is 1.13.0

**Smartphone (please complete the following information):**
 - Motorola Moto G7 Play
 - OS: [e.g. Android Pie 9.0]

**Additional context**
I know that bug reproduced on some other devices like nexus 5x.

**Comment by romainguy** [comment]
Thanks for the report. Does this reproduce with *any* Sceneform app? The fact that it's raising a `SIGILL` is a  little scary.

**Comment by romainguy** [comment]
@pixelflinger Do you think it could be caused by Sceneform not using the same compiler flags we use? I  know we carefully picked which architectures/CPU types to compile against.

**Comment by sqaaa** [comment]
> Thanks for the report. Does this reproduce with _any_ Sceneform app? The fact that it's raising a `SIGILL` is a little scary.

It's difficult to say. I don't know which app using sceneform under the hood but I can check it thought google examples for sure. (I will ckeck this out)
But it can be useless because we're using pretty difficult models which may contains several parts connected to each other

Little update, now I have instant crash right after app starting to work, no delay for render a bit like before. 
Here stack trace
![image](https://user-images.githubusercontent.com/11176780/75754309-90167300-5d3d-11ea-99d4-ada2c16b814c.png)

**Comment by sqaaa** [comment]
I checked out sample with solar system by google `sceneform + ar.`
So I have same crash after a while
![image](https://user-images.githubusercontent.com/11176780/75755344-7d04a280-5d3f-11ea-9a3d-7abcd7496d75.png)

**Comment by pixelflinger** [comment]
I see the app is running in 32-bit mode, is that expected? Are you able to try in 64-bit mode?

@romainguy We're targeting the cortex-a15 and the G7 Play is using a cortex-a53, so we should be good here.

**Comment by sqaaa** [comment]
> I see the app is running in 32-bit mode, is that expected? Are you able to try in 64-bit mode?

How do I do this? Btw I just run app through android studio "run" without any specific flags

**Comment by chiel99** [comment]
Hi @sqaaa,
I found a similar issue on filament 1.8.1 and all the bug reports are from Motorola Moto G7 Play devices.
May I know the SIGILL issue is solved in your app or not?
Thanks.
