### ISSUE TITLE
Protocol buffers

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2211]
**Is your feature request related to a problem? Please describe.**
We need schema for our messaging within filament within webgl.

**Describe the solution you'd like**
Protocol Buffers.

**Describe alternatives you've considered**
none

**OS and backend**
In this case, it is a front-end concern.

Please forgive me if this is off-topic, but I am struggling to make protocol buffers work w/ emscripten.  Would be grateful if I could get some help.

**Comment by prideout** [comment]
What does "messaging within filament within webgl mean"?

**Comment by unicomp21** [comment]
When using websockets from an html5 single page app, compiled w/ emscripten, we need to be able to use protocol buffers for messages on the websocket.

**Comment by unicomp21** [comment]
How are most devs handling their messages now when using filament on webgl?

**Comment by prideout** [comment]
Filament's WebGL 2.0 backend can be used in any of the following ways:

1. You can use Filament's JavaScript API.
2. You can use Filament's TypeScript API.
3. You can use Filament's C++ API by building your own wasm module.

Our sample apps and tutorials use (1).  The `google/model-viewer` project uses (2).

Sounds like you need some sort of client-server communication protocol that is outside the scope of our project, which is meant to be a renderer only.

**Comment by unicomp21** [comment]
Within C++ for html5/emscripten/webgl, it would be really nice if we could use Google Protocol Buffers cc: @romainguy

**Comment by romainguy** [comment]
I don't see why you can't? Additionally this is completely unrelated to Filament and our team has no experience/expertise with Protobufs. We can't really help you here unfortunately.

**Comment by prideout** [comment]
Are you writing an Electron app?  If so, your filament API calls would live in the Renderer process,  not in the Main process.  I would imagine sending high-level JSON messages over Electron's built-in ipc mechanism, rather than trying to marshal the entire Filament API.
