### ISSUE TITLE
Linking to sample app suzanne

### ISSUE THREAD

**Issue by byjinglemen** [google/filament#2213]
I am attempting to run the sample app suzanne by linking to the precompiled libraries. When the sample apps are compiled by compiling the whole source code, everything works fine, however when I attempt to instead link to the precompiled libraries, I get the following error:

```[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/joel/Documents/KiwiTest/filament-suzanne/out/cmake-debug
[1/347] Compiling material materials/sandboxLitThinRefractionSsr.mat to /home/joel/Documents/KiwiTest/filament-suzanne/out/cmake-debug/generated/material/sandboxLitThinRefractionSsr.filamat
FAILED: generated/material/sandboxLitThinRefractionSsr.filamat 
cd /home/joel/Documents/KiwiTest/filament-suzanne/out/cmake-debug && /home/joel/Documents/KiwiTest/filament-suzanne/bin/matc -o /home/joel/Documents/KiwiTest/filament-suzanne/out/cmake-debug/generated/material/sandboxLitThinRefractionSsr.filamat /home/joel/Documents/KiwiTest/filament-suzanne/materials/sandboxLitThinRefractionSsr.mat
ERROR: 0:1198: '*' :  wrong operand types: no operation '*' exists that takes a left-hand operand of type 'layout( column_major std140 offset=256) uniform highp 4X4 matrix of float' and a right operand of type ' global mediump 3-component vector of float' (or there is no acceptable conversion)
ERROR: 0:1198: '' : missing #endif 
ERROR: 0:1198: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.


ERROR: Unable to parse fragment shader:
ERROR: 0:69: 'absorption' : no such field in structure 
ERROR: 0:69: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

Could not compile material /home/joel/Documents/KiwiTest/filament-suzanne/materials/sandboxLitThinRefractionSsr.mat```

**Comment by romainguy** [comment]
This error has nothing to do with linking. It looks like you are using a different `matc`? Which version of `matc` are you compiling with? Did you modify the materials?

**Comment by byjinglemen** [comment]
Thank you, yes I was using a slightly different version of `matc`.

If I want to take one of sample apps (for example, suzanne), and decouple it so I can compile it without having to recompile the entire source code, how would I do that? I have been really struggling to achieve this...

Thanks

**Comment by romainguy** [comment]
You should be able to download one of the binary releases from the GitHub page and compile/link against the static libraries that are part of the binary release. The sample apps rely on SDL2 so you'll need to link against that as well. That said you'll also have to choose versions of the samples that match whatever release you downloaded: we often update the samples as we add new APIs, etc. so they may not compile with older versions of Filament.
