### ISSUE TITLE
TransformManager Instance error after destroy one  

### ISSUE THREAD

**Issue by BillyUSA** [google/filament#2216]
after detroy one TransformManager instance for an entity, if create new one TransformManager Instance for new one entity, the TransformManager Instance got  is the exist one for other entity

![1](https://user-images.githubusercontent.com/11308319/76043770-766e6900-5f93-11ea-9a43-21dae0e23dd3.png)
![2](https://user-images.githubusercontent.com/11308319/76043775-7a01f000-5f93-11ea-82ac-308aea75fb48.png)

**Comment by romainguy** [comment]
Could you please show your code? Note that instances are only *temporary handles*. You must query the instance every time.

**Comment by BillyUSA** [comment]
like this:
Entity = CreateEntity();
TransInst=getTransformManager::create(Entity);   //for later use
after replace TransInst by  getTransformManager::getInstance(Entity) ,no assertion happened
