### ISSUE TITLE
Using the build script to make a debug build fails in making an ASM object for shaders.

### ISSUE THREAD

**Issue by AlexanderPattison** [google/filament#2228]
**Describe the bug**
Using the build script to make a debug build fails in making an ASM object for shaders.

**To Reproduce**
./build.sh -c debug

**Bash Info**
ubuntu@ubuntu:~/Documents/GitHub Projects/googlefilament/filament$ ./build.sh -c debug
Warning: JAVA_HOME is not set, skipping Java projects
Cleaning build directories...
Building debug in out/cmake-debug...
-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Embree not found, pipeline features are disabled.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/cc
-- DFG LUT size set to 128x128
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug
[776/1124] Linking C shared library third_party/libsdl2/tnt/libsdl2.so
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
[829/1124] Generating matdbg_resources.bin, matdbg_resources.S, matdbg_resources.apple.S, matdbg_resources.h
Generated files: /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/libs/matdbg/matdbg_resources.h /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/libs/matdbg/matdbg_resources.S /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/libs/matdbg/matdbg_resources.apple.S /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/libs/matdbg/matdbg_resources.bin
[830/1124] Aggregating shaders
Generated files: /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/shaders/generated/shaders.h /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/shaders/generated/shaders.S /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/shaders/generated/shaders.apple.S /home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/shaders/generated/shaders.bin
[832/1124] Building ASM object shaders/CMakeFiles/shaders.dir/generated/shaders.S.o
FAILED: shaders/CMakeFiles/shaders.dir/generated/shaders.S.o 
/usr/bin/cc -DFILAMENT_DRIVER_SUPPORTS_VULKAN -Ishaders -g   -I/home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/shaders/generated -MD -MT shaders/CMakeFiles/shaders.dir/generated/shaders.S.o -MF shaders/CMakeFiles/shaders.dir/generated/shaders.S.o.d -o shaders/CMakeFiles/shaders.dir/generated/shaders.S.o -c shaders/generated/shaders.S
clang: error: no such file or directory: 'Projects/googlefilament/filament/out/cmake-debug/shaders/generated'
[837/1124] Generating generated/texture/ao.ktx
Reading image...
Generating miplevels...
Writing KTX file to disk...
[838/1124] Generating generated/texture/roughness.ktx
Reading image...
Generating miplevels...
Writing KTX file to disk...
[839/1124] Generating generated/texture/metallic.ktx
Reading image...
Generating miplevels...
Writing KTX file to disk...
[840/1124] Generating generated/texture/albedo_s3tc.ktx
Reading image...
Generating miplevels...
Writing KTX file to disk...
[841/1124] Generating venetian_crossroads_2k/venetian_crossroads_2k_skybox.ktx, venetian_crossroads_2k/venetian_crossroads_2k_ibl.ktx
ninja: build stopped: subcommand failed.

**Desktop**
ubuntu@ubuntu:/usr$ uname -a
Linux ubuntu 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
I am trying to make a debug build and try the app in the samples folder.

**Comment by romainguy** [comment]
Looks like spaces are not properly handled in a path: `clang: error: no such file or directory: 'Projects/googlefilament/filament/out/cmake-debug/shaders/generated'`

It should be `/home/ubuntu/Documents/GitHub Projects/googlefilament/filament/out/cmake-debug/shaders/generated`.

@AlexanderPattison As a workaround, build from a directory without spaces in its path.

@prideout Can you check if it's an issue on our side? It seems to be a CMake problem.

**Comment by AlexanderPattison** [comment]
Yes, the issue was a space in the path, on my side. Thanks, it is working.
