### ISSUE TITLE
Does support the multiple light?

### ISSUE THREAD

**Issue by Realitian** [google/filament#2229]
Filament does support the multiple light?
I tried to add 8 directional lights in the scene, but I could only last light had enabled.
How can I enable multiple light?

**Comment by romainguy** [comment]
Filament supports many point and spot lights, but only 1 directional light at a time.

**Comment by Realitian** [comment]
I tried to run the multiple point light sample, but it didn't work.
`lightbulb.exe -m ..\assets\models\monkey\monkey.obj`
It's hang when I added -m option.

**Comment by romainguy** [comment]
It's a known issue on Windows/64 bit, there's a fix pending that should be merged in the next few hours.

**Comment by RonMehta** [comment]
Hi, @romainguy is this issue fixed? can you point me to the fix?

**Comment by Debdutta-Panda** [comment]
Still no support for multiple directional light?
