### ISSUE TITLE
Crash when trying to load non-animated GLTF model

### ISSUE THREAD

**Issue by MarkMurillo** [google/filament#2241]
**Describe the bug**
Using the Android sample app "sample-gltf-viewer" I replaced the default model it was loading to one of the sample models from here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Avocado/glTF-Binary

**To Reproduce**
1. Download and insert [this model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Avocado/glTF-Binary) into the assets folder for the sample-gltf-viewer project.
2. In the MainActivity.kt in `createRenderables()` replace the asset that opens to the `Avocado.glb` and call `modelViewer.loadModelGlb(buffer)` instead of `loadModelGltf()`
3. Crash.

**Expected behavior**
Should display the model which has no animations.

**Screenshots**
I received a sigsegv on this [line](https://imgur.com/iDUL7tv), and lldb caught the null pointer access here in the gltfio-android library file [Animator.cpp](https://imgur.com/a6ZECQj)

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android 10.0

**Additional context**
Built the project on macOS 10.15.2

**Comment by romainguy** [comment]
Could you please show the entire logs you get from adb? We test against all the glTF samples on desktop and web and they load with no issues.

**Comment by MarkMurillo** [comment]
logcat for both [filtered and unfiltered](https://github.com/MarkMurillo/logfiles):

**Comment by MarkMurillo** [comment]
Actually I think it the FrameCallback in the sample is ignoring the Animator's animationCount and trying to call applyAnimation on index 0 even if there is no animations loaded.

It just needed to check `if (this.animationCount == 0)  return` before calling `applyAnimation()`. When I added this in, the model renders fine!

**Comment by romainguy** [comment]
You are right, it seems to be what another sample app does (`bloom`):

`if (filamentAsset.animator.animationCount > 0) {`

Looks like this sample was written with assumption that the animator would be null when no animation is present. I'll upload a fix, thanks for investigating.

**Comment by romainguy** [comment]
I just pushed a fix, thank you!
