### ISSUE TITLE
Undefined symbols（iOS Sample project hello-ar）

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#2246]
**Commint:** 3b52b89f
Undefined symbols for architecture arm64:
  "___asan_stack_free_8", referenced from:
      meshopt::decodeVertexBlockSimd(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned long, unsigned char*) in libmeshoptimizer.a(vertexcodec.cpp.o)
  "___asan_stack_malloc_9", referenced from:
      filament::details::Froxelizer::update() in libfilament.a(Froxelizer.cpp.o)
  "___asan_stack_free_9", referenced from:
      filament::details::Froxelizer::update() in libfilament.a(Froxelizer.cpp.o)
  "___asan_set_shadow_f8", referenced from:
      filament::details::FRenderer::colorPass(filament::FrameGraph&, char const*, filament::FrameGraphTexture::Descriptor const&, filament::details::FRenderer::ColorPassConfig const&, filament::details::RenderPass const&, filament::details::FView const&) const in libfilament.a(Renderer.cpp.o)
      auto filament::PostProcessManager::gaussianBlurPass(filament::FrameGraph&, filament::FrameGraphId<filament::FrameGraphTexture>, unsigned char, filament::FrameGraphId<filament::FrameGraphTexture>, unsigned char, bool, unsigned long, float)::$_18::operator()<filament::PostProcessManager::gaussianBlurPass(filament::FrameGraph&, filament::FrameGraphId<filament::FrameGraphTexture>, unsigned char, filament::FrameGraphId<filament::FrameGraphTexture>, unsigned char, bool, unsigned long, float)::BlurPassData>(filament::FrameGraphPassResources const&, filament::PostProcessManager::gaussianBlurPass(filament::FrameGraph&, filament::FrameGraphId<filament::FrameGraphTexture>, unsigned char, filament::FrameGraphId<filament::FrameGraphTexture>, unsigned char, bool, unsigned long, float)::BlurPassData const&, filament::backend::CommandStream&) const in libfilament.a(PostProcessManager.cpp.o)
      filament::details::Froxelizer::update() in libfilament.a(Froxelizer.cpp.o)
      filament::details::ShadowMap::intersectWithShadowCasters(filament::Aabb&, filament::math::details::TMat44<float> const&, filament::Aabb const&) in libfilament.a(ShadowMap.cpp.o)
      meshopt::decodeVertexBlockSimd(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned long, unsigned char*) in libmeshoptimizer.a(vertexcodec.cpp.o)
      filament::backend::metal::MetalDriver::draw(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>) in libbackend.a(MetalDriver.mm.o)
      filament::backend::metal::StateCache<filament::backend::metal::PipelineState, id<MTLRenderPipelineState> __strong, filament::backend::metal::PipelineStateCreator>::getOrCreateState(filament::backend::metal::PipelineState const&) in libbackend.a(MetalDriver.mm.o)
      ...
  "___asan_before_dynamic_init", referenced from:
      __GLOBAL__sub_I_Engine.cpp in libfilament.a(Engine.cpp.o)
      __GLOBAL__sub_I_Log.cpp in libutils.a(Log.cpp.o)
      __GLOBAL__sub_I_vertexcodec.cpp in libmeshoptimizer.a(vertexcodec.cpp.o)
      __GLOBAL__sub_I_MetalBlitter.mm in libbackend.a(MetalBlitter.mm.o)
      __GLOBAL__sub_I_MetalExternalImage.mm in libbackend.a(MetalExternalImage.mm.o)
  "___asan_stack_malloc_7", referenced from:
      void std::__1::__sort<filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*> >(utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&) in libfilament.a(Scene.cpp.o)
      filament::details::ShadowMap::computeShadowCameraDirectional(filament::math::details::TVec3<float> const&, filament::details::FScene const*, filament::details::ShadowMap::CameraInfo const&, filament::details::FLightManager::ShadowParams const&, unsigned char) in libfilament.a(ShadowMap.cpp.o)
  "___asan_stack_malloc_6", referenced from:
      filament::details::FView::prepare(filament::details::FEngine&, filament::backend::CommandStream&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::Viewport const&, filament::math::details::TVec4<float> const&) in libfilament.a(View.cpp.o)
      filament::details::FRenderer::renderJob(utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::details::FView&) in libfilament.a(Renderer.cpp.o)
      filament::details::ShadowMap::computeShadowCameraSpot(filament::math::details::TVec3<float> const&, filament::math::details::TVec3<float> const&, float, float, filament::details::ShadowMap::CameraInfo const&, filament::details::FLightManager::ShadowParams const&) in libfilament.a(ShadowMap.cpp.o)
      filament::details::ShadowMap::intersectWithShadowCasters(filament::Aabb&, filament::math::details::TMat44<float> const&, filament::Aabb const&) in libfilament.a(ShadowMap.cpp.o)
  "___asan_stack_malloc_5", referenced from:
      filament::details::FTransformManager::validateNode(utils::EntityInstance<filament::TransformManager, false>) in libfilament.a(TransformManager.cpp.o)
      filament::details::FTransformManager::swapNode(utils::EntityInstance<filament::TransformManager, false>, utils::EntityInstance<filament::TransformManager, false>) in libfilament.a(TransformManager.cpp.o)
      filament::details::FView::prepareCamera(filament::details::CameraInfo const&, filament::Viewport const&) const in libfilament.a(View.cpp.o)
      filament::details::FScene::prepare(filament::math::details::TMat44<float> const&) in libfilament.a(Scene.cpp.o)
      unsigned int std::__1::__sort3<filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*> >(utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&) in libfilament.a(Scene.cpp.o)
      unsigned int std::__1::__sort5<filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*> >(utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&) in libfilament.a(Scene.cpp.o)
      bool std::__1::__insertion_sort_incomplete<filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*> >(utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&) in libfilament.a(Scene.cpp.o)
      ...
  "___asan_stack_free_5", referenced from:
      filament::details::FTransformManager::validateNode(utils::EntityInstance<filament::TransformManager, false>) in libfilament.a(TransformManager.cpp.o)
      filament::details::FTransformManager::swapNode(utils::EntityInstance<filament::TransformManager, false>, utils::EntityInstance<filament::TransformManager, false>) in libfilament.a(TransformManager.cpp.o)
      filament::details::FView::prepareCamera(filament::details::CameraInfo const&, filament::Viewport const&) const in libfilament.a(View.cpp.o)
      filament::details::FScene::prepare(filament::math::details::TMat44<float> const&) in libfilament.a(Scene.cpp.o)
      unsigned int std::__1::__sort3<filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*> >(utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&) in libfilament.a(Scene.cpp.o)
      unsigned int std::__1::__sort5<filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*> >(utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&) in libfilament.a(Scene.cpp.o)
      bool std::__1::__insertion_sort_incomplete<filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, 

filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*> >(utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, utils::Zip2Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>::Iterator<utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked>, filament::math::details::TVec4<float>, filament::math::details::TVec3<float>, utils::EntityInstance<filament::LightManager, false>, unsigned char, filament::math::details::TVec2<float>, filament::details::FScene::ShadowInfo>*>, float*>, filament::details::FScene::prepareDynamicLights(filament::details::CameraInfo const&, utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::DebugAndHighWatermark> >&, filament::backend::Handle<filament::backend::HwUniformBuffer>)::$_0&) in libfilament.a(Scene.cpp.o)
      ...

**Comment by bejado** [comment]
We just turned on ASAN for Filament, looks like we need to update the iOS
samples as well.

**Comment by romainguy** [comment]
@pixelflinger @bejado Android builds are broken with the same issues. And desktop builds fail because one of the unit tests leaks in NamedComponentManager.

**Comment by bejado** [comment]
Adding `-fsanitize=address` to the linker flags in the iOS projects fixes this. I'll put up a PR.
