### ISSUE TITLE
When resizing an hdr format file with cmgen, it flips horizontally

### ISSUE THREAD

**Issue by cx20** [google/filament#2248]
I tried to resize the `hdr` format file using `cmgen`.
The resize succeeds, but seems to be flipping left and right.

hdr file:
http://www.hdrlabs.com/sibl/archive/downloads/PaperMill_Ruins_E.zip

Converted using the following command:
```
cmgen.exe -x . --type=equirect --format=hdr --size=512  papermill.hdr
```

The following is the display result in the online HDR viewer.
https://viewer.openhdr.org/i

before: 3200x1600
![image](https://user-images.githubusercontent.com/1833979/76653800-cdd09280-65ac-11ea-9c12-84b1d14cc584.png)

after: 1024x512
![image](https://user-images.githubusercontent.com/1833979/76653891-0a9c8980-65ad-11ea-88fd-9e9ca24bbf0b.png)

The following version of the tool was used.
https://github.com/google/filament/releases/download/v1.4.5/filament-20200127-windows.tgz

**Comment by romainguy** [comment]
`cmgen` flips images horizontally because it's intended to generate cubemaps. It should skip that step when going from equirect to equirect.

@pixelflinger

**Comment by cx20** [comment]
I have found that this problem can be avoided with the `--no-mirror` option.
