### ISSUE TITLE
How to set JAVA_HOME and EMSDK

### ISSUE THREAD

**Issue by AlexanderPattison** [google/filament#2250]
Sorry for the amateur request. I am trying to build filament for web as per filament/web/filament-js/README.md

./build.sh -ap webgl release
Warning: JAVA_HOME is not set, skipping Java projects
Error: EMSDK is not set, exiting

How do I set JAVA_HOME, EMSDK, (and also ANDROID_HOME)?

**Comment by romainguy** [comment]
`JAVA_HOME` is not needed to build Filament for Web. To set `EMSDK` you'll need to set a variable in your shell:

```
$ export EMSDK=/path/to/emscripten_sdk
# ./build.sh -p webgl release
```

You fill find more details in `BUILDING.md` at the root.
