### ISSUE TITLE
Error on compile android filament on windows 10

### ISSUE THREAD

**Issue by geroge-d** [google/filament#2253]
Hi 
When i built  the filament of android-release-arm7 on Windows 10 using the latest version source code, it outputed the error messages below:

[4/670] Compiling material G:/works/filament/out/cmake-and...release-arm7/libs/gltfio/specularGlossiness_opaque.filamat
ERROR: 0:930: '=' :  cannot convert from ' const int' to ' temp mediump uint'
ERROR: 0:930: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

[5/670] Compiling material G:/works/filament/out/cmake-and...d-release-arm7/libs/gltfio/specularGlossiness_fade.filamat
ERROR: 0:931: '=' :  cannot convert from ' const int' to ' temp mediump uint'
ERROR: 0:931: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

[6/670] Compiling material G:/works/filament/out/cmake-and...release-arm7/libs/gltfio/specularGlossiness_masked.filamat
ERROR: 0:931: '=' :  cannot convert from ' const int' to ' temp mediump uint'
ERROR: 0:931: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

[9/670] Compiling material G:/works/filament/out/cmake-and.../cmake-android-release-arm7/libs/gltfio/lit_masked.filamat
ERROR: 0:934: '=' :  cannot convert from ' const int' to ' temp mediump uint'
ERROR: 0:934: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

[149/670] Compiling material G:/works/filament/out/cmake-a.../cmake-android-release-arm7/libs/gltfio/lit_opaque.filamat
ERROR: 0:933: '=' :  cannot convert from ' const int' to ' temp mediump uint'
ERROR: 0:933: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

[152/670] Compiling material G:/works/filament/out/cmake-a...ut/cmake-android-release-arm7/libs/gltfio/lit_fade.filamat
ERROR: 0:934: '=' :  cannot convert from ' const int' to ' temp mediump uint'
ERROR: 0:934: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

**Comment by romainguy** [comment]
I can reproduce on macOS. It's odd that this wasn't caught by CI.

**Comment by romainguy** [comment]
@bejado Ben, I can repro but the build servers can't apparently. It seems to be due to spirv-cross or spirv-opt. The issue doesn't happen when I turn off matc's optimization stage.

**Comment by bejado** [comment]
Bizarre, I’ll take a look. Might have something to do with spot shadows

**Comment by romainguy** [comment]
If I comment out `fullOptimization()` in `GLSLPostProcessor` the error happens anyway, so probably not related to optimizations after all. But somehow related since `-g` bypasses the problem when invoking matc.

**Comment by romainguy** [comment]
Ah it's contact shadows.

```
for (uint i = 0 ; i < kStepCount ; i++, t += dt) {
```

It should be `0u` not `0`.

**Comment by romainguy** [comment]
Yeah that fixes it. Ben, want to do the checkin? :)
