### ISSUE TITLE
Link issue on building the filament of android version on windows 10 using vs2019

### ISSUE THREAD

**Issue by geroge-d** [google/filament#2255]
Hi 
When i built filament of android version on windows 10, using vs 2019, the issue below occur.  

../../../../src/main/cpp/SurfaceOrientation.cpp:153: error: undefined reference to 'filament::geometry::SurfaceOrientation::getQuats(filament::math::details::TQuaternion<filament::math::half>*, unsigned int, unsigned int) const'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by romainguy** [comment]
Which version of Filament? We recently fixed that issue but you'll need the latest version from master.

**Comment by geroge-d** [comment]
the latest version source codes, we pulled codes from master just now

**Comment by geroge-d** [comment]
When i comment the function  implementation  of SurfaceOrientation.cpp:153 , it succeed in building
