### ISSUE TITLE
The right way to call createSwapChain when rendering to an imported texture

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2260]
When rendering into a texture what is the proper way to create the swap chain? I'm currently doing this:

`filamentSwapChain = fframe.engine.createSwapChain(1, 1, 0)`

Which is working, but feels like a hack. I'm actually rendering to two textures that I have imported into Filament using importShared (they are the eye buffers of a VR rendering).

Is the eglCreatePbufferSurface created in PlatformEGL actually used if we are specifying a renderTarget for the View?

**Comment by romainguy** [comment]
It's fine to create a 1x1 swap chain like this. It's a common trick in renderers.

**Comment by dandingol03** [comment]
> When rendering into a texture what is the proper way to create the swap chain? I'm currently doing this:
> 
> `filamentSwapChain = fframe.engine.createSwapChain(1, 1, 0)`
> 
> Which is working, but feels like a hack. I'm actually rendering to two textures that I have imported into Filament using importShared (they are the eye buffers of a VR rendering).
> 
> Is the eglCreatePbufferSurface created in PlatformEGL actually used if we are specifying a renderTarget for the View?

HI, i am intersted what you have done. Are you trying to render something into an imported texture using rendertarget?
