### ISSUE TITLE
Alpha for background color doesn't seem to work in Canvas 

### ISSUE THREAD

**Issue by JonathanLehner** [google/filament#2263]
**Describe the bug**
I cannot set a transparent or semi-transparent background of the webgl2 canvas with Filament. The renderer seems to ignore the options.

**To Reproduce**
I modified the suzanne example. 1.)
`const options = {
  majorVersion: 2,
  minorVersion: 0,
  antialias: false,
  depth: true,
  alpha: true,
  premultipliedAlpha: false,
  preserveDrawingBuffer: true
};
this.engine = Filament.Engine.create(canvas, options);`
and 2)
`this.view.setClearColor([0,1,0,0])`
However the background is never transparent.
If I use `var gl = filament_canvas.getContext('webgl2', {alpha: true, premultipliedAlpha: false});
gl.clearColor(0,0.1,0,0.5);
gl.clear(gl.COLOR_BUFFER_BIT);`then I get a semi-transparent background (but of course there won't rendered objects). 

**Expected behavior**
There should be the monkey head with a semi-transparent background color of the WebGL2 canvas.

**Desktop (please complete the following information):**
Chrome & Firefox

**Comment by prideout** [comment]
Filament currently requires post-processing to be disabled for this to work; this is not an issue with Filament's JavaScript API.

So, in addition to adding `{alpha: true}` to your canvas options, you need to add:

`this.view.setPostProcessingEnabled(false);`

Note however that this will deactivate tone mapping and other features like bloom and FXAA.

I defer to @pixelflinger about whether we should support semi-transparent background in our post-processing pipeline...

**Comment by romainguy** [comment]
I thought we had a special path specifically to do FXAA on a transparent background. There's nothing in the post process pipeline that should require an opaque surface.

**Comment by prideout** [comment]
In that case this might be a regression, I've confirmed that disabling post-processing seems to fix the issue.

I've also noticed that post-processing now triggers several WebGL warnings in the Chrome console, which is possibly related -- I'll file a separate bug for that.

**Comment by JonathanLehner** [comment]
If I disable postprocessing then the track pad doesnt work anymore. The old views all merge together

**Comment by JonathanLehner** [comment]
Can the canvas be cleared manually between rendering?

**Comment by JonathanLehner** [comment]
The way I solved it for now is by making a loop to clear the canvas before every re-render
setInterval(()=>{ 
      this.gl.clearColor(1,0,0,0);
      this.gl.clear(this.gl.COLOR_BUFFER_BIT | this.gl.DEPTH_BUFFER_BIT | this.gl.ACCUM_BUFFER_BIT | this.gl.STENCIL_BUFFER_BIT)
    }, 0); 
very hacky but it works well.

**Comment by prideout** [comment]
This works now.  Three steps to success:
1) Remove the skybox from the scene.
2) Pass `{alpha: true}` into the optional second argument of `Engine.create(...)`
3) Call `view.setBlendMode(Filament.View$BlendMode.TRANSLUCENT)`
