### ISSUE TITLE
Unexposed library are using in Samples

### ISSUE THREAD

**Issue by iamlkj** [google/filament#2265]
**Describe the bug**
I'm wondering why there's some library that doesn't expose in public install library but using in Samples (Such like NameComponentManager). I thought NameComponentManager should be public and it's also a sample for using SingleInstanceComponentManager.h. Or are those two files meant to be hidden?

I can't find a way to load out the node name from gltf file using AssetLoader with default filament public install library.

**Comment by romainguy** [comment]
`NameComponentManager` is part of `libutils`, it's available as a public library. What problem are you running into exactly?

**Comment by romainguy** [comment]
@pixelflinger Should `NameComponentManager` be tagged `UTILS_PUBLIC`? Most things in `libutils` aren't marked with `UTILS_PUBLIC`, I assume on purpose. But I don't see any reason why `NameComponentManager` wouldn't be public.

**Comment by pixelflinger** [comment]
Yes it should probably be `UTILS_PUBLIC` -- We've just been (too?) cautious about making things public.

**Comment by iamlkj** [comment]
Should all the .h files expose as public? I'm modifying CMakelist to expose NameComponentManager.h and SingleInstanceComponentManager.h into `DIST_HDRS` but turns out I need to expose tons of headers in libutils.

**Comment by romainguy** [comment]
No, not all .h files should be public. I still need to add those two to `DIST_HDRS`.

**Comment by iamlkj** [comment]
I see. Thanks for this or it's almost impossible to expose the libutils and make build works.

**Comment by romainguy** [comment]
I just committed the change.

**Comment by iamlkj** [comment]
Thanks! I'll cherrypick it and try it on release branch.

**Comment by iamlkj** [comment]
Wait I tried this before. Turns out there's more dependancies inside SingleInstanceComponentManager.h such like StructureOfArrays.h needs to be exposed.

**Comment by romainguy** [comment]
Damn, `StructureOfArrays.h` needs `Allocator`, `Mutex`, `Slice`…

**Comment by iamlkj** [comment]
Yes thats why Im so struggle in this lol

**Comment by iamlkj** [comment]
And in the end it needs robin_map and generic/mutex...

**Comment by 100espressos** [comment]
Seems related to what I'm stuck on in Linux? My report:

```
other.cpp:160: undefined reference to `utils::Path::concat(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cpp:129: undefined reference to `utils::Path::getName[abi:cxx11]() const'
test.cpp:647: undefined reference to `utils::Path::getExtension[abi:cxx11]() const'
test.cpp:995: undefined reference to `filament::viewer::writeJson[abi:cxx11](filament::viewer::ColorGradingSettings const&)'
test.cpp.o: in function `main::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)#10}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const':
test.cpp:1026: undefined reference to `utils::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cpp.o: in function `main':
test.cpp:612: undefined reference to `utils::operator<<(std::ostream&, utils::Path const&)'
test.cpp:618: undefined reference to `utils::Path::getExtension[abi:cxx11]() const'
test.cpp:624: undefined reference to `utils::operator<<(std::ostream&, utils::Path const&)'
```
