### ISSUE TITLE
cannot generate libfilamat_combined.a on windows

### ISSUE THREAD

**Issue by zbzdys** [google/filament#2279]
I could build filament on windows several months ago.
Now I download release 1.4.5 source code and all-build by vs ok, 119 projects total.
Then I use Ninja to build matc tools and others like resgen, no prob.
The last step is build cmake-android-release-aarch64, after running ninja install, I get:

[357/613] Update build-version.inc in the SPIRV-Tools build directory (if necessary).
C:/Users/dingw/Desktop/workspace/Cpp/Filament/third_party/spirv-tools/utils/update_build_version.py:91: DeprecationWarning: 'U' mode is deprecated
  with open(changes_file, mode='rU') as f:
[612/613] Install the project...
-- Install configuration: "Release"

still no prob.
But it failed to install at libfilamat_combined.a like this:

-- Installing: C:/Users/dingw/Desktop/workspace/Cpp/Filament/out/android-release/filament/lib/arm64-v8a/libmeshoptimizer.a
CMake Error at libs/filamat/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "C:/Users/dingw/Desktop/workspace/Cpp/Filament/out/cmake-android-release-aarch64/libs/filamat/libfilamat_combined.a":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:67 (include)

FAILED: CMakeFiles/install.util
cmd.exe /C "cd /D C:\Users\dingw\Desktop\workspace\Cpp\Filament\out\cmake-android-release-aarch64 && "C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake"
ninja: build stopped: subcommand failed.

I have the required cmake, ninja, ndk, latest version. I can build many other .a files like lib/arm64-v8a/libmeshoptimizer.a, only filamat combind failed.

Please have a look, thanks a lot~

**Comment by zbzdys** [comment]
Build with the latest master branch code, still got the same error.

Envs:
Windows 10, VS2019, NDK 21, cmake 3.16, python 3.8

**Comment by zbzdys** [comment]
Also, cmake outputs:

building with clang on windows is no longer supported, use msvc 3019 instead

But the doc of filament is the same as old version, so i'm not sure what's the right command.

**Comment by bejado** [comment]
We no longer use Clang to build on Windows. I'll update the documentation.

`libfilamat_combined.a` is generated through a Bash script: `build\linux\combine-static-libs.sh`. The error message you're seeing probably means it failed to run. Are there any other error messages after running `ninja install`? I'd expect something like:

```
combine-static-libs.sh is not recognized as an internal or external command, operable program or batch file.
```

Note: we get away with using a Bash script on Windows because Git for Windows provides a Bash emulator.

**Comment by zbzdys** [comment]
I have Git, so "ombine-static-libs.sh" not shown in the output log.

I will paste more info here:
To get vs project:
cmake ..\.. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DFILAMENT_SUPPORTS_VULKAN=ON 
all-build ok

To build android, first build some tools, even though these tools already generated by vs project:
cmake ..\.. -G Ninja -DFILAMENT_SUPPORTS_VULKAN=ON -DCMAKE_INSTALL_PREFIX=..\release\filament -DCMAKE_BUILD_TYPE=Release -DFILAMENT_ENABLE_JAVA=ON

but -DFILAMENT_ENABLE_JAVA=ON seems not recognized.

To build android:
cmake ..\.. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\android-release\filament -DCMAKE_TOOLCHAIN_FILE=..\..\build\toolchain-aarch64-linux-android.cmake -DFILAMENT_SUPPORTS_VULKAN=ON

I can get many *.a files:
-- Installing: C:/Users/dingw/Desktop/workspace/Cpp/Filament/out/android-release/filament/include/backend/TargetBufferInfo.h
-- Installing: C:/Users/dingw/Desktop/workspace/Cpp/Filament/out/android-release/filament/lib/arm64-v8a/libshaders.a
-- Installing: C:/Users/dingw/Desktop/workspace/Cpp/Filament/out/android-release/filament/lib/arm64-v8a/libsmol-v.a
-- Installing: C:/Users/dingw/Desktop/workspace/Cpp/Filament/out/android-release/filament/lib/arm64-v8a/libmeshoptimizer.a
CMake Error at libs/filamat/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "C:/Users/dingw/Desktop/workspace/Cpp/Filament/out/cmake-android-release-aarch64/libs/filamat/libfilamat_combined.a":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:67 (include)


FAILED: CMakeFiles/install.util
cmd.exe /C "cd /D C:\Users\dingw\Desktop\workspace\Cpp\Filament\out\cmake-android-release-aarch64 && "C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake"
ninja: build stopped: subcommand failed.

It stoped at libfilamat_combined.a not exists.

The combine shell script can open with git bash:
![sh](https://user-images.githubusercontent.com/18547591/77605315-8dc7c300-6f4f-11ea-94cd-933bdc3060b5.png)

By the way, to build aar, the gradlew command is incorrect in the doc, should be like:
..\gradlew -Pfilament_dist_dir=..\..\out\android-release\filament assembleRelease

**Comment by zbzdys** [comment]
sorry github convert ..\\.. to ....

**Comment by zbzdys** [comment]
i noticed that combine-static-libs.sh get:
AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android-ar.exe
cmake-android-release-aarch64/libs/filamat/libfilamat_combined.a
cmake-android-release-aarch64/third_party/glslang/tnt/OGLCompilersDLL/libOGLCompiler.a
...
as parameters, but it went to:
if [[ "$#" -lt 3 ]]; then
    print_help
    exit 1
fi

echo "$#"

Result is 0, that is why could not generate combined.a file.

still looking into the reason why this happens

**Comment by zbzdys** [comment]
there is a problem with my git bash, it can not get command line arguments when calls from cmd.exe

however, it can get the correct arguments when execute .sh file in git-bash window(MINGW64)

so i copy:
...Filament\build\linux\combine-static-libs.sh ...aarch64-linux-android-ar.exe ...libfilamat_combined.a

to the git-bash windows and execute successfully.

problem solved.

**Comment by zbzdys** [comment]
The last step generate aar failed because:
Task '..\..\out\android-release\filament' not found in project ':filament-android'.

here is the log:
PS C:\Users\dingw\Desktop\workspace\Cpp\Filament\android\filament-android> ..\gradlew -Pfilament_dist_dir=..\..\out\android-release\filament assembleRelease -Pextra_cmake_args=-DFILAMENT_SUPPORTS_VULKAN=ON
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :filamat-android
WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.

> Configure project :filament-android
WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.

> Configure project :filament-utils-android
WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.

> Configure project :gltfio-android
WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.

FAILURE: Build failed with an exception.

* What went wrong:
Task '..\..\out\android-release\filament' not found in project ':filament-android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by zbzdys** [comment]
I think the doc about android build should be updated, especially about vulkan

**Comment by romainguy** [comment]
`FILAMENT_ENABLE_JAVA` is only for desktop, it is indeed ignored for Android builds.

**Comment by romainguy** [comment]
```By the way, to build aar, the gradlew command is incorrect in the doc, should be like:
..\gradlew -Pfilament_dist_dir=....\out\android-release\filament assembleRelease```

Where in the doc is the command incorrect? The command in `Windows.md` looks like exactly like this one.

@bejado Can you update the section "## Generate AAR" in `Windows.md` please? It's based on the old structure where each library had its own root Gradle file. Now it's better to invoke Gradle from `android/` instead of `android/filament-android`.

**Comment by zbzdys** [comment]
![aar](https://user-images.githubusercontent.com/18547591/77711390-cf1da880-700b-11ea-85c5-52aa30be207a.PNG)

Here is the screenshot about generating aar. There is no gradlew in android\filament-android, gradlew is actually in "android" folder.

The most important thing is my command failed to run because:
**out\android-release\filamen not found in project ':filament-android'**

**Comment by zbzdys** [comment]
when i execute:

.\gradlew -Pfilament_dist_dir=..\out\android-release\filament -Pextra_cmake_args=-DFILAMENT_SUPPORTS_VULKAN=ON assembleRelease

in "android" directory,  the error becomes:

 '..\out\android-release\filament' not found in root project 'filament'

I dont know how to fix it up, help me please.

**Comment by romainguy** [comment]
I've updated `Windows.md`. I don't know what this error you're running into means. Do you have a directory `..\out\android-release\filament`? Did you properly build filament for Android in it?

**Comment by zbzdys** [comment]
Yes I have this "out\android-release\filament" because I have run "ninja install" after building toolchain-aarch64-linux-android.cmake.

**Comment by zbzdys** [comment]
[SOLVED]
It is powershell problem, when i use cmd to run the command, gradlew tasks all successfully executed.
If use powershell, gradlew is not recognized so i have to use '.\gradlew' and this is the different part from your doc.
If use cmd, gradlew is recognized so i can run:
gradlew -Pfilament_dist_dir=..\out\android-release\filament -Pextra_cmake_args=-DFILAMENT_SUPPORTS_VULKAN=ON assembleRelease

If this is confirmed not only my problem, the doc about generating aar should put a notice about this.
