### ISSUE TITLE
Typo: smoothness (1.0) or roughness (0.0) in the document

### ISSUE THREAD

**Issue by syoyo** [google/filament#228]
**Describe the bug**

https://github.com/google/filament/blob/master/docs/Filament.md.html#L606

> smoothness (1.0) or roughness (0.0)

Contrary value is assigned for each meanings.
This should be 

```
smoothness(0.0) or roughness(1.0)
```

**Comment by romainguy** [comment]
Good catch!

**Comment by syoyo** [comment]
😎
