### ISSUE TITLE
how filament work with mediapipe

### ISSUE THREAD

**Issue by jiqimaogou** [google/filament#2280]
how filament work with mediapipe? do you have some example?
or how filament render to framebuffer texture.

**Comment by romainguy** [comment]
What is `mediapipe`?

**Comment by jiqimaogou** [comment]
https://github.com/google/mediapipe

**Comment by jiqimaogou** [comment]
> What is `mediapipe`?

https://github.com/google/mediapipe it is google another machine learning pipeline library

**Comment by prideout** [comment]
On Android, we provide a `UiHelper` class that makes it easy to render into a TextureView.  We don't know anything about MediaPipe but it looks like it has a [mechanism](https://g3doc.corp.google.com/third_party/mediapipe/g3doc/hello_world_android.md?cl=head#externaltextureconverter-setup) for consuming a SurfaceTexture, which you can grab from a TextureView.
