### ISSUE TITLE
Expose getLayerMask() in RenderableManager

### ISSUE THREAD

**Issue by iamlkj** [google/filament#2286]
Is there any reason why filament only expose RenderableManager::setLayerMask but hide RenderableManager::getLayerMask in FRenderableManager? Is it possible to expose it out?

**Comment by romainguy** [comment]
It's most likely an oversight. We usually expose APIs as they become needed. Feel free to send a PR to expose it if you want, otherwise we can do it.

**Comment by iamlkj** [comment]
I can do it later today
