### ISSUE TITLE
gltf_baker doesn't bake tangent space normal maps

### ISSUE THREAD

**Issue by romainguy** [google/filament#2293]
gltf_baker should generate normal/bent normal maps in tangent space. Right now it takes the normals computed by libray and just writes them to PNG as is. They should at least be encoded to fit in 0..1 instead of -1..+1.

**Comment by prideout** [comment]
Let me know if there is significant interest in reviving the tool, its usage message still describes it as an AO baking tool but the UV wrapping was very dodgy and we sort of gave up on it.

On a related note I wonder if we should consider moving projects like this and Tungsten into a separate repo outside of Filament since they are somewhat experimental.

**Comment by romainguy** [comment]
We should definitely move those projects out if we're not going to maintain it. Actually I would recommend we do a big sweep of `samples/` in general and ditch the ones that are not useful. If we do move `gltf_baker` out we may want to consider moving `OpenImageDenoise` and `libray` as well. Anything we do to shorten build times is nice.

We should also stop backing an IBL + FlightHelmet in `gltf_viewer` (shorter build times, smaller executables) and move `gltf_viewer` to `tools` or at least install it in `bin` in our release packages. It is a genuinely useful app and good example of Filament. `material_sandbox` should be given the same treatment I think. It's a good showcase of what Filament can do.

`lightbulb`, `frame_generator` and `sample_full_pbr` should move to a `test` directory. They're really useful for us during development and nothing else. All the `vk_*` samples should probably be renamed because they're not really Vulkan specific.

What do you think?

**Comment by romainguy** [comment]
BTW the only reason I looked at `gltf_baker` and filed this bug is because I'm implementing support for bent normal maps. I have other tools I can use to bake bent normals so I don't need this one. But in case it worked… :)

**Comment by prideout** [comment]
Your plan for `samples/` sounds great, the only part that I dislike is removing the default IBL from the viewer, personally I find it helpful. Moreover the fact that we invoke cmgen in the build has helped us catch issues in the past.  As a compromise maybe we could add a CMake option for this feature.

**Comment by prideout** [comment]
gltf_baker has been removed but exists in our history.
