### ISSUE TITLE
Question: Using filament in game engine

### ISSUE THREAD

**Issue by amerkoleci** [google/filament#2294]
Not a bug or feature requested, just a question,

I'm working on personal game engine (https://github.com/amerkoleci/alimer) and would like to use filament and modify/adapt on some engine logic, are there any issues between MIT license and the apache V2 of filament? Are there any best practice when integrating into other projects?

Probably I would like to add Direct3D11/Direct3D12 backend as we..

This is just an idea, not sure if I will pursue it :)

Thanks

**Comment by romainguy** [comment]
There shouldn't be any issue with the license. As for integrating Filament in another engine the easiest way is probably to do it via prebuilt binaries. Our build system is a bit complicated and I'm not sure how easy it would be to merge it with another project's build system.

**Comment by romainguy** [comment]
BTW let us know if you do create a DirectX backend, it could be interesting.
