### ISSUE TITLE
cmake error on linux, build.sh -p webgl release

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2295]
I think something might have changed on the cmake side ...

CMake Warning at third_party/spirv-tools/CMakeLists.txt:207 (find_package):
  By not providing "FindPython3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python3" with any
  of the following names:

    Python3Config.cmake
    python3-config.cmake

  Add the installation prefix of "Python3" to CMAKE_PREFIX_PATH or set
  "Python3_DIR" to a directory containing one of the above files.  If
  "Python3" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by romainguy** [comment]
Which version of CMake are you using?

**Comment by unicomp21** [comment]
3.10.2

**Comment by romainguy** [comment]
You'll need CMake 3.12, I see I forgot to update BUILDING.md, I'll fix this asap.

**Comment by unicomp21** [comment]
Is there a way to install that via apt-get?  Or is it  a manual install?

**Comment by romainguy** [comment]
What distribution do you use? It should be available via apt-get if you have a recent distribution or the right repositories for apt-get.

**Comment by romainguy** [comment]
Let me see if I can make the CMake files compatible with 3.10.

**Comment by unicomp21** [comment]
ubuntu18.10

**Comment by romainguy** [comment]
https://github.com/google/filament/pull/2296 should address your problem hopefully.

**Comment by unicomp21** [comment]
Thx!

**Comment by unicomp21** [comment]
after #2296

-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:27 (cmake_policy):
  Policy "CMP0074" is not known to this version of CMake.

**Comment by unicomp21** [comment]
I can manually install 3.12, but I can see this creating a support headache in the future.

**Comment by romainguy** [comment]
I checked in a fix, try again :)

**Comment by unicomp21** [comment]
[94/662] Building CXX object filament/backend/CMakeFiles/backend.dir/src/vulkan/VulkanContext.cpp.o
[95/662] Generate extended instruction tables for debuginfo.
[96/662] Generate tables based on the SPIR-V XML registry.
FAILED: third_party/spirv-tools/generators.inc 
cd /tmp/filament/out/cmake-release/third_party/spirv-tools/source && /usr/bin/python3 /tmp/filament/third_party/spirv-tools/utils/generate_registry_tables.py --xml=/tmp/filament/third_party/spirv-tools/external/spirv-headers/include/spirv/spir-v.xml --generator-output=/tmp/filament/out/cmake-release/third_party/spirv-tools/generators.inc
Traceback (most recent call last):
  File "/tmp/filament/third_party/spirv-tools/utils/generate_registry_tables.py", line 17, in <module>
    import distutils.dir_util
ModuleNotFoundError: No module named 'distutils.dir_util'
[97/662] Building C object third_party/getopt/CMakeFiles/getopt.dir/src/getopt_long.c.o
[98/662] Generate extended instruction tables for spv-amd-gcn-shader.
[99/662] Generate info tables for SPIR-V vunified1 core instructions and operands.
[100/662] Generate language specific header for OpenCLDebugInfo100.
[101/662] Building CXX object filament/backend/CMakeFiles/backend.dir/src/vulkan/VulkanDriver.cpp.o
ninja: build stopped: subcommand failed.
The command '/bin/sh -c ./build.sh -p webgl release' returned a non-zero code: 1

**Comment by romainguy** [comment]
Looks like an issue with your python installation or spirv-tools. It's not part of filament itself unfortunately.

**Comment by unicomp21** [comment]
@romainguy for some reason it only happens on master, v1.4.5 builds fine.

**Comment by romainguy** [comment]
We've upgraded to a more recent version of spirv-tools that requires Python3.

**Comment by unicomp21** [comment]
I've got python3 installed, guess it's the spirv-tools.

**Comment by romainguy** [comment]
Not sure, you're missing the module `distutils` which is part of [Python](https://docs.python.org/3/library/distutils.html).

**Comment by unicomp21** [comment]
>python3 --version
Python 3.6.9

**Comment by romainguy** [comment]
Try `apt-get install python3-distutils` maybe? It should already be installed but it seems it's not on your distribution.

**Comment by unicomp21** [comment]
That did the trick, thx @romainguy !
