### ISSUE TITLE
Win64: material_sandbox ImGui font not found

### ISSUE THREAD

**Issue by Hayaweh** [google/filament#23]
Hi there,

Whilst trying to test the material_sandbox, It happened to crash at:
`libs\filagui\src\ImGuiHelper.cpp : line 52.`

It seems like `getCurrentExecutable()` returns the executable path properly and `.getParent()` removes the material_sandbox.exe from this path.

It afterward adds the path to the font as if assets was a sub-folder to the executable path.

Is there a symlink missing to the assets folder or is `getParent()` returning something wrong, maybe.

It seems like it *could* be linked to #13 as getParent uses `getCanonicalPath`, but something else feels off to me there (get parent only peels the last segment anyway).

here is the path value I get for the font: `"X:\\Projects\\Projects\\Renderers\\Filament\\bin\\bin\\Debug\\assets/fonts/Roboto-Medium.ttf"`

Hope this can help.
Cheers.

**Comment by bejado** [comment]
Hello- yes this appears to be a valid bug. Probably an oversight with how we’re passing paths to Windows. Will take a look, thanks for reporting!

**Comment by romainguy** [comment]
The `assets` directory should be in the same directory as `material_sandbox.exe`. We are indeed looking for `./assets` where the current directory is the directory of `material_sandbox.exe`. Here what it looks like on macOS:

```
romainguy-macpro2:filament ᛘpbr $ ll out/cmake-release/samples/
total 113544
drwxr-xr-x  22 romainguy  eng      748 Jul 31 16:18 CMakeFiles
-rw-r--r--   1 romainguy  eng      139 Jul 27 09:26 MoltenVK_icd.json
-rwxr-xr-x   1 romainguy  eng  1872428 Aug  3 18:25 animation
drwxr-xr-x   4 romainguy  eng      170 Jul 27 09:26 assets
-rw-r--r--   1 romainguy  eng      898 Jul 27 09:26 cmake_install.cmake
-rwxr-xr-x   1 romainguy  eng  1872356 Aug  3 18:25 depthtesting
drwxr-xr-x   3 romainguy  eng      102 Jul 27 09:26 generated
-rwxr-xr-x   1 romainguy  eng  3831176 Aug  3 18:25 hellopbr
-rwxr-xr-x   1 romainguy  eng  1872356 Aug  3 18:25 hellotriangle
-rwxr-xr-x   1 romainguy  eng  5698400 Jul 27 09:26 libMoltenVK.dylib
-rw-r--r--   1 romainguy  eng   328744 Aug  3 18:25 libsample-app.a
-rwxr-xr-x   1 romainguy  eng   329416 Jul 27 09:26 libvulkan.1.dylib
-rwxr-xr-x   1 romainguy  eng  3901500 Aug  3 18:25 lightbulb
-rwxr-xr-x   1 romainguy  eng  4872932 Aug  3 18:25 material_sandbox
-rwxr-xr-x   1 romainguy  eng  2014556 Aug  3 18:25 sample_cloth
-rwxr-xr-x   1 romainguy  eng  3994424 Aug  3 18:25 sample_full_pbr
-rwxr-xr-x   1 romainguy  eng  2168508 Aug  3 18:25 sample_imgui
-rwxr-xr-x   1 romainguy  eng  2014180 Aug  3 18:25 sample_normal_map
-rwxr-xr-x   1 romainguy  eng  2010852 Aug  3 18:25 sample_opacity_mask
-rwxr-xr-x   1 romainguy  eng  3990232 Aug  3 18:25 sample_pbr
-rwxr-xr-x   1 romainguy  eng  3981364 Aug  3 18:25 sample_position_offset
-rwxr-xr-x   1 romainguy  eng  2014556 Aug  3 18:25 sample_subsurface
-rwxr-xr-x   1 romainguy  eng  3880868 Aug  3 18:25 shadowtest
-rwxr-xr-x   1 romainguy  eng  1843372 Aug  3 18:25 strobecolor
-rwxr-xr-x   1 romainguy  eng  1872376 Aug  3 18:25 texturedquad
drwxr-xr-x  10 romainguy  eng      442 Jul 27 09:26 textures
-rwxr-xr-x   1 romainguy  eng  1866028 Aug  3 18:25 vbotest
-rwxr-xr-x   1 romainguy  eng  1841388 Aug  3 18:25 viewtest
```

How did you build the samples?

**Comment by bejado** [comment]
@Hayaweh, the issue should be fixed now, please sync and try again. (you may also need to delete your build directory and re-run CMake). `material_sandbox` is now built in the `samples/` directory on Windows, so it should have access to the font resource.
