### ISSUE TITLE
Render transparent opaque object

### ISSUE THREAD

**Issue by JonathanLehner** [google/filament#2304]
I need to render a transparent opaque object. It needs to hide the objects behind it, but itself it has to output transparent/alpha=0 to the canvas (needs to be invisible in the final rendering). 
How can I achieve this?
Do I need to do something like
```
material {
    blending : masked
}
```
?

**Comment by romainguy** [comment]
You do this by rendering an opaque object with colorWrite set to false and depthWrite set to true.
