### ISSUE TITLE
Color buffer of view is not cleared

### ISSUE THREAD

**Issue by geroge-d** [google/filament#2312]
Hi 
We clear view color buffer by calling view.setClearTargets(true,true,true), but the filament don't clear the color buffer.We added some logs in the filament ,found that rs.colorWrite in the function clearWithRasterPipe in opengldriver.cpp  set to false.  The codes below where we added logs in filament:
1. logs in  FRenderer::renderJob
 if (any(discardedFlags & TargetBufferFlags::COLOR0)){
        utils::slog.e << "View discardedFlags color0: 1" <<  utils::io::endl;
    }
    else{
        utils::slog.e << "View discardedFlags color0: 0" <<  utils::io::endl;
    }
    if (any(viewclearflags & TargetBufferFlags::COLOR0)){
        utils::slog.e << "View viewclearflags color0: 1" <<  utils::io::endl;
    }
    else{
        utils::slog.e << "View viewclearflags color0: 0" <<  utils::io::endl;
    }
    if (any(discardedFlags & TargetBufferFlags::COLOR1)){
        utils::slog.e << "View discardedFlags COLOR1: 1" <<  utils::io::endl;
    }
    else{
        utils::slog.e << "View discardedFlags COLOR1: 0" <<  utils::io::endl;
    }
    if (any(discardedFlags & TargetBufferFlags::DEPTH)) {
        clearFlags |= TargetBufferFlags::DEPTH;
        utils::slog.e << "View clear depth: 1" <<  utils::io::endl;
    }
    else{
        utils::slog.e << "View clear depth: 0" <<  utils::io::endl;
    }

2. logs in  OpenGLDriver::clearWithRasterPipe:

    if (any(clearFlags & TargetBufferFlags::COLOR_ALL)) {
        rs.colorWrite = true;
        utils::slog.e << "clear colorwrite:true " << utils::io::endl;
    }
    else{
        utils::slog.e << "clear colorwrite:false, " << (int)clearFlags << utils::io::endl;

    }
    if (any(clearFlags & TargetBufferFlags::DEPTH)) {
        utils::slog.e << "clear depthWrite:true " << utils::io::endl;
        rs.depthWrite = true;
    }
    else{
        utils::slog.e << "clear depthWrite:false " << utils::io::endl;

    }
AND WE GOT logs printed like below :

03-31 21:59:30.777 2803-3794/E/Filament: View discardedFlags color0: 1
03-31 21:59:30.777 2803-3794/E/Filament: View viewclearflags color0: 1
03-31 21:59:30.777 2803-3794/E/Filament: View discardedFlags COLOR1: 0
03-31 21:59:30.777 2803-3794/E/Filament: View clear depth: 1
03-31 21:59:30.777 2803-3794/E/Filament: View haspostprocess: 0
03-31 21:59:30.777 2803-3794/E/Filament: View discardedFlags color0: 1
03-31 21:59:30.777 2803-3794/E/Filament: View viewclearflags color0: 1
03-31 21:59:30.777 2803-3794/E/Filament: View discardedFlags COLOR1: 0
03-31 21:59:30.777 2803-3794/E/Filament: View clear depth: 1
03-31 21:59:30.777 2803-3794/E/Filament: View haspostprocess: 0
03-31 21:59:30.777 2803-3794/E/Filament: View discardedFlags color0: 1
03-31 21:59:30.777 2803-3794/E/Filament: View viewclearflags color0: 1
03-31 21:59:30.777 2803-3815/E/Filament: clear colorwrite:false, 16
03-31 21:59:30.777 2803-3815/E/Filament: View discardedFlags COL
03-31 21:59:30.777 2803-3794/E/Filament: View discardedFlags COLOR1: 0
03-31 21:59:30.777 2803-3794/E/Filament: View clear depth: 1
03-31 21:59:30.777 2803-3815/E/Filament: clear colorwrite:false, 16
03-31 21:59:30.777 2803-3815/E/Filament: clear depthWrite:true 
03-31 21:59:30.787 2803-3815/E/Filament: clear colorwrite:false, 16
03-31 21:59:30.787 2803-3815/E/Filament: clear depthWrite:true 
03-31 21:59:30.787 2803-3794/E/Filament: View haspostprocess: 0
03-31 21:59:30.787 2803-3794/E/Filament: View discardedFlags color0: 1
03-31 21:59:30.787 2803-3794/E/Filament: View viewclearflags color0: 1
03-31 21:59:30.787 2803-3794/E/Filament: View discardedFlags COLOR1: 0
03-31 21:59:30.787 2803-3794/E/Filament: View clear depth: 1
03-31 21:59:30.787 2803-3815/E/Filament: clear colorwrite:false, 16
03-31 21:59:30.787 2803-3815/E/Filament: clear depthWrite:true

**Comment by geroge-d** [comment]
FYI
We use the latest source code,just pulled from master branch

**Comment by prideout** [comment]
Thanks for bringing this to our attention, I can reproduce it using our `vk_hellotriangle` sample.

**Comment by romainguy** [comment]
Looks like @pixelflinger fixed the glClear path but not the clear with raster pipe path.
