### ISSUE TITLE
Android gltf-viewer sample crashes in 1.5.1

### ISSUE THREAD

**Issue by alexredko** [google/filament#2319]
Hi guys,
**Describe the bug**
I use code similar to android gltf viewer sample to load a gltf model (sync method). It worked with version 1.4.5. But the app crashes after updating to 1.5.1 from maven.
The android/sample-gltf-viewer  sample also crashes now with 1.5.1 and the BusterDrone model from the sample. But the sample works when I downgrade to 1.4.5.
It appears when the ResourceLoader tries to call 
`nLoadResources(mNativeObject, asset.getNativeObject());`
and for async version from modelViewer:
n`AsyncBeginLoad(mNativeObject, asset.getNativeObject());`

I/Filament: Filament library loaded.
I/Filament: FEngine (64 bits) created at 0x751d200000 (threading is enabled)
D/Filament: FEngine resolved backend: OpenGL
D/SurfaceView: setPackageUsesOwnResolution() (Java SurfaceView) for unknown app: 0x0 (false)
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb0 in tid 15486 

**To Reproduce**
1. Run the android/sample-gltf-viewer app.

**Smartphone (please complete the following information):**
 - Device: Galaxy A8 2018, Lenovo TB3-850M
 - OS:  Android 8.0, Android 6.0

**Comment by prideout** [comment]
I can repro using our maven packages but it works when built within our source tree.

I don't understand what's going on yet.  Thanks for the report!

**Comment by prideout** [comment]
This should be fixed #2332, I'm doing some extra testing  before closing.
