### ISSUE TITLE
Crashing when i try to recreate android sample project

### ISSUE THREAD

**Issue by arctic4x** [google/filament#2320]
i ran into difficulties while running samples (get some errors when start scripts and some files desn't generated) and made a decision to make a new project by implementing lib and using samples code. But i alsways get a crash on v-1.5.1:

 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 Build fingerprint: 'Xiaomi/cancro_wc_lte/cancro:6.0.1/MMB29M/V9.5.5.0.MXDMIFA:user/release-keys'
 Revision: '0'
 ABI: 'arm'
 pid: 6194, tid: 6194, name: example.qweqwe2  >>> com.example.qweqwe2 <<<
 signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x88
     r0 00000000  r1 00000000  r2 00000000  r3 9ea268f0
     r4 9ec6e070  r5 00000014  r6 9ec6e070  r7 bec70c68
     r8 9ec5e0d8  r9 9ec5e0a0  sl 9ec5e0fc  fp 00000000
     ip 00000018  sp bec70bec  lr b33949ef  pc b339cbb6  cpsr 60000830
 backtrace:
     #00 pc 00024bb6  /data/app/com.example.qweqwe2-1/lib/arm/libgltfio-jni.so

Early i try v-1.4.5 and get that on the same code: 
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memmove4" referenced by "/data/app/com.example.qweqwe2-2/lib/arm/libfilament-utils-jni.so"

Сan anyone explain what I'm doing wrong

**Comment by prideout** [comment]
Sorry for the trouble, we're looking into it.  This is a dup of #2319.

**Comment by romainguy** [comment]
Closing as duplicate.

**Comment by romainguy** [comment]
@arctic4x What version of Android are you seeing the crash on btw?

**Comment by romainguy** [comment]
Actually @prideout this looks like a different problem. `__aeabi_memmove4` is missing because the ABI for it changed in API 21.

@arctic4x Did you build the libraries yourself or are you using the ones we provide already compiled?

**Comment by romainguy** [comment]
See https://github.com/android/ndk/issues/126 for more info.

**Comment by arctic4x** [comment]
> Actually @prideout this looks like a different problem. `__aeabi_memmove4` is missing because the ABI for it changed in API 21.
> 
> @arctic4x Did you build the libraries yourself or are you using the ones we provide already compiled?

I implement libs in gradle dependencies, Should i build filament anyway?

**Comment by arctic4x** [comment]
> @arctic4x What version of Android are you seeing the crash on btw?

version - 24
device - xiomi mi4w

**Comment by romainguy** [comment]
Thanks, we'll look into this.

**Comment by romainguy** [comment]
Could you please show me your Gradle file? I've been looking at this error with the NDK folks and the only thing we can think of is an issue with the device. The symbol has always been present.

**Comment by romainguy** [comment]
We double checked and at this point it does look like an issue with your device. Would you be able to run `readelf` on your device's `libc`? We'd like to check if the symbol is missing.

**Comment by prideout** [comment]
From what @arctic4x said in the #2337 description, it sounds like we can close this particular issue?

**Comment by romainguy** [comment]
Seems like it.
