### ISSUE TITLE
Update to latest SDL 2.0.12

### ISSUE THREAD

**Issue by amerkoleci** [google/filament#2321]
**Is your feature request related to a problem? Just to keep dependencies up to date

**Describe the solution you'd like**
Just update 

**Describe alternatives you've considered**
Remain as it is 

**OS and backend**
Windows, linux and osx

**Comment by romainguy** [comment]
Is there any reason why we should update? We use only SDL2 for our test apps (and we'd like to move to GLFW) and unless there are issues that an update would fix I'd rather we didn't (just in case we do create problems).

**Comment by amerkoleci** [comment]
No reason, i like the idea to move to glfw, we can close it then.

Thanks
