### ISSUE TITLE
Light Effect error ( opengl,win10 )

### ISSUE THREAD

**Issue by BillyUSA** [google/filament#2327]
Material_sandbox app render sphere model with tangent data, the effect looks error.
Image A lit by directional ight,
Image B lit by spot light.

![图片](https://user-images.githubusercontent.com/11308319/78231800-f1c92900-7505-11ea-9421-05d4de0e99e0.png)

**Comment by romainguy** [comment]
Could you please give more details about this? What model are you using? Here's what directional and spot lights look like with `assets/model/sphere/sphere.obj`.
<img width="394" alt="Screen Shot 2020-04-02 at 8 33 55 AM" src="https://user-images.githubusercontent.com/869684/78268373-f6b5ba80-74bc-11ea-8949-d8e772880ee3.png">
<img width="258" alt="Screen Shot 2020-04-02 at 8 35 30 AM" src="https://user-images.githubusercontent.com/869684/78268381-f9b0ab00-74bc-11ea-9ec5-d02ee35d85eb.png">

**Comment by BillyUSA** [comment]
I use this model :
[EARTHMAP.zip](https://github.com/google/filament/files/4424416/EARTHMAP.zip)

**Comment by romainguy** [comment]
<img width="1136" alt="Screen Shot 2020-04-02 at 6 19 22 PM" src="https://user-images.githubusercontent.com/869684/78314356-9d767700-750e-11ea-8310-692aa517ffa3.png">

Looks fine to me when I convert it to .obj. Seems like an issue with your conversion?

**Comment by BillyUSA** [comment]
i use assimp to direct load the model into Material_sandbox
