### ISSUE TITLE
How to pass attribute parameters to filamat?

### ISSUE THREAD

**Issue by jakkypan** [google/filament#2335]
![image](https://user-images.githubusercontent.com/15864446/78342644-299aa400-75cc-11ea-9b94-8f7766516aff.png)

![image](https://user-images.githubusercontent.com/15864446/78343903-1e487800-75ce-11ea-9e1d-b97fdc1e98e5.png)

I have 2 attribute parameters in filamat, how to  pass attribute parameters form cpp to shader？？can you give me an code episode？

**Comment by romainguy** [comment]
Attributes like position and texture coordinates are already declared for you in the shaders. You should not declare them yourself. Custom attributes can declared using the `variables` material block (see documentation).

Setting attributes on the CPU side is done on the `VertexBuffer::Builder` class. Here is an example:

```
    VertexBuffer::Builder vbb;
    vbb.vertexCount(header->vertexCount)
            .bufferCount(1)
            .normalized(VertexAttribute::COLOR)
            .normalized(VertexAttribute::TANGENTS)
            .attribute(VertexAttribute::POSITION, 0, VertexBuffer::AttributeType::HALF4,
                        header->offsetPosition, uint8_t(header->stridePosition))
            .attribute(VertexAttribute::TANGENTS, 0, VertexBuffer::AttributeType::SHORT4,
                        header->offsetTangents, uint8_t(header->strideTangents))
            .attribute(VertexAttribute::COLOR, 0, VertexBuffer::AttributeType::UBYTE4,
                        header->offsetColor, uint8_t(header->strideColor))
            .attribute(VertexAttribute::UV0, 0, VertexBuffer::AttributeType::HALF2,
                        header->offsetUV0, uint8_t(header->strideUV0))
            .normalized(VertexAttribute::UV0, header->flags & TEXCOORD_SNORM16);
```
