### ISSUE TITLE
Support for Android RGB565 bitmaps

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2336]
Is it possible to load a Bitmap as RGB565 and send it through to Filament using _TextureHelper.setBitmap_ so that it ends up as GL_RGB565 texture type?

I'm trying to find a more memory efficient way to store uncompressed opaque textures than RGBA8.

**Comment by romainguy** [comment]
`TextureHelper` already supports RGB565. `4444` and `HARDWARE` are not supported however (and won't be). I would however recommend using compressed textures over 565.

**Comment by rawnsley** [comment]
@romainguy I'm struggling to get this working in the samples. For example in sample-textured-object, Filament crashes if I add this line to [TextureLoader.loadTexture](https://github.com/google/filament/blob/master/android/filament-utils-android/src/main/java/com/google/android/filament/utils/TextureLoader.kt#L41):

`options.inPreferredConfig = Bitmap.Config.RGB_565
`

I assumed this was because there's a mismatch between the raw bytes from the imported Bitmap and the internal format of the Filament Texture, but it still crashes if I specify the format explicitly like this:

```
val texture = Texture.Builder()
    ...
    .format(Texture.InternalFormat.RGB565)
    ...
    .build(engine)
```

I take your point about preferring compressed textures over 565 format, but in my case I'm loading 3rd-party GLTF files where the texture sources are JPEG so loading into a reduced color space is a quick-and-dirty way to claw back some memory.

**Comment by romainguy** [comment]
Looking into the crash…

**Comment by romainguy** [comment]
I have a fix coming.
