### ISSUE TITLE
Black surfaceview on android

### ISSUE THREAD

**Issue by arctic4x** [google/filament#2337]
Previously, i wrote an issue https://github.com/google/filament/issues/2320 and stuck with some problems.
After release 1.5.2 it doesnt crash, but still doesnt display anything on my device. There was only black screen on surfaceview and nothing else. Tried this on some another devices (Samsung s10, android 9 and meizu u10, android 6) and it works fine.
Do you know what's the problem? and how to fix it?

Device: Xiaomi mi4w, android version 6.0.1

**Comment by romainguy** [comment]
Do you have more information about the GPU in that device? Could you also provide the logcat logs when you start your app?

**Comment by arctic4x** [comment]
Here is logs:

04-03 22:32:37.124 26340-26340/? I/art: Late-enabling -Xcheck:jni
04-03 22:32:37.210 26340-26340/com.example.qweqwe2 I/Filament: Filament library loaded.
04-03 22:32:37.254 26340-26340/com.example.qweqwe2 D/AccessibilityManager: current package=com.example.qweqwe2, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
04-03 22:32:37.270 26340-26359/com.example.qweqwe2 D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-03 22:32:37.302 26340-26359/com.example.qweqwe2 I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013_msm8974_refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013__release_AU (I48a9d37399)
    OpenGL ES Shader Compiler Version: E031.29.00.00
    Build Date: 11/17/16 Thu
    Local Branch: 
    Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013
    Local Patches: NONE
    Reconstruct Branch: NOTHING
04-03 22:32:37.311 26340-26359/com.example.qweqwe2 I/OpenGLRenderer: Initialized EGL, version 1.4

And i think that  gpu - adreno 330, if i correctly understrand what u want

**Comment by romainguy** [comment]
Anything after `OpenGLRenderer: Initialized EGL, version 1.4`? I'm interested in checking whether there are driver errors during rendering. You could also — if you can — make a debug build of Filament which will trigger extra checks after every GL call.

If it's an Adreno 330 I would expect driver bugs to get in our way, especially in shader compilation :/

**Comment by arctic4x** [comment]
no, its no any logs after( 
only system logs, not related to app

So, can i somehow use yout gltf loader and draw 3d model by myself?

**Comment by prideout** [comment]
gltfio can only be used Filament, not other renderers.

@arctic4x, to better diagnose the issue, I'd like to send you a debug build in the form of an `aar`, if you're willing to give it a try.  It would tell us more in the logs.  Are you willing to give it a try?  (I'm not sure which version of Filament I would build, I'd probably just build the current top-of-tree.)

By the way, when you try to run our Android samples directly (e.g. sample-hello-triangle), do they work?  If so, do they *all* work?

**Comment by prideout** [comment]
I've attached a zip with 5 debug build aar files (core filament + its 4 utility libs), you should be able to use the latest release of Filament, then swap out the aar files for filament (and for its utility  libraries if you're using any)

[Archive_72056ee9.zip](https://github.com/google/filament/files/4441362/Archive_72056ee9.zip)
```
 4.7M filament-android-debug.aar
 317K filament-utils-android-debug.aar
 317K filament-utils-android-lite-debug.aar
 3.6M gltfio-android-debug.aar
 1.0M gltfio-android-lite-debug.aar
```

**Comment by arctic4x** [comment]
now logs look like this: 

04-07 15:11:37.621 11811-11811/? I/art: Late-enabling -Xcheck:jni
04-07 15:11:37.722 11811-11811/com.example.qweqwe2 I/Filament: Filament library loaded.
04-07 15:11:37.791 11811-11811/com.example.qweqwe2 D/AccessibilityManager: current package=com.example.qweqwe2, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
04-07 15:11:37.812 11811-11811/com.example.qweqwe2 I/Filament: FEngine (32 bits) created at 0x9e980000 (threading is enabled)
04-07 15:11:37.814 11811-11857/com.example.qweqwe2 D/Filament: FEngine resolved backend: OpenGL
04-07 15:11:37.815 11811-11857/com.example.qweqwe2 I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013_msm8974_refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013__release_AU (I48a9d37399)
    OpenGL ES Shader Compiler Version: E031.29.00.00
    Build Date: 11/17/16 Thu
    Local Branch: 
    Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013
    Local Patches: NONE
    Reconstruct Branch: NOTHING
04-07 15:11:37.832 11811-11857/com.example.qweqwe2 I/Filament: Qualcomm, Adreno (TM) 330, OpenGL ES 3.0 V@140.0 AU@06.00.01.181.013 (GIT@I48a9d37399), OpenGL ES GLSL ES 3.00
04-07 15:11:37.836 11811-11857/com.example.qweqwe2 I/Filament: OS version: 23
04-07 15:11:39.964 11811-11891/com.example.qweqwe2 D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-07 15:11:39.996 11811-11891/com.example.qweqwe2 I/OpenGLRenderer: Initialized EGL, version 1.4

**Comment by romainguy** [comment]
We need the logs after that, this is just initialization.

**Comment by arctic4x** [comment]
is there any tag by which i can search?
becouse there left only system logs and there are a lot of them

**Comment by prideout** [comment]
You can simply attach the result of "adb bugreport" but to answer your question we interested in the "Filament" tag, especially messages that begin with "OpenGL error" or "OpenGL framebuffer error".

**Comment by romainguy** [comment]
Please try with more recent versions of Filament
