### ISSUE TITLE
SPOT vs FOCUSED_SPOT issue

### ISSUE THREAD

**Issue by prideout** [google/filament#2339]
My former NVIDIA colleague Philippe Rollin sent me some questions, creating a ticket for reference.

Q1:
I might have stumbled on a potential issue in Filament but I am not sure if it is me being dumb or
if it is an actual issue: The SPOT and FOCUSED_SPOT definition and usage seem to be inverted: in the
documentation (https://google.github.io/filament/Filament.html#mjx-eqn-spotLightLuminousPower), the physically correct "spot" takes into account the coneOuterAngle (as it should) to convert from lumen to candela; in Filament's code, this is supposed to be SPOT. However, the conversion from lumen to candela used by SPOT seem to be the one that is decoupled from the cone angle. FOCUSED_SPOT uses the correct one (but is documented as being decoupled).

Q2:
Another thing I spotted is that LightManager::setSpotLightCone might be halving the cosOuterAngle by mistake when converting from lumen to candela. CosOuterAngle is already the half angle (at least it is supposed to be when coming from gltf's KHR_lights_punctual).

**Comment by romainguy** [comment]
`LightManager` expects the full angle, so if glTF already provides the half angle we need glTF code to undo that before calling `LightManager`.

**Comment by romainguy** [comment]
The implementation of focused spot and spot seems correct to me. Focused spot is the physically correct one, spot is the non-physically correct one. It seems the only issue is right here in the doxygen comments:

```
        FOCUSED_SPOT,   //!< Spot light with coupling of outer cone and illumination disabled.
        SPOT,           //!< Physically correct spot light.
```

They should be inverted. I'll correct them.

**Comment by romainguy** [comment]
@bejado @prideout Can you double check our implementation of KHR_punctual_lights to make sure we don't use the quarter angle?

**Comment by romainguy** [comment]
Documentation fix: https://github.com/google/filament/commit/17dd44fd917c285dc79a5ec659cabd219d53cc40

**Comment by bejado** [comment]
Yeah, I think we need to convert from gLTF's half angles to full angles for `LightManager`. I'll make the change.

**Comment by romainguy** [comment]
Does glTF give angle or cos angles?

**Comment by bejado** [comment]
Plain angles: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual#spot

**Comment by prideout** [comment]
Fixed by #2340

**Comment by prollin** [comment]
Another related issue:
When loading a gltf spot light, filament seems to default to the SPOT type; shouldn't it be FOCUSED_SPOT since gltf lights are expressed in candela?

**Comment by romainguy** [comment]
glTF lights are FOCUSED_SPOTs indeed.

**Comment by romainguy** [comment]
@bejado can you fix this please?

**Comment by bejado** [comment]
I chose a `SPOT` light to make the math simpler. Inside `LightManager.cpp`:

```
            case Type::SPOT:
                // li = lp / pi
                luminousIntensity = luminousPower * float(F_1_PI);
                break;
```

In `AssetLoader.cpp` I multiply by Pi to cancel it out so we can effectively set `luminousIntensity` directly.
```
        builder.intensity(F_PI * light->intensity);
```

What we should _really_ do is add a builder method that allows setting the luminous intensity directly in candelas, then we don't have to do any conversions.

**Comment by romainguy** [comment]
Sounds good to me. We would probably need an equivalent setter on light instances too.

**Comment by romainguy** [comment]
We're switching the API to use half angles for consistency: https://github.com/google/filament/pull/2399

**Comment by pixelflinger** [comment]
Looking more at the code, it looks like we were expecting half angles in the shader and full angles in the calculation of the intensity for the focused spot light.

I have uploaded a fix that standardize on half-angles.

**Comment by romainguy** [comment]
Is there anything left to do on this?

**Comment by prideout** [comment]
I'm good.

**Comment by romainguy** [comment]
Looks like the only thing left is setting the light intensity correctly. `gltfio` now uses `FOCUSED_SPOT` as expected but the intensity is set as if for a `SPOT`.

**Comment by romainguy** [comment]
`gltfio` now passes the intensity in candelas as expected by the glTF spec.
