### ISSUE TITLE
Stop overriding VK_ICD_FILENAMES on macOS

### ISSUE THREAD

**Issue by kvark** [google/filament#2343]
**Describe the bug**
```
    const Path dylibPath = executableFolder.concat(VKLIBRARY_PATH);
    const Path jsonPath = executableFolder.concat("MoltenVK_icd.json");
    setenv("VK_ICD_FILENAMES", jsonPath.c_str(), 1);
```

**To Reproduce**
  1. set `VK_ICD_FILENAMES` to something
  2. Run on macOS

**Expected behavior**
Vulkan Loader interface is respected, and the user-chosen ICD is loaded.

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Backend: Vulkan

**Additional context**
Running with [gfx-portability](https://github.com/gfx-rs/portability).

**Comment by romainguy** [comment]
Thanks for the report. Seems like we should just test whether `VK_ICD_FILENAMES` is set and pointing to a seemingly correct file.
