### ISSUE TITLE
how to pass attribute parameters to shader？

### ISSUE THREAD

**Issue by jakkypan** [google/filament#2355]
![image](https://user-images.githubusercontent.com/15864446/78652809-cc1c9500-78f4-11ea-9132-17c5c970f466.png)

![image](https://user-images.githubusercontent.com/15864446/78652847-db034780-78f4-11ea-882e-97e975d4c383.png)

![image](https://user-images.githubusercontent.com/15864446/78652912-f2423500-78f4-11ea-8deb-f1dd3a18ca93.png)

I want to pass 2 attribute parameters to shader,  but when i run the code, any thing not changed, i just  want to check is it right of the code? 

----------
![image](https://user-images.githubusercontent.com/15864446/78653213-6381e800-78f5-11ea-80d5-03632654845f.png)

and i get this warning, is it ok?

**Comment by romainguy** [comment]
Normals and positions shouldn't be passed as custom attributes. Use the dedicated attributes for this. Positions in particular is always required. Filament also provided specific attributes for color, UVs (two sets) and bones.

**Comment by jakkypan** [comment]
use the dedicated attributes  **TANGENTS**  as normal？how can i get he value in vertex shader? i cannot found the function in **Filament Materials Guide**

**Comment by romainguy** [comment]
You can use material.worldNormal. It's described in the MaterialInputs section of the documentation. Note that you don't pass just normals to the TANGENTS attribute but a full tangent orthonormal frame (Filament provided helper APIs to build that frame as we expect it to be encoded as a quaternion).

**Comment by jakkypan** [comment]
thank you, then how pass the normal values to **material.worldNormal**？

**Comment by romainguy** [comment]
That value is given to you automatically. You set the attribute TANGENTS and our shader will unpack the normal for you (and transform it etc.)
