### ISSUE TITLE
Multiple views no longer working on Android

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2364]
Rendering multiple views in a single frame hasn't worked for a while. This is [already documented](https://github.com/google/filament/pull/1916), but I wanted to raise it's profile a little and provide an easy reproduce.

It we modify the lit-cube sample to have four views arranged in quadrants ([patch file](https://github.com/google/filament/files/4451048/patch.diff.zip)) we get:

![before](https://user-images.githubusercontent.com/303516/78796606-73113780-79ae-11ea-9d52-fe217610c551.png)

before [this change](https://github.com/google/filament/pull/1916/commits/7d0f2fff343f2e1aca18cee47f12a9cbbab4619b). After the change we get the following output:

![after](https://user-images.githubusercontent.com/303516/78797203-4b6e9f00-79af-11ea-88c5-748ae026a0ab.png)

I appreciate that multiple views is a minority use case, but it might be worth having at least one sample that demonstrates it to avoid retros.

**Comment by romainguy** [comment]
Have you tried wit the latest version of Filament. There were several fixes related to multi-view rendering recently.

**Comment by romainguy** [comment]
@pixelflinger Looks like with the patch linked above we always invalidate a framebuffer if we use several times (for several views). It used to work I believe because of the test `currentFbo != newFbo`.

**Comment by rawnsley** [comment]
@romainguy Yes - this is straight from today's master branch at [68a78a77](https://github.com/google/filament/commit/68a78a77a85f2fbe5dce4d9c5fbe859ca6fd014f).

**Comment by pixelflinger** [comment]
@rawnsley are you setting the discard flags on the supplemental views? i.e. like this:

`view.setRenderTarget(TargetBufferFlags::NONE);`

You need to do that for all views, except the first one.

**Comment by rawnsley** [comment]
@pixelflinger Is this possible through the JNI interface?

**Comment by romainguy** [comment]
Looks like the Java API is missing the TargetBufferFlags parameter and overload.

**Comment by romainguy** [comment]
We should also add a sample app to explain this behavior.

**Comment by romainguy** [comment]
I just checked in the missing API and a sample app.

Note it does *not* fix the issue entirely. You have to disable color clears after the 1st view and the only way to show a background is to use a skybox of equivalent. I'm going to file a new bug so we can fix how clear/clear color works in multi view mode.

**Comment by rawnsley** [comment]
Can confirm fixed for me. Thank you so much!
