### ISSUE TITLE
headless swapchain/readPixels test doesn't work on windows + gl

### ISSUE THREAD

**Issue by teub** [google/filament#2365]
**Describe the bug**
I compiled a very small program based on filament_rendering_test.cpp to check why readPixels isn't working as expected in my code. The assert fails as the buffer is filled with 0.
I was having the issue with 1.4.* and I can reproduce it with 1.5.2

**To Reproduce**
1. here's the code I compiled and tested in debug: 
edited: created a gist instead because the code formatting didn't seem to work
https://gist.github.com/teub/0b03062c51332d7772572ba02ee42e40

libraries linked:
`
lib/x86_64/mdd/filament.lib
lib/x86_64/mdd/utils.lib
lib/x86_64/mdd/backend.lib
lib/x86_64/mdd/filamat.lib
lib/x86_64/mdd/filaflat.lib
lib/x86_64/mdd/filabridge.lib
lib/x86_64/mdd/geometry.lib
lib/x86_64/mdd/ibl.lib
lib/x86_64/mdd/bluegl.lib
opengl32.lib
`

**Expected behavior**
Asserts should pass, they correspond to the tests in filament_rendering_test.cpp

**Desktop :**
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Comment by romainguy** [comment]
You are calling `readPixels()` too early, you should call it after `endFrame()`. Without the call to `endFrame()` the buffers haven't been swapped so there's nothing for you to read back (if you rendered multiple frames you would probably see something, with a 1 frame latency).

**Comment by teub** [comment]
the code was copied directly from https://github.com/google/filament/blob/master/filament/test/filament_rendering_test.cpp, so there's a bug in this file either way.

I made the change you proposed; now the buffer is no longer filled with 0 but the assert still doesn't pass: instead of being filled with 0, it's filled with 221 (or random things)

**Comment by romainguy** [comment]
@pixelflinger Is that an issue with clear color not working?

**Comment by pixelflinger** [comment]
Actually readPixels() must be called *before* `endFrame()` -- sorry about the misinformation here.

I think it's more likely that headless support is broken for Windows (maybe has never worked?) as headless support is platform specific. Will take a look.

**Comment by romainguy** [comment]
@pixelflinger We call it after `endFrame` in `frame_generator` and it works there :)

**Comment by bejado** [comment]
Windows doesn't have headless Swapchain support: https://github.com/google/filament/blob/master/filament/backend/src/opengl/PlatformWGL.cpp#L186-L187

This has been on my todo list for awhile, I can look into it and see how difficult it'd be to add it.

**Comment by teub** [comment]
I was going to comment on how I worked around the issue on my side, but I've seen you've already implemented the fix!

If I may, I'm not sure leaking a window each time the swapchain is great; can't the window pointer be stored in some userdata?

Another remark : knowing it wasn't implemented in the first place could have saved me a lot of time (with a log or an assert).

Anyway, thanks.

**Comment by romainguy** [comment]
The leak is temporary, we'll fix it.
