### ISSUE TITLE
How to render multi overlay view in same viewport? (Win10 OpenGL )

### ISSUE THREAD

**Issue by BillyUSA** [google/filament#2372]
I want to render two view with differen scene/camera in same viewport ( win32 window ),
if both view without PostProcessing, can see the overlay result, but not smoothed ( no AntiAliasing );
if the last rendered view with PostProcessing(MSAA /FXAA) enabled，the reult is smoothed，but can't see the first view .

How to render multi overlay view with  PostProcessing ( MSAA /FXAA ) Enabled ?

**Comment by romainguy** [comment]
Are the two views side by side or on top of each other?

**Comment by BillyUSA** [comment]
two views are on top of each other

**Comment by romainguy** [comment]
What clear flags and target buffer flags do you use?

@pixelflinger

**Comment by BillyUSA** [comment]
view 0 :  setClearTargets(true, true, true)
view 1 :  setClearTargets(false, true, true)

**Comment by romainguy** [comment]
Thanks you could also try to call setRenderTarget(nullptr, View:: TargetBufferFlags::NONE) on the the top view?

**Comment by BillyUSA** [comment]
nothing changed after setRenderTarget(nullptr, View:: TargetBufferFlags::NONE)   on the the top view.

**Comment by romainguy** [comment]
This is fixed by https://github.com/google/filament/pull/2376. See the PR description to understand what APIs to use.

**Comment by BillyUSA** [comment]
#2376 when setPostProcessingEnabled(true) and BlendMode with TRANSLUCENT , the 2nd view cover and erase the 1st view .
Is there example about  one view  drawn on top of another ?

**Comment by romainguy** [comment]
How do you setup the background of the top view? @pixelflinger
