### ISSUE TITLE
how to use vulkan android? 

### ISSUE THREAD

**Issue by jakkypan** [google/filament#2373]
i have revised my local code as this commit [f58b3a8](https://github.com/google/filament/commit/f58b3a867b080734acd213595890b029412ee891)

but when i build using the command **./build.sh -vcp android debug**, it failed, as below,
![image](https://user-images.githubusercontent.com/15864446/78891565-666a0d80-7a9a-11ea-8ef2-a4b694ca7854.png)

so whether vulkan backend is accomplished?

**Comment by romainguy** [comment]
I just committed a small fix to our CMake files that was creating issues when building Vulkan for Android and some versions of CMake. What version of Filament are you using? The August 2019 commit you're pointing to is quite old at this point and I would recommend you try with the latest master. Vulkan should work, it definitely compiles.

**Comment by romainguy** [comment]
I just did 2 clean builds of Vulkan for Android, in debug and release, and they both succeeded.

**Comment by jakkypan** [comment]
i am using the filament 1.5.0

![image](https://user-images.githubusercontent.com/15864446/78955017-80463780-7b10-11ea-9bc4-1a8aeee96958.png)

Doesn't the **FILAMENT_SUPPORTS_VULKAN** need to be turned on?

And does i still use the command **./build.sh -vcp android debug**?

**Comment by romainguy** [comment]
It's turned on by passing -v to build.sh. But our Vulkan back end isn't complete yet. It builds on master.

**Comment by jakkypan** [comment]
ok, and thank you for your persistently reply.
