### ISSUE TITLE
Adsense for Games

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2377]
Filament needs to support Adsense for Games, from a WebGL perspective.

https://support.google.com/adsense/answer/7170212?hl=en

**Comment by romainguy** [comment]
What kind of support would be needed exactly? I imagine AdSense can be presented as part of the HTML document around the WebGL canvas.

**Comment by romainguy** [comment]
Based on the technical FAQ I don't see anything that needs to be done in filament.

**Comment by unicomp21** [comment]
Where is the technical FAQ?  Would be really cool if we could have meshes textured w/ ads which can be clicked on while still complying w/ the rules for Adsense.
