### ISSUE TITLE
Heightfield example and custom GPU code

### ISSUE THREAD

**Issue by teub** [google/filament#2378]
**Is your feature request related to a problem? Please describe.**

I've seen there was a heightfield example and I was hoping it would generate geometry based on a texture; however it looks like the geometry is generated on the CPU side. Is there any way of using filament to generate geometry using the GPU?

I'm not really an expert in this but I'm afraid any custom code like this is not possible due to the fact that the backend is not directly accessible in any way, and I've read somewhere this was a design decision.

In the same way, and it's related, it would be convenient to be able to have control over the rendering thread (for GL backend, everything needs to happen on the same thread). I had to fork filament to disable threading and handle it on my side for my VR tests.
Forking filament comes with its own struggles as it's hard to keep up with each new version.

**Describe the solution you'd like**
I wish there was a way to access native objects, and to have ways of writing custom native code for the backend.

**Describe alternatives you've considered**
Filament could also propose its own wrappers for geometry or compute shaders, but I suppose this would be a lot more work.

**Comment by romainguy** [comment]
We are not giving access to the backend or backend customizations on purpose. We definitely do not want to give the app any access to the render thread. There are several reasons for this but it's mostly about maintainability and stability (and also flexibility, with the current design for instance we could abandon OpenGL entirely in favor of Vulkan and apps wouldn't be affected).

Computer shaders are definitely something we want to support but it's not a priority at the moment. Support is made difficult by WebGL and OpenGL ES 3.0.
