### ISSUE TITLE
potential double-free in gltfio

### ISSUE THREAD

**Issue by iamlkj** [google/filament#2379]
**Describe the bug**
In AssetLoader there's a example for model loading flow:
/*
 * ...
 * FilamentAsset* asset = loader->createAssetFromJson(content.data(), content.size());
 * ...
 * // Load buffers and textures from disk.
 * ResourceLoader({engine, ".", true}).loadResources(asset);
 * ....
 * // Free the glTF hierarchy as it is no longer needed.
 * asset->releaseSourceData();
 * .... add to scene and start the loop ....
 *
 *
 * loader->destroyAsset(asset);
 * materials->destroyMaterials();
 * delete materials;
 * AssetLoader::destroy(&loader);
 * Engine::destroy(&engine);
*/

It'll crash if not doing `asset->releaseSourceData()` after loadResources.

**Error code**
 `malloc: *** error for object 0x128d30078: pointer being freed was not allocated`
It'll crash when engine destroy. It crash at Engine.cpp::340: getDriver()->purged();

**Expected behavior**
I track down the code, I think it's because the `mResourceCount` not decrease to 0 inside FilamentAsset if not call `releaseSourceData()` for loadResources. 
But the question is, it should cause memoryleak since the data did not delete (or delete at engine shoudown) rather than the error I received, which is delete twice.

Is there any memory double deletion bug here?

**Desktop (please complete the following information):**
 - OS: Mac
 - GPU: Intel onChip 
 - Backend: OpenGL

**Comment by prideout** [comment]
I am not able to reproduce this, can you attach a zip with your C++ code?  Also, I don't see `mResourceCount` in our current codebase.

**Comment by prideout** [comment]
Closing due to lack of a repro, I tried removing the releaseSourceData and enabling asan.  We may have fixed this in a recent refactor.  Please re-open if you have repro steps.
