### ISSUE TITLE
Support LunarG SDK on macOS

### ISSUE THREAD

**Issue by kvark** [google/filament#238]
**Is your feature request related to a problem? Please describe.**
The current implementation is bundled with libMoltenVK.dylib, and the ICD json path is hardcoded:
```cpp
const Path jsonPath = executableFolder.concat("MoltenVK_icd.json");
setenv("VK_ICD_FILENAMES", jsonPath.c_str(), 1);
```
This prevents easy use of the library with either SDK-provided build of MoltenVK or [gfx-portability](https://github.com/gfx-rs/portability). We got the necessary patches in https://github.com/gfx-rs/gfx/pull/2401 and the next packaged build will support Filament.

**Describe the solution you'd like**
Detect the LunarG SDK on the target machine in the build scripts, load `libvulkan.1.dylib` from there and let the SDK handle the rest (e.g. `VK_ICD_FILENAMES`). If the SDK is not found, resort to the bundled `libvulkan.1.dylib`. The actual loading code should only modify `VK_ICD_FILENAMES` if it's not set.

**Describe alternatives you've considered**
The loading code could also just append the bundled ICD JSON to the end of `VK_ICD_FILENAMES` list.

**OS and backend**
This is macOS/iOS (Darwin) specific.

**Comment by prideout** [comment]
Seems like a good idea.  For detecting the SDK I guess we could just check if `VK_ICD_FILENAMES` already exists.

**Comment by prideout** [comment]
Actually I think we try to implement your first proposed solution, which is to detect `VULKAN_SDK` at build time, and it's not there, then fall back to the current strategy.  The detection code could sort of look like this:

    https://github.com/SaschaWillems/Vulkan/blob/master/CMakeLists.txt#L22-L45

We do want to keep our current loading strategy as a fallback though, so that we don't force all devs to install the LunarG SDK.

**Comment by prideout** [comment]
Hi @kvark, hopefully PR #240 will do what you need.  Is `gfx-rs` using Filament for testing purposes?  We don't know much about that project, it looks interesting!

**Comment by kvark** [comment]
@prideout thank you!

gfx-portability hasn't made as much noise as the alternative, but we've got some [interesting](https://gfx-rs.github.io/2018/08/10/dota2-macos-performance.html) [results](https://gfx-rs.github.io/2018/09/03/rpcs3-dolphin.html). We are trying to make sure all the existing (various samples, vkQuake, Dota2) and future (RPCS3, Dolphin, wine) applications to work efficiently with our library. See https://github.com/gfx-rs/portability/issues/125 for the full list.

**Comment by prideout** [comment]
I've been wanting to learn Rust, this looks super interesting.  Good luck!
