### ISSUE TITLE
filament outputs to stdout even when not being used

### ISSUE THREAD

**Issue by teub** [google/filament#2383]
**Describe the bug**
I'm writing a command line tool to output xml to stdout. It uses a dll that statically links to filament, and even when not using the filament engine, it writes stuff to stdout: "Filament library loaded.", which is a problem if stdout is to be used for something.

**To Reproduce**
Statically link filament to an empty program, run said program.

**Expected behavior**
Nothing should be written to stdout if nothing is being done, IMO.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by romainguy** [comment]
Thanks for the report, we should definitely fix that indeed.

**Comment by romainguy** [comment]
@pixelflinger Do you have any objection against putting this log behind a debug flag?

**Comment by romainguy** [comment]
Fix is here: #2391
