### ISSUE TITLE
FEngine (32 bits) created at 0x595690 (threading is disabled)

### ISSUE THREAD

**Issue by Huai-Dc** [google/filament#2384]
**Describe the bug**
The web demo will report this problem when run

**Screenshots**
![image](https://user-images.githubusercontent.com/19547344/79089333-5f801b00-7d78-11ea-9fe3-336ae9db8eca.png)

**Comment by romainguy** [comment]
Are you reporting a specific issue? This is just a message we use for debugging purposes. Threading is indeed disabled with WebGL because we have to (at this time).
