### ISSUE TITLE
Hwo to change shadow density ?

### ISSUE THREAD

**Issue by BillyUSA** [google/filament#2385]
default shadow is too dark, can i change the shadow density ?

default shadow edge is so hard, can it be changed soft ?

**Comment by romainguy** [comment]
You can't control the shadow "density". Something is in shadow or is not. You can however adjust the intensity of your IBL (IndirectLight) if you want the shadow to appear lighter.

Our shadows are already softened. We'll probably add support for ESM/VSM and capsule shadows in the future to get softer shadows.
