### ISSUE TITLE
Mobile + WebGL exhibits some shader issues.

### ISSUE THREAD

**Issue by prideout** [google/filament#241]
Low roughness values causes strange rendering on my Pixel 2, it looks similar to the screenshot reported by Eric:

https://twitter.com/RaptorDeVitesse/status/1040050253548777473

**Comment by prideout** [comment]
Hm, the term computed by `D_GGX_Anisotropic` is what's blowing up here.

Anisotropy is zero but the code path is enabled because it uses the existing sandboxLit material.

**Comment by prideout** [comment]
Small values of `at` and `ab` (e.g. when they hover between MIN_LINEAR_ROUGHNESS and 0.1) cause the aforementioned term to blow up on WebGL Mobile.

**Comment by romainguy** [comment]
I'll try on Android see what happens. It's surprising this computation wouldn't work, I've implemented it in WebGL directly before and successfully.
