### ISSUE TITLE
mipgen corrupts certain png files

### ISSUE THREAD

**Issue by EvilTrev** [google/filament#2417]
**Describe the bug**
I have one or two png files that mipgen seems to corrupt. I've done the most basic of tests with only writing out the png that has been read in as a series of png files, and each mip png output is corrupt.

**To Reproduce**
./mipgen SpiritAtlas.png test%2d.png
Assuming GitHub doesn't transcode or tamper with the files, they are attached here:
![SpiritAtlas](https://user-images.githubusercontent.com/2244257/79623478-5cb35c00-80d1-11ea-8e46-6415f496454c.png)
![test 1](https://user-images.githubusercontent.com/2244257/79623480-61781000-80d1-11ea-9b91-d5f47ebadf34.png)

**Screenshots**
<img width="1106" alt="Screen Shot 2020-04-17 at 5 24 53 PM" src="https://user-images.githubusercontent.com/2244257/79623352-a64f7700-80d0-11ea-849c-1eb2d1a45622.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3

**Comment by romainguy** [comment]
I can reproduce the issue with the supplied file. It does not happen with other files however. I'm not sure what the issue is: the source PNG is 8 bit and doesn't have a color profile.

**Comment by romainguy** [comment]
I found what's different about this image: it's palette based. Here's the output of `identify -verbose`:

```
  Properties:
    date:create: 2020-04-18T00:40:01+00:00
    date:modify: 2020-04-18T00:39:59+00:00
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 3
    png:IHDR.color_type: 3 (Indexed)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 512, 512
    png:PLTE.number_colors: 256
    png:sRGB: intent=0 (Perceptual Intent)
    png:text: 1 tEXt/zTXt/iTXt chunks were found
    png:tRNS: chunk was found
    signature: 20b229536e74f15749263c76b656f706ab8960310b1b9e12dca90f0464d2d100
    Software: Adobe ImageReady
```

@EvilTrev It should work if you save the PNG as a regular 24 bit image instead. We'll check but I am not sure the decoder we use even supports paletted PNG files.

**Comment by EvilTrev** [comment]
@romainguy Thank you for the quick turn around, I can take a look at the decoder as well to see if there is an obvious issue here. In the mean time, I will need to stub in an error on palletized files... often the pngs are outside my control.

**Comment by romainguy** [comment]
We use `libpng` so hopefully the bug is on our side. It could just be that our `libimage` (which itself uses `libpng`) wasn't written with this use case in mind. I know it supports grayscale PNGs but I never tested with palettes.

**Comment by EvilTrev** [comment]
The pattern looks like a stride issue to me, so I'm expecting a step size to be incorrect somewhere.

**Comment by romainguy** [comment]
The PNG decoding code lives here: https://github.com/google/filament/blob/master/libs/imageio/src/ImageDecoder.cpp#L235

**Comment by EvilTrev** [comment]
cheers!

**Comment by EvilTrev** [comment]
@romainguy Fix is pretty simple, looks to be a logic bug introduced by not updating colorType after Libpng is done transforming the source material. Which means after the data is read into a buffer, the colorType is still PNG_COLOR_TYPE_PALETTE and not PNG_COLOR_TYPE_RGBA. The fix is to add this after png_read_update_info:

**Comment by EvilTrev** [comment]
@romainguy Additionally, some of this code may be useful or worth looking at because I think there may be other uncaught edge cases like GRAY_ALPHA and 1/2/4 bit grays:

```
        int colorType = png_get_color_type(mPNG, mInfo);
        int bitDepth = png_get_bit_depth(mPNG, mInfo);

        if (colorType == PNG_COLOR_TYPE_PALETTE) {
            png_set_palette_to_rgb(mPNG);
        }
        if (colorType == PNG_COLOR_TYPE_GRAY || colorType == PNG_COLOR_TYPE_GRAY_ALPHA) {
			if (bitDepth < 8) {
				png_set_expand_gray_1_2_4_to_8(mPNG);
			}
            png_set_gray_to_rgb(mPNG);
        }
		if (png_get_valid(mPNG, mInfo, PNG_INFO_tRNS)) {
			png_set_tRNS_to_alpha(mPNG);
		}
        if (getColorSpace() == ImageDecoder::ColorSpace::SRGB) {
            png_set_alpha_mode(mPNG, PNG_ALPHA_PNG, PNG_DEFAULT_sRGB);
        } else {
            png_set_alpha_mode(mPNG, PNG_ALPHA_PNG, PNG_GAMMA_LINEAR);
        }
        if (bitDepth < 16) {
            png_set_expand_16(mPNG);
        }
```

**Comment by romainguy** [comment]
Good catch about needing to call `png_get_color_type` again! Your proposed fix for `GRAY_ALPHA` would also address another bug that was filed a while back. I'll try your suggestions asap!
