### ISSUE TITLE
The GLTF transparency is not rendered correctly in Filament (Sceneform 1.16.0)

### ISSUE THREAD

**Issue by House3D** [google/filament#2424]
**Describe the bug**
The GLB transparency is correctly rendered in some 3D viewers like Microsoft Windows 3D Viewer or Three.js GLTF viewer (https://gltf-viewer.donmccurdy.com/), but not correctly rendered in Fillament

**To Reproduce**
1. Use the sceneform sample from Sceneform Android SDK 1.16.0:
https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/gltf
3. Test with the _diamond.glb_ file that exported from _diamond.blend_ Blender file
**Expected behavior**
The transparency is displayed
**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/33864295/79735562-aa72d300-8322-11ea-962a-dc6b5c9e98e9.png)

Actual:
![image](https://user-images.githubusercontent.com/33864295/79735419-75ff1700-8322-11ea-9128-13eb30c5c35c.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10.0

**Attached the GLB and original Blender file:**
[diamond.zip](https://github.com/google/filament/files/4502443/diamond.zip)

**Comment by romainguy** [comment]
The glTF file is loaded properly. It is marked transparent as it should be but the alpha value is 1 (fully opaque). The first screenshot at the top doesn't show transparency but just reflections. They also appear with Sceneform/Filament,  just less obvious because it's a different IBL.

**Comment by House3D** [comment]
No, it both has transparency and reflection
In the Thress.js player:
![image](https://user-images.githubusercontent.com/33864295/79837446-9dfe8100-83db-11ea-8467-f0fcf930bfe9.png)

In windows 3D Viewer:
![image](https://user-images.githubusercontent.com/33864295/79837535-c9816b80-83db-11ea-9ac5-4c8441ecc01e.png)

Can you open the GLB and check?

**Comment by romainguy** [comment]
I did and its baseColorFactor is 1,1,1,1 or opaque white.

**Comment by romainguy** [comment]
Note that I also tried exporting from Blender into a new gltf file and I got the same result. The alpha value of the principled bsdf is set to 1 in Blender so that may be the reason?

**Comment by romainguy** [comment]
I also checked, there's no extension used in the glb file. No transparency shows up in https://gltf-viewer.donmccurdy.com/ either:

<img width="1017" alt="Screen Shot 2020-04-21 at 9 24 45 AM" src="https://user-images.githubusercontent.com/869684/79888747-f4ef6080-83b1-11ea-9cac-f5060e9e87cd.png">

If I change the baseColor's alpha channel in Blender to a value less than 1 then the object shows up with transparency as expected in Filament and other viewers.

**Comment by House3D** [comment]
OK thank you @romainguy

**Comment by MatHeartGaming** [comment]
Hi guys! I'm experiencing some issues using sceneform-ux:1.12.0 with sceneform:assets:1.15.0 regarding the loading of models via web. The issue I'm referring to is the transparency. So, I applied the alpha using Blender as suggested, but when loading it into the app it isn't as tranparent as I'd like since it seems sceneform is applying to it a sort of white color I don't really want. I'm attaching the settings I'm using in Blender and the code snippet used to load it.

![WhatsApp Image 2020-11-19 at 12 37 11](https://user-images.githubusercontent.com/25991137/99662510-a4360800-2a65-11eb-9494-a1df4f288cdb.jpeg)

This is the material I'm using, which as you can see it should be transparent without any white color. My base color values are R: 1, G: 1, B: 1, A: 0.05.

![Settings blender](https://user-images.githubusercontent.com/25991137/99662712-eb23fd80-2a65-11eb-8405-749b4d6c2912.jpeg)

This is the code snippet I'm using:

![Captura de pantalla 2020-11-19 125313](https://user-images.githubusercontent.com/25991137/99662943-35a57a00-2a66-11eb-9f27-749fd0c6d654.png)

Thanks in advance for any help!

**Comment by romainguy** [comment]
Your asset is white in Blender, depending on your lighting environment what you are seeing is perfectly normal. Try with black instead.

**Comment by MatHeartGaming** [comment]
Hi, now I'm experiencing another problem. The issue on hand is that I'm trying to map textures on a transparent material in Blender but what I actually get is an opaque texture. This is the texture I'm using: https://www.spaarkly.it/models/carreraGlasses/texture/lenti_BaseColor.png

and these are the screenshots I took in Blender:
![photo_2020-12-10_12-09-25](https://user-images.githubusercontent.com/25991137/101764937-f0aeb980-3ae0-11eb-91b9-262abb6b8c8d.jpg)

![photo_2020-12-10_12-11-21](https://user-images.githubusercontent.com/25991137/101764960-f60c0400-3ae0-11eb-8555-417100160c3e.jpg)


So, what I'm wondering is: in case I want to apply a transparent texture what's the correct approach?

**Comment by romainguy** [comment]
You have to connect the alpha channel of your texture to the Alpha input of the Principled BSDF in Blender.

**Comment by Michele-Telesca** [comment]
Hi @romainguy  .
i am a little confused on this topic. I'm trying to import into sceneform assets at runtime. I created a fake object that I overwrite in runtime with the desired gltf. textures are also loaded in runtime respectively: baseColorMap, normalMap, metallicMap, roughnessMap.
this is my pbr_material.mat 

`material {
    name : "Textured material",
    parameters : [
        {
           type : sampler2d,
           name : baseColorMap
        },
        {
            type : sampler2d,
            name : normalMap
        },
        {
            type : sampler2d,
            name : metallicMap
        },
        {
            type : sampler2d,
            name : roughnessMap
        }
    ],
    requires : [
        uv0
    ],
    shadingModel : lit,
    blending : transparent
}

fragment {
    void material(inout MaterialInputs material) {
        vec3 normal = texture(materialParams_normalMap, getUV0()).xyz;
        material.normal = normal * 2.0 - 1.0;

        prepareMaterial(material);

        material.baseColor = texture(materialParams_baseColorMap, getUV0());
        material.metallic = texture(materialParams_metallicMap, getUV0()).r;
        material.roughness = texture(materialParams_roughnessMap, getUV0()).r;
    }
}`

this the custom_material.sfa generated by sceneform

`{
  materials: [
    {
      name: 'Material',
      parameters: [
        {
          baseColorMap: 'DiffuseMap',
        },
        {
          normalMap: 'NormalMap',
        },
        {
          metallicMap: 'MetallicMap',
        },
        {
          roughnessMap: 'RoughnessMap',
        },
        {
            alphaFactor: 0.5,
        },
      ],
      source: 'sampledata/materials/pbr_material.mat',
    },
  ],
  model: {
    attributes: [
      'Position',
      'Orientation',
    ],
    collision: {},
    file: 'sampledata/materials/custom_material.obj',
    name: 'custom_material',
    recenter: 'root',
    scale: 0.5,
  },
  samplers: [
      {
          file:'src/main/res/raw/custom_material_default_diffuse.jpg',
          name: "DiffuseMap",
      },
      {
          file:'src/main/res/raw/custom_material_default_metallic.jpg',
          name: "MetallicMap",
          params: {
              usage_type: 'Data',
          }
      },
      {
          file:'src/main/res/raw/custom_material_default_roughness.jpg',
          name: "RoughnessMap",
          params: {
              usage_type: 'Data',
          }
      },
      {
          file:'src/main/res/raw/custom_material_default_normal.jpg',
          name: "NormalMap",
          params: {
              usage_type: 'Normal',
          }
      },
    ],

  version: '0.52:1',
}
`
I set the model at runtime like this

`  Uri baseColorSource = Uri.parse(TEXTURE_BASE_COLOR);
        Uri metallicSource = Uri.parse(TEXTURE_METAL);
        Uri roughnessSource = Uri.parse(TEXTURE_ROUGHNESS);
        Uri normalSource = Uri.parse(TEXTURE_NORMAL);

        customMaterial = new CustomMaterial(this, baseColorSource, metallicSource, roughnessSource, normalSource);
        this.materialFuture = customMaterial.getBuilder().build();

-----------------------------------------------------------------------------

  renderableFuture = ModelRenderable.builder().setSource(this, RenderableSource.builder()
                .setSource(this, Uri.parse(GLTF_ASSET),
                        RenderableSource.SourceType.GLTF2).setRecenterMode(RenderableSource.RecenterMode.ROOT)
                .build()).build();

        renderableFuture.thenAcceptBoth(materialFuture, (renderableResult, materialResult) -> {
            customMaterial = materialResult;
            renderableModel = renderableResult;
            renderableModel.setMaterial(customMaterial.getValue());
        });`

part of the build of the custom_material class

`
 CompletableFuture<CustomMaterial> build() {
            AndroidPreconditions.checkUiThread();

            CompletableFuture<ModelRenderable> renderableFuture = createMaterialRenderable();
            CompletableFuture<Texture> defaultColorFuture = createTexture(R.raw.custom_material_default_diffuse, Texture.Usage.COLOR);
            CompletableFuture<Texture> defaultMetallicFuture = createTexture(R.raw.custom_material_default_metallic, Texture.Usage.DATA);
            CompletableFuture<Texture> defaultRoughnessFuture = createTexture(R.raw.custom_material_default_roughness, Texture.Usage.DATA);
            CompletableFuture<Texture> defaultNormalFuture = createTexture(R.raw.custom_material_default_normal, Texture.Usage.NORMAL);
            CompletableFuture<Texture> baseColorFuture = createTexture(baseColorSource, Texture.Usage.COLOR);
            CompletableFuture<Texture> metallicFuture = createTexture(metallicSource, Texture.Usage.DATA);
            CompletableFuture<Texture> roughnessFuture = createTexture(roughnessSource, Texture.Usage.DATA);
            CompletableFuture<Texture> normalFuture = createTexture(normalSource, Texture.Usage.NORMAL);

            return CompletableFuture.allOf(
                    renderableFuture,
                    baseColorFuture,
                    metallicFuture,
                    roughnessFuture,
                    normalFuture,
                    defaultColorFuture,
                    defaultMetallicFuture,
                    defaultRoughnessFuture,
                    defaultNormalFuture
            ).thenApplyAsync(aVoid -> {
                CustomMaterial customMaterial = null;
                try {
                    customMaterial = new CustomMaterial(
                            renderableFuture.get().getMaterial(),
                    baseColorFuture.get(),
                            metallicFuture.get(),
                            roughnessFuture.get(),
                            normalFuture.get(),
                            defaultColorFuture.get(),
                            defaultMetallicFuture.get(),
                            defaultRoughnessFuture.get(),
                            defaultNormalFuture.get()
                );
                } catch (Exception ex) {

                }

                return customMaterial;
            });
        }

        private CompletableFuture<ModelRenderable> createMaterialRenderable() {
            return ModelRenderable.builder()
                .setSource(context, R.raw.custom_material)
            .build().exceptionally(new Function<Throwable, ModelRenderable>() {
                @Override
                public ModelRenderable apply(Throwable ex) {
                    Log.e("TAG", "unable to load custom_material renderable", ex);
                    return null;
                }
            });
        }

        private CompletableFuture<Texture> createTexture(Uri sourceUri, Texture.Usage usage){
            return Texture.builder().setSource(context, sourceUri)
                .setUsage(usage)
                .setSampler(
                Texture.Sampler.builder()
                        .setMagFilter(Texture.Sampler.MagFilter.LINEAR)
                        .setMinFilter(Texture.Sampler.MinFilter.LINEAR_MIPMAP_LINEAR)
                        .build()
                ).build().exceptionally(new Function<Throwable, Texture>() {
                    @Override
                    public Texture apply(Throwable ex) {
                        Log.e("TAG", "Unable to load texture from $sourceUri", ex);
                        return null;
                    }
                });
        }

        private CompletableFuture<Texture>  createTexture(int id, Texture.Usage usage) {
                return Texture.builder().setSource(context, id)
                    .setUsage(usage)
                    .setSampler(
                            Texture.Sampler.builder()
                                    .setMagFilter(Texture.Sampler.MagFilter.LINEAR)
                                    .setMinFilter(Texture.Sampler.MinFilter.LINEAR_MIPMAP_LINEAR)
                                    .build()
                    ).build();
        }

    }

}`

I can't understand if the changes have to be made in blender or inside my custom material to load transparent runtime textures. the previous steps work well when I don't need to apply a texture to my object. Could you help us? now I think I'm crazy
