### ISSUE TITLE
dyld: Symbol not found: _OBJC_CLASS_$_MTLSharedEventListener

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#2431]
now only support iOS12+?

**Comment by romainguy** [comment]
Thanks for the report but could you provide more details please? What version of filament are you using and on which device?

**Comment by bejado** [comment]
Filament only officially supports iOS 12.0 and higher. Our continuous and release builds are compiled with `-mios-version-min` set to 12.0.

In the future we might lower support to iOS 11. If you want to experiment with iOS 11, you can change the [build setting](https://github.com/google/filament/blob/master/build.sh#L527) and build yourself. I think there's only one or two places we're relying on iOS 12.0 or newer APIs—everything else (like the `MTLSharedEventListener`) should be wrapped in an `@availability` check.

Note that Filament must always be _built_ against the latest iOS SDK.

**Comment by romainguy** [comment]
@bejado Can you make sure README.md mentions that iOS 12 is the minimum requirement?

**Comment by bejado** [comment]
I have a note in `ios/samples/README.md`, but I'll add one to the main README as well.

**Comment by cjsliuj** [comment]
thanks
