### ISSUE TITLE
Filament incompatible with sanctioned glb models

### ISSUE THREAD

**Issue by tellypresence** [google/filament#2443]
As mentioned [on khronos site](https://github.com/KhronosGroup/glTF-Sample-Models), the kenney models ["tower defense kit"](https://kenney.nl/assets/tower-defense-kit) fail to load due to filament error, e.g. for `towerRound_sampleF.glb`:
```
 E/Filament: Unable to parse glb file.
```
with throwable `CompletionException`:
```
java.lang.IllegalStateException: Failed to load gltf
```

(First raised in https://github.com/google-ar/sceneform-android-sdk/issues/1055)

**Comment by romainguy** [comment]
Thank you. As mentioned in google-ar/sceneform-android-sdk#1055, the asset you mentioned is non-conformant (doesn't follow the glTF specifications).
