### ISSUE TITLE
Forget to export JobSystem.h in the include folder?

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2444]
**Describe the bug**
[Filament 1.5.2 ios] I tried to use engine->getJobSystem().adopt() but received a compiler error which indicates "JobSystem" is an incomplete class. But I can't find "utils/JobSystem.h" in the include folder.

**To Reproduce**
@see Description.

**Expected behavior**
Use JobSystem instance.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
JobSystem is not exposed in purpose at this time. What are you trying to do with it?

**Comment by vcxyk** [comment]
> JobSystem is not exposed in purpose at this time. What are you trying to do with it?

I am trying integrating Filament with google's MediaPipe framework, but it crash on the JobSystem's  assert in getState() function. (Mediapipe has its own thread scheduler and it seems conflicts with Filament's Jobsystem. So i try to use JobSystem.adopt() function to avoid the thread conflicts.)

**Comment by romainguy** [comment]
Can you describe the problem in more details please? Filament will call `adopt()` on the thread you use to interact with Filament the first time. Adopting another thread wouldn't solve this.

Adding @pixelflinger who wrote `JobSystem` and can help better than me.

**Comment by pixelflinger** [comment]
@vcxyk filament's API is single threaded (filament itself uses multiple threads). You *cannot* use filament's API from several threads.
The only thread filament's API can be called from is the thread that created the `filament::Engine` (and this thread will be automatically adopted by the `JobSystem`).

It sounds like you're breaking that contract.

To be clear, the "conflict" you're mentioning is not with filament's `JobSystem`, it's that you're calling filament's API from multiple threads -- at least, the thread that created the engine + another thread (I'm guessing MediaPipe's).

Currently, you need to create the Engine in the thread's it's going to be used from.
