### ISSUE TITLE
'libfilamat-jin.so',missing and no known rule to make it

### ISSUE THREAD

**Issue by feiziang** [google/filament#2449]
**Describe the bug**
When I do this:
`gradlew -Pfilament_dist_dir=..\out\android-release\filament assembleRelease`
It will get a error (test in v1.3.2; v1.4.1;v1.5.2)
`ninja:error:'D:******/libfilamat.a',needed by'../../../../build/intermedates/cmake/fullRelease/obj/arm64-v8a/libfilamat-jin.so',missing and no known rule to make it  `
**To Reproduce**
1. do the whole behavior before Generate AAR
2.gradlew -Pfilament_dist_dir=..\out\android-release\filament assembleRelease

**Expected behavior**
what should i do??

**Screenshots**
![image](https://user-images.githubusercontent.com/46670194/80169996-88769a80-8619-11ea-867a-1d960baf59cb.png)

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
Did you build Filament itself first? There should be a `libfilamat.a` somewhere in the directory `..\out\android-release\filament`.
