### ISSUE TITLE
sFullScreenTriangleVertices quesition

### ISSUE THREAD

**Issue by jiqimaogou** [google/filament#2453]
[in this issue](https://github.com/google/filament/issues/2430)
romainguy has the code:
```
static constexpr float4 sFullScreenTriangleVertices[3] = {
        { -1.0f, -1.0f, 1.0f, 1.0f },
        {  3.0f, -1.0f, 1.0f, 1.0f },
        { -1.0f,  3.0f, 1.0f, 1.0f }
};
```
my quesion is:

why each vertice has four floats.
and what is 3.0f mean?

**Comment by jiqimaogou** [comment]
I find the answer, it's a great skill.

**Comment by BillyUSA** [comment]
Is  this only valid  in ORTHO Projection Mode?  @jiqimaogou

**Comment by romainguy** [comment]
No, it's in clip space (or NDC). To use it, set your `vertexDomain` on your material to `device`.
