### ISSUE TITLE
build.sh calls wget as root.

### ISSUE THREAD

**Issue by stolk** [google/filament#2455]
**Describe the bug**
When you run linux build.sh then wget is executed as root, which makes no sense.

```
++ sudo wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.sh
```

**To Reproduce**
1. ./build.sh

**Expected behavior**
Call wget as user, not root.

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 

**Additional context**
Latest version from git.

**Comment by romainguy** [comment]
You are running the CI server build scripts. The README file mentions the root build.sh file, not the one in build/linux. You can also use CMake directly if you prefer doing so. The README should have the proper instructions already. I'll add a notice in the build/ subdirectory explaining these scripts are intended for CI only.

**Comment by romainguy** [comment]
Sorry I meant the BUILDING file, not README.

**Comment by romainguy** [comment]
I just uploaded a PR with the following improvements:
- Added an extra README file detailing what the scripts are for
- The scripts now display a warning and a prompt before requiring user confirmation to continue
- The system install commands are only executed in CI environments (`ninja` and `cmake` being installed as root without checking for the environment was a leftover from a previous non-GitHub based CI setup)

Thanks for the feedback, let me know if you run into issues building Filament with the root `build.sh` script or with CMake.
