### ISSUE TITLE
No texture bound to unit 7 (`light_structure`)

### ISSUE THREAD

**Issue by stolk** [google/filament#2459]
**Describe the bug**
The shadow example spews an error message on std out, complaining about unit 7.

It seems related to not having an `envs/` directory in `out/cmake-debug/samples/` dir.

I did notice that build.sh was running cmgen for quite a long time, so I expect the images have been generated?

```
bram@ubuntupc:~/src/filament$ find . -name pillars\* -print
./third_party/environments/pillars_2k.hdr
./docs/webgl/pillars_2k
./docs/webgl/pillars_2k/pillars_2k_skybox.ktx
./docs/webgl/pillars_2k/pillars_2k_ibl.ktx
./docs/webgl/pillars_2k/pillars_2k_skybox_tiny.ktx

```

**To Reproduce**

```
bram@ubuntupc:~/src/filament/out/cmake-debug/samples$ ./shadowtest 
FEngine (64 bits) created at 0x7f6881c10010 (threading is enabled)
FEngine resolved backend: OpenGL
NVIDIA Corporation, GeForce GTX 1650/PCIe/SSE2, 4.1.0 NVIDIA 440.82, 4.10 NVIDIA via Cg compiler
OS version: 0
The specified IBL path does not exist: /home/bram/src/filament/out/cmake-debug/samples/envs/pillars
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
no texture bound to unit 7
Renderer: Commands High watermark 7 KiB (0%), 224 commands, 32 bytes/command
CircularBuffer: High watermark 27 KiB (0%)

```

1. ...

**Expected behavior**
No missing texture.

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu
clang-8

**Additional context**

**Comment by stolk** [comment]
`The specified IBL path does not exist` message seems unrelated...

When I use:
```
static const char* IBL_FOLDER = "venetian_crossroads_2k";
```
I still get the error about unit 7 (but the missing directory error goes away.)

**Comment by romainguy** [comment]
Thanks, this is a debug message we recently added to help track Vulkan issues. You can safely ignore it. Btw I would recommend using release builds.

**Comment by romainguy** [comment]
The error message is unrelated to the IBL indeed.

**Comment by romainguy** [comment]
@prideout @pixelflinger The issue is with unlit materials that use `shadowMultiplier`. We treat these materials as both lit and unlit: they are unlit but they need access to the shadow map. The unbound texture is the `light_structure` which we don't even use in this case. It's probably just a matter of fixing `filamat` to not generate the samplers in this case.

**Comment by romainguy** [comment]
@pixelflinger Looking at the sampler interface block generation code, what I just proposed would be tricky. We treat all light-related textures as a single block. We need to either create a separate shadow interface block or simply bind a dummy texture to structure. The latter is probably the easiest solution.

**Comment by romainguy** [comment]
@pixelflinger @prideout I'm now getting `no texture bound to unit 7` in `material_sandbox` as well. We need to fix this, it's annoying :))

**Comment by romainguy** [comment]
Actually this affects all the lit shaders of `material_sandbox`.
