### ISSUE TITLE
Self-shadowing does not seem to work.

### ISSUE THREAD

**Issue by stolk** [google/filament#2460]
**Describe the bug**
If I make suzanne receive shadows, the model remains un-shadowed. It will only cast shadows, not receive them, despite setting both `.receiveShadows` and `.castShadows` flags.

**To Reproduce**
Modify shadowtest.cpp
```
@@ -85,7 +86,7 @@ int main(int argc, char** argv) {
             auto instance = rcm.getInstance(renderable);
             if (rcm.hasComponent(renderable)) {
                 rcm.setCastShadows(instance, ENABLE_SHADOWS);
-                rcm.setReceiveShadows(instance, false);
+                rcm.setReceiveShadows(instance, ENABLE_SHADOWS);
                 scene->addEntity(renderable);
             }
         }
```

**Expected behavior**
The face of Suzanne should throw a shade onto her left ear.

**Screenshots**
Regardless of receiveShadows flag: the model looks the same.

![image](https://user-images.githubusercontent.com/455280/80287033-fe473880-86e3-11ea-89bc-e78cbf0fec6f.png)

**Desktop (please complete the following information):**
Ubuntu
nvidia
clang-8

**Additional context**
Latest git version.

**Comment by romainguy** [comment]
Self shadowing works in this sample when I make the change you mention:

<img width="1136" alt="Screen Shot 2020-04-25 at 11 20 35 AM" src="https://user-images.githubusercontent.com/869684/80287491-df967100-86e6-11ea-866e-33b12ccad4b6.png">

The screenshot above is without an IBL, the IBL you have is apparently too high intensity?

Here is what I get when I add the pillars IBL, the shadow is there although a bit subtle:

<img width="1136" alt="Screen Shot 2020-04-25 at 11 26 17 AM" src="https://user-images.githubusercontent.com/869684/80287697-9eeb2780-86e7-11ea-96e3-9c8fc984e939.png">

**Comment by romainguy** [comment]
Did you make any other change to the sample app? Was it properly rebuilt as well?

**Comment by stolk** [comment]
I did indeed use venetian_crossroads_2k as the IBL, and that one will not show the shadow.

When I undo that change and revert to a missing IBL, the shadows shows up again.
Thanks.

![image](https://user-images.githubusercontent.com/455280/80288957-6e5bbb80-86f0-11ea-89e8-67e91de470fc.png)

**Comment by romainguy** [comment]
That explains it, thank you. Venetian cross road has a huge dynamic range and already contains a sun light.

BTW you might be interested in playing with `material_sandbox` and `gltf_viewer` to play with many of the available rendering features.
