### ISSUE TITLE
Material Sandbox: Cannot enable spot light.

### ISSUE THREAD

**Issue by stolk** [google/filament#2461]
**Describe the bug**
When I start the Material Sandbox (model monkey.obj) then I cannot enable the Spot Light.

**To Reproduce**
* Launch Material Sandbox with monkey object.
* Expand Spot Light menu
* Click enabled

**Expected behavior**
At the very least, a check-mark should appear in the enabled[ ] box. And the extra light should show up in the scene.

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu
clang-8
nvidia
OpenGL

**Additional context**
Latest git version.

**Comment by romainguy** [comment]
The spot light is there. I tweaked the position a bit so it would be more obvious in this scene (and I turned off directional and image-based light too):

<img width="1136" alt="Screen Shot 2020-04-25 at 1 30 07 PM" src="https://user-images.githubusercontent.com/869684/80290227-e75f1100-86f8-11ea-99b4-2c96614e9649.png">

With the default position the light happens to be inside this model I think. Changing the Z position to 1.2 for instance make it visible.

**Comment by romainguy** [comment]
BTW the default camera exposure parameters are designed for extremely bright lights (sun and sky), you can try boosting the intensity of the spot light or changing the camera exposure.

**Comment by stolk** [comment]
No, the bug is more fundamental than that.

If I click on 'enabled' nothing happens, not even a check mark in the box.

**Comment by stolk** [comment]
Sorry... tried to repro again, and now the check mark does appear. I have no idea what this was. I'll do more testing. You can ignore for now. Sorry.

**Comment by stolk** [comment]
Ok, I repro'd it again. The repro steps are more involved:

* Launch Material Sandbox
* Expand the **Directional Light** menu.
* Expand the **Spot Light** menu (but leave other expanded as well!)
* Click on spot light 'enable'
* Checkbox breaks: no [ ] toggle is shown.

**Comment by romainguy** [comment]
Oh wow that reproduces the bug indeed. Thanks for finding this, I'll fix it asap!

**Comment by romainguy** [comment]
I just checked in a fix: https://github.com/google/filament/commit/1d73027df61d40abed13d9f506ac266d3a0f7551

The checkbox for the spot light was using the same label as the directional light's, causing ImGui to override one with the other. They now properly use distinct keys. Thanks for finding this!

**Comment by stolk** [comment]
Thanks. Works now. I think color has the same name clash.

Finally... is "Tone Mapping" toggle doing the SRGB? Because the scene looks too dark with out it.

**Comment by romainguy** [comment]
Yes, "Tone mapping" does both tone mapping and linear->sRGB conversion. I've opened a feature request a while ago to separate both. The main reason it's this way is because on mobile we merged the tone mapper and the sRGB conversion to optimize post-processing.

I'll fix the color key clash.

**Comment by romainguy** [comment]
Fixed, thanks for noticing that one too!
