### ISSUE TITLE
1.6.0 release does not have Windows version asset

### ISSUE THREAD

**Issue by cx20** [google/filament#2476]
I've tried checking the `1.6.0` release content.
https://github.com/google/filament/releases/tag/v1.6.0
However, I don't think `Windows` asset is included.

![image](https://user-images.githubusercontent.com/1833979/80851414-b6cd2900-8c5c-11ea-9b89-2c0ddfc20cc0.png)

**Comment by romainguy** [comment]
It’s still building :)

**Comment by cx20** [comment]
Thanks! I confirmed that `filament-20200502-windows.tgz` was built.
