### ISSUE TITLE
Filament version used in JS Tutorial is old

### ISSUE THREAD

**Issue by cx20** [google/filament#2483]
**Is your feature request related to a problem? Please describe.**
The latest version of Filament contains some breaking changes, so the tutorial code will not work with the latest version of Filament.

**Describe the solution you'd like**

The current version of Filament used in Tutorial is probably v1.4.x.
Some methods are out of date and need to be updated.

For example.
https://google.github.io/filament/webgl/tutorial_triangle.html
```javascript
//this.view.setClearColor([0.1, 0.2, 0.3, 1.0]);
this.renderer.setClearOptions({clearColor: [0.1, 0.2, 0.3, 1.0], clear: true});
```
Also, The material files (`.filamat`) are also incompatible and will need to be regenerated with the latest version of matc.

**Comment by prideout** [comment]
Thanks for the bug report, I'll go ahead and update these.  I recently updated our Android tutorial on Medium but yes we should maintain our JavaScript tutorials too.
