### ISSUE TITLE
Docs for build process for WebGL on Ubuntu 18.04

### ISSUE THREAD

**Issue by ad8e** [google/filament#249]
This is just a step-by-step guide of the process, for those who come after me. Success takes about 6 build attempts and some debugging; this guide will get things working on the first try for people using Ubuntu 18.04 specifically. All the necessary clues are in the docs, but not in the expected places.

Guide:
1. install emscripten. The instructions for installing emscripten at https://github.com/google/filament#webassembly under `install the Emscripten SDK` are fine. If you want to use the "latest" branch in emsdk instead of filament's specified one, that works too.
2. Go to https://github.com/google/filament#linux and install the dependencies. When it says `libxi-dev` may be required, it's required for Ubuntu. Don't do the steps past the dependency section. Also install the pre-requisites at https://github.com/google/filament#prerequisites: `sudo apt install clang ninja-build cmake`.
3. Make sure you ran `export EMSDK=$PWD` when you were in the emsdk folder, like the docs told you to. Also, run `export FILAMENT_REQUIRES_CXXABI=true` (the docs don't mention this).
4. Navigate to the filament folder and run `CC=/usr/bin/clang CXX=/usr/bin/clang++ ./build.sh -p webgl release`. The "release" is necessary; the webgl build gets skipped if you leave it out.

Suggestions for the docs:
The Webassembly section should note that the Linux package dependencies are still required. (Or Windows dependencies. Basically, all the requirements for the desktop build are still requirements for the WebGL build.)
Mention Ubuntu specifically when talking about `libxi-dev`, not only that some distributions will need it. This will save Ubuntu users some time.
Also mention Ubuntu specifically when talking about how `-DFILAMENT_REQUIRES_CXXABI=true` may be needed, in the desktop build; this will also save Ubuntu users some time.
My guess is that `export FILAMENT_REQUIRES_CXXABI=true` lets Ubuntu users continue using the `build.sh` script instead of falling back to cmake, but this is just a guess. Similarly, it may be possible to avoid the cmake fallback on the Desktop build by using the `CC` `CXX` flags with `build.sh`.
Needing "release" to avoid skipping the WebGL build may be a bug but I'm not sure.
WebGL needing the `CC` and `CXX` flags might be noted, it's in the Desktop section for those with GCC systems.
If a build fails, the `out` folder must be deleted before `build.sh` can be run again.

**Comment by prideout** [comment]
Thanks, I'll improve the README.
