### ISSUE TITLE
Emissive material are corrupt when optimization is disabled on Android

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2490]
If you define an emissive texture using the standard pattern then the output is corrupted when you build the material without optimization, either with matc or with filamat (full and lite). The corruption looks like this on Adreno:

![device-2020-05-06-150304](https://user-images.githubusercontent.com/303516/81186513-c923cb80-8faa-11ea-8b82-a43f43fca752.png)

On Mali it is sometimes doesn't happen and sometimes it's just black.

I modified _sample-textured-object_ so that the base color texture was switched to an emissive texture and I modified the shader to mimic the emissiveFactor * emissiveMap pattern used by most of the standard shaders. I also disabled optimization in the matc invocation. Here are the changes on a recent branch from master: https://github.com/LearnHub/filament/commit/44ba510119bc07a731daf9601c9d6d199ceaf15a

You can prevent the corruption by avoiding the multiplication or by switching material compiler optimization back on.

**Comment by romainguy** [comment]
I can't reproduce the issue. Emissive works fine both with optimized and unoptimized shaders. The emissive code is just this:

```
void addEmissive(const MaterialInputs material, inout vec4 color) {
#if defined(MATERIAL_HAS_EMISSIVE)
    highp vec4 emissive = material.emissive;
    highp float attenuation = mix(1.0, frameUniforms.exposure, emissive.w);
    color.rgb += emissive.rgb * attenuation;
#endif
}
```

I don't quite see what could be causing issues. Does it happen with unlit materials too (they support emissive as well)? The only thing I can think of is a driver bug with `inout`.

**Comment by rawnsley** [comment]
Changing to 'unlit' (and removing the references to ambientOcclusion, roughness, and metallic in the shader) makes the problem go away.

It certainly feels like a driver problem, but I get similar behaviour on two devices:

```
Pocofone F1

QUALCOMM build                   : dc7175c, I423ca2612a
Build Date                       : 09/12/19
OpenGL ES Shader Compiler Version: EV031.27.05.01
Local Branch                     : 
Remote Branch                    : 
Remote Branch                    : 
Reconstruct Branch               : 
Build Config                     : S P 8.0.11 AArch64

XR1 device

QUALCOMM build                   : 183617d, I6f3c5dffee
Build Date                       : 10/01/18
OpenGL ES Shader Compiler Version: EV031.25.07.01
Local Branch                     : mybranch36158767
Remote Branch                    : quic/gfx-adreno.lnx.1.0.r67-rel
Remote Branch                    : NONE
Reconstruct Branch               : NOTHING
Build Config                     : S L 4.0.10 AArch64
```
I'll try comparing the fragment shaders for lit and unlit to see if I can spot any clues.

**Comment by rawnsley** [comment]
Changing 

`material.emissive = vec4(materialParams.emissiveFactor.rgb, 0.0);
`

to

`material.emissive = vec4(materialParams.emissiveFactor.rgb, 0.0) * 1.0;
`

makes the problem go away, which implies it's a shader compiler bug when fetching emissiveFactor. Odd that it doesn't impact the unlit model, but it could be something to do with the alignment of the other uniforms for instance. Also odd that the compiler doesn't optimize away the multiplication, which it always manages to do when I don't want it to.

I appreciate you can't do much about it without a local reproduce and I'm comfortable with this workaround if you want to close it.

**Comment by romainguy** [comment]
That's what I suspected unfortunately. This kind of bug is unfortunately not uncommon, see some examples here: https://medium.com/@afd_icl. Stuff like `+ 0.0` or `* 1.0` can indeed break compilers. If you have time and can compile Filament itself, it might be worth trying to find a workaround directly in our code. Maybe just moving `emissive.rgb * attenuation` to a temporary variable?

**Comment by romainguy** [comment]
Another thing to try would be to remove the function altogether and inline its content at the call site.

**Comment by rawnsley** [comment]
Unfortunately neither inlining the function nor using a temporary variable made a difference. I also tried swapping emissiveFactor to a vec4 instead.

**Comment by pixelflinger** [comment]
not actionable / shader compiler bug.
