### ISSUE TITLE
GLTF's UV scaling functionality not implemented?

### ISSUE THREAD

**Issue by vortice3D** [google/filament#2500]
**Bug description**
We suspect that the Filament 1.4.5 version, present in last Sceneform version (1.16.0), does not deal (properly) with UV Scaling in GLTF/GLB files.

**To Reproduce**
This kind of transform is carried-out by means of the GLTF 2.0 extension **KHR_texture_transform**.
Said this, when this kind of UV Scaling is used in a GLTF file under ARCore, in order to obtain a repeatable large texture, these are the wrong results obtained:
![image](https://user-images.githubusercontent.com/1760601/81282246-2f682700-905b-11ea-92c5-da06f416fa6d.png)
Please note the wrong repetition problem in the platform and the rail.

**Expected behavior**
Of course, the texture is shown in a correct way when we visualize the GLTF by means of a WebGL viewer (e.g. VSCodium GLTF Extension with BJS rendering):
![image](https://user-images.githubusercontent.com/1760601/81282521-91289100-905b-11ea-8032-befc0a286f84.png)

**Smartphone (please complete the following information):**
 - Device: Motorola MotoG6 and Samsung Tab S4
 - OS: Android 9.0

**Comment by romainguy** [comment]
Texture transforms are implemented. Would you mind sharing the glTF file that's causing issues please?

**Comment by romainguy** [comment]
Note that Filament 1.4.5 is rather old at that point, so it might just be that the feature wasn't available then. It should definitely work with Filament 1.5 and 1.6.

**Comment by prideout** [comment]
@romainguy , do we know if Sceneform uses gltfio?

**Comment by romainguy** [comment]
The Open Source version does yes. Ask Tim about the details

**Comment by vortice3D** [comment]
Hi **Romain** and **Philip**:

First of all, thank you very much for your time.

As stated I'd need this functionality working for **Filament 1.4.5** as this is the one implemented under **Sceneform 1.16.0**.

On its part, I need **Sceneform 1.16.0** as I want use GLTF/GLB animation and this last version is the one implementing it, on **ARCore**, by means of **gltfio**.

An abstract with the relevant parts of my 3D scene (as you can see exported by Blender) is:

```
{
    "asset" : {
        "generator" : "Khronos glTF Blender I/O v1.1.46",
        "version" : "2.0"
    },
    "extensionsUsed" : [
        "KHR_texture_transform"
    ],
    "extensionsRequired" : [
        "KHR_texture_transform"
    ],

    ...

   "materials" : [
         ...
        {
            "emissiveFactor" : [
                0,
                0,
                0
            ],
            "name" : "Plataforma_material.001",
            "normalTexture" : {
                "extensions" : {
                    "KHR_texture_transform" : {
                        "scale" : [
                            50,
                            1
                        ]
                    }
                },
                "index" : 10,
                "texCoord" : 0
            },
            "pbrMetallicRoughness" : {
                "baseColorTexture" : {
                    "extensions" : {
                        "KHR_texture_transform" : {
                            "scale" : [
                                50,
                                1
                            ]
                        }
                    },
                    "index" : 11,
                    "texCoord" : 0
                },
                "metallicRoughnessTexture" : {
                    "extensions" : {
                        "KHR_texture_transform" : {
                            "scale" : [
                                50,
                                1
                            ]
                        }
                    },
                    "index" : 12,
                    "texCoord" : 0
                }
            }
        }
         ...
    ],
    ...
}
```

If you need a "live" sample we can generate a scene with a textured plane showing this same issue,

Best regards:

**Comment by romainguy** [comment]
If you send us a test model that doesn't work in your case, we can test it with the curent versions of Filament.

**Comment by prideout** [comment]
@vortice3D yes a complete gltf or glb would be helpful.

I just checked and we still pass the TextureTransformTest, in both ubershader mode and matgen mode.

**Comment by vortice3D** [comment]
Hi @romainguy  and @prideout, and forgive me for the delay in my answering.

How can I pass you the assets? A WeTransfer link will work for you?

Thanks in advance.

**Comment by romainguy** [comment]
A WeTransfer would work just fine yes.

**Comment by vortice3D** [comment]
Thank you, @romainguy, for your immediate response.

Please access the "conflicting" model through [this link](https://we.tl/t-iJ2HBajZog).

Best regards.

**Comment by romainguy** [comment]
Thank you, that's extremely helpful!

**Comment by romainguy** [comment]
Here is what I see with the current version of Filament:

<img width="790" alt="Screen Shot 2020-05-21 at 11 14 28 PM" src="https://user-images.githubusercontent.com/869684/82637058-d949c680-9bb8-11ea-9795-728030935d1f.png">

Looks like it works? Your best solution is to compile Sceneform 1.16 from source yourself to use a newer version of Filament.

**Comment by vortice3D** [comment]
Hi @romainguy:

Well, as I stated at the beginning of this thread We knew the model was correct, as we test all of them by means of WebGL viewers (BJS Sandbox mainly) as a core part of our pipeline with GLTF/GLB work.

Said that, if the problem is not in Filament, bearing in mind that Sceneform uses it (v4.5), I can't understand how can to solve the issue the suggested recompilation? Do you mean that the problem is in the version of Filament (v4.5) used in Sceneform 1.16? @prideout said that such a previous version of Filament already supported the uv-scaling.

Best regards.

**Comment by romainguy** [comment]
I never doubted the model was correct :) Previous versions of Filament did support UV scaling but maybe we had a bug that was fixed since then. We're currently at Filament 1.7.0. I'll build Filament 1.4.5 and test with it to see what the behavior was then.

**Comment by romainguy** [comment]
It works too in 1.4.5: 
<img width="522" alt="Screen Shot 2020-05-21 at 11 32 32 PM" src="https://user-images.githubusercontent.com/869684/82638255-5ece7600-9bbb-11ea-959d-661bc6e7a59a.png">

I tested with and without ubershaders. Not sure what's going on with Sceneform here but the issue doesn't seem to be on our end.

**Comment by vortice3D** [comment]
Hi @romainguy.

Thank you very much for the info.

I suppose then that we need to return to the Sceneform issues-forum, when we first answered about this subject.

The problem is that is not a very active forum (not in the side of Sceneform developers) and with the open-sourcing of the engine it has even worse, as now the repository appear as "archived by the owner".

By the way, do you know about any resource (documentation) that we can use as a guideline for recompiling Filament versions inside Sceneform?

Best regards.

**Comment by romainguy** [comment]
Looking at the source of Sceneform, it should just be a matter of changing those two lines in `build.gradle`:

```
    api 'com.google.android.filament:filament-android:1.4.5'
    api 'com.google.android.filament:gltfio-android:1.4.5'
```

And then recompiling Sceneform with `./gradlew assembleRelease` at the root of the project.

Besides AR tracking do you use any specific features of Sceneform? It should be fairly straightforward to use ARCore + Filament directly.

**Comment by vortice3D** [comment]
Hi @romainguy:

Again, thank you very much for your time! We'll try the recompilation.

Certainly this subject of the open-sourcing of **Sceneform**, with the use of **Filament**, seemed at the beginning as a good thing for the community of developers, but sadly it has finally become, under my point of view, as a bit of foul play, with the GitHub repo closed and, not all parts and examples of the engine ported to 1.16, the docs badly linked, ...

With the previous experience of Vuforia, Kudan, ... and so on, it's clear to me that the AR Engines are intended by vendors almost exclusively to be used by means of Unity/Unreal engines. If you are so daring to try to avoid that bloatware-generators developing directly with Android/iOS SDKs, you will be not helped at all by the vendors (if not directly busted).

Said that, about using **Filament** instead of **Sceneform**, as you are suggesting, we are concerned about the former is more a Render Engine and the latter a 3D Engine. Either way, we use several specific APIs from [com.google.ar.sceneform.ux](https://developers.google.com/sceneform/reference/com/google/ar/sceneform/ux/package-summary), so is not an easy decision.

Best regards.

**Comment by romainguy** [comment]
Well Sceneform has always used Filament, and Filament was always Open Source.

I'm not sure what distinction you make between 3D and rendering engine but Filament does provide support for scenes, transforms (with parent transforms), multiple views and even glTF via the gltfio library. Whether what Filament provides is enough for your needs mostly depends on which Sceneform APIs you use.

**Comment by vortice3D** [comment]
Hi again, @romainguy  and @prideout :

I'm reopening this issue after checking that, even using Filament 1.7 (from [here](https://github.com/google-ar/arcore-android-sdk/issues/1049)), we get the same not-correct behavior of UV-Scaling under ARCore(1.17)/Sceneform(1.16)/Filament(1.7) basis.

Any idea about how this issue can be tacked?

Thanks for your time!

**Comment by prideout** [comment]
I'm not able to open the WeTransfer link, can you attach a zip to this GitHub issue?

**Comment by romainguy** [comment]
I'm unable to reproduce the issue with just Filament, I wonder if there's a problem on the Sceneform side.

BTW @vortice3D, the Sceneform team just updated Sceneform to use Filament v1.7.0. You might want to try again with a new checkout, just in case.

**Comment by vortice3D** [comment]
Hi again @prideout.

> I'm not able to open the WeTransfer link, can you attach a zip to this GitHub issue?

Any news with this issue?

**Comment by romainguy** [comment]
I'm surprised it would fail with Filament 1.7.0 since Sceneform uses our gltfio library. @prideout would you mind testing the asset in sample-gltf-viewer? Just in case.

**Comment by prideout** [comment]
I can repro with 1.7.0 + Sceneform (thanks to @tpsiaki) but strangely I cannot repro with `sample-gltf-viewer` at tag v1.7.0 (see screenshot below).   This is very strange.  I will keep digging.

![device-2020-06-17-104200](https://user-images.githubusercontent.com/1288904/84946030-e3b68d80-b09c-11ea-86b1-e734618ae382.png)

**Comment by prideout** [comment]
Actually, I can repro the issue in `sample-gltf-viewer` by removing `transformToUnitCube()`, which causes the relative position of the camera to be closer to what's used in the Sceneform app, so we're looking at a much different part of the mesh.  See screenshot below.

However doing the same thing on desktop does not reveal the issue.

I tried hacking the ubershader to visualize the transformed UV coords and they looked okay, roughly speaking.

This is starting to look like a precision issue.

![BAD](https://user-images.githubusercontent.com/1288904/84959111-9396f580-b0b3-11ea-9cd4-7244bc779b45.png)

**Comment by romainguy** [comment]
We may have UVs not marked `highp` somewhere then. Could be in the gltf specific shaders since they apply transform matrices. `mediump` isn't good enough for textures > 1024, the solution is probably as simple as adding a `highp` modifier in the glTF shaders wherever we apply texture transforms (i.e. anything that looks like `vec2 uv0 = textureTransform * getUV0() `).

**Comment by prideout** [comment]
Yup adding highp to gltfio fixes this.  It was a Philip bug after all.  /shame
