### ISSUE TITLE
Switching from textured skybox to solid color skybox leaves old cubemap in reflections

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#2505]
When switching from a skybox containing a cubemap to a skybox using only a color, the cubemap from the first skybox shows up as reflections.

This procedure also seems to create a glossier, more reflective surface in all of my materials.  See the images below for reference.  The top image contains a cubemap skybox, the bottom image uses a gray-colored skybox.

Notice the second image reflections show the cubemap from the first skybox.  The reflections seem much stronger than in the first image (the object's material's reflection parameter is set to 0.0 in both cases).  This could be due to a difference in the IBL lighting, I suppose, but I mention it in case there is a shader bug.

These images were both taken in the same session, I simply swapped skyboxes between captures.

![SkyboxTexture](https://user-images.githubusercontent.com/40642629/81434950-3f980900-9124-11ea-8c39-ca0135987b62.PNG)
![SkyboxColor](https://user-images.githubusercontent.com/40642629/81434960-47f04400-9124-11ea-8337-cf4ee92a82b3.PNG)

 - OS: Windows 10
 - GPU: NVIDIA GTX 1050
 - Backend: OpenGL

**Comment by romainguy** [comment]
The skybox just renders the background, it is separate from the `IndirectLight` object that provides reflections. The shaders don't know anything about the skybox.

**Comment by BStringhamVRSK** [comment]
I will double-check, but I believe I am replacing both the skybox and the indirect light.

**Comment by romainguy** [comment]
`IndirectLight` doesn't have a solid color mode, you need to provide that data yourself via a texture (it can just be a 1x1 texture).

**Comment by BStringhamVRSK** [comment]
The first indirect light I create is built with a cube-map reflection texture like this:
`
IndirectLight* newLight = IndirectLight::Builder()
		.reflections(cubemap->GetTexture())
		.irradiance(3, FilamentIndirectLight::GetCoefficients(lightType))
		.build(*engine);
`
The second indirect light is built with spherical harmonic coefficients only, like this:
`
	IndirectLight* newLight = IndirectLight::Builder()
		.irradiance(3, lightCoef)
		.intensity(intensity)
		.build(*engine);
`
I can't figure out why the second light would be using reflections at all, as I do not specify any.  Are they a required parameter?  Is that what you mean in your last comment?

**Comment by romainguy** [comment]
If you don't give it a texture it'll most likely what was last bound to the cubemap slot in GL.

**Comment by BStringhamVRSK** [comment]
Ok.  Makes sense.  That must be what I'm seeing, then.  Thanks.
