### ISSUE TITLE
Building Filament for Android on Windows Failed

### ISSUE THREAD

**Issue by starthlw** [google/filament#2509]
Hi，I build filament-master for Android on windows10(vs2017) as filament/android/Windows.md , 
then execute 'cmake -G Ninja ...' success, 
but execute 'ninja matc resgen cmgen' failed, The error is as follows：
...
..\..\libs\image\src\ImageSampler.cpp(44): error C2059: 语法错误:“.”
..\..\libs\image\src\ImageSampler.cpp(44): error C2143: 语法错误: 缺少“;”(在“{”的前面)
..\..\libs\image\src\ImageSampler.cpp(44): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
..\..\libs\image\src\ImageSampler.cpp(44): error C2059: 语法错误:“,”
..\..\libs\image\src\ImageSampler.cpp(46): error C2143: 语法错误: 缺少“;”(在“}”的前面)
...
and ImageSampler.cpp(44) is:
`const FilterFunction Box {`
`    .fn = [](float t) { return t <= 0.5f ? 1.0f : 0.0f; },`
`    .boundingRadius = 1`
`};`
It looks like ninja can't build c++ code with lambda
How can i solve this problem, thank you very much

**Comment by romainguy** [comment]
Ninja shouldn't have an issue with this, but we require VS2019 because we rely on C++14 features that didn't work in 2017.

@bejado Can you confirm please?

**Comment by bejado** [comment]
Yes, we require VS2019 for building the host tools on Windows. I'll make a note of this.

**Comment by sourabhgupta811** [comment]
Hi @romainguy 
I am trying to build filament for android on Windows with vs2019.
my build also fails on the same step as mentioned in the question above.
Here is the console output-
```
..\..\libs\ibl\src\Cubemap.cpp(102): error C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
..\..\libs\ibl\src\Cubemap.cpp(102): error C2065: 'x': undeclared identifier
..\..\libs\ibl\src\Cubemap.cpp(102): error C2065: 'ssize_t': undeclared identifier
..\..\libs\ibl\src\Cubemap.cpp(102): error C2146: syntax error: missing ',' before identifier 'y'
..\..\libs\ibl\src\Cubemap.cpp(102): error C2059: syntax error: ')'
..\..\libs\ibl\src\Cubemap.cpp(102): error C2143: syntax error: missing ';' before '{'
..\..\libs\ibl\src\Cubemap.cpp(103): error C2065: 'image': undeclared identifier
..\..\libs\ibl\src\Cubemap.cpp(103): error C2065: 'x': undeclared identifier
..\..\libs\ibl\src\Cubemap.cpp(103): error C2065: 'image': undeclared identifier
..\..\libs\ibl\src\Cubemap.cpp(103): error C2065: 'y': undeclared identifier
..\..\libs\ibl\src\Cubemap.cpp(103): error C2065: 'image': undeclared identifier
```
Please help me how can i solve this problem.

**Comment by bejado** [comment]
@sourabhgupta811 Which version of VS 2019 are you using?

**Comment by sourabhgupta811** [comment]
@bejado I am using version VS 2019 version 16.7

**Comment by bejado** [comment]
Do you have Python 3 installed and configured in your system PATH?

Run `python --version` in the command prompt and check you see version 3.

**Comment by sourabhgupta811** [comment]
I had the version 3.7 installed but I only had python launcher managing it for me and it was not register in environment varibales. I added it there and it worked. But there is one new issue now while building the host tools.
This is the console output 
```
 Assembling: ..\..\libs\bluegl\src\BlueGLCoreWindowsImpl.S
..\..\libs\bluegl\src\BlueGLCoreWindowsImpl.S(22) : error A2013:.MODEL must precede this directive
..\..\libs\bluegl\src\BlueGLCoreWindowsImpl.S(25) : error A2034:must be in segment block : glMultiDrawArraysIndirectBindlessCountNV
..\..\libs\bluegl\src\BlueGLCoreWindowsImpl.S(26) : error A2034:must be in segment block
..\..\libs\bluegl\src\BlueGLCoreWindowsImpl.S(27) : error A2034:must be in segment block
..\..\libs\bluegl\src\BlueGLCoreWindowsImpl.S(28) : fatal error A1010:unmatched block nesting : glMultiDrawArraysIndirectBindlessCountNV
```

**Comment by bejado** [comment]
I'm not sure what's going on, I'm able to assemble that file without a problem. If you run

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>ml64.exe --version
Microsoft (R) Macro Assembler (x64) Version 14.27.29111.0
Copyright (C) Microsoft Corporation.  All rights reserved.
```

what do you see?

**Comment by sourabhgupta811** [comment]
I have the same version for ml64.exe but as i see the command is using the 32 bit version of it i.e ml.exe and not ml64.exe
I am building it on a 64-bit machine.
```
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx86\x86\ml.exe  -I..\..\libs\bluegl\include  /c  /Fo libs\bluegl\CMakeFiles\bluegl.dir\src\BlueGLCoreWindowsImpl.S.obj ..\..\libs\bluegl\src\BlueGLCoreWindowsImpl.S
```.

**Comment by sourabhgupta811** [comment]
Hi, the problem has been resolved.
VS command prompt was using the 32 bit toolchain that's why it was failing. I used the x64 vs command prompt and it ran smooth.
Thanks for the help!

**Comment by ouyangpeng** [comment]
> @bejado I am using version VS 2019 version 16.7 Edit- The commands now runs successfully after i uninstalled and reinstalled all the vs components. But the task now fails on build with `ninja install` command. This is the console output-
> 
> ```
> [12/631] Generate extended instruction tables for spv-amd-shader-explicit-vertex-parameter.
> FAILED: third_party/spirv-tools/spv-amd-shader-explicit-vertex-parameter.insts.inc
> cmd.exe /C "cd /D D:\sourabh_data\android_studio_projects\filament-main\filament-main\out\cmake-android-release-aarch64\third_party\spirv-tools\source && D:\sourabh_data\android_studio_projects\filament-main\filament-main\third_party\spirv-tools\utils\generate_grammar_tables.py --extinst-vendor-grammar=D:/sourabh_data/android_studio_projects/filament-main/filament-main/third_party/spirv-tools/source/extinst.spv-amd-shader-explicit-vertex-parameter.grammar.json --vendor-insts-output=D:/sourabh_data/android_studio_projects/filament-main/filament-main/out/cmake-android-release-aarch64/third_party/spirv-tools/spv-amd-shader-explicit-vertex-parameter.insts.inc --vendor-operand-kind-prefix="
> [14/631] Building CXX object libs/filaflat/CMakeFiles/filaflat.dir/src/ChunkContainer.cpp.o
> ninja: build stopped: subcommand failed.
> ```

I also encountered this problem. The compilation was successful, but the ninja installation failed
```
E:\GitLab Source\filament\out\cmake-android-release-aarch64>ninja install
[1/849] Linking CXX static library third_party\libgtest\tnt\libgtest.a
FAILED: third_party/libgtest/tnt/libgtest.a
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E rm -f third_party\libgtest\tnt\libgtest.a && C:\Android\SDK\ndk\android-ndk-r16b-windows-x86_64.zip\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-ar.exe qc third_party\libgtest\tnt\libgtest.a  third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o && C:\Android\SDK\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-ranlib.exe third_party\libgtest\tnt\libgtest.a && cd ."
系统找不到指定的路径。
[2/849] Linking CXX static library libs\math\libmath.a
FAILED: libs/math/libmath.a
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E rm -f libs\math\libmath.a && C:\Android\SDK\ndk\android-ndk-r16b-windows-x86_64.zip\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-ar.exe qc libs\math\libmath.a  libs/math/CMakeFiles/math.dir/src/dummy.cpp.o && C:\Android\SDK\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-ranlib.exe libs\math\libmath.a && cd ."
系统找不到指定的路径。
[10/849] Building C object libs/gltfio/CMakeFiles/uberarchive.dir/materials/uberarchive.c.o
ninja: build stopped: subcommand failed.
```
