### ISSUE TITLE
Vulkan shader errors 

### ISSUE THREAD

**Issue by nemerle** [google/filament#251]
**Describe the bug**
Running any of the provided vk_* samples leads to a bunch of
```
VULKAN ERROR: (Validation)  [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Structure id 232 decorated as Block must follow standard uniform buffer layout rules: member 8 at offset 412 overlaps previous member ending at offset 415
  OpFunctionEnd

VULKAN ERROR: (Validation)  [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Structure id 336 decorated as Block must follow standard uniform buffer layout rules: member 8 at offset 412 overlaps previous member ending at offset 415
  OpFunctionEnd
```

**To Reproduce**
1. Run samples/vk_hellopbr

**Expected behavior**
No errors :)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - GPU: NVIDIA GTX 1080 and GTX 970  (driver ver. 396.54 )
 - Backend: Vulkan

**Additional context**
startup log:
```
Engine (64 bits) created at 0x7ffa6e571010 (threading is enabled)
FEngine resolved backend: Vulkan
Selected physical device 'GeForce GTX 1080' from 1 physical devices. (vendor 0x10de, device 0x1b80, api 0x401046, driver 0x630d8000)
Hierarchy depth = 1
vkCreateSwapchain: 1024x640, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 2
```
[sdkinfo.txt](https://github.com/google/filament/files/2390107/sdkinfo.txt)

**Comment by prideout** [comment]
Interesting, thanks for the report.  I don't see this today on master debug or release on my Quadro M4000 with driver ver. 384.111

**Comment by prideout** [comment]
Since this is a validation error, it could be more related to the LunarG SDK than the driver.  @nemerle maybe you could do `vulkaninfo > sdkinfo.txt` and attach the resulting text file?

Meanwhile I'll see if my SDK is up to date.

**Comment by nemerle** [comment]
Sure thing, attached the log from my home machine which exhibits the same behavior ( same os/driver just a different gpu )

**Comment by nemerle** [comment]
Just an update, the problem still persists on driver version 410.57 

I have no idea if this is caused by that problem, but I'm getting rendering artefacts in vk_viewtest
![peek 2018-09-25 13-11](https://user-images.githubusercontent.com/96597/46011037-eb622180-c0c4-11e8-8604-576f427f0db1.gif)

**Comment by prideout** [comment]
Interesting thanks!  I see the `vk_viewtest` issue too, we'll take a look at both of these issues soon.

**Comment by romainguy** [comment]
@prideout So @bejado's link fix doesn't solve this problem?

**Comment by prideout** [comment]
I don't have a repro yet for the InconsistentSpirv reported by @nemerle  but there is a good chance it might fix that.

@nemerle note that 13cb47e has been merged to master, and might possibly fix this issue.

**Comment by nemerle** [comment]
Checked out a clean 86b8a973
```
FEngine (64 bits) created at 0x7ff02d013010 (threading is enabled)
FEngine resolved backend: Vulkan
Selected physical device 'GeForce GTX 1080' from 1 physical devices. (vendor 0x10de, device 0x1b80, api 0x401046, driver 0x630d8000)
vkCreateSwapchain: 1024x640, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 2
VULKAN ERROR: (Validation)  [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Structure id 61 decorated as Block must follow standard uniform buffer layout rules: member 8 at offset 412 overlaps previous member ending at offset 415
  OpFunctionEnd
```

**Comment by prideout** [comment]
Thanks for the attempt!  I do have a GeForce card in the office, so I'll try with that later today.

**Comment by prideout** [comment]
I am now using NVIDIA 390.87, still no repro with debug or release.

**Comment by nemerle** [comment]
After upgrading to latest commit, and vulkan validation layers to 1.1.85, things got better:
```
FEngine (64 bits) created at 0x7f2fda827010 (threading is enabled)
FEngine resolved backend: Vulkan
Selected physical device 'GeForce GTX 1080' from 1 physical devices. (vendor 0x10de, device 0x1b80, api 0x401046, driver 0x630d8000)
vkCreateSwapchain: 1024x640, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 2
VULKAN ERROR: (Validation)  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x7f2fd42876e8 (Type = 6) | Cannot submit cmd buffer using image (0x23) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL.
VULKAN ERROR: (Validation)  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x7f2fd42876e8 (Type = 6) | Cannot submit cmd buffer using image (0x20) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL.
froxel arena: High watermark 0 KiB (0%)
froxel arena: High watermark 0 KiB (0%)
Renderer: Commands High watermark 0 KiB (0%), 4 commands, 32 bytes/command
CircularBuffer: High watermark 43 KiB (1%)
cleaning up 1 leaked filament::details::FMaterial
Destroying 0 descriptor sets.
per-renderpass allocator arena: High watermark 4194303 KiB (204805%)
```

The graphical corruption presented before still occurs though.

**Comment by prideout** [comment]
Let's file a new issue (just for the graphical corruption) if it still exists, now that we've overhauled the resource lifetime management in the Vulkan backend.
