### ISSUE TITLE
Minor typo in the documentation

### ISSUE THREAD

**Issue by ApoorvaJ** [google/filament#2510]
The description below equation (13) should say cos(theta_m) instead of theta_m.

![image](https://user-images.githubusercontent.com/2312221/81485459-8897ac80-924d-11ea-9123-b59aa9304f90.png)

And thank you for the stellar documentation. :)

**Comment by romainguy** [comment]
Thank you! I'm fixing this right away.

**Comment by romainguy** [comment]
https://github.com/google/filament/commit/6a0a2d965e5d927668f071c2a8b04a2637c89266
