### ISSUE TITLE
How do I achieve AR try on with filament.

### ISSUE THREAD

**Issue by jiqimaogou** [google/filament#2513]
hello, I want to write an AR try on application with filament.
first input is 3d head vertices, second input is glass model vertices.
I want to put the glass on the head, hidden the 3d face vertice, and hidden the part of the glass which is blocked by head.

how How do I achieve it with filament.

**Comment by romainguy** [comment]
You would just need to render the head as an opaque material but with `colorWrite` turned off (so it will write only to the depth buffer), then you can render the glass as a transparent material.

**Comment by jiqimaogou** [comment]
tha

> You would just need to render the head as an opaque material but with `colorWrite` turned off (so it will write only to the depth buffer), then you can render the glass as a transparent material.

than you so much!
