### ISSUE TITLE
how to do the sample_cloth example?

### ISSUE THREAD

**Issue by SssWen** [google/filament#2514]
![image](https://user-images.githubusercontent.com/37821777/81541204-5731f480-93a5-11ea-9b27-ec13dbbb0af6.png)
it's seems to need some textures, but i can't find in the assets folder. where can i find these textures?

**Comment by romainguy** [comment]
This sample is a bit silly, you just need to be in a directory with files named `basecolor.png`, `normal.png` and `roughness.png`. `third_party/textures` has textures you can use if you want.
