### ISSUE TITLE
webgl build appears to be broken

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2515]
[421/442] Linking CXX executable web/filament-js/filament.js
FAILED: web/filament-js/filament.js 
: && /tmp/emsdk/upstream/emscripten/em++  -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics  -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 -DNDEBUG -O2 -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti  -s USE_WEBGL2=1  --bind -s ALLOW_MEMORY_GROWTH=1 -s MODULARIZE_INSTANCE=1 -s EXPORT_NAME=Filament -s ERROR_ON_UNDEFINED_SYMBOLS=0 --post-js /app/filament/web/filament-js/wasmloader.js --post-js /app/filament/web/filament-js/extensions.js --post-js /app/filament/web/filament-js/utilities.js -O2 web/filament-js/CMakeFiles/filament-js.dir/jsenums.cpp.o web/filament-js/CMakeFiles/filament-js.dir/jsbindings.cpp.o  -o web/filament-js/filament.js  filament/libfilament.a libs/math/libmath.a libs/utils/libutils.a libs/image/libimage.a libs/filameshio/libfilameshio.a libs/gltfio/libgltfio_core.a third_party/meshoptimizer/libmeshoptimizer.a filament/libfilament.a filament/backend/libbackend.a libs/filaflat/libfilaflat.a libs/filabridge/libfilabridge.a libs/ibl/libibl.a libs/geometry/libgeometry.a libs/math/libmath.a libs/utils/libutils.a libs/gltfio/libgltfio_resources.a third_party/draco/tnt/libdracodec.a && :
em++: error: Attempt to set a non-existent setting: 'MODULARIZE_INSTANCE'
 - did you mean one of MODULARIZE?
 - perhaps a typo in emcc's  -s X=Y  notation?
 - (see src/settings.js for valid values)
[427/442] Building CXX object third_party/imgui/tnt/CMakeFiles/imgui.dir/__/imgui.cpp.o
ninja: build stopped: subcommand failed.

**Comment by prideout** [comment]
Our continuous builds are pinned to commit `1b1f08f` of the emsdk.  I'll try updating it to see what happends.

**Comment by prideout** [comment]
I've reproduced this, it is indeed an issue with newer versions of the EMSDK.

**Comment by prideout** [comment]
Indeed this feature was removed:
https://github.com/emscripten-core/emscripten/pull/11037

I also discovered that `--post-js` is (sort of) deprecated in favor of `--extern-post-js`.
https://github.com/emscripten-core/emscripten/issues/6814

I'm currently investigating these issues, meanwhile our clients need to use an older EMSDK using the same version that is mentioned in our `BUILDING.md` instructions.
