### ISSUE TITLE
Failed to build android on Windows

### ISSUE THREAD

**Issue by geroge-d** [google/filament#2516]
Succeed in building windows version. But when i compile for android on windows system. see error log below:
In file included from ../../third_party/spirv-tools/source/opt/redundancy_elimination.cpp:15:
In file included from ../../third_party/spirv-tools\source/opt/redundancy_elimination.h:20:
In file included from ../../third_party/spirv-tools\source/opt/ir_context.h:29:
In file included from ../../third_party/spirv-tools\source/assembly_grammar.h:20:
In file included from ../../third_party/spirv-tools\source/operand.h:21:
In file included from ../../third_party/spirv-tools\source/table.h:18:
../../third_party/spirv-tools\source/extensions.h:27:10: fatal error: 'extension_enum.inc' file not found
#include "extension_enum.inc"
         ^~~~~~~~~~~~~~~~~~~~

**Comment by romainguy** [comment]
It's a file generated at build time. @bejado could you take a look please?

**Comment by bejado** [comment]
Can you show the output of the `cmake` command?

**Comment by amadlover** [comment]
Hello.

I am facing the same issue on windows 10, visual studio 2019.

[525/734] Building CXX object third_party/spirv-tools/source/opt/CMakeFiles/SPIRV-Tools-opt.dir/basic_block.cpp.o
FAILED: third_party/spirv-tools/source/opt/CMakeFiles/SPIRV-Tools-opt.dir/basic_block.cpp.o
C:\Users\nihal\AppData\Local\Android\Sdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android21-clang++.cmd  -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -I../../third_party/spirv-tools -I../../third_party/spirv-tools/include -I../../third_party/spirv-tools/external/SPIRV-Headers/include -Ithird_party/spirv-tools -DANDROID -fPIE -mcpu=cortex-a57 -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -fPIC   -Wextra-semi -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-self-assign -Werror -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -ftemplate-depth=1024 -std=gnu++11 -MD -MT third_party/spirv-tools/source/opt/CMakeFiles/SPIRV-Tools-opt.dir/basic_block.cpp.o -MF third_party\spirv-tools\source\opt\CMakeFiles\SPIRV-Tools-opt.dir\basic_block.cpp.o.d -o third_party/spirv-tools/source/opt/CMakeFiles/SPIRV-Tools-opt.dir/basic_block.cpp.o -c ../../third_party/spirv-tools/source/opt/basic_block.cpp
In file included from ../../third_party/spirv-tools/source/opt/basic_block.cpp:15:
In file included from ../../third_party/spirv-tools\source/opt/basic_block.h:29:
In file included from ../../third_party/spirv-tools\source/opt/instruction.h:25:
In file included from ../../third_party/spirv-tools\source/opcode.h:20:
In file included from ../../third_party/spirv-tools\source/table.h:18:
../../third_party/spirv-tools\source/extensions.h:27:10: fatal error: 'extension_enum.inc' file not found
#include "extension_enum.inc"
         ^~~~~~~~~~~~~~~~~~~~

Please tell me if should open a new issue for this? 

Also please tell me if you need more information.

Best regards.
Nihal Kenkre.

**Comment by bejado** [comment]
@amadlover Typically, SPIR-V problems on Windows are related to Python. Please make sure you have Python 3 installed and accessible in the command prompt. Can you also show the output of running `cmake`?

**Comment by amadlover** [comment]
Hello.

I built filament with ubuntu 20.04 on wsl2. Using the ./build.sh "easy" build script. It was easy!! 

Thank you for taking the time to reply and thank you for this library.

And the documentation which can be a reference text book.

Best regards
Nihal Kenkre.
