### ISSUE TITLE
Visual differences in materials compiled with and without optimization 

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2524]
I use filamat-lite to do runtime material compilation and I've been assuming that there will be no  difference between the appearance and performance of the materials. However, when I compile a skybox texture I get blocky sampling artefacts when optimization is disabled vs smooth interpolation when optimization is enabled.

Is this expected behaviour or should I post more information?

**Comment by romainguy** [comment]
What do you mean by “when I compile a skybox texture”? Skybox is precompiled as part of Filament and filamat doesn’t do anything to textures

**Comment by rawnsley** [comment]
For legacy reasons I'm using a custom skybox like this:

```
material {
    name : skyboxEquirect,
    parameters : [
        { type : sampler2d, name : skybox }
    ],
    variables : [ eyeDirection ],
    vertexDomain : device,
    depthWrite : false,
    shadingModel : unlit,
    variantFilter : [ skinning ]
}

vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        float3 p = getPosition().xyz;
        float3 u = mulMat4x4Float3(getViewFromClipMatrix(), p).xyz;
        material.eyeDirection.xyz = mulMat3x3Float3(getWorldFromViewMatrix(), u);
    }
}

fragment {

    const vec2 normVector = vec2(1.0 / (2.0 * PI), 1.0 / PI);

    void material(inout MaterialInputs material) {
        prepareMaterial(material);

        // Eye direction comes in such that azimuth zero is backwards, which means forwards is Pi
        // This maps to texture parameter 0.5, which is the middle of the image and the presumed default direction

        // Normalize the eye direction
        vec3 eyeNorm = normalize(variable_eyeDirection.xyz);

        // Convert eye vector to polar coordinates in the range [-0.5, +0.5], [0, 1]
        vec2 radAzPol = vec2(-atan(eyeNorm.x, eyeNorm.z), acos(eyeNorm.y)) * normVector;

        material.baseColor = texture(materialParams_skybox, radAzPol);

    }
}
```
To which I provide a screen quad.

**Comment by romainguy** [comment]
Do you have screenshots of what happens when it fails? And on what device? There should be no difference between unoptimized and optimized shaders. But we do use the optimizer in the hope to work around many driver bugs on old hardware. Is there any chance you can use a precompiled material for your skybox?

**Comment by rawnsley** [comment]
Here are the optimized and non-optimized versions:

![optimized](https://user-images.githubusercontent.com/303516/81723576-f4129180-947a-11ea-9982-ad2b107e0b0b.png)

![nonoptimized](https://user-images.githubusercontent.com/303516/81723601-fbd23600-947a-11ea-9b06-93b6e731ec72.png)

The difference is more pronounced in VR. This is on a Pocophone F1 and I get the same issue on Adreno and Mali VR headsets.

I have been using a precompiled shader, but I want to move to compiling everything at runtime to break the compile-time dependency on matc, which is making it tricky to go backwards-and-forwards in my version history independent of the Filament version history.

I'll probably just switch to the Filament Skybox component, although I have a mix of cube maps (which are supported) and equirectangular images (which aren't supported) so I'll need to do something about that.

All the VR SDKs that I target have built-in support for skybox layers anyway because they can be lens corrected more accurately that way. I'll be switching to use them eventually anyway so it is not high priority to fix.

**Comment by romainguy** [comment]
Definitely looks like a driver shader compiler bug and we can't really do much about it :/

**Comment by pixelflinger** [comment]
> Definitely looks like a driver shader compiler bug and we can't really do much about it :/

Isn't it strange, though, that this would happen on both Adreno and Mali headsets?

@rawnsley are you sure that the *only* difference is matc optimization option? It looks like bilinear filtering is off in the 2nd case.

**Comment by romainguy** [comment]
I thought about that but I’m not so sure it’s point sampling.

**Comment by rawnsley** [comment]
@pixelflinger Apologies - it's not happening on Mali (I got confused with devices and versions). It is only happening on Adreno and very likely a driver bug.

The only difference in code is the switch between PERFORMANCE and NONE in the MaterialBuilder.Optimization flag.

**Comment by pixelflinger** [comment]
We have noticed recently issues with bilinear filtering on Adreno when using Vulkan.

**Comment by pixelflinger** [comment]
not actionable / shader compiler bug.
