### ISSUE TITLE
obj file vertexBuffer update.

### ISSUE THREAD

**Issue by jiqimaogou** [google/filament#2540]
I read a mesh from filamat which is converted by obj file.
```
MeshReader::Mesh mesh;
mesh = MeshReader::loadMeshFromFile(mEngine, Path(filename), g_materialInstances);
```

than I want to update the vertice buffer with new vertices:

```
        mesh.verticeBuffer->setBuffer(
            *mEngine,
            VerticeBuffer::BufferDescriptor(triangles, size));
```

the vertices count is equals to the vertices in obj file. but it works wrong.

the flamat process the vertice.

    const aiScene* scene = importer.ReadFile(src,
            // normals and tangents
            aiProcess_GenSmoothNormals |
            aiProcess_CalcTangentSpace |
            // topology optimization
            aiProcess_FindInstances |
            aiProcess_OptimizeMeshes |
            aiProcess_JoinIdenticalVertices |
            // misc optimization
            aiProcess_ImproveCacheLocality |
            aiProcess_PreTransformVertices |
            aiProcess_SortByPType |
            // we only support triangles
            aiProcess_Triangulate);

the vertice is changed and is not compatible with the raw vertice.

**Comment by romainguy** [comment]
Is the problem that the optimization performed by `filamesh` changes the vertex count from your original file? If so, I would recommend using a different format. Filamesh was designed specifically to create smaller meshes not to preserve the original topology.
