### ISSUE TITLE
Scene Leak in ImGuiHelper.cpp

### ISSUE THREAD

**Issue by teub** [google/filament#2542]
**Describe the bug**
A Scene is created in ImGuiHelper.cpp and the pointer is never deleted.
This result in a Scene leak for each view the helper is used on when closing the engine.

I could provide more details but the leak seems to be clear in the ImGuiHelper constructor; also I checked it was still there on master : https://github.com/google/filament/blob/master/libs/filagui/src/ImGuiHelper.cpp

`
    // Create a scene solely for our one and only Renderable.
    Scene* scene = engine->createScene();
    view->setScene(scene);
    EntityManager& em = utils::EntityManager::get();
    mRenderable = em.create();
    scene->addEntity(mRenderable);

`

**Comment by romainguy** [comment]
Objects created via `engine->create*()` are automatically cleaned up when the engine is shutdown.
