### ISSUE TITLE
Memory leaks related to MetalFence and TimerQueryFence.

### ISSUE THREAD

**Issue by vpopovyc** [google/filament#2547]
**Describe the bug**
Memory leaks related to MetalFence and TimerQueryFence.

https://github.com/google/filament/commit/27f4504dfc027f3187446835fd5ed679ffe7594b introduced ```TimerQueryFence``` with 
```void TimerQueryFence::beginTimeElapsedQuery(MetalTimerQuery* query)``` and 
```void TimerQueryFence::endTimeElapsedQuery(MetalTimerQuery* query)```.
In both implementations ```MetalFence``` is allocated like 
```auto* fence = new MetalFence(mContext);```
and deleted like
```delete fence;``` in ```fence.onSignal``` closure.

So the issue is, imo, that ```fence.onSignal``` sometimes isn't called.

As a result, almost on each frame that pair leaking some memory.

**To Reproduce**
You can easily reproduce that by launching any sample app(I used hello-pbr) for iOS, turn on ```Malloc Stack```, launch app on device and click ```Debug Memory Graph```.

**Expected behavior**
No leaks, I think.

**Screenshots**
<img width="1920" alt="Screenshot 2020-05-18 at 17 30 13" src="https://user-images.githubusercontent.com/24235281/82225037-49dcb300-992d-11ea-94c7-3be5b0da12a2.png">

<img width="1058" alt="Screenshot 2020-05-18 at 17 32 47" src="https://user-images.githubusercontent.com/24235281/82225268-a9d35980-992d-11ea-8eb6-dd86fe36186f.png">

**Smartphone (please complete the following information):**
 - OS: [iOS 13.4]
 - GPU: [AGXA10Device]
 - Backend: [Metal]

**Comment by bejado** [comment]
Thanks for the report. Indeed, those fences are not being encoded and thus the `onSignal` callback is never called.
