### ISSUE TITLE
alpha region of texture is dark.

### ISSUE THREAD

**Issue by minus31** [google/filament#2560]
Describe the bug
When blendingmode is Transparent, textures' boundary is dark.(please see the capture below)

I rendered a 3D object and put a texture in png format onto the object. But when I set filament::Shading::UNLIT and filament::BlendingMode::TRANSPARENT, the texture's alpha region is dark. I used filament 1.5.2. I wonder why it happens.

To Reproduce
Here is the code that I use.

c++
builder.name("DefaultMaterial")
            .platform(filamat::MaterialBuilderBase::Platform::MOBILE)
            .require(filament::VertexAttribute::UV0)
            .parameter(filamat::MaterialBuilder::SamplerType::SAMPLER_2D, "baseColorMap")
            .shading(filament::Shading::UNLIT)
            .blending(filament::BlendingMode::TRANSPARENT)
            .material(R"SHADER(
             void material(inout MaterialInputs material) {
                prepareMaterial(material);
                material.baseColor = texture(materialParams_baseColorMap, getUV0());
             }
             )SHADER");

Screenshots
![](https://www.dropbox.com/s/icierxd4hrq2p7k/1589939103763.jpg?raw=1)

Desktop (please complete the following information):
 - OS: IOS
 - GPU: Intel Iris Pro 1536 MB
 - Backend: OpenGL

Smartphone (please complete the following information):
 - Device: LG V60
 - OS: Android

**Comment by romainguy** [comment]
Filament works in premultiplied alpha. If your image loader doesn't do it for you, you need to do it in your shader: material.baseColor.rgb *= material.baseColor.a
