### ISSUE TITLE
Future plans on Android as a platform and eventually updating Sceneform

### ISSUE THREAD

**Issue by Consti10** [google/filament#2564]
A lot of methods in [RenderableInternalFilamentAssetData](https://github.com/google-ar/sceneform-android-sdk/blob/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform/rendering/RenderableInternalFilamentAssetData.java) are just declared with the comment
`// Not Implemented`
And since the repo's status is now 'Archived' this raises the question if our team should continue using Sceneform. Personally I am a big fan of Sceneform and I also like the decision making it OS, but since filament-android is still receiving updates I am wondering if you have any plans migrating sceneform to the latest filament-android release(s).

**Comment by romainguy** [comment]
Unfortunately Sceneform is owned by a different team. I would love to see Sceneform move to a more recent version of Filament, and you can certain do so yourself by downloading the source. You may try to file a feature request on Sceneform's GitHub issue tracker too.

**Comment by Consti10** [comment]
Unfortunately since Sceneform was archived It doesn't allow creating / answering issues nor push requests. 
[link](https://github.com/google-ar/sceneform-android-sdk)
