### ISSUE TITLE
vulkan fails with error after pull request 

### ISSUE THREAD

**Issue by neshume** [google/filament#2565]
After merge commit Commit 65e286e7
by Philip Rideout, 05/20/2020 02:47 AM
committed 05/20/2020 03:58 AM

vulkan fails with :

FEngine (64 bits) created at 0x7f032578d010 (threading is enabled)
FEngine resolved backend: Vulkan
Selected physical device 'Quadro P2000' from 1 physical devices. (vendor 0x0x10de, device 0x0x1cba, driver 0x0x6e100000, api 1.1)
VULKAN ERROR: (Validation) Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x7f031c55fde0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid SPIR-V binary version 1.3 for target environment SPIR-V 1.0 (under Vulkan 1.0 semantics).

**Comment by romainguy** [comment]
This should be fixed by #2563

**Comment by neshume** [comment]
got it. makes sense.

**Comment by neshume** [comment]
just one question... should i merge it by myself to my fork or wait for the merge into master?

**Comment by romainguy** [comment]
Up to you but I expect the fix to be merged today.

**Comment by neshume** [comment]
of course. thx closed.
