### ISSUE TITLE
Object with screen-space refraction gets rendered on top

### ISSUE THREAD

**Issue by ast3rX** [google/filament#2576]
**Describe the bug**
Objects with screen-space refractive materials get rendered on top of the scene without respecting depth information. Cubemap-based refraction is behaving as expected.

**To Reproduce**
1. Create a scene with multiple objects.
2. Assign a material to one of them which has screen-space refraction mode enabled.
3. The refractive material gets rendered on top of the viewport without taking the depth into consideration.

**Expected behavior**
The same behavior as cubemap refraction, otherwise the feature would be unusable in multi-object scenes.

**Desktop (please complete the following information):**
 - OS: iOS
 - Backend: OpenGL

**Comment by romainguy** [comment]
Do you have a screenshot you can share please? Refraction objects are rendered after opaque objects but before transparents, and they should respect depth testing unless you turn that off. I'll try tomorrow to see if I can repro. Could you also share your material file please?

**Comment by ast3rX** [comment]
I have created a basic scene that demonstrates the issue. There is no transparency involved, SSAO is disabled.

![refraction03](https://user-images.githubusercontent.com/743329/82654633-e3c68900-9bd5-11ea-8c41-1d91971ee3a1.jpg)
![refraction02](https://user-images.githubusercontent.com/743329/82654637-e45f1f80-9bd5-11ea-9dba-9a6075b23e99.jpg)
![refraction01](https://user-images.githubusercontent.com/743329/82654638-e4f7b600-9bd5-11ea-843b-5fa62f84e329.jpg)

An example for the refractive material:

```
material {
  name : transparentBMaterial,
  shadingModel : lit,
  refractionType : solid,
  refractionMode : screenspace,
  parameters : [
  // baseColor
    {
      type : float3,
      name : baseColor
    },
  // roughness
    {
      type : float,
      name : roughness,
      default: 0.0
    },
  // transmission
    {
      type : float,
      name : transmission,
      default: 0.0
    },
  // ior
    {
      type : float,
      name : ior,
      default: 1.5
    },
  // microThickness
    {
      type: float,
      name: microThickness,
      default: 0.0
    },
  // thickness
    {
      type: float,
      name: thickness,
      default: 0.5
    },
  // absorption
    {
      type: float3,
      name: absorption,
      default: 0.5
    }
  ]
}
fragment {
  void material(inout MaterialInputs material) {
    prepareMaterial(material);
    material.baseColor.rgb = materialParams.baseColor;
    material.roughness = materialParams.roughness;
    material.transmission = materialParams.transmission;
    material.ior = materialParams.ior;
    material.thickness = materialParams.thickness;
    material.absorption = materialParams.absorption;
  }
}
```

**Comment by romainguy** [comment]
Thank you! I can reproduce the issue, it looks like our refracted objects are always drawn after all the opaque objects. Instead the refracted pass should be triggered once all the objects behind the first refracted object are drawn.
