### ISSUE TITLE
How to intergrate NVPR(Nvidia Path Rendering)?

### ISSUE THREAD

**Issue by ewayboy** [google/filament#2584]
I'm working on some path rendering using NVPR. And I want to porting it to Filament, but since it don't have any vertex and indices. How can i draw it with native gl calls?
I don't care about the solution being cross-platform. I just need it to work on Windows/OpenGL.

**Comment by romainguy** [comment]
If you are talking about the `NV_path_rendering` extension we are not going to support it. We also do not expose the backends (GL, etc.) directly on purpose. You are welcome to modify the APIs for your own needs though. Note that you can do path rendering without using custom vendor extensions.
