### ISSUE TITLE
Add support for "transparent" shadows

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2585]
I tried to simulate casting shadows of an eyeglasses to a virtual ground using groundShadow.mat sample but I can't find a way to distinguish the eyeglasses' "frame" and "glass" shadow parts since they use a unified "alpha" value to determine the shadow strength. Is there some way to make "transparent" glasses' shadow more lighter than the frame's?   Thanks a lot~

**Comment by romainguy** [comment]
There isn't a way to make shadows for transparent objects at this time, at least not shadows that look different from regular shadows.

**Comment by vcxyk** [comment]
> There isn't a way to make shadows for transparent objects at this time, at least not shadows that look different from regular shadows.

hi  romainguy, thanks for your reply! Is it practical for filament to use a RG texture for shadow depth map instead of a gray-scale texture in which R channel stores the shadow-caster's depth component and G channel stores the opacity/intensity of the shadow considering the caster's transparency?    It looks a bit weird now for the ground to  receive a hard shadow from  a highly transparent glasses.

**Comment by romainguy** [comment]
It's not that it's impractical but it would be expensive, both in memory but also because we'd have to execute the material for those objects. It also wouldn't match the transparent's color. We usually just disable shadows for transparent objects. Anyway it's something we'd like to support eventually it's just not a priority right now.

**Comment by romainguy** [comment]
I have an experiment available for this: https://github.com/google/filament/pull/3298

**Comment by romainguy** [comment]
Note that the PR linked above needs "blurry" variance shadow maps to be truly useful. @pixelflinger is currently working on implementing this feature. Once it goes it, we'll add the transparent shadows feature.
