### ISSUE TITLE
Is there a way to change weights of glTF blendshape model by every frame.

### ISSUE THREAD

**Issue by minus31** [google/filament#2596]
I load **glTF model** which blend shape weights are applied. And I want to change **the weights** by every frame. Does filament support this feature?

I know  a 3d model created with `filament::RenderableManager::Builder()` function is able to be handled with `setMorphWeights(instance, weights)`. 

**OS and backend**
   Android, OpenGL

**Comment by romainguy** [comment]
The `gltio` APIs expose all the underlying entities. You can query their `Renderable` components and set the morph weights programmatically from there. @prideout, does this seem right to you? Do we have an easy way to look up a renderable node by name?

**Comment by prideout** [comment]
Romain is correct, clients can call `FilamentAsset::getEntities()`, query each one's name using `FilamentAsset::getName()`, then use `RenderableManager::setMorphWeights()`.

One idea to make this easier would be to add a `getByName()` method.  One gotcha is that names need not be unique, so it might need to return a list.

Let's leave this bug open until we add an API that makes this process a bit easier.

**Comment by minus31** [comment]
Thanks a lot! For now I am in trouble with using `FilamentAsset::getName()` because  it doesn't give Name(gives null value) but I would try more. And if there is an easy way to call renderable node, that would be awesome! Thank you for replying.

**Comment by prideout** [comment]
Closing because `setMorphWeights` is already available and `getEntityByName` will be available in #2622.
