### ISSUE TITLE
how to pass cubemap to filamat?

### ISSUE THREAD

**Issue by jakkypan** [google/filament#2603]
![image](https://user-images.githubusercontent.com/15864446/83085245-f94c1f00-a0bd-11ea-8ea4-cd0a1e948908.png)

i have known how to use cubemap in mat, but how to pass textures to the parameters  **samplerCubemap**, do I need to pass six textures or just one texture that have six faces?

if possible,can show me the sample code? thanks.

**Comment by romainguy** [comment]
You have to pass a single cube texture. See this example here: https://github.com/google/filament/blob/master/libs/filamentapp/src/IBL.cpp#L144

You need to set the texture's sampler type to `Texture::Sampler::SAMPLER_CUBEMAP` and pass `FaceOffsets` to `Texture::setImage()`. The `FaceOffsets` structure indicates where the data of each cube face is in the `PixelBufferDescriptor`.
