### ISSUE TITLE
How to set a custom filamat material to one of glb submesh's material to play video from a mediaplayer

### ISSUE THREAD

**Issue by balarayen** [google/filament#2616]
In Android, I want to load an animated GLB file and display video from a mediaplayer on it's front face. I see the android sample hellocam which sets a custom material on a custom rendered object. But is it possible to change the material of a GLB FilamentAsset to set the ExternalTexture with a filamat/matc videoTexture param to display the video from a mediaPlayer?

**Smartphone :**
 - Device: Pixel 2
 - OS: Android 10

Please give some pointers.

**Comment by romainguy** [comment]
You can request the list of entities from your `FilamentAsset`, iterate over them to find the one that has for instance the correct name and then set its material using `RenderableManager`. You would need to supply your own material though, our glTF materials are not setup to receive external textures.

**Comment by steven-gao** [comment]
> In Android, I want to load an animated GLB file and display video from a mediaplayer on it's front face. I see the android sample hellocam which sets a custom material on a custom rendered object. But is it possible to change the material of a GLB FilamentAsset to set the ExternalTexture with a filamat/matc videoTexture param to display the video from a mediaPlayer?
> 
> **Smartphone :**
> 
> * Device: Pixel 2
> * OS: Android 10
> 
> Please give some pointers.

hello ,balarayen,see you again, how to render a local video to a model? thank you
