### ISSUE TITLE
Unable to figure out where to start.

### ISSUE THREAD

**Issue by vivasvan1** [google/filament#2620]
Hi there.

I want to build an android application using filament but I am having trouble how to start.
I have seen the hello triangle in android/samples but I am still having an issue on how to begin with filament and how to **compile and run**.

Would appreciate if someone could guide me on how to compile and run the examples.
Thank you

**Comment by prideout** [comment]
Have you seen this medium post?

https://medium.com/@philiprideout/getting-started-with-filament-on-android-d10b16f0ec67

**Comment by prideout** [comment]
Or, if you prefer working with GitHub source, consult our README's.  Note that there is some extra information in the Android samples README:

https://github.com/google/filament/tree/master/android/samples

**Comment by vivasvan1** [comment]
Thank you so much for the medium post <3!
