### ISSUE TITLE
Change vertex position in vertex shader

### ISSUE THREAD

**Issue by kpeeters** [google/filament#2624]
I have a material with `vertexDomain: device`, in which I want to apply some transformation to the vertex positions. I tried (example code only, this is obviously not the transformation I want to apply)

    vertex {
        void materialVertex(inout MaterialVertexInputs material) {
             gl_Position = getPosition()*2.0;
        }
    }

but that does not seem to have any effect. Where should I stick this transformation? Thanks!

**Comment by prideout** [comment]
In the device domain, vertex position can be manipulated by setting `material.clipSpaceTransform` to a mat4 of your choice.
