### ISSUE TITLE
Android lifecycle management

### ISSUE THREAD

**Issue by kpeeters** [google/filament#2632]
None of the Android examples seem to contain onPause/onResume handlers, which suggests that Filament 'knows' how to deal with a possible loss of GL context in such a pause/resume cycle. Is that a correct assumption, or should I do anything myself in addition? (apart, of course, from stopping any animation/choreographer callbacks).

**Comment by romainguy** [comment]
There's nothing for Filament to do in onPause/onResume. Context loss isn't a thing (or at least hasn't been for a very, very long time), the only thing you need to deal with is losing the underlying surface which is already shown in the examples/handled by UiHelper.
