### ISSUE TITLE
How to add gui buttons to filament application?

### ISSUE THREAD

**Issue by vivasvan1** [google/filament#2633]
I am sorry if this is the wrong place for this.

I want to add a button to browse and import any downloaded glb/gltf model directly on my phone.
I am not sure how to add GUI to Surface View.
Does filament support such functionality?

Can you guide what files to edit or stuff to look into for this?

Thanks,
vivasvan

**Comment by romainguy** [comment]
You could write your own GUI, or use something like ImGui (we have a native library to integrate ImGui with Filament, you can find it in `libs/filagui` in the source tree). But in your case it would be much simpler to just use the Android UI toolkit. You can add buttons either on top of or around your SurfaceView, and this has nothing to do with Filament.
