### ISSUE TITLE
Does filament support STL format?

### ISSUE THREAD

**Issue by vivasvan1** [google/filament#2634]
I am artist and wanted to know what formats does filament supports? I am interested in STL and how to load it with filament?

what i know:
I need to convert my .obj/.fbx to .filamesh on my pc and then i can use loadMesh()
Or i can import glb/gltf format directly with modelViewer.loadModelGltf() function.

Is it possible to convert .obj/.fbx to .filamesh directly on Android phone without pc.

Thank you
Vivasvan

**Comment by romainguy** [comment]
Filament itself doesn't know about file formats. It just accepts raw vertices for the GPU. We do provide a library called `gltfio` to load glTF models easily. For other formats such as .obj or .stl you'd have to provide your own loader. For instance https://github.com/javagl/Obj.

**Comment by vivasvan1** [comment]
I understand this .. <3
