### ISSUE TITLE
Video texture is applied perpendicular to a plane object

### ISSUE THREAD

**Issue by balarayen** [google/filament#2642]
**Describe the bug**
In android, when rendering a video on a glb plane object, the video texture seems to rendered perpendicular to the plane surface(a row of video texture edge is applied to the whole plane).

Rotating the texture UV is not helping as it is still perpendicular to the object. Rotating the object is also not working.

How to overcome this issue? Please help.

**Screenshots**
![Video on a plane](https://user-images.githubusercontent.com/15100341/83773011-a49e3a80-a6a1-11ea-9993-74b4596f50e0.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10

**Additional context**

`video.mat`

```
material {
    name : lit,
    shadingModel : lit,
    doubleSided  : true,
    variables : [
        uv
    ],
    parameters : [
        {
            type : float3,
            name : baseColor
        },
        {
            type : float,
            name : roughness
        },
        {
            type : float,
            name : metallic
        },
        {
            type : samplerExternal,
            name : videoTexture
        },
        {
            type : mat4,
            name : textureTransform
        }
    ],
}

vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        material.uv = 0.5 * (getPosition() + vec4(1));
    }
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.roughness = materialParams.roughness;
        material.metallic = materialParams.metallic;

        vec2 uv = (materialParams.textureTransform * vec4(variable_uv.xy, 0, 1)).xy;
        uv.x = 1.0 - uv.x;
        material.baseColor.rgb = texture(materialParams_videoTexture, uv).rgb;
    }
}

```

**Comment by romainguy** [comment]
It looks like the way you compute the UVs is wrong. You are seeing the result of UVs out of 0..1 range being clamped by the texture sampler. Instead of doing `material.uv = 0.5 * (getPosition() + vec4(1));` I would recommend just assigning UVs to your mesh and using those directly.
