### ISSUE TITLE
Vulkan+Android exhibits bad texturing for all stages > 0

### ISSUE THREAD

**Issue by prideout** [google/filament#2643]
After modifying sample-gltf-viewer to use Vulkan, base color looks ok but other textures like occlusion-roughness-metallic are completely wrong.  It looks fine on MoltenVK, and there are no validation warnings.

**Comment by romainguy** [comment]
Could it be a linear vs sRGB sampling issue?

**Comment by prideout** [comment]
No it's very very wrong, like the descriptor set isn't getting honored.  Strange that it is Android only.
