### ISSUE TITLE
Import Animation .glb files to existing glb model?

### ISSUE THREAD

**Issue by jfson** [google/filament#2654]
**Describe the bug**
I have two .glb file,then parse them to two Renderables(A,B),

the Renderables A use to ModelViewer.
the Renderables B parse one animations.
what should i do to use B's aimations in A ModelViewer? 

I try to use B‘s  animator  applyAnimation() , the animtion stop and cant play B's animation

may be this problem shoule be write in feature。。。

**Comment by jfson** [comment]
There is a need to separate skeletal GLB from animated GLB and combine them when used.

**Comment by prideout** [comment]
If I understand correctly, you have two GLB files and you would like to apply the animation defined in file A to the model defined in file B.

I'm not sure this feature is in scope for gltfio.

Maybe you could write a tool that consumes assets A and B and produces a new asset C, which you would then render using gltfio + Filament.

Don McCurdy has created a library for doing these sorts of things:
https://github.com/donmccurdy/glTF-Transform

**Comment by jfson** [comment]
yes...That's the question。i don't want to make too much animation in one GLB file, cause contains bones material GLB file A file is much bigger than not has bones nodes GLB file B , the file B just contains animation ...so that we can save memory，and more flexible to combination bones nodes with different animator... I try to change the code ,parse the file B and  animation ,  when i try to applyAnimation()  ,it is doesn't work...  I’m glad hope you can help to make sure whether gltfio can support this feature in java layer...if you want no more about this feature ,you can search about iOS  
SceneKit , this feature is very necessary~ hope message form you ~  thx very much~

**Comment by jfson** [comment]
I've tried with filament in android/smaple/sample-gltf-viewer demo... 

first of all ,load file A to ModelViewer and let A.applyAnimation() ,the animation is ok, cache A'animator in memory, then load file B and applyAnimation() ,B's animation is ok too, however ,when i use the cache animation of A, it doesn't work...

just wanna play different animation  in same bones, a file with bones and animations about 4MB, the same animations without bones file about 1MB, 

 much glad to see your message about whether gltfio can support this problem~

o.0

**Comment by prideout** [comment]
I have an idea that might help your optimization problem.  Usually, `.glb` files are self contained and do not reference external files.  In your case however, I think you should get your bone data from an external `bin` file, similar to how `.gltf` files work.  This would be similar to re-using a Texture among several assets.

Currently, I think `ResourceLoader` evicts eagerly, but we should make it configurable.  At the very least, you will be improving your archive size.  What do you think of this idea?

**Comment by jfson** [comment]
Pretty good idea ! 

Currently,Most of Applications need add different model .glb or .glft files ,  In fact to users , There is  also need just one model with different animations.

Usually  use a file which contains bones with T post(no animation) ,  And all the animations in one or more other files.  When the bones  load success, The animations will be add to it, we can also load more animations form net instead of reload file which contains bones. 

That's don't look friendly to mobile's users when we load repetition  big file form net. If we wanna make it configurable. It will be a great feature in filament. 

 I have some suggestions from work about what should be config
*  1.whether can load file only bones (model with T POSE)
*  2.whether can load file only animations
*  3.whether can load common file which contains bones and animations
*  4.whether can combine bones and animations form different files
*  5.replace different bones


Thanks muuuuuch for your time ~ What do you think of this suggestions ?

**Comment by Keshav300501** [comment]
How can I import gltf file format and .anime format separately in android studio using filament.

**Comment by jfson** [comment]
> How can I import gltf file format and .anime format separately in android studio using filament.
It seems to only be able to import file from one .glb file

**Comment by prideout** [comment]
I think we should close this issue since gltfio is an importer rather than a compositional framework.

However, I do think that `ResourceLoader` could have better support for re-use of external resources such as textures and buffers (the latter potentially containing bone data) in order to optimize memory footprint and load time.  If that sounds like a good idea, feel free to create a feature request, ideally with example assets attached to the issue.

**Comment by prideout** [comment]
@Keshav300501  I am not familiar with the `.anime` file format or how it relates to glTF.
