### ISSUE TITLE
getUV0() for an ExternalTexture always returns zero

### ISSUE THREAD

**Issue by balarayen** [google/filament#2659]
In Android, loaded a plane from a glb file and when applying a material instance with video from an ExternalTexture, the video is not rendered edge to edge of the plane. It looks like this:

![filament_video_render_issue](https://user-images.githubusercontent.com/15100341/84154575-ec97d580-aa84-11ea-8b0a-2bfa06ca0521.png)

The actual video is here:
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4

The plane's vertices are like this(not unit vec3) and as you can see it is not symmeterical at origin:
```
o Plane
v -3.449268 0.000000 2.000000
v 4.636948 0.000000 2.000000
v -3.449268 0.000000 -2.975009
v 4.636948 0.000000 -2.975009
vt 0.000000 0.000000
vt 1.000000 0.000000
vt 1.000000 1.000000
vt 0.000000 1.000000
vn 0.0000 1.0000 0.0000
```

Inspired from the `lit.mat` from `sample-hello-camera`, used getPosition() to convert it into uv(0 to 1). But this getPosition() method will work only if the vertices fall within -1 to +1.

My actual glb is complicated and it cannot be easily reduced to -1 to +1. So I tried using the getUV0() to get external texture material as it isn't but it always returns 0,0.

1. Am I missing something for getUV0() to work properly? Any reference will help.
2. Or how to make the video texture display edge to edge irrespective of the vertices and scale?

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10.0

Please clarify.

**Comment by balarayen** [comment]
Here is the full mat file:

```
material {
    name : lit,

    shadingModel : lit,

    doubleSided  : true,

    blending : masked,

    flipUV : false,

    variables : [
        uv
    ],

    requires : [
        position,
        uv0
    ],

    parameters : [
        // The color must be passed in linear space, not sRGB
        {
            type : float3,
            name : baseColor
        },
        {
            type : float,
            name : roughness
        },
        {
            type : float,
            name : metallic
        },
        {
            type : samplerExternal,
            name : videoTexture
        },
        {
            type : mat4,
            name : textureTransform
        },
        {
            type : int,
            name : plane
        },
        {
            type : bool,
            name : enableChromaKey
        },
        {
            type : float4,
            name : keyColor
        }
    ],
}

vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        material.uv = 0.5 * (getPosition() + vec4(1));
    }
}

fragment {
    vec3 desaturate(vec3 color, float amount) {
        // Convert color to grayscale using Luma formula:
        // https://en.wikipedia.org/wiki/Luma_%28video%29
        vec3 gray = vec3(dot(vec3(0.2126, 0.7152, 0.0722), color));

        return vec3(mix(color, gray, amount));
    }

    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.roughness = materialParams.roughness;
        material.metallic = materialParams.metallic;

        vec2 uv;
        if (materialParams.plane == 1) {
            uv = (materialParams.textureTransform * vec4(variable_uv.xz, 0, 1)).xy;
        }
        else if (materialParams.plane == 2) {
            uv = (materialParams.textureTransform * vec4(variable_uv.yz, 0, 1)).xy;
        }
        else {
            uv = (materialParams.textureTransform * vec4(variable_uv.xy, 0, 1)).xy;
        }

        vec4 color = texture(materialParams_videoTexture, uv).rgba;

        if (materialParams.enableChromaKey) {

            vec3 keyColor = materialParams.keyColor.rgb;

            float threshold = 0.675;
            float slope = 0.2;

            float distance = abs(length(abs(keyColor - color.rgb)));
            float edge0 = threshold * (1.0 - slope);
            float alpha = smoothstep(edge0, threshold, distance);
            color.rgb = desaturate(color.rgb, 1.0 - (alpha * alpha * alpha));

            material.baseColor.a = alpha;
            material.baseColor.rgb = inverseTonemapSRGB(color.rgb);
            material.baseColor.rgb *= material.baseColor.a;
        }
        else {
            material.baseColor = color;
        }
    }
}

```

**Comment by balarayen** [comment]
Problematic plane:
[blender_plane4.glb.zip](https://github.com/google/filament/files/4752949/blender_plane4.glb.zip)

However, if I use the face of a distorted cube that has vertices higher than -1 to +1, and replace the face's dark material with video texture material, the same above shader works fine.

<img width="390" alt="distorted_cube" src="https://user-images.githubusercontent.com/15100341/84166604-bfeaba80-aa92-11ea-998e-515aa283270e.png">

![distorted_cube_video](https://user-images.githubusercontent.com/15100341/84166580-b8c3ac80-aa92-11ea-9c94-5a17778e1903.png)

The distorted cube's vertices are like this:
```
o Cube
v 1.437747 0.870455 -2.347068
v 2.000000 -1.000000 -3.000000
v 2.000000 1.000000 2.522783
v 2.000000 -1.000000 3.000000
v -2.000000 1.000000 -3.000000
v -2.000000 -1.000000 -3.000000
v -2.000000 1.000000 2.522783
v -2.000000 -1.000000 3.000000

```

**For a cube (with vertices higher than -1 to +1), it seems when rendering the video, the material texture, getPosition() is returning normalized vertices -1 to +1 (same as in GLSL vertex shader). 
But in plane it seems getPosition() vertices are not normalized, in my understanding.**

**Comment by romainguy** [comment]
UVs from glTF files should work fine, we use them all the time (and you can see them in action in our glTF samples). 

The problem you see in your first example is expected because your positions are not in -1..+1 indeed. Your texture coordinates are however, so you should use those.

**Comment by balarayen** [comment]
How to get the texture coordinates in the fragment shader? getUV0() is returning 0,0 always.

**Comment by romainguy** [comment]
`getUV0()` is the correct way. If it's always returning 0,0 there might be an issue with your glTF file. That's how this sample (`sample-gltf-viewer`) works for instance: https://github.com/google/filament/blob/master/docs/images/samples/sample_gltf_viewer.jpg

The first step would be to output your UVs as the color of your object so you can see what they look like.

**Comment by balarayen** [comment]
Thanks a ton for your time @romainguy . After adding an image texture to the glb, getting the uv values properly from getUV0(). Just with a material it was returning 0,0.

**Comment by romainguy** [comment]
I wonder if that's an optimization of the glTF exporter, or the glTF importer.

@prideout are we somehow ignoring UVs if a glTF file comes without textures? We should probably have the attribute if the data is present.

**Comment by prideout** [comment]
Yes it's quite possible we do this, UV management is more complicated than you might think because we remap the glTF UV set indices in order to try to fit them into slots 0 and 1.

**Comment by balarayen** [comment]
@prideout I'm using sceneform sdk which uses gltfio to load the glb as a FilamentAsset and created a MaterialInstance with custom shader and link to ExternalTexture for video.
I tried with 2 planes(glb), one exported from Blender and one from Cinema4D. Both had the same issue i.e, getUV0() always returned 0,0. And both get proper getUV0() when an image texture was applied before exporting.

Also please clarify why getPosition()(in the custom shader posted in the second comment) is returning absolute vertices (ranging above -1 to +1) for a Plane object, but for the face of a cube it gives normalized vertices (ranging within -1 to +1) which can be observed from the results in my first and third comment. 

For the plane the video looks zoomed out, which means absolute vertices are returned by getPosition().
For the face of a cube the video fits properly, which means normalized vertices are returned.

Below obj export shows both the Plane and the face of the cube object has vertices value above -1 to +1.

```
o Cube
v 1.437747 0.870455 -2.347068
v 2.000000 -1.000000 -3.000000
v 2.000000 1.000000 2.522783
v 2.000000 -1.000000 3.000000
v -2.000000 1.000000 -3.000000
v -2.000000 -1.000000 -3.000000
v -2.000000 1.000000 2.522783
v -2.000000 -1.000000 3.000000

```

```
o Plane
v -3.449268 0.000000 2.000000
v 4.636948 0.000000 2.000000
v -3.449268 0.000000 -2.975009
v 4.636948 0.000000 -2.975009

```

**Comment by romainguy** [comment]
Could you share your glb files please?

**Comment by balarayen** [comment]
[plane.glb.zip](https://github.com/google/filament/files/4762478/plane.glb.zip)
[cube.glb.zip](https://github.com/google/filament/files/4762477/cube.glb.zip)

Note: Cube has two materials and I set the video MaterialInstance when primitiveIndex == 1, to display the video on the top face.

**Comment by romainguy** [comment]
Ok I found the problem. Your cube mesh data is normalized in the glTF file. But there is a scale transform (2.0/2.0/3.0). Because .obj doesn't support transforms, your 3D package applies it to the vertices. But when exporting the glTF file, the transform is left as is. In Blender you can apply the transform at export time, it's an option in the glTF export panel, or you can use Ctrl-A in the viewport to apply the scale transform before export. Filament and `getPosition()` are behaving as expected here.

**Comment by romainguy** [comment]
There is one fix for us though: we need to set the UV attributes on the mesh data even if the embedded materials don't have a texture.

**Comment by balarayen** [comment]
Thanks for the details @romainguy !

**Comment by SGTjeong** [comment]
@balarayen 

Hi, Thank you in advance for bringing some issues with filament-sceneform that i am also goting through.

I am pretty new to filament, so i am having a hard time creating texture with mp4. I could barely find any source code for that.

Could you share how you built texture with video file? Any guideline would be very appreciated.

Thank you!
