### ISSUE TITLE
External texture support on older Android devices

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2660]
_sample-hello-camera_ shows us a simple way to hook up ImageReader to a Stream to a Texture, but it uses things like [Image.getHardwareBuffer](https://developer.android.com/reference/android/media/Image#getHardwareBuffer()) which is only available on SDK 28.

What's best practice for < SDK 28? (I'm specifically interested in SDK 22+)

**Comment by romainguy** [comment]
For SDK < 28 you should just use a `SurfaceTexture` instead. Create a `Stream` object that you then hook up to a `Texture` using `setExternalStream`.
