### ISSUE TITLE
Add JNI bindings for gltfio on desktop

### ISSUE THREAD

**Issue by MovementSpeed** [google/filament#2670]
I would like to be able to use gltfio using Java\Kotlin for desktop platforms (right now I'm working on Windows). Inside the Windows release, I can find bindings for Filament (filament-java.jar, filament-jni.dll) and Filamat (filamat-java.jar, filamat-jni.dll), but I can't find gltfio. Right now, I don't know how to replicate Android's ModelViewer util on desktop platforms.

**Describe the solution you'd like**
Include all libraries for each desktop platform (Windows, Linux, MacOS) to be able to use Filament completely, like on Android.

**OS and backend**
Windows, Linux, MacOS

**Comment by romainguy** [comment]
@prideout You'd need to add a directory in `java/` for `gltfio/`. You can start from the `CMakeLists.txt` in `java/filamat`.
