### ISSUE TITLE
I want to render filament and iOS OpenGL at the same time

### ISSUE THREAD

**Issue by 5gok** [google/filament#2671]
I want to render filament and iOS OpenGL at the same time.

So I created filament engine 

EAGLContext *myGLContext = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
**engine = Engine::create(filament::Engine::Backend::OPENGL, nullptr, myGLContext.sharegroup);**

But when I run my project, I got an error at **renderer->beginFrame(swapChain)** 
_**Thread 10: signal SIGABRT : “Assertion failed: (mThreadId == std::this_thread::get_id())"**_

How should I do now?

**Comment by romainguy** [comment]
Note that Filament must always be accessed from the same thread you initialized the `Engine` on.

**Comment by bejado** [comment]
Where do you call `renderer->beginFrame`? Like Romain mentioned, you're getting that assertion because you're calling a Filament method from a different thread than the one it was initialized on.

**Comment by 5gok** [comment]
It works! Thanks for your comment.
