### ISSUE TITLE
Possible AO map bug seen on AR Core

### ISSUE THREAD

**Issue by DanielSturk** [google/filament#2679]
**Describe the bug**
As I turn my mesh around, the AO map intensity seems to "blow up", pixels that were 99% white become completely dark

**To Reproduce**
Here's the glTF file https://drive.google.com/file/d/1Iq3ljA4o1QTLq-9GvDzeaoUshLoErq4R/view?usp=sharing
Here's the AO map
![dull ao](https://user-images.githubusercontent.com/2774286/84529097-d8372100-acae-11ea-860d-b09db21c2e7a.png)

**Expected behavior**
Not to see broken AO

**Screenshots**
![image](https://user-images.githubusercontent.com/2774286/84528998-ae7dfa00-acae-11ea-85cc-39a4bb1937f8.png)
![image](https://user-images.githubusercontent.com/2774286/84529014-b6d63500-acae-11ea-9c0f-d97641412798.png)

Here's a video https://drive.google.com/file/d/1AGyrLA4ind36sJZ5yMxDEDwH5ZsGBUst/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: S9, SM-G960W, Qualcomm Adreno 630
 - OS: Android
 - Backend: Google AR Core

**Comment by romainguy** [comment]
The bug doesn't happen with the current version of Filament, either in the emulator or on a device with an Adreno 630. It could be an issue either with the older version of Filament currently used by ARCore, or an issue with ARCore's own glTF loader. I'll forward the bug to them, thanks a lot for the report!
