### ISSUE TITLE
tabs for matdbg

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#2683]
It would be nice if matdbg could open shaders in a tab, so it's easy to go back and forth between a few shaders.

**Comment by andreperezmaselco** [comment]
I wonder if I could also give some style to `matdbg` using [Material Components for the web](https://material-components.github.io/material-components-web-catalog).

**Comment by andreperezmaselco** [comment]
Hi, @romainguy, @pixelflinger and @prideout.
I wonder if I could give some style to `matdbg`, using the [Material Components for the web](https://material-components.github.io/material-components-web-catalog).

**Comment by prideout** [comment]
I received an email for this comment, but I don't see the comment on the
Issue page.  Very strange.

Anyway, to answer your question: resizeable panes would be nice but I don't
think we're very interested in purely cosmetic improvements if they involve
adding new libraries to matdbg or increasing its complexity.

**Comment by andreperezmaselco** [comment]
@prideout, I was thinking in a simple style by using the following links:
https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js

May I try and open the PR, so you could say what you think?

**Comment by prideout** [comment]
Yes, feel free to open a PR, thanks!

**Comment by prideout** [comment]
We are working on a FrameGraph debugger, that's probably higher priority.
