### ISSUE TITLE
Does compilation for android contain the tools(matc,filamesh) for it as well?

### ISSUE THREAD

**Issue by vivasvan1** [google/filament#2685]
If i compile filament from android as described in android/Windows.md.
Will the compilation output contain tools like matc, filamesh etc. which can be run on android?

I want to convert .stl file to filamesh on android device itself. Is this possible?If yes how?

**Comment by romainguy** [comment]
Those tools are host tools. You can however use their library equivalent on Android like filamat for matc. Doing a conversion to filamesh on device doesn't make much sense though. You should just create the renderable.
