### ISSUE TITLE
IsoSphere tangents may not be calculated correctly

### ISSUE THREAD

**Issue by wojciechczerniak** [google/filament#2687]
**Describe the bug**
I'm not sure about this one. Looks like IsoSphere tangents are not calculated correctly?

I've tried to calculate tangents for an STL file with a code fragment from IsoSphere as suggested here https://github.com/google/filament/issues/959#issuecomment-472189487 but got some weird results with a simple `plastic.filamat` material. So I've checked more carefully the provided `redball.html` demo. Looks like the material is not applied correctly to IsoSphere if it has a different geometry than the default demo value?

**To Reproduce**
1. Copy `redball.html` demo
2. Set IsoSphere `nsubdivs` to `0` (zero)

**Expected behavior**
I would expect that IsoSphere with low res to be correctly covered with the set material.

**Screenshots**
Redball demo `plastic.filamat` with IsoSphere `nsubdivs` set to `0`:
![Screenshot 2020-06-14 at 23 37 53](https://user-images.githubusercontent.com/4718998/84604699-2f4c1a00-ae98-11ea-869c-c39e0f9dce96.png)

IsoSphere with default `nsubdivs` set to `5` for reference:
![Screenshot 2020-06-15 at 00 02 13](https://user-images.githubusercontent.com/4718998/84605171-8e5f5e00-ae9b-11ea-9d3c-6f713d30d765.png)

Same `plastic.filamat` applied to `susanne.html` demo looks ok:
![Screenshot 2020-06-14 at 22 04 10](https://user-images.githubusercontent.com/4718998/84604702-38d58200-ae98-11ea-87f7-e6450e85a2fe.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - GPU: Intel Iris Plus Graphics 655 1536 MB
 - Backend: OpenGL probably

**Comment by romainguy** [comment]
Hard to tell whether the lighting is correct or not. What do you expect that you are not getting?

**Comment by wojciechczerniak** [comment]
The material texture looked stretched and the geometry lost its edges. But you're right, it's the lighting. Pretty obvious now... it's set to make the sphere look good  🤦  Sorry.

And thank you.
