### ISSUE TITLE
Post-processing material compilation error on Mali

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2688]
When the PostProcessing manager compiles [dofBlur.mat](https://github.com/google/filament/commits/master/filament/src/materials/dofBlur.mat) I get the following error message:

`0:51: S0060: Multiple output variables defined. Location must be specified for all outputs.
`

If I export the first OpenGL fragment shader from the compiled filamat file I get the same error with the Mali offline compiler. The error doesn't seem to match the code, which looks to be declaring the layout of the output variables explicitly.

The optimized version doesn't have this problem, which implies a layout-related compiler bug. The optimized and non-optimized OpenGL fragment shaders [are attached](https://github.com/google/filament/files/4780187/dofBlur.zip) (in both cases the first variant has been exported).

I'm actually using a branch from version 1.6, but the master version of the shader appears to have the same problem when compiled directly with matc.

**Comment by romainguy** [comment]
Please try with more recent versions of Filament
