### ISSUE TITLE
Are there any Java examples?

### ISSUE THREAD

**Issue by Alice-ww** [google/filament#2696]
I'm trying to implement this library into my project, but I don't have much experience in Kotlin. I have also spent many hours searching for Java example implementations but couldn't find any. I asked on SO to try to convert the Kotlin code into Java, but a user said there are some Kotlin specific syntax? 

If there are any Java examples that I am unaware of could you please link me. And if there aren't any could you please create one.

**Comment by romainguy** [comment]
We don't have samples but you can use Sceneform as a reference (it uses Filament): https://github.com/google-ar/sceneform-android-sdk/tree/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform/rendering

The conversion from Kotlin to Java should be fairly straightforward though. Our API is Java based so they don't do anything that you can't do from Java.

**Comment by prideout** [comment]
Please see `sample-page-curl`, it is 100% pure Java.

**Comment by romainguy** [comment]
Or that :) Thanks @prideout!

**Comment by Alice-ww** [comment]
Thanks!

**Comment by kartikeysaran** [comment]
> 

Where can i find this file ?

**Comment by kartikeysaran** [comment]
> Please see `sample-page-curl`, it is 100% pure Java.

Where can i `sample-page-curl` ?

**Comment by prideout** [comment]
https://github.com/google/filament/tree/main/android/samples/sample-page-curl
