### ISSUE TITLE
Is there a way to #define when calling `matc`?

### ISSUE THREAD

**Issue by MingweiSamuel** [google/filament#2699]
GLSL supports C-style preprocessor directives but is there a way to set defines when calling `matc` like `gcc -D` does?

**Comment by bejado** [comment]
We don't have support for this now, but note you're free to put preprocessor directives inside material blocks like so:

```
fragment {

#define FOO 1

    void material(inout MaterialInputs material) {
        prepareMaterial(material);
    }
}

```

**Comment by romainguy** [comment]
It's something I've always wanted to add :)

**Comment by MingweiSamuel** [comment]
Thanks for the response! I'm just curious since I have a shared material which could be split up into similar materials with conditionals. Using `if`s works fine though.

**Comment by bejado** [comment]
@romainguy I can add this, I have some related material preprocessor stuff I've been meaning to merge in too
