### ISSUE TITLE
SurfaceOrientation$Builder and the triangles16 method: TypeError: Cannot convert "1,2,3" to long

### ISSUE THREAD

**Issue by wojciechczerniak** [google/filament#2702]
**Describe the bug**

Are TS types for SurfaceOrientation$Builder correct? `triangles16`, `triangles32` and few other methods that (probably, see code snippets below for C++ and Java) should accept buffer are described here as a `number` type:

https://github.com/google/filament/blob/94776a01b38901d9b3a7592c555f67acdbca4eab/web/filament-js/filament.d.ts#L874-L879

That would not be a problem (only IDE complains "Argument type Uint16Array is not assignable to parameter type number ") but an attempt to use it ends with an error: `TypeError: Cannot convert "1,2,3" to long`.

Edit: I'm using the Javascript version.

**To Reproduce**
```ts
const sob = new Filament.SurfaceOrientation$Builder();

sob.triangles16(new Uint16Array([1,2,3]));
sob.triangleCount(trianglesCount);

const orientation = sob.build();
```

**Expected behavior**
I would expect that those methods correspond somehow to the `SurfaceOrientation.cpp` implementation and will trigger `buildWithFlatNormals`, `buildWithNormalsOnly` or `buildWithUvs` internally and I will be able to get tangents for triangle mesh imported from an STL file.

**Screenshots**
![Screenshot 2020-06-17 at 19 47 00](https://user-images.githubusercontent.com/4718998/84932213-3eb7a700-b0d4-11ea-8df6-43faa476a403.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - GPU: Intel Iris Plus Graphics 655 1536 MB
 - Backend: OpenGL probably

**Additional context**

In the C++ version those are buffers
https://github.com/google/filament/blob/94776a01b38901d9b3a7592c555f67acdbca4eab/libs/geometry/src/SurfaceOrientation.cpp#L103-L111

Same for Java bindings:
https://github.com/google/filament/blob/94776a01b38901d9b3a7592c555f67acdbca4eab/android/filament-android/src/main/java/com/google/android/filament/SurfaceOrientation.java#L116-L126

**Comment by prideout** [comment]
Good catch, the current bindings for this were contributed from an outside party and I should have reviewed it more thoroughly.

**Comment by prideout** [comment]
Just to be clear, the current JS bindings for SurfaceOrientation actually so work, but they require usage of `Filament._malloc` which is not consistent with the other parts of our JS API.
