### ISSUE TITLE
RenderTarget::Builder example

### ISSUE THREAD

**Issue by dsafa22** [google/filament#2713]
I want to know mush about the use of RenderTarget.

But there is no samples.

Such as I want to render a view in offscreen RenderTarget and then render the offscreen one in screen RenderTarget. Because I will render the offscreen one in other graphic engine.

**Comment by prideout** [comment]
You can look at `lucy_bloom.cpp` or `sample-gltf-bloom/.../MainActivity.kt` at [this commit](https://github.com/google/filament/commit/e8a7d9f0c29b26dd028306d27e4e6d44dd25b1fa) but yes we should provide a simple demo.

**Comment by prideout** [comment]
Here are links to the source files that I mentioned:

[lucy_bloom.cpp](https://github.com/google/filament/blob/e8a7d9f0c29b26dd028306d27e4e6d44dd25b1fa/samples/lucy_bloom.cpp)

[sample-gltf-bloom/.../MainActivity.kt](https://github.com/google/filament/blob/e8a7d9f0c29b26dd028306d27e4e6d44dd25b1fa/android/samples/sample-gltf-bloom/src/main/java/com/google/android/filament/bloom/MainActivity.kt)

**Comment by prideout** [comment]
>  Because I will render the offscreen one in other graphic engine.

What's the other graphic engine?  What are you trying to achieve?  Filament's RenderTarget API is meant for when you use Filament to render, not an outside engine.

**Comment by dsafa22** [comment]
Thanks a lot!

**Comment by dsafa22** [comment]
> > Because I will render the offscreen one in other graphic engine.
> 
> What's the other graphic engine? What are you trying to achieve? Filament's RenderTarget API is meant for when you use Filament to render, not an outside engine.

I use Filament's RenderTarget to render 3D object to offscreen FrameBuffer.

And I render the FrameBuffer texture to  other graphic engine.

That is my purpose.


Simply : 
Filament to render.
Other graphic engine render to screen.

**Comment by dandingol03** [comment]
> > > Because I will render the offscreen one in other graphic engine.
> > 
> > 
> > What's the other graphic engine? What are you trying to achieve? Filament's RenderTarget API is meant for when you use Filament to render, not an outside engine.
> 
> I use Filament's RenderTarget to render 3D object to offscreen FrameBuffer.
> 
> And I render the FrameBuffer texture to other graphic engine.
> 
> That is my purpose.
> 
> Simply : Filament to render. Other graphic engine render to screen.

HI, i met the same need. How can you make `offscreen-rendering` work. i use the `importTexture` api to convert a opengles texture to filament texture, and regard it as color attachment of render-target.However, i didn't make it. Is it convinient for you to share you core or demo? thanks.
