### ISSUE TITLE
Polly glTF model does not display correctly in WebGL environment

### ISSUE THREAD

**Issue by cx20** [google/filament#2714]
**Describe the bug**

I tried displaying the [Polly glTF model](https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/0e23c773bf27dad67d2c25f060370d6fa012d87d/polly/project_polly.gltf) in Filament `1.7.0`.
However, after a few seconds the display goes wrong.

![filament_polly_problem](https://user-images.githubusercontent.com/1833979/85203987-41bccc80-b34c-11ea-8acd-fe9d10757dfb.gif)

**To Reproduce**
https://cx20.github.io/jsdo.it-archives/cx20/M2lx/

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser : [Chrome 83]
 - GPU: [Intel(R) UHD Graphics 617]
 - Backend: [ANGLE]

**Comment by prideout** [comment]
Taking a look now.  I suspect that Animator is producing NaN's during the bad frames, although I already fixed a slew of quaternion-related NaN bugs a while back.  Happens on desktop too.

**Comment by cx20** [comment]
BTW, when I tried to display Polly with the latest version of Filament, I found a new artifact on Polly's head. It looks like an antenna, but I'm wondering what it is.

[Filament latest version + Polly glTF model result:](https://cx20.github.io/gltf-test/examples/filament/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/64017da8f49a618dbeec8ff80f6053cbcb715ad5/polly/project_polly.gltf)
![image](https://user-images.githubusercontent.com/1833979/85330831-0ec33600-b510-11ea-9f53-b1cd347c5aa8.png)

**Comment by prideout** [comment]
Ha, I thought that was the antenna but yes it seems to be an artifact!  I will take a look.

Regarding the original bug, it appears that our Animator is not applying CUBICSPLINE interpolation correctly for morph weights, although we *do* apply this interpolation correctly for other types of rigid body transforms.

The glTF spec is somewhat unclear about the buffer layout for this situation, and there are no models in the Khronos test suite that exercise cubic interpolation in conjunction with morph weights.  However [this Khronos issue](https://github.com/KhronosGroup/glTF-Tutorials/issues/36) has some helpful information that I will use to make our implementation more consistent with the ecosystem.

**Comment by prideout** [comment]
The antenna artifact is due to non-normalized skinning weights in the model and is therefore not a Filament bug.

The artifact goes away after adding this line to gltf_viewer.cpp:

`configuration.normalizeSkinningWeights = true;`

Another way to see this is to use gltf-validator, e.g. by viewing the model in Don McCurdy's glTF viewer and looking at the warnings / errors.

**Comment by romainguy** [comment]
Is there a downside in normalizing the weights by default in our library?

**Comment by prideout** [comment]
In the past we normalized by default, but we made it opt-in after noticing negative impact to loading time.

**Comment by prideout** [comment]
Default behavior was changed in https://github.com/google/filament/pull/2621

**Comment by cx20** [comment]
@prideout Thank you for the repair. I have confirmed that the latest version resolves the issue.

[Filament latest version + Polly glTF model result:](https://rawcdn.githack.com/cx20/gltf-test/1b6c59d822ff7f818610c5123f407eb0f86c85ec/examples/filament/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/64017da8f49a618dbeec8ff80f6053cbcb715ad5/polly/project_polly.gltf)
