### ISSUE TITLE
[Web] "Module is not defined"

### ISSUE THREAD

**Issue by ferry-creator** [google/filament#2715]
Filament web v1.7.0

```
ReferenceError: Module is not defined
filament.js:638
```

```
ReferenceError: Module is not defined
filament.js:654
```

I'm completely new to WASM and Filament, but i figured, that line 6 in filament.js would be the wasm-loader, but minified. Looking into the end of that line, it seems like it returns `Filament` rather than `Module` - looking a bit into emscripten, i was able to figure out that changing "Module" to "Filament" on line 638 and 654, would resolve the issue, and i was _then able to load the sample succesfully with no erros in console!_ 🤠 ✅

Tried first with the original file from //unpkg as suggested by the tutorial - later downloaded the web version from releases v1.7.0 so i could change it.

Being new to Filament, and wanting to set up a production environment, i am worried if i'm doing something wrong, or if this is simply a bug. Please let me know 🙏

**To Reproduce**
Follow the guide on [https://google.github.io/filament/webgl/tutorial_redball.html](url)

**Expected behavior**
Expected to load redball.html demo with no errors in console.

**Screenshots**
<img width="2031" alt="Skærmbillede 2020-06-20 kl  11 26 11 PM" src="https://user-images.githubusercontent.com/33785363/85211853-7a10da80-b34d-11ea-99a3-fc7583729f2e.png">

 - OS: macOS Catalina 10.15.2
 - GPU: Intel Iris Pro 1536 MB / Razor Core X EGPU AMD Radeon RX Vega 56
 - Backend:  WebGL 2.0 / WASM

*Thank you for this amazing engine!*

**Comment by ferry-creator** [comment]
After changing `Module` to `Filament` on line `638` and `654`:

<img width="2035" alt="Skærmbillede 2020-06-21 kl  12 27 23 AM" src="https://user-images.githubusercontent.com/33785363/85212743-045d3c80-b356-11ea-952c-7a613f344551.png">

**Comment by prideout** [comment]
Thanks for the bug report, I'll see if I can repro.  The live demos work right now, and I recently updated them.  However they use a checked-in wasm file rather than unpkg.  I will change that, it will help catch issues.

**Comment by prideout** [comment]
This was fixed in https://github.com/google/filament/commit/242e8d1b567bef920f6535fea393f44ed28a4de5#diff-5f50d59dee9fdfd4b554f60e760a525d

**Comment by ferry-creator** [comment]
Amazing work, thank you for maintaining Filament 💯
