### ISSUE TITLE
ExternalTexture in gltf is not working properly

### ISSUE THREAD

**Issue by SGTjeong** [google/filament#2724]
I am trying to set video texture to gltf model.

I created a custom material for test, but it's working awkwardly. The gltf model just turns red as shown below. 

![arachi](https://user-images.githubusercontent.com/57657823/85363725-99318700-b55c-11ea-925f-95ff4f0b8585.jpg)

I wonder if i am doing anything wrong or it's the issue of filament.

Below is mat file i used.

```
material {
    name : ubershader_lit_opaque,
    requires : [ uv0, uv1, color ],
    shadingModel : lit,
    blending : opaque,
    depthWrite : true,
    doubleSided : true,
    flipUV : false,
    specularAmbientOcclusion: simple,
    
    parameters : [
        // Base Color
        { type : samplerExternal, name : videoTexture }
    ],
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        vec2 uv = getUV0();
        material.baseColor = texture(materialParams_videoTexture, uv).rgba;
    }
}

```

and android code 

```
    rm.setMaterialInstanceAt(renderable, 0, materialInstance)
    val mat = rm.getMaterialInstanceAt(renderable, 0)

    val sampler = TextureSampler()
    val surfaceTexture = SurfaceTexture(0)
    surfaceTexture.detachFromGLContext()
    val surface = Surface(surfaceTexture)
    val stream = Stream.Builder().stream(surfaceTexture).build(EngineInstance.getEngine().filamentEngine)

    val mediaPlayer = MediaPlayer.create(context, R.raw.arachi_jump)
    mediaPlayer.setSurface(surface)
    mediaPlayer.setLooping(true)
    mediaPlayer.start()

    val engine = EngineInstance.getEngine()
    val textureSampler =
        com.google.android.filament.Texture.Sampler.SAMPLER_EXTERNAL
    val textureInternalFormat =
        com.google.android.filament.Texture.InternalFormat.RGB8
    val videoTexture = com.google.android.filament.Texture.Builder()
        .sampler(textureSampler)
        .format(textureInternalFormat)
        .build(engine.filamentEngine)

    videoTexture.setExternalStream(engine.filamentEngine, stream)

    mat.setParameter("videoTexture", videoTexture, sampler)
```

I made sure video texture is actually applied to gltf model, but somehow works like this. What am I missing?

**Comment by prideout** [comment]
This bug sounds similar to #2659, which is now fixed.  If you don't have the fix you can work around by ensuring that the glTF file has a placeholder texture for `baseColor`.

**Comment by SGTjeong** [comment]
@prideout 

Thanks in advance for your prompt response! 

Our gltf already has baseColorTexture in it. I don't think getUV returns 0,0 in our model. 

After I visuailized UV coordinates as you suggested, its like below. 

![arachi](https://user-images.githubusercontent.com/57657823/85468861-f292c800-b5e7-11ea-971e-936a991132d2.png)

**Comment by prideout** [comment]
Interesting, thanks.  Hmm.  Do you see anything interesting in Logcat when filtering for `Filament`?

**Comment by SGTjeong** [comment]
@prideout

Not that I know of.

It's weird because if i try the same thing with Galaxy Fold(Android 9). gltf model doesn't turn red but black. 

Is there any other possible thing i could be missing now?

**Comment by prideout** [comment]
The difference you see between various devices might be due to uninitialized texture memory, if the texture isn't getting set.

If you can construct a repro case and attach a zip to the issue, then we can take a closer look.

**Comment by SGTjeong** [comment]
@prideout 

Thanks for giving me great insight!

It was a sampler problem. I solved the issue by setting TextureSampler's filter and wrap mode. 

I really appreciate your help.
