### ISSUE TITLE
Vulkan issues when rotating screen or changing screen res.

### ISSUE THREAD

**Issue by prideout** [google/filament#2728]
Try running `gltf_viewer -a vulkan` on a high DPI monitor, then drag the window to a low DPI window.  This causes validation errors and/or visually strange behavior.  Resizing the window usually causes a segfault on macOS.

**Comment by prideout** [comment]
More importantly, rotating the screen on Android is also problematic.

**Comment by prideout** [comment]
Mathias has reported issues with resizing material_sandbox.

**Comment by romainguy** [comment]
Although that's MoltenVK, I'm always suspicious of whether MoltenVK is good enough to show true issues in our Vulkan implementation vs the translation layer.

**Comment by prideout** [comment]
Yes, I need to investigate the Android rotation issue first and foremost.

**Comment by prideout** [comment]
Tested today on Android with screen rotation and task switcher, no crash.

Resizing material_sandbox seems okay too.

There's been a lot of churn since this was filed, time to close it.
