### ISSUE TITLE
Shadows cut off

### ISSUE THREAD

**Issue by MingweiSamuel** [google/filament#2734]
**Describe the bug**
Shadows are cut off at strange angles, changing based on the camera's position.  
I assume I'm doing something stupid/wrong but I have no idea what.

**To Reproduce**

Example project here: https://github.com/MingweiSamuel/FilamentShadowsTest/
1. Take the redball example.
2. Add a ground plane.
3. Set `castShadows` and `receiveShadows` on the ball/plane/light so the ball casts a shadow on the plane

Tried setting TANGENTS buffer but only changes (darkens) the color of the plane

**Expected behavior**
Shadow not cut off.

**Screenshots**

http://www.mingweisamuel.com/FilamentShadowsTest/redball2/redball2.html

![screenshot 1](http://www.mingweisamuel.com/FilamentShadowsTest/images/Screen%20Shot%202020-06-24%20at%203.49.06%20PM.png)
![screenshot 2](http://www.mingweisamuel.com/FilamentShadowsTest/images/Screen%20Shot%202020-06-24%20at%203.49.54%20PM.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4 / Firefox 76.0.1 (64-bit) / Chrome 83.0.4103.106 (64-bit)
 - GPU: AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB
 - Backend: WebGL (?)

version 81c60c4efaab85d30a6d5619ef66890980e763f0 but has been happening

**Comment by romainguy** [comment]
It repros in Chrome as well. I wonder if it's just a near/far issue? We have a different far for shadows.

**Comment by bejado** [comment]
It looks like your bounding box is off. When I replace `center: [-1, -1, -1]` with `[0, 0, 0]` the shadow is no longer cut off.

**Comment by MingweiSamuel** [comment]
I see, thank you!

**Comment by MingweiSamuel** [comment]
I had a similar issue with shadows not showing up on certain triangles which I also fixed. Turned out I was setting the TANGENTS vertex attribute to some garbage, leaving it unset fixed the shadows.
