### ISSUE TITLE
Question about how to get/generate the header files resources.h and monkey.h in suzanne.cpp.

### ISSUE THREAD

**Issue by PixxlMaster** [google/filament#2739]
Hello, I have a question about how to get or generate the header files used in [suzanne.cpp](https://github.com/google/filament/blob/main/samples/suzanne.cpp). I'm trying to use Filament in my project, and I want to use a modified version of the suzanne project for learning. All other headers are available, but I do not know how to get or generate (if that is required) the resources.h and monkey.h files. They are both in "generated/resources".

Thanks in advance, and I apologize if this is not the right way to ask questions.

**Comment by romainguy** [comment]
Those are generated by the tool called `resgen`. It's just a simple and easy way for us to embed binary data in our sample apps and libraries. This avoids dealing with I/O :)

It is definitely *not* required to do it this way.

**Comment by PixxlMaster** [comment]
I understand, thanks!
