### ISSUE TITLE
changing material of glb not working

### ISSUE THREAD

**Issue by vivasvan1** [google/filament#2745]
Hi there @prideout @romainguy again,

I am using 
renderableManager.setMaterialInstanceAt(entity,0,goldmaterialInstance)

ScreenShot of STL to GLB converted model:
![Screenshot_2020-06-28-22-16-50-612_com shahidhar jeweldisp](https://user-images.githubusercontent.com/21074796/85953500-4efe3a80-b98e-11ea-832c-0db976b27992.jpg)

I am converting stl files to glb using [this link](https://github.com/wangerzi/3d-model-convert-to-gltf/blob/master/server/service/stl2gltf.py)

Why is the output like this? It works on normal GLB files but not on converted ones.How to fix this?

**Comment by vivasvan1** [comment]
Screenshot of normal GLB file:
![Screenshot_2020-06-28-22-31-11-861_com shahidhar jeweldisp](https://user-images.githubusercontent.com/21074796/85953588-2460b180-b98f-11ea-93fb-b622633bfee3.jpg)

**Comment by vivasvan1** [comment]
My material looks like this.

.material( "void material(inout MaterialInputs material) {\n" + " prepareMaterial(material);\n" + " material.baseColor.rgb = materialParams.baseColor;\n" + " material.roughness = 0.3;\n" + " material.metallic = 1.0;\n" + " material.clearCoat = 1.0;\n" + " material.reflectance = 0.3;\n" + "}\n" )

**Comment by vivasvan1** [comment]
ok i fixed this by adding a material to the json stucture in [convertor.py](https://github.com/wangerzi/3d-model-convert-to-gltf/blob/master/server/service/stl2gltf.py) as show below.

```
...
  "nodes" : [
    {
      "mesh" : 0
    }
  ],

  "materials" : [
          {
              "doubleSided" : true,
              "emissiveFactor" : [
                  0,
                  0,
                  0
              ],
              "name" : "Material.001",
              "pbrMetallicRoughness" : {
                  "baseColorFactor" : [
                      0.8000000715255737,
                      0.1996239870786667,
                      0.054953426122665405,
                      1
                  ],
                  "metallicFactor" : 0.8869569897651672,
                  "roughnessFactor" : 0.14347800612449646
              }
          }
      ],

  "meshes" : [
    {
      "primitives" : [ {
        "attributes" : {
          "POSITION" : 1
        },
        "indices" : 0,
        "material" : 0
      } ]
    }
  ],
...
```

But my model structure gets bit messed up.

Any idea on y this is happening?

![Screenshot_2020-06-29-10-20-25-205_com shahidhar jeweldisp](https://user-images.githubusercontent.com/21074796/85975523-f5c9f180-b9f5-11ea-9769-6669434c6024.jpg)

**Comment by romainguy** [comment]
Looks like a coordinate system issue. Filament uses Y-up, other engines or tools uses Z-up sometimes. Looks like your exporter didn't properly convert as gltf should be Y-up.
