### ISSUE TITLE
Unexpected FXAA / MSAA behavior on Android

### ISSUE THREAD

**Issue by wangyufeng371** [google/filament#2746]
**Describe the bug**
In my project, the scene quality is not satisfactory when i turn on MSAA and FXAA.Then through comparison i found that ,  the aliasing when I turn on post-processing but no FXAA and MSAA,  is more and bigger than the time when I turn off the post-processing.But  they are normal  in the demo. So i think some settings in my proejct cause the quetion.now I don't know how and why ,I hope I can get  some advice or help，thanks very much.

**To Reproduce**

 The surface view is created like that:
mSurfaceView = (SurfaceView) inflater.inflate(R.layout.fragment__layout, container, false);

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. Adreno]
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: [e.g. huawei]

**Additional context**

**Comment by romainguy** [comment]
Could you please provide screenshots so we can understand the issue?

**Comment by wangyufeng371** [comment]
Thanks very much for your answer .I check our code commits ,and find that some people change the code of the UiHelper.Maybe the  question is caused by  the UiHelper,and I plan to modify the code  to see the result。 

The screenshot in my project without FXAA and MSAA:
![5C4B9128D5B0B5D8FB6755323](https://user-images.githubusercontent.com/11827654/86086694-ea012c80-bad4-11ea-84b4-8fa32b37f7e0.jpg)

The screenshot in demo without FXAA and MSAA:
![4CEEE70C4AF1186FCAE0C310E](https://user-images.githubusercontent.com/11827654/86086701-ec638680-bad4-11ea-8731-720712a26134.jpg)

**Comment by wangyufeng371** [comment]
I find the reason is that I use the filament-debug.aar，not release.I am convinced that why the debug is wrong.

**Comment by wangyufeng371** [comment]
> Could you please provide screenshots so we can understand the issue?

I find the reason is that I use the filament-debug.aar，not release.I am convinced that why the debug is wrong.

**Comment by wangyufeng371** [comment]
> It sounds like FXAA and MSAA work as expected in our samples, but not in your app? Are you using our `UiHelper` class?

I find the reason is that I use the filament-debug.aar，not release.I am convinced that why the debug is wrong.

**Comment by romainguy** [comment]
Debug releases of Filament use unoptimized shaders that sometimes cause us to run into driver bugs. This seems to be what's going on in your case.

**Comment by prideout** [comment]
Does this occur on some devices but not others?  Can it be reproduced using one of our sample apps?

**Comment by wangyufeng371** [comment]
Now we use the filament in release, it's well.Maybe we should ignore this problem.
