### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by qmz13579** [google/filament#2753]
E/Filament: Panic
    in static filament::MaterialParser *filament::details::FMaterial::createParser(backend::Backend, const void *, size_t):500
    reason: Material version mismatch. Expected 7 but received 0.
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13441 (le.filamentdemo), pid 13441 (le.filamentdemo)

=============================================================================

    private void loadMaterial() {

        ByteBuffer buffer = BufferUtils.readFile(getAssets(), "baked_color.mat");
        material = createFilamentMaterial(buffer);
    }
//        try {
//            Buffer buffer = readCompressedAsset("baked_color.mat");
//            material = new Material.Builder().payload(buffer, buffer.limit()).build(engine);
//        } catch (IOException e) {
//            e.printStackTrace();
//        }

How to solve this problem，thank you

**Comment by romainguy** [comment]
You cannot load a .mat file directly. You first need to compile it using the tool called matc.
