### ISSUE TITLE
Occluder shadow receiving issues

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2756]
Hi, I have a problem using filament to achieve "shadows on invisible occluder blending with background" effects. 

Expected:
An invisible head, a visible eye-glasses in front it, casting shadows to the invisible head and blend with the background "camera photo".

What I tried with the invisible head before:
1. Apply a material to the invisible head with color-write-off, depth-write-on. It can occlude eye-glasses, but can't show shadows since the color-write is off.
2. Apply a material to the invisible head with unlit,  color-write-on, depth-write-on, blend-on ("multiply"), output the shadow as base-color so it can mix with the 'real world' background. But the problem is: eye-glasses is opaque,  invisible head is now transparent, and rendered after eye-glasses, so it didn't write depth firstly and cannot occlude the eye-glasses. 
[occluder_with_shadows.mat.zip](https://github.com/google/filament/files/4851991/occluder_with_shadows.mat.zip)

My problem is, is there any way in filament to promote some specified 'transparent' mesh's rendering order before 'opaque' rendering stage?  Or any other ways to accomplish such request? Thanks!

**Comment by bejado** [comment]
Have you tried using [`shadowMultiplier`](https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/lighting:shadowmultiplier) on the invisible head with `depthWrite : true`?

**Comment by vcxyk** [comment]
> Have you tried using [`shadowMultiplier`](https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/lighting:shadowmultiplier) on the invisible head with `depthWrite : true`?

Yes, I tried it before. It can receive the shadow but cannot occlude the glasses since the depth of the invisible head is rendered after the eye-glasses.  Filament seems doesn't have the cap of rendering group with specified priority now and I don't know how to explicitly make the invisible head rendered first.

**Comment by vcxyk** [comment]
> > Have you tried using [`shadowMultiplier`](https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/lighting:shadowmultiplier) on the invisible head with `depthWrite : true`?
> 
> Yes, I tried it before. It can receive the shadow but cannot occlude the glasses since the depth of the invisible head is rendered after the eye-glasses. Filament seems doesn't have the cap of rendering group with specified priority now and I don't know how to explicitly make the invisible head rendered first.

I found a work-around for this case: draw the invisible head twice. One acts aswh shadow-receiver (transparent) and the other acts as invisible occluder (opaque with depth-write off).  The drawback is an extra draw of the head which is acceptable .

**Comment by bejado** [comment]
[`RenderableManager::setPriority`](https://github.com/google/filament/blob/main/filament/include/filament/RenderableManager.h#L209) might be what you're looking for.
