### ISSUE TITLE
Building v1.7.0 is broken with vs2019 16.6.2

### ISSUE THREAD

**Issue by TechnikEmpire** [google/filament#2765]
**Describe the bug**
Tinyexr has C++17 features that are illegal in C++20, yet needs to have the lang version specified to C++20 for build. More about this feature causing the issue can be found [here](https://developercommunity.visualstudio.com/content/problem/1034754/warning-c5208-a-c20-feature-occurs-when-compiling-1.html). MS used to erroneously warn about it, but now correctly errors and thus we can't build. If we try to switch just those projects to C++17 where unnamed class typedefs with static members or member functions are legal, then the rest of the build fails as requiring at least C++20.

**To Reproduce**
1. Check out v1.7.0 and try to build with VS2019 v16.6.2.

**Expected behavior**
Should compile.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 1909
 - GPU: RTX 2060
 - Backend: Vulkan

**Additional context**

**Comment by cxyzs7** [comment]
I believe newer commits solved the issue, maybe time for a new release?

**Comment by bejado** [comment]
I think we've updated tinyexr since the 1.7.0 release: https://github.com/google/filament/pull/2644. Can you try building on the latest main?

**Comment by TechnikEmpire** [comment]
I'll try a fresh build from head, just didn't know what was up with skybox gen. If I switch just the tinyexr to c++17 I can build, I had erroneously changed a second project depending on it to c++17 as well when I filed this. Will update after test.

**Comment by romainguy** [comment]
Skygen was recently removed.

**Comment by TechnikEmpire** [comment]
@romainguy yeah I saw the comments about a real time system replacement, just didn't see if that was already in or what the roadmap was etc.

**Comment by romainguy** [comment]
It's not there yet.

**Comment by TechnikEmpire** [comment]
Issue is solved as of 1af254d. Built from there with no issues. Thanks for your time everyone! Thanks for the library. :)
