### ISSUE TITLE
Help for Slide

### ISSUE THREAD

**Issue by Realitian** [google/filament#2770]
Hi @romainguy ,
I watched your presentation very helpfully. ( High Performance Graphics Programming ).
https://www.youtube.com/watch?v=Lcq_fzet9Iw&t=3s&pbjreload=101
I tried to find the slide for this video, but I couldn't find that.
Could you share this slide?
Although this github is not perfect space for ask this, but I couldn't find most fast way for asking it ever than github.
Thank you in advance.

**Comment by romainguy** [comment]
The only source for those slides is that YouTube video.
