### ISSUE TITLE
Plan to support x86 on windows？

### ISSUE THREAD

**Issue by dsafa22** [google/filament#2773]
I want to use filament on windows x86.
But it only support x64.
Do you plan to support x86 on windows？

**Comment by romainguy** [comment]
It *should* work but we haven't tested it nor do we plan on supporting it officially. 32 bit support for Android is only there for the emulators and older devices and we plan on getting rid it of it as soon as we can.

**Comment by dsafa22** [comment]
> It _should_ work but we haven't tested it nor do we plan on supporting it officially. 32 bit support for Android is only there for the emulators and older devices and we plan on getting rid it of it as soon as we can.

THANKS.
Some compilation options and assembly codes of the windows platform need to be adjusted. I have modified them locally. If there is no plan, I will not mention PR.

**Comment by FinleyPan** [comment]
Hi @dsafa22 Would you mind sharing your modifications with me, I am also stuck on building assembly for Win32 with Visual Studio。 please see this [post](https://stackoverflow.com/questions/66468693/stuck-on-compiling-assembly-with-ml-exe-of-visual-studio2019)

**Comment by liang0724s** [comment]
> Hi @dsafa22 Would you mind sharing your modifications with me, I am also stuck on building assembly for Win32 with Visual Studio。
Hi @FinleyPan, did you meet your expectations ?I also  want to use filament on windows x86.

**Comment by liang0724s** [comment]
Hi @FinleyPan, did you meet your expectations ?I also want to use filament on windows x86.

**Comment by MaybeWong** [comment]
Hi @FinleyPan Would you mind sharing your modifications with me, I am also stuck on building assembly for Win32 with Visual Studio。
