### ISSUE TITLE
Saving file with transparent background not working if computer have external graphics card

### ISSUE THREAD

**Issue by Pankaj003** [google/filament#2775]
I am trying to save a file with transparent background on Windows platform (Windows10).
On machines which doesn't have external graphics card it is working fine but on machines with external graphics card I am getting non transparent background with Alpha channel 255 and black background. I've Geforce GTX1070 graphics cared installed on my laptop. Do I need to set some configuration setting? 

Code snippet:
 int n_channels = transparent ? 4 : 3;
    auto dataformat = transparent ? backend::PixelBufferDescriptor::PixelDataFormat::RGBA : backend::PixelBufferDescriptor::PixelDataFormat::RGB;
    auto qimageformat = transparent ? QImage::Format_RGBA8888 : QImage::Format_RGB888;
    const Viewport& vp = mOffscreenView->getViewport();

    mCamManipulator.updateCamera(mOffscreenCamera);

    // if transparent, change clear color to full alpha
    Renderer::ClearOptions new_clear_options = mClearOptions;
    if (transparent) {
        new_clear_options.clearColor[3] = 0.0;
    }
    else {
        new_clear_options.clearColor[3] = 1.0;
    }
    mRenderer->setClearOptions(new_clear_options);

    bool done = false;

    uint8_t* pixels = new uint8_t[vp.width * vp.height * n_channels];
    backend::PixelBufferDescriptor buffer(
        pixels,
        vp.width * vp.height * n_channels,
        dataformat,
        backend::PixelBufferDescriptor::PixelDataType::UBYTE,
        [](void* buffer, size_t size, void* capture_state) {
            CaptureState* state = static_cast<CaptureState*>(capture_state);
            const Viewport& v = state->view->getViewport();
            QImage img(reinterpret_cast<unsigned char*>(buffer), v.width, v.height, state->img_format);
            QImage scaled = img.scaled(state->w, state->h, Qt::IgnoreAspectRatio, Qt::SmoothTransformation);
            scaled.save(state->filepath);

            // cleanup.
            delete[] static_cast<uint8_t*>(buffer);
            delete state;

            *(state->done) = true;
        }, new CaptureState{ mOffscreenView, filepath, qimageformat, w, h, &done });

    while (!mRenderer->beginFrame(mOffscreenSwapChain)) {
        std::this_thread::sleep_for(8ms);
    }
    mRenderer->render(mOffscreenView);
    mRenderer->readPixels(0, 0, vp.width, vp.height, std::move(buffer));
    mRenderer->endFrame();

    while (!done) {
        // Keep flushing the render buffer.  Filament requires the
        // command stream to execute while CPU bound operations are scheduled
        if (mRenderer->beginFrame(mOffscreenSwapChain)) {
            mRenderer->render(mOffscreenView);
            mRenderer->endFrame();
        }
        std::this_thread::sleep_for(8ms);
    }
    mRenderer->setClearOptions(mClearOptions);

**Comment by romainguy** [comment]
To make this work you need to create a transparent swap chain. Make sure you pass the flag `SwapChain::CONFIG_TRANSPARENT` to `Engine::createSwapChain()`. You also need to make sure the native surface you're rendering into is transparent, otherwise the driver may notice you a proper alpha channel as you've discovered.

**Comment by Pankaj003** [comment]
Thanks for your reply...I am already doing this while creating the engine
    auto backend = filament::Engine::Backend::OPENGL;
    mEngine = filament::Engine::create(backend);
    mSwapChain = mEngine->createSwapChain(nativewindow, filament::SwapChain::CONFIG_TRANSPARENT);
    mOffscreenSwapChain = mEngine->createSwapChain(mOffscreenDim, mOffscreenDim, filament::SwapChain::CONFIG_TRANSPARENT);

This is working fine on some systems but not on with graphics card installed

**Comment by romainguy** [comment]
You also need to make sure the native window in which you rendee is transparent.

**Comment by Pankaj003** [comment]
I am saving the rendered image to the hard disk, by native window you mean the application window or the main swapChain?
main swapChain is also transparent
mSwapChain = mEngine->createSwapChain(nativewindow, filament::SwapChain::CONFIG_TRANSPARENT);

I am suspecting some graphics card config setting, may be wrong guess

**Comment by romainguy** [comment]
I'm talking about the native window. If it's not transparent itself the driver may discard the alpha channel. Another solution is to render to an offscreen RenderTarget.

**Comment by Pankaj003** [comment]
native window is also set to transparent, looks like something else is going on, I'll try rendering to an offscreen Render Target.

**Comment by prideout** [comment]
One note of interest is that clear behavior had issues with offscreen render targets, we have a fix in #3276.

**Comment by romainguy** [comment]
Please try with recent fixes we made to offscreen render targets and let us know if the bug is still present.
