### ISSUE TITLE
How to use a depth attachment texture with a RenderTarget? 

### ISSUE THREAD

**Issue by roxlu** [google/filament#2777]
I just ran into an `assert()` inside `OpenGLDriver::createTextureSwizzleR()`.  I use a RenderTarget, to which I add a texture with the `COLOR_ATTACHMENT` point and one using the `DEPTH24` attachment point. The texture that I use for the `DEPTH24` attachment point is created with the `DEPTH_ATTACHMENT` usage only.

**1. 
Does a depth attachment need both `DEPTH_ATTACHMENT` and `SAMPLEABLE` usage?**

**2. 
I've disabled the code which attaches the depth texture in my app. This fixes the assert. My scene renders fine without any perceivable depth buffer related issues. This makes me wonder if I actually need a depth attachment?**

_I've pasted the code for `createTextureSwizzledR()` which fails on the assert fro the `SAMPLEABLE` usage:_

```c++
void OpenGLDriver::createTextureSwizzledR(Handle<HwTexture> th,
        SamplerType target, uint8_t levels, TextureFormat format, uint8_t samples,
        uint32_t w, uint32_t h, uint32_t depth, TextureUsage usage,
        TextureSwizzle r, TextureSwizzle g, TextureSwizzle b, TextureSwizzle a) {
    DEBUG_MARKER()

    assert(uint8_t(usage) & uint8_t(TextureUsage::SAMPLEABLE)); // *** THIS FAILS ****

    createTextureR(th, target, levels, format, samples, w, h, depth, usage);

    // WebGL does not support swizzling. We assert for this in the Texture builder,
    // so it is probably fine to silently ignore the swizzle state here.
    #if !defined(__EMSCRIPTEN__)

    // the texture is still bound and active from createTextureR
    GLTexture* t = handle_cast<GLTexture *>(th);

    glTexParameteri(t->gl.target, GL_TEXTURE_SWIZZLE_R, getSwizzleChannel(r));
    glTexParameteri(t->gl.target, GL_TEXTURE_SWIZZLE_G, getSwizzleChannel(g));
    glTexParameteri(t->gl.target, GL_TEXTURE_SWIZZLE_B, getSwizzleChannel(b));
    glTexParameteri(t->gl.target, GL_TEXTURE_SWIZZLE_A, getSwizzleChannel(a));

    #endif

    CHECK_GL_ERROR(utils::slog.e)
}
```

**Comment by romainguy** [comment]
Do you use `Texture::Builder::swizzle()`?

**Comment by romainguy** [comment]
It looks like we may have an inverted logic bug:

`if (UTILS_LIKELY(builder->mTextureIsSwizzled))`

should be:

`if (UTILS_LIKELY(!builder->mTextureIsSwizzled))`

**Comment by roxlu** [comment]
> Do you use `Texture::Builder::swizzle()`?

No.

> It looks like we may have an inverted logic bug:
> 
> `if (UTILS_LIKELY(builder->mTextureIsSwizzled))`
> 
> should be:
> 
> `if (UTILS_LIKELY(!builder->mTextureIsSwizzled))`

Thanks!
