### ISSUE TITLE
Build TNT.sln couldn't find generated/resources/resources.h

### ISSUE THREAD

**Issue by josuemnb** [google/filament#2792]
Build TNT.sln couldn't find generated/resources/resources.h for 20200709 version

1 - follow the build manul for windows.
mkdir out
cd out 
cmake ..

Open TNT.SLN
Build material_sandbox

**Comment by romainguy** [comment]
Merging with the other issues

**Comment by prideout** [comment]
Ah -- In my case, I think this particular error was caused by the fact that I enabled case sensitivity in my github folder, which is not aligned with CMake's expectations for how Windows works.

**Comment by JackQu2018** [comment]
Is there any solution for this problem？I met this error and can't find a way to fix it. Could you please help me to fix it out?

**Comment by dngs365** [comment]
This issue not fixed in Windows.
