### ISSUE TITLE
Build multiple error on sugested code in README.MD

### ISSUE THREAD

**Issue by josuemnb** [google/filament#2793]
following the sugested code and makefile for windows generated a ton of linkage errors.
Version 20200709 Release for windows

**Comment by romainguy** [comment]
What are the build errors? What version of Visual Studio are you using?

**Comment by romainguy** [comment]
@bejado See issue #2792 as well

**Comment by bejado** [comment]
Ah, this might be because I added Vulkan support in our CI jobs.

@josuemnb you can fix this by adding `bluevk.lib` to `FILAMENT_LIBS` in your Makefile.

```
FILAMENT_LIBS=filament.lib backend.lib bluegl.lib bluevk.lib filabridge.lib filaflat.lib utils.lib geometry.lib smol-v.lib ibl.lib
```

**Comment by josuemnb** [comment]
Thanks. it worked

**Comment by JackQu2018** [comment]
> @bejado See issue #2792 as well

Is there any solution for this problem？I met this error and can't find a way to fix it. Could you please help me to fix it out?
