### ISSUE TITLE
missing vkInvalidateMappedMemoryRanges in filament-android-release.aar

### ISSUE THREAD

**Issue by kpeeters** [google/filament#2801]
I have an android app which calls filament directly from its native code (not through the java/kotlin wrappers). Built against 1.8.0 built from source, and doing `System.loadLibrary("filament-jni")` before loading my native code.

This worked with 1.6.0 and 1.7.0. With 1.8.0 I get a

    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "vkInvalidateMappedMemoryRanges" referenced by ...

error at startup. 

This happens both with the `filament-android-release.aar` built by me locally and with the binary release `.aar`.

Any ideas?

**Comment by romainguy** [comment]
If you are not using the Vulkan backend you can compile without it using `-v` when invoking `build.sh`. I'm surprised this is happening with our release aar.

@prideout Aren't we excluding the Vulkan backend from our release binaries at this time?

What version of Android do you use when this happens?

**Comment by kpeeters** [comment]
Ok, I'll try that. This is on Android 10 on a Samsung Tab S6.

**Comment by romainguy** [comment]
Thank you. I hope it's just a Vulkan version number issue. You don't happen to know which version of Vulkan this device supports by any chance?

**Comment by kpeeters** [comment]
According to 'OpenGL Extensions Viewer', this device has/supports Vulkan Version 1.1.87.

**Comment by kpeeters** [comment]
Building with `-v` indeed 'solves' the problem.

**Comment by prideout** [comment]
I'll take a look.

The way this is supposed to work is that Vulkan is enabled by default in local builds but not in ci builds.  Adding `-v` to the root-level build script excludes Vulkan.

Our release process uses `release.yml`, which does`cd build/android && printf "y" | ./build.sh release`, which in turn does `./build.sh -p android -v ...`

Note that in the past `-v` meant inclusion, now it means exclusion; see #2544.

**Comment by romainguy** [comment]
Ah the problem is that AARs we publish to Maven Central are built locally not by CI. I did not use `-v` unfortunately, so it's my fault :( We should publish 1.8.1 to fix this :/

**Comment by romainguy** [comment]
(but it should not crash anyway :)

**Comment by prideout** [comment]
Adding the -v before doing an incremental build is problematic, I would often see errors like this when I didn't thoroughly clobber first.  This might be due to the gradle cache since we use a gradle option to control a CMake option.  We pass `-Pfilament_exclude_vulkan` to gradle, which turns into `-DFILAMENT_SUPPORTS_VULKAN=ON`.

**Comment by romainguy** [comment]
Yes you need a clean build.

**Comment by romainguy** [comment]
The current Maven Central builds exclude Maven.
