### ISSUE TITLE
Android App suspended after glLinkProgram called in OpenGLProgram()

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2813]
**Describe the bug**
Mobile app hangs when filament execute glLinkProgram in OpenGLProgram constructor.
Shader: MipmapDepth
ps: glCompile shader successfully.

**Smartphone (please complete the following information):**
 - Device: XiaoMi4  with Adreno 330 GPU   (support gles 3.0)
 - OS: MIUI 10.8.9.13

**Additional context**

**Comment by vcxyk** [comment]
I solved the problem by converting the ivec2 to vec2 as the second parameter of texelFetch() in mipmapDepth.mat.  It seems a gpu-specific problem.

**Comment by romainguy** [comment]
That's a bit scary since texelFetch takes an ivec2 and not a vec2 :/
