### ISSUE TITLE
Issue of building android on windows

### ISSUE THREAD

**Issue by geroge-d** [google/filament#2815]
hi guys
  I just tried to build an android filament on windows from the latest source codes. It worked very well in the previous source codes(1.7). But now it failed, please see the logs below

```
[101/732] Generate extended instruction tables for spv-amd-shader-explicit-vertex-parameter.
FAILED: third_party/spirv-tools/spv-amd-shader-explicit-vertex-parameter.insts.inc
cmd.exe /C "cd /D G:\works\filament\out\cmake-android-release-aarch64\third_party\spirv-tools\source && G:\works\filament\third_party\spirv-tools\utils\generate_grammar_tables.py --extinst-vendor-grammar=G:/works/filament/third_party/spirv-tools/source/extinst.spv-amd-shader-explicit-vertex-parameter.grammar.json --vendor-insts-output=G:/works/filament/out/cmake-android-release-aarch64/third_party/spirv-tools/spv-amd-shader-explicit-vertex-parameter.insts.inc --vendor-operand-kind-prefix="
error: at least one output should be specified.
```

if I add "python.exe" in front of G:\works\filament\third_party\spirv-tools\utils\generate_grammar_tables.py,  it works

**Comment by romainguy** [comment]
What version of Windows/Python do you use? We recently updated spirv-tools, it's probably a chance in their build files.

**Comment by bejado** [comment]
Sounds like you need to associate .py files with Python on Windows. Note that Python 3 is required.

**Comment by geroge-d** [comment]
Python 3.7

**Comment by romainguy** [comment]
Can you confirm that the fix of associating .py files with Python works? Since this is from a 3p library it's something we'd rather not have to change and maintain.

**Comment by geroge-d** [comment]
I found one way workaround. 
 Just add one line below  in the file : third_party\spirv-tools\source\CMakeLists.txt
set(PYTHON_EXECUTABLE "python")
