### ISSUE TITLE
Double deletion error in gltf_viewer demo

### ISSUE THREAD

**Issue by DianxinWang** [google/filament#2820]
**Describe the bug**
Double-deletion in gltf_viewer demo.

**To Reproduce**
Once I run gltf_viewer demo and then exit, it exits with code 11.

**Expected behavior**
Once I run gltf_viewer demo and then exit, it exits with code 11.

**Screenshots**
![image](https://user-images.githubusercontent.com/36990568/87501353-71cc6680-c691-11ea-98df-f5f121b08389.png)
**Additional context**
In file `AssetLoader.cpp`
```
    auto cleanup = [&app](Engine* engine, View*, Scene*) {
        app.loader->destroyAsset(app.asset);
        app.materials->destroyMaterials();

        engine->destroy(app.scene.groundPlane);
        engine->destroy(app.scene.groundVertexBuffer);
        engine->destroy(app.scene.groundIndexBuffer);
        engine->destroy(app.scene.groundMaterial);

        delete app.viewer;
        delete app.materials;
        delete app.names;

        AssetLoader::destroy(&app.loader);
    };
```
`delete app.materials;` `AssetLoader::destroy(&app.loader);` These two delete the same material twice, which cause the error.

**Comment by prideout** [comment]
`AssetLoader::destroy` documentation says "This does not not automatically free the cache of materials" .

Why did you close this issue?

**Comment by DianxinWang** [comment]
I found it's a stupid error of my own code. Already solved.
