### ISSUE TITLE
IBL not working in old android devices

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2824]
Device: XiaoMi 4
GPU: Adreno GPU 330
Lights:  venetian_crossroads_2k IBL  + SunLight
DamagedHelmet.glb in this device using Filament can only show EmissivePart + Sun Specular. The IBL is not working. (ps: I can see from the breakpoints that the ktx is correctly loaded  and the cubemap texture is created successfully via the ktx.  )

(pps: GAPID & snapdragon profiler can make it crash when the capture begins so I am trying older adreno profiler.  The monoFramwork's download encountered some problems. Once I have done the gpu capture, I will post the frames here.)

**Comment by romainguy** [comment]
Could you share the logs from logcat please? This is unfortunately very likely due to driver bugs. We can try to find workarounds but it will be difficult since we don't have that device to test with.

**Comment by vcxyk** [comment]
> Could you share the logs from logcat please? This is unfortunately very likely due to driver bugs. We can try to find workarounds but it will be difficult since we don't have that device to test with.

[two logs.zip](https://github.com/google/filament/files/4936109/two.logs.zip)
Here's two logs from logcat with two android devices.
Mali-G76 GPU works properly.
Adreno-tm-330 GPU doesn't have the ibl part.

**Comment by romainguy** [comment]
If it's not a shader issue, debug builds of Filament might be able to catch it (we enable many asserts). I don't see anything in the logs. Adreno 330 is an old GPU and I wouldn't be surprised if we're just running into hardware/driver bugs here.

**Comment by vcxyk** [comment]
> If it's not a shader issue, debug builds of Filament might be able to catch it (we enable many asserts). I don't see anything in the logs. Adreno 330 is an old GPU and I wouldn't be surprised if we're just running into hardware/driver bugs here.

After trials and errors, I finally make the IBL work in my adreno 330 device. But I still don't know what's the actual reason:(

Here's the route:
I hooked the shader source at runtime in the "OpenGLProgram.cpp" and replace it with my modified version to debug the shader code.  And I found three lines in the PBR's fragment shader cause the unexpected problems.

1) mipmapDepth.mat,   FRAGMENT_SHADER
gl_FragDepth = texelFetch(materialParams_depth, 2 * icoord + ivec2(icoord.y & 1, icoord.x & 1), level).r;
The 'level' param lead the later "glLinkProgram" call stuck forever. But if I change it to a constant int, glLinkProgram can get through normally.
gl_FragDepth = texelFetch(materialParams_depth, 2 * icoord + ivec2(icoord.y & 1, icoord.x & 1), 0).r;

2) Generated PBR Shader for gltf model,   FRAGMENT_SHADER
The original line:  (aoStrength passed in by the gltfio is 1.0, watched from the breakpoint view)
material.ambientOcclusion = texture(materialParams_occlusionMap, aoUV).r * materialParams.aoStrength;

The product above in adreno 330 is 0.0 (expected 1.0),  but the high-end android device is ok.
And the strange part is:
material.ambientOcclusion = texture(materialParams_occlusionMap, aoUV).r;  // 1.0, ok
material.ambientOcclusion = materialParams.aoStrength; // 1.0, ok
material.ambientOcclusion = texture(materialParams_occlusionMap, aoUV).r * materialParams.aoStrength; // 0.0, error
This result influcent the diffuseAO->Fd->IBL  and make the IBL part black.

3) Generated PBR Shader for gltf model,   FRAGMENT_SHADER
The original line in combineDiffuseAndSpecular():
color.rgb += (Fd + Fr) * frameUniforms.iblLuminance;  // turn out to be black in adreno 330
Change it to:
color.rgb += (Fd + Fr) * float3(frameUniforms.iblLuminance);  // works fine in adreno 330

Here's the complete cpp code for runtime shader source hacking. ( with a comment for each hacked line: "modified line")
[OpenGLProgram.cpp.zip](https://github.com/google/filament/files/4953212/OpenGLProgram.cpp.zip)

As you can see it's just a workaround to get through the IBL effects.  Any ideas to fix these uncompatible issues? Thanks:)

**Comment by romainguy** [comment]
Thanks for the investigation, they definitely point to driver bugs. Is this happening with debug builds or release builds? In release our shaders go through an optimizer so the code looks very different.

We could adopt #3 as a fix in our code base but I'm not sure what we can do about the other two.

BTW have you tried FIlament 1.8? We've updated several things, including the shader optimizer. It may help?

**Comment by romainguy** [comment]
Please try with more recent versions of Filament
