### ISSUE TITLE
blend

### ISSUE THREAD

**Issue by orenmiron** [google/filament#2837]
i would like to render a semi transparent shape  above an opaque object
the alpha value of the red shape is 128 and the alpha value of the green shape is 255
![blend](https://user-images.githubusercontent.com/7829843/88076134-5e823500-cb82-11ea-9bfe-5d9008bf2ff4.jpg)
when using cg, i am using the following options:
		DepthTestEnable = true;
		DepthMask       = true;
		CullFaceEnable  = true;
		BlendEnable = true;
		DepthFunc = LEqual;		
		BlendFunc = int2(SrcAlpha, OneMinusSrcAlpha);
what option should i use in filamat ? 
    shadingModel : lit, 
    doubleSided: true,
    blending: ?
i already tried setting blending to opaque, transparent, fade, add, masked, multiply, screen.

**Comment by romainguy** [comment]
You'll want to use the `transparent` blending mode. It's equivalent to `One, OneMinusSrcAlpha`. Note that you *must* use pre-multiplied alpha. So if you don't use pre-multiplied textures or colors, you'll have to do the following in your material:

`material.baseColor.rgb *= material.baseColor.a;`

After setting `material.baseColor`.

**Comment by romainguy** [comment]
For more reference about materials, see our [documentation](https://google.github.io/filament/Materials.html), and in particular the [short section about pre-multiplied alpha](https://google.github.io/filament/Materials.html#handlingcolors/pre-multipliedalpha).

**Comment by orenmiron** [comment]
thank u, it works fine
should i sort my shapes?, opaque first and transparent last?

**Comment by romainguy** [comment]
No Filament will sort them for you (opaque first, transparent last and transparents are sorted back to front). You need correct bounding boxes though for your transparents.

**Comment by orenmiron** [comment]
sorting works fine, i am using "priority" to mark my transparent shapes.
now i have a noise problem, i think it is because the distance between my shapes is very small
can i control depth buffer resolution? can i set near plan and far plan of camera?
i currently use this:

 shadingModel : lit, 
 doubleSided: true,
![blending](https://user-images.githubusercontent.com/7829843/88204938-b8ebc600-cc54-11ea-909d-defb6dfc8897.jpg)
 blending: transparent,

**Comment by romainguy** [comment]
I can't really tell from your screenshot what is image compression and what is the problem you are mentioning. Filament sets up a 24 bit depth buffer but you can set the near and far planes of the camera of course. Not that we use an infinite far plane in practice, the far plane is really only used for culling. The near place is what's going to impact how the depth buffer is used.

You don't need to use priority to mark transparent objects, they are always drawn after opaque objects.

**Comment by orenmiron** [comment]
I am trying to understand transparency
i changed the hellotriangle program by adding one more triangle (blue, semi transparent) and rotating it on Z axis.
and i don't understand why the blue triangle is hidden when rotated in 315 degrees

    shadingModel : unlit, 
    doubleSided: false,
    blending: transparent,
    depthCulling: false,

pls advise


![0](https://user-images.githubusercontent.com/7829843/89556406-04d46880-d81a-11ea-93e2-6a7bda173d60.jpg)
![45](https://user-images.githubusercontent.com/7829843/89556408-056cff00-d81a-11ea-8a86-0fd5aa4c42bb.jpg)
![135](https://user-images.githubusercontent.com/7829843/89556410-06059580-d81a-11ea-9970-8b4143198ad3.jpg)
![180](https://user-images.githubusercontent.com/7829843/89556412-06059580-d81a-11ea-9d68-8d639e377068.jpg)
![225](https://user-images.githubusercontent.com/7829843/89556415-069e2c00-d81a-11ea-9065-12bef5393162.jpg)
![315](https://user-images.githubusercontent.com/7829843/89556417-069e2c00-d81a-11ea-95c3-5a38d31b0206.jpg)
[source changes to hello triangle.zip](https://github.com/google/filament/files/5036250/source.changes.to.hello.triangle.zip)

**Comment by romainguy** [comment]
It's hard to say from the screenshots since the triangle is unlit. But depending on the rotation pivot your blue triangle might just be pointing behind the green triangle and depth testing would cause what you see. Turning off depth testing in this case would fix it (so should changing the rotation pivot).

**Comment by orenmiron** [comment]
in this example i tried to cancel depth testing by changing mat file:
depthCulling: false,
is there another way to change depth testing? is culling means testing?

**Comment by orenmiron** [comment]
Thank u very much for your support, i have a new question:
i am creating my renderables and the scene render is ok.

now, I want to change the depthCulling from true to false.

can i call setParameter function?
can i change the material instance of an existing renderable Entity?

This is my code for creating renderables
utils::Entity renderable = utils::EntityManager::get().create();
    RenderableManager::Builder builder(1);
	builder.boundingBox(rm.aabb)
		.material(0, mat)
		.geometry(0, RenderableManager::PrimitiveType::TRIANGLES, rm.vb, rm.ib, 0, rm.indexCount)
		.culling(false)
		.castShadows(true)
		.receiveShadows(true)
		//.blendOrder()
		.priority(rm.mPriority);
	auto res = builder.build(*mEngine, renderable);
