### ISSUE TITLE
Camera::GetCullingProjectionMatrix is need in Android JNI

### ISSUE THREAD

**Issue by DianxinWang** [google/filament#2843]
Camera::GetCullingProjectionMatrix is a public method in C++ side but it's not available in android part. We can't find such a method in `android/filament-android/src/main/cpp/Camera.cpp` like `Java_com_google_android_filament_Camera_nGetProjectionMatrix`.

**Comment by romainguy** [comment]
We can add this, thanks for filing this request. Note that the only difference between `getCullingProjectionMatrix` and `getProjectionMatrix` is the far plane.

**Comment by DianxinWang** [comment]
That will be helpful for our project. Thanks.
