### ISSUE TITLE
Implementing a mirror texture

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2846]
Any suggestions on the best way to add a mirror to a Filament scene?

**Comment by romainguy** [comment]
@prideout had/has a demo somewhere. Basically you render your scene into an offscreen texture with a different camera and then use that texture on the mirror. It's often called "planar reflections", you should be able to find multiple articles online on how to do it.

**Comment by prideout** [comment]
Yes take a look at [RenderTarget](https://github.com/google/filament/blob/main/filament/include/filament/RenderTarget.h).

It's a bit crufty but there's a sample [here](https://github.com/google/filament/blob/73c2a874445d38bf279cea6ec4e1575b3ba21d6a/samples/lucy_bloom.cpp).
