### ISSUE TITLE
SurfaceOrientation typo in jni wrapper

### ISSUE THREAD

**Issue by chiel99** [google/filament#2854]
**Describe the bug**
When using SurfaceOrientation.Builder().build() in Android platform, the no implementation exception is thrown out.
The JNI method name is **m**BuilderTriangleCount instead of **n**BuilderTriangleCount.

No implementation found for void com.google.android.filament.SurfaceOrientation.nBuilderTriangleCount(long, int) (tried Java_com_google_android_filament_SurfaceOrientation_nBuilderTriangleCount and Java_com_google_android_filament_SurfaceOrientation_nBuilderTriangleCount__JI)

**To Reproduce**

Try the code in android:
SurfaceOrientation surfaceOrientation = new SurfaceOrientation.Builder()
                .vertexCount(vertexCount)
                .triangleCount(triangleCount)
                .normals(normals)
                .build();

**Expected behavior**
Without exceptions.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10

**Additional context**
Fixed in PR: #2853

**Comment by romainguy** [comment]
Thanks!
