### ISSUE TITLE
The skinning animation is broken in the latest version of Filament

### ISSUE THREAD

**Issue by cx20** [google/filament#2856]
**Describe the bug**
I updated the Filament sample from `v1.8.0` to the [latest version](https://github.com/google/filament/actions/runs/179130980).
However, in the latest version of Filament, the model of skinning animation appears broken.

[Filament latest + RiggedFigure.gltf result:](https://cx20.github.io/gltf-test/examples/filament/index.html?model=RiggedFigure&scale=1)
![image](https://user-images.githubusercontent.com/1833979/88278572-92459200-cd1d-11ea-84a0-e700f65d3111.png)

**To Reproduce**
Filament latest + RiggedFigure.gltf result:
https://cx20.github.io/gltf-test/examples/filament/index.html?model=RiggedFigure&scale=1

**Expected behavior**
Filament v1.8.0+ RiggedFigure.gltf result:
![image](https://user-images.githubusercontent.com/1833979/88279547-3845cc00-cd1f-11ea-8f76-20a0cf32afba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 + Chrome 84
 - GPU: Intel UHD Graphics 617
 - Backend: WebGL/ANGLE (Intel(R) UHD Graphics 617 Direct3D11 vs_5_0 ps_5_0)

**Comment by romainguy** [comment]
We haven't made changes to skinning related code recently. We did update cgltf though. @prideout any ideas?

**Comment by romainguy** [comment]
Where can we get this asset? Rigging works fine in other gltf files.

**Comment by prideout** [comment]
I have reproduced this, not sure what's going on yet.

**Comment by prideout** [comment]
This only reproduces with our WASM build, other platforms are fine.

**Comment by cx20** [comment]
@romainguy The assets are available from the Khronos glTF Sample Models repository.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0#more-complex-models
|Model|Screenshot|
|:-------:|:------------:|
|[Rigged Figure](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/RiggedFigure)|![](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/RiggedFigure/screenshot/screenshot.gif)|

I tried other skinning animation models ([SimpleSkin](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/SimpleSkin), [RiggedSimple](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/RiggedSimple), [CesiumMan](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/CesiumMan), [Fox](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox), [BrainStem](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BrainStem)), but none of them displayed correctly. I've tried JavaScript versions of Filament.

I think something happened recently because it used to show up correctly. I don't know what it is.

**Comment by cx20** [comment]
@prideout Thanks! I have confirmed that the latest version of Filament resolves the issue.

[Filament latest + RiggedFigure.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/213692748002cdf44eb345eef5c6239b7ce25218/examples/filament/index.html?category=sampleModels&model=RiggedFigure&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/88724993-5f106200-d166-11ea-8f84-51b07cd0ab41.png)
