### ISSUE TITLE
Custom material crash on some Android Phones

### ISSUE THREAD

**Issue by zxPhoenix** [google/filament#2857]
I created custom material which works well on OnePlus/6T Android 10, but crashes on some Phones. I checked on Samsung Note 10+ Android 10 and Samsung Galaxy S8 Android 9. Filament's version: 1.8(20200709). The issue is not reproducible for Filament 1.7. 

Material sources:
`lateinit var mat: com.google.android.filament.Material?
        lateinit var material: MaterialInstance
        
        MaterialBuilder.init()

        val matPackage2 = MaterialBuilder()
            .platform(MaterialBuilder.Platform.MOBILE)
            .transparencyMode(MaterialBuilder.TransparencyMode.TWO_PASSES_TWO_SIDES)
            .name("Steel")
            .doubleSided(true)
            .shading(MaterialBuilder.Shading.LIT)
            .blending(MaterialBuilder.BlendingMode.OPAQUE)
            .depthWrite(true)
            .uniformParameter(MaterialBuilder.UniformType.FLOAT3, "baseColor")
            .samplerParameter(MaterialBuilder.SamplerType.SAMPLER_2D, MaterialBuilder.SamplerFormat.FLOAT, MaterialBuilder.SamplerPrecision.DEFAULT, "normalMap")
            .samplerParameter(MaterialBuilder.SamplerType.SAMPLER_2D, MaterialBuilder.SamplerFormat.FLOAT, MaterialBuilder.SamplerPrecision.DEFAULT, "metallicRoughness")
            .require(MaterialBuilder.VertexAttribute.UV0)
            .material("""void material(inout MaterialInputs material) {
                    vec3 normal = normalize(texture(materialParams_normalMap, getUV0()).xyz * 2.0 - 1.0);
                    material.normal = normal;
                    prepareMaterial(material);
                    material.baseColor.rgb = materialParams.baseColor;
                    material.baseColor.a = 1.0;
                    material.reflectance = 1.0;
                    vec3 metallicRoughnessSample = texture(materialParams_metallicRoughness, getUV0()).xyz;
                    material.metallic = metallicRoughnessSample.b;
                    material.roughness =  metallicRoughnessSample.g;
                }""")
            .optimization(MaterialBuilder.Optimization.NONE)
            .build()
        
        if (matPackage2.isValid) {
            val buffer = matPackage2.buffer
            mat = Material.Builder().payload(buffer, buffer.remaining()).build(engine)
        }
        
        MaterialBuilder.shutdown()

        material = mat!!.createInstance()
        
        material?.setParameter("baseColor", Colors.RgbType.SRGB, 0.83f, 0.81f, 0.78f)
        val normal = loadTexture(engine, context.resources,  R.drawable.material_1_normal, TextureType.NORMAL)
        material.setParameter("normalMap", normal, TextureSampler())
        val metallicRoughnessSample = loadTexture(engine, context.resources,  R.drawable.material_1_metallic_roughness, TextureType.DATA)
        material.setParameter("metallicRoughness", metallicRoughnessSample, TextureSampler())`

Error:
` E/Filament: COMPILE ERROR: 
 E/Filament: 0:4: P0003: Warning: Extension 'GL_GOOGLE_cpp_style_line_directive' not supported
    0:2: L0001: Unknown character '"'(34)
    0:2: L0001: Unknown character '"'(34)
 E/Filament: 1:   #version 300 es
 E/Filament: 2:   
 E/Filament: 3:   #define TARGET_MOBILE
 E/Filament: 4:   #extension GL_GOOGLE_cpp_style_line_directive : enable
 E/Filament: 5:   
 E/Filament: 6:   precision mediump float;
 E/Filament: 7:   precision mediump int;
 E/Filament: 8:   #if !defined(TARGET_MOBILE) || defined(TARGET_LANGUAGE_SPIRV)
 E/Filament: 9:   #define LAYOUT_LOCATION(x) layout(location = x)
 E/Filament: 10:   #else
 E/Filament: 11:   #define LAYOUT_LOCATION(x)
 E/Filament: 12:   #endif
 E/Filament: 13:   #define bool2    bvec2
 E/Filament: 14:   #define bool3    bvec3
 E/Filament: 15:   #define bool4    bvec4
 E/Filament: 16:   #define int2     ivec2
 E/Filament: 17:   #define int3     ivec3
 E/Filament: 18:   #define int4     ivec4
 E/Filament: 19:   #define uint2    uvec2
 E/Filament: 20:   #define uint3    uvec3
 E/Filament: 21:   #define uint4    uvec4
 E/Filament: 22:   #define float2   vec2
 E/Filament: 23:   #define float3   vec3
 E/Filament: 24:   #define float4   vec4
 E/Filament: 25:   #define float3x3 mat3
 E/Filament: 26:   #define float4x4 mat4
 E/Filament: 27:   
 E/Filament: 28:   #define CLEAR_COAT_IOR_CHANGE
 E/Filament: 29:   #define MAX_SHADOW_CASTING_SPOTS 2
 E/Filament: 30:   #define SPECULAR_AMBIENT_OCCLUSION 0
 E/Filament: 31:   #define MULTI_BOUNCE_AMBIENT_OCCLUSION 0
 E/Filament: 32:   #define HAS_DIRECTIONAL_LIGHTING
 E/Filament: 33:   #define HAS_DYNAMIC_LIGHTING
 E/Filament: 34:   #define MATERIAL_HAS_DOUBLE_SIDED_CAPABILITY
 E/Filament: 35:   #define BLEND_MODE_OPAQUE
 E/Filament: 36:   #define POST_LIGHTING_BLEND_MODE_TRANSPARENT
 E/Filament: 37:   #define SHADING_MODEL_LIT
 E/Filament: 38:   #define MATERIAL_HAS_BASE_COLOR
 E/Filament: 39:   #define MATERIAL_HAS_ROUGHNESS
 E/Filament: 40:   #define MATERIAL_HAS_METALLIC
 E/Filament: 41:   #define MATERIAL_HAS_REFLECTANCE
 E/Filament: 42:   #define SHADING_INTERPOLATION 
 E/Filament: 43:   #define HAS_ATTRIBUTE_TANGENTS
 E/Filament: 44:   
 E/Filament: 45:   #if !defined(DEPTH_PREPASS)
 E/Filament: 46:   LAYOUT_LOCATION(4) in highp vec3 vertex_worldPosition;
 E/Filament: 47:   #endif
 E/Filament: 48:   #if defined(HAS_ATTRIBUTE_TANGENTS)
 E/Filament: 49:   LAYOUT_LOCATION(5) SHADING_INTERPOLATION in mediump vec3 vertex_worldNormal;
 E/Filament: 50:   #if defined(MATERIAL_NEEDS_TBN)
 E/Filament: 51:   LAYOUT_LOCATION(6) SHADING_INTERPOLATION in mediump vec4 vertex_worldTangent;
 E/Filament: 52:   #endif
 E/Filament: 53:   #endif
 E/Filament: 54:   LAYOUT_LOCATION(7) in highp vec4 vertex_position;
 E/Filament: 55:   #if defined(HAS_ATTRIBUTE_COLOR)
 E/Filament: 56:   LAYOUT_LOCATION(9) in mediump vec4 vertex_color;
 E/Filament: 57:   #endif
 E/Filament: 58:   #if defined(HAS_ATTRIBUTE_UV0) && !defined(HAS_ATTRIBUTE_UV1)
 E/Filament: 59:   LAYOUT_LOCATION(10) in highp vec2 vertex_uv01;
 E/Filament: 60:   #elif defined(HAS_ATTRIBUTE_UV1)
 E/Filament: 61:   LAYOUT_LOCATION(10) in highp vec4 vertex_uv01;
 E/Filament: 62:   #endif
 E/Filament: 63:   #if defined(HAS_SHADOWING) && defined(HAS_DIRECTIONAL_LIGHTING)
 E/Filament: 64:   LAYOUT_LOCATION(11) in highp vec4 vertex_lightSpacePosition;
 E/Filament: 65:   #endif
 E/Filament: 66:   #if defined(HAS_SHADOWING) && defined(HAS_DYNAMIC_LIGHTING)
 E/Filament: 67:   LAYOUT_LOCATION(12) in highp vec4 vertex_spotLightSpacePosition[MAX_SHADOW_CASTING_SPOTS];
 E/Filament: 68:   #endif
 E/Filament: 69:   layout(location = 0) out vec4 fragColor;
 E/Filament: 70:   
 E/Filament: 71:   layout(std140) uniform FrameUniforms {
 E/Filament: 72:       highp mat4 viewFromWorldMatrix;
 E/Filament: 73:       highp mat4 worldFromViewMatrix;
 E/Filament: 74:       highp mat4 clipFromViewMatrix;
 E/Filament: 75:       highp mat4 viewFromClipMatrix;
 E/Filament: 76:       highp mat4 clipFromWorldMatrix;
 E/Filament: 77:       highp mat4 worldFromClipMatrix;
 E/Filament: 78:       highp mat4 lightFromWorldMatrix[4];
 E/Filament: 79:       highp vec4 cascadeSplits;
 E/Filament: 80:       highp vec4 resolution;
 E/Filament: 81:       highp vec3 cameraPosition;
 E/Filament: 82:       highp float time;
 E/Filament: 83:       vec4 lightColorIntensity;
 E/Filament: 84:       vec4 sun;
 E/Filament: 85:       vec3 lightDirection;
 E/Filament: 86:       uint fParamsX;
 E/Filament: 87:       vec3 shadowBias;
 E/Filament: 88:       float oneOverFroxelDimensionY;
 E/Filament: 89:       vec4 zParams;
 E/Filament: 90:       uvec2 fParams;
 E/Filament: 91:       vec2 origin;
 E/Filament: 92:       float oneOverFroxelDimension;
 E/Filament: 93:       float iblLuminance;
 E/Filament: 94:       float exposure;
 E/Filament: 95:       float ev100;
 E/Filament: 96:       vec3 iblSH[9];
 E/Filament: 97:       vec4 userTime;
 E/Filament: 98:       float iblRoughnessOneLevel;
 E/Filament: 99:       float cameraFar;
 E/Filament: 100:       float refractionLodOffset;
 E/Filament: 101:       uint directionalShadows;
 E/Filament: 102:       vec3 worldOffset;
 E/Filament: 103:       float ssContactShadowDistance;
 E/Filament: 104:       float fogStart;
 E/Filament: 105:       float fogMaxOpacity;
 E/Filament: 106:       float fogHeight;
 E/Filament: 107:       float fogHeightFalloff;
 E/Filament: 108:       vec3 fogColor;
 E/Filament: 109:       float fogDensity;
 E/Filament: 110:       float fogInscatteringStart;
 E/Filament: 111:       float fogInscatteringSize;
 E/Filament: 112:       float fogColorFromIbl;
 E/Filament: 113:       uint cascades;
 E/Filament: 114:       float aoSamplingQuality;
 E/Filament: 115:       float aoReserved1;
 E/Filament: 116:       float aoReserved2;
 E/Filament: 117:       float aoReserved3;
 E/Filament: 118:       vec4 padding2[62];
 E/Filament: 119:   } frameUniforms;
 E/Filament: 120:   
 E/Filament: 121:   layout(std140) uniform ObjectUniforms {
 E/Filament: 122:       highp mat4 worldFromModelMatrix;
 E/Filament: 123:       highp mat3 worldFromModelNormalMatrix;
 E/Filament: 124:       highp vec4 morphWeights;
 E/Filament: 125:       int skinningEnabled;
 E/Filament: 126:       int morphingEnabled;
 E/Filament: 127:       uint screenSpaceContactShadows;
 E/Filament: 128:       float padding0;
 E/Filament: 129:   } objectUniforms;
 E/Filament: 130:   
 E/Filament: 131:   layout(std140) uniform LightsUniforms {
 E/Filament: 132:       highp mat4 lights[256];
 E/Filament: 133:   } lightsUniforms;
 E/Filament: 134:   
 E/Filament: 135:   layout(std140) uniform MaterialParams {
 E/Filament: 136:       vec3 baseColor;
 E/Filament: 137:       bool _doubleSided;
 E/Filament: 138:   } materialParams;
 E/Filament: 139:   
 E/Filament: 140:   uniform mediump sampler2DArrayShadow light_shadowMap;
 E/Filament: 141:   uniform mediump usampler2D light_records;
 E/Filament: 142:   uniform mediump usampler2D light_froxels;
 E/Filament: 143:   uniform mediump sampler2D light_iblDFG;
 E/Filament: 144:   uniform mediump samplerCube light_iblSpecular;
 E/Filament: 145:   uniform mediump sampler2D light_ssao;
 E/Filament: 146:   uniform mediump sampler2D light_ssr;
 E/Filament: 147:   uniform mediump sampler2D light_structure;
 E/Filament: 148:   
 E/Filament: 149:   
 E/Filament: 150:   #define PI                 3.14159265359
 E/Filament: 151:   #define HALF_PI            1.570796327
 E/Filament: 152:   #define MEDIUMP_FLT_MAX    65504.0
 E/Filament: 153:   #define MEDIUMP_FLT_MIN    0.00006103515625
 E/Filament: 154:   #ifdef TARGET_MOBILE
 E/Filament: 155:   #define FLT_EPS            MEDIUMP_FLT_MIN
 E/Filament: 156:   #define saturateMediump(x) min(x, MEDIUMP_FLT_MAX)
 E/Filament: 157:   #else
 E/Filament: 158:   #define FLT_EPS            1e-5
 E/Filament: 159:   #define saturateMediump(x) x
 E/Filament: 160:   #endif
 E/Filament: 161:   #define saturate(x)        clamp(x, 0.0, 1.0)
 E/Filament: 162:   #define atan2(x, y)        atan(y, x)
 E/Filament: 163:   float pow5(float x) {
 E/Filament: 164:   float x2 = x * x;
 E/Filament: 165:   return x2 * x2 * x;
 E/Filament: 166:   }
 E/Filament: 167:   float sq(float x) {
 E/Filament: 168:   return x * x;
 E/Filament: 169:   }
 E/Filament: 170:   float max3(const vec3 v) {
 E/Filament: 171:   return max(v.x, max(v.y, v.z));
 E/Filament: 172:   }
 E/Filament: 173:   float min3(const vec3 v) {
 E/Filament: 174:   return min(v.x, min(v.y, v.z));
 E/Filament: 175:   }
 E/Filament: 176:   float acosFast(float x) {
 E/Filament: 177:   float y = abs(x);
 E/Filament: 178:   float p = -0.1565827 * y + 1.570796;
 E/Filament: 179:   p *= sqrt(1.0 - y);
 E/Filament: 180:   return x >= 0.0 ? p : PI - p;
 E/Filament: 181:   }
 E/Filament: 182:   float acosFastPositive(float x) {
 E/Filament: 183:   float p = -0.1565827 * x + 1.570796;
 E/Filament: 184:   return p * sqrt(1.0 - x);
 E/Filament: 185:   }
 E/Filament: 186:   vec4 mulMat4x4Float3(const highp mat4 m, const highp vec3 v) {
 E/Filament: 187:   return v.x * m[0] + (v.y * m[1] + (v.z * m[2] + m[3]));
 E/Filament: 188:   }
 E/Filament: 189:   vec3 mulMat3x3Float3(const highp mat4 m, const highp vec3 v) {
 E/Filament: 190:   return v.x * m[0].xyz + (v.y * m[1].xyz + (v.z * m[2].xyz));
 E/Filament: 191:   }
 E/Filament: 192:   void toTangentFrame(const highp vec4 q, out highp vec3 n) {
 E/Filament: 193:   n = vec3( 0.0,  0.0,  1.0) +
 E/Filament: 194:   vec3( 2.0, -2.0, -2.0) * q.x * q.zwx +
 E/Filament: 195:   vec3( 2.0,  2.0, -2.0) * q.y * q.wzy;
 E/Filament: 196:   }
 E/Filament: 197:   void toTangentFrame(const highp vec4 q, out highp vec3 n, out highp vec3 t) {
 E/Filament: 198:   toTangentFrame(q, n);
 E/Filament: 199:   t = vec3( 1.0,  0.0,  0.0) +
 E/Filament: 200:   vec3(-2.0,  2.0, -2.0) * q.y * q.yxw +
 E/Filament: 201:   vec3(-2.0,  2.0,  2.0) * q.z * q.zwx;
 E/Filament: 202:   }
 E/Filament: 203:   
 E/Filament: 204:   #if defined(HAS_SHADOWING)
 E/Filament: 205:   vec4 computeLightSpacePosition(const vec3 p, const vec3 n, const vec3 l, const float b,
 E/Filament: 206:   const mat4 lightFromWorldMatrix) {
 E/Filament: 207:   float NoL = saturate(dot(n, l));
 E/Filament: 208:   float sinTheta = sqrt(1.0 - NoL * NoL);
 E/Filament: 209:   vec3 offsetPosition = p + n * (sinTheta * b);
 E/Filament: 210:   vec4 lightSpacePosition = (lightFromWorldMatrix * vec4(offsetPosition, 1.0));
 E/Filament: 211:   return lightSpacePosition;
 E/Filament: 212:   }
 E/Filament: 213:   #endif
 E/Filament: 214:   
 E/Filament: 215:   highp mat3  shading_tangentToWorld;
 E/Filament: 216:   highp vec3  shading_position;
 E/Filament: 217:   vec3  shading_view;
 E/Filament: 218:   vec3  shading_normal;
 E/Filament: 219:   vec3  shading_geometricNormal;
 E/Filament: 220:   vec3  shading_reflected;
 E/Filament: 221:   float shading_NoV;
 E/Filament: 222:   #if defined(MATERIAL_HAS_BENT_NORMAL)
 E/Filament: 223:   vec3  shading_bentNormal;
 E/Filament: 224:   #endif
 E/Filament: 225:   #if defined(MATERIAL_HAS_CLEAR_COAT)
 E/Filament: 226:   vec3  shading_clearCoatNormal;
 E/Filament: 227:   #endif
 E/Filament: 228:   highp vec2 shading_normalizedViewportCoord;
 E/Filament: 229:   
 E/Filament: 230:   float luminance(const vec3 linear) {
 E/Filament: 231:   return dot(linear, vec3(0.2126, 0.7152, 0.0722));
 E/Filament: 232:   }
 E/Filament: 233:   float computePreExposedIntensity(const highp float intensity, const highp float exposure) {
 E/Filament: 234:   return intensity * exposure;
 E/Filament: 235:   }
 E/Filament: 236:   void unpremultiply(inout vec4 color) {
 E/Filament: 237:   color.rgb /= max(color.a, FLT_EPS);
 E/Filament: 238:   }
 E/Filament: 239:   vec3 ycbcrToRgb(float luminance, vec2 cbcr) {
 E/Filament: 240:   const mat4 ycbcrToRgbTransform = mat4(
 E/Filament: 241:   1.0000,  1.0000,  1.0000,  0.0000,
 E/Filament: 242:   0.0000, -0.3441,  1.7720,  0.0000,
 E/Filament: 243:   1.4020, -0.7141,  0.0000,  0.0000,
 E/Filament: 244:   -0.7010,  0.5291, -0.8860,  1.0000
 E/Filament: 245:   );
 E/Filament: 246:   return (ycbcrToRgbTransform * vec4(luminance, cbcr, 1.0)).rgb;
 E/Filament: 247:   }
 E/Filament: 248:   vec3 Inverse_Tonemap_Unreal(const vec3 x) {
 E/Filament: 249:   return (x * -0.155) / (x - 1.019);
 E/Filament: 250:   }
 E/Filament: 251:   vec3 inverseTonemapSRGB(vec3 color) {
 E/Filament: 252:   color = clamp(color, 0.0, 1.0);
 E/Filament: 253:   return Inverse_Tonemap_Unreal(color);
 E/Filament: 254:   }
 E/Filament: 255:   vec3 inverseTonemap(vec3 linear) {
 E/Filament: 256:   linear = clamp(linear, 0.0, 1.0);
 E/Filament: 257:   return Inverse_Tonemap_Unreal(pow(linear, vec3(1.0 / 2.2)));
 E/Filament: 258:   }
 E/Filament: 259:   vec3 decodeRGBM(vec4 c) {
 E/Filament: 260:   c.rgb *= (c.a * 16.0);
 E/Filament: 261:   return c.rgb * c.rgb;
 E/Filament: 262:   }
 E/Filament: 263:   vec3 heatmap(float v) {
 E/Filament: 264:   vec3 r = v * 2.1 - vec3(1.8, 1.14, 0.3);
 E/Filament: 265:   return 1.0 - r * r;
 E/Filament: 266:   }
 E/Filament: 267:   vec3 uintToColorDebug(uint v) {
 E/Filament: 268:   if (v == 0u) {
 E/Filament: 269:   return vec3(0.0, 1.0, 0.0);
 E/Filament: 270:   } else if (v == 1u) {
 E/Filament: 271:   return vec3(0.0, 0.0, 1.0);
 E/Filament: 272:   } else if (v == 2u) {
 E/Filament: 273:   return vec3(1.0, 1.0, 0.0);
 E/Filament: 274:   } else if (v == 3u) {
 E/Filament: 275:   return vec3(1.0, 0.0, 0.0);
 E/Filament: 276:   } else if (v == 4u) {
 E/Filament: 277:   return vec3(1.0, 0.0, 1.0);
 E/Filament: 278:   } else if (v == 5u) {
 E/Filament: 279:   return vec3(0.0, 1.0, 1.0);
 E/Filament: 280:   }
 E/Filament: 281:   }
 E/Filament: 282:   #if defined(TARGET_MOBILE)
 E/Filament: 283:   #define MIN_PERCEPTUAL_ROUGHNESS 0.089
 E/Filament: 284:   #define MIN_ROUGHNESS            0.007921
 E/Filament: 285:   #else
 E/Filament: 286:   #define MIN_PERCEPTUAL_ROUGHNESS 0.045
 E/Filament: 287:   #define MIN_ROUGHNESS            0.002025
 E/Filament: 288:   #endif
 E/Filament: 289:   #define MIN_N_DOT_V 1e-4
 E/Filament: 290:   float clampNoV(float NoV) {
 E/Filament: 291:   return max(NoV, MIN_N_DOT_V);
 E/Filament: 292:   }
 E/Filament: 293:   vec3 computeDiffuseColor(const vec4 baseColor, float metallic) {
 E/Filament: 294:   return baseColor.rgb * (1.0 - metallic);
 E/Filament: 295:   }
 E/Filament: 296:   vec3 computeF0(const vec4 baseColor, float metallic, float reflectance) {
 E/Filament: 297:   return baseColor.rgb * metallic + (reflectance * (1.0 - metallic));
 E/Filament: 298:   }
 E/Filament: 299:   float computeDielectricF0(float reflectance) {
 E/Filament: 300:   return 0.16 * reflectance * reflectance;
 E/Filament: 301:   }
 E/Filament: 302:   float computeMetallicFromSpecularColor(const vec3 specularColor) {
 E/Filament: 303:   return max3(specularColor);
 E/Filament: 304:   }
 E/Filament: 305:   float computeRoughnessFromGlossiness(float glossiness) {
 E/Filament: 306:   return 1.0 - glossiness;
 E/Filament: 307:   }
 E/Filament: 308:   float perceptualRoughnessToRoughness(float perceptualRoughness) {
 E/Filament: 309:   return perceptualRoughness * perceptualRoughness;
 E/Filament: 310:   }
 E/Filament: 311:   float roughnessToPerceptualRoughness(float roughness) {
 E/Filament: 312:   return sqrt(roughness);
 E/Filament: 313:   }
 E/Filament: 314:   float iorToF0(float transmittedIor, float incidentIor) {
 E/Filament: 315:   return sq((transmittedIor - incidentIor) / (transmittedIor + incidentIor));
 E/Filament: 316:   }
 E/Filament: 317:   float f0ToIor(float f0) {
 E/Filament: 318:   float r = sqrt(f0);
 E/Filament: 319:   return (1.0 + r) / (1.0 - r);
 E/Filament: 320:   }
 E/Filament: 321:   vec3 f0ClearCoatToSurface(const vec3 f0) {
 E/Filament: 322:   #if defined(TARGET_MOBILE)
 E/Filament: 323:   return saturate(f0 * (f0 * 0.526868 + 0.529324) - 0.0482256);
 E/Filament: 324:   #else
 E/Filament: 325:   return saturate(f0 * (f0 * (0.941892 - 0.263008 * f0) + 0.346479) - 0.0285998);
 E/Filament: 326:   #endif
 E/Filament: 327:   }
 E/Filament: 328:   
 E/Filament: 329:   mat4 getViewFromWorldMatrix() {
 E/Filament: 330:   return frameUniforms.viewFromWorldMatrix;
 E/Filament: 331:   }
 E/Filament: 332:   mat4 getWorldFromViewMatrix() {
 E/Filament: 612:   shading_view = normalize(frameUniforms.cameraPosition - shading_position);
 E/Filament: 626:   #endif
 E/Filament: 634:   #endif
 E/Filament: 636:   
 E/Filament: 660:   fogColor += sunColor * (sunInscattering * inscatteringOpacity);
 E/Filament: 662:   #if   defined(BLEND_MODE_OPAQUE)
 E/Filament: 669:   #elif defined(BLEND_MODE_SCREEN)
 E/Filament: 683:                       material.roughness = 0.0;
 E/Filament: 717:   #if defined(SHADING_MODEL_SUBSURFACE) || defined(HAS_REFRACTION)
 E/Filament: 719:   #endif
 E/Filament: 731:   float uThickness;
 E/Filament: 733:   #endif
 E/Filament: 809:   return saturateMediump(v);
 E/Filament: 826:   }
 E/Filament: 863:   #if BRDF_CLEAR_COAT_D == SPECULAR_D_GGX
 E/Filament: 874:   return D_Charlie(roughness, NoH);
 E/Filament: 876:   }
 E/Filament: 883:   return 1.0 / PI;
 E/Filament: 885:   float Fd_Burley(float roughness, float NoV, float NoL, float LoH) {
 E/Filament: 899:   #endif
 E/Filament: 934:   }
 E/Filament: 1047:   }
 E/Filament: 1049:   float SpecularAO_Cones(float NoV, float visibility, float roughness) {
 E/Filament: 1051:   float cosAv = sqrt(1.0 - visibility);
 E/Filament: 1054:   float ao = sphericalCapsIntersection(cosAv, cosAs, cosB) / (1.0 - cosAs);
 E/Filament: 1066:   return 1.0;
 E/Filament: 1068:   }
 E/Filament: 1086:   }
 E/Filament: 1127:   return decodeDataForIBL(textureLod(light_iblSpecular, n, frameUniforms.iblRoughnessOneLevel));
 E/Filament: 1135:   float du = 1.0 / float(s.x);
 E/Filament: 1137:   vec3 m0 = normalize(cross(n, vec3(0.0, 1.0, 0.0)));
 E/Filament: 1139:   vec3 m0du = m0 * du;
 E/Filament: 1154:   }
 E/Filament: 1174:   #if defined(MATERIAL_HAS_ANISOTROPY)
 E/Filament: 1176:   vec3  anisotropicTangent  = cross(anisotropyDirection, v);
 E/Filament: 1178:   float bendFactor          = abs(pixel.anisotropy) * saturate(5.0 * pixel.perceptualRoughness);
 E/Filament: 1194:   #if IBL_INTEGRATION == IBL_INTEGRATION_IMPORTANCE_SAMPLING
 E/Filament: 1197:   const uint numSampleBits = uint(log2(float(numSamples)));
 E/Filament: 1219:   vec3 up = abs(v.z) < 0.9999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
 E/Filament: 1221:   vec3 b = cross(t, v);
 E/Filament: 1299:   #if defined(MATERIAL_HAS_SUBSURFACE_COLOR)
 E/Filament: 1307:   return;
 E/Filament: 1309:   #if defined(MATERIAL_HAS_CLEAR_COAT)
 E/Filament: 1331:   #elif defined(SHADING_MODEL_CLOTH) && defined(MATERIAL_HAS_SUBSURFACE_COLOR)
 E/Filament: 1333:   #endif
 E/Filament: 1337:   vec3 position;
 E/Filament: 1358:   ray.d = d;
 E/Filament: 1377:   }
 E/Filament: 1390:   #if defined(MATERIAL_HAS_THICKNESS) || defined(MATERIAL_HAS_MICRO_THICKNESS)
 E/Filament: 1392:   #else
 E/Filament: 1394:   #endif
 E/Filament: 1396:   float perceptualRoughness = pixel.perceptualRoughnessUnclamped;
 E/Filament: 1398:   perceptualRoughness = saturate((0.65 * pixel.etaRI - 0.35) * perceptualRoughness);
 E/Filament: 1408:   vec3 Ft = textureLod(light_ssr, p.xy, lod).rgb;
 E/Filament: 1410:   Ft *= 1.0 - E;
 E/Filament: 1719:   pixel.clearCoat = material.clearCoat;
 E/Filament: 1734:   void getRoughnessPixelParams(const MaterialInputs material, inout PixelParams pixel) {`

**Comment by romainguy** [comment]
Can you make sure to run your materials through the optimizer? This should be the default behavior of `matc` and it will fix your problem.

@prideout @bejado Looks like `GL_GOOGLE_cpp_style_line_directive` is causing issues on some devices when shaders don't go through the optimizer stage.

**Comment by zxPhoenix** [comment]
@romainguy , Can I use optimizer from sources without using matc and how? Looks like changing of .optimization() builds non valid material.

**Comment by romainguy** [comment]
You need to use the full version of `filamat`. If you can't use that (it's larger), please wait for a fix on our side.

**Comment by zxPhoenix** [comment]
Ok. I just tried full version and tried all values for .optimization() method but the issue hasn't gone. I'll wait for fix. Thanks.

**Comment by prideout** [comment]
This is similar to #2800, where chrome (and some mobile drivers apparently) is validating the GLSL string before pre-processing, which is non-conformant behavior according to the spec.  Ben: since this is affecting more than chrome we might need a workaround :(

**Comment by zxPhoenix** [comment]
Sorry guys, I made mistake. Optimization() method works. But, in this case I have some problem with lights. Looks like some (maybe directional) light can disappear or change position after first app run. I see it on complex object with multiple reflections. Filament 1.7 has the problem with lights too. I'd like to have shader without any optimizations. Thanks.

**Comment by romainguy** [comment]
Any reason why you want unoptimized shaders?
