### ISSUE TITLE
Doesn't build on BSD: please provide an implementation based on POSIX mutexes

### ISSUE THREAD

**Issue by yurivict** [google/filament#2861]
```filament``` uses Linux-specific call ```futex``` here: https://github.com/google/filament/blob/main/libs/utils/src/linux/futex.h#L36

This causes ```filament``` to not compile on BSDs.

Could you please provide an implementation based on POSIX mutexes so that ```filament``` would be able to work on all OSes?

Thank you,
Yuri

**Comment by romainguy** [comment]
We may make other Linux assumptions in other places.

**Comment by pixelflinger** [comment]
Okay noted. This will take some time to clean-up our makefiles.
