### ISSUE TITLE
Directional light issue for unoptimized shaders

### ISSUE THREAD

**Issue by zxPhoenix** [google/filament#2866]
Any reason why you want unoptimized shaders?

_Originally posted by @romainguy in https://github.com/google/filament/issues/2857#issuecomment-663168898_

Looks like it’s another issue. I use directional light for highlight gemstones in my scene. It works as expected for non optimized shaders and disappear or not reflected (I’m not sure) for optimized shader after first app launch. First run is ok but I lose directional light for next launches till application reinstall.   It doesn’t depends of material which I optimize. I can optimize steel material and will lose lights for gems.
Samples: [without optimizations](https://prnt.sc/tng617),  [with optimizations](https://prnt.sc/tng73r)

FYI, I tried point lights and those lights works good for optimized and non optimized shaders. Looks like this behaviour is actual for directional light only.

**Comment by romainguy** [comment]
If it works on first launch it could be a shader cache issue, and that would be a driver bug. There’s nothing different across launches as far filament is concerned. I unfortunately don’t think there’s anything actionable here on our side :/

**Comment by romainguy** [comment]
What device does this happen on?

**Comment by zxPhoenix** [comment]
It's reproducible on OnePlus 6T Android 10 and Samsung Galaxy Note 10+ Android 10. Unfortunately, I don't have other devices to check the issue.

**Comment by romainguy** [comment]
Do you have shadows turned on btw?

**Comment by zxPhoenix** [comment]
I use .castShadows(false)

**Comment by pixelflinger** [comment]
not actionable / shader compiler bug
