### ISSUE TITLE
Android crash when creating engine (randomly occurred)

### ISSUE THREAD

**Issue by DianxinWang** [google/filament#2867]
When some of our users were using our app which use filament as a backend, the app would crash (not sure how often it is) and we fail to reproduce.
![image](https://user-images.githubusercontent.com/36990568/88373601-b3b08780-cdca-11ea-9f1d-3c92fe99ce07.png)

based on the log, we found it crashed at 
![image](https://user-images.githubusercontent.com/36990568/88373896-3d605500-cdcb-11ea-8235-449aeaddd9d5.png)

Can you please explain more about the comments and in what cases will this fail?

These are the phones that crash.
[OPPO R11s;Android 8.1.0,level 27]
[POT-AL00a;Android 10,level 29]
[MI 9 SE;Android 10,level 29]
And more

By the way, we are using filament release 1.4.5.

**Comment by romainguy** [comment]
This was fixed in later versions of Filament. Also please make sure to always invoice filament from the same thread in your app.
