### ISSUE TITLE
What is the correct way to completely clean up an Entity?

### ISSUE THREAD

**Issue by roxlu** [google/filament#2868]
When I create a `utils::Entity` using `utils::EntityManager::get().create()` and then use that to create a renderable instance, transform instance etc. what is the correct way to clean up this entity when I want to destroy all data/references from it?

How do I know if an entity has been destroyed/cleaned completely and not used anymore? 

Is this correct or missing something:

```c++
// create
Entity enitty = EntityManager::get().create();
RenderableManager::Builder(1).build(*engine, entity);
engine->getTransformManager().setTransform(...entity...);

// cleanup 
engine->destroy(entity);
utils::EntityManager::get().destroy(entity);
```

**Comment by romainguy** [comment]
That's the correct way yes.

**Comment by roxlu** [comment]
Thanks @romainguy  

I would expect that `entity.isNull()` would return true after cleaning up using the above snippet. This is not the case, it returns false. Is this on purpose?

**Comment by romainguy** [comment]
An entity is just an integer, it won't be modified by calling `destroy(entity)`. You can use `EntityManager::isAlive(entity)` though.

**Comment by roxlu** [comment]
What's the use of `isNull()` ? To check if it has been created by the manager? 

Thanks for thhe pointer to `isAlive()`, I will use that instead.

**Comment by romainguy** [comment]
It tells you if the entity is valid effectively. Or if you just want to have the concept of  uninitialized entities in your code base (just like with nullptr for instance).

**Comment by roxlu** [comment]
When I call `EntityManager::get().destroy(entity)`  the entity is *not* null and not alive anymore. 

Would it make sense to calll `entity.clear()` once it's destroyed?  

Or can the entity have another purpose after it's been destroyed?  I don't think `reusing` a destroyed entity with other components is valid.
