### ISSUE TITLE
Black screen on NVidia 1080 ti, Vulkan Backend

### ISSUE THREAD

**Issue by alex-mat** [google/filament#2872]
Hello,

I have an issue with filament, a black screen when presenting the frame on the Vulkan backend, on OpenGL works correctly.
GPU is NVidia 1080 TI, drivers tried 445, and latest both whql and 451 developer driver.
OS is Windows 10 64 bits 18363.
Issue is present both with prebuild filament libs and my own build, both debug and release, whether it is my own engine or samples such as gltf_viewer. Tried disabling NV optimizations, messing with vsync in control panel, nothing.
When analyzing the frame using RenderDoc, I can see that all the rendering is done normally, everything is ok up until vkQueuePresentKHR.
Unfortunately I don't have any other vulkan compatible hardware on hand to test on.

I can provide the RenderDoc capture if needed.

Thanks for any insight regarding this issue.

**Comment by prideout** [comment]
Can you try a debug build?  This would enable validation layers.

**Comment by alex-mat** [comment]
Oh I meant to include that

```
FEngine (64 bits) created at 000001AA19E8C080 (threading is enabled)
FEngine resolved backend: Vulkan
Selected physical device 'GeForce GTX 1080 Ti' from 1 physical devices. (vendor 0x0x10de, device 0x0x1b06, driver 0x0x70d3c000, api 1.2)
Sampleable depth formats: VK_FORMAT_D16_UNORM VK_FORMAT_X8_D24_UNORM_PACK32 VK_FORMAT_D32_SFLOAT VK_FORMAT_S8_UINT VK_FORMAT_D24_UNORM_S8_UINT VK_FORMAT_D32_SFLOAT_S8_UINT
vkCreateSwapchain: 1024x640, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 3
VULKAN WARNING: (Validation) Validation Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x1ee3a20000000047, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | fragment shader writes to output location 0 with no matching attachment
VULKAN WARNING: (Validation) Validation Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x1ee3a20000000047, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | fragment shader writes to output location 0 with no matching attachment
```

**Comment by bejado** [comment]
I'm on a GeForce GTX 970. At first I wasn't able to reproduce, then I updated my NVIDIA driver to version 451.67 and now I see that black screen when running gltf_viewer and suzanne with Vulkan. Very interesting. I don't remember the exact version I upgraded from, but I believe it was circa November 2019.

**Comment by romainguy** [comment]
Please try with more recent versions of Filament
