### ISSUE TITLE
Full cross platform support using Flutter and Dart:FFI

### ISSUE THREAD

**Issue by sharp3dges** [google/filament#2877]
Related to #2036 which got closed IMHO due to lack of support for C-interop functions in flutter.

Would it be possible to use the [Dart FFI](https://api.dart.dev/dev/2.10.0-0.0.dev/dart-ffi/dart-ffi-library.html) to fully enable support for flutter?
This would mean Filament would be able to run on web, android, ios and desktop on a single code-base.
Also it would be the first full-blown-3d-engine entirely running on flutter.
With the API's exposed there should be only the need for a simple flutter plugin instantiating the engine and binding it to a SurfaceView / MetalView.

**Comment by romainguy** [comment]
I'm sure it's possible to use the Dart FFI but our small team must already support many platforms, graphics APIs, and bindings and we don't have the resources to take on more such bindings for now. We would welcome any contributions in that space though.

**Comment by azhong-git** [comment]
From 2023, +1 on Flutter and [Dart FFI](https://api.dart.dev/dev/2.10.0-0.0.dev/dart-ffi/dart-ffi-library.html)

Single codebase for android + web is already killer feature. Flutter makes it a great candidate given it supports wasm (React cannot).

**Comment by nmfisher** [comment]
I have mostly implemented cross-platform bindings for Flutter (iOS/MacOS/Android/Linux, web & Windows TBA). I do intend on open-sourcing it soon(ish), if anyone need something sooner please reach out to me.

I did actually initially implement a version using FFI which was nice and compact (basically a single Dart file with auto-generated bindings for all platforms) but I set it aside in favour of platform channels (Flutter will make all FFI calls on its own non-rendering thread which can get a bit sluggish). Another option is FFI from background isolate but currently there's no way to pin an isolate to a specific thread (which won't work with Filament). Last time I checked this was being implemented so once this lands that might be a better alternative.
