### ISSUE TITLE
How can I change Material property value at run time?

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#2882]
e.g. depthWrite、doubleSided、flipUV...
Can you give some advice？

**Comment by romainguy** [comment]
If the property is not exposed as an API on Material/MaterialInstance then it cannot be changed at runtime because it would require generating new shaders. You can either use libfilamat or simply swap material. Depth write and double sidef can be changed at runtime. FlipUV cannot.

**Comment by cjsliuj** [comment]
thanks
