### ISSUE TITLE
Build failure on Unbuntu 16.04

### ISSUE THREAD

**Issue by daichen** [google/filament#2890]
**Describe the bug**
cmake 3.18
clang-8 
libc++-8-dev
libc++abi-8-dev

**To Reproduce**
1. run command   ./build.sh -p android release
Building release in out/cmake-release...
-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/cc
-- DFG LUT size set to 128x128
-- Found Python3: /usr/bin/python3.5 (found version "3.5.2") found components: Interpreter 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
-- Found Java: /usr/lib/jvm/java-8-openjdk-amd64/bin/java (found version "1.8.0_252") 
-- Found JNI: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjawt.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mi/work/code/filament/out/cmake-release
[516/672] Linking CXX executable tools/resgen/resgen
FAILED: : && /usr/bin/c++ -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections tools/resgen/CMakeFiles/resgen.dir/src/main.cpp.o -o tools/resgen/resgen  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/utils/libutils.a  third_party/getopt/libgetopt.a  -Wl,-Bdynamic  -pthread  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: linker command failed due to signal (use -v to see invocation)
[516/672] Building CXX object third_party/spirv-cross/tnt/CMakeFiles/spirv-cross-msl.dir/__/spirv_msl.cpp.o
ninja: build stopped: subcommand failed.

**Comment by daichen** [comment]
/build.sh -c debug

Cleaning build directories...
Building debug in out/cmake-debug...
-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/cc
-- DFG LUT size set to 128x128
-- Found Python3: /usr/bin/python3.5 (found version "3.5.2") found components: Interpreter 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
-- Found Java: /usr/lib/jvm/java-8-openjdk-amd64/bin/java (found version "1.8.0_252") 
-- Found JNI: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjawt.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mi/work/code/filament/out/cmake-debug
[84/1275] Linking CXX executable libs/camutils/test_camutils
FAILED: : && /usr/bin/c++ -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector -Wl,--gc-sections libs/camutils/CMakeFiles/test_camutils.dir/tests/test_camutils.cpp.o -o libs/camutils/test_camutils  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/camutils/libcamutils.a  third_party/libgtest/tnt/libgtest.a  libs/math/libmath.a  -Wl,-Bdynamic  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic  -pthread && :
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: linker command failed due to signal (use -v to see invocation)
[84/1275] Linking CXX executable libs/math/test_math
FAILED: : && /usr/bin/c++ -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector -Wl,--gc-sections libs/math/CMakeFiles/test_math.dir/tests/test_fast.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_half.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_mat.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_vec.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_quat.cpp.o -o libs/math/test_math  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/math/libmath.a  third_party/libgtest/tnt/libgtest.a  -Wl,-Bdynamic  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic  -pthread && :
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: linker command failed due to signal (use -v to see invocation)
[84/1275] Building CXX object libs/utils/CMakeFiles/test_utils.dir/test/test_JobSystem.cpp.o
ninja: build stopped: subcommand failed.

**Comment by romainguy** [comment]
Your linker crashed, this is unfortunately not something we can fix.
