### ISSUE TITLE
Apply custom material on ModelViewer

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#2891]
Hi, I am referencing this post.

https://medium.com/@philiprideout/getting-started-with-filament-on-android-d10b16f0ec67

I am able to load .gltf model. but I want to change model inner parts color runtime. is that possible with Modelviewer?

i tried to apply custom material with below code but i got this crash 

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x784cf77310 in tid 5846 (FEngine::loop), pid 5801 (.filamentsample)

Here is the code.

 private fun buildMaterial() {
        // MaterialBuilder.init() must be called before any MaterialBuilder methods can be used.
        // It only needs to be called once per process.
        // When your app is done building materials, call MaterialBuilder.shutdown() to free
        // internal MaterialBuilder resources.
        MaterialBuilder.init()

        engine = Engine.create()

        val matPackage = MaterialBuilder()
            // By default, materials are generated only for DESKTOP. Since we're an Android
            // app, we set the platform to MOBILE.
            .platform(MaterialBuilder.Platform.MOBILE)

            // Set the name of the Material for debugging purposes.
            .name("Clear coat")

            // Defaults to LIT. We could change the shading model here if we desired.
            .shading(MaterialBuilder.Shading.LIT)

            // Add a parameter to the material that can be set via the setParameter method once
            // we have a material instance.
            .uniformParameter(MaterialBuilder.UniformType.FLOAT3, "baseColor")

            // Fragment block- see the material readme (docs/Materials.md.html) for the full
            // specification.
            .material(
                "void material(inout MaterialInputs material) {\n" +
                        "    prepareMaterial(material);\n" +
                        "    material.baseColor.rgb = materialParams.baseColor;\n" +
                        "    material.roughness = 0.65;\n" +
                        "    material.metallic = 1.0;\n" +
                        "    material.clearCoat = 1.0;\n" +
                        "}\n"
            )

            // Turn off shader code optimization so this sample is compatible with the "lite"
            // variant of the filamat library.
            .optimization(MaterialBuilder.Optimization.NONE)

            .build()

        if (matPackage.isValid) {
            val buffer = matPackage.buffer
            material = Material.Builder().payload(buffer, buffer.remaining()).build(engine)
        }

        // We're done building materials, so we call shutdown here to free resources. If we wanted
        // to build more materials, we could call MaterialBuilder.init() again (with a slight
        // performance hit).
        MaterialBuilder.shutdown()
    }

 private fun setupMaterial() {
        // Create an instance of the material to set different parameters on it
        materialInstance = material.createInstance()
        // Specify that our color is in sRGB so the conversion to linear
        // is done automatically for us. If you already have a linear color
        // you can pass it directly, or use Colors.RgbType.LINEAR
        materialInstance.setParameter("baseColor", Colors.RgbType.SRGB, 0.71f, 0.0f, 0.0f)
    }

 private fun createRenderables() {
        val buffer = assets.open("models/ANDROID_ASSET.gltf").use { input ->
            val bytes = ByteArray(input.available())
            input.read(bytes)
            ByteBuffer.wrap(bytes)
        }

        modelViewer.loadModelGltfAsync(buffer) { uri -> readCompressedAsset("models/$uri") }
        modelViewer.transformToUnitCube()
        modelViewer.asset?.materialInstances?.set(0,materialInstance)
    }

This is how i am trying to access and change material.

 val asset = modelViewer.asset!!
        val rm = modelViewer.engine.renderableManager
        for (entity in asset.entities) {
            println("name ${asset.getName(entity)}")

            val renderable = rm.getInstance(entity)
            if (renderable == 0) {
                continue
            }
            rm.setMaterialInstanceAt(renderable,0,materialInstance)
        }

**Comment by chiragchauhan1073** [comment]
@romainguy Any thought on this?

**Comment by romainguy** [comment]
It is possible but we need more information, like the full stack trace.

**Comment by chiragchauhan1073** [comment]
when i try to apply material like this 
 rm.setMaterialInstanceAt(renderable,0,materialInstance)
it crashes. 
Here is the crash log 
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x784cf77310 in tid 5846 (FEngine::loop), pid 5801 (.filamentsample)

**Comment by romainguy** [comment]
Please provide the full crash log not just the first line.

**Comment by chiragchauhan1073** [comment]
Crash log 

2020-07-30 21:55:40.197 27619-27619/? I/.filamentsampl: Late-enabling -Xcheck:jni
2020-07-30 21:55:40.589 27619-27619/com..filamentsample D/OpenGLRenderer: Skia GL Pipeline
2020-07-30 21:55:40.612 27619-27619/com.filamentsample I/Filament: FEngine (64 bits) created at 0x7799400000 (threading is enabled)
2020-07-30 21:55:40.612 27619-27651/com..filamentsample D/Filament: Using ASurfaceTexture
2020-07-30 21:55:40.612 27619-27651/com..filamentsample D/Filament: FEngine resolved backend: OpenGL
2020-07-30 21:55:40.612 27619-27651/com..filamentsample I/Adreno: QUALCOMM build                   : 94a5458, I21281c58c8
    Build Date                       : 12/18/18
    OpenGL ES Shader Compiler Version: EV031.25.03.02
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.6.2.R1.09.00.00.463.046
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-07-30 21:55:40.612 27619-27651/ I/Adreno: Build Config                     : S L 6.0.7 AArch64
2020-07-30 21:55:40.616 27619-27651/com..filamentsample I/Adreno: PFP: 0x005ff112, ME: 0x005ff066
2020-07-30 21:55:40.620 27619-27651/com..filamentsample I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2020-07-30 21:55:40.621 27619-27651/com..filamentsample I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-07-30 21:55:40.662 27619-27619/com..filamentsample I/Filament: FEngine (64 bits) created at 0x7797600000 (threading is enabled)
2020-07-30 21:55:40.662 27619-27662/com..filamentsample D/Filament: Using ASurfaceTexture
2020-07-30 21:55:40.662 27619-27662/com..filamentsample D/Filament: FEngine resolved backend: OpenGL
2020-07-30 21:55:40.820 27619-27619/com..filamentsample A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 27619 (.filamentsample), pid 27619 (.filamentsample)

**Comment by chiragchauhan1073** [comment]
Here is the full code which I am trying

companion object {
        // Load the library for the utility layer, which in turn loads gltfio and the Filament core.
        init {
            Utils.init()
            Filament.init()
        }
    }

    private lateinit var surfaceView: SurfaceView
    private lateinit var choreographer: Choreographer
    private val frameScheduler = FrameCallback()
    private lateinit var modelViewer: ModelViewer
    private val doubleTapListener = DoubleTapListener()
    private lateinit var doubleTapDetector: GestureDetector

    private lateinit var material: Material
    private lateinit var materialInstance: MaterialInstance

    private lateinit var engine: Engine

    @SuppressLint("ClickableViewAccessibility")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        surfaceView = SurfaceView(this).apply { setContentView(this) }
        choreographer = Choreographer.getInstance()

        doubleTapDetector = GestureDetector(applicationContext, doubleTapListener)

        modelViewer = ModelViewer(surfaceView)

        surfaceView.setOnTouchListener { _, event ->
            modelViewer.onTouchEvent(event)
            doubleTapDetector.onTouchEvent(event)
            true
        }

        engine = Engine.create()

        buildMaterial()
        setupMaterial()

        createRenderables()
        createIndirectLight()
        

        // enable dynamic resolution
        val options = modelViewer.view.dynamicResolutionOptions
        options.enabled = true
        modelViewer.view.dynamicResolutionOptions = options

        modelViewer.view.ambientOcclusion = View.AmbientOcclusion.SSAO

        val bloom = modelViewer.view.bloomOptions
        bloom.enabled = true
        modelViewer.view.bloomOptions = bloom

        val asset = modelViewer.asset!!
        val rm = modelViewer.engine.renderableManager
        for (entity in asset.entities) {
            val renderable = rm.getInstance(entity)
            if (renderable == 0) {
                continue
            }

            rm.setMaterialInstanceAt(renderable,0,materialInstance)
        }

    }

    private fun createIndirectLight() {
        val engine = modelViewer.engine
        val scene = modelViewer.scene
        val ibl = "venetian_crossroads_2k"
        readCompressedAsset("envs/$ibl/${ibl}_ibl.ktx").let {
            scene.indirectLight = KtxLoader.createIndirectLight(engine, it)
            scene.indirectLight!!.intensity = 30_000.0f
        }
        readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx").let {
            scene.skybox = KtxLoader.createSkybox(engine, it)
        }
    }

    private fun createRenderables() {
        val buffer = assets.open("models/myASSET.gltf").use { input ->
            val bytes = ByteArray(input.available())
            input.read(bytes)
            ByteBuffer.wrap(bytes)
        }

        modelViewer.loadModelGltfAsync(buffer) { uri -> readCompressedAsset("models/$uri") }
        modelViewer.transformToUnitCube()

    }

    private fun buildMaterial() {
        // MaterialBuilder.init() must be called before any MaterialBuilder methods can be used.
        // It only needs to be called once per process.
        // When your app is done building materials, call MaterialBuilder.shutdown() to free
        // internal MaterialBuilder resources.
        MaterialBuilder.init()

        val matPackage = MaterialBuilder()
            // By default, materials are generated only for DESKTOP. Since we're an Android
            // app, we set the platform to MOBILE.
            .platform(MaterialBuilder.Platform.MOBILE)

            // Set the name of the Material for debugging purposes.
            .name("Clear coat")

            // Defaults to LIT. We could change the shading model here if we desired.
            .shading(MaterialBuilder.Shading.LIT)

            // Add a parameter to the material that can be set via the setParameter method once
            // we have a material instance.
            .uniformParameter(MaterialBuilder.UniformType.FLOAT3, "baseColor")

            // Fragment block- see the material readme (docs/Materials.md.html) for the full
            // specification.
            .material(
                "void material(inout MaterialInputs material) {\n" +
                        "    prepareMaterial(material);\n" +
                        "    material.baseColor.rgb = materialParams.baseColor;\n" +
                        "    material.roughness = 0.65;\n" +
                        "    material.metallic = 1.0;\n" +
                        "    material.clearCoat = 1.0;\n" +
                        "}\n"
            )

            // Turn off shader code optimization so this sample is compatible with the "lite"
            // variant of the filamat library.
            .optimization(MaterialBuilder.Optimization.NONE)

            .build()

        if (matPackage.isValid) {
            val buffer = matPackage.buffer
            material = Material.Builder().payload(buffer, buffer.remaining()).build(engine)
        }

        // We're done building materials, so we call shutdown here to free resources. If we wanted
        // to build more materials, we could call MaterialBuilder.init() again (with a slight
        // performance hit).
        MaterialBuilder.shutdown()
    }

    private fun setupMaterial() {
        val rm = modelViewer.engine.renderableManager

        // Create an instance of the material to set different parameters on it
        materialInstance = rm.getMaterialInstanceAt(1,0)
        // Specify that our color is in sRGB so the conversion to linear
        // is done automatically for us. If you already have a linear color
        // you can pass it directly, or use Colors.RgbType.LINEAR
        materialInstance.setParameter("baseColor", Colors.RgbType.SRGB, 255f, 255f, 0.0f)

    }


    private fun readCompressedAsset(assetName: String): ByteBuffer {
        val input = assets.open(assetName)
        val bytes = ByteArray(input.available())
        input.read(bytes)
        return ByteBuffer.wrap(bytes)
    }

    override fun onResume() {
        super.onResume()
        choreographer.postFrameCallback(frameScheduler)
    }

    override fun onPause() {
        super.onPause()
        choreographer.removeFrameCallback(frameScheduler)
    }

    override fun onDestroy() {
        super.onDestroy()
        choreographer.removeFrameCallback(frameScheduler)
    }

    inner class FrameCallback : Choreographer.FrameCallback {
        private val startTime = System.nanoTime()
        override fun doFrame(frameTimeNanos: Long) {
            choreographer.postFrameCallback(this)

            modelViewer.animator?.apply {
                if (animationCount > 0) {
                    val elapsedTimeSeconds = (frameTimeNanos - startTime).toDouble() / 1_000_000_000
                    applyAnimation(0, elapsedTimeSeconds.toFloat())
                }
                updateBoneMatrices()
            }

            modelViewer.render(frameTimeNanos)
        }
    }

    // Just for testing purposes, this releases the model and reloads it.
    inner class DoubleTapListener : GestureDetector.SimpleOnGestureListener() {
        override fun onDoubleTap(e: MotionEvent?): Boolean {
            modelViewer.destroyModel()
            createRenderables()
            return super.onDoubleTap(e)
        }
    }

**Comment by prideout** [comment]
I don't understand this codeline in your `setupMaterial` function:

    materialInstance = rm.getMaterialInstanceAt(1,0)

At first glance, I think it should be:

    materialInstance = material.createMaterialInstance()

**Comment by chiragchauhan1073** [comment]
materialInstance = material.createInstance()
cause the same issue.

**Comment by prideout** [comment]
Note that it is preferable to change parameters on the built-in materials rather than changing the material itself.  The "Getting Started" Medium post describes this near the end of the post, right before "Further Reading".  For example, if you want to change the color of a renderable to red, you can simply do:

`rm.getMaterialInstanceAt(renderable, primIndex).setParameter("baseColorFactor", 1,0,0,1)`

**Comment by chiragchauhan1073** [comment]
Okay this is how my default model looks like

![image](https://user-images.githubusercontent.com/24297327/88955383-77dd5c80-d2b9-11ea-8f3f-96b57e76fc63.png)

Now i tried the above code to change the color of handle part.

below image is the result
![image](https://user-images.githubusercontent.com/24297327/88955091-12896b80-d2b9-11ea-9d9c-022959174ad9.png)

**Comment by chiragchauhan1073** [comment]
i am trying Yellow color with baseColorFactor Property.

**Comment by chiragchauhan1073** [comment]
sample code 

val asset = modelViewer.asset!!
        val rm = modelViewer.engine.renderableManager
        for (entity in asset.entities) {
            val renderable = rm.getInstance(entity)
            if (renderable == 0) {
                continue
            }
            if (asset.getName(entity) == "HANDLE CHROME FINISH") {
                val material = rm.getMaterialInstanceAt(renderable, 0)
                material.setParameter("baseColorFactor", 255f, 255f, 0f)
            }
        }

**Comment by prideout** [comment]
Note that [baseColorFactor](https://github.com/google/filament/blob/main/libs/gltfio/materials/ubershader.mat.in#L18) is a float4 not a float3, although I'm not sure if that's the issue here.

**Comment by romainguy** [comment]
Also note that colors are specified with values between 0 and 1, not between 0 and 255. See our materials documentation: https://google.github.io/filament/Materials.html

**Comment by prideout** [comment]
Oh, and that's a very bright yellow.  I think you want (1,1,0,1) rather than (255,255,0)

**Comment by chiragchauhan1073** [comment]
(1,1,0,1) seems not working for me.

here is the output

![image](https://user-images.githubusercontent.com/24297327/88956294-cc350c00-d2ba-11ea-9957-107ea83ac645.png)

**Comment by prideout** [comment]
Sorry meant (1f, 1f, 0f, 1f).  You also might want to set `metallicFactor` and `roughnessFactor` appropriately.

**Comment by chiragchauhan1073** [comment]
Wow. great catch.
It works, Thank you so much for your instant support.
