### ISSUE TITLE
Gltf model's color looks very different in two viewers

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2893]
I have a glass model exported from Substance Painter and I dragged into two different viewers:
1. Filament's gltf-viewer
2. https://gltf-viewer.donmccurdy.com/

It looks a bit weird in Filament's gltf_viewer. 
Here's the screen-shot:
![image](https://user-images.githubusercontent.com/5915889/88925563-4360a500-d2a7-11ea-91f9-dd10d2e2e775.png)

Here's the model:
[glass.glb.zip](https://github.com/google/filament/files/5001315/glass.glb.zip)

So what cause such a difference between two viewers? (I tried srgb/linear options in the second viewer but it seems not the reason.)
Thanks:)

**Comment by romainguy** [comment]
I'll take a look but the lighting setup is different. Our viewer for instance has a strong directional light turned on by default.

**Comment by romainguy** [comment]
Here is what it looks like with a different IBL:

<img width="1136" alt="Screen Shot 2020-07-30 at 9 00 02 AM" src="https://user-images.githubusercontent.com/869684/88945648-18dd0080-d243-11ea-8860-7970a373e71e.png">

**Comment by vcxyk** [comment]
> Here is what it looks like with a different IBL:
> 
> <img alt="Screen Shot 2020-07-30 at 9 00 02 AM" width="1136" src="https://user-images.githubusercontent.com/869684/88945648-18dd0080-d243-11ea-8860-7970a373e71e.png">

I change the IBL texture to "Venice Sunset", which is the same to the gltf-web-viewer. And we can see the rendering in Filament's viewer has a higher contrast, which makes it less realistic in an AR scene.

![image](https://user-images.githubusercontent.com/5915889/88994651-73499000-d31b-11ea-8d27-87468dcc7bdf.png)

It seems the color encoding of IBL makes such differences?  (Filament uses R11G11B10 while the web viewer use RGB8?)

**Comment by romainguy** [comment]
There's also the exposure, the tone mapping etc. And yes our IBLs are stored in HDR float as R11G11B10F instead of an 8 bit based encoding like RGBM.

**Comment by romainguy** [comment]
You may want to check what tone mapper the online viewer uses. I know many viewers default to Reinhard which produces very flat results.
