### ISSUE TITLE
Filament 1.8.1 doesn't build on Ubuntu 20.04

### ISSUE THREAD

**Issue by bioglaze** [google/filament#2900]
**Describe the bug**
Filament 1.8.1 doesn't build on Ubuntu 20.04.

**To Reproduce**
1. I downloaded filament-1.8.1.tar.gz
2. I ran `./build.sh release`
3. I get this error:

```
CMake Error at CMakeLists.txt:163 (message):
  Detected C compiler GNU is unsupported
```

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 64-bit
 - GPU: AMD Radeon R9 Nano
 - Backend: Vulkan

**Additional context**

* gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)
* clang version 10.0.0-4ubuntu1
* cmake version 3.16.3
 
[CMakeOutput.log](https://github.com/google/filament/files/5006319/CMakeOutput.log)

**Comment by romainguy** [comment]
See BUILDING.md, we require to build with clang.
