### ISSUE TITLE
how to convert Hex color value to Pre-multiplied linear RGB Float4

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#2904]
Hello, is there any way to convert hex to Pre-multiplied linear RGB Float4 ? 

I tried by this way but it is not accurate.

int color = Color.parseColor("#6F00AC");
int red = Color.red(color);
int green = Color.green(color);
int blue = Color.blue(color);
int alpha = Color.alpha(color);

**Comment by romainguy** [comment]
This gives you values between 0 and 255. You have to divide them by 255.0f. Filament's APIs let you pass a color type so you can let it handle premultiplication and conversion to linear space.
