### ISSUE TITLE
"computeTangents" has a high cost during AssetLoading process.

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2905]
Hi, I am working on a demo using Filament which has several high-poly assets in the scene. But the loading time of these assets is a bit longer. After profiling it indicates that the "resourceLoader" for GLB asset have to computeTangents and costs almost half time of the loading process. But I don't use normal map for this asset and it seems I don't need tangents for "TangentSpace NormalMap".    
I tried to comment "computeTangents" out, the results are: some models render properly, but the others renders with triangle chaos error ( incorrect lighting..).
Is there a way to skip "computeTangents" when no normal maps are used?  Thanks~
Version: Filament 1.7.0

**Comment by romainguy** [comment]
Please try 1.8, this step was optimized.
