### ISSUE TITLE
KHR_materials_transmission sample model artifacts

### ISSUE THREAD

**Issue by abwood** [google/filament#2907]
The KHR_materials_transmission support looks amazing, however I think there's a minor artifact visible in the TransmissionTest sample model, most noticeable in the TranmssionTexture w/ Opacity column of spheres.  Looking at the image captured in the release notes for v1.8.1, I see fresnel highlights on the outer edge of the sphere.  This should not be visible.

![image](https://user-images.githubusercontent.com/3868547/89208280-0851c080-d58a-11ea-9292-6eef233ef99b.png)

**Comment by emackey** [comment]
Yes.  Specifically, the test model is using alpha blending here, not transmission, so the material itself shouldn't be present at that location.

**Comment by emackey** [comment]
(Separately, we should probably make a test model that compares a completely transmissive material to a zero-alpha-coverage material, to highlight this difference)

**Comment by romainguy** [comment]
Our loader should be applying the "fade" blend mode to regular glTF materials (both diffuse and specular get the opacity defined in the material) but our "blend" mode to any material with transmission (only diffuse is affected by the opacity). What is KHR_materials_transmission supposed to do? Still use the "fade" model?

@emackey In the glb file I'm using the `BlueTransWithMask` material uses `KHR_materials_transmission`.

**Comment by abwood** [comment]
It looks like those spheres define a baseColorTexture and include an alpha value of 0.0 for those "holes".  The spec defines the transmission tint through this baseColor factor, which would cancel out the f_transmission contribution to your final color.

**Comment by MiiBond** [comment]
> only diffuse is affected by the opacity

In `KHR_materials_transmission`, both diffuse and specular are still affected by alpha opacity. The transmission is controlled only by the "transmissionFactor/Texture". The material should still be completely invisible where alpha is zero.

**Comment by romainguy** [comment]
Thanks for the clarification.

**Comment by romainguy** [comment]
@prideout I still see the specular reflections in the cutout parts of the material.

**Comment by romainguy** [comment]
Git mixup, it's fixed now, thanks @prideout!

<img width="420" alt="Screen Shot 2020-08-03 at 10 53 10 AM" src="https://user-images.githubusercontent.com/869684/89211998-907a9a80-d577-11ea-918b-0d88f124fe02.png">
