### ISSUE TITLE
Possible error in launch-c.ini and launch-cxx.ini

### ISSUE THREAD

**Issue by dmigliore** [google/filament#2922]
I don't know if it is an error, but I had a problem during compilation.
I am using Ubuntu 20.04 and clang version 10.0.0-4ubuntu1 

I received this message continuously:

launch-cxx: 3: [[: not found

And I had error in third-party libraries compilation.

So I modified lunch-c.ini and launch-cxx.ini removing a [] in the if:

if [ "$1" = "${CMAKE_C_COMPILER}" ]; then
    shift
fi

this solved the issue.

Does someone have the same problem?

**Comment by romainguy** [comment]
It's a mistake in the script, it should use /bin/bash at the top instead, or use `[`. `[[` is a bash-ism.

**Comment by romainguy** [comment]
I fixed the scripts, thank you!
