### ISSUE TITLE
Aliasing on 3d view (and off-screen snapshot) 

### ISSUE THREAD

**Issue by Maria098** [google/filament#2932]
Hello

I am looking for a suggestion to reduce aliasing coming from rendering small parts - stitches on cloth.
This is how zoomed-in view looks (correct view):
![ActualAfterZoomIn](https://user-images.githubusercontent.com/67960527/89862031-c3dcab00-dbaf-11ea-9c36-0a35b7fa5353.PNG)

When we zoom out this is what we see (stitches appear jittery) and they are jittery on a snapshot generated from this zoom out view. Even when we zoom in on this snapshot. This is of cource a problem for our customers in the design world.
![SnapshotFull](https://user-images.githubusercontent.com/67960527/89862108-eb337800-dbaf-11ea-8c6d-424a69d0f357.PNG)
![SnapshotCloseup](https://user-images.githubusercontent.com/67960527/89862118-eec6ff00-dbaf-11ea-9bce-f7eb978c33c2.PNG)

Any pointers are appreciated!

**Comment by romainguy** [comment]
@Maria098 Are your stitches a texture or a mesh? If it's a texture make sure you either supply or generate mipmaps. You can also use the other solutions listed next. If your stitches are a mesh you can try to enable MSAA by using `View::setSampleCount()`. A high sample count (`8`) might help. However if these stitches are geometry, rasterization will fail and there isn't much that MSAA will be able to do once you have micro (sub-pixel) triangles.

You could also try supersampling by forcing a resolution greater than your final render target (this can be done by turning on dynamic resolution and using a factor > `1.0` on both axis, but this will work only if your GPU has enough bandwidth; note that dynamic resolution works only on iOS and Android at the moment).

Last but not least you could try the most recent versions of Filament (by checking out our `main` branch and building Filament yourself or by downloading a [snapshot build](https://github.com/google/filament#snapshots). This will give you the ability to turn on TAA (temporal anti-aliasing) which may help fix your issue.

Finally it would be helpful if you could share a 3D model that reproduces the issue so we can better assist you.

**Comment by Maria098** [comment]
Thanks @romainguy Attaching the zipped fbx, without textures.  These stitches are thousands of tiny meshes. We do use View::setSampleCount(8) and filament::View::AntiAliasing::FXAA already.  We are currently working on Windows version and then Mac. Not Android.  We will explore the latest Filament version as you suggested. I think our developer used filament 1.6 on Windows and 1.5 on Mac as later Mac version of filament did not allow off-screen rendering.
Please let me know if you see an improvement with TAA  on our model with the latest version.
Thanks!


[DenimDress.zip](https://github.com/google/filament/files/5056067/DenimDress.zip)

**Comment by romainguy** [comment]
I just tried with TAA and it seems to solve your problem. I would however recommend using textures instead of geometry if that's possible :)

**Comment by Maria098** [comment]
@romainguy Thanks a lot!

**Comment by Maria098** [comment]
@romainguy How to turn TAA on in the latest Filament?

**Comment by romainguy** [comment]
Use `View::setTemporalAntiAliasingOptions()`. Note that it's not in 1.8.1 you'll have to build Filament yourself or wait for the next version.

**Comment by Maria098** [comment]
@romainguy Thank you for your help! However neither of the above gives us a satisfactory result. We downloaded the latest git snapshot and tried various options of Temporal Anti Aliasing but our stitches are still partially missing.  Our users are textile professionals and need to have all details of their design on a high res snapshot.

![Filament](https://user-images.githubusercontent.com/67960527/90360778-40b2cd80-e065-11ea-9fdf-6ff5e5027b6e.PNG)

We need something like that (this is what we get in another application that uses old version of Scenix from Nvidia):
![HQR](https://user-images.githubusercontent.com/67960527/90360804-4ad4cc00-e065-11ea-84bf-803d469fa9f9.PNG)

Do you have any other suggestion how to make Filament sample with a small step at depth so that all these details will stay visible?  Thank you!

**Comment by romainguy** [comment]
Looks like you are now running into z fighting issues. Use a higher precision depth buffer might help. I'll tell you what to change to test that yourself tomorrow (it's 11pm here).

**Comment by romainguy** [comment]
Actually I'm not sure where to make the change. @pixelflinger what would be an easy way to test `DEPTH32F` for the default render target?

**Comment by romainguy** [comment]
@Maria098 Could you also tell us what near/far values you are using for your camera?

**Comment by Maria098** [comment]
@romainguy We actually were able to solve the problem by adjusting near and far values of the camera from 0.1-10 to 3-20. Thank you for your help!

**Comment by romainguy** [comment]
Glad to hear!

**Comment by pixelflinger** [comment]
Let me add one more detail here -- In filament, the z-precision depends only on the near value of the camera (so, don't worry too much about the far).  It is very important, as you saw, to set the largest near you can.

Also remember that filament prefers that all these units be meters -- I suspect this is not the case in your application, maybe your world units are cm or inches (can you confirm?).  Generally, filament will work fine with non-meter world units, but we still have some effects that might break, such as SSAO. Also remember that all our default values for various options are assuming meters where applicable.
