### ISSUE TITLE
Need help to build the libraries.

### ISSUE THREAD

**Issue by Pankaj003** [google/filament#2934]
Hi,
I am building the libs locally on Windows machine and able to successfully build the TNT solution. I've some questions where I need your help:
1. By default "Runtime library" flag is set to "Multi-threaded(/MT)" switch but I want to build the libs with switch MD. I saw that in the filament release folder binaries are shared as per the runtime flags, do you have different project configurations for different runtime library flags or build it using some visual studio or other script? could you please share the info how to set the flag for complete solution. Can we do it from CMake utility or we have to manually change the project configuration for the individual project in the solution?
2. After building the project I am not sure which all header files and library to use. Do you have any script or batch file which can collect the required header files and libraries?

Thanks,
Pankaj

**Comment by bejado** [comment]
The runtime library flags are set via the `USE_STATIC_CRT` CMake option. To build the MD variant, use `-DUSE_STATIC_CRT=OFF`.

There's an `install` target you can use to build and collect distribution files.

It should be visible in the TNT solution:

![image](https://user-images.githubusercontent.com/5298046/89938448-5dfe1c80-dbcb-11ea-81e1-6d25c2c73bbf.png)

Alternatively, you can invoke it directly through CMake:

```
cmake --build . --target install --config Release -- /m
```

Afterwards, Filament will be installed to `.\install` (configurable with `CMAKE_INSTALL_PREFIX`).

**Comment by Pankaj003** [comment]
Thanks @bejado , it solves the building and copying issue.
