### ISSUE TITLE
Sample crash

### ISSUE THREAD

**Issue by mayi203** [google/filament#2942]
**Describe the bug**
E/Filament: Panic
    in static filament::MaterialParser *filament::FMaterial::createParser(backend::Backend, const void *, size_t):508
    reason: Material version mismatch. Expected 7 but received 0.

sample-hello-triangle

Android

**Comment by romainguy** [comment]
It looks like you didn't build the sample successfully. Can you try a clean build? Make sure to delete the assets directory first.

**Comment by mayi203** [comment]
> It looks like you didn't build the sample successfully. Can you try a clean build? Make sure to delete the assets directory first.

I use it this way : implementation 'com.google.android.filament:filament-android:1.8.1'

**Comment by romainguy** [comment]
How did you compile your materials? You need to compile them with the matc tool first.

**Comment by mayi203** [comment]
> How did you compile your materials? You need to compile them with the matc tool first.

That's the question! Thank you !
