### ISSUE TITLE
How to increase resolution of model. 

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#2949]
I am using sample-gltf-viewer, everything seems working well. but when module loads initially it looks little bit blury, is there any way to improve the resolution of the model ? i wants as much as possible a higher resolution. 
here is the screenshot of module.

this is how it looks initially.
![image](https://user-images.githubusercontent.com/24297327/90135116-cf86c800-dd8f-11ea-9a10-2baf355afd46.png)

this is my expected resolution.
![image](https://user-images.githubusercontent.com/24297327/90135303-1bd20800-dd90-11ea-9d36-16a7a1c7ba8e.png)

**Comment by prideout** [comment]
This might be due to `dynamicResolutionOptions.enabled`.  Search for this in MainActivity and try changing it to false.

**Comment by romainguy** [comment]
Well it's hard to tell because the second screenshot is just closer to the model. You could try to disable dynamic resolution and move the camera closer.
