### ISSUE TITLE
How to achieve off-screen rendering wiht framebuffer on Android?

### ISSUE THREAD

**Issue by mayi203** [google/filament#2955]
Android.

**Comment by prideout** [comment]
See our RenderTarget API, it is not Android specific:
https://github.com/google/filament/blob/main/filament/include/filament/RenderTarget.h

Here's an example:
https://github.com/google/filament/blob/e8a7d9f0c29b26dd028306d27e4e6d44dd25b1fa/samples/lucy_bloom.cpp

**Comment by prideout** [comment]
If you're interested in rendering into a surface from outside of filament, you can see our camera and stream samples in /android/samples/.

**Comment by mayi203** [comment]
I looked at this part of the code, but how do I get final texture ID, which I need to render and codec

**Comment by mayi203** [comment]
My Programe like this: [https://ftp.bmp.ovh/imgs/2020/08/a649af4131bdd782.jpg](url)

**Comment by mayi203** [comment]
My program like this:  ![avatar](https://ftp.bmp.ovh/imgs/2020/08/a649af4131bdd782.jpg)
