### ISSUE TITLE
How to achieve off-screen rendering wiht framebuffer on Android?

### ISSUE THREAD

**Issue by mayi203** [google/filament#2962]
My program like this:  ![avatar](https://ftp.bmp.ovh/imgs/2020/08/a649af4131bdd782.jpg)

_Originally posted by @mayi203 in https://github.com/google/filament/issues/2955#issuecomment-674336713_

**Comment by mayi203** [comment]
I looked at the RenderTarget code, but how do I get final texture ID, which I need to render and codec

**Comment by prideout** [comment]
MediaCodec is similar to CameraDevice in that they both accept a Surface to render into, which you can get from ImageReader.  We have an example of CameraDevice usage in `android/samples/sample-hello-camera`.  You can also look at `sample-stream-test`, which demonstrates all the different ways in which Filament Streams can work on Android.

**Comment by mayi203** [comment]
The MediaCodec section is a third_party rtc library that accepts texture ID only...  I think texture ID is a very important property, so why don't wejust get it.  Many third_party library  accepts texture ID only

**Comment by romainguy** [comment]
That's because Filament has several backends and a texture id wouldn't work with all those backends. We also plan on removing OpenGL support at some point, which would break such APIs.

**Comment by romainguy** [comment]
And indeed on Android the proper way to do this is via a Surface or HardwareBuffer.
