### ISSUE TITLE
webgl examples not working on macos/safari

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2963]
http://localhost:8080/parquet.html

[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'ctx.getExtension')
	(anonymous function) (filament.js:196)
	App (parquet.html:42)
	(anonymous function) (parquet.html:36)
	taskFinished (filament.js:65)
	(anonymous function) (filament.js:126)
	promiseReactionJob

commit 1c726fcef6c9838a9ee17eb358d34368bf8d6c9b (origin/master, origin/HEAD, github/main, master, github_master)
Author: Philip Rideout <philiprideout@gmail.com>
Date:   Fri Aug 14 12:04:02 2020 -0700

Safari Version 13.1.2 (15609.3.5.1.3)
Macos Version 10.15.6 (19G2021)

**Comment by romainguy** [comment]
That's because Filament requires WebGL2 which is not enabled in Safari yet (it should be in the new macos). Please use Firefox or a chromium based browser in the meantime.

**Comment by unicomp21** [comment]
@romainguy does chrome on ios support webgl2?  On mac, it appears to work.

**Comment by romainguy** [comment]
Apple forbids to use a different engine than Safari’s on iOS. So Chrome uses WebKit there.
