### ISSUE TITLE
support for clang/llvm co_await

### ISSUE THREAD

**Issue by unicomp21** [google/filament#2964]
https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/impl/use_future.hpp

port the above into filament so we can have coroutine/co_await support

**Comment by romainguy** [comment]
Coroutines are part of C++20 and Filament is only on C++17. And as we discussed before it's not clear why you want coroutines? Some Filament APIs could benefit (callbacks based APIs) but it's not something we want to impose on  our users.

**Comment by unicomp21** [comment]
@romainguy think about "on the fly" procedural generation of geometry, etc.  Being able to have something "thread-like", for handling jobs, which could be multiplexed on the main browser thread would be "huge".  This stuff is really really powerful in terms of simplifying things.  Callback hell is a very real problem as complexity increases.

**Comment by unicomp21** [comment]
@romainguy I think it's worth putting on the backlog for when c++20 hits.

**Comment by romainguy** [comment]
I know what coroutines are for but I don't see why Filament needs to be involved. Our implementation is currently multithreaded which is of course limited in the current implementations of WASM, but it's all internal so we can change this eventually when WebAssembly threads are widely supported.

**Comment by unicomp21** [comment]
@romainguy what's the main "goto" for coroutines among devs currently using filament?  Is it lua?  Maybe something else?

**Comment by unicomp21** [comment]
@romainguy Unity is hugely successful, part of that is due to C# and async/await.
