### ISSUE TITLE
zoom out flickering

### ISSUE THREAD

**Issue by orenmiron** [google/filament#2965]
Hello
I am looking for a solution for a zoom out flickering
my model is a blue cover shirt above a red undershirt, there are no intersections
but the distance between the layers is small.
pls watch the attached video
i get the same results in opaque and transparent blending.
**depthCulling** is set to true
any idea for the cause of the flickering?
[flick.zip](https://github.com/google/filament/files/5081128/flick.zip)
- OS Microsoft Windows 10
 - GPU: GeForce GTX 980/PCie/SSE2

**Comment by romainguy** [comment]
It looks like z-fighting. You should try to leave a bigger gap between the two models. Alternatively you can try `MaterialInstance::setPolygonOffset()` to fix this.
