### ISSUE TITLE
Example sample-stream-test not working on Android 5.1 Mali device

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2978]
Example sample-stream-test works fine on my Adreno Android 7.0 device, but fails on a Mali-based (RockChip) Android 5.1 device. I'm compiling from a recent (6 Aug) version of the main branch.

This is the output on the Mali device:

![stream-fail1](https://user-images.githubusercontent.com/303516/90793335-868cc180-e303-11ea-90f2-3d3c90397deb.png)

I'm actually trying to solve [this problem](https://github.com/google/filament/issues/1448), but I expect they are related and this one is easier to reproduce.

I'm happy to provide logcat (nothing obvious there at the moment) and I'm compiling from source so I can add any instrumentation that might be useful. I'm just not sure where to start.

**Comment by romainguy** [comment]
All these issues very much look like platform/driver bugs unfortunately. And we don't have devices to reproduce them :/

**Comment by romainguy** [comment]
Related bugs: #2831 #1448

**Comment by rawnsley** [comment]
I feared as much. I have camera and video texture binding working OK in an OpenGL application on this device so I'll try and narrow down the difference.

**Comment by rawnsley** [comment]
External texture streams fail when the TextureSampler uses _TextureSampler.WrapMode.REPEAT_. If you change to _TextureSampler.WrapMode.CLAMP_TO_EDGE_ then it works fine on the Mali device I had problems with originally. It also fixes video streams.

[The spec](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_EGL_image_external.txt) says it's always an error to use anything except CLAMP_TO_EDGE so I suppose the other devices are just failing more gracefully.

**Comment by romainguy** [comment]
Yes it is indeed one of the limitations of external textures :( We could enforce `CLAMP_TO_EDGE` on external texture streams I suppose.

@pixelflinger do you agree?

**Comment by bejado** [comment]
I'm fine with enforcing `CLAMP_TO_EDGE` for iOS external textures, but ideally we'd put this check into the platform/backend because AFAIK iOS doesn't require any particular wrap mode.

**Comment by pixelflinger** [comment]
What's completely stupid about this limitation is that `REPEAT` can be emulated in the shader by just doing a `fract(uv)`.
