### ISSUE TITLE
How to rotate/translate  multiple objects/entities as a group.

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#2993]
Hi guys,

I understand you can use transform manager to rotate/translate renderable/entity. But how do I rotate multiple entities as a group? Is there a way to combine multiple entities into one so I can rotate/translate them together? 

Another question is any tips on how to go about simulating entity/renderable selection based on mouse click? I know I will have to capture mouse events from imgui but not sure how to go about detecting mouse clicked on filament entity/renderable.

Is it possible to turn off ambient occlusion per object ? Let's say I want ambient occlusion to be applied for entire scene but turn off for a sphere object.

Thanks

**Comment by romainguy** [comment]
You can simply create an entity with a transform and parent all your other entities to that root (using the transform's manager `setParent()` method). Then by transforming the root entity you'll transform the entire group.
