### ISSUE TITLE
gl_PointCoord is not supported? 

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#2994]
gl_PointSize is support but gl_PointCoord is not.  
Is there a document explaining which APIs in GLSL can support

**Comment by prideout** [comment]
We support all functions that GLSL supports because we use GLSL.  Our point sprite sample uses `gl_PointCoord` to form UV coordinates:

https://github.com/google/filament/blob/main/samples/materials/pointSprites.mat#L26
