### ISSUE TITLE
IBL shows different effect when imported from ktx and png

### ISSUE THREAD

**Issue by DianxinWang** [google/filament#2996]
**Describe the bug**
We were using png for generate IBL indirectlight. We followed `samples/app/IBL.cpp`  `rgb32f` and write a script for png format.
But the result are different. 
This is from ktx.
![image](https://user-images.githubusercontent.com/36990568/91043359-05f0fc80-e646-11ea-9a2e-4202f8fc21ac.png)

This is from png
![image](https://user-images.githubusercontent.com/36990568/91043412-1ef9ad80-e646-11ea-8b40-ffff3a81e8a9.png)

it seem the 

**To Reproduce**
[machine_shop_01_1k.zip](https://github.com/google/filament/files/5117671/machine_shop_01_1k.zip)
we were using command `cmgen -f ktx -x machine_shop machine_shop_01_1k.hdr` for ktx
`cmgen -f png -x machine_shop machine_shop_01_1k.hdr` for png

**Expected behavior**
the object should be rendered similar both in png IBL and ktx IBL.

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: GTX 2070

**Additional context**
The only difference I can find is that ktx store data with the format of rgb32f(R10G11B11), while PNG is of sRGB8. The data precision might differ but I don't expect that influence that much.

**Comment by romainguy** [comment]
The difference is large. sRGB8 cannot encode HDR data. The difference is not surprising. KTX files simply store rgb32f as PNG files. Use the rgb32f export format to generate HDR PNGs.
