### ISSUE TITLE
setSampleCount produces black view on some android devices

### ISSUE THREAD

**Issue by kpeeters** [google/filament#3000]
Using view->setSampleCount with anything but 1 as argument produces a black screen on some android devices; so far confirmed on Samsung Tab S6 lite, which has a Mali-G72 MP3 GPU. If this is dependent on hardware capabilities, is there some way to query filament whether this is going to work or not?

**Comment by romainguy** [comment]
MSAA should work everywhere, it seems like you are running into driver bugs :/

**Comment by romainguy** [comment]
What post-processing effects do you use btw? Some of them change how we need to handle MSAA.

**Comment by kpeeters** [comment]
Color grading and ambient occlusion. I am pretty sure turning those off makes no difference to the MSAA failing, but I'll double check.

**Comment by romainguy** [comment]
Those two shouldn't affect MSAA.

**Comment by kpeeters** [comment]
We see the same issue on Samsung Tab A, which has a Mali-G71 MP2 GPU. So it may well be a Mali driver issue across models. 

If we want to blacklist by hand, what's the best way to do this (does Filament provide any hooks for this)?

**Comment by kpeeters** [comment]
This one is perhaps related: https://github.com/godotengine/godot/issues/33172 & https://github.com/godotengine/godot/pull/33181, but I haven't looked yet at how you handle framebuffer allocation for MSAA.

**Comment by kpeeters** [comment]
Also happens on Samsung Galaxy S9 with Mali-G72 MP18. If there's anything I can do to help debug this, please let me know.

**Comment by geroge-d** [comment]
Also happen On Huawei Pro30 with Mali gpu

**Comment by kpeeters** [comment]
@romainguy This seems to remain problematic on all Mali GPU's I can get my hands on. Can you perhaps disable MSAA on Mali (I see there are already some blacklist entries in the `OpenGLContext::OpenGLContext()` constructor), or if that goes too far for your taste, add a method to be able to query a GPU identification string from the `Filament::Renderer` (GL_RENDERER on OpenGL or the equivalent on other backends), so that I can easily turn off MSAA for Mali GPUs myself?

**Comment by pixelflinger** [comment]
We have fixed issues related to msaa on arm GPUs recently. It might be worth giving it another shot.

**Comment by kpeeters** [comment]
@pixelflinger Finally had a chance to test this: yes, those fixes resolve the problems I had on Mali G72 MP3. Thanks!

**Comment by Alan-FGR** [comment]
I'm having something that I think might be related to this - I'm trying to render with no MSAA at all, but that yields a fully black render, whereas even with 2x MSAA it renders correctly. Could this be a driver bug? I'm currently on an integrated Intel Iris.
