### ISSUE TITLE
BeginFrame() js binding not functional

### ISSUE THREAD

**Issue by DylanYasen** [google/filament#3002]
**Describe the bug**
Cannot call Renderer.beginFrame due to unbound types: 0x1bc646, 0x1bc647, 0x1bc648

**To Reproduce**
```
if (renderer.beginFrame(swapChain)) {
    renderer.render(view);
    renderer.endFrame();
}
```

**Comment by DylanYasen** [comment]
```
    bool beginFrame(SwapChain* swapChain,
            uint64_t vsyncSteadyClockTimeNano = 0u,
            backend::FrameFinishedCallback callback = nullptr, void* user = nullptr);
```

**Comment by romainguy** [comment]
That seems strange since all of our samples use this API. @prideout any idea?

**Comment by DylanYasen** [comment]
most samples I could find are using the simplified call 
```
this.renderer.render(this.swapChain, this.view);
```

I needed to take a screenshot before the frame ends. maybe I could take in only the swapchain from js and pass 0s through for other params in the binding locally for now

**Comment by prideout** [comment]
Thank.  This regressed when we added a callback argument to our C++ beginFrame, we didn't notice because all our samples use the single-view helper method.
