### ISSUE TITLE
shadow map prefiltering for VSM

### ISSUE THREAD

**Issue by DylanYasen** [google/filament#3006]
Very excited about the incoming VSM changes. thanks for adding it!!

I believe shadow maps prefiltering work with VSM but not PCF.  Can we have some support for that so we can apply a blur directly on the shadow map for really soft shadow?

or any pointers for where is the best place to add a temp workaround would be much appreciated. looks like shadow map render pass is currently outside of frame graph, wanted to minimize engine change to avoid future merge headaches.

thanks again

**Comment by romainguy** [comment]
The whole point of adding VSM is to do prefiltering. We're working on this.
