### ISSUE TITLE
customize the blending function of the material

### ISSUE THREAD

**Issue by buaacyfisok** [google/filament#3009]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I get a problem that when I render an object with MASK material type. The MASKED TYPE is bounding with a fixed  blend function; In my version the code is:
`case BlendingMode::MASKED:
            mRasterState.blendFunctionSrcRGB   = BlendFunction::ONE;
            mRasterState.blendFunctionSrcAlpha = BlendFunction::ONE;
            mRasterState.blendFunctionDstRGB   = BlendFunction::ZERO;
            mRasterState.blendFunctionDstAlpha = BlendFunction::ZERO;
            mRasterState.depthWrite = true;
            break;`
But there is a question that the dstAlpha has been changed to zero. It may cause some rendering bugs in my app.
I solve it by changing the code into:
` mRasterState.blendFunctionDstAlpha = BlendFunction::ONE_MINUS_SRC_ALPHA;` 
this change works for me.
But I just want to change this object, not all MASKED objects.
I want to figure out that why a MASKED material has to be related those fixed blending function configuration? Why a MASKED material can not bind with other blending functions?

**Describe the solution you'd like**

I want to customize the blending function of one material. Even it is a MASKED MATERIAL, but I still want to change the blending  function to what I expected. 
I hope there is a interface in the class MaterialInstance. such as:
`setBlendFunction(srcColor, srcAlpha, dstColor, dstAlpha)`
if the developers don‘t use this interface, a MASKED material can use the default MASKED blending function. But if the developers use this interface, the material can use the customized blending function.

THX~

**Comment by romainguy** [comment]
This was a bug we recently fixed. Dst alpha is now preserved.

**Comment by buaacyfisok** [comment]
> This was a bug we recently fixed. Dst alpha is now preserved.

Thx for replay.
I know that the MASKED blending function has changed. the link is https://github.com/google/filament/pull/2896/commits/b828ae0c9739702868d175db40e71a74bf50945e.
But these changes still can not solve my problem.
only this type of blending function can solve it.
`  mRasterState.blendFunctionSrcRGB   = BlendFunction::ONE;
    mRasterState.blendFunctionSrcAlpha = BlendFunction::ONE;
    mRasterState.blendFunctionDstRGB   = BlendFunction::ZERO;
    mRasterState.blendFunctionDstAlpha = BlendFunction::ONE_MINUS_SRC_ALPHA;
    mRasterState.depthWrite = true;`
