### ISSUE TITLE
Entities in the scene

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#3010]
How do you get a list of all the entities in the scene ? I don't see a way to get this from Scene, EntityManager or RenderableManager? Is this feature provided by filament or is it the clients responsibility to keep track of all the entities in the scene ?

I need to get the AABB for all the objects in the scene so I can do ray / AABB intersection.

**Comment by romainguy** [comment]
This is not something provided by the APIs. What you'd actually want is the list of renderables.

**Comment by romainguy** [comment]
@pixelflinger wdyt?

**Comment by pixelflinger** [comment]
We could add such an API, the only hurdle is that internally we don't keep them as an array -- so the API would have to copy the entries into a user-provided buffer. I need to think about it a bit more.

**Comment by prideout** [comment]
If the API takes a filter argument bitmask (e.g. "I only want renderables") then a copy would already be required.
