### ISSUE TITLE
Dynamic change image resource to glTF files

### ISSUE THREAD

**Issue by YC-Chang** [google/filament#3011]
Thanks this awesome project. 
I am new to 3D model rendering with glTF file in Android app, and  I just have a question but not sure if it is suitable to ask questions here, so If it is not suitable, you can remove my issue immediately.

My question is:  **Is there a way to dynamic change baseColorTexture or normalTexture resource images?**

Below is my testing model
![glTF](https://user-images.githubusercontent.com/26915050/91419237-c44e9480-e885-11ea-85e4-0a46821f6d5d.png)

The skin resource (baseColorTexture) image is like:
![ch_boy_body_lambert2SG_BaseColor 1001](https://user-images.githubusercontent.com/26915050/91418420-b2202680-e884-11ea-809f-6b2419b49aa1.png)

and I want to change baseColorTexture to this image on runtime:
![ch_boy_body_lambert2SG_BaseColor 1001_A](https://user-images.githubusercontent.com/26915050/91418461-c19f6f80-e884-11ea-8dfd-6f6eccfba692.png)

My question is similar with #2891 , but he only change baseColorFactor on runtime but I want to change png resource files

I find this API in MaterialInstance, but I can’t find how to use this for glTF files. I only find some sample for .mat file. 

> public void setParameter(@NonNull String name,
>         @NonNull Texture texture, @NonNull TextureSampler sampler)

Can you give me some example or hint for this?  Thanks a lot.

**Comment by romainguy** [comment]
You can change those values at runtime indeed. The [source material](https://github.com/google/filament/blob/main/libs/gltfio/materials/ubershader.mat.in) will show you all the names to use.
