### ISSUE TITLE
ANDROID: How to eliminate lag and improve FPS.

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#3012]
I am referencing sample gltf viewer demo to load my model. everything is working fine except lagging. once model loads, the screen starts lagging so much. is there any way to tackle this issue?
My model size is around 150 MB.

**Comment by romainguy** [comment]
The size of the glTF doesn't matter much, what matters is going to be:
- How many triangles
- How many materials
- How large the textures
- etc.

You can optimize your glTF by trying to reduce all those values. A good rule of thumb would be to use ~40,000 triangles and textures that are 1024x1024 each.

You can also:
- Make sure the app doesn't render at native resolution (1080p or 720p is good enough on many devices)
- Enable dynamic resolution
- Turn off expensive features like bloom or SSAO

**Comment by paulorrfilho** [comment]
@romainguy you suggested changing the render resolution in a couple of threads. Do you mean setting it via  `this.surfaceView.holder.setFixedSize(760, 360)` ?

**Comment by paulorrfilho** [comment]
Answering the initial question, removing unnecessary lights from the scene will improve performance drastically. My app was lagging bad and removing a light from the scene basically fixed the issue for me.
