### ISSUE TITLE
gltfio::animator reverse direction and status of animator notifications

### ISSUE THREAD

**Issue by vortice3D** [google/filament#3013]
Hi:

In order to use gltfio animations in non-trivial projects is necessary, at least, being notified when the playing-status change (onStart and onEndReached as a minimum).

Also, it would be very nice to be able to play the animations backwards.

Best regards.

_P.S. Maybe all these functionalities are already implemented, but I haven't been able to find any documentation on it._

**Comment by prideout** [comment]
The Animator API is not stateful.  There is no notion of play/pause/rewind.  Clients pass the current time to `applyAnimation` and ask for duration via `getAnimationDuration`.

Note that callbacks are tricky due to our language bindings (C++, Java, JS).

**Comment by vortice3D** [comment]
Hi @prideout:

First I want to thank you for your time.

If I don't misunderstand you comment, the proposed mechanism is as rudimentary as:
1) launch the animation from an arbitrary point (applyAnimation)
2) launch a timer
3) compare the elapsed timer's time with the duration of the animation (getAnimationDuration)

This said, regarding that is a not very evolved way, can you please recommend me an alternative in order to achieve a "more suitable" animation control? Maybe using 3rd party solutions?

Best regards.

**Comment by prideout** [comment]
gltfio is a thin bridge between glTF and Filament.  Currently, the only purpose of `gltfio::Animator` is to make it easier to update a set of matrices according to glTF `animation` and `skin` definitions.

We can consider broadening the scope of `gltfio::Animator` by adding a stateful animation system.  However, since callbacks or events would be involved, it might be easier to implement it in a platform-specific utility layer such as `ModelViewer.kt`.

As an aside, note that glTF files do not contain high-level information about animations, such as whether they are meant to be looped, or played concurrently with other animations, or daisy-chained.

**Comment by SGTjeong** [comment]
@vortice3D 

Compare **prevAnimLoc** and **currentAnimLoc**, then you will be able to know when the animation ends.
Below is how I control animation. I don't think it's a clean way to do it, but I couldn't find a better way. 

```
    fun doAnimation(){
        currentAnimation?.let{ animation ->
            if(!isPaused){
                time = System.nanoTime()
                prevAnimLoc = currentAnimLoc
                currentAnimLoc = ((time - animStartTime) / TimeUnit.SECONDS.toNanos(1).toDouble()).toFloat() % (animation.animationDuration / animSpeed)
                if(currentAnimLoc < prevAnimLoc){
                    listener?.onEnd(animation)
                    if(!isLooping){
                        isPaused = true
                    }
                } else {
                    filamentAnimator.applyAnimation(animation.animationIndex, currentAnimLoc * animSpeed)
                    filamentAnimator.updateBoneMatrices()
                }
            }
        }
    }
```

For the reverse animation you could do like below. I haven't tested the code, but it would work

```

      filamentAnimator.applyAnimation(animation.animationIndex, animation.animationDuration - currentAnimLoc)
      filamentAnimator.updateBoneMatrices()

```

**Comment by vortice3D** [comment]
Hi @SGTjeong:

First I'd like to apologize for not thank you earlier, for your time and interest, but I've been very busy this last weeks.

--------------------

As stated, with a loop-as-default (weird that this is not avoidable) behavior and without an end-of-animation-reached event, the oldie "timer-approach" is the only left for us.

I'm implementing it in my Activity in a way similarly that yours, in my case for a multi-animation renderable:

```
float _previousAnimationTime=0.0f;
....
arFragment
    .getArSceneView()
    .getScene()
    .addOnUpdateListener(
        frameTime -> {
            for (AnimationInstance myAnimator : animators) {
                int indexAnimation;
                if(_isPlayingDoors){
                    indexAnimation=0;
                }
                else if(_isPlayingExplode){
                    indexAnimation=1;
                }
                else if(_isPlayingFan){
                    indexAnimation=2;
                 }
                 else{
                     break;
                 }

                 Long time = System.nanoTime();
                 float currentAnimationTime =  (float) ((time - myAnimator.startTime) / (double) SECONDS.toNanos(1))% myAnimator.duration;
                 if(_previousAnimationTime<currentAnimationTime){
                     _previousAnimationTime=currentAnimationTime;
                     myAnimator.animator.applyAnimation(indexAnimation, currentAnimationTime);
                     myAnimator.animator.updateBoneMatrices();
                }
                else{
                    switch(indexAnimation){
                        case 0:
                            _isPlayingDoors=false;
                            break;

                        case 1:
                            _isPlayingExplode=false;
                            break;

                        case 2:
                            _isPlayingFan=false;
                    }
              }
        }
});
```

In fact, this works because we are in a range of low frame rates (30-60fps), so even if we pass the end of animation in terms of time, soon a new update will come to check and will fix it. As an example, for a 3.96'' animation:

**Current time**
...
3.8527026
3.884522
3.9178448
3.950593
**0.02167797**  <--- Time passed from end of animation until stopped

------------------
About the reverse play, what to say!, It's a pity that the **applyAnimation** method does not incorporate it.

Best regards.

**Comment by prideout** [comment]
Closing in favor of https://github.com/google/filament/issues/3121.
