### ISSUE TITLE
Piecewise copy of matrix results in unexpected output

### ISSUE THREAD

**Issue by roxlu** [google/filament#3027]
This issue is either caused because I've been looking at the wrong thing or I must be doing something wrong at a different level. While trying to fix an issue I had with billboarding I stripped away my code piece by piece down to the following code. Somehow I get different results when I use `material.worldPosition = mat * getPosition();`  and `material.worldPosition = rot * getPosition();`

```glsl
material {
 name : color,
    shadingModel : lit,
    blending: opaque,
    doubleSided: true,
    vertexDomain: object,
    parameters : [
      { type: float3, name: albedo },
      { type: float, name: roughness },
      { type: float, name: metallic },
      { type: float, name: alpha }
    ],
    }

fragment {
  void material(inout MaterialInputs material) {
    prepareMaterial(material);
    material.baseColor.rgb = vec3(1, 1, 1);
    material.baseColor.a = 1.0;
  }
}

vertex {
  
  void materialVertex(inout MaterialVertexInputs material) {

    mat4 mat = getWorldFromModelMatrix();
    mat4 rot;
        
    rot[0][0] = mat[0][0];
    rot[0][1] = mat[0][1];
    rot[0][2] = mat[0][2];
    rot[0][3] = mat[0][3];
        
    rot[1][0] = mat[1][0];
    rot[1][1] = mat[1][1];
    rot[1][2] = mat[1][2];
    rot[1][3] = mat[1][3];
        
    rot[2][0] = mat[2][0];
    rot[2][1] = mat[2][1];
    rot[2][2] = mat[2][2];
    rot[2][3] = mat[2][3];

    rot[3][0] = mat[3][0];
    rot[3][1] = mat[3][1];
    rot[3][2] = mat[3][2];
    rot[3][3] = mat[3][3];

    //material.worldPosition = mat * getPosition();
    material.worldPosition = rot * getPosition();
  }
}
```

When I use `material.worldPosition = mat * getPosition()` I get 
![image](https://user-images.githubusercontent.com/358809/91718142-1c8ddb00-eb93-11ea-9086-5c15adaa51d5.png)

And when I use `material.worldPosition = rot * getPosition()` I get
![image](https://user-images.githubusercontent.com/358809/91718194-362f2280-eb93-11ea-8f45-d0e3d2dbcd5d.png)

My system:
```
$ lspci -k | grep -A 2 -E "(VGA|3D)"
01:00.0 VGA compatible controller: NVIDIA Corporation TU104 [GeForce RTX 2080 SUPER] (rev a1)
	Subsystem: Gigabyte Technology Co., Ltd Device 3fe9
	Kernel driver in use: nvidia

$ uname -a
Linux arch2080 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux

# from /var/log/Xorg.0.log
[    12.853] (II) Module nvidia: vendor="NVIDIA Corporation"
[    12.854] (II) NVIDIA dlloader X Driver  450.66  Wed Aug 12 19:44:12 UTC 2020
[    12.854] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[    12.862] (**) NVIDIA(0): Depth 24, (--) framebuffer bpp 32
[    12.862] (==) NVIDIA(0): RGB weight 888
[    12.862] (==) NVIDIA(0): Default visual is TrueColor
[    12.862] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[    12.862] (II) Applying OutputClass "nvidia" options to /dev/dri/card0
[    12.862] (**) NVIDIA(0): Option "AllowEmptyInitialConfiguration"
[    12.862] (**) NVIDIA(0): Option "HardDPMS" "false"
[    12.862] (**) NVIDIA(0): Enabling 2D acceleration
[    12.862] (II) Loading sub module "glxserver_nvidia"
[    12.862] (II) LoadModule: "glxserver_nvidia"
[    12.863] (II) Loading /usr/lib/nvidia/xorg/libglxserver_nvidia.so
[    12.924] (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
[    12.925] (II) NVIDIA GLX Module  450.66  Wed Aug 12 19:41:37 UTC 2020
[    12.927] (II) NVIDIA: The X server supports PRIME Render Offload.
```

**Comment by bejado** [comment]
Can you try declaring `rot` as `highp mat4 rot;`? Though I wouldn't expect precision to have that large of an effect.

Are you compiling the material with optimizations? Try turning optimizations off (matc: `-g` flag) and see if that makes a difference.

**Comment by romainguy** [comment]
`highp` is the default in vertex shaders, it shouldn't be necessary (and `mediump` might not even turn into fp16 computations on desktop GPUs anyway).

**Comment by roxlu** [comment]
> Are you compiling the material with optimizations? Try turning optimizations off (matc: `-g` flag) and see if that makes a difference.

When I disable optimizations it works as expected.

**Comment by bejado** [comment]
Interesting, perhaps it's a glslang / spirv-cross bug.

**Comment by romainguy** [comment]
Sounds like it. Does `rot = mat` work?

**Comment by roxlu** [comment]
> Sounds like it. Does `rot = mat` work?

Yep that works.

**Comment by pixelflinger** [comment]
I investigated a bit, and clearly this code gets optimized very very wrongly -- either spirv-cross or spirv-opt ends-up generating a full matrix assignment per assignment, e.g.:
```
mat4 _428;
void main()
{
    mat4 _381 = _428;
    _381[0].x = _105._m0[0].x;
    mat4 _384 = _381;
    _384[0].y = _105._m0[0].y;
    mat4 _387 = _384;
    _387[0].z = _105._m0[0].z;
  ...
}
```

We'll report this.

**Comment by romainguy** [comment]
That said the generated code is correct, just a bit too complicated. The driver is falling over :/

**Comment by pixelflinger** [comment]
Still need to report this to spirvopt/spirvtools.

**Comment by prideout** [comment]
There are two issues here: (1) incorrect rendering seen on an NVIDIA Linux machine, and (2) poor optimization.

The poor optimization code that Mathias noticed is actually from the "good" case (correct rendering).

For (1) I don't think there's anything actionable on our end, I can't repro it on my MacBook.  @roxlu maybe you can give it another try using latest NVIDIA drivers + the latest Filament code.  Note that we updated glslang and spirv-tools today.

For (2) I can still reproduce it, even with the latest glslang and spirv-tools.  I verified this by hacking the vertex shader in pointSprites.mat and doing:

```
./out/cmake-release/tools/matinfo/matinfo -w 8080 out/cmake-release/samples/generated/material/pointSprites.filamat
```

**Comment by prideout** [comment]
Correction, the poor optimization that Mathias noticed is indeed from the "bad" case.

However, there are still two separate issues here: for the second issue I will file a ticket against spirv-tools and reference it here, so that we can close this one out.

**Comment by prideout** [comment]
I filed an issue with spirv-tools here:
https://github.com/KhronosGroup/SPIRV-Tools/issues/4371

**Comment by dandingol03** [comment]
> This issue is either caused because I've been looking at the wrong thing or I must be doing something wrong at a different level. While trying to fix an issue I had with billboarding I stripped away my code piece by piece down to the following code. Somehow I get different results when I use `material.worldPosition = mat * getPosition();` and `material.worldPosition = rot * getPosition();`
> 
> ```glsl
> material {
>  name : color,
>     shadingModel : lit,
>     blending: opaque,
>     doubleSided: true,
>     vertexDomain: object,
>     parameters : [
>       { type: float3, name: albedo },
>       { type: float, name: roughness },
>       { type: float, name: metallic },
>       { type: float, name: alpha }
>     ],
>     }
> 
> fragment {
>   void material(inout MaterialInputs material) {
>     prepareMaterial(material);
>     material.baseColor.rgb = vec3(1, 1, 1);
>     material.baseColor.a = 1.0;
>   }
> }
> 
> vertex {
>   
>   void materialVertex(inout MaterialVertexInputs material) {
> 
>     mat4 mat = getWorldFromModelMatrix();
>     mat4 rot;
>         
>     rot[0][0] = mat[0][0];
>     rot[0][1] = mat[0][1];
>     rot[0][2] = mat[0][2];
>     rot[0][3] = mat[0][3];
>         
>     rot[1][0] = mat[1][0];
>     rot[1][1] = mat[1][1];
>     rot[1][2] = mat[1][2];
>     rot[1][3] = mat[1][3];
>         
>     rot[2][0] = mat[2][0];
>     rot[2][1] = mat[2][1];
>     rot[2][2] = mat[2][2];
>     rot[2][3] = mat[2][3];
> 
>     rot[3][0] = mat[3][0];
>     rot[3][1] = mat[3][1];
>     rot[3][2] = mat[3][2];
>     rot[3][3] = mat[3][3];
> 
>     //material.worldPosition = mat * getPosition();
>     material.worldPosition = rot * getPosition();
>   }
> }
> ```
> 
> When I use `material.worldPosition = mat * getPosition()` I get ![image](https://user-images.githubusercontent.com/358809/91718142-1c8ddb00-eb93-11ea-9086-5c15adaa51d5.png)
> 
> And when I use `material.worldPosition = rot * getPosition()` I get ![image](https://user-images.githubusercontent.com/358809/91718194-362f2280-eb93-11ea-8f45-d0e3d2dbcd5d.png)
> 
> My system:
> 
> ```
> $ lspci -k | grep -A 2 -E "(VGA|3D)"
> 01:00.0 VGA compatible controller: NVIDIA Corporation TU104 [GeForce RTX 2080 SUPER] (rev a1)
> 	Subsystem: Gigabyte Technology Co., Ltd Device 3fe9
> 	Kernel driver in use: nvidia
> 
> $ uname -a
> Linux arch2080 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux
> 
> # from /var/log/Xorg.0.log
> [    12.853] (II) Module nvidia: vendor="NVIDIA Corporation"
> [    12.854] (II) NVIDIA dlloader X Driver  450.66  Wed Aug 12 19:44:12 UTC 2020
> [    12.854] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
> [    12.862] (**) NVIDIA(0): Depth 24, (--) framebuffer bpp 32
> [    12.862] (==) NVIDIA(0): RGB weight 888
> [    12.862] (==) NVIDIA(0): Default visual is TrueColor
> [    12.862] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
> [    12.862] (II) Applying OutputClass "nvidia" options to /dev/dri/card0
> [    12.862] (**) NVIDIA(0): Option "AllowEmptyInitialConfiguration"
> [    12.862] (**) NVIDIA(0): Option "HardDPMS" "false"
> [    12.862] (**) NVIDIA(0): Enabling 2D acceleration
> [    12.862] (II) Loading sub module "glxserver_nvidia"
> [    12.862] (II) LoadModule: "glxserver_nvidia"
> [    12.863] (II) Loading /usr/lib/nvidia/xorg/libglxserver_nvidia.so
> [    12.924] (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
> [    12.925] (II) NVIDIA GLX Module  450.66  Wed Aug 12 19:41:37 UTC 2020
> [    12.927] (II) NVIDIA: The X server supports PRIME Render Offload.
> ```

Hi, is it convinient for you to share the `billboard` implemention code? I am also studying how to implement `billboard` with filament
