### ISSUE TITLE
Bitmaskable Texture$Usage through jsbinding

### ISSUE THREAD

**Issue by DylanYasen** [google/filament#3028]
**Describe the bug**
bitwise ops on typed enum, specifically needed for TextureUsage, doesn't seem to work through interop. can't create a sampleable & color/depth texture because of this.

```
Texture$Usage.SAMPLEABLE => js object
Texture$Usage.SAMPLEABLE | Texture$Usage.COLOR  => 0 
Texture$Usage.SAMPLEABLE.value | Texture$Usage.COLOR.value  => 17 (correct)
```

**To Reproduce**
```
Texture.Builder()
.width(1024).height(1024).levels(1)
.usage(Texture$Usage.SAMPLEABLE | Texture$Usage.COLOR)
.format(Texture$InternalFormat.RGB32F)
.sampler(Texture$Sampler.SAMPLER_2D)
.build(engine)
```

**Work around**
this is what I'm doing locally for now as a workaround.
basically set the binding to take in an uint instead of the enum
```
.BUILDER_FUNCTION("usage", TexBuilder, (TexBuilder* builder, uint8_t usage), {
        return &builder->usage((Texture::usage)usage); });
```

this now allows:
```
.usage(Texture$Usage.SAMPLEABLE.value | Texture$Usage.COLOR.value)
```
which still looks nasty and unnatural to me because of that .value,  

I'm open for better ideas, not familiar with wasm.  
thanks

**Comment by prideout** [comment]
Thanks for reporting this!  I think your "workaround" is actually the simplest way to fix this.  Luckily this is the only bitmask type used by the JS bindings.  I will need to adjust the TypeScript definitions too.
