### ISSUE TITLE
How to reset model to its default position and orientation.

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#3030]
I am trying to set the model position and orientation with the below code.

 
```
val manip = Manipulator.Builder()
            .targetPosition(0.0f, 0.0f, -4.0f)
            .orbitHomePosition(0.00f, 0.0f, -1.25f)
            .viewport(mySurfaceView.width, mySurfaceView.height)
            .build(Manipulator.Mode.ORBIT)
        engine = Engine.create()
        modelViewer = ModelViewer(mySurfaceView, engine, manip)

```
The above code set up my model to the initial position. 
but I want to reset it programmatically like when the user press any button, it should be reset to its default position. I tried to reinitialize the model viewer with new manipulator values but seems like it is not working. is there any way that we can change manipulator values runtime?

**Comment by romainguy** [comment]
The manipulator only changes the camera, not the model itself. You can simply use the ModelViewer's camera directly and reset its position.

**Comment by prideout** [comment]
To reset the manipulator to the home position, you can do:

```
val home = manipulator.getHomeBookmark()
manipulator.jumpToBookmark(home)
```

This is documented in [Manipulator.java](https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java)
