### ISSUE TITLE
Entity that always renders on top of scene ?

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#3033]
Is it possible to render a particular entity so that it always is visible and never occluded by other objects in the scene ? Not sure if this is material level change or entity change. I played with priority and unlit materials but they still disappear when interested by other entities in scene.

**Comment by DylanYasen** [comment]
Turn off depth test

**Comment by romainguy** [comment]
What @DylanYasen said, you can do so by setting `depthCulling` to `false` in your material. You'll also want to give the `Renderable` a low priority so it's drawn last.

**Comment by thirdmenson** [comment]
@romainguy Thanks. I tried to build a unlit material with depthCulling set to false like this 
`filamat::MaterialBuilder::init();
	filamat::Package pkg = filamat::MaterialBuilder()
		.name("AlwaysVisibleMat")
		.parameter(filamat::MaterialBuilder::SamplerType::SAMPLER_2D, "basecolor")
		.material(R"SHADER(
                void material(inout MaterialInputs material) {
					prepareMaterial(material);
					material.baseColor = materialParams.baseColor;
				}
            )SHADER")
		.shading(Shading::UNLIT)
		.depthWrite(false)
		.depthCulling(false)
		.build();

	Material* material = Material::Builder().package(pkg.getData(), pkg.getSize())
		.build(engine);`

But I am getting material version mismatch. MATERIAL_VERSION is 4 and the version from the chunk is 1 for some reason. Who sets the version on the chunk? Is it because I have older version of filamat.lib (should be same build but not sure what is causing the version mismatch)?

**Comment by romainguy** [comment]
Yes filamat sets the version. You need to use a library that matches the version of filament you are using. Alternatively you can just use matc from the command line instead.
