### ISSUE TITLE
Filament + Vuforia

### ISSUE THREAD

**Issue by tanis2000** [google/filament#3034]
I am trying to use Filament together with Vuforia on Android but I'm experiencing some issues.
As far as I understand Vuforia is using a GLSurfaceView to render its stuff into a GL texture.

I would like to take that texture and use it with Filament to draw it as the background of the Surface and then add some models on top of it based on the anchors that I'm getting back from Vuforia.

It looks like Filament needs to run on the main thread when rendering so I wonder if there's a way to share the GL context or if there's any differe way to handle this use-case.

My current implementation is just using one GLSurfaceView and on its GLThread there's Vuforia rendering the texture. Then I have a Choreographer that is attached to that surface and I'm trying to render from there but it's crashing badly.

**Comment by romainguy** [comment]
The way to do this properly on Android is to use a `SurfaceTexture` and have Vuforia (or any other producer) render into the `SurfaceTexture`'s `Surface`. If Vuforia forces you to go through a `GLSurfaceView` (and it **shouldn't**), you're out of luck.

Filament does *not* need to run on the main thread. You can use any thread you want as long as it's always the same thread (and Filament is heavily multi-threaded internally, rendering actually happens on a separate thread).

**Comment by tanis2000** [comment]
If you check the Android sample coming from Vuforia, they are using the `GLSurfaceView` https://gist.github.com/tanis2000/8a8079839ae38627abf2811d767e4207#file-vuforiaactivity-kt-L34 and under the hood the C++ controller is creating a GL render texture and passing around it's id so that their GL renderer can reference that texture https://gist.github.com/tanis2000/02ae3b63f122aa12e8041cf12731a628#file-appcontroller-cpp-L338

Or at least that's what I'm guessing as the library sources are closed source.

I believe that your proposed flow would be like:

- create a new GL texture from within Filament's GL context 
- create a new SurfaceTexture from the texture id that I get back from Filament
- create a new Surface from the SurfaceTexture
- feed the Surface to Vuforia

but maybe it's even easier to just do this from within the C++ part as Vuforia is mainly a C++ library and all of the heavy lifting is already done there. What I'm not sure about is how Vuforia renders the camera feed to that texture...

**Comment by romainguy** [comment]
You don't need to create the SurfaceTexture from within Filament's GL context. And actually our APIs don't let you do this, because Filament doesn't assume it's using OpenGL. The SurfaceTexture can be created outside of Filament.

Alternatively, can Vuforia just give you the camera stream? That's how ARCore works and we simply pass the camera stream's SurfaceTexture to Filament for rendering.

**Comment by tanis2000** [comment]
I'm not an expert with Vuforia, I've just started having a look at it so I'm diving through the scarse documentation that I could find around the net.

According to the lifecycle page https://library.vuforia.com/content/vuforia-library/en/reference/cpp/index.html#Lifecycle there is a `CameraDevice` class that is bound to the hardware camera https://library.vuforia.com/content/vuforia-library/en/reference/cpp/classVuforia_1_1CameraDevice.html but I can't see any method to get the stream out of that thing. Indeed that would have been handy.

**Comment by prideout** [comment]
@tanis2000, do we need to keep this issue open?  Is there a Filament feature that would help you with this integration?

**Comment by tanis2000** [comment]
@prideout I guess you can close this. Integrating Vuforia with Filament is painful and it looks like the best chance is to actually read the NV21 image from its internal array of images and perform the conversion in a shader (Filament's material?) and then apply it to a plane but it's a stretch.
Unfortunately Vuforia's documentation is lacking.
