### ISSUE TITLE
Vulkan on Win10 black screen

### ISSUE THREAD

**Issue by Qskotlv** [google/filament#3037]
Run the hellowTriangle, hellowPBR, black screen.
The Log :
FEngine (64 bits) created at 0000016A1FD7D080 (threading is enabled)
FEngine resolved backend: Vulkan
Vulkan device driver: NVIDIA 451.48
Selected physical device 'GeForce GTX 1060' from 2 physical devices. (vendor 0x0x10de, device 0x0x1c20, driver 0x0x70cc0000, api 1.2)
Sampleable depth formats: VK_FORMAT_D16_UNORM VK_FORMAT_X8_D24_UNORM_PACK32 VK_FORMAT_D32_SFLOAT VK_FORMAT_S8_UINT VK_FORMAT_D24_UNORM_S8_UINT VK_FORMAT_D32_SFLOAT_S8_UINT
vkCreateSwapchain: 1024x640, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 3, VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR

**Comment by Qskotlv** [comment]
I captured one frame in RenderDoc, the ColorPass is black.

**Comment by romainguy** [comment]
Thanks for the report. Which version of Filament did you try?

**Comment by Qskotlv** [comment]
> Thanks for the report. Which version of Filament did you try?
Maybe the latest.

**Comment by Qskotlv** [comment]
> Thanks for the report. Which version of Filament did you try?

I downloaded a few days ago. Maybe at the latest.

**Comment by bejado** [comment]
I suspect this is related to #2872

**Comment by zbzdys** [comment]
with nvidia driver version 456.38, problem gone

**Comment by ArtisticCoding** [comment]
hellotriangle 1.70 work correctly, but 1.80, 1.81, 1.9x does not work!!!

int main(int argc, char** argv) {
    Config config;
    config.title = "hellotriangle";
    config.backend = filament::Engine::Backend::VULKAN;  //<- Added!!!

    App app;
       ... 
}

**Comment by bejado** [comment]
Thanks for the additional info. I'm able to reproduce and will investigate.

**Comment by bejado** [comment]
@prideout 

I see a couple validation warnings like this:
```
VULKAN WARNING: (UNASSIGNED-CoreValidation-Shader-OutputNotConsumed) fragment shader writes to output location 0 with no matching attachment
```

I wonder if they're related to the black screen.

**Comment by prideout** [comment]
@bejado thanks for looking into this!

By the way that warning is a known issue, see the TODO in `colorGradingAsSubpass.mat`; I think we were going to add a post processing feature for this.
