### ISSUE TITLE
Displaying device domain background through material with high transmission factor

### ISSUE THREAD

**Issue by kapsyst** [google/filament#3040]
**Describe the bug**
I'm not entirely sure if this is a bug, but I'm trying to achieve the following:
- Implementing AR Augmented Faces using Filament
- Use physically based rendering (with an environment map) to draw realistic mesh materials in the AR space
- This rendering must also support transparency to allow the original photo stream to bleed through different parts of the mesh.

This works fine when I use a Skybox with image based lighting, and using a material with a high `transmission` factor (0.95):
<img src="https://user-images.githubusercontent.com/37162976/92100502-d8127180-ee16-11ea-8584-5313c42d5405.PNG" width="50%">

However, when disabling the Skybox (while still using the IBL), the original IBL is still displayed through the mesh, instead of the camera stream:
<img src="https://user-images.githubusercontent.com/37162976/92100667-0c862d80-ee17-11ea-96b4-66ecac76646c.PNG" width="50%">

I would like to use IBL to give the material specular/reflective properties of the environment, while still allowing the background photo stream (vertexDomain : device, shadingModel : unlit) to be displayed. Is there any way to achieve this?

PS: Is there a way to rotate the skybox/IBL? I can't find one...

**To Reproduce**
1. As above, create a project with a `vertexDomain: device` background, and skybox with IBL. Create a mesh with a high transmission value (so that it's semi-transparent). Disable the skybox and the skybox should still be seen behind the mesh.

**Expected behavior**
I would expect to see the background rather than the IBL. Although it makes sense why the IBL would be shown, I'm wondering if there's a way to display the background.

**Screenshots**
As above.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.6.1

**Comment by romainguy** [comment]
Transmission is only supported when enabling refraction on an object, is that what you are doing? If so, there are [two refraction modes](https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/blendingandtransparency:refractionmode): cubemap and screenspace. It sounds like you want the latter. Note that if you are not going to use rough transmission, it would be much, much cheaper so simply use a transparent material with an alpha.

There is a way to rotate the IBL, with `IndirectLight::setRotation`. `Skybox` will automatically pickup the rotation.

**Comment by kapsyst** [comment]
@romainguy Thank you very much for your reply. Rotating the IBL worked perfectly.

Yes, this is for a virtual makeup application. Particularly for lipstick, I need to represent a material that allows the original lip texture (from the camera image) to bleed through to a certain degree when refracting, but still use the cube map when reflecting (for highly reflective lip glosses etc). As far as I understand, just using a transparent material will also mean that reflected pixels (at steep to grazing angles, i.e, close to 100% reflection) will also appear transparent, when they should be opaque?

A `screenspace` refraction mode sounds like what I'm after, but I get the following error when trying it:
```
validateFunctionArguments:3543:
failed assertion `Fragment Function(blitterFrag):
Shader reads texture (sourceColor[0]) whose usage (0x04) doesn't specify MTLTextureUsageShaderRead (0x01)'
```
This occurs at line 248 of `MetalBlitter.mm`:
```
[encoder drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];
```
And it occurs even when disabling the camera stream texture.

Here is the material for the face mesh:
```
material {
    name : bakedColor2,
    refractionMode : screenspace,
    refractionType : thin,
    culling : none,
    shadingModel : lit,

    parameters : [
        {
            type : float3,
            name : baseColor
        }
    ],
    requires : [
        uv0,
        tangents
    ]
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);

        material.baseColor.rgb = materialParams.baseColor;
        material.roughness = 0.3;
        material.metallic = 0.0;
        material.clearCoat = 1.0;
        material.ior = 1.1;
        material.transmission = 0.7;
    }
}
```
I understand you must be busy and this is not a normal usage case, but any help would be much appreciated!

**Comment by romainguy** [comment]
Ah no Filament implements transparency properly. Specular reflections will not be transparent. You can make them be using the "fade" blend mode. But the "transparency" mode will do what you want.

What version of filament are you using? We made fixes in the Metal backend recently.

@bejado as fyi

**Comment by kapsyst** [comment]
@romainguy Thank you very much and I apologize for the late reply.

Using 1.8.0 I was witnessing Z-fighting? like artifacts, but upgrading to 1.8.1 made them go away.

FYI I also had to use the patch here: https://github.com/google/filament/commit/3092063ebba2cb24a6dfc5ff97121fdfa09e1da1

**Comment by dandingol03** [comment]
@kapsyst HI,there is also z-fighting after i set the tranmission mat's blending mode to `fade`. My filament version is 1.12.5

**Comment by kapsyst** [comment]
@dandingol03 the project I was working ended up using different tech. So my memory of the particulars of Filament and this issue have long since faded. Apologies I can't be of any help.
