### ISSUE TITLE
Filament webGL demos not working on iOS 

### ISSUE THREAD

**Issue by Juanmaramon** [google/filament#3041]
Filament webGL demos from https://google.github.io/filament/webgl/ are not working on my iphone iOS13.1.3 + Chrome 84.0.4147.122. On Android devices the demos are working fine.
Does is WebGL filament compatible with iOS?

**Comment by romainguy** [comment]
Filament uses WebGL 2 which is not supported on iOS 13. It is however coming to Safari/iOS 14 I believe.

**Comment by tangobravo** [comment]
WebGL 2 was an experimental feature, off by default, in iOS 14. It did however appear to work with the filament demos when toggled on - I think iOS 14 switched to use ANGLE as a WebGL backend, the previous Safari WebGL 2 implementation was very incomplete and basically unusable before then.

The good news is it looks like WebGL 2 will finally be on by default in iOS 15. :tada:
https://developer.apple.com/documentation/safari-release-notes/safari-15-beta-release-notes (scroll down to near the bottom, it's in the "WebAPIs" section).
