### ISSUE TITLE
Filament Android project compilation fail

### ISSUE THREAD

**Issue by otakutronic** [google/filament#3046]
I am a Mac user who is building Filament for Android using the following instructions https://github.com/google/filament/blob/main/BUILDING.md

1. I tried both **./build.sh -p android release** and **./build.sh -i -p android release**

2.  After building successfully I open the **android/samples/hellotriangle** project in Android Studio but the project compilation fails with error:  **Could not find xxxx/xxxxx/xxxx/filament/out/release/filament/bin/matc. Ensure Filament has been built/installed before building this app.**

_Why is there no release/filament in the out/ folder?_

3. So I tried downloading the compiled release for Mac **filament-v1.8.1-mac.tgz** from here https://github.com/google/filament/releases

4. I copied the bin folder to the root directory of filament, under out/release/filament. The Android project now compiles. 

5. When I run it on my Android phone I see a crash similar to this https://github.com/google/filament/issues/1088

Logcat details:

**filament.hellotriangle E/Filament: Panic
    in static filament::MaterialParser *filament::FMaterial::createParser(backend::Backend, const void *, size_t):514
    reason: Material version mismatch. Expected 8 but received 7.**

_If it is the same issue described here  https://github.com/google/filament/issues/1088 and I am building Filament for Android with an older version of matc where can I get version 8?_

_Or is it another issue?_

**Comment by otakutronic** [comment]
Okay I fixed it with this:

./build.sh -p desktop,android -i release

**Comment by lightRain2010** [comment]
> Okay I fixed it with this:
> 
> ./build.sh -p desktop,android -i release

> 

It works ,thanks
