### ISSUE TITLE
Normalmap detail differs between iOS and desktop

### ISSUE THREAD

**Issue by vcxyk** [google/filament#3047]
hi, I have some problem on the normal map precision. Here's the screenshots from two different material providers based on filament 1.7.0.  (Camera in a very short distance to the bag surface)

GENERATE_SHADERS version:
![image](https://user-images.githubusercontent.com/5915889/92373722-5762b680-f131-11ea-991e-cd9037414dc9.png)

LOAD_UBERSHADERS version:
![image](https://user-images.githubusercontent.com/5915889/92373537-0a7ee000-f131-11ea-9b5f-14023cdb1e3d.png)

**Comment by romainguy** [comment]
No the implementation is the same for normal maps. Your issue must be somewhere else.

**Comment by bejado** [comment]
Is the `LOAD_UBERSHADERS` version is running on iOS with Metal? What's the texture format for the normal map?

On desktop, you can try the ubershader version using the `-u` flag in `gltf_viewer`. My guess is this is an iOS texture bug rather than anything related to shaders or normal mapping.

**Comment by vcxyk** [comment]
> Is the `LOAD_UBERSHADERS` version is running on iOS with Metal? What's the texture format for the normal map?
> 
> On desktop, you can try the ubershader version using the `-u` flag in `gltf_viewer`. My guess is this is an iOS texture bug rather than anything related to shaders or normal mapping.

Hi bejado, I think that the texture is correctly loaded since it works fine when I use the "GENERATE_SHADERS" material provider.  I tried "LOAD_UBERSHADERS" and "GENERATE_SHADERS" with -u param in gltf_viewer and it works fine, too.  The problem occurs when I use LOAD_UBERSHADERS material provider on mobile.  (By the way,  it runs with OpenGLES driver since we have some GL context passed in to initialize the Filament engine.)

**Comment by bejado** [comment]
I'm not able to reproduce:

![Screen Shot 2020-09-11 at 1 04 13 PM](https://user-images.githubusercontent.com/5298046/92968145-6b5b3080-f42f-11ea-8f62-5e6a4e82aac7.png)



Could you try with the latest version of Filament? Which iOS device / version are you using?
