### ISSUE TITLE
sample-gltf-viewer with transparent background

### ISSUE THREAD

**Issue by YuChengFan** [google/filament#3048]
I am new to filament and recently I am working on sample-gltf-viewer. 
I tried to modify skybox parameters to remove black background, but was still not able to remove it. 
![Screenshot_20200907-201933](https://user-images.githubusercontent.com/17403810/92387807-c7c90200-f148-11ea-9f16-9126e6219289.png)

Below are my skybox parameters. 
`scene.skybox = Skybox.Builder().color(0.0f, 0.0f, 0.0f, 0.0f).build(engine)`

Could you guide me how to make the background transparent? Thank you very much. 

**OS and backend**
android

**Comment by prideout** [comment]
Try the following.

```
view.setBlendMode(View.BlendMode.TRANSLUCENT)
scene.setSkybox(null)
```

**Comment by shivammaindola** [comment]
@prideout It is showing like this. This code is not working.
How can I make it's background transparent? I want only a drone image, not the background part.

![Screenshot_2020-10-21-11-18-24-514_com google android filament gltf (1)](https://user-images.githubusercontent.com/39567362/96678612-b0a84180-138f-11eb-8646-b1b68a773d4a.jpg)

**Comment by anshmidt** [comment]
I spent a lot of time making the background transparent, and finally made it work. Here's how.

```
private fun makeTransparentBackground() {
        surfaceView.setZOrderOnTop(true)
        surfaceView.setBackgroundColor(Color.TRANSPARENT)
        surfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT)

        modelViewer.view.blendMode = View.BlendMode.TRANSLUCENT
        modelViewer.scene.skybox = null

        val options = renderer.clearOptions
        options.clear = true
        renderer.clearOptions = options
    }
```

**Comment by p147123456** [comment]
I have the same problem, tried all the above methods and not work.
