### ISSUE TITLE
WebAssembly build error

### ISSUE THREAD

**Issue by dzwdyc** [google/filament#3055]
use "./build.sh -p webgl release" to build WebAssembly cause error:

[622/675] Building CXX object filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o
/usr/bin/clang++  -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/ibl/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections   -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -fPIC -MD -MT filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o -MF filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o.d -o filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o -c ../../filament/src/fg/FrameGraphHandle.cpp
In file included from ../../filament/src/fg/FrameGraphHandle.cpp:21:
../../filament/src/fg/FrameGraph.h:77:46: error: explicit specialization of 'create' in class scope
        FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                             ^
../../filament/src/fg/FrameGraph.h:218:42: error: explicit specialization of 'import' in class scope
    FrameGraphId<FrameGraphRenderTarget> import(const char* name,
                                         ^
../../filament/src/fg/FrameGraph.h:299:42: error: explicit specialization of 'create' in class scope
    FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                         ^
3 errors generated.

**Comment by bejado** [comment]
Your Emscripten SDK might be out of date. You can try running:

```
${EMSDK}/emsdk install latest
${EMSDK}/emsdk activate latest
```

I'm using `releases-upstream-3880c744c068986d4ee781a61f7b2e820043e11f-64bit`.

**Comment by dzwdyc** [comment]
> Your Emscripten SDK might be out of date. You can try running:
> 
> ```
> ${EMSDK}/emsdk install latest
> ${EMSDK}/emsdk activate latest
> ```
> 
> I'm using `releases-upstream-3880c744c068986d4ee781a61f7b2e820043e11f-64bit`.

 I'm using "sdk-releases-upstream-5974288502aab433d45f53511e961aaca4079d86-64bit"

**Comment by dzwdyc** [comment]
~/emsdk-2.0.0$ emsdk list

The *recommended* precompiled SDK download is 2.0.0 (5974288502aab433d45f53511e961aaca4079d86).

To install/activate it, use one of:
         latest                  [default (llvm) backend]
         latest-fastcomp         [legacy (fastcomp) backend]

Those are equivalent to installing/activating the following:
         2.0.0             INSTALLED
         2.0.0-fastcomp

All recent (non-legacy) installable versions are:
         2.0.0    INSTALLED
         1.40.1
         1.40.0
         1.39.20
         1.39.19
         1.39.18
         1.39.17
         1.39.16
         1.39.15
         1.39.14
         1.39.13
         1.39.12
         1.39.11
         1.39.10
         1.39.9
         1.39.8
         1.39.7
         1.39.6
         1.39.5
         1.39.4
         1.39.3
         1.39.2
         1.39.1
         1.39.0
         1.38.48
         1.38.47
         1.38.46
         1.38.45
         1.38.44
         1.38.43
         1.38.42
         1.38.41
         1.38.40
         1.38.39
         1.38.38
         1.38.37
         1.38.36
         1.38.35
         1.38.34
         1.38.33

The additional following precompiled SDKs are also available for download:
         sdk-releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit
         sdk-releases-upstream-2f9889f6f78403210222b177b068d5004be2798c-64bit
         sdk-releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit
         sdk-releases-fastcomp-2f9889f6f78403210222b177b068d5004be2798c-64bit
         sdk-fastcomp-1.38.30-64bit
         sdk-fastcomp-1.38.31-64bit

**Comment by tommitytom** [comment]
FWIW, I'm using the master branch of emsdk on both WSL and docker and it's building fine for me

**Comment by prideout** [comment]
Our continuous builds use emscripten 1.39.19, as per BUILDING.md.

**Comment by dzwdyc** [comment]
> Our continuous builds use emscripten 1.39.19, as per BUILDING.md.

got it!
