### ISSUE TITLE
Clarification of shared material behaviour

### ISSUE THREAD

**Issue by rawnsley** [google/filament#3058]
If two renderables share a material instance does Filament combine them into a single draw call? Similarly if a material with no parameters generates two instances will renderables using those instances be combined into a single draw call? (less likely I guess).

The background for this is that I would like to know how much mesh combining and bookkeeping I need to do in my application and how much Filament is already doing.

**Comment by romainguy** [comment]
Filament will not combine draw calls on your behalf (they would also need the same transform btw). It will however avoid any unnecessary state change, so multiple renderables with the same instance will be drawn without swapping program on the GPU.
