### ISSUE TITLE
Runtime shader compilation error on Android devices that don't support GL_GOOGLE_cpp_style_line_directive

### ISSUE THREAD

**Issue by rawnsley** [google/filament#3059]
I think this another instance of [this problem](https://github.com/google/filament/issues/2857), which was fixed [by explicitly removing the unsupported directives](https://github.com/google/filament/pull/2860).

The problem occurs for me when I link to the debug version of the Filament AAR. The _skybox.mat_ material has been compiled into the AAR [without optimization](https://github.com/google/filament/blob/main/CMakeLists.txt#L409), which means the unsupported directives remain and it gives the following error:

```
E/Filament: COMPILE ERROR: 
    0:4: P0003: Warning: Extension 'GL_GOOGLE_cpp_style_line_directive' not supported
    0:9: L0001: Unknown character '"'(34)
    0:9: L0001: Unknown character '"'(34)
    0:44: L0001: Unknown character '"'(34)
    0:44: L0001: Unknown character '"'(34)
    0:207: L0001: Unknown character '"'(34)
    0:207: L0001: Unknown character '"'(34)
    0:347: L0001: Unknown character '"'(34)
    0:347: L0001: Unknown character '"'(34)
    0:370: L0001: Unknown character '"'(34)
    0:370: L0001: Unknown character '"'(34)
    0:446: L0001: Unknown character '"'
    1:   #version 300 es
    2:   
    3:   #define TARGET_MOBILE
    4:   #extension GL_GOOGLE_cpp_style_line_directive : enable
    5:   
    6:   precision highp float;
    7:   precision highp int;
    8:   #if defined(GL_GOOGLE_cpp_style_line_directive)
    9:   #line 0 "common_types.fs"
    ....
```

**Comment by bejado** [comment]
@romainguy @pixelflinger 
Here's my recommendation, which I don't love, but I think is worth it considering how much benefit we get from these #line directives.

In the OpenGL driver, before compiling a shader, we search for the "GL_GOOGLE_cpp_style_line_directive" string. If we find it in the first ~10 lines, it's probably an unoptimized shader. In that case, we remove any Google-style line directives from the rest of the shader before passing it to the OpenGL driver.

**Comment by romainguy** [comment]
I'm ok with that, esp. in debug mode.
