### ISSUE TITLE
Tombstone in sample-gltf-viewer 

### ISSUE THREAD

**Issue by daichen** [google/filament#3061]
**Describe the bug**
Tombstone in sample-gltf-viewer 

**To Reproduce**
1. keep on double tabing the activity to reload the model
2. after some times the app crashed
[SYSTEM_TOMBSTONE@1599705295475.txt](https://github.com/google/filament/files/5198940/SYSTEM_TOMBSTONE%401599705295475.txt)

[so-files.zip](https://github.com/google/filament/files/5198944/so-files.zip)

**Comment by bejado** [comment]
Looks like an assert is getting fired inside [`FTexture::setImage`](https://github.com/google/filament/blob/main/filament/src/Texture.cpp#L180). Can you check the logs and see which one?

**Comment by romainguy** [comment]
So there is code in gltf-viewer to detroy and recreate the model on double tap:

```
    inner class DoubleTapListener : GestureDetector.SimpleOnGestureListener() {
        override fun onDoubleTap(e: MotionEvent?): Boolean {
            modelViewer.destroyModel()
            createRenderables()
            return super.onDoubleTap(e)
        }
    }
```

The problem as identified by @pixelflinger is if you double tap while the model is being loaded. It should properly cancel the async loading.

**Comment by daichen** [comment]
the back trace

`Build fingerprint: 'Xiaomi/cepheus/cepheus:10/QKQ1.190825.002/20.8.13:user/release-keys'
Abort message: 'terminating with uncaught exception of type utils::PostconditionPanic'
#00 0x00000000000830f0 /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: f7f8284982bf528e628529b3fc094df1)
#01 0x0000000000530320 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                abort_message
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:76:5
#02 0x0000000000530490 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                demangling_terminate_handler()
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_default_handlers.cpp:67:21
#03 0x000000000052d5bc /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                std::__terminate(void (*)())
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_handlers.cpp:59:9
#04 0x000000000052cbe8 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_exception.cpp:152:5
#05 0x000000000052cb44 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (__cxa_throw+112) (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                __cxa_throw
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_exception.cpp:284:5
#06 0x0000000000501438 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (utils::TPanic<utils::PostconditionPanic>::panic(char const*, char const*, int, char const*, ...)+408) (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                utils::TPanic<utils::PostconditionPanic>::panic(char const*, char const*, int, char const*, ...)
                                                                                                /home/dc/work/code/dc/filament/out/cmake-android-debug-aarch64/../../libs/utils/src/Panic.cpp:143:9
#07 0x00000000003241b0 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (filament::FTexture::setImage(filament::FEngine&, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, filament::backend::PixelBufferDescriptor&&) const+336) (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                filament::FTexture::setImage(filament::FEngine&, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, filament::backend::PixelBufferDescriptor&&) const
                                                                                                /home/dc/work/code/dc/filament/out/cmake-android-debug-aarch64/../../filament/src/Texture.cpp:203:10
#08 0x000000000032705c /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (filament::Texture::setImage(filament::Engine&, unsigned long, filament::backend::PixelBufferDescriptor&&) const+172) (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                filament::Texture::setImage(filament::Engine&, unsigned long, filament::backend::PixelBufferDescriptor&&) const
                                                                                                /home/dc/work/code/dc/filament/out/cmake-android-debug-aarch64/../../filament/src/Texture.cpp:1048:19
#09 0x0000000000154364 /data/app/com.google.android.filament.gltf/lib/arm64/libgltfio-jni.so (BuildId: 917b324868564956152f9b9f33a609f64717f39f)
                                                                                              gltfio::ResourceLoader::Impl::uploadPendingTextures()::$_1::operator()((anonymous namespace)::TextureCacheEntry*, filament::Engine&) const
                                                                                              /home/dc/work/code/dc/filament/libs/gltfio/src/ResourceLoader.cpp:538:22
`

**Comment by daichen** [comment]
backtrace

Build fingerprint: 'Xiaomi/cepheus/cepheus:10/QKQ1.190825.002/20.8.13:user/release-keys'
Abort message: 'terminating with uncaught exception of type utils::PostconditionPanic'
#00 0x00000000000830f0 /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: f7f8284982bf528e628529b3fc094df1)
#01 0x0000000000530320 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                abort_message
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:76:5
#02 0x0000000000530490 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                demangling_terminate_handler()
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_default_handlers.cpp:67:21
#03 0x000000000052d5bc /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                std::__terminate(void (*)())
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_handlers.cpp:59:9
#04 0x000000000052cbe8 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_exception.cpp:152:5
#05 0x000000000052cb44 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (__cxa_throw+112) (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                __cxa_throw
                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_exception.cpp:284:5
#06 0x0000000000501438 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (utils::TPanic<utils::PostconditionPanic>::panic(char const*, char const*, int, char const*, ...)+408) (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                utils::TPanic<utils::PostconditionPanic>::panic(char const*, char const*, int, char const*, ...)
                                                                                                /home/dc/work/code/dc/filament/out/cmake-android-debug-aarch64/../../libs/utils/src/Panic.cpp:143:9
#07 0x00000000003241b0 /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (filament::FTexture::setImage(filament::FEngine&, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, filament::backend::PixelBufferDescriptor&&) const+336) (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                filament::FTexture::setImage(filament::FEngine&, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, filament::backend::PixelBufferDescriptor&&) const
                                                                                                /home/dc/work/code/dc/filament/out/cmake-android-debug-aarch64/../../filament/src/Texture.cpp:203:10
#08 0x000000000032705c /data/app/com.google.android.filament.gltf/lib/arm64/libfilament-jni.so (filament::Texture::setImage(filament::Engine&, unsigned long, filament::backend::PixelBufferDescriptor&&) const+172) (BuildId: 20610464664270654d45561b23680d00fc74c624)
                                                                                                filament::Texture::setImage(filament::Engine&, unsigned long, filament::backend::PixelBufferDescriptor&&) const
                                                                                                /home/dc/work/code/dc/filament/out/cmake-android-debug-aarch64/../../filament/src/Texture.cpp:1048:19
#09 0x0000000000154364 /data/app/com.google.android.filament.gltf/lib/arm64/libgltfio-jni.so (BuildId: 917b324868564956152f9b9f33a609f64717f39f)
                                                                                              gltfio::ResourceLoader::Impl::uploadPendingTextures()::$_1::operator()((anonymous namespace)::TextureCacheEntry*, filament::Engine&) const
                                                                                              /home/dc/work/code/dc/filament/libs/gltfio/src/ResourceLoader.cpp:538:22

**Comment by romainguy** [comment]
If the offsets are correct, the panic happens here:

```
    if (!ASSERT_POSTCONDITION_NON_FATAL(!mStream, "setImage() called on a Stream texture.")) {
        return;
    }
```

**Comment by romainguy** [comment]
Fixed in recent change.
