### ISSUE TITLE
Image texture color does not look right

### ISSUE THREAD

**Issue by daichen** [google/filament#3067]
Use a image as texture, and the color does not look right compare with android image view

**Here is the screenshots**

![2](https://user-images.githubusercontent.com/1658580/92913507-690fcb00-f45d-11ea-9a17-5ad3b060d3d9.jpg)
![3](https://user-images.githubusercontent.com/1658580/92913517-6b722500-f45d-11ea-9858-758758cec2b8.jpg)

**Here is the source file**
![Frame 1](https://user-images.githubusercontent.com/1658580/92913825-ab390c80-f45d-11ea-9b7d-81dbb22e78c9.png)
![Frame 2](https://user-images.githubusercontent.com/1658580/92913832-ad9b6680-f45d-11ea-873c-28520cb2d003.png)

**Here is the code I create and set the texture**

` baseColor = loadTexture(engine, resources, R.drawable.p1, TextureType.COLOR)`
`val sampler = TextureSampler()`
 `materialInstance.setParameter("secondary", baseColor, sampler)`

**loadTexture is in com.google.android.filament.textured**

`fun loadTexture(engine: Engine, resources: Resources, resourceId: Int, type: TextureType): Texture {
    val options = BitmapFactory.Options()
    // Color is the only type of texture we want to pre-multiply with the alpha channel
    // Pre-multiplication is the default behavior, so we need to turn it off here
    options.inPremultiplied = type == TextureType.COLOR

    val bitmap = BitmapFactory.decodeResource(resources, resourceId, options)

    val texture = Texture.Builder()
            .width(bitmap.width)
            .height(bitmap.height)
            .sampler(Texture.Sampler.SAMPLER_2D)
            .format(internalFormat(type))
            // This tells Filament to figure out the number of mip levels
            .levels(0xff)
            .build(engine)

    // TextureHelper offers a method that skips the copy of the bitmap into a ByteBuffer
    if (SKIP_BITMAP_COPY) {
        TextureHelper.setBitmap(engine, texture, 0, bitmap)
    } else {
        val buffer = ByteBuffer.allocateDirect(bitmap.byteCount)
        bitmap.copyPixelsToBuffer(buffer)
        // Do not forget to rewind the buffer!
        buffer.flip()

        val descriptor = Texture.PixelBufferDescriptor(
                buffer,
                format(bitmap),
                type(bitmap))

        texture.setImage(engine, 0, descriptor)
    }

    texture.generateMipmaps(engine)

    return texture
}`

**My mat code**

`material {
    name : blit,
    shadingModel : unlit,
    parameters : [
         {
             type : sampler2d,
             name : secondary
         }
    ],
    requires: [
        uv0
    ]
}

fragment {
    precision highp float;
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = texture(materialParams_secondary, getUV0());
        //material.baseColor.rgb = inverseTonemapSRGB(material.baseColor.rgb);
    }
}`

The images are sRGB, but does not look right in texture...
So how to make the color right？ Can anyone tell me where i am wrong

**Comment by daichen** [comment]
And how to deal with the other images with different format?
I want same color with android image view

**Comment by romainguy** [comment]
The only way to make the colors exact is to disable tonemapping. You can set the tonemapping to be `LINEAR` in the `ColorGrading` API.

**Comment by Amitdygon** [comment]
> And how to deal with the other images with different format? I want same color with android image view

Hello Can you please provide your full code its really help to create a texture using any png file.
Thanks
