### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Zumbalamambo** [google/filament#3068]
I'm trying to build it from source on Ubuntu 20. It throws the following error,

```
/filament-1.8.1/third_party/libgtest/tnt/../googletest/include/gtest/gtest.h:55:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
```

Is there any readily available package for ubuntu? or how can I fix it?

**Comment by romainguy** [comment]
cstddef is part of the standard C++ library. Make sure you have installed libc++ and libc++-dev (see our BUILDING instructions file).
