### ISSUE TITLE
Enabling fog gives a black screen on Android adreno GPU

### ISSUE THREAD

**Issue by rawnsley** [google/filament#3069]
If I enable fog for a View I can see the effect fine on my RockChip Mali device, but on my two Adreno devices (an SD 835 and an XR1 processor) the screen is all black.

One time I did see some of my scene, but there was a diagonal line cutting the screen in half with the clear part completely unchanged (no fog) and other part completely black. I can't actually reproduce this state reliably, but it implied some sort of threshold / rounding issue with fog shader calculation.

It seems to be the same with and without post-processing and with optimized and non-optimized material compilation.

Has anyone seen anything similar?

**Comment by rawnsley** [comment]
I've found I can generate the weird effect with the IBL sample. [Full video](http://avn.pub/SkRt0U) and screenshot:


![device-2020-09-11-163656](https://user-images.githubusercontent.com/303516/92945331-0adaec00-f44d-11ea-9c81-f901e33e7a82.png)

**Comment by pixelflinger** [comment]
confirmed. It seems to depend on the camera orientation.

**Comment by pixelflinger** [comment]
You can workaround this bug by setting `inScatteringSize` manually to `-1.0f` (or to a value larger than 0 if you need in-scattering -- 0 is not allowed).
