### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Zumbalamambo** [google/filament#3071]
I'm trying to build filament in Ubuntu 20.0.4. I'm getting the following error,

```
CMake Error at CMakeLists.txt:179 (message):
  Detected C compiler GNU is unsupported
```

The command that I tried is `./build.sh -p desktop,android -i release`

Both Ninja and clang-10 are installed though

**Comment by romainguy** [comment]
See our building instructions. You need to either set clang as your default c/c++ compiler or you need to do so when invoking the build script:

`CC=/usr/bin/clang CXX=/usr/bin/clang++ ./build.sh …`

**Comment by Zumbalamambo** [comment]
@romainguy I tried it too but it throws a new error,

```
CMake Error: File /home/Tools/filament/build/licenses.inc.in does not exist.
CMake Error at CMakeLists.txt:446 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  tools/cmgen/CMakeLists.txt:45 (list_licenses)
```

**Comment by romainguy** [comment]
Make sure you start from scratch. If CMake fails configuration it leaves the build directory in a broken state.

**Comment by Zumbalamambo** [comment]
@romainguy I tried it... Now it has another build error,
```

[35/1218] Linking CXX shared library libs/utils/libbenchmark_utils_callee.so
FAILED: libs/utils/libbenchmark_utils_callee.so 
: && /usr/bin/clang++ -fPIC -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -Wl,--gc-sections -Wl,-Bsymbolic-functions -shared -Wl,-soname,libbenchmark_utils_callee.so -o libs/utils/libbenchmark_utils_callee.so libs/utils/CMakeFiles/benchmark_utils_callee.dir/benchmark/benchmark_callee.cpp.o  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
/usr/bin/ld: cannot find -lc++abi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[44/1218] Building CXX object libs/mat...les/test_math.dir/tests/test_mat.cpp.o
ninja: build stopped: subcommand failed.

```

**Comment by romainguy** [comment]
It's mentioned in the BUILDING instructions file, you need to install `libc++` and `libc++-dev`.

**Comment by Zumbalamambo** [comment]
@romainguy I have ofcourse installed both of those dependencies

**Comment by disini** [comment]
> If under Ubuntu OS, please ref: `$(FILAMENT_SRC_DIR)/build/linux/ci-common.sh`:
> 
> ```
> $ sudo apt-get install clang-8 libc++-8-dev libc++abi-8-dev
> $ sudo apt-get install mesa-common-dev libxi-dev libxxf86vm-dev
> $ sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-8 100
> $ sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-8 100
> ```

It works！ Much  appreciated bro !

**Comment by AndrewChan2022** [comment]
set clang as default 

    sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 60
    sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 60

show all compiler menu and choose default

    sudo update-alternatives --config c++
    sudo update-alternatives --config cc
