### ISSUE TITLE
Pretty easy way to make filament work w/ Google Dart

### ISSUE THREAD

**Issue by unicomp21** [google/filament#3076]
cleanup filament.d.ts so that it works with 

https://github.com/dart-lang/js_facade_gen

https://github.com/google/filament/blob/c529a511f5471a40ec8080b30032391c5b8bb678/web/filament-js/filament.d.ts

**Comment by romainguy** [comment]
Could you elaborate a bit please? What "cleanup" are you talking about?

**Comment by unicomp21** [comment]
Due to the ordering of types in filament.d.ts, the tool cannot run successfully.  Should I post the errors in here?

**Comment by unicomp21** [comment]
@kevmoo was thinking adding filament, in addition to StageXL, for dart graphics libs would be pretty nice!

**Comment by prideout** [comment]
It would be nice if the tool would run in our GitHub Action so that we don't accidentally regress the type ordering.

Looks like it requires nodejs...

**Comment by kevmoo** [comment]
That does look pretty cool! I've pinged folks working on JS interop to see if they have thoughts.

**Comment by romainguy** [comment]
@unicomp21 You can post the errors if you want but please understand that this won't likely be a priority for us as we already have to support many operating systems, graphics APIs and languages with limited resources.

**Comment by unicomp21** [comment]
@kevmoo any feedback from the JS interop guys?

**Comment by kevmoo** [comment]
I was hoping they'd reply here – nothing so far, it seems.

**Comment by unicomp21** [comment]
looks like this isn't going to happen, closing
