### ISSUE TITLE
How to draw lines and set the width of lines?

### ISSUE THREAD

**Issue by shlzxjp** [google/filament#3086]
How to draw lines and set the width of lines?

**Comment by prideout** [comment]
You can use `RenderableManager::PrimitiveType::LINES` but wide lines are not widely supported on all the platform that Filament supports.  For example, they are supported under Vulkan only on 8% of Android devices.  Most WebGL implementations do not support them either.

You might have better luck tessellating them into triangles.

**Comment by shlzxjp** [comment]
Thank you！
