### ISSUE TITLE
Minimum graphics card version for Filament library - macOS

### ISSUE THREAD

**Issue by Pankaj003** [google/filament#3087]
@romainguy, @bejado 
Hi,
We've created a XCode based macOS application and filament is not rendering on few of the macOS systems. I suspect, it may be due to the installed graphics card. I created the application on the below configuration and it is working fine (on other machines with similar GPU/graphics card configuration).
OS: mac10.14.6
Chipset: Intel Iris Plus Graphics 650
VRAM: 1536 MB

On the below graphics card machines I am seeing black window and nothing is getting rendered.
OS: macOS10.14.6
Chipset: Radeon Pro Vega 56
VRAM: 8 GB

OS: macOS10.15.6
Chipset Model: Intel HD Graphics 4000
VRAM: 1536MB

Are the above mentioned graphics cards supported by filament library? Is there any minimum graphics card configuration requirement to use the Filament library?

This issue is also liked to: #2876 

Thanks,
Pankaj

**Comment by rawnsley** [comment]
Have you tried running one of the native apps that ship with Filament? For instance filament/out/cmake-release/samples/gltf-viewer

This will tell you if the problem is with Filament or with your app.

**Comment by Pankaj003** [comment]
Hi,
Thanks for your reply. I am using custom build filament library from #2876, it'll be a bit tricky to link the TNT sample apps with it.  I'll see if I can link my libs with the project, meanwhile are the mentioned graphics card supported by filament?

**Comment by rawnsley** [comment]
I am 99% sure all of those graphics cards are supported.

You can always pull down a clean version of Filament into a separate directory and build it from source. We have a git fork with our own "production" branch, but I often swap back to the main upstream branch when I'm trying to debug problems. This would allow you to build a plain version of gltf_viewer and test it on all three machines.

**Comment by romainguy** [comment]
These cards are supported. Actually filament should support all cards on macos going back to 6 years ago or so at least.

**Comment by Pankaj003** [comment]
@romainguy , @bejado 
Hi, 
I am using **macOS10.14.6, Xcode11.3.1, MacOSX10.15.sdk**, filament version **1.5.2 (filament-20200403-mac.tgz
https://github.com/google/filament/releases/tag/v1.5.2)**. I am getting Metal framework related linker error. Previously I was using Xcode9.2 and got the same error and that time we build the Filament library without Metal  support( #2876). 
Since my application is not working on some of the machines, I want to enable Metal support to be sure that it is not the source of issue.
How can I fix these errors? or alternatively please suggest which filament version I can use which can work on above mentioned versions and has support for the call View::setClearColor?

Undefined symbols for architecture x86_64:
  "_CVPixelBufferGetPixelFormatType", referenced from:
      filament:: backend:: metal::MetalExternalImage:: set(__CVBuffer*) in libbackend.a(MetalExternalImage.mm.o)
      filament:: backend:: metal:: MetalExternalImage::set(__CVBuffer*, unsigned long) in libbackend.a(MetalExternalImage.mm.o)
  "_CVPixelBufferGetPlaneCount", referenced from:
      filament::b ackend:: metal:: MetalExternalImage:: set(__CVBuffer*) in libbackend.a(MetalExternalImage.mm.o)
  "_CVPixelBufferGetWidthOfPlane", referenced from:
      filament:: backend:: metal:: MetalExternalImage::s et(__CVBuffer*) in libbackend.a(MetalExternalImage.mm.o)
      filament:: backend:: metal:: MetalExternalImage:: set(__CVBuffer*, unsigned long) in libbackend.a(MetalExternalImage.mm.o)
  "_CVPixelBufferGetHeightOfPlane", referenced from:
      filament:: backend:: metal:: MetalExternalImage:: set(__CVBuffer*) in libbackend.a(MetalExternalImage.mm.o)
      filament:: backend:: metal:: MetalExternalImage:: set(__CVBuffer*, unsigned long) in libbackend.a(MetalExternalImage.mm.o)
  "_CVMetalTextureGetTexture", referenced from:
      filament:: backend:: metal:: MetalExternalImage::set(__CVBuffer*) in libbackend.a(MetalExternalImage.mm.o)
      filament:: backend:: metal::MetalExternalImage:: getMetalTextureForDraw() const in libbackend.a(MetalExternalImage.mm.o)
  "_OBJC_CLASS_$_MTLDepthStencilDescriptor", referenced from:
      objc-class-ref in libbackend.a(MetalState.mm.o)
  "_OBJC_CLASS_$_MTLCompileOptions", referenced from:
      objc-class-ref in libbackend.a(MetalHandles.mm.o)
      objc-class-ref in libbackend.a(MetalBlitter.mm.o)
  "_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
      objc-class-ref in libbackend.a(MetalDriver.mm.o)
      objc-class-ref in libbackend.a(MetalHandles.mm.o)
      objc-class-ref in libbackend.a(MetalContext.mm.o)
      objc-class-ref in libbackend.a(MetalExternalImage.mm.o)
  "_CVBufferRetain", referenced from:
      filament:: backend:: metal:: MetalExternalImage:: getMetalTextureForDraw() const in libbackend.a(MetalExternalImage.mm.o)
  "_OBJC_CLASS_$_MTLRenderPassDescriptor", referenced from:
      objc-class-ref in libbackend.a(MetalDriver.mm.o)
      objc-class-ref in libbackend.a(MetalBlitter.mm.o)
  "_OBJC_CLASS_$_MTLCaptureManager", referenced from:
      objc-class-ref in libbackend.a(MetalDriver.mm.o)
  "_OBJC_CLASS_$_MTLVertexDescriptor", referenced from:
      objc-class-ref in libbackend.a(MetalState.mm.o)
  "_OBJC_CLASS_$_MTLSharedEventListener", referenced from:
      objc-class-ref in libbackend.a(MetalDriver.mm.o)
  "_CVMetalTextureCacheCreateTextureFromImage", referenced from:
      filament:: backend:: metal:: MetalExternalImage:: set(__CVBuffer*) in libbackend.a(MetalExternalImage.mm.o)
      filament:: backend:: metal:: MetalExternalImage:: set(__CVBuffer*, unsigned long) in libbackend.a(MetalExternalImage.mm.o)
  "_CVPixelBufferRelease", referenced from:
      filament:: backend:: metal:: MetalDriver::cancelExternalImage(void*) in libbackend.a(MetalDriver.mm.o)
      filament:: backend:: metal:: MetalExternalImage::s et(__CVBuffer*) in libbackend.a(MetalExternalImage.mm.o)
      ____ZN8filament7backend5metal18MetalExternalImage3setEP10__CVBuffer_block_invoke in libbackend.a(MetalExternalImage.mm.o)
      filament:: backend:: metal:: MetalExternalImage::set(__CVBuffer*, unsigned long) in libbackend.a(MetalExternalImage.mm.o)
  "_OBJC_CLASS_$_MTLRenderPipelineDescriptor", referenced from:
      objc-class-ref in libbackend.a(MetalState.mm.o)
  "_CVBufferRelease", referenced from:
      filament :: backend: : metal::MetalExternalImage::set(__CVBuffer*) in libbackend.a(MetalExternalImage.mm.o)
      ____ZN8filament7backend5metal18MetalExternalImage3setEP10__CVBuffer_block_invoke in libbackend.a(MetalExternalImage.mm.o)
      filament : : backend :: metal ::MetalExternalImage::set(__CVBuffer*, unsigned long) in libbackend.a(MetalExternalImage.mm.o)
      std::__1::__function::__func<filament :: backend :: metal::$_1, std::__1::allocator<filament :: backend :: metal::$_1>, void (void const*)>::operator()(void const*&&) in libbackend.a(MetalExternalImage.mm.o)
  "_CVPixelBufferRetain", referenced from:
      filament :: backend :: metal:: MetalDriver::setupExternalImage(void*) in libbackend.a(MetalDriver.mm.o)
      filament :: backend :: metal:: MetalExternalImage:: getMetalTextureForDraw() const in libbackend.a(MetalExternalImage.mm.o)
  "_OBJC_CLASS_$_MTLSamplerDescriptor", referenced from:
      objc-class-ref in libbackend.a(MetalState.mm.o)
  "_MTLCreateSystemDefaultDevice", referenced from:
      filament: : backend:: metal:: MetalDriver:: MetalDriver(filament :: backend::MetalPlatform*) in libbackend.a(MetalDriver.mm.o)
  "_CVMetalTextureCacheCreate", referenced from:
      filament :: backend:: metal:: MetalDriver::MetalDriver(filament :: backend: :MetalPlatform*) in libbackend.a(MetalDriver.mm.o)
  "_CVMetalTextureCacheFlush", referenced from:
      filament :: backend:: metal:: MetalDriver::endFrame(unsigned int) in libbackend.a(MetalDriver.mm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by romainguy** [comment]
Why do you need `setClearColor`? We have equivalent APIs in newer versions. We've made many fixes to the Metal backend since 1.5.

**Comment by Pankaj003** [comment]
@romainguy 
Hi, I am using setClearColor api to set the background color and also to set the transparency while saving the file using offscreen rendering. Is the latest version v1.9.0 compatible with macOS10.14.6, Xcode11.3.1, MacOSX10.15.sdk?
Or which version do you suggest?

**Comment by romainguy** [comment]
Yes it should work. Our target version is macOS 10.14.

**Comment by bejado** [comment]
@Pankaj003, I am able to build Filament 1.5.2 using the MacOSX10.15.sdk without any issues.

I am using `Apple clang version 11.0.3 (clang-1103.0.32.62)`, the version released alongside Xcode 11.6.

I recommend deleting and re-creating your CMake build directory:

```
rm -rf cmake-build
mkdir cmake-build && cd cmake-build
cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15
ninja
```

If you have multiple Xcode versions installed, use `xcode-select -p` to see which one is "active".

**Comment by Pankaj003** [comment]
@bejado 
Hi, I am also able to build the Filament and sample applications. I was missing CoreVideo framework in my application which was the reason for some of the linker errors. I checked the  filament sample application on the machine where my app is not working and sample applications like suzzane and basic triangle one are working. So the issue is with my app only. 
Do you have any suggestion, what could be going wrong with Filament rendering from my application. Rendering is fine on some of the machines and on other it just shows black screen. Do I need to include few more frameworks?

**Comment by bejado** [comment]
I don't think that would be caused by any missing frameworks. On the machines that show a black screen, I think you mentioned it works when not using Qt?
