### ISSUE TITLE
Callback reference delete errors

### ISSUE THREAD

**Issue by rawnsley** [google/filament#3089]
I'm getting some jobject / DeleteGlobalRef related errors that I think are due to the [mHandler and mCallback](https://github.com/google/filament/blob/main/android/common/CallbackUtils.h#L51) fields not being initialized as [they are here](https://github.com/google/filament/blob/main/android/filament-android/src/main/cpp/Texture.cpp#L549).

I think it falls over when it calls [DeleteGlobalRef on the uninitialized pointers](https://github.com/google/filament/blob/main/android/common/CallbackUtils.cpp#L44).

I can put more detail around this if required and I'm waiting for a compilation to confirm, but this looks wrong to me.

**Comment by romainguy** [comment]
They are not initialized but the only constructor sets them. It could be a copy/move gone wrong (but we delete those constructors) or a caller passing bogus data.

**Comment by rawnsley** [comment]
I'll try and narrow down the cause and give you more details.

**Comment by rawnsley** [comment]
Actually I think it might be the members of the [`CallbackJNI` struct](https://github.com/google/filament/blob/main/android/common/CallbackUtils.h#L26). In the case where a texture doesn't have a callback, `acquireCallbackJni` is never called and those fields are not initialized. Then when the corresponding call to `releaseCallbackJni` is invoked in` ~AutoBitmap` the fields can contain random data like this:

```
... JNI ERROR (app bug): accessed stale WeakGlobal 0x76697463  (index 124163910 in a table of size 55)
... java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: use of deleted weak global reference 0x76697463
... java_vm_ext.cc:570]     from void com.google.android.filament.Renderer.nRender(long, long)
```
If I initialize all the members of `CallbackJNI` with zero this problem goes away.

**Comment by romainguy** [comment]
Right that makes more sense. I'll prepare a fix, thanks!

**Comment by romainguy** [comment]
Fixed, thank you!
