### ISSUE TITLE
GLES 3.0/3.1 confusion in our implementation

### ISSUE THREAD

**Issue by romainguy** [google/filament#309]
Filament requires OpenGL ES 3.0 only but in `gl_headers.h` we assert on the fact that OpenGL ES 3.1 headers are present. In addition, MSAA only works with OpenGL ES 3.1 as currently implemented. We should fallback on the extension when running on 3.0 hardware.

**Comment by pixelflinger** [comment]
I'm looking at this.

**Comment by pixelflinger** [comment]
Okay so actually requiring the ES31 headers is correct. We should always include the most recent headers so that we can use ES31 features (such as MSAA) natively. In the future we might even require ES32 headers. However, we must MAKE SURE that we're running on an ES30 implementation.
