### ISSUE TITLE
 When using filament to draw a line, it will flash and you can check the effect in the video。

### ISSUE THREAD

**Issue by shlzxjp** [google/filament#3095]
When using Filament to draw a line, the line will flash。
![ezgif-1-34f9b442427f](https://user-images.githubusercontent.com/8434971/93557273-2a25cc00-f9ad-11ea-8e95-40527639d1f1.gif)

**Comment by romainguy** [comment]
That’s because of dithering and fxaa together. You’ll need to use TAA instead or disable dithering.

**Comment by shlzxjp** [comment]
The anti-aliasing effect of taa is very good, the lines will not flicker, but there will be residual and fuzzy problems on the screen.

![image](https://user-images.githubusercontent.com/8434971/93738458-66a93000-fc18-11ea-8ec2-6ffa49bb98fa.png)
