### ISSUE TITLE
libfilament-jni.so', missing and no known rule to make it

### ISSUE THREAD

**Issue by steven-gao** [google/filament#3098]
**Describe the bug**

I run the sample-hello-camera occurs error,the log is ,please help me ,thank you 
 Build command failed.
Error while executing process /Users/wh-gaotaiwen/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/wh-gaotaiwen/Desktop/ar-pro/filament-main/android/filament-android/.cxx/cmake/debug/arm64-v8a filament-jni}
ninja: Entering directory `/Users/wh-gaotaiwen/Desktop/ar-pro/filament-main/android/filament-android/.cxx/cmake/debug/arm64-v8a'

ninja: error: '/Users/wh-gaotaiwen/Desktop/ar-pro/filament-main/out/android-release/filament/lib/arm64-v8a/libfilament.a', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libfilament-jni.so', missing and no known rule to make it

**To Reproduce**
1.cd filament-main/build/android 
2. invoke "./build.sh release"
3 run sample-hello-camera

**Expected behavior**
the app is run successfuly
**Screenshots**
![截屏2020-09-19 下午11 04 33](https://user-images.githubusercontent.com/4360916/93670254-ab27b500-facc-11ea-99f9-e68d155c6f1d.png)

**Desktop (please complete the following information):**
macOs 10.15.6 (19G2021)
 - GPU: [e.g. NVIDIA GTX 1080]
Intel HD Graphics 6000 1536 MB
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
huawei mate20
 - OS: [e.g. Android Pie 9.0]
android 10
**Additional context**

**Comment by romainguy** [comment]
Please refer to BUILDING.md for instructions. This script is for CI only. Use the root build.sh instead.
