### ISSUE TITLE
error: use of undeclared identifier 'SREV_TAM'

### ISSUE THREAD

**Issue by Nand2com** [google/filament#3102]
**Describe the bug**
I try to load a material but I get an error with the following expression in android studio:

static constexpr uint8_t DEFAULT_MATERIAL_PACKAGE [] = {

     #include "Assets/materials/aiDefaultMat.filamat"
};

The error I get is: "error: use of undeclared identifier 'SREV_TAM'"
SREV_TAM is the first string that appears in the aiDefaultMat.filamat file.

**To Reproduce**

I use the matc tool and the aiDefaultMat.mat material that comes in the examples to create aiDefaultMat.filamat, I try to load the material and it gives me an error. I am using c ++("-std=c++17").

**Expected behavior**
I think the error is due to the fact that the version of c ++ that I am using does not recognize the expression "#include" to load the material file.

**Additional context**

The operating system is OSX Catalina

**Comment by romainguy** [comment]
You can't do it this way. When you invoke matc you need to use `-f header` to produce a file that can be included in a C++ file. This is not the preferred way of loading materials. Instead you should just read them like normal binary files.

**Comment by Nand2com** [comment]
Very grateful for the answer, I have followed examples and I have only seen that way. I will try read them like normal binary files.
