### ISSUE TITLE
How to Add "#version 430 compatibility"  in opengl backend material ?

### ISSUE THREAD

**Issue by bitTalk1** [google/filament#3106]

**Comment by romainguy** [comment]
Why do you need to add this? You'd have to modify the filamat library to achieve this.

**Comment by bitTalk1** [comment]
thanks.
I try to add one 3rd party lib that using gl_TexCoord for texture.

**Comment by romainguy** [comment]
That's old-style GL and we don't support this. You can modify Filament yourself if you wish though.

**Comment by romainguy** [comment]
(If you want to do so look inside CodeGenerator.cpp in libs/filamat).
