### ISSUE TITLE
Is it possible to port the c ++ code samples to Android without much change?

### ISSUE THREAD

**Issue by Nand2com** [google/filament#3117]
Hello, I have a question about filament. I am trying to run an example of c ++ in android, I get error in the libraries; #include <filamentapp / Config.h> and #include <filamentapp / FilamentApp.h>. I do not know if this is not possible because it is android or there is an option that I am missing when I build filament or there is simply a way to obtain a similar functionality in android to be able to port these codes without many changes to Android.

Thx.

**OS and backend**
osx 10.15.6 
Android

**Comment by romainguy** [comment]
Porting the samples wouldn't be difficult but you can't use FilamentApp as is. It's meant to be used on desktop. I recommend you start with our Android samples.

**Comment by Nand2com** [comment]
Thanks, this clarifies me much more. I will try to continue without FilamentApp.
