### ISSUE TITLE
How to render a video to a Node?

### ISSUE THREAD

**Issue by steven-gao** [google/filament#3118]
**Is your feature request related to a problem? Please describe.**

Hello every one ,Before sceneform 1.16.0 version ,i was used chroma_key_video.sfb to create a renderable for puting a video node. But in 1.16.0 version ,still use this format will crash. 

the error trace is follows :
 2020-09-18 17:36:34.033 15587-15587/com.whyhow.sucailib E/Filament: in static filament::MaterialParser 

*filament::details::FMaterial::createParser(backend::Backend, const void *, size_t):493

    reason: could not parse the material package

my code is :
` ModelRenderable.builder().setSource(activity, R.raw.chroma_key_video)
                .build()
                .thenAccept(
                        { renderable ->
                            renderable.material.setExternalTexture("videoTexture", texture)
                            renderable.material.setFloat4("keyColor", Color(0.1843f, 1.0f, `0.098f))`
                            if (!mediaPlayer.isPlaying) {
                                mediaPlayer.start()
                                texture.surfaceTexture.setOnFrameAvailableListener { surfaceTexture: SurfaceTexture ->
                                            texture.surfaceTexture.setOnFrameAvailableListener(null)
                                            this.renderable = renderable
                                        }
                            }
                        })`

**Describe the solution you'd like**
i want to know how to use filament rendering video to a node.

**Describe alternatives you've considered**
Is it compatible with the sfb format rendering model？
I would be very grateful to you for making these compatible
**OS and backend**
android 10 ,arcore v1.16.0 ,sceneform v1.16.0,filament v1.7.0 

Looking forward to your reply

**Comment by romainguy** [comment]
This is a Sceneform question, not Filament. It seems like sfb files are not supported anymore? Filament itself does not know what an sfb file is.

**Comment by steven-gao** [comment]
I'm sorry to bother you
