### ISSUE TITLE
What is the minimal OpenGL version supported

### ISSUE THREAD

**Issue by Maria098** [google/filament#3136]
Hello!
We are using Filament 1.6 in our product on Mac and Windows.
Customer is inquiring regarding minimal computer requirements.
Is it correct to state that OpenGL 4.1+ should be installed on the machine?

thank you!

**Comment by prideout** [comment]
Yes, the minimum requirement for macOS and Windows is OpenGL 4.1.

One quick way of double-checking this is by typing chrome://gpu into your Chrome browser and searching for GL_VERSION.
