### ISSUE TITLE
gltfio: Create additional FilamentInstances dynamically

### ISSUE THREAD

**Issue by FabianRueckert** [google/filament#3137]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/google/filament/issues/1513, which introduced asset instance creation.
However the current API only allows creating instances when the asset is first loaded, i.e. the number of instances has to be known from the beginning. 

```
 filamentAsset = assetLoader.createInstancedAsset(buffer, filamentInstances)
```

This is not sufficient in our application, as we want to load the asset into memory and then allow the user to place and delete instances dynamically without having to load the asset into memory again and without having a fixed number of instances allocated from the beginning.

**Describe the solution you'd like**

I would like to have an API that allows me to create and destroy additional asset instances from a FilamentAsset dynamically.

It could work like this:
```
filamentAsset = assetLoader.createInstancedAsset(buffer)

// ... time passes...

filamentInstance = assetLoader.createInstance(filamentAsset)
```

```
assetLoader.destroyInstance(filamentAsset, filamentInstance)
```

**Comment by prideout** [comment]
I think this is a reasonable request and we should be able to enhance gltfio to allow for this.  I can look into it soon.

**Comment by prideout** [comment]
This is almost ready.  It is tricky because it breaks assumptions that currently exist in the internal dependency graph that is used for asynchronous loading.

**Comment by FabianRueckert** [comment]
Thank you!
Will the Animator be supported on a newly created instance?

**Comment by prideout** [comment]
@FabianRueckert In my current PR, the `createInstance` docstring warns users that animation is not supported on dynamically added instances.  That's a feature that I can add as a follow up if you need it.  It would require some refactoring of how the skinning data is stored.

**Comment by FabianRueckert** [comment]
> @FabianRueckert In my current PR, the `createInstance` docstring warns users that animation is not supported on dynamically added instances. That's a feature that I can add as a follow up if you need it. It would require some refactoring of how the skinning data is stored.

@prideout Yes, animation support would be great. Thank you.

**Comment by FabianRueckert** [comment]
@prideout Could you look into animation support for these dynamically created instances? Without animators, these dynamically created instances are not usable for us.

**Comment by prideout** [comment]
Sorry for the delay, I will take a look at this today.
