### ISSUE TITLE
Immediate mode rendering

### ISSUE THREAD

**Issue by jeanleflambeur** [google/filament#3140]
**Is your feature request related to a problem? Please describe.**
Is there any way - or plan - to do immediate mode rendering?

**Describe the solution you'd like**
I'd like to be able to render a vertex + index buffer with a certain material without having to add them to a scene as a rendarable.
The use case are CPU particles, debug primitives or any volatile data that changes per frame.

**Describe alternatives you've considered**
Right now the only way that I've found and the way I've seen used in ImGUI is to create a renderable and add it to a scene.
This cannot be optimal for volatile data and makes lifetime management a bit tricker for fire-and-forget draw calls.

**Comment by romainguy** [comment]
This is not something we want to support. You can reuse a renderable a upload its days every frame.

**Comment by jeanleflambeur** [comment]
Got it. Thanks a lot!
