### ISSUE TITLE
Lights flicker when a certain distance away.

### ISSUE THREAD

**Issue by jeanleflambeur** [google/filament#3141]
**Describe the bug**
When lights are far enough, they begin to flicker, exposing the froxel structure.
My guess is that there is uninitialized froxel data or the froxel - light volume has an issue when the lights approach some distance.

**To Reproduce**
Place lights (point or spot) far away from the camera (around 100m away).

**Screenshots**
Expected behaviour (lights < 100m away)
![image](https://user-images.githubusercontent.com/10252034/94747898-557ec280-0380-11eb-9486-6e4ba04fcc33.png)

Current Behaviour (lights >= 100m away)
![image](https://user-images.githubusercontent.com/10252034/94747840-33854000-0380-11eb-8ffa-1c4cc102ef3c.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - GPU: NVIDIA GTX 1050ti
 - Backend: OpenGL

**Comment by romainguy** [comment]
100m is the default distance where lights get culled. You can change the the far parameter of the camera to change that. The depth buffer uses a far at infinity always.

**Comment by jeanleflambeur** [comment]
I've seen this, yes. I was expecting the lights to simply dissapear beyond the far distance but there is this limbo zone where they start flickering until I zoom out a few meters more. This causes visual issues in my scene, but I could work around it by doing the culling myself.

I added a few bugs now and totally forgot to mention: amazing job with filament. I've rarely seen code this clean and nice and cozy. It's a pleasure to use the engine and browse through the header files. It's like reading a good book! Thanks a lot for spending so much time on this, the effort definitely shows.

**Comment by romainguy** [comment]
Pushing the far plane should help. The flickering likely happens when light are at the boundary of the froxels volume. Thanks for the bug reports btw it's super helpful!

**Comment by jeanleflambeur** [comment]
Is there any side-effect to having a further far plane? I guess the froxels stretch a bit more so potentially there are more lights per froxel, right?
Not an issue in my case, just curious.

**Comment by romainguy** [comment]
The froxels will be bigger and we use an exponential spread so it's really the farther ones that will grow the most. But they should also cover fewer pixels to shade. Ideally we would have a built-in way to replace lights beyond the far plane with additive sprites or something.
