### ISSUE TITLE
Lights get clipped at certain angles

### ISSUE THREAD

**Issue by jeanleflambeur** [google/filament#3142]
**Describe the bug**
Sometimes, at certain angles parts of lights are missing. Most probably cause seems to be the froxel - light volume intersection, because it looks like the light is not assigned to some froxels so the shader doesn't use it.

**To Reproduce**
One light over a plane. Light intensity: 100000 W LED, 12m Falloff (smaller falloff distance amplifies the problem), 50m away from the camera.
The camera viewing angle makes this more or less visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/10252034/94748138-e786cb00-0380-11eb-963a-a49a37ad2f24.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - GPU: NVIDIA GTX 1050 ti
 - Backend: OpenGL

**Comment by romainguy** [comment]
Do you have a test we can run to repro? Note that this can happen if your light radius is too small for the intensity.

**Comment by jeanleflambeur** [comment]
Unfortunately no, as it's part of a bigger project. To repro this though I ended up with a floor (a 10x10x1m box) and a light setup as in the bug description.
If needed, I can spend some time to setup one of the samples to repro this.

I did notice the bug more with smaller falloff distances - which is consistent with what you mention. But I think (just a guess) that this happens with lights with bigger falloffs, just that it's less noticeable as the light fades out way further away from the edge and the bugg is always at the edge (hope it makes sense).

**Comment by romainguy** [comment]
Well the radius is what we use to know which froxels to assign a light to. So if the radius doesn't cover the full extended of what the light lights you can get what you see. We may have a bug on our side though but it's good to first make sure your radius isn't too small. That's where a visual editor would be super helpful :/

**Comment by pixelflinger** [comment]
I *think* this is a real bug because the radius should always "win", that is, it forces the intensity to 0 at the radius distance (it's not physically correct though).
