### ISSUE TITLE
MaterialInstance lifetime issue

### ISSUE THREAD

**Issue by jeanleflambeur** [google/filament#3143]
**Describe the bug**
There seem to be a lifetime issue with MaterialInstances assigned ro renderables.

**To Reproduce**
Change the MaterialInstance material instance of a renderable per frame, destroying the previous one.
This causes either the object to flip to a default material - in my case causing the object to flicker to black - or a crash.

Holding on to the previous material until the next frame fixes the issue.
I think that the render thread needs those materials alive while it's rendering, or has some dangling pointers to the deleted materials.

**Desktop (please complete the following information):**
 - OS: Win10
 - GPU: NVIDIA GTX 1050 ti
 - Backend: OpenGL

**Comment by romainguy** [comment]
A MaterialInstance is effectively a UBO, so it is indeed needed while the frame is rendering.

**Comment by jeanleflambeur** [comment]
Got it.
For how long should I keep it alive though? 
In my case I deleted the old material instance between Renderer::beginFrame and endFrame, so I'm guessing that during this time the previous frame is potentially submitted on another thread.
So I guess I should keep them alive for 3 frames (for triple buffering) + one extra frame due to threaded submission of draw calls, right?
Should I use a fence to detect for certain when the gpu iss done with a MaterialInstance or it's overkill?

**Comment by romainguy** [comment]
A fence could help but @pixelflinger can answer this better than I can. Ideally however you should reuse the instance. If you don't change the base material you can set new parameters and that'll be cheaper.

**Comment by romainguy** [comment]
I wonder if we could/should provide a simple utility function for this (`scheduleDestroy()`). @pixelflinger, any take on this?
