### ISSUE TITLE
Crash from libfilament-jni.so after upgrade to Android 11

### ISSUE THREAD

**Issue by Sheng-Xuan** [google/filament#3148]
**Describe the bug**
Random crash happens during my ARcore session, not always happening, no special action to trigger it.

**To Reproduce**
1. run my app with arcore 1.17 + sceneform 1.16.0 + filament 1.8.0 or 1.8.1

**Expected behavior**
Do not crash

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 11

**Additional context**
This is the tombstone of this crash: https://gist.github.com/Sheng-Xuan/8b3b659642a8941d14eb99a99fdd2165
The backtrace only has one line and I can't get more no matter what.
Have not tried filament 1.9.2 yet as I am not sure how to rebuild material file.

My app was running without any crash before upgrading to Android 11.

Thanks!

**Comment by romainguy** [comment]
Please try with 1.9.2, we have fixed a JNI bug. To rebuild the material file just use `matc` from the 1.9.2 release for your host operating system.

**Comment by Sheng-Xuan** [comment]
After upload to 1.9.2 seems to be fine so far, close issue first. Thanks for the support!
