### ISSUE TITLE
Rendering artifacts in WebGL on Chrome

### ISSUE THREAD

**Issue by dellisd** [google/filament#3151]
**Describe the bug**
WebGL rendering appears to be broken in Chrome(?) on desktop. The output image has artifacts everywhere and flickers.

My graphics drivers are all up to date, and as far as I can tell this only happens in Chrome. The demos work fine in Edge for instance and they also work normally in Chrome on Android.

**To Reproduce**
1. Open WebGL tutorials or demo in Chrome on desktop (v85.0.4183.121) (e.g. https://google.github.io/filament/webgl/suzanne.html)

**Expected behavior**
The demo should be rendered normally

**Screenshots**
![image](https://user-images.githubusercontent.com/6743693/94928378-97e3f480-0491-11eb-8389-a2cc8459dad2.png)
![image](https://user-images.githubusercontent.com/6743693/94928415-a6321080-0491-11eb-8c6d-0acfb60a999b.png)
![image](https://user-images.githubusercontent.com/6743693/94928554-dda0bd00-0491-11eb-83af-57ce211f6291.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA RTX 2070 Super
 - Backend: WebGL

**Additional context**
No errors appear in the console.

**Comment by prideout** [comment]
Thanks for the bug report!  This might be a Windows-only issue, I'm using the same version of Chrome on macOS but I do not see this.

**Comment by dellisd** [comment]
I noticed that the knotess demo works normally for me, not sure what version of filament that uses compared to the others.

**Comment by bejado** [comment]
I'm unable to reproduce on Windows with an older NVIDIA GTX 970 (same version of Chrome).

**Comment by dellisd** [comment]
I reached out to some friends who have a few other different GPUs to see if the issue occurs for them too (all on Windows):

|GPU|Artifacts?|
|----|----|
| 2070 Super | Yes |
| 2070 | Yes |
| 1060 | No |
| 1650 | No |

_Note: this is a different 2070 Super_

So if I had to guess right now it seems to only happen with RTX cards?

**Comment by dellisd** [comment]
A bit more digging and it turns out that the artifacts only occur when using the D3D11 backend for ANGLE in Chrome. Switching the backend to OpenGL or D3D11on12 allows the demos to render fine.

**Comment by prideout** [comment]
Interesting, thanks for digging deeper!  This bug should perhaps be reported to NVIDIA.

**Comment by cx20** [comment]
I'm having the same issue with a `Windows 10` + `Chrome 90` + `GeForce RTX 2060` environment.
The following was displayed on the console.

> [.WebGL-000014380033B500]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, Medium): You could get a better shader compiling performance if you re-write the uniform block(s)
> [ FrameUniforms ]
> in the FRAGMENT shader.
> You could get more details from https://chromium.googlesource.com/angle/angle/+/refs/heads/master/src/libANGLE/renderer/d3d/d3d11/UniformBlockToStructuredBufferTranslation.md

For now, it seems to display correctly in the `Firefox 88` environment.

**Comment by cx20** [comment]
I tested it again in several browsers.
Perhaps `Chrome 92.0.4491.6` or later has resolved this issue.

|GPU|OS|Browser|result|
|:----:|:----:|:----|:----:|
|GeForce RTX 2060|Windows 10|Chrome 90.0.4430.93|:x:|
|GeForce RTX 2060|Windows 10|Chrome 92.0.4491.6 (Dev)|:white_check_mark:|
|GeForce RTX 2060|Windows 10|Chrome 92.0.4494.0 (Canary)|:white_check_mark:|
|GeForce RTX 2060|Windows 10|Edge 90.0.818.51 (Chrome 90.0.4430.93)|:x:|
|GeForce RTX 2060|Windows 10|Edge 92.0.873.1 (Dev) (Chrome 92.0.4474.0)|:x:|
|GeForce RTX 2060|Windows 10|Edge 92.0.874.0 (Canary) (Chrome 92.0.4482.0)|:x:|

**Comment by pixelflinger** [comment]
not actionable / gpu/driver specific

**Comment by 1226085293** [comment]
When will this problem be solved? When I saw the filament demo a year ago it was the same, and a year later it was the same

<img width="1399" height="372" alt="Image" src="https://github.com/user-attachments/assets/7e48cf3b-848c-4456-9671-b2e523dba79c" />
