### ISSUE TITLE
Rotate object dynamically.

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#3152]
Hi there, is there any way to Rotate Object dynamically?  
Here are some step which I want to achieve
1. Initially my model loads with below position

![image](https://user-images.githubusercontent.com/24297327/94951337-b8e42e00-0501-11eb-9024-ce136b889a76.png)

but I want to rotate it like the below screenshot programmatically (left facing instead of right-facing). 

![image](https://user-images.githubusercontent.com/24297327/94951647-4fb0ea80-0502-11eb-870e-39d833a7cb3a.png)

I used, manipulator, to achieve the above functionality

like below

manipulator = Manipulator.Builder()
            .targetPosition(0.0f, 0.0f, -4.0f)
            .orbitHomePosition(0f, 0.0f, -1.25f)
            .viewport(mySurfaceView.width, mySurfaceView.height)
            .build(Manipulator.Mode.ORBIT)

modelViewer = ModelViewer(mySurfaceView, engine, manipulator)

but seems like it's not that much properly positioned. 

also, I want to reset it to 2nd step position(left facing), Is that possible?

Any help will be highly appreciated. Thank you.

**Comment by chiragchauhan1073** [comment]
I tried using transform Manager as below.
 modelViewer.transformToUnitCube(Float3(0f, 0.of, -4f))
but it makes no effect.

**Comment by romainguy** [comment]
That is not transform manager. This is only to scale the object. Check out the samples to see how to use transform manager.

**Comment by chiragchauhan1073** [comment]
Okay, but when i try to set transform like below code. my model disappear from screen,
        engine.transformManager.setTransform(engine.transformManager.getInstance(mesh.renderable),
                floatArrayOf(
                        1.0f,  0.0f, 0.0f, 0.0f,
                        0.0f,  1.0f, 0.0f, 0.0f,
                        0.0f,  0.0f, 1.0f, 0.0f,
                        0.0f, -1.2f, 0.0f, 1.0f
                ))

**Comment by chiragchauhan1073** [comment]
Also, I do not want to move it, as the current transform does.

**Comment by chiragchauhan1073** [comment]
My model will be steady at one place. user can rotate 180 degree. but instead of right facing, it will front facing.

**Comment by romainguy** [comment]
You create a translation transform, you'll need to create a rotation transform to achieve what you want. You can use the `Mat4` class from the `filament-utils` library to help you create correct transform matrices.

**Comment by chiragchauhan1073** [comment]
Okay, I did checked samples but did not found any relevant code for this, it will be very helpful if you post sample code for rotation transform

**Comment by romainguy** [comment]
https://github.com/google/filament/blob/main/android/samples/sample-hello-triangle/src/main/java/com/google/android/filament/hellotriangle/MainActivity.kt#L236

**Comment by chiragchauhan1073** [comment]
Okay, so far, I tried the following code. but still no luck with it.

 ```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupViewModel()

        setupFilament()
        initFilament()
    }

 private fun setupFilament() {
        choreographer = Choreographer.getInstance()
        engine = Engine.create()
    }

  /**
     * Initialize filament and Start loading Model
     */
    private fun initFilament() {

        //To change the height and width of object
        manipulator = Manipulator.Builder()
            .targetPosition(0f, 0.0f, -4.0f)
            .orbitHomePosition(0f, 0f, -1.25f)
            .viewport(mySurfaceView.width, mySurfaceView.height)
            .build(Manipulator.Mode.ORBIT)

        modelViewer = ModelViewer(mySurfaceView, engine)

        createRenderables()
        createIndirectLight()

        mySurfaceView.setOnTouchListener { _, event ->
            modelViewer.onTouchEvent(event)
            true
        }
    }

 private fun createIndirectLight() {
        val scene = modelViewer.scene
        val ibl = "venetian_crossroads_2k"

        viewLifecycleOwner.lifecycleScope.launch {
            val byteBuffer = readCompressedAsset("envs/$ibl/${ibl}_ibl.ktx")
            scene.indirectLight = KtxLoader.createIndirectLight(engine, byteBuffer)
            scene.indirectLight!!.intensity = 30_000.0f
        }

        viewLifecycleOwner.lifecycleScope.launch {
            val byteBuffer = readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx")
            scene.skybox = KtxLoader.createSkybox(engine, byteBuffer)
        }

        scene.skybox = Skybox.Builder().color(01f, 01f, 01f, 01f).build(engine)

        modelViewer.transformToUnitCube(Float3(0f, 0f, -4f))

         //Trying this code to rotate the object
         val transformMatrix = FloatArray(16)
         android.opengl.Matrix.setRotateM(transformMatrix, 0, 0.55f, 0.0f, 0.0f, 1.0f)
         val tcm = engine.transformManager
         tcm.setTransform(tcm.getInstance(modelViewer.asset?.root!!), transformMatrix)
      }

     private fun createRenderables() {
     viewLifecycleOwner.lifecycleScope.launch {

            val  assetsName = "models/CUSTOMFX_FX870_ANDROID_ASSET.gltf"

            val byteBuffer = readCompressedAsset(assetsName)

            modelViewer.loadModelGltfAsync(byteBuffer) { uri -> readCompressedAsset("models/$uri") }
      }

 private fun readCompressedAsset(assetName: String): ByteBuffer {
        val input = activity?.assets?.open(assetName)
        val bytes = ByteArray(input?.available()!!)
        input.read(bytes)
        return ByteBuffer.wrap(bytes)
    }

inner class FrameCallback : Choreographer.FrameCallback {
        private val startTime = System.nanoTime()
        override fun doFrame(frameTimeNanos: Long) {
            choreographer.postFrameCallback(this)
            modelViewer.animator?.apply {
                if (animationCount > 0) {
                    val elapsedTimeSeconds =
                        (frameTimeNanos - startTime).toDouble() / 1_000_000_00000000000
                    applyAnimation(0, elapsedTimeSeconds.toFloat())
                }
                updateBoneMatrices()
            }

            modelViewer.render(frameTimeNanos)
        }
    }
}
```

**Comment by romainguy** [comment]
You are rotating by 0.5 degree. Please check the documentation:
https://developer.android.com/reference/android/opengl/Matrix#setRotateM(float[],%20int,%20float,%20float,%20float,%20float)

**Comment by chiragchauhan1073** [comment]
okay but if i use any of above values. my model starts rotating inside whole screen, like user drag model by its touch.
but I want it on specific position on screen. and just rotate

**Comment by chiragchauhan1073** [comment]
It is possible to make a model positioned at a specific position? and just rotate from right to left ?

**Comment by chiragchauhan1073** [comment]
![Uploading testmodel.gif…]()
This is what i achieved after 
android.opengl.Matrix.setRotateM(transformMatrix, 0, 0.55f, 0.0f, 0.0f, 1.0f)

**Comment by romainguy** [comment]
By using `setRotateM` you are overriding the translation you specified just before with `modelViewer.transformToUnitCube(Float3(0f, 0f, -4f))`. You can use the other `Matrix` APIs to do both a rotation and translation. And again your rotation is only 0.5 degree, I don't expect you'll see much on screen.

**Comment by chiragchauhan1073** [comment]
So how can i get only rotation, not translation

**Comment by chiragchauhan1073** [comment]
![testmodel](https://user-images.githubusercontent.com/24297327/95358722-fd4b4180-08e6-11eb-9108-87ea16d3cb5c.gif)

**Comment by chiragchauhan1073** [comment]
This is how it behaves currently

**Comment by romainguy** [comment]
You can get both, see the Matrix APIs, you can combine transforms in a single matrix.

**Comment by shivammaindola** [comment]
I'm doing it like this and it worked

` modelViewer.transformToUnitCube()

        val localMatrix = FloatArray(16)
        modelViewer.engine.transformManager.getTransform(modelViewer.asset?.root!!, localMatrix)

        val rotateMatrix = FloatArray(16)
        Matrix.setRotateM(rotateMatrix, 0, 0F, 0.0f, 0.0f, 1.0f)

        val resultMatrix = FloatArray(16)
        Matrix.multiplyMM(resultMatrix, 0, rotateMatrix, 0, localMatrix, 0)

        val tcm = modelViewer.engine.transformManager
        tcm.setTransform(tcm.getInstance(modelViewer.asset?.root!!), rotateMatrix)
`

**Comment by kishore5304** [comment]
Hi @romainguy I am also working on android filament. I have a glb model. I need to rotate the model without moving the position. The center axis of the model should be filed. I need to change the rotation alone of the entire model programatically. What I need to do? Please suggest me some suggestions on this. There is a lack of examples for filament rotation. So Its hard to understand the rotation.

**Comment by Y0urLocalCatboy** [comment]
Have you guys found the solution yet? It's weird how complicated it seems

**Comment by chiragchauhan1073** [comment]
Hey @Y0urLocalCatboy @kishore5304, Somehow, I was able to set up the Object as per my requirement. Let me know your exact requirements So I can help.

**Comment by Y0urLocalCatboy** [comment]
Hello there @chiragchauhan1073 may I ask you how? It seems like every rotation function I use changes the axis of rotation instead of the starting angle

**Comment by chiragchauhan1073** [comment]
Using Manipulator Object. @Y0urLocalCatboy Here is the sample code i used. 
`  manipulator = Manipulator.Builder()
                    .targetPosition(0.0f, 0.0f, -4.0f)
                    .orbitHomePosition(0f, 0.0f, -1.25f)
                    .viewport(binding.mySurfaceView.width, binding.mySurfaceView.height)
                    .build(Manipulator.Mode.ORBIT)`

**Comment by chiragchauhan1073** [comment]
and then i used manipulator instance to create ModelViewer as below

`        modelViewer = ModelViewer(binding.mySurfaceView, manipulator = manipulator)
`

**Comment by lamhoang28** [comment]
how to set initial view to coordinates 0 0 0 plssss

**Comment by Churchil-Oduor** [comment]
Hi same here, I am using transform manager to  do the transformation and only included the Rotation component and left out the translation bit. The image rotates but some translation occurs.
            val modelEntity = modelViewer.asset?.root ?: return
            val tm = modelViewer.engine.transformManager
            val inst = tm.getInstance(modelEntity)
            val  matrix = FloatArray(16)

            val rotationMatrix = floatArrayOf(
                0f, 0f, 1f, 0f,
                0f, 1f, 0f, 0f,
                -1f, 0f, 0f, 0f,
                0f, 0f, 0f, 1f
            )
            
            tm.setTransform(inst, rotationMatrix)
            modelViewer.render(currentTime)

**Comment by Churchil-Oduor** [comment]
Found a solution!! 
Filanent changes everything when you tamper with the Rotation matrix. To solve this...get the current translation component and feed it to the transform matrix before applying the transformation. as follows:

              val modelEntity = modelViewer.asset?.root ?: return
                        val tm = modelViewer.engine.transformManager
                        val inst = tm.getInstance(modelEntity)
                        val  current = FloatArray(16)
                        tm.getTransform(inst, current)

            val rotationMatrix = floatArrayOf(
                0f, 0f, 1f, 0f,
                0f, 1f, 0f, 0f,
                -1f, 0f, 0f, 0f,
                current[12], current[13], current[14], 1f
            )

            tm.setTransform(inst, rotationMatrix)
            modelViewer.render(currentTime)

With this approach, you get to retain the initial traslation as you manipulate the Rotation.
