### ISSUE TITLE
Shadow is jagged

### ISSUE THREAD

**Issue by SGTjeong** [google/filament#3158]
![shadow](https://user-images.githubusercontent.com/57657823/95032876-18575f00-06f7-11eb-8d29-b45c48d825c6.png)

Hi,

The shadow within the red circle came out jagged. Is there a way to smoothe it out?

It gets worse especially on animated models.

**Comment by romainguy** [comment]
That's because your light is directly overhead. You can change the light direction to improve the result. You can also change the shadow map resolution and/or play with the view's shadow options to adapt the scale and bias.

**Comment by romainguy** [comment]
With recent versions of filament you can also try VSM shadows which may work better (but more expensive).
