### ISSUE TITLE
Filament Issue when compiling using 1.9.2

### ISSUE THREAD

**Issue by HemanParbhakar** [google/filament#3159]
**Describe the bug**
**Error : Panic in static filament::MaterialParser *filament::FMaterial::createParser(backend::Backend, const void *, size_t):512
    reason: Material version mismatch. Expected 10 but received 7.**
Version 
    **Androd:**
    api 'com.google.android.filament:filament-android:1.9.2'
    api 'com.google.android.filament:gltfio-android:1.9.2'
    implementation files("../libs/libsceneform_runtime_schemas.jar")
    api "com.google.ar:core:1.19.0"
   **Filament version compiled with**
     1.9.2
     matc --version
      10
**To Reproduce**
1. Created a mat file using
material {
	name : "Occlusion material",
	shadingModel : unlit,
	colorWrite : false,
	depthWrite : true
}

fragment {
	void material(inout MaterialInputs material) {
		prepareMaterial(material);
		material.baseColor = vec4(0.0);
	}
}
2. Compile the mat file using 

matc -p mobile -a opengl -o output.filamat input.mat
--
3. Then set the model using: 
Renderable renderable;
        ModelRenderable.builder()
                .setSource(
                        this,
                        Uri.parse(
                                "https://storage.googleapis.com/ar-answers-in-search-models/static/Tiger/model.glb"))
                .setIsFilamentGltf(true)
                .build()
                .thenAccept(
                        modelRenderable -> {
                                renderable = modelRenderable;
                                com.google.ar.sceneform.rendering.Material.builder()
                                        .setSource(
                                                getApplicationContext(),
                                                R.raw.output
                                        )
                                        .build()
                                        .thenAccept(new Consumer<Material>() {
                                            @Override
                                            public void accept(Material material) {
                                                renderable.setMaterial(material);
                                            }
                                        });
                                
                        })
                .exceptionally(
                        throwable -> {
                            Toast toast =
                                    Toast.makeText(this, "Unable to load Tiger renderable", Toast.LENGTH_LONG);
                            toast.setGravity(Gravity.CENTER, 0, 0);
                            toast.show();
                            return null;
                        });
    }
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Android 10
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
You are passing Filament an older material file. Make sure you recompile all your materials.

**Comment by HemanParbhakar** [comment]
i have recompiled it again still same

**Comment by romainguy** [comment]
It must be another material

**Comment by HemanParbhakar** [comment]
no its same i have only one material

**Comment by HemanParbhakar** [comment]
Also how to set this material priority above then that of camera.

**Comment by romainguy** [comment]
If you are using Sceneform you will probably need to recompile the materials used by Sceneform internally.

**Comment by HemanParbhakar** [comment]
i have already recompile then given the path of the .filamat file

**Comment by HemanParbhakar** [comment]
on using the 1.7.1 version the element does not perform occulsion.

**Comment by HemanParbhakar** [comment]
@romainguy I guess there is no use of adding our issues over here. As most of the time either it is went unanswered or un noticed.
