### ISSUE TITLE
Leaking resource causes crash on exit using Vulkan backend in 1.9.2

### ISSUE THREAD

**Issue by nmcveity** [google/filament#3166]
**Describe the bug**
Leaking resource causes crash (by assertion failure) on exit using Windows with Vulkan backend in 1.9.2. 

The assert that fails is in `VulkanDisposer::reset()`

`assert(mDisposables.empty());`

**To Reproduce**
1. Create Engine, SwapChain and Renderer
2. Destroy Renderer, SwapChain and Engine

**Expected behavior**
No asserts on exit.

**Additional context**
The problem was created with pull request #3073. A dummy texture array is created in PostProcessManager:227 but it not destroyed in the PostProcessManager::terminate call.

**Comment by romainguy** [comment]
Thanks for the report!

**Comment by bejado** [comment]
Thank you!
