### ISSUE TITLE
Add option to set output directory for material compiler

### ISSUE THREAD

**Issue by Consti10** [google/filament#3169]
It is quite time consuming to compile a bunch of materials with the matc tool. And since they have to be recompiled with each release,you have to do that quite often.
I'd suggest the option to specify an output directory, and optionally also an input directory.
Example command:

matc  ./materials/src/car_paint.mat -od ./compiled_materials

Would generate a file called car_paint.filamat in compiled_materials

Also, having to specify the full filename (also the suffix) can lead to confusion.

The sceneform example names the compiled materials .matc instead of .filamat - I do not think that was intended.

**Comment by Consti10** [comment]
Here is a simple windows script I created as workaround:
```
@ECHO OFF
ECHO Compiling all materials

SET MATC_INPUT_DIRECTORY=..\sceneformMaterials\
SET MATC_OUTPUT_DIRECTORY=..\src\main\res\raw\
SET MATC_EXE_DIRECTORY=v1_7_0\
REM START matc.exe -o %MATC_OUTPUT_DIRECTORY%sceneform_camera_material.filamat %MATC_INPUT_DIRECTORY%sceneform_camera_material.mat ^>test.txt
ECHO %MATC_INPUT_DIRECTORY%
ECHO %MATC_OUTPUT_DIRECTORY%

SETLOCAL ENABLEDELAYEDEXPANSION
for %%f in (%MATC_INPUT_DIRECTORY%*.mat) do (
	REM ECHO Hello from loop
	SET FILENAME=%%~nf
	REM echo %%~nf
    ECHO !FILENAME!
	START %MATC_EXE_DIRECTORY%matc.exe -o %MATC_OUTPUT_DIRECTORY%!FILENAME!.filamat %MATC_INPUT_DIRECTORY%!FILENAME!.mat 
)

ECHO Done compiling all materials

PAUSE

```

**Comment by romainguy** [comment]
You can use any file extension you want, `.filamat` is only a convention. `.matc` is fine too. `matc` is intended to be used like any other compiler, you can check our samples to see how we use it from Gradle to automate this process. I'm not sure how setting an output directory would simplify the problem that much since you still need to iterate over the source files.

**Comment by bejado** [comment]
> And since they have to be recompiled with each release

Note that our goal is to only require recompiling materials when we bump the middle version number. So 1.9.2 -> 1.9.3, for example, should not require any material recompilation.
