### ISSUE TITLE
Question : How to Handle shadow and lighting.

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#3174]
Hello, I am facing one lighting-related issue here.
the lights on the model are not in applying evenly. how to handle this lighting issue. 
![lighting](https://user-images.githubusercontent.com/24297327/95455040-e4946780-098a-11eb-9c5f-278fe38f3740.gif)

**Comment by romainguy** [comment]
There's nothing "wrong" with your lighting. It looks like you are using a lighting setup that's not uniform. What lights do you use?

**Comment by chiragchauhan1073** [comment]
i am applying only indirect light intensity like below

```
private fun createIndirectLight() {
        val scene = modelViewer.scene
        val ibl = "venetian_crossroads_2k"

        viewLifecycleOwner.lifecycleScope.launch {
            val byteBuffer = readCompressedAsset("envs/$ibl/${ibl}_ibl.ktx")
            scene.indirectLight = KtxLoader.createIndirectLight(engine, byteBuffer)
            scene.indirectLight!!.intensity = 60_000.0f
        }

        viewLifecycleOwner.lifecycleScope.launch {
            val byteBuffer = readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx")
            scene.skybox = KtxLoader.createSkybox(engine, byteBuffer)
        }

        scene.skybox = Skybox.Builder().color(01f, 01f, 01f, 01f).build(engine)
    }
```

**Comment by romainguy** [comment]
Then just use a different environment map. venetian_crossroads_2k contains a strong directional light from the sun. You've also set a very high intensity (double what would normally work for that env map with the default exposure)>

**Comment by chiragchauhan1073** [comment]
okay so how can i get environment ?, i need grey background like above image. is it possible to set grey background without setting up skybox

**Comment by romainguy** [comment]
You can create your own and use `cmgen` to compile it for use with Filament, or download one online (look for "HDRI" or "IBL" images, for instance from hdrihaven.com).
