### ISSUE TITLE
about headless rendering

### ISSUE THREAD

**Issue by ohouha** [google/filament#3176]
Can I build filament for headless rendering, like building in docker?

**Comment by romainguy** [comment]
You can build Filament with SwiftShader support (with the `-t` argument when calling `build.sh`). You can also use headless OpenGL rendering if you have a software implementation like Mesa installed for instance. You can also create headless swap chains in the Filament API (using `Engine::createSwapChain(width, height)`).

**Comment by ohouha** [comment]
"You can also use headless OpenGL rendering if you have a software
implementation like Mesa installed for instance." If I want to use this
one, what should I do? should I change something in the cmake file?
Thanks.
Regards,
-Wanyan

Romain Guy <notifications@github.com> 于2020年10月8日周四 下午2:47写道：
