### ISSUE TITLE
Crash on  void filament::FEngine::flushAndWait():390

### ISSUE THREAD

**Issue by geroge-d** [google/filament#3179]
Hi guys
  We met a random crash on android using the latest version. The printed log below:

10-10 18:23:11.625 21606 22150 E Filament: Panic
--
17510-10 18:23:11.625 21606 22150 E Filament: in void filament::FEngine::flushAndWait():390
17610-10 18:23:11.625 21606 22150 E Filament: reason: flushAndWait() failed inexplicably after 2s
17710-10 18:23:11.625 21606 22150 E Filament:

GPU info:
PowerVR Rogue GE8320,vendor:Imagination Technologies,version:OpenGL ES 3.2 build 1.9@4971894  
Device:
![2333](https://user-images.githubusercontent.com/53041249/95654555-527b9300-0b33-11eb-8025-d11f1d4672f0.jpg)

**Comment by geroge-d** [comment]
Another Device found crash logs:  HuaWei ARS AL00

**Comment by romainguy** [comment]
Please provide the full logs. Ideally capturing a systrace when it happens would be very useful. There's not much we can do with the information provided.

**Comment by pixelflinger** [comment]
"reason: flushAndWait() failed inexplicably after 2s" this if concerning.

This is the check we put in to detect destroy calls from the wrong thread.
However, this specific assert shouldn't happen, even in that case (I think).

**Comment by geroge-d** [comment]
this issue occurs on OOM
