### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by jkvargas** [google/filament#3180]
Hi, I am having issues to build the project.
Using manjaro and clang here to build.
Manjaro: 5.8.11-1-MANJARO
and clang: 
clang version 10.0.1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

` ✘ vargasj@vargasj  ~/dev/filament   main  ./build.sh -p desktop -q x86_64 debug 
Warning: JAVA_HOME is not set, skipping Java projects
Building debug in out/cmake-debug...
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang
-- DFG LUT size set to 128x128
-- Found Python3: /usr/bin/python3.8 (found version "3.8.5") found components: Interpreter 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vargasj/dev/filament/out/cmake-debug
[1/1232] Building CXX object libs/camutils/CMakeFiles/camutils.dir/src/Bookmark.cpp.o
FAILED: libs/camutils/CMakeFiles/camutils.dir/src/Bookmark.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/camutils/include -I../../libs/math/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -Wno-deprecated-register -MD -MT libs/camutils/CMakeFiles/camutils.dir/src/Bookmark.cpp.o -MF libs/camutils/CMakeFiles/camutils.dir/src/Bookmark.cpp.o.d -o libs/camutils/CMakeFiles/camutils.dir/src/Bookmark.cpp.o -c ../../libs/camutils/src/Bookmark.cpp
In file included from ../../libs/camutils/src/Bookmark.cpp:17:
In file included from ../../libs/camutils/include/camutils/Bookmark.h:20:
In file included from ../../libs/math/include/math/vec2.h:20:
In file included from ../../libs/math/include/math/TVecHelpers.h:20:
../../libs/math/include/math/compiler.h:19:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 error generated.
[2/1232] Building CXX object libs/camutils/CMakeFiles/camutils.dir/src/Manipulator.cpp.o
FAILED: libs/camutils/CMakeFiles/camutils.dir/src/Manipulator.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/camutils/include -I../../libs/math/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -Wno-deprecated-register -MD -MT libs/camutils/CMakeFiles/camutils.dir/src/Manipulator.cpp.o -MF libs/camutils/CMakeFiles/camutils.dir/src/Manipulator.cpp.o.d -o libs/camutils/CMakeFiles/camutils.dir/src/Manipulator.cpp.o -c ../../libs/camutils/src/Manipulator.cpp
In file included from ../../libs/camutils/src/Manipulator.cpp:17:
In file included from ../../libs/camutils/include/camutils/Manipulator.h:20:
In file included from ../../libs/camutils/include/camutils/Bookmark.h:20:
In file included from ../../libs/math/include/math/vec2.h:20:
In file included from ../../libs/math/include/math/TVecHelpers.h:20:
../../libs/math/include/math/compiler.h:19:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 error generated.
[3/1232] Building CXX object libs/filaflat/CMakeFiles/filaflat.dir/src/ChunkContainer.cpp.o
FAILED: libs/filaflat/CMakeFiles/filaflat.dir/src/ChunkContainer.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/math/include -I../../filament/backend/include -I../../third_party/smol-v/tnt/../source -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -fvisibility=hidden -MD -MT libs/filaflat/CMakeFiles/filaflat.dir/src/ChunkContainer.cpp.o -MF libs/filaflat/CMakeFiles/filaflat.dir/src/ChunkContainer.cpp.o.d -o libs/filaflat/CMakeFiles/filaflat.dir/src/ChunkContainer.cpp.o -c ../../libs/filaflat/src/ChunkContainer.cpp
In file included from ../../libs/filaflat/src/ChunkContainer.cpp:17:
In file included from ../../libs/filaflat/include/filaflat/ChunkContainer.h:25:
../../third_party/robin-map/tnt/../tsl/robin_map.h:28:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
[4/1232] Building CXX object libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerBindingMap.cpp.o
FAILED: libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerBindingMap.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/filabridge/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/math/include -I../../filament/backend/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector -MD -MT libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerBindingMap.cpp.o -MF libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerBindingMap.cpp.o.d -o libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerBindingMap.cpp.o -c ../../libs/filabridge/src/SamplerBindingMap.cpp
In file included from ../../libs/filabridge/src/SamplerBindingMap.cpp:17:
In file included from ../../libs/filabridge/include/private/filament/SamplerBindingMap.h:22:
../../third_party/robin-map/tnt/../tsl/robin_map.h:28:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
[5/1232] Building CXX object libs/filabridge/CMakeFiles/filabridge.dir/src/UibGenerator.cpp.o
FAILED: libs/filabridge/CMakeFiles/filabridge.dir/src/UibGenerator.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/filabridge/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/math/include -I../../filament/backend/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector -MD -MT libs/filabridge/CMakeFiles/filabridge.dir/src/UibGenerator.cpp.o -MF libs/filabridge/CMakeFiles/filabridge.dir/src/UibGenerator.cpp.o.d -o libs/filabridge/CMakeFiles/filabridge.dir/src/UibGenerator.cpp.o -c ../../libs/filabridge/src/UibGenerator.cpp
In file included from ../../libs/filabridge/src/UibGenerator.cpp:17:
In file included from ../../libs/filabridge/include/private/filament/UibGenerator.h:20:
In file included from ../../libs/math/include/math/mat4.h:20:
../../libs/math/include/math/compiler.h:19:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 error generated.
[6/1232] Building CXX object libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerInterfaceBlock.cpp.o
FAILED: libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerInterfaceBlock.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/filabridge/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/math/include -I../../filament/backend/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector -MD -MT libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerInterfaceBlock.cpp.o -MF libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerInterfaceBlock.cpp.o.d -o libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerInterfaceBlock.cpp.o -c ../../libs/filabridge/src/SamplerInterfaceBlock.cpp
In file included from ../../libs/filabridge/src/SamplerInterfaceBlock.cpp:17:
In file included from ../../libs/filabridge/include/private/filament/SamplerInterfaceBlock.h:21:
In file included from ../../filament/backend/include/backend/DriverEnums.h:22:
../../libs/utils/include/utils/BitmaskEnum.h:22:10: fatal error: 'type_traits' file not found
#include <type_traits> // for std::false_type
         ^~~~~~~~~~~~~
1 error generated.
[7/1232] Building CXX object libs/filabridge/CMakeFiles/filabridge.dir/src/SibGenerator.cpp.o
FAILED: libs/filabridge/CMakeFiles/filabridge.dir/src/SibGenerator.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/filabridge/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/math/include -I../../filament/backend/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector -MD -MT libs/filabridge/CMakeFiles/filabridge.dir/src/SibGenerator.cpp.o -MF libs/filabridge/CMakeFiles/filabridge.dir/src/SibGenerator.cpp.o.d -o libs/filabridge/CMakeFiles/filabridge.dir/src/SibGenerator.cpp.o -c ../../libs/filabridge/src/SibGenerator.cpp
In file included from ../../libs/filabridge/src/SibGenerator.cpp:17:
In file included from ../../libs/filabridge/include/private/filament/SibGenerator.h:21:
In file included from ../../filament/backend/include/backend/DriverEnums.h:22:
../../libs/utils/include/utils/BitmaskEnum.h:22:10: fatal error: 'type_traits' file not found
#include <type_traits> // for std::false_type
         ^~~~~~~~~~~~~
1 error generated.
[8/1232] Building CXX object libs/filabridge/CMakeFiles/filabridge.dir/src/UniformInterfaceBlock.cpp.o
FAILED: libs/filabridge/CMakeFiles/filabridge.dir/src/UniformInterfaceBlock.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/filabridge/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/math/include -I../../filament/backend/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector -MD -MT libs/filabridge/CMakeFiles/filabridge.dir/src/UniformInterfaceBlock.cpp.o -MF libs/filabridge/CMakeFiles/filabridge.dir/src/UniformInterfaceBlock.cpp.o.d -o libs/filabridge/CMakeFiles/filabridge.dir/src/UniformInterfaceBlock.cpp.o -c ../../libs/filabridge/src/UniformInterfaceBlock.cpp
In file included from ../../libs/filabridge/src/UniformInterfaceBlock.cpp:17:
In file included from ../../libs/filabridge/include/private/filament/UniformInterfaceBlock.h:20:
In file included from ../../filament/backend/include/backend/DriverEnums.h:22:
../../libs/utils/include/utils/BitmaskEnum.h:22:10: fatal error: 'type_traits' file not found
#include <type_traits> // for std::false_type
         ^~~~~~~~~~~~~
1 error generated.
[9/1232] Building CXX object libs/camutils/CMakeFiles/test_camutils.dir/tests/test_camutils.cpp.o
FAILED: libs/camutils/CMakeFiles/test_camutils.dir/tests/test_camutils.cpp.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/camutils/include -I../../libs/math/include -I../../third_party/libgtest/tnt/../googletest/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -pthread -MD -MT libs/camutils/CMakeFiles/test_camutils.dir/tests/test_camutils.cpp.o -MF libs/camutils/CMakeFiles/test_camutils.dir/tests/test_camutils.cpp.o.d -o libs/camutils/CMakeFiles/test_camutils.dir/tests/test_camutils.cpp.o -c ../../libs/camutils/tests/test_camutils.cpp
In file included from ../../libs/camutils/tests/test_camutils.cpp:17:
In file included from ../../libs/camutils/include/camutils/Bookmark.h:20:
In file included from ../../libs/math/include/math/vec2.h:20:
In file included from ../../libs/math/include/math/TVecHelpers.h:20:
../../libs/math/include/math/compiler.h:19:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 error generated.
[10/1232] Building CXX object third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o
FAILED: third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o 
/usr/bin/clang++ -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../third_party/libgtest/tnt/../googletest/include -I../../third_party/libgtest/tnt/../googletest -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -pthread -MD -MT third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o -MF third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o.d -o third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o -c ../../third_party/libgtest/googletest/src/gtest-all.cc
In file included from ../../third_party/libgtest/googletest/src/gtest-all.cc:38:
../../third_party/libgtest/tnt/../googletest/include/gtest/gtest.h:55:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.`

Also, I could find /usr/include/c++/10.2.0/type_traits for example in my system, but the file does not end with .h.
The same happens for cstddef, what am I missing?
Thanks.

**Comment by romainguy** [comment]
Those files are not supposed to end in .h so that's fine. It seems like you may not have libc++-dev installed for your compiler.

**Comment by jkvargas** [comment]
hey romain, even if I have the files in /usr/include/c++/10.2.0 ?

**Comment by romainguy** [comment]
I don’t know what that version maps to. Your compiler is 10.0.1 which isn’t the same version.
