### ISSUE TITLE
BlendingMode and alpha effect problem

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#3181]
![image](https://user-images.githubusercontent.com/4098790/95714917-896cb880-0c9b-11eb-8df0-0a5de2044607.png)
The effect is as follows：
![image](https://user-images.githubusercontent.com/4098790/95714951-9d181f00-0c9b-11eb-8841-9ce8a285a27a.png)

why the plane is not white? Can you give me some hints？

**Comment by cjsliuj** [comment]
and the render cleanr color is:  {1,1,1, 1}

**Comment by romainguy** [comment]
If you want to render color exactly as is you need to disable tone mapping or use the inverse tone mapping shader functions (see materials documentation). Tone mapping can be disabled via the ColorGrading API.
