### ISSUE TITLE
Is backend supported stencil?

### ISSUE THREAD

**Issue by raochp** [google/filament#3182]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**OS and backend**
Is this feature OS/backend specific? If so, explain why.

**Comment by romainguy** [comment]
Stencil buffers are currently not supported.

**Comment by raochp** [comment]
Is there a plan to support it?

**Comment by raochp** [comment]
hi,  Is there a plan to support it? @romainguy

**Comment by romainguy** [comment]
Eventually most likely yes, it's not a priority at the moment though :/
