### ISSUE TITLE
Crash while creating renderables when reloading new heavy 3D object - Mac

### ISSUE THREAD

**Issue by Pankaj003** [google/filament#3183]
Hi,
The issue relate to Mac OS, Xcode11.3, filamentv1.6.0
I am loading a fbx file and in some of the cases it is crashing at below code.

RenderableManager::Builder builder(1);
                builder.boundingBox(rm.aabb)
                    .material(0, mat)
                    .geometry(0, RenderableManager::PrimitiveType::TRIANGLES, rm.vb, rm.ib, 0, rm.indexCount)
                    .culling(false)
                    .castShadows(true)
                    .receiveShadows(true)
                    //.blendOrder()
                    //.priority(rm.mPriority)
                    ;
                auto res = builder.build(*mEngine, renderable);

I've got the below crash stack:
**0   com.adobe.illustrator.plugins.AI3D 0x000000011c1aaece filament::OpenGLDriver::allocateHandle(unsigned long) + 142
1   com.adobe.illustrator.plugins.AI3D 0x000000011c1ab24e filament::OpenGLDriver::createUniformBufferS() + 14**

We thought this might be buffer allocation issue and modified the Allocators.h file from TNT project. This is what we did
**static constexpr size_t CONFIG_PER_RENDER_PASS_ARENA_SIZE = 32 * 1024 * 1024;
static constexpr size_t CONFIG_PER_FRAME_COMMANDS_SIZE = 16 * 1024 * 1024;
static constexpr size_t CONFIG_MIN_COMMAND_BUFFERS_SIZE = 16 * 1024 * 1024;
static constexpr size_t CONFIG_COMMAND_BUFFERS_SIZE = 48 * CONFIG_MIN_COMMAND_BUFFERS_SIZE;**

I am loading one fbx file after another using same engine, view and scene instances and cleaning up the renderables, renderable meshes, materials and textures before each loading. 
Any idea what could be going wrong?
Could you please point us to any sample code where we are loading multiple files(one after another and one at a time) and cleaning and reusing same engine, renderer and scene.

Thanks,
Pankaj

**Comment by romainguy** [comment]
Does increasing the allocation sizes fix your issue? If not, then that's a different problem. Note that these allocations only matter for the duration of a frame, usually they would cause an issue when rendering with **many** objects, not with a 1 large one. Have you tried with a more recent version of Filament too?

**Comment by romainguy** [comment]
BTW: with recent versions of Filament you can override those allocation sizes directly using environment variables when compiling Filament.

**Comment by Pankaj003** [comment]
No, buffer size increase hasn't fixed the problem. I haven't tried with any other version of Filament. We are using same Engine,  SwapChain and renderer for each file load just cleaning the materials, renderable, textures etc.. Do we need to create new instance of the Engine and Renderer for new 3D object? Or are we missing any cleanup?

**Comment by romainguy** [comment]
No you don't need to clean up anything. Is there more to the stack trace? I wonder if it's because you didn't clean up the material instances. You can definitely reuse Engine/Scene/Renderer/View/etc.

**Comment by Pankaj003** [comment]
we are cleaning the material instances. Below is the code snippet of what we are cleaning up before setting up the scene
for (auto mat_texs : mTextures) {
        if (mat_texs.albedo)
            mEngine->destroy(mat_texs.albedo);
        if (mat_texs.normalMap)
            mEngine->destroy(mat_texs.normalMap);
        if (mat_texs.aoMap)
            mEngine->destroy(mat_texs.aoMap);
        if (mat_texs.specMap)
            mEngine->destroy(mat_texs.specMap);
        if (mat_texs.maskMap)
            mEngine->destroy(mat_texs.maskMap);
    }
    mTextures.clear();

 for (filament::MaterialInstance* mat : mMaterialInstances) {
        mEngine->destroy(mat);
    }
    mMaterialInstances.clear();

for (RenderMesh& rm : mRenderMeshes) {
        mEngine->destroy(rm.vb);
        mEngine->destroy(rm.ib);
    }
    mRenderMeshes.clear();

for (utils::Entity e : mRenderables) {
        mScene->remove(e);

        mEngine->destroy(e);

        // destroy entities themselves
        utils::EntityManager::get().destroy(e);
    }
    mRenderables.clear();

I am downloading filamentv1.9.3 and see if it works. But looks like many things have been deprecated in this version and api to create View, SwapChains have been changed.

**Comment by romainguy** [comment]
Ah I see you are not cleaning the `Material` themselves, which probably means their default `MaterialInstance` is still around.

All the things that have been deprecated have been replaced with other APIs. The main change is how to clear/set a background clear color (basically you use a `Skybox` now to draw a clear color in the background).

**Comment by prideout** [comment]
Quick side note: one strategy for finding leaks is to use a debug version of Filament, and quit your application normally after a few reloads; you might see a message like: `cleaning up 3 leaked filament::FMaterial`

**Comment by Pankaj003** [comment]
do I need to call mEngine->destroy(mMaterial); everytime before setting the new scene and create new Material?
We are initializing the material as mMaterial =
        filament::Material::Builder().package(RESOURCES_TRANSPARENT_DATA, RESOURCES_TRANSPARENT_SIZE)
        .build(*mEngine);

**Comment by prideout** [comment]
For every call to `build(...)`, there should be a corresponding call to `destroy(...)`.

**Comment by romainguy** [comment]
You only need to destroy the material if you don't use it anymore. If you are going to reload the same material, just keep it around and create new instances instead. From `package(RESOURCES_TRANSPARENT_DATA, RESOURCES_TRANSPARENT_SIZE)` it seems you are using the same material, so don't destroy it.

**Comment by Pankaj003** [comment]
Attached complete crash log. Please have a look and let me know if it gives any clue...
[Crash.rtf.zip](https://github.com/google/filament/files/5366348/Crash.rtf.zip)

**Comment by Pankaj003** [comment]
Hi,

I am facing different issues related to the Filament library usage, may be I am missing something basic.
I am collating issues below for general discussion.

1. Off-Screen rendering:
I’ve created a sample application in which I am using two swap chains. One for onscreen rendering associated with native window and other for offscreen rendering for file saving. I’ve created a test application and both the swap chains are working as expected.
But when I used the same code in one of our Adobe illustrator plugin app, I am getting black output with offscreen rendering.
I am suspecting that Adobe Illustrator has also created some rendering instances and it may be limiting the rendering resource allocation?
Is there a way we can switch the context between onScreen and offScreen swapChains/rendering?

2. I am using OpenGL backend, I tried using Metal backend but getting the crash with the message that material is not created for Metal framework. 
I’ve compiled material resource using below steps
cmgen -x outFolder -f ktx hdrfile.hdr
matc -o "transparent.filamat" "transparent.mat"
resgen -qc -p resources transparent.filamat skybox.ktx ibl.ktx

Do I need to use some flag to compile the material for Metal backend?

3. I am loading a 3D object(fbx file) which has over 1million vertices and more than 10000 renderable. While building the renderables, filament is crashing in OpengGL driver handle allocation. I’ve increased the buffer size as below but it doesn’t have any impact, it prevented the crash on Windows OS.
static constexpr size_t CONFIG_PER_RENDER_PASS_ARENA_SIZE    =  32 * 1024 * 1024; 
static constexpr size_t CONFIG_PER_FRAME_COMMANDS_SIZE = 16 * 1024 * 1024; 
static constexpr size_t CONFIG_MIN_COMMAND_BUFFERS_SIZE = 16 * 1024 * 1024; 
static constexpr size_t CONFIG_COMMAND_BUFFERS_SIZE     = 48 * CONFIG_MIN_COMMAND_BUFFERS_SIZE;

If I limit the number of  the renderables to 9900, I am able to prevent the crash but it’s also not loading the complete data.
Is there any limit for renderables?

Thanks,
Pankaj

**Comment by romainguy** [comment]
For 1: I don't understand what you mean by "Is there a way we can switch the context between onScreen and offScreen swapChains/rendering?". Filament will take care of this when you ask to render a frame into a swap chain.

For 2: By default matc generates shaders only for OpenGL (see `matc --help`). Use `matc -a metal …` to generate for metal (you can also use `matc -a all …` to generate for Vulkan, GL and Metal).

For 3: With a large number of renderables, yes you'll have to increase the size of those buffers. An alternative solution is to load the renderables over several frames to bypass this problem. It's something we definitely want to fix. That said, you may still run into allocations issue while drawing the scene if all 10,000 renderables are visible at the same time. Do you have 10,000 different materials? If not, it would be useful to merge as many renderables as possible for performance reasons (libraries like assimp can do it for you at load time).

**Comment by Pankaj003** [comment]
@romainguy Thanks for your reply. 
1. What could be possible reason for offScreenSwapChain creating/saving file with black output? Same code works fine in my test application. The only difference here is I am loading Filament inside Adobe Illustrator which already may be opening OpenGL/Metal resource handles. On screen swapchain and view are rendering correct data. So somehow either readPixels call is failing or I may need to reset/clear or flush some data...not sure...

3. I am using assimp to load the FBX file, I'll see if I can merge the renderables...Thanks for pointer

below is my implementation for saving the file using offscreen swapchain...do you see any issue which may be causing the black output issue:
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
void saveScreenshot(const QString &filepath, bool transparency, int w, int h)
{
    using namespace filament;
    using namespace std::chrono_literals;
    
    const bool transparent = true;
    int n_channels = transparent ? 4 : 3;
    auto dataformat = transparent ? backend::PixelBufferDescriptor::PixelDataFormat::RGBA : backend::PixelBufferDescriptor::PixelDataFormat::RGB;
    auto qimageformat = transparent ? QImage::Format_RGBA8888 : QImage::Format_RGB888;
    const Viewport& vp = mOffscreenView->getViewport();
    
    mCamManipulator.updateCamera(mMainCamera);
    
//    if transparent, change clear color to full alpha
    Renderer::ClearOptions new_clear_options = mClearOptions;
    if (transparent) {
        new_clear_options.clearColor[3] = 0.0;
    } else {
        new_clear_options.clearColor[3] = 1.0;
    }
    mRenderer->setClearOptions(new_clear_options);
    
    bool done = false;
    
    uint8_t* pixels = new uint8_t[vp.width * vp.height * n_channels];
    backend::PixelBufferDescriptor buffer(
                                          pixels,
                                          vp.width * vp.height * n_channels,
                                          dataformat,
                                          backend::PixelBufferDescriptor::PixelDataType::UBYTE,
                                          [](void* buffer, size_t size, void *capture_state) {
                                              CaptureState* state = static_cast<CaptureState*>(capture_state);
                                              const Viewport &v = state->view->getViewport();
                                              QImage img(reinterpret_cast<unsigned char*>(buffer), v.width, v.height, state->img_format);
                                             
                                              int dpm = 120 / 0.0254;
                                              img.setDotsPerMeterX(dpm);
                                              img.setDotsPerMeterY(dpm);
        
                                              img.save(state->filepath);
                                              
                                              // cleanup.
                                              delete[] static_cast<uint8_t*>(buffer);
                                              delete state;
                                              
                                              *(state->done) = true;
                                          }, new CaptureState{mView, filepath, qimageformat, w, h, &done});
    
    while (!mRenderer->beginFrame(mOffscreenSwapChain)) {
        std::this_thread::sleep_for(8ms);
    }
    mRenderer->render(mOffscreenView);
    mRenderer->readPixels(0, 0, vp.width, vp.height, std::move(buffer));
    mRenderer->endFrame();
    
    while (!done) {
        // Keep flushing the render buffer.  Filament requires the
        // command stream to execute while CPU bound operations are scheduled
        if (mRenderer->beginFrame(mOffscreenSwapChain)) {
            mRenderer->render(mOffscreenView);
            mRenderer->endFrame();
        }
        std::this_thread::sleep_for(8ms);
    }
    
    mRenderer->setClearOptions(mClearOptions);
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by romainguy** [comment]
Try doing `readPixels` *after* `endFrame()`.

**Comment by Pankaj003** [comment]
I already tried that...it produces same result

**Comment by pixelflinger** [comment]
There are many bugs/problems/discussions reported in this issue.  Please create a new issue per problem.
As it is now, nothing is actionable here.
