### ISSUE TITLE
Question : How to disable ibl reflection ?

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#3186]
can we disable ibl reflections? 
I am using the below hdr image as for lighting. 

https://hdrihaven.com/hdri/?h=phone_shop

I am facing one issue with it, my model has a chrome finish. so when i try to apply color on that. the model reflects an HDR image. attaching the screenshot below. 

![image](https://user-images.githubusercontent.com/24297327/95869979-98319900-0d89-11eb-916e-689f11e3c49e.png)

I want to disable reflection, it should look like the top part of the model. is there any way to handle this?

**Comment by chiragchauhan1073** [comment]
Okay, I tried to remove IndirectLight, but then it removes all lights from the scene.

**Comment by romainguy** [comment]
You can also create a solid color environment as your IBL. Or use an IBL that’s more abstract like studio lights.

**Comment by chiragchauhan1073** [comment]
Do i need to create a solid color environment programmatically ? or it refers to HDRI image?

**Comment by chiragchauhan1073** [comment]
@romainguy Do I need to create a solid color environment programmatically ? or it refers to HDRI image?

**Comment by romainguy** [comment]
You can do it either way. When you pass the data for the IBL texture you can just pass a bunch of constant floats (1.0 for instance to get white).
