### ISSUE TITLE
How to use the build files for web?

### ISSUE THREAD

**Issue by davidwarford** [google/filament#3194]
When you download the filament release for web you get a .js and .wasm files. However in my experience i have only ever had to deal with .bc files, how am I supposed to utilize this in a project?

**Comment by prideout** [comment]
The filament release for web is meant for web developers.  I believe `.bc` is one of the intermediary files generated by emscripten.

If you are a C++ developer who does not need our JavaScript API, and you instead wish to use an emscripten build of Filament, I think you'll need to build Filament yourself.  If you app uses CMake, you can declare a dependency to the core filament library, similar to what we do for our JavaScript bindings.  See the CMakeLists.txt in `web/filament-js` for inspiration.
