### ISSUE TITLE
i run sample-stream-test on my phone ,but nothing i can see . Is it correct?

### ISSUE THREAD

**Issue by steven-gao** [google/filament#3199]
**Describe the bug**
i run sample-stream-test on my phone ,but nothing i can see . Is it correct?

**To Reproduce**
1 run sample-stream-test

**Expected behavior**
i want to render a video to a scene
**Screenshots**
[https://user.qzone.qq.com/76132921/infocenter](url)

**Desktop (please complete the following information):**
 - OS:macos
 - GPU: 
 - Backend:

**Smartphone (please complete the following information):**
 - phone: huawei mate 20x
 - OS: Android  10

**Comment by prideout** [comment]
It should look like this screenshot:

https://github.com/google/filament/tree/main/android/samples#stream-test

Do you see any errors with logcat?  Have you tried `sample-hello-camera`?

**Comment by steven-gao** [comment]
> It should look like this screenshot:
> 
> https://github.com/google/filament/tree/main/android/samples#stream-test
> 
> Do you see any errors with logcat? Have you tried `sample-hello-camera`?

no, my canvas is black. i don't know how to upload sceenshot on this website.but i upload screenshot to QQ website :https://user.qzone.qq.com/76132921/infocenter

**Comment by steven-gao** [comment]
> It should look like this screenshot:
> 
> https://github.com/google/filament/tree/main/android/samples#stream-test
> 
> Do you see any errors with logcat? Have you tried `sample-hello-camera`?

I'm not see any error with logcat

**Comment by steven-gao** [comment]
on my phone like this :
![WechatIMG3](https://user-images.githubusercontent.com/4360916/100705536-4b119100-33e2-11eb-83d9-72d1fb733d98.jpeg)


> It should look like this screenshot:
> 
> https://github.com/google/filament/tree/main/android/samples#stream-test
> 
> Do you see any errors with logcat? Have you tried `sample-hello-camera`?
