### ISSUE TITLE
How to show only gltf model not the background part

### ISSUE THREAD

**Issue by shivammaindola** [google/filament#3208]
I want to render the gltf model with a transparent background in android-

the code is 

      ` surfaceView = SurfaceView(this);
        choreographer = Choreographer.getInstance()
        modelViewer = ModelViewer(surfaceView)
        surfaceView.setOnTouchListener(modelViewer)
        loadGltf("BusterDrone")
        loadEnvironment("venetian_crossroads_2k")

    }

    private fun loadEnvironment(ibl: String) {
        // Create the indirect light source and add it to the scene.
        var buffer = readAsset("envs/$ibl/${ibl}_ibl.ktx")
        KtxLoader.createIndirectLight(modelViewer.engine, buffer).apply {
            intensity = 100_000f
            modelViewer.scene.indirectLight = this

        }

        // Create the sky box and add it to the scene.
        buffer = readAsset("envs/$ibl/${ibl}_skybox.ktx")
        KtxLoader.createSkybox(modelViewer.engine, buffer).apply {
            //modelViewer.view.blendMode=View.BlendMode.TRANSLUCENT
            modelViewer.scene.skybox= Skybox.Builder().intensity(0f).color(0.0f, 0.0f, 0.0f, 0.0f).build(modelViewer.engine)
            //modelViewer.scene.skybox=null
        }
    }

    private fun loadGltf(name: String) {
        val buffer = readAsset("models/${name}.gltf")
        modelViewer.loadModelGltf(buffer) { uri -> readAsset("models/$uri") }
        modelViewer.transformToUnitCube()
    }

    private fun readAsset(assetName: String): ByteBuffer {
        val input = assets.open(assetName)
        val bytes = ByteArray(input.available())
        input.read(bytes)
        return ByteBuffer.wrap(bytes)
    }`

I'm getting the black background when I'm using this code in skybox
` modelViewer.scene.skybox= Skybox.Builder().intensity(0f).color(0.0f, 0.0f, 0.0f, 0.0f).build(modelViewer.engine)`

and twhen I'm using this code in skybox.
` modelViewer.view.blendMode=View.BlendMode.TRANSLUCENT
  modelViewer.scene.skybox=null`

I'm getting like this
![Screenshot_2020-10-21-11-18-24-514_com google android filament gltf (1)](https://user-images.githubusercontent.com/39567362/96693872-5f0ab180-13a5-11eb-9a01-c9de5a9567e2.jpg)

Please tell me how can I show the model without any background?

**Comment by romainguy** [comment]
You also need to make the `SurfaceView` transparent using `getHolder().setFormat(PixelFormat.TRANSLUCENT)`. The `SwapChain` also needs to be transparent. This is normally handled by our `UiHelper` API but `ModelViewer` hides this from you. We need to add a new parameter to `ModelViewer` so it sets everything up properly.

@prideout it should just be a matter of passing an extra boolean to `UiHelper`.

**Comment by shivammaindola** [comment]
@romainguy I did what you said but it made everything invisible(the 3D model also).

This is the code
```
choreographer = Choreographer.getInstance()
        modelViewer = ModelViewer(surfaceView)
        surfaceView.setOnTouchListener(modelViewer)

        loadGltf("scene")
        loadEnvironment("venetian_crossroads_2k")
        makeItInvisible()
    }

private fun makeItInvisible() {

    surfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT)
    uiHelper = UiHelper(UiHelper.ContextErrorPolicy.DONT_CHECK)
    uiHelper.renderCallback = SurfaceCallback()

    // Make the render target transparent
    uiHelper.isOpaque = false

    uiHelper.attachTo(surfaceView)

    val options = modelViewer.engine.createRenderer().clearOptions
    options.clear = true
    modelViewer.engine.createRenderer().clearOptions = options

}

 private fun loadEnvironment(ibl: String) {
        // Create the indirect light source and add it to the scene.
        var buffer = readAsset("envs/$ibl/${ibl}_ibl.ktx")
        KtxLoader.createIndirectLight(modelViewer.engine, buffer).apply {
            intensity = 100_000f
            modelViewer.scene.indirectLight = this
        }

        // Create the sky box and add it to the scene.
        buffer = readAsset("envs/$ibl/${ibl}_skybox.ktx")
        KtxLoader.createSkybox(modelViewer.engine, buffer).apply {
            modelViewer.view.blendMode=View.BlendMode.TRANSLUCENT
            //modelViewer.scene.skybox= Skybox.Builder().color(0.0f, 0.0f, 0.0f, 0.0f).build(modelViewer.engine)
            modelViewer.scene.skybox=null
        }
    }

```

**Comment by romainguy** [comment]
You can't use `ModelViewer` and `UiHelper` together, `ModelViewer` already creates a `UiHelper` for you. We need to add an option to `ModelViewer` or you need to bypass `ModelViewer` and load the glTF yourself. Here's the source code of `ModelViewer`, it's pretty simple and you can just copy/paste it in your app: https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt

**Comment by shivammaindola** [comment]
@romainguy I'm getting black background.
This is the code

`     

        modelViewer = ModelViewer3D(surfaceView)
        surfaceView.setOnTouchListener(modelViewer)
        modelViewer.makeItTransparent()
        loadGltf("scene")
        loadEnvironment("venetian_crossroads_2k")
        //surfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT)`

I've added one function in modelViewer

```
fun makeItTransparent() {
        uiHelper.isOpaque = false
        uiHelper.attachTo(surfaceView)
        val options = renderer.clearOptions
        options.clear = true
        renderer.clearOptions = options
    }

```

Still I'm getting black background not transparent.

Using this line also did not worked

`surfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT)`

**Comment by shivammaindola** [comment]
Finally, the issue has been solved.  I changed the makeItTransparent() to this 

 fun makeItTransparent() {
        val options = renderer.clearOptions
        options.clear = true
        renderer.clearOptions = options
    }

and added this `uiHelper.isOpaque = false` inside ModelViewer constructor

**Comment by memostark** [comment]
Does this work with glb files? I also created a custom `ModelViewer`, added `uiHelper.isOpaque = false` to the constructor, and call the `makeItTransparent()` function but the background is still black.

```
        surfaceView = SurfaceView(this)
        surfaceView.holder.setFormat(PixelFormat.TRANSLUCENT)

        val textView = TextView(this).apply {
            val d = resources.displayMetrics.density
            text = "This TextView is under the Filament SurfaceView."
            textSize = 32.0f
            setPadding((16 * d).toInt(), 0, (16 * d).toInt(), 0)
        }

        choreographer = Choreographer.getInstance()
        modelViewer = ModelViewerAlpha(surfaceView)
        surfaceView.setOnTouchListener(modelViewer)

        setUpModelViewer()
        createRenderables()
        createIndirectLight()
        modelViewer.makeItTransparent()

        setContentView(FrameLayout(this).apply {
            addView(textView, FrameLayout.LayoutParams(
                    FrameLayout.LayoutParams.MATCH_PARENT,
                    FrameLayout.LayoutParams.WRAP_CONTENT,
                    Gravity.CENTER_VERTICAL
            ))
            addView(surfaceView)
        })
```
Loading the glb model
```
private fun createRenderables() {
        val buffer = assets.open("mymodel.glb").use { input ->
            val bytes = ByteArray(input.available())
            input.read(bytes)
            ByteBuffer.wrap(bytes)
        }

        modelViewer.loadModelGlb(buffer)
        modelViewer.transformToUnitCube()
}
```
Also slightly related but the Android sample `sample-transparent-view` crashes on start

**Comment by romainguy** [comment]
You need your `SurfaceView` to be above your `Activity` or use a `TextureView` instead (like the sample does).

**Comment by memostark** [comment]
I copied the code from the sample (it has a `SurfaceView` and a `TextView`). As far as I can tell the [sample](https://github.com/google/filament/blob/61b154246813b3c6b29b8c23421c2dc6c6beb0ad/android/samples/sample-transparent-view/src/main/java/com/google/android/filament/transparentrendering/MainActivity.kt#L56) is using a `SurfaceView`, not a `TextureView`. What do you mean with being above the `Activity`?

**Comment by romainguy** [comment]
Sorry I forgot that UiHelper will automatically move the `SurfaceView` above the `Activity` when set to non-opaque. By default a `SurfaceView` creates a window *behind* your `Activity`.

**Comment by memostark** [comment]
I checked the UiHelper code and yes it sets the `SurfaceView` above when attached using `setZOrderOnTop(true)`, I tried calling that from my code but the background continues to be black.

```
...
surfaceView = SurfaceView(this)
surfaceView.setZOrderOnTop(true)
surfaceView.holder.setFormat(PixelFormat.TRANSLUCENT)
...
```

Also tried using a gltf model (the drone from the samples) and still no luck.

**Comment by memostark** [comment]
Transparency is finally working, just needed to add these lines:
```
modelViewer.view.blendMode = com.google.android.filament.View.BlendMode.TRANSLUCENT
modelViewer.scene.skybox = null
```
No need to modify your `SurfaceView`. UIHelper in the `ModelViewer` does that for you.

Warning, don't enable the dynamic resolution option in your ModelViewer otherwise the screen will flicker.

**Comment by romainguy** [comment]
Ah good catch, I should have suggested making sure you don't have a skybox.

Dynamic resolution should work just fine without flicker. On what devices did you observe flicker?

**Comment by memostark** [comment]
Thanks for your help @romainguy, my device is a Samsung Galaxy A51 (SM-A515F), API 29, filament version: 1.9.14

**Comment by paulorrfilho** [comment]
It is also flickering for me in a Samsung Galaxy S8, filament 1.9.13

**Comment by jaswinder13** [comment]
It is also flickering for me in a Mi Note6 Pro, please help and thanks in advance

**Comment by jaswinder13** [comment]
> Ah good catch, I should have suggested making sure you don't have a skybox.
> 
> Dynamic resolution should work just fine without flicker. On what devices did you observe flicker?

it is also flickering for me in my device

**Comment by soruppuAswin** [comment]
Not sure what's wrong. I am still seeing the black background even after adding the following lines mentioned above....

```
modelViewer.view.blendMode = com.google.android.filament.View.BlendMode.TRANSLUCENT
modelViewer.scene.skybox = null
```

**Comment by romainguy** [comment]
You need to enabling clearing + set the view blend mode to translucent *and* change the Z order of your `SurfaceView` (using `setZOrderOnTop()`). The easiest way to do the latter is to use our [`UiHelper`](https://github.com/google/filament/blob/main/android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java).

**Comment by soruppuAswin** [comment]
Thanks @romainguy for your inputs. By the way, I just changed the blendMode to OPAQUE and added white color to skybox builder, then it worked for me.

Now the problem is, the lighting is too low. I need to add another lighting source. None of the lighting source to the engine is helping me. Also, as per the documentation, "If several directional lights are added to the scene, the dominant one will be used.". My be the dominant one is the default one. Not sure.

**Comment by romainguy** [comment]
You can use multiple point/spot lights, but only one directional light will be applied. If the image is too "dark" increase light intensities or change the camera exposure.

**Comment by soruppuAswin** [comment]
Got you. By default, one directional light is already applied. That means, we can't add another one right? Because the following is already part of ModelViewer

`
        val (r, g, b) = Colors.cct(6_500.0f)
        LightManager.Builder(LightManager.Type.DIRECTIONAL)
                .color(r, g, b)
                .intensity(100_000.0f)
                .direction(0.0f, -1.0f, 0.0f)
                .castShadows(true)
                .build(engine, light)

        scene.addEntity(light)
`

**Comment by soruppuAswin** [comment]
Adding a new light source is not helping even now.

Also, in order to query the light, can I do something like this... LightManager's builder implementation is not exposed to see how is it implemented!

```
val light = EntityManager.get().create()
val lm = engine.lightManager
val lightInstance = lm.getInstance(light)
```

**Comment by romainguy** [comment]
`ModelViewer` exposes the light entity. Just do `lm.getInstance(modelViewer.light)` to get its light manager instance to modify it.

**Comment by soruppuAswin** [comment]
Oy yes, I am now able to get the light instance, but unfortunately we will not be able to modify the properties. Those are final values.

**Comment by romainguy** [comment]
The values aren't final: `LightManager.setIntensity(lightInstance, newIntensity)`.

**Comment by soruppuAswin** [comment]
Got you. It is working now. I will add more light sources and play around for getting the required lighting now. Thank you very much for your help!

**Comment by soruppuAswin** [comment]
Hey, after modifying the properties of existing light source, I tried to add few more light sources in each axis something like this... there is no effect on the screen. Please let me know what's wrong with my approach.

```
            val light1 = EntityManager.get().create()
            val light2 = EntityManager.get().create()
            val light3 = EntityManager.get().create()
            val light4 = EntityManager.get().create()
            val light5 = EntityManager.get().create()

            LightManager.Builder(LightManager.Type.POINT)
                .intensity(200_000f)
                .position(1f, 0f, 0f)
                .castShadows(false)
                .build(engine, light1)

            LightManager.Builder(LightManager.Type.POINT)
                .intensity(200_000f)
                .position(-1f, 0f, 0f)
                .castShadows(false)
                .build(engine, light2)

            LightManager.Builder(LightManager.Type.POINT)
                .intensity(200_000f)
                .position(0f, 1f, 0f)
                .castShadows(false)
                .build(engine, light3)

            LightManager.Builder(LightManager.Type.POINT)
                .intensity(200_000f)
                .position(0f, -1f, 0f)
                .castShadows(false)
                .build(engine, light4)

            LightManager.Builder(LightManager.Type.POINT)
                .intensity(200_000f)
                .position(0f, 0f, -1f)
                .castShadows(false)
                .build(engine, light5)

            scene.addEntity(light1)
            scene.addEntity(light2)
            scene.addEntity(light3)
            scene.addEntity(light4)
            scene.addEntity(light5)
```

**Comment by romainguy** [comment]
You need to give point lights a radius of influence.

**Comment by soruppuAswin** [comment]
Tried it. These are the only 2 options that I found in the builder- setSunAngularRadius and falloff.
Do you have a guide/example for this?

**Comment by romainguy** [comment]
You have to set the falloff:

```
        /**
         * Set the falloff distance for point lights and spot lights.
         *
         * At the falloff distance, the light has no more effect on objects.
         *
         * The falloff distance essentially defines a *sphere of influence* around the light, and
         * therefore has an impact on performance. Larger falloffs might reduce performance
         * significantly, especially when many lights are used.
         *
         * Try to avoid having a large number of light's spheres of influence overlap.
         *
         * @param radius Falloff distance in world units. Default is 1 meter.
         *
         * @return This Builder, for chaining calls.
         *
         * @note
         * The Light's falloff is ignored for directional lights (Type.DIRECTIONAL or Type.SUN)
         */
```

**Comment by romainguy** [comment]
The default falloff, as explained in the doc I showed above, is already 1 meter. Make it larger, like 20.

**Comment by soruppuAswin** [comment]
I have used 25 as well. Not working.

**Comment by fancychendong** [comment]
![screenshot-20220902-141527](https://user-images.githubusercontent.com/3930976/188077649-1c1ea173-0564-4494-8e8d-4743fb2d0490.png)
Samsung Galaxy S8, filament version: 1.12.5

I want to render the gltf model with a transparent background in android, but is not correct.
this is code
`
@Suppress("unused")
    constructor(textureView: TextureView, engine: Engine = Engine.create(), manipulator: Manipulator? = null, extraGltfMats: HashMap<String, String>? = null) : this(engine, extraGltfMats) {
        cameraManipulator = manipulator ?: Manipulator.Builder()
            .targetPosition(kDefaultObjectPosition.x, kDefaultObjectPosition.y, kDefaultObjectPosition.z)
            .viewport(textureView.width, textureView.height)
            .build(Manipulator.Mode.ORBIT)

        textureView.isOpaque = false
        this.extraGltfMats = extraGltfMats
        this.textureView = textureView
        gestureDetector = GestureDetector(textureView, cameraManipulator)
        displayHelper = DisplayHelper(textureView.context)
        uiHelper.renderCallback = SurfaceCallback()
        uiHelper.isOpaque = false
        uiHelper.attachTo(textureView)
        addDetachListener(textureView)
    }
`
I had try this code, but it do not work, someone can help me please?
`
val option = modelViewer.renderer.clearOptions
            option.clear = true
            modelViewer.renderer.clearOptions = option
            modelViewer.view.blendMode = View.BlendMode.TRANSLUCENT
            modelViewer.scene.skybox = null
            view.dynamicResolutionOptions = view.dynamicResolutionOptions.apply {
                enabled = true
                quality = View.QualityLevel.MEDIUM
            }
            view.ambientOcclusionOptions = view.ambientOcclusionOptions.apply {
                enabled = true
            }

            view.bloomOptions = view.bloomOptions.apply {
                enabled = true
            }
`

**Comment by atul161** [comment]
@romainguy ,

Any update on why flickering happens in some device while using Dynamic resolution?
