### ISSUE TITLE
Can not make the sample work on mac

### ISSUE THREAD

**Issue by ErikToth97** [google/filament#3209]
Hi,
I am trying to use filament on macOS (10.15.7) with a basic cocoa app, xcode version: 12.0.1
The picture is fallen apart and the triangles does not appear.

![filament_app](https://user-images.githubusercontent.com/52783764/96847880-fd555080-1453-11eb-92ca-1495fc21654f.png)

The only error I get is probably not a filament error, but I am not sure how to handle it:
2020-10-22 10:28:20.927861+0200 filament_build[2312:51382] flock failed to lock maps file: errno = 35
2020-10-22 10:28:20.928330+0200 filament_build[2312:51382] flock failed to lock maps file: errno = 35

I have never used cocoa before, sorry if I am missing something obvious. I followed this path because I read in the Render with Filament section that for the swapchain an NSView is needed.
I created a basic app in xcode, created a view controller (which works if I draw without filament). I put in this controller everything from the Rendering with Filament section.
I gave the swapchain the view which is controlled by the viewcontroller. 

I wanted to use the hellotriangle sample, so I copied the vertexbuffer and indexbuffer from there, and everything else I needed (without filamentApp).  Which means for filament I didn't write any new code, everything I use is from the hellotriangle and the Render with Filament description.

I also tried using materials, but I couldn't make Xcode see the files, after that I also tried to use the method in hellotriangle ( mat->getDefaultInstance() ) but that led to a THREAD 1: EXC_BAD_ACCESS error, so I simple didn't give it any material. This way the program runs, but the result is like the one in the picture.

Could you please help me as to what I am doing wrong, or maybe provide me a very basic example in macOS where you render something (like a triangle) with filament. 

Thank you,
Erik

**Comment by romainguy** [comment]
Could you please show us what code you are trying to run? It's hard to guess what might be going wrong without knowing exactly what it is you are doing.

**Comment by bejado** [comment]
Please show the code where you're creating the Filament `SwapChain`. In the screenshot you posted, where is that texture coming from? Is that something you've loaded?

**Comment by ErikToth97** [comment]
Sorry for not including the code at first. As i wrote I used the code that was provided in the Rendering with Filament section:

    Engine* engine = Engine::create();
    SwapChain* swapChain = engine->createSwapChain(self.view);
    Renderer* renderer = engine->createRenderer();

    Camera* camera = engine->createCamera(utils::EntityManager::get().create());
    View* view = engine->createView();
    Scene* scene = engine->createScene();
    view->setCamera(camera);
    view->setScene(scene);

In this code 'self' is a NSViewController to which I attached  a NSView which is displayed in the window, this part of the code works because I could draw on the NSview without filament.

I didn't not want to use any materials, I just needed a simple sample to see if it works, so for the other parts I used the triangles code in the hellotriangle sample, because it seemed to most basic:

    static Vertex TRIANGLE_VERTICES[3] = {
        {{1, 0}, 0xffff0000u},
        {{cos(M_PI * 2 / 3), sin(M_PI * 2 / 3)}, 0xff00ff00u},
        {{cos(M_PI * 4 / 3), sin(M_PI * 4 / 3)}, 0xff0000ffu},
    };
    static constexpr uint16_t TRIANGLE_INDICES[3] = { 0, 1, 2 };

    VertexBuffer* vb;
    IndexBuffer* ib;
    
    vb = VertexBuffer::Builder()
                    .vertexCount(3).bufferCount(1)
                    .attribute(VertexAttribute::POSITION, 0, VertexBuffer::AttributeType::FLOAT2, 0, 12)
                    .attribute(VertexAttribute::COLOR, 0, VertexBuffer::AttributeType::UBYTE4, 8, 12)
                    .normalized(VertexAttribute::COLOR).build(*engine);
    vb->setBufferAt(*engine, 0,
                    VertexBuffer::BufferDescriptor(TRIANGLE_VERTICES, 36, nullptr));
    
    
    ib = IndexBuffer::Builder().indexCount(3).bufferType(IndexBuffer::IndexType::USHORT).build(*engine);

    ib->setBuffer(*engine,
                    IndexBuffer::BufferDescriptor(TRIANGLE_INDICES, 6, nullptr));
    
    utils::Entity renderable = utils::EntityManager::get().create();
    
    RenderableManager::Builder(1)
                .boundingBox({{ -1, -1, -1 }, { 1, 1, 1 }})
                .geometry(0, RenderableManager::PrimitiveType::TRIANGLES, vb, ib, 0, 3)
                .build(*engine, renderable);
    scene->addEntity(renderable);
    
    if(renderer->beginFrame(swapChain)){
        renderer->render(view);
        renderer->endFrame();
    }

I was trying to use materials, but couldn't figure out how to make filament see the resource files, because I copied the material builder part of the code:

    Material* material = Material::Builder()
        .package((void*) BAKED_MATERIAL_PACKAGE, sizeof(BAKED_MATERIAL_PACKAGE))
        .build(*engine);
    MaterialInstance* materialInstance = material->createInstance();

I also tried with the one in the hellotriangle sample, I included the resources header file in the project and it didn't give any errors but in both cases it throws a linker error at runtime if I try to use materials. So I removed them.

On the other hand I don't know what that texture was that I sent a screenshot of, I thought it is something default that the filament displays, because as soon as I gave my self.view to the swapchain, I got that result. But today I cleaned the build and rerun the code, and now it doesn't display anything, although I did not change anything in the code.

**Comment by bejado** [comment]
You need to set the Viewport of the `View`:

```
view->setViewport({0, 0, width, height});
```

It's also a good idea to set the camera's projection:

```
const double aspect = (double) width / height;

const double left   = -2.0 * aspect;
const double right  =  2.0 * aspect;
const double bottom = -2.0;
const double top    =  2.0;
const double near   =  0.0;
const double far    =  1.0;
camera->setProjection(Camera::Projection::ORTHO, left, right, bottom, top, near, far);
```

**Comment by ErikToth97** [comment]
Thank you very much, this solved the issue!
