### ISSUE TITLE
Use span's instead of pointer+count arguments

### ISSUE THREAD

**Issue by shartte** [google/filament#321]
This ocurred to me while creating the API json spec. There are several (not many) methods in filament that take an array and a size argument. Examples:

```
EntityManager:
    // create n entities. Thread safe.
    void create(size_t n, Entity* entities);
    // destroys n entities. Thread safe.
    void destroy(size_t n, Entity* entities) noexcept;

RenderableManager.h:
  void setBones(Instance instance, Bone const* transforms, size_t boneCount = 1, size_t offset = 0) noexcept;
```

C++20 added std::span, while before then, there were things like gsl::span. When filament moves to C++20, I request that at least overloads for these methods are provided that take a std::span instead of the pointer+count arguments.

This would look like this, for example:
```
EntityManager:
    // create n entities. Thread safe.
    void create(std::span<Entity> entities);
    // destroys n entities. Thread safe.
    void destroy(std::span<Entity> entities) noexcept;

RenderableManager.h:
  void setBones(Instance instance, std::span<Bone>transforms) noexcept;
```

A side effect of this would be that an API JSON parser would be able to correctly infer that an array is being passed.

**Comment by romainguy** [comment]
If you look at our APIs you will see that we never expose STL types (in signatures or as private members). This is to help with ABI compatibility and to not force the use of STL on client apps.

**Comment by shartte** [comment]
Oh, I didn't actually notice that yet. I am a bit puzzled on the ABI compatibility though, since filament doesn't seem to be built as a shared library, and doesn't that make it a moot point?

**Comment by romainguy** [comment]
You would still need the headers used by the client app to match whatever was used to compile Filament. We link statically against the STL (and it's nice that we could go back to a .so easily).

**Comment by shartte** [comment]
Alright, understood.
An alternative for API purposes would be going for some annotation based approach, linking the array & size arguments. I think at some point I saw something like that for static-analysis purposes.
