### ISSUE TITLE
Expose setCullingFar() in webgl

### ISSUE THREAD

**Issue by davidwarford** [google/filament#3217]
**Is your feature request related to a problem? Please describe.**
webgl exposes getCullingFar() but has no way to set it to my knowledge

**Describe the solution you'd like**
I would like a setCullingFar() function exposed on the camera

**Describe alternatives you've considered**
Just really anyway to alter the culling distance in webgl

**Comment by romainguy** [comment]
There is no `setCullingFar`, it's just the `far` you specify when creating your project matrix. Internally Filament always uses infinity as the actual projection far plane, but will use the far you've specified as the culling distance.

**Comment by prideout** [comment]
This is also true for our low-level C++ API.  The shape of the viewing frustum can be controlled via the `set*Projection` methods.

**Comment by davidwarford** [comment]
okay sorry i didn't realize that, is there a utility for constructing a projection matrix with a different far plane?
