### ISSUE TITLE
Failed to import the forked filament project

### ISSUE THREAD

**Issue by vaaneeunbnd** [google/filament#3218]
Hello, 

I have forked the filament library and have tried to import it into my android studio project using jitpack.io. However, each time I am getting Failed to resolve error.

Below is the link for the jitpack error log - https://jitpack.io/com/github/vaaneeunbnd/filament/v1.9.5/build.log 

**To Reproduce**
1. Add it in your root build.gradle at the end of repositories:
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
2. Add the dependency:
dependencies {
	        implementation 'com.github.vaaneeunbnd:filament:v1.9.5'
	}

**Expected behavior**
Failed to resolve 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 2 API 28 Emulator
 - OS: Android

I would be grateful if someone could please help me with this.

Thank you!

**Comment by romainguy** [comment]
Check your build.log there are many errors. The build isn't properly configured it seems. Why not use our Maven Central binaries directly?

**Comment by vaaneeunbnd** [comment]
Hi @romainguy, 

Yes, I have checked the build log and I am unsure why this issue is happening with the configuration and stuff. I am new to filament and android dev, I would be grateful if you could please redirect me to your Maven Central binaries. Also, how can I use my forked version of 
implementation 'com.google.android.filament:filament-utils-android:1.9.3'
   implementation 'com.google.android.filament:gltfio-android:1.9.3'

Thanks
