### ISSUE TITLE
Not able to rotate .glb model

### ISSUE THREAD

**Issue by shivammaindola** [google/filament#3219]
I am trying to control the rotation of 3d Model. I'm able to control the .gltf model but not .glb. 

here's the code for .gltf

`       
         private fun loadGltf(name: String) {
         
         val buffer = readAsset("models/${name}.gltf")
         modelViewer.loadModelGltf(buffer) { uri -> readAsset("models/$uri") }

        modelViewer.transformToUnitCube()

        val localMatrix = FloatArray(16)
        modelViewer.engine.transformManager.getTransform(modelViewer.asset?.root!!, localMatrix)

        val rotateMatrix = FloatArray(16)
        Matrix.setRotateM(rotateMatrix, 0, 20F, 0.0f, 0.0f, 1.0f)

        val resultMatrix = FloatArray(16)
        Matrix.multiplyMM(resultMatrix, 0, rotateMatrix, 0, localMatrix, 0)

        val tcm = modelViewer.engine.transformManager
        tcm.setTransform(tcm.getInstance(modelViewer.asset?.root!!), resultMatrix)

    }`

and here's the code of .glb 

` private fun loadGlb(name: String) {
        
        val buffer = readAsset("models/${name}.glb")
        modelViewer.loadModelGlb(buffer)

        modelViewer.transformToUnitCube()

        val localMatrix = FloatArray(16)
        modelViewer.engine.transformManager.getTransform(modelViewer.asset?.root!!, localMatrix)

        val rotateMatrix = FloatArray(16)
        Matrix.setRotateM(rotateMatrix, 0, 0F, 0.0f, 0.0f, 1.0f)

        val resultMatrix = FloatArray(16)
        Matrix.multiplyMM(resultMatrix, 0, rotateMatrix, 0, localMatrix, 0)

        val tcm = modelViewer.engine.transformManager
        tcm.setTransform(tcm.getInstance(modelViewer.asset?.root!!), rotateMatrix)

    }`

Logic is the same in both cases but the .glb model is becoming invisible and .gltf is showing in the right way. I want to control the rotation of .glb model too. Please help.

**Comment by shivammaindola** [comment]
Done

**Comment by rabinansal** [comment]
@shivammaindola please share the code
