### ISSUE TITLE
Aliased silhouette with DOF

### ISSUE THREAD

**Issue by ttothfalussy** [google/filament#3221]
![dof_aliasing](https://user-images.githubusercontent.com/54284553/97224423-68df4b00-17d1-11eb-95d4-bbd9ef8ffe1d.jpg)

With DOF on, the object’s silhouette in focus gets aliased if the background or the next object is relatively far from the object itself. Changing the anti-alias options or type makes no difference. 

Depth of field and anti-aliasing features should be on (in the image it was MSAA). The image was made with the given gltf viewer sample.

Expected behavior:
Silhouette should have the same nicely anti-aliased look on the whole object regardless of the distance to the next one behind it.

Backend: Metal
Device: iPad pro 12.9” 2018
OS: 13.7

**Comment by romainguy** [comment]
This is not an anti-aliasing issue, it's an artifact of the depth of field effect.

**Comment by pixelflinger** [comment]
Indeed, currently we don't support well objects that are "almost out of focus", because the DoF effect is computed at quarter resolution. We might address this in the future (at a performance cost).

**Comment by ttothfalussy** [comment]
> Indeed, currently we don't support well objects that are "almost out of focus", because the DoF effect is computed at quarter resolution. We might address this in the future (at a performance cost).

Right, objects in the almost out of focus area can get problematic. Full resolution DoF calculation made the silhouettes a little better, but I've also noticed glitches and sometimes even floating artifacts, like at the top in the image. These are still present with full resolution. 
What parameters could I experiment more with, if I don't mind sacrificing performance for better image quality? If I remember right around 1.6-1.7 version it was slower but looked better.
![filament-dof-artifact](https://user-images.githubusercontent.com/54284553/99916413-6b6a8d00-2d0a-11eb-9518-4c94d97839a6.jpg)

**Comment by pixelflinger** [comment]
Yes at some point we had a version that could use as much as 1000 samples -- it did look better :-)

The parameters you can play with are:
 `RING_COUNT_GATHER` and `RING_COUNT_FAST` in `dof.mat`.  This will have the most impact I think.

You can also try to disable both `KERNEL_USE_MIPMAP` and `KERNEL_USE_NOISE`, but you'll need to really increase the `RING_COUNT_` above.

Another thing you can try is to disable the median filter, you can do that in `PostProcessManager.cpp`, look for
``` if (/* DISABLES CODE */ (false)) { // TODO: make this a quality setting ```
 and change this to `true`.

You already went full resolution, which will help as well.

In the image above, I believe the artifacts you see in the front are due to not using enough "rings", the strange ghosting at the top... that I don't know. I never noticed it before. Do you know how to reproduce it?

Is there any way you could share the scene you used above with us?

**Comment by pixelflinger** [comment]
A few more data points:
The maximum value that makes sense for `RING_COUNT_GATHER` is 17, this will perform the DoF blur with 1089 samples, and you never need more for the default maximum circle-of-confusion value of 32. Generally it doesn't make sense to increase `RING_COUNT_FAST` to that much. Maybe try a value around 8. These would be overkill values imho.
You can compute the number of effective samples as `(RING_COUNT*2-1)^2`.

**Comment by ast3rX** [comment]
@pixelflinger, thanks for the suggestions above. After pulling the latest version from the main branch the similar issues I was noticing mentioned here seemed to be fixed, and the average dof quality is a lot better! However, the object's silhouette still has an artifact in this version. There is a border around the object that seems to contain the background without the blur/dof effect. It's really easy to notice if your background has some details. Increasing the ring count might improve it a bit but it never disappears.

Attached is a screenshot from the desktop viewer.
![image](https://user-images.githubusercontent.com/743329/114005004-02486980-9814-11eb-9776-d1d2c1e1d14b.png)

**Comment by pixelflinger** [comment]
Yes, it's a known problem. You can improve it either by increasing the number of rings, or reducing the maximum CoC.

There is a better solution which will take some time to implement.

**Comment by ast3rX** [comment]
@pixelflinger , thanks! I started with the highest quality settings but the artifact was quite obvious, unfortunately.

**Comment by pixelflinger** [comment]
Oh that's interesting, even with 17 rings+native resolution? That should not be the case, it might be a bug indeed then.

**Comment by ast3rX** [comment]
Yes, even with 17 rings and native resolution the artifact is present.

**Comment by ast3rX** [comment]
Have you been able to repro this on your end?
