### ISSUE TITLE
Weird artifacts when I upgraded from version 1.4.5 -> 1.9.4

### ISSUE THREAD

**Issue by MarkMurillo** [google/filament#3228]
When I did the following dependency upgrades
```
implementation 'com.google.android.filament:filament-android:1.4.5' -> 1.9.4
implementation 'com.google.android.filament:filament-utils-android:1.4.5' -> 1.9.4
implementation 'com.google.android.filament:gltfio-android:1.4.5' -> 1.9.4
```
The rendering went from this:
![Rendering with version 1.4.5](https://i.imgur.com/6vKnvLb.png)

To this:
![Rendering with version 1.9.4](https://i.imgur.com/YDtYuaU.png)

I am using Vuforia to display camera frames on a GLSurfaceView, while I use TextureView on top of the GLSurfaceView to render the models using filament.

I imported the `Avocado.glb` model I was using into another sample that uses the 1.9.4 filament dependencies and it was rendering it correctly. I'm not sure what is producing the white lines and causing the tiling of the model...

 - Device: Pixel 4 XL
 - OS: Android 11

Any insights as to what is causing these artifacts would be helpful, thanks in advance!

**Comment by romainguy** [comment]
It looks like you are not clearing the `TextureView` properly (this kind of tiling artifact is what you get on tiled GPUs when not drawing the entire screen and/or not clearing it). We did change the APIs around clearing between 1.4 and 1.9 so check how you are doing the clear.

**Comment by romainguy** [comment]
@pixelflinger fyi

**Comment by MarkMurillo** [comment]
Thanks a lot @romainguy , I'll look into that and update here incase I manage to fix it.

**Comment by MarkMurillo** [comment]
Update:

I managed to fix the problem by setting the clear options after creating the filament `Renderer`
```
// Clear options for renderer
Renderer.ClearOptions().let {
            it.discard = true
            it.clear = true
            renderer.clearOptions = it
}
```

Thanks @romainguy for pointing me into the right direction!
