### ISSUE TITLE
Camera Rotation is laggy

### ISSUE THREAD

**Issue by vaaneeunbnd** [google/filament#3231]
**Describe the bug**
I have been trying to rotate the camera based on the device orientation( using gyroscope sensors android). I am using 
manipulator.grabBegin and manipulator.grabUpdate to do so. However, the camera rotation is laggy. 

I would be grateful if anyone could help me with this or suggest another way apply rotation to the camera

**To Reproduce**
1. Instantiate sensors as Sensors.TYPE_GYROSCOPE

**Expected behavior**
The camera should rotate as per the device rotation

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OPPO, Pixel 3
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
These APIs are designed to receive touch screen positions, not gyroscope orientations. You should compute the camera orientation from the gyroscope (ARCore will do that for you).

**Comment by vaaneeunbnd** [comment]
Thanks @romainguy, 

It makes sense. I will look at the ARCorew, however, I wanted to ask how can we apply that to the filament manipulator or camera?

**Comment by hanker666** [comment]
I meet the same problem,I can't change my camera,position or rotation

**Comment by romainguy** [comment]
@hanker666 How have you tried to change the camera's transform?

**Comment by hanker666** [comment]
> @hanker666 How have you tried to change the camera's transform?
modelView.getCamera().lookAt(...);`
