### ISSUE TITLE
Allow skinned models to share bones

### ISSUE THREAD

**Issue by aylaylay** [google/filament#3238]
I'm not sure if this is already supported but allowing models to share bones would be a useful optimization.
If you have a player model with clothing attached (that share the same skeleton structure) there's no reason to set the bones when they could use the master pose.

**Comment by romainguy** [comment]
I don't think there's anything preventing you from doing this? You just need to set the same transforms on two meshes. The skinning itself is done on the GPU so that will still happen per mesh. We've talked about caching this data but it hasn't been a priority so far.

**Comment by aylaylay** [comment]
The call to RenderableManager::setBones is still doing unnecessary work. You should be able to reuse the same buffer that the master pose has already has on the GPU if it's exactly the same.

**Comment by romainguy** [comment]
Like I said we don't cache the output of skinning at the moment so we can't share the skinning itself. It would be easy to add a version of setBones() that expects data already in the right format for sharing though.

**Comment by aylaylay** [comment]
Is it not possible to share the same uniform buffer? I know using texture buffers for gpu skinning you can just reuse the same buffer if the skeletons match.

**Comment by romainguy** [comment]
We can share the UBO but it just contains the transform data. If that's all you want to share then that's easy but it's not the expensive part of the process. We'll still reapply all the transforms to the vertices in the GPU shader.

**Comment by aylaylay** [comment]
Yeah it's just the updating of the UBO I'm on about. If they're not that expensive to update then maybe it's fine how it is. I'm thinking of the situations where you have many bones and lots of clothing attached to a player model, surely uploading the same data to a UBO once is much better than 10 or so times.

**Comment by romainguy** [comment]
Oh yeah it's definitely better, no argument here :)

**Comment by pixelflinger** [comment]
Very interesting use case.
