### ISSUE TITLE
issue on resusing the color texture of rendertarget 

### ISSUE THREAD

**Issue by geroge-d** [google/filament#3244]
Hi guys
   The color texture of render target is not correct on this render target being destroyed when finishing render.
   The detailed process is below:
   Step 1: create a rendertarget named A1
   Step 2: render some models into the A1 rendertarget    
   Step 3: destroy this A1 rendertarget, but keep its color texture
   Step 4:  create another render target A2
   Step 5: render the color texture of A1 onto the A2 rendertarget
Please give me some clue to fix it
Thanks in adavance

**Comment by prideout** [comment]
Thanks for the bug report!  This should be a valid sequence, we can look into it.  Do you see an error message in your log?

**Comment by romainguy** [comment]
Could you please provide screenshots? Are you using the OpenGL backend?

**Comment by geroge-d** [comment]
yes,wes use opengles backend in android 9.0 platform.
We get nothing but a black bitmap on finishing the steps above

**Comment by geroge-d** [comment]
FYI
If we destroy render target after endFrame,and render its color texture inside another beginFrame and endFrame. We can get the correct result

**Comment by romainguy** [comment]
That seems normal. When do you destroy the render target when it doesn't work?

**Comment by geroge-d** [comment]
The steps,which didn't work,  are called inside the same beginFrame /endFrame

**Comment by romainguy** [comment]
We should double check but that makes sense because of the resource tracking etc. we do internally during a frame.

**Comment by geroge-d** [comment]
Because our project, sometimes ，needs about 30 rendertargets to render a scene. so if we don't destroy the used rendertarget, the app will crash by OOM.

**Comment by geroge-d** [comment]
Sorry , it is my mistake. Filament work very well
