### ISSUE TITLE
Original material's name replaced using loadModelGlb. 

### ISSUE THREAD

**Issue by simonepelosi** [google/filament#3252]
It seems that the original name of the material is replaced when the glb model is loaded. 
For example: 

material name on blender/threejs = "my_mat" 
the same material on filament  = "ubershader_lit_opaque"

**Comment by prideout** [comment]
Note the distinction between materials and material instances.  The material instance should have the label in the gltf.  In ubershader mode (e.g. on Android or WebGL), the material is a fixed "ubershader" material so has a pre-assigned name.

![Screen Shot 2020-11-04 at 8 39 53 AM](https://user-images.githubusercontent.com/1288904/98139816-7b185380-1e79-11eb-877c-35d751ea802c.png)

**Comment by prideout** [comment]
Closing since the name should be fine when querying the `MaterialInstance` as opposed to the `Material`.  We can re-open if that's not the case.

**Comment by simonepelosi** [comment]
Nice! How can I get the label from the materialInstance? I cannot see any getter from Java.

<img width="560" alt="Schermata 2020-11-04 alle 18 05 47" src="https://user-images.githubusercontent.com/9490772/98142660-60210000-1ec8-11eb-8964-0a70a48c6851.png">

**Comment by prideout** [comment]
`MaterialInstance.java` currently exposes a `getName()` method.  Maybe you're using an old version of Filament?

**Comment by simonepelosi** [comment]
Done! Thank you!
