### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#3253]
I hava two custom material name testpbr and testunlit.
I use these to replace glb default material.
When I load glb and setMaterialInstanceAt , it work well.
But, When I switch material instance ,  then will be crash.
When I switch material, I will build a new Material instance and createNewInstance and then using setMaterialInstanceAt.
So can anyone give me some prompt for this problem?

Crash:
N5utils18PostconditionPanicE
in filament::backend::Program filament::FMaterial::getProgramBuilderWithVariants(uint8_t, uint8_t, uint8_t) const:392
reason: The material 'testpbr' has not been compiled to include the required GLSL or SPIR-V chunks for the vertex shader (variant=0x0, filtered=0x0).
![image](https://user-images.githubusercontent.com/4098790/98139140-ce80b500-1efe-11eb-87a8-78643955d3c7.png)

**Comment by cjsliuj** [comment]
PBR generator
`
filament::Material* PbrMaterial::generateMaterial(filament::Engine* engine) {
  filamat::MaterialBuilder::init();

  std::string customShader = R"(
        void material(inout MaterialInputs material) {
            highp float2 uvs[2];
            uvs[0] = getUV0();
            uvs[1] = getUV1();

            if (materialParams.normalIndex > -1) {
                highp float2 uv = uvs[materialParams.normalIndex];
                uv = (vec3(uv, 1.0) * materialParams.normalUvMatrix).xy;
                material.normal = texture(materialParams_normalMap, uv).xyz * 2.0 - 1.0;
                if (materialParams.normalEnableGReverse){
                  material.normal.y = 1.0 - material.normal.y;
                }
                material.normal.xy *= materialParams.normalScale;
            }
            if (materialParams.clearCoatNormalIndex > -1) {
                highp float2 uv = uvs[materialParams.clearCoatNormalIndex];
                uv = (vec3(uv, 1.0) * materialParams.clearCoatNormalUvMatrix).xy;
                material.clearCoatNormal = texture(materialParams_clearCoatNormalMap, uv).xyz * 2.0 - 1.0;
                material.clearCoatNormal.xy *= materialParams.clearCoatNormalScale;
            }

            prepareMaterial(material);
            material.baseColor = materialParams.baseColorFactor;

            if (materialParams.baseColorIndex > -1) {
                highp float2 uv = uvs[materialParams.baseColorIndex];
                uv = (vec3(uv, 1.0) * materialParams.baseColorUvMatrix).xy;
                material.baseColor *= texture(materialParams_baseColorMap, uv);
            }

            material.baseColor *= getColor();

            material.roughness = materialParams.roughnessFactor;
            material.metallic = materialParams.metallicFactor;

            // KHR_materials_clearcoat forbids clear coat from
            // being applied in the specular/glossiness model
            material.clearCoat = materialParams.clearCoatFactor;
            material.clearCoatRoughness = materialParams.clearCoatRoughnessFactor;

            if (materialParams.clearCoatIndex > -1) {
                highp float2 uv = uvs[materialParams.clearCoatIndex];
                uv = (vec3(uv, 1.0) * materialParams.clearCoatUvMatrix).xy;
                material.clearCoat *= texture(materialParams_clearCoatMap, uv).r;
            }
            if (materialParams.clearCoatRoughnessIndex > -1) {
                highp float2 uv = uvs[materialParams.clearCoatRoughnessIndex];
                uv = (vec3(uv, 1.0) * materialParams.clearCoatRoughnessUvMatrix).xy;
                material.clearCoatRoughness *= texture(materialParams_clearCoatRoughnessMap, uv).g;
            }

            material.emissive = vec4(materialParams.emissiveFactor.rgb, 0.0);

            if (materialParams.metallicRoughnessIndex > -1) {
                highp float2 uv = uvs[materialParams.metallicRoughnessIndex];
                uv = (vec3(uv, 1.0) * materialParams.metallicRoughnessUvMatrix).xy;

                vec4 mr = texture(materialParams_metallicRoughnessMap, uv);
                material.roughness *= mr[materialParams.roughnessSamplingChannel];
                material.metallic *= mr[materialParams.metallicSamplingChannel];
            }

            if (materialParams.aoIndex > -1) {
                highp float2 uv = uvs[materialParams.aoIndex];
                uv = (vec3(uv, 1.0) * materialParams.occlusionUvMatrix).xy;
                material.ambientOcclusion = texture(materialParams_occlusionMap, uv)[materialParams.metallicSamplingChannel] * materialParams.aoStrength;
            }
            if (materialParams.emissiveIndex > -1) {
                highp float2 uv = uvs[materialParams.emissiveIndex];
                uv = (vec3(uv, 1.0) * materialParams.emissiveUvMatrix).xy;
                material.emissive.rgb *= texture(materialParams_emissiveMap, uv).rgb;
            }

            if (materialParams.reflectanceIndex > -1) {
                highp float2 uv = uvs[materialParams.reflectanceIndex];
                uv = (vec3(uv, 1.0) * materialParams.reflectanceUvMatrix).xy;
                material.reflectance = texture(materialParams_reflectanceMap, uv).r * materialParams.reflectanceFactor;
            }
        }
    )";

  std::string vertexShader = R"(
      void materialVertex(inout MaterialVertexInputs material) {
          material.worldPosition = getWorldFromModelMatrix() * materialParams.vertexTransform * getPosition();
      }
    )";
  filamat::MaterialBuilder builder =
      filamat::MaterialBuilder()
          .name("testpbr")
          .require(filament::VertexAttribute::COLOR)
          .require(filament::VertexAttribute::UV0)
          .require(filament::VertexAttribute::UV1)
          .depthWrite(this->depth_write_)
          .depthCulling(this->depth_culling_)
          .culling(this->culling_mode_)
          .colorWrite(this->color_write_)
          .doubleSided(this->double_side_)
          .blending(this->blending_)
          .flipUV(this->flipUV_)
          .shading(this->shading_model_)
          .specularAmbientOcclusion(this->specular_ambient_occlusion_)
          .material(customShader.c_str())
//          .materialVertex(vertexShader.c_str())
          .targetApi(filamat::targetApiFromBackend(engine->getBackend()));


  //------------------------- fragment
  // BASE COLOR
  builder.parameter(MaterialBuilder::UniformType::INT, "baseColorIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT4, "baseColorFactor");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "baseColorMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "baseColorUvMatrix");

  // METALLIC-ROUGHNESS
  builder.parameter(MaterialBuilder::UniformType::INT, "metallicRoughnessIndex");
  builder.parameter(MaterialBuilder::UniformType::INT, "metallicSamplingChannel");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "metallicFactor");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "roughnessFactor");
  builder.parameter(MaterialBuilder::UniformType::INT, "roughnessSamplingChannel");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "metallicRoughnessMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "metallicRoughnessUvMatrix");

  // AMBIENT OCCLUSION
  builder.parameter(MaterialBuilder::UniformType::INT, "aoIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "aoStrength");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "occlusionMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "occlusionUvMatrix");
  builder.parameter(MaterialBuilder::UniformType::INT, "aoSamplingChannel");

  // NORMAL MAP
  builder.parameter(MaterialBuilder::UniformType::INT, "normalIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "normalScale");
  builder.parameter(MaterialBuilder::UniformType::BOOL, "normalEnableGReverse");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "normalMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "normalUvMatrix");

  // EMISSIVE
  builder.parameter(MaterialBuilder::UniformType::INT, "emissiveIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT3, "emissiveFactor");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "emissiveMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "emissiveUvMatrix");

  // Clear coat
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "clearCoatFactor");
  builder.parameter(MaterialBuilder::UniformType::INT, "clearCoatIndex");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "clearCoatMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "clearCoatUvMatrix");

  // Clear coat roughness
  builder.parameter(MaterialBuilder::UniformType::INT, "clearCoatRoughnessIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "clearCoatRoughnessFactor");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "clearCoatRoughnessMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "clearCoatRoughnessUvMatrix");

  // Clear coat normal
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "clearCoatNormalScale");
  builder.parameter(MaterialBuilder::UniformType::INT, "clearCoatNormalIndex");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "clearCoatNormalMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "clearCoatNormalUvMatrix");

  // Reflectance
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "reflectanceFactor");
  builder.parameter(MaterialBuilder::UniformType::INT, "reflectanceIndex");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "reflectanceMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "reflectanceUvMatrix");

  // ---------------------- vertex block
  builder.parameter(filamat::MaterialBuilder::UniformType::MAT4, "vertexTransform");

  filamat::Package pkg = builder.build();
  return filament::Material::Builder().package(pkg.getData(), pkg.getSize()).build(*engine);
}`

**Comment by cjsliuj** [comment]
**pbr generator**
`
filament::Material* PbrMaterial::generateMaterial(filament::Engine* engine) {
  filamat::MaterialBuilder::init();

  std::string customShader = R"(
        void material(inout MaterialInputs material) {
            highp float2 uvs[2];
            uvs[0] = getUV0();
            uvs[1] = getUV1();

            if (materialParams.normalIndex > -1) {
                highp float2 uv = uvs[materialParams.normalIndex];
                uv = (vec3(uv, 1.0) * materialParams.normalUvMatrix).xy;
                material.normal = texture(materialParams_normalMap, uv).xyz * 2.0 - 1.0;
                if (materialParams.normalEnableGReverse){
                  material.normal.y = 1.0 - material.normal.y;
                }
                material.normal.xy *= materialParams.normalScale;
            }
            if (materialParams.clearCoatNormalIndex > -1) {
                highp float2 uv = uvs[materialParams.clearCoatNormalIndex];
                uv = (vec3(uv, 1.0) * materialParams.clearCoatNormalUvMatrix).xy;
                material.clearCoatNormal = texture(materialParams_clearCoatNormalMap, uv).xyz * 2.0 - 1.0;
                material.clearCoatNormal.xy *= materialParams.clearCoatNormalScale;
            }

            prepareMaterial(material);
            material.baseColor = materialParams.baseColorFactor;

            if (materialParams.baseColorIndex > -1) {
                highp float2 uv = uvs[materialParams.baseColorIndex];
                uv = (vec3(uv, 1.0) * materialParams.baseColorUvMatrix).xy;
                material.baseColor *= texture(materialParams_baseColorMap, uv);
            }

            material.baseColor *= getColor();

            material.roughness = materialParams.roughnessFactor;
            material.metallic = materialParams.metallicFactor;

            // KHR_materials_clearcoat forbids clear coat from
            // being applied in the specular/glossiness model
            material.clearCoat = materialParams.clearCoatFactor;
            material.clearCoatRoughness = materialParams.clearCoatRoughnessFactor;

            if (materialParams.clearCoatIndex > -1) {
                highp float2 uv = uvs[materialParams.clearCoatIndex];
                uv = (vec3(uv, 1.0) * materialParams.clearCoatUvMatrix).xy;
                material.clearCoat *= texture(materialParams_clearCoatMap, uv).r;
            }
            if (materialParams.clearCoatRoughnessIndex > -1) {
                highp float2 uv = uvs[materialParams.clearCoatRoughnessIndex];
                uv = (vec3(uv, 1.0) * materialParams.clearCoatRoughnessUvMatrix).xy;
                material.clearCoatRoughness *= texture(materialParams_clearCoatRoughnessMap, uv).g;
            }

            material.emissive = vec4(materialParams.emissiveFactor.rgb, 0.0);

            if (materialParams.metallicRoughnessIndex > -1) {
                highp float2 uv = uvs[materialParams.metallicRoughnessIndex];
                uv = (vec3(uv, 1.0) * materialParams.metallicRoughnessUvMatrix).xy;

                vec4 mr = texture(materialParams_metallicRoughnessMap, uv);
                material.roughness *= mr[materialParams.roughnessSamplingChannel];
                material.metallic *= mr[materialParams.metallicSamplingChannel];
            }

            if (materialParams.aoIndex > -1) {
                highp float2 uv = uvs[materialParams.aoIndex];
                uv = (vec3(uv, 1.0) * materialParams.occlusionUvMatrix).xy;
                material.ambientOcclusion = texture(materialParams_occlusionMap, uv)[materialParams.metallicSamplingChannel] * materialParams.aoStrength;
            }
            if (materialParams.emissiveIndex > -1) {
                highp float2 uv = uvs[materialParams.emissiveIndex];
                uv = (vec3(uv, 1.0) * materialParams.emissiveUvMatrix).xy;
                material.emissive.rgb *= texture(materialParams_emissiveMap, uv).rgb;
            }

            if (materialParams.reflectanceIndex > -1) {
                highp float2 uv = uvs[materialParams.reflectanceIndex];
                uv = (vec3(uv, 1.0) * materialParams.reflectanceUvMatrix).xy;
                material.reflectance = texture(materialParams_reflectanceMap, uv).r * materialParams.reflectanceFactor;
            }
        }
    )";

  std::string vertexShader = R"(
      void materialVertex(inout MaterialVertexInputs material) {
          material.worldPosition = getWorldFromModelMatrix() * materialParams.vertexTransform * getPosition();
      }
    )";
  filamat::MaterialBuilder builder =
      filamat::MaterialBuilder()
          .name("testpbr")
          .require(filament::VertexAttribute::COLOR)
          .require(filament::VertexAttribute::UV0)
          .require(filament::VertexAttribute::UV1)
          .depthWrite(this->depth_write_)
          .depthCulling(this->depth_culling_)
          .culling(this->culling_mode_)
          .colorWrite(this->color_write_)
          .doubleSided(this->double_side_)
          .blending(this->blending_)
          .flipUV(this->flipUV_)
          .shading(this->shading_model_)
          .specularAmbientOcclusion(this->specular_ambient_occlusion_)
          .material(customShader.c_str())
//          .materialVertex(vertexShader.c_str())
          .targetApi(filamat::targetApiFromBackend(engine->getBackend()));


  //------------------------- fragment
  // BASE COLOR
  builder.parameter(MaterialBuilder::UniformType::INT, "baseColorIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT4, "baseColorFactor");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "baseColorMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "baseColorUvMatrix");

  // METALLIC-ROUGHNESS
  builder.parameter(MaterialBuilder::UniformType::INT, "metallicRoughnessIndex");
  builder.parameter(MaterialBuilder::UniformType::INT, "metallicSamplingChannel");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "metallicFactor");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "roughnessFactor");
  builder.parameter(MaterialBuilder::UniformType::INT, "roughnessSamplingChannel");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "metallicRoughnessMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "metallicRoughnessUvMatrix");

  // AMBIENT OCCLUSION
  builder.parameter(MaterialBuilder::UniformType::INT, "aoIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "aoStrength");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "occlusionMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "occlusionUvMatrix");
  builder.parameter(MaterialBuilder::UniformType::INT, "aoSamplingChannel");

  // NORMAL MAP
  builder.parameter(MaterialBuilder::UniformType::INT, "normalIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "normalScale");
  builder.parameter(MaterialBuilder::UniformType::BOOL, "normalEnableGReverse");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "normalMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "normalUvMatrix");

  // EMISSIVE
  builder.parameter(MaterialBuilder::UniformType::INT, "emissiveIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT3, "emissiveFactor");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "emissiveMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "emissiveUvMatrix");

  // Clear coat
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "clearCoatFactor");
  builder.parameter(MaterialBuilder::UniformType::INT, "clearCoatIndex");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "clearCoatMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "clearCoatUvMatrix");

  // Clear coat roughness
  builder.parameter(MaterialBuilder::UniformType::INT, "clearCoatRoughnessIndex");
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "clearCoatRoughnessFactor");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "clearCoatRoughnessMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "clearCoatRoughnessUvMatrix");

  // Clear coat normal
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "clearCoatNormalScale");
  builder.parameter(MaterialBuilder::UniformType::INT, "clearCoatNormalIndex");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "clearCoatNormalMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "clearCoatNormalUvMatrix");

  // Reflectance
  builder.parameter(MaterialBuilder::UniformType::FLOAT, "reflectanceFactor");
  builder.parameter(MaterialBuilder::UniformType::INT, "reflectanceIndex");
  builder.parameter(MaterialBuilder::SamplerType::SAMPLER_2D, "reflectanceMap");
  builder.parameter(MaterialBuilder::UniformType::MAT3, "reflectanceUvMatrix");

  // ---------------------- vertex block
  builder.parameter(filamat::MaterialBuilder::UniformType::MAT4, "vertexTransform");

  filamat::Package pkg = builder.build();
  return filament::Material::Builder().package(pkg.getData(), pkg.getSize()).build(*engine);
}`

**Comment by cjsliuj** [comment]
[Uploading testpbr_generator.txt…]()

**Comment by cjsliuj** [comment]
[testpbr_generator.txt](https://github.com/google/filament/files/5489125/testpbr_generator.txt)
[testunlit_generator.txt](https://github.com/google/filament/files/5489126/testunlit_generator.txt)

**Comment by cjsliuj** [comment]
I am very confused about this problem, if I can get help, I will be very grateful

**Comment by prideout** [comment]
This seems like an issue with how you're invoking the `matc` tool.  Are you using a pre-built matc?  If so make sure that it matches your Filament build.  Also make sure that the arguments you pass to `matc` are appropriate for your platform.

**Comment by romainguy** [comment]
The sample code is in the .txt files. @cjsliuj is using filamat directly.

@cjsliuj Could you check the logs before the crash? It's probably because the material didn't compile properly.

**Comment by cjsliuj** [comment]
If the compilation is incorrect, then I should always have this crash problem, but currently it only occurs during the process of switching material instances.
Then, I dealt with it like this before I switch material instance:
`engine_->destroy(old_mat_instance);` 
Then it won't crash.

**Comment by cjsliuj** [comment]
In addition, there are indeed some warnings when compiling： 
`WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16 (testpbr)
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap
WARNING: Exceeded max sampler count of 16
     records
   froxels
   iblDFG
   iblSpecular
   ssao
   ssr
   structure
  baseColorMap
  	 metallicRoughnessMap
  
 occlusionMap
   normalMap
   emissiveMap
  
 clearCoatMap
   clearCoatRoughnessMap
   clearCoatNormalMap
   reflectanceMap`
