### ISSUE TITLE
Incorrect function name: nGetRefraction vs nGetRefractionMode

### ISSUE THREAD

**Issue by alexey-pelykh** [google/filament#3254]
https://github.com/google/filament/blob/f37a3e94974f691b0df6ff728c175ace895ff8f4/android/filament-android/src/main/cpp/Material.cpp#L94

**Comment by romainguy** [comment]
Thank you, that's a great catch. The name was refactored a while back. I'll fix this asap.

**Comment by romainguy** [comment]
I just pushed a fix into the main branch.

**Comment by alexey-pelykh** [comment]
Thanks for quick response!

**Comment by romainguy** [comment]
Fix in https://github.com/google/filament/commit/24ca2bf181d96a839266ac7c3ffbf45696fd7f3b
