### ISSUE TITLE
Update gltf/glb android samples

### ISSUE THREAD

**Issue by simonepelosi** [google/filament#3255]
The samples are not working, please can you update them? I need a guide to use a glb model.
(I'm using Java)

**Comment by prideout** [comment]
We have only one glTF sample for Android, `sample-gltf-viewer`, what happens when you try to run it?

**Comment by romainguy** [comment]
I was able to successfully compile and run the sample glTF viewer app for Android. Please reopen this issue with more information if you are still running into problems.
