### ISSUE TITLE
Null pointer dereference on Filament 1.9.6 on Android

### ISSUE THREAD

**Issue by Sheng-Xuan** [google/filament#3256]
**Describe the bug**
App crashed with error thrown from native

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
Cause: null pointer dereference
    x0  0000007bc85e64b0  x1  0000000000000000  x2  0000000000000000  x3  0000000000000040
    x4  0000000000000010  x5  0000007b208aa89f  x6  0000000000000002  x7  0000000065747563
    x8  0000000000000000  x9  0000000000000000  x10 ffffffffffffffff  x11 0000000000000000
    x12 0000000000000000  x13 0000007b8c279168  x14 0000000000000002  x15 0000000000000000
    x16 0000007b8bfd14e8  x17 0000007e3b8a081c  x18 0000007b1fa6c000  x19 0000007ce84dbd90
    x20 0000007bc85e64b0  x21 0000007b1f540040  x22 0000007b97f438f0  x23 0000007bb85071b0
    x24 0000007bb85071c0  x25 0000007b208aacc0  x26 0000007b208aaff8  x27 00000000000fc000
    x28 0000007b207b2000  x29 0000007b208aac70
    lr  0000007b98a41f4c  sp  0000007b208aaa70  pc  0000007b98a41f78  pst 0000000080000000

backtrace:
      #00 pc 0000000000080f78  /data/app/~~jTAONzYqCXisrSqLxWdYkg==/com.my.app.demo-LJhmSdpqEqCvHK4aik-hhQ==/base.apk!libfilament-jni.so (offset 0x6b4000) (BuildId: 76e3c59bc8306b2aa8b0cedb17e9b6c9d6ed1ac7)

**To Reproduce**
1. Use arcore 1.20 and sceneform 1.16 setup AR, crash randomly during the AR session.

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 11

**Additional context**

That's the only backtrace I have, all mat assets are recompiled with matc tool 1.9.6, attached the tombstone of this crash
[tombstone_26.zip](https://github.com/google/filament/files/5495096/tombstone_26.zip)

**Comment by romainguy** [comment]
There's not much we can do without more information or without a repro case.
