### ISSUE TITLE
crashed on filament debug version

### ISSUE THREAD

**Issue by geroge-d** [google/filament#3259]
Hi 
     When we rendered a large scene,which has about 20 render targets, we met a crash, the relative log below
OS: Andorid 10, GPU Adreno (TM) 530,vendor:Qualcomm,version:OpenGL ES 3.2 V@328.0 (GIT@d7977ce, Ife855c4895) (Date:08/21/18)

Filament: KHR_debug ERROR: texture target 0 is an invalid enum
Filament: OpenGL error 0x500 (GL_INVALID_ENUM) in "void filament::OpenGLProgram::updateSamplers(filament::OpenGLDriver *)" at line 236

**Comment by geroge-d** [comment]
When it finish rendering some rendertargets,  the app will destroy its view and all buffers but color buffer. and we met the crash above.  If we keep its view and color buffer ,we met the crash below
2020-11-06 17:58:14.114 18710-18970 E/Filament: KHR_debug ERROR: unable to locate sync object
    
    --------- beginning of crash
2020-11-06 17:58:14.114 18710-18970 A/libc: ../../filament/backend/src/opengl/OpenGLContext.h:431: void filament::OpenGLContext::bindTexture(GLuint, GLuint, GLuint, size_t): assertion "targetIndex == getIndexForTextureTarget(target)" failed

**Comment by geroge-d** [comment]
I guess it is caused by  running out of  gpu resource handles. 
Any suggestion is very appeciate

**Comment by romainguy** [comment]
It could also be because you are destroying resources too early. We need more information about what you are doing exactly though.

**Comment by geroge-d** [comment]
The whole render process below:
1. create some render targets
2. call beginFrame
3. render some models into the created targets
4. call endFrame
5. destroy these render targets but keep the color buffer
6. create another render target, and blit these color buffers, which are used above ,  into this new created render target

**Comment by romainguy** [comment]
Could you please share the code you use to create/destroy the render targets and color buffers?

**Comment by geroge-d** [comment]
sorry to disturb you.  it is my mistake. I just fixed it .

**Comment by BobiAce** [comment]
> sorry to disturb you. it is my mistake. I just fixed it .

I also encountered the same mistake, can you refer to how you solved it?
