### ISSUE TITLE
Wrong Mathias's twitter handle in the docs

### ISSUE THREAD

**Issue by borodust** [google/filament#3262]
**Describe the bug**
Wrong Mathias's twitter handle at Authors chapter of Materials page. Link is correct though.

**To Reproduce**
1. Go to https://google.github.io/filament/Materials.html#about/authors

**Expected behavior**
Both twitter handles correctly labeled.

**Screenshots**
![Screenshot_2020-11-08_00-21-26](https://user-images.githubusercontent.com/2681281/98451634-a55b6100-2158-11eb-97fa-c10db1040ee7.png)

**Comment by romainguy** [comment]
Thanks, it's now fixed!
