### ISSUE TITLE
filament.d.ts should be included in the web release

### ISSUE THREAD

**Issue by davidwarford** [google/filament#3268]
**Is your feature request related to a problem? Please describe.**
Currently you need to pull both the web release and the source code release so that you can get the correct version of filament.d.ts

**Describe the solution you'd like**
add filament.d.ts to the web release going forward.

**Comment by prideout** [comment]
It's included in the npm package (https://unpkg.com/browse/filament@1.9.6/) but yes we should include it in the release zip too, especially after we factor the doc comments into it.

**Comment by davidwarford** [comment]
#3250

**Comment by davidwarford** [comment]
Is this likely to be included in the next release?
