### ISSUE TITLE
Cast Hidden Shadows

### ISSUE THREAD

**Issue by aylaylay** [google/filament#3269]
Is there a way to cast shadows for hidden renderables? Use case being casting player model shadows while in first person (player model is hidden while in first person)

**Comment by romainguy** [comment]
You can achieve this by using a material that sets `colorWrite` and `depthWrite` to `false`. Make sure the renderable is a shadow caster and it will appear only in the shadow map.

**Comment by aylaylay** [comment]
I mean I guess it works but not an elegant solution. Can we not have a CastHiddenShadow bool on renderables?

**Comment by romainguy** [comment]
I'd rather we didn't add extremely specific APIs like this on a generic APIs like `Renderable`. Note that it would do exactly the same in the end anyway.

**Comment by aylaylay** [comment]
You already have layer masks and shadow casting options on renderable. An option to cast shadows from hidden objects fits very nicely into that and is not "extremely specific"
