### ISSUE TITLE
assert occurs in  android debug version

### ISSUE THREAD

**Issue by geroge-d** [google/filament#3271]
Hi 
  When i disabled  antiAliasing of view,which has a depth buffer. the app met an assertion below
The code where to disable antiAliasing:
          ` view.antiAliasing = View.AntiAliasing.NONE
                view.sampleCount = 1`
Code where the  assert  occur:
` line  665  in  void OpenGLDriver::createTextureR(....){
           ....
            assert(any(usage & (
                TextureUsage::COLOR_ATTACHMENT |
                TextureUsage::DEPTH_ATTACHMENT |
                TextureUsage::STENCIL_ATTACHMENT)));
           ....
}`
If  i change  the usage  of  FrameGraphTexture::Descriptor from default 0 to backend::TextureUsage::DEFAULT, this assertion will not occur

**Comment by romainguy** [comment]
Could you describe your rendering setup?

**Comment by geroge-d** [comment]
The code below is to create color and depth texture
` var color: Texture
    var depth: Texture?
    val view :View = sceneRenderImpl.engine.createView()
    val scene: Scene = sceneRenderImpl.engine.createScene()
    var renderTarget:RenderTarget? = null
    init {
        scene.skybox = sceneRenderImpl.getDefaultSkyBox()
        val internalformat:Texture.InternalFormat;
        if (sceneRenderImpl.supportFloatRenderTarget())
        {
            internalformat = Texture.InternalFormat.RGBA16F;
//            L.e(TAG,"color texture format:rgba16f")
        }
        else{
            internalformat = Texture.InternalFormat.RGBA8;
//            L.e(TAG,"color texture format:rgba8")
        }

        color = Texture.Builder()
                .width(width)
                .height(height)
                .levels(1)
                .usage(Texture.Usage.COLOR_ATTACHMENT or Texture.Usage.SAMPLEABLE)
                .format(internalformat)
                .build(sceneRenderImpl.engine)
        if ( hasDepth)
        {
            val depthbit:Texture.InternalFormat
            if ( PixelBuffer.getDepthBits() == 32){
                depthbit = Texture.InternalFormat.DEPTH32F
            }
            else if ( PixelBuffer.getDepthBits() == 24){
                depthbit = Texture.InternalFormat.DEPTH24
            }
            else{
                depthbit = Texture.InternalFormat.DEPTH24
            }
            depth = Texture.Builder()
                    .width(width).height(height).levels(1)
                    .usage(Texture.Usage.DEPTH_ATTACHMENT )
                    .format(depthbit)
                    .build(sceneRenderImpl.engine)

            scene.indirectLight = sceneRenderImpl.getDefaultIBL().indirectLight
        }
        else{
            depth =  null
        }

    }
`
The codes below where to init view to render:
 protected fun initView(view: View){
        view.camera = camera
        view.scene = scene
        view.blendMode = View.BlendMode.OPAQUE
        view.setScreenSpaceRefractionEnabled(false)
        view.setShadowingEnabled(false)

//        view.setShadowingEnabled(false)
        if ( hasDepth && hasColor){
            view.dithering = View.Dithering.NONE
            view.isPostProcessingEnabled = true
            if (hasAnti){
//                if ( !PixelBuffer.isMaliGPU()){
//                    view.antiAliasing = View.AntiAliasing.FXAA
//                    view.sampleCount = 4// 解决华为手机的显示不了问题
//                }
//                else
//                {
//                    view.antiAliasing = View.AntiAliasing.NONE
//                    view.sampleCount = 1// 解决华为手机的显示不了问题
//                }
//                view.antiAliasing = View.AntiAliasing.FXAA
//                view.sampleCount = 1// 解决华为手机的显示不了问题
                view.antiAliasing = View.AntiAliasing.NONE
                view.sampleCount = 1// 解决华为手机的显示不了问题
//                val opt = View.TemporalAntiAliasingOptions()
//                opt.enabled = true
//                view.setTemporalAntiAliasingOptions(opt)
            }
            else{
                view.sampleCount = 1
                view.antiAliasing = View.AntiAliasing.NONE
            }
            val grading =sceneRenderImpl.getColorGrading()
            view.colorGrading = grading
            view.ambientOcclusion = View.AmbientOcclusion.NONE //有些手机一打开3D就会出现编译shader错误，通过关闭ssao可以解决这个问题
            renderTarget= RenderTarget.Builder()
                    .texture(RenderTarget.AttachmentPoint.COLOR, color)
                    .texture(RenderTarget.AttachmentPoint.DEPTH, depth)
                    .build(sceneRenderImpl.engine)
            view.renderTarget = renderTarget

        }
        else if ( hasColor){
//            view.setShadowsEnabled(false)
            view.toneMapping = View.ToneMapping.LINEAR
//                view.depthPrepass = View.DepthPrepass.DISABLED
            view.dithering = View.Dithering.NONE
            view.sampleCount = 1
            view.antiAliasing = View.AntiAliasing.NONE
            view.isPostProcessingEnabled = false
            renderTarget = RenderTarget.Builder()
                    .texture(RenderTarget.AttachmentPoint.COLOR, color)
                    .build(sceneRenderImpl.engine)
            view.renderTarget = renderTarget
        }
        else{
            throw IllegalStateException("should not reach hear,hasCOlor:${hasColor} hasDepth:${hasDepth}")
        }
//        else if ( hasDepth){
//            view.dithering = View.Dithering.NONE
//            view.isPostProcessingEnabled = true
////                view.sampleCount = 1
////                view.antiAliasing = View.AntiAliasing.NONE
//            if ( hasAnti){
//                if ( !PixelBuffer.isMaliGPU()){
//                    view.antiAliasing = View.AntiAliasing.FXAA
//                    view.sampleCount = 4// 解决华为手机的显示不了问题
//                }
//                else{
//                    view.antiAliasing = View.AntiAliasing.NONE
//                    view.sampleCount = 1// 解决华为手机的显示不了问题
//                }
//
//            }
//            else{
//                view.sampleCount = 1
//                view.antiAliasing = View.AntiAliasing.NONE
//            }
//            val grading =sceneRenderImpl.getColorGrading()
//            view.colorGrading = grading
//            view.ambientOcclusion = View.AmbientOcclusion.NONE //有些手机一打开3D就会出现编译shader错误，通过关闭ssao可以解决这个问题
//            renderTarget= RenderTarget.Builder()
//                    .texture(RenderTarget.AttachmentPoint.DEPTH, depth)
//                    .build(sceneRenderImpl.engine)
//            view.renderTarget = renderTarget
//        }
        view.viewport = Viewport(0,0,width,height)
    }

**Comment by geroge-d** [comment]
FYI
I call this method initView between beginFrame and endFrame. so should i call it before beginFrame?

**Comment by romainguy** [comment]
I'm not sure but in general you should not be creating resources and setting up rendering after `beginFrame()`.
