### ISSUE TITLE
How do you get access to instances from a filamentAsset in the web api

### ISSUE THREAD

**Issue by davidwarford** [google/filament#3274]
So I am trying to build  a basic object pool for gltf instanced assets. However the filamentAsset only provides a way to get all of the entities at once, but it seems there is no way to tell which of those entities belong to which instance. If i could get a list of instances from an asset it would be trivial, alternatively there may be some method to the way entities are layed out that i just don't know yet. What is the intended way to handle something like this?

**Comment by prideout** [comment]
`FilamentInstance` has a `getEntities()` method.

**Comment by davidwarford** [comment]
Yes it does. But how do I get those instances?

**Comment by prideout** [comment]
Ah, I see.  We could add a `getInstances()` to make this easier.  For now, yes, you'll need to keep your own list of `FilamentInstance`.

By the way, PR contributions are welcome :)

**Comment by davidwarford** [comment]
I might consider doing that when I get more familiar. Filament is a really cool project and I hope to use it in many of my projects in the future =)

**Comment by davidwarford** [comment]
havn't been able to test yet but the getInstances() function IS in the jsbindings file. So the only thing keeping me from using it then is that it's not in the .d.ts file. I will test later today (code is in a broken state can't test easily) to see if that works and will submit a pull request if it does.

**Comment by davidwarford** [comment]
So I tested a while ago and the only issue is that it is not included to the .d.ts file, also the function returns a vector and not a javascript array because it is not in the jsbindings. However as of this comment I am going to close the issue.
