### ISSUE TITLE
sumsung s10 phone load video crash,anyone can help me ?

### ISSUE THREAD

**Issue by steven-gao** [google/filament#3278]
**Describe the bug**
i load a video into my  ar scene crashed on my s10 phone,but the same code is work on huawei mate20x

**To Reproduce**
1.load video 
`Material.builder().setSource(activity, GetSceneformResource(activity, VIEW_RENDERABLE_MATERIAL))
                .build()
                .thenAccept(
                        { material ->

                            var vertices = arrayListOf<Vertex>()
                            vertices.add(Vertex.builder().setPosition(Vector3(-0.5f, 0.0f, 0.0f))
                                    .setNormal(Vector3(0.0f, 0.0f, 1.0f))
                                    .setUvCoordinate(Vertex.UvCoordinate(0.0f, 0.0f))
                                    .build())

                            vertices.add(Vertex.builder().setPosition(Vector3(0.5f, 0.0f, 0.0f))
                                    .setNormal(Vector3(0.0f, 0.0f, 1.0f))
                                    .setUvCoordinate(Vertex.UvCoordinate(1.0f, 0.0f))
                                    .build())

                            vertices.add(Vertex.builder().setPosition(Vector3(-0.5f, 1.0f, 0.0f))
                                    .setNormal(Vector3(0.0f, 0.0f, 1.0f))
                                    .setUvCoordinate(Vertex.UvCoordinate(0.0f, 1.0f))
                                    .build())

                            vertices.add(Vertex.builder().setPosition(Vector3(0.5f, 1.0f, 0.0f))
                                    .setNormal(Vector3(0.0f, 0.0f, 1.0f))
                                    .setUvCoordinate(Vertex.UvCoordinate(1.0f, 1.0f))
                                    .build())

                            var triangleIndices = arrayListOf<Int>()

                            triangleIndices.add(0)
                            triangleIndices.add(1)
                            triangleIndices.add(2)
                            triangleIndices.add(1)
                            triangleIndices.add(3)
                            triangleIndices.add(2)

                            var submesh = RenderableDefinition.Submesh.builder().setTriangleIndices(triangleIndices)
                                    .setMaterial(material).build()

                            var ulCorner = ModelRenderable.builder().setSource(
                                    RenderableDefinition.builder().setVertices(vertices)
                                            .setSubmeshes(Arrays.asList(submesh)).build()).build()

                            ulCorner.thenAccept({ renderable ->
                                renderable.getMaterial().setExternalTexture("viewTexture", texture)
                                if (!mediaPlayer.isPlaying) {
                                    mediaPlayer.start()
                                    texture.surfaceTexture.setOnFrameAvailableListener {
                                        surfaceTexture: SurfaceTexture ->
                                        this.renderable = renderable
                                    }
                                }
                            })
`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  macos
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: sumsung model:SM-G9730
 - OS: Android Pie 9.0

**Additional context**
can anyone help me ?

**Comment by steven-gao** [comment]
the log i had catch these:
2020-11-11 14:14:48.562 6814-7090/com.whyhow.sucailib A/whyhow.sucaili: java_vm_ext.cc:542]   native: #10 pc 000570d5  /data/app/com.whyhow.sucailib-yU_hMat5RSxHXi7sm2XW3Q==/lib/arm/libfilament-jni.so (???)
2020-11-11 14:14:48.640 6814-7090/com.whyhow.sucailib A/whyhow.sucaili: runtime.cc:574] #28 pc 000570d5  /data/app/com.whyhow.sucailib-yU_hMat5RSxHXi7sm2XW3Q==/lib/arm/libfilament-jni.so (???)
2020-11-11 14:14:48.705 7267-7090/? E/DEBUG:     28 pc 000570d5  /data/app/com.whyhow.sucailib-yU_hMat5RSxHXi7sm2XW3Q==/lib/arm/libfilament-jni.so
2020-11-11 14:14:48.736 7267-7090/? E/DEBUG: /data/app/com.whyhow.sucailib-yU_hMat5RSxHXi7sm2XW3Q==/lib/arm/libfilament-jni.so: f0ea41d366fe91d0561682a81042f26b73aa901a
2020-11-11 14:14:48.736 7267-7090/? E/DEBUG: /data/app/com.whyhow.sucailib-yU_hMat5RSxHXi7sm2XW3Q==/lib/arm/libfilament-jni.so: f0ea41d366fe91d0561682a81042f26b73aa901a

**Comment by romainguy** [comment]
What version of Filament are you using? Could you also show the entire crash logs please? Important bits are missing

**Comment by steven-gao** [comment]
the version is 1.7.0, Can only catch so many logs，sorry for this .and thank you for your time.

**Comment by steven-gao** [comment]
> What version of Filament are you using? Could you also show the entire crash logs please? Important bits are missing

the version is 1.7.0, Can only catch so many logs，sorry for this .and thank you for your time.

**Comment by romainguy** [comment]
Please try with Filament 1.9, we fixed several JNI bugs that could explain your crash from what I can see.
