### ISSUE TITLE
Output gamma is very different with post-processing on or off

### ISSUE THREAD

**Issue by rawnsley** [google/filament#3280]
On Android it is very useful to disable post-processing for low-end devices as it practically doubles the frame rate, but without the tone mapping pass the output is very dark.

**Post Processing On**
![postProcessingOn](https://user-images.githubusercontent.com/303516/98831078-02923380-2433-11eb-8eb9-63488aad3a46.png)

**Post Processing Off**
![postProcessingOff](https://user-images.githubusercontent.com/303516/98831103-08881480-2433-11eb-833b-37ddf3a684bf.png)

Are there any obvious workarounds for boosting the darker view without a second pass of all the pixels? I'm presuming it's because the output buffer is in linear color space and we are relying on the a post-processing pass to map it to sRGB, in which case could we use something like GL_FRAMEBUFFER_SRGB?

**Comment by romainguy** [comment]
With newer versions of Filament you should simply use the linear tone mapper on the `ColorGrading` API to achieve what you want (and turn off all other post-processing options). Using `GL_FRAMEBUFFER_SRGB` brings a host of other issues we'd rather avoid.
