### ISSUE TITLE
Some models are rendered distorted in filament 1.9.x

### ISSUE THREAD

**Issue by SGTjeong** [google/filament#3282]
**Describe the bug**
 Our 3d animated models have been rendered correctly in filament 1.7.0, but are dented weirdly in 1.9.x. We have tested in Babylon,  Three.js, and there wasn't any problem.

**To Reproduce**
1. Tried with 1.9.0, 1.9.3, 1.9.8, and we could see some models are not rendered correctly.
2. Rolled back to 1.7.0, and there wasn't any problem

**Expected behavior**

**Screenshots**
![Screenshot_20201112-115627_MxxrTest170](https://user-images.githubusercontent.com/57657823/98890576-a802e100-24df-11eb-8b62-758dcb7e2172.jpg)
![Screenshot_20201112-115656_MxxrTest193](https://user-images.githubusercontent.com/57657823/98890588-ac2efe80-24df-11eb-8ad9-dfe32280161b.jpg)
[](url)

**Comment by romainguy** [comment]
Could you please share the model? Or a model that reproduces this behavior?

**Comment by SGTjeong** [comment]
https://cdn-dev.qrio.link/upload/converted/3dfd0928-2129-43f2-8b7c-8e59b37b8acb.glb

Here's the url for the model above.

Thanks!

**Comment by prideout** [comment]
I see "access denied" when I click the link.  You should be able to attach a zip to the issue.

**Comment by SGTjeong** [comment]
@prideout 
 Oh yeah, that url expires in 3 day. I attached a zip. Thanks.

[arachi_surprise.zip](https://github.com/google/filament/files/5550722/arachi_surprise.zip)

**Comment by prideout** [comment]
Thanks!  It is difficult for me to see the problem, the animation in Filament looks similar to what I see in ThreeJS:


![Screen Recording 2020-11-17 at 10 52 01 AM](https://user-images.githubusercontent.com/1288904/99434937-474f1c00-28c4-11eb-8126-fc4cb105cd5a.gif)


I noticed that some of the weights do not add up to 1.0.  One thing we changed to improve load time is that weight re-normalization is now opt-in; search for `normalizeSkinningWeights` in the API.

**Comment by SGTjeong** [comment]
Yeah, I am a bit confused because when we tested this model in filament web there wasn't any problem.

As you pointed out, we are aware of some weights not adding up to 1.0. We're gonna fix it, and test it again.

And if you don't mind could you test the model on android please?

**Comment by SGTjeong** [comment]
@prideout ,

Thanks for suggesting me to check out `normalizeSkinningWeights`. We could solve the issue by forcing resourceloader to normalize skinning weights.

I have one more question, sir. 

When I looked at the code from `ResoucreLoader.cpp`, 

```
  auto normalize = [](cgltf_accessor* data) {
        if (data->type != cgltf_type_vec4 || data->component_type != cgltf_component_type_r_32f) {
            slog.w << "Cannot normalize weights, unsupported attribute type." << io::endl;
            return;
        }
        uint8_t* bytes = (uint8_t*) data->buffer_view->buffer->data;
        float4* floats = (float4*) (bytes + data->offset + data->buffer_view->offset);
        for (cgltf_size i = 0; i < data->count; ++i) {
            float4 weights = floats[i];
            float sum = weights.x + weights.y + weights.z + weights.w;
            floats[i] = weights / sum;
        }
    };
```

 I guess `normalize` function above is normalizing weights assuming that weight per vertex(max influence) are 4. Am i correct?
What happen if our gltf model doesn't limit max influence to 4, let's say max influence is 8.  Is Fliament able to render the model?

**Comment by prideout** [comment]
Thanks, I'm glad that `normalizeSkinningWeights` fixed the issue for you.

As per the documentation for `RenderableManager::skinning`, Filament supports up to 255 bones but only 4 bones may be used simultaneously.  The following language can be found in the glTF specification:

```
client implementations are only required to support a single set of up to four weights and joints
```
