### ISSUE TITLE
Render on image 

### ISSUE THREAD

**Issue by GrigorySamokhin** [google/filament#3283]
Hello! 

Globally I'm trying to create a cross platform example for processing a frame for drawing a .glb 3d emoticon on face as shown in the image. 
![](https://sun9-17.userapi.com/BX2EmaxEzDbZS3aIFmKZfUlBrWf5uXc75N0XDw/tar8Ys5pFxM.jpg)

Can you please provide or write a pure console example (with the simplest setup), that can do the following:
1) Load image.
2) Load a 3D object (shape & texture) from a file, glb probably.
3) Render the object with some camera and some scene into an image .
3) Save the image into file.
I don't find anything somehow similar, thanks!

**Comment by romainguy** [comment]
We have several samples that show how to load glTF files, render objects, save images, etc. We are however not going to build a sample that is as specific as you are describing :)
