### ISSUE TITLE
I don't understand the color space logic in mipgen

### ISSUE THREAD

**Issue by rawnsley** [google/filament#3284]
I'm using mipgen to convert sRGB PNG images to ETC2 compressed textures. My expectation is that if I create an sRGB ETC2 texture the pixel levels will basically stay the same (plus some compression noise), but actually they are lower because it converts them from linear to sRGB space.

I can fudge it by either creating RGB ETC2 textures or by applying the `--linear` argument, which forces the pixels through `fromLinearToRGB` rather than `fromLinearTosRGB` in a twist of logic that doesn't seem to make sense.

I would expect mipgen to read the color space from the PNG file and apply the appropriate pixel value scaling depending on the output format color space requested (linear2linear, linear2srgb, srgb2srgb, srgb2linear).

_I love mipgen by the way - it's incredibly useful_

**Comment by romainguy** [comment]
`--linear` is oddly enough used for two things: interpret source data as linear and export data as linear.

**Comment by romainguy** [comment]
See issue #2422
