### ISSUE TITLE
 Error when importing a glb file with blendshape animation

### ISSUE THREAD

**Issue by GiorgioCarosi** [google/filament#3285]
Hi everyone, I'm new to github. I am using filament for a project where a 3d model (glb format) is implemented.
Inside my avatar I have inserted different blend shapes for the various facial expressions. Not knowing how to access blendshape values. To solve the problem I created shape keys animations, but when I import the model on filament the system crashes without giving me an error. Note that the same model is working on filament v 1.6.0, using the loadModelGlb function. I'm currently working on 1.9.8 (also on 1.9.7). 

I wanted also to know if there is a way to access the blendshapes via script and be able to animate them in a given time frame through a value (ranging from 0 to 1)?

**Comment by romainguy** [comment]
What is the error exactly? Can you share the crash logs please? Note that there is a current limit of 8 blend shapes. See https://github.com/google/filament/issues/1487

**Comment by GiorgioCarosi** [comment]
> What is the error exactly? Can you share the crash logs please? Note that there is a current limit of 8 blend shapes. See #1487


When I load the model on 1.9.8 the app crashes without any errors on the console. We also noticed that debugging the code always crashes when it fetches the animator and the "loadmodel" function. This is a strange fact as mentioned above in version 1.6.0 everything was fine and everything was tested both on emulator and on physical media (xiaomi mi8 google 4 nexus 6). Any idea why the crash?

p.s. At the moment we cannot attach the model due to copyright issues

**Comment by simonepelosi** [comment]
same problem

**Comment by prideout** [comment]
Thanks @simonepelosi -- do you have a repro model or call stack?

**Comment by simonepelosi** [comment]
@prideout this is the console
<img width="1556" alt="Schermata 2020-11-17 alle 11 13 44" src="https://user-images.githubusercontent.com/9490772/99377324-5cc54580-28c6-11eb-831f-07dfb8d6cc7c.png">

**Comment by GiorgioCarosi** [comment]
I think I understand what causes the error: then I have an avatar created by several components, the head and body grouped together. The body is joined to a skeleton while the head is related to the "head" joint of the skeleton (so it is not part of the skeleton binding). I saw the animations of the blend shapes work for me because I only exported the head to test it on filament. The problem is that when I import the file that contains both the skeleton animations and the blend shape animations (shape keys) it crashes giving me the error. Soon I'll pass you a model that makes the same mistake.

Error:

E/Filament: Error opening trace file: No such file or directory (2)
A/libc: /Volumes/Android/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating" failed
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12642 (p.Test1), pid 12642 (p.Test1)


p.s. Su three js il modello le animazione dei blendshape funzionano. Soon I will share a 3d model that shows the same error

**Comment by GiorgioCarosi** [comment]
[AvatarEx.glb.zip](https://github.com/google/filament/files/5560840/AvatarEx.glb.zip)

This is a simplified version of the  3d  model but it gives the same error.

**Comment by prideout** [comment]
Thank you!  I am able to reproduce the issue now.

**Comment by prideout** [comment]
In this model, the `Emote_Happy` animation targets the `Head_Netural` node, which does not belong to any of the scenes.  I think this is technically a legal thing to do, so I will make a fix for this in `gltfio::Animator`.  Thanks for the bug report!

**Comment by simonepelosi** [comment]
Thank you @prideout !

**Comment by GiorgioCarosi** [comment]
thank you @prideout

Il giorno mer 18 nov 2020 alle ore 20:26 Philip Rideout <
notifications@github.com> ha scritto:

**Comment by sunRunFast** [comment]
> Hi everyone, I'm new to github. I am using filament for a project where a 3d model (glb format) is implemented. Inside my avatar I have inserted different blend shapes for the various facial expressions. Not knowing how to access blendshape values. To solve the problem I created shape keys animations, but when I import the model on filament the system crashes without giving me an error. Note that the same model is working on filament v 1.6.0, using the loadModelGlb function. I'm currently working on 1.9.8 (also on 1.9.7).
> 
> I wanted also to know if there is a way to access the blendshapes via script and be able to animate them in a given time frame through a value (ranging from 0 to 1)?

Hello, I would like to ask if you now know how to access the value of blendshape? I have the same problem, thanks for answer
