### ISSUE TITLE
How to add gravity effect to the model

### ISSUE THREAD

**Issue by shivammaindola** [google/filament#3291]
I'm trying to control the bones and add gravity motion to the model. This is how it looks in a blender and I want to implement the same thing in the filament. Is there any way to apply gravity physics to bones?

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/39567362/99221651-f88f7c80-2806-11eb-9b02-ed232fd22dfd.gif)

**Comment by romainguy** [comment]
Hi, Filament is only a rendering engine so you'll have to use a separate physics engine to compute the bone transforms.

**Comment by prideout** [comment]
Filament is a rendering library and physics is outside its scope.  I would suggest investigating a physics library such as Bullet.  At every time step, your application can peek at the transform associated with the Bullet objects, then push those transforms into their corresponding Filament objects (e.g. TransformManager components and skinning matrices).
