### ISSUE TITLE
How to render texture with transparent background(Sprite)

### ISSUE THREAD

**Issue by piusogs** [google/filament#3295]
I am trying to render a textured cube that uses a transparent png image, but it is rendering with a white background, how do I fix this?

![Capture cat](https://user-images.githubusercontent.com/18129257/99307319-9d857600-2856-11eb-9c8b-a0b72ea7a16b.PNG)

I am getting this

![Capture cat 2](https://user-images.githubusercontent.com/18129257/99307387-b4c46380-2856-11eb-95a2-4903d503d139.PNG)

**Comment by romainguy** [comment]
You need to use a material that sets the blend mode to translucent. You also need to make sure to use premultiplied alpha (see the Materials documentation at the end).
