### ISSUE TITLE
Load image

### ISSUE THREAD

**Issue by noseeevil** [google/filament#3297]
Hello! 
I'm writing a sample demo to render gltf model on image, and i can save image (by renderer->readPixels) 
but I can't find any functions to load image to render on, load bytebuffer or something similar.

**Comment by romainguy** [comment]
Filament is only a renderer and does not provide image loaders. You can load an image using whatever APIs are at your disposal in the language you use and feed the resulting bytes to a Texture. If you use C++ you can look at our samples to see how we use stb_image for instance for this purpose.
