### ISSUE TITLE
Crash in renderer destruction on Mac with Metal

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3306]
**Describe the bug**
When I tested minimal startup and shutdown on macOS, using a Metal backend, there is a crash (uncaught objective-C exception) when destroying the renderer.

**To Reproduce**
In a Mac app, try this code, where inTargetView is a pointer to an NSView.

	Engine* engine = Engine::create( backend::Backend::METAL );
	SwapChain* swapChain = engine->createSwapChain( (__bridge void*)inTargetView );
	Renderer* renderer   = engine->createRenderer();
	engine->destroy(renderer);
	engine->destroy(swapChain);
	engine->destroy(&engine);

**Expected behavior**
No errors.

**Actual behavior**
A crash saying "-[NSView setDevice:]: unrecognized selector sent to instance"

**Desktop (please complete the following information):**
 - OS: macOS 11.1 Beta (20C5048k)
 - GPU: Radeon Pro 560X 4 GB
 - Backend: Metal

**Additional context**
If I don't pass the flag `backend::Backend::METAL` to `Engine::create`, letting it use OpenGL, then there is no error.

**Comment by bejado** [comment]
The Metal backend does not use a `NSView` as its native window. You need to pass a `CAMetalLayer` to `createSwapChain`.
