### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by oHuflying** [google/filament#3309]
macos 10.13
**filament** 1.9.9
**Ninja**
➜  filament-main ninja --version
1.10.1

**Clang**
➜  filament-main clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Cmake**
➜  filament-main cmake --version
cmake version 3.18.4

CMake suite maintained and supported by Kitware (kitware.com/cmake)

**Java**
➜  filament-main java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)

Android studio 4.1.1
<img width="497" alt="screen" src="https://user-images.githubusercontent.com/74444849/99908238-6f070f80-2d1c-11eb-870a-c4903b003c68.png">

below is when run build, terminal show, how to fix it, I want use dof effect for android, can everyone give me some sample code:
➜  filament-main ./build.sh -p android release
Building release in out/cmake-release...
[2/34] Building CXX object filament/CM...ment.dir/src/fg/fg/ResourceEntry.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/fg/fg/ResourceEntry.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DFILAMENT_SUPPORTS_METAL -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/ibl/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -fno-stack-check -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/CMakeFiles/filament.dir/src/fg/fg/ResourceEntry.cpp.o -MF filament/CMakeFiles/filament.dir/src/fg/fg/ResourceEntry.cpp.o.d -o filament/CMakeFiles/filament.dir/src/fg/fg/ResourceEntry.cpp.o -c ../../filament/src/fg/fg/ResourceEntry.cpp
In file included from ../../filament/src/fg/fg/ResourceEntry.cpp:19:
../../filament/src/fg/FrameGraph.h:77:46: error: explicit specialization of 'create' in class scope
        FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                             ^
../../filament/src/fg/FrameGraph.h:218:42: error: explicit specialization of 'import' in class scope
    FrameGraphId<FrameGraphRenderTarget> import(const char* name,
                                         ^
../../filament/src/fg/FrameGraph.h:299:42: error: explicit specialization of 'create' in class scope
    FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                         ^
3 errors generated.
[3/34] Building CXX object filament/CM...ment.dir/src/fg/FrameGraphHandle.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DFILAMENT_SUPPORTS_METAL -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/ibl/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -fno-stack-check -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o -MF filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o.d -o filament/CMakeFiles/filament.dir/src/fg/FrameGraphHandle.cpp.o -c ../../filament/src/fg/FrameGraphHandle.cpp
In file included from ../../filament/src/fg/FrameGraphHandle.cpp:21:
../../filament/src/fg/FrameGraph.h:77:46: error: explicit specialization of 'create' in class scope
        FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                             ^
../../filament/src/fg/FrameGraph.h:218:42: error: explicit specialization of 'import' in class scope
    FrameGraphId<FrameGraphRenderTarget> import(const char* name,
                                         ^
../../filament/src/fg/FrameGraph.h:299:42: error: explicit specialization of 'create' in class scope
    FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                         ^
3 errors generated.
[4/34] Building CXX object filament/CM...r/src/fg/FrameGraphPassResources.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/fg/FrameGraphPassResources.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DFILAMENT_SUPPORTS_METAL -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/ibl/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -fno-stack-check -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/CMakeFiles/filament.dir/src/fg/FrameGraphPassResources.cpp.o -MF filament/CMakeFiles/filament.dir/src/fg/FrameGraphPassResources.cpp.o.d -o filament/CMakeFiles/filament.dir/src/fg/FrameGraphPassResources.cpp.o -c ../../filament/src/fg/FrameGraphPassResources.cpp
In file included from ../../filament/src/fg/FrameGraphPassResources.cpp:19:
../../filament/src/fg/FrameGraph.h:77:46: error: explicit specialization of 'create' in class scope
        FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                             ^
../../filament/src/fg/FrameGraph.h:218:42: error: explicit specialization of 'import' in class scope
    FrameGraphId<FrameGraphRenderTarget> import(const char* name,
                                         ^
../../filament/src/fg/FrameGraph.h:299:42: error: explicit specialization of 'create' in class scope
    FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                         ^
3 errors generated.
[5/34] Building CXX object filament/CM.../fg/fg/RenderTargetResourceEntry.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/fg/fg/RenderTargetResourceEntry.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DFILAMENT_SUPPORTS_METAL -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/ibl/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -fno-stack-check -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/CMakeFiles/filament.dir/src/fg/fg/RenderTargetResourceEntry.cpp.o -MF filament/CMakeFiles/filament.dir/src/fg/fg/RenderTargetResourceEntry.cpp.o.d -o filament/CMakeFiles/filament.dir/src/fg/fg/RenderTargetResourceEntry.cpp.o -c ../../filament/src/fg/fg/RenderTargetResourceEntry.cpp
In file included from ../../filament/src/fg/fg/RenderTargetResourceEntry.cpp:23:
In file included from ../../filament/src/fg/fg/PassNode.h:20:
../../filament/src/fg/FrameGraph.h:77:46: error: explicit specialization of 'create' in class scope
        FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                             ^
../../filament/src/fg/FrameGraph.h:218:42: error: explicit specialization of 'import' in class scope
    FrameGraphId<FrameGraphRenderTarget> import(const char* name,
                                         ^
../../filament/src/fg/FrameGraph.h:299:42: error: explicit specialization of 'create' in class scope
    FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                         ^
3 errors generated.
[6/34] Building CXX object filament/CM.../filament.dir/src/fg/fg/PassNode.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/fg/fg/PassNode.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DFILAMENT_SUPPORTS_METAL -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/ibl/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -fno-stack-check -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/CMakeFiles/filament.dir/src/fg/fg/PassNode.cpp.o -MF filament/CMakeFiles/filament.dir/src/fg/fg/PassNode.cpp.o.d -o filament/CMakeFiles/filament.dir/src/fg/fg/PassNode.cpp.o -c ../../filament/src/fg/fg/PassNode.cpp
In file included from ../../filament/src/fg/fg/PassNode.cpp:17:
In file included from ../../filament/src/fg/fg/PassNode.h:20:
../../filament/src/fg/FrameGraph.h:77:46: error: explicit specialization of 'create' in class scope
        FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                             ^
../../filament/src/fg/FrameGraph.h:218:42: error: explicit specialization of 'import' in class scope
    FrameGraphId<FrameGraphRenderTarget> import(const char* name,
                                         ^
../../filament/src/fg/FrameGraph.h:299:42: error: explicit specialization of 'create' in class scope
    FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                         ^
3 errors generated.
[7/34] Building CXX object filament/CM...s/filament.dir/src/fg/FrameGraph.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/fg/FrameGraph.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DFILAMENT_SUPPORTS_METAL -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/ibl/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -fno-stack-check -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/CMakeFiles/filament.dir/src/fg/FrameGraph.cpp.o -MF filament/CMakeFiles/filament.dir/src/fg/FrameGraph.cpp.o.d -o filament/CMakeFiles/filament.dir/src/fg/FrameGraph.cpp.o -c ../../filament/src/fg/FrameGraph.cpp
In file included from ../../filament/src/fg/FrameGraph.cpp:17:
../../filament/src/fg/FrameGraph.h:77:46: error: explicit specialization of 'create' in class scope
        FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                             ^
../../filament/src/fg/FrameGraph.h:218:42: error: explicit specialization of 'import' in class scope
    FrameGraphId<FrameGraphRenderTarget> import(const char* name,
                                         ^
../../filament/src/fg/FrameGraph.h:299:42: error: explicit specialization of 'create' in class scope
    FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                         ^
3 errors generated.
[11/34] Building CXX object filament/CMakeFiles/filament.dir/src/Engine.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/Engine.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DFILAMENT_SUPPORTS_METAL -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/ibl/include -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -fno-stack-check -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/CMakeFiles/filament.dir/src/Engine.cpp.o -MF filament/CMakeFiles/filament.dir/src/Engine.cpp.o.d -o filament/CMakeFiles/filament.dir/src/Engine.cpp.o -c ../../filament/src/Engine.cpp
In file included from ../../filament/src/Engine.cpp:37:
In file included from ../../filament/src/details/View.h:34:
In file included from ../../filament/src/details/ShadowMapManager.h:32:
../../filament/src/fg/FrameGraph.h:77:46: error: explicit specialization of 'create' in class scope
        FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                             ^
../../filament/src/fg/FrameGraph.h:218:42: error: explicit specialization of 'import' in class scope
    FrameGraphId<FrameGraphRenderTarget> import(const char* name,
                                         ^
../../filament/src/fg/FrameGraph.h:299:42: error: explicit specialization of 'create' in class scope
    FrameGraphId<FrameGraphRenderTarget> create(const char* name,
                                         ^
3 errors generated.
ninja: build stopped: subcommand failed

**Comment by romainguy** [comment]
I don't understand that error. We don't have this issue on macos with effectively the same setup. Could you show the full output of the build.sh command? Make sure to run build.sh -c first. Also for Android you may want to use the AARs we publish on Maven Central. It's much easier.

**Comment by oHuflying** [comment]
I update macos 10.13 to 10.15, build successfully.
