### ISSUE TITLE
cmake error on macOS

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3310]
**Describe the bug**
When I tried to run cmake on macOS, I got an error that I don't understand.

Input:

    cmake ../filament -DFILAMENT_ENABLE_JAVA=OFF -DFILAMENT_SUPPORTS_METAL=ON -DFILAMENT_SKIP_SAMPLES=OFF

Output:

    -- DFG LUT size set to 128x128
    -- No Vulkan SDK was found, using prebuilt MoltenVK.
    -- No build type selected, default to Debug
    CMake Error at third_party/spirv-cross/tnt/CMakeLists.txt:23 (message):
     Build out of tree to avoid overwriting Makefile

My working directory is not in the filament tree, so I don't know what "build out of tree" could mean.

**Desktop**
 - OS: macOS 11.1 Beta (20C5048k)
 - GPU: Radeon Pro 560X 4 GB

**Comment by romainguy** [comment]
This is something we had to do because of assumptions in spirv tools if I remember correctly. Please build in a directory placed in the filament folder (we use filament/out for instance).

**Comment by jwwalker** [comment]
I tried going into a subfolder of my own creation and then using `cmake .. <options>` and I got the same error.

**Comment by romainguy** [comment]
This is exactly what our build.sh script does. It's also what CLion does when building from that IDE. Not sure what the difference would be. What version of CMake do you use?

**Comment by jwwalker** [comment]
I'm using cmake 3.19.0

**Comment by jwwalker** [comment]
@romainguy  Regarding your comment "This is exactly what our build.sh script does.", if I say

    ./build.sh -m -i -j debug

then I get the same message about building out of tree, but without `-m` it works.

**Comment by jwwalker** [comment]
P.S. the reason I'm trying to do this is I would like to see the Makefiles.

**Comment by romainguy** [comment]
Interesting, we never use Makefiles anymore. It was only supporter because of CI limitations. We use ninja instead.
