### ISSUE TITLE
Forum or mailing list

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3311]
I wish Filament had a forum or mailing list where I could ask possibly-stupid questions without having to formulate them as bug reports.

**Comment by davidwarford** [comment]
Can agree with this. I'll add to the potential list with a discord or IRC or an official Reddit page. right now i have a few issues that were meant to just be questions which are now actual issues which could get confusing for the project maintainers. If we had a Reddit or something I could ask a question and if it raised suspicion of a bug or required a new feature i could then make a proper issue.

**Comment by xumo** [comment]
I agree. I just need to ask questions that I think would just generate garbage as issues.

**Comment by bejado** [comment]
We've just enabled GitHub discussions: https://github.com/google/filament/discussions

**Comment by davidwarford** [comment]
Thank you!
