### ISSUE TITLE
Possible to use MediaPlayer with Filament's Streams?

### ISSUE THREAD

**Issue by MarkMurillo** [google/filament#3316]
Hi, I'm trying to display a video feed on a rendered quad using Filament. I noticed that in the streams example, it takes in an external texture, where a SurfaceTexture is rendering to. The MediaPlayer also uses SurfaceTexture so I was wondering if they could work together. The current workflow im trying to do to set this up is as follows:

1. create an external texture using the calls
```
GLES30.glGenTextures()
GLES30.glBindTexture()
```
which give me a texture id.

2. load the .mp4 video file using `MediaPlayer` and set it's surface using a `SurfaceTexture` created by using the texture id created in (1)

3. Create a new filament `Stream` and pass it the same texture id created in (1).

4. Create a new filament `Texture` and pass in the stream created in (3) to `setExternalStream` call for the new Texture.

5. Create a new material instance and pass in the texture created in (4) to the samplerExternal parameter

6. Create the quad mesh and use the material instance created in (5)

7. Add the quad renderable created in (6) to the scene and render

The quad currently displays black, and im not sure what's wrong. Is there an existing example of using MediaPlayer along with filament?

Current material used:
```
material {
    name : exttextured,
    shadingModel : unlit,
    blending : opaque,
    parameters : [
        {
            type : samplerExternal,
            name : videoTexture
        }
    ],
    requires : [
        uv0
    ]
}
fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor.rgb = inverseTonemapSRGB(texture(materialParams_videoTexture, getUV0()).rgb);
    }
}
```

Current `createExternalTexture()` implementation:
```
fun createExternalTextureId(): Int = IntArray(1)
    .apply { GLES30.glGenTextures(1, this, 0) }
    .first()
    .apply { GLES30.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, this) }
```

**Comment by romainguy** [comment]
That should work just fine. The problem might be how you are creating your GL context. It could also be in how you're driving the MediaPlayer?

**Comment by MarkMurillo** [comment]
Figured out the problem. It was building the stream prematurely in a sense that the MediaPlayer was returning bad values for the video width/height because it wasn't ready yet. So the stream was setting the width and height to -1. Thanks anyways!
