### ISSUE TITLE
Can you provide examples of rendering bitmap as texture for 2D images?

### ISSUE THREAD

**Issue by oHuflying** [google/filament#3320]
I'm studying OpenGL and Google Filament, Because just started to learn graphics, I don't know how to use this library to draw a rectangle on the android screen and the local bitmap as texture rendering on the rectangle, I saw the wallpaper demo render colors to skybox, but doesn't seem to support bitmap. other cases are triangular or cube, I try to modify texture in the triangle of code, but the picture does not show, just a grey triangle, can you provide the code, how to use bitmap as texture rendering it in rectangular or full screen?

**Comment by Avtar-Code-Farm** [comment]
Hey @oHuflying  I am in same boat. Did you find any reference? I have learned OpenGL and able to draw basic things using OpenGL. From last one week, I am trying to put together a minimal example of a C++ program (OSX) that uses filament and draw a triangle with some texture on it. 

It would be great if you can share the project which does simple rendering using filament. 

Also, if there is any tutorial available as didn't find any reference document on how to do accomplish X using filament.
