### ISSUE TITLE
macOS main thread checker violations

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3321]
**Describe the bug**
When trying to use Filament under the Xcode debugger, the method `PlatformCocoaGL::makeCurrent` produces a runtime error message

    Main Thread Checker: UI API called on a background thread: -[NSView bounds]

and if I let it run further it also complains that `-[NSView convertRectToBacking:]` should only be used on the main thread.  This is happening in a thread called `Engine::loop`.

I was trying to get Filament to work on macOS without SDL by imitating the project at iOS/samples/hello-triangle.

**Desktop:**
 - OS: macOS Big Sur 11.1 Beta (20C5048k)
 - GPU: Radeon Pro 560X 4 GB
 - Backend: OpenGL

**Additional context**
Xcode 12.3 beta

**Comment by bejado** [comment]
This should have been fixed with https://github.com/google/filament/pull/3273. You may have to wait for the fix to make it into the next release or build Filament yourself.

**Comment by jwwalker** [comment]
@bejado No, I did build from source.  That revision made thread-safety changes in `PlatformCocoaGLImpl::updateOpenGLContext`, whereas I am talking about `PlatformCocoaGL::makeCurrent`.

**Comment by bejado** [comment]
`makeCurrent` calls `updateOpenGLContext`, which is why I suspect it's the same bug.

**Comment by jwwalker** [comment]
@bejado Looks like a similar bug, but not the same.  Comments in `updateOpenGLContext` say it's trying to make sure that the methods `-[NSOpenGLContext setView:]` and `-[NSOpenGLContext update]` are called only from the main thread, and that this is a "hard requirement" as of macOS 10.15.  Whereas my bug is about methods of `NSView`, and maybe it's not a hard requirement.

**Comment by bejado** [comment]
Modifying our calls to `convertRectToBacking` and `bounds` so that they happen synchronously on the main thread drastically hurts performance. Given that these don't seem to be hard requirements and that OpenGL is deprecated on macOS anyway, I don't think this will be a priority for us to fix.

**Comment by jwwalker** [comment]
@bejado Of course I wouldn't have expected you to just synchronously do it on the main thread.  A more reasonable approach would be to subscribe to notifications of frame geometry updates, and when such a notification is received (on the main thread), cache the bounds.  It looks like `NSViewFocusDidChangeNotification` would be the best notification, though for some reason it's deprecated.
