### ISSUE TITLE
Foreground

### ISSUE THREAD

**Issue by noseeevil** [google/filament#3324]
hello!
How can I set my custom UI/Foreground? (like the pucture)

<img width="810" alt="Снимок экрана 2020-12-01 в 13 56 22" src="https://user-images.githubusercontent.com/16321108/100732569-f1a76300-33dd-11eb-9cb5-a1ec3b0650a9.png">

Should I create some geometry, and apply some material with texture?
or maybe exist another way?

**Comment by romainguy** [comment]
You can either use a 2nd (transparent/blended) view on top or you can draw your UI in device domain by turning off depth testing.
