### ISSUE TITLE
Blending and transparency: completely transparent material is still used in final result.

### ISSUE THREAD

**Issue by roxlu** [google/filament#3325]
I've got this 3D model (image 1) and I've got a material with an alpha parameter. I use the alpha parameter to fade away the walls of the building. I also animate the Y position of the walls so that they animate a bit upwards while fading out [as you can see in this video](https://imgur.com/a/dZZ7ryS). Once the alpha has been animated to zero the meshes are still used in the final result as you can see in the second image.

Am I doing something wrong or could this be a bug?

![image](https://user-images.githubusercontent.com/358809/100754465-6d5bdc80-33eb-11eb-8a92-172eeb102091.png)
*image 1*

![image](https://user-images.githubusercontent.com/358809/100754630-954b4000-33eb-11eb-95ee-6ceb23eb6439.png)
*image 2*

The mesh of the walls:
![image](https://user-images.githubusercontent.com/358809/100755673-ba8c7e00-33ec-11eb-9e02-d38c6932e5e0.png)
*image 3*

The material I'm using:

```js
material {
    name: color,
    shadingModel: lit,
    blending: fade,
    transparency: twoPassesOneSide,
    parameters: [
        { type: sampler2d, name: albedo },
        { type: float, name: roughness },
        { type: float, name: metallic },
        { type: float, name: alpha }
    ],
    requires: [
      uv0
    ]
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = texture(materialParams_albedo, getUV0());
        material.baseColor.rgb = material.baseColor.rgb * material.baseColor.a * materialParams.alpha;
        material.baseColor.a = material.baseColor.a * materialParams.alpha;
        material.roughness = materialParams.roughness;
        material.metallic = materialParams.metallic;
    }
}
```

**Comment by romainguy** [comment]
I'm not sure I understand what you expect to see in the second image. Is the roof supposed to disappear as well?

**Comment by roxlu** [comment]
Thanks for your reply @romainguy. Currently part of the roof becomes transparent/hidden which I don't want. My goal is to move the building/walls a bit up and fade it to completely transparent so that only the roof is visible. 

In this screenshot I'm *not* fading the side walls so you can see how I move the building/walls a bit upwards:

![image](https://user-images.githubusercontent.com/358809/100776667-195df180-3405-11eb-9856-20c393aa7cc5.png)

But when I make the building/walls completely transparent, it somehow "hides" parts the roof where the walls are in front of the roof. I think it's more clear in this screenshot, it's like the walls are masking the roof:

![image](https://user-images.githubusercontent.com/358809/100777007-86718700-3405-11eb-9a03-0a5d00272e0d.png)

And another screenshot where you also can see how the chimneys are "masking" the roof:

![image](https://user-images.githubusercontent.com/358809/100777158-bae54300-3405-11eb-9e80-c7415556c07a.png)

I hope this explains the issue a bit better, if not I'll add some code where I can toggle the transparency instead of animating it.

**Comment by romainguy** [comment]
The only reason why this may happen is if your roof is also blended. `twoPassesOneSide` (that you use for the walls) writes to the depth buffer which can occlude any other transparent object. Can you check what material you use for the roof?

**Comment by roxlu** [comment]
I'm not behind my pc atm but its blended to, I'm only not sure what type. 

How can I accomplish what I'm trying to do?

**Comment by romainguy** [comment]
Does it need to be blended? If yes, then you can change the roof's render priority to make sure it draws before the walls.

**Comment by roxlu** [comment]
Thanks @romainguy, I want the roof to blend similarly as the walls. 

I can imagine that changing the priority works in this case but when I want to fade out any arbitrary mesh changing the priority won't really work or does it? 

Btw, it's amazing how quick you always reply to issues, thanks for that!

**Comment by romainguy** [comment]
That's the problem with transparency. Until (if… :) we implement order-independent transparency (which is expensive), there is no good way to handle multiple overlapping transparent objects. You can play tricks with the bounding boxes as well to force a particular ordering but the render priority is easier to manage. You could also instead render the meshes individually to offscreen textures and fade that instead.

**Comment by roxlu** [comment]
Thanks for all the suggestions.  Changing the priority fixed this issue but introduces some other issues. 

I was thinking to change the blending at runtime, but I didn't find a function that allows me to do that. I assume there is a good reason for this. Would it be possible to add this?

**Comment by romainguy** [comment]
The problem is that it also affects the shader code. We could allow blending to be overridden but it would have caveats (for instance shaders being more expensive when you go from transparent to opaque, or shaders not doing what you want when going from opaque to transparent).

**Comment by roxlu** [comment]
I understand what you mean. 

Tomorrow I'm going to hide the renderables once their alpha becomes zero and make them visible again when their alpha gets higher than zero. I'll use the layer mask feature for that. It's not perfect but flexible and as the animations will take about 150-250 millis it might be unnoticeable.
