### ISSUE TITLE
macOS samples?

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3329]
Is there any desire for contributions of macOS-specific samples, similar to the samples in ios/samples?  So far I have built a macOS project by imitating ios/samples/hello-triangle.

**Comment by prideout** [comment]
I'm not sure if that's really necessary since everything in `filament/samples`, such as `hellotriangle.cpp` and `hellopbr.cpp` already build & run on macOS.

**Comment by jwwalker** [comment]
@prideout I guess that's reasonable.  The iOS samples seemed more inviting to me because they had Xcode projects, which is what I'm used to.  And it wasn't immediately obvious to me whether the general samples would be using OpenGL or Metal.  But I'll take another look at them.

**Comment by romainguy** [comment]
The general samples can use both (some of them have a command line flag to use Metal over OpenGL).

**Comment by jwwalker** [comment]
> The general samples can use both (some of them have a command line flag to use Metal over OpenGL).

A possible way to make it easier to specify the backend of the general samples would be to modify `libs/filamentapp/include/filamentapp/Config.h` by inserting

    #ifndef FILAMENTAPP_CONFIG_BACKEND
        #define FILAMENTAPP_CONFIG_BACKEND DEFAULT
    #endif

and then in the `Config` structure saying

    filament::Engine::Backend backend = filament::Engine::Backend::FILAMENTAPP_CONFIG_BACKEND;

If that sounds useful, I could turn it into a pull request.
