### ISSUE TITLE
Gltf object behind model with occluder material still visible

### ISSUE THREAD

**Issue by Miao-10k** [google/filament#3331]
I first loaded a gltf object which is a room and another gltf object which is a container of the room that is a little bit larger than the room such that I can put the room totally inside the container.
This is the room:
![image](https://user-images.githubusercontent.com/32147896/100860036-f1d15c80-34ca-11eb-8d16-011b29b66792.png)

This is the container:
![image](https://user-images.githubusercontent.com/32147896/100860096-06adf000-34cb-11eb-946e-43e03c61e105.png)

Then I change the material of the container to an occluder material and set the render priority to camera > container > room. I suppose that the container would occlude the room so that I can achieve something like a portal. But the fact is while the container itself looks like invisible, the outside of the room is not occluded。
This is my Occluder Material:
```
material {
    "name" : "Face Mesh Occluder",
    "parameters" : [
        {
            "type" : "float",
            "name" : "unused"
        }
    ],
    "shadingModel" : "unlit",
    "colorWrite" : false,
    "depthWrite" : true,
}
```

This is what I expect:
![WechatIMG26](https://user-images.githubusercontent.com/32147896/100865787-c3f01600-34d2-11eb-902a-f1a9be9b1f14.jpeg)

This is what I get:
![WechatIMG25](https://user-images.githubusercontent.com/32147896/100865800-c7839d00-34d2-11eb-8c94-eb58cdd8e62e.jpeg)

I am using filament with the open-source sceneform 1.6.0 on android devices. The gltf object is loaded by gltfio and I only use the filament way to change the material. I'm not sure if this is a bug. I suspect this problem may be related to the material generated by gltfio. I've gone through other issues about occlusion material but didn't get a solution. Hope can get some help here.

**Comment by romainguy** [comment]
The only thing I can think of is that your render priority is inverted, lower priorities (lower numbers) are rendered first.

**Comment by Miao-10k** [comment]
Hi @romainguy,
I set the render priority as following camera = 0, container = 4, room = 7. So I think this may not the reason.
I forgot to mention that I tried to change the material of all the entities of the room to sceneform_opaque_textured_material.filamat. Although the texture is not rendered correctly in this case, I noticed that some part of the room is occluded while other parts are still not occluded from some angle. That's why I suspect its about the material generated by gltfio.
This is sceneform_opaque_textured_material:
```
material {
    "name" : "Opaque Textured",

    "parameters" : [ 
        {
           "type" : "sampler2d",
           "name" : "texture"
        },
        {
           "type" : "float",
           "name" : "metallic"
        },
        {
            "type" : "float",
            "name" : "roughness"
        },
        {
            "type" : "float",
            "name" : "reflectance"
        }
    ],
    "requires" : [
        "position",
        "uv0"
    ],
    "shadingModel" : "lit",
    "blending" : "opaque"
}
fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = texture(materialParams_texture, getUV0());
        material.metallic = materialParams.metallic;
        material.roughness = materialParams.roughness;
        material.reflectance = materialParams.reflectance;
    }
}

```

This is what I get with occluder material for the container, sceneform_opaque_textured_material for the room and the same render priority as before:
![WechatIMG28](https://user-images.githubusercontent.com/32147896/100957645-cd6e9200-3555-11eb-8cd5-1e20d9c669a6.jpeg)

**Comment by Miao-10k** [comment]
Hi @romainguy,
I found that actually priority is the cause. I was using sceneform api to set the priority. Although I set the priority number right but I think there may be problems inside the sceneform implementation of setting priority. After changing to filament way to set the priority, everything  just works fine.
I apologize that this is not a filament error and thank you for your support.
