### ISSUE TITLE
Get GPU pointer to image  

### ISSUE THREAD

**Issue by GrigorySamokhin** [google/filament#3333]
Hello, I am developing a cpp shared library that takes an image, applies computer vision algorithms, filament for rendering, and returns it, now to get image to the cpu on an Android device takes 100 ms, is there any way to get a pointer to this image leaving it on the gpu?

**Comment by romainguy** [comment]
What image are you talking about? The result of rendering by Filament? If so, you should create a `SurfaceTexture` and using the `SurfaceTexture`'s `Surface` to render with Filament. This will leave all rendering on the GPU.
