### ISSUE TITLE
Please support glTF PBR Next Phase 1 extension

### ISSUE THREAD

**Issue by cx20** [google/filament#3337]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I tried out the new ToyCar model introduced in the press release of glTF PBR Next with Filament.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ToyCar

However, the sheen part seemed to be unsupported, yet.

[Filament + new ToyCar.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/36cecb758ebddeabdc49209c431f61fe422dfe1e/examples/filament/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/101101118-37953e80-360b-11eb-8ab5-07040190f674.png)

**Describe the solution you'd like**

As stated in the [press release of glTF PBR Next Phase 1](https://www.khronos.org/news/press/khronos-releases-wave-of-new-gltf-pbr-3d-material-capabilities), the ToyCar model uses three extensions.
The three extensions used are `KHR_materials_clearcoat`, `KHR_materials_transmission`, and `KHR_materials_sheen`.
I think Filament already supports two extensions, so I would like to see support for the `KHR_materials_sheen` extension.

https://www.khronos.org/news/press/khronos-releases-wave-of-new-gltf-pbr-3d-material-capabilities
![image](https://user-images.githubusercontent.com/1833979/101101300-98bd1200-360b-11eb-92aa-be46883171a7.png)

**Describe alternatives you've considered**

So far, I think only Babylon.js supports the three extensions. I would be happy if Filament could be supported as well.

**OS and backend**
WebGL

**Comment by romainguy** [comment]
Sheen is not supported yet but planned (we were part of the Khronos discussions on sheen btw, and Filament's "cloth" material model is effectively the sheen model of glTF, we just need to wire things up the right way). We're also adding `_ior` and `_specular`.

**Comment by romainguy** [comment]
Note: we already added support for those extensions to cgltf :)

**Comment by cx20** [comment]
@romainguy  Thank you for supporting this extension. I have confirmed that this feature is now available in the latest build.

[Filament + ToyCar result:](https://rawcdn.githack.com/cx20/gltf-test/b00b236067c1f3e0908881fbd6cccba23091f432/examples/filament/index.html?category=tutorialModels&model=ToyCar&scale=50&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/102000133-6d32d980-3d27-11eb-808e-2367166a746f.png)

BTW, one thing that bothered me was that the result of [SheenCloth](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SheenCloth) seems to be different from the sample. In the sample, the color is `purple`, but the result of Filament is `blue`. Is there something I'm missing?

|Library|result (small)| result (large)|
|:----:|:----:|:----:|
|Sample screenshot|![image](https://user-images.githubusercontent.com/1833979/102000625-b76a8980-3d2c-11eb-988a-e20787e1e3a5.png)||
|[Babylon.js](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/102000634-c81aff80-3d2c-11eb-82a9-df077bb90f7c.png)|![image](https://user-images.githubusercontent.com/1833979/102000639-cd784a00-3d2c-11eb-8681-ed04f1adfe83.png)|
|[Filament](https://rawcdn.githack.com/cx20/gltf-test/b00b236067c1f3e0908881fbd6cccba23091f432/examples/filament/index.html?category=tutorialModels&model=SheenCloth&scale=85&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/102000642-d5d08500-3d2c-11eb-8118-3b89735d95e4.png)|![image](https://user-images.githubusercontent.com/1833979/102000646-db2dcf80-3d2c-11eb-87e3-7a91cd3a064d.png)|

**Comment by romainguy** [comment]
I've noticed differences in how Babylon handles IBLs. I've been chatting with one of the authors already and we couldn't figure out why.

**Comment by romainguy** [comment]
Note that filament assumes the color texture is sRGB as per the spec. Maybe there's a difference here in Babylon?

**Comment by romainguy** [comment]
@cx20 Another thing to check btw is the tone mapping. I believe Babylon.js doesn't tone map by default?

**Comment by romainguy** [comment]
At least Filament seems to match the source texture more closely:

![technicalFabricSmall_basecolor_256](https://user-images.githubusercontent.com/869684/102000810-fa325000-3c9f-11eb-9d63-912a07939e48.png)

The sheen color is purple, as seen in both renderers:

![technicalFabricSmall_sheen_256](https://user-images.githubusercontent.com/869684/102000815-06b6a880-3ca0-11eb-9ffe-5457674ba386.png)

**Comment by romainguy** [comment]
Hmm there may be an issue with how the sheen roughness is applied from glTF file in Filament. Looking deeper…

**Comment by cx20** [comment]
@PatrickRyanMS @bghgary Do you have any advice for us?

**Comment by romainguy** [comment]
It's a bug in our handling of roughness. I'm sampling the wrong channel.

**Comment by romainguy** [comment]
With [the roughness fix](https://github.com/google/filament/commit/eb70fd5dee0f4d1b21577266054d1648e54409f3):

<img width="1304" alt="Screen Shot 2020-12-12 at 6 04 45 PM" src="https://user-images.githubusercontent.com/869684/102001241-8a729400-3ca4-11eb-9d06-bf0adbfa8473.png">

**Comment by cx20** [comment]
Hmm, I tried again with the latest build of Filament. However, not much seems to have changed.
Is it the difference between the native version and the WebGL version? Or is it a difference in settings?

|Library|result (small)| result (large)|
|:----:|:----:|:----:|
|[Filament (before)](https://rawcdn.githack.com/cx20/gltf-test/b00b236067c1f3e0908881fbd6cccba23091f432/examples/filament/index.html?category=tutorialModels&model=SheenCloth&scale=85&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/102000642-d5d08500-3d2c-11eb-8118-3b89735d95e4.png)|![image](https://user-images.githubusercontent.com/1833979/102000646-db2dcf80-3d2c-11eb-87e3-7a91cd3a064d.png)|
|[Filament (after)](https://rawcdn.githack.com/cx20/gltf-test/f1b0e02d93c0d5462903d417c661e8647a838b59/examples/filament/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/102009002-ebb76780-3d77-11eb-99bf-d255b0eb3048.png)|![image](https://user-images.githubusercontent.com/1833979/102009005-f114b200-3d77-11eb-971e-ec30dd1684a1.png)|

I can't decide if this is right or not. It's difficult.
I think it would be nice to have a sample model that can properly validate the Sheen extension.

**Comment by romainguy** [comment]
You can see the difference in sheen roughness between before and after. To better compare with Babylon use the linear tone mapper.

**Comment by cx20** [comment]
> To better compare with Babylon use the linear tone mapper.

Does tone-mapping refer to the following parameters?

![image](https://user-images.githubusercontent.com/1833979/102021836-15977b00-3dc6-11eb-8691-fe61322336bb.png)

I'm trying Filament with WebGL.
Is it possible to set that parameter in Filament's JavaScript API? I tried to look at the [reference](https://google.github.io/filament/webgl/reference.html), but it was not clear.

**Comment by romainguy** [comment]
We need to update the web reference docs I think (@prideout). You can set the tone mapper via the ColorGrading API. See https://github.com/google/filament/blob/main/filament/include/filament/ColorGrading.h

A ColorGrading instance has to be set on the View object to take effect.

**Comment by cx20** [comment]
I have tried the `ColorGrading` API in JavaScript.

```javascript
window.ToneMapping = Filament.ColorGrading$ToneMapping;

const colorGrading = Filament.ColorGrading.Builder()
    .toneMapping(ToneMapping.LINEAR)
    .build(engine);

this.view.setColorGrading(colorGrading);
```

The results are as follows. Initially, it was closer to light blue, so I think the modified result is a little closer to the Babylon.js result.

|Library|result (small)| result (large)|
|:----:|:----:|:----:|
|[Fialment + ToneMapping default](https://rawcdn.githack.com/cx20/gltf-test/f1b0e02d93c0d5462903d417c661e8647a838b59/examples/filament/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/102009002-ebb76780-3d77-11eb-99bf-d255b0eb3048.png)|![image](https://user-images.githubusercontent.com/1833979/102009005-f114b200-3d77-11eb-971e-ec30dd1684a1.png)|
|[Filament + ToneMapping.LINEAR](https://rawcdn.githack.com/cx20/gltf-test/fcb56ed78a33dbb4898b0b22381dc254cfa956c5/examples/filament/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/102100314-a6289680-3e6c-11eb-81b5-65e70da380ae.png)|![image](https://user-images.githubusercontent.com/1833979/102100346-ad4fa480-3e6c-11eb-8dd2-fa30c4b68df6.png)|
|[Babylon.js](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/102000634-c81aff80-3d2c-11eb-82a9-df077bb90f7c.png)|![image](https://user-images.githubusercontent.com/1833979/102000639-cd784a00-3d2c-11eb-8681-ed04f1adfe83.png)|
