### ISSUE TITLE
Spot and Point Lights not working on Linux/OpenGL?

### ISSUE THREAD

**Issue by roxlu** [google/filament#3338]
I'm adding support for spot and point lights in my app and noticed that they didn't show up.  To figure out if I'm doing something wrong in my implementation, I've created a scene in Blender which I've exported to (binary) GLTF. I've attached the [test files](https://github.com/google/filament/files/5641527/light-test-model.zip). Next, I used the `gltf_viewer` app and I'm not seeing the lights there either. 

Screenshot from Blender:

![image](https://user-images.githubusercontent.com/358809/101141699-f6099100-3614-11eb-9713-e592ca66b024.png)

![image](https://user-images.githubusercontent.com/358809/101143181-dbd0b280-3616-11eb-846d-29b006ff9962.png)

Result in `gltf_viewer`:

![image](https://user-images.githubusercontent.com/358809/101141656-e25e2a80-3614-11eb-95be-119ed15b3330.png)

Started like `./gltf_viewer ./assets/models/spotlight-test-v1.glb` using a fresh build.

Output `gltf_viewer`:

```
FEngine (64 bits) created at 0x7f805a70f010 (threading is enabled)
FEngine resolved backend: OpenGL
NVIDIA Corporation, GeForce RTX 2080 SUPER/PCIe/SSE2, 4.1.0 NVIDIA 455.45.01, 4.10 NVIDIA via Cg compiler
OS version: 0
Renderer: Commands High watermark 5 KiB (0%), 160 commands, 32 bytes/command
CircularBuffer: High watermark 54 KiB (1%)
```
System info:

```
$ uname -a
Linux arch2080 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux

$ nvidia-smi 
Fri Dec  4 09:52:50 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   41C    P8    17W / 250W |   1881MiB /  7979MiB |     19%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
```

[light-test-model.zip](https://github.com/google/filament/files/5641527/light-test-model.zip)

*update* I get the same behavior on Windows 10, similar pc specs.

**Comment by romainguy** [comment]
It's most likely an issue of exposure/intensity. Try to disable the directional light in `gltf_viewer` and change the camera exposure. The default settings work for extremely bright outdoors.

**Comment by romainguy** [comment]
Here's a glTF with spot lights working just fine (exposure changed to ƒ/2.8, 1/75s and ISO 500, IBL intensity to 10 and directional light intensity to 18):

<img width="593" alt="Screen Shot 2020-12-04 at 8 29 43 AM" src="https://user-images.githubusercontent.com/869684/101188695-e6854a80-360a-11eb-9e53-01c635fc8250.png">

**Comment by bejado** [comment]
FYI Blender's glTF exporter does not convert units correctly: https://github.com/KhronosGroup/glTF-Blender-IO/issues/564. This results in needing to make the lights extra bright in Blender for them to show up correctly in Filament.

**Comment by roxlu** [comment]
Thanks @bejado and @romainguy  I knew it had to do with those other settings! I thought that disabling the directional light (sun) completely would be enough but that didn't work. I've experimented with the values you suggested (ƒ/2.8, 1/75s and ISO 500, IBL intensity to 10 and directional light intensity to 18) and that works.

Here's a screenshot of another scene with a red and green light:

![image](https://user-images.githubusercontent.com/358809/101216201-61884880-367f-11eb-9ea1-fdbc9111310b.png)

It would we great to have a list with recommended settings for different common environments, It would be great to e.g. have some standard light settings for a morning, midday, afternoon and evening.

**Comment by romainguy** [comment]
You can always use unitless lights and exposure. See https://github.com/google/filament/blob/main/filament/include/filament/Camera.h#L379

By using this API, you can then set your light intensities to be unitless (for instance "1") like you do in Blender, Unity, etc.
