### ISSUE TITLE
The image is darkens

### ISSUE THREAD

**Issue by GrigorySamokhin** [google/filament#3339]
Hello! Im trying to load image from camera, I have adopted hello-ar sample to android via change setExternalImage to setImage. It works but my image is darkens when real one. First is loaded image, second is after Filament render. Where I can be wrong?

![](https://sun9-19.userapi.com/impf/BGW-QIs7AQi79_ULWgLzYosi1xozW-K2iv32xA/F88es5z_iJs.jpg?size=1920x1080&quality=96&proxy=1&sign=d9e4f59e106025af0d306f7f011ce33d)

![](https://sun9-27.userapi.com/impf/4b4Y1zZ6h6zoibKHbJcCfC7vPCjBh5w6aoSaDw/HZozB43iXyU.jpg?size=2340x1154&quality=96&proxy=1&sign=b49ba2540f95bf80e849b74b244f7605)

**Comment by romainguy** [comment]
You need to either disable tone mapping (set the tone mapping to `LINEAR` on the `ColorGrading` API) or inverse tonemap your background texture in your material (see `inverseTonemap()` and `inverseTonemapSrgb()` [in the docs](https://google.github.io/filament/Materials.html)).

**Comment by GrigorySamokhin** [comment]
Change inverseTonemapSrgb to inverseTonemap in camera_feed.mat solve problem, thanks!

**Comment by steven-gao** [comment]
@GrigorySamokhin  draw camera stream as my backgroud failed. so could you give me a copy of your project? 
thans a lot

**Comment by GrigorySamokhin** [comment]
Hello @steven-gao! Sorry, its a product code. Also you can try open camera demo of filament to process Gpu Texture of image

**Comment by GrigorySamokhin** [comment]
In what part do you failed?

**Comment by steven-gao** [comment]
hello,@GrigorySamokhin thanks all the same. I want to know what the camera demo is ,is it ”sample-hello-camer“?
![image](https://user-images.githubusercontent.com/4360916/158331912-d13754b2-b1c5-4da5-9594-f443c60fa9e4.png)

**Comment by GrigorySamokhin** [comment]
Yes, https://github.com/google/filament/tree/main/android/samples/sample-hello-camera, and I use shader and texture of FullSrcreenTriangle from https://github.com/google/filament/blob/main/ios/samples/hello-ar/hello-ar/FilamentArView/FullScreenTriangle.cpp

**Comment by GrigorySamokhin** [comment]
So, I forgot to say, I don't use FilamentApp wrapper

**Comment by steven-gao** [comment]
but i am a android developer,so i read cpp file has  a bit strenuous
