### ISSUE TITLE
Vulkan samples panic when resizing the window

### ISSUE THREAD

**Issue by prideout** [google/filament#334]
I'm hitting a panic with recent NVIDIA driver on Linux: "Stale / resized swap chain not yet supported."

**Comment by prideout** [comment]
Yes I think this is still an issue on Linux although somewhat low priority.  If you'd like we could close this in favor of a task in the Vulkan project.

**Comment by nitronoid** [comment]
Hi there, I'm wondering what the correct procedure for handling a resize is? I had a look at the FilamentApp samples and it seems to be:

1. create a new swap chain?
2. set the viewport size
3. recalculate the projection matrix for our camera based on the new size

As you've said earlier, when using the Vulkan backend, an exception is thrown on resizing. When using OpenGL the above steps work, however it still works fine if I omit step one and continue using the old swap chain.

My question is, what is the correct set of steps to follow, perhaps in preparation for when the issues with Vulkan are fixed?

Thanks

**Comment by romainguy** [comment]
There is indeed no reason to recreate the `SwapChain` if the underlying native window hasn't changed (you didn't get a new pointer).

**Comment by romainguy** [comment]
@prideout @pixelflinger We should fix the samples (or take that into account when we create new ones)

**Comment by prideout** [comment]
Mathias reports that Vulkan-on-macOS also has issues after resizing the window.

**Comment by ebachard** [comment]
Hello,

Just FYI, there is a similar issue with Dear ImGui (vulkan + SDL2  backend). See https://github.com/ocornut/imgui/issues/2626 for further information.

I traced a bit, but I'm not able to solve the issue, and didn't find any serious track. Excepted a workaround, as explained in the issue above.
