### ISSUE TITLE
Is the index offset in bytes or number of indices for RenderableManager::Buildfer::geometry()? 

### ISSUE THREAD

**Issue by roxlu** [google/filament#3351]
I just ran into this `[entity=1, primitive @ 4] offset (48) + count (6) > indexCount (36)`  which is triggered in the `RenderableManager::Builder`: 

```c++
RenderableManager::Builder::Result RenderableManager::Builder::build(Engine& engine, Entity entity) {
        // ....
        // reject invalid geometry parameters
        if (!ASSERT_PRECONDITION_NON_FATAL(entry.offset + entry.count <= entry.indices->getIndexCount(),
                "[entity=%u, primitive @ %u] offset (%u) + count (%u) > indexCount (%u)",
                i, entity.getId(),
                entry.offset, entry.count, entry.indices->getIndexCount())) {
            entry.vertices = nullptr;
            return Error;
        }
        // ....
}
```

The function description says:
```
         * @param offset specifies where in the index buffer to start reading (expressed as a number of bytes)
```

But precondition check assumes offset is specified as an index not in bytes; which makes me wonder if the offset description in the header should be changed/updated.

**Comment by romainguy** [comment]
On this API `offset` is a number of indices, the documentation is incorrect (probably because of a copy paste from other APIs like `VertexBuffer`). Thanks for noticing!
