### ISSUE TITLE
Web: Filament not working on Google Chrome

### ISSUE THREAD

**Issue by andreperezmaselco** [google/filament#3352]
After the last update of Google Chrome, the following errors are being logged on the console.
```
[.WebGL-0x1a5baa513500] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[.WebGL-0x1a5baa513500] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete
```
It can be verified in the Filament website samples.

**Comment by cx20** [comment]
Yes. This issue now occurs on Windows `Chrome 87`.
https://github.com/google/filament/issues/3308

If you don't mind using the Nightly build, you can download it from the following link.
https://github.com/google/filament/actions/runs/397120566

![image](https://user-images.githubusercontent.com/1833979/101783518-b6bfd080-3b3d-11eb-80ac-4a802c072f12.png)

**Comment by andreperezmaselco** [comment]
I'm using Google Chrome on Ubuntu 18.04.
Both `google-chrome-stable` and `google-chrome-beta` do not work.

I am going to try this Filament build that you provided.
Thanks!

**Comment by andreperezmaselco** [comment]
It also works on Ubuntu 18.04.
Thanks!

**Comment by cx20** [comment]
I hadn't tried it on Linux. Thanks for sharing the information.
