### ISSUE TITLE
matc should report and error if input file is empty or if no output file is generated

### ISSUE THREAD

**Issue by davidwarford** [google/filament#3355]
**Is your feature request related to a problem? Please describe.**
Currently, if the input file for matc is empty, no output is generated and matc does not give an explanation

**Describe the solution you'd like**
An error message for empty input `Input file cannot be empty`
and or an error message that tells you no file was outputted `Error: no output file`

**Comment by romainguy** [comment]
Technically an empty input file can produce a valid material, albeit a rather useless one that doesn't do anything :) But yes, we should log this.

**Comment by bejado** [comment]
If given an empty file, `matc` return an error code of 1, but I agree that a message would be helpful.
