### ISSUE TITLE
Occlusion material

### ISSUE THREAD

**Issue by noseeevil** [google/filament#3356]
Hi!
I made simple example in unity, that shows how quad occluded cubes.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/16321108/101833173-a01f7680-3b49-11eb-9473-9992acfffbac.png">

I used a simple shader for it
<img width="935" alt="image" src="https://user-images.githubusercontent.com/16321108/101833115-8c741000-3b49-11eb-875b-d90266ac6e6e.png">

and I’m trying to do the same with use filament:

1) I load "DamagedHelmet.glb"
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/16321108/101833618-4cf9f380-3b4a-11eb-8b74-d9b31e3bd061.png">

2) I create occlusion material 
<img width="885" alt="image" src="https://user-images.githubusercontent.com/16321108/101833763-80d51900-3b4a-11eb-8309-9602d80ba226.png">

3) I create quad, and setup material + renderable manager
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/16321108/101834067-e5907380-3b4a-11eb-9847-28194579381f.png">

4) result if I set RenderableManager::Builder(1).priority(0) for QUAD
<img width="674" alt="image" src="https://user-images.githubusercontent.com/16321108/101834288-3902c180-3b4b-11eb-9049-fe76adc28ae1.png">

5) result if I set RenderableManager::Builder(1).priority(6) for QUAD
<img width="675" alt="image" src="https://user-images.githubusercontent.com/16321108/101834409-618abb80-3b4b-11eb-95a7-0a45949051a0.png">

   What am I doing wrong?

 - OS: macOS 10.15.7 (19H2)
 - Backend: OpenGL

**Comment by romainguy** [comment]
It seems to be working when you set the priority to 0. How do you render the background?

**Comment by romainguy** [comment]
Note: the built-in Skybox object is rendered last (priority = 7), so it will be affected by your depth writes. Which would explain what you showed in step 4 if you are indeed using a Skybox to draw the background.

**Comment by noseeevil** [comment]
Yeah, you’re absolutely right - It's Skybox on the background, thanks for the tip I understand my "problem" =)
maybe it will be useful for somebody else
