### ISSUE TITLE
Where can I find how uniforms are defined in default lit shader?

### ISSUE THREAD

**Issue by SC5Shout** [google/filament#3357]
I'd like to see how uniform buffers are defined for like pbr uniforms. I've found `shaders` folder, but it does not contain informations I need. The project is quite complex and it is hard to find it.

**Comment by romainguy** [comment]
There are no PBR uniforms declared by default. We only generate uniforms declared by the material and that's done by the library called filamat. What information do you need/what are you trying to achieve?

If you want to know what material properties are supported they are all listed in the materials documentation.

**Comment by prideout** [comment]
Also note that we have a "Discussions" tab for questions like this.  :)
