### ISSUE TITLE
1.9.9 pre-built libs for Windows, how to initialize and load GLTF

### ISSUE THREAD

**Issue by pkovacs86** [google/filament#3362]
Hello,

I would like to use 1.9.9 Windows pre-built libraries for loading GLTF file into a scene.
SDL window creation:
https://github.com/MTASZTAKI/ApertusVR/blob/0.9.1/plugins/render/sdlWindow/apeSdlWindowPlugin.cpp#L25
Filament init:
https://github.com/MTASZTAKI/ApertusVR/blob/0.9.1/plugins/render/filamentRenderWindows/apeFilamentWindowsRenderPlugin.cpp#L419
Then the rendering loop can be found here:
https://github.com/MTASZTAKI/ApertusVR/blob/0.9.1/plugins/render/filamentRenderWindows/apeFilamentWindowsRenderPlugin.cpp#L455
Any modification in the scene processed by that function:
https://github.com/MTASZTAKI/ApertusVR/blob/0.9.1/plugins/render/filamentRenderWindows/apeFilamentWindowsRenderPlugin.cpp#L468
The GLTF file open, read, parse, and adding to the scene:
https://github.com/MTASZTAKI/ApertusVR/blob/0.9.1/plugins/render/filamentRenderWindows/apeFilamentWindowsRenderPlugin.cpp#L155

Somehow only a black screen is showed but seems everything is parsed and loaded and the render loop is running
![image](https://user-images.githubusercontent.com/7982721/101989296-b7707800-3c9f-11eb-891b-38c03790cea6.png)

May I miss something?

Thank you
Peter

**Comment by prideout** [comment]
There are many things that could cause a black screen.  :)

It sounds like verified that `filament::Renderer::render(..)` is indeed getting called?  If Filament initialized successfully, you should see "FEngine (64 bits) created" in the console.

Since ApertusVR uses CMake anyway, it may be worthwhile for you to build Filament yourself as a subproject, this would let you dig deeper, try a debug build, enable GL errors, etc.

**Comment by bejado** [comment]
I don't see where you're setting the viewport. Try adding a call to `mpFilamentView->setViewport({0, 0, width, height})`.

Some additional details about your system would also be helpful (OS version, GPU model, etc).

**Comment by pkovacs86** [comment]
Dear Ben,

Many thanks for your suggestion.
Now it works.
![image](https://user-images.githubusercontent.com/7982721/102187965-fcb9c300-3eb4-11eb-99c4-bc6f7f9eab4f.png)

BR
Peter
