### ISSUE TITLE
create instance from FilamentAsset?

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#3364]
At present, I can only create an asset containing a specified number of instances from createInstancedAsset, but my current scenario is that when I create an asset, I don’t know how many instances I need, but I may continue to create new instances later.

So, Is it a good idea to add a create instance interface to FilamentAsset?

**Comment by davidwarford** [comment]
You already can 70dba2398e37e1913031f55b07b402679e87812a but the interface is on the loader and not the asset it's self. You should have 1 loader per asset you want to make instances of. I would highly recommend building an object pool as creating instances is apparently inefficient.

**Comment by prideout** [comment]
What David said; see the`createInstance` method.

Also note that animation is not yet supported in dynamically added instances.
