### ISSUE TITLE
"gltfviewer -s" results in no lighting

### ISSUE THREAD

**Issue by JackKaiXing** [google/filament#3366]
**Describe the bug**
in windows, command "gltf_viewer my.gltf", that point lighting effect is visible; however, command "gltf_viewer -s my.gltf",that point lighting effect is gone. However, we do not want to scale the scene.

**Expected behavior**
 how could be modify the code to control this?

**Comment by JackKaiXing** [comment]
thanks in advance

**Comment by romainguy** [comment]
There’s a directional light by default, no point lights. Could you provide screenshots please? Directional lighting works with or without -s in all my tests.

**Comment by JackKaiXing** [comment]
without -s 
![无标题](https://user-images.githubusercontent.com/21079351/102189050-0a8d3980-3ef1-11eb-9409-e5adec810910.png)
with -s
![无标题1](https://user-images.githubusercontent.com/21079351/102189088-17119200-3ef1-11eb-985d-626b2b707348.png)
and here is my gltf string, as listed below:
{
  "asset": {
    "version": "2.0",
      },
  "extensionsUsed": [
    "KHR_lights_punctual",
    "KHR_draco_mesh_compression"
  ],
  "scene": 0,
  "scenes": [
    {
      "nodes": [
        0,
        1,
        2
      ]
    }
  ],
  "nodes": [
    {
      "mesh": 0,
      "translation": [
        -0.5439453,
        0,
        8.354431
      ],
      "name": "Box001",
      "rotation": [
        0,
        0,
        0,
        1
      ],
      "scale": [
        1,
        1,
        1
      ]
    },
    {
      "translation": [
        8.409393,
        24.04018,
        11.8579865
      ],
      "rotation": [
        -0.707106769,
        0,
        0,
        0.707106769
      ],
      "name": "PhotometricLight001",
      "extensions": {
        "KHR_lights_punctual": {
          "light": 0
        }
      },
      "scale": [
        1,
        1,
        1
      ]
    },
    {
      "translation": [
        4.13425446,
        -16.18853,
        12.9804688
      ],
      "rotation": [
        -0.707106769,
        0,
        0,
        0.707106769
      ],
      "name": "PhotometricLight002",
      "extensions": {
        "KHR_lights_punctual": {
          "light": 1
        }
      },
      "scale": [
        1,
        1,
        1
      ]
    }
  ],
  "meshes": [
    {
      "primitives": [
        {
          "attributes": {
            "POSITION": 1,
            "TANGENT": 2,
            "NORMAL": 3,
            "TEXCOORD_0": 4
          },
          "indices": 0,
          "material": 0,
          "mode": 4,
          "extensions": {
            "KHR_draco_mesh_compression": {
              "bufferView": 0,
              "attributes": {
                "POSITION": 0,
                "TANGENT": 1,
                "NORMAL": 2,
                "TEXCOORD_0": 3
              }
            }
          }
        }
      ],
      "name": "Box001"
    }
  ],
  "accessors": [
    {
      "componentType": 5123,
      "count": 36,
      "type": "SCALAR",
      "name": "accessorIndices"
    },
    {
      "componentType": 5126,
      "count": 24,
      "max": [
        58.259484098680986,
        11.356984611626771,
        62.89313910600879
      ],
      "min": [
        -58.2570391060088,
        -0.061389106008793354,
        -62.893139106008796
      ],
      "type": "VEC3",
      "name": "accessorPositions"
    },
    {
      "componentType": 5126,
      "count": 24,
      "type": "VEC4",
      "name": "accessorTangents"
    },
    {
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "name": "accessorNormals"
    },
    {
      "componentType": 5126,
      "count": 24,
      "type": "VEC2",
      "name": "accessorUVs"
    }
  ],
  "bufferViews": [
    {
      "buffer": 0,
      "byteOffset": 0,
      "byteLength": 573
    }
  ],
  "buffers": [
    {
      "name": "test",
      "byteLength": 576,
      "uri": "test.bin"
    }
  ],
  "materials": [
    {
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.1764706,
          0.388235331,
          0.24313727,
          1
        ],
        "metallicFactor": 0,
        "roughnessFactor": 1
      },
      "name": "01 - Default",
      "emissiveFactor": [
        0,
        0,
        0
      ],
      "alphaMode": "OPAQUE",
      "doubleSided": false
    }
  ],
  "extensions": {
    "KHR_lights_punctual": {
      "lights": [
        {
          "color": [
            2.78720665,
            0.5679655,
            0.000001
          ],
          "intensity": 10000,
          "type": "point"
        },
        {
          "color": [
            0.904883146,
            1.0083766,
            1.19620013
          ],
          "intensity": 10000,
          "type": "point"
        }
      ]
    }
  },
  "extensionsRequired": [
    "KHR_draco_mesh_compression"
  ]
}

**Comment by JackKaiXing** [comment]
we checked the code, without -s, gltf_viewer would execute function "fitIntoUnitCube", why is that?

**Comment by romainguy** [comment]
It does this so the loaded glTF can be visible from the default camera position and entirely visible on screen. This is a pretty common thing to do in 3D viewers.

**Comment by romainguy** [comment]
Can you please share the entire glTF file with us?

@prideout @bejado Any idea why scale would impact lights? I imagine we don't rescale their falloff which would explain why it's more visible without -s.

**Comment by bejado** [comment]
If the glTF file doesn't have a range set for punctual lights, we give it an arbitrary one (10.0 units I believe). When using `-s`, the light and geometry probably fall outside this arbitrary range.

**Comment by JackKaiXing** [comment]
The entire glTF file.

https://github.com/JackKaiXing/glTF/tree/master/glTF

**Comment by romainguy** [comment]
@bejado That must be it then, I don't see a range in the glTF file.

**Comment by JackKaiXing** [comment]
Based on the above discussion, we added "range":4000 for light property. with -s, lighting is still invisible.

**Comment by romainguy** [comment]
I can't open the glTF file in Blender because of the Draco mesh compression extension.

@JackKaiXing Sorry to bother you, do you have a version of the asset that doesn't use Draco? I'd like to check where the lights are.

**Comment by JackKaiXing** [comment]
@romainguy . 

gltf with no draco compression: https://github.com/JackKaiXing/glTF/tree/master/glTF/gltf_WithoutDraco

**Comment by romainguy** [comment]
The positions are correct, so either there's a bug on our side or it's simply that the intensity of the lights isn't enough for the distances because of the falloff.

@JackKaiXing Could you try with brighter lights?

**Comment by JackKaiXing** [comment]
we tried brighter lights by changing its intensity and still no lighting .

**Comment by cx20** [comment]
It seems that this glTF model includes the `KHR_lights_punctual` extension, but I don't think Filament supports this extension yet.

For reference, here are the results displayed by other libraries.
|Library|Result|
|:-----:|:-----:|
|[Three.js](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://rawcdn.githack.com/JackKaiXing/glTF/f593cb10952c373cc11074b50142ff3a299a89ea/glTF/gltf_WithoutDraco/test.gltf&scale=0.01)|[![image](https://user-images.githubusercontent.com/1833979/102485038-6bac3d00-40aa-11eb-8e83-b7f931ed3bb5.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://rawcdn.githack.com/JackKaiXing/glTF/f593cb10952c373cc11074b50142ff3a299a89ea/glTF/gltf_WithoutDraco/test.gltf&scale=0.01)|
|[Babylon.js](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/JackKaiXing/glTF/f593cb10952c373cc11074b50142ff3a299a89ea/glTF/gltf_WithoutDraco/test.gltf&scale=0.01)|[![image](https://user-images.githubusercontent.com/1833979/102485334-d1002e00-40aa-11eb-9bf4-9889aa90add1.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/JackKaiXing/glTF/f593cb10952c373cc11074b50142ff3a299a89ea/glTF/gltf_WithoutDraco/test.gltf&scale=0.01)|

Also, I think the lights on this model are too bright.
![image](https://user-images.githubusercontent.com/1833979/102485519-14f33300-40ab-11eb-8812-f56180477bcc.png)
The specification of this extension says that the unit of intensity is candela (lm/sr).
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual

**Comment by JackKaiXing** [comment]
sorry for the intensity of 50000 value, it is for our test. However, if we change the intensity to 3000, without -s there is lighting and with -s there is no lighting.

About KHR_lights_punctual, without -s, lighting effects is visible. so I do think it is related.

@cx20

**Comment by cx20** [comment]
@JackKaiXing I'm sorry. Your point seems to be correct, `PhotometricLight001` seems to be a light included in glTF.

|Sun light|Photometric Light 001|Image|
|:----:|:----:|:----:|
|off|on|![image](https://user-images.githubusercontent.com/1833979/102508859-395e0800-40c9-11eb-98f2-c734704914b5.png)|
|off|off|![image](https://user-images.githubusercontent.com/1833979/102508997-601c3e80-40c9-11eb-916d-c1a327cefa48.png)|

**Comment by romainguy** [comment]
Filament supports `KHR_lights_punctual`.

**Comment by cx20** [comment]
Hmm, I tried to display the following model with `gltf_viewer`, but it doesn't seem to reflect the lights.

https://github.com/Reon90/glTF-Sample-Models/tree/master/2.0/Lights

|No|object name|type       |color  |intensity|
|-:|:-----------|:----------|:-----:|--------:|
| 1|Light       |point      |[1,0,0]|        5|
| 2|Spot        |spot       |[0.1,0]|       10|
| 3|Spot.001    |spot       |[0,0,1]|       10|
| 4|Sun         |directional|[0,1,1]|        1|

|Sun|Spot.001|Spot|Light|Image|
|:---:|:---:|:---:|:---:|:---:|
|on|on|on|on|![image](https://user-images.githubusercontent.com/1833979/102511327-ff423580-40cb-11eb-9001-5f60239a8585.png)|

**Comment by romainguy** [comment]
Those intensities are too low for the default camera exposure. glTF uses photometric units, so those lights use 5 lumens, 1 lux, etc. Here is the scene with a different exposure:

![Screen Shot 2020-12-17 at 8 04 21 AM](https://user-images.githubusercontent.com/869684/102512127-8052eb80-403e-11eb-935f-231fc25929fe.png)

**Comment by JackKaiXing** [comment]
Does exposure also works for my case? I really hope to find out as we do not scale the scene.

@romainguy

**Comment by romainguy** [comment]
Yes the exposure works since the light is visible without `-s`.

**Comment by cx20** [comment]
@romainguy Does exposure also work for the JavaScript API? I tried `setExposure()` in JavaScript API, but the box stayed black. 

```javascript
let aperture = 1;
let shutterSpeed = 1;
let ISO = 350;
this.camera.setExposure(aperture, shutterSpeed, ISO);
```
Perhaps I need to retrieve the `glTF` light extension information and set it individually like the embedded camera?

**Comment by romainguy** [comment]
Exposure should work in JavaScript yes. @prideout might help here

**Comment by prideout** [comment]
We do have a JavaScript binding for the 3-argument `setExposure`, but I have not tested it explicitly.  I can give it a try.  Let us know if you see any errors in your Developer Tools.

**Comment by prideout** [comment]
`setExposure` seems to work for me fine in JavaScript.  Below are screenshots with ISO levels 50 and 200.

<img width="694" alt="iso50" src="https://user-images.githubusercontent.com/1288904/102532671-2e6b8f00-4059-11eb-8073-edcd3c13a7e0.png">
<img width="694" alt="iso100" src="https://user-images.githubusercontent.com/1288904/102532672-2f9cbc00-4059-11eb-8ab7-8780d7030282.png">

**Comment by cx20** [comment]
@prideout Hmm, I tried setting `setExposure()` in the [gltf-test](https://github.com/cx20/gltf-test) Filament sample, but it didn't work as expected.

https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF

|setExposure()|Skybox|Lights|IBL|Image|
|:----:|:----:|:----:|:----:|:----:|
|N/A|On|Off|On|![image](https://user-images.githubusercontent.com/1833979/102553151-bd35e580-4105-11eb-9fd7-189acf422e02.png)|
|(1,1,100)|On|Off|On|![image](https://user-images.githubusercontent.com/1833979/102553250-f1110b00-4105-11eb-8460-a6b4066f7693.png)|
|(1,1,100)|On|On|Off|![image](https://user-images.githubusercontent.com/1833979/102553371-1736ab00-4106-11eb-8390-7c5a382bdffe.png)|

It would be helpful if you could give me some advice.

**Comment by romainguy** [comment]
Those results look correct to me. 1/1/100 is extremely bright, it's a 1 second exposure at ƒ/1, it's the kind of exposure you'd use for night time shots.

**Comment by cx20** [comment]
@romainguy I'm sorry, I don't know much about cameras, so please tell me what parameters I should set.

**Comment by romainguy** [comment]
For what? The exposure you want to set depends on the intensity of your lights and the visuals you want to achieve. Note that we have a tone mapper that helps with this called "display range". It shows the exposure in EVs using color codes.

**Comment by cx20** [comment]
@romainguy  Thank you for the information. I have to go out now and will try it when I get back.

**Comment by cx20** [comment]
I completely misunderstood the use of shutter speed in `setExposure()`. As you pointed out, I used the reciprocal of the shutter speed, and that solved the problem of the blank white.

I improved the Filament sample in [gltf-test](https://cx20.github.io/gltf-test/) so that you can adjust the Exposure settings like in `gltf_viewer`.
https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF
|setExposure()|Image|
|:-----:|:-----:|
|(16,1/125,50)|![image](https://user-images.githubusercontent.com/1833979/102623521-f746cc00-4185-11eb-8ea0-10ee13b81526.png)|
|(16,1/125,200)|![image](https://user-images.githubusercontent.com/1833979/102623648-2e1ce200-4186-11eb-9f2a-0dc070778668.png)|

I understand how to change the Exposure, but I couldn't figure out how to display the `KHR_lights_punctual` model in the JavaScript API. Can you give me some advice?

https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=Lights&scale=1&type=glTF
|setExposure()|Image|
|:-----:|:-----:|
|(16,1/125,100)|![image](https://user-images.githubusercontent.com/1833979/102624958-1c3c3e80-4188-11eb-89f9-d3d5ab2747b3.png)|
|(1,1,300)|![image](https://user-images.githubusercontent.com/1833979/102624999-28c09700-4188-11eb-8fd7-e46fa1d589c2.png)|

**Comment by cx20** [comment]
I have confirmed that the JavaScript API can also display the lights of the `KHR_lights_punctual` extension by adding the following code.

```javascript
const lights = asset.getLightEntities();
for (let i = 0; i < lights.length; i++) {
    this.scene.addEntity(lights[i]);
}
```

https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=Lights&scale=1&type=glTF
|setExposure()|Image|
|:-----:|:-----:|
|(1,1,300)|![image](https://user-images.githubusercontent.com/1833979/102640004-32a0c500-419d-11eb-8875-db5d531dc01b.png)|

https://cx20.github.io/gltf-test/examples/filament/index.html?url=https://rawcdn.githack.com/JackKaiXing/glTF/f593cb10952c373cc11074b50142ff3a299a89ea/glTF/gltf_WithoutDraco/test.gltf&scale=0.02
|setExposure()|Image|
|:-----:|:-----:|
|(16,1/125,100)|![image](https://user-images.githubusercontent.com/1833979/102640831-6a5c3c80-419e-11eb-82c9-a5f46a1a5d30.png)|

**Comment by prideout** [comment]
I think this bug is resolved, if not feel free to add a comment.
