### ISSUE TITLE
Filament - Forward only render? 

### ISSUE THREAD

**Issue by pure-water** [google/filament#3368]
Hi, 
  It appears to me the filament is a forward only render?  Is there any plan to do a deferred type in the future? 

Regards

**Comment by romainguy** [comment]
It is a forward renderer yes, but it uses clustered shading to handle many lights efficiently. We don't plan on adding a deferred renderer. Why do you want one?

**Comment by pure-water** [comment]
No, I don't have particular reason wanting one.  I am asking just for clarification purpose.  Since Filament is targeted for mobile primiarily (I assume?), it makes sense. 

Thanks
