### ISSUE TITLE
thread id assert crash

### ISSUE THREAD

**Issue by 564654509** [google/filament#3370]
Hello, we use filament engine in a complex project.  The main thread id is always changed.   Filament will crash when it destroyed.   Why filament adds some assert lines about thread id ?  Can we remove these 
and utilize lock in project to ensure thread safety of filament api ?  Thanks very much!

![image](https://user-images.githubusercontent.com/7654837/102302229-935cb180-3f93-11eb-8076-1158e8ebe3b8.png)
![image](https://user-images.githubusercontent.com/7654837/102302313-bf783280-3f93-11eb-8b72-25e1819f0e56.png)

**Comment by romainguy** [comment]
You could do this if you wanted sure. We keep the asserts because it's a common programming mistake.
