### ISSUE TITLE
Next filament release 2.0?

### ISSUE THREAD

**Issue by GiorgioCarosi** [google/filament#3371]
Hi, Could you tell me when you plan to release filament 2.0?
Thanks in advance,
Giorgio

**Comment by cx20** [comment]
I've seen a similar question before. https://github.com/google/filament/issues/3235

**Comment by romainguy** [comment]
We have a release once a week and it will be 1.9.10. We're current holding releases until we solve something internally at Google but if shouldn't be long hopefully.
