### ISSUE TITLE
Bind Entity to Entity

### ISSUE THREAD

**Issue by GrigorySamokhin** [google/filament#3374]
Hello! I want to cover the back of the mask with a transparent sphere shader, how can i move the sphere to -z relative to the mask? If I set -z via tcm in world coordinates I have distortion in equals scales. What is the best way to do so? 
<img width="507" alt="Screenshot 2020-12-17 at 21 39 19" src="https://user-images.githubusercontent.com/47357694/102528991-5e924c80-40b0-11eb-83a8-c7d29158e6e7.png">

**Comment by romainguy** [comment]
You can parent entities to each other: https://github.com/google/filament/blob/main/filament/include/filament/TransformManager.h#L149

You can also do this by computing the combined world transform yourself.

Note: this kind of question is better asked in the `Discussions` section.

**Comment by GrigorySamokhin** [comment]
Ok! Thanks, setParent works perfect
