### ISSUE TITLE
Memory leak related to View::setViewport

### ISSUE THREAD

**Issue by kpeeters** [google/filament#3381]
I am updating the viewport using `View::setViewport` at every frame. If the settings are different from one frame to the next, memory usage quickly goes through the roof. If the viewports alternate between two settings from one frame to the next, this does not happen. If there is only a limited set (e.g. 10) of different viewports through which I cycle, memory usage goes up substantially, but remains bounded. Nothing else changes between these cases (rendering the same things).

So it looks like something is cached or not freed when updating the viewport and the new settings haven't been seen before. I  couldn't see anything obvious in the filament source, but it may be hidden deeper than I have dug so far. Any bells?

This is on Android with v1.9.9; will try other platforms later.

**Comment by romainguy** [comment]
@pixelflinger can explain. There is a cache but I don't recall the policy we use.

I assume you are changing the viewport dimensions. What are you trying to achieve exactly?

**Comment by kpeeters** [comment]
Yes, viewport dimensions. Trying to get an A/B split view between two scenes, with a user-set split point. Works fine, just running out of memory.

**Comment by pixelflinger** [comment]
We have a cache of textures allocations, it evicts objects older than 30 frames, but only one per frame, unless it reaches 64MB in which case we are removing old entries until the cache is below 64MB.
So... It should settle around 64MB in theory.

That being said, this cache was added to handle the dynamic resolution and the framegraph, not frequent viewport changes.

Note that a viewport changes comes with some overhead, especially when dynamic lighting is used. So now, I'm wondering if maybe we have a bug/memory leak in that part of the code.

You could try to disable all dynamic lighting to see if the memory usage settles around 64MB, as we would expect.

**Comment by kpeeters** [comment]
Sorry @pixelflinger, which lighting do you consider 'dynamic'? I have an IBL, a directional light and some spots. Do you want me to try with all these off?

**Comment by romainguy** [comment]
Turn off just the spots

**Comment by kpeeters** [comment]
No luck, unfortunately. Also tried turning off all lights (so black screen apart from unlit materials) but still getting the memory leak.

While it would obviously be good to fix this, I can imagine if it is not high priority on your end. If there is a better way to clip a view, I'd be happy to use that. Right now, in order to clip a view, I set a clipped viewport, and adjust the camera setting. That is a lot of work for a simple operation, which could be done e.g. with a simple scissor test (which is what I do when targeting three.js).

**Comment by pixelflinger** [comment]
Ok. Let's use a hammer! Could you try to set `mEnabled` to `false` in `ResourceAllocator.h`?

This gets rid of the cache.

Thanks!

**Comment by kpeeters** [comment]
Good hammer, this gets rid of the leak! If I can do anything else to pin it down further, let me know.

**Comment by pixelflinger** [comment]
Thank you for getting and reporting. It might take some time before we can fix this, but we'll definitely get to it.

**Comment by konovalov-k** [comment]
@kpeeters What is the reason for update viewport every frame?

**Comment by kpeeters** [comment]
@konovalov-k I have two views next to each other, for an A/B comparison, and want to be able to move the separator between those two views left/right, while keeping the rendered view the same. So essentially I want a clipped view, with a per-frame clip depending on how much of A is visible. If there had been stencil buffer support I would have done it that way.

**Comment by ringoz** [comment]
The issue is still relevant for Renderer::renderStandaloneView(), because it isn't calling ResourceAllocator::gc() for some reason.
