### ISSUE TITLE
Crash in Metal when switching views

### ISSUE THREAD

**Issue by ast3rX** [google/filament#3384]
**Describe the bug**
Crash in Metal during switching views when shadow caster is enabled for lights.

**To Reproduce**
1. Setup two views where the first view doesn't contain a light, and the second one has a single light source.
2. Toggling between the views and switching back to the one with the light results in a consistent crash if the light source is set to shadow caster. Disabling shadow casting eliminates the issue.

**Expected behavior**
Toggling between views should work seamlessly without a potential crash.

**Desktop (please complete the following information):**
 - OS: iOS
 - Backend: Metal

**Additional context**
In this case the view with the light source is loaded from a GLB, and the other view doesn't contain the GLB entities.

There is an assert in `MetalDriver::draw()`'s `enumerateSamplerGroups()` call:

`const auto metalTexture = handle_const_cast<MetalTexture>(mHandleMap, sampler->t);
`

In `handle_const_cast()` the following check fails: `assert(iter != handleMap.end());`

**Comment by bejado** [comment]
Thanks for the report, I'm able to reproduce and will take a closer look.
