### ISSUE TITLE
How to use fliagui to render a image

### ISSUE THREAD

**Issue by dzwdyc** [google/filament#3387]
ImGui implementation creates Filament objects, it doesn't run with custom GL code.
So i must to render a imagebutton with Filament objects,
Could you give me some suggest:
How to create a imagebutton with filagui?
thanks！

**Comment by romainguy** [comment]
Hmm no with filagui you use ImGui like you normally would. The fact that it uses Filament constructs underneath is implementation details you don't need to worry about.

**Comment by dzwdyc** [comment]
> Hmm no with filagui you use ImGui like you normally would. The fact that it uses Filament constructs underneath is implementation details you don't need to worry about.

But I cant draw a Image with imgui, it needs a texture id.

**Comment by prideout** [comment]
I think @dzwdyc  is referring to the image-based widgets in imgui (e.g. `ImGui::ImageButton`), which we are not using in our demo apps.

The imgui notion of a texture id is just a void*, so we could handle this by allowing users to pass a Filament Texture* for this. 
 Filagui should examine the the `TextureId` field of the imgui draw command, near the same spot where it already examines the `UserCallback`.
