### ISSUE TITLE
Build Error on Ubuntu 16 with clang-8

### ISSUE THREAD

**Issue by adizhol** [google/filament#3392]
env CC=/usr/bin/clang-8 CXX=/usr/bin/clang++-8 CXXFLAGS=-stdlib=libc++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release/filament -DCMAKE_CXX_FLAGS="-I/usr/include/libcxxabi/" ../..

```
-- DFG LUT size set to 128x128
-- Configuring done
-- Generating done
-- Build files have been written to: /home/azholkover/code/filament/out/cmake-release

```
 ninja
[194/1238] Linking CXX executable libs/math/benchmark_math
FAILED: libs/math/benchmark_math 
: && /usr/bin/clang++-8 -I/usr/include/libcxxabi/ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections libs/math/CMakeFiles/benchmark_math.dir/benchmarks/benchmark_fast.cpp.o -o libs/math/benchmark_math  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  third_party/benchmark/tnt/libbenchmark_main.a  libs/utils/libutils.a  libs/math/libmath.a  third_party/benchmark/tnt/libbenchmark.a  -Wl,-Bdynamic  -pthread  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
clang: error: unable to execute command: Segmentation fault
clang: error: linker command failed due to signal (use -v to see invocation)
[196/1238] Linking CXX executable libs/utils/benchmark_utils
**FAILED: libs/utils/benchmark_utils** 
: && /usr/bin/clang++-8 -I/usr/include/libcxxabi/ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,--gc-sections libs/utils/CMakeFiles/benchmark_utils.dir/benchmark/benchmark_allocators.cpp.o libs/utils/CMakeFiles/benchmark_utils.dir/benchmark/benchmark_binary_search.cpp.o libs/utils/CMakeFiles/benchmark_utils.dir/benchmark/benchmark_calls.cpp.o libs/utils/CMakeFiles/benchmark_utils.dir/benchmark/benchmark_JobSystem.cpp.o libs/utils/CMakeFiles/benchmark_utils.dir/benchmark/benchmark_mutex.cpp.o libs/utils/CMakeFiles/benchmark_utils.dir/benchmark/benchmark_memcpy.cpp.o -o libs/utils/benchmark_utils  -Wl,-rpath,/home/azholkover/code/filament/out/cmake-release/libs/utils  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  third_party/benchmark/tnt/libbenchmark_main.a  libs/utils/libutils.a  -Wl,-Bdynamic  libs/utils/libbenchmark_utils_callee.so  third_party/benchmark/tnt/libbenchmark.a  -pthread  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
**clang: error: unable to execute command: Segmentation fault
clang: error: linker command failed due to signal (use -v to see invocation)**
[243/1238] Building CXX object third_party/draco/tnt/CMakeFiles/draco_io.dir/__/src/draco/io/ply_decoder.cc.o
**ninja: build stopped: subcommand failed.**

**Comment by romainguy** [comment]
Your toolchain is crashing:

```
clang: error: unable to execute command: Segmentation fault
```

You  might want to try with a newer version.
