### ISSUE TITLE
Spot light crash

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#3393]
**Sample Code（1.8.0）:**
 Entity spotEntity = EntityManager::get().create();
  LightManager::Builder(LightManager::Type::SPOT)
      .position({0,0,0})
      .direction({-1, -1, -1})
      .build(*engine, spotEntity);
  scene->addEntity(spotEntity);
  //engine->getLightManager().setShadowCaster(engine->getLightManager().getInstance(spotEntity), true);`

**If I uncomment setShadowCaster, then it crashed :**

utils::PostconditionPanic
in filament::backend::Program filament::FMaterial::getProgramBuilderWithVariants(uint8_t, uint8_t, uint8_t) const:393
in file filament/src/Material.cpp
reason: The material 'ubershader_lit_opaque' has not been compiled to include the required GLSL or SPIR-V chunks for the vertex shader (variant=0x4e, filtered=0x4c).

**Comment by romainguy** [comment]
Can you explain a bit more what you are doing? According to the error message you did not compile the materials with all the required variants. Are you using gltfio? Could you try with more recent versions? 1.9.x instead of 1.8.

**Comment by cjsliuj** [comment]
Sorry ,Bugs caused by changes made by my team members
