### ISSUE TITLE
Point lights and spot lights don't work on desktop

### ISSUE THREAD

**Issue by aylaylay** [google/filament#3395]
Never been able to get lights other than directional to actually work

https://user-images.githubusercontent.com/1667289/103274569-e6822b80-49b9-11eb-9b1a-3a78c714d13a.mp4

**Comment by romainguy** [comment]
They work but you need to make sure their intensity and falloff radius are properly set.

**Comment by aylaylay** [comment]
This is unchanged, compiled directly off the github. If intensity and falloff radius need to be properly set then your lightbulb example is broken.

**Comment by romainguy** [comment]
The sample works, what you are seeing is the fog that's enabled in this sample. When you are looking up at the object the camera is inside the fog. Maybe disabling the fog would make sense in this sample, it's probably a leftover from a test since this executable is mostly for internal testing.

**Comment by romainguy** [comment]
You can use the "disco ball" mode to see a bunch of lights. Here are two examples in "disco ball" and "more lights" mode with a larger asset:

<img width="1136" alt="Screen Shot 2020-12-29 at 4 50 51 PM" src="https://user-images.githubusercontent.com/869684/103323087-17805180-49f6-11eb-8929-4f62b0ac7d69.png">

<img width="1136" alt="Screen Shot 2020-12-29 at 4 51 08 PM" src="https://user-images.githubusercontent.com/869684/103323093-1a7b4200-49f6-11eb-97c6-9608985ca6bd.png">

**Comment by romainguy** [comment]
Note: a better test is `gltf_viewer` with a glTF file containing point/spot lights (like https://www.dropbox.com/s/uffti7xfl2m0bvw/bistro_gltf.zip?dl=0).

**Comment by aylaylay** [comment]
https://user-images.githubusercontent.com/1667289/103323323-491b0c00-4a3a-11eb-9cd6-bd7118059435.mp4

`FEngine (64 bits) created at 0000028847FBD080 (threading is enabled)
FEngine resolved backend: OpenGL
NVIDIA Corporation, GeForce RTX 2080 Ti/PCIe/SSE2, 4.1.0 NVIDIA 441.20, 4.10 NVIDIA via Cg compiler
OS version: 0`

**Comment by aylaylay** [comment]
https://github.com/google/filament/issues/1119 Same issue as this?

**Comment by romainguy** [comment]
Pass `-s` to disable scene scaling, otherwise the scene is fit into a unit cube but the lights photometric units will be too bright with too large falloffs.

**Comment by aylaylay** [comment]
Disabling scene scaling just doesn't render lights at all. Fitting the scene in a x10 unit cube shows the lights but they still flicker.


https://user-images.githubusercontent.com/1667289/103323902-e5461280-4a3c-11eb-8dcc-3565142e0e58.mp4

**Comment by bejado** [comment]
Reopening because I'm able to reproduce this, but only on Windows. Investigating...

**Comment by prideout** [comment]
Maybe try playing with the `-g` option in matc, who knows! 🤣
