### ISSUE TITLE
JavaScript binding for camutils

### ISSUE THREAD

**Issue by andreperezmaselco** [google/filament#3396]
It would be great to bind the `camutils` lib (`Manipulator` and `Bookmark` classes) via the `web/filament-js/jsbindings.cpp` file.
This way, we would have a way to control the camera using a pure `Filament` lib (all the code would be integrated).

**Comment by prideout** [comment]
@pixelflinger unfortunately we might want to consider closing this as "will not fix" since it would increase our maintenance burden.

**Comment by romainguy** [comment]
Agreed.
