### ISSUE TITLE
Undefined reference to utils::Path and other methods

### ISSUE THREAD

**Issue by 100espressos** [google/filament#3399]
```
other.cpp:160: undefined reference to `utils::Path::concat(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cpp:129: undefined reference to `utils::Path::getName[abi:cxx11]() const'
test.cpp:647: undefined reference to `utils::Path::getExtension[abi:cxx11]() const'
test.cpp:995: undefined reference to `filament::viewer::writeJson[abi:cxx11](filament::viewer::ColorGradingSettings const&)'
test.cpp.o: in function `main::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)#10}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const':
test.cpp:1026: undefined reference to `utils::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cpp.o: in function `main':
test.cpp:612: undefined reference to `utils::operator<<(std::ostream&, utils::Path const&)'
test.cpp:618: undefined reference to `utils::Path::getExtension[abi:cxx11]() const'
```

**To Reproduce**
Build `utils` and `viewer` libraries for Linux and attempt to link with `utils::Path()`, `utils::Path::concat()`, `utils::Path::getName()`, `utils::Path::getExtension()`, `viewer::writeJson()`...

**Desktop**
arch Linux

**Comment by romainguy** [comment]
What are you building exactly and how?

**Comment by 100espressos** [comment]
Thanks for the follow-up. The source code above is the `gltf_viewer.cpp` sample.

**Comment by 100espressos** [comment]
In scouring the Issues for a couple weeks, I gathered that I'm not the first to try using filamentapp sources slated for rework (https://github.com/google/filament/issues/2287) so it's not that I expect them to build yet without changes, but I'm trying to eliminate potential source of error; manually sussing out dependencies seems error-prone and hard to look at.

**Comment by romainguy** [comment]
The `Path` class and its API is properly publicly exported, did you not link against `libutils`?

**Comment by 100espressos** [comment]
Apologies, I could have added that the API does seem properly publicly exported, the test apps compile, and I am linking against the installed (linux) `libutils`. Maybe there's a problem somewhere in my promiscuous including and linking to `filamentapp` and every supporting internal/external library..

**Comment by lasagnaphil** [comment]
I'm currently having the exact same issue. Could you explain what specific library was incompatible with filament?

**Comment by 100espressos** [comment]
I think the error was most likely caused by my inadvertently attempting to link clang-produced libraries later with gcc.

**Comment by lasagnaphil** [comment]
Okay, now I understand. It seems that `utils::Path` depends on `std::string`, which makes linking filament (compiled with libc++) with another library compiled with libstdc++ difficult. (Only the lower level parts of libstdc++ and libc++ seem to be compatible with each other, and STL containers aren't.) I think there were some efforts to remove any STL ABI dependencies (such as https://github.com/google/filament/pull/1050), but it still seems like the process is incomplete. Anyways, thanks for the tip!

**Comment by 100espressos** [comment]
Thanks for the details!
