### ISSUE TITLE
Stream samples don't work on Samsung Galaxy S9

### ISSUE THREAD

**Issue by martinnovak** [google/filament#3403]
**Describe the bug**

I tried some samples with changing textures on Samsung Galaxy S9 with Android 10, and they seems not to be working. I want to point out specifically to hello-camera and stream-test samples. They both show an empty rectangle like that nothing is drawn inside. I also found no error or other interesting message in the logs.

Just a side note - the thing I want to do is to display a video inside AR content, so I was doing some research regarding this. I hope that Filament could be a good framework to be used to do this.

**To Reproduce**
1. run hello-camera or stream-test samples on Sumsung Galaxy S9

**Screenshots**

![device-2021-01-05-090943](https://user-images.githubusercontent.com/590042/103624745-4046a080-4f3a-11eb-8bdc-4b1d1f0c01b1.png)
![device-2021-01-05-091027](https://user-images.githubusercontent.com/590042/103624757-43da2780-4f3a-11eb-83ef-14efcf949d0b.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10

**Comment by prideout** [comment]
Filament has 3 different ways of using Streams, the texture id based strategy is probably most robust so you might want to try that.  In the stream-test MainActivity, can you try changing from this:

```
private var streamSource = StreamSource.CANVAS_STREAM_NATIVE
```

to

```
private var streamSource = StreamSource.CANVAS_STREAM_TEXID
```

**Comment by kpeeters** [comment]
Using `CANVAS_STREAM_TEXID` I also get black textures with `sample-stream-test` on Mali-T830 MP1. This device runs API 27 so I can't try the `CAMERA_STREAM_NATIVE` method.

An independent app, which uses the `TEXTURE_ID` method to get the camera stream too, also produces a black texture on this device (while it works fine on other devices).

**Comment by pixelflinger** [comment]
not actionable / device specific
