### ISSUE TITLE
Make object seen in a transparent object in full view angle

### ISSUE THREAD

**Issue by 1939938853** [google/filament#3410]
Hello,

I'm using filament rendering in Open3D, trying to make  object seen in a transparent object in full view angle. Unfortunately without success -- only in some view angle,   the inside object can be seen,  as shown in the following two images.

Here are the filament material properties I set for the transparent object. 

`
    mat->base_color = { 119.0f / 255.0f, 119.0f / 255.0f, 119.0f / 255.0f, 0.3f };
    mat->point_size = 3.0;
    mat->base_metallic = 0.f;
    mat->base_roughness = 1.f;
    mat->base_reflectance = 0.10f;
    mat->base_clearcoat = 1.f;
    mat->base_clearcoat_roughness = 1.f;
    mat->base_anisotropy = 0.0f;
    mat->thickness = .5f;
    mat->transmission = .5f;
    mat->absorption_color = { 0.5f, 0.5f, 0.5f };
    mat->absorption_distance = .5f;
    mat->shader = "defaultLitTransparency";
    mat->name = "glass";
`

Any suggestions would be  appreciated? 
Thank You!

![image](https://user-images.githubusercontent.com/59957922/104129637-17287480-536d-11eb-8a73-eb388443d73e.png)
![image](https://user-images.githubusercontent.com/59957922/104129652-2f988f00-536d-11eb-8d71-da8f63a7e74e.png)

**Comment by romainguy** [comment]
Could you try to use the "fade" blending mode instead of "transparent"?

**Comment by 1939938853** [comment]
Hello romainguy,

Open3D seems has no  "fade" blending mode material, see the pic below. How can I select this fade blending mode? Could you please give me more detailed hint? 

[Here is the filament interface in Open3D](https://github.com/intel-isl/Open3D/tree/master/cpp/open3d/visualization/rendering/filament)

Thank you!

![image](https://user-images.githubusercontent.com/59957922/104149607-26440c80-53d7-11eb-96c0-9ba14bbd6618.png)

**Comment by romainguy** [comment]
You would have to ask Open3D to add it. Anyway in your case the cube is transparent but you are seeing specular highlights. You could use an unlit transparent material instead or set the roughness to 0.0 instead of 1.0.
