### ISSUE TITLE
How can we get default position of gltf model after export form blender ?

### ISSUE THREAD

**Issue by duy-maimanh** [google/filament#3411]
I try to render gltf model with default location that i set in blender.
In sample-gltf-viewer, You call modelViewer.transformToUnitCube() then this func move model to center of scene because kDefaultObjectPosition. But i can not find how to get default position of my model. Any suggestion ?

The folowing image will show position of my model and center point.
<img width="581" alt="Screen Shot 2021-01-11 at 10 55 07" src="https://user-images.githubusercontent.com/58172953/104154458-8f4b7480-5417-11eb-9709-ca75f2668f63.png">

**Comment by prideout** [comment]
Hmm, I do not understand the question -- note that you do not need to call `transformToUnitCube()`, it is optional.

**Comment by duy-maimanh** [comment]
I am sorry to have confused you.
I have done my issue. Thanks for your help.

**Comment by chiragchauhan1073** [comment]
Hey @duy-maimanh How did you handled this scenario ? i have same requirement. could you please share you code. ?

**Comment by duy-maimanh** [comment]
@chiragchauhan1073 I do not remember exactly. My question was then because I didn't quite understand how filament works. But for my case, the filament renders exactly where I set it in blender. I don't need to do anything.
