### ISSUE TITLE
Question: Supplying texture handles for ImGui

### ISSUE THREAD

**Issue by inanevin** [google/filament#3412]
I am writing an editor for my custom engine and trying to get ImGui to draw images while using Filament. I've successfuly implemented ImGui using the helper functions in filagui library and run it as a second UI view on top of my game view.

However, in order to draw an image, ImGui requires a texture handle retrieved from the GPU but as far as I know it's not possible to get the handles since Filament supports multiple backends and does not expose underlying details.

What is the best way for me to handle this? I know it's possible that I edit the source code & expose the handles somewhow, but I don't want to mess around in source for every backend Filament supports and find a hack which might be broken in the future.

I've thought about this; whenever I want to draw a texture in my editor (in a lot of places), I create a new view & camera with ortho projection, which draws a quad with an unlit material using the texture. I set the viewport of this view depending on where I want to draw this texture in my main window & in which size. I think it might be possible to do so if I draw these views on top ImGui UI view, but I think it's an overkill for something that literally takes 1 LoC for ImGui to do so (not even mentioning that I won't be able to manipulate this view like any other ImGui object) and might have some performance effects. Is there any other way to handle this?

**Comment by prideout** [comment]
Currently, the Filagui library does not support image-based widgets in imgui such as `ImGui::ImageButton`.

The imgui notion of a "texture id" is just a void*, so in theory Filagui could be enhanced by allowing users to pass a pointer to a `Filament::Texture` for their texture id.  Filagui would then examine the TextureId field of the imgui draw command, near the same spot where it already examines the UserCallback.

(similar question was asked via Issue #3387)

**Comment by inanevin** [comment]
> Currently, the Filagui library does not support image-based widgets in imgui such as `ImGui::ImageButton`.
> 
> The imgui notion of a "texture id" is just a void*, so in theory Filagui could be enhanced by allowing users to pass a pointer to a `Filament::Texture` for their texture id. Filagui would then examine the TextureId field of the imgui draw command, near the same spot where it already examines the UserCallback.
> 
> (similar question was asked via Issue #3387)

As far as I understood Filagui just converts the ImGui commands into renderables for Filament, and after your comment I've double checked and see that it actually runs a check for TextureId near Usercallback;

`if (pcmd.TextureId)
 {
                    TextureSampler sampler(TextureSampler::MinFilter::LINEAR, TextureSampler::MagFilter::LINEAR);
                    materialInstance->setParameter("albedo", (Texture const*)pcmd.TextureId, sampler);
 }`

Is this the part where it checks if the draw command contains a texture id or not? If so, technically passing Filament::Texture* as you said should work out of the box, or is this piece of code checks for something else? I could not grasp the idea about how I can enhance this more to support what I need, or is it already technically supported lol. I will give it a try.

**Comment by prideout** [comment]
Ha, I had forgotten that I already implemented this!  Yes in theory it should work out of the box.
