### ISSUE TITLE
Help: Renderer.copyFrame() with MediaCodec.createInputSurface()

### ISSUE THREAD

**Issue by MarkMurillo** [google/filament#3418]
Hi, I'm trying to leverage the Renderer.copyFrame() to render into an input surface created by MediaCodec.createInputSurface().
I was wondering if this is possible. I've tried creating a SwapChain using `Engine.createSwapChain(<MediaCodec's input buffer>)` but not sure why the callback I passed into the MediaCodec isn't firing...

I call copyFrame() right after render() and just before endFrame() (as specified in the documentation) and I pass in the MediaCodec swapchain as the destination. I also set `MIRROR_FRAME_FLAG_COMMIT` and `MIRROR_FRAME_FLAG_CLEAR` on the copyFrame() call.

Code snippet for creating the MediaCodec encoder:
```
// VIDEO_MIME_TYPE is "video/avc"
videoEncoder = MediaCodec.createEncoderByType(VIDEO_MIME_TYPE)
// Pass in null for surface to designate it as an encoder
videoEncoder?.configure(mediaFormat, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE)
inputSurface = videoEncoder?.createInputSurface()

// Check if we have to create the swapchain for recording.
if (recordingSwapChain == null) {
    recordingSwapChain = engine.createSwapChain(inputSurface!!)
}

// encoderCallback is a MediaCodec.Callback
videoEncoder?.setCallback(encoderCallback)
videoEncoder?.start()
```

And the copyFrame() snippet:
```
recordingSwapChain?.let {
    // Use the same viewport as source since we want to mirror exact dimensions in the recording.
    renderer.copyFrame(it, view.viewport, view.viewport, MIRROR_FRAME_FLAG_COMMIT.and(MIRROR_FRAME_FLAG_CLEAR))
}

videoEncoder?.let {
    it.flush()
    it.start()
}
```

Any insights would be great, thanks in advance.

**Comment by romainguy** [comment]
You can see an example of how SceneForm is doing it here: https://github.com/google-ar/sceneform-android-sdk/blob/b33fa25987561e5bf2129a25fbce6ad3b43ac4ee/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform/rendering/Renderer.java#L301

**Comment by romainguy** [comment]
I believe for video encoding that you need the `SET_PRESENTATION_TIME` flag otherwise the encoder cannot know the video framerate.
