### ISSUE TITLE
Loading heavy glTF asset to a scene fails

### ISSUE THREAD

**Issue by 61315** [google/filament#3419]
**Describe the bug**
Android filament engine does not load large glTF asset properly. Good amount of entities added to a scene doesn't get rendered whatsoever.

**To Reproduce**
I attach a repro project [here](https://drive.google.com/file/d/1ZPwS5ZDr4wJnY7ASYttvpfzLgXC49lwk/view?usp=sharing). The project is basically a copy of [sample-gltf-viewer](android/samples/sample-gltf-viewer). Thing is that it's using [pre-built binaries](https://github.com/google/filament/releases/tag/v1.9.9) and tweaked [ModelViewer.kt](android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt) on my demand. Notice this project has `android:largeHeap` option enabled.

**Expected behavior**
gltfio loads the asset and renderer renders the asset.

**Screenshots**
https://user-images.githubusercontent.com/46559594/104541921-e8a8e300-5665-11eb-942e-7d1acf705822.mp4

**Smartphone:**
 - Device: Samsung Galaxy S10e
 - OS: Android Q 10.0
 - GPU: Mali-G76

**Additional context**
 - ![Screen Shot 2021-01-13 at 4 18 11 PM](https://user-images.githubusercontent.com/46559594/104418876-f6edf500-55ba-11eb-9934-1d79bfc21f33.png)

This glTF asset is made for 3D video contents, contains a sequence of meshes, is heavily compressed over various measures, each given a specific node name in a sequential manner. The asset has 2394 mesh nodes and a vertex count of 8125751 and the asset was processed through the pipeline below.

1. Simplify using [gltfpack](https://github.com/zeux/meshoptimizer/tree/b1b414b4dd84935b85ae421b8b005ade79f67b66)
`$ gltfpack -i in.glb -o out.glb -km -kn -ke -noq -si 0.25`

2. Strip normal and vertex color leaving only UV using Blender 2.91 Stable/[glTF-Blender-IO 1.5.9](https://github.com/KhronosGroup/glTF-Blender-IO/tree/48a7c54f4f47069acb50fdb1136716e7636f33f3)
![Screen Shot 2021-01-14 at 11 35 06 AM](https://user-images.githubusercontent.com/46559594/104537066-97e0bc80-565c-11eb-8ef2-caf0f4e6e1cf.png)

3. Unlink texture and image references by mangling the texture property names (e.g. baseColorTexture -> baseColorTexture_unused)

4. Compress using [gltf-pipeline 3.0.2](https://github.com/CesiumGS/gltf-pipeline) while draco compression enabled.
`$ gltf-pipeline -i in.glb -o out.glb -d -b`

This glTF asset runs fine on the following environments, meaning entire 2394 mesh nodes being loaded to a scene and rendered.
- [Babylon.js Sandbox](https://sandbox.babylonjs.com/) (Web)
- [Babylon.js + VSCode glTF Tools 2.3.2](https://github.com/AnalyticalGraphicsInc/gltf-vscode) (Desktop, Mac)
- [three.js + VSCode glTF Tools 2.3.2](https://github.com/AnalyticalGraphicsInc/gltf-vscode) (Desktop, Mac)
- [tinygltf + SceneKit](https://github.com/toshiks/glTF-quicklook) (iOS)
- [GLTFKit](https://github.com/warrenm/GLTFKit) (iOS)

**Comment by 61315** [comment]
You can find 4 different approaches to load the asset in the `ModelViewerAlt.kt`, line 256.

```
asset?.let {
    /**
     *  1. Using populateScene()
     *  Asset is not fully added to the scene.
     */
    
    //populateScene(it)

    
    /**
     *  2. Inserting entities all at once
     *  Asset is not fully added to the scene, and crashes occur sporadically.
     */
    
    //scene.addEntities(it.entities)

    
    /**
     *  3. Using popRenderable()
     *  Asset is not fully added to the scene and popRenderable() pops entities in an arbitrary order.
     */
    
    /*
    val entity = it.popRenderable()
    scene.addEntity(entity)
    println("@Entity: $entity, " +
            "entityName: ${it.getName(entity)}, " +
            "hasRenderable: ${engine.renderableManager.hasComponent(engine.renderableManager.getInstance(entity))}")
    */

    
    /**
     *  4. Using getFirstEntityByName()
     *  Asset is not fully added to the scene, but Entities are in order,
     *  respecting the order of the sequence from the glTF asset.
     */

    val count = frameNumber
    val entity = it.getFirstEntityByName("Mesh_$count")
    if (entity == 0) { return@let }
    val prevEntity = it.getFirstEntityByName("Mesh_${count - 1}")

    scene.removeEntity(prevEntity)
    scene.addEntity(entity)
    frameNumber++
    
    println("@Entity: $entity, " +
            "entityName: ${it.getName(entity)}, " +
            "hasRenderable: ${engine.renderableManager.hasComponent(engine.renderableManager.getInstance(entity))}")
}
```

**Comment by 61315** [comment]
What will be the case?

1. The asset is a _rogue_?
2. gltfio should not load _rogue_ asset?
3. Renderer cannot handle excessive number of renderables?
4. Some of the loaded nodes are disposed prematurely?
5. The size of uncompressed asset exceed the memory capacity?

**Comment by romainguy** [comment]
Could you please show:
1. What the asset is supposed to look like
2. Logs from your device when this happens

**Comment by romainguy** [comment]
Your asset loads fine (with all 2394 mesh nodes) in our desktop `gltf_viewer`. The issue may then be cause by memory limits on phones.

**Comment by 61315** [comment]
These are the first five seconds of the Logcat stream. 

[gltf_test_nofilters.txt](https://github.com/google/filament/files/5818036/gltf_test_nofilters.txt)
[gltf_test_filtered.txt](https://github.com/google/filament/files/5818037/gltf_test_filtered.txt)

No discernible logs were found except the following lines.

> W/Filament: Cannot decompress mesh, Draco decoding error.
> I/chatty: uid=10316(com.example.gltf_test) identical 566 lines
> W/Filament: Cannot decompress mesh, Draco decoding error.

**Comment by romainguy** [comment]
That could explain what you are seeing. We haven't updated Draco in a while I believe.

**Comment by 61315** [comment]
The asset was compressed using gltf-pipeline 3.0.2 made by Cesium team. I assume their version of Draco is npm Draco 1.4.0 that is backward compatible to Draco 1.3.6.

[CesiumGS/gltf-pipeline/package.json](https://github.com/CesiumGS/gltf-pipeline/blob/490f8941db9e25affeaa60738a7ea7e07f5ca99a/package.json#L31)
https://github.com/CesiumGS/gltf-pipeline/commit/0f056c301a097cd7115808342710441152a14004
https://github.com/CesiumGS/gltf-pipeline/pull/562#issuecomment-727006761

@romainguy Would you care to describe the cgltf support of Draco 1.4.0 release, and your version of filament desktop build you just tested the asset? If this is a Draco compatibility issue, it shouldn't be platform specific. I guess this is a subtle combination of Draco compatibility and memory limit then?

**Comment by romainguy** [comment]
I haven't tried on Android but these messages in the logs show that the mesh couldn't be decompressed properly. It could also be a Draco bug on Android with that version, etc. Have you tried loading the glb without applying Draco compression?

**Comment by 61315** [comment]
It crashes. I attach the logs and the asset here.

[gltf_test_nondraco_nofilters.txt](https://github.com/google/filament/files/5818349/gltf_test_nondraco_nofilters.txt)
[sequence_2394f_nondraco.glb](https://drive.google.com/file/d/1vI750b1_LOKEV8_73apgrGXAJkPZNigM/view?usp=sharing)

> A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
> A/DEBUG: Cause: null pointer dereference
> A/DEBUG:     x0  00000075e0434900  x1  00000074d9fdc0c0  x2  00000074e81f0b28  x3  0000000000000003
> A/DEBUG:     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  000000000030f000
> A/DEBUG:     x8  0000000000000008  x9  00000074d9fbc040  x10 0000000000000001  x11 0000000000000000
> A/DEBUG:     x12 0000000002b1d880  x13 0000000000000000  x14 0000000000000000  x15 0000000000000002
> A/DEBUG:     x16 00000075df83a9f0  x17 00000075de335318  x18 00000074e6904000  x19 00000074d7b2d6e0
> A/DEBUG:     x20 00000074d9fa5000  x21 00000074d7b2d6e0  x22 00000074eece83b0  x23 000000754571a100
> A/DEBUG:     x24 000000754571a1a0  x25 00000074e81f0d50  x26 0000007548d46140  x27 00000000000fd000
> A/DEBUG:     x28 0000007ff7a930e0  x29 00000074e81f0d10
> A/DEBUG:     sp  00000074e81f0ad0  lr  0000007548d88260  pc  0000007548d89f98
> A/DEBUG: backtrace:
> A/DEBUG:       #00 pc 0000000000088f98  /data/app/com.example.gltf_test-MSfLyq7N7A7sdyO-trLgSg==/base.apk!libfilament-jni.so (offset 0x1c02000) (BuildId: 54802414ffabe932202b04617aef440852b15774)

**Comment by romainguy** [comment]
@prideout We haven't updated Draco in a while right?

**Comment by prideout** [comment]
Draco updated via #3429.  I have not tried them with Android, but both the draco and the non-draco glb files attached to this issue load without crashing in macOS, and the result looks similar to what I see in https://gltf-viewer.donmccurdy.com/

Filament scenes are unordered, you can add entities in any order.

**Comment by 61315** [comment]
Tweaked the repro case with the aars from [Actions: Update Draco to 1.4.1 | prideout | 6473771 | main](https://github.com/google/filament/actions/runs/488676026).

Issue persists. The non-draco glb crashes the app and the compressed one loads partially. https://github.com/google/filament/issues/3419#issuecomment-760333255 Think of it, as **romainguy** confirmed the asset loads just fine in his desktop `gltf_viewer` before #3429, I cannot tell if this is related to Draco source at all. 

I think this is more of an issue of Android platform specific implementation of cgltf, or how filament interact with drivers.

Binary volume of 230 MiB is still far too low for causing row on memory to a 6GB RAM device. Lets put cgltf's memory overhead compared to original glb is 200%, the app should handle ~700 MiB loads without making a scene.

Issue should be reproducible on the Pixel devices, I tried the emulator and it presented similar behaviors to my Samsung device. I'm just putting the stack here as emulator gave me some extra ideas. All test was done using #3429.

 - [gltf_test_nondraco_emulator_filtered.txt](https://github.com/google/filament/files/5823865/gltf_test_nondraco_emulator_filtered.txt)

> D/eglCodecCommon: setVertexArrayObject: set vao to 12 (12) 11976 59
> E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0xc7e09cf0
> E/emuglGLESv2_enc: Out of bounds vertex attribute info: clientArray? 0 attribute 0 vbo 60 allocedBufferSize 38880 bufferDataSpecified? 1 wantedStart 0 wantedEnd 786432


 - [gltf_test_draco_emulator_nofilter.txt](https://github.com/google/filament/files/5823864/gltf_test_draco_emulator_nofilter.txt)

> A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc66dc5a8
> A/DEBUG:     eax ff815ac8  ebx ff815af0  ecx 00000000  edx 00000000
> A/DEBUG:     edi c66dc5a4  esi ff815ab8
> A/DEBUG:     ebp ff815a98  esp ff815a70  eip caeeef88
> A/DEBUG: backtrace:
> A/DEBUG:       #00 pc 00066f88  /data/app/com.example.gltf_test-voVbYneX0RSvLS5I_WRKdg==/base.apk!libgltfio-jni.so (offset 0xc00a000) (BuildId: 0b18d49ff43b3d5bdaf194684abdf657493db0da)

**Comment by romainguy** [comment]
The in-memory representation of the glTF is not going to be the same as the size of the glTF file. Also note that an app may not have access to the entire device's memory. But it looks like it's not an out of memory error.

**Comment by prideout** [comment]
@61315 we recently added some robustness improvements, and improved error messaging, specifically for large assets, so I'm going to close this bug.  If you are still blocked with the latest build, please re-open.
