### ISSUE TITLE
GPU Memory Leak after ResourceLoader (Android)

### ISSUE THREAD

**Issue by konovalov-k** [google/filament#3420]
Greetings! Thx for the awesome lib!

**Describe the bug**
When I load some glb asset for use it in scene, I use ResourceLoader.
And it affect GPU Memory. Each adding asset increase GPU memory (each tap in memory profiler).
**To Reproduce**
```C++ 
asset = assetLoader->createAssetFromBinary(buffer, size);
gltfio::ResourceLoader({
    .engine = engine, .normalizeSkinningWeights = false, .recomputeBoundingBoxes = false
}).loadResources(asset);
asset->releaseSourceData();
engine->destroy(asset->getRoot());
asset = nullptr;
```

**Expected behavior**
After release asset gpu memory would be also released :)

**Screenshots**
<img width="1729" alt="Screenshot 2021-01-14 at 18 35 13" src="https://user-images.githubusercontent.com/51828487/104616901-e5c8e500-569b-11eb-8ca2-dd3a15355633.png">

**Question**
How can I properly delete assets after loading into Entity?
What is the right way to handle load / release assets?

**Comment by romainguy** [comment]
You also need to destroy the asset using `assetLoader->destroyAsset(asset)`, otherwise you are not releasing any of the Filament owned data. You should also remove the entities from the scene (`scene->removeEntities(asset->entities)`).

**Comment by GrigorySamokhin** [comment]
@romainguy I have same problem, but im use struct to collect Entities from loaded assets. I have 45 glb models needed to be loaded in initialisation step. So after assetLoader->destroyAsset(asset) i can't see any of my glb models, is there any other way to release data from asset, but store only Entity to use them after assetLoader->destroyAsset(asset)?

**Comment by prideout** [comment]
You can free up some CPU memory by calling `asset->releaseSourceData()` after everything has been loaded.

The asset has strong ownership over material instances, vertex buffers, index buffers, and textures, currently there is no way of transferring their ownership.  However FilamentAsset itself is just a thin wrapper and hardly uses any CPU memory after you call `releaseSourceData`.
