### ISSUE TITLE
How to override GLB material?

### ISSUE THREAD

**Issue by noseeevil** [google/filament#3427]
I loaded .glb model, and I want to change material of this model, like a shading/blending and etc.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/16321108/104727336-3563eb00-5746-11eb-8ae9-b3ca088b9d6b.png">

Should I use createMaterialGenerator() instead createUbershaderLoader() ?

and how it work? I can not find any examples of it

**Comment by romainguy** [comment]
You can create your own implementation of `MaterialProvider`. Alternatively you can replace the materials after the glTF files are loaded by setting a material directly on the renderable entities provided by `FilamentAsset`.
