### ISSUE TITLE
gltf_viewer throws an exception on a multithreaded release mode. 

### ISSUE THREAD

**Issue by BrodaJarek** [google/filament#3428]
**Describe the bug**
When I run gltf_viewer on a multithreaded release mode it throws this exception

Exception thrown at 0x00007FF75980D394 in gltf_viewer.exe: 0xC0000005: Access violation reading location 0x00000238118769CC.

On Debug mode it works. It works also on release but single threaded

**To Reproduce**
1. Build the Release version
2. Run gltf_viewer

**Expected behavior**
I expect it to run and not throw any exceptions

**Screenshots**
![image](https://user-images.githubusercontent.com/47335145/104750230-153b2880-5754-11eb-8180-425a27ea125c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: GTX 1080
 - Backend: opengl

**Comment by romainguy** [comment]
I cannot reproduce this issue on macOS. Which version of Filament are you using?

**Comment by BrodaJarek** [comment]
The main one. Just barely cloned it

**Comment by bejado** [comment]
Sounds like a Windows-specific issue, I'll take a look.

**Comment by bejado** [comment]
The crash happening in `stbi_load_from_memory`. It appears this is a regression introduced by https://github.com/google/filament/pull/3413. I'll continue to investigate further.

@prideout FYI

**Comment by prideout** [comment]
Strange.  Ben sounds like my fault, feel free to hand this over to me.  I have a Windows machine I can try.

**Comment by bejado** [comment]
Sounds good, thanks @prideout

**Comment by prideout** [comment]
I accidentally reproduced this today and I have a fix on the way.
