### ISSUE TITLE
combine-static-libs.sh doesn't handle fat .a

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#3432]
`combine-static-libs.sh` doesn't handle fat binaries which prevents us from building for arm64+x86_64 on new macs

To reproduce the issue:

```
mkdir out
cmake -GNinja -Bout -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
ninja -C out
```

**Comment by bejado** [comment]
Will take a look.
