### ISSUE TITLE
gltfio: StainedGlassLamp error (ubershader mode is ok)

### ISSUE THREAD

**Issue by prideout** [google/filament#3444]
https://github.com/KhronosGroup/glTF-Sample-Models/pull/288

```
in ssize_t filament::UniformInterfaceBlock::getUniformOffset(const char *, size_t) const:120
reason: uniform named "_maskThreshold" not found
```

**Comment by romainguy** [comment]
Link to the model: https://github.com/KhronosGroup/glTF-Sample-Models/blob/a0b090da192dde2a1c3a82dd2e3720c912631b0a/2.0/StainedGlassLamp/glTF-Binary/StainedGlassLamp.glb

**Comment by romainguy** [comment]
Note: the bug does not happen with the übershader (but then we drop transmission).
