### ISSUE TITLE
Make ColorGrading shadowsMidtonesHighlights, slopeOffsetPower, vibrance public

### ISSUE THREAD

**Issue by Yaski** [google/filament#3449]
https://github.com/google/filament/blob/main/android/filament-android/src/main/java/com/google/android/filament/ColorGrading.java

For some reason few properties doesn't have 'public' keyword
Please make them public so we can use them in applications
shadowsMidtonesHighlights
slopeOffsetPower
vibrance

**Comment by romainguy** [comment]
Good catch! The dangers of switching between Kotlin and Java code… I just pushed a fix.
