### ISSUE TITLE
FrameGraph minor issues

### ISSUE THREAD

**Issue by skaarj1989** [google/filament#3450]
Two minor flaws in FrameGraph:
1. [Redundant line of code](https://github.com/google/filament/blob/41186340c9d0da965f1fb3e2c8bcd9db8074d624/filament/src/fg/FrameGraph.cpp#L519)
2. [Arrows that supposed to be `lightgreen` are pitch black.](https://github.com/google/filament/blob/41186340c9d0da965f1fb3e2c8bcd9db8074d624/filament/src/fg/FrameGraph.cpp#L538) 

![image](https://user-images.githubusercontent.com/34756939/105770310-4d661680-5f5f-11eb-853b-b8328b34e2fe.png)

**Comment by romainguy** [comment]
Arrows appear light green for us, could it be your GraphViz version?

![foo](https://user-images.githubusercontent.com/869684/105771585-a0b37700-5f15-11eb-8205-ce915db5847d.png)

**Comment by skaarj1989** [comment]
I'm using [this](https://dreampuf.github.io/GraphvizOnline/#digraph%20%22Main%20View%22%20%7B%0D%0Arankdir%20%3D%20LR%0D%0Abgcolor%20%3D%20black%0D%0Anode%20%5Bshape%3Drectangle%2C%20fontname%3D%22helvetica%22%2C%20fontsize%3D10%5D%0D%0A%0D%0A%22P0%22%20%5Blabel%3D%22Prepare%20View%20Uniforms%5Cnrefs%3A%201%5Cnseq%3A%200%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange%5D%0D%0A%22P1%22%20%5Blabel%3D%22Structure%20Pass%5Cnrefs%3A%200%5Cnseq%3A%201%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange4%5D%0D%0A%22P2%22%20%5Blabel%3D%22Depth%20Mipmap%20Pass%5Cnrefs%3A%200%5Cnseq%3A%202%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange4%5D%0D%0A%22P3%22%20%5Blabel%3D%22Depth%20Mipmap%20Pass%5Cnrefs%3A%200%5Cnseq%3A%203%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange4%5D%0D%0A%22P4%22%20%5Blabel%3D%22Depth%20Mipmap%20Pass%5Cnrefs%3A%200%5Cnseq%3A%204%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange4%5D%0D%0A%22P5%22%20%5Blabel%3D%22Depth%20Mipmap%20Pass%5Cnrefs%3A%200%5Cnseq%3A%205%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange4%5D%0D%0A%22P6%22%20%5Blabel%3D%22Prepare%20Color%20Passes%5Cnrefs%3A%201%5Cnseq%3A%206%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange%5D%0D%0A%22P7%22%20%5Blabel%3D%22Color%20Pass%5Cnrefs%3A%201%5Cnseq%3A%207%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange%5D%0D%0A%22P8%22%20%5Blabel%3D%22Finish%20Color%20Passes%5Cnrefs%3A%201%5Cnseq%3A%208%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange%5D%0D%0A%22P9%22%20%5Blabel%3D%22colorGrading%5Cnrefs%3A%201%5Cnseq%3A%209%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange%5D%0D%0A%22P10%22%20%5Blabel%3D%22fxaa%5Cnrefs%3A%201%5Cnseq%3A%2010%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange%5D%0D%0A%22P11%22%20%5Blabel%3D%22Present%5Cnrefs%3A%201%5Cnseq%3A%2011%22%2C%20style%3Dfilled%2C%20fillcolor%3Ddarkorange%5D%0D%0A%0D%0A%22R0_0%22%5Blabel%3D%22viewRenderTarget%5Cn(version%3A%200)%5Cnid%3A0%5Cnrefs%3A2%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dpalegreen%5D%0D%0A%22R1_0%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%200)%5Cnid%3A1%5Cnrefs%3A0%2C%20renderbuffer%5Cn512x320%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R1_1%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%201)%5Cnid%3A1%5Cnrefs%3A0%2C%20renderbuffer%5Cn512x320%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R2_0%22%5Blabel%3D%22Structure%20Target%5Cn(version%3A%200)%5Cnid%3A2%5Cnrefs%3A0%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R1_2%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%202)%5Cnid%3A1%5Cnrefs%3A0%2C%20renderbuffer%5Cn512x320%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R3_0%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%200)%5Cnid%3A3%5Cnrefs%3A0%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R1_3%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%203)%5Cnid%3A1%5Cnrefs%3A0%2C%20renderbuffer%5Cn512x320%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R4_0%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%200)%5Cnid%3A4%5Cnrefs%3A0%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R1_4%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%204)%5Cnid%3A1%5Cnrefs%3A0%2C%20renderbuffer%5Cn512x320%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R5_0%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%200)%5Cnid%3A5%5Cnrefs%3A0%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R1_5%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%205)%5Cnid%3A1%5Cnrefs%3A0%2C%20renderbuffer%5Cn512x320%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R6_0%22%5Blabel%3D%22Structure%20Buffer%5Cn(version%3A%200)%5Cnid%3A6%5Cnrefs%3A0%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue4%5D%0D%0A%22R7_0%22%5Blabel%3D%22Color%20Buffer%5Cn(version%3A%200)%5Cnid%3A7%5Cnrefs%3A2%2C%20texture%5Cn1024x640%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R8_0%22%5Blabel%3D%22Depth%20Buffer%5Cn(version%3A%200)%5Cnid%3A8%5Cnrefs%3A1%2C%20renderbuffer%5Cn1024x640%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R7_1%22%5Blabel%3D%22Color%20Buffer%5Cn(version%3A%201)%5Cnid%3A7%5Cnrefs%3A2%2C%20texture%5Cn1024x640%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R8_1%22%5Blabel%3D%22Depth%20Buffer%5Cn(version%3A%201)%5Cnid%3A8%5Cnrefs%3A1%2C%20renderbuffer%5Cn1024x640%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R9_0%22%5Blabel%3D%22Color%20Pass%20Target%5Cn(version%3A%200)%5Cnid%3A9%5Cnrefs%3A1%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R10_0%22%5Blabel%3D%22colorGrading%20output%5Cn(version%3A%200)%5Cnid%3A10%5Cnrefs%3A1%2C%20texture%5Cn1024x640%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R10_1%22%5Blabel%3D%22colorGrading%20output%5Cn(version%3A%201)%5Cnid%3A10%5Cnrefs%3A1%2C%20texture%5Cn1024x640%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R11_0%22%5Blabel%3D%22colorGrading%20Target%5Cn(version%3A%200)%5Cnid%3A11%5Cnrefs%3A1%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R12_0%22%5Blabel%3D%22fxaa%20output%5Cn(version%3A%200)%5Cnid%3A12%5Cnrefs%3A1%2C%20renderbuffer%5Cn1024x640%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R12_1%22%5Blabel%3D%22fxaa%20output%5Cn(version%3A%201)%5Cnid%3A12%5Cnrefs%3A1%2C%20renderbuffer%5Cn1024x640%22%2C%20style%3Dfilled%2C%20fillcolor%3Dskyblue%5D%0D%0A%22R0_0%22%5Blabel%3D%22viewRenderTarget%5Cn(version%3A%200)%5Cnid%3A0%5Cnrefs%3A2%2C%20RenderTarget%22%2C%20style%3Dfilled%2C%20fillcolor%3Dpalegreen%5D%0D%0A%0D%0AP0%20-%3E%20%7B%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP1%20-%3E%20%7B%20R1_1%20R1_1%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP2%20-%3E%20%7B%20R1_2%20R1_2%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP3%20-%3E%20%7B%20R1_3%20R1_3%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP4%20-%3E%20%7B%20R1_4%20R1_4%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP5%20-%3E%20%7B%20R1_5%20R1_5%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP6%20-%3E%20%7B%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP7%20-%3E%20%7B%20R7_1%20R7_1%20R8_1%20R8_1%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP8%20-%3E%20%7B%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP9%20-%3E%20%7B%20R10_1%20R10_1%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP10%20-%3E%20%7B%20R12_1%20R12_1%20%7D%20%5Bcolor%3Dred2%5D%0D%0AP11%20-%3E%20%7B%20%7D%20%5Bcolor%3Dred2%5D%0D%0A%0D%0AR0_0%20-%3E%20%7B%20P10%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR1_0%20-%3E%20%7B%20P1%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR1_1%20-%3E%20%7B%20P2%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR2_0%20-%3E%20%7B%20P1%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR1_2%20-%3E%20%7B%20P3%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR3_0%20-%3E%20%7B%20P2%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR1_3%20-%3E%20%7B%20P4%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR4_0%20-%3E%20%7B%20P3%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR1_4%20-%3E%20%7B%20P5%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR5_0%20-%3E%20%7B%20P4%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR1_5%20-%3E%20%7B%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR6_0%20-%3E%20%7B%20P5%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR7_0%20-%3E%20%7B%20P7%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR8_0%20-%3E%20%7B%20P7%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR7_1%20-%3E%20%7B%20P9%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR8_1%20-%3E%20%7B%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR9_0%20-%3E%20%7B%20P7%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR10_0%20-%3E%20%7B%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR10_1%20-%3E%20%7B%20P10%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR11_0%20-%3E%20%7B%20P9%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR12_0%20-%3E%20%7B%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR12_1%20-%3E%20%7B%20P11%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0AR0_0%20-%3E%20%7B%20P10%20%7D%20%5Bcolor%3Dlightgreen%5D%0D%0A%7D) viewer

**Comment by romainguy** [comment]
`lightgreen` is part of the supported color set: https://www.graphviz.org/doc/info/colors.html

It was apparently added to upstream GraphViz [~2 years ago](https://gitlab.com/graphviz/graphviz/-/issues/1446), it seems like this viewer is out of date.

**Comment by romainguy** [comment]
Please try again with the new rewrite of framegraph.
