### ISSUE TITLE
SurfaceView with transparent background issue

### ISSUE THREAD

**Issue by GiorgioCarosi** [google/filament#3460]
Hi, i'm currently using surfaceView.setOpaque(true) on my glb model to make sure that it doesn't overlap the other UI element but i'm not able to see transparent background. In particular if you see the attached screenshot, i should be able to see an image as a background (the one you see on the bottom) while i'm getting a black screen. 

I also used setOpaque(false) but in that case i could see a transparent background but the 3d model was on top of the other UI elements. 
I also tried the texture view but it didn't show me the model.

Any suggestions?
Thanks in advance

p.s. whether or not I put the skybox (or I put it null) the result does not change.

Image below - surfaceView.setOpaque(true)
![1611769008350](https://user-images.githubusercontent.com/74369948/106033146-aeadf700-60d1-11eb-833a-e7fd6c0e8c28.JPEG)

Image below - surfaceView.setOpaque(false)
![1611770453160](https://user-images.githubusercontent.com/74369948/106033469-15331500-60d2-11eb-915a-8975d51ac26a.JPEG)

**Comment by romainguy** [comment]
Please refer to this sample: https://github.com/google/filament/blob/main/android/samples/sample-transparent-view/src/main/java/com/google/android/filament/transparentrendering/MainActivity.kt

To do this right you need to properly configure the SurfaceView (which you don't do by calling `setOapque` but by setting the `TRANSLUCENT` `PixelFormat` on its holder. You also need to create a transparent `SwapChain` for Filament. The easiest way to do this is to use the `UiHelper` we provide as part of Filament, as seen in the sample.

**Comment by GiorgioCarosi** [comment]
Hi Romainguy, sorry but it doesn't solve my problem because if i use "surfaceview.SetOpaque = false" this will set automatically the TRANSLUCENT PixelFormat on its holder (I can see this when the attachTo function of the SurfaceView is called)and also the swapchain will use automatically the Transparent config. Now at this stage I'm able to see the transparent background but model is over the other UI elements (which is the second screenshot I sent you).

**Comment by romainguy** [comment]
A transparent surface view is meant to go *above* the UI elements. You cannot "sandwich" a SurfaceView between buttons and a background for instance (think of a SurfaceView as a separate window).

**Comment by dandingol03** [comment]
> Please refer to this sample: https://github.com/google/filament/blob/main/android/samples/sample-transparent-view/src/main/java/com/google/android/filament/transparentrendering/MainActivity.kt
> 
> To do this right you need to properly configure the SurfaceView (which you don't do by calling `setOapque` but by setting the `TRANSLUCENT` `PixelFormat` on its holder. You also need to create a transparent `SwapChain` for Filament. The easiest way to do this is to use the `UiHelper` we provide as part of Filament, as seen in the sample.

uiHelper is amazing!
