### ISSUE TITLE
How we get ModelViewer's root transform ?

### ISSUE THREAD

**Issue by duy-maimanh** [google/filament#3467]
Hello. I try this example but it did not working. I think it was outdated.

> modelViewer.asset?.apply {
                modelViewer.transformToUnitCube()
                val rootTransform = this.root.getTransform()
                val degrees = 20f * seconds.toFloat()
                val zAxis = Float3(0f, 0f, 1f)
                this.root.setTransform(rootTransform * rotation(zAxis, degrees))
            }

So how do we get the  ModelViewer's root transform in a new way?

**Comment by prideout** [comment]
`modelViewer.asset.root` is just an `Entity` so you need to use `TransformManager` to get to its transform component.
