### ISSUE TITLE
Potential memory leak in MaterialProvider.destroy

### ISSUE THREAD

**Issue by stevexbritton** [google/filament#3469]
**Describe the bug**
Memory leak in MaterialProvider.destroy()
Repeated calls to the following leaks 1.2Mbytes per iteration:
     materialProvider = MaterialProvider(engine)
     assetLoader = AssetLoader(engine, materialProvider, EntityManager.get())
     asset = assetLoader?.createAssetFromJson(buffer)

     assetLoader?.destroyAsset(asset)
     assetLoader?.destroy()
     assetLoader = null
     materialProvider?.destroy()
     materialProvider = null

**To Reproduce**
1. Modified loadModelGltfAsync and destroyModel in the loadModelGltfAsyncsample-gltf-viewer 1.9.9
[ModelViewer.kt.zip](https://github.com/google/filament/files/5895185/ModelViewer.kt.zip)

 to achieve the above (see attached file).
2. Each double tap leaks about 1.2M of memory.

**Expected behavior**
No memory leak. (This does appear to be the case if we do not create a new MaterialProvider for each iteration)

**Screenshots**

**Desktop (please complete the following information):**
 - Android

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android Pie 10

**Additional context**

**Comment by prideout** [comment]
Thanks, we are not exposing `destroyMaterials` in `MaterialProvider` to Java, which is a bug.

Also: the Java comment for AssetLoader `destroy` is inconsistent with the C++ comment, which says:

```
     * This does not not automatically free the cache of materials, nor
     * does it free the entities for created assets (see destroyAsset).
```

I'll fix these.
