### ISSUE TITLE
Add the count for the Variable，but encounter other error

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3475]
I need add the count of Variable,some I change code like below.
But When I compile the *.mat file,encounter the error:
E
RROR: 0:97: 'location' : overlapping use of location 4
ERROR: 1 compilation errors.  No code ge
nerated.

Please give me a guide and tell me where I need to modify. Thank you！

diff --git a/libs/filamat/include/filamat/MaterialBuilder.h b/libs/filamat/include/filamat/MaterialBuilder.h
index 536291b4..5df7dc84 100644
--- a/libs/filamat/include/filamat/MaterialBuilder.h
+++ b/libs/filamat/include/filamat/MaterialBuilder.h
@@ -167,12 +167,16 @@ class UTILS_PUBLIC MaterialBuilder : public MaterialBuilderBase {
 public:
     MaterialBuilder();

-    static constexpr size_t MATERIAL_VARIABLES_COUNT = 4;
+    static constexpr size_t MATERIAL_VARIABLES_COUNT = 8;
     enum class Variable : uint8_t {
         CUSTOM0,
         CUSTOM1,
         CUSTOM2,
-        CUSTOM3
+        CUSTOM3,
+        CUSTOM4,
+        CUSTOM5,
+        CUSTOM6,
+        CUSTOM7
         // when adding more variables, make sure to update MATERIAL_VARIABLES_COUNT
     };

diff --git a/libs/filamat/src/MaterialBuilder.cpp b/libs/filamat/src/MaterialBuilder.cpp
index d7273e6f..91bac8bc 100644
--- a/libs/filamat/src/MaterialBuilder.cpp
+++ b/libs/filamat/src/MaterialBuilder.cpp
@@ -170,6 +170,10 @@ MaterialBuilder& MaterialBuilder::variable(Variable v, const char* name) noexcep
         case Variable::CUSTOM1:
         case Variable::CUSTOM2:
         case Variable::CUSTOM3:
+        case Variable::CUSTOM4:
+        case Variable::CUSTOM5:
+        case Variable::CUSTOM6:
+        case Variable::CUSTOM7:
             assert(size_t(v) < MATERIAL_VARIABLES_COUNT);
             mVariables[size_t(v)] = CString(name);
             break;
diff --git a/tools/matc/src/matc/ParametersProcessor.cpp b/tools/matc/src/matc/ParametersProcessor.cpp
index 4fd0c57e..6b4dee1a 100644
--- a/tools/matc/src/matc/ParametersProcessor.cpp
+++ b/tools/matc/src/matc/ParametersProcessor.cpp
@@ -59,6 +59,10 @@ static MaterialBuilder::Variable intToVariable(size_t i) noexcept {
         case 1:  return MaterialBuilder::Variable::CUSTOM1;
         case 2:  return MaterialBuilder::Variable::CUSTOM2;
         case 3:  return MaterialBuilder::Variable::CUSTOM3;
+        case 4:  return MaterialBuilder::Variable::CUSTOM4;
+        case 5:  return MaterialBuilder::Variable::CUSTOM5;
+        case 6:  return MaterialBuilder::Variable::CUSTOM6;
+        case 7:  return MaterialBuilder::Variable::CUSTOM7;
         default: return MaterialBuilder::Variable::CUSTOM0;
     }
 }
@@ -256,8 +260,8 @@ static bool processVariables(MaterialBuilder& builder, const JsonishValue& value
     const JsonishArray* jsonArray = value.toJsonArray();
     const auto& elements = jsonArray->getElements();

-    if (elements.size() > 4) {
-        std::cerr << "variables: Max array size is 4." << std::endl;
+    if (elements.size() > 8) {
+        std::cerr << "variables: Max array size is 8." << std::endl;
         return false;
     }

**Comment by romainguy** [comment]
You would have to update other parts of the code that generate uniform/attribute locations. But note that adding 4 attributes like this will put you above limits on some platforms (webgl, OpenGL ES).
