### ISSUE TITLE
android sample-hello-triangle  show nothing

### ISSUE THREAD

**Issue by ab503044120** [google/filament#3477]
**Describe the bug**
android sample-hello-triangle  show nothing
![image](https://user-images.githubusercontent.com/5219122/106355310-f5019100-6331-11eb-8764-801a85d20c84.png)
** version
tag: v1.9.9
**To Reproduce**
build in windows 10 and run it in android studio,
sample-hello-triangle show black screen, but sample -gltf-viewer show well
![image](https://user-images.githubusercontent.com/5219122/106355374-62adbd00-6332-11eb-89e8-9e21e6b5fdfa.png)

device: xiaomi 9  and xiaomi note 3

**Comment by ab503044120** [comment]
i checkout v1.8.1 android can work well

**Comment by prideout** [comment]
Does it work on other devices?  Can you try with a more recent version of Filament?

**Comment by ab503044120** [comment]
> Does it work on other devices? Can you try with a more recent version of Filament?

1.9.14 work well
