### ISSUE TITLE
support for surface subdivision

### ISSUE THREAD

**Issue by fishelegs** [google/filament#3479]
How can I extend filament to support surface subdivision?

![image](https://user-images.githubusercontent.com/1646940/106435874-61090400-64ae-11eb-8588-178571677ca5.png)

Is this feature OS/backend specific? 
NO

**Comment by prideout** [comment]
You should be able to use Pixar's OpenSubdiv to perform subdivision, then upload the results into a `filament::VertexBuffer`.
