### ISSUE TITLE
Drawing (annotation) custom shapes in Filament Android (like JustALine app)

### ISSUE THREAD

**Issue by udayk07** [google/filament#3481]
Is there any option/workaround to draw shapes/annotate objects ( like pen tool options) in filament Android ( Like JustAline App ) ?

https://github.com/googlecreativelab/justaline-android

**Comment by prideout** [comment]
Filament's `PrimitiveType` enumeration includes TRIANGLES, LINES, and POINTS, so yes you can draw whatever shape you can dream of.
