### ISSUE TITLE
Can I get the Light world position and the Light direction in Lit shadingModel ?

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3488]
I found some code snipt in matc comile output.But I did not found API in document.

    if (cascade == 0u) {
        return getLightSpacePosition();
    }

    highp vec4 pos = computeLightSpacePosition(getWorldPosition(), getWorldNormalVector(),
        frameUniforms.lightDirection, frameUniforms.shadowBias.y,
        frameUniforms.lightFromWorldMatrix[cascade]);

If there is some API can let me get the light world position and light direction ?

**Comment by romainguy** [comment]
You can technically use those variables for the directional light but it won't work for other lights. It's why we don't expose it as a supported public API. You could however pass that information yourself as material params.
