### ISSUE TITLE
material_sandbox substance model seems not work

### ISSUE THREAD

**Issue by ohouha** [google/filament#3496]
**Describe the bug**
I tried mterial_sandbox, and found there's no diff if I change lit mode to subsurface model, and also when i try to pick other color of subsurface color, there's no reaction in the view.

**To Reproduce**
1. I just run ./material_sandbox -i ./default_env/ ./assets/models/monkey/monkey.obj

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Linux, ubuntu 18.04
 - GPU: [e.g. NVIDIA GTX 2080]
 - Backend: [OpenGL/Vulkan]

**Additional context**

**Comment by romainguy** [comment]
It works but the effect is easier to see without an IBL. Looking directly at a light through the object also helps.
