### ISSUE TITLE
How can materials be backward compatible?

### ISSUE THREAD

**Issue by shlzxjp** [google/filament#3497]
![image](https://user-images.githubusercontent.com/8434971/106865928-ce16d680-6706-11eb-9822-2cadfcaac8cd.png)

I found that the filament material version (MATERIAL_VERSION) is frequently upgraded and is not compatible with the old material. How to achieve backward compatibility?

**Comment by romainguy** [comment]
Materials must match the version used by Filament, a change in version indicates an incompatible change in the shaders. You can simply recompile your materials with matc though. Note that we avoid changing the version as much as possible.

**Comment by shlzxjp** [comment]
Can I achieve backward compatibility without recompiling the material?

**Comment by romainguy** [comment]
It is not possible unfortunately. We change the version number when we make incompatible changes in the shaders.
