### ISSUE TITLE
How can I get the same position with Unity ?

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3498]
I have a sphere which is exported from unity used gltf format.
In filament the sphere‘shape show right，but the material display abnormal.

The material shader in Unity like below:

					vertexOutput output;
					float4x4 modelMatrix = unity_ObjectToWorld;
					float4x4 modelMatrixInverse = unity_WorldToObject;
					output.posWorld = mul(modelMatrix, input.vertex);
					float3 v3Pos = mul(unity_ObjectToWorld, input.vertex).xyz - v3Translate;

In Filament I write the shader:

    void materialVertex(inout MaterialVertexInputs material) {
        //material.pos = mulMat4x4Float3(getClipFromWorldMatrix(),material.worldPosition.xyz);
        float3 v3CameraPos = float3(0.3,0.5,-2.0);// getWorldCameraPosition() - materialParams.v3Translate;
        float fCameraHeight = length(v3CameraPos);
        float fCameraHeight2 = fCameraHeight*fCameraHeight;
        float3 p = getPosition().xyz;
        float3 v3Pos = material.worldPosition.xyz + getWorldOffset() ;

I debuged and found the cause of display abnormal in Filament is what the **_v3Pos_** is different with Unity.

How can I get the same value with the unity ?
Thanks for any suggestion.

**Comment by romainguy** [comment]
Your shaders are not equivalent. In the Unity version you subtract `v3Translate` from the world position but in Filament you do this on the camera position instead. It seems like your material should read:

```
float3 v3Pos = material.worldPosition.xyz + getWorldOffset() - v3Translate;
```

**Comment by fanbinnet** [comment]
the v3Translate is an uniform  and the value is (0.,0.,0.). So this is not the cause for the abnormal.
