### ISSUE TITLE
face mask rendered from ARcore AugmentedFace object vertices/indexes is distorted

### ISSUE THREAD

**Issue by kiler222** [google/filament#3499]
When I try to render a face mask using vertices, indexes from ARcore Augmented Face node, then the final result is corrupted. The face mask is at the correct position, but the texture is not solid. You can check it how it looks [here](https://i.stack.imgur.com/6dSCy.jpg).

I take meshes from the AugmentedFace object:
`val meshVertices = face.meshVertices`
`val uvs = face.meshTextureCoordinates`
`val meshNormals = face.meshNormals`
`val meshIndices = face.meshTriangleIndices`

Buffers are created like that:
`faceVertexBuffer = VertexBuffer.Builder()`
`    .bufferCount(3)`
 `   .vertexCount(468)`
  `  .attribute(VertexBuffer.VertexAttribute.POSITION, 0, VertexBuffer.AttributeType.FLOAT3, 0, 3 * Float.SIZE_BYTES)`
   ` .attribute(VertexBuffer.VertexAttribute.TANGENTS, 1, VertexBuffer.AttributeType.FLOAT3, 0,             3 * Float.SIZE_BYTES)`
`    .attribute(VertexBuffer.VertexAttribute.UV0, 2, VertexBuffer.AttributeType.FLOAT2, 0,             2 * Float.SIZE_BYTES)`
 `   .build(filament.engine)`

`meshVertices.rewind()`
`meshNormals.rewind()`
`uvs.rewind()`

`faceVertexBuffer.setBufferAt(filament.engine, 0, meshVertices)`
`faceVertexBuffer.setBufferAt(filament.engine, 1, meshNormals)`
`faceVertexBuffer.setBufferAt(filament.engine, 2, uvs)`

`faceIndexBuffer = IndexBuffer.Builder()`
`    .indexCount(2694)`
`    .bufferType(IndexBuffer.Builder.IndexType.USHORT)`
`    .build(filament.engine)`

`meshIndices.rewind()`
`faceIndexBuffer.setBuffer(filament.engine, meshIndices)`

And I render it:
`RenderableManager.Builder(1)`
`.boundingBox(Box(0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f))`
`.geometry(0, RenderableManager.PrimitiveType.TRIANGLES, faceVertexBuffer, faceIndexBuffer, 0, 468)`
`.material(0, materialInstance)`
`.build(filament.engine, faceRenderable)`
`filament.scene.addEntity(faceRenderable)`

Do you have any suggestions what am I doing wrong? What am I missing?

**Comment by romainguy** [comment]
Filament expects a tangent frame not just normal vectors in the `TANGENTS` attribute. You can use the `SurfaceOrientation` API to generate those tangent frames directly. Also, are your vertex and index counts correct since you hardcode them?

**Comment by kiler222** [comment]
Thanks @romainguy for the hint. I tried SurfaceOrientation API and some other stuff.
So I build SurfaceOrientation in a few configuration and then get tangents using getQuatsAsFloat. 
I have the following results:

1. When I use normals only, then nothing is changed. The mask is distorted as before.
2. For positions + indices I get error `libfilament-jni.so (offset 0x7b1000) (filament::geometry::OrientationBuilderImpl::buildWithFlatNormals()+136) (BuildId: 54802414ffabe932202b04617aef440852b15774)`
3. For normals + uvs + positions + indices I get error `libfilament-jni.so (offset 0x7b1000) (filament::geometry::OrientationBuilderImpl::buildWithUvs()+820)` And when I remove uvs from the builder then there is no error and nothing is changed.

I checked Sceneform sdk and I found out that they build tangents from normals only. I implemented the same function in my app and nothing has changed. They also convert indices from short to int. I tried that as well, no success.

Also I tried to build vertexbuffer using only position buffer. Again I got distorted mask in the same way as before.

Do you have any other idea what should I check?

**Comment by kiler222** [comment]
@romainguy do you have any suggestions what is wrong?

**Comment by pixelflinger** [comment]
I think this should be moved into a discussion. There won't be any action/fixes on our side at this point.
