### ISSUE TITLE
Shadows?

### ISSUE THREAD

**Issue by gtarplyer1** [google/filament#350]
Does Filament do shadows?  Or better yet, what is the state of the shadows feature?

I think it does do shadowing, the render with the chess pieces has shadows, but they do not look correct.  They look too light, or maybe where the shadow meets the chess piece, its too light, it should be darker as is gets closer to object.

Thanks for any info.

**Comment by romainguy** [comment]
Filament supports shadows yes.

**Comment by pixelflinger** [comment]
We only support hard shadows from the single directional light. We don't use cascades, but compensate somewhat with LiSPSM, which uses a projection that gives more resolution to shadows closer to the camera.  We also employ various techniques to fight shadow acne, none being perfect. We don't support raytracing or anything like that.

**Comment by seasiainfotech** [comment]
> Filament supports shadows yes.

how is it possible?
