### ISSUE TITLE
Depth issue when post-processing is disabled.

### ISSUE THREAD

**Issue by prideout** [google/filament#3501]
To repro, run the RenderTarget demo with #3500.  Screenshot below.  Occurs with all backends.

<img width="354" alt="Screen Shot 2021-02-04 at 9 45 09 AM" src="https://user-images.githubusercontent.com/1288904/106933404-b53dff00-66cd-11eb-9531-4f2e85abd387.png">

**Comment by romainguy** [comment]
@pixelflinger, this happens when post processing is disabled for an offscreen render target. Do we not allocate a depth buffer or something?

**Comment by pixelflinger** [comment]
Not that I know. I would be interesting to look at the framegraph.

**Comment by prideout** [comment]
This is not a Filament bug, the demo is not creating a depth attachment.  **facepalm**
