### ISSUE TITLE
Navigate inside 3d model

### ISSUE THREAD

**Issue by Zumbalamambo** [google/filament#3506]
Is there any example on how I can navigate inside the 3d model?

**Comment by prideout** [comment]
You can try gltf_viewer with the `-c` argument which enables FREE_FLIGHT mode in our camera manipulator helper library, which is documented [here](https://github.com/google/filament/blob/main/libs/camutils/include/camutils/Manipulator.h).

WASD-style controls are accepted in `FilamentApp::manipulatorKeyFromKeycode`.
