### ISSUE TITLE
bug in backend::PixelBufferDescriptor::computeDataSize

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3512]
**Describe the bug**

I think computeDataSize produces incorrect outputs for some inputs.

I'm assuming that `PixelDataType::USHORT_565` would normally be used together with `PixelDataFormat::RGB_INTEGER`.  In that case, the code sets `n` to 3, and then `bpp` to 3.  Then a switch says `bpp *= 2`, so `bpp` becomes 6.  But I think that `USHORT_565` intends to pack the pixel into 2 bytes, so the switch case for `USHORT_565` should be `bpp = 2`.  Maybe there should also be an assertion, as in the case for `PixelDataType::UINT_2_10_10_10_REV`.

**Comment by romainguy** [comment]
`bpp` should always be `2` for `USHORT_565` and the format should always be `RGB` in that case.
