### ISSUE TITLE
Continuously tint indirect light?

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3522]
**Is your feature request related to a problem? Please describe.**

If I have a scene that's gradually transitioning from midday to dusk, I'd like the indirect light to gradually get dimmer and redder.  Creating a whole series of cube maps seems unwieldy.

**Describe the solution you'd like**

Could `IndirectLight::setIntensity` take an RGB parameter instead of a float?

**Comment by romainguy** [comment]
`setIntensity()` is a physical light unit, it wouldn't make much sense to have it be an RGB color. We could add a tint parameter but that would only work for very simple cases and not really for realistic IBLs. One way to achieve what you want is to instead change the white balance of the image via the `ColorGrading` API.

**Comment by jwwalker** [comment]
@romainguy I don't think `ColorGrading` would do what I want. If I understand correctly, it would affect the whole image, including light coming from local point or spot lights as well as ambient light.
