### ISSUE TITLE
Documentation Bug: Incrementing Subsection Numbers Don't Reset

### ISSUE THREAD

**Issue by Lucodivo** [google/filament#3525]
**Describe the bug**
A new section/subsection does not reset incrementing subsections/sub-subsections. [see screenshot]

**To Reproduce**
View documentation on Mozilla Firefox using Windows 10.

**Expected behavior**
Subsection numbers should reset after every section.
Sub-subsection numbers should reset after every subsection.

**Screenshots**
This is a picture of the beginning of section 8.
<img width="566" alt="Filament_SubsectionBug" src="https://user-images.githubusercontent.com/5397399/107317704-02183180-6a50-11eb-8c0d-f1bf1da1e31e.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by romainguy** [comment]
I can't reproduce the bug on my browsers. If it happens with Filament.md.html it's a bug in Markdeep (https://casual-effects.com/markdeep/).
