### ISSUE TITLE
build issue : log is stoped at '-- Found Threads: TRUE  '

### ISSUE THREAD

**Issue by bambootang** [google/filament#3532]
when i run command './build.sh release'

log is stoped at '-- Found Threads: TRUE  '

Building release in out/cmake-release...
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang
-- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- DFG LUT size set to 128x128
-- No Vulkan SDK was found, using prebuilt MoltenVK.
-- Found Python3: /usr/local/Frameworks/Python.framework/Versions/3.9/bin/python3.9 (found version "3.9.1") found components: Interpreter 
-- Found PythonInterp: /Users/tangshuai/anaconda3/bin/python3 (found suitable version "3.8.3", minimum required is "3") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE

**Comment by bambootang** [comment]
![image](https://user-images.githubusercontent.com/5106326/107721724-49d0de80-6d18-11eb-95c2-03ead800f4b5.png)

**Comment by bambootang** [comment]
![image](https://user-images.githubusercontent.com/5106326/107721749-5bb28180-6d18-11eb-8f84-695411bf6388.png)

**Comment by romainguy** [comment]
I don't see anything wrong in the logs. Is it truly stuck or taking time? Try to run build.sh -c first as well. Otherwise I don't see anything we can do for you here :/

**Comment by bambootang** [comment]
i had retry  more times，and each time it is stoped at Found Threads:TRUE，no matter how long you wait  it can't go to next step.

**Comment by bambootang** [comment]
i don't know what happend, and i can't find the reason. has anyone else encountered it?

**Comment by romainguy** [comment]
You could try two things:
- Update CMake
- Use ActivityMonitor to see which process is hanging and/or where
