### ISSUE TITLE
Clear coat documentation equation

### ISSUE THREAD

**Issue by tombsar** [google/filament#3555]
In Filament's documentation (here: https://google.github.io/filament/Filament.html#materialsystem/clearcoatmodel/integrationinthesurfaceresponse) the equation for combining the clear coat with the standard model uses n where I believe it should use v.

`f(v,l)=\fDiffuse(n,l) (1 - F_c) + \fSpecular(n,l) (1 - F_c) + f_c(n,l)`

vs

`f(v,l)=\fDiffuse(**v**,l) (1 - F_c) + \fSpecular(**v**,l) (1 - F_c) + f_c(**v**,l)`

**Comment by romainguy** [comment]
Thanks, I just uploaded a fix.
