### ISSUE TITLE
Documentation section numbering is incorrect

### ISSUE THREAD

**Issue by tombsar** [google/filament#3556]
Throughout the documentation the numbering in the table of contents does not match the section numbering of the rest of the document. It looks like the subsection numbering resets to 1 for every new section in the ToC (correctly), but continues to count up across sections in the body of the document (incorrectly).

e.g. https://google.github.io/filament/Materials.html#overview/coreconcepts is the first subsection of section 2 (so appears as 2.1 in the ToC), but is labelled as 2.2.

It's possible this is a browser bug, as I don't see anything wrong with the CSS. I'm using Firefox 85.0.2 (64-bit) on Windows 10.

**Comment by romainguy** [comment]
It's properly labeled 2.1 in Chrome and Safari.
