### ISSUE TITLE
Documentation comment update needed in Camera.h

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3559]
In filament/include/filament/Camera.h, under "Creation and destruction", we are told to destroy a camera using `Engine::destroy(const Camera*)`, and then there is a code sample doing that as well as creating a camera using `Engine::createCamera()`.  But in filament/include/filament/Engine.h, both of those methods are deprecated.

**Comment by romainguy** [comment]
Thanks, I fixed the docs!
