### ISSUE TITLE
Windows Vulkan problem

### ISSUE THREAD

**Issue by FakerShy** [google/filament#3562]
**Describe the bug**
When I finished building the filament on Windows，The configured backend is opengl.When I change the configuration to Vulkan ，The library doesn't work.

The program gave me some logs.But i dont know how to fix it.So i need some help.
VULKAN ERROR: (VUID-vkMapMemory-size-00680) Validation Error: [ VUID-vkMapMemory-size-00680 ] Object 0: handle = 0x8e7343000000014d, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xff4787ab | VkMapMemory: Attempting to map memory range of size zero The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must be greater than 0 (https://vulkan.lunarg.com/doc/view/1.2.141.0/windows/1.2-extensions/vkspec.html#VUID-vkMapMemory-size-00680)

**To Reproduce**
config.backend = filament::Engine::Backend::VULKAN;

 - OS: [e.g. windows]
 - GPU: [e.g. NVIDIA GTX 1660ti]
 - Backend: [Vulkan]

**Comment by prideout** [comment]
Thanks, we currently trigger some known validation messages, but this one is new to me.  Which sample app are you running?  Does it work in release configuration?

**Comment by FakerShy** [comment]
Sample is suzanne. My program runs in win10, vs version is 2019, and the downloaded version is 1.9.12.I found the compilation option of cmakelist in windows，I changed option(FILAMENT_SUPPORTS_VULKAN "Include the Vulkan backend" ON).But it 
didn't work,I only changed the compilation options and configuration in the project. OpenGL works, Vulkan doesn't.
I've tried many examples, all of which are about this problem. I doubt the version of Vulkan. 1.1.0 1.2 doesn't work. My own program has no problem using Vulkan, so I need your help.

**Comment by wumo** [comment]
Also failed due to validation error. OS: Windows 10, Nvidia RTX 3080.
```
filament\cmake-build-debug\samples\gltf_viewer.exe --api vulkan
FEngine (64 bits) created at 000002714928B080 (threading is enabled)
FEngine resolved backend: Vulkan
Vulkan device driver: NVIDIA 461.40
Selected physical device 'GeForce RTX 3080' from 1 physical devices. (vendor 0x10de, device 0x2206, driver 0x734a0000, a
pi 1.2)
Sampleable depth formats: VK_FORMAT_D16_UNORM VK_FORMAT_X8_D24_UNORM_PACK32 VK_FORMAT_D32_SFLOAT VK_FORMAT_S8_UINT VK_FO
RMAT_D24_UNORM_S8_UINT VK_FORMAT_D32_SFLOAT_S8_UINT
vkCreateSwapchain: 1024x640, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 3, VK_SURFACE_TRANSFORM_IDENTI
TY_BIT_KHR
VULKAN ERROR: (VUID-VkImageViewCreateInfo-subresourceRange-01718) Validation Error: [ VUID-VkImageViewCreateInfo-subreso
urceRange-01718 ] Object 0: handle = 0x771ada00000000bf, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x1405bc25 | vkCreat
eImageView: pCreateInfo->subresourceRange.baseMipLevel + .levelCount (= 0 + 6 = 6) is greater than the mip level count o
f the image (i.e. greater than 5). The Vulkan spec states: If subresourceRange.levelCount is not VK_REMAINING_MIP_LEVELS
, subresourceRange.baseMipLevel + subresourceRange.levelCount must be less than or equal to the mipLevels specified in V
kImageCreateInfo when image was created (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html
#VUID-VkImageViewCreateInfo-subresourceRange-01718)
```

**Comment by romainguy** [comment]
This was just fixed yesterday, please try with tip of tree from the main branch.

**Comment by wumo** [comment]
@romainguy  Yeah, It is fixed.

**Comment by prideout** [comment]
@FakerShy I _think_ your original issue is fixed now, if not please re-open this bug -- I can take a look fairly soon, since I have a Windows NVIDIA machine now (I didn't have one when you filed the bug).
