### ISSUE TITLE
Apple M1 Chip

### ISSUE THREAD

**Issue by Pankaj003** [google/filament#3563]
@bejado @romainguy 
Hi,
I've few question regarding new Apple M1 chip. 
1. Is Filament library tested with this new Chip?
2. Do you see any issue we may face with Filament library on using this Chip?
3. I am using OpenGL backend in my project, do Filament supports OpenGL with M1 Chip or I need to move to Metal framework?

Thanks,
Pankaj

**Comment by romainguy** [comment]
You can build Filament for M1 chips natively (see build.sh --help) or you can just rely on x86 translation. There shouldn't be issues since M1 is just arm64 that we support on Android and iOS. GL is supported on M1.

**Comment by Pankaj003** [comment]
@romainguy  
Thanks....
