### ISSUE TITLE
Change the light in onAnimationUpdate not work

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3564]
I run the example for android.
But When I want change the light direction or intensity in onAnimationUpdate ,it not work.

engine.lightManager.setIntensity(light, a.animatedValue as Float * 1000_000f)

The light create in steupScene

     light = EntityManager.get().create()

        // Create a color from a temperature (5,500K)
        val (r, g, b) = Colors.cct(5_500.0f)
        LightManager.Builder(LightManager.Type.DIRECTIONAL)
                .color(r, g, b)
                // Intensity of the sun in lux on a clear day
                .intensity(110_000.0f)
                // The direction is normalized on our behalf
                .direction(0.0f, -0.5f, -1.0f)
                .castShadows(true)
                .build(engine, light)

        // Add the entity to the scene to light it
        scene.addEntity(light)

If this is a bug, or there are some restrictions ?

**Comment by romainguy** [comment]
The managers (like `LightManager`) don't use an `Entity` to set values, but an instance of their component on a given `Entity`. You can see how it's done for the transform for instance:

```
tcm.setTransform(tcm.getInstance(renderable), transformMatrix)
```

You first need to obtain an instance. So in your case:

```
lightManager.setIntensity(lightManager.getInstance(light), …)
```

**Comment by fanbinnet** [comment]
It works，Thanks very much
