### ISSUE TITLE
Can I change the fragColor in material file ?

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3567]
If there are some method can let me  change the fragColor in fragment like below:

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
//        material.baseColor.rgb = materialParams.baseColor;
        fragColor.rgb = float3(1.0,0.0,0.0);
}

We now have a requirement to do a mapping of the final color.
Thanks very much!

**Comment by romainguy** [comment]
This is not possible in surface materials unless you use an unlit shader. We plan on exposing post processing materials at some point though.
