### ISSUE TITLE
If there are some example code for use blendPostLightingColor

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3569]
I found below code in main.fs
#if defined(MATERIAL_HAS_POST_LIGHTING_COLOR)
    blendPostLightingColor(inputs, fragColor);
#endif

But I don't know how to use this. 
Can help give me some example code or other guidance

**Comment by romainguy** [comment]
It's explained in the documentation: https://google.github.io/filament/Materials.html

**Comment by fanbinnet** [comment]
Thanks very much!
