### ISSUE TITLE
Bug for filamat don't generateDefine MATERIAL_HAS_POST_LIGHTING_COLOR

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3571]
I found post lighting color can't work in android.
I anaylzed the cause,and did below modify.Now It work Ok in my phone.
Please check if this modify is right.

--- a/libs/filamat/src/MaterialBuilder.cpp
+++ b/libs/filamat/src/MaterialBuilder.cpp
@@ -421,6 +421,9 @@ void MaterialBuilder::prepareToBuild(MaterialInfo& info) noexcept {
             info.subpass = { utils::CString("MaterialParams"), param.name, param.subpassType,
                 param.format, param.precision, attachmentIndex, binding };
         }
+        if (param.name == "postLightingColor") {
+            info.hasPostLightingColor = true;
+        }
     }

diff --git a/libs/filamat/src/shaders/MaterialInfo.h b/libs/filamat/src/shaders/MaterialInfo.h
index 17219a4c..9e44c9f1 100644
--- a/libs/filamat/src/shaders/MaterialInfo.h
+++ b/libs/filamat/src/shaders/MaterialInfo.h
@@ -43,6 +43,7 @@ struct UTILS_PUBLIC MaterialInfo {
     bool multiBounceAO;
     bool multiBounceAOSet;
     bool specularAOSet;
+    bool hasPostLightingColor;
     filament::SpecularAmbientOcclusion specularAO;
     filament::RefractionMode refractionMode;
     filament::RefractionType refractionType;
diff --git a/libs/filamat/src/shaders/ShaderGenerator.cpp b/libs/filamat/src/shaders/ShaderGenerator.cpp
index b464b5c7..dc5ae6a7 100644
--- a/libs/filamat/src/shaders/ShaderGenerator.cpp
+++ b/libs/filamat/src/shaders/ShaderGenerator.cpp
@@ -398,6 +398,9 @@ std::string ShaderGenerator::createFragmentProgram(filament::backend::ShaderMode
         default:
             break;
     }
+    if (material.hasPostLightingColor){
+        cg.generateDefine(fs, "MATERIAL_HAS_POST_LIGHTING_COLOR", true);
+    }
     cg.generateDefine(fs, getShadingDefine(material.shading), true);
     generateMaterialDefines(fs, cg, mProperties, mDefines);

**Comment by fanbinnet** [comment]
I think the postLightingColor value is also not right.

**Comment by romainguy** [comment]
Your change is not correct, the `MATERIAL_HAS_*` defines are generated by `CodeGenerator::generateMaterialProperty()` already. Note that this feature only works if you *also* specify the `postLightingBlendMode` in your material properties (and the `opaque` property will do what you originally wanted btw, it can be used to completely override lighting, I forgot about this :-).
