### ISSUE TITLE
Bug with loading GLB model

### ISSUE THREAD

**Issue by GrigorySamokhin** [google/filament#3572]
Hello! I'm load glb model for Foreground this way:
```
   materialProvider = gltfio::createUbershaderLoader(engine);
   assetLoader = gltfio::AssetLoader::create({engine, materialProvider, nullptr});
...
 void addForeground(...) {

    assetFG = assetLoader->createAssetFromBinary(buffer, size);
    gltfio::ResourceLoader({
          .engine = engine
     }).loadResources(assetFG);

    int entCount = (int)assetFG->getEntityCount();
    __android_log_print(ANDROID_LOG_INFO, "FilamentLoader", "Entity Count %d", entCount);

    scene->addEntities(assetFG->getEntities(), assetFG->getEntityCount());

    auto customTrasform = mat4f::translation(float3{ 0.0f, 0.0f, -2.0f }) * mat4f::scaling(1.0f);
    engine->getTransformManager().setTransform(engine->getTransformManager().getInstance(assetFG->getRoot()), customTrasform);


    animatorGLB = assetFG->getAnimator();
    assetFG->releaseSourceData();
    animationTimer = 0.0f;
    model_numFG += 1;
}
...
```
And delete from scene and memory by this:
```
void removeForeground(...) {
        scene->removeEntities(assetFG->getEntities(), assetFG->getEntityCount());
        assetFG->releaseSourceData();
        assetLoader->destroyAsset(assetFG);
    }
...
```
But then I first execute addForeground function I get:
<img width="897" alt="Screenshot 2021-02-24 at 15 16 47" src="https://user-images.githubusercontent.com/47357694/109000342-a33ff280-76b4-11eb-89ad-c725a6dd4665.png">

But this is not a complete model. Im expecting with the full right side, like on photo below.
<img width="785" alt="Screenshot 2021-02-24 at 15 17 03" src="https://user-images.githubusercontent.com/47357694/109000648-0a5da700-76b5-11eb-99c8-c4b6ac089442.png">

Calling the function addForeground -> removeForeground -> addForeground (i.e call addForground twice) loads the full model, where can be a problem?

Buffer size and asset->entityCount are the same in two cases. Model
[Template_CS01_resized.glb.zip](https://github.com/google/filament/files/6035956/Template_CS01_resized.glb.zip)

**Comment by GrigorySamokhin** [comment]
In addition, if I add these lines in initialisation step
```
    utils::EntityManager& em = utils::EntityManager::get();
    Entity example1 = em.create();
    Entity example2 = em.create();
    Entity example3 = em.create();
```
glb model will load correctly in first. How did it affect the loading of glb?

**Comment by prideout** [comment]
When I look at the model in `gltf_viewer` I can see all the parts, but the transforms look a bit off (both with and without animation enabled).  Does your application apply custom transformations?  Could it be that the missing part had been loaded correctly, but its transform has been broken?

<img width="1218" alt="Screen Shot 2021-02-24 at 8 36 52 AM" src="https://user-images.githubusercontent.com/1288904/109033560-9d79eb00-767b-11eb-90dc-e62bf0217a73.png">

**Comment by prideout** [comment]
By the way, the image that I see in gltf_viewer is consistent with what I see with ThreeJS via https://gltf-viewer.donmccurdy.com/.

**Comment by GrigorySamokhin** [comment]
I see, I didn't even take into account that blue part on the right) Recompile wo this part, but problem is somewhere in loading , because I found another case, if I add this strange lines 
```
 utils::EntityManager& em = utils::EntityManager::get();
    Entity example1 = em.create();
    Entity example2 = em.create();
    Entity example3 = em.create();
```
and load 30 times, with assetLoader->destroyAsset and assetLoader->createAssetFromBinary after 29 load I don't have any model in scene, like it hasn't been loaded. I.e. I can load model 29 times the same way but on 30 run i haven't nothing in scene, model disappear. The same situation if I turn off animation.Profiler doesn't show any increase in RAM memory or CPU. Maybe some strange relationship between EntityManager and my loading of glb

**Comment by prideout** [comment]
If your application loads Filament dynamically, then you might have more than one EntityManager instance, which can cause strange problems like this.  You can check by putting a breakpoint in the EntityManager constructor.  To help with this situation, the `AssetConfiguration` struct let you pass in a custom entity manager so that it doesn't use the global one associated with its module.

**Comment by GrigorySamokhin** [comment]
The problem about EntityManager is that I don't use example1, example2, example3 vars, these variable was added because of problem that not full model are loaded in first run( 
I cleaned up the app and left only loading and unloading models, Here each tap is unloading and loading the glb model.
[device-2021-02-24-224523.mp4.zip](https://github.com/google/filament/files/6038490/device-2021-02-24-224523.mp4.zip) 
As you can see first model are not complete, this is because I remove EntityManager lines. After 35 tap models are disappear

**Comment by GrigorySamokhin** [comment]
One more remark, on 35 scene, (then models are disappear) assetFG->getRoot(); returns Entity with mIdentity equals == 131099, whereas 
```
    utils::EntityManager& em = utils::EntityManager::get();
    auto tt = em.getMaxEntityCount(); // returns 131071
```
What can lead to this?

**Comment by romainguy** [comment]
@pixelflinger to check me but the identity is different from the number of entities. The entity identity is defined as thus:

```
    static inline Entity::Type makeIdentity(Entity::Type g, Entity::Type i) noexcept {
        return (g << GENERATION_SHIFT) | (i & INDEX_MASK);
    }
```

Indices can be reused and when they get reused their generation increments.

**Comment by pixelflinger** [comment]
Yes, Romain is right.

**Comment by GrigorySamokhin** [comment]
How I understand I it is not normal that mIdendity return explosion values? What can I do in such situation? I load filament as static and shared libraries via cmake

**Comment by romainguy** [comment]
What do you mean by `explosion values`? `mIdentity` encodes an index + a generation, so high values just mean that a particular index has been reused (which is by design).

**Comment by GrigorySamokhin** [comment]
Okey, It turns out that this is a coincidence that mIdentity is increase by 30 each step and on 35 step it increasing on 131000 and my glb model are disappear? The main problems is that on first load is not full loaded and I can't apply transform to glb and second that model is disappear on 35 step, like I show on video above. Do you have any idea what can be a reason for this behaviour?

**Comment by GrigorySamokhin** [comment]
As observation my model has 31 Entity then I load (and I can load it 35 times), and then I change model this has only 10 entitys I can load it about 60 times. May be there are some restrictions on how many Entities I can load ?

**Comment by GrigorySamokhin** [comment]
Oh, I switched from 1.9.9 to 1.9.13 and all my problems go away. Thanks
