### ISSUE TITLE
Transmission rendering issue on Google Pixel 3

### ISSUE THREAD

**Issue by alexey-pelykh** [google/filament#3584]
**Describe the bug**
Visual artifacts when rendering transmission test model

**To Reproduce**
1. Modify GLTF viewer demo to use https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TransmissionTest
2. Launch on Google Pixel 3

**Expected behavior**
No visual artifacts.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/345102/109292038-7285c780-7832-11eb-837e-f1b5566e8cc6.png)

https://user-images.githubusercontent.com/345102/109292047-74e82180-7832-11eb-8f73-f8daaadb2a7c.mp4

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 11

**Additional context**
Samsung Galaxy S10 5G renders the same demo correctly.

**Comment by alexey-pelykh** [comment]
cc @romainguy if possible, please take a look into the issue. Thanks!

**Comment by pixelflinger** [comment]
I tried on Pixel 4, and it works fine. I don't have pixel 3 to test unfortunately.

**Comment by alexey-pelykh** [comment]
We've tested on two Pixel 3's (`MP1.0`) - results are consistent, unfortunately.

**Comment by pixelflinger** [comment]
Tried on a Pixel 2 and it is working fine.  I think at this point there is no actionable things we can do.

**Comment by pixelflinger** [comment]
Today I was able to try on a Pixel 3 XL and it worked fine.

**Comment by alexey-pelykh** [comment]
I believe there was a recent commit regarding that, where it stated that transmissions was fixed or amended.
