### ISSUE TITLE
Picky typographical issue in Filament Materials Guide

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3592]
The Filament Materials Guide (https://google.github.io/filament/Materials.html) lists parameter types including `float3×3` and `float4×4`.  Actually to get `matc` to accept it, you must use a plain ASCII lower case letter x instead of the pretty cross character.  I'm probably being too literal-minded, but that's an occupational hazard.

**Comment by romainguy** [comment]
It's a (neat) feature of the Markdeep system we use to generate the documentation. I'm not sure how to prevent this auto formatting from happening so I'll probably keep it as is for now.

**Comment by jwwalker** [comment]
@romainguy  OK, I had never heard of Markdeep.  Pretty cool.  Now that I know to look for `.md.html`, I found the source for the Filament Materials Guide.

There seems to be a simple fix: In the first column of the table of parameter types, quote the terms with backticks.  That makes semantic sense anyway, since these are keywords in a programming language.
