### ISSUE TITLE
New texture on GLB

### ISSUE THREAD

**Issue by nPhil01** [google/filament#3595]
I am writing this here because I could not find any help on other platforms (e.g. stackoverflow).

I am currently working on an AR app with sceneform 1.16. I use sceneform 1.16 because I need to run animations and change textures of GLTF/GLB models. 

My problem is, when I change the texture of a model, it just changes its color to completely black, it seems it looses all texture.

After I created the renderable with sceneform, I save the filamentAsset to a variable like this:

        // Creating a AnchorNode with a specific anchor
        AnchorNode anchorNode = new AnchorNode(anchor);

        // attaching the anchorNode with the ArFragment
        anchorNode.setParent(arCam.getArSceneView().getScene());

        // attaching the anchorNode with the TransformableNode
        TransformableNode model = new TransformableNode(arCam.getTransformationSystem());
        model.setParent(anchorNode);

        // attaching the 3d model with the TransformableNode
        // that is already attached with the node
        model.setRenderable(modelRenderable);
        model.select();

        // Saving the object as filament asset
        // -> Possibility to run animations and change textures
        filamentAsset = model.getRenderableInstance().getFilamentAsset();

When a user wants to change the texture, I invoke this method:

    public void changeMaterials() {
        textureBC = loadTexture(engine, R.drawable.avocado_basecolor);
        MaterialInstance[] materialInstances = filamentAsset.getMaterialInstances();

        TextureSampler textureSampler = new TextureSampler();
        textureSampler.setWrapModeR(TextureSampler.WrapMode.REPEAT);
        textureSampler.setWrapModeS(TextureSampler.WrapMode.REPEAT);
        textureSampler.setWrapModeT(TextureSampler.WrapMode.REPEAT);

        for (MaterialInstance materialInstance : materialInstances) {
            materialInstance.setParameter("baseColorMap", textureBC, textureSampler);
        }
    }

This is my _loadTexture()_ :

    private com.google.android.filament.Texture loadTexture(Engine engine, int resourceId) {
        Resources resources = getResources();

        Bitmap bitmap = BitmapFactory.decodeResource(resources, resourceId, null);
        
        com.google.android.filament.Texture texture = new com.google.android.filament.Texture.Builder()
                .width(bitmap.getWidth())
                .height(bitmap.getHeight())
                .sampler(Texture.Sampler.SAMPLER_2D)
                .format(Texture.InternalFormat.SRGB8_A8) // It is crucial to use an SRGB format.
                .levels(0xff) // tells Filament to figure out the number of mip levels
                .build(engine);

        TextureHelper.setBitmap(engine, texture, 0, bitmap);

        texture.generateMipmaps(engine);
        return texture;
    }

After I called the method, the model is completely black:

Before:
![Screenshot_20210224-125556_My Application](https://user-images.githubusercontent.com/18659032/109507093-a8c77f00-7a9e-11eb-97b2-18b5ba639699.jpg)

After:
![Screenshot_20210224-125618_My Application](https://user-images.githubusercontent.com/18659032/109507168-bb41b880-7a9e-11eb-804f-ffb617ae8cd2.jpg)

As an example I used this [avocado model](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Avocado/glTF-Binary/Avocado.glb). As an input for the loadTexture method I used this [image](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Avocado/glTF/Avocado_baseColor.png) of the avocado GLTF and changed some colors to check, whether the texture change is working.

**Comment by prideout** [comment]
At first glance your code looks correct.  Maybe my colleagues will spot something.  If not I can try reproducing locally by hacking our android-gltf-viewer sample.  (This might be an interesting experiment on your end as well.)

**Comment by romainguy** [comment]
I don't see anything wrong, the only thing I can think of is an issue with the texture file itself. If you use a PNG make sure that PNG is not in 16 bit. Also in your code check the bitmap returned by decodeResource() is valid (check width/height and whether the bitmap is !null).

**Comment by nPhil01** [comment]
I tried with 8, 24 and 32 bit PNGs, every time with the same result. The width/height values of the bitmap and the texture are both correct.

**Comment by ThomasGorisse** [comment]
My answer for Sceneform usage here : [Submeshcount always 0, assign new Texture with filament ThomasGorisse/sceneform-android-sdk#10
](https://github.com/ThomasGorisse/sceneform-android-sdk/issues/10#issuecomment-789885750)

**Comment by nPhil01** [comment]
It seems to be a problem with the filamentAsset provided by sceneform. I build a small application loading the .glb and change the texture using filaments modelViewer. Thanks for your help!
