### ISSUE TITLE
on MacOS + java, FilamentCanvas displaying nothing,but FilamentPanel work fine.

### ISSUE THREAD

**Issue by leeho0108** [google/filament#3598]
Hi

I am learning filament with java on MacOS,I use android/samples/sample-hello-triangle as my start point...
my code is 

`package me.leeho.filamenttest;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.InvocationTargetException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import com.google.android.filament.Box;
import com.google.android.filament.Camera;
import com.google.android.filament.Engine;
import com.google.android.filament.Engine.Backend;
import com.google.android.filament.EntityManager;
import com.google.android.filament.Filament;
import com.google.android.filament.FilamentPanel;
import com.google.android.filament.FilamentTarget;
import com.google.android.filament.IndexBuffer;
import com.google.android.filament.Material;
import com.google.android.filament.RenderableManager;
import com.google.android.filament.RenderableManager.PrimitiveType;
import com.google.android.filament.Renderer;
import com.google.android.filament.Scene;
import com.google.android.filament.Skybox;
import com.google.android.filament.VertexBuffer;
import com.google.android.filament.VertexBuffer.AttributeType;
import com.google.android.filament.VertexBuffer.VertexAttribute;
import com.google.android.filament.View;
import com.google.android.filament.Viewport;

public class FilamentTest extends JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FilamentTarget filamentCanvas;
	private volatile boolean running = true;
	protected Engine engine;
	protected Renderer renderer;
	protected Scene scene;
	protected View view;
	protected Camera camera;
	private IndexBuffer indexBuffer;
	private VertexBuffer vertexBuffer;
	private Material material;

	public FilamentTest() {
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		addWindowListener(new WindowAdapter() {

			@Override
			public void windowClosed(WindowEvent e) {
				running = false;
			}
		});
	}

	protected void init() {
		setSize(1136, 640);
		setLocationRelativeTo(null);
		setVisible(true);
		Filament.init();
		engine = Engine.create(Backend.OPENGL);
		renderer = engine.createRenderer();
		scene = engine.createScene();
		view = engine.createView();
		camera = engine.createCamera();
		getContentPane().setLayout(new BorderLayout());
		initCanvas();
		pack();
		setupView();
		setupScene();
	}

	private void initCanvas() {
//		filamentCanvas = new MyFilamentCanvas();
//		filamentCanvas = new FilamentCanvas();
		filamentCanvas = new FilamentPanel();
		Component component = (Component) filamentCanvas;
		component.setPreferredSize(new Dimension(1136, 640));
		component.setSize(getPreferredSize());
		component.addComponentListener(new ComponentAdapter() {
			@Override
			public void componentResized(ComponentEvent e) {
				super.componentResized(e);
				onCanvasResize(e.getComponent().getWidth(), e.getComponent().getHeight());
			}
		});
		getContentPane().add(component);
	}

	protected void onCanvasResize(int width, int height) {
		double zoom = 1.5;
		double aspect = 1.0 * width / height;
		camera.setProjection(Camera.Projection.ORTHO, -aspect * zoom, aspect * zoom, -zoom, zoom, 0.0, 10.0);

		view.setViewport(new Viewport(0, 0, width, height));
		System.out.println("onCanvasResize:" + width + "/" + height);
	}

	private void createMesh() {
		int intSize = 4;
		int floatSize = 4;
		int shortSize = 2;
		// A vertex is a position + a color:
		// 3 floats for XYZ position, 1 integer for color
		int vertexSize = 3 * floatSize + intSize;

		// Define a vertex and a function to put a vertex in a ByteBuffer
		class Vertex {
			float x;
			float y;
			float z;
			int color;

			public Vertex(float x, float y, float z, int color) {
				super();
				this.x = x;
				this.y = y;
				this.z = z;
				this.color = color;
			}

			public void put(ByteBuffer buffer) {
				buffer.putFloat(x);
				buffer.putFloat(y);
				buffer.putFloat(z);
				buffer.putInt(color);
			}
		}

		// We are going to generate a single triangle
		int vertexCount = 3;
		double a1 = Math.PI * 2.0 / 3.0;
		double a2 = Math.PI * 4.0 / 3.0;

		ByteBuffer vertexData = ByteBuffer.allocate(vertexCount * vertexSize);

		// It is important to respect the native byte order
		vertexData.order(ByteOrder.nativeOrder());
		new Vertex(1.0f, 0.0f, 0.0f, 0xffff0000).put(vertexData);
		new Vertex((float) Math.cos(a1), (float) Math.sin(a1), 0.0f, 0xff00ff00).put(vertexData);
		new Vertex((float) Math.cos(a2), (float) Math.sin(a2), 0.0f, 0xff0000ff).put(vertexData);
		// Make sure the cursor is pointing in the right place in the byte buffer
		vertexData.flip();

		// Declare the layout of our mesh
		vertexBuffer = new VertexBuffer.Builder().bufferCount(1).vertexCount(vertexCount)
				// Because we interleave position and color data we must specify offset and
				// stride
				// We could use de-interleaved data by declaring two buffers and giving each
				// attribute a different buffer index
				.attribute(VertexAttribute.POSITION, 0, AttributeType.FLOAT3, 0, vertexSize)
				.attribute(VertexAttribute.COLOR, 0, AttributeType.UBYTE4, 3 * floatSize, vertexSize)
				// We store colors as unsigned bytes but since we want values between 0 and 1
				// in the material (shaders), we must mark the attribute as normalized
				.normalized(VertexAttribute.COLOR).build(engine);

		// Feed the vertex data to the mesh
		// We only set 1 buffer because the data is interleaved
		vertexBuffer.setBufferAt(engine, 0, vertexData);

		// Create the indices
		ByteBuffer indexData = ByteBuffer.allocate(vertexCount * shortSize).order(ByteOrder.nativeOrder())
				.putShort((short) 0).putShort((short) 1).putShort((short) 2);

		indexData.flip();

		indexBuffer = new IndexBuffer.Builder().indexCount(3).bufferType(IndexBuffer.Builder.IndexType.USHORT)
				.build(engine);

		indexBuffer.setBuffer(engine, indexData);
	}

	private void loadMaterial() {
		InputStream resourceAsStream = FilamentTest.class.getResourceAsStream("baked_color.filamat");
		try {
			byte[] readAll = readAll(resourceAsStream);
			ByteBuffer byteBuffer = ByteBuffer.wrap(readAll);
			material = new Material.Builder().payload(byteBuffer, byteBuffer.remaining()).build(engine);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}

	public static byte[] readAll(InputStream in) throws IOException {
		ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
		byte[] buf = new byte[512];
		int r;
		while ((r = in.read(buf)) != -1) {
			byteArrayOutputStream.write(buf, 0, r);
		}
		return byteArrayOutputStream.toByteArray();
	}

	private void setupScene() {
		loadMaterial();
		createMesh();

		// To create a renderable we first create a generic entity
		int renderable = EntityManager.get().create();

		// We then create a renderable component on that entity
		// A renderable is made of several primitives; in this case we declare only 1
		new RenderableManager.Builder(1)
				// Overall bounding box of the renderable
				.boundingBox(new Box(0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.01f))
				// Sets the mesh data of the first primitive
				.geometry(0, PrimitiveType.TRIANGLES, vertexBuffer, indexBuffer, 0, 3)
				// Sets the material of the first primitive
				.material(0, material.getDefaultInstance()).build(engine, renderable);

		// Add the entity to the scene to render it
		scene.addEntity(renderable);
	}

	private void setupView() {

		scene.setSkybox(new Skybox.Builder().color(0.035f, 0.035f, 0.035f, 1.0f).build(engine));

		// NOTE: Try to disable post-processing (tone-mapping, etc.) to see the
		// difference
		// view.isPostProcessingEnabled = false

		// Tell the view which camera we want to use
		view.setCamera(camera);

		// Tell the view which scene we want to render
		view.setScene(scene);
	}

	public static void main(String[] args) {
//		new Thread() {
//			public void run() {
		main2(args);
//			}
//		}.start();
	}

	public static void main2(String[] args) {
		FilamentTest filamentTest = new FilamentTest();
		SwingUtilities.invokeLater(() -> {
			filamentTest.init();
		});
		new Thread() {
			public void run() {
				while (filamentTest.running) {
					try {
						SwingUtilities.invokeAndWait(() -> {
							filamentTest.renderFrame();
						});
					} catch (InvocationTargetException e1) {
						e1.printStackTrace();
					} catch (InterruptedException e1) {
						e1.printStackTrace();
					}
					try {
						Thread.sleep(16);
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
				}
			}
		}.start();
//		filamentTest.start();
	}

	/**
	 * start loop on current thread
	 */
	private void start() {
		setLocationRelativeTo(null);
		setVisible(true);
		Backend backend = engine.getBackend();
		System.out.println("backend=" + backend);
		while (running) {
			renderFrame();
			try {
				Thread.sleep(16);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	private void renderFrame() {
		if (filamentCanvas.beginFrame(engine, renderer)) {
			try {
				renderFrame0();
			} finally {
				filamentCanvas.endFrame(renderer);
			}
		}
	}

	private void renderFrame0() {
		renderer.render(view);
	}
}
`

run this code.
if I use FilamentPanel,it works just fine.
but, if I use FilamentCanvas,It displaying nothing.
I as tried in main thread,get same result.

**To Reproduce**
just toggle comment for FIlamentCanvas or FilamentPanel

**Expected behavior**
work both fine。it seems FilamentPanel has a **much higher cost**. So in product, better use FilamentCanvas

**Screenshots**

screenshot for FilamentPanel

![image](https://user-images.githubusercontent.com/10900736/109535193-3d5dcb80-7af7-11eb-96e6-ea4b6c08993a.png)

screenshot for FilamentCanvas
![image](https://user-images.githubusercontent.com/10900736/109535392-78f89580-7af7-11eb-9315-af33a050d331.png)

**Desktop (please complete the following information):**
 - OS:MacOS 10.15.5
 - GPU: Colorful GeForce GTX 760 1024 MB
 - Backend: [OpenGL]

BTW,I also try other Backends like metal and Vuakan,app just crash...but this is not my focus point now...

**Comment by romainguy** [comment]
`FilamentCanvas` is a known (recent) issue. Note that beyond the cost, `FilamentPanel` has advantages over `FilamentCanvas` if you use Swing. It's much easier to overlap other widgets with a `FilamentPanel`. There is also something we could do to optimize `FilamentPanel` by getting rid of the CPU copy/swizzle we currently do and have the GPU do it instead.

Unfortunately desktop Java support is not a high priority at this point so I cannot tell you when we're going to look into these issues. We'll be more than happy to review PRs though.

**Comment by leeho0108** [comment]
@romainguy 
Thanks for reply.

It's OK to me if this bug can not fix now,I can use `FilamentPanel`,and it's enough for now...

Thanks for your awesome works.

Best Regards

**Comment by leeho0108** [comment]
I write a  FilamentSWTCanvas for java use swt in macOS.this may useful for who want use filament in java without `FilamentPanel` **much higher cost**. It should have same performance as `FilamentCanvas`...
for now,It seems work perfectly...

here is same code's screenshot
![image](https://user-images.githubusercontent.com/10900736/109549743-5a02ff00-7b09-11eb-953a-77bd3789a30d.png)

code is here:
FIlamentSWTCanvas.java
https://github.com/leeho0108/FilamentJavaSWTCanvas/blob/main/FilamentSWTCanvas.java

Full Sample Codes
https://github.com/leeho0108/FilamentJavaSWTCanvas

Hopes this can help anyone want use FilamentCanvas in java for now

**Comment by romainguy** [comment]
It's great, but this requires to use SWT, which is not necessarily something folks want/can do. We still need to fix `FilamentCanvas` itself on macOS.

**Comment by pixelflinger** [comment]
there is no plan to work in this issue.
