### ISSUE TITLE
Allow usage of native textures from shared contexts

### ISSUE THREAD

**Issue by borodust** [google/filament#3604]
**Problem**
I want Filament and Skia to become best friends: Filament is awesome for 3D, Skia is amazing at 2D. Skia can render into user-provided native texture (via `SkSurface::MakeFromBackendTexture`), but Filament is being a bit capitalistic and won't easily accept shared resources such as textures.

**Possible solution**
Maybe we can have `NativeTexture` (`BackendTexture`, `SharedTexture`, maybe `OpenGLTexture` and friends) builder that will accept textures created somewhere else. As a user, I already control what backend Filament is going to use, so I might as well could have a power to feed some native resources from that backend into the engine.

**Alternatives**
I had a look into streaming rabbit hole (`Filament::Stream` aka external texture). I didn't find a straightforward solution for non-EGL platforms. There are some extensions that might work for OpenGL 4.5 contexts (`EXT_external_objects`), but I'm not smart enough to wrap my head around all the machinery and complexity involved.

At first I was thinking about using Dear ImGui drawing backend for 2D, but it's quite a limiting solution. I have experience with NanoVG and `ImDrawList` is a step back. Skia seems to be a solid leap forward.

**P.S.**
This request is kinda opposite of https://github.com/google/filament/issues/1899 - rather than exposing Filament internals, Filament might allow users to feed it with what they think will work at their own risk being bitten hard.

**Comment by romainguy** [comment]
Filament does support shared resources via `Stream`. It has three modes, one of which being `TEXTURE_ID` which is meant for exactly this. What's missing however is hooking up that support on non-EGL platforms.

@pixelflinger

**Comment by pixelflinger** [comment]
Actually we have `Texture::Builder& import(intptr_t id) noexcept;` which pretty much does exactly what you were asking for.

**Comment by borodust** [comment]
Blimey!

**Comment by borodust** [comment]
Just in case anyone else stumbles upon this issue - tex import works like a charm. Filament rendering a texture that Skia has drawn onto in the background thread with in separate context with FBO double buffering: 
https://peertube.social/videos/watch/723669b8-f3f1-47ac-9769-b8b2b66ab953
