### ISSUE TITLE
Can we hide the Gltf model?

### ISSUE THREAD

**Issue by duy-maimanh** [google/filament#3605]
Can we temporarily hide a model and show it again later without having to destroy and re-create?
Because my model is quite large and takes a long time to initialize.

**Comment by romainguy** [comment]
Yes you can simply change the layer mask on your renderable. You can use this to make the Renderable visible only in Views that have the appropriate layer mask. In your case you just set it to 0 to hide it entirely. You could also just remove the object from the scene without destroying it. Doing so is cheap.
