### ISSUE TITLE
Transparent object behind another transparent object

### ISSUE THREAD

**Issue by ttothfalussy** [google/filament#3618]
**Describe the bug**
If I have 2 (or more) transparent objects with screen-space refraction turned on behind each other, only the closest one to the camera gets rendered.

**To Reproduce**
Simply add transparent material with screen-space refraction on to more than one object, the one further from the camera is not rendered behind the other.

**Expected behavior**
Transparent objects should be visible through other transparent objects.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9" 2020
 - OS: iPadOS 14.4

**Additional context**
If the root of the problem is we can't have the result of one screen-space refraction "fed" into another object's screen-space refraction effect, could we maybe just have the objects visible without SSR?

![refraction](https://user-images.githubusercontent.com/54284553/110341169-58b26480-802a-11eb-86aa-6d5307550ea2.jpg)

**Comment by romainguy** [comment]
This is an unfortunate limitation of screen space refraction and working as intended.
