### ISSUE TITLE
Dominant Light Shadows on Metal

### ISSUE THREAD

**Issue by ttothfalussy** [google/filament#3619]
**Describe the bug**
Dominant Light Shadows feature looks different and glitchy on Metal compared to OpenGL.

**To Reproduce**
Compare the same models with the same lighting parameters on OpenGL and Metal in the gltf_viewer sample.

**Expected behavior**
Dominant Light Shadows should look the same on Metal and OpenGL.

**Screenshots**
See added screenshot.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.1
 - GPU: Intel Iris Plus Graphics 645
 - Backend: OpenGL/Metal

**Additional context**
On Metal seems like the direction of DLS is a different vector and the camera angle has a much more dramatic influence on it than on OpenGL.

![dominant-shadows](https://user-images.githubusercontent.com/54284553/110350419-fc544280-8033-11eb-86f6-7a78358b482f.jpg)
.

**Comment by bejado** [comment]
Thanks for the report, I'm able to reproduce.
