### ISSUE TITLE
Mac rendering broken by commit [1189c9e29]

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3628]
**Describe the bug**
In recent builds, I'm seeing incorrect rendering on macOS.  If I had to guess what's going wrong by looking at the output, I'd say that the depth buffer isn't getting cleared between frames.

**To Reproduce**
1. Invoke the `rendertarget` sample on the command line, like `rendertarget -a metal`.

**Expected behavior**
The sample is supposed to show a rotating head and a mirror reflection.

**Actual behavior**
The direct image looks OK, but the mirror image kind of disappears piecemeal.

**Screenshots**
I have a hard time snapping a screen shot fast enough, but here's one with just a little of the reflection still present.

<img width="779" alt="Screen Shot 2021-03-10 at 12 58 31 PM" src="https://user-images.githubusercontent.com/730426/110696964-9802c180-81a0-11eb-8abd-ce7c3e4246e3.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.3 Beta
 - GPU: Radeon Pro 560X 4 GB
 - Backend: Metal

**Additional context**
If I run the `rendertarget` sample using OpenGL, then the reflection is completely missing from the start.

It appears that the problem started with the commit "FrameGraph rewrite from the ground up  [1189c9e29]".

@pixelflinger

**Comment by jwwalker** [comment]
When I forced the `hellotriangle` sample to use Metal by editing `filament/libs/filamentapp/include/filamentapp/Config.h`, I also got some fun results:  

<img width="550" alt="Screen Shot 2021-03-10 at 2 01 23 PM" src="https://user-images.githubusercontent.com/730426/110704205-807c0680-81a9-11eb-8bab-816559ad27e1.png">

Whereas `hello triangle` looks OK with OpenGL.

**Comment by prideout** [comment]
`rendertarget` and `hellotriangle` are both broken with OpenGL too, not just Metal.

**Comment by jwwalker** [comment]
@prideout I'm not seeing a problem with `hellotriangle` in OpenGL, but yes `rendertarget` fails, in a different-looking way, with OpenGL.

**Comment by bejado** [comment]
With `hellotriangle` on Metal, Filament is setting a `LoadAction` of `DontCare`, which is incorrect. The framegraph is most likely calculating incorrect `discardStart` flags.
