### ISSUE TITLE
Build failure with USE_STATIC_LIBCXX option set to OFF

### ISSUE THREAD

**Issue by randomgraphics** [google/filament#3633]
**Describe the bug**
I'm trying to integrate filament with another project built against shared c++ library. To be able to do that, I'll have build filament with shared c++ library too. filament's main CMakeList.txt has provided that option: USE_STATIC_LIBCXX. It is turned on by default. When I turn it off and build the filament again, I encounter many build failures. All of them are missed definition of some standard C functions, like memset, strlen and such. I gave it a try and it is actually not so hard to fix, just include proper headers (such as ```<cstring> <cstddef>```)

**To Reproduce**
1. Modify <root>/CMakeList.txt to turn off USE_STATIC_LIBCXX option:
    change line ```option(USE_STATIC_LIBCXX "Link against the static runtime libraries." ON)```
    to: ```    option(USE_STATIC_LIBCXX "Link against the static runtime libraries." OFF)```

2. build.sh release

**Expected behavior**
Build completes with no error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU: N/A
 - Backend: N/A

**Additional context**
Here's the clang version that I'm using:
```
$ clang --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by romainguy** [comment]
Thanks for reporting this. I'm not sure why using a static libc++ would affect the required includes. We like to keep our includes clean anyway but the main issue is that we won't test this forward so this is likely to break again.

**Comment by randomgraphics** [comment]
[patch.txt](https://github.com/google/filament/files/6120444/patch.txt)

Created a patch file to address the build error. It is diff againts release v1.9.15.
Tested with both USE_STATIC_LIBCXX set to ON and OFF. seems build fine. hope that's helpful.

**Comment by romainguy** [comment]
It's very helpful thank you!

**Comment by 100espressos** [comment]
Thanks for the contribution. Though it no longer applies, the hope is that it can spur interest in providing some relief from the huge, slow-linking static libraries.
