### ISSUE TITLE
The issue of  world from object normal matrix

### ISSUE THREAD

**Issue by wernertan** [google/filament#3638]
when I run the demo of gltf_view , and make the scale of  entity  as **(1,1,-1)** . The redner effect is not right , the  surface of mesh reflects wrong image.  If I make it rotate 180 drgee with Y axis , it is corret.

According to the source code , I find that the function of "**getTransformForNormals**" is not correct. It can not handle this case . 
and I fix the function like that:
           **matrix::transpose( matrx::inverse(m))**

[transforming-normals](https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/transforming-normals)

**Comment by romainguy** [comment]
See issue #3635
