### ISSUE TITLE
filament backend not support compute shader feature

### ISSUE THREAD

**Issue by xaioxw** [google/filament#3650]
filament backend not support compute shader feature. And some function not support, for example, i use opengl bindImageTexture() function,it call 'calling missing GL function!'.

**Comment by romainguy** [comment]
Filament supports the OpenGL ES 3.0 feature set so there is no support for compute shaders indeed. We don’t have plans to address this until ES 3.0 phases out or we can rely only on Vulcan and Metal.

**Comment by xaioxw** [comment]
If I want to implement this function in OpenGL, how to solve the problem that the GL function can’t find it，just 'calling missing GL function!'

**Comment by romainguy** [comment]
It depends on the platform. On desktop you’ll have to update the bluegl library. On Android it should just work if you include es 3.1 headers.

**Comment by xaioxw** [comment]
Thanks, yeah, I want  implement for macos platform , Can it done?

**Comment by xaioxw** [comment]
Can I ask you a question? When I use compute shader, program compile success contains a uniform variable, such as layout (rgba32f, binding = 0) uniform image2d outputimage. When I use glgetuniformlocation() method to access the variable, it prompts invalid gl operation. What is the reason？ it not support？Thanks
