### ISSUE TITLE
Inconsistent behavior of depthWrite for transparent object rendering

### ISSUE THREAD

**Issue by DianxinWang** [google/filament#3651]
Inconsistency between documentation about code implementation.

In [filament materials guide](https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/rasterization:depthwrite), it says depth write is false by default for transparent materials. But when I tried to render some transparent thing, I found it to be true for depthWrite.

The possible reason might be that in [ubershader.mat.in](https://github.com/google/filament/blob/main/libs/gltfio/materials/ubershader.mat.in). The depthWrite is hardcoded as true.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/36990568/111133838-eefc0280-85b5-11eb-87c6-dfa99fa0adfe.png">

**Comment by romainguy** [comment]
`ubershader.mat` is a material file written for the `gltfio` library. That material writes transparents to the depth buffer to follow what other glTF viewers do. There's no inconsistency here, `depthWrite` is off by default, but this material decides to turn it on.
