### ISSUE TITLE
The latest code can't compile by Visual Studio 2019  and get the C2610 error.

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3652]
D:\oscar\github\filament2\filament\filament\src\fg2\Blackboard.cpp	25	
Erro C2610	“filament::PassNode::PassNode(filament::PassNode &&) noexcept”: 'class::member': is not a special member function which can be defaulted filament	D:\oscar\github\filament2\filament\filament\src\fg2\PassNode.cpp	39	

The Blackboard can modify to 
Blackboard() noexcept {}  in Blackboard.h ,but PassNode modify get more error.

Can some one can kindly help to resolve this issue ?
Thanks very much.

**Comment by bejado** [comment]
I'm unable to reproduce with the latest Visual Studio (16.9.1). Can you make sure you're on the latest version?

**Comment by fanbinnet** [comment]
My version is 16.5.4. I will update my Visual Studio and give the reproduce info later.

**Comment by fanbinnet** [comment]
Yes，the latest version is OK. I'll close this issue.
