### ISSUE TITLE
How to apply Lighting on scene without using IBL ? 

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#3654]
Currently I am using ModelViewer class to load my gltf Model and IBL for lighting, and for that I am using HDR images. but current IBL images show shadow of the HDR images on my model and that looks little weird. something like image I have attached below.

![image](https://user-images.githubusercontent.com/24297327/111294649-8b82db00-8670-11eb-836e-98002e54f346.png)

but It should look like below image

![oie_ICQM6gS2I2KK](https://user-images.githubusercontent.com/24297327/111295135-0cda6d80-8671-11eb-8b20-7c1410d21f33.png)

So is there any way to apply lighting without using IBL ? or is there any option so I can control that shadow on my model ?

Thanks in advance.

**Comment by romainguy** [comment]
IBLs do not cast shadows. If the reflections you are seeing are not appropriate you should use a different IBL. You can find more files at hdrihaven.com for instance or even create your own.

**Comment by chirag-qs** [comment]
Hi, 
I tried some HDR images to fix above issue but could not found exact solution, Basically I am trying to setup lighting, which does not reflect any shadow.  

I am trying to setup Lighting and shadow similar to below video.

https://user-images.githubusercontent.com/86815724/153820719-f7f903bc-fe1a-4b9a-9448-7403b7f9b039.mp4

But it looks like this.

https://user-images.githubusercontent.com/86815724/153825484-edba00bc-0b78-4fcd-bde9-048a30889c5f.mp4

So, Is there any way to apply lighting without having its shadow ? Also if you can suggest any HDR image for that, it will be really helpful. 

Thanks in Advance.
