### ISSUE TITLE
Incorrect render priority with occluder material

### ISSUE THREAD

**Issue by Miao-10k** [google/filament#3668]
I was using occluder material to render a portal with a red plane in the bottom on an Android device. The model I use is showing below.
![image](https://user-images.githubusercontent.com/32147896/111759997-2e3d9280-88d9-11eb-866e-59fad2b781ee.png)
The outside of the portal is a mask that is applied occluder material. I set the render priority as camera = 2, mask = 3, the red plane = 1, other elements = 4. I was expecting that the mask occludes only the things inside it. However, as shown below, it also occludes the red plane which has the highest render priority.  
![Screenshot_20210319_172718](https://user-images.githubusercontent.com/32147896/111761310-b96b5800-88da-11eb-851b-0aa0b90ee830.jpg)     ![Screenshot_20210319_172659](https://user-images.githubusercontent.com/32147896/111761483-e7e93300-88da-11eb-8646-3dba54bb6f93.jpg)

**Comment by romainguy** [comment]
Is your plane transparent by any chance? Transparents are always rendered after opaque objects, regardless of priority.

**Comment by Miao-10k** [comment]
@romainguy Thank you for your help. By setting the plane to opaque, the render result is as expected now. Is there any way I can get the expected render order if I need the plane to be transparent?

**Comment by romainguy** [comment]
We need to render transparent objects after opaque objects. You could render the occluders twice maybe? Once as opaque and once as transparent?

**Comment by Miao-10k** [comment]
It seems doesn't help to render the occluders twice. I am not sure I understand this correctly. How should I render the occluders twice with java API?

**Comment by Miao-10k** [comment]
@romainguy I found that occluder doesn't render correctly on some device. Following is the render result I get on Oneplus 6T with exactly the same code as the previous one.
![Screenshot_20210325-171316](https://user-images.githubusercontent.com/32147896/112449730-aea73c00-8d8e-11eb-9427-f34a194f7871.jpg)

**Comment by Miao-10k** [comment]
> @romainguy I found that occluder doesn't render correctly on some device. Following is the render result I get on Oneplus 6T with exactly the same code as the previous one.
> ![Screenshot_20210325-171316](https://user-images.githubusercontent.com/32147896/112449730-aea73c00-8d8e-11eb-9427-f34a194f7871.jpg)

Hi, @romainguy do you have any idea of this problem？I found that this also happens on Sony Xperia G8142. The occluder material is as follows.

```
material {
    "name" : "Face Mesh Occluder",
    "parameters" : [
        {
            "type" : "float",
            "name" : "unused"
        }
    ],
    "shadingModel" : "unlit",
    "colorWrite" : false,
    "depthWrite" : true,
}
```

**Comment by romainguy** [comment]
It's a [known issue](https://github.com/google/filament/issues/2636) unfortunately and seems to be related to a driver issue. We haven't found a satisfactory fix.

**Comment by romainguy** [comment]
Closing this bug to avoid multiple duplicates. We'll keep tracking in the other issues mentioned above.
