### ISSUE TITLE
Multiview support?

### ISSUE THREAD

**Issue by dsanjit** [google/filament#3671]
Multiview (or SPV_KHR_multiview for Vulkan backens) support will greatly benefit VR/Stereo applications of Filament.

I have looked at the shader code code but its not clear where I should make the modifications as there seems to be a complex materials/shader build process in use (not a simple bunch of vert and frag shaders which can be simply modified. 

Any suggestions please ?

**Comment by romainguy** [comment]
See [issue 435](https://github.com/google/filament/issues/435) and [issue 1690](https://github.com/google/filament/issues/1690). We'd like to add support for VR some day but it's not a priority at the moment. Support for multiview would however be useful for other reasons (cascaded shadows, etc.).

The materials build process is not that complicated, it mostly concatenates the shader files found in `shaders/src` based on various options declared by the material. Multiview support would most likely be implemented as a new vertex variant.
