### ISSUE TITLE
Textures not showing while rotating model in Android

### ISSUE THREAD

**Issue by udayk07** [google/filament#3675]
I am trying to load simple cube with texture. Initially texture renders fine as shown in below image(1). While rotating cube, the texture become transparent and showing like white cube ( image 2). Using opaque texture only in cube. Also, cube edges not showing correctly.

![Screenshot_20210322-140009_AR Creator](https://user-images.githubusercontent.com/78372917/111964139-4b14d880-8b1a-11eb-9ff8-7a8448448998.jpg)

 
![Screenshot_20210322-140028_AR Creator](https://user-images.githubusercontent.com/78372917/111963783-e8bbd800-8b19-11eb-99ac-ff4f278a41df.jpg)
 

Model and material file available in below zip file
[model&matFile.zip](https://github.com/google/filament/files/6181965/model.matFile.zip)

**Comment by prideout** [comment]
I think your fbx loader is not computing tangent quaternions correctly, it should use our `SurfaceOrientation` helper for that.

You might want to consider switching from fbx to glTF, since we have an official library for that (`gltfio`).

**Comment by romainguy** [comment]
Please use a discussion to ask further questions, thanks.
