### ISSUE TITLE
VulkanBlitter breaking linking on MacOS (undefined symbols for x86_64)

### ISSUE THREAD

**Issue by pearshapedcode** [google/filament#3676]
Starting a project from scratch with the latest precompiled release v1.9.16 for macOS, using the bare minimum project and build makefile from the main readme example.  Running the makefile through the terminal, the linker is flipping out because of missing symbols for the VulkanBlitter patches introduced in v1.9.12:

```
Undefined symbols for architecture x86_64:
  "_VKSHADERS_BLITCOLORFS_OFFSET", referenced from: filament::backend::VulkanBlitter::lazyInit() in libbackend.a(VulkanBlitter.cpp.o)
  "_VKSHADERS_BLITCOLORFS_SIZE", referenced from: filament::backend::VulkanBlitter::lazyInit() in libbackend.a(VulkanBlitter.cpp.o)
  "_VKSHADERS_BLITCOLORVS_OFFSET", referenced from: filament::backend::VulkanBlitter::lazyInit() in libbackend.a(VulkanBlitter.cpp.o)
  "_VKSHADERS_BLITCOLORVS_SIZE", referenced from: filament::backend::VulkanBlitter::lazyInit() in libbackend.a(VulkanBlitter.cpp.o)
  "_VKSHADERS_PACKAGE", referenced from: filament::backend::VulkanBlitter::lazyInit() in libbackend.a(VulkanBlitter.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

I rolled back through the releases until I hit v1.9.11 which solved this issue, linking and executing as expected so I can carry on with playing with Filament.

I've tested this on a MacBookPro 11,1 + Big Sur and an iMac 14,1 + Catalina, both having the latest full-fat XCode + Command Line Tools the Vulkan SDK installed.

**Comment by prideout** [comment]
Inside the macOS release zip you will find `libvkshaders.a` in the `x86_64` folder.  If you link against it, your problem should go away.

**Comment by pearshapedcode** [comment]
Thanks for that Philip, my libs line in my makefile is now:

`FILAMENT_LIBS=-lfilament -lbackend -lbluegl -lbluevk -lfilabridge -lfilaflat -lutils -lgeometry -lsmol-v -libl lib/x86_64/libvkshaders.a`

...and that compiles a treat.  Would this linking need be updated in the readme.md too? Anyway, cheers :-)
