### ISSUE TITLE
Modify glTF baseColorMap texture

### ISSUE THREAD

**Issue by ThomasGorisse** [google/filament#3684]
Hi,

I'm trying to modify the texture of a glb asset without applying a new material.
Using the [sample-gltf-viewer](https://github.com/google/filament/tree/main/android/samples/sample-gltf-viewer):
- I change the model to [this one](https://github.com/google/filament/files/6188657/model.zip) (Blender default cube without camera and light, default Principled BSDF material)

- I put the [floor_basecolor.png](https://github.com/google/filament/blob/main/android/samples/sample-textured-object/src/main/res/drawable-nodpi/floor_basecolor.png) from [sample-textured-object](https://github.com/google/filament/tree/main/android/samples/sample-textured-object) in the drawble-nodpi folder
- I modify createRenderables() to this:
```kotlin
    private fun createRenderables() {
        val buffer = assets.open("models/model.glb").use { input ->
            val bytes = ByteArray(input.available())
            input.read(bytes)
            ByteBuffer.wrap(bytes)
        }

        modelViewer.loadModelGlb(buffer)
        modelViewer.transformToUnitCube()

        val texture = loadTexture(modelViewer.engine,resources, R.drawable.floor_basecolor, TextureType.COLOR)
        val textureSampler = TextureSampler()
        modelViewer.asset?.materialInstances?.forEach {
            it.setParameter("baseColorMap", texture, textureSampler)
        }
    }
```
Result: The texture is not applied.

Note : This works when trying to only modify an already glb defined base color texture image: 
![image](https://user-images.githubusercontent.com/6597529/112171945-926f9780-8bf4-11eb-9933-302b29ec1c32.png)
but not when basely defined as a color:
![image](https://user-images.githubusercontent.com/6597529/112172170-c480f980-8bf4-11eb-8457-1a56d72c0fc1.png)

**Comment by romainguy** [comment]
`gltfio` will generate shaders that support exactly what the glTF file needs. i.e. if the glTF does not use textures, the material generate will not support textures.

**Comment by prideout** [comment]
Romain is correct, we generally don't support this.  However there is small trick you can do, assuming you're using ubershader mode (which is the default on Android).  If the model has good texture coordinates in UV set 0, you can do:

```
it.setParameter("baseColorIndex", 0)
it.setParameter("baseColorMap", texture, textureSampler)
```

This trick should work because the ubershader loader sets `baseColorIndex` to -1 by default, which tells the shader to disable the lookup.
