### ISSUE TITLE
Formatting improvement for detailed description of BloomOptions

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3692]
In `filament/include/filament/View.h`, the detailed description of `struct BloomOptions` lists descriptions of each member of the structure.  When processed by doxygen, these all run together in a single paragraph, which becomes quite hard to read.  The simple fix is to add blank lines in the source to become paragraph breaks in the documentation.

**Comment by romainguy** [comment]
@bejado @pixelflinger
