### ISSUE TITLE
Chromatic aberration of the picture

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#3711]
**filament version: 1.8.1**
I have a png:
[1.png.zip](https://github.com/google/filament/files/6217323/1.png.zip)
 I use it for a material baseColor for a plane mode.
But the effect on the phone is different from the original picture, I know this is because of post-processing. But I need to turn on post-processing. So, I tried to use inverseTonemap or inverseTonemapSRGB for processing, but the result is still different from the original picture (if post-processing is turned off, there is no problem).
**The shader is:**
`material {
    name : simple_img,
    requires : [ uv0 ],
    shadingModel : unlit,
    blending : opaque,
    flipUV : false,
    parameters : [
        {
            type : sampler2d,
            name : baseColorMap
        }
    ]
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        float4 color = texture(materialParams_baseColorMap,getUV0());
        // float3 inversed = inverseTonemap(color.xyz);
        float3 inversed = inverseTonemapSRGB(color.xyz);
        material.baseColor = float4(inversed, color.w);
    }
}`

TonnMaping is the default: ACES_LEGACY.
Another phenomenon: even if I set TonnMaping to LINEAR, there is still color difference.

**What else might go wrong? Hope to give some hints. Thanks**

**Comment by romainguy** [comment]
Do you have a side-by-side comparison? `inverseTonemap()`or `LINEAR` tone mapping should definitely fix this. Is your texture properly loaded as an `SRGB8_A8` texture?

**Comment by cjsliuj** [comment]
The image is not in sRGB space. So texture is not loaded as SRGB8_A8. And will this have any effect?

**Comment by romainguy** [comment]
According to the image's metadata it is sRGB and that's how all viewers will interpret it. Filament materials expect all colors to be in linear sRGB. If you don't mark your texture as such the result will likely be different than you expect. And it would explain why the linear tone mapper doesn't "work" (Filament will still apply the transfer function at the end to exit linear space).

**Comment by cjsliuj** [comment]
ok thanks

**Comment by cjsliuj** [comment]
One more question, what's the mean of linear sRGB,  I only heard linear or sRGB.

**Comment by romainguy** [comment]
"linear" doesn't mean anything by itself. It's often a shortcut for "linear sRGB", or sRGB color gamut + white point but with a linear transfer function.

**Comment by dandingol03** [comment]
> inverseTonemap

Setting the texture to `SRGB8_A8` can not solve my problem. I use a opengles texture as the color buffer of render target and draw the bitmap texture on it. There is obviously Chromatic aberration even after i close the tome-mapping. However, this acts right at on-screen rendering.

**Comment by dandingol03** [comment]
i can make sure the image below is not the same as the origin picture color 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/13013579/188205072-1a1d3de8-afea-4348-b43e-4083d654bd97.png">
