### ISSUE TITLE
support rendering more than 4 blend shapes simultaneouslly

### ISSUE THREAD

**Issue by AlgoHunt** [google/filament#3726]
**Is your feature request related to a problem? Please describe.**
Thanks for such a great work and supporting more than 4 blend shapes. I'm wondering if it is possible to support rendering more blend shapes (e.g., 16 or 32) once due to the consideration of efficiency. 
  

**Describe alternatives you've considered**
1. I'm trying to solve it based on CPU render.  Could you give some suggestion for the way of accessing the vertex buffer and the index buffer of blend shapes which have been loaded? Thank you. 
2.  I'm also considering to address it based on GPU shader as in https://github.com/google/filament/issues/1487#issuecomment-519237177. To my best knowledge, WebGL2.0-based graphics engineer (e.g., Babylon.js) has supported such a function. 

Any suggestion or update for achieving a similar function will be greatly appreciated.  I'm also glad to contribute for the feature.

**Comment by prideout** [comment]
I don't think supporting more than 4 simultaneous blend shapes is something we can do any time soon, and this appears to be more of a discussion than an issue.  Note that this limitation is not uncommon; e.g. ThreeJS has the same constraint.

**Comment by AlgoHunt** [comment]
Thanks for your advice, I have implemented the CPU method by directly editing vertex position in cgltf data. I would like to ask if there is a way to update vertex position on frame-base. Once the asset is upload to GPU, I can't find an api to force re-upload it. For now, I have to reload the full asset every frame.

**Comment by prideout** [comment]
When you call `setBufferAt` you are actually specifying a range whose size is taken from the buffer descriptor, and the byte offset is an optional fourth argument.

Note that we now also have `setBufferObjectAt` which lets you cache a preloaded swath of vertex data, and quickly swap it in at run time.  To use this new API you will need to call `enableBufferObjects` on the builder.
