### ISSUE TITLE
Camera::setProjection should either allow far to be infinite, or explicitly forbid it

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3730]
**Describe the bug**
Setting a camera's `far` to `INFINITY` results in nothing getting rendered.

**To Reproduce**
1. In material_sandbox.cpp, at the end of the `preRender` function, add the line `camera.setProjection( 40.0, 1.0, 0.1, INFINITY )`.
2. Recompile and run  the sample.

**Expected behavior**
Fairly normal rendering.

**Actual behavior**
Just a black screen.

**Desktop (please complete the following information):**
 - OS: macOS 11.3 Beta
 - GPU: Radeon Pro 560X 
 - Backend: Metal

**Additional context**
In the source of `FCamera::setProjection`, I see that in the perspective case, you're actually using an infinite far (correctly) for rendering.  But if an infinite far is passed in, `mProjectionForCulling` gets set to a matrix containing NaNs.

**Comment by romainguy** [comment]
The far you set via `setProjection` is going to be used for culling and lighting, it should definitely not be set to infinity. As you've discovered, we do this internally anyway.

**Comment by pixelflinger** [comment]
We should maybe improve the documentation here. The far must be set to  where you want the geometry and lighting to be clipped, internally we're always using an infinite far for rendering.
