### ISSUE TITLE
suzanne sample crashing with Metal

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3731]
**Describe the bug**
When compiled to use Metal as the backend, the `suzanne` sample crashes.

**To Reproduce**
1. Set up the sample to use Metal, e.g., in libs/filamentapp/include/filamentapp/Config.h, set the initial value of `backend` to  `filament::Engine::Backend::METAL`.
2. Recompile.
3. Run suzanne.

**Expected behavior**
The sample renders a shiny monkey head.

**Actual behavior**
An immediate crash, logging:

```
utils::PostconditionPanic
in filament::Texture *filament::Texture::Builder::build(filament::Engine &):113
in file filament/src/Texture.cpp
reason: Texture format 65 not supported on this platform
```

**Desktop (please complete the following information):**
 - OS: macOS 11.3 beta
 - GPU: Radeon Pro 560X
 - Backend: Metal

**Additional context**
When using OpenGL, `suzanne` works fine.

**Comment by romainguy** [comment]
It's not technically a bug of the sample. This sample uses `S3TC` compressed textures which aren't supported by Metal.

**Comment by romainguy** [comment]
@bejado @prideout What do you want to do here? I'm inclined to leave it as is or at least add a comment in the sample explaining what I just wrote.

**Comment by jwwalker** [comment]
How about making the sample actually log something saying it can't run with Metal?

**Comment by prideout** [comment]
Sounds good to me.

**Comment by bejado** [comment]
I can look into making that change. I think we want to remove the `--strip-alpha` argument passed to `mipgen`.

**Comment by prideout** [comment]
Thanks Ben!!
