### ISSUE TITLE
compiling application using binaries

### ISSUE THREAD

**Issue by uromastix87** [google/filament#376]
I pulled the git repo and followed the instructions and was able to build using ninja and run the samples fine. However, I'm lost when I want to make my own project. I downloaded the binaries from here:
https://github.com/google/filament/releases
then made a .cpp file like this:
```
#include <filament/FilamentAPI.h>
#include <filament/Engine.h>

using namespace filament;

int main()
{
    Engine *engine = Engine::create();
    // SwapChain *swapChain = engine->createSwapChain(createSDLwindow);
    // Renderer *renderer = engine->createRenderer();
}
```

My directory structure looks like this:
`bin  docs  include  lib  main.cpp  makefile  README.md`
My make file looks like this:
```
OBJECTS=lib/x86_64/libbluegl.a lib/x86_64/libbluevk.a lib/x86_64/libfilabridge.a lib/x86_64/libfilaflat.a lib/x86_64/libfilament.a lib/x86_64/libutils.a
CC=clang++

renderTest: main.o
	$(CC) -Iinclude/ main.cpp $(OBJECTS)

``` 

When I run make I get bombarded with undefined reference errors to Opengl and Vulkan stuff among other things. The output is in the error.txt file. What else do I need to do to get this to compile?
My kernel is: 4.18.12-arch1-1-ARCH 
Thank you.
[error.txt](https://github.com/google/filament/files/2476748/error.txt)

**Comment by bejado** [comment]
I don't think that's the correct way to link against static libraries using Clang. You need to set the library search path with `-Llib/x86_64/` and then specify the names of libraries to link against. And looking at some of the linker errors, I think you'll also need to add the `-pthread` flag:

```
$(CC) -Iinclude/ -Llib/x86_64/ -pthread -lbluegl -lbluevk -lfilabridge -lfilaflat -lfilament -lutils main.cpp 
```

**Comment by bejado** [comment]
Here's a full Makefile that worked for me. I had to copy some linker flags from Filament's root [CMakelists](https://github.com/google/filament/blob/master/CMakeLists.txt) and rearrange the `OBJECTS` order.

```
OBJECTS=lib/x86_64/libfilament.a lib/x86_64/libbluegl.a lib/x86_64/libbluevk.a lib/x86_64/libfilabridge.a lib/x86_64/libfilaflat.a lib/x86_64/libutils.a
CC=clang++-5.0

main.o: main.cpp
	$(CC) -Iinclude/ -std=c++14 -pthread -c main.cpp

main: main.o
	$(CC) main.o $(OBJECTS) -lpthread -lc++ -ldl
```

**Comment by romainguy** [comment]
We should document this :) It's effectively what the JNI bindings do btw. The Android bindings run a different build system.
