### ISSUE TITLE
Color not display as expect(Eg. pure white not pure white).Am I missed something?

### ISSUE THREAD

**Issue by leeho0108** [google/filament#3776]
**Describe the bug**
I am implementing text rendering using filament.
when I use a simple unlit material,and simple set baseColor to `float4(1.0)`,But in output window,It display not as a pure white color,it 0xE3E3E3. Am I missed something?

**To Reproduce**
My test material 
`material {
    name : text,
	blending : transparent,
    // Lists the required vertex attributes
    // Here we only need a color (RGBA)
    requires : [
        color,
        uv0
    ],

    // This material disables all lighting
    shadingModel : unlit,
    parameters : [
    	 {
            type : sampler2d,
            name : baseColor
        }
    ],
}

fragment {
    void material(inout MaterialInputs material) {
        // You must always call the prepareMaterial() function
        prepareMaterial(material);
        float4 finalColor = float4(1.0);
        material.baseColor =  finalColor;
    }
}`

**Expected behavior**
 

**Screenshots**
Here is a screenshot in mac(when I take a screenshot, mouse curser is in red rectangle which I make)
and right window is text draw by awt/swing with pure white color.
 
![image](https://user-images.githubusercontent.com/10900736/113918542-2789a780-9815-11eb-944c-658db21812db.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - GPU: Colorful GeForce GTX 760 1024 MB
 - Backend: [OpenGL]

Best Regards
LeeHo

**Comment by romainguy** [comment]
This is because of tonemapping. Filament always operates in HDR so "pure white" (or display white) will not be FFFFF. You can use a linear tone mapper to disable this, using the `ColorGrading` API on `View`.

**Comment by leeho0108** [comment]
yeah,haha
sorry for newbie question...
and I change tongmapping to `ToneMapping.LINEAR`,it looks just as expect.
Thank you.
