### ISSUE TITLE
Computing a tangent space in the vertex shader

### ISSUE THREAD

**Issue by teub** [google/filament#3782]
**Is your feature request related to a problem? Please describe.**
In order to save a lot of CPU time when generating dynamic procedural geometry, I'm trying to generate the tangent space in the vertex shader from the UVs and normals.

**Describe the solution you'd like**
Be able to customize the vertex format and its processing in the vertex shader.

**Describe alternatives you've considered**
I thought I could write to the tangent space in the function "void materialVertex(inout MaterialVertexInputs material)", but I can only see a "worldNormal" property in MaterialVertexInputs and no tangent information, so I'm at a loss as to what to do from here. Is the rest of the tangent space actually used at all?

Also it doesn't look like I can pass only a normal in the vertex data (or maybe it's possible with custom channels ?)

Thank you

**Comment by teub** [comment]
As a side question : is there any way to access material parameters from the vertex shader? the "parameters" block only seems to be available from the fragment shader, and the "variables" block is only a vertex output if I understood correctly.
Thanks in advance for any clarification.

**Comment by romainguy** [comment]
You can access all the material parameters from the vertex block. We use the full tangent space in the fragment shader but we don't currently provide a way for the vertex shader to override/compute it. Is computing the tangents a real CPU bottleneck for you?

**Comment by prideout** [comment]
This is perhaps unsanctioned but you can modify `vertex_worldTangent` in the vertex block.  For example:

        float3 normal;
        toTangentFrame(myCustomQuat, normal, vertex_worldTangent.xyz);
        material.worldNormal = objectUniforms.worldFromModelNormalMatrix * normal;
        
(the second and third args of `toTangentFrame` are out args)

**Comment by teub** [comment]
> You can access all the material parameters from the vertex block.

Ok maybe I didn't do it correctly then, I'll try this again, thank you.

> Is computing the tangents a real CPU bottleneck for you?

Yes, computing the tangent frame frequently came up in the profiling for this use case (cloth simulation, so it happens at every frame). Not having a geometry shader is already painful (it would look much better with more vertices), and ideally the cloth simulation results should even be used directly by the shader on the GPU without ever going to the CPU.

I've seen among past tickets that the tangent frame computation has been optimized; I'll give it a try but I still don't expect it to give decent results compared to doing it on the GPU.

**Comment by teub** [comment]
So I tried again and everything works as intended. Prideout's solution seems to allow me to modify the tangent space as he explained so I guess I can close the ticket (I'm not sure I can compute it easily from the VS as I thought I could though). Thank you for your help!

**Comment by romainguy** [comment]
Glad to hear it works. Please note however that this is not a public API. We may break it later (I don't think so but just a heads up):
