### ISSUE TITLE
Please provide me some example code for using Dof

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#3788]
I have set depthOfFieldOptions to View with below code:
        view.depthOfFieldOptions.enabled = true
        view.depthOfFieldOptions.cocScale = 10.0f
        view.depthOfFieldOptions.focusDistance = 1.0f

But I can't see any change,
Some one can kindly figure out what's my mistake or give me some example code.

Thanks !

**Comment by romainguy** [comment]
Please use the Discussion tab instead of an issue for questions. Make sure you haven't disabled post processing. And make sure you set the DoF options on View:

val dof = view.depthOfFieldOptions
// Modify options 
view.depthOfFieldOptions = dof
