### ISSUE TITLE
How to update the Bluegl Library

### ISSUE THREAD

**Issue by xaioxw** [google/filament#3792]
I want to use OpenGL to implement the function of compute shader, so I need to upgrade bluegl to support some APIs. But where do I need to get the latest version Library of bluegl， Tks

**Comment by xaioxw** [comment]
for example, i want use mathod 'glBindImageTexture' on macos platform ,and it notes "calling missing GL function!"

**Comment by romainguy** [comment]
There's no "latest version" of bluegl. It's part of Filament. The library is generated by a Python script in the bluegl directory. You'll have to update the headers it uses to generate the code.
