### ISSUE TITLE
samplerParameter is not available, android

### ISSUE THREAD

**Issue by pseandersson** [google/filament#3805]
On Android,  a Material.Builder using the samplerParameter with following line
`.samplerParameter(MaterialBuilder.SamplerType.SAMPLER_2D, MaterialBuilder.SamplerFormat.FLOAT, MaterialBuilder.SamplerPrecision.DEFAULT, "albedo")`
does not generate the parameter "materialParams_albedo".  The  created  instance contains the other uniforms, but not the sampler one, when I look in the debugger, and I am unable to set it, so the texture cannot be rendered.

**To Reproduce**
1. Create a material in Android Studio (kotlin/java) using the Material.Builder and use the samplerParameter method
2. Try to assigne a texture with the setParameter to the sampler
3. Run it on Android 10 emulator

**Expected behavior**
It should be possible to call setParameter and assign texture for the samplerParameter method.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Android 10 Emulator
 - GPU: Quadio P1000
 - Backend: [OpenGL/Vulkan]

**Comment by prideout** [comment]
Interesting.  What do you see in logcat when you try to call `setParameter`?  We use filamat in gltfio (which is C++) so this might be a Java-specific issue.  At first glance the JNI bindings for MaterialBuilder look okay to me.  @bejado might have ideas.

**Comment by bejado** [comment]
I'm unable to reproduce on both emulator and device. Can you show the rest of the calls to`MaterialBuilder`? What happens when you call `setParameter`?

**Comment by pseandersson** [comment]
My wrong, I looked on wrong material.
