### ISSUE TITLE
Point lights don't seem to be working on Android

### ISSUE THREAD

**Issue by SamAmco** [google/filament#3811]
I have been trying to get point lights working on Android with no luck. I added a simple piece of code to the sample-gltf-viewer project and I can see that the point light does not show up: 

```            
private fun createIndirectLight() {
        val engine = modelViewer.engine
        val scene = modelViewer.scene
        val ibl = "default_env"
        readCompressedAsset("envs/$ibl/${ibl}_ibl.ktx").let {
            scene.indirectLight = KtxLoader.createIndirectLight(engine, it)
            scene.indirectLight!!.intensity = 30_000.0f
        }
        readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx").let {
            scene.skybox = KtxLoader.createSkybox(engine, it)
        }

        val light = EntityManager.get().create()

//TRY ADDING A POINT LIGHT

        // Create a color from a temperature (5,500K)
        val (r, g, b) = Colors.cct(5_500.0f)
        LightManager.Builder(LightManager.Type.POINT)
                .color(1f, 0f, 0f)
                // Intensity of the sun in lux on a clear day
                .intensity(110_000.0f)
                // The direction is normalized on our behalf
                .direction(0.0f, -0.5f, -1.0f)
                .position(0f, 1f, 0f)
                .castShadows(true)
                .build(engine, light)

        // Add the entity to the scene to light it
        scene.addEntity(light)
    }
```

![Screenshot_20210415_163206_com google android filament gltf](https://user-images.githubusercontent.com/5012146/114897155-e0994480-9e08-11eb-96f9-8a5df8aa9984.jpg)

However if I change the light type to DIRECTIONAL then I can see the red light in the scene. 

![Screenshot_20210415_163241_com google android filament gltf](https://user-images.githubusercontent.com/5012146/114897183-e727bc00-9e08-11eb-948c-59c5eb8ba8c8.jpg)

I also tried adding the following line in onCreate just to be sure that this isn't due to the light being clipped somehow but I still can't see the effect of the point light: 

```
        modelViewer.view.setDynamicLightingOptions(0.1f, 100f)
```

**Smartphone (please complete the following information):**
 - Device: Huawei P20
 - OS: Android 10

**Comment by romainguy** [comment]
A color temperature of 5,500K shouldn't produce red. Is your code snippet above correct? You may also want to check the light intensity vs the camera exposure. Maybe first try disabling all the other lights (IBL and directional).

**Comment by SamAmco** [comment]
Sorry I'm not actually using that color temperature, I just copied and pasted it across from a different sample. The color passed is just 1.0f, 0.0f, 0.0f in the code above. I just tried removing all other lights from the scene including the IBL and the light added by the model viewer class and I now just see a black screen.

**Comment by SamAmco** [comment]
To be clear all I have done in the above example is taken the example project at android/samples/sample-gltf-viewer/ and added the above code to: android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt

**Comment by romainguy** [comment]
I just realized you didn't give your point light a radius. It's required for point and spot lights.

**Comment by SamAmco** [comment]
Ah yes sorry that works, sorry for my mis-understanding. Thank you for your help.
