### ISSUE TITLE
Documentation error on result of getNormalizedViewportCoord

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3821]
In Filament Materials Guide, the fragment function `getNormalizedViewportCoord` is documented as returning `float2`.  But when I wrote

```
float2 curLoc = getNormalizedViewportCoord();
```

in a fragment shader, `matc` gave an error "cannot convert from ' global 3-component vector of float' to ' temp 2-component vector of float".  If you want more evidence, `shaders/src/getters.fs` shows `getNormalizedViewportCoord` returning a `vec3`.

It wouldn't hurt to explain what the z coordinate means, too.  What's the deal with reversing the z coordinate that I see in `getters.fs`?

**Comment by pixelflinger** [comment]
Regarding the inverted z, filament uses an inverted z because on vulkan, metal or GL with the clip_control extension, this gives us a much better precision in the depth buffer through the whole range.
