### ISSUE TITLE
documentation bug on Skybox

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3826]
The API documentation on `Skybox::Builder::intensity` says:

> Skybox intensity when no IndirectLight is set.
> 
> This call is ignored when an IndirectLight is set, otherwise it is used in its place.

But I don't see anything in `Skybox` or `Skybox::Builder` that can associate an `IndirectLight` with a `Skybox` in any way.

Also, the "Creation and destruction" overview docs on `Skybox` show sample code in which `Skybox::Builder::build` seems to return an `IndirectLight*` instead of a `Skybox*`.

**Comment by romainguy** [comment]
That's not a bug. The association is performed internally at the scene level.

**Comment by jwwalker** [comment]
@romainguy  So, when it says "when an IndirectLight is set", it means when an an IndirectLight is set **on the Scene**.  OK, I didn't guess that.

**Comment by romainguy** [comment]
Thanks, I pushed a small fix.
