### ISSUE TITLE
How to use LookAt in Android?

### ISSUE THREAD

**Issue by theCodes7** [google/filament#3833]
lookat is not taking effect while using in Android. Any thought on that?
`public void lookAt(double eyeX, double eyeY, double eyeZ, double centerX, double centerY, double centerZ, double upX, double upY, double upZ)`

**Comment by romainguy** [comment]
Please open a discussion instead of filing an issue. Like I said in the other bug where you commented, I just used it without any issue. Here's the code I was using:

```
                viewer?.camera?.lookAt(
                    0.0, 0.0, 0.0,
                    direction.x.toDouble(), 0.3, direction.z.toDouble(),
                    0.0, 1.0, 0.0
                )
```
