### ISSUE TITLE
Jagged borders (blending ?) in webGL demo

### ISSUE THREAD

**Issue by MikOfClassX** [google/filament#3838]
![Clipboard03](https://user-images.githubusercontent.com/6151192/115683372-aa9f1780-a356-11eb-951a-777422385ebd.png)
Hello!

Maybe it's no issue at all, but I found that the https://google.github.io/filament/webgl/helmet.html webgl demo is showing some strange white jagged compositing on background.

Looks like a blending / or / interpolation artifact. Taking a look at the picture, there's jagged white borders even inside the helmet eye.

I'm attaching screenshots.

OS: Win10 x64 , NV RTX 2060, WebGL Firefox

Cheers!!

Mik

![Clipboard02](https://user-images.githubusercontent.com/6151192/115682798-19c83c00-a356-11eb-9421-50a99c73041a.png)

**Comment by romainguy** [comment]
That's specular aliasing. It can be addressed by turning on more antialiasing option/tweaking specular antialiasing for this scene. Another IBL would probably look better too.
