### ISSUE TITLE
Is there any options to build shared libraries of filament?

### ISSUE THREAD

**Issue by runchen0518** [google/filament#3842]
- **Describe problem?**

Look at the build output files as usual, they are static libraries, and, it will cost around 25MB.

![image](https://user-images.githubusercontent.com/24858448/115810450-8445ae80-a420-11eb-9456-4a157771fabc.png)

I wanna build shared libraries of filament, it may be smaller on package size.

- **Describe the solution you'd like**

I want to modify some many _CMakeLists.txt_, and change the config _STATIC_ to _SHARED_ in _add_library_
but, i am not sure there will cause new problem.
And, I want to know why the usual build configuration is static libraries?

- **Describe alternatives you've considered**
Is there any options to build shared libraries based on android platform?

- **OS and backend**
**Android Platform**, I want to output files: hpp header files + many so binary files.

In addition, build output binary files and put into [github releases](https://github.com/google/filament/releases) may be a good way lol.

related: #1075

**Comment by romainguy** [comment]
Note that you do not need to link against all those libraries and the final binary will be smaller since your linker can get rid of what you are not using. Anyway this feature has been requested and we're tracking it in issue #1075

**Comment by runchen0518** [comment]
Yep! Later, I thought it, it's just like what you say. But I forgot to to close the issue. Sorry..😀
