### ISSUE TITLE
Rendering oddity in lightbulb sample with Metal

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3849]
**Describe the bug**
When the `lightbulb` sample program uses the Metal back end on macOS, the image does not redraw property when you rotate the image with the mouse.

**To Reproduce**
1. Run the `lightbulb` sample from the command line, like `./lightbulb -a metal assets/models/monkey/monkey.obj`
2. Use the mouse to rotate the monkey

**Expected behavior**
The monkey rotates.

**Actual behavior**
Images of the monkey in various positions accumulate.

**Screenshots**
![screen shot](https://user-images.githubusercontent.com/730426/115940166-5b8bdc00-a455-11eb-8627-d3d7b03f34ee.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.4 Beta
 - GPU: Radeon Pro 560X 4 GB
 - Backend: Metal

**Additional context**
When using the OpenGL backend, I don't get that problem, but oddly, the background is red instead of black.

**Comment by romainguy** [comment]
Yeah it's just because lightbulb doesn't setup a background if you don't give it an IBL. It happens in GL too (I just tried to verify and it's green with my GPU/driver).

**Comment by romainguy** [comment]
@pixelflinger We should probably setup a default skybox/background clear when there's no IBL.

**Comment by pixelflinger** [comment]
lightbulb is not very useful actor actually. material_sandbox has all the features it used to have. Maybe we should just remove it?

**Comment by jwwalker** [comment]
@pixelflinger The reason I was interested in the `lightbulb` sample is its use of a transform with lights in the disco ball.  There's no disco ball in `material_sandbox`.

**Comment by pixelflinger** [comment]
Okay. I will fix lightbulb then :-)
