### ISSUE TITLE
Rendering artifacts on Adreno 505

### ISSUE THREAD

**Issue by paulorrfilho** [google/filament#3854]
Any ideas of what could be happening here? 4 different beta testers reporting the same issue. This only happens in Xiaomi Redmi phones with an Adreno 505/506 GPU. The same GPU in different phones seems to be working fine.
Notes:
- Each cymbal is in a separate fragment.
- Material blending is transparent.
- Material depthWrite is on.
- Fragments overlap.

![messed cymbals](https://user-images.githubusercontent.com/3690419/115974890-affe8c80-a525-11eb-9d51-f3e970552136.png)

**Comment by romainguy** [comment]
This looks like a tiling artifact due to underdraw. Do you have a skybox or something similar to cover/clear every pixel of the rendering surface?

**Comment by paulorrfilho** [comment]
No, I don't add a skybox to the scene, if that's what you are asking.

This is how I set the clearOptions:

`val options = renderer.clearOptions
options.clear = true
renderer.clearOptions = options`

also set the view like this:

`view.blendMode = com.google.android.filament.View.BlendMode.TRANSLUCENT`

**Comment by romainguy** [comment]
Do you also make sure to set `SwapChain.CONFIG_TRANSPARENT` on the `SwapChain` and using `PixelFormat.TRANSLUCENT` for the `SurfaceHolder` format? If you are using our `UiHelper` you can do all of this by setting `isOpaque` to false.

**Comment by paulorrfilho** [comment]
Yes, I am using `UiHelper` and `isOpaque` was already set to false.

**Comment by pixelflinger** [comment]
I'm confused, why does the surface and view need to be translucent? Is there something behind it?


Regardless, you could try to run in vulkan mode, see if that changes anything.

**Comment by paulorrfilho** [comment]
Only the cymbals are rendered in real-time, that's why I need them transparent.

Is using Vulkan as easy as `engine = Engine.create(Engine.Backend.VULKAN)`?
I am getting "Couldn't create Engine" in my project and "Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)" when I run a sample. I am testing this in a deivice that is able to run my project and the samples with no issues.
I am using the pre-built library by the way.

**Comment by pixelflinger** [comment]
Yes it should be at least at specifying vulkan like you did. Maybe your phone doesn't support vulkan?

**Comment by romainguy** [comment]
Our prebuilt binaries for Android don't support Vulkan. You need to build the library yourself.

What do you render the cymbals on top of? Could you render everything with Filament?

**Comment by paulorrfilho** [comment]
> Our prebuilt binaries for Android don't support Vulkan. You need to build the library yourself.
> 
> What do you render the cymbals on top of? Could you render everything with Filament?

It is rendered on top of an `ImageView`. It would be too heavy to render everything. That was my experience with the iOS version of my app using the SceneKit library.

**Comment by paulorrfilho** [comment]
> Yes it should be at least at specifying vulkan like you did. Maybe your phone doesn't support vulkan?

I just tested it in 3 different phones that supposely support Vulkan, it runs in one of them the other two crash on start.
Tested running the IBL sample built locally.

I guess the Vulkan support is not stable at this point?

**Comment by romainguy** [comment]
Why would it be too heavy? It will either be cheaper to render everything with Filament or basically the same. Adding an image in the background isn't exactly expensive esp. compared to the cost of the transparent path in Filament (memory and performance).

**Comment by romainguy** [comment]
Oh and for Vulkan, the prebuilts are not compiled with Vulkan support at this time.

**Comment by paulorrfilho** [comment]
> Why would it be too heavy? It will either be cheaper to render everything with Filament or basically the same. Adding an image in the background isn't exactly expensive esp. compared to the cost of the transparent path in Filament (memory and performance).

Do you mean to render the background plus cymbals with Filament? I thought you meant to render the whole scene.
I didn't think about this possibility. Anyway, the problem with this approach is that I need full control of where exactly the cymbals appear in every android screen, precision is very important for the users of my app, and I found it a lot easier to achieve this by putting each cymbal in a fragment.

**Comment by paulorrfilho** [comment]
> Yes it should be at least at specifying vulkan like you did. Maybe your phone doesn't support vulkan?

I think I need to turn on this flag as well, no? `option(FILAMENT_SUPPORTS_VULKAN "Enables Vulkan on Android" OFF)`

Should I touch this? `def excludeVulkan = project.hasProperty("filament_exclude_vulkan")`

is there any documentation around this?

**Comment by romainguy** [comment]
If you use build.sh Vulkan is compiled by default (and -v will turn it back off).

**Comment by paulorrfilho** [comment]
Ok, that's what I did, so it makes sense because the ibl sample ran fine in one of my devices using Vulkan. The other phones didn't work for some reason, will test a bit more.

**Comment by paulorrfilho** [comment]
Preliminary results are not good. Vulkan didn't show much improvement. I will use the fake cymbals approach when I launch my app within a month or two. I will run additional tests later after that.
Thank you

**Comment by pixelflinger** [comment]
Could you check if our `Multi View` test works on your device? That might give us some clue.

**Comment by paulorrfilho** [comment]
`Multi View` runs fine when using the OpenGL backend on my device with the Adreno 505 GPU. I do see some artifacts when I change the backend to Vulkan, so OpenGL is better in this case.

Just to be clear, the image I posted at the beginning of this issue was sent by a user, and other users sent me similar images, all of them using the Adreno 505 on a Xiaomi Redmi 4X/Pro, my device runs fine.

I was able to reproduce the issue a couple of days ago. It started when I added the Admob (ads provider) library. I was initializing it at the same time as the fragments with the 3D views are created. Admob is known to be heavy to initialize, so my best guess is that the artifacts are caused by some sort of memory pressure issue. Does that make sense? When I don't start the Admob library the 3D is fine.

The fact that all users having this issue have the same Redmi 4x/Pro phone and other phones with an Adreno 505 run ok makes me think it is indeed related to a memory/low spec issue and not the GPU or rendering approach.

**Comment by pixelflinger** [comment]
It's possible -- I would expect something meaningful in the logs though. 
Transmission definitely uses more memory. Given that this has been reproduced on a single device, I think there is not much we can do.

**Comment by dandingol03** [comment]
i reproduce this problem on vivo x9, oppo R9s, vivo x21.

**Comment by dandingol03** [comment]
@paulorrfilho  Hi,  i also met the same problem. Have you figure out why the 505/506 gpu acts like that?

**Comment by paulorrfilho** [comment]
It is hard to pinpoint the reason, but I think it was related to either high memory usage or heavy CPU usage while loading the 3D model in Filament. I could not reproduce this issue myself but after optimizing the memory usage of my app I stopped receiving reports of this issue from my users.
