### ISSUE TITLE
highlighting geometry

### ISSUE THREAD

**Issue by Pankaj003** [google/filament#3859]
Hi, I want to highlight the object geometry/contour like one in the attached file. Do we have any sample application I can check or can you guide me the filament classes I need to explore.

Thanks

![highlight](https://user-images.githubusercontent.com/8086656/116190899-0b5c9480-a749-11eb-8666-9ef2f1132bb1.PNG)

**Comment by romainguy** [comment]
Please open a discussion instead of an issue for questions like this. We do not have a sample that does this exactly but someone was recently explaining in a discussion how they achieved this exact effect.
