### ISSUE TITLE
FPS test

### ISSUE THREAD

**Issue by Ziyu98** [google/filament#3869]
I run the gltf-viewer sample to measure the rendering performance on Android device (Pixel 3 Phone). To see if the frame is missed/dropped, I modified the code in "android/filament-utils-android/src/main/java/com/google/android/filament/utils/**ModelViewer.kt**" like following (begin with line 267 in original code):
_// Render the scene, unless the renderer wants to skip the frame.
        if (renderer.beginFrame(swapChain!!, frameTimeNanos)) {
            System.out.println("rendering .....")
            renderer.render(view)
            renderer.endFrame()
        } else {
            System.out.println("skipping .....")
        }_
        
In the logcat of Android Studio, about 1/3 of the log shows "skipping...", meaning that there are about 1/3 frames being missed.

However, I aslo used the systrace tool to collect the traces. In the [output html file](https://github.com/google/filament/files/6389188/temp.zip) (attached), no frame drops. This makes me confused. Did I misunderstand something?
[temp.zip](https://github.com/google/filament/files/6389188/temp.zip)

**Comment by romainguy** [comment]
How do you invoke the render method of Model viewer?

**Comment by Ziyu98** [comment]
I didn't modify any code other than adding two display lines in ModelView.kt. Based on the sample code in MainActivity.kt for gtlf-viewer, the render should be invoked by the Choreographer via:
_modelViewer.render(frameTimeNanos)_

**Comment by romainguy** [comment]
Then it's probably working as intended. Systrace only shows dropped frames for the UI renderer of Android itself, not for arbitrary renderers like Filament. There are various ways to improve performance, like lowering the render quality, reducing the resolution or better even, enabling dynamic resolution in Filament.

**Comment by Ziyu98** [comment]
Does this mean that the performance/FPS collected from the Android Studio logcat is the real rendering performance? Since I found that after enabling dynamic resolution in Filament, less frames are dropped.

**Comment by romainguy** [comment]
Logcat isn't a good way to assess performance no. You can use systrace but you'd have to look at the frame durations as shown by Filament's render thread and SurfaceFlinger.
