### ISSUE TITLE
Poor doxygen formatting of Renderer::readPixels

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3880]
The header comments on the two versions of `Renderer::readPixels` include a diagram that should be handled as preformatted text and isn't, making the diagram illegible in doxygen output, and conversely some text that doesn't need to be preformatted is.

I've attached my version of Renderer.h, but if you'd rather have a pull request, I can easily do that.

[Renderer.h.zip](https://github.com/google/filament/files/6411986/Renderer.h.zip)

**Comment by romainguy** [comment]
A PR would be better if you don't mind.

**Comment by jwwalker** [comment]
OK, I created a PR #3881.   I don't know how to link it to this issue.

**Comment by romainguy** [comment]
All you have to do is say something like "Fixes issue #XXXX" in the PR description to link it. Anyway, it's merged, thank you so much for your help!
