### ISSUE TITLE
Broken IBL reflections

### ISSUE THREAD

**Issue by SamAmco** [google/filament#3889]
_I am using filament for android and I discovered the following issue using an Android 10 device (Huawei P20). I have zipped up the example project that demonstrates this problem [here](https://drive.google.com/file/d/1b55XsnULpY4xhj0GA2q_RvaiaYJvTFS5/view?usp=sharing) and you can find a video of the issue [here](https://drive.google.com/file/d/1xc-jk8SM4FuyV_Ir1Vtl2WaziLCpXGSl/view?usp=sharing)_

I used the ModelVIewer class to load a glb file containing two reflective spheres into a scene. Then I add a skybox and IBL using the following code:

```
    private fun createSkybox() {
        val engine = modelViewer.engine
        val scene = modelViewer.scene
        readCompressedAsset("pillars_2k_skybox.ktx").let {
            scene.skybox = KtxLoader.createSkybox(engine, it)
        }
    }

    private fun createEnvironmentLighting() {
        val engine = modelViewer.engine
        val scene = modelViewer.scene
        readCompressedAsset("pillars_2k_skybox.ktx").let {
            scene.indirectLight = KtxLoader.createIndirectLight(engine, it)
            scene.indirectLight?.intensity = 10_000f
        }
    }
```

I would expect the spheres to fully reflect the IBL from all orientations, but what I find is that there are sections of the spheres which do not reflect the IBL like so: 

![Screenshot_20210504_181017_uk co conjure filament_test2](https://user-images.githubusercontent.com/5012146/117044072-e4ccc980-ad05-11eb-9b0e-bedb0409de97.jpg)

Initially I assumed this must be a problem with the ktx file, but the file I am using is from this git repo at: docs/webgl/pillars_2k/pillars_2k_skybox.ktx. Additionally there is no tearing or blank sections in the background cubemap. What is most puzzling is that when I rotate the device and the view is destroyed and re-created, the sections of the spheres that do not reflect the IBL are different, as in the below image:

![Screenshot_20210504_181258_uk co conjure filament_test2](https://user-images.githubusercontent.com/5012146/117044246-22c9ed80-ad06-11eb-992e-640f75483965.jpg)

Any help would be much appreciated. Thank you.

**Comment by romainguy** [comment]
How do you create the sphere? The problem could be caused by incorrect normals on the 3D object.

**Comment by SamAmco** [comment]
I created the spheres and material in Blender. I just used a default sphere with smooth shading, you can see the setup here:

![sphere-normals-demo](https://user-images.githubusercontent.com/5012146/117119758-68c89500-ad8a-11eb-91ee-c802e95e434e.png)

After exporting to glb I dragged it into https://gltf-viewer.donmccurdy.com/ and the spheres seem to reflect the IBL fully in there: 

![working-spheres-demo](https://user-images.githubusercontent.com/5012146/117119840-80078280-ad8a-11eb-9bff-ce81418cf066.png)

**Comment by prideout** [comment]
It looks like you are using `pillars_2k_skybox.ktx` for both the skybox and the IBL.  Note that cmgen can generate two KTX files: one for the KTX and one for the IBL.  They're not the same thing.

**Comment by romainguy** [comment]
Ah yes good catch @prideout. That KTX file will not work for the reflections. BTW @SamAmco you can also try your glTF directly in Filament on this page: https://google.github.io/filament/viewer/

**Comment by SamAmco** [comment]
I see, thanks very much guys. I will close this issue then.
