### ISSUE TITLE
Camera stream texture shift on some devices

### ISSUE THREAD

**Issue by iamlkj** [google/filament#3900]
Hi we’re using filament on a android AR project. We basically copied SceneForm to set up our camera stream:https://github.com/google-ar/sceneform-android-sdk/blob/master/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform/rendering/CameraStream.java). It works ok except some Samsung products(S9, S9+, Note9) on the front facing camera. 

Data:
device resolution(2220 * 1080)
Androdi surface view dimention(2031 * 1080)
ARCore front camera intrinsices returns resolution of. 1440 x 1080 by using
`frame.getCamera().getTextureIntrinsics().getImageDimensions();`
The display orientation is portrait.

With this setup in a basic GLSurfaceView system, where we can directly use the external texture from ARCore (no UV transforms for rotation, etc), we get this result:
![gl](https://user-images.githubusercontent.com/7697488/117360412-9d614d00-ae6d-11eb-9391-3f76be49671d.png)

When we set up the equivalent in Filament using this call:
`filament::Stream::Builder().width(1440).height(1080).stream(textureID).build(engine);`

We get this result:
![filament](https://user-images.githubusercontent.com/7697488/117360432-a18d6a80-ae6d-11eb-8d89-24096c7c9da4.png)
This image seems bias and shift. We don’t understand the mapping in the extra copy here.  Are we using the right resolution for the stream?  We’re guessing there’s a resolution mismatch, and don’t understand why.  We also don’t understand what happens when there is a resolution mismatch.

**Comment by iamlkj** [comment]
We've tried [Sceneform AugmentedFaces ](https://github.com/google-ar/sceneform-android-sdk/tree/v1.15.0/samples/augmentedfaces/app/src/main/java/com/google/ar/sceneform/samples/augmentedfaces
)example and we got the same issue on Samsung S9+

![image (9)](https://user-images.githubusercontent.com/7697488/117366324-6c851600-ae75-11eb-989e-bdf6e1fbd2b1.png)

**Comment by pixelflinger** [comment]
Are you sure that the camera stream is 1440x1080? this is the value we will use to copy the buffer?

Would you be able to try to disable the copy:

`#define DEBUG_NO_EXTERNAL_STREAM_COPY false`

Set this to true in `OpenGLDriver.cpp` -- this will tell us if the problem is from the copy.

**Comment by iamlkj** [comment]
We currently using filament 1.9.8 and the 1440x1080 is read from ARCore camera and it's exactly the size we set for camera stream. For the Sceneform example, we use Sceneform 1.15 since they take out the AugmentedFaces example on the latest version. 
we'll try to disable the copy and come reply back later.

**Comment by iamlkj** [comment]
We tried disabling the copy. The green bias still exists.

**Comment by hillesland** [comment]
Please disregard KJ's comment about the 5 cm bias.  The bottom line is that the copy "fixed" that particular problem (but then we got other issues, probably related to lack of copy)

The root of the problem seems to be a resolution error somewhere at or below ARCore.  However, most people outside Filament won't see this because they use texture() instead of texelFetch().  

So locally, we've changed the OpenGLBlitter to do a texture() instead of texelFetch (GL_LINEAR).  I realize that's not really a "blit" but I actually think that's a good way to go.  It would be more robust to these sorts of situations, while allowing for some flexibility - maybe I don't need full resolution copies, for example.  Access to that copy is probably going to be a filtered [0,1] style fetch anyways.

**Comment by romainguy** [comment]
That's more a workaround than an actual fix. A 1:1 copy should work with texelFetch and we should investigate what's going on.

**Comment by hillesland** [comment]
There's no bug in the 1:1 copy itself (as far as we know).  It's a workaround for a bug elsewhere (ARCore?)

I agree that we did not do a proper fix for a 1:1 copy semantic.  I suppose I'm making a feature request, where I only have to specify the size of the destination for the reasons I mentioned.

**Comment by hillesland** [comment]
Thanks for all the help, by the way.

**Comment by pixelflinger** [comment]
One problem is that opengl doesn't let us query the real size of the image. So we rely on the info given to us. I will take another look to see if I missed something somehow.

**Comment by pixelflinger** [comment]
So, ARCore now has an API that can avoid the copy entirely -- you can use `Texture::import` instead.
You should use that instead and in fact we will deprecate and remote the `Stream` API that make a copy in the near future.
