### ISSUE TITLE
filament-1.9.18: memory about ResourceLoader::LoadResources

### ISSUE THREAD

**Issue by JackKaiXing** [google/filament#3910]
Hello,
Our project uses filament-1.9.18.

The `ResourceLoader::LoadResources` method would use large memory, while i do not know how to free those memory since `FilamentAsset::releaseSourceData`, `AssetLoader::DestoryAsset` and `AssetLoader::destory(my_asset_variable)` does not free as much memory as `ResourceLoader::LoadResources`.

Does filament-1.9.18 also has bug as this issue *https://github.com/google/filament/issues/3888* pointed out?

Thanks.

**Comment by prideout** [comment]
v1.9.20 was the first release that had the VBO memory leak in #3888.

**Comment by JackKaiXing** [comment]
@prideout thanks for quick reply.
https://github.com/google/filament/blob/v1.9.18/filament/backend/src/opengl/OpenGLDriver.cpp. The implementation of `destroyVertexBuffer ` is not same as your new commit *https://github.com/google/filament/pull/3894/commits/85a30d1cb70e0f8342e4b9eb3d2c54c07fcb6507* and *https://github.com/google/filament/pull/3906/commits/bb513966efe39ee3ab784e047258064b48c2580d*.

Besides, how to *accurately* destroy a `ResourceLoader`? just `delete my_resourceloader_variable`?

thanks.

**Comment by prideout** [comment]
Yes, you can simply use `delete` for ResourceLoader if you created it with `new`.

**Comment by JackKaiXing** [comment]
@prideout 

Our *URI data of Gltf file* is not loaded from disk, but from memory using `addResourceData`. Does the `memory free process` remains the same as we mentioned above?

**Comment by prideout** [comment]
Yep, you can either delete the ResourceLoader or call `evictResourceData()` to clear the cache.  If you are using asynchronous loading, be sure to this only after a model has been fully loaded or canceled.

**Comment by JackKaiXing** [comment]
@prideout 

https://github.com/google/filament/blob/v1.9.18/libs/gltfio/src/DracoCache.cpp
**line 42:** `DracoMesh* mesh = DracoMesh::decode(compressedData, key->size);`

https://github.com/google/filament/blob/v1.9.18/libs/gltfio/src/ResourceLoader.cpp
**line 212:**`DracoMesh* mesh = dracoCache->findOrCreateMesh(draco.buffer_view);`

Does this pointer `mesh`  needed to be deleted?

**Comment by JackKaiXing** [comment]
@prideout 

In file, ResourceLoader.h, both `decodeDracoMeshes(asset);`and `asset->mResourcesLoaded = pImpl->createTextures(async);` would create large memory, does `AssetLoader::DestoryAsset` free all those memory?
