### ISSUE TITLE
How to disable tonemapping for individual materials?

### ISSUE THREAD

**Issue by alexey-pelykh** [google/filament#3915]
**Is your feature request related to a problem? Please describe.**
We'd like to be able to render specific objects without tonemapping, that represent either HUD or non-AR background.

**Describe the solution you'd like**
Being able to exclude specific objects/materials from the tonemapping.

**Describe alternatives you've considered**
Adding a material that will inverse tonemapping to negate the tonemapping effect, but it's likely to be non-linear.

**Comment by romainguy** [comment]
Why would inverse tone mapping be non linear? Anyway that’s the way to do it in a given material. The other option is to use a second View wit tone mapping disabled on it.
