### ISSUE TITLE
'MT_StaticRelease' doesn't match value 'MD_DynamicRelease'

### ISSUE THREAD

**Issue by teub** [google/filament#3932]
**Is your feature request related to a problem? Please describe.**
So I'm updating filament to the latest release (I got behind quite a lot), and now the static libraries don't link to my project anymore. 
I suppose there were reasons for removing those md libs from the release  (to save space?) : does that mean I need to recompile all the binaries myself ?

**Describe the solution you'd like**
I think both md and mt versions of the libraries were useful. If my memory is correct, I'm also expecting the debug versions are needed too, because of some stl shenanigans with debug flags.

**OS and backend**
Windows

**Comment by bejado** [comment]
This has been fixed; you can find the latest Windows binaries under the [1.9.24 release](https://github.com/google/filament/releases/tag/v1.9.24).
