### ISSUE TITLE
CMake target names

### ISSUE THREAD

**Issue by ScatteredRay** [google/filament#3936]
**Is your feature request related to a problem? Please describe.**
While integrating Filament into another CMAKE project, I sometimes get target conflicts, specifically the `image` target in libs/image/CMakeLists.txt conflicts with an image target in FLTK. 

It also produces libs with names like `image.lib` which even without CMake, will cause conflicts.

**Describe the solution you'd like**

If Filament targets could be namespaced, this would greatly reduce the chance of collision, i.e.

`set(TARGET Filament::image)`
`set(TARGET filament_image)`

**Comment by prideout** [comment]
Yes we're starting to move to a `filament-image` convention.  In fact if you made a PR for that we'd probably merge it :)

**Comment by romainguy** [comment]
Let's not use namespaces but new library names. That's safer anyway.
