### ISSUE TITLE
BlueGL shouldn't export GL symbols on Windows

### ISSUE THREAD

**Issue by ScatteredRay** [google/filament#3938]
**Describe the bug**
Trying to link filament into another application that includes opengl32.lib, it seems that filament provides it's own opengl function bindings in the bluegl lib, it appears that this conflicts with the symbols in opengl32.lib

**To Reproduce**
I'll try to create a test project that exhibits the behaivor, but broadly
1. Create a new cmake project
2. Add a new executable target.
3. Add a filament as a link library
4. Add opengl32.lib as a link library.
5. In source for the new target, try to initialize a filament Engine, and ensure there is a few calls to gl functions, such as glBlendFunc (maybe in a separate dependent .lib)

Observe linker errors, such as:
```
opengl32.lib(OPENGL32.dll) : error LNK2005: glBlendFunc already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glDisable already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glDrawBuffer already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glEnable already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glFlush already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glGetIntegerv already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glLineWidth already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glReadBuffer already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glViewport already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glPixelStorei already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glReadPixels already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glScissor already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glBindTexture already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glDeleteTextures already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glGenTextures already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glGetDoublev already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glGetFloatv already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glGetString already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glGetTexLevelParameteriv already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glTexImage2D already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
opengl32.lib(OPENGL32.dll) : error LNK2005: glTexParameteri already defined in bluegl.lib(BlueGLCoreWindowsImpl.S.obj)
bin\riggy_editor.exe : fatal error LNK1169: one or more multiply defined symbols found
```

**Expected behavior**
Applications using OpenGL should be able to compile with filament.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Backend: OpenGL

**Comment by romainguy** [comment]
That is correct, Filament does not expect to be linked against `opengl32.lib`. Its `bluegl` library is all you need and was designed for efficiency.

**Comment by romainguy** [comment]
All the symbols in bluegl are marked private (at least they are on macOS/Linux), you should be able to link filament libraries into a .so to avoid conflicts. Let us know if that works, otherwise we can figure something out.

@bejado Do you know if we hide the GL symbols on Windows? I know we do on other platforms.

**Comment by romainguy** [comment]
I hope it does :/ Otherwise we could offer a compile-time flag to link against opengl32.lib instead of bluegl.lib. BlueGL itself is basically 2 function calls so that would be trivial (all the GL calls are regular GL calls in the Filament code base so no impact there).

**Comment by bejado** [comment]
Looking into this...

**Comment by bejado** [comment]
> other libraries we are linking against (e.g. Maya dlls) link against opengl32.lib

@ScatteredRay I'm confused by this. Can you elaborate on your use-case here? What set of libraries are getting passed to the linker alongside Filament libs (`filament.lib`, `backend.lib`, etc)?
