### ISSUE TITLE
 RuntimeError: function signature mismatch

### ISSUE THREAD

**Issue by wasabia** [google/filament#3939]
when run web demo triangle

```
filament.wasm:0x10c6ef Uncaught (in promise) RuntimeError: function signature mismatch
    at http://localhost:8000/filament.wasm:wasm-function[1820]:0x10c6ef
    at http://localhost:8000/filament.wasm:wasm-function[390]:0x1a7d4
    at Function.Engine$_create [as _create] (eval at new_ (http://localhost:8000/filament.js:9:90896), <anonymous>:7:10)
    at Function.Filament.Engine.create (http://localhost:8000/filament.js:222:40)
    at new App (http://localhost:8000/triangle.html:29:54)
    at http://localhost:8000/triangle.html:23:18
    at taskFinished (http://localhost:8000/filament.js:65:13)
    at http://localhost:8000/filament.js:83:9
```

**Comment by prideout** [comment]
I do not see this with main and Chrome 90.0.4430.212 on macOS x86_64.

Which version of Filament and Browser are you using?

**Comment by cx20** [comment]
I have confirmed the same error in the following environment.
Windows 10 + GeForce GTX 660 + Chrome 90.0.4430.93

**Comment by wasabia** [comment]
Hi @prideout

macOS 11.2.3  chrome 90.0.4430.93 (x86_64)

just open this link have same error
[https://google.github.io/filament/webgl/demo_triangle.html](https://google.github.io/filament/webgl/demo_triangle.html)

<img width="963" alt="QQ20210512-101923@2x" src="https://user-images.githubusercontent.com/1768228/117908813-b3f32280-b30b-11eb-9df2-0e4eafefe450.png">

**Comment by prideout** [comment]
I can't reproduce the issue (via the github.io page) on my NVIDIA Windows machine either.  Maybe this is a race condition with the wasm loader.  Does this reproduce for you reliably or intermittently?

**Comment by wasabia** [comment]
Hi
@prideout 
[https://google.github.io/filament/webgl/](https://google.github.io/filament/webgl/)

Any webgl demos not work!

**Comment by cx20** [comment]
In my case, I'm having this issue on a GeForce GTX 660 on Windows 10.
The same issue occurs with Triangle and other demos.
However, the same Chromium version of Edge doesn't seem to cause any problems.
Also, Chrome Canary doesn't seem to have any issues.

|OS|GPU|Browser|result|
|:----:|:----:|:----|:----:|
|Windows 10|GeForce GTX 660|Chrome 90.0.4430.93|:x:|
|Windows 10|GeForce GTX 660|Chrome 90.0.4430.212|:x:|
|Windows 10|GeForce GTX 660|Chrome Canary 92.0.4505.0|:white_check_mark:|
|Windows 10|GeForce GTX 660|Edge 90.0.818.56(Chrome 90.0.4430.93)|:white_check_mark:|

**Comment by cx20** [comment]
I have confirmed that the event can be reproduced by changing the settings even on Windows 10 + Chrome + `GeForce RTX 2060`.
This happened when I changed Chrome's `ANGLE` backend from `default` to `OpenGL`.

![image](https://user-images.githubusercontent.com/1833979/119564776-1fe18a80-bde4-11eb-9693-d4494eac2293.png)

```
filament.js:9 
in static filament::backend::Driver *filament::OpenGLDriver::create(filament::backend::OpenGLPlatform *const, void *const):92
put_char @ filament.js:9
filament.js:9 
reason: Can't get OpenGL version
put_char @ filament.js:9
filament.js:9 
put_char @ filament.js:9
demo_triangle.html:1 
[.WebGL-000007E8024BBC80] GL_INVALID_OPERATION: Extension is not requestable.

filament.wasm:0x10c97e Uncaught (in promise) RuntimeError: function signature mismatch
    at https://unpkg.com/filament@1.10.0/filament.wasm:wasm-function[1819]:0x10c97e
    at https://unpkg.com/filament@1.10.0/filament.wasm:wasm-function[390]:0x1a995
    at Function.Engine$_create [as _create] (eval at new_ (https://unpkg.com/filament/filament.js:9:90896), <anonymous>:7:10)
    at Function.Filament.Engine.create (https://unpkg.com/filament/filament.js:222:40)
    at new App (https://google.github.io/filament/webgl/tutorial_triangle.js:4:50)
    at https://google.github.io/filament/webgl/tutorial_triangle.js:83:16
    at taskFinished (https://unpkg.com/filament/filament.js:65:13)
    at https://unpkg.com/filament/filament.js:83:9
```

**Comment by prideout** [comment]
This is not actionable on our end, seems like an ANGLE bug, especially since the error message seems related to `ANGLE_request_extension`.
