### ISSUE TITLE
feedbackLoops test is not passed 

### ISSUE THREAD

**Issue by mirsfang** [google/filament#3941]
run result : 

Intel Inc., Intel(R) UHD Graphics 630, 4.1 INTEL-16.2.16, 4.10
OS version: 0
Level Level : 180x90
Level : 90x45
Computed hash is 0x405970a1, Expected 0xe93a4a07

**Comment by pixelflinger** [comment]
That would indicate a problem with this GPU. @prideout  what do you think?

**Comment by prideout** [comment]
Yes I'd say this is a driver bug, and it indicates that some of our post-processing effects might not work properly with this GPU.
