### ISSUE TITLE
setIBLRotation:: how to get the rotation matrix in vertex block

### ISSUE THREAD

**Issue by JackKaiXing** [google/filament#3951]
Hello, 

Our project rotate the IBL use `IndirectLight::setRotation`, we also use `world space direction vector` in `vertex block`. however, I found i have to rotate my direction vector in `vertex block` to match the ibl rotation. 

Is there a fast way to get **IBL_ROTATION MATRIX** in vertex block, so i do not need to upload the matrix through material instance.

Thanks.

**Comment by romainguy** [comment]
Please open a discussion instead of a bug for questions. The IBL rotation is not available to the shaders as it is handled on the CPU side by transforming the entire scene. Could you please describe what you are trying to achieve?
