### ISSUE TITLE
Question: why does the worldFromModelNormalMatrix apply to tangent vector?

### ISSUE THREAD

**Issue by Hearwindsaying** [google/filament#3952]
In main() of main.vs:
```cpp
        // We don't need to normalize here, even if there's a scale in the matrix
        // because we ensure the worldFromModelNormalMatrix pre-scales the normal such that
        // all its components are < 1.0. This prevents the bitangent to exceed the range of fp16
        // in the fragment shader, where we renormalize after interpolation
        vertex_worldTangent.xyz = objectUniforms.worldFromModelNormalMatrix * vertex_worldTangent.xyz;
        vertex_worldTangent.w = mesh_tangents.w;
        material.worldNormal = objectUniforms.worldFromModelNormalMatrix * material.worldNormal;
```
This might be a graphics/math related problem.
I know that for normal vector transformation, it should use a fixed transform to ensure that it's perpendicular to the tangent plane after transformation.
But why do we apply this to tangent vector instead of using the trivial worldFromModelMatrix?

**Comment by romainguy** [comment]
Please use discussions for questions instead of filing bug reports.

The tangent is subject to the same problems as the normal when transforming it. Note that the computations in the shaders are the same, it's just a different matrix that's being used.
