### ISSUE TITLE
ResourceLoader::asyncbeginload does not return immediately for gld and ResourceLoader::addResourceData

### ISSUE THREAD

**Issue by JackKaiXing** [google/filament#3959]
Hello,

In *ResourceLoader.cpp*, our project sets `#define USE_FILESYSTEM 1` for WIN and IOS.

After `ResourceLoader::createAssetFromJson` and  `ResourceLoader::addResourceData` for all the bins and texture, we call `ResourceLoader::asyncBeginLoad` but it does not return immediately.

Any ideas?

**Comment by prideout** [comment]
This method does do some work synchronously, such as processing and uploading vertex buffers.  The primary asynchronous activity is texture decoding, which tends to be the slowest part of the loading process.

**Comment by JackKaiXing** [comment]
@prideout 

I looked into code of ResourceLoader and made experiments with draco and undraco gltf files. It seems that the method `static void decodeDracoMeshes(FFilamentAsset* asset)` consumes some time for delayed return in the main loop.

Any Ideas that I could changed this part as async loading as the texture decoding tasks?

thanks.

**Comment by JackKaiXing** [comment]
@prideout 

I looked into code of ResourceLoader and made experiments with draco and undraco gltf files. It seems that the method `static void decodeDracoMeshes(FFilamentAsset* asset)` consumes some time for delayed return in the main loop.

Any Ideas that I could changed this part as async loading as the texture decoding tasks?

thanks.
