### ISSUE TITLE
GLTF Morph Stress Test rendering issues

### ISSUE THREAD

**Issue by FabianRueckert** [google/filament#3961]
**Describe the bug**
Using the morph stress test model from:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphStressTest

When playing the animation at index 0, it usually looks like this: 

<img src="https://user-images.githubusercontent.com/61990737/118297927-13edf280-b4df-11eb-9db4-73f8db9f1f19.png" alt="image" width="200" >

It is only applying the first morph targets. Even though the model has 8 morph targets in the animation.
This can also be seen on the web viewer: https://google.github.io/filament/viewer/

When playing the animation at index 1, it completely breaks: (sometimes also for animation 0)

https://www.youtube.com/watch?v=tVzdR8U4lqg
<img src="https://user-images.githubusercontent.com/61990737/118298314-9bd3fc80-b4df-11eb-8b66-876df7dc5190.png" alt="image" width="200" >

**To Reproduce**
1. In Filament Android gltf-viewer app, add code to load above model .glb.
2. Change animation index to "1" in
```
  applyAnimation(1, elapsedTimeSeconds.toFloat())
````

**Expected behavior**
See videos here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphStressTest

**Smartphone (please complete the following information):**
 - Device: Pixel 3 + Samsung S10
 - OS: Android 11

**Comment by prideout** [comment]
Thanks, I will take a look!

**Comment by prideout** [comment]
This is an excellent test case, it's uncovering several issues that were not provoked by other models we tried.  So far I've fixed one of the issues with the `Individuals` animation.

We will never handle the `TheWave` animation perfectly since we only honor the 4 highest weights, but obviously we should not fail so badly.

Fixes are on the way.
