### ISSUE TITLE
Can't sample depth texture in OpenGL on Mac

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3962]
**Describe the bug**
When I render to a `RenderTarget` with a sample-able depth texture attached, I can successfully sample from the depth texture using Metal but not OpenGL.

**To Reproduce**
1. Uncompress the attached Xcode project on a Mac.
2. Open the project in Xcode.
3. Edit the file "proj.xcconfig" and change FILAMENT_REPO to the full path to the Filament repository on your computer.
4. Set the target pop-up menu at the top of the project window to "DR-OpenGL".
5. Build and run.

[DepthReader.zip](https://github.com/google/filament/files/6526906/DepthReader.zip)

**Expected behavior**
I expected a depth buffer display something like what is produced by the Metal target of the project:

**Actual behavior**
I see solid red.

**Screenshots**

*Metal output*
![depth display in Metal](https://user-images.githubusercontent.com/730426/118303623-825c9180-b49a-11eb-8852-0747e70427ce.png)

*OpenGL output*
![depth display in OpenGL](https://user-images.githubusercontent.com/730426/118303815-bf288880-b49a-11eb-98d9-fafa035f95db.png)

**Desktop:**
 - OS: macOS 11.4 Beta (20F5055c)
 - GPU: Radeon Pro 560X 4 GB
 - Backend: OpenGL

**Additional Context:**

Previous discussion #3934

**Comment by romainguy** [comment]
@jwwalker Are you reading from the depth texture in the same pass that you are writing into it? If so, that's an undefined behavior in GL.

**Comment by jwwalker** [comment]
@romainguy The code I posted did this on each frame:

```c++
    if (_renderer->beginFrame( _swapChain ))
    {
		_renderer->render( _renderTargetView );
		_renderer->render( _filaView );
		_renderer->endFrame();
    }
```

Is that what you mean by "same pass"?  But just now I tried changing it to

```c++
    if (_renderer->beginFrame( _swapChain ))
    {
		_renderer->render( _renderTargetView );
		_renderer->endFrame();
    }

    if (_renderer->beginFrame( _swapChain ))
    {
		_renderer->render( _filaView );
		_renderer->endFrame();
    }
```

and the result was the same.

**Comment by romainguy** [comment]
No what I meant is do you read from the depth texture in the same render() call that you write to it. But that doesn't seem to be the case?

@pixelflinger Looks like it might be due to our buffer discarding code then like we discussed over chat.

**Comment by jwwalker** [comment]
@romainguy  Oh, no, not the same render call.  I write to the depth texture when rendering to a `RenderTarget`, and read from it when rendering to an on-screen view.

**Comment by pixelflinger** [comment]
Yes,  so currently we always discard the depth buffer after it's used.
I will see if I can fix that.

**Comment by jwwalker** [comment]
@pixelflinger With this update, the sample project that I attached to this bug crashes, both with Metal and OpenGL.  In `FRenderer::renderJob`, line 325, when it looks at `attachment.texture->getUsage()`, the texture is NULL.

**Comment by pixelflinger** [comment]
> @pixelflinger With this update, the sample project that I attached to this bug crashes, both with Metal and OpenGL.  In `FRenderer::renderJob`, line 325, when it looks at `attachment.texture->getUsage()`, the texture is NULL.

Ah yes. Duh. I'll fix this on Monday. 
I wasn't able to run the project on my Apple Silicon Mac, btw.

**Comment by jwwalker** [comment]
@pixelflinger I've edited the project so it will run on Apple Silicon.

**Comment by pixelflinger** [comment]
> @pixelflinger I've edited the project so it will run on Apple Silicon.

Thank you! I've never used xcode.
