### ISSUE TITLE
Non-uniformly scaled rotated bones don't animate correctly

### ISSUE THREAD

**Issue by seizir** [google/filament#3969]
If a bone with non-uniform scaling is rotated Filament produces a result different from every other renderer I've tested.

Here is a simple model demonstrating the issue: [scaled-rotated.zip](https://github.com/google/filament/files/6488278/scaled-rotated.zip)

This is the model as it appears in Blender (correct)
![image](https://user-images.githubusercontent.com/30301860/118378771-37479900-b5d6-11eb-9c6c-1e891ad89ff4.png)

And this is how it appears in the Filament gltf viewer sample compiled from the current main branch (incorrect)
![image](https://user-images.githubusercontent.com/30301860/118378758-2860e680-b5d6-11eb-8b70-4c127bb52248.png)

Renderers like [Three.js](https://gltf-viewer.donmccurdy.com/) and [Babylon.js](https://sandbox.babylonjs.com/) also produce the expected result.

**Comment by prideout** [comment]
As noted in #3707, Filament does not support shear in the finalized bone matrix (which includes the inverse bind matrix).

In general, shear can be decomposed into (rotation + non_uniform_scale + rotation).
