### ISSUE TITLE
FXAA causes a line of black pixels at top of viewport.

### ISSUE THREAD

**Issue by prideout** [google/filament#397]
I noticed this with Vulkan but I see it with WebGL too, where it's a little more irksome, especially on low DPI displays.

I'm pretty sure this is caused by the post-process pass, because it definitely goes away when I turn off post-processing.

**Comment by romainguy** [comment]
You can see it in GL too on desktop. I think we have a rounding error in the postprocess shader. It's on the right side too sometimes.

**Comment by prideout** [comment]
Renamed the issue. This goes away when I leave postprocessing on, but disable FXAA.

**Comment by prideout** [comment]
Our `PostProcess_AntiAliasing` function uses the `resolution` uniform to compute texel size, which seems to be 800 x 200 in my test case.  However I'm seeing that my actual surface size (allocated by `RenderTargetPool`) is 800 x 224.

I think there are two problems here.  (1) our half-texel offset is slightly wrong; should be 0.5/224.0 rather than 0.5/220.0 and (2) we need to manually clamp our texcoords, because the wrap mode clamps to 1.0 rather than 1.0-24.5/224.0

Per discussion, we will fix this by using `textureSize`.
