### ISSUE TITLE
How to bookmark at specific position

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#3976]
Is there are way to bookmark 3d Model at specific position ? 

Currently i am using below code to set model position 

 manipulator = Manipulator.Builder()
            .targetPosition(0.0f, 0.0f, -4.0f)
            .orbitHomePosition(2.8f, 0.0f, -1.17f)
            .viewport(mySurfaceView.width, mySurfaceView.height)
            .build(Manipulator.Mode.ORBIT)

        engine?.let { engine ->
            manipulator?.let { manip ->
                modelViewer = ModelViewer(mySurfaceView, engine, manip)
            }
        }

now after some points i wants to reset model back to above position. for that i am using bookmark as below

 manipulator?.let {
            val home = it.homeBookmark
            it.jumpToBookmark(home)
        }

jumpToBookmark is working fine, but it repositioned model to its default position, not at customised position which i set using above manipulator code. 

so is there any way to bookmark current position and later i can access that bookmark to reset my model ?

**Comment by romainguy** [comment]
Bookmarks are for the camera, not arbitrary properties of the scene. You would have to implement this yourself.
