### ISSUE TITLE
Unable to load glb model in Android with sceneform using filament

### ISSUE THREAD

**Issue by udayk07** [google/filament#3986]
Hi team, 

Unable to load below attached models in android with filament v1.9.24.  

Model 1:
I tried to load using https://google.github.io/filament/viewer/ and it is loading fine ( But, console showing warning ). Also, materials are missing in viewer.

expected output:
<img width="865" alt="Screenshot 2021-05-18 at 8 38 20 PM" src="https://user-images.githubusercontent.com/78372917/118677182-ad880d80-b819-11eb-8b35-a43d89146276.png">

** In Android studio console found no specific filament logs for this case.

<img width="1428" alt="Screenshot 2021-05-18 at 8 22 14 PM" src="https://user-images.githubusercontent.com/78372917/118673856-f8545600-b816-11eb-9a2f-47fea707e0ca.png">

[castle.zip](https://github.com/google/filament/files/6502198/castle.zip)

Model2:
While loading below model, it is not displaying in both filament-viewer and Android.

<img width="1432" alt="Screenshot 2021-05-18 at 8 28 40 PM" src="https://user-images.githubusercontent.com/78372917/118675122-fb037b00-b817-11eb-858d-b4b43a337461.png">

[car.zip](https://github.com/google/filament/files/6502284/car.zip)

**Comment by romainguy** [comment]
I cannot repro the issue with the first model in the Web viewer. There are no warnings in the console. The second model seems invalid and fails to load in both our Web and native viewers.

**Comment by udayk07** [comment]
Tried once again the first model in Android device ( SAMSUNG S9 device ) ( https://github.com/google/filament/files/6502198/castle.zip ) and another model ( size 60MB ) (https://www.dropbox.com/s/z5q4twlfjwqf96o/kirala.zip?dl=0). Both models failed to load.

In both case found no specific logs in Android Studio console with filament. Attached error logs from console. 

`com.example.augmentedreality/com.example.augmentedreality.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!`

[Console_log.txt](https://github.com/google/filament/files/6502751/Console_log.txt)

**Comment by prideout** [comment]
In a debug build on Desktop, the `car.zip` model triggers an assert in `OpenGLDriver::allocateHandle`. (@pixelflinger)   I'd be surprised if the handle arena is overflowing -- this model has a lot of renderables (7151 meshes) but not a totally crazy number.

**Comment by udayk07** [comment]
@prideout Do we have any workaround to fix this rendering issue for car.zip (https://github.com/google/filament/files/6502284/car.zip) model as it seems to be in valid format while check with gltf-validator ?

**Comment by prideout** [comment]
@udayk07 which tool did you use to generate this glTF?

It might be interesting to see what would happen if you were to combine the meshes to reduce the number of renderables.

**Comment by udayk07** [comment]
@prideout The model generated by three.js exporter ( to load as .glb file in Android ).
<img width="951" alt="Screenshot 2021-05-24 at 9 18 54 PM" src="https://user-images.githubusercontent.com/78372917/119375540-8b3e3600-bcd8-11eb-90ad-41b615f9c369.png">


Will look into combine meshes in this model. Do we have any maximum mesh count in filament ?

**Comment by prideout** [comment]
Our internal handle arena is limited to 2 MB which should be plenty.  To be honest my mesh reduction idea is just an experiment to see what will happen, since I don't understand this bug yet.  (note however that your model will be more optimal if you reduce the mesh count)

**Comment by udayk07** [comment]
@prideout Tried to combine meshes for car.zip model. Found below results, 
1. [car_partial_meshjoin.glb.zip](https://github.com/google/filament/files/6534005/car_partial_meshjoin.glb.zip)  -> combined only few meshes in this model (total mesh count 4965) which is not loading in Android device and filament viewer also ( original mesh count 7151 )

2.  [car_high_meshjoin.glb.zip](https://github.com/google/filament/files/6534012/car_high_meshjoin.glb.zip) -> Combined almost all meshes in this which is loading fine in Android device ( total mesh count 258 )

Even though above one with 258 meshes loads fine, the model https://github.com/google/filament/files/6502198/castle.zip with only 5 meshes not loading in Android ( found no filament logs in console also )

**Comment by prideout** [comment]
Thanks, that is interesting.  I haven't had time to investigate yet, so I'm not sure if this is an actual bug or if a resource limit has been exceeded, either way we should probably try to emit better error messages.

@pixelflinger these models might be good stress tests, not sure how they compare to bistro and sponza

**Comment by pixelflinger** [comment]
So `car.zip` seems to be invalid. At least, our `ResourceLoader` asserts with a problem where there are no triangles when processing tangents. 

The model also uses more memory than we set by default, thankfully, we have compile time configuration flags you can set. It seems that you need to:
- increase `FILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB` -- but I'm not sure to what value yet. Maybe try 8 MB.
- increase `FILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB` to 4MB

Finally there is another problem where we're running out of jobs, I have a [PR](https://github.com/google/filament/pull/4032) that fixes that.

Because of the 1st problem, I wasn't able to load this model.

**Comment by udayk07** [comment]
@pixelflinger 

I am using filament in Android app through maven dependency ( implementation 'com.google.android.filament:filament-android:1.10.0' ).

Is it possible to set above mentioned flags in Android build ?

**Comment by pixelflinger** [comment]
Ah no not yet. It's on my to-do list to make them settable at runtime.

I'm also working on some changes that will make this car work better.


So that said, such a model won't run well, due to the overhead of referring very small geometry with a lot of calls. On my desktop computer, I can't even get good performance.

It's important to group meshes together that are close from each other and of similar size and of same material.

**Comment by udayk07** [comment]
Will there be any update on memory size change option to resolve rendering issue ? 
<img width="1440" alt="Screenshot 2021-06-21 at 10 50 06 PM" src="https://user-images.githubusercontent.com/78372917/122802973-ae620280-d2e3-11eb-9ea2-f678ae2bf236.png">

**Comment by prideout** [comment]
Yes, thanks for the reminder: I think @pixelflinger and I have discussed increasing this constant for the WebGL build only, because the WebGL build is more likely to be used as a generic viewer.  For Android builds, we probably want to avoid increasing this limit.

**Comment by prideout** [comment]
The handle limit has been increased via #4201.

**Comment by udayk07** [comment]
Thanks for the help.

It seems the changes available in version 1.10.5. But, the android version 1.10.5 not available ( Could not find com.google.android.filament:filament-android:1.10.5 )

**Comment by udayk07** [comment]
@prideout  @pixelflinger 

Tried to load car.zip with latest filament update 1.10.6 and facing same crash issue.

Have added crash logs 
[filament_crash_log.txt](https://github.com/google/filament/files/6784293/filament_crash_log.txt)

Thnx for ur effort.
