### ISSUE TITLE
Provide a Gltf View for jetpack compose

### ISSUE THREAD

**Issue by Ditscheridou** [google/filament#3997]
**Is your feature request related to a problem? Please describe.**
Im currently developing an application where i need to display a gltf file. Currently i have to do some workarounds to achieve this

**Describe the solution you'd like**
It would be nice if the project provides for example a `GltfView(model="myModel")` where you simple could load and display it inside your compose view structure.

**Describe alternatives you've considered**
The alternative is, to use Compose interop between the "old way" like defining a fragment and the new way. 

**OS and backend**
This is Android specific because of the nature of the compose framework.

**Comment by romainguy** [comment]
I wrote a sample app that shows exactly how to do this: https://github.com/romainguy/sample-materials-shop

You don't need a fragment, you just need an `AndroidView` to wrap a `SurfaceView`.

**Comment by Ditscheridou** [comment]
Thanks for your hint! Works pretty well so far :) i will make a pr on your sample project for upgrading to the latest beta compose version
