### ISSUE TITLE
Cmake error following Windows Android instructions.

### ISSUE THREAD

**Issue by griffin2000** [google/filament#3999]
Are the Android Windows instructions up to date?  When I follow them and run this command:

```
cmake ^
    -G Ninja ^
    -DCMAKE_INSTALL_PREFIX=..\release\filament ^
    -DFILAMENT_ENABLE_JAVA=NO ^
    -DCMAKE_BUILD_TYPE=Release ^
    ..\..
```

Then I get this error:
```

CMake Error at CMakeLists.txt:211 (message):
  Building with Clang on Windows is no longer supported.  Use MSVC 2019
  instead.
```
Is there a step required to get CMake on Windows to use MSVC not Clang, for the Ninja generator?
```
-- The C compiler identification is Clang 12.0.0 with GNU-like command-line  
```

**Comment by romainguy** [comment]
@bejado

**Comment by bejado** [comment]
Are you running the commands inside a "Visual Studio x64 Native Tools Command Prompt for VS 2019"? Make sure `cl.exe` is on your path.

You could also try adding the following flags to the CMake invocation:
```
-DCMAKE_C_COMPILER="cl.exe" -DCMAKE_CXX_COMPILER="cl.exe"
```

**Comment by griffin2000** [comment]
Ah yes, my bad @bejado, that was the issue (confused as regular Cmake-generated MSVC does not need to be run from VS command prompt, but I guess Ninja does?)

**Comment by bejado** [comment]
At least with my environment, commands must always be run from the VS command prompt in order for the toolchain to be visible to CMake.
