### ISSUE TITLE
Changing .png textures on GLTF, textures not appearing

### ISSUE THREAD

**Issue by muizamhailey004** [google/filament#4000]
I'm rendering a gltf model which has many entities. I'm working on an AR app where I would want to change the .png textures. The problem is, the textures are not appearing, and the model is just appearing plain. I tried to change the texture with this:

I'm very new to filament and ARcore. Help would be appreciated. Here's the full code.

`init {
        coroutineScope.launch {

            val filamentAsset =
                    withContext(Dispatchers.IO) {
                        @Suppress("BlockingMethodInNonBlockingContext")
                        context.assets
                                .open("joochiat_ease/joochiat_ease.gltf")
                                .use { input ->
                                    val bytes = ByteArray(input.available())
                                    input.read(bytes)
                                    filament.assetLoader.createAssetFromJson(ByteBuffer.wrap(bytes))!!
                                }

                    }

                            val resourceLoader = ResourceLoader(filament.engine)
                            for (uri in filamentAsset.resourceUris){
                                val buffer = loadResource(uri,context)
                                resourceLoader.addResourceData(uri,buffer)
                            }

                            resourceLoader.loadResources(filamentAsset)
                            resourceLoader.destroy()
                            filamentAsset.releaseSourceData()

            materialInstance = material2.createInstance()
            baseColor = loadTexture(filament.engine, context.resources, R.drawable.wall_tex_at, TextureType.COLOR)
            normal = loadTexture(filament.engine, context.resources,R.drawable.wall_tex_n,TextureType.NORMAL)
            ao = loadTexture(filament.engine, context.resources,R.drawable.wall_tex_ao,TextureType.DATA)
            roughnessMetallic = loadTexture(filament.engine, context.resources,R.drawable.wall_tex_ms,TextureType.DATA)
            val rm = filament.engine.renderableManager
            val sampler = TextureSampler()
            sampler.anisotropy = 8.0f
            for (entity in filamentAsset.entities) {
                            println("name ${filamentAsset.getName(entity)}")
                                val renderable = rm.getInstance(entity)
                                if (filamentAsset.getName(entity) == "wall") {
                                    if (renderable == 0) {
                                        continue
                                    }
                                    val material = rm.getMaterialInstanceAt(renderable, 0)
                                    material.setParameter("baseColorIndex",0)
                                    material.setParameter("baseColorMap",baseColor,sampler)
                                    material.setParameter("normalMap",normal,sampler)
                                    material.setParameter("occlusionMap",ao,sampler)
                                    material.setParameter("metallicRoughnessMap",roughnessMetallic,sampler)
                                }
        }`

I iterated over filamentAsset to get the entity which I want to add the textures on(wall). My .png texture files are placed in drawable-nodpi folder.

**Comment by prideout** [comment]
You're probably using ubershader mode if you're on Android, so this should be possible if the original glTF includes texture coordinates and a standard metallic-roughness material.

Your code looks correct at first glance, maybe my colleagues will spot something.  Have you confirmed that the `setParameter` codelines are indeed being executed?  If the original model does not have any textures specified, you will also need to do:

material.setParameter("normalIndex",0)
material.setParameter("metallicRoughnessIndex",0)
material.setParameter("aoIndex",0)

You are modifying only the first primitive in the wall renderable, which is fine, unless it has multiple primitives.

**Comment by prideout** [comment]
@muizamhailey004 were you able to narrow this down?

**Comment by muizamhailey004** [comment]
Sorry for the late update. Yes, fortunately I was able to narrow it down. However, another problem arises. I am able to render the textures to the wall, but the color of the original .gltf model without texture still retains behind the texture.

Color of original .gltf wall:
<img width="1045" alt="Screenshot 2021-05-27 at 5 15 30 PM" src="https://user-images.githubusercontent.com/84392941/119800069-3f290680-bf0f-11eb-8258-541c4fc0069f.png">

Expected wall after applying textures:
![photo6080298189660990697](https://user-images.githubusercontent.com/84392941/119800774-aba40580-bf0f-11eb-8a36-5073aa7f6de9.jpg)

What I encountered:
![Screenshot_20210527-172010_Example App](https://user-images.githubusercontent.com/84392941/119801047-e86ffc80-bf0f-11eb-941c-7cdfbf4871cf.jpg)

**Comment by muizamhailey004** [comment]
After some troubleshooting, I realized that the normal map is causing the problem. Without the normal map, the color is fine, just that it's missing the bumps. When I add the normal map, it gives the entire texture some sort of translucency in such a way that the color of the .gltf model can be seen. Any ideas?

**Comment by romainguy** [comment]
@prideout Doesn't glTF calls for the base color factor to multiply any base color texture? If so the result is not surprising

**Comment by prideout** [comment]
I like Romain's theory, you can do `setParameter("baseColorFactor", float4(1))` to test it out.  I don't understand the result of the normal map experiment though, interesting...

**Comment by romainguy** [comment]
Checking the ubershader, the base color shouldn't be affected by the normal map:

```
        material.baseColor = materialParams.baseColorFactor;

        if (materialParams.baseColorIndex > -1) {
            highp float2 uv = uvs[materialParams.baseColorIndex];
            uv = (vec3(uv, 1.0) * materialParams.baseColorUvMatrix).xy;
            material.baseColor *= texture(materialParams_baseColorMap, uv);
        }

        #if defined(BLEND_MODE_TRANSPARENT)
            material.baseColor.rgb *= material.baseColor.a;
        #endif

        material.baseColor *= getColor();
```

Interestingly, the vertex colors may also affect the final base color.

**Comment by prideout** [comment]
@muizamhailey004 have you had any luck with this issue?

**Comment by muizamhailey004** [comment]
Yes! I realised that the issue lies on the .gltf model itself not being exported correctly. I'm able to apply textures correctly now. Thanks for the swift responses! Appreciate it.
