### ISSUE TITLE
`Fragment Function(blitterFrag): Shader reads texture (sourceColor[0]) whose usage (0x04) doesn't specify MTLTextureUsageShaderRead (0x01)'

### ISSUE THREAD

**Issue by IceCreamWu** [google/filament#4003]
I want to readPixels with backend of MetalDriver, but I get the error as the title. I find source.color in MetalBlitter::BlitArgs is get from MetalRenderTarget::getDrawColorAttachment(size_t index), and inner it from MetalSwapChain::acquireDrawable(), and it from [CAMetalLayer nextDrawable].texture, but this texture typically be used to create an MTLRenderTargetDescriptor. Is it a bug?

 - OS:  iOS
 - Device: iPhone 12 with iOS 14.2 
 - Backend: Metal

**Comment by bejado** [comment]
If you're trying to read pixels from a SwapChain, then you need to ensure that you pass the `SwapChain::CONFIG_READABLE` flag to `createSwapChain`:

```
swapChain = engine->createSwapChain(layer, SwapChain::CONFIG_READABLE)
```
