### ISSUE TITLE
lightbulb sample crash with args "-m -a vulkan"

### ISSUE THREAD

**Issue by dex1990** [google/filament#4014]
**Describe the bug**
When i run lightbulb sample with args "-m -a vulkan", application crashed with output log :

VULKAN ERROR: (VUID-vkQueuePresentKHR-pWaitSemaphores-03268) Validation Error: [ VUID-vkQueuePresentKHR-pWaitSemaphores-03268 ] Object 0: handle = 0x225c05e9078, type = VK_OBJECT_TYPE_QUEUE; Object 1: handle = 0x68d1dd0000000007, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x251f8f7a | vkQueuePresentKHR: Queue VkQueue 0x225c05e9078[] is waiting on pWaitSemaphores[0] (VkSemaphore 0x68d1dd0000000007[]) that has no way to be signaled. The Vulkan spec states: All elements of the pWaitSemaphores member of pPresentInfo must reference a semaphore signal operation that has been submitted for execution and any semaphore signal operations on which it depends (if any) must have also been submitted for execution (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-vkQueuePresentKHR-pWaitSemaphores-03268)

it`s ok with args "-a vulkan".

**To Reproduce**
 ./lightbulb.exe -m -a vulkan /d/filament-main/filament-main/assets/models/monkey/monkey.obj

**Desktop (please complete the following information):**
 - OS: [e.g. windows ]
 - GPU: [e.g. NVIDIA RTX 3090]
 - Backend: [Vulkan]

**Comment by dex1990** [comment]
> MoltenVK

I also used the latest LunarG SDK(1.2.176.1).
![image](https://user-images.githubusercontent.com/2503734/119600358-7917e100-be19-11eb-9d09-9ebb6c5d26d0.png)
I built Filament myself with the latest source code, as you can see.
![image](https://user-images.githubusercontent.com/2503734/119600542-d6ac2d80-be19-11eb-95ce-97ce154bc4e3.png)

**Comment by dex1990** [comment]
> I cannot reproduce with MoltenVK and the validation layers in the latest LunarG SDK, screenshot attached.
> 
> Note that we recently rewrote our command buffer manager, were you using a fairly recent build?
> 
> <img alt="Screen Shot 2021-05-25 at 10 58 36 AM" width="1545" src="https://user-images.githubusercontent.com/1288904/119545973-3fc37080-bd48-11eb-89a3-d33863c35abd.png">

I built filament myself with recent source code. I also use the latest LunarG SDK(1.2.176.1)

**Comment by prideout** [comment]
Got it.  I'll give this a try on my NVIDIA machine.  Thanks for the bug report!

**Comment by prideout** [comment]
I have a repro with NVIDIA RTX 2060 + Windows 10.  Investigating.

**Comment by prideout** [comment]
This is due to VK_DEVICE_LOST which would be impossible to handle robustly, but hopefully we can prevent it from happening in the first place.  I think the next step is to root cause it using `NV_device_diagnostic_checkpoints` so I'll play around with that.

**Comment by prideout** [comment]
Update: DEVICE_LOST is still occurring with NVIDIA hardware, even after recent pipeline barrier fixes.  This is triggered only by froxelization.  (!)  This is _not_ triggered by any of our post-processing features.

**Comment by prideout** [comment]
DEVICE_LOST goes away by hacking `evaluatePunctualLights` in the fragment shader and commenting out the call to `shadow(...)`.

Pretty sure this is a driver bug at this point.

**Comment by romainguy** [comment]
@prideout So sounds like we are basically crashing the driver/GPU?

**Comment by prideout** [comment]
Correct, the Windows Event Viewer says "Display driver nvlddmkm stopped responding and has successfully recovered."

Another workaround is to replace `light.shadowIndex` with zero, so I should double check that we're populating the UBO correctly.
