### ISSUE TITLE
Introduce Quaternion support

### ISSUE THREAD

**Issue by Ditscheridou** [google/filament#4022]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to use Quaternions to avoid angle problems, that you get with euler angles. Since the normal matrix support is pretty neat, it would be nice to enhance this with quaternions.  

**Describe the solution you'd like**
For the android project: Add extension functions (or functions to the Matrix class) to calculate with Quaternions and convert e.g. between a quaternion and a rotation matrix and vice versa. 

**Describe alternatives you've considered**
The alternative would be that everyone implement it by itself, but that cant be the goal.

**Comment by romainguy** [comment]
Are you talking about the APIs that are part of the filament-utils-android library?

**Comment by Ditscheridou** [comment]
Yes!

**Comment by romainguy** [comment]
Quaternions are now available.
