### ISSUE TITLE
How to custom a YUV texture downloader

### ISSUE THREAD

**Issue by FinleyPan** [google/filament#4024]
I use `readPixels` to read the rendered result back to host memory with `PixelDataFormat::RGBA`, everything goes well. My question is it possible to convert the resultant rendered texture from `RGBA` to `YUV`(e.g. NV12) in the material file(.mat)? I know how to do it with opengl fragment shader, but don't know whether it can be achieved with filament supported features or any customizable post-pocessing modules?

**Comment by romainguy** [comment]
You could easily output interleaved YUV but NV12 is one Y plane and a UV plane with U and V interleaved. You won't be able to achieve this with a fragment shader. BTW please open a discussion instead of an issue for this kind of question, thanks!
