### ISSUE TITLE
Triangle Tutorial is not working after changing to Filament v1.10.0

### ISSUE THREAD

**Issue by cx20** [google/filament#4027]
**Describe the bug**
[Triangle Tutorial](https://google.github.io/filament/webgl/tutorial_triangle.html) is not working after `v1.10.0` is released.
This is probably due to the [material breakage](https://github.com/google/filament/releases/tag/v1.10.0) in Filament, as described in the release notes. I think it needs to be rebuilt.

**To Reproduce**
1. Go to Filament's Triangle Tutorial page
https://google.github.io/filament/webgl/tutorial_triangle.html

The following error is displayed on the console.
```javascript
filament.js:9 
in filament::MaterialParser *filament::createParser(filament::backend::Backend, const void *, size_t):69

filament.js:9 
reason: Material version mismatch. Expected 11 but received 10.

filament.js:9 
Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (https://unpkg.com/filament/filament.js:9:10953)
    at _abort (https://unpkg.com/filament/filament.js:9:112511)
    at https://unpkg.com/filament@1.10.0/filament.wasm:wasm-function[243]:0x9bcb
    at https://unpkg.com/filament@1.10.0/filament.wasm:wasm-function[271]:0xcbd3
    at https://unpkg.com/filament@1.10.0/filament.wasm:wasm-function[1686]:0x1006cb
    at https://unpkg.com/filament@1.10.0/filament.wasm:wasm-function[1038]:0x980b7
    at Engine$_createMaterial [as _createMaterial] (eval at new_ (https://unpkg.com/filament/filament.js:9:90896), <anonymous>:9:10)
    at Engine.Filament.Engine.createMaterial (https://unpkg.com/filament/filament.js:247:29)
    at new App (https://google.github.io/filament/webgl/tutorial_triangle.js:31:24)
    at https://google.github.io/filament/webgl/tutorial_triangle.js:83:16
```

**Expected behavior**
It is expected that the triangle will be displayed without any error.

**Screenshots**
The canvas is black and nothing is displayed

**Desktop (please complete the following information):**
 - OS: Windows 10 + Chrome 90.0.4430.212 
 - GPU: NVIDIA GTX RTX 2060
 - Backend: WebGL(ANGLE)

**Additional context**
The same error appears in the console in Firefox.

**Comment by prideout** [comment]
Gah, thank you for the bug report!  Will fix ASAP.
