### ISSUE TITLE
Mint/Ubuntu: __cxxabi_config.h not found

### ISSUE THREAD

**Issue by Chainfire** [google/filament#403]
On my fully upgraded Mint 18 install (Ubuntu Xenial based), the following error occurs when trying to build:

`/usr/include/c++/v1/cxxabi.h:21:10: fatal error: '__cxxabi_config.h' file not found`

Adding `-DFILAMENT_REQUIRES_CXXABI=true` did not help, but adding CXXFLAGS did:

`CC=/usr/bin/clang CXX=/usr/bin/clang++ CXXFLAGS=-isystem\ /usr/include/libcxxabi cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release/filament ../..`

Perhaps this could be added to the documentation or easy build script.

**Comment by romainguy** [comment]
Thanks for the report. I'd like to understand why an extra include flag is required on Mint.

**Comment by Chainfire** [comment]
I think it may have something to do with the default version of libc++-dev (3.7.0-1ubuntu0.1) on this distro. Other references to this issue also state this specific version.

If you need any specific information from my install, let me know.

**Comment by romainguy** [comment]
Does Filament compile with the default libc++-dev that's preinstalled?

**Comment by romainguy** [comment]
Thanks. I'm surprised `-stdlib=libc++` is needed since that's what we use in our CMake files.

**Comment by Chainfire** [comment]
Just checked again and you are of course correct - it's just `LDFLAGS="-lc++"`  that is needed to fix compilation.
