### ISSUE TITLE
ktx::createTexture doesn't respect sRGB option for compressed textures

### ISSUE THREAD

**Issue by bejado** [google/filament#4037]
I'm trying to ASTC encode a  ktx image and load it as an sRGB texture.

```
mipgen -f ktx -c astc_fast_ldr_4x4 -m 1 srgb_image.png out.ktx

auto buffer = readFile(out.ktx);
auto albedo = new KtxBundle(buffer.data(), buffer.size());
auto tex = ktx::createTexture(mEngine, albedo, true /* srgb */);
```

The result texture has a format of `RGBA_ASTC_4x4`, but I would expect the format to instead be `SRGB8_ALPHA8_ASTC_4x4`.

I think this block should be expanded to also support compressed texture formats:

```
// KtxUtility.h

if (srgb) {
    if (texformat == Texture::InternalFormat::RGB8) {
        texformat = Texture::InternalFormat::SRGB8;
    }
    if (texformat == Texture::InternalFormat::RGBA8) {
        texformat = Texture::InternalFormat::SRGB8_A8;
    }
}
```

If that sounds correct, I can make the change.

**Comment by romainguy** [comment]
That looks right to me but @prideout should double check.
