### ISSUE TITLE
RenderTarget.AttachmentPoint in java does not match with the cpp side struct

### ISSUE THREAD

**Issue by geroge-d** [google/filament#4055]
hi 
  RenderTarget.AttachmentPoint  in java  doesn't match with the cpp enum AttachmentPoint

**Comment by pixelflinger** [comment]
I think the jni code takes care of that. Does it cause an actual problem?

I think the mismatch is because we added values and didn't want to break the java API.

**Comment by geroge-d** [comment]
This mismatch will cause problem on creating offline render target with depth buffer

**Comment by romainguy** [comment]
@pixelflinger I just checked and we don't do any remapping in the JNI layer. This means the value for `DEPTH` is indeed broken.

**Comment by pixelflinger** [comment]
Ah ok. Good one.
