### ISSUE TITLE
Cannot reach KtxLoader after update to 1.10.1

### ISSUE THREAD

**Issue by grigorij2503** [google/filament#4070]
**Describe the bug**
We are getting _Unresolved reference: KtxLoader_ message after updating filament libs to 1.10.1
After downgrading only filament-utils-android to 1.10.0 - everything is ok

**To Reproduce**
1. import com.google.android.filament:filament-utils-android:1.10.1
2. compileDebugKotlin shows Unresolved reference: KtxLoader

**Expected behavior**
Application should compile

**Comment by romainguy** [comment]
`KtxLoader` was renamed `KTXLoader` to be more consistent with other APIs.
