### ISSUE TITLE
glTFio MaterialProvider constructor implementation not found

### ISSUE THREAD

**Issue by Botyto** [google/filament#4080]
**Description**
When constructing a MaterialProvider in Java, an error occurs:
No implementation found for long com.google.android.filament.gltfio.MaterialProvider.nCreateMaterialProvider(long) (tried Java_com_google_android_filament_gltfio_MaterialProvider_nCreateMaterialProvider and Java_com_google_android_filament_gltfio_MaterialProvider_nCreateMaterialProvider__J)
I haven't had this issue with the rest of the filament library I've tried.

**To Reproduce**
1. Create a new Android studio project
2. Download the released .aar files (all of them) and add them to the project
3. Construct a new MaterialProvider object

**Desktop**
 - OS: Windows 10
 - Backend: OpenGL

**Smartphone**
 - Device: Pixel 3a emulator
 - OS: Android 11

**Comment by romainguy** [comment]
`Java_com_google_android_filament_gltfio_MaterialProvider_nCreateMaterialProvider` is present, did you properly initialize the library? Make sure you call `com.google.android.filament.utils.Utils.init()` to initialize gltfio *and* Filament.
