### ISSUE TITLE
TRANSLUCENT display incorrect.

### ISSUE THREAD

**Issue by dsafa22** [google/filament#4084]
use android sample:sample-gltf-viewer
I need an image of the model with a transparent background.
So,I change the code like this.

In MainActivity.kt:
do not use sky box
```
//        readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx").let {
//            scene.skybox = KtxLoader.createSkybox(engine, it)
//        }
```

The first situation:
In ModelViewer.kt:
```
val opt = Renderer.ClearOptions()
opt.clear = true
opt.clearColor = floatArrayOf(1.0f, 1.0f, 0.0f, 0.0f)
renderer.clearOptions = opt

view.blendMode = View.BlendMode.OPAQUE
```
The result is right.
![13E0F696A390474DDB9BC692727316F4](https://user-images.githubusercontent.com/8586217/120657732-56d83000-c4b7-11eb-91b9-55138b2f1bf6.jpg)

The second situation:
In ModelViewer.kt:
```
val opt = Renderer.ClearOptions()
opt.clear = true
opt.clearColor = floatArrayOf(1.0f, 1.0f, 0.0f, 0.0f)
renderer.clearOptions = opt

view.blendMode = View.BlendMode.TRANSLUCENT
```
The result is not right.

![2C8F718F46FB0CB217835BC5BFEB3D76](https://user-images.githubusercontent.com/8586217/120657744-5b9ce400-c4b7-11eb-927c-a41c28497bc2.jpg)

This is the model.
[role_boy.glb.zip](https://github.com/google/filament/files/6596877/role_boy.glb.zip)

BTW,opengles and vulkan are both not correct.

**Comment by romainguy** [comment]
The easiest way to do this is to set !opaque on `UiHelper`. Also, if you are using a `SurfaceView` you'll need to change the Z order of the `Surface` (which `UiHelper` will do for you) or use a `TextureView`. `sample-transparent-view` shows this.

**Comment by dsafa22** [comment]
> The easiest way to do this is to set !opaque on `UiHelper`. Also, if you are using a `SurfaceView` you'll need to change the Z order of the `Surface` (which `UiHelper` will do for you) or use a `TextureView`. `sample-transparent-view` shows this.

I tried `sample-transparent-view`, the same problem.
