### ISSUE TITLE
RenderTarget crashes with transparent material

### ISSUE THREAD

**Issue by ast3rX** [google/filament#4085]
**Describe the bug**
RenderTarget crashes when there is transparent material in the scene.

**To Reproduce**
1. Add the following lines to aiDefaultMat.mat - which is applied to the object in the rendertarget example application.

```
    refractionType : solid,
    refractionMode : screenspace,
```
2. Try running the recompiled rendertarget example which will crash immediately:
```
in void filament::backend::metal::MetalDriver::createRenderTargetR(Handle<filament::backend::HwRenderTarget>, filament::backend::TargetBufferFlags, uint32_t, uint32_t, uint8_t, backend::MRT, filament::backend::TargetBufferInfo, filament::backend::TargetBufferInfo):273
reason: The COLOR0 flag was specified, but no color texture provided.
```

**Expected behavior**
No crash with transparent materials when using render targets.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Backend: OpenGL/Metal

**Comment by romainguy** [comment]
Which version of Filament are you using?

**Comment by ast3rX** [comment]
The latest `main` branch version.

**Comment by romainguy** [comment]
@prideout I can repro the error. Can you think of any reason why the rendertarget samples would crash when a material uses transmission/refraction?

**Comment by prideout** [comment]
Interesting, it isn't obvious to me what's going on.  Could be a framegraph issue in the refraction codepath (`FRenderer::refractionPass`).

**Comment by romainguy** [comment]
Seems like it, but I'm not sure what's different about a `RenderTarget`. We always render to an FBO anyways so it should be the same. @pixelflinger any idea?

**Comment by pixelflinger** [comment]
So this is exposing a more serious bug in the FrameGraph, where basically we'll always fail in this manner if post processing is disabled.

This is because when post-processing is disabled, the FrameGraph realizes that it doesn't have to allocate a new buffer for the main pass. However, in the case of transmission we have to blit from there to a temporary buffer. The blitting fails because the rendertarget is "imported" into the framegraph, which takes a different path.  

This is going to take a bit of time to untangle. Meanwhile, if this is causing a problem in real code, it can be worked around by not disabling the post processing (instead you can disable every feature in it).

**Comment by ast3rX** [comment]
Previously, disabling post processing came up to remove the noticable color shift in the texture:
https://github.com/google/filament/discussions/3402#discussioncomment-338512

I haven't been able to achieve the same without setting the flag. In the Renderer `colorGrading` is directly driven by `hasPostProcess`:
https://github.com/google/filament/blob/786eee4eb97def286ce04b1c3e4be67d02866d31/filament/src/Renderer.cpp#L229

**Comment by romainguy** [comment]
You can set the color grading’s tonemap to LINEAR to do what you want.

**Comment by ast3rX** [comment]
I did that but the mirror is a lot brighter.

```
        //app.offscreenView->setPostProcessingEnabled(false);
        app.colorGrading = ColorGrading::Builder()
                    .toneMapping(ColorGrading::ToneMapping::LINEAR)
                    .build(*engine);
        app.offscreenView->setColorGrading(app.colorGrading);
```

**Comment by romainguy** [comment]
Ah yeah you want a way to turn off the transfer function. We could add that.

**Comment by ast3rX** [comment]
I turned off `colorGrading` with a new setting in the Renderer which solves the issue. However, the render target's depth attachment will contain unexpected (empty?) data in case post processing is NOT disabled. It is related to `fxaa` being enabled. If I disable `fxaa` then the refractive material scene will crash the same way, so I assume the depth issue is related as well. @pixelflinger , is there a workaround to fix this?

**Comment by pixelflinger** [comment]
Actually, when you disable enough stuff, we fall into the same bug, which leads to the same crash.

For the depth to be preserved, it needs to have the sampleable bit set, but we haven't tested that path very well yet.

**Comment by ast3rX** [comment]
The bit is properly set:
`        .usage(Texture::Usage::DEPTH_ATTACHMENT | Texture::Usage::SAMPLEABLE)
`
The rendertarget sample defines the depth attachment but I don't think it's used at the moment.
