### ISSUE TITLE
TRANSLUCENT display incorrect.(use method in sample-transparent-view)

### ISSUE THREAD

**Issue by dsafa22** [google/filament#4087]
#4084 
use android sample:`sample-gltf-viewer`
In `ModelViewer.kt`, use the method in `sample-transparent-view`,the code changed as blow(no other code change)  
in`SurfaceCallback` :

```
swapChain = engine.createSwapChain(surface, SwapChain.CONFIG_TRANSPARENT)
```
In MainActivity.kt:
do not use sky box
```
//        readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx").let {
//            scene.skybox = KtxLoader.createSkybox(engine, it)
//        }
```

and I set the view background `#0f0` in layout 
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/simple_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="#f00">
....
```

It show as blow
![82A3A8D45C5BDD87B8CE060A81BDA658](https://user-images.githubusercontent.com/8586217/120877357-acf8c080-c5e8-11eb-86fb-9ebdab17c1af.jpg)

not right.

**Comment by romainguy** [comment]
What's not right? The background is set to red and visible through the 3D view. What issue are you reporting?

**Comment by dsafa22** [comment]
> What's not right? The background is set to red and visible through the 3D view. What issue are you reporting?

The face is missing some part.

**Comment by dsafa22** [comment]
<img width="313" alt="截屏2021-06-05 13 45 14" src="https://user-images.githubusercontent.com/8586217/120881542-631dd380-c604-11eb-87ac-dcd345d888c3.png">
<img width="306" alt="18CB8970-6118-4670-9710-1CA8EAF3A9B8" src="https://user-images.githubusercontent.com/8586217/120881543-64e79700-c604-11eb-8620-ad7b3766c771.png">

**Comment by pixelflinger** [comment]
Is the face okay when you're NOT setting the view to transparent?

**Comment by romainguy** [comment]
Could you share the glTF file you are loading please?

**Comment by dsafa22** [comment]
debug in metal.

after colorGrading, the texture begin not right.
<img width="1095" alt="2D4FCBB6-961C-4BAA-80EA-038DDE02C8A4" src="https://user-images.githubusercontent.com/8586217/120881664-4df57480-c605-11eb-9bf6-c251e1f2b111.png">
<img width="1266" alt="B469F754-FC90-4404-81A0-6A4CAEEDE21E" src="https://user-images.githubusercontent.com/8586217/120881666-52219200-c605-11eb-814b-9241de64dc09.png">

**Comment by dsafa22** [comment]
> Could you share the glTF file you are loading please?

https://github.com/google/filament/issues/4084

**Comment by dsafa22** [comment]
the missing part same as the face node exceed the hair node.
<img width="839" alt="F458687C-C029-490A-A6E7-6EB18BC8E248" src="https://user-images.githubusercontent.com/8586217/120881807-539f8a00-c606-11eb-9d9a-c9cb0f22bb51.png">
<img width="833" alt="91FD3A42-DCD2-4AEE-9D2A-170EC4F4C2D2" src="https://user-images.githubusercontent.com/8586217/120881820-6d40d180-c606-11eb-827e-1f37d391d9f5.png">

**Comment by dsafa22** [comment]
> Is the face okay when you're NOT setting the view to transparent?

Yes, it is OK when not set transparent.

**Comment by romainguy** [comment]
How did you modify gltf_viewer? When I remove the skybox and set the swap chain to transparent, everything renders properly:

<img width="1136" alt="Screen Shot 2021-06-04 at 11 04 44 PM" src="https://user-images.githubusercontent.com/869684/120881901-42fcfe80-c589-11eb-99a0-bcf9d2fbbe2d.png">

**Comment by dsafa22** [comment]
> How did you modify gltf_viewer? When I remove the skybox and set the swap chain to transparent, everything renders properly:
> 
> <img alt="Screen Shot 2021-06-04 at 11 04 44 PM" width="1136" src="https://user-images.githubusercontent.com/869684/120881901-42fcfe80-c589-11eb-99a0-bcf9d2fbbe2d.png">

<img width="616" alt="F837CAE8-AFB6-4FBA-AEE2-9FD35A7F2BE2" src="https://user-images.githubusercontent.com/8586217/120882083-120fde80-c608-11eb-9dcb-24cf987bfb7b.png">
```
dest->setBlendMode(View::BlendMode::TRANSLUCENT);
```

**Comment by romainguy** [comment]
Ah I was able to repro. There's no need to set the swap chain to use `CONFIG_FLAG_TRANSPARENT`. What triggers the bug is setting the `View`'s blend mode to `TRANSLUCENT`:

```
view->setBlendMode(View::BlendMode::TRANSLUCENT);
```

**Comment by romainguy** [comment]
@pixelflinger I forgot, is the app supposed to set the `ClearOptions` in this case? It looks like we're not properly clearing the depth buffer (or depth test is still incorrectly enabled).

**Comment by dsafa22** [comment]
> Ah I was able to repro. There's no need to set the swap chain to use `CONFIG_FLAG_TRANSPARENT`. What triggers the bug is setting the `View`'s blend mode to `TRANSLUCENT`:
> 
> ```
> view->setBlendMode(View::BlendMode::TRANSLUCENT);
> ```

yes, very smart!

**Comment by romainguy** [comment]
@pixelflinger I found the bug. It's caused by this line in the post processing material:

```
color.rgb /= color.a + FLT_EPS;
```

I'm not sure why it causes the problem yet. But it's fine when returning just before and it's broken when returning right after. I imagine we have bad values in color.a.

**Comment by romainguy** [comment]
Alright I found the issue. The problem is *the asset*. The face uses alpha masking with an alpha value that comes from the face texture. And the alpha channel of said texture looks like this:

<img width="692" alt="Screen Shot 2021-06-04 at 11 51 09 PM" src="https://user-images.githubusercontent.com/869684/120883035-cfaabb00-c58f-11eb-9d48-ed6c56943441.png">

So what's happening is that in "view transparent" mode the alpha of the alpha masking is used to blend and we correctly interpret it and the model disappears. The bug doesn't appear in opaque mode because we disable blending so all pixels are treated as alpha=1.

Please disable alpha masking on the face, it'll fix your issue and improve rendering performance.

**Comment by dsafa22** [comment]
> Alright I found the issue. The problem is _the asset_. The face uses alpha masking with an alpha value that comes from the face texture. And the alpha channel of said texture looks like this:
> 
> <img alt="Screen Shot 2021-06-04 at 11 51 09 PM" width="692" src="https://user-images.githubusercontent.com/869684/120883035-cfaabb00-c58f-11eb-9d48-ed6c56943441.png">
> 
> So what's happening is that in "view transparent" mode the alpha of the alpha masking is used to blend and we correctly interpret it and the model disappears. The bug doesn't appear in opaque mode because we disable blending so all pixels are treated as alpha=1.
> 
> Please disable alpha masking on the face, it'll fix your issue and improve rendering performance.

Yes, I also suspect that this model has a problem, because other models don't have this problem. I'll try to modify it. Thank you.

**Comment by ShoutTree** [comment]
Hi, @romainguy, I also met this issue in version 1.15.0. Does that mean the issue is still not fixed? From your comments above I thought it was a model issue at first, but since the model is correctly rendered in other renderer(https://gltf-viewer.donmccurdy.com/), I concluded that it's still a filament blending issue. Seems filament does not correctly use the alpha masking.  Am I right ?
Thanks.
