### ISSUE TITLE
A bit confuse about the method  ResourceLoader::Impl::computeTangents

### ISSUE THREAD

**Issue by geroge-d** [google/filament#4088]
Hi guys
When i read the method computeTangent in resource loader of gltf io, I got confused about these fact below. Please give me any hint,Thanks in adavance

Based on the glTF Spec 2.0, Morph Targets should  be calculated with all targets conmbined by weights, for example POSITION:
   ` primitives[i].attributes.POSITION + weights[0] * primitives[i].targets[0].POSITION +  weights[1] * primitives[i].targets[1].POSITION +  weights[2] * primitives[i].targets[2].POSITION + ...`

But in Filament, I see only one target added to the attributes, without weights applied  on computing the TANGENT. 
Like these codes in ResourceLoader computeTangents method, it seams just to create a job for each morph target seperately

` for (int morphTarget = 0; morphTarget < 4; morphTarget++) {

            const auto& tangents = morphTangents[morphTarget];

            auto iter = tangents.find(vb);

            if (iter != tangents.end()) {

                jobParams.emplace_back(Params {{ pair.first, morphTarget }, {vb, iter->second }});

            }

        }`

The tangent-compute job seams to only  add morphDeltas ,without any weights apply
The code in TangentsJob::run:
` if (auto basePosInfo = baseAccessors[cgltf_attribute_type_position]; basePosInfo) {

        assert(basePosInfo->count == vertexCount && basePosInfo->type == cgltf_type_vec3);

        unpackedPositions.reset(new float3[vertexCount]);

        cgltf_accessor_unpack_floats(basePosInfo, &unpackedPositions[0].x, vertexCount * 3);

        sob.positions(unpackedPositions.get());

        if (auto mtPositionsInfo = morphTargetAccessors[cgltf_attribute_type_position]) {

            cgltf_accessor_unpack_floats(mtPositionsInfo, &morphDeltas[0].x, vertexCount * 3);

            for (cgltf_size i = 0; i < vertexCount; i++) {

                unpackedPositions[i] += morphDeltas[i];

            }

        }

    }

`

**Comment by romainguy** [comment]
Are you reporting an issue? If not please open a discussion instead.

**Comment by romainguy** [comment]
Btw weights are applied in the vertex shader: https://github.com/google/filament/blob/e297f65d8cdf203daaf9c35f766672a42eb642e8/shaders/src/main.vs#L14

**Comment by geroge-d** [comment]
> Btw weights are applied in the vertex shader:
> 
> https://github.com/google/filament/blob/e297f65d8cdf203daaf9c35f766672a42eb642e8/shaders/src/main.vs#L14

I think this place is for rendering. But I don't know whether it is necessary to apply morph weights on computing  tangents  or not

**Comment by geroge-d** [comment]
I 'm not sure it is a bug or my misunderstanding the codes.

**Comment by prideout** [comment]
Yes the way we handle morphing is somewhat complex by necessity, feel free to open a discussion.

Note that there is one job per primitive, not per morph target.

Also note that Filament does not have a vertex attribute for normal vectors, instead we use tangent quaternions and extract normals in the vertex shader.

In the glTF file, morph normals and tangents are actually offsets (deltas) from the base value.  So, our TangentsJob implementation adds these deltas to the base values to get a finalized value.  It uses our SurfaceOrientation helper in order to generate the tangent quaternions in a form that Filament accepts.
