### ISSUE TITLE
[Feature request] glTF KHR_materials_variants extension

### ISSUE THREAD

**Issue by cx20** [google/filament#4098]
**Is your feature request related to a problem? Please describe.**
Recently, some models using the [KHR_materials_variants](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_variants) extension have been added to the [Khronos glTF Sample models](https://github.com/KhronosGroup/glTF-Sample-Models/) repository.
However, Filament does not support this extension, so I am unable to try it.

The following is an example of a model from the `KHR_materials_variants` extension.
|Model|Screenshot|
|:---:|:---:|
|[Glam Velvet Sofa](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/GlamVelvetSofa)|![image](https://user-images.githubusercontent.com/1833979/121071795-6040ff80-c80b-11eb-83ff-15cbada7428c.png)|
|[Materials Variants Shoe](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MaterialsVariantsShoe)|![image](https://user-images.githubusercontent.com/1833979/121071746-4d2e2f80-c80b-11eb-814d-911a1b49d13a.png)|
|[Sheen Chair](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SheenChair)|![image](https://user-images.githubusercontent.com/1833979/121072111-bf9f0f80-c80b-11eb-8822-c81718494591.png)|

**Describe the solution you'd like**
It is expected that support and sample code for the `KHR_materials_variants` extension will be provided.

**Describe alternatives you've considered**
I am testing some samples with [gltf-test](https://github.com/cx20/gltf-test#extension-test-models), but until this extension is supported, the test will be marked as Fail.

**Comment by romainguy** [comment]
It's something we'd like to support as well. It should be fairly easy since the concept of variants should map very well to our concept of `MaterialInstance`.

**Comment by issacclee** [comment]
Sorry to piggy back on this question.
For complex gltf model with multiple heavily textured material variants, it normally would make sense to also employ extensions such as KHR_texture_basisu to reduce the packaged assets transmission size.
Currently it seems filament doesn't support KHR_texture_basisu extension. I was wondering if the filament team would consider support it?

**Comment by cx20** [comment]
@issacclee I think the following are issues related to `KHR_texture_basisu`.

https://github.com/google/filament/issues/1378

**Comment by issacclee** [comment]
> @issacclee I think the following are issues related to `KHR_texture_basisu`.
> 
> #1378

Ah, thanks!

**Comment by ThomasGorisse** [comment]
> Describe alternatives you've considered
I am testing some samples with gltf-test, but until this extension is supported, the test will be marked as Fail.

@cx20 Your repo rocks!
Thanks for your crazy work. It's very helpful.

**Comment by cx20** [comment]
@prideout Thank you for supporting this extension. I have confirmed that this extension works with [gltf-test](https://github.com/cx20/gltf-test#extension-test-models).
https://github.com/cx20/gltf-test
![image](https://user-images.githubusercontent.com/1833979/161869977-5910bd71-ac10-4f2d-afe4-62f19fb84c0c.png)

**Comment by cx20** [comment]
https://github.com/google/filament/pull/5361
