### ISSUE TITLE
Would be great to have a sample for using Filament with React Native

### ISSUE THREAD

**Issue by karanganesan** [google/filament#4112]
**Is your feature request related to a problem? Please describe.**
Using React Native's Native UI Modules, is it possible to expose the Filament's main view scene and use it with react native?

**OS and backend**
Android and iOS

**Comment by romainguy** [comment]
Thanks for the suggestion but we won't write a sample for React Native. Our team is not familiar with React and we cannot provide samples for all the frameworks out there. I don't know how React Native works but it seems like all you need is this: https://agoraio-community.github.io/react-native-agora/classes/surfaceview.html (or equivalent).
