### ISSUE TITLE
On iOS, the application that removes the skybox displays an error. How to set transparent background of 3D model.

### ISSUE THREAD

**Issue by cwwng** [google/filament#4115]
**Describe the bug**
Use the official Helllo-gltf demo, after removing the skybox.
Run OpenGL Target and the background is red.
Run Metal Target, and the background displays a splash screen, and the splash screen keeps beating.

**To Reproduce**
In the Helllo-gltf project, remove the scene->setSkybox(app.skybox) from app.cpp.

**Screenshots**
![IMG_0009](https://user-images.githubusercontent.com/12265892/121456069-09d4ec00-c9d8-11eb-9721-a9da74bd8567.PNG)
![IMG_0008](https://user-images.githubusercontent.com/12265892/121456072-0b061900-c9d8-11eb-87d2-9a174c0de7ba.PNG)

**Smartphone**
iPhone 11

**Expected behavior**
On iOS devices：
1.After removing the skybox, the background is displayed normally.
2.The background of the model is transparent. How to set it? For example, loading a 3D model onto a custom image.

**Comment by romainguy** [comment]
This happens when you don't draw a background. You can't just remove the skybox, you need to use a transparent swap chain as well.

**Comment by cwwng** [comment]
> This happens when you don't draw a background. You can't just remove the skybox, you need to use a transparent swap chain as well.

Thank you very much. Set the transparent swap chain. Is it set here?
Metal
- (void)initializeMetalLayer
{
#if METAL_AVAILABLE
    CAMetalLayer* metalLayer = (CAMetalLayer*) self.layer;
    metalLayer.pixelFormat = MTLPixelFormatBGRA8Unorm;
    CGRect nativeBounds = [UIScreen mainScreen].nativeBounds;
    metalLayer.drawableSize = nativeBounds.size;
    metalLayer.opaque = NO;
#endif
}

OpenGL ES
- (void)initializeGLLayer
{
    CAEAGLLayer* glLayer = (CAEAGLLayer*) self.layer;
    glLayer.opaque = NO;
    glLayer.backgroundColor = [UIColor colorWithRed:0 green:0 blue:0 alpha:0].CGColor;
}

Settings finished, not in effect.

**Comment by romainguy** [comment]
No you need to set the transparent flag on the Filament SwapChain object when it gets created.

**Comment by romainguy** [comment]
See this sample app: https://github.com/google/filament/blob/ee2767875cba57d3a637d1cf8480cfcf096f053f/ios/samples/transparent-rendering/transparent-rendering/FilamentView.mm#L154

**Comment by cwwng** [comment]
> See this sample app:
> 
> https://github.com/google/filament/blob/ee2767875cba57d3a637d1cf8480cfcf096f053f/ios/samples/transparent-rendering/transparent-rendering/FilamentView.mm#L154

👍👍👍
