### ISSUE TITLE
GITF/GIB compression (similar question with #issue 558)

### ISSUE THREAD

**Issue by Yan-Xiaodi** [google/filament#4119]
Recently，I am trying to do some work based on Filament ,and I also noticed the Draco. 
Dose Filament has some tools to support the gITF or glb compression ?or Filament has already  realized this funcion just I didn't found it. 
I noticed you have mentioned  may  add this Draco compression in issue 558.
Thanks for your great work

**Comment by prideout** [comment]
Yes, our glTF reader library (gltfio) already supports Draco decoding.  We do not provide tools for encoding or writing glTF files.  Feel free to use our "discussions" tab for further questions.
