### ISSUE TITLE
When I'm using Filament on iOS, I'm seeing a lot of weight gain

### ISSUE THREAD

**Issue by wangruibobobo** [google/filament#4124]
**Is your feature request related to a problem? Please describe.**
When I'm using Filament on iOS, I'm seeing a lot of weight gain, 

**Describe the solution you'd like**
so I want to be able to select some libraries for it just like on Android. Is there any plan to split into different libraries like Android? For example, filament-iOS, gltfio- iOS.

**Describe alternatives you've considered**
Or how should I replace libgltfio_resources.a with libgltfio_resources_lite.a, because the linkMap occupied by libgltfio_resources.a is too large, with 4.7M.

**OS and backend**
iOS

**Comment by romainguy** [comment]
Filament is already split up in multiple libraries on iOS. Is the problem the size of the gltfio library?

@bejado Should we disable the GL backend so we could compile only Metal shaders maybe? Or maybe we’re not filtering back ends when compiling the iOS library and generating materials with too many shaders?

**Comment by wangruibobobo** [comment]
Yes, the key point is that libgltfio_resources.a occupies the actual size of the ipa packet of 4.7M. Can libgltfio_resources_lite.a replace libgltfio_resources.a, We can accept features that do not support part of GLTF 2.0. How should we replace them?

**Comment by bejado** [comment]
@romainguy Yes the long-term goal is to remove the OpenGL backend from iOS.

@wangruibobobo I believe you can replace libgltfio_resources.a with libgltfio_resources_lite.a, albeit with some glTF features missing. @prideout can confirm.

**Comment by wangruibobobo** [comment]
> @romainguy Yes the long-term goal is to remove the OpenGL backend from iOS.
> 
> ~@wangruibobobo I believe you can replace libgltfio_resources.a with libgltfio_resources_lite.a, albeit with some glTF features missing. @prideout can confirm.~ Actually, I think this is incorrect. From another thread:
> 
> > You can't use gltfio_ resources_lite.a directly as a replacement of gltfio_ resources.a, you first need to compile gltfio in "lite" mode. You can do so by setting -DGLTFIO_LITE=ON when invoking CMake to compile Filament.

Thank you for your answer, I recompiled the Lite library, and the sample project hello-gltf reported an error

Unsupported glTF material configuration; falling back to LIT_OPAQUE.

in const SamplerInterfaceBlock::SamplerInfo *filament::SamplerInterfaceBlock::getSamplerInfo(const char *) const:110
reason: sampler named "clearCoatMap" not found
