### ISSUE TITLE
Does filament have support for volume textures?

### ISSUE THREAD

**Issue by unicomp21** [google/filament#4125]
**Is your feature request related to a problem? Please describe.**
volume texture support ie indexed by uvw

**Comment by prideout** [comment]
Yes, in fact our Color Grading LUT is a 3D texture.   Take a look at `colorGrading.mat`.

**Comment by unicomp21** [comment]
@prideout is this it?
http://github.com/google/filament/blob/acfae2882d34adbdc491190a9640ba868cfe9663/filament/include/filament/ColorGrading.h#L94-L94

**Comment by prideout** [comment]
Yes that's  the ColorGrading API, the material file might be more interesting to you since it does 3D sampling:

https://github.com/google/filament/blob/main/filament/src/materials/colorGrading/colorGrading.mat#L10
