### ISSUE TITLE
Use libgltfio_resources_lite.a  library to crash in hello-gltf

### ISSUE THREAD

**Issue by wangruibobobo** [google/filament#4143]
**Describe the bug**

**To Reproduce**

Because libgltfio_resources.a took up too much space,
 -DGLTFIO_LITE=1 was used at compile time, and libgltfio_resources_lite.a was chosen instead

**Expected behavior**
A crash occurs while hello-gltf is running

> **in const SamplerInterfaceBlock::SamplerInfo *filament::SamplerInterfaceBlock::getSamplerInfo(const char *) const:110
> reason: sampler named "clearCoatMap" not found**

**Screenshots**
<img width="1680" alt="企业微信截图_5e079b48-69f8-4353-92a5-a267a31debbd" src="https://user-images.githubusercontent.com/34636280/122177355-1ebded80-ceb8-11eb-94c5-916a0ca403cf.png">

**Desktop (please complete the following information):**
 - OS: iOS14
 - Backend: Matal

**Smartphone (please complete the following information):**
 - Device: iphoneX
 - OS: iOS14

**Comment by romainguy** [comment]
How exactly did you use -DGLTFIO_LITE? Did you compile the gltfio library yourself? That flag is not meant to be used to compile your app.

**Comment by wangruibobobo** [comment]
In fact, I modified the libs/gltfio/CMakeList.text  file. 

[CMakeLists.txt](https://github.com/google/filament/files/6670206/CMakeLists.txt)

 And UbershaderLoader.cpp  file.
 
![企业微信截图_588a388a-ccc3-4da5-9cb2-fd06efe40888](https://user-images.githubusercontent.com/34636280/122397187-4fcb1a80-cfab-11eb-94ef-b89d518eadf2.png)

Or how can I use it correctly libgltfio_resources_lite.a


Thanks.

**Comment by romainguy** [comment]
This define is needed in more places than just `UbershaderLoader.cpp`. You should pass it as a flag to the compiler.

**Comment by wangruibobobo** [comment]
With these two lines of code currently compiled, how do I add flags

sudo ./build.sh -p desktop -i release 
sudo ./build.sh -p ios -i release

**Comment by romainguy** [comment]
You need to modify `build.sh` to add `-DGLTFIO_LITE=1` to the invocation of CMake in the function `build_ios_target`.

**Comment by wangruibobobo** [comment]
I removed all the previous changes and added -DGLTFIO_LITE=1，
Run
```
sudo ./build.sh -p desktop -i release
sudo ./build.sh -p ios -i release
```
and change Other Linker Flags 
Did I add it in the wrong place

![企业微信截图_b6d8e30c-301e-40db-ba21-df3f1e07ca65](https://user-images.githubusercontent.com/34636280/122444483-2de58e00-cfd3-11eb-9bac-5181dbc445c7.png)
![企业微信截图_5f4c7a3c-a6d4-4890-95f2-7aa691b05313](https://user-images.githubusercontent.com/34636280/122444649-5a010f00-cfd3-11eb-93e2-16fbada2ddac.png)

![企业微信截图_cef02845-7182-4935-aff8-ab6bc10fefbe](https://user-images.githubusercontent.com/34636280/122444498-31791500-cfd3-11eb-850f-095402a7eea7.png)

**Comment by romainguy** [comment]
@wangruibobobo The problem you are running into is that gltfio-lite does not support clear coat. gltfio-lite only supports a subset of glTF extensions. If you want to support clear coat you will need to use the full version of gltfio. As for your linker error, you probably need to do a clean build for the flag to take effect (but like I just mentioned this won't fix your original issue with clear coat).

**Comment by wangruibobobo** [comment]
Thank you for your quick reply. I would like to know if there is a material that is not supported by the Lite Library, will crash be caused? Will this material be ignored

**Comment by prideout** [comment]
In debug builds, we assert if a sampler is set that does not exist, which can occur when attempting to load a model that uses an extension that is not supported by the ubershader.  The intention is to not crash in release builds.
