### ISSUE TITLE
how to build armv7 arch ios

### ISSUE THREAD

**Issue by aliyunvideo** [google/filament#4144]
we user filament to render GLB Mode，Make a SDK for APP, but only arm64，not have armv7, HOW TO BUILD ARMV7 AND ARM64

I  TRY TO FIX BUILD.SH 
![image](https://user-images.githubusercontent.com/33014286/122219681-4164fc00-cee2-11eb-8213-fdb56a1e0516.png)

THIS ERROR

-- Build files have been written to: /Users/botao/Desktop/aliyun/aidemo/filament/out/cmake-ios-release-armv7
[  0%] Building CXX object third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o
clang: error: invalid iOS deployment version '-mios-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
clang: warning: optimization flag '-fomit-frame-pointer' is not supported for target 'armv7' [-Wignored-optimization-argument]
make[2]: *** [third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/googletest/src/gtest-all.cc.o] Error 1
make[1]: *** [third_party/libgtest/tnt/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2

**Comment by romainguy** [comment]
Do you need armv7 for iOS? This is not something we support nor intend to support since Apple doesn't support armv7 anymore.

**Comment by bejado** [comment]
The last armv7 iPhone was [iPhone 5c](https://www.innerfence.com/howto/apple-ios-devices-dates-versions-instruction-sets), which only supports up to iOS 10. Filament requires iOS 11 support, so it doesn't make sense for us to support armv7 for iOS.

**Comment by lichentao** [comment]
@bejado But. if not support armv7 ,How To Add exits APP ,the App IS Support ARMV7 And ARM64

**Comment by lichentao** [comment]
![image](https://user-images.githubusercontent.com/5095376/122322732-8592e380-cf58-11eb-9b3f-c6e973797b89.png)

**Comment by lichentao** [comment]
Can I.  modify Shell. to. Support ARMV7 and arm64. to build filament.a for exit APP

**Comment by lichentao** [comment]
others framework is support armv7 and arm64 ,only filament is arm64 , can not  compile and send appstore,can you help to solution this problem

**Comment by romainguy** [comment]
Filament requires iOS 11 minimum and iOS 11 does not support armv7. We will therefore not provide support for it since we can't compile Filament for armv7.

**Comment by lichentao** [comment]
hi. @romainguy  thouth filament support ios11,but. some exist app is support armv7 and arm64, and want to use filament , yet can not do this? how do you think about this case?

**Comment by lichentao** [comment]
we are only to match exit app ,not only to support ios10, just so

**Comment by bejado** [comment]
You need to configure your app's build to only include Filament when targeting arm64 then.

**Comment by lichentao** [comment]
@bejado  thiank you , can i. build source file to  support armv7 ,need to modify which file ,can you help tell me?  our app must support armv7,  if. you have not plan to support

**Comment by bejado** [comment]
This SO question may help you: [Xcode Conditional Build Settings based on architecture](https://stackoverflow.com/questions/1211854/xcode-conditional-build-settings-based-on-architecture-device-arm-vs-simulat).
