### ISSUE TITLE
The build breaks under Debian 10.9

### ISSUE THREAD

**Issue by tcgoiazx** [google/filament#4149]
**Describe the bug**
The Filament build breaks under Debian 10.9 (the latest stable release of the distribution). The build complains about the version of cmake installed on Debian.

**To Reproduce**
Run, for example,
`./build.sh -p desktop -i release`
at the root of Filament's source tree under Debian 10.9, with cmake from the _Debian Main_ repository.

**Expected behavior**
Filament build produces the expected binaries and libraries.

**Additional context**
Debian 10.9 provides cmake 3.13.4: https://debian.pkgs.org/10/debian-main-amd64

However, starting with google/filament release v1.9.25, `cmake_minimum_required` in many CMakeLists files in Filament's source tree is set to `version 3.19`. Before google/filament release v1.9.25, `cmake_minimum_required` was `version 3.10` or lower.

Note that the latest version of Filament can be build after manually setting `cmake_minimum_required` to `version 3.13.4` in the CMakeLists files that officially require a higher version.

**Comment by romainguy** [comment]
We use more recent versions of CMake and thus can only guarantee our build with CMake 3.19 and higher. Please update your CMake to a newer version (the latest are 3.20.x).
