### ISSUE TITLE
Question: How to best render a scene both normally (as light) and with a different material (think thermal night vision).

### ISSUE THREAD

**Issue by molysgaard** [google/filament#415]
**Is your feature request related to a problem? Please describe.**
This is more of a question, and not a bug/feature report. I just didn't know where else to ask questions.

I have a scene that I am rendering in the visual light spectrum. This is done exacly as fillament is intended.
In addition I would like to render the scene in another part of the electromagnetic spectrum, thermal imaging.
The way I am doing it today I have to choose between visual light and thermal camera. For visual light I use my normal PBR materials. For thermal camera, I have to manually change the material of all the entities in the scene to my thermal material.

**Describe the solution you'd like**
My ideal solution would be to be able to render the whole scene in the visual light spectrum as is done normally in filament.
And in addition specify a specific "render pass" that renders exactly the same scene but all entities are rendered with the thermal material.

I am wondering if such a "render pass" feature exists in filament?
If it doesn't, what would be the point of least work in filament to implement such a feature?

In a more general setting one could imagine the entity's materials as a mapping `PassID -> Material` and then having multiple passes each with their `PassID`. This way a scene could be rendered in multiple spectrum. I am not sure how this would be implemented or if this would be efficient or lead to some sort of material churn on the GPU side.

**Describe alternatives you've considered**
The only solution I have tried is rendering a scene with only one of the two materials. I have not tried to implement dynamic switching of the materials in the render loop.

**OS and backend**
This is not OS/backend specific.

**Comment by romainguy** [comment]
It's a feature we actually recently got rid of. There used to be a way to set an "override" material on a `View`, to achieve precisely what you are describing. It was however complicating the render loop. @pixelflinger can talk more about this.

Another way to achieve this (which is not very easy I admit), is to create 2 renderables per mesh, with different material instances. The renderables can share the same vertex and index buffers.

**Comment by pixelflinger** [comment]
To expand of the solution proposed by @romainguy , you can create 2 renderables per mesh with different materials and add BOTH to the scene -- and they can share the same transform using parenting (e.g.: the thermal entity can be parented to the normal one, with identity transform) -- but in different layers. This way it'll be very easy to switch between the two renderings, just activate/hide the proper layer. The extra memory usage and runtime cost will be minimal. The only complexity is when you build the scene initially.
I hope this helps!
