### ISSUE TITLE
filagui load custom font

### ISSUE THREAD

**Issue by mnesarco** [google/filament#4159]
**Is your feature request related to a problem? Please describe.**

Apparently there is no encapsulated way to add a custom font for ImGui from filagui api. If i understand correctly, after calling `io.Fonts->AddFontXXX` it is required to create a texture by hand.

**Describe the solution you'd like**

Expose some kind of public static method from ImGuiHelper to add custom fonts.

**Comment by prideout** [comment]
This already exists, see `ImGuiHelper::createAtlasTexture()`.  You can call this after calling one of the `io.Fonts->AddFont*()` functions.

**Comment by mnesarco** [comment]
The problem with that is that there is no access to the `ImGuiHelper` instance from the `FilamentApp` setup. So there is no way to call `ImGuiHelper::createAtlasTexture()` _(it is not static)_ if the app is based on `FilamentApp`.

A possible elegant solution is to pass a pointer to the internal `ImGuiHelper` instance in the setup callback. Or add another callback specific to initialize ImGui.

**Comment by prideout** [comment]
Ah understood.  FilamentApp isn't very configurable, it's a toy framework.  We could add this feature though, I like your idea of simply adding a parameter to the callback.  Feel free to make a PR.

**Comment by romainguy** [comment]
FilamentApp is not a public API. It only exists for our convenience to build test apps. It's pretty terrible overall anyway. Note that we may break/rewrite FilamentApp at any time and I strongly advise you do not rely on it.

**Comment by mnesarco** [comment]
I am just learning, so i am using **FilamentApp** as a base. I was trying to add an icon font for **ImGui** and I finally modified the **FilamentApp** source but I suppose many people try to do things with **FilamentApp** as first try like me. 
BTW, Filament is very impressive. Thank you for all the hard work.
