### ISSUE TITLE
third-party getopt conflicts with POSIX getopt

### ISSUE THREAD

**Issue by 100espressos** [google/filament#4163]
**Describe the bug**
```
In file included from /usr/include/unistd.h:883:
In file included from /usr/include/bits/getopt_posix.h:27:
/usr/include/bits/getopt_core.h:91:12: error: exception specification in declaration does not match previous declaration
extern int getopt (int ___argc, char *const *___argv, const char *__shortopts)
           ^
filament/third_party/getopt/include/getopt/getopt.h:54:5: note: previous declaration is here
int getopt(int, char **, const char *);
    ^
```

**To Reproduce**
Include a conflicting getopt()

**Desktop:**
 - OS: arch linux

**Comment by romainguy** [comment]
Does this happen when building Filament? getopt is only used by our tools and samples.

**Comment by 100espressos** [comment]
No, it does not occur internally with Filament.. I probably pulled it in by mistake. Thanks for checking.

**Comment by dandingol03** [comment]
I encounter the conflict too. When i compiled the viewer demo with ``libarchive``. Is there any possible i can update the ``getopt`` to resolve the conflict?

**Comment by kpeeters** [comment]
I am still seeing this with clang-18. The system getopt declared in `/usr/include/aarch64-linux-gnu/bits/getopt_core.h` has
```
extern int getopt (int ___argc, char *const *___argv, const char *__shortopts)
     __THROW __nonnull ((2, 3));
```
but the one included in filament misses the exception specification.
