### ISSUE TITLE
Abnormal rendering of translucent material in library libgltfio_resources_lite.a

### ISSUE THREAD

**Issue by wangruibobobo** [google/filament#4164]
Describe the bug

When I use library libgltfio_resources_lite.a，
It is normal to use the model that comes with GLTF-Viewer，
But we replaced it with our own model with a translucent material，
The transparent area is rendered white.
I want to know is it because libgltfio_resources_lite.a library does not support translucent material or is this a bug

Expected behavior
Transparent areas can be rendered normally

Screenshots
The built-in model scene.gltf is normal
![IMG_0028](https://user-images.githubusercontent.com/34636280/122678387-3af3be80-d219-11eb-8c22-77d415959047.PNG)
Model  with translucent material
![IMG_0027](https://user-images.githubusercontent.com/34636280/122678422-64144f00-d219-11eb-9fb7-eb7f834d7058.PNG)

Desktop (please complete the following information):

OS: iOS14
Backend: Matal
Smartphone (please complete the following information):

Device: iphoneX
OS: iOS14

**Comment by prideout** [comment]
```
    // In the GLTFIO_LITE configuration we do not support UV matrices, clear coat, sheen, specular
    // glossiness, or transmission. For more details, see `gltflite.mat.in`. To configure a custom
    // set of features, create your own MaterialProvider class, perhaps using UbershaderLoader as a
    // starting point.
    ```
