### ISSUE TITLE
Multithread problem in JobSystem?

### ISSUE THREAD

**Issue by magicchao** [google/filament#4167]
JobSystem::execute runs in threads, and calls JobSystem::pop(), and calls WorkStealingDequeue::pop
Job* pop(WorkQueue& workQueue) noexcept {
        size_t index = workQueue.pop();
        assert(index <= MAX_JOB_COUNT);
        return !index ? nullptr : &mJobStorageBase[index - 1];
}

But WorkStealingDequeue::pop has a comment that "Must be called from the main thread"
Is this a problem?
PS: JobSystem::run -> JobSystem::put -> WorkStealingDequeue::push  has the same situation

**Comment by romainguy** [comment]
It is not a problem in practice because each thread has its own work queue as part of the `ThreadState`.
