### ISSUE TITLE
Native So Crash signal 11 (SIGSEGV), code 2 (SEGV_ACCERR) libgltfio-jni.so (offset 0x196e000)

### ISSUE THREAD

**Issue by allen-hsu** [google/filament#4170]
**Describe the bug**
Native Crash signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)
libgltfio-jni.so (offset 0x196e000)

Hi, I used the filament lib, and I got some native crash like this

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.machipopo.media17 <<<

backtrace:
  #00  pc 000000000041bfdc  /data/app/com.machipopo.media17-WnaZawbuusuMdtVDe3GYyQ==/split_config.arm64_v8a.apk!lib/arm64-v8a/libgltfio-jni.so (offset 0x196e000)
```
And this amount is very large, I went to find out if there is a similar problem. I saw on stackoverflow that some people say that this is caused by the Android Application Bundle and needs to be resolved on a specific version of the NDK. What version of NDK do you compile and use?

**To Reproduce**
Can't Reproduce, Receive Native Crash From Google Play Console

**Expected behavior**
Not Crash

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**
Hi, I used the filament lib, and I got some native crash like this

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.machipopo.media17 <<<

backtrace:
  #00  pc 000000000041bfdc  /data/app/com.machipopo.media17-WnaZawbuusuMdtVDe3GYyQ==/split_config.arm64_v8a.apk!lib/arm64-v8a/libgltfio-jni.so (offset 0x196e000)
```
And this amount is very large, I went to find out if there is a similar problem. I saw on stackoverflow that some people say that this is caused by the Android Application Bundle and needs to be resolved on a specific version of the NDK. What version of NDK do you compile and use?

**Comment by romainguy** [comment]
Do you have more logs or the asset that creates the crash? What API levels are those devices? There isn't much we can do without more information.

**Comment by allen-hsu** [comment]
Hi, @romainguy  I just got those info from google play, 
```

bar_chart
Statistics
Publishing overview
sync
Release
widgets
Releases overview
Production
arrow_drop_down
slow_motion_video
Testing
Open testing
Closed testing
Internal testing
Pre-registration
arrow_drop_down
Pre-launch report
Overview
Details
Settings
devices
Device catalog
App bundle explorer
arrow_drop_down
settings
Setup
App integrity
Internal app sharing
Advanced settings
Grow
arrow_drop_down
Store presence
Main store listing
Custom store listings
Store listing experiments
LiveOps
Store settings
Translation service
arrow_drop_down
trending_up
Store performance
Store analysis
Conversion analysis
Quality
arrow_drop_down
comment
Ratings and reviews
Ratings
Reviews
Reviews analysis
Testing feedback
arrow_drop_down
Android vitals
Overview
arrow_drop_down
Performance
Frame rate
Settings
Crashes and ANRs
App size
Monetize
keyboard_arrow_down
App pricing
In-app products
Subscriptions
Overview
arrow_drop_down
Subscriptions
Overview
Retention
Cancellations
Revenue
Buyers
Conversions
Policy
Policy status
App content
Crash details
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)
libfilament-jni.so (offset 0x17b2000)
filter_list
Add filter
date_range
Last 30 days
arrow_drop_down
Occurrences
877
Last 30 days
Total occurrences
1.99K
Lifetime
Impacted users
344
Lifetime
Last occurred
9 hours ago
Occurrences of this crash between May 23, 2021 and Jun 22, 2021
Occurrences
Impacted users
By app version
2626.aab
2631.aab
2622.aab
2625.aab
Others
By Android version
Android 10 (SDK 29)
Android 11 (SDK 30)
Android 9 (SDK 28)
By device
Motorola moto e
Asus ZenFone 7 / 7 Pro (ZS670KS/ZS671KS)
Asus ZenFone 6 (ZS630KL) (WW) / 6Z (ZS630KL) (IN)
Motorola moto g(7) play
Others
Stack trace
Occurrence 1 of 877
Crash
brightness_1
Asus ROG Phone 5
brightness_1
Android 11 (SDK 30)
brightness_1
2631.aab
brightness_1
9 hours ago
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.machipopo.media17 <<<

backtrace:
  #00  pc 00000000000d2310  /data/app/~~0UgCiPu0yDyZMggAsitz8g==/com.machipopo.media17-g-YVdxxcHN8C09_0Sh5S_w==/split_config.arm64_v8a.apk!lib/arm64-v8a/libfilament-jni.so (offset 0x17b2000)
```

![截圖 2021-06-22 上午10 34 25](https://user-images.githubusercontent.com/2819672/122853863-78556a80-d345-11eb-86d4-487525349860.png)

**Comment by allen-hsu** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.machipopo.media17 <<<

backtrace:
  #00  pc 000000000041bfdc  /data/app/com.machipopo.media17-1/lib/arm64/libgltfio-jni.so
  #00  pc 000000000041bafc  /data/app/com.machipopo.media17-1/lib/arm64/libgltfio-jni.so

![截圖 2021-06-22 上午10 35 30](https://user-images.githubusercontent.com/2819672/122853940-928f4880-d345-11eb-9d46-c81e4edd9d0b.png)

**Comment by allen-hsu** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.machipopo.media17 <<<

backtrace:
  #00  pc 000000000004a4b0  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+224)
  #00  pc 000000000041b0d0  /data/app/~~Qpdqg3fwIKcTyR8SMAKi7A==/com.machipopo.media17-3tjW5vHepTCRQgqRDGil3w==/split_config.arm64_v8a.apk!lib/arm64-v8a/libgltfio-jni.so (offset 0x196e000)

![截圖 2021-06-22 上午10 36 21](https://user-images.githubusercontent.com/2819672/122854043-b5b9f800-d345-11eb-9ccd-80e04cda2a29.png)

**Comment by allen-hsu** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.machipopo.media17 <<<

backtrace:
  #00  pc 00000000000a3114  /system/lib64/libc.so (arena_run_first_best_fit+376)
  #00  pc 0000000000098ff4  /system/lib64/libc.so (arena_bin_malloc_hard+172)
  #00  pc 0000000000098cd8  /system/lib64/libc.so (je_arena_tcache_fill_small+168)
  #00  pc 00000000000c26d8  /system/lib64/libc.so (je_tcache_alloc_small_hard+32)
  #00  pc 00000000000b1ec0  /system/lib64/libc.so (je_malloc+752)
  #00  pc 000000000046b510  /data/app/com.machipopo.media17-i_3Y1i_ctEkEDQg8f4Ofig==/split_config.arm64_v8a.apk!lib/arm64-v8a/libgltfio-jni.so (offset 0x196e000)
  #00  pc 00000000003f2c94  /data/app/com.machipopo.media17-i_3Y1i_ctEkEDQg8f4Ofig==/split_config.arm64_v8a.apk!lib/arm64-v8a/libgltfio-jni.so (offset 0x196e000)
  
  
![截圖 2021-06-22 上午10 37 15](https://user-images.githubusercontent.com/2819672/122854124-d1bd9980-d345-11eb-9446-4ad414ccee91.png)

This is a lot of crashes related to filament, Can you tell me about the NDK version you compile and use? I want to confirm if it is related to the NDK version

**Comment by romainguy** [comment]
I don't think it has anything to do with the NDK (we use version 22.1.7171670). The crashes in malloc could be an out of memory situation. What assets are you trying to load?

**Comment by allen-hsu** [comment]
@romainguy We try to read an avatar, and it can dynamically replace the texture on the body
，But， I think the out of memory issue just for this issue ?
```
#0 pc 00000000000a3114 /system/lib64/libc.so (arena_run_first_best_fit+376)
#0 pc 0000000000098ff4 /system/lib64/libc.so (arena_bin_malloc_hard+172)
#0 pc 0000000000098cd8 /system/lib64/libc.so (je_arena_tcache_fill_small+168)
#0 pc 00000000000c26d8 /system/lib64/libc.so (je_tcache_alloc_small_hard+32)
#0 pc 00000000000b1ec0 /system/lib64/libc.so (je_malloc+752)
#0 pc 000000000046b510 /data/app/com.machipopo.media17-i_3Y1i_ctEkEDQg8f4Ofig==/split_config.arm64_v8a.apk!lib/arm64-v8a/libgltfio-jni.so (offset 0x196e000)
#0 pc 00000000003f2c94 /data/app/com.machipopo.media17-i_3Y1i_ctEkEDQg8f4Ofig==/split_config.arm64_v8a.apk!lib/arm64-v8a/libgltfio-jni.so (offset 0x196e000
```

But there are other jni-related crashes that seem to have nothing to do with memory?

**Comment by pixelflinger** [comment]
That looks like more a heap corruption to me -- could be an actual corruption, or more likely a double free. There is also a report in memcpy, and that could be due an out of memory (e.g. if some malloc returned 0), or also a memory corruption.
It would be helpful to have  a repro case.

**Comment by pixelflinger** [comment]
Okay reading the comments again, I think it is most likely that you are freeing an object twice, probably a texture (since it looks like you're updating the texture on the model).

**Comment by pixelflinger** [comment]
unfortunately this doesn't seem actionable to us at this point. please reopen if you have more info or a repro case.
