### ISSUE TITLE
How to compile the source code? How do I reference source code in my project?

### ISSUE THREAD

**Issue by cwwng** [google/filament#4175]
macOS
iOS platform
Thanks

**Comment by romainguy** [comment]
Please see the file BUILDING.md for all the information on how to compile Filament.

**Comment by cwwng** [comment]
> Please see the file BUILDING.md for all the information on how to compile Filament.

Hello, I was able to compile all the static libraries with build.sh.
I want to use the source code into our project.
No solution was found in building.md.

**Comment by romainguy** [comment]
The easiest thing would be to invoke our CMake files from your build.
