### ISSUE TITLE
Vulkan Instance creation fails

### ISSUE THREAD

**Issue by Joaopmoliveira** [google/filament#4183]
**Describe the bug**
While running the samples with the Vulkan backend the engine fails to create a Vulkan instance.

**To Reproduce**
1. Run the hellotriangle sample on windows

**Expected behavior**
I would expected the engine to be able to select the features it requires from the list of available features

**Screenshots**
´´´
FEngine (64 bits) created at 000002BFE63B6080 (threading is enabled)
FEngine resolved backend: Vulkan
class utils::PostconditionPanic
in __cdecl filament::backend::VulkanDriver::VulkanDriver(class filament::backend::VulkanPlatform *,const char *const *,unsigned int) noexcept:228
in file C:\libraries\Filament\filament\filament\backend\src\vulkan\VulkanDriver.cpp
reason: Unable to create Vulkan instance.
'''
**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: Intel(R) HD Graphics 630/ NVidia GeForce GTX 1050 (I don't know which one the engine selects as the VkPhysicalDevice)
 - Backend: Vulkan

**Additional context**
After failing to run the samples, I debugged the application with the visual studio debugger and the error happens when vkCreateInstance is called with a return error which indicates that an extension was requested that does not exist (VK_ERROR_EXTENSION_NOT_PRESENT). I assume that in the code base you select extensions from the available extension list so I don't know how to solve the problem.

**Comment by Joaopmoliveira** [comment]
When I compile the samples in release mode the code works fine, so there is an extension in debug mode that crashes the application from what I can tell.

**Comment by prideout** [comment]
In older releases we requested some debug-related instance extensions unconditionally but nowadays we first check for availability.  So...yeah this is weird.

Can you try commenting out some of the codelines in `VulkanDriver.cpp` to see which extension is causing the issue?  Specifically, in this code block:

```
#if VK_ENABLE_VALIDATION
#if defined(ANDROID)
    ppEnabledExtensions[enabledExtensionCount++] = "VK_EXT_debug_report";
#endif
    if (validationFeaturesSupported) {
        ppEnabledExtensions[enabledExtensionCount++] = "VK_EXT_validation_features";
    }
#endif
    if (mContext.debugUtilsSupported) {
        ppEnabledExtensions[enabledExtensionCount++] = "VK_EXT_debug_utils";
    }
```

**Comment by Joaopmoliveira** [comment]
I will do as you say, for now what i did was define the VK_ENABLE_VALIDATION as zero in debug mode and it does run, but this gives no information about the specific extension which is giving problems... when I have the time to rebuild and follow your suggestion I will post some updates, and thank you for the awesome library!
