### ISSUE TITLE
Crash on AMD GPU

### ISSUE THREAD

**Issue by Damianno19** [google/filament#42]
All examples on OpenGL crashes on same function `OpenGLDriver::updateUniformBuffer`, on friend pc ( GTX 970, win 10 ) works fine.

OS: Win 10
GPU: RX 480 8GB
Drivers: 18.5.1 ( on older drivers same situation )

> FEngine (64 bits) created at 000002C860664080
> FEngine resolved backend: OpenGL
> HwFence: 16
> GLIndexBuffer: 24
> GLSamplerBuffer: 24
> GLRenderPrimitive: 48
> GLTexture: 64
> OpenGLProgram: 56
> GLRenderTarget: 72
> GLVertexBuffer: 112
> GLUniformBuffer: 128
> GLStream: 128
> ATI Technologies Inc.
> Radeon (TM) RX 480 Graphics
> 4.1.13521 Core Profile Forward-Compatible Context 24.20.11016.4
> 4.50
> OS version: 0
> Hierarchy depth = 1
> OpenGL error 1282 (GL_INVALID_OPERATION) in "void filament::OpenGLDriver::updateUniformBuffer(Driver::UniformBufferHandle, filament::UniformBuffer &&)" at line 1851

Callstack:

> ucrtbased.dll!00007fff40f67135()	Unknown
> ucrtbased.dll!00007fff40f672d3()	Unknown
> ucrtbased.dll!00007fff40f7bf3d()	Unknown
> ucrtbased.dll!00007fff40f7af86()	Unknown
> material_sandbox.exe!filament::GLUtils::checkGLError(utils::io::ostream & out, const char * function, unsigned __int64 line) Line 56	C++
> material_sandbox.exe!filament::OpenGLDriver::updateUniformBuffer(filament::Handle<filament::HwUniformBuffer> ubh, filament::UniformBuffer && uniformBuffer) Line 1853	C++
> material_sandbox.exe!filament::trampoline<void (filament::OpenGLDriver::*&)(filament::Handle<filament::HwUniformBuffer>, filament::UniformBuffer &&),filament::OpenGLDriver &,std::tuple<filament::Handle<filament::HwUniformBuffer>,filament::UniformBuffer> &,0,1>(void(filament::OpenGLDriver::*)(filament::Handle<filament::HwUniformBuffer>, filament::UniformBuffer &&) & m, filament::OpenGLDriver & d, std::tuple<filament::Handle<filament::HwUniformBuffer>,filament::UniformBuffer> & t, std::integer_sequence<unsigned long long,0,1>) Line 96	C++
> material_sandbox.exe!filament::apply<void (filament::OpenGLDriver::*&)(filament::Handle<filament::HwUniformBuffer>, filament::UniformBuffer &&),filament::OpenGLDriver &,std::tuple<filament::Handle<filament::HwUniformBuffer>,filament::UniformBuffer> &>(void(filament::OpenGLDriver::*)(filament::Handle<filament::HwUniformBuffer>, filament::UniformBuffer &&) & m, filament::OpenGLDriver & d, std::tuple<filament::Handle<filament::HwUniformBuffer>,filament::UniformBuffer> & t) Line 103	C++
> material_sandbox.exe!filament::CommandType<void (filament::Driver::*)(filament::Handle<filament::HwUniformBuffer>, filament::UniformBuffer &&)>::Command<&filament::Driver::updateUniformBuffer>::execute<void (filament::OpenGLDriver::*)(filament::Handle<filament::HwUniformBuffer>, filament::UniformBuffer &&),filament::OpenGLDriver &>(void(filament::OpenGLDriver::*)(filament::Handle<filament::HwUniformBuffer>, filament::UniformBuffer &&) && method, filament::OpenGLDriver & driver, filament::CommandBase * base, __int64 * next) Line 139	C++
> material_sandbox.exe!filament::ConcreteDispatcher<filament::OpenGLDriver>::updateUniformBuffer(filament::Driver & driver, filament::CommandBase * base, __int64 * next) Line 354	C++
> material_sandbox.exe!filament::CommandBase::execute(filament::Driver & driver) Line 83	C++
> material_sandbox.exe!filament::CommandStream::execute(void * buffer) Line 78	C++
> material_sandbox.exe!filament::details::FEngine::loop() Line 384	C++

**Comment by romainguy** [comment]
Thanks for the report! We had to find an AMD GPU now… :)

**Comment by pixelflinger** [comment]
@Damianno19 would you be able to try with the attached change?

```
diff --git a/filament/src/driver/opengl/OpenGLDriver.cpp b/filament/src/driver/opengl/OpenGLDriver.cpp
index cb1d53c..a6ef609 100644
--- a/filament/src/driver/opengl/OpenGLDriver.cpp
+++ b/filament/src/driver/opengl/OpenGLDriver.cpp
@@ -400,7 +400,7 @@ void OpenGLDriver::bindBuffer(GLenum target, GLuint buffer) noexcept {
     } else {
         update_state(state.buffers.targets[targetIndex].genericBinding, buffer, [&]() {
             glBindBuffer(target, buffer);
-        });
+        }, true);
     }
 }
```

Thanks!

**Comment by pixelflinger** [comment]
@Damianno19 thank you for testing this; that rules out a state-tracking bug in filament.
All the GL_INVALID_OPERATION cases from the spec are ruled out, so I can only guess a driver bug (at the very least in how it reports errors). Not sure what to do from here.

**Comment by Damianno19** [comment]
So, I tested samples on Ubuntu with mesa drivers, and it works, so it's looks like AMD broke something 🤷‍♂️

**Comment by romainguy** [comment]
@Damianno19 Thanks! Could you try with this change if possible: https://github.com/google/filament/pull/68 ?

**Comment by Damianno19** [comment]
@romainguy 
I tested it. Still crash, but in different place
[Log](https://pastebin.com/8ikkPnPp)
[Callstack](https://pastebin.com/MzevJSZn)

**Comment by Damianno19** [comment]
@romainguy 
Yes.
[dxdiag](https://pastebin.com/TEiw67BR)

**Comment by romainguy** [comment]
See #163
