### ISSUE TITLE
Too much geometry errors in Metal

### ISSUE THREAD

**Issue by tottero** [google/filament#4202]
**Describe the bug**
The following Metal error appears consistently if I add a few hundred objects as separate renderables which are highly tessellated:
```
Execution of the command buffer was aborted due to an error during execution. Too much geometry to support memoryless render pass attachments. (IOAF code 13).
```
**To Reproduce**
It is fairly easy to reproduce the problem in the hello-triangle iOS example.
1. You can keep adding the same triangle vertices in a loop to generate more complex geometry (~10-20K triangles).
2. Instead of having a single renderable, create a few hundred renderables as unique buffers:
```
struct App {
    VertexBuffer* vb[COUNT];
    IndexBuffer* ib[COUNT];
    Material* mat;
    Entity renderable[COUNT];
};
```
If you enable anti-aliasing with `setSampleCount()` then the error appears consistently and white frames are rendered.
**Expected behavior**
No errors and white frame artifacts.
**Desktop (please complete the following information):**
 - OS: iOS
 - Backend: Metal

**Comment by bejado** [comment]
Thanks, I'm able to consistently reproduce on an iPhone 12 Pro. I get the error right around 19k triangles. I understand why this limitation exists, but I've seen absolutely no guidance on it from Apple, which is really unfortunate.

I think our best bet is to apply some sort of heuristic to determine if a render pass uses too much geometry and can't support memoryless textures. For now, you'll have to either reduce the amount of geometry in a scene or turn off MSAA.

**Comment by romainguy** [comment]
19k triangles doesn't seem that much though

**Comment by bejado** [comment]
I agree. Perhaps it has to do with the number of buffers used in a render pass. I need to experiment more.

As another workaround, you can change `MTLResourceStorageModeMemoryless` to `MTLResourceStorageModePrivate` [here](https://github.com/google/filament/blob/ceced43e9314fde6a953d99e940a7a138306c292/filament/backend/src/metal/MetalHandles.mm#L870).

**Comment by tottero** [comment]
Thanks for looking into this. Coming up with an acceptable heuristic seems to be difficult. The error most likely depends on the number of buffers (as you noted) but devices with more RAM tend to produce the error at higher object/triangle count only. 

Unfortunately, turning off the MSAA is not an acceptable visual compromise.

Changing the storage mode to MTLResourceStorageModePrivate has a major memory impact during rendering on all the scenes. Ideally, in my opinion, whenever the memoryless mode fails the engine should fall back to use the private mode instead.

What do you think?

**Comment by bejado** [comment]
We could try to render a frame using memoryless render targets, check if the command buffer fails, and if so, switch to private mode instead for the next frame. This would lead to skipped frames though, which isn't ideal either.

**Comment by bejado** [comment]
> Changing the storage mode to MTLResourceStorageModePrivate has a major memory impact during rendering on all the scenes.

@tottero Can you give more details on this? How much of a memory impact, and what types of scenes are you rendering?
