### ISSUE TITLE
IOS Memory too high

### ISSUE THREAD

**Issue by lichentao** [google/filament#4206]
when i use filament to render glb obj ,the memory is grow up fast

**Comment by romainguy** [comment]
Could you provide more details please? Decoding and rendering a glTF file will require a lot of memory allocations. Is the problem that memory usage keeps going up (leak)? Or just that the baseline is too high?

**Comment by pixelflinger** [comment]
Also can your share the glb with us?

**Comment by lichentao** [comment]
sorry ,double check cpu high is our code cause

**Comment by lichentao** [comment]
GLTF file too big. phone  get  amount of heat
