### ISSUE TITLE
[Feature request] The possibility of dolls system(Avatar/Custom Character)?

### ISSUE THREAD

**Issue by allenhsu-17live** [google/filament#4220]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Is there any teaching or any example that can be done like a custom doll system.
It means that I can dynamically load many model components, and these components can be dynamically added or deleted on the character ?

**Describe the solution you'd like**

like this : https://www.youtube.com/watch?v=Ch1aJljEYp4
And not only change texture, I think we can add equipment and other models

**Describe alternatives you've considered**

**OS and backend**
Is this feature OS/backend specific? If so, explain why.

**Comment by romainguy** [comment]
Please open a discussion for this kind of questions, thank you!
