### ISSUE TITLE
Could not find autoScaleEnabled and clearRootTransform 

### ISSUE THREAD

**Issue by PritishSawant** [google/filament#4224]
**Describe the bug**
For the android gltf viewer sample I am getting error for autoScaleEnabled and clearRootTransform

**To Reproduce**
Import the gltf viewer sample for android

**Screenshots**
![image](https://user-images.githubusercontent.com/24708929/123949363-1ab5c380-d9c0-11eb-8b87-23abb9e850af.png)

**Desktop (please complete the following information):**
 - OS: Android
 - GPU: N/A
 - Backend: N/A

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 10

**Comment by prideout** [comment]
This a build issue, do a clean build.  We provide an aggressive clobber utility in our easy build script (`./build.sh -c`)
