### ISSUE TITLE
Question about linking against imageio

### ISSUE THREAD

**Issue by Joaopmoliveira** [google/filament#4226]
To link the image::ImageEncoder class I assume the imageio library is required. Which other third party and internal libs are also required? Or are they all bundled into the imageio static library? 
While trying to replicate the samples you provide I obtain a couple of linking errors. I also tried including the png library but the visual studio compiler still complains about not finding some definitions, i.e. png_reset_zstream, png_compare_ICC_profile_with_sRGB, ...

**Comment by prideout** [comment]
libpng is a requirement, so if it's not finding the `png_reset_zstream` definition then something's wrong; make sure you're using the copy of libpng that's in our tree.

imageio also depends on libz, tinyexr, stb.

(If you have IMAGEIO_SUPPORTS_BLOCK_COMPRESSION enabled then you also need astcenv and EtcLib from our repo)

**Comment by Joaopmoliveira** [comment]
Exactly as you said, once I included tinyexr and libz everything worked (I saw them in the targets of the imageio library but hasn't sure if they were required to add by hand or if they were bundled). The only strange thing is that I needed to also add the ws2_32.lib which contains the definition for __imp__htonl. (in case someone is also faced with the same problem in the future)
Thank you!
