### ISSUE TITLE
[Android] Render::readPixels get nothing in the buffer

### ISSUE THREAD

**Issue by RockVampire** [google/filament#4229]
I'm trying to get the frame raw data by the method 'readPixels' in Renderer like this on Android.

```
        Buffer buffer = ByteBuffer.allocateDirect(mView.getViewport().width * mView.getViewport().height * 4);
        buffer.clear();
        Texture.PixelBufferDescriptor descriptor = new Texture.PixelBufferDescriptor(buffer,Texture.Format.RGBA,Texture.Type.UBYTE);

        // Render the scene, unless the renderer wants to skip the frame.
        if (mRenderer.beginFrame(mSwapChain, frameTimeNanos)) {
            mRenderer.render(mView);
            mRenderer.readPixels(0,0,mView.getViewport().width,mView.getViewport().height,descriptor);
            mRenderer.endFrame();
        }
```

And I also tried to do this in native method like this 

```
if (m_renderer->beginFrame(m_swap_chain)) {
    m_renderer->render(m_view);
    m_renderer->readPixels(0, 0, width, height, std::move(pbd));
    m_renderer->endFrame();
    // todo: todo keria, bad performance here...
    m_engine->flushAndWait();
}
```
But all the buffer I have gotten are full of zero, same as something happend here https://github.com/google/filament/issues/4077

I read the notes of 'readPixels', it said the method is  " intended for debugging and testing" .
Now , I'm trying doing something about AR living room with filament.
In order to pushing the stream to the server , I want to get the frame raw data from filament  and then mix it with data from camera before pushing them to the server.
Do I have any other choice to get the frame raw data from filament.

**Comment by bejado** [comment]
If you clear your `Buffer` with `0xFF` before passing it to `readPixels`, are you still getting zeroes? You should also make sure your SwapChain is created with the `SwapChain::CONFIG_READABLE` flag.

**Comment by romainguy** [comment]
Note that on the Java side the Buffer needs to be marked with the native byte order.

**Comment by RockVampire** [comment]
Thanks for your answer , It helps a lot .Now I can get the pixel buffer.
I mentioned in the question, the method is "intended for debugging an testing".Now I'm looking for something can be really used.I saw https://github.com/google/filament/issues/1899 and it seems filament can processing the scene with a textureID.
Does any demo or project can show how it works and, in that way how can I init filament.

**Comment by romainguy** [comment]
On Android the best thing to do is render into a Surface. These can come from a surface view, a surface texture (to share the result as a texture with another renderer), a movie encoder etc.

**Comment by dandingol03** [comment]
Hi, i met the same problem. I invoke the `readPixels` in `jni`. How do you get the pixel buffer? What is your current solution? @RockVampire

**Comment by caorm** [comment]
Hi, i met the same problem. I invoke the readPixels in jni. How do you get the pixel buffer? What is your current solution? @RockVampire @romainguy

 // Render the scene, unless the renderer wants to skip the frame.
        if (renderer.beginFrame(swapChain!!, frameTimeNanos)) {
            renderer.render(view)
            if(isScreenShot) {
                takeScreenShot();
                isScreenShot = false;
            }
            renderer.endFrame()
        }


fun takeScreenShot() {
        val width = textureView?.width ?: 0
        val height = textureView?.height ?: 0
        val size = width * height * 4;

        val imageBuffer = ByteBuffer.allocateDirect(size)
        imageBuffer.clear()

        val pixelBuffer: Texture.PixelBufferDescriptor? =
            Texture.PixelBufferDescriptor(imageBuffer, Texture.Format.RGBA, Texture.Type.UBYTE)

        if (pixelBuffer != null) {
            renderer.readPixels(0, 0, width, height, pixelBuffer)

            val viewBitmap: Bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)

            val pixels = IntArray(width * height)
            val tempBuffer = pixelBuffer.storage as ByteBuffer
            for (i in 0 until width * height) {
                pixels[i] = tempBuffer.get().toInt()
            }
            viewBitmap.setPixels(pixels, 0, width, 0, 0, width, height)

            val imageFile = File.createTempFile("textureview_screenshot", ".png", externalCacheDir)
            if (imageFile.exists()) {
                imageFile.delete()
            }

            var outputStream: OutputStream? = null
            try {
                outputStream = FileOutputStream(imageFile)
                viewBitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream)
                outputStream.flush()
                outputStream.close()
            } catch (e: FileNotFoundException) {
                e.printStackTrace()
            } catch (e: IOException) {
                e.printStackTrace()
            }
        }
    }

PixelBufferDescriptor storage Attributes is zero，why？thinks！

**Comment by caorm** [comment]
Hi, i met the same problem. I invoke the readPixels in jni. How do you get the pixel buffer? What is your current solution? 
@dandingol03 

I want to screenshot a image， but  PixelBufferDescriptor storage Attributes  get is zero？ 
Do you know where is the problem with the code below?

// Render the scene, unless the renderer wants to skip the frame.
if (renderer.beginFrame(swapChain!!, frameTimeNanos)) {
renderer.render(view)
if(isScreenShot) {
takeScreenShot();
isScreenShot = false;
}
renderer.endFrame()
}

fun takeScreenShot() {
val width = textureView?.width ?: 0
val height = textureView?.height ?: 0
val size = width * height * 4;

    val imageBuffer = ByteBuffer.allocateDirect(size)
    imageBuffer.clear()

    val pixelBuffer: Texture.PixelBufferDescriptor? =
        Texture.PixelBufferDescriptor(imageBuffer, Texture.Format.RGBA, Texture.Type.UBYTE)

    if (pixelBuffer != null) {
        renderer.readPixels(0, 0, width, height, pixelBuffer)

        val viewBitmap: Bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)

        val pixels = IntArray(width * height)
        val tempBuffer = pixelBuffer.storage as ByteBuffer
        for (i in 0 until width * height) {
            pixels[i] = tempBuffer.get().toInt()
        }
        viewBitmap.setPixels(pixels, 0, width, 0, 0, width, height)

        val imageFile = File.createTempFile("textureview_screenshot", ".png", externalCacheDir)
        if (imageFile.exists()) {
            imageFile.delete()
        }

        var outputStream: OutputStream? = null
        try {
            outputStream = FileOutputStream(imageFile)
            viewBitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream)
            outputStream.flush()
            outputStream.close()
        } catch (e: FileNotFoundException) {
            e.printStackTrace()
        } catch (e: IOException) {
            e.printStackTrace()
        }
    }
}
PixelBufferDescriptor storage Attributes is zero，why？thinks！
