### ISSUE TITLE
Strange roughness in redball web demo

### ISSUE THREAD

**Issue by prideout** [google/filament#423]
There's a visual aberration in the redball JS tutorial... half the ball is more rough than the other half.  Not sure yet if this is an app issue (bad normals?) or a WebGL-specific issue (shader compiler bug?) or an actual bug in Filament's shaders.

![redball2](https://user-images.githubusercontent.com/1288904/47449357-4bf18680-d777-11e8-90df-105e41c52666.gif)

I'm less worried about the dark spot, we probably just need to adjust the IBL / sun position in the demo.

**Comment by romainguy** [comment]
This looks like a broken ibl. What happens with roughness 0?

**Comment by prideout** [comment]
After removing the IBL, the specular highlight still changes shape strangely:

![redball3](https://user-images.githubusercontent.com/1288904/47453164-e4403900-d780-11e8-977b-cf5c332b8eeb.gif)

**Comment by prideout** [comment]
Next I'll try visualizing normals, since my spheregen code could be bad...
