### ISSUE TITLE
Gltfio : Skinning - Some wrong bones influence

### ISSUE THREAD

**Issue by ThomasGorisse** [google/filament#4236]
Hi,

I have a strange skinning behavior.

It seems that there is little gap between some bones influences on some vertex groups:

![GIF 02-07-2021 17-13-59](https://user-images.githubusercontent.com/6597529/124296723-92b7f100-db5a-11eb-85ba-ffd50884b324.gif)

Everything seems OK when rendering it from Blender or [Kronos sample model viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/)

![image](https://user-images.githubusercontent.com/6597529/124296976-db6faa00-db5a-11eb-99be-c54b3e9f674e.png)

![GIF 02-07-2021 17-24-13](https://user-images.githubusercontent.com/6597529/124296521-5ab0ae00-db5a-11eb-839b-a2936f98393b.gif)

I can't see it on the web Filament model viewer since the camera is in the wrong orientation.

Do you have an idea of where it could come from?

**Comment by ThomasGorisse** [comment]
OK.

I figure out that disabling the 
```
Blender > Export > gltTF 2.0
   v Animation
      v Skinning
         x Include All Bone Influences
```
 is the way to go.

![GIF 02-07-2021 18-14-07](https://user-images.githubusercontent.com/6597529/124302359-681d6680-db61-11eb-921c-77a22bca7000.gif)

_Now I have to make my animation more natural_

**Comment by romainguy** [comment]
There's a limit on the number of influences a vertex can receive, I imagine that's what you are running into. @prideout

**Comment by prideout** [comment]
Hard to tell what's going on without looking at your gltf file, but here are our known skinning limitations:

- Filament supports only one vec4 joints/weights set (however this conforms with the glTF spec).
- Filament does not support shearing in the bone matrix, where shearing is defined as rotation + non_uniform_scale + rotation.

**Comment by prideout** [comment]
This is not actionable unless we have a repro model to work with.
