### ISSUE TITLE
Glitches in Chrome

### ISSUE THREAD

**Issue by keaukraine** [google/filament#4251]
Web demos in Chrome 91.0.4472.124 on Windows 10 produce graphical glitches at the top part of viewport:

https://user-images.githubusercontent.com/414072/124750302-f876f500-df2d-11eb-8575-291cc85ab8d2.mp4

No errors in console.

Sometimes after refreshing page glitches disappear.

**Comment by cx20** [comment]
Probably the same phenomenon as below.
https://github.com/google/filament/issues/3151

**Comment by prideout** [comment]
This is a known issue with NVIDIA, duplicate of #3151.

**Comment by cx20** [comment]
@keaukraine 
I don't know if it's the right way, but to get around this glitch on NVIDIA GPUs, you may be able to improve it by calling `setClearOptions` function.

https://github.com/google/filament/discussions/3670#discussioncomment-506371

**Comment by keaukraine** [comment]
Thank you for explaining the cause of this glitch!
