### ISSUE TITLE
Vulkan: texture filtering looks wrong (Qualcomm)

### ISSUE THREAD

**Issue by prideout** [google/filament#4253]
On a Pixel 4, load up bistro and disable scale-to-unit cube to move the camera close to the floor.  Does not occur on Mali devices or MoltenVK.

The can also be reproduced using the default BusterDrone model, just zoom in to the floor.  GL and Vulkan comparisons are attached.

![OpenGL](https://user-images.githubusercontent.com/1288904/124803260-bb026f80-df0d-11eb-88d1-ff72166bd01c.png)
![Vulkan](https://user-images.githubusercontent.com/1288904/124803266-bdfd6000-df0d-11eb-9f0c-8603a69df2b4.png)

**Comment by prideout** [comment]
See also https://github.com/google/filament/issues/2524

**Comment by prideout** [comment]
This issue still occurs even after unconditionally adding the `-g` arg to matc, both for Filament's built-in materials and gltfio materials.

**Comment by pixelflinger** [comment]
When you tested with `-g` did you do a "Real clean build", using the `-C` option? I've been bit by that before.

**Comment by romainguy** [comment]
It looks like one texture is in NEAREST, it shouldn't be related to `matc`.

**Comment by pixelflinger** [comment]
No it shouldn't, but I've seen a similar problem before related to material optimization, so did an external developer. There is obviously a bug in the compiler somewhere.

**Comment by prideout** [comment]
When I substitute the texture with a small 100x100 version, the result is good, you can tell it is doing LINEAR interpolation.

However when I use a large texture and zoom in, the NEAREST problem comes back.

I tried simplifying the ubershader by removing the texture matrix and the problem still occurs.

Very strange!

**Comment by romainguy** [comment]
Then it might be an fp16 issue. If the texture is > 1024 we can't have sub-pixel UVs, which would explain the lack of filtering. It would also explain why `-g` fixes it.
