### ISSUE TITLE
Android RenderableManager::setGeometryAt call lost material in v1.9.8

### ISSUE THREAD

**Issue by PsycoTodd** [google/filament#4259]
**Describe the bug**
I try to implement a feature to replace a loaded gltf model's mesh in filament by calling `setGeometryAt(Instance instance, size_t primitiveIndex, PrimitiveType type, VertexBuffer* vertices, IndexBuffer* indices, size_t offset, size_t count)`. 

I am able to switch the geometry while get the object still rendered with the original material on Mac with cpp built filament library.

But If I do this on android once the `setGeometryAt` is called, nothing renders. The loaded model just disappear. 

**To Reproduce**
1. ...

**Expected behavior**
After calling setGeometryAt, I should see the gltf model still rendered with its previous material. Just the geometry changes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - GPU: Intel Iris Plus Graphics 655
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9

**Additional context**

**Comment by prideout** [comment]
To summarize, calling `setGeometryAt` on a fully loaded model works fine on macOS, but on Android it causes the geometry to disappear.  Is that correct?

Are you sure you're doing this on a fully loaded model (asyncGetLoadProgress >= 1.0)?

Is there a simple modification that we can make to our sample code (e.g. in `sample-gltf-viewer`) to reproduce the issue?

**Comment by PsycoTodd** [comment]
To summarize, calling setGeometryAt on a fully loaded model works fine on macOS, but on Android it causes the geometry to disappear. Is that correct?

**Correct. Right now I feel it related to the material instance**

Are you sure you're doing this on a fully loaded model (asyncGetLoadProgress >= 1.0)?

**Yes, on my android device, I first draw the original mesh for 3 seconds, then call update mesh.**

Is there a simple modification that we can make to our sample code (e.g. in sample-gltf-viewer) to reproduce the issue?

**I did it in my own project with dependency on filament android library. I will try to change sample-gltf_viewer with call to setGeometryAt.**

**Comment by pixelflinger** [comment]
Are you using C++ or Java/Kotlin on Android for the setGeometryAt call?

**Comment by PsycoTodd** [comment]
Are you using C++ or Java/Kotlin on Android for the setGeometryAt call?

**I tired two ways. my original implementation is to call `setGeometryAt` in cpp by some java interface. In the sample-gltf_viewer demo, I directly call the java version.**

I notice one warning actually when I do this. 
` W/Filament: [instance=3, primitive @ 0] missing required attributes (0x1f), declared=0xb` 

There is possibility that I just try to setGeometry with position(float3), normal(float3) and uv(float2), which might not be the internal attribute arrangement that cgltf load the gltf model and set as. In this case, the `setGeometryAt` might fail?

May I know what is the attribute type and layout internally when we load gltf model?

**Comment by PsycoTodd** [comment]
**Update**: I think I notice that in the `AssetLoader.cpp` there is some dummy attributes [uv1, color]. And when we call setGeometryAt function we need to also pack these dummy data by the client. 

If I pack the dummy attributes, then the warning is gone:
W/Filament: [instance=3, primitive @ 0] missing required attributes (0x1f), declared=0xb

**Comment by PsycoTodd** [comment]
**It is indeed the problem**

 I have to make sure that the required attributes [uv0, uv1, color] for android has been there in the vertexbuffer I passed in when call setGeometryAt.
 
 Specifically, I have to provide the dummy data, even I don't use them for android. 

```c++
 uint32_t size = sizeof(filament::math::ubyte4) * vertexBuffer.vertexCount();
  uint32_t* dummyData = (uint32_t*) malloc(size);
  memset(dummyData, 0xff, size);
  static const auto FREE_CALLBACK = [](void* mem, size_t, void*) { free(mem); };
  filament::VertexBuffer::BufferDescriptor bd(dummyData, size, FREE_CALLBACK);
  int slot = attributes.tangent.index + 1;
  buffer->setBufferAt(engine, slot, std::move(bd));
```

**Comment by PsycoTodd** [comment]
Then it is general that when client call `setGeometryAt`, how do they know the dummy data for uber shader without reading the `AssetLoader.cpp`?

**Comment by pixelflinger** [comment]
@prideout might be able to answer better than I.

**Comment by prideout** [comment]
Ah, this explains the difference between Android and macOS, we use `UbershaderLoader` by default on Android whereas desktop platforms use `MaterialGenerator` by default.

I'm glad you found the issue, sounds like we can close this bug and start a discussion if necessary.  Here are some tips:

- Use `MaterialProvider::needsDummyData` (implemented by `UbershaderLoader`) to find out which attributes need to be provided with dummy data if they don't exist.
- Use `RenderableManager::getEnabledAttributesAt` to find out which attributes are enabled in a given primitive.

**Comment by PsycoTodd** [comment]
Thanks!
