### ISSUE TITLE
Build fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by obeletski** [google/filament#426]
Compilation fails on Ubuntu 14.04
cmake version 3.4.1
ninja 1.8.2
clang 5.0 and 6.0 tried

See logs below

Running easy build: ./build.sh release
Building release in out/cmake-release...
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang-6.0
-- Found Java: /usr/lib/jvm/java-8-openjdk-amd64/bin/java (found version "1.8.0.171") 
-- Found JNI: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjawt.so  
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/webteam/opensource/filament/out/cmake-release
......

[159/973] Building CXX object third_party/spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/val/validate.cpp.o
FAILED: third_party/spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/val/validate.cpp.o 
/usr/bin/clang++-6.0   -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -I../../third_party/spirv-tools/source -I../../third_party/spirv-tools -I../../third_party/spirv-tools/include -Ithird_party/spirv-tools -I../../third_party/spirv-tools/external/spirv-headers/include -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -fPIC   -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-self-assign -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -MMD -MT third_party/spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/val/validate.cpp.o -MF third_party/spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/val/validate.cpp.o.d -o third_party/spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/val/validate.cpp.o -c ../../third_party/spirv-tools/source/val/validate.cpp
In file included from ../../third_party/spirv-tools/source/val/validate.cpp:15:
In file included from ../../third_party/spirv-tools/source/val/validate.h:18:
In file included from /usr/include/c++/v1/functional:474:
/usr/include/c++/v1/type_traits:433:83: error: no matching function for call to '__source'
    : public integral_constant<bool, sizeof(__libcpp_is_function_imp::__test<_Tp>(__libcpp_is_function_imp::__source<_Tp>())) == 1>
                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/type_traits:438:14: note: in instantiation of template class 'std::__1::__libcpp_is_function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (unsigned int) const, false>' requested here
    : public __libcpp_is_function<_Tp> {};
             ^
/usr/include/c++/v1/type_traits:443:97: note: in instantiation of template class 'std::__1::is_function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (unsigned int) const>' requested here
template <class _Tp, class _Up> struct __libcpp_is_member_function_pointer<_Tp _Up::*> : public is_function<_Tp> {};
                                                                                                ^
/usr/include/c++/v1/type_traits:446:14: note: in instantiation of template class 'std::__1::__libcpp_is_member_function_pointer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const>' requested here
    : public __libcpp_is_member_function_pointer<typename remove_cv<_Tp>::type> {};
             ^
/usr/include/c++/v1/type_traits:3094:17: note: in instantiation of template class 'std::__1::is_member_function_pointer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const>' requested here
                is_member_function_pointer<typename remove_reference<_Fp>::type>::value &&
                ^
/usr/include/c++/v1/type_traits:3101:1: note: in instantiation of default argument for '__invoke<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const, spvtools::val::ValidationState_t &, unsigned int &>' required here
__invoke(_Fp&& __f, _A0&& __a0, _Args&& ...__args)
^~~~~~~~
/usr/include/c++/v1/type_traits:3147:13: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
            __invoke(_VSTD::declval<_Fp>(), _VSTD::declval<_Args>()...)
            ^
/usr/include/c++/v1/functional:1973:31: note: in instantiation of template class 'std::__1::__invokable<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const, spvtools::val::ValidationState_t &, unsigned int &>' requested here
    static const bool value = __invokable<_Fp,
                              ^
/usr/include/c++/v1/functional:1985:18: note: in instantiation of template class 'std::__1::_is_valid_bind_return<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const, std::__1::tuple<std::__1::reference_wrapper<spvtools::val::ValidationState_t>, std::__1::placeholders::__ph<1> >, std::__1::tuple<unsigned int &> >' requested here
          bool = _is_valid_bind_return<_Fp, _BoundArgs, _TupleUj>::value>
                 ^
/usr/include/c++/v1/functional:2082:18: note: in instantiation of default argument for '__bind_return<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const, std::__1::tuple<std::__1::reference_wrapper<spvtools::val::ValidationState_t>, std::__1::placeholders::__ph<1> >, std::__1::tuple<unsigned int &> >' required here
        typename __bind_return<_Fd, _Td, tuple<_Args&&...> >::type
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/algorithm:1925:21: note: while substituting deduced template arguments into function template 'operator()' [with _Args = <unsigned int &>]
        *__result = __op(*__first);
                    ^
../../third_party/spirv-tools/source/val/validate.cpp:165:8: note: in instantiation of function template specialization 'std::__1::transform<std::__1::__wrap_iter<unsigned int *>, std::__1::ostream_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char, std::__1::char_traits<char> >, std::__1::__bind<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const, std::__1::reference_wrapper<spvtools::val::ValidationState_t>, std::__1::placeholders::__ph<1> &> >' requested here
  std::transform(
       ^
/usr/include/c++/v1/type_traits:424:28: note: candidate template ignored: substitution failure [with _Tp = std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (unsigned int) const]: reference to function type 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (unsigned int) const' cannot have 'const' qualifier
template <class _Tp> _Tp&  __source();
                     ~~~   ^
In file included from ../../third_party/spirv-tools/source/val/validate.cpp:15:
In file included from ../../third_party/spirv-tools/source/val/validate.h:21:
In file included from /usr/include/c++/v1/vector:265:
In file included from /usr/include/c++/v1/__bit_reference:15:
/usr/include/c++/v1/algorithm:1925:21: error: no matching function for call to object of type 'std::__1::__bind<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const, std::__1::reference_wrapper<spvtools::val::ValidationState_t>, std::__1::placeholders::__ph<1> &>'
        *__result = __op(*__first);
                    ^~~~
../../third_party/spirv-tools/source/val/validate.cpp:165:8: note: in instantiation of function template specialization 'std::__1::transform<std::__1::__wrap_iter<unsigned int *>, std::__1::ostream_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char, std::__1::char_traits<char> >, std::__1::__bind<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const, std::__1::reference_wrapper<spvtools::val::ValidationState_t>, std::__1::placeholders::__ph<1> &> >' requested here
  std::transform(
       ^
/usr/include/c++/v1/functional:2083:9: note: candidate template ignored: substitution failure [with _Args = <unsigned int &>]: implicit instantiation of undefined template 'std::__1::__bind_return<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*)(unsigned int) const, std::__1::tuple<std::__1::reference_wrapper<spvtools::val::ValidationState_t>, std::__1::placeholders::__ph<1> >, std::__1::tuple<unsigned int &>, false>'
        operator()(_Args&& ...__args)
        ^
/usr/include/c++/v1/functional:2092:9: note: candidate template ignored: substitution failure [with _Args = <unsigned int &>]: implicit instantiation of undefined template 'std::__1::__bind_return<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (spvtools::val::ValidationState_t::*const)(unsigned int) const, const std::__1::tuple<std::__1::reference_wrapper<spvtools::val::ValidationState_t>, std::__1::placeholders::__ph<1> >, std::__1::tuple<unsigned int &>, false>'
        operator()(_Args&& ...__args) const
        ^
2 errors generated.
[200/973] Building CXX object third_party/spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/val/validation_state.cpp.o
ninja: build stopped: subcommand failed.

**Comment by romainguy** [comment]
Which version of libc++-dev do you have?

**Comment by obeletski** [comment]
Looks like 1.0

apt show libc++-dev 
Package: libc++-dev
Priority: extra
Section: universe/libdevel
Installed-Size: 5 873 kB
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
Source: libc++
Version: 1.0~svn199600-1
Provides: libstdc++-dev
Depends: libc++1 (= 1.0~svn199600-1), libc++-helpers
Download-Size: 553 kB
Homepage: http://libcxx.llvm.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
APT-Manual-Installed: yes
APT-Sources: http://fi.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
Description: LLVM C++ Standard library (development files)
 libc++ is a new implementation of the C++ standard library, targeting C++11.
 .
 Features and Goals
 .
   * Correctness as defined by the C++11 standard.
   * Fast execution.
   * Minimal memory use.
   * Fast compile times.
   * ABI compatibility with gcc's libstdc++ for some low-level features such
     as exception objects, rtti and memory allocation.
   * Extensive unit tests.

**Comment by romainguy** [comment]
You'll need a newer version of that library. We have to build our own in CI on Ubuntu 14 (you can check the script in build/linux).

**Comment by obeletski** [comment]
I was suspecting that problem was in C++ headers. I will check your scripts, thanks.

**Comment by romainguy** [comment]
Were you able to fix this issue btw?

**Comment by obeletski** [comment]
Thanks, CI script help to fix the problem. Since last week I moved to Ubuntu 18.04 that get delivers correct version of all the components out of the box. The only inconvenience that is left is the need to specify manually -DFILAMENT_REQUIRES_CXXABI=true for cmake if I want to rebuild from scratch everything. It is document though.

**Comment by romainguy** [comment]
`FILAMENT_REQUIRES_CXXABI` is unfortunate, I'd love to find a way to figure this one out automatically. I'm not sure what to use to decide when to set it.
