### ISSUE TITLE
Metal performance seems not better than OpenGL in iOS

### ISSUE THREAD

**Issue by JiangXiaotian** [google/filament#4271]
**Describe the bug**
I tried iOS sample hello-gltf app，
metal-backend gpu frame time is 7.5 ms, while opengl-backend gpu frame time is 6.8ms.
the rendering time of opengl is also shorter than that of metal  in instrument->GamePerformance.

**To Reproduce**
just change backend, both of them "build configuration" choose release.

**Expected behavior**
metal performance better than opengl

**Screenshots**
<img width="1334" alt="截屏2021-07-08 下午4 34 26" src="https://user-images.githubusercontent.com/29564832/124899574-d86d3180-e012-11eb-8421-ad2855ea555d.png">
<img width="1321" alt="截屏2021-07-08 下午4 34 57" src="https://user-images.githubusercontent.com/29564832/124899582-db682200-e012-11eb-8e8d-040c082164a4.png">
<img width="1075" alt="截屏2021-07-08 下午4 38 37" src="https://user-images.githubusercontent.com/29564832/124899611-e28f3000-e012-11eb-9a67-e96f605b56a9.png">
<img width="1167" alt="截屏2021-07-08 下午4 50 15" src="https://user-images.githubusercontent.com/29564832/124899628-e458f380-e012-11eb-8ef9-6d7428fbfed5.png">
<img width="879" alt="截屏2021-07-08 下午5 22 35" src="https://user-images.githubusercontent.com/29564832/124899630-e58a2080-e012-11eb-9130-a2a0c92e416c.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Backend: [Metal/OpenGL]

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: 13.7

**Comment by romainguy** [comment]
What are you rendering? With a scene with not many draw calls and mostly shader bound there's no reason for Metal to be faster if you look at vertex/fragment processing time on the GPU.

**Comment by romainguy** [comment]
Also note that as long as you are under 16ms the GPU is probably not clocked as high at it can be, so exact timings are not really comparable.

**Comment by JiangXiaotian** [comment]
I re-used a glb with 980018 vertices and 100011 faces on iphone 7 for test. And I enabled bloom, AmbientOcclusion, and fxaa. The result still seems to be that metal is not faster than opengl, and even the cpu usage rate of metal is 42%. , OpengGL is only 17%. 

I tested it in  iOS hello-gltf sample, the Screenshot below is the code I changed.
<img width="827" alt="截屏2021-07-10 上午2 17 26" src="https://user-images.githubusercontent.com/29564832/125120412-02167d80-e125-11eb-97a8-7aa986c83a8a.png">

glb link: https://drive.google.com/file/d/1xwKpoiMxDfhLc8lMpknbA7w-VZRkrgvg/view?usp=sharing
hello-gltf sample link: https://drive.google.com/file/d/1FT5adwJNCW1LU4CxTnKVUdrl2liO1934/view?usp=sharing

<img width="1479" alt="截屏2021-07-10 上午1 39 51" src="https://user-images.githubusercontent.com/29564832/125118635-8fa49e00-e122-11eb-8667-1e5768e9bf32.png">

<img width="1478" alt="截屏2021-07-10 上午1 39 04" src="https://user-images.githubusercontent.com/29564832/125118629-8ddada80-e122-11eb-8e48-f30286dcb19b.png">

**Comment by romainguy** [comment]
For this use case, there's no reason for Metal to be faster than GL on the GPU. CPU usage should/could be the same or better though, looks like we have improvements to make.

**Comment by JiangXiaotian** [comment]
Is it convenient to give an example Metal is faster than GL?

**Comment by JiangXiaotian** [comment]
Is it recommended to use opengl instead of metal even in iOS?

**Comment by bejado** [comment]
There are a handful of optimizations I'm working on to improve both CPU and GPU performance for Metal. You're welcome to use OpenGL, though the goal is to eventually remove support for it on Apple platforms.

**Comment by pixelflinger** [comment]
I would not recommend using the opengl backend on iOS (not macos) because we're planning to remove support soon.

Also when doing performance comparisons you need to also look at other factors like GPU/CPU clocks. Sometimes, when some code is more optimized it runs slower but at a lower power usage. As long as rendering happens in less than the vsync rate, there is no problem.

And finally, there is no reason for metal to be significantly faster or slower than gl, it's the same GPU in the end.

**Comment by JiangXiaotian** [comment]
> There are a handful of optimizations I'm working on to improve both CPU and GPU performance for Metal. You're welcome to use OpenGL, though the goal is to eventually remove support for it on Apple platforms.

Could you share your optimization idea in details? How much improvement could we expected, and in which scenarios we can expect big improvements, and how soon is the optimization expected to be completed?

**Comment by pixelflinger** [comment]
It won't be significantly faster than gl.

What kind of improvement are you hoping for?

**Comment by bejado** [comment]
This issue is a year-old and a bit vague, so closing. We do have some Metal-specific improvements in the pipeline, including using argument buffers to reduce CPU encoding time.
