### ISSUE TITLE
Enhancement: light channels

### ISSUE THREAD

**Issue by jwwalker** [google/filament#4275]
### Discussed in https://github.com/google/filament/discussions/3839

<div type='discussions-op-text'>

<sup>Originally posted by **jwwalker** April 22, 2021</sup>
Is there any way to make a geometry cast shadows from certain lights and not from other generally shadow-casting lights?  I'm guessing the answer is No, but figured I might as well ask.  If you wonder why I would want such a thing, I want to make an invisible mask to put in front of a spot light to change the shape of the beam.  And the reason I want to do THAT is to see if I can fake a shadow-casting point light by putting together 4 spot lights.</div>

**Comment by romainguy** [comment]
BTW would you like a renderable to be lit by a given light without casting shadows from that light?

**Comment by jwwalker** [comment]
@romainguy The ideal thing would be for the mask object to be invisible to the camera, but cast a shadow from just one light.  I can't remember whether I ever asked if it's possible for an invisible object to cast a shadow.  Maybe `MaterialInstance::setCullingMode(FRONT_AND_BACK)`, or does that prevent casting a shadow?

**Comment by romainguy** [comment]
You can simply use a material that doesn't write to the color buffer.

**Comment by jwwalker** [comment]
@romainguy If the material doesn't write to the color buffer or the depth buffer, would that still work?

**Comment by romainguy** [comment]
It should, you'd have to try :)

**Comment by jwwalker** [comment]
Fair enough, I'll put that on my to-do list.

**Comment by jwwalker** [comment]
Yes, something that does not write to either the color buffer or the depth buffer can cast a shadow.  So, I don't care whether a renderable that doesn't cast a shadow from a certain light is lit by that light or not, because in my case I won't see it at all.
