### ISSUE TITLE
Memory alloc issues in JS API

### ISSUE THREAD

**Issue by prideout** [google/filament#429]
JavaScript does not have finalizers or destructors, so embind requires JS clients to call `foo.delete()` on instances of stack-allocated wrapped objects, where `delete()` is a special object method added by embind itself.

Filament API objects are often heap allocated and explicitly destroyed anyway (eg `Engine::destroyMaterial`) so ideally users do not need to `delete()`. However there are a few places where Filament clients work with stack-allocated objects (e.g. builders).

We should (1) auto-delete builder wrappers upon `build()` and (2) write a leak test to help find other problems like this.

**Comment by romainguy** [comment]
That's exactly what we did in the Java bindings. Builders are automanaged but other types must be destroyed explicitly.
