### ISSUE TITLE
window10 build release branch failed

### ISSUE THREAD

**Issue by wolfand11** [google/filament#4304]
**Describe the bug**
build release branch failed

**To Reproduce**
1. cd d:/Documents/MyProject/Public/Graphics/filament/
2. git clone -b release https://github.com/google/filament.git ./
3. mkdir out
4. cd out 
5. cmake ..
error message ： CMake Error at third_party/glslang/tnt/CMakeLists.txt:96 (list):
  list GET given empty list

**Expected behavior**
build success

**Screenshots**
![image](https://user-images.githubusercontent.com/1425676/125411967-0b3b6f00-e3f1-11eb-8475-7994458164be.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - GPU: NVIDIA GTX 1050
 - Backend: OpenGL
 - CMake version: 3.20.5

**Comment by wolfand11** [comment]
i tried main branch and rc/1.10.7 ,  failed too.

**Comment by prideout** [comment]
This is more of a glslang build issue than a Filament issue. I think the `build_info.py` script is erroring out, so the GLSLANG_VERSIONS variable in the CMake is empty.

**Comment by bejado** [comment]
What version of CMake are you using?

**Comment by wolfand11** [comment]
@bejado cmake version is 3.20.5

**Comment by bejado** [comment]
Seems like this is a Python-related problem. I recommend filing an issue directly with [glslang](https://github.com/KhronosGroup/glslang).

**Comment by wolfand11** [comment]
@bejado  i clone and build glslang. it's success. thanks for any help. i'm not good at cmake. can't find any issue.

build glslang sucess.
![image](https://user-images.githubusercontent.com/1425676/125890802-d8c30ad0-459c-4469-8329-4ea6df0695ea.png)
![image](https://user-images.githubusercontent.com/1425676/125890830-515c92b2-69da-44f5-b1e6-2f1728d030e4.png)

**Comment by bejado** [comment]
I'm not sure why this isn't working for you, but I notice that our glslang `CMakeLists.txt` is out-of-date. For example, they no longer use Python to retrieve the GLSLANG version: https://github.com/KhronosGroup/glslang/commit/05798c17fb17d339d66e064a407e75ceae4c0316.

I'll update our CMakeLists.txt, which hopefully will fix the issue fo ryou.

**Comment by romainguy** [comment]
@bejado Can we update glslang while we're at it?

**Comment by bejado** [comment]
@romainguy I think we just did, but not the `CMakeLists.txt`.

**Comment by prideout** [comment]
Thanks for looking into this Ben, it's my fault, when I updated glslang I didn't notice this detail.
