### ISSUE TITLE
DynamicResolution and BlendMode.TRANSLUCENT compatibility issue

### ISSUE THREAD

**Issue by kpeeters** [google/filament#4306]
If I add a single line

    view.blendMode = View.BlendMode.TRANSLUCENT

to the end of the `setupView` function in e.g. the `MainActivity.kt` of the Android sample `sample-textured-object`, the result is that the view is just a uniformly filled screen with a colour which changes over time. It looks like the resolution has been set to 1x1 and was then upscaled to screen size, or something like that.

Turning off either translucent rendering or dynamic resolution produces the correct result.

This is on an old and slow Samsung SM-T585 (which is why I wanted to try dynamic resolution in the first place; my frame rate at full resolution is too low). On a Tab S6, the first few frames are messed up in the same way when both dynamic resolution and translucency are turned on, but after a while it 'catches up' and the rendering is correct. The slow tablet does not do that, not even when left to run for several minutes.

Note that while the fast tablet gets to a stage where every `beginFrame` returns `true`, the slow one never manages to get there, and still returns `false` for a substantial number of frames. Perhaps the resolution is scaled down until `beginFrame` returns true? That still does not explain why it works fine without translucent rendering though.

**Comment by pixelflinger** [comment]
I can reproduce easily on Android and on Desktop with this:
```
        View::DynamicResolutionOptions options;
        options.enabled = true;
        options.maxScale = 0.25f;
        options.minScale = 0.125f;
        options.homogeneousScaling = true;
        view->setDynamicResolutionOptions(options);
        view->setBlendMode(View::BlendMode::TRANSLUCENT);
```

**Comment by kpeeters** [comment]
#4310 fixed the rendering, thanks! However, it exposed a new issue: the bottom of my viewport is clipped when I turn blended views + dynamic scaling on (a black bar along the bottom of the screen). When I do a `setShift`, this clip changes and I can get values for which my left-hand side is also clipped. This looks *very* similar in spirit to  #3552 (for which I never managed to create a minimal example), where I saw that kind of clipping on shadows only, in that a a simple `setShift` clips the rendered output.

If it rings any bells, let me know. If not, I'll have another shot at a minimal example for this issue and #3552.

**Comment by kpeeters** [comment]
This was an issue with `MaterialInstance::setScissor` which behaved differently with and without dynamic resolution. Dropping that scissor (I didn't actually need it anymore) makes all ok again. You can close this issue, will followup in #3552 with some remaining puzzles.
