### ISSUE TITLE
Gltf animation is abnormal and can't control by index

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#4312]
I have a gltf model file, it have five animations.
I want to control any one of the animation's independent.

![image](https://user-images.githubusercontent.com/3060688/125572346-00bcb78a-f19a-446d-b97f-3b2d61bf32b4.png)

**I use below code,the animation is abnormal.**
`applyAnimation(0, elapsedTimeSeconds.toFloat())`
![image](https://user-images.githubusercontent.com/3060688/125572186-2f06665c-52ba-499b-8b1e-22621d85ff9a.png)

**Use the code below,there no any animation being show.**
```
applyAnimation(1, elapsedTimeSeconds.toFloat())
or
applyAnimation(3, elapsedTimeSeconds.toFloat())
```

The window 10 software 3D viewer and gltf-viewer in web can show all animation very well.

Thanks for any suggestion or other help.
The filament is very good and has helped me a lot with my work.

![image](https://user-images.githubusercontent.com/3060688/125572480-8af10f54-e64c-4ee1-ac46-9105ae576729.png)
I used the release v1.10.6 and the latest sample-gltf-view for test.
![image](https://user-images.githubusercontent.com/3060688/125572930-536bd2d6-f36a-40cf-a200-37602c6ee176.png)

Please rename morphtest.z01.zip to morphtest.z01 and do the same for others.
[morphtest.zip](https://github.com/google/filament/files/6813896/morphtest.zip)
[morphtest.z01.zip](https://github.com/google/filament/files/6813897/morphtest.z01.zip)
[morphtest.z02.zip](https://github.com/google/filament/files/6813898/morphtest.z02.zip)
[morphtest.z03.zip](https://github.com/google/filament/files/6813900/morphtest.z03.zip)
[morphtest.z04.zip](https://github.com/google/filament/files/6813901/morphtest.z04.zip)

**Comment by prideout** [comment]
@fanbinnet is this the same model that you attached to #4268?

**Comment by fanbinnet** [comment]
> @fanbinnet is this the same model that you attached to #4268?

Not exactly the same. We do some change for animations.
In #4268 , just one animation in the model, the new model we separated the animation of “D，L，R，U”

**Comment by prideout** [comment]
Note to self: on macOS you can we recombine the zip files with: `zip -s 0 morphtest.zip --out=unsplit.zip`

[unsplit.zip](https://github.com/google/filament/files/6824536/unsplit.zip)

**Comment by prideout** [comment]
babylonjs won't let me look at the model at all due to an error: "Offset is outside the bounds of the DataView"

At https://gltf-viewer.donmccurdy.com/, it doesn't look normal either.

**Comment by fanbinnet** [comment]
If this issues is still be anaylsing ？

**Comment by romainguy** [comment]
[gltf-transform](https://gltf-transform.donmccurdy.com/cli.html) shows a bunch of errors in the model when running the validator (`MESH_PRIMITIVE_MORPH_TARGET_INVALID_ATTRIBUTE_COUNT`).
