### ISSUE TITLE
Support GL_ARM_shader_framebuffer_fetch on Mali GPU

### ISSUE THREAD

**Issue by fishelegs** [google/filament#4313]
**Describe the bug**
On ARM's mali GPU OpenGL extension "GL_EXT_shader_framebuffer_fetch" may not be supported.
Will filament support GL_ARM_shader_framebuffer_fetch on Mali's GPU.

OpenGLContext.cpp:
    ext.EXT_shader_framebuffer_fetch = hasExtension(exts, "GL_EXT_shader_framebuffer_fetch");

**Smartphone :**
 - Device: Android mobile phone supports GL_ARM_shader_framebuffer_fetch. 
 https://opengles.gpuinfo.org/listreports.php?extension=GL_ARM_shader_framebuffer_fetch

**Comment by prideout** [comment]
Filament works fine on devices that do not support that extension.  If the extension is supported, then Filament enables an optimized codepath for color grading.
