### ISSUE TITLE
Manipulating the camera position

### ISSUE THREAD

**Issue by rally-zach** [google/filament#4318]
I'm attempting to modify the gltf_viewer.cpp sample to add some camera repositioning on key press. I got the keypress functionality registering but I can't figure out how to access the cameras being used from the gltf_viewer.cpp file. How can I access them (especially the main camera being used) and how can I tell them to update the position to a new position? Bonus points if I can animate between positions.

So far I've considered adding a getter method to the Window class that passes the main camera object back but that doesn't seem right. I have also considered using bookmarks but when I try to access `.flight` from inside the gltf_viewer.cpp file it says I don't have access because the property is private, even if I am creating the bookmark right before trying to set the property.

**Comment by bejado** [comment]
The gltf_viewer code is mainly for our testing and isn't the best structured, but you should be able to access the main camera via [app.mainCamera](https://github.com/google/filament/blob/17d67f2a390f8193d8b00ae9e7505b2a816960c5/samples/gltf_viewer.cpp#L494).

You can set the position via 

```
auto entity = app.mainCamera->getEntity();
auto& tcm = engine->getTransformManager();
tcm.setTransform(tcm.getInstance(entity), transform);
```

**Comment by romainguy** [comment]
Please use discussions for this instead of opening issues.

**Comment by rally-zach** [comment]
> Please use discussions for this instead of opening issues.

Oops, didn't see those. Thanks for the suggestion.

> You'll probably need to also disable the camera manipulators in FilamentApp.cpp otherwise they'll override the position.

I'm not seeing a disable method. Do you mean commenting out all of the relevant lines creating/referencing the manipulators or something else? Commenting out those lines, it updates the camera for a frame then jumps to a blank screen.

**Comment by bejado** [comment]
You can disable camera manipulation by commenting out [this line](https://github.com/google/filament/blob/0dd04f6e734baaa584be90cc043b3e4ed1e501d2/libs/filamentapp/src/FilamentApp.cpp#L370):

```
        // Update the position and orientation of the two cameras.
        filament::math::float3 eye, center, up;
        window->mMainCameraMan->getLookAt(&eye, &center, &up);
        //window->mMainCamera->lookAt(eye, center, up);
```

**Comment by rally-zach** [comment]
Thanks a lot, @bejado! That did the trick.
