### ISSUE TITLE
Unable to load glb model in Android with sceneform using filament

### ISSUE THREAD

**Issue by udayk07** [google/filament#4331]
Issue : https://github.com/google/filament/issues/3986

Tried to load car.zip with latest filament update 1.10.6 and facing crash issue. It throws "OpenGL backend handle arena is full" error in console ( attached crash log )

[filament_crash_log.txt](https://github.com/google/filament/files/6830467/filament_crash_log.txt)

Is there any common workaround to load models like car.zip ?

**Comment by pixelflinger** [comment]
This issue is related to #2057.

The only workaround at this time is to increase `FILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB` to at least 4MB (maybe more) and recompile.
