### ISSUE TITLE
Web viewer will fail if the glTF model contains relative paths

### ISSUE THREAD

**Issue by cx20** [google/filament#4335]
**Describe the bug**
When I try to view a particular model in the Filament [Web Viewer](https://google.github.io/filament/viewer/), it fails.

**To Reproduce**
1. Download the model below.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/PearlGoldOliveCoveredGlassDish/2.0/IridescentDishWithOlives/glTF
2. Try to view the above model in Filament Web Viewer.
https://google.github.io/filament/viewer/
The following message will be output to the console and the model will not be displayed.
```
Unable to load texture: ./goldleaf_orm.png
```

**Expected behavior**
It is expected that the model will be displayed correctly.

**Desktop (please complete the following information):**
 - OS: Windows 10 + Chrome 91
 - GPU: NVIDIA GeForce RTX 2060
 - Backend: WebGL + ANGLE

**Additional context**

I think the reason why the display fails is because the model uses relative paths. However, the glTF specification allows relative paths to be used, so the expected behavior is to display the model correctly.

https://github.com/KhronosGroup/glTF-Sample-Models/blob/PearlGoldOliveCoveredGlassDish/2.0/IridescentDishWithOlives/glTF/IridescentDishWithOlives.gltf#L613-L645

```
"uri": "./goldleaf_orm.png"
```

**Comment by prideout** [comment]
Interesting bug, though not surprising since ResourceLoader does not canonicalize the URI's it finds in the glTF.  Currently it performs simple string comparison when looking inside its URI cache, so `./foo.png != foo.png`.

(I wish that C++ provided a simple URI library.)

**Comment by prideout** [comment]
Even though our `Path::getCanonicalPath` function is designed for file paths rather than URI's, maybe I can leverage it to (basically) fix this.

**Comment by prideout** [comment]
I think I'm going to close this as a "will not fix", for the following reasons:
1. The author of this particular model removed the relative paths.
2. We actually do support relative paths, but we don't support non-canonical URI's in the glTF.
3. The glTF spec says:  `While the spec does not explicitly disallow non-normalized URIs, their use may be unsupported or lead to unwanted side-effects — such as security warnings or cache misses — on some platforms.`
4. Some competing viewers do not support relative paths either (e.g. PlayCanvas)
5. We don't want to add a C++ URL library to the Filament repo unless we have to.

**Comment by cx20** [comment]
I had a similar issue with [PlayCanvas glTF Viewer](https://playcanvas.com/viewer), but it has now been fixed. (However, it seems that it has not been reflected in the live environment yet)
https://forum.playcanvas.com/t/the-viewer-will-fail-if-the-gltf-model-contains-relative-paths/20976

Also, [Babylon.js Sandbox](https://sandbox.babylonjs.com/) and [Three.js glTF Viewer](https://gltf-viewer.donmccurdy.com/) seem to be able to drag and drop even with relative paths.

It can be difficult to address if you have security concerns, but it would be great if many models could be viewed in an online viewer without modification.
BTW, for reference, it seems that Max2Babylon exporter was the reason why the model was given an unnecessary relative path.
