### ISSUE TITLE
No way to disable VSync, and setting the refreshRate has no effect

### ISSUE THREAD

**Issue by teub** [google/filament#4337]
**Describe the bug**
Hello,
I'm trying to disable vsync and I can't find a way to do it. I tried setting displayInfo.refreshRate to 120 and I'm still stuck at 60 fps. 
I tried to look for code that would set SetSwapInterval but I couldn't find anything yet so I'm not sure what's happening.
I think this is a recent issue, at least I don't think I had it with some older versions of filament.

**To Reproduce**
This can be reproduced by taking the material_sandbox sample:
- commenting out SDL_Delay(16); line 380
- setting the DisplayInfo on the renderer : 
        filament::Renderer::DisplayInfo displayInfo;
        displayInfo.refreshRate = 120;
        renderer->setDisplayInfo(displayInfo);
- disabling the frameskipper : if (mFrameSkipper.beginFrame() || true) {

I used some printf code to show the frame time which won't go below 16ms, see the patch attached  to this bug report :
[120fps_test.zip](https://github.com/google/filament/files/6836612/120fps_test.zip)

**Expected behavior**
120 fps

Ideally there should also be a simple way of bypassing completely the framerate limiter on filament and let the app decide when to render or not. It spent maybe 2 hours trying to figure out what was happening and I still have no clue.

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Comment by romainguy** [comment]
Filament itself does not decide to skip frames, it just tells the app whether it should skip or not but the app can ignore this. And Filament itself does not mandate vsync (actually our samples are bad for that since they do not properly schedule frames at vsync but just use a sleep/delay).

**Comment by teub** [comment]
Note: I tried to force vsync off in the driver and it fixed it.

The original setting was "use the 3D application setting", so it's still controlled by filament right ? Or maybe the default 3d application setting is on ?

**Comment by teub** [comment]
> Filament itself does not decide to skip frames

OK, looking at FilamentApp.cpp again, I understand this part now :)
