### ISSUE TITLE
Performance issue with render target created/destroyed on high resolution displays

### ISSUE THREAD

**Issue by teub** [google/filament#4338]
**Describe the bug**
Using a 4K display and MSAA x2, creating and destroying render targets at each frame has a big performance impact when they could be re-used from frame to frame. The issue is less glaring when not using MSAA or PP, which is a hint the performance hit is related to the size of the RTs.

This is very similar to this issue I reported 2 years ago, but I'm not sure if I can or should reopen it ?
https://github.com/google/filament/issues/1460

**To Reproduce**
Displaying a simple scene with MSAAx2 and profiling it, I get these results which highlights the costs of recreating the RT :

Function Name	Total CPU [unit, %]
| - filament::backend::ConcreteDispatcher<filament::OpenGLDriver>::createRenderTarget	492 (21.53%)
| - filament::backend::invoke<filament::OpenGLDriver,void __cdecl(filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo),filament::OpenGLDriver &,filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo>	492 (21.53%)
| - filament::OpenGLDriver::createRenderTargetR	492 (21.53%)
| - filament::OpenGLDriver::framebufferTexture	488 (21.36%)
| - filament::backend::ConcreteDispatcher<filament::OpenGLDriver>::destroyRenderTarget	405 (17.72%)
| - filament::OpenGLDriver::destroyRenderTarget	405 (17.72%)

Edit: I tried to profile in the sandbox app (out of my project) but I don't have symbols in release there. I expect it'd show the same results though.

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Comment by pixelflinger** [comment]
We have a cache but it has a limited, hardcoded size right now, chosen to be reasonable on mobile devices, which is our main target.

One possible solution is to make this cache configurable and have more reasonable defaults on desktops.

**Comment by teub** [comment]
Are you talking about
static constexpr size_t CACHE_CAPACITY = 64u << 20u;   // 64 MiB
in ResourceAllocator.h ? 

I tried increasing this to 512MB, I didn't notice an increase in performance and I'm still seeing create/destroyRenderTarget when profiling : 

Function Name	Total CPU [unit, %]
| - filament::OpenGLDriver::destroyRenderTarget	688 (26.95%)
| - filament::OpenGLDriver::createRenderTargetR	582 (22.80%)
| - filament::backend::ConcreteDispatcher<filament::OpenGLDriver>::createRenderTarget	582 (22.80%)
| - filament::backend::invoke<filament::OpenGLDriver,void __cdecl(filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo),filament::OpenGLDriver &,filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo>	582 (22.80%)
| - filament::OpenGLDriver::framebufferTexture	577 (22.60%)

It looks like there needs to be a RT cache in addition to the texture cache?

I don't know how much I should trust these results but it looks like half the frame time is spent creating/destroying those, which is not very negligible even if PC is not your main platform.

**Comment by romainguy** [comment]
The numbers are completely different on other platforms. For instance on Android this kind of caching is done by the drivers.

**Comment by teub** [comment]
I trust you they do, I was just saying that if the figures I profiled were reliable, this was a *really* bad hit on PC, even if it is not the main target.

**Comment by pixelflinger** [comment]
Yes, we're not caching RT, just the attachments (textures, renderbuffers), RT (ie fbo) are really cheap to create/destroy on any decent gl driver.

**Comment by teub** [comment]
I'm on a GTX 1080, latest drivers ("game" version).

Indeed, turning off MSAA divides by 10 the cost of create/destroyRenderTarget. 

Rough numbers are : 

1080p:
Function Name	Total CPU [unit, %]
| - filament::backend::invoke<filament::OpenGLDriver,void __cdecl(filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo),filament::OpenGLDriver &,filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo>	110 (2.25%)
| - filament::backend::ConcreteDispatcher<filament::OpenGLDriver>::createRenderTarget	110 (2.25%)
| - filament::OpenGLDriver::createRenderTargetR	108 (2.21%)
| - filament::OpenGLDriver::beginRenderPass	105 (2.15%)
| - filament::backend::ConcreteDispatcher<filament::OpenGLDriver>::beginRenderPass	105 (2.15%)
| - filament::OpenGLDriver::framebufferTexture	104 (2.13%)

4k:
Function Name	Total CPU [unit, %]
| - filament::backend::ConcreteDispatcher<filament::OpenGLDriver>::createRenderTarget	78 (1.64%)
| - filament::backend::invoke<filament::OpenGLDriver,void __cdecl(filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo),filament::OpenGLDriver &,filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo>	78 (1.64%)
| - filament::OpenGLDriver::createRenderTargetR	78 (1.64%)
| - filament::OpenGLDriver::framebufferTexture	77 (1.62%)

Frame time (1080/4k) is 1.5 / 3ms to render a simple scene, vs 7 / 10ms for 2x MSAA. That's a massive difference, especially for a gpu this big.

**Comment by pixelflinger** [comment]
Okay. Thanks for the numbers.

I think this is real problem in how we're doing the msrtt extension "emulation". Fixing this will also help the transmission msaa case on Android.

**Comment by teub** [comment]
Hello @pixelflinger; I'm not sure the issue is fixed? I just updated to the latest version, and now I'm seeing this in my profile, even without MSAA for a 10ms frame: 

Function Name	Total CPU [unit, %]
| - filament::OpenGLDriver::destroyTexture	1518 (27.26%)
| - filament::backend::ConcreteDispatcher<filament::OpenGLDriver>::createRenderTarget	1273 (22.86%)
| - filament::backend::invoke<filament::OpenGLDriver,void __cdecl(filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo),filament::OpenGLDriver &,filament::backend::Handle<filament::backend::HwRenderTarget>,enum filament::backend::TargetBufferFlags,unsigned int,unsigned int,unsigned char,filament::backend::MRT,filament::backend::TargetBufferInfo,filament::backend::TargetBufferInfo>	1272 (22.84%)
| - filament::OpenGLDriver::createRenderTargetR	1271 (22.82%)
| - filament::OpenGLDriver::framebufferTexture	1268 (22.77%)

So, I think it basically got worse?
