### ISSUE TITLE
build visual studio solution failed 

### ISSUE THREAD

**Issue by wolfand11** [google/filament#4368]
**Describe the bug**

**To Reproduce**
1. follow build manual document generate solution
2. open TNT.sln
3. build solution

**Expected behavior**
no error. build success

**Screenshots**
![image](https://user-images.githubusercontent.com/1425676/126612716-f1d19b7e-a853-4b03-849c-89edc8e51899.png)

**Logs**
`
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'glsl.std.450.insts.inc': No such file or directory	SPIRV-Tools-static	D:\Documents\MyProject\Public\Graphics\filament\third_party\spirv-tools\source\ext_inst.cpp	30	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'generators.inc': No such file or directory	SPIRV-Tools-static	D:\Documents\MyProject\Public\Graphics\filament\third_party\spirv-tools\source\opcode.cpp	52	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'D:\Documents\MyProject\Public\Graphics\filament\out\third_party\spirv-tools\source\Debug\SPIRV-Tools.lib'	filamat	D:\Documents\MyProject\Public\Graphics\filament\out\libs\filamat\LINK	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
call ..\..\..\build\windows\combine-static-libs.bat lib.exe D:/Documents/MyProject/Public/Graphics/filament/out/libs/filamat/libfilamat_combined.a D:/Documents/MyProject/Public/Graphics/filament/out/third_party/glslang/tnt/OGLCompilersDLL/Debug/OGLCompilerd.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/glslang/tnt/glslang/OSDependent/Windows/Debug/OSDependentd.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/glslang/tnt/SPIRV/Debug/SPIRVd.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/spirv-tools/source/Debug/SPIRV-Tools.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/spirv-tools/source/opt/Debug/SPIRV-Tools-opt.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/glslang/tnt/SPIRV/Debug/SPVRemapperd.lib D:/Documents/MyProject/Public/Graphics/filament/out/libs/filamat/Debug/filamat.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/glslang/tnt/glslang/Debug/glslangd.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/spirv-cross/tnt/Debug/spirv-cross-core.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/spirv-cross/tnt/Debug/spirv-cross-glsl.lib D:/Documents/MyProject/Public/Graphics/filament/out/third_party/spirv-cross/tnt/Debug/spirv-cross-msl.lib
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1181.	filamat	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	155	
`

**Desktop (please complete the following information):**
 - OS: Windows 10 
 
**source code version**
* main      306f6e1ca [origin/main] fix some broken samples and add -a option

**Comment by bejado** [comment]
Can you show the CMake command you ran to generate the solution?

**Comment by wolfand11** [comment]
@bejado 
![image](https://user-images.githubusercontent.com/1425676/126729846-aad6eba8-abb3-4684-a5d3-dccbbe478500.png)

**Comment by bejado** [comment]
It looks like some file generation task is not working properly in SPIRV-Tools. I would suggest trying a "normal" install of Python instead of using pyenv-win.

**Comment by wolfand11** [comment]
@bejado  thanks, It's work.
![image](https://user-images.githubusercontent.com/1425676/126861678-ed73044f-ce49-4e3a-9cff-896e39376240.png)
![image](https://user-images.githubusercontent.com/1425676/126861691-f70e2ea7-140c-4c28-9b16-1cc22591e48d.png)
