### ISSUE TITLE
Vulkan subpasses don't work on Apple M1 w/ MoltenVK

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#4373]
Note: this was worked around in #4372 

Reverting the workaround above, to reproduce:
`./cmake-build-debug/samples/gltf_viewer -a vulkan `

And disable all options under `View`, except the top level `Post Processing`.

The screen will appear scrambled.

This bug is just about investigating whether we're not using the VK subpass API properly.
![Screen Shot 2021-07-22 at 10 46 40 AM](https://user-images.githubusercontent.com/1240896/126689326-54755b29-2b6e-4d95-af8a-cbc5381771ab.png)

**Comment by jeanlemotan** [comment]
I've noticed that the Metal backend supports framebuffer fetch only on iOS. So not on macOS.
However the vulkan backend reports that it always supports it.
Could this be the reason this fails on MoltenVK? Assuming vulkan supports it but the underlying metal backend of molten doesn't?

**Comment by pixelflinger** [comment]
I thought it that too, but vk support for fb fetch (ie subpasses) is implemented (I mean at the api level) in a way that it can use regular texture fetches.
In other words, a gpu without a tiling system should be able to implement it reasonably well.

Moreover, the M1 GPU is actually a tiler, afaik, so it should support this easily.

Of course, you may be right, maybe it's a problem with moltenvk, or something else.
What worries me is the possibility that we missed something necessary in the vk API to make it work, given how finicky/tricky this API is.

Thank you for the suggestion!

**Comment by pixelflinger** [comment]
This was in fact a dup of #4542
