### ISSUE TITLE
Remove the default renderview on the Filament.

### ISSUE THREAD

**Issue by cwwng** [google/filament#4379]
1、I want to use the _renderer->readPixels method to read buffer data and render it to my own view. 
2、Step 1 was successful, but our render view and the Filament default render view were repeated.
3、Now I need to remove the default renderview of the Filament. What can I do?
Thanks.

**Comment by romainguy** [comment]
Filament does not have a default render view. It only renders the views you tell Filament to render between beginFrame() and endFrame(). You can also use multiple renderers with different render targets instead of doing a readPixel() (see the samples).

**Comment by cwwng** [comment]
> Filament does not have a default render view. It only renders the views you tell Filament to render between beginFrame() and endFrame(). You can also use multiple renderers with different render targets instead of doing a readPixel() (see the samples).

Use the Filament default
    if (_renderer->beginFrame(_swapChain)) {
        _renderer->render(_view);
        _renderer->endFrame();
    }

Between beginFrame and endFrame, I only want pixelBuffer data or TextureID, I don't need a _view, what should I do?

 (see the samples). Where is it？

**Comment by romainguy** [comment]
You can call `readPixels()` before `endFrame()` to capture the content.

**Comment by cwwng** [comment]
> You can call `readPixels()` before `endFrame()` to capture the content.

We've implemented the _renderer->readPixels method to read the buffer data and render it into my own view.
The following：
    if (_renderer->beginFrame(_swapChain)) {
        _renderer->render(_view);
        
        void* bufferSrc = malloc(self.width * self.height * 4);
        backend::PixelBufferDescriptor buffer(
                                              bufferSrc,
                                              self.width * self.height * 4,
                                              backend::PixelBufferDescriptor::PixelDataFormat::RGBA,
                                              backend::PixelBufferDescriptor::PixelDataType::UBYTE,
                                              &callbackFun, (__bridge void *)self);
        _renderer->readPixels(0, 0, self.width, self.height, std::move(buffer));

        _renderer->endFrame();
    }

However, when we initialize Swapchain, we pass in a Layer view. The model is also rendered on this Layer.
code：    _swapChain = _engine->createSwapChain(layer, SwapChain::CONFIG_TRANSPARENT);

Question: How do I remove Layer in SwapChain?

We only want pixelbuffers or TextureID data in the Filament, not layers in the Filament process.
Do you have any suggestions？ Thanks

**Comment by romainguy** [comment]
To do this then don't use read pixels but use a separate renderer with a different SwapChain/RenderTarget.

**Comment by cwwng** [comment]
> To do this then don't use read pixels but use a separate renderer with a different SwapChain/RenderTarget.

Can you provide some specific steps?
Or provide a Demo?
Thanks

**Comment by cwwng** [comment]
> To do this then don't use read pixels but use a separate renderer with a different SwapChain/RenderTarget.

Hi：
I made a few attempts, but they all failed.

I have two questions:
How to use RenderTarget?
How to get pixelBuffers or TextureID using RenderTarget?

I am looking forward to your solution. Thanks very much. 😊😊😊
