### ISSUE TITLE
The bloom for emissive seems not work

### ISSUE THREAD

**Issue by zhenhuafan** [google/filament#4383]
I use the sample "sample-material-builder" in android dir to check the emissive function in an android phone.
But It seems not work，it don't have any bloom effect.It just show the color and there is no any luminous effect.

Below is the code I have changed.

               val matPackage = MaterialBuilder()
                // By default, materials are generated only for DESKTOP. Since we're an Android
                // app, we set the platform to MOBILE.
                .platform(MaterialBuilder.Platform.MOBILE)
                // Set the name of the Material for debugging purposes.
                .name("Clear coat")

                // Defaults to LIT. We could change the shading model here if we desired.
                .shading(MaterialBuilder.Shading.LIT)

                // Add a parameter to the material that can be set via the setParameter method once
                // we have a material instance.
                .uniformParameter(MaterialBuilder.UniformType.FLOAT3, "baseColor")
                .uniformParameter(MaterialBuilder.UniformType.FLOAT4, "emissive")

                // Fragment block- see the material readme (docs/Materials.md.html) for the full
                // specification.
                .material("void material(inout MaterialInputs material) {\n" +
                        "    prepareMaterial(material);\n" +
                        "    material.baseColor.rgb = materialParams.baseColor;\n" +
                        "    material.emissive = materialParams.emissive;\n" +
                        "}\n")

                // Turn off shader code optimization so this sample is compatible with the "lite"
                // variant of the filamat library.
                .optimization(MaterialBuilder.Optimization.NONE)

                // When compiling more than one material variant, it is more efficient to pass an Engine
                // instance to reuse the Engine's job system
                .build(engine)

`        materialInstance.setParameter("baseColor", Colors.RgbType.SRGB, 0.90f, 0.00f, 0.00f)
        materialInstance.setParameter("emissive",  1.0f, 1.0f, 1.0f,1.0f)`

Comment the line ‘materialInstance.setParameter("emissive",  1.0f, 1.0f, 1.0f,1.0f)’ don't have any change.

I have set the view with below code:
`        view.bloomOptions.enabled = true
        view.bloomOptions.levels = 11`

![image](https://user-images.githubusercontent.com/78893358/126941364-b5372c04-68d1-4a45-8d0a-79155af00d23.png)

**Comment by romainguy** [comment]
Emissive doesn't necessarily force a bloom. If that's what you want set the alpha to 0 instead. Please also read the docs that explain how to compute values in EV. Note that emissive values can be > 1 (it's basically a light).

https://google.github.io/filament/Materials.html#materialmodels/litmodel/emissive

**Comment by zhenhuafan** [comment]
Looks still not right, there is no bloom effect.

`        materialInstance.setParameter("baseColor", Colors.RgbType.SRGB, 1.00f, 1.00f, 1.00f)
        materialInstance.setParameter("emissive",  1.5f, 1.5f, 1.5f,0.0f)`

I hava try emissive value from 0.5 to 1000.0f. Can you help me to give me some right value which can make the bloom effect work ? 

![image](https://user-images.githubusercontent.com/78893358/127083088-af90a4e5-b804-41db-a819-799847a839c4.png)

**Comment by romainguy** [comment]
Did you enable the bloom effect? `view.bloomOptions.enabled = true` isn't enough, you need to set the `bloomOptions`:

```
        view.bloomOptions = view.bloomOptions.apply {
            enabled = true
        }
```

**Comment by zhenhuafan** [comment]
> Did you enable the bloom effect? `view.bloomOptions.enabled = true` isn't enough, you need to set the `bloomOptions`:
> 
> ```
>         view.bloomOptions = view.bloomOptions.apply {
>             enabled = true
>         }
> ```

This can work.Thank you very much. @romainguy
