### ISSUE TITLE
a crash when viewing glTF with point/spot lights with filament-1.11.0 on iOS

### ISSUE THREAD

**Issue by JackKaiXing** [google/filament#4388]
![screenshot](https://user-images.githubusercontent.com/21079351/127101660-da530c4f-8ffb-460b-9eb6-01bf86036a75.png)

**Comment by JackKaiXing** [comment]
Froxel: 1125x2172 / 72x72
Froxel: 16x31x16 = 7936 (256 lost)

Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (IOAF code 3)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (IOAF code 3)}
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (IOAF code 3)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (IOAF code 3)}
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=4 "Ignored (for causing prior/excessive GPU errors) (IOAF code 4)" UserInfo={NSLocalizedDescription=Ignored (for causing prior/excessive GPU errors) (IOAF code 4)}
Terminating due to blacklisting by kernel driver

**Comment by JackKaiXing** [comment]
This only happens on iOS. Android and windows are fine.

The iOS project `gilt-viewer` of filament could also load the model and would not crash.

Any ideas?

**Comment by bejado** [comment]
Is the crash with the OpenGL or the Metal backend (or both)? The stacktrace screenshot shows OpenGL, but the error logs you copied show Metal. It would also be helpful if you could share the glTF file that reproduces the issue.

**Comment by JackKaiXing** [comment]
@bejado 

backend is OpenGL. I am trying to reproduce the crash. however, it is a bigger project and it would not crash using the iOS project gilt-viewer of filament.

**Comment by JackKaiXing** [comment]
![screenshot](https://user-images.githubusercontent.com/21079351/127270116-5bd17f2e-eb88-45c1-9df0-555f24330295.png)

The above image is taken on windows, through it would not crash, the white light appear weird as the camera moves away from the light.

on iOS, when camera moves away it would crash.

**Comment by JackKaiXing** [comment]
@bejado 

I think, it is reproducible now. Here are the steps.

1. download the glTF `testlight6.gltf` file and its resources at https://github.com/JackKaiXing/glTF
2. with filament-1.11.0, use the iOS sample project, `gltf-viewer`;
3. modify the demo code
    a.     FILViewController.mm --> NSString* path = [[NSBundle mainBundle] pathForResource:@"testlight6" ofType:@"gltf" inDirectory:@"BusterDrone"];
    b.     FILModelView.mm--> // tm.setTransform(tm.getInstance(_asset->getRoot()), transform); // disable this transform
    c.     FILModelView.mm--> math::float3 offset = {-752.836548, 90, -850.815369};     _camera->lookAt(eye + offset, target+offset, upward); // this is for the render function
4. rotate and zoom out until you could view something like this. it will crash as mentioned above.
![IMG_0427](https://user-images.githubusercontent.com/21079351/127283140-d530d68e-5b95-4d48-b57c-cc82258f1581.png)


Let me know whether you could reproduce.

**Comment by bejado** [comment]
Thanks @JackKaiXing, I can reproduce and will take a look.

**Comment by pixelflinger** [comment]
But the crash is inside the gl driver, correct? That's odd.

On the the devices where it doesn't crash, is the rendering correct?
