### ISSUE TITLE
Crash : createParser  reason: Material version mismatch. Expected 12 but received 11.

### ISSUE THREAD

**Issue by RockVampire** [google/filament#4399]
**Describe the bug**

I'm running the samples.sample-multi-view on Android.
A Crash appeared when the app started.

**To Reproduce**
1. run the sample on Android.

**Expected behavior**
Crash!!!

**Screenshots**

**Logs**

E/Filament: Panic
    in filament::MaterialParser *filament::createParser(filament::backend::Backend, const void *, size_t):69
    reason: Material version mismatch. Expected 12 but received 11.
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 22910 (ament.multiview), pid 22910 (ament.multiview)

**Smartphone (please complete the following information):**
 - Device: [e.g. MI 8 ]
 - OS: [e.g. Android Pie 9.0]

**Additional context**
I noticed that the method MaterialParser::createParser was called twice.Once is called when filament engine creating, the version it got was 12 , correct ! Another time is when I load the gltf model by the AssetLoader , it got the Material version is 11 and it crashed. Why  it was called twice and where the  Material version it got from?

**Comment by RockVampire** [comment]
The problem occured when I update the version to v1.11.1

**Comment by romainguy** [comment]
It looks like you have a stale material file somewhere that you need to recompile. Try a clean build.
