### ISSUE TITLE
Stuck on rendering to the same rendertarget twice

### ISSUE THREAD

**Issue by FinleyPan** [google/filament#4404]
Hey, I created two views and one rendertarget(I intend to render content of the 2nd view into the framebuffer after the 1st rendering):
```cpp
filament::View* first_view     = nullptr;
filament::View* second_view    = nullptr;
filament::Renderer *renderer = nullptr;
filament::RenderTarget *target;
//codes to initialize views, render and target
...

first_view->setRenderTarget(target);
second_view->setRenderTarget(target);
....
renderer->render(first_view);
renderer->render(second_view);
```
But I can only see the content of the `second_view`, content of the first view can be seen too if comment out the second render. Is anything vital igonred?

**Comment by romainguy** [comment]
Please use "Discussions" for this kind of questions. For this to work your second view needs to be marked transparent:

```
view->setBlendMode(View::BlendMode::TRANSLUCENT);
```

**Comment by FinleyPan** [comment]
> Please use "Discussions" for this kind of questions. For this to work your second view needs to be marked transparent:
> 
> ```
> view->setBlendMode(View::BlendMode::TRANSLUCENT);
> ```

Hey, it worked only if the post-processing is disabled:
```cpp
second_view->setPostProcessingEnabled(false);
```
above problem comes again when enabling  post-processing. I need it due to the anti-aliasing.
