### ISSUE TITLE
API to enumerate and remove all entities in a Scene.

### ISSUE THREAD

**Issue by jeanlemotan** [google/filament#4428]
Sometimes it's useful to be able to get all the entities added to a scene and to be able to quickly remove all of them for fast scene manipulation.
One such use-case is to do a multi-pass render of the scene. First pass would render all the entities, but for the second pass I would need to remove all entities, add back just one of them and render another view of this scene.
There are multiple ways to do this on the user side already but all of them involve the user having to maintain an extra copy of the list of entities. 

I added these 3 methods to the Scene class:
```C++
/**
* Removes all entities from the scene.
*/
void removeAllEntities();

/**
* Returns the number of entities in the scene.
* 
* This doesn't take into account if the entities are alive or not. 
* 
* @return number of entities added to the scene
*/
size_t getEntityCount() const;

/**
* Returns up to maxCount entities from the scene.
* 
* This doesn't take into account if the entities are alive or not. 
* The passes buffer needs to be allocated by the user to fit at least maxCount entities.
* 
* @return the actual number of entities copied in the buffer.
*/
size_t getEntities(utils::Entity* entities, size_t maxCount) const;
```

The signature for getEntities is to avoid having to expose the internal robin_set or to add a std::vector dependency.
The implementation for these methods is trivial - removeAllEntities and getEntityCount are one liners. getEntities is a simple for loop.

I can do a PR with the changes if these features are accepted.

Thanks!

//Edit - code formatting

**Comment by romainguy** [comment]
Why not simply create a new, empty scene?

**Comment by jeanlemotan** [comment]
I didn't realize that I could add an entity to 2 scenes at the same time.
That solves it, thanks.
