### ISSUE TITLE
Small compiler warning in LightManager.h line 312

### ISSUE THREAD

**Issue by jeanlemotan** [google/filament#4429]
There is a double constant assigned to a float member in LightManager.h line 312.
I compile with W4 and errors as warnings and I have this thing fixed in my local filament copy - so I can do a PR with this.

Opening an issue for this seems overkill and I would just open a PR - but this is that the CONTRIBUTING.md doc says. 
Hope it's ok, if there is a better/faster way let me know.

**Comment by pixelflinger** [comment]
Yes please, upload a PR! Thank you.

**Comment by pixelflinger** [comment]
Fixed. Thank you.
