### ISSUE TITLE
Fail to Blend current rendering results with color buffer of framebuffer when post-processing enabled

### ISSUE THREAD

**Issue by FinleyPan** [google/filament#4430]
This problem originates from #4404 . Basically, I have two views and one render target and I want to render the 2nd view on top of the 1st view by alpha blending:
```cpp
filament::Scene *first_scene = nullptr;
filament::Scene *second_scene = nullptr;
filament::View* first_view     = nullptr;
filament::View* second_view    = nullptr;
filament::Renderer *renderer = nullptr;
filament::RenderTarget *target = nullptr;

//this will cause the 1st view overlaid by the 2nd view, disabling post-processing will overcome it.
second_view->setBlendMode(View::BlendMode::TRANSLUCENT);
second_view->setPostProcessingEnabled(true);
second_view->setAntiAliasing(filament::View::AntiAliasing::FXAA);
//codes to initialize views, render and target
...

first_view->setScene(first_scene);
second_view->setScene(second_scene);
first_view->setRenderTarget(target);
second_view->setRenderTarget(target);
....
renderer->render(first_view);
renderer->render(second_view);
```
There are only one entity in both scenes, material of entity in the first scene is `bakedTexture` and that in the second scene is a trivial modification of `bakedColor.mat`:
```glsl
material {
    name : BakedColor,
    requires : [
        color
    ],
    blending: transparent,
    shadingModel : unlit,
    culling : none
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = getColor();
        material.baseColor.a = 0.2;
}
```
Result is as expected when disabling post-processing:
![img](https://user-images.githubusercontent.com/26212839/127840279-03d355e1-99b8-4546-a1f8-0f61293c6fc1.png)

While contents of the 1st view was completely overlaid by that of the 2nd view if open post-processing:
![img1](https://user-images.githubusercontent.com/26212839/127841646-c9ca2ec3-b31f-4be7-9ab5-079bab9c22c6.png)

Post-processing is necessary to me due to anti-aliasing.

**Comment by pixelflinger** [comment]
How do you create the textures of `target`? What `usage` bits are you using?

Also are you able to run your test with a debug version of filament? (this might help us diagnose the problem).

**Comment by FinleyPan** [comment]
> How do you create the textures of `target`? What `usage` bits are you using?

Hi, I create my render target as follows:
```cpp
bool need_depth = true;
color_ = filament::Texture::Builder()
    .width(width)
    .height(height)
    .levels(1)
    .sampler(filament::Texture::Sampler::SAMPLER_2D)
    .format(filament::Texture::InternalFormat::RGBA8)
    .usage(filament::Texture::Usage::COLOR_ATTACHMENT | filament::Texture::Usage::SAMPLEABLE)
    .build(*engine);

if(!need_depth){
    target_ = filament::RenderTarget::Builder()
        .texture(filament::RenderTarget::AttachmentPoint::COLOR, color_)
        .mipLevel(filament::RenderTarget::AttachmentPoint::COLOR, 0)
        .build(*engine);
}else{
    depth_ = filament::Texture::Builder()
        .width(width)
        .height(height)
        .sampler(filament::Texture::Sampler::SAMPLER_2D)
        .format(filament::Texture::InternalFormat::DEPTH24_STENCIL8)
        .usage(filament::Texture::Usage::DEPTH_ATTACHMENT)
        .build(*engine);

    target_ = filament::RenderTarget::Builder()
        .texture(filament::RenderTarget::AttachmentPoint::COLOR, color_)
        .mipLevel(filament::RenderTarget::AttachmentPoint::COLOR, 0)
        .texture(filament::RenderTarget::AttachmentPoint::DEPTH, depth_)
        .mipLevel(filament::RenderTarget::AttachmentPoint::DEPTH, 0)
        .build(*engine);
}
```
Usage bit of color attachment is `filament::Texture::Usage::COLOR_ATTACHMENT | filament::Texture::Usage::SAMPLEABLE` and that of depth attachment is `filament::Texture::Usage::DEPTH_ATTACHMENT`.
> Also are you able to run your test with a debug version of filament? (this might help us diagnose the problem).
My test program is already in debug building, the terminal only printed:
```
Loaded texture: 700x984, channels: 3
FEngine (32 bits) created at 0427D050 (threading is enabled)
FEngine resolved backend: OpenGL
NVIDIA Corporation, GeForce GTX 1050/PCIe/SSE2, 4.1.0 NVIDIA 462.31, 4.10 NVIDIA via Cg compiler
OS version: 0
E:\CPPCode\projects\filament\build32\samples\Debug\multiple_fbos.exe (process 16764) exited with code -1.
```
it was tested on Windows, but above problem arose on both Android and iOS.

**Comment by pixelflinger** [comment]
Does this mean that this problem doesn't happen on windows?

**Comment by FinleyPan** [comment]
> Does this mean that this problem doesn't happen on windows?

Sorry for my ambiguous statement, it happen Windows, iOS and Android.

**Comment by FinleyPan** [comment]
@pixelflinger Hey, I reproduced this problem on latest filament, please check this [branch](https://github.com/FinleyPan/filament/tree/reproduce-4430).   You can directly build and run the [test](https://github.com/FinleyPan/filament/blob/reproduce-4430/samples/multiple_fbos.cpp). By changing this [line](https://github.com/FinleyPan/filament/blob/reproduce-4430/samples/multiple_fbos.cpp#L427):
```cpp
bool open_post_process = false;
```
you can control over opening or closing of the second view's post-processing.
This time, I run the test on macOS, the render result is as follows(for the left result post-processing is closed, for the right it is opened):
<img width="320" alt="bbb" src="https://user-images.githubusercontent.com/26212839/127992665-bc718e8e-3816-494a-b740-761420976abb.png">
<img width="320" alt="aaa" src="https://user-images.githubusercontent.com/26212839/127992686-393c3933-57f1-4dd0-90a3-92d3111cd02b.png">
So I think it is a common bug across all platforms

**Comment by pixelflinger** [comment]
Fantastic, thank you.

**Comment by FinleyPan** [comment]
thanks! the fix works for me!
