### ISSUE TITLE
WebGL shader behaves differently than PC/OpenGL

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#4441]
**Description**
I am getting some strange reflections on WebGL that I don't see on PC/OpenGL.

**To Reproduce**
Here is the shader I'm using:

```
material {
    name : Lit_Textured,
    requires : [
        uv0
    ],
    shadingModel : lit,
	doubleSided : false,
	colorWrite : true,
	depthWrite : true,
	depthCulling : true,
	culling : back,
    parameters : [
		{
            type : float,
            name : reflectance
        },
        {
		type : float4,
		name : baseColor
        },
	{
		type : float2,
		name : uvscale
	},
        {
            type : sampler2d,
            name : albedo
        },
        {
            type : sampler2d,
            name : roughness
        },
        {
            type : sampler2d,
            name : metallic
        },
        {
            type : sampler2d,
            name : normal
        },
        {
            type : sampler2d,
            name : ao
        }
    ],
}

fragment {
    void material(inout MaterialInputs material) {
	float2 uvScale = getUV0() * materialParams.uvscale;
	float4 rawNormal = texture(materialParams_normal, uvScale).xyzw;
	float3 normal = rawNormal.xyz * 2.0 - 1.0;
	material.normal = normal;
		
	prepareMaterial(material);
	float4 texColor = texture(materialParams_albedo, uvScale);
        material.baseColor = materialParams.baseColor * texColor;
        material.roughness = texture(materialParams_roughness, uvScale).r;
        material.metallic = texture(materialParams_metallic, uvScale).r;
        material.ambientOcclusion = texture(materialParams_ao, uvScale).r;
        material.reflectance = materialParams.reflectance;
    }
}

```
Here is a comparison of the PC vs WebGL renderings.  Note that **reflectance** has been set to 0 in all images.

**PC rendering (expected behavior):**
![PC_Render](https://user-images.githubusercontent.com/40642629/128071313-adeb62da-4958-4d71-8a88-a20e26c21b1b.PNG)

**WebGL rendering - note the chrome-like reflections which seem to be reflecting at odd angles, to my eye:**
![WebGL_Render](https://user-images.githubusercontent.com/40642629/128071457-2d8a3550-2c7a-4fef-8710-2b61c08087b1.PNG)

**WebGL - If I force the normal to (0,0,1), the surface goes flat, as expected, but reflections remain:**
![WebGL_NoNormalMap](https://user-images.githubusercontent.com/40642629/128071649-a035e78e-fc69-43c0-8fc3-da441052189e.PNG)

Things I have tried:
- Explicitly setting some other parameters to 0, such as clearCoat, and anisotropy.
- Tried using different sky box maps, some with and without mips.
- Setting reflectance to 0 - **seems to affect PC, but not WebGL**

**Differences between PC and Web:**
- PC implementation creates the IBL from SH parameters
- Web implementation creates the IBL a cube map (no other option, to my knowledge)

**Comment by romainguy** [comment]
Note that setting reflectance to 0 does NOT remove all reflections. 

"PC implementation creates the IBL from SH parameters
Web implementation creates the IBL a cube map (no other option, to my knowledge)"

What do you mean by "creates the IBL from SH parameters"? SH are only used for indirect diffuse lighting, specular reflections always come from a cubemap. Did you not set a cubemap on your PC version?

Either way in your first WebGL screenshot it looks like your tangent frames are incorrect.

**Comment by BStringhamVRSK** [comment]
You're correct, I meant to point out that the only lighting differences I can account for is the indirect diffuse lighting.   PC from SH, Web from cube map.

Regarding tangent frames:
So far as I can tell, I am doing the same thing for both platforms.  As per our discussion yesterday, I was having difficulty getting the tangents set into the vertex buffers correctly.  The frames seem correct for non-textured shaders (or if I force the normal in the shader to (0,0,1), the trivial case).

Link to yesterday's discussion: #4434

**Comment by BStringhamVRSK** [comment]
Watching the SurfaceOrientation.Builder return values, I found a case where all of the quaternions came back with the value: -16384

This seems suspicious.  Is that a value that indicates I have sent in invalid data?  All of the positions, normals, uvs, and indices I provided seem correct.

**Comment by romainguy** [comment]
Testing non-textured shaders won't give you the whole story. It will validate the normals but not the tangent and bitangent, which are used when normal mapping is in play.

> Watching the SurfaceOrientation.Builder return values, I found a case where all of the quaternions came back with the value: -16384

Maybe? We use SNORM values so that would just indicate `-1.0f`.

**Comment by BStringhamVRSK** [comment]
The -16384 values is just one case.  The other geometry all seems to return differing values.

**Comment by BStringhamVRSK** [comment]
I can't account for the tangent frame problems, which could be a separate bug?  I have tried to exhaust all the possibilities, as described in my post here:  #4434
