### ISSUE TITLE
Build filament on windows 10 use vs2019,generated a lot of c99 standard error.

### ISSUE THREAD

**Issue by zero406-CC** [google/filament#4445]
Hello there,but i got a problem about windows build filament, my system environment below：
 windows 10 ，  vs2019 ，python 3.7 ，cmake 3.20，filament version 1.11.2,
I followed the build doc to create  TNT.sln ,this step is ok,but when i build the solution it generated a lot of errors，
I find out is becase of c99 standard is not supported very well on vs2019，for example ：const Header header {
        .version = VERSION,
        .parts = 1,
        .aabb = unitBox,
        .offsetTangents = sizeof(positions),
        .offsetColor = sizeof(positions) + sizeof(tangents),
        .offsetUV0 = sizeof(positions) + sizeof(tangents) + sizeof(colors),
        .strideUV1 = maxint,
        .vertexCount = vertexCount,
        .vertexSize = sizeof(positions) + sizeof(tangents) + sizeof(colors) + sizeof(uv0),
        .indexType = IndexType::UI16,
        .indexCount = 3,
        .indexSize = sizeof(uint16_t) * 3
    };
this is not supported when assign a struct value by dot on vs2019，if i have to modify all of this code grammar myself or is there any steps did wrong；
Is there any suggestions？I look forward to receiving your reply，thank u！

**Comment by zero406-CC** [comment]
by the way this is my cmake build info:
D:\dev\filament_git\filament\out>"C:\Program Files\CMake\bin\cmake.exe" ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.20.27508.1
-- The CXX compiler identification is MSVC 19.20.27508.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
-- DFG LUT size set to 128x128
-- No build type selected, default to Debug
-- Found PythonInterp: C:/ProgramData/Miniconda3/python.exe (found suitable version "3.7.4", minimum required is "3")
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/ml64.exe
-- Configuring done
-- Generating done
-- Build files have been written to: D:/dev/filament_git/filament/out

**Comment by bejado** [comment]
What's the error that you're seeing?

**Comment by zero406-CC** [comment]
Hello，bejado,there is more than 1000 errors.
I'll give you an example to illustrate，for example i only build BlockCompression.cpp  part of the errors is like below:
Error	C3861	'astcParseOptionString': identifier not found	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	518	
Error	C2065	'ASTC': undeclared identifier	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	520	
Error	C2653	'CompressedFormat': is not a class or namespace name	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	524	
Error	C2653	'CompressedFormat': is not a class or namespace name	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	529	
Error	C2653	'CompressionConfig': is not a class or namespace name	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	516	
Error	C2653	'CompressionConfig': is not a class or namespace name	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	520	
Error	C2653	'CompressionConfig': is not a class or namespace name	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	525	
Error	C2653	'CompressionConfig': is not a class or namespace name	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	530	
Error	C2653	'CompressionConfig': is not a class or namespace name	imageio	D:\dev\filament_git\filament\libs\imageio\src\BlockCompression.cpp	533	

Because there are too many errors(over hundreds),so i only list part of them.
These mistakes are strange，I found three returns of CompressedTexture  like below
return {
        .format = config.format,
        .size = size,
        .data = decltype(CompressedTexture::data)(buffer)
    };
Because vs2019 has a red line error message about .format，if i modify the code grammar like blow：
 return {
        config.format,
        size,
         decltype(CompressedTexture::data)(buffer)
    };

It‘s succeeded.
1>------ Build started: Project: imageio, Configuration: Release x64 ------
1>BlockCompression.cpp
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
There are too many grammar like above。

**Comment by romainguy** [comment]
We build Filament using VS2019 and we don't run into this issue.

**Comment by zero406-CC** [comment]
Hello romainguy, yes， so weird,i wonder if my vs2019 version is too low，16.0 version，i will download high version vs，thank u！
