### ISSUE TITLE
Hiding an entity from scene at runtime

### ISSUE THREAD

**Issue by muizamhailey004** [google/filament#4448]
Hi. Is it possible to hide an entity from my rendered scene at runtime? E.g. on a button press? I've tried to do setLayerMask and filament.scene.removeEntity but both doesn't hide the entity and does nothing. Thanks in advance!

**Comment by romainguy** [comment]
Please don't file a bug for questions, use the Discussions tab. Setting a layer mask is the cheapest way to hide an entity, but you need to set a layer mask on your View as well.
