### ISSUE TITLE
Runtime calling filament::Texture::setImage every frame possible?

### ISSUE THREAD

**Issue by PsycoTodd** [google/filament#4464]
**Describe the bug**
I have some runtime generated images on mobile end and try to update that to the filament texture. These images are not from video. And when I try to call it frequently on main thread the app crashes.

My question is that the texture is used for rendering and at the same time being updated here. Would it crash because race condition or similar things? Is there recommendation on updating Textures at this high frequency?

**To Reproduce**
1. Just try to get the image data and set it to the texture we created  with filament every frame.
2. Then the whole system slow down and it becomes unuseable.

**Expected behavior**
Suppose the app should run smoothly and we can see the texture update.

**Screenshots**

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

v ***** FATAL SIGNAL RECEIVED ******* 
    Received fatal signal: SIGSEGV(11)	PID: 20263
    
    ***** SIGNAL SIGSEGV(11)
    
    *******	STACKDUMP *******
      # 0: 0x6d3bff4ab4  
      # 1: 0x6d3bfeca68  
      # 2: 0x6d3bfec8dc  
      # 3: 0x6d3bff54fc  
      # 4: 0x5837eeed04  
      # 5: 0x786fec463c  __kernel_rt_sigreturn
      # 6: 0x77d21ced90  
      # 7: 0x77d21a9c60  
      # 8: 0x77d21b0ca8  
      # 9: 0x786c444f14  
      #10: 0x786c3e30cc  
    
    Exiting after fatal event  (FATAL_SIGNAL). Fatal type:  SIGSEGV
    Log content flushed sucessfully to sink

**Desktop (please complete the following information):**
 - OS: Android
 - GPU: 
 - Backend: OpenGL

**Smartphone (please complete the following information):**
 - Device: Samsung S10E
 - OS: [e.g. Android Pie 9.0]

**Additional context**
The API I am using:     void setImage(Engine& engine, size_t level, PixelBufferDescriptor&& buffer) const;

**Comment by romainguy** [comment]
Could you please show more of the logs? Updating a texture every frame shouldn't be an issue. Do you properly free memory after an upload is complete? The fact that the entire system slows down would indicate you may be exhausting system memory.

**Comment by pixelflinger** [comment]
There is no race condition between using `setImage` and the texture being used for rendering. It is guaranteed that the effect of `setImage` will happen after the next call to `Renderer::render()`.
There shouldn't be any issue updating a texture every frame, but note that it's not ideal for performance.

If possible try to run a DEBUG version of filament so we get a better stacktrace. Also as @romainguy said, this looks like memory is not being freed.

**Comment by PsycoTodd** [comment]
Update: seems like the crash is gone if I setImage with the same size. 

for example, if I `createTexture` to be 2k x 2k RGB image, and then try to `setImage`  with a RGB image, it crashes.

**Comment by romainguy** [comment]
Please show the full logs and check that you are freeing the memory.

**Comment by PsycoTodd** [comment]
The crash log is indeed that short. 

I am able to resolve this problem by providing setImage with the same size image that the GLTF loaded. 

Technically, filament allows to link the uber shader variables to other texture we load in other source, rather than from the gltf file. In this case, we faces this case:
1. load the gltf model, whose texture dimension is B.
2. create filament texture (with dimension A)
3.  Binding the uber shader key with the one from step 2.
4. Try to update the textures from step 2 with another one (dimension C)

So here I have to make sure that A == B && B == C. Or system would crash. And the image format also need to be same.

**Comment by romainguy** [comment]
If you call setImage on an existing texture, yes you’ll have to match format and dimensions. You can however create your own texture object with a new format and new dimensions and use that as the parameter for the material. In that case you don’t need to match anything.

**Comment by pixelflinger** [comment]
sounds like a user error. Please move this to a discussion if needed.
