### ISSUE TITLE
Webgl demos are blank with empty black window on Android phone

### ISSUE THREAD

**Issue by briangavin** [google/filament#4470]
**Describe the bug**
Webgl demos are blank with empty black window on Android phone

**To Reproduce**
1.  Use Chrome stable for Android
2. https://google.github.io/filament/webgl/helmet.html
3. 3D window is empty black in color.

Using moto g7 Android 10 supports webgl2.

**Comment by pixelflinger** [comment]
Just tried on S20+, works fine.

**Comment by prideout** [comment]
@pixelflinger I'm closing this.  At the time of this writing,  the web helmet demo works on Pixel 6 Chrome and it would be difficult to test our WebGL implementation against every Android device.
