### ISSUE TITLE
Unable to build webgl/web assembly version of Filament on Manjaro Linux

### ISSUE THREAD

**Issue by briangavin** [google/filament#4471]
Since there are no instruction for how to build the webgl version on Windows I am using Majaro linux.

I have installed emcripten sdk version 2.0.26.
When I run the following command I get an error and filament will not build for me.

I run the following command
./build.sh -p webgl release

I get the following error.

building release in out/cmake-release...
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:9 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:9 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!

**Comment by briangavin** [comment]
I figured it out.   You need to run this command instead.  I would suggest you add this to your documentation.

nv CC=clang CXX=clang++ ./build.sh -p webgl release

**Comment by briangavin** [comment]
Would be nice to have instructions for how to build web assembly version on MS Windows.

**Comment by romainguy** [comment]
Setting those variables is already described in the Linux section of the building.md doc. Windows is unfortunately not our main development environment so we probably won't be able to ensure we keep up to date and accurate info on how to build the WebGL target for Windows.
