### ISSUE TITLE
Allow more shadow-casting lights

### ISSUE THREAD

**Issue by jwwalker** [google/filament#4473]
Please permit far more shadow-casting lights.  Currently there is a limit of `CONFIG_MAX_SHADOW_CASTING_SPOTS = 6`.  (And by the way, more than the current 8 light channels would also be good.)

**Comment by bejado** [comment]
This is because we use a `uint8_t` for visibility culling: https://github.com/google/filament/blob/bbee5599f13e49267936aa2c5dc979026af07b8a/filament/src/details/View.h#L100-L101

In the past @pixelflinger and I have discussed changing this to a `uint32_t`, which would allow for a max of 30 lights.

**Comment by jwwalker** [comment]
@bejado Ideally I'd like even more than 30, especially if I have to build my own shadow-casting point lights using 4 spot lights each.

**Comment by pixelflinger** [comment]
Performance will be abysmal though. And handling so many shadowmaps is not a priority for us (for mobile).
