### ISSUE TITLE
OpenXR

### ISSUE THREAD

**Issue by ErikToth97** [google/filament#4479]
We would like to render with filament for OpenXR.

But we have two questions for which we haven't found a solution yet:

1. Is it possible to render into a texture?
2. Can we get the texture's OpenGL textureID somehow?

**Comment by bejado** [comment]
1. Yes, with the [`RenderTarget`](https://github.com/google/filament/blob/abb6ae304cd0023e2de6a72986ded90e712bede5/filament/include/filament/RenderTarget.h#L94) API you can attach a Filament `Texture` to render into.
2. No, but you can create an OpenGL texture and then [import it into Filament](https://github.com/google/filament/blob/abb6ae304cd0023e2de6a72986ded90e712bede5/filament/include/filament/Texture.h#L238).

That _should_ allow you to render into the OpenGL texture, though I can't recall if we've ever tested this path before. You'll need to pass in a `sharedGLContext` when creating the Filament `Engine` to share the Texture, as Filament maintains its own, separate OpenGL context.

**Comment by romainguy** [comment]
Please use Discussions for questions. You could also use a SurfaceTexture to achieve the same result without importing a texture on the Filament side.
