### ISSUE TITLE
Use in OpenXR - expose graphics device and context 

### ISSUE THREAD

**Issue by 1runeberg** [google/filament#4482]
**Is your feature request related to a problem? Please describe.**
Looking at using filament as a render engine for use with OpenXR (new api standard for VR and AR applications by Khronos).

In OpenXR, the application submits the graphics bindings.

e.g. for OpenGLWin32:
```
    HDC                         hDC;
    HGLRC                     hGLRC;
```

for Vulkan:
```
    VkInstance                instance;
    VkPhysicalDevice      physicalDevice;
    VkDevice                  device;
    uint32_t                    queueFamilyIndex;
    uint32_t                    queueIndex;

```
this is then used by the runtime (e.g. SteamVR, Oculus, WMR, etc) to generate swapchain images/textures that apps should use to render to.

See: https://github.com/microsoft/OpenXR-MixedReality/blob/main/openxr_preview/include/openxr/openxr_platform.h

Unfortunately this info doesn't appear to be accessible in the filament api afaict.

**Describe the solution you'd like**

- Expose the graphics platform specific context info in the API. 

Note: filament::Texture seems to have an import param that allows for  texture ids, but has an ominous warning of it possibly being taken away, and is located under a section called "no user serviceable parts below".

**Describe alternatives you've considered**
I understand this may go against the design principle/s of the api, but perhaps these context info can be exposed for rendering pipeline use cases such as with OpenXR.

**OS and backend**
Should be supported across all supported platforms and graphics apis

**Comment by romainguy** [comment]
We definitely don't want to expose internals like these. It would be preferable for us to support OpenXR directly.
