### ISSUE TITLE
app crash when activity is finish

### ISSUE THREAD

**Issue by asalin** [google/filament#4490]
according to https://medium.com/@philiprideout/getting-started-with-filament-on-android-d10b16f0ec67
,i succeed in getting the 3d gltf work,but when i finish the render activity,the app crash(signal 11 (SIGSEGV)).By debugging,i found out the destory method in AssetLoader that call mMaterialCache.destroyMaterials is the code that cause the crash ,can someone tell me what's the problem?(USING FILAMENT VERSION 1.11.2)
**Describe the bug**

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
Please share the crash logs.

**Comment by asalin** [comment]
> Please share the crash logs.

the logcat shows:
![image](https://user-images.githubusercontent.com/6972999/129130448-749f7f05-ca33-4550-aae3-d69ab16f6433.png)

**Comment by romainguy** [comment]
Could you make sure you don’t destroy the asset loader twice? We’ve never seen this issue so it’s likely to be a problem in your app. Do you have an apk you could share to reproduce the problem please?

**Comment by asalin** [comment]
> Could you make sure you don’t destroy the asset loader twice? We’ve never seen this issue so it’s likely to be a problem in your app. Do you have an apk you could share to reproduce the problem please?
i didn't destroy the asset loader on purpose,it's called in modelviewer when the activity finish and the surface detached.
![Uploading image.png…]()

**Comment by romainguy** [comment]
Do you have an apk we can use to test?

**Comment by asalin** [comment]
> Do you have an apk we can use to test?

https://www.pgyer.com/FBc3
click the bell icon on main page
![{830H}TQ$MK0{6`}LR%JTN1](https://user-images.githubusercontent.com/6972999/129132503-867f2f68-a1c2-4e35-8e78-ef526d832b8d.jpg)

**Comment by asalin** [comment]
> Do you have an apk we can use to test?

hi,did you had a clue yet.i try the 1.12.0,and it still doesn't work

**Comment by pixelflinger** [comment]
The fault address in the log is in fact an ASCII string of some kind "oc_avar", this definitely indicates either a memory corruption or a double free.

**Comment by asalin** [comment]
> oc_avar

then how should i fix that?

**Comment by asalin** [comment]
Here is the Code:

package com.example.myapplication

import android.annotation.SuppressLint
import android.os.Bundle
import android.view.Choreographer
import android.view.SurfaceView
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.coroutineScope
import com.google.android.filament.gltfio.Gltfio
import com.google.android.filament.utils.ModelViewer
import com.google.android.filament.utils.Utils
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import java.nio.Buffer
import java.nio.ByteBuffer
/**
 * @Description:
 * @Author:         Jack
 * @CreateDate:     2021/8/13 10:48
 */
class TestActivity : AppCompatActivity() {

    companion object {
        init {
            Utils.init()
        }

        public const val URL = "URL"
    }

    private lateinit var surfaceView: SurfaceView
    private lateinit var choreographer: Choreographer
    private val frameScheduler = FrameCallback()
    private lateinit var modelViewer: ModelViewer


    @SuppressLint("ClickableViewAccessibility")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initGltf()
    }

    private fun readCompressedAsset(assetName: String): ByteBuffer {
        val input = assets.open(assetName)
        val bytes = ByteArray(input.available())
        input.read(bytes)
        return ByteBuffer.wrap(bytes)
    }

    override fun onResume() {
        super.onResume()
        choreographer.postFrameCallback(frameScheduler)
    }

    override fun onPause() {
        super.onPause()
        choreographer.removeFrameCallback(frameScheduler)
    }

    override fun onDestroy() {
        super.onDestroy()
        choreographer.removeFrameCallback(frameScheduler)
    }

    inner class FrameCallback : Choreographer.FrameCallback {
        private val startTime = System.nanoTime()
        override fun doFrame(frameTimeNanos: Long) {
            choreographer.postFrameCallback(this)

            modelViewer.animator?.apply {
                if (animationCount > 0) {
                    val elapsedTimeSeconds =
                            (frameTimeNanos - startTime).toDouble() / 1_000_000_000
                    applyAnimation(0, elapsedTimeSeconds.toFloat())
                }
                updateBoneMatrices()
            }

            modelViewer.render(frameTimeNanos)
        }
    }

    fun initGltf() {
//        surfaceView = findViewById(R.id.main_sv)
        surfaceView = SurfaceView(this).apply { setContentView(this) }
        choreographer = Choreographer.getInstance()
        modelViewer = ModelViewer(surfaceView)
        surfaceView.setOnTouchListener(modelViewer)

//        loadGlb("DamagedHelmet")
//        modelViewer.scene.skybox = Skybox.Builder().build(modelViewer.engine)
        loadGltf("BusterDrone")
    }



    private fun loadGltf(name: String) {
        val buffer = readAsset("models/${name}.gltf")
        modelViewer.loadModelGltf(buffer) { uri -> readAsset("models/$uri") }
        modelViewer.transformToUnitCube()
    }

    private fun readAsset(assetName: String): ByteBuffer {
        val input = assets.open(assetName)
        val bytes = ByteArray(input.available())
        input.read(bytes)
        return ByteBuffer.wrap(bytes)
    }
}

**Comment by romainguy** [comment]
Same issue as #4517
