### ISSUE TITLE
JavaScript Request: Expose Texture methods getWidth(), getHeight(), getDepth(), getLevels(), etc.

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#4492]
**Problem:**
After using Engine.createTextureFromKtx/jpeg/Png, I need to query the texture width and height so I can generate proper UV coordinates for font display.

**Proposed solution**
Expose the Texture.getWidth(), getHeight(), etc. methods to get texture information.  I currently only need width and height, but I can see usage cases for many of the other "getters" available in the C++ interface.

**OS and backend**
WebGL

**Comment by prideout** [comment]
This is a good feature request, thanks!

**Comment by abhakta-47** [comment]
Hi, I would like to work on this.
as suggested I would update filament/Texture.h and also class Texture in filament/web/filament-js/filament.d.ts.
Am I missing anything?

**Comment by BStringhamVRSK** [comment]
Thanks!  Sounds right.
Not sure, but you may also need to modify  web/filament-js/jsbindings.cpp

**Comment by sarikachhom** [comment]
Hi, I having a bit issue on  my Voxelab Aquila C2 V.1.2.1 20210731 im trying to download firmwares and it's still not working? can someone please tell what am i missing anything? thank you
