### ISSUE TITLE
[EGL platform] move to FBO from pbuffer

### ISSUE THREAD

**Issue by jwinarske** [google/filament#4499]
**Is your feature request related to a problem? Please describe.**

Using EGL on Wayland (Linux), Wayland does not allow usage of pbuffer support without patching the compositor.
https://bugs.freedesktop.org/show_bug.cgi?id=105995

"Pixmap surfaces can never be supported on Wayland, as there is no native pixmap type defined by Wayland." - Daniel Stone

**Describe the solution you'd like**
Use FBO in place of pbuffer

**Describe alternatives you've considered**
Alternative is patching the compositor.  This would be okay for target builds, but does not work for dev work flow.  Devs would have to customize each machine.

**OS and backend**

PlatformEGL specific.

In addition the call in PlatformEGL.cpp does not work as-is for Linux Wayland:  `mEGLDisplay = eglGetDisplay(EGL_DEFAULT_DISPLAY);`

Wayland requires `mEGLDisplay = get_egl_display(EGL_PLATFORM_WAYLAND_KHR, mNativeDisplay, nullptr);

mNativeDisplay needs to be passed in from Wayland Client session.

**Comment by romainguy** [comment]
What pbuffer are you talking about? The only pbuffer we use is for operations that require an active context when we don’t have a surface available. An FBO would not help since it’s a GL object and we need an EGL object.

**Comment by romainguy** [comment]
Also this sounds like Wayland does not provide a compliant implementation of EGL?

**Comment by jwinarske** [comment]
I think that it's fair to say EGL is a subset on Wayland.

Sounds like the primary concern is to prevent developers from using pbuffers due to performance concerns.
https://bugs.freedesktop.org/show_bug.cgi?id=105995

Our use cases all involve headless RenderTarget scenarios.

**Comment by romainguy** [comment]
We don’t use pbuffers for rendering.

**Comment by jwinarske** [comment]
https://github.com/google/filament/blob/main/filament/backend/src/opengl/PlatformEGL.cpp#L189

**Comment by jwinarske** [comment]
What would be your suggested work around?

**Comment by romainguy** [comment]
See my previous comment. We never render into that pbuffer, we use it to make necessary (E)GL calls when we don’t have a surface to make the context current.

**Comment by romainguy** [comment]
I don’t know of a workaround, we never tested with Wayland as our official Linux support is based on XGL. I’m not honestly not happy to hear that Wayland is not a proper EGL implementation. All I know at this point is that FBOs are not a replacement for what we do with the pbuffer. There’s hopefully another way of handling this but I don’t know what it is.

**Comment by jwinarske** [comment]
pbuffers were deprecated in OpenGL 3.0, and removed with 3.1+, and the recommendation is to use Framebuffer Objects instead.

https://www.khronos.org/opengl/wiki/P-buffer

**Comment by romainguy** [comment]
This is about EGL, not OpenGL, and we don’t render into pbuffers. FBOs are a replacement for rendering, not making context current. The solution highlighted in your link is not practical for us (create an invisible window).

**Comment by pixelflinger** [comment]
Is using the Vulkan backend an option instead?

We're reluctant adding features to the GL backend because it's not a long term solution, since GL is essentially being phased out

**Comment by jwinarske** [comment]
@pixelflinger If I move to the Vulkan backend then I will need to either implement OpenGL interop to emulate a texture for the Flutter Engine, or modify the Flutter Engine to implement Linux Vulkan.  While my preference is to run 100% Vulkan, not everything in our stack is Vulkan, so GLES interop is going to have to happen somewhere.

I see in the Filament Vulkan backend that the texture import is "not implemented".  Is that a permanent thing?  Looking into interop it would involve a couple Vulkan calls to emulate a texture.

**Comment by pixelflinger** [comment]
@jwinarske I'm not sure what this bug is about anymore :-)
Can we close it and maybe reopen another issue/feature request?

**Comment by jwinarske** [comment]
@pixelflinger It's about Wayland blocks support of pbuffer, which means EGL as-is implementation is not compatible.  Closing as Vulkan is the focus.

**Comment by pixelflinger** [comment]
thanks! and happy new year! :-)
