### ISSUE TITLE
Segfault in cmgen with horizontal cross

### ISSUE THREAD

**Issue by emmcbd** [google/filament#45]
When I process a horizontal cross cubemap with cmgen, I get a segmentation fault in Cubemap.cpp::makeSeamless line 102.

When looking at the code :

        if (geometry == Geometry::HORIZONTAL_CROSS) { // horizontal cross
            stich(  getImageForFace(Face::NZ).getPixelRef(0, dim), bpp,
                    getImageForFace(Face::NY).getPixelRef(dim - 1, dim - 1), -bpp);

            stich(  getImageForFace(Face::NZ).getPixelRef(dim, 0), bpr,
                    getImageForFace(Face::NX).getPixelRef(0, 0), bpr);

            stich(  getImageForFace(Face::NY).getPixelRef(0, dim), bpp,
                    getImageForFace(Face::NZ).getPixelRef(dim - 1, dim - 1), -bpp);

        }

With this reference : http://iwearshorts.com/Mike/uploads/2015/04/map.jpg

If this reference is correct, in the last two stich calls, the right column of NZ (dim, 0) and the bottom row of NY (0, dim) are indeed outside the image.

There is probably the same issue with vertical cross, but I didn't try it.

**Comment by romainguy** [comment]
Thanks for the report. We mostly use rectilinear images, we must have introduced a regression to cross maps a while ago. We'll look into it.
