### ISSUE TITLE
Example for using a custom shader

### ISSUE THREAD

**Issue by senselevel** [google/filament#450]
Just started looking at filament.  I was wondering if there was an example somewhere for embedding a full custom fragment and vertex shader (not necessarily using the materials system).  I see fragment shaders like this : 

fragment {
 void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor.rgb = materialParams.baseColor;
        material.roughness = materialParams.roughness;
        material.metallic = materialParams.metallic;
        material.reflectance = materialParams.reflectance;
        material.clearCoat = materialParams.clearCoat;
        material.clearCoatRoughness = materialParams.clearCoatRoughness;
        material.anisotropy = materialParams.anisotropy;
    }
}

but is it possible to embed other stuff in here as well?  I scanned the documentation but could not see anything on this.

**Comment by senselevel** [comment]
I see this for skyboxes.  I'm assuming that the you want the material and materialVertex functions specially named, but can I do other things in here?

material {
    name : Skybox,
    parameters : [
        {
           type : samplerCubemap,
           name : skybox
        }
    ],
    variables : [
         eyeDirection
    ],
    vertexDomain : device,
    depthWrite : false,
    shadingModel : unlit
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        float3 sky = texture(materialParams_skybox, variable_eyeDirection.xyz).rgb;
        material.baseColor = vec4(sky, 1.0);
    }
}

vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        float3 p = getPosition().xyz;
        float3 u = mulMat4x4Float3(getViewFromClipMatrix(), p).xyz;
        material.eyeDirection.xyz = mulMat3x3Float3(getWorldFromViewMatrix(), u);
    }
}

**Comment by romainguy** [comment]
I'm not sure what you are asking about. You can create your own functions if you want to call them from `material()` and `materialVertex()`. And you can of course write pretty much anything you want inside those functions. What you cannot do however is write a complete shader from scratch. Could you describe your use case?

**Comment by senselevel** [comment]
My use case would be exactly that - write a custom shader from scratch.  I understand I'd have to intercept your light and other inputs.  I do see you point - pretty much anything is going to be surface appearance anyway but ideally I'd like to have control over the whole shader system - for example I might want to use a lighter-weight shader for certain objects in the scene, like handles, far way objects, etc in order to get reasonable performance in a large scene.  I assume what you are doing at the shader level is substituting those functions into a broader shader?

**Comment by romainguy** [comment]
That's correct, we inserting those functions in a larger shader system. It is not the goal of filament to offer this level of control over the shader system. We've been however thinking about doing auto simplification of shader (similar to a system of LOD).

**Comment by senselevel** [comment]
Ok, thanks.  Closing.
