### ISSUE TITLE
Triangle Strips?

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#4508]
### Discussed in https://github.com/google/filament/discussions/4506

<div type='discussions-op-text'>

<sup>Originally posted by **jeanlemotan** August 16, 2021</sup>
I've noticed that triangle strips are not supported in filament. Any reason for that?
I see that GL_PRIMITIVE_RESTART_FIXED_INDEX is also supported in GL ES 3.0 which allows an even bigger reduction of the index buffer size.</div>

**Comment by pixelflinger** [comment]
Might be worth investigating.

**Comment by prideout** [comment]
This is sort of unrelated but another thing to consider is supporting null IndexBuffer (i.e. non-indexed draw calls), which would be useful for glTF and for point sprites.

**Comment by romainguy** [comment]
The app/gltio can always generate an index buffer for this use case. I'm not sure it's worth us supporting it in Filament itself.

**Comment by pixelflinger** [comment]
It's this even supported in ES?

**Comment by jwwalker** [comment]
> It's this even supported in ES?

If by "this" you mean triangle strips, then yes, the OpenGL ES documentation for `glDrawElements` does list `GL_TRIANGLE_STRIP` as one of the accepted modes.

**Comment by romainguy** [comment]
We're not talking about triangle trips, we know they are supported. We were talking about index-less draw calls.

**Comment by romainguy** [comment]
The change just went in!

**Comment by romainguy** [comment]
https://github.com/google/filament/pull/5017
