### ISSUE TITLE
The latest sample rendertarget show abnormal in windows 10

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#4512]
When the sample first run ，just show black screen and a color rect in bottom_left. 
![wrong_rendertarget2](https://user-images.githubusercontent.com/3060688/129726176-1ab67844-3f57-47ca-bf48-9be6355d9d18.JPG)

After I drag the mouse in the window,the monkey obj can show sometimes, but there are nothing planar reflections be show.
I have used an older version filament but have the same issue.
The mode of camera and renderables is the same.
I used windows 10 os and a Intel(R) UHD Graphics 630 GPU do this test.

![wrong_rendertarge](https://user-images.githubusercontent.com/3060688/129726210-d9660df9-1cfa-44a6-81a5-8309cf315fe9.JPG)

**Comment by fanbinnet** [comment]
This is a gpu specific issue. I retest the same release .exe in an os windows 10 with gpu 1080 and 1660,it can work OK.
Just the Intel(R) UHD Graphics 630 GPU can not work.

**Comment by pixelflinger** [comment]
bug amnesty, too old, not actionable
