### ISSUE TITLE
Shader compiler errors on NVIDIA hardware

### ISSUE THREAD

**Issue by prideout** [google/filament#4515]
I think we're trying to use **unpackHalf2x16** on an OpenGL 4.1 platform without enabling the appropriate shading language extension.  Details follow.

When examining a glTF with additional lights (thus requiring froxelization) on a machine with GeForce RTX 2060 + Windows 10, I see the following:

> FEngine (64 bits) created at 00000128E6FE1080 (threading is enabled)
> FEngine resolved backend: OpenGL
> NVIDIA Corporation, GeForce RTX 2060/PCIe/SSE2, 4.1.0 NVIDIA 461.09, 4.10 NVIDIA via Cg compiler
> OS version: 0
> Froxel: 1024x640 / 40x40
> Froxel: 26x16x16 = 6656 (1536 lost)
> Froxel: 614x640 / 32x32
> Froxel: 20x20x16 = 6400 (1792 lost)
> Compilation error in fragment shader "Material":
> "0(4) : warning C7508: extension GOOGLE_cpp_style_line_directive not supported
> 0(3139) : error C7532: global function unpackHalf2x16 requires "#version 420" or later
> 0(3139) : error C0000: ... or #extension GL_ARB_shading_language_packing : enable

**Comment by romainguy** [comment]
@pixelflinger added code to inject that function on desktop and named it the same as the official GLSL function. It looks like the shader compiler is too eager and doesn't realize we have our own…

**Comment by romainguy** [comment]
@pixelflinger Looks like we'll need to go through some kind of #define on mobile and give the function a different name :/

**Comment by pixelflinger** [comment]
> @pixelflinger Looks like we'll need to go through some kind of #define on mobile and give the function a different name :/

Actually, another issue is that we want to drop GL4.1 support -- the only reason it exists now is because of MacOS, but now that we have a sold Metal backend it becomes moot.

I would be in favor of not accepting less than 4.3 on Windows and Linux.

**Comment by prideout** [comment]
@pixelflinger sounds ok to me but I should mention that my machine definitely supports newer GL, we're just selecting old GL.

For example, I can work around this by doing the following two things:

- Replace `410 core` with `420 core` in CodeGenerator.cpp
- Update WGL_CONTEXT_MINOR_VERSION_ARB in PlatformWGL

I'm happy to try other stuff too.

**Comment by pixelflinger** [comment]
This is weird because I inject the function only if GL Version is 4.1 and `GL_ARB_shading_language_packing` is not supported.

So I think this is squarely a driver bug.
