### ISSUE TITLE
NoCmake3.19

### ISSUE THREAD

**Issue by toby018** [google/filament#4528]
**Describe the bug**
I have done some searching and found that I should install CMake in SDK manager but the 3.19+ version does not show here as shown in the picture below.

NoCmake3.19

Is there anything that has to be done in order to have CMake 3.19?

Edit:

The android studio current version is 4.2.2
This happen when I want to try google/filament samples in android

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
You need to install CMake separately. On macOS the easiest way is to use HomeBrew.

**Comment by toby018** [comment]
What ninja version should I install when I get below wrong log?

-----------
* What went wrong:
Execution failed for task ':filament-android:buildCMakeDebug'.
> Build command failed.
  Error while executing process C:\Users\lWX885442\AppData\Local\Android\Sdk\cmake\3.21.1\bin\ninja.exe with arguments {-C D:\codebase\3rd\filament_toby\android\filament-android\.cxx\Debug\3l3v166c\arm64-v8a filament-jni}
  ninja: Entering directory `D:\codebase\3rd\filament_toby\android\filament-android\.cxx\Debug\3l3v166c\arm64-v8a'
  
  ninja: warning: bad deps log signature or version; starting over
  ninja: error: 'D:/codebase/3rd/filament_toby/out/android-release/filament/lib/arm64-v8a/libfilament.a', needed by '../../../../build/intermediates/cxx/Debug/3l3v166c/obj/arm64-v8a/libfilament-jni.so', missing and no known rule to make it

**Comment by romainguy** [comment]
You first need to build filament itself by following the instructions in BUILDING.md.
