### ISSUE TITLE
How to change transparency of a loaded .glb model at run time?

### ISSUE THREAD

**Issue by CallumHoughton** [google/filament#4530]
Hello all,

Fairly new to graphics programming and Filament, so I am unsure of what to do here. 

I would like to change the transparency of a loaded .glb model. [The previous issue here (#1918)](https://github.com/google/filament/issues/1918) shows you can do `setParameter("baseColorFactor", redValue, greenValue, blueValue, alpha)` which does adjust the transparency but obviously removes any of the previous RGB values of the "baseColorFactor" parameter.

Is it possible to retain the previous RGB values on the material and just adjust the alpha? I don't see anyway to read parameter values (I assume this is by design).

Or is there a better way to go about this? The high level idea is to have a UI slider which the user can use to adjust the transparency of the loaded model.

Thanks!

**Comment by romainguy** [comment]
Please use the "Discussions" tab for question. There is an ongoing [conversation](https://github.com/google/filament/discussions/4504) on this topic already.
