### ISSUE TITLE
Metal crashes after recent commit

### ISSUE THREAD

**Issue by jwwalker** [google/filament#4534]
**Describe the bug**

In my app, if I close the window (which destroys the View, Scene, SwapChain etc., pretty much everything except the Engine) and then open another window, there is a crash inside the metal driver.  This started happening as of an August 19 commit [7f4832706].  That is, I verified that the crash doesn't happen in the previous commit, and does happen with this one.

So far I haven't been able to construct a  simple sample that will reproduce the problem.  I can tell you that it's crashing in the function `backend::metal::MetalBuffer::getGpuBufferForDraw`, line 88 of the file MetalBuffer.mm, and the buffer's `mContext` pointer has a bogus-looking value like zero or 0xEFEFEFEFEFEFEFEF.  In the calling function, `MetalBuffer::bindBuffers`, the loop counter `b` always seems to be 1.

**Desktop:**
 - OS: macOS 11.5.2 (20G95)
 - GPU: Radeon Pro 560X
 - Backend: Metal

**Additional context**

An Apple crash log:

[FilamentViewer-Metal_2021-08-20-161008_James-Walker-Home-Lap.crash.zip](https://github.com/google/filament/files/7024432/FilamentViewer-Metal_2021-08-20-161008_James-Walker-Home-Lap.crash.zip)

**Comment by jwwalker** [comment]
Now I have a self-contained Xcode project to replicate the crash: 

[MetalCrash.zip](https://github.com/google/filament/files/7026466/MetalCrash.zip)

See the enclosed README.md file for information on setting up the project and replicating the crash.

**Comment by pixelflinger** [comment]
@bejado the EF pattern indicates we're dereferencing into a freed buffer.

**Comment by bejado** [comment]
Thanks for the report, I'll take a look this week.
