### ISSUE TITLE
Setting an empty scene

### ISSUE THREAD

**Issue by Stefterv** [google/filament#4536]
**Describe the bug**
View->setScene doesn't warn or error when an empty pointer is given.

**To Reproduce**
`
view->setScene(scene);
`
Works as expected

`
view->setScene(nullptr);
`
Stops all rendering from happening, a warning would be helpful when trying to debug issues with the rendering setup.

**Expected behavior**
Either some of the rendering should still happen (e.g. the background) or a warning should pop up explaining an empty scene is being rendered

**Desktop (please complete the following information):**
 - OS: iOS
 - GPU: Apple A14 GPU
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro

**Additional context**

**Comment by romainguy** [comment]
`nullptr` is a valid value to pass, as documented:

```
\p scene can be nullptr to dissociate the currently set Scene
     from this View.\n
```

There should be no warning when `nullptr` is passed as it is the correct way to "unset" the scene on a `View`.
