### ISSUE TITLE
How do I find the model node corresponding to where I click on the screen?

### ISSUE THREAD

**Issue by cwwng** [google/filament#4541]
1、Load a GLTF model.
2、The GLTF model consists of many nodes.
3、When the screen position is clicked, the model node for the current clicked position needs to be highlighted.

The question is, how do I find the model node corresponding to where I clicked?

macOS、iOS platform.
Thanks

**Comment by fanbinnet** [comment]
https://github.com/google/filament/issues/4266

**Comment by romainguy** [comment]
Please use [discussions](https://github.com/google/filament/discussions) for questions.
