### ISSUE TITLE
basic blit fails on Vulkan on Mac

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#4542]
When the screen is scaled rendering is all garbage.
This code path uses a "blit" instead of geometry for scaling.

![Screen Shot 2021-08-24 at 2 25 22 PM](https://user-images.githubusercontent.com/1240896/130692146-2ad49ffc-83c2-4490-84e6-b19884e35c77.png)

**Comment by prideout** [comment]
@pixelflinger This might be fixed, I tried playing with the "Dynamic Resolution" menu and am unable to repro.
