### ISSUE TITLE
Building Filament for Android on Windows

### ISSUE THREAD

**Issue by toby018** [google/filament#4544]
**Describe the bug**
ninja matc resgen cmgen run fail
**To Reproduce**
D:\codebase\3rd\filament_toby\out\cmake-release>ninja matc resgen cmgen
[6/421] Building CXX object libs\utils\CMakeFiles\utils.dir\src\JobSystem.cpp.obj
FAILED: libs/utils/CMakeFiles/utils.dir/src/JobSystem.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\utils\CMakeFiles\utils.dir\src\JobSystem.cpp.obj /Fdlibs\utils\CMakeFiles\utils.dir\utils.pdb /FS -c D:\codebase\3rd\filament_toby\libs\utils\src\JobSystem.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[7/421] Building CXX object libs\utils\CMakeFiles\utils.dir\src\Profiler.cpp.obj
FAILED: libs/utils/CMakeFiles/utils.dir/src/Profiler.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\utils\CMakeFiles\utils.dir\src\Profiler.cpp.obj /Fdlibs\utils\CMakeFiles\utils.dir\utils.pdb /FS -c D:\codebase\3rd\filament_toby\libs\utils\src\Profiler.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[8/421] Building CXX object libs\ibl\CMakeFiles\ibl.dir\src\CubemapUtils.cpp.obj
FAILED: libs/ibl/CMakeFiles/ibl.dir/src/CubemapUtils.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\ibl\include -ID:\codebase\3rd\filament_toby\libs\math\include -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /fp:fast /showIncludes /Folibs\ibl\CMakeFiles\ibl.dir\src\CubemapUtils.cpp.obj /Fdlibs\ibl\CMakeFiles\ibl.dir\ibl.pdb /FS -c D:\codebase\3rd\filament_toby\libs\ibl\src\CubemapUtils.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[9/421] Building CXX object libs\ibl\CMakeFiles\ibl.dir\src\CubemapSH.cpp.obj
FAILED: libs/ibl/CMakeFiles/ibl.dir/src/CubemapSH.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\ibl\include -ID:\codebase\3rd\filament_toby\libs\math\include -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /fp:fast /showIncludes /Folibs\ibl\CMakeFiles\ibl.dir\src\CubemapSH.cpp.obj /Fdlibs\ibl\CMakeFiles\ibl.dir\ibl.pdb /FS -c D:\codebase\3rd\filament_toby\libs\ibl\src\CubemapSH.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[10/421] Building CXX object libs\utils\CMakeFiles\utils.dir\src\CallStack.cpp.obj
FAILED: libs/utils/CMakeFiles/utils.dir/src/CallStack.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\utils\CMakeFiles\utils.dir\src\CallStack.cpp.obj /Fdlibs\utils\CMakeFiles\utils.dir\utils.pdb /FS -c D:\codebase\3rd\filament_toby\libs\utils\src\CallStack.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[11/421] Building CXX object libs\utils\CMakeFiles\utils.dir\src\ashmem.cpp.obj
FAILED: libs/utils/CMakeFiles/utils.dir/src/ashmem.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\utils\CMakeFiles\utils.dir\src\ashmem.cpp.obj /Fdlibs\utils\CMakeFiles\utils.dir\utils.pdb /FS -c D:\codebase\3rd\filament_toby\libs\utils\src\ashmem.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[12/421] Building CXX object libs\filabridge\CMakeFiles\filabridge.dir\src\SibGenerator.cpp.obj
FAILED: libs/filabridge/CMakeFiles/filabridge.dir/src/SibGenerator.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\filabridge\include -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. -ID:\codebase\3rd\filament_toby\libs\math\include -ID:\codebase\3rd\filament_toby\filament\backend\include /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\filabridge\CMakeFiles\filabridge.dir\src\SibGenerator.cpp.obj /Fdlibs\filabridge\CMakeFiles\filabridge.dir\filabridge.pdb /FS -c D:\codebase\3rd\filament_toby\libs\filabridge\src\SibGenerator.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[13/421] Building CXX object libs\utils\CMakeFiles\utils.dir\src\Allocator.cpp.obj
FAILED: libs/utils/CMakeFiles/utils.dir/src/Allocator.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\utils\CMakeFiles\utils.dir\src\Allocator.cpp.obj /Fdlibs\utils\CMakeFiles\utils.dir\utils.pdb /FS -c D:\codebase\3rd\filament_toby\libs\utils\src\Allocator.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[14/421] Building CXX object libs\utils\CMakeFiles\utils.dir\src\Path.cpp.obj
FAILED: libs/utils/CMakeFiles/utils.dir/src/Path.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\utils\CMakeFiles\utils.dir\src\Path.cpp.obj /Fdlibs\utils\CMakeFiles\utils.dir\utils.pdb /FS -c D:\codebase\3rd\filament_toby\libs\utils\src\Path.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[15/421] Building CXX object libs\utils\CMakeFiles\utils.dir\src\NameComponentManager.cpp.obj
FAILED: libs/utils/CMakeFiles/utils.dir/src/NameComponentManager.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\utils\CMakeFiles\utils.dir\src\NameComponentManager.cpp.obj /Fdlibs\utils\CMakeFiles\utils.dir\utils.pdb /FS -c D:\codebase\3rd\filament_toby\libs\utils\src\NameComponentManager.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[16/421] Building CXX object libs\ibl\CMakeFiles\ibl.dir\src\CubemapIBL.cpp.obj
FAILED: libs/ibl/CMakeFiles/ibl.dir/src/CubemapIBL.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\ibl\include -ID:\codebase\3rd\filament_toby\libs\math\include -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /fp:fast /showIncludes /Folibs\ibl\CMakeFiles\ibl.dir\src\CubemapIBL.cpp.obj /Fdlibs\ibl\CMakeFiles\ibl.dir\ibl.pdb /FS -c D:\codebase\3rd\filament_toby\libs\ibl\src\CubemapIBL.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[17/421] Building CXX object libs\image\CMakeFiles\image.dir\src\ImageSampler.cpp.obj
FAILED: libs/image/CMakeFiles/image.dir/src/ImageSampler.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\image\include -ID:\codebase\3rd\filament_toby\libs\math\include -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /fp:fast /showIncludes /Folibs\image\CMakeFiles\image.dir\src\ImageSampler.cpp.obj /Fdlibs\image\CMakeFiles\image.dir\image.pdb /FS -c D:\codebase\3rd\filament_toby\libs\image\src\ImageSampler.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[18/421] Building CXX object libs\filabridge\CMakeFiles\filabridge.dir\src\SamplerBindingMap.cpp.obj
FAILED: libs/filabridge/CMakeFiles/filabridge.dir/src/SamplerBindingMap.cpp.obj
D:\PROGRA~3\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DFILAMENT_SUPPORTS_OPENGL -ID:\codebase\3rd\filament_toby\libs\filabridge\include -ID:\codebase\3rd\filament_toby\libs\utils\include -ID:\codebase\3rd\filament_toby\third_party\robin-map\tnt\.. -ID:\codebase\3rd\filament_toby\libs\math\include -ID:\codebase\3rd\filament_toby\filament\backend\include /std:c++latest /W0 /Zc:__cplusplus -D_USE_MATH_DEFINES=1 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE  /MT /Zi -MD /showIncludes /Folibs\filabridge\CMakeFiles\filabridge.dir\src\SamplerBindingMap.cpp.obj /Fdlibs\filabridge\CMakeFiles\filabridge.dir\filabridge.pdb /FS -c D:\codebase\3rd\filament_toby\libs\filabridge\src\SamplerBindingMap.cpp
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.
[23/421] Generate extended instruction tables for opencl.debuginfo.100.
ninja: build stopped: subcommand failed.

**Expected behavior**

**Screenshots**

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
It looks like there's a problem with your setup/install:

D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h(555): fatal error C1189: #error: STL1001: Unexpected compiler version, expected MSVC 19.29 or newer.

The error occurs in msvc's headers not in Filament's code.

**Comment by romainguy** [comment]
Looks like you are compiling with msvc 14 instead of 19?
