### ISSUE TITLE
Tangent frames are deformed using JavaScript SurfaceOrientation$Builder

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#4551]
**Description**
Tangent frames are incorrect when using the JavaScript bindings to create them and set them into the vertex buffer.  See this discussion for screen shots: #4434 and #4441

**To Reproduce**
Here is some sample TypeScript code which illustrates the problem.  The WebGL material shader used is the same as in this issue: #4441 
`      
 private testTangentFrames(engine: Filament.Engine, scene: Filament.Scene, matInst: Filament.MaterialInstance) {

            // Geometry
            var vertices: number[] = [
                -3.0, 1.0, 35.0,
                3.0, 1.0, 35.0,
                3.0, 1.0, 37.0,
                -3.0, 1.0, 37.0
            ];

            var indices: number[] = [0, 1, 2, 0, 2, 3];

            var uvCoords: number[] = [
                -2.5, -0.5,
                1.5, -0.5,
                1.5, 3.0,
                -2.5, 3.0
            ];

            var normals: number[] = [
                0.0, -1.0, 0.0,
                0.0, -1.0, 0.0,
                0.0, -1.0, 0.0,
                0.0, -1.0, 0.0
            ];

            var vertCount = vertices.length / 3;
            var triCount = indices.length / 3;

            // Create vertex buffer
            var vStride = 20;  // Pos + UVs (12 + 8)
            var vBuffer = Filament.VertexBuffer.Builder()
                .bufferCount(2)
                .vertexCount(vertCount)
                .attribute(Filament.VertexAttribute.POSITION, 0, Filament.VertexBuffer$AttributeType.FLOAT3, 0, vStride)
                .attribute(Filament.VertexAttribute.UV0, 0, Filament.VertexBuffer$AttributeType.FLOAT2, 12, vStride)
                .attribute(Filament.VertexAttribute.TANGENTS, 1, Filament.VertexBuffer$AttributeType.SHORT4, 0, 0)
                .normalized(Filament.VertexAttribute.TANGENTS)
                .build(this._engine);

            // Create index buffer
            var iBuffer = Filament.IndexBuffer.Builder()
                .bufferType(Filament.IndexBuffer$IndexType.USHORT)
                .indexCount(indices.length)
                .build(engine);

            // Create tangents
            var sob = new Filament.SurfaceOrientation$Builder();
            sob.vertexCount(vertCount);
            sob.normals(new Float32Array(normals), 0);
            sob.uvs(new Float32Array(uvCoords), 0);
            sob.positions(new Float32Array(vertices), 0);
            sob.triangleCount(triCount);
            sob.triangles32(new Uint32Array(indices));
            var orientation = sob.build();
            var quatsBuffer = orientation.getQuats(vertCount);

            // Interleave vertex data
            var vSize = vStride / 4;
            var interleave = new Float32Array(vertCount * vSize);
            var bBoxMinX, bBoxMinY, bBoxMinZ: number;
            var bBoxMaxX, bBoxMaxY, bBoxMaxZ: number;
            for (var idx = 0; idx < vertCount; ++idx) {
                //Positions
                var posX = vertices[idx * 3];
                var posY = vertices[idx * 3 + 1];
                var posZ = vertices[idx * 3 + 2];
                if (idx == 0) {
                    bBoxMinX = bBoxMaxX = posX;
                    bBoxMinY = bBoxMaxY = posY;
                    bBoxMinZ = bBoxMaxZ = posZ;
                } else {
                    bBoxMinX = Math.min(bBoxMinX, posX);
                    bBoxMinY = Math.min(bBoxMinY, posY);
                    bBoxMinZ = Math.min(bBoxMinZ, posZ);
                    bBoxMaxX = Math.max(bBoxMaxX, posX);
                    bBoxMaxY = Math.max(bBoxMaxY, posY);
                    bBoxMaxZ = Math.max(bBoxMaxZ, posZ);
                }
                interleave[idx * vSize] = posX;
                interleave[idx * vSize + 1] = posY;
                interleave[idx * vSize + 2] = posZ;

                //UVs
                interleave[idx * vSize + 3] = uvCoords[idx * 2]
                interleave[idx * vSize + 4] = uvCoords[idx * 2 + 1]
            }

            // Set vertex and index buffer data
            vBuffer.setBufferAt(engine, 0, interleave, 0);
            vBuffer.setBufferAt(engine, 1, quatsBuffer, 0);
            iBuffer.setBuffer(engine, new Uint16Array(indices), 0);
            orientation.delete();

            // Bounding box
            var bbCenter: number[] = [(bBoxMinX + bBoxMaxX) / 2, (bBoxMinY + bBoxMaxY) / 2, (bBoxMinZ + bBoxMaxZ) / 2];
            var bbHalfExtent: number[] = [(bBoxMaxX - bBoxMinX) / 2, (bBoxMaxY - bBoxMinY) / 2, (bBoxMaxZ - bBoxMinZ) / 2];
            var bBox = new Box(bbCenter, bbHalfExtent);

            // Create mesh
            var newEntity = Filament.EntityManager.get().create();
            Filament.RenderableManager.Builder(1)
                .boundingBox(bBox)
                .material(0, matInst)
                .geometryOffset(0, Filament.RenderableManager$PrimitiveType.TRIANGLES, vBuffer, iBuffer, 0, indices.length)
                .culling(true)
                .castShadows(true)
                .receiveShadows(true)
                .build(this._engine, newEntity);

            // Add to scene
            scene.addEntity(newEntity);
        }
`

**Expected behavior**
See issue #4441 for screen shots of correct behavior on desktop using OpenGL backend

**Additional context**
I have done every permutation of parameters and vertex buffer attributes I can think of.  I believe the trouble must either exist in the shader, in SurfaceOrientation$Builder, or somewhere in the marshalling of tangent data between them.

**Comment by BStringhamVRSK** [comment]
@romainguy @prideout 
Do you know if you will be able to take a look at this anytime soon?  We have an upcoming product release that needs this fix (no pressure! :)).  If this was a desktop bug, I would try to debug it myself, but, being fairly new at web development, I'll have to defer to your experience.

**Comment by romainguy** [comment]
Sorry it's going to take a bit longer as @prideout is not available.

**Comment by BStringhamVRSK** [comment]
Thanks for letting me know.  If we can get it fixed in the next couple of weeks, we are good.  If not, maybe I could get some pointers on how to approach this for library-level web debugging?

**Comment by romainguy** [comment]
I took a look at our code and I don't see any obvious issue. Here's the `getQuats()` implementation:

```
    Filament.SurfaceOrientation.prototype.getQuats = function(nverts) {
        const attribType = Filament.VertexBuffer$AttributeType.SHORT4;
        const quatsBufferSize = 8 * nverts;
        const quatsBuffer = Filament._malloc(quatsBufferSize);
        this._getQuats(quatsBuffer, nverts, attribType);
        const arrayBuffer = Filament.HEAPU8.subarray(quatsBuffer, quatsBuffer + quatsBufferSize).slice().buffer;
        Filament._free(quatsBuffer);
        return new Int16Array(arrayBuffer);
    };
```

And `_getQuats()`:

```
class_<SurfaceOrientation>("SurfaceOrientation")
    .function("_getQuats", EMBIND_LAMBDA(void, (SurfaceOrientation* self,
            intptr_t out, size_t quatCount, VertexBuffer::AttributeType attrtype), {
        switch (attrtype) {
            case VertexBuffer::AttributeType::FLOAT4: {
                self->getQuats((filament::math::quatf*) out, quatCount);
                break;
            }
            case VertexBuffer::AttributeType::HALF4: {
                self->getQuats((filament::math::quath*) out, quatCount);
                break;
            }
            case VertexBuffer::AttributeType::SHORT4: {
                self->getQuats((filament::math::short4*) out, quatCount);
                break;
            }
            default:
                utils::slog.e << "Unsupported quaternion type." << utils::io::endl;
        }
    }), allow_raw_pointers());
```

**Comment by BStringhamVRSK** [comment]
@romainguy  Nothing pops out as a problem to me, either.  I think it must be something subtle, such as: a SHORT4 value getting treated/cast as signed in one context and unsigned in another, for example.
Were you able to run my code and reproduce the error?  My problem is that I can't tell if the quaternion values the SurfaceOrientation$Builder generates are making it into the vertex buffer unaltered.  I suspect that they are getting interpreted incorrectly at some point in my process (such as signed/unsigned problems), but I can't tell where or how.

**Comment by BStringhamVRSK** [comment]
@romainguy @prideout 
Any new revelations on this?

**Comment by romainguy** [comment]
Thanks for figuring this out! I think we have an open bug already about transfer function related issues in mipgen (https://github.com/google/filament/issues/2422 but it seems ASTC specific). Is the issue here that we interpret the gamma field on normal maps?
