### ISSUE TITLE
build  android error

### ISSUE THREAD

**Issue by ouxiang** [google/filament#4560]
when I completed build，I open  the android example with android studio,there is a error.

![image](https://user-images.githubusercontent.com/7112672/131223944-a8500aa9-8bdd-4c31-b21b-f7ca366864a4.png)
I do not know why.

**Comment by romainguy** [comment]
You need to open the android/ folder as a project. The samples are subprojects.

**Comment by ouxiang** [comment]
> You need to open the android/ folder as a project. The samples are subprojects.

The sample-gltf-viewer of example is not run. Other examples can run. This is error: the variable of animationCount,the 
functions of  applyAnimation and updateBoneMatrices not found。
![image](https://user-images.githubusercontent.com/7112672/131247966-96334666-7dbb-4386-a734-2277debafc59.png)
