### ISSUE TITLE
Async issues with upgrade from 1.11 to 1.12

### ISSUE THREAD

**Issue by elalish** [google/filament#4565]
During the course of [upgrading](https://github.com/google/model-viewer/pull/2741) filament for our render fidelity tests, I'm running into some strange problems. First, we seem to have a new race condition, as a number of the renders are showing up blank, but upon further runs, they just seem to be flaky. Is there something extra we need to await now to ensure the render is done before we screenshot it? The relevant code is [here](https://github.com/google/model-viewer/blob/master/packages/render-fidelity-tools/src/components/renderers/filament-viewer.ts). 

Also, every test is now spitting this error, though it doesn't seem to adversely affect anything:
```
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
➡️ falling back to ArrayBuffer instantiation
➡️ FEngine (32 bits) created at 0x80a7c0 (threading is disabled)
```
And some of the tests are also showing this: 
`➡️ [entity=39, primitive @ 0] missing required attributes (0x1f), declared=0x1d`

Any thoughts, @prideout?

**Comment by romainguy** [comment]
@elalish `[entity=39, primitive @ 0] missing required attributes (0x1f), declared=0x1d`

This means the material expects these attributes: position, color, tangents, uv0, and uv1, but you provided position, color, uv0, and uv1 (no tangents).

**Comment by elalish** [comment]
Interesting; do you think these khronos sample models are invalid? I thought tangents were optional...

**Comment by romainguy** [comment]
Tangents = normals + tangent/bitangent in Filament (we always encode all 3 together as a single quaternion). If a model doesn't provide them, the glTF loader should compute them. Do you have an example of a model that triggers the message? I can try and repro but I don't recall seeing this issue in our native glTF viewer with any model.

**Comment by elalish** [comment]
I'm seeing it with khronos-Triangle and khronos-SimpleMorph as well as several others.

**Comment by romainguy** [comment]
I can reproduce in the native viewer, thank you!

**Comment by romainguy** [comment]
@bejado @pixelflinger `gltf_viewer` shows the missing required attribute when loading the `Triangle` sample from Khrono's glTF samples repository:

`[entity=83, primitive @ 0] missing required attributes (0x3), declared=0x1`

**Comment by pixelflinger** [comment]
And we think it's a recent regression, yes?

**Comment by romainguy** [comment]
@elalish I'm not a JavaScript specialist but if you are reusing `updateScenario`, is it possible that you [have a race](https://github.com/google/model-viewer/blob/master/packages/render-fidelity-tools/src/components/renderers/filament-viewer.ts#L155)? You are destroying existing entities/assets when a new asset is requested for render but I don't see any synchronization/await on the rendering itself.

**Comment by elalish** [comment]
We were waiting for one animation frame after loading, but changing it to two seems to have fixed the async issue. Surprised I haven't seen that before now.
