### ISSUE TITLE
Error when ANGLE backend is OpenGL

### ISSUE THREAD

**Issue by cx20** [google/filament#4573]
**Describe the bug**
I changed the ANGLE backend to OpenGL to get around the [NVIDIA GPU issue](https://github.com/google/filament/issues/3151).
However, this method now seems to cause a crash when the following page is displayed.
https://google.github.io/filament/webgl/suzanne.html
This method used to work, but now it does not seem to work.

**To Reproduce**
1. Change the `ANGLE` backend to `OpenGL` at `chrome://flags/`

![image](https://user-images.githubusercontent.com/1833979/131676635-77b222d1-809a-4340-a239-14f8f57e83c5.png)

2. Go to the following page.
https://google.github.io/filament/webgl/suzanne.html
-> The screen will go black and an error will be output to the console.

**Expected behavior**
I expect that the model will be displayed without errors.

**Screenshots**
The screen is completely dark.

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.
```
filament.js:9 
in static filament::backend::Driver *filament::OpenGLDriver::create(filament::backend::OpenGLPlatform *const, void *const):126
reason: Can't get OpenGL version

suzanne.html:1 
[.WebGL-00007812023C7B80] GL_INVALID_OPERATION: Extension is not requestable.

filament.wasm:0x10dc8b 
Uncaught (in promise) RuntimeError: null function or function signature mismatch
    at filament.wasm:0x10dc8b
    at filament.wasm:0x1aa88
    at Function.Engine$_create [as _create] (eval at new_ (filament.js:9), <anonymous>:7:10)
    at Function.Filament.Engine.create (filament.js:223)
    at new App (suzanne.html:56)
    at suzanne.html:50
    at taskFinished (filament.js:65)
    at filament.js:83
```

**Desktop (please complete the following information):**
 - OS: Widows 10
 - Browser : Chrome 92
 - GPU: GeForce RTX 2060
 - Backend: ANGLE + OpenGL

**Comment by romainguy** [comment]
Seems like an issue in ANGLE?

**Comment by cx20** [comment]
Oops. I have encountered that error in the past. Certainly it may be related to ANGLE.
https://github.com/google/filament/issues/3939#issuecomment-848247342

**Comment by pixelflinger** [comment]
That option is not available on my Chrome on Mac.

**Comment by cx20** [comment]
> That option is not available on my Chrome on Mac.

Probably only `Windows` has `ANGLE` setting so far.

BTW, When I change the Chrome's `ANGLE` backend from `Default` to `OpenGL` and try to view the Emscripten WebGL sample (Filament is not used)  below, I get an error message on the console.
https://cx20.github.io/webgl-test/examples/wasm/triangle/index.html
```
GL_INVALID_OPERATION: Extension is not requestable.
```

My guess is that if the above error occurs, Filament will detect the error and stop.

https://github.com/google/filament/blob/00d36110d528991ebeae4d45d28be3dbb206bd9e/filament/backend/src/opengl/OpenGLDriver.cpp#L125-L130

> Seems like an issue in ANGLE?

The _"Extension is not requestable."_ error is displayed independently of the Filament, so as you might expect, it could be an `ANGLE` issue. I think it worked a few months ago, so I think the behavior has changed with recent versions of Chrome.

Where should I report the problem in this case? Is it a Chrome browser issue report?

**Comment by romainguy** [comment]
If the issue happens with a basic WebGL sample, then yes filing the issue with the Chrome team is probably the best next step.

**Comment by cx20** [comment]
@romainguy Thank you for your advice. 

BTW, do you know where to bug report for `NVIDIA`?
I've been wondering what the cause of the #3151 problem is.
