### ISSUE TITLE
glTF conformance: khronos-RecursiveSkeletons

### ISSUE THREAD

**Issue by elalish** [google/filament#4575]
Looks like the recursive skeletons have having some trouble: https://modelviewer.dev/fidelity/#khronos-RecursiveSkeletons

**Comment by romainguy** [comment]
I noticed that as well, thanks for filing the issue.

**Comment by romainguy** [comment]
This now works.

**Comment by elalish** [comment]
Anyone up for updating the MV render fidelity tests to the latest Filament release when this is out and generating new goldens?

**Comment by romainguy** [comment]
The fix is already available in recent versions btw.

**Comment by prideout** [comment]
The render fidelity tests need to call `updateBoneMatrices()`.  I can make this change myself since I'm already mucking around in there.
