### ISSUE TITLE
problem to use filament for building hello-triangle in ios

### ISSUE THREAD

**Issue by mstfabbstbr** [google/filament#4592]
i wanna use hello-triangle ios sample, and when i run `./build.sh -p desktop -i release` the following error shows to me:

<img width="891" alt="Screen Shot 1400-06-15 at 10 18 38" src="https://user-images.githubusercontent.com/54117642/132167039-91737202-9579-4c8a-8add-1477ef8051ea.png">

**how to solve this error?**
i'm not fimiliar with this error..

**Comment by romainguy** [comment]
You need to install `ninja` first as explained in our readmes.

**Comment by mstfabbstbr** [comment]
now i'm install ninja

> ninja --version

> 1.10.2

but this errors still here:
<img width="886" alt="Screen Shot 1400-06-15 at 10 56 26" src="https://user-images.githubusercontent.com/54117642/132170391-c8fbdb16-7225-49f8-a97c-9e74bf5b787f.png">

**Comment by romainguy** [comment]
Then rm -Rf out/

**Comment by mstfabbstbr** [comment]
nothing happend.. and that error shows me again

**Comment by bejado** [comment]
@mstfabbstbr Please run exactly the following and show the output:
```
ninja --version
cmake --version
rm -rf out
./build.sh -p desktop -i release
```
