### ISSUE TITLE
MaterialInstance constructed by 'duplicate' lead to a crash on Android 

### ISSUE THREAD

**Issue by RockVampire** [google/filament#4593]
platform : Android
I‘m trying to get the new `MaterialInstance` like this 
`otherMaterialInstance = MaterialInstance.duplicate(oldMaterialInstance,"light")`.
Then I got a new crash when calling 
`RenderableManager.setMaterialInstanceAt(entity,0,otherMaterialInstance)`
The crash Log remind me I'm calling method on destroyed Material.

 ```
E/InputEventReceiver: Exception dispatching input event.
 E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.IllegalStateException: Calling method on destroyed Material
```

I debug into the method and found it crashed in the row
` int required = materialInstance.getMaterial().getRequiredAttributesAsInt(); when 'getRequiredAttributesAsInt()'`
in the java class  `RenderableManager` 
I compared the two MaterialInstance , it seems the MaterialInstance I got from MaterialInstance.duplicate() comes from the constructor` MaterialInstance(@NonNull Material material, long nativeMaterialInstance) `. It seems missing 
`mNativeMaterial = nGetMaterial(mNativeObject); `
by contract.

**Comment by romainguy** [comment]
Thanks, I'll upload a fix right away.
