### ISSUE TITLE
when using gltfio-lite: sample-gltf-viewer error, dlopen failed: cannot locate symbol

### ISSUE THREAD

**Issue by sniperPqc** [google/filament#4601]
I run the sample sample-gltf-viewer found error,  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt6__ndk113basic_istreamIcNS_11char_traitsIcEEED0Ev" referenced by "/data/app/com.google.android.filament.gltf-SYMAGavDLh2YGITG9Qxsew==/lib/arm64/libfilament-utils-jni.so"...

this is my dependencies:
    implementation 'com.google.android.filament:filament-android:1.12.3'
    implementation 'com.google.android.filament:gltfio-android-lite:1.12.3'
    implementation 'com.google.android.filament:filament-utils-android-lite:1.12.3'

I want to use the lite version of filament, is there something wrong with my setting?

**Comment by romainguy** [comment]
On what device/version of Android does this happen?

**Comment by sniperPqc** [comment]
On Redmi Note 9 and HONOR V20, the os both is Android 10, it seems nothing about with device.

**Comment by sniperPqc** [comment]
> On what device/version of Android does this happen?
On Redmi Note 9 and HONOR V20, the os both is Android 10, it seems nothing about with device.

**Comment by romainguy** [comment]
I cannot reproduce the issue.

**Comment by rawnsley** [comment]
I'm seeing the same thing on all three Android devices (including a Pocophone F1) here on the bench after building from the current main branch. I'll see if I can work out what's going on.

**Comment by romainguy** [comment]
@pixelflinger @bejado Can you try and repro on a device? I can't repro in emulators.

**Comment by bejado** [comment]
@romainguy Sure, I'll give it a try

**Comment by bejado** [comment]
I'm able to reproduce, but I'm not sure what's going on. I'll continue investigating.

**Comment by pixelflinger** [comment]
Uh, I have no problem running on a device.

@rawnsley have you tried to *uninstall* the APK from the device?

**Comment by rawnsley** [comment]
> Uh, I have no problem running on a device.
> 
> @rawnsley have you tried to _uninstall_ the APK from the device?

Do you mean a complete uninstall before installing and running? I can certainly try it tomorrow.

BTW it crashes for me immediately on initialising the util library with `Utils.init()`, but the filament and filamat libraries are working fine.

**Comment by pixelflinger** [comment]
nevermind I didn't realize you were using the `lite` version.

**Comment by pixelflinger** [comment]
For the record the missing symbol is `std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char> >::~basic_istream()`

**Comment by pixelflinger** [comment]
@sniperPqc note that even with the fix above the `sample-gltf-viewer` will fail on startup with a NPE -- this is only because the default glTF model is compressed with draco and in `lite` mode draco is not supported.
