### ISSUE TITLE
Android Studio cannot find Cmake 3.19.0+

### ISSUE THREAD

**Issue by Sardorbekcyber** [google/filament#4609]
Hello after opening android/samples I cannot run samples because android studio showing me that latest version of Cmake is 3.18.1 but project requires 3.19.0 what is a go around?

![image](https://user-images.githubusercontent.com/58398866/132948345-acb57afa-3efd-4042-853f-e381d3c79014.png)

**Comment by romainguy** [comment]
You need to install CMake on your machine outside of Studio.
