### ISSUE TITLE
What's the lowest ndk version for filament android build.

### ISSUE THREAD

**Issue by hushuhui** [google/filament#4614]
In our filament project, I can easily see the ndk version of filament android is '22.1.7171670', but in almost cases, we use lower ndk version. So, is there a version threshold for filament android build by using ndk.

**Comment by romainguy** [comment]
that's the version of the NDK we use to build Filament, you should be able to use 20 or 21.

**Comment by hushuhui** [comment]
> that's the version of the NDK we use to build Filament, you should be able to use 20 or 21.

Could you pls tell me the reason of the high ndk version, and can we downgrade the ndk version by changing something in filament project?

**Comment by romainguy** [comment]
Are you compiling filament yourself? Otherwise it should probably not matter.

**Comment by hushuhui** [comment]
> Are you compiling filament yourself? Otherwise it should probably not matter.

yep, I build filament by myself, I use cpp static library.
