### ISSUE TITLE
Material Java Object isn't initialized when MaterialInstance creating

### ISSUE THREAD

**Issue by RockVampire** [google/filament#4615]
platform : Android

First,Thanks for fixing the bug #4593 so fast!
But there's also another a little problem about `Material` and  `MaterialInstance` on Android.
When I get a `MaterialInstance`  by the method 'RenderableManager.getMaterialInstanceAt()' ,I find the Member Variable java object `Material` won''t be initialized ,and will result a crash when use the `MaterialInstance` you got directly.For example ,  'RenderableManager.setMaterialInstanceAt()' .
Now ,I bypassed it calling `MaterialInstance.getMaterial` Manually. 

Does it necessary initialize the java object `Material` in the constructor of 'MaterialInstance' ,or warning the developer to call 'getMaterial()' first  when using `MaterialInstance`  ?

**Comment by romainguy** [comment]
Where do you see the crash? `RenderableManager.setMaterialInstanceAt()` calls `MaterialInstance.getMaterial()` everywhere it needs access to the material.

**Comment by RockVampire** [comment]
> Where do you see the crash? `RenderableManager.setMaterialInstanceAt()` calls `MaterialInstance.getMaterial()` everywhere it needs access to the material.

OK,I got a mistake. The crash happens when I'm calling `MaterialInstance.duplicate()` by putting the `MaterialInstance` I got from `RenderableManager .getMaterialInstanceAt`

**Comment by romainguy** [comment]
Thanks but what's the crash?

**Comment by RockVampire** [comment]
> Thanks but what's the crash?
`duplicate()` returns a `MaterialInstance` with the constructor 
   ```
  MaterialInstance(@NonNull Material material, long nativeMaterialInstance) {
        mMaterial = material;
        mNativeMaterial = material.getNativeObject();
        mNativeObject = nativeMaterialInstance;
    }
```
Crash comes where`mNativeMaterial = material.getNativeObject();` 
The material here is a nullptr.

**Comment by romainguy** [comment]
Thanks, I just pushed a fix.
