### ISSUE TITLE
Setting DepthOfFieldOptions on Android causes performance drop even when disabled

### ISSUE THREAD

**Issue by rawnsley** [google/filament#4617]
I pulled in the latest changes since the beginning of the year and noticed as significant performance drop. I traced it to the setting the DepthOfFieldOptions property on my View object to a new object instance. Even though the enabled flag is set to false there is a significant reduction in performance unless I also set the filter to be NONE.

I couldn't see anything obvious in Renderer.cpp, which appears to be checking the enabled flag before registering dof for post-processing.

**Comment by romainguy** [comment]
That seems quite strange since all we do is check the enabled flag. The presence of a new instance shouldn't matter (esp. at the native level since it's just a struct).

**Comment by rawnsley** [comment]
I forgot to mention that this was on Android. I will try and reproduce it with one of the sample projects, but it wants me to change to Java 11 and I don't want to mess with my build setup at the moment.

**Comment by pixelflinger** [comment]
What do you mean by "unless I also set the filter to be NONE."?

**Comment by rawnsley** [comment]
> What do you mean by "unless I also set the filter to be NONE."?

The `filter` property:

```
val dof = View.DepthOfFieldOptions()
dof.filter = View.DepthOfFieldOptions.Filter.NONE
dof.enabled = false
view.depthOfFieldOptions = dof

```

**Comment by pixelflinger** [comment]
Okay, that is super strange. I will have a look. Thanks for the report.

**Comment by pixelflinger** [comment]
I can't reproduce this problem at all -- I tried in Android.
A better repro case would be useful here.

**Comment by rawnsley** [comment]
I'm struggling to even get DoF to do anything in the Android samples. I've added the following to `setupView` in sample-texture-object:

```
val dof = View.DepthOfFieldOptions()
dof.enabled = true
dof.cocScale = 40f
view.depthOfFieldOptions = dof
camera.focusDistance = 0.1f
```

My expectation is that this should make everything very blurry. Have I missed a step?

**Comment by romainguy** [comment]
Try to change your camera aperture to ƒ/2.8 for instance.

**Comment by rawnsley** [comment]
> Try to change your camera aperture to ƒ/2.8 for instance.

I tried `camera.setExposure(2.8f, 1.0f / 125.0f, 100.0f)` and a few other combinations, but all it did was make it brighter.

**Comment by rawnsley** [comment]
I still can't make it blur more than a pixel with any combination of settings or positioning of the model and camera. Previously I could blur out the whole screen easily. I'm not actually using this feature anymore so feel free to close the issue if it's too obscure.

**Comment by pixelflinger** [comment]
The best way to play with this stuff is to use our remote ui for gltf-viewer, have you tried that?

I will double check that something didn't break on mobile, this has happened before.

**Comment by rawnsley** [comment]
I've just discovered that and you are right - it's working on the remote viewer. I'll chalk it up to "one of those things" and close the issue for now.
