### ISSUE TITLE
Light intensity comparison with other render engines

### ISSUE THREAD

**Issue by rawnsley** [google/filament#4625]
I'm aware this is a can of worms and I'm not expecting pixel-perfect matching, but I'm struggling with the most basic comparison. I expect I'm doing something wrong, but I can't see it.

Sadly there are no definitive examples, but the _KHR_lights_punctual_ extension PR has a simple one that appears good enough to start with: https://github.com/KhronosGroup/glTF/pull/1223#issuecomment-420127026

The initial renders don't seem to be correct, but eventually a consensus is reached from a mix of tools https://github.com/KhronosGroup/glTF/pull/1223#issuecomment-434350984. Here is the output in [glTF Viewer](https://gltf-viewer.donmccurdy.com/):

<img width="1001" alt="Screenshot 2021-09-15 at 14 59 20" src="https://user-images.githubusercontent.com/303516/133447605-c89b930c-b474-4403-aa78-4f4156f2e15b.png">

If I load the same file into Filament's gltf_viewer the plane is completely black (once sunlight is disabled).

<img width="916" alt="Screenshot 2021-09-15 at 14 59 44" src="https://user-images.githubusercontent.com/303516/133447725-d2091e31-b379-4ac0-88a9-2b74a086bf9e.png">

I have to boost the light _intensity_ by a factor of a thousand to get something similar to the other render engines.

<img width="981" alt="Screenshot 2021-09-15 at 15 03 18" src="https://user-images.githubusercontent.com/303516/133448097-e8521dea-9352-4d3b-a992-da5718634f4a.png">

If anything Filament is giving the more believable result. The "default" light in the scene has an intensity of 1 candela and I would not expect a single candle held half a metre above a plane to have much visible effect and certainly not reach the ground nearly four meters away.

**Comment by romainguy** [comment]
The problem is that glTF does not define the exposure of the camera. The other renderers use a very sensitive exposure by default equivalent to f/1 1s ISO 100 in Filament. We just had a call with Khronos about this and I'm going to write a proposal for an extension that adds exposure parameters to glTF cameras. To match other renderers you can use Camera::setExposure(1) in Filament.
