### ISSUE TITLE
Possible alpha blending issue 

### ISSUE THREAD

**Issue by nmfisher** [google/filament#4632]
**Describe the bug**

Possibly a blending issue, possibly a sub-optimal shader configuration.

**To Reproduce**
1. Download GLB model from https://drive.google.com/file/d/1NOxz4pbC75CsvaIHhQq6UQlyRbcE1Qpc/view?usp=sharing
2. Load model in gltf-viewer

**Expected behavior**
This hair on this model looks correct in Blender:

![blender2](https://user-images.githubusercontent.com/7238578/133793710-e89d7eca-6ced-4fdc-be4f-797007e5caf6.png)
![blender1](https://user-images.githubusercontent.com/7238578/133793715-207bf998-7af4-49c1-b47b-0383f1e2480a.png)

and also correct in sandbox.babylonjs.com:

![babylonjs](https://user-images.githubusercontent.com/7238578/133793733-bdd950f5-809d-47a0-b75c-98da5374fcc5.png)

however when rendering in Filament gltf-viewer (Ubershader), the transparency on the hair is not rendering correctly:

![Screenshot 2021-09-17 at 9 30 04 PM](https://user-images.githubusercontent.com/7238578/133793778-a8074298-2a0a-442d-af90-0cfae112d674.png)

The same issue is seen when running on iOS (Ubershader/OpenGL):

![IMG_4770B495F302-1](https://user-images.githubusercontent.com/7238578/133793803-2eae27fa-43de-4c77-a565-2e8e0441a4ad.jpg)

Interestingly, the issue looks very similar to BabylonJS when "Need depth pre-pass" is enabled:

![bbjs2](https://user-images.githubusercontent.com/7238578/133793813-712066a0-1daf-445c-984c-42b29b0f97bb.png)

**Screenshots**
As above

**Logs**
N/A

**Desktop (please complete the following information):**
 - OS: Tested on both macOS/Windows (Android emulator)
 - GPU: N/A
 - Backend: OpenGL

**Smartphone (please complete the following information):**
 - Device: iPhone 6/11
 - OS: iOS 13 & 14

**Additional context**

**Comment by pixelflinger** [comment]
This model seems to have a serious problem with its bounding boxes, and I've not been able to display it in our gltf-viewer.

**Comment by romainguy** [comment]
This would be solved by using alpha masking instead of alpha blending. To properly render most glTF files, Filament enables depth writes on transparent objects, which is the source of the issue you are seeing (and why you can replicate it in Babylon.js with the depth option). We could fix this particular model but it would break numerous other models we've seen. I would therefore recommend you use alpha masking (which should work well for hair anyway).

**Comment by romainguy** [comment]
Re-opening because I may have a fix.

**Comment by romainguy** [comment]
<img width="478" alt="Screen Shot 2021-09-17 at 12 20 47 PM" src="https://user-images.githubusercontent.com/869684/133842592-f9656b4b-0424-4faf-9a7b-320e4e95855d.png">

The fix I have should work well for other glTF assets as well and should match what three.js does.

**Comment by nmfisher** [comment]
Fantastic - looking forward to testing this out. Thanks!
