### ISSUE TITLE
GLB file rendering artifacts

### ISSUE THREAD

**Issue by amenon** [google/filament#4636]
**Describe the bug**

I've noticed that while animating my GLB models, the ring fingers on my model have an odd rendering artifact. I've tested the GLB file on multiple other viewers (Blender on the desktop, Babylon and 3JS on the web)  and don't see any issues on those viewers.

**To Reproduce**
1. Play any of the following GLB files using the `sample-gltf-viewer` on Android or the [filament web viewer](https://google.github.io/filament/viewer/)

    - [Ab Crunch](https://dev-img.physera.com/animation/bd9699feea75ce06.glb)
    - [Ankle Dorsiflexion](https://dev-img.physera.com/animation/b92f2c6ed74e81a6.glb)

**Expected behavior**
There shouldn't be any rendering artifact during the animation

**Screenshots**

1. AB Crunch

https://user-images.githubusercontent.com/1328587/133847034-46154300-8c1a-4dfc-a62a-32680c25a819.mp4

2. Ankle Dorsiflexion

https://user-images.githubusercontent.com/1328587/133847048-a7efc164-7b95-4369-a6de-02bf49d7593e.mp4

**Desktop:**
 - Browser: Chrome 93
 - OS: Mac OS Big Sur

**Smartphone:**
 - Device: Pixel 3, x86 Emulator
 - OS: Android 9/10/11/12

**Comment by romainguy** [comment]
Thanks for the files. Looks like the bug still happens with the recent skinning fix, must be a different issue :/

**Comment by romainguy** [comment]
Good news, this is fixed. The latest versions of Filament don't show the bugs.

**Comment by amenon** [comment]
I confirmed that the newest version resolved the issue in our project as well. Thank you and the team for the hard work in resolving this!
