### ISSUE TITLE
How to include a static lightmap in a material definition?

### ISSUE THREAD

**Issue by rawnsley** [google/filament#4648]
In three.js some materials have a [lightmap property](https://threejs.org/docs/#api/en/materials/MeshStandardMaterial.lightMap) that is used as a multiplier for indirect light sources.

I'm using some GLTF extensions to bring in HDR lightmap map textures (which all works well), but I'm struggling to work out how I should include them in my material definitions in Filament.

In unlit mode I can just multiply the materials `baseColor`, but in lit mode this doesn't affect the specular light components from the IBL as I would like it to.

**Comment by romainguy** [comment]
We don't support lightmaps currently because we haven't decided how we'd like our lightmaps to work (the solution you describe does not provide any directionality, we'd prefer to use something based on spherical harmonics or gaussians). Proper lightmaps would also require a baking tool.

**Comment by romainguy** [comment]
Please either move this to a discussion or change this to be a feature request.

**Comment by rawnsley** [comment]
[Done](https://github.com/google/filament/discussions/4650). Thanks for the super quick reply.
