### ISSUE TITLE
KHR_materials_volume: unticking "scale to unit box" in GLTF viewer breaks MosquitoInAmber

### ISSUE THREAD

**Issue by alexey-pelykh** [google/filament#4659]
It seems that https://github.com/google/filament/commit/4f287340429fc5691cee8f13d96a95c02e799696#diff-d996768901848d3b97fc3f0def4594d8ddfd639403d005e994135228a643aa59R129 using local scale does not work with MosquitoInAmber since the model itself contain scale above the mesh with volume material.

**Comment by romainguy** [comment]
What's broken exactly? The scene appears very small but that's all, and that doesn't seem related to the change you linked at all.

**Comment by alexey-pelykh** [comment]
https://youtu.be/NCXA12eoKWs

**Comment by romainguy** [comment]
The behavior you are seeing has nothing to do with the change you linked to (and specifically not the use of local scale which is what the glTF spec requires). `KHR_materials_volume` is implemented as a screenspace effect and it comes with all the issues and limitations of a screenspace implementation.

**Comment by alexey-pelykh** [comment]
Indeed, that's clear now. Thanks for the insights!

**Comment by romainguy** [comment]
There is however something strange about this object as its origin is not 0/0/0 without scaling to the unit box. I've seen many glTF files with similar issues (bad bounding boxes is also common).
