### ISSUE TITLE
Documentation on Specular Integration with Distant Lights

### ISSUE THREAD

**Issue by damontylor** [google/filament#4664]
In this section:
https://google.github.io/filament/Filament.md.html#lighting/imagebasedlights/distantlightprobes

Before equation (91), there's a vague sentence about what values of h and v should be inserted. In general, it's not clear how the integration is not dependent on v and can be done offline.

I would appreciate if someone can clarity that! The following paragraph also looks incomplete:

> When integrating, we can choose any 𝑣 v  we please as long as it satisfies n ⋅ v  (e.g.: when calculating v ⋅ h ).

**Comment by romainguy** [comment]
@pixelflinger can say more, but it's exactly what's explained in that sentence you quote. The DFG lut is indexed by dot(n,v) on one axis and roughness on the other axis. The view vector (v) you pick does not matter as long as it corresponds to the value of dot(n, v) you are currently computing. You can see how it is done here: https://github.com/google/filament/blob/main/libs/ibl/src/CubemapIBL.cpp#L748

This is also explained in the annex: https://google.github.io/filament/Filament.md.html#annex/precomputinglforimage-basedlighting

**Comment by damontylor** [comment]
Thanks, Romain for your swift reply and the code. I understand the code and it helps!
