### ISSUE TITLE
High frequency texture filckering and moire effect when moving camera

### ISSUE THREAD

**Issue by JackeryShh** [google/filament#4666]
**Describe the bug**
       High frequency texture filckering when moving camera
**To Reproduce**
1. moving camera 

**Expected behavior**
    No texture filckering and moire effect

**Screenshots**

https://user-images.githubusercontent.com/10266164/134484320-21a37ba9-1c5b-4e89-97b0-0a452017349f.mov

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Smartphone (please complete the following information):**
 - Device: [iPhone 12]
 - OS: [ios13]

**Additional context**

**Comment by JackeryShh** [comment]
When I checked the model in the blender, there was no obvious flickering and moiré phenomenon. I wonder if it is caused by the Filament not turning on mipmap.

**Comment by romainguy** [comment]
Did you generate mipmaps on those textures? There's an API for this. We don't have this issue when mipmaps are enabled.

**Comment by JackeryShh** [comment]
> Did you generate mipmaps on those textures? There's an API for this. We don't have this issue when mipmaps are enabled.

Thank you for your reply. I used to think it was a problem of not enable the  mipmap, but I didn't  find an API to enable mipmap. In texture.cpp, I saw some APIs for generating mipmaps, but they did not solve the current problem. Which API is used to enable mipmaps?

**Comment by romainguy** [comment]
Texture.generateMipMaps()

**Comment by JackeryShh** [comment]
thanks, I just debugged and looked at this interface. The mipmap interface is enabled by default?  My app calls canGenerateMipmaps() by default and it return true.  My 3D model format is the glb.

![image](https://user-images.githubusercontent.com/10266164/134610613-2eeb2e93-edc6-43b5-a409-e24f8f643863.png)

**Comment by romainguy** [comment]
Do you have dynamic resolution enabled?

**Comment by JackeryShh** [comment]
Yes, I tried to enable DynamicResolution a few days ago, but it doesn't seem to work

**Comment by romainguy** [comment]
My point was more about disabling it (and it won't do anything if you hit the performance target). Can you share the glb?

**Comment by JackeryShh** [comment]
ok, the zip file is the glb 
[model.zip](https://github.com/google/filament/files/7221987/model.zip)

**Comment by romainguy** [comment]
So unfortunately this particular texture doesn't play well with mipmapping. I tried other glTF viewers and they have the same issue. I would recommend tweaking the textures (including the normal maps). Another alternative is to enable TAA which solves the problem in our renderer.

**Comment by JackeryShh** [comment]
Yes, other gltfl viewers also have this problem, such as gltf-viewer, but in Blender it seems well . I also have tried to turn on TAA a month ago, and the effect has been improved, but it will produce the certain ghost effect(especially when the frame rate is low) .

**Comment by fanbinnet** [comment]
> Yes, other gltfl viewers also have this problem, such as gltf-viewer, but in Blender it seems well . I also have tried to turn on TAA a month ago, and the effect has been improved, but it will produce the certain ghost effect(especially when the frame rate is low) .

Can you start a issue for the ghost effect when TAA is enable ？

**Comment by romainguy** [comment]
This is a know limitation of our current TAA implementation (and something that's always somewhat present anyway, but we can limit it). Fixing it will come at a cost though.

**Comment by fanbinnet** [comment]
> Fixing it will come at a cost though.

Thanks for the quickly replay！

**Comment by JackeryShh** [comment]
> This is a know limitation of our current TAA implementation (and something that's always somewhat present anyway, but we can limit it). Fixing it will come at a cost though.

Do we plan to fix this problem about the ghost effect in the future？

**Comment by JackeryShh** [comment]
> > Yes, other gltfl viewers also have this problem, such as gltf-viewer, but in Blender it seems well . I also have tried to turn on TAA a month ago, and the effect has been improved, but it will produce the certain ghost effect(especially when the frame rate is low) .
> 
> Can you start a issue for the ghost effect when TAA is enable ？

This problem is very obvious in high-frequency textures, and there is no plan to  start a issue for the ghost effect. And I plan to adjust the texture and normals to avoid this problem.
