### ISSUE TITLE
Sharp specular reflections on a rough object when using IBL

### ISSUE THREAD

**Issue by rawnsley** [google/filament#4668]
This is a little subjective, but the reflected light from an IBL on a 100% rough PBR material feels off. It also differs significantly from an equivalent three.js render.

Here is the filament render on Android using the gltf-viewer sample and the [Venice HDR](https://github.com/mrdoob/three.js/blob/dev/examples/textures/equirectangular/venice_sunset_1k.hdr) IBL
![device-2021-09-23-135021](https://user-images.githubusercontent.com/303516/134511294-19ed8ff7-431e-4404-86b2-043be7af53de.png)
Here is the equivalent in [glTF Viewer](https://gltf-viewer.donmccurdy.com/) using three.js
<img width="1746" alt="Screenshot 2021-09-23 at 13 51 25" src="https://user-images.githubusercontent.com/303516/134511341-82a7718a-dfc5-4319-a959-0d835cae63f0.png">

[The sample model](https://github.com/google/filament/files/7217790/rough-duck.glb.zip) has 100% roughness and is non-metallic, but the filament render definitely looks shiny. Other objects with 50% roughness are almost as shiny as those with 0% and the effect is particularly pronounced on HDR images with small bright points of light.

My guess is that there's something wrong with the IBL cubemap, either the initial generation or the eventual roughness-based selection, none of which I understand very well. I was trying to investigate this assumption, but I got stuck working out how to write the various IBL cubemaps out as bitmaps so I could look at them.

**Comment by romainguy** [comment]
Our rendering is correct:
<img width="948" alt="Screen Shot 2021-09-23 at 8 34 42 AM" src="https://user-images.githubusercontent.com/869684/134538230-d750d939-0930-42ac-b2fe-e5ba04356d10.png">

You can see automated comparison between Filament and other glTF renderers. Aside from specific (known) differences with some extensions, they all compare roughly the same: https://modelviewer.dev/fidelity/

It seems like you are not generating/loading your IBL properly. The easiest way to properly load an IBL is to use `cmgen -f ktx -x path/to/output envmap.hdr` and then to use `KTXLoader.createIndirectLight()`. Example:

```
    private fun createIndirectLight() {
        val engine = modelViewer.engine
        val scene = modelViewer.scene
        val ibl = "default_env"
        readCompressedAsset("envs/$ibl/${ibl}_ibl.ktx").let {
            scene.indirectLight = KTXLoader.createIndirectLight(engine, it)
            scene.indirectLight!!.intensity = 30_000.0f
            viewerContent.indirectLight = modelViewer.scene.indirectLight
        }
        readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx").let {
            scene.skybox = KTXLoader.createSkybox(engine, it)
        }
    }
```

**Comment by rawnsley** [comment]
@romainguy That comparison site is super useful, but my screenshot is straight from the [sample-gltf-viewer](https://github.com/google/filament/tree/main/android/samples/sample-gltf-viewer) not my own code. It uses an IBLPrefilterContext to generate the IBL reflections object at runtime rather than cmgen.

**Comment by romainguy** [comment]
It looks fine there as well:
![Screenshot_1632412432](https://user-images.githubusercontent.com/869684/134541557-54bfd47c-dfd8-496c-8857-2960e46b8fa5.png)

**Comment by rawnsley** [comment]
Oh. Perhaps it is device specific? I'm using a Pocophone F1 and a Snapdragon XR1 based VR headset and I get the same issue on both I think. I'll do some more testing to try and narrow it down.

Is there any easy way to dump the cubemap textures that IBLPrefilterContext spits out? It might help debugging.

**Comment by romainguy** [comment]
You could try and dump the textures but they are in R11G11B10F format, so you won't be able to look at them easily. The best way to inspect them is to use a GL debugger like AGI or vendor tools like Adreno/Snapdragon Profiler.

**Comment by rawnsley** [comment]
Apologies for bringing this one back after so long. I can't find a single hardware device where this works like it does in the emulator. Is anyone able to confirm it working on a real device?

In case it isn't clear from the screenshots, the specular component is too sharp and the diffuse component has a much more defined highlight than the reference renders.

This is the reference model [roughness.glb.zip](https://github.com/google/filament/files/7670089/roughness.glb.zip). It's non-metallic spheres with roughness varying from 0% to 100%. The background IBL is [from three.js](https://github.com/mrdoob/three.js/blob/dev/examples/textures/equirectangular/venice_sunset_1k.hdr), but I see the same thing with other HDRIs, particularly when they have very bright elements like noonday sun.

## glTF Viewer (for reference)
<img width="1651" alt="glTFViewer-Web" src="https://user-images.githubusercontent.com/303516/145070861-7fd4b23f-ed0a-40d4-a09a-28fdd3fa21db.png">

## Emulator
![Emulator](https://user-images.githubusercontent.com/303516/145070887-cb540d50-11f7-423c-ab3d-8b805a1de66f.png)

## Qualcomm XR1 (Ardeno GPU)
![QualcommXR1-Ardeno](https://user-images.githubusercontent.com/303516/145070957-e15ab0a0-4597-4620-a7b9-31216f538ec7.png)

## Samsung S6 (Mali-T760MP8)
![SamsungS6-Exynos](https://user-images.githubusercontent.com/303516/145071041-6e034fdc-51a4-4b08-ab59-87cc5c047d82.png)

## Generic RK3399 Tablet (Mali-T860MP4)
![RK3399-Mali](https://user-images.githubusercontent.com/303516/145071070-55a41d6f-8819-4860-89d8-ea52cf02ba4f.png)

**Comment by romainguy** [comment]
Looks fine with the built-in IBL:

![device-2021-12-07-091126](https://user-images.githubusercontent.com/869684/145075091-fe6e91fe-6607-4d68-b1cf-2912968ec5bb.png)

The issue only shows up (Pixel 6) when prefiltering an IBL at runtime:

![device-2021-12-07-091350](https://user-images.githubusercontent.com/869684/145075217-96b03196-1035-48aa-9d26-9c6f09f34d95.png)

Looks like it's not a rendering bug but either a bug in libibl or how gltf_viewer uses it.

**Comment by romainguy** [comment]
Offline generation looks fine:

<img width="595" alt="Screen Shot 2021-12-07 at 9 37 53 AM" src="https://user-images.githubusercontent.com/869684/145078824-c5a95897-a45b-4e31-a893-786b3334f1cc.png">

**Comment by pixelflinger** [comment]
Thank you for reopening this, we caught a bunch of problems on mobile.
