### ISSUE TITLE
Material version mismatch. Expected 12 but received 0.

### ISSUE THREAD

**Issue by wingdi** [google/filament#4685]
platform : Android 
I add `implementation 'com.google.android.filament:filament-android:1.12.6'` in my testProject, 
and copy filament-main/android/samples/sample-hello-triangle  to my testProject, 
after running , it encounter this error：
```
E/Filament: Panic
    in filament::MaterialParser *filament::createParser(filament::backend::Backend, const void *, size_t):69
    reason: Material version mismatch. Expected 12 but received 0.
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 16297 (ai.filamenttest), pid 16297 (ai.filamenttest)
```
I also test 'com.google.android.filament:filament-android:1.12.5'`  it still have this problem ?
Anything wrong ?

after add
```
  implementation 'com.google.android.filament:gltfio-android:1.12.6'
    implementation 'com.google.android.filament:filament-utils-android:1.12.6'
    implementation 'com.google.android.filament:filamat-android:1.12.6'
```
still get this error,  and i checked Material.java , there are no method to set version.

**Comment by romainguy** [comment]
Did you use a previous version of Filament? If so, make sure your materials get compiled/recompiled. How do you compile your materials?

**Comment by wingdi** [comment]
@romainguy   The baked_color.mat is copied from filament-main/android/samples/sample-hello-triangle/src/main/materials/ , 

<img width="1200" alt="截屏2021-09-29 下午11 23 58" src="https://user-images.githubusercontent.com/25787391/135300377-58baa142-c1ec-4984-a39a-f0b460439c60.png"> 
in kotlin code, i just change the .filamat to .mat ,   is this problem ?

**Comment by romainguy** [comment]
Yes it is. `.mat` files are source files, you need to compile them to `.filamat` using the tool called `matc`.

**Comment by wingdi** [comment]
Thanks for your help .   @romainguy
