### ISSUE TITLE
Android  How to generate asserts/envs/flower_road_no_sun_2k/m0_nx.rgb32f ? 

### ISSUE THREAD

**Issue by wingdi** [google/filament#4686]
When I try android sample : textured-object,  it needs envs/flower_road_no_sun_2k/m0_nx.rgb32f , I didn't find documents to illustrate how to generate this file ,  how can i get it ？

```
private fun loadIndirectLight(assets: AssetManager, name: String, engine: Engine): Pair<IndirectLight, Texture> {
    val (w, h) = peekSize(assets, "$name/m0_nx.rgb32f")
}

```

**Comment by romainguy** [comment]
Please use the Discussions tab for questions. It's generated at build time by our Gradle plugin which itself invokes cmgen: cmgen -x out_dir/ envmap.hdr

**Comment by wingdi** [comment]
Ok, thanks,  I noticed Discussions tab, I will use it later.
