### ISSUE TITLE
Shadow casting - how to get on Android

### ISSUE THREAD

**Issue by obeletski** [google/filament#469]
We working on simple chessboard view on Android and we would like to get some shadows casting from pieces. We have a directional light with shadow casting enabled in our scene but we see not shadows.

Please advise what we would do to get shadows working.

**Comment by romainguy** [comment]
You need to mark your chess pieces as shadow casters. This can be achieved via the RenderableManager API. You must also set the light as a shadow caster in the light builder. All renderables are shadow receivers by default.

**Comment by grassel** [comment]
Thank you romainguy for your help. obeletski and I forgot the setting via RenderableManager::Builder to enable shadow casting. This fixed our problem.

**Comment by obeletski** [comment]
@grassel, good to know that things are working now. Closing the issue.

**Comment by seasiainfotech** [comment]
> Thank you romainguy for your help. obeletski and I forgot the setting via RenderableManager::Builder to enable shadow casting. This fixed our problem.

what are you do for this, please help it
