### ISSUE TITLE
Black Screen on Running Android Samples in Emulator

### ISSUE THREAD

**Issue by GokulDas027** [google/filament#4692]
**Describe the bug**
Black Screen on running android samples (except sample-gltf-viewer) on Emulator, showing only the App Bar. sample-gltf-viewer runs on emulator. However the debug apk build on same machine, runs on real android device (tested on One Plus Nord, Android 11 based Oxygen OS)

**To Reproduce**
1. On Linux, Build filament release and android release from source
2. Build Sample Projects using Android Studio
3. Run on emulator (Pixel 4 API 30 with Google Play)

**Expected behavior**
Was expecting it to be like in the android samples screenshots, with virtual camera scene in emulator for sample-hello-camera.
Particularly interested in sample-hello-camera since I'm learning to user filament with ArCore

**Screenshots**
sample-hello-camera
<img src="https://user-images.githubusercontent.com/22936485/135619322-18d9f1f0-6243-4a0a-91b3-b1640cb9db4b.png" alt="Hello Camera" width="300"/>

sample-hello-triangle
<img src="https://user-images.githubusercontent.com/22936485/135619412-da9f716e-4643-411e-bfdc-3ad213435842.png" alt="Hello Triangle" width="300"/>

sample-image-based-lighting
<img src="https://user-images.githubusercontent.com/22936485/135619600-7897c51e-3e59-4f4f-bb9d-ce734049f9dc.png" alt="Image Based Lighting" width="300"/>

sample-gltf-viewer works
<img src="https://user-images.githubusercontent.com/22936485/135619806-c8ff4185-f454-4016-a05e-a941d61fc199.png" alt="glTF Viewer" width="300"/>

**Logs**
E/Filament: Compilation error in fragment shader "colorGradingAsSubpass":
    "ERROR: 0:79: 'inout' : invalid qualifier: can be only used with function parameters
    ERROR: 0:79: 'location' : invalid layout qualifier: only valid on program inputs and outputs
    "
    1:   #version 300 es
    2:   #extension GL_EXT_shader_framebuffer_fetch : require
    3:   precision mediump float;
    4:   precision mediump int;
    5:   layout(std140) uniform FrameUniforms
    6:   {
    7:   highp mat4 a;
    8:   highp mat4 b;
    9:   highp mat4 c;
    10:   highp mat4 d;
    11:   highp mat4 e;
    12:   highp mat4 f;
    13:   highp mat4 g[4];
    14:   highp vec4 h;
    15:   highp vec4 i;
    16:   highp vec3 j;
E/Filament: 17:   highp float k;
    18:   vec4 l;
    19:   vec4 m;
    20:   vec3 n;
    21:   uint o;
    22:   vec3 p;
    23:   uint q;
    24:   vec3 r;
    25:   float s;
    26:   vec4 t;
    27:   uvec2 u;
    28:   vec2 v;
    29:   float w;
    30:   float x;
    31:   highp float y;
    32:   float z;
    33:   vec3 az[9];
    34:   vec4 bz;
    35:   float cz;
    36:   float dz;
    37:   float ez;
    38:   uint fz;
    39:   vec3 gz;
    40:   float hz;
    41:   float iz;
    42:   float jz;
    43:   float kz;
    44:   float lz;
    45:   vec3 mz;
    46:   float nz;
    47:   float oz;
    48:   float pz;
    49:   float qz;
    50:   uint rz;
    51:   float sz;
    52:   float tz;
    53:   float uz;
    54:   float vz;
    55:   vec2 wz;
    56:   vec2 xz;
    57:   float yz;
    58:   float zz;
    59:   float azz;
    60:   float bzz;
    61:   float czz;
    62:   float dzz;
    63:   float ezz;
    64:   float fzz;
    65:   vec4 gzz[58];
    66:   } frameUniforms;
    67:   layout(std140) uniform MaterialParams
    68:   {
    69:   vec2 a;
    70:   int b;
    71:   int c;
    72:   highp float d;
    73:   vec4 e;
    74:   vec4 f;
    75:   } materialParams;
    76:   mediump vec4 materialParams_colorBuffer;
    77:   uniform mediump sampler3D materialParams_lut;
    78:   in highp vec2 vertex_uv;
    79:   layout(location = 0) inout vec4 output_dummy;
    80:   layout(location = 1) out vec4 output_tonemappedOutput;
    81:   in highp vec4 variable_vertex;
    82:   vec4 _588;
    83:   void main()
    84:   {
    85:   materialParams_colorBuffer = output_dummy;
    86:   vec4 _397 = vec4(materialParams_colorBuffer.xyz, 1.0);
    87:   vec4 _589;
    88:   if (materialParams.e.x < 65504.0)
    89:   {
    90:   highp vec2 _460 = abs((vertex_uv * frameUniforms.i.zw) - vec2(0.5)) * materialParams.e.x;
    91:   vec2 _583 = _460;
    92:   _583.x = _460.x * materialParams.e.z;
    93:   vec2 _472 = pow(clamp(_583, vec2(0.0), vec2(1.0)), vec2(materialParams.e.y));
    94:   vec3 _485 = _397.xyz * mix(materialParams.f.xyz, vec3(1.0), vec3(pow(clamp(1.0 - dot(_472, _472), 0.0, 1.0), materialParams.e.w * 5.0)));
    95:   _589 = vec4(_485.x, _485.y, _485.z, _397.w);
E/Filament: 96:   }
    97:   else
    98:   {
    99:   _589 = _397;
    100:   }
    101:   vec4 _506 = textureLod(materialParams_lut, vec3(materialParams.a.x) + (((log2((_589.xyz * 5.555555820465087890625) + vec3(0.04799599945545196533203125)) * 0.07349978387355804443359375) + vec3(0.3860360085964202880859375)) * materialParams.a.y), 0.0);
    102:   highp vec4 _422 = vec4(_506.x, _506.y, _506.z, _589.w);
    103:   vec4 _590;
    104:   if (materialParams.c > 0)
    105:   {
    106:   vec4 _585 = _422;
    107:   _585.w = dot(_506.xyz, vec3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875));
    108:   _590 = _585;
    109:   }
    110:   else
    111:   {
    112:   _590 = _422;
    113:   }
    114:   vec4 _591;
    115:   if (materialParams.b > 0)
    116:   {
    117:   highp vec2 _544 = fract(((gl_FragCoord.xy * frameUniforms.i.zw) + vec2(0.070000000298023223876953125 * materialParams.d)) * vec2(5.398700237274169921875, 5.442100048065185546875));
    118:   highp vec2 _552 = _544 + vec2(dot(_544.yx, _544 + vec2(21.5351009368896484375, 14.3136997222900390625)));
    119:   highp float _557 = _552.x * _552.y;
    120:   vec4 _537 = _590 + vec4(((fract(_557 * 95.43070220947265625) + fract(_557 * 75.0496063232421875)) - 1.0) * 0.0039215688593685626983642578125);
    121:   _591 = vec4(_537.x, _537.y, _537.z, _590.w);
    122:   }
    123:   else
    124:   {
    125:   _591 = _590;
    126:   }
    127:   output_dummy = clamp(_588, vec4(-65504.0), vec4(65504.0));
    128:   output_tonemappedOutput = clamp(_591, vec4(-65504.0), vec4(65504.0));
    129:   }

**Desktop (please complete the following information):**
 - OS: Pop OS 21.04
 - GPU: NVIDIA GTX 1650
 - Backend: [OpenGL/Vulkan]  (not sure, using default on debian based os)

**Smartphone (please complete the following information):**
 - Device: Emulator Pixel 4 API 30 with Google Play Services
 -   
Name: Pixel_4_API_30
CPU/ABI: Google Play Intel Atom (x86)
Path: .android/avd/Pixel_4_API_30.avd
Target: google_apis_playstore [Google Play] (API level 30)
Skin: pixel_4
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_4
hw.lcd.width: 1080
hw.initialOrientation: Portrait
**image.androidVersion.api: 30**
tag.id: google_apis_playstore
hw.mainKeys: no
**hw.camera.front: emulated**
avd.ini.displayname: Pixel 4 API 30
**hw.gpu.mode: auto**
**hw.ramSize: 1536**
**PlayStore.enabled: true**
fastboot.forceColdBoot: no
**hw.cpu.ncore: 4**
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 2280
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images/android-30/google_apis_playstore/x86/
showDeviceFrame: yes
**hw.camera.back: virtualscene**
**AvdId: Pixel_4_API_30**
hw.lcd.density: 440
hw.arc: false
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google Play
runtime.network.latency: none
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
 - OS:  Android 11, API 30 with Google Play

**Additional context**
First time I build on a previous version of filament and there was this same issue, later pulled the latest version as of today and build from scratch. build only for filament release and android-release

**Comment by romainguy** [comment]
@pixelflinger The issue seems to be the `inout output_dummy`. According to the spec (section 4.3.6):

```
There is not an inout storage qualifier for declaring a single variable name as both input and
output to a shader. Also, a variable cannot be declared with both the in and the out qualifiers, this
will result in a compile-time or link-time error. Output variables must be declared with different
names than input variables
```

**Comment by pixelflinger** [comment]
Yes `inout` is from the framebuffer_fetch extension, in theory we're checking for it though.

**Comment by romainguy** [comment]
Ah right, makes sense. It could be an emulator specific issue then.

**Comment by pixelflinger** [comment]
I'm not able to reproduce this. All samples work well in the emulator.
It could be specific to the linux emulator, maybe.

**Comment by GokulDas027** [comment]
> I'm not able to reproduce this. All samples work well in the emulator. It could be specific to the linux emulator, maybe.

Ohh, then let me try if I could make it work by changing any emulator settings.
It's running Emulator version 30.8.4

**Comment by GokulDas027** [comment]
Output on running 

Transparent Rendering
![Screenshot_1633150041](https://user-images.githubusercontent.com/22936485/135703920-26b9fbf4-ec1d-411a-9403-29366884d684.png)
![Screenshot_1633149846](https://user-images.githubusercontent.com/22936485/135703937-f761bf74-7868-4ea7-ae75-98bb7892401f.png)

But freezes and inconsistent on each run, with black screen on all other runs.
Logs the same error and

```D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 ```

**Comment by pixelflinger** [comment]
I think you could file a bug against the emulator for now.

**Comment by GokulDas027** [comment]
Okay will do that.

Apps build with Sceneform, using Filament 1.7.0 runs fine, what could be the reason for the current issue.

**Comment by GokulDas027** [comment]
The problem seems to be with the Intel Integrated Graphics, previously even though I tried running emulator with gpu host, It wasn't actually running on my device's Nvidia GPU. And when It is explictly specified to run emulator on Nvidia GPU (Proprietary Driver) It's rendering perfectly.

on Pop OS (not using optimus)
> `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia $ANDROID_HOME/emulator/emulator -avd Pixel_4_API_30 -gpu host`

**Comment by kelvinwatson** [comment]
@GokulDas027  Did you ever end up filing a bug against the emulator? This is occurring for me as well.

**Comment by GokulDas027** [comment]
Yes, I did [report the issue](https://issuetracker.google.com/issues/203446380?pli=1)  but nothing happened besides assigning it to someone.

**Comment by cobratracysaur** [comment]
@GokulDas027 Hi, have you got this issue solved on your emulator? The black screen issue is occurring for me as well on emulator.
