### ISSUE TITLE
How to fix building errors such as MSB8066 and others?

### ISSUE THREAD

**Issue by SC5Shout** [google/filament#4695]
Hi. I use visual studio 2019 and I've got a whole lot of errors when I build the project.

![image](https://user-images.githubusercontent.com/43299401/135764544-71fe0711-486a-4c82-bec0-4a6370588157.png)

what I did was
`
> git clone --recursive https://github.com/google/filament.git
> cd filament
> mkdir out
> cd out
> make ..
`
how can I fix these errors?

**Comment by romainguy** [comment]
Make sure you follow the instructions at https://github.com/google/filament/blob/main/BUILDING.md

**Comment by SC5Shout** [comment]
I did. I've got the latest windows 10 sdk, python and cmake. Every step I did was exactly from the instruction you've linked.

**Comment by SC5Shout** [comment]
> Make sure you follow the instructions at https://github.com/google/filament/blob/main/BUILDING.md

I did. I've got the latest windows 10 sdk, python and cmake. Every step I did was exactly from the instruction you linked and still got them errors.
