### ISSUE TITLE
gltf_viewer automation saves all black images with Linux Vulkan backend

### ISSUE THREAD

**Issue by auzyze** [google/filament#4727]
**Describe the bug**
1. After "./build.sh release", I run "./gltf_viewer --batch default --api vulkan", the helmet is showing, but the saved .ppm images are all black. If I changed --api to opengl, then everything is OK.
2. Not sure if it is related, when I run "./frame_generator" with vulkan backend, the saved images are also all black.

**To Reproduce**
1. sync to the tag v1.12.8;
2. easy build the source code on Linux(ubuntu 18.04)
3. go to "out/cmake_release/samples", run "./gltf_viewer --batch default --api vulkan"
4. check the saved .ppm images

**Expected behavior**
I expected the rendered helmets are in the saved .ppm images.

**Screenshots**
<img width="905" alt="Screen Shot 2021-10-12 at 9 34 41 PM" src="https://user-images.githubusercontent.com/3727314/137067831-345095c2-48c0-4506-8325-f74b43ecc15f.png">

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU: NVIDIA GTX 1080
 - Backend: Vulkan

**Additional context**
About my installation of Vulkan:
I've tried apt install libvulkan1 and libvulkan-dev, and I got the above problem;

I've also tried to install the complete Vulkan SDK, and got the same problem.
(I followed this link to install the SDK: https://vulkan.lunarg.com/doc/view/1.1.130.0/windows/getting_started.html)
It seems the Vulkan SDK has bee installed properly, as I can run "vkvia" without any issue.

**Comment by romainguy** [comment]
Looks like a readPixels issue with Vulkan.

**Comment by auzyze** [comment]
Hurray! I just made it work, gltf_viewer automation in vulkan/headless mode produces beautiful helmet images on a remote server. 

It turns out the be an issue with my local environment, I just changed to a new machine which has different video card and driver, and the issue is gone.

Btw, I've also tried SwiftShader, which works like a charm in both headless and normal modes.

Thank you guys!
