### ISSUE TITLE
Low gltf animation playback frame rate for iphone se 2

### ISSUE THREAD

**Issue by Ankbzpx** [google/filament#4737]
**Describe the bug**

The gltf animation playback appears scattered even though the rendering seems smooth

**To Reproduce**

Reproducible with [hello-gltf example](https://github.com/google/filament/tree/main/ios/samples/hello-gltf) on iphone se 2, filament v1.12.8

**Expected behavior**

The animation should  play smoothly

**Screenshots**

https://user-images.githubusercontent.com/21233675/137484898-4d290200-72d3-4cd4-aa74-48cb5c7b06d1.mp4

**Smartphone**
 - Device: iphone se 2
 - OS: IOS version: 14.6

**Comment by bejado** [comment]
You can also see if https://github.com/google/filament/pull/4753/commits/6b6c32c22836d92517534150c569e718a3771a32 fixes it.

**Comment by Ankbzpx** [comment]
Both restart and [caching `_startTime`](https://github.com/google/filament/commit/6b6c32c22836d92517534150c569e718a3771a32) fixed the issue. Thank you!
