### ISSUE TITLE
SDL2 Wayland support

### ISSUE THREAD

**Issue by jwinarske** [google/filament#4756]
**Describe the bug**
Wayland is not supported via SDL2.  Fedora and Ubuntu ship default with Wayland.  Only X11 is supported based on third_party/libsdl2/include/SDL_config_linux.h. 

More current version of SDL2 than in Filament auto generates config header based on CMake detection.

To support Wayland today requires patching third_party/libsdl2/include/SDL_config_linux.h, and when doing that libsdl2 CMake doesn't generate protocol code.

Also when cross compiling wayland-scanner in libsdl2 is incorrectly detected.  https://github.com/libsdl-org/SDL/issues/4860

**To Reproduce**

```
CC=clang CXX=clang++ cmake .. -D BUILD_SHARED_LIBS=OFF -D CMAKE_BUILD_TYPE=Release -D FILAMENT_SUPPORTS_VULKAN=TRUE -D FILAMENT_SUPPORTS_OPENGL=FALSE -D FILAMENT_USE_SWIFTSHADER=FALSE -D FILAMENT_SUPPORTS_XCB=FALSE -D FILAMENT_SUPPORTS_XLIB=FALSE -D FILAMENT_ENABLE_LTO=TRUE
```

**Expected behavior**
Vulkan on Wayland is supported

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 / Fedora 34
 - Backend: Vulkan

**Comment by romainguy** [comment]
We'd be happy to take a look at a PR if you're up for it, yes. Thanks for offering.

**Comment by pixelflinger** [comment]
What is the status of this one?

**Comment by jwinarske** [comment]
Done!
