### ISSUE TITLE
Validation error about vulkan image layout

### ISSUE THREAD

**Issue by wumo** [google/filament#4768]
**Describe the bug**
Running sample gltf_viewer got vulkan validation error on version 1.12.9

**To Reproduce**
1. Compile and run gltf_viewer.

**Expected behavior**
Got validation error:

```shell
VULKAN ERROR: (UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout) Validation Error: [ UNASSIGNED-CoreValidation-Dra
wState-InvalidImageLayout ] Object 0: handle = 0x1b4d3eebb88, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae
5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x1b4d3eebb88[] expects VkImage 0x
54fef00000000a6[] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_O
NLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA RTX 3080
 - Backend: Vulkan (Using Vulkan SDK 1.2.189.2 for validation layer)
 - filament: 1.12.9

Additional Context:

This validation error won't happen before this [merge](https://github.com/google/filament/pull/4678).

**Comment by prideout** [comment]
I reproduced this today with MoltenVK + debug build of `gltf_viewer`.
