### ISSUE TITLE
Skybox without IndirectLight is not black

### ISSUE THREAD

**Issue by prideout** [google/filament#477]
To repro, remove the call to `setIndirectLight` in FilamentApp and enlarge the camera aperture (small value).

The skybox is visible, but is very very dark.

**Comment by romainguy** [comment]
To recap the issue: when setting a skybox without setting an indirect light, the app cannot control the intensity of the skybox.

**Comment by pixelflinger** [comment]
In that case the intensity is set to DEFAULT_INTENSITY which is 30000 lux.
