### ISSUE TITLE
Support KTX2 texture

### ISSUE THREAD

**Issue by 0k1019** [google/filament#4771]
**Is your feature request related to a problem? Please describe.**

Filament can't render GLB/GLTB file containing KTX2 texture.
The explanation of [KTX2](https://www.khronos.org/ktx/) is in Khronos group website.
[Examples GLB files](https://github.com/KhronosGroup/3D-Formats-Guidelines/tree/main/samples/StainedGlassLamp) containing KTX2.

**Describe the solution you'd like**
I wish filament supports to render KTX2 texture. KTX2 is really nice for rendering quality and compression 3D file.

**Describe alternatives you've considered**
[cgltf.h](https://github.com/google/filament/blob/1182d30fb909fee4af1d9ebab14c15dd434f3655/third_party/cgltf/cgltf.h#L3964): This line means GLB with ktx2 texture convert to `basisu_image` not `image`.

[AssetLoader.cpp](https://github.com/google/filament/blob/1182d30fb909fee4af1d9ebab14c15dd434f3655/libs/gltfio/src/AssetLoader.cpp#L1210): This line means `basisu_image` can't load to render. 

Accept `basisu_image` in AssetLoader.

Testing in [filament viewer](https://google.github.io/filament/viewer/) between [GLB(with png)](https://raw.githubusercontent.com/KhronosGroup/3D-Formats-Guidelines/main/samples/StainedGlassLamp/StainedGlassLamp-JPG-PNG-Volume.glb) and [GLB(with KTX2)](https://raw.githubusercontent.com/KhronosGroup/3D-Formats-Guidelines/main/samples/StainedGlassLamp/StainedGlassLamp-KTX-BasisU-Volume.glb)
![image](https://user-images.githubusercontent.com/11485593/138989119-c90a8c31-e8e0-4f86-90c7-9e0467fdf399.png)

**OS and backend**
macOS Big Sur 11.6
Chrome 95.0.4638.54 (x86_64) 

Thank you for @codpot's help.

**Comment by August1996** [comment]
May I ask which version of the features of ktx2 is planned to support?😊

**Comment by prideout** [comment]
We intend to fully support `KHR_texture_basisu` and use that as the driving force for our ktx2 support.  The only reason we would drop features would be to reduce binary size.

**Comment by August1996** [comment]
> We intend to fully support `KHR_texture_basisu` and use that as the driving force for our ktx2 support. The only reason we would drop features would be to reduce binary size.

very good feature👍. have you started developing this feature?

**Comment by starccode** [comment]
> We intend to fully support `KHR_texture_basisu` and use that as the driving force for our ktx2 support. The only reason we would drop features would be to reduce binary size.

Looking forward to the support of ktx2. Recently, we are also try to using ktx2 texture in our project through filament.

**Comment by zhazhaxia** [comment]
Looking forward to the support of ktx2. +1s

**Comment by prideout** [comment]
This was fixed a few weeks ago, forgot to close the ticket.

**Comment by 0k1019** [comment]
Thank you for support KTX2

But I found that it is not working in filament 1.22.0


Not working in `gltf_viewer`
<img width="910" alt="image" src="https://user-images.githubusercontent.com/11485593/168553623-d012a4a6-a49c-49de-adbd-a60dc8f3188a.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/11485593/168553658-35847fdb-4f8b-427e-a370-f030536d9596.png">

Not working in [filament web viewer ](https://google.github.io/filament/viewer/)

<img width="1392" alt="스크린샷 2022-05-16 오후 5 02 41" src="https://user-images.githubusercontent.com/11485593/168546789-046751bd-0fb4-4a66-8752-3a2ca164f67b.png">

macOS Monterey 12.3.1(21E258)
Chrome 101.0.4951.64 (x86_64)

**Comment by prideout** [comment]
Correct, it is supported on main only.  The final commit for this feature landed on May 2 with https://github.com/google/filament/commit/f035655f5b2a2d288d5df73709642dd219450e23, so it should arrive with v1.22.1

**Comment by 0k1019** [comment]
Thank you for supporting this feature.
It works in filament viewer.
<img width="1136" alt="스크린샷 2022-05-18 오후 2 49 05" src="https://user-images.githubusercontent.com/11485593/168966478-c4c33caf-1194-49d7-887c-59cd261ab6b8.png">
[Web viewer](https://google.github.io/filament/viewer/) is not working because it is v1.22.0 filament.js. I think it working soon.
