### ISSUE TITLE
Build x86 filament on windows 10 use vs2019,generated a lot of error in bluegl.prox

### ISSUE THREAD

**Issue by MaybeWong** [google/filament#4780]
Hello,I have to  use filament on windows x86.
But I bulid it  generated error like that.
E:\WY\filament\filament-main\libs\bluegl\src\BlueGLCoreWindowsImpl.S(22): error A2013: .MODEL must precede this directive
1>E:\WY\filament\filament-main\libs\bluegl\src\BlueGLCoreWindowsImpl.S(25): error A2034: must be in segment block : bluegl_glProgramUniform1dvEXT
1>E:\WY\filament\filament-main\libs\bluegl\src\BlueGLCoreWindowsImpl.S(26): error A2034: must be in segment block
1>E:\WY\filament\filament-main\libs\bluegl\src\BlueGLCoreWindowsImpl.S(27): error A2034: must be in segment block
1>E:\WY\filament\filament-main\libs\bluegl\src\BlueGLCoreWindowsImpl.S(28): fatal error A1010: unmatched block nesting : bluegl_glProgramUniform1dvEXT
Is there any suggestions？I look forward to receiving your reply，thank u！

**Comment by MaybeWong** [comment]
@romainguy Any version is not supported anymore, including the previous version？

**Comment by romainguy** [comment]
No we've never supported x86 on Windows, only on Android (and even there we plan on getting rid of it as soon as possible).
