### ISSUE TITLE
App crashed calling filament.utils.Utils.init() under release version

### ISSUE THREAD

**Issue by nevermore1993** [google/filament#4793]
**Describe the bug**
app crashed when I trying to initialize Filament module under release version. But it works fine under debug version

**To Reproduce**
1. open a new fragment
2. call Utils.init()
3. crashed

**Screenshots**
see attached pic

**Logs**
Fatal Exception: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~uY90yHWTlDBpzeu-hY_mXw==/com.tlive.madcat-vZys9zo13-FTtDLFjmy9Ng==/lib/arm64/libfilament-utils-jni.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at com.google.android.filament.utils.Utils.init(Utils.java:28)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy note 9
 - OS: Android 10

**Additional context**
filament version: 1.12.9
![filament_bug](https://user-images.githubusercontent.com/34294200/139673038-c3d6fd97-6cdb-46ad-aa8b-b8867a2b3f73.png)

**Comment by romainguy** [comment]
Please provide the actual logs, not a screenshot. I cannot reproduce the issue with Filament 1.12.8 and 1.12.9. If this happens in a release build make sure to check your Proguard rules to ensure you are not removing anything that Filament needs.

**Comment by nevermore1993** [comment]
> Please provide the actual logs, not a screenshot. I cannot reproduce the issue with Filament 1.12.8 and 1.12.9. If this happens in a release build make sure to check your Proguard rules to ensure you are not removing anything that Filament needs.

Thanks for your quick reply. I modified Proguard rules, and the problem got solved. Thank you.

**Comment by orhangulcan** [comment]
@nevermore1993 hey, need help with the same thing for me, can you share your proguard rules?
