### ISSUE TITLE
Simple construction of 3D model

### ISSUE THREAD

**Issue by wuao** [google/filament#4812]
I have many groups of coordinates
I hope not to calculate triangles to form a three-dimensional model, unlike the cube example, because it is irregular. I can't calculate how many triangles I need. Now I build a two-dimensional line segment
 get file.zip in OutLine list 
[all_floor_list.json.zip](https://github.com/google/filament/files/7472902/all_floor_list.json.zip)

I hope Android  API is simple enough to facilitate production
https://threejs.org/docs/index.html?q=ex#api/zh/geometries/ExtrudeGeometry

**Comment by romainguy** [comment]
This doesn't seem like a bug? Is this a feature request? If so, it is not Filament's role to create geometry.

**Comment by wuao** [comment]
yes。but. Can you recommend one
