### ISSUE TITLE
How to set the position of the Entity? Create an example for it?

### ISSUE THREAD

**Issue by zcufo123** [google/filament#4821]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I really want to set the position of the Entity that I have loaded

**Describe alternatives you've considered**
I can load the Entity with customized position.

**OS and backend**
Nothing with OS or backend

I believe there should be some examples about how we can change the node, but to be honest, I can't find it in the sample apps, could we add some examples related to it?

**Comment by romainguy** [comment]
Most of the samples show how to do this, using `TransformManager`. For instance in `sample-page-curl`:

```
        final float[] transformMatrix = new float[16];
        final double degrees = -Math.toDegrees(mPageAnimationRadians);
        Matrix.setRotateM(transformMatrix, 0, (float) degrees, 0.0f, 1.0f, 0.0f);
        Matrix.translateM(transformMatrix, 0, 0.0f, -0.5f, 0.0f);
        TransformManager tcm = mEngine.getTransformManager();
        tcm.setTransform(tcm.getInstance(mPage.renderable), transformMatrix);
```

Or in the native sample `shadowtest`:

```
    auto& tcm = engine->getTransformManager();
    tcm.setTransform(tcm.getInstance(renderable), mat4f::translation(float3{ 0, -1, -4 }));
```

**Comment by zcufo123** [comment]
I mean on the Android Samples, anyway, the C++ code also helps, thanks, @romainguy
