### ISSUE TITLE
Help: mesh rendered only black

### ISSUE THREAD

**Issue by QUAN-Zhao** [google/filament#4825]
I feel that the sample codes are too complicated for me, especially "FilamentApp". I write some simple codes that want to render the mesh of monkey.bin in the sample, but the rendered object is totally black...
Here is my codes for material:

    filamat::MaterialBuilder builderAiDefaultMat;
    builderAiDefaultMat.name("aiDefaultMat")
        .material("void material(inout MaterialInputs material) {"
                  "  prepareMaterial(material);"
                  "  material.baseColor.rgb = materialParams.baseColor;"
                  "  material.metallic = materialParams.metallic;"
                  "  material.roughness = materialParams.roughness;"
                  "  material.reflectance = materialParams.reflectance;"
                  "}")
        .parameter(filamat::MaterialBuilder::UniformType::FLOAT3, "baseColor")
        .parameter(filamat::MaterialBuilder::UniformType::FLOAT, "metallic")
        .parameter(filamat::MaterialBuilder::UniformType::FLOAT, "roughness")
        .parameter(filamat::MaterialBuilder::UniformType::FLOAT, "reflectance")
        .shading(filamat::MaterialBuilder::Shading::LIT)
        // .blending(filamat::MaterialBuilder::BlendingMode::OPAQUE)
        .targetApi(filamat::MaterialBuilder::TargetApi::VULKAN)
        .platform(filamat::MaterialBuilder::Platform::DESKTOP);
    pkg = builderAiDefaultMat.build(mEngine->getJobSystem());
    mDefaultMaterial = filament::Material::Builder().package(pkg.getData(), pkg.getSize()).build(*mEngine);
    mDefaultMI = mDefaultMaterial->createInstance();
    mDefaultMI->setParameter("baseColor", filament::RgbType::sRGB, filament::sRGBColor{1.0f, 0.0f, 0.0f});
    mDefaultMI->setParameter("roughness", 0.4f);
    mDefaultMI->setParameter("metallic", 1.0f);
    mDefaultMI->setParameter("reflectance", 0.5f);

 I load the mesh of monkey.bin:

    filamesh::MeshReader::MaterialRegistry matRegistry = filamesh::MeshReader::MaterialRegistry();
    matRegistry.registerMaterialInstance(utils::CString("DefaultMaterial"), mDefaultMI);
    filamesh::MeshReader::Mesh mesh = filamesh::MeshReader::loadMeshFromFile(mEngine, 
        utils::Path("/home/quanzhao/git-space/filament/out/cmake-release/samples/generated/resources/monkey.bin"), 
        matRegistry);
    mScene->addEntity(mesh.renderable);

I added the light:

    filament::LightManager::Builder::Result lightResult;
    utils::Entity lightEntity = em.create();
    lightResult = filament::LightManager::Builder(filament::LightManager::Type::SUN)
        .color(filament::Color::toLinear<filament::ColorConversion::ACCURATE>(filament::sRGBColor(0.98f, 0.92f, 0.89f)))
        .intensity(110000)
        .direction({ 0.7, -1, -0.8 })
        .sunAngularRadius(1.9f)
        .castShadows(true)
        .build(*mEngine, lightEntity);
    if (lightResult == filament::LightManager::Builder::Result::Error) {
        utils::slog.d << "sun light build fail" << utils::io::endl;
    }
    mScene->addEntity(lightEntity);
    utils::Entity lightEntity2 = em.create();
    lightResult = filament::LightManager::Builder(filament::LightManager::Type::SUN)
        .color(filament::Color::toLinear<filament::ColorConversion::ACCURATE>(filament::sRGBColor(0.98f, 0.92f, 0.89f)))
        .intensity(110000)
        .direction({ 0.7, -1, 0.8 })
        .sunAngularRadius(1.9f)
        .castShadows(true)
        .build(*mEngine, lightEntity2);
    if (lightResult == filament::LightManager::Builder::Result::Error) {
        utils::slog.d << "sun light build fail" << utils::io::endl;
    }
    mScene->addEntity(lightEntity2);
    filament::Skybox* skybox = filament::Skybox::Builder().color({0.1, 0.125, 0.25, 1.0}).build(*mEngine);
    mScene->setSkybox(skybox);

I also have set the camera, but the view only shows a black mesh. Could anyone help me? Is the definition of material correct ? Or if there are some problems with the light? Thanks.

PS:
I delete related codes of IBL in FilamentApp. Because I think it's too complicated for my simple example, I want to reserve the smallest codes which can render a mesh. The view can rotate/scale correct, and also the black mesh in the view... The only problem is: the mesh is black.

**Logs**
SDL_Init success
FEngine (64 bits) created at 0x6e2a400 (threading is enabled)
FEngine resolved backend: Vulkan
Vulkan device driver: NVIDIA 455.23.04
Selected physical device 'GeForce RTX 3090' from 1 physical devices. (vendor 0x10de, device 0x2204, driver 0x71c5c100, api 1.2)
vkCreateSwapchain: 1024x640, 44, 0, 3, 1

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - GPU: GeForce RTX 3090/PCIe/SSE2
 - Backend: Vulkan

**Comment by romainguy** [comment]
Please use the Discussions tab for questions like this. I highly recommend starting with an IBL because it will light your object from all direction. Alternatively make the object not metallic (0.0f) and fully rough (1.0f) so the single directional light is more visible. Also make sure your camera exposure is correct and that the camera is pointing at your object.
