### ISSUE TITLE
It is crash that post-processing set the false in iOS

### ISSUE THREAD

**Issue by Theo-Y** [google/filament#4838]
**Describe the bug**
When I turned off post-processing, crash is happened on the iOS(Xcode)
it is like https://github.com/google/filament/issues/1215

Is this problem unresolved?

**To Reproduce**
1. `view->setPostProcessingEnabled(false);`

**Expected behavior**
I want to turn off post-processing. because post-processing change the color differently.
So, When I use the RenderTarget, the color of last view is completely different.

**Screenshots**

**Logs**
validateDepthStencilState:4140: failed assertion `MTLDepthStencilDescriptor sets depth test but MTLRenderPassDescriptor has a nil depthAttachment texture'

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone SE2
 - OS: iOS14

**Additional context**

**Comment by bejado** [comment]
Hey @Theo-Y which version of Filament are you using and are you running a particular iOS sample? I'm unable to reproduce with our gltf-viewer sample on the tip of main.

**Comment by Theo-Y** [comment]
Thanks to reply @bejado, I use the 1.12.10 version. When I render the view into render target, the crash happen. The render target has only color attachment.

**Comment by bejado** [comment]
No, we should support that case. I'll take a closer look. As a workaround you should be able to add a depth attachment to avoid the crash.
