### ISSUE TITLE
Filament Web in mobile

### ISSUE THREAD

**Issue by ManluZhang** [google/filament#4840]
Hi there, I'm working with the Filament JS API. It seems that the demo doesn't work on mobile (iOS / Android). I've tried Safari and Chrome, but only got blank page. 
Does the JS API works on mobile?
BTW, the demo I used is https://google.github.io/filament/webgl/helmet.html

**Comment by romainguy** [comment]
The JS API works on mobile if your browser supports WebGL 2.0. I just tried it and it works fine both on iOS and Android.
