### ISSUE TITLE
Any way to combine OpenGL calls with filament rendering?

### ISSUE THREAD

**Issue by MarkMurillo** [google/filament#4841]
Hi, I'm wondering if there's any way to use Open GL calls to leverage Stencil buffers with the Filament rendering workflow. I imagine something like:
- Begin frame (Filament)
- Enable stencil buffer
- Render models with open GL
- Render other models with Filament render() call
- End frame (Filament)

Would this general idea work or are stencil buffers just not supported at the moment?

**Comment by romainguy** [comment]
Filament does not allow the user to run their own OpenGL commands (esp. since we may be using Vulkan or Metal). You can however render Filament into a texture and use that in your own OpenGL context.
