### ISSUE TITLE
[Android JNI] Render::readPixels get nothing in the buffer

### ISSUE THREAD

**Issue by dandingol03** [google/filament#4845]
**Describe the bug**
Get empty pixel buffer in android c++. The `recordView` i has setup some renderable and light. The `recordSwapChain` is created by `engine->createSwapChain(params->width, params->height, 2)`. This is the `jni` code below :
```
if (renderer->beginFrame(params->recordSwapChain, frameTimeNanos)) {
    renderer->render(params->recordView);
        int size = params->width * params->height * 4;
        auto* captureBuffer = malloc(size);
        memset(captureBuffer, 0, size);
      
        auto callback = [](void* buffer, size_t size, void*) {
            uint8_t const* rgba = (uint8_t const*)buffer;
            onCaptureResult(rgba, size);
        };
      
        auto descriptor = PixelBufferDescriptor(captureBuffer, size, PixelDataFormat::RGBA, PixelDataType::UBYTE, 1, 0, 0, 0, callback,
                                                nullptr);
        renderer->readPixels(0, 0, params->width, params->height, std::move(descriptor));
    renderer->endFrame();
}
```

**Expected behavior**
read the pixel data succesfully

**Screenshots**
![image](https://user-images.githubusercontent.com/13013579/141675740-b12925e8-9a39-41f8-ba2e-7b42e06887f9.png)

**Additional context**
The engine is initialized in jni,  and  this is all.

**Device**
The problem can be reproduced everytime , so it is not relevant about device

**Comment by romainguy** [comment]
`BitmapFactory.decodeByteArray` won’t work, Filament returns a raw array of bytes, the result is not encoded. You should use `Bitmap.copyFrom` instead (or better, use our Java APIs that simplify handling this).

**Comment by dandingol03** [comment]
> `BitmapFactory.decodeByteArray` won’t work, Filament returns a raw array of bytes, the result is not encoded. You should use `Bitmap.copyFrom` instead (or better, use our Java APIs that simplify handling this).

ok, i will try, thanks
