### ISSUE TITLE
Point light invisible in both Linux and Android.

### ISSUE THREAD

**Issue by flykule** [google/filament#4878]
**Describe the bug**
I test point light with below gltf:
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/schema/examples/lights.gltf
Command to test with gltf_viewer:
```
~/C++Projects/filament/out/release/filament/bin/gltf_viewer -a opengl ./lights.gltf
```
The point light is invisible and has no effect on the box.
Also I have change code in android/sample-gltf-viewer to load this file with same result.

**To Reproduce**
1. Download test file: https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/schema/examples/lights.gltf
2. Use gltf-viewer to show it: ~/C++Projects/filament/out/release/filament/bin/gltf_viewer -a opengl ./lights.gltf

**Expected behavior**
It should show same result with other 3d-viewer, like here:[gltf-viewer](https://gltf-viewer.donmccurdy.com/)
![image](https://user-images.githubusercontent.com/7899000/142794857-9c2ad4ec-3cab-4a07-a857-b3d617cc71c6.png)

**Screenshots**
Current result
![image](https://user-images.githubusercontent.com/7899000/142794873-ff13de22-10cf-4dec-bcdc-da30d60c115f.png)

**Logs**
FEngine (64 bits) created at 0x7efd60204010 (threading is enabled)
FEngine resolved backend: OpenGL
The specified IBL path does not exist: /home/castle/C++Projects/filament/out/release/filament/bin/assets/ibl/lightroom_14b

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.0.4
 - GPU: Mesa Driver/Nvidia GTX 970M
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: OPPO RENO
 - OS: Android Pie 11.0

**Additional context**
I have also tried build a point light myself and add it to the scene, if I turn IBL and other light down, the screen become black:
```
        LightManager.Builder(LightManager.Type.POINT)
                .fallof(40f)
                .color(1f, 0f, 0f)
                // Intensity of the sun in lux on a clear day
                .intensity(110_000.0f)
                // The direction is normalized on our behalf
                .direction(0.0f, -0.5f, -1.0f)
                .position(0f, 1f, 0f)
                .castShadows(true)
                .build(engine, light)

        // Add the entity to the scene to light it
        scene.addEntity(light)
```

**Comment by flykule** [comment]
I have checked other light issues like mine, but therir solution seems not working. Any help will be appreciated!

**Comment by romainguy** [comment]
Point lights work just fine but because a glTF file cannot specify the camera exposure, Filament's default exposure is not sensitive enough. Here's that same glTF with a different camera exposure:
<img width="1136" alt="Screen Shot 2021-11-21 at 7 28 19 PM" src="https://user-images.githubusercontent.com/869684/142796723-3cf624b0-6318-43e2-988b-4d2d92b8e552.png">

To recreate the exposure of other viewers use aperture 1.0, shutter speed 1.2, and ISO 100.

**Comment by flykule** [comment]
Can you confirm this with the latest version? I have change camera exposure like yours, but with same result except everything become extremly bright:
![image](https://user-images.githubusercontent.com/7899000/142797905-7329a220-c028-4082-be48-f726d10ab156.png)

**Comment by romainguy** [comment]
You've left the sun turned on :)

**Comment by flykule** [comment]
I see, my mistake. Would you kindly tell me where is the ibl file: lightroom_14b?

**Comment by romainguy** [comment]
It should be built as part of the build. Try a clean build on a recent version of filament. It's not very important though, it's just a default ibl we load when none is specified.

**Comment by flykule** [comment]
Ok, thank you very much.

**Comment by flykule** [comment]
I'm sorry that my gltf-viewer still does not look like yours after I disable sunlight.Please look at the below image:
![image](https://user-images.githubusercontent.com/7899000/142803124-85900e78-1dab-432e-a981-2c2f2cedbd82.png)
Any idea what's going wrong?

**Comment by flykule** [comment]
I have diable sunlight, and modify camera exposure like your suggestion, here is the result:
![image](https://user-images.githubusercontent.com/7899000/142807748-06a1577d-83d9-40dc-bb99-e90db10a3740.png)
Here comes two new questions:
1. why it is so dark?( The ibl intensity is 100)
2. It's still looks very different from your picture, wht's going wrong?

**Comment by romainguy** [comment]
Your ISO is 25, mine was 100 or more.

**Comment by flykule** [comment]
I think i have found some interesting stuff. I want use stable version so I check out tag v1.14.0 and build gltf-viewer, here is the result:
![image](https://user-images.githubusercontent.com/7899000/142826523-65f804e7-2858-4240-8d18-d592c9bebcd0.png)

If i switch to main brach, the red point light comes back.!Apparently something has related to this issue in recent commits.
Btw, the latest commit update android build tool version broken all the android samples. I have to manually add "android:export=true" to all the activity tag in these sample's androidmanifest. If i run sample-gltf-viewer, it will crash and log error " animator created failed before resoure load" which located in ModelViewer.kt and nothing has changed.

**Comment by flykule** [comment]
Another interesting thing is if i chang backend api to vulkan, ISO need to be 25 to reach same effect which is 100 under opengl, I wonder why?

**Comment by flykule** [comment]
Update: with commit df06e8dc411ef88589a4cddba0a2079004b285e2 I successfully see point light both in desktop and mobile device. Thank you for your patience and helpful suggestion!
