### ISSUE TITLE
Crash in destroy engine right after creation

### ISSUE THREAD

**Issue by UnickSoft** [google/filament#4881]
**Describe the bug**
I faced with crash on Android with own built filament libs. I destroy engine after creation.

Engine* engine = Engine::create(Engine::Backend::OPENGL, nullptr, nullptr);
Engine::destroy(&engine);

I used C++ directly.

**To Reproduce**
1. Build filament 1.14.0 using this command ./build.sh -v -p android debug
2. Link it to your app.
3. Create create and destroy from C++;
Engine* engine = Engine::create(Engine::Backend::OPENGL, nullptr, nullptr);
Engine::destroy(&engine);

**Expected behavior**
No crash

**Logs**
Crash happened after line mCommandBufferQueue.requestExit(); in my thread. But crash happened in other thread. I attached crash stack [crash_stack.txt](https://github.com/google/filament/files/7582797/crash_stack.txt). It happened in line glGenVertexArrays(1, &rp->gl.vao); of createRenderPrimitiveR function.

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - 
**Additional context**
Maybe I should rebuild with other parameters or I should provide additional compilation parameter in my cmake file. I also want to use filament in C++.

**Comment by romainguy** [comment]
Does it happen only when you call `destroy` immediately after `create`?

**Comment by UnickSoft** [comment]
I checked it. Also it crashes if I try render one empty frame in the same place in code.
Maybe there is problem in my build parameters. But I cannot, how I can check it.

**Comment by UnickSoft** [comment]
Looks like I forgot to link libfilament-jni.so to my app. After that crashes gone away.
