### ISSUE TITLE
Optional System SDL2

### ISSUE THREAD

**Issue by jwinarske** [google/filament#4882]
I have proposal to add option to use the system SDL2 vs libsdl2 (third_party source).

The proposed change is would be very similar to this commit:
https://github.com/jwinarske/filament-samples/commit/56848ee128481e8d419130210fcfb8cbf8b52bbf

It would add a variable something like FILAMENT_SKIP_INTERNAL_SDL2.  If not set it would attempt to find the system SDL2 using find_package(SDL2 REQUIRED).

- If Skip flag is set, it uses find_package(SDL2 REQUIRED), and sets global include path accordingly
- The target name for libsdl2 "sdl2" becomes "SDL2".  This allows it to be resolved from sysroot.
- SDL2 can be installed into system as an archive and/or shared module.
- Allows easier integration
- Easier to rev SDL2 version

**Comment by romainguy** [comment]
We don't want to use the system SDL2. It's hard enough to deal with all the cross-platform bus we have to deal with, we'd rather avoid introducing dependencies we don't control.

**Comment by romainguy** [comment]
Note that SDL2 is only used by our internal tests, samples, etc. It's not required fo Filament, and we therefore shouldn't build an infrastructure around it (not mentioning the fact that we'd like to replace it with glfw or other anyway).

**Comment by jwinarske** [comment]
The key issue with glfw is that it limits the use cases.  It's focus is desktop, and a total pain to deal with in embedded Linux.

Given the recent SDL2 release it's much further along than glfw for Wayland support.

Have you considered pulling out the samples and associated deps into their own repo?

**Comment by romainguy** [comment]
> The key issue with glfw is that it limits the use cases. It's focus is desktop, and a total pain to deal with in embedded Linux.

But it doesn't really matter since it's just for samples and tools. Filament itself does not rely on SDL2 (and shouldn't). We would like to get rid of SDL2 because it does much more than we need.

**Comment by jwinarske** [comment]
The first step for a potential adopter is to make it run on their target.  If that involves a high buy in, there will be less adopters.

We (Toyota) are interested in investing further time and effort in Filament to help make it more accessible for others and ourselves.

**Comment by romainguy** [comment]
That sounds great but:
- We don't want to lock our users in (i.e. we don't want to impose SDL2 or any other equivalent library)
- Filament itself was always designed to be purely a rendering engine

Given these constraints, we could do what we did for glTF support: create a separate library. Filament itself knows nothing about file formats, etc. but gltfio does and is built on top of Filament. The same could be done to support SDL2, gltfw, or whatever else. They should be extra, optional libraries, built on top of Filament and not part of it. Does that make sense?

**Comment by jwinarske** [comment]
Yes an abstraction layer would be an improvement.

**Comment by romainguy** [comment]
Well it's not really an abstraction layer, just keeping different responsibilities separated. The question is what such a library's responsibilities would be? The minimal interface needed is connecting a backing surface/window/whatever to a SwapChain. I don't think providing support for the render loop, etc. should be part of such a library but should be left as part of the app.

**Comment by jwinarske** [comment]
For Linux there are four possible backends:
- KMS/DRM (no compositor - preferred for simple embedded use cases)
- Wayland (compositor - preferred for handling multiple hardware layers and hardware alpha blending)
- X11
- XCB

Then popular higher level application frameworks that implement the above directly:
GTK+
QT

For the interface I would say something agnostic that can handle all scnearios.  I would take a composite of SDL2, GLFW, GTK+, and QT and implement an API that could be mapped/used to/by any.  Implementation could use whatever framework API calls, or implement native compositor interface, such as for the agl-compositor (Wayland based), or other Wayland based compositor (Kiosk, etc).  Automotive Grade Linux (AGL).

I've done something similar creating a native Wayland backend for imgui using the GLFW implementation as starting point.  It's a bit tedious and requires some decent test cases to ensure it's all good.

**Comment by romainguy** [comment]
Doesn't this mean there would be a single library serving as an entry point that would call into 1 of N libraries that contain the actual implementations? I imagine you don't want to run/load code for any of the backends that don't exist on the host machine.

Linux graphics is such a mess :/

**Comment by jwinarske** [comment]
The common pattern I see is having all "supported" platforms in the same source tree enabled/disabled via build flags.  This enables an optimized build for a given environment.  In embedded Linux you would only build one configuration.

Having a single library could certainly work.

**Comment by jwinarske** [comment]
@romainguy Are you available for a short call to discuss potential alignment of work?

**Comment by romainguy** [comment]
Next week yes, you can reach out to me at my github user name @google.com

**Comment by jwinarske** [comment]
cool thanks
