### ISSUE TITLE
loading shperical harmonics from *_ibl.ktx fails on systems locals using `,` instead of `.` for decimal separator 

### ISSUE THREAD

**Issue by hernot** [google/filament#4883]
**Describe the bug**

When building my own 3d viewer in open3d which uses filament for rendering i observed that setting indirect lighting  by loading *_ibl.ktx file faild with inability to load spherical harmonics from *_ibl.ktx file. The file contains proper 3 x 9 table for spherical harmonics.

After investigation i figured that the reason for this locals sensitivity is the `std::strtof` function used on line `ilament/libs/image/src/KtxBundle.cpp:298` of current master branch to parse the spherical harmonics list. See also [std::strtof reference](https://en.cppreference.com/w/cpp/string/byte/strtof).

**To Reproduce**
1. set system locals to for example `de_DE` or `de_UTF8`
2. run your program which uses indirect lighting only
3. surfaces will be black only

4. Open editor (eg vi/vim)
5. replace all `.` in spherical harmonics list (key `sh`) with `,`
6. rerun demo
7. Surface colors will be back

**Expected behavior**

That `KtxBundle::getSphericalHarmonics` returns valid spherical harmonics list independent of which locals are set on the system filament or filament based library is used. 

**Screenshots**
`std::strtof` failing on eg.: German locale 
![std_strtof_failing_on_locale](https://user-images.githubusercontent.com/11776325/143007663-8913393b-4751-46e7-8d12-226a4c3fe947.png)
with `,` as decimal separator eg: in German locale
![with_as_decimal_separator](https://user-images.githubusercontent.com/11776325/143007675-3161f147-739b-4b60-8adc-aa61149edc56.png)

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mint 20 i386 
 - GPU: [e.g. NVIDIA GTX 1080] irrelevant
 - Backend: [OpenGL/Vulkan] guess opengl through intel/open3d python wheel

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2] 
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
Thank you! I didn't realize strtof was locale aware :/
