### ISSUE TITLE
Weird distortion when rendering model with skinned animation

### ISSUE THREAD

**Issue by Ankbzpx** [google/filament#4887]
**Describe the bug**
I have a model with skeletal animation that renders weirdly distorted in filament.

**To Reproduce**
- Unzip [Suzanne_glb.zip](https://github.com/google/filament/files/7595692/Suzanne_glb.zip) 
- Render Suzanne in gltf_viewer sample (v1.14.1)

**Expected behavior**
Suzanne should not be distorted.

**Screenshots**
### [Babylon sandbox](https://sandbox.babylonjs.com)
![babylon](https://user-images.githubusercontent.com/21233675/143241490-eb8bafaf-1a83-4d52-b913-ec41c88627cc.gif)

### [glTF sample viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/)
![gltf_sample_viewer](https://user-images.githubusercontent.com/21233675/143241541-b33f9b43-7439-4c1b-9475-229943c5ce64.gif)

### [ModelViewer](https://modelviewer.dev/editor/)
![modelviewer](https://user-images.githubusercontent.com/21233675/143241569-70290f38-dab7-4f36-bb29-323a7bfe3cf2.gif)

### Filament (v1.14.1)
![filament](https://user-images.githubusercontent.com/21233675/143241595-a5b866e2-401b-4d3b-ba03-2bc4c2339119.gif)

**Comment by Ankbzpx** [comment]
I believe the issue is, in [glTF specification](https://www.khronos.org/files/gltf20-reference-guide.pdf) (the same as in [Filament](https://github.com/google/filament/blob/main/libs/gltfio/src/Animator.cpp#L315)), `jointMatrix` is calculated as `jointMatrix = inverse(globalTransform) * globalJointTransform * inverseBindMatrix`, which involves transformation of coordinate systems ( `skin/mesh` -> `jointLocal`  -> `jointGlobal/world` -> `skin/mesh`). Therefore, decompose it into [scale, rotation, translation](https://github.com/google/filament/blob/main/filament/src/SkinningBuffer.cpp#L140) and apply it with [TRS](https://github.com/google/filament/blob/main/shaders/src/getters.vs#L36) order (s then r then t) could be wrong, as it applies scale along the axis of `skin/mesh` coordinate system, which is not necessarily the case.

A 2D example: 

![image](https://user-images.githubusercontent.com/21233675/143540368-17eb5b61-85bc-4a66-97b3-3bc2f5328055.png)

**Comment by Ankbzpx** [comment]
We managed to fix the distortion by directly passing upperLeft JointMatrix to `boneVertex`, as well as its transpose inverse to `boneNormal`, but at the cost of 32 more bytes per bone (50% increase, so the `CONFIG_MAX_BONE_COUNT` is reduced to 170)

| Babylon     | Before | After |
|-----------|----------|-------------|
| ![babylon](https://user-images.githubusercontent.com/21233675/144051405-7cf392ec-68de-4a0b-aa56-3ffc4c6f4862.gif)   | ![torus](https://user-images.githubusercontent.com/21233675/144051424-583f5488-723c-4eeb-b9cd-032fd50bb442.gif)   |  ![torus_fix](https://user-images.githubusercontent.com/21233675/144054663-c8a6deca-3034-4136-85ec-03ff9730a6f9.gif)  |

Patch: [distortion_fix_diff.zip](https://github.com/google/filament/files/7625926/distortion_fix_diff.zip)
Test model: [torus_glb.zip](https://github.com/google/filament/files/7625903/torus_glb.zip)

@romainguy

**Comment by pixelflinger** [comment]
Thank you for the investigation. Not sure how we can fix this without reducing the max bone count, I need to think more about it.
