### ISSUE TITLE
Podspec on MacOS platform? Some binary libraries are missing from the release version, fg filamentapp, imageio ...

### ISSUE THREAD

**Issue by ccworld1000** [google/filament#4896]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Podspec on MacOS platform,  Some binary libraries are missing from the release version, fg filamentapp, imageio ...

**Describe the solution you'd like**
Support Podspec for MacOS,  Some binary libraries are missing from the release version, fg filamentapp, imageio ...

**Describe alternatives you've considered**
Support Podspec for MacOS,  Some binary libraries are missing from the release version, fg filamentapp, imageio ...

**OS and backend**
Is this feature OS/backend specific? If so, explain why.
MacOS, Mainly take advantage of pod,  Some binary libraries are missing from the release version, fg filamentapp, imageio ...

**Comment by bejado** [comment]
There are no plans to support CocoaPods for macOS. Instead you can access the binaries from our [releases](https://github.com/google/filament/releases/tag/v1.14.1).

**Comment by ccworld1000** [comment]
Some binary libraries are missing from the release version, fg filamentapp, imageio

**Comment by romainguy** [comment]
These are not supposed to be part of the release. They're only used by our tools/tests/samples.

**Comment by ccworld1000** [comment]
Also, the new MacOS arm seems to lack binary support?

**Comment by romainguy** [comment]
We build for M1 Macs as well

**Comment by ccworld1000** [comment]
It seems only x86_ 64 binary?

CC # ls filament/lib/x86_64/
MoltenVK_icd.json		libgltfio.a
libMoltenVK.dylib		libgltfio_core.a
libbackend.a			libgltfio_resources.a
libbluegl.a			libgltfio_resources_lite.a
libbluevk.a			libibl-lite.a
libcamutils.a			libibl.a
libcivetweb.a			libimage.a
libdracodec.a			libmatdbg.a
libfilabridge.a			libmeshoptimizer.a
libfilaflat.a			libshaders.a
libfilamat.a			libsmol-v.a
libfilamat_lite.a		libutils.a
libfilament-iblprefilter.a	libviewer.a
libfilament.a			libvkshaders.a
libfilameshio.a			libvulkan.1.dylib
libgeometry.a
CC #
