### ISSUE TITLE
Triangle Tutorial is not working after changing to Filament v1.14.x

### ISSUE THREAD

**Issue by cx20** [google/filament#4899]
**Describe the bug**
[Triangle Tutorial](https://google.github.io/filament/webgl/tutorial_triangle.html) is not working after `v1.14.0` is released.
This is probably due to the [material breakage](https://github.com/google/filament/releases/tag/v1.14.0) in Filament, as described in the release notes. I think it needs to be rebuilt.

**To Reproduce**
1. Go to Filament's Triangle Tutorial page
https://google.github.io/filament/webgl/tutorial_triangle.html

The following error is displayed on the console.
```javascript
filament.js:9 
in filament::MaterialParser *filament::createParser(filament::backend::Backend, const void *, size_t):69

filament.js:9 
reason: Material version mismatch. Expected 14 but received 12.
```

**Expected behavior**
It is expected that the triangle will be displayed without any error.

**Screenshots**
The canvas is black and nothing is displayed

**Desktop (please complete the following information):**
 - OS: Windows 10 + Chrome 96.0.4664.45
 - GPU: NVIDIA GTX RTX 2060
 - Backend: WebGL(ANGLE)

**Additional context**
Probably the same cause as the following problem.
#4027

**Comment by romainguy** [comment]
Thanks! I fixed the demos.
