### ISSUE TITLE
use of GL_ARM_shader_framebuffer_fetch or GL_EXT_shader_framebuffer_fetch

### ISSUE THREAD

**Issue by coldgemini** [google/filament#4901]
**Describe the bug**
unable to use any of these two extensions in matc

**To Reproduce**
![image](https://user-images.githubusercontent.com/33364009/143865490-356e4dbf-a443-4fd6-be44-c7e3f466bdd9.png)
![image](https://user-images.githubusercontent.com/33364009/143865608-c2945055-806b-41d7-b031-1b5df8b68f18.png)
![image](https://user-images.githubusercontent.com/33364009/143865938-18587e1c-5116-4e4c-b875-7fff6eb5d237.png)

**Comment by romainguy** [comment]
This extension needs to be supported by glslang and spirv-tools.

**Comment by coldgemini** [comment]
so is there a way to use this extension in matc?

**Comment by romainguy** [comment]
You'd have to add or request support for it in glslang.

**Comment by coldgemini** [comment]
I only need this extension for opengl, not vulkan. I can compile shader with this extension using pure glsl however..

**Comment by romainguy** [comment]
We use glslang to parse the shaders, even if you don't target Vulkan.

**Comment by coldgemini** [comment]
thanks for reply.
so basically no way to get around even this opengl mobile matc compilation right?

![image](https://user-images.githubusercontent.com/33364009/143977369-a5ec4fd4-c973-44c5-979f-f38dd8acf74f.png)

**Comment by romainguy** [comment]
Since you are modifying matc you could inject the extension after parsing :)

**Comment by coldgemini** [comment]
could you give a specific place for this injection? 
:<

**Comment by coldgemini** [comment]
when compiling postprocessing mat files, I could see this extension enabled. how come the builtin variable gl_LastFragData still cannot be identified?

![image](https://user-images.githubusercontent.com/33364009/143980496-688e5399-f0af-42ed-ba90-f06ac6df03ad.png)
![image](https://user-images.githubusercontent.com/33364009/143980570-b1eef4e3-893a-41f5-a425-0b1738598a60.png)
![image](https://user-images.githubusercontent.com/33364009/143980605-3fe86b6a-b309-4a0b-aa67-81a71c41f142.png)

**Comment by coldgemini** [comment]
also, if this extension is not supported by glslang, how come it is used by postprocessing shaders?

![image](https://user-images.githubusercontent.com/33364009/144018331-d073b91c-e874-4b72-b2eb-ee4833051bab.png)

**Comment by romainguy** [comment]
GL_EXT_shader_framebuffer_fetch is supported

**Comment by coldgemini** [comment]
thanks, then is there a way to use pure glsl in material?
