### ISSUE TITLE
spotlight culling issue with projection (custom) with finite far plane

### ISSUE THREAD

**Issue by teub** [google/filament#4916]
**Describe the bug**
When the camera is far away, the spot light shading is missing on certain regions of the screen.

**To Reproduce**
I used material_sandbox to reproduce the issue; I added monkey2.obj to better show the problem (with a big plane under it), plus a .diff files of how I tweaked the cameras / spot lights.
The attached screenshots show where the problem starts to appear (one with the directional light enabled, the other with it turned off; in both case we can see that the spotlight isn't shading the whole plane).

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Files**

monkey2.obj : [monkey2.obj.zip](https://github.com/google/filament/files/7636630/monkey2.obj.zip)

material_sandbox diff : [spotlight_culling_bug.diff.zip](https://github.com/google/filament/files/7636631/spotlight_culling_bug.diff.zip)

![spotlight_culling_bug_spot](https://user-images.githubusercontent.com/11277063/144300301-dc7f0831-2bdd-46cc-a883-b62502221de7.png)

![spotlight_culling_bug_spot_with_dir](https://user-images.githubusercontent.com/11277063/144300294-2b2e4f70-25c3-4774-a2af-f3eab2607b10.png)
.

**Comment by romainguy** [comment]
Looks like another issue with the froxels.

**Comment by pixelflinger** [comment]
You need to use `View::setDynamicLightingOptions` to set the far plane for lighting for you scene. The default is 100m, after this distance from the camera, lights are not expected to shine.

We could improve things a bit by fading the lights instead of just dropping cells.

**Comment by teub** [comment]
> You need to use View::setDynamicLightingOptions to set the far plane for lighting for you scene

Thanks, tweaking the value will help me hide the problem.

> The default is 100m, after this distance from the camera, lights are not expected to shine.

I think there's still an issue. 
I tried setting the dynamiclightingoptions zfar to 200m in my app and I could still see squares, and I was pretty sure they weren't further than 200m. Just to make sure I also set up my camera proj matrix zfar to 200 and sure enough, I can still see squares.

**Comment by teub** [comment]
Just for the record, here's a test in my app with setDynamicLightingOptions(1.0f, 100.0f)

Camera ZFar is 100, obviously the artefacts are much closer than 100m.
I'm still not sure how to repro the issue in the material_sandbox, I'm actually trying to debug the other issue here (the shadow not touching the ground)

![image](https://user-images.githubusercontent.com/11277063/144678247-c117acb8-26f6-4b84-bd80-9a78937e5e35.png)

**Comment by teub** [comment]
From what I can tell after trying things, it looks like the problem comes from me using Camera::setCustomProjection instead of using Camera::setProjection.

I'm not sure there's something wrong with my custom projection matrix, and FCamera::setProjection seems to be doing something with mProjectionForCulling that setCustomProjection isn't doing.

**Comment by pixelflinger** [comment]
@teub Are you including the model matrix in your custom projection?  You'll run into issue if you do that. You need to use `setModelMatrix` separately.

What was the issue with the shadow not touching the ground?

**Comment by teub** [comment]
> Are you including the model matrix in your custom projection?

No, it's a projection matrix I built myself. I did use setModelMatrix for the model matrix. As I mentioned earlier, FCamera::setProjection seems to be doing something with mProjectionForCulling that setCustomProjection isn't doing.

For the ground problem it was because a very large object seems to be causing a precision issue (you can see for example in the background of this image : https://user-images.githubusercontent.com/11277063/144678247-c117acb8-26f6-4b84-bd80-9a78937e5e35.png, a 200mx200m ground with a checkerboard behind)

**Comment by pixelflinger** [comment]
There are two versions of `setCustomProjection` one of them is accepting a `projectionForCulling` matrix. 

We need both because we want to allow the "drawing" projection to have an infinite far, which is not reasonable for culling.

So maybe that's your problem? Does your projection have a finite far? Other than that the regular `setProjection` doesn't to anything special.

**Comment by teub** [comment]
Yes my proj matrix had a zfar; to workaround the issue, I extracted the fov/znear/zfar params of my proj matrix and called setProjection instead with the same parameters.

I'm not sure if this is a bug or not, I got misled into thinking I could just provide my proj matrix to setCustomProjection and didn't see there was an override.

**Comment by pixelflinger** [comment]
This should have worked then. It's possible we have a bug somewhere that *assumes* an infinite far. I will have a look.

**Comment by pixelflinger** [comment]
This was fixed/worked around in #4928
