### ISSUE TITLE
Website Example rendering "Glitchy"

### ISSUE THREAD

**Issue by Shigetorum635** [google/filament#4922]
**Describe the bug**
Rendering engine on example page broken.

**To Reproduce**
1. Go to Example website
2. Encounter bug.

**Expected behavior**
To render the monkey model flawlessly.
**Screenshots**
![image](https://user-images.githubusercontent.com/48862659/144514248-16fd3c23-39d1-4e1f-abe7-832377bbbc19.png)
![image](https://user-images.githubusercontent.com/48862659/144514282-dcbc674f-7fc4-4921-b668-2286355f6027.png)

https://user-images.githubusercontent.com/48862659/144514287-891841e3-7f2e-498a-852f-ad560ce1e3a8.mp4

**Logs**
None, as seen in the screenshot, asides the normal information log, there is nothing.

**Desktop (please complete the following information):**
 - OS: Windows 10 Ameliorated *Should not interfer at all with rendering*
 - GPU: GTX 1650 GDDR5
 - Backend: WebGL

**Additional context**
Not much asides I just happened to be browsing the examples.

**Comment by romainguy** [comment]
Thanks, which version of Chrome do you use?

**Comment by Shigetorum635** [comment]
> Thanks, which version of Chrome do you use?

<html>
<body>


Google Chrome | 96.0.4664.45 (Build oficial) (64 bits) (cohort: Stable)
-- | --
Revisión | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}


</body>
</html>

**Comment by pixelflinger** [comment]
Definitely not reproducing here. Might be GPU specific.

What is `Windows 10 Ameliorated` ?

**Comment by Shigetorum635** [comment]
> Definitely not reproducing here. Might be GPU specific.
> 
> What is `Windows 10 Ameliorated` ?

A Windows release without **telemetry**, and one of the features that included Telemetry was DirectX 12 Updates. But since this is running off WebGL it should not interfer at all.

I am also running latest drivers of Nvidia GameReady.

**Comment by Shigetorum635** [comment]
Note; it is indeed my GPU issue.
![image](https://user-images.githubusercontent.com/48862659/144719957-ba621558-e317-4dc9-a30d-6b0e9035f0ac.png)

Tested in Edge and Firefox and both gave me this behaviour. Not sure why.

**Comment by Shigetorum635** [comment]
```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
/favicon.png:1 
        
       Failed to load resource: the server responded with a status of 404 ()
filament.js:9 FEngine (32 bits) created at 0x8316d0 (threading is disabled)
demo_suzanne.html:1 
        
       [.WebGL-000068FA00DB1C00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, Medium): You could get a better shader compiling performance if you re-write the uniform block(s)
[ FrameUniforms ]
in the VERTEX shader.
You could get more details from https://chromium.googlesource.com/angle/angle/+/refs/heads/main/src/libANGLE/renderer/d3d/d3d11/UniformBlockToStructuredBufferTranslation.md

demo_suzanne.html:1 
        
       [.WebGL-000068FA00DB1C00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, Medium): You could get a better shader compiling performance if you re-write the uniform block(s)
[ FrameUniforms ]
in the FRAGMENT shader.
You could get more details from https://chromium.googlesource.com/angle/angle/+/refs/heads/main/src/libANGLE/renderer/d3d/d3d11/UniformBlockToStructuredBufferTranslation.md

demo_suzanne.html:1 
        
       [.WebGL-000068FA00DB1C00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, Medium): You could get a better shader compiling performance if you re-write the uniform block(s)
[ FrameUniforms ]
in the FRAGMENT shader.
You could get more details from https://chromium.googlesource.com/angle/angle/+/refs/heads/main/src/libANGLE/renderer/d3d/d3d11/UniformBlockToStructuredBufferTranslation.md
```

LOGS from Edge

**Comment by pixelflinger** [comment]
not actionable at this point.

**Comment by Shigetorum635** [comment]
Alright.

**Comment by vinkovsky** [comment]
Hi! I have the same issue. 

win 10 
geforce rtx 2070 super
chrome ver 97.0.4692.99

**Comment by Shigetorum635** [comment]
> Hi! I have the same issue.
> 
> win 10 geforce rtx 2070 super chrome ver 97.0.4692.99

🤔 Problem could be bigger than expected..
