### ISSUE TITLE
VSM shadows don't seem to support disabling castShadows on renderables

### ISSUE THREAD

**Issue by teub** [google/filament#4929]
**Describe the bug**
Objects still cast shadows even when calling setCastShadows(false) on them.
I suppose this is a bug unless there's a technical reason for it?

**To Reproduce**
This can easily be reproduced with material_sandbox : in the setup function, enable VSM shadows on the view, then uncheck the "cast shadow" option for the loaded object

**Screenshots**
![image](https://user-images.githubusercontent.com/11277063/144717968-27d498aa-8c99-40e7-b225-87a168228e23.png)

**Desktop
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Comment by romainguy** [comment]
For VSMs to work, receivers must be in the shadow map and therefore act as casters as well.

**Comment by teub** [comment]
Thank you ! I thought I read something like it but couldn't find it back.
