### ISSUE TITLE
Objects with refraction materials do not distort the objects behind it

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#4933]
**Describe the bug**
I have an sphere with refraction material. Material code below:
`
material {
    name : refraction_test,
    requires : [ color ],
    shadingModel : lit,
    blending : transparent,
    refractionMode: screenspace,
    refractionType: solid
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = vec4(0,0,0,0);
        material.ior = 1.33;
        material.transmission = 0.0;
        material.roughness = 0.0;
        material.metallic = 0.0;
    }
}
`

I put the spere before "DamagedHelmet" in the gltf_viewr demo.
But when I look behind the sphere through sphere, no refraction happend.
 
![image](https://user-images.githubusercontent.com/4098790/145148002-80ee96b4-8b76-4b9e-b06c-c35c601ae7d8.png)

**Expected behavior**
When I look at "DamagedHelmet" through the sphere, "DamagedHelmet" should be distorted。Just like:
![image](https://user-images.githubusercontent.com/4098790/145147941-26389458-7f73-473e-8087-d9b348b32cd1.png)

 
**Desktop (please complete the following information):**
 - OS: MacOS
 - GPU: AMD Radeon Pro 5500 XT 8 GB
 - Backend: Metal

FilamentVersion: release 1.15.0

**Comment by romainguy** [comment]
You need transmission set to 1 (or at least not 0), a baseColor that's not black and more importantly you need to set the thickness. Setting the thickness to 1 should give you the result you want. See example:
<img width="1136" alt="Screen Shot 2021-12-07 at 8 38 13 PM" src="https://user-images.githubusercontent.com/869684/145149089-07ad9be3-0215-4554-bf72-c401be51f18a.png">

**Comment by cjsliuj** [comment]
ok  thanks
