### ISSUE TITLE
No implementation found for long com.google.android.filament.Skybox.nGetTexture(long)

### ISSUE THREAD

**Issue by Miao-10k** [google/filament#4940]
A typo in SkyBox.cpp leads to java.lang.UnsatisfiedLinkError.

![image](https://user-images.githubusercontent.com/32147896/145530981-2fe5a6f5-47c2-418c-85c6-84d8cc2f6093.png)

https://github.com/google/filament/blob/main/android/filament-android/src/main/cpp/SkyBox.cpp

**Comment by romainguy** [comment]
Thanks! I just pushed the fix.
