### ISSUE TITLE
the FPS is only about 15 when it has a animation on my android device

### ISSUE THREAD

**Issue by magicwo** [google/filament#4942]
Hi, I render a gltf model in my Android device and it has an animation。However , the FPS is only about 15fps. How can I improve the fps?

Android device:
Android 8.0
CPU Info : mt8167
CPU Arch: armeabi-v7a
CPU Core Num:4
GPU Info: PowerVR Rogue GE8300
Ram: 0.94 GB
Resolution:720x1440

**Comment by magicwo** [comment]
And I have tryed like this , the quality is lower，But FPS is still not improve

 view.renderQuality = view.renderQuality.apply {
            hdrColorBuffer = View.QualityLevel.LOW
        }
        view.apply {
            fogOptions.enabled= false
            depthOfFieldOptions.enabled = false
            ambientOcclusionOptions.enabled = false
            dynamicResolutionOptions.enabled = true
            dynamicResolutionOptions.minScale = 0.3f
            dynamicResolutionOptions.maxScale = 0.8f
            dynamicResolutionOptions.homogeneousScaling = true
            dynamicResolutionOptions.quality = View.QualityLevel.LOW
            temporalAntiAliasingOptions.enabled = false
            vignetteOptions.enabled = false
            antiAliasing = View.AntiAliasing.NONE
            fogOptions = fogOptions
            depthOfFieldOptions = depthOfFieldOptions
            ambientOcclusionOptions = ambientOcclusionOptions
            dynamicResolutionOptions = dynamicResolutionOptions
            temporalAntiAliasingOptions = temporalAntiAliasingOptions
            vignetteOptions = vignetteOptions
            setScreenSpaceRefractionEnabled(false)
            setShadowingEnabled(false)
        }

**Comment by magicwo** [comment]
And the Filament Version is 1.14.2

**Comment by romainguy** [comment]
We should move this to a discussion. Could you share the glTF please? I would also recommend capturing a systrace in the profiler so we can see what's taking time. But given the GPU in your device I wouldn't expect miracles with PBR/glTF rendering unfortunately :/

**Comment by magicwo** [comment]
@romainguy Hi, Thank you for your answer。I also think my gpu is of low performence. So，can I turn off the PBR？

**Comment by magicwo** [comment]
[fps15.html.zip](https://github.com/google/filament/files/7704288/fps15.html.zip)
@romainguy Hi, romain, this is my systrace file. Thanks!
