### ISSUE TITLE
Draw outline of mesh

### ISSUE THREAD

**Issue by flykule** [google/filament#4947]
**Is your feature request related to a problem? Please describe.**

I want draw outline of a renderable instance from imported gltf model, is it possible currently?

**Describe the solution you'd like**

Outline effect like three.js, will be better if we can change border color and width.

**Describe alternatives you've considered**

I'm not quite familaliar with outline effect.

**OS and backend**

No.

**Comment by romainguy** [comment]
Please use Discussions for questions
