### ISSUE TITLE
Sceneform/filament: how to change camera projection to othographic/orthogonal?

### ISSUE THREAD

**Issue by agGitHub** [google/filament#4948]
Hi,

I use the project ['Sceneform maintained'.](https://github.com/SceneView/sceneform-android)

I would like to use a camera with orthographic projection.

How can I do that in Sceneform? Would it be possible to add a 'OrthographicCamera' object like in [Three.js](https://threejs.org/docs/#api/en/cameras/OrthographicCamera) ? Or any workaround to have an orthographic projection in Sceneform?

I asked the question on [Sceneform repo](https://github.com/SceneView/sceneform-android/issues/212), but asked me to ask this question here.

Thanks for your help.

**Comment by romainguy** [comment]
There's an API for this on the Camera object. Please don't open issues for questions

**Comment by agGitHub** [comment]
Hi,

Thanks for your answer. I see a setProjection method in the filament version of the objet Camera [here](https://github.com/google/filament/blob/main/android/filament-android/src/main/java/com/google/android/filament/Camera.java), but I don't see an equivalent in the [Sceneform version](https://github.com/google-ar/sceneform-android-sdk/blob/b33fa25987561e5bf2129a25fbce6ad3b43ac4ee/sceneformsrc/sceneform/src/main/java/com/google/ar/sceneform/Camera.java) of the Camera objet. 

How to set the projection to orthogonal in Sceneform?

Thanks.
