### ISSUE TITLE
CLion MSVC SDL2 build failed

### ISSUE THREAD

**Issue by dontweaks** [google/filament#4956]
**Describe the bug**
SDL2 has some errors when it comes to building.

**To Reproduce**
1. Follow building steps https://github.com/google/filament/blob/main/BUILDING.md
2. git clone
3. open the root directory's CMakeLists.txt in CLion to obtain a usable project.
4. build sdl2

**Expected behaviour**
I expect it to build without any errors

**Logs**
```
FAILED: third_party/libsdl2/tnt/CMakeFiles/sdl2.dir/__/src/dynapi/SDL_dynapi.c.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx86\x86\cl.exe  /nologo -DFILAMENT_SUPPORTS_OPENGL -D_THREAD_SAFE -IC:\Users\mprze\source\repos\filament\third_party\libsdl2\tnt\..\include /DWIN32 /D_WINDOWS -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE /Zi /Ob0 /Od /RTC1 /Z7 -MDd /MTd /showIncludes /Fothird_party\libsdl2\tnt\CMakeFiles\sdl2.dir\__\src\dynapi\SDL_dynapi.c.obj /Fdthird_party\libsdl2\tnt\CMakeFiles\sdl2.dir\sdl2.pdb /FS -c C:\Users\mprze\source\repos\filament\third_party\libsdl2\src\dynapi\SDL_dynapi.c
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/MDd' with '/MTd'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winnt.h(2501): error C2118: negative subscript
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by bejado** [comment]
I suspect CLion is attempting to build for x86, which we don't support on Windows. You may need to generate the CMake project outside of CLion inside a `x64 Native Tools Command Prompt` to ensure the correct toolchain is found.

**Comment by dontweaks** [comment]
That's true. I changed in a CLion toolchain panel to amd64 (the only 64 and it seems like it builds (still waiting until it ends). Is there a way to build it on x86?

**Comment by romainguy** [comment]
We don't support x86, only x86_64
