### ISSUE TITLE
Leaking global references from JniCallback on Android

### ISSUE THREAD

**Issue by rawnsley** [google/filament#4957]
It appears that the global references allocated in `acquireCallbackJni` are not always being released because `releaseCallbackJni` is not always called. In our app it occurs after we have turned the screen on and off, which creates and destroys a large scene model with many calls to functions like `setBufferAt`. Eventually (after about 20 power cycles) the JNI global limit is reached and the application crashes out.

I think you can see the problem in apps like _sample-image-based-lighting_ on a smaller scale:

1. run the app
2. back out from it to the home launcher
3. bring it forward again from the recent apps

I'm tracking the global ref allocations with some crude print statements in CallbackUtils.cpp like this:

```
...
#include "CallbackUtils.h"

#include "private/backend/VirtualMachineEnv.h"

#include <utils/Log.h>

int activeCallbackCount = 0;

void acquireCallbackJni(JNIEnv* env, CallbackJni& callbackUtils) {
    ++activeCallbackCount;
    utils::slog.e << "CALLBACKS ADD " << activeCallbackCount << utils::io::endl;    
#ifdef __ANDROID__
    callbackUtils.handlerClass = env->FindClass("android/os/Handler");
    callbackUtils.handlerClass = (jclass) env->NewGlobalRef(callbackUtils.handlerClass);
    callbackUtils.post = env->GetMethodID(callbackUtils.handlerClass,
            "post", "(Ljava/lang/Runnable;)Z");
#endif

    callbackUtils.executorClass = env->FindClass("java/util/concurrent/Executor");
    callbackUtils.executorClass = (jclass) env->NewGlobalRef(callbackUtils.executorClass);
    callbackUtils.execute = env->GetMethodID(callbackUtils.executorClass,
                                              "execute", "(Ljava/lang/Runnable;)V");
}

void releaseCallbackJni(JNIEnv* env, CallbackJni callbackUtils, jobject handler, jobject callback) {
    --activeCallbackCount;
    utils::slog.e << "CALLBACKS DEL " << activeCallbackCount << utils::io::endl;    
    if (handler && callback) {
#ifdef __ANDROID__
        if (env->IsInstanceOf(handler, callbackUtils.handlerClass)) {
            env->CallBooleanMethod(handler, callbackUtils.post, callback);
        }
#endif
        if (env->IsInstanceOf(handler, callbackUtils.executorClass)) {
            env->CallVoidMethod(handler, callbackUtils.execute, callback);
        }
    }
    env->DeleteGlobalRef(handler);
    env->DeleteGlobalRef(callback);
#ifdef __ANDROID__
    env->DeleteGlobalRef(callbackUtils.handlerClass);
#endif
    env->DeleteGlobalRef(callbackUtils.executorClass);
}
...
```
The logcat output indicates the app is losing about 8 global references every cycle.

I'm trying to trace through the cause and it appears `releaseCallbackJni` isn't always being called because either the OpenGL driver function isn't calling `scheduleDestroy` or the queued destructor is not being executed, but I'm not familiar enough with the drive command queue flow to understand which.

**Comment by romainguy** [comment]
@bejado @pixelflinger Can you take a look please? It seems like the issue would be because of scheduled destructions not running.

**Comment by pixelflinger** [comment]
I'm curious (and worried) that power cycles have anything to do with this -- because filament really doesn't know anything about them.

**Comment by jimbz** [comment]
I also observed a similar issue in my application. One element of my scene is updated very frequently (every couple of frames) with a new buffer and newer versions of Filament crash after a little while.

```
A/android.ar.dem: java_vm_ext.cc:674] JNI ERROR (app bug): global reference table overflow (max=102400)global reference table dump:
    java_vm_ext.cc:674]   Last 10 entries (of 102400):
    java_vm_ext.cc:674]     102399: 0x70b38a18 java.lang.Class<android.os.Handler>
    java_vm_ext.cc:674]     102398: 0x1349c8b8 com.phiar.android.arscene.ARMesh$$ExternalSyntheticLambda0
    java_vm_ext.cc:674]     102397: 0x131a8060 android.os.Handler
    java_vm_ext.cc:674]     102396: 0x1349c7f8 java.nio.DirectByteBuffer
    java_vm_ext.cc:674]     102395: 0x12e16e70 java.lang.Class<com.google.android.filament.NioUtils>
    java_vm_ext.cc:674]     102394: 0x702178a0 java.lang.Class<java.util.concurrent.Executor>
    java_vm_ext.cc:674]     102393: 0x70b38a18 java.lang.Class<android.os.Handler>
    java_vm_ext.cc:674]     102392: 0x12e16e70 java.lang.Class<com.google.android.filament.NioUtils>
    java_vm_ext.cc:674]     102391: 0x132e1250 java.nio.DirectByteBuffer
    java_vm_ext.cc:674]     102390: 0x70b38a18 java.lang.Class<android.os.Handler>
    java_vm_ext.cc:674]   Summary:
    java_vm_ext.cc:674]     101969 of java.lang.Class (253 unique instances)
    java_vm_ext.cc:674]       310 of java.nio.DirectByteBuffer (310 unique instances)
```

**Comment by romainguy** [comment]
@pixelflinger It probably has to do with what the app does in the Activity's onPause/onStop/etc. For instance, do we executed scheduled detroys when we destroy the `Engine`? But @jimbz's message seems to indicate the issue could be different and more general.

**Comment by jimbz** [comment]
I am quite confident in my case it is not due to activity lifecycle. It could be a different issue but everything else looks very similar: global reference overflow when using `setBufferAt`.

**Comment by rawnsley** [comment]
> @pixelflinger It probably has to do with what the app does in the Activity's onPause/onStop/etc. For instance, do we execute scheduled destroys when we destroy the `Engine`? But @jimbz's message seems to indicate the issue could be different and more general.

@romainguy is right in my case: I clean up all the scene assets in Activity::onPause and destroy everything including the engine in Activity::onDestroy

**Comment by romainguy** [comment]
That bug aside, you shouldn't clean up all asset in `onPause`. This is expensive and will be wrong in split window mode, or on a large screens, etc.

**Comment by pixelflinger** [comment]
@rawnsley yes, I was actually just about to check that theory -- looking at the code, I think it's possible we're not executing all pending callbacks when the engine is destroyed. Will report on that soon.

**Comment by pixelflinger** [comment]
@rawnsley I con't prove it here yet. Would you be able to try to add this
```
                    ASSERT_POSTCONDITION(serviceThreadCallbackQueue.empty(),
                            "Callback queue not empty, going to leak memory!");
```
inside the 
```
                if (mExitRequested) {
                    break;
                }
```
in `DriverBase::DriverBase`.  And see if it triggers for you?

**Comment by pixelflinger** [comment]
@rawnsley so the fix above will certainly fix a lot of the issues (thanks for reporting!). However, I think there might be another leak when the engine is destroyed, Please let me know if you hit that assert in your case.

**Comment by rawnsley** [comment]
Removing those extra assignments seems to have fixed the leak for me (I should have noticed that myself). Thanks for the super quick turnaround as always.

That post-condition check doesn't fire, but I'll leave it in place in case there are some unusual conditions where it might happen and report back.

I'll close it for now, but if the change doesn't fix the problem @jimbz was having we can reopen.

**Comment by jimbz** [comment]
Thank you for the quick fix! It appears to have fixed my crash indeed.

**Comment by rawnsley** [comment]
@pixelflinger one strange thing now is that there are sometimes more calls to `releaseCallbackJni` than `acquireCallbackJni`. Using the same crude tracking in CallbackUtils.cpp as above and running _sampled-textured-object_ in the emulator I see 8 adds and 11 releases. If I write out **callbackUtils.handlerClass** and **callbackUtils.executorClass** in the release function they are null in three of the calls.
```
utils::slog.e << "CALLBACKS ADD " << activeCallbackCount << " " << &callbackUtils << " " << callbackUtils.handlerClass << " " << callbackUtils.executorClass << utils::io::endl;    

    CALLBACKS ADD  1 0xb4000074344ba0e8 0x27a6 0x27b6
    CALLBACKS ADD  2 0xb4000074344ba458 0x27e6 0x27f6
    CALLBACKS ADD  3 0xb4000074344b9ed8 0x2826 0x2836
    CALLBACKS ADD  4 0xb4000074344b9b68 0x2866 0x2876
    CALLBACKS ADD  5 0xb4000074344ba668 0x28a6 0x28b6
    CALLBACKS ADD  6 0xb4000074344ba038 0x28e6 0x28f6
    CALLBACKS ADD  7 0xb4000074344b8f08 0x2926 0x2936
    CALLBACKS ADD  8 0xb4000074344bc818 0x2966 0x2976

utils::slog.e << "CALLBACKS DEL " << activeCallbackCount << " " << &callbackUtils << " " << callbackUtils.handlerClass << " " << callbackUtils.executorClass << utils::io::endl;    

    CALLBACKS DEL  7 0x7ff696a780 0x0 0x0
    CALLBACKS DEL  6 0x7ff696a780 0x0 0x0
    CALLBACKS DEL  5 0x7ff696a780 0x0 0x0
    CALLBACKS DEL  4 0x7346438b70 0x27a6 0x27b6
    CALLBACKS DEL  3 0x7346438b70 0x27e6 0x27f6
    CALLBACKS DEL  2 0x7346438b70 0x2826 0x2836
    CALLBACKS DEL  1 0x7346438b70 0x2866 0x2876
    CALLBACKS DEL  0 0x7346438b70 0x28a6 0x28b6
    CALLBACKS DEL -1 0x7346438b70 0x28e6 0x28f6
    CALLBACKS DEL -2 0x7346438b70 0x2926 0x2936
    CALLBACKS DEL -3 0x7346438b70 0x2966 0x2976
```
I can't see any obvious reason this is happening, but I also can't understand how handlerClass and executorClass become null. The repeated address for callbackUtils in the remove function implies there's some copy step somewhere into a common variable and perhaps it happens there. All this is speculative based on my rather out-of-date C++ knowledge.

As far as I can tell this behaviour is benign, but it's possible there would be unexpected side-effects if the handlers were set.

**Comment by pixelflinger** [comment]
I will have a look tomorrow, but I'm not sure how to reproduce though.

btw, your crude checks is okay, but you should use std::atomic_int for the global counter and use this pattern to read-update, eg:

int prev = ++counter;

**Comment by rawnsley** [comment]
> 

Agreed about the atomic counter - it's only to illustrate the point rather than for production. Just running the texture sample from main branch in the emulator made it happen, so hopefully it is easy to reproduce. Low priority as it isn't causing any actual problems that I can see.
