### ISSUE TITLE
Question in light distance calculation.

### ISSUE THREAD

**Issue by v4vendeta** [google/filament#4958]
In filament/src/View.cpp line 879

```c++
// always allocate at least 4 entries, because the vectorized loops below rely on that
float* const UTILS_RESTRICT distances = arena.allocate<float>((size + 3u) & 3u, CACHELINE_SIZE);
```
What does ```(size + 3u) & 3u``` mean? When size equals to 1/5/9, the allocation size is 0.

I think it may be ```(size + 3） & ~3``` according to the comment.

**Comment by romainguy** [comment]
Good catch! Yes you are right, it should be `~3u` and not `3u`.

**Comment by romainguy** [comment]
I just pushed a fix.
