### ISSUE TITLE
Support for self-rotation inside Manipulator on mobile

### ISSUE THREAD

**Issue by wes-nz** [google/filament#4963]
#### Feature Request
`Manipulator.cpp` doesn't appear to allow self rotation in Orbit Mode.

This gesture is specific to mobile platforms, in Orbit Mode it should rotate the camera on itself, see below.
![Screenshot 2021-12-14 at 2 10 05 PM](https://user-images.githubusercontent.com/2945380/145914226-bdf33089-6c8f-4dad-85f6-95aa52558c84.png)

https://user-images.githubusercontent.com/2945380/145916602-1f44c27a-554a-4ec8-90c5-03158d31eb3d.mov

**Describe the solution you'd like:**
Update `Manipulator.cpp` to include a new method allowing self rotation. 
Even better, also updating `GestureDetector.kt` to detect the rotation gesture out of the box.

**Describe alternatives you've considered:**
Detecting the rotation with a custom `GestureDetector` and rotating the camera, however the rotation get overwritten by any manipulator using the camera.

**OS and backend:**
Android

**Comment by prideout** [comment]
Unsure of the fate of CamUtils, the team is open to PR's though :)

also check out [scene-viewer from @ThomasGorisse ](https://github.com/SceneView/sceneview-android)
