### ISSUE TITLE
How can I turn off the PBR ？

### ISSUE THREAD

**Issue by magicwo** [google/filament#4966]
the gpu of my Android device has poor performence. So I want to improve ths fps

**Comment by magicwo** [comment]
https://github.com/google/filament/files/7704288/fps15.html.zip 
this is the systrace file

**Comment by romainguy** [comment]
You can't turn off PBR. Please use a discussion instead of an issue.

**Comment by magicwo** [comment]
@romainguy Thank you very much !

**Comment by magicwo** [comment]
@romainguy Could you please help see the systrace file? whitch step  cost much time?
