### ISSUE TITLE
How can I turn off the PBR or some shaders ？

### ISSUE THREAD

**Issue by yj512029078** [google/filament#4967]
the gpu of my Android device has poor performence. So I want to improve ths fps

**Comment by yj512029078** [comment]
Is there a way to not use GPU, just use CPU. Our gpu is very poor. So  i want to try if i can disable some shader or  PBR?

**Comment by romainguy** [comment]
Performance would be even worse on the CPU.

**Comment by bejado** [comment]
Using [unlit](https://google.github.io/filament/Materials.html#materialmodels/unlitmodel) materials will give better performance compared to other material models.
