### ISSUE TITLE
【Android】Filament: N5utils18PostconditionPanicE, AABB can't be empty

### ISSUE THREAD

**Issue by dandingol03** [google/filament#4972]
**Describe the bug**
Crash when loading obj model. This happened on some special android device , such as Redmi.

**To Reproduce**
1. just load obj model and crash 

**Logs**
12-14 10:47:38.322 30802 3539 E Filament: N5utils18PostconditionPanicE
12-14 10:47:38.322 30802 3539 E Filament: in RenderableManager::Builder::Result filament::RenderableManager::Builder::build(filament::Engine &, utils::Entity):267
12-14 10:47:38.322 30802 3539 E Filament: reason: [entity=41] AABB can't be empty, unless culling is disabled and the object is not a shadow caster/receiver
12-14 10:47:38.322 30802 3539 E Filament:
12-14 10:47:38.352 30802 3539 E libc++abi: terminating with uncaught exception of type utils::PostconditionPanic

**Smartphone (please complete the following information):**
 - Device: [Redmi M2012K11AC]
 - OS: [Android 11]

**Additional context**
because the obj model is  the company's private asset ,  i won't upload this model .Sorry~ If the model with empty `AABB` is not   legal, is there any way for me to bypass this problem? Thanks for your time~

**Comment by romainguy** [comment]
Please see the error message: either provide a bounding box or disable culling for that object.
