### ISSUE TITLE
Material sandbox should allow selecting filamat files.

### ISSUE THREAD

**Issue by redstonedash** [google/filament#4976]
**Is your feature request related to a problem? Please describe.**
Sorta? right now material sandbox only allows playing with material properties, but would be nice as a way to test materials without having to setup a demo project.

**Describe the solution you'd like**
A toggle button to switch between what we currently have, and custom material selection which would use a file dialog.

**Describe alternatives you've considered**
Could also be cool to have a text editor where you can just type in and compile the shader? would need to call on matc to do that.

**Comment by redstonedash** [comment]
I would implement this myself but I only use the webversion of filament and don't have the build environment setup.

**Comment by pixelflinger** [comment]
This would also need to generate a UI to set the parameters of the material, and there could be tricky ones like textures.
Another way to test materials is to use matdbg, which allows realtime editing.

**Comment by redstonedash** [comment]
> This would also need to generate a UI to set the parameters of the material, and there could be tricky ones like textures. Another way to test materials is to use matdbg, which allows Realtime editing.

What is matdbg?
Is their a tool that does what I want already?

On the point about the UI. I wouldn't say that is strictly necessary, would be ideal but wouldn't need to exist in the first iteration of the feature.
