### ISSUE TITLE
Java implementation of MorphHelper::applyWeights

### ISSUE THREAD

**Issue by will4621d** [google/filament#4982]
I'm an Android developer, know little about C++, could you implement MorphHelper::applyWeights with Java?

**Comment by bejado** [comment]
`MorphHelper::applyWeights` isn't meant to be called directly. It gets called via [`Animator::applyAnimation`](https://github.com/google/filament/blob/main/android/gltfio-android/src/main/java/com/google/android/filament/gltfio/Animator.java#L54).
