### ISSUE TITLE
【Android & MAC】obj model render uncorrect. Needs Help!

### ISSUE THREAD

**Issue by dandingol03** [google/filament#4987]
**Describe the bug**
I render the model using same obj file using `filament` and `blender`. The model seems a little weird with `filament`.

**To Reproduce**
1. just render the obj file.

**Expected behavior**
render correctly

**Screenshots**
1.filament
![image](https://user-images.githubusercontent.com/13013579/146720261-eafc4152-c5fc-43ab-b2a3-8fb00d655ce4.png)

2.blender
![image](https://user-images.githubusercontent.com/13013579/146720318-71ec40af-e0a5-4203-a77b-67782f67e042.png)

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: [macOS Big Sur]
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: [samsung S20]
 - OS: [e.g. Android 11]

**Additional context**
The obj file is company's asset,  i feel sorry that i can't upload it online. Thanks for your time. The green dirty mark is to erase the company logo on the screenshot, it 's not bug.

**Comment by romainguy** [comment]
How do you open the file with Filament? There isn't much we can do without the file to test. Make sure all the normals point outside before exporting from Blender.

**Comment by dandingol03** [comment]
This obj file is not exported from blender,  i mentioned `blender` is just to provide pictures to be compared. I use the`MeshAssimp` in the filament repo to add obj model to the scene

**Comment by dandingol03** [comment]
Close first, if there is anyone who has encounter the same problem. Just let me know

**Comment by fershous** [comment]
Hi @dandingol03 do you solve the problem? Is there a chance you could help me on how you achieved loading and `obj` with `MeshAssimp` on the device? Thanks in advance!
