### ISSUE TITLE
driverApi.allocate with wrong alignment crash

### ISSUE THREAD

**Issue by RYDB3RG** [google/filament#4991]
Hi,

on my platform (win x64) `alignof(PerRenderableUibBone)` is 16 but there are a few `driverApi.allocate` calls that use default alignment, which is 8, e.g.:

https://github.com/google/filament/blob/b5c4b30ff6332193070a759b5c1c8ac6637ac80e/filament/src/components/RenderableManager.cpp#L368

This leads to crashes when the allocated ptr is read or written because the compiler assumes 16-byte alignment.

**Comment by pixelflinger** [comment]
ah yes, because we have a `alignas(16)` in PerRenderableUibBone. this would actually also fail with `malloc()`. Okay will find a solution...
