### ISSUE TITLE
matc glsl transpile version issue

### ISSUE THREAD

**Issue by RYDB3RG** [google/filament#4993]
Hi,

When `matc` optimizations are enabled, it seems to set `CodeGenerator::mTargetLanguage` to `SPIRV`, in which case shaders become `#version 450`:
https://github.com/google/filament/blob/251abf0545b9b4afcc49a21de5620e79a743ddad/libs/filamat/src/shaders/CodeGenerator.cpp#L61-L64

The problem is when transpiling back to GLSL (because optimizations are enabled), it configures `CompilerGLSL `with `GL_CORE_41`:
https://github.com/google/filament/blob/251abf0545b9b4afcc49a21de5620e79a743ddad/libs/filamat/src/GLSLPostProcessor.cpp#L350

This means it will output a `#version 410` shader and the problem with that is:

```
"0(158) : error C7532: global function unpackHalf2x16 requires "#version 420" or later
0(158) : error C0000: ... or #extension GL_ARB_shading_language_packing : enable
"
1:   #version 410
2:   struct BoneData
3:   {
4:   mat3x4 transform;
5:   uvec4 cof;
6:   };
7:   layout(std140) uniform FrameUniforms
8:   {
9:   mat4 a;
10:   mat4 b;
11:   mat4 c;
12:   mat4 d;
13:   mat4 e;
14:   mat4 f;
15:   mat4 g[4];
16:   vec4 h;
17:   vec4 i;
18:   vec3 j;
19:   float k;
...
```

**Comment by romainguy** [comment]
We use matc with optimizations to compile Filament and don't have this issue. When this particular function is missing we inject our own implementation. How do you reproduce the problem on your end?

**Comment by romainguy** [comment]
Also, which version of Filament are you using?

**Comment by RYDB3RG** [comment]
I'm on HEAD (#4970)
The isse seems related to matrixskinning, it disappears when I don't enable it (has_bones=false)

```
            filament::RenderableManager::Builder builder(node_info->ai_node->mNumMeshes);

            size_t renderable_index = 0;
            for (auto submesh_index : RangeIter(node_info->ai_node->mMeshes, node_info->ai_node->mNumMeshes))
            {
                const auto &submesh_info = submesh_infos[submesh_index];
                builder
                    .material(renderable_index, submesh_info.material)
                    .geometry(
                        renderable_index,
                        filament::RenderableManager::PrimitiveType::TRIANGLES,
                        mesh.vb.vb.get(), mesh.vb.ib.get(),
                        submesh_info.face_offset * 3,
                        submesh_info.min_index, submesh_info.max_index,
                        submesh_info.ai_mesh->mNumFaces * 3);
                ++renderable_index;
            }

            if (has_bones)
                builder
                    .skinning(node_infos.size());

            builder
                .culling(true)
                .screenSpaceContactShadows(true)
                .castShadows(true)
                .receiveShadows(true)
                .boundingBox(bb)
                .build(*global->engine, node_info->node->entity.get());
```

I'll have another look how skinning is related to this. But I'm wondering if it would a good idea to make sure `matc` transpiles to  `version 450` (atleast that is my workaround)

**Comment by romainguy** [comment]
We don't want to/can't transpile to 450, our minimum requirement is GL 4.10 because of macOS.

**Comment by romainguy** [comment]
The real fix is probably to just include the missing functions at code generation. Like I said earlier we have our own implementations, the skinning code generation might just be missing the proper include. It would be in CodeGenerator.cpp or ShaderGenerator.cpp.

**Comment by RYDB3RG** [comment]
The matc shadersource is version 450 and technically doesn't need `unpackHalf2x16` (and probably barfs if I inject it?)
And `OpenGLProgram` doesn't inject it during runtime since `context.ext.ARB_shading_language_packing` is true  (windows x64 GTX 1070)

**Comment by romainguy** [comment]
Then we need to figure out why the runtime injection is failing.

**Comment by pixelflinger** [comment]
It's because I'm injecting it only in the fragment shader.

**Comment by bejado** [comment]
If I understand correctly, this should be as simple as adding `#extension GL_ARB_shading_language_packing : enable` to vertex shaders on platforms that support the extension. @RYDB3RG can you test that https://github.com/google/filament/pull/5022 fixes the issue for you?

**Comment by RYDB3RG** [comment]
@bejado works now. thx
