### ISSUE TITLE
Need python to build on Windows

### ISSUE THREAD

**Issue by Theundeadwarrior** [google/filament#50]
Running:
`cmake -T"LLVM-vs2014" -G "Visual Studio 14 2015 Win64" ../..`
results in:

> -- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.15063.
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler: C:/Program Files/LLVM/msbuild-bin/cl.exe
-- Check for working C compiler: C:/Program Files/LLVM/msbuild-bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files/LLVM/msbuild-bin/cl.exe
-- Check for working CXX compiler: C:/Program Files/LLVM/msbuild-bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang
-- Found assembler: C:/Program Files/LLVM/msbuild-bin/cl.exe
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/ml64.exe
-- Could NOT find Java (missing: Java_JAR_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) (found version "1.8.0_121")
CMake Warning at java/CMakeLists.txt:10 (message):
  JDK not found, skipping Java projects
-- No build type selected, default to Debug
**-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)**
-- SPIR-V optimizer enabled
-- Configuring done
-- Generating done
-- Build files have been written to: D:/github/filament-master/out/cmake-nopython

and running this:
`msbuild TNT.sln /t:material_sandbox /m /p:configuration=Debug`

gives this output:
> 43>CustomBuild: 'PYTHON_EXECUTABLE-NOTFOUND' is not recognized as an internal or external command,
> 43>CustomBuild: operable program or batch file.
> 43>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 9009. [D:\github\filament-master\out\cmake-nopython\third_party\spirv-tools\source\SPIRV-Tools.vcxproj]

**Comment by bejado** [comment]
We removed Python from the dependencies list because the `repo` tool is no longer needed (which uses Python), but that may have been a mistake- looks like spirv needs python to build. @romainguy

**Comment by romainguy** [comment]
We should list the dependency on all platforms then.

**Comment by romainguy** [comment]
Looks like Python is not needed since we skip the tests that use it in spirv-tools.
