### ISSUE TITLE
Filament failed to build with error 2280 with MSVC on windows

### ISSUE THREAD

**Issue by YangYang129** [google/filament#5006]
Hello,

The MSVC team add newly project filament as part of RWC testing to detect compiler. And we found some errors when building filament. These issues come from unreleased VS, I use release VS and the error disappeared. Could you please help look at this issue? Thank you very much

**Steps to reproduce**
1. open VS2019 x64 tools command
2. git clone https://github.com/google/filament F:\gitP\google\filament
3. cd F:\gitP\google\filament
4. mkdir build_amd64 & cd build_amd64
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release ..
6. msbuild /m /p:Platform=x64 /p:Configuration=Release TNT.sln /t:Rebuild

**Build.log:**
[filament_build.log](https://github.com/google/filament/files/7795273/filament_build.log)

**Error info:**
F:\gitP\google\filament\tools\matc\tests\MockConfig.cpp(64,1): error C2280: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(std::nullptr_t)': attempting to reference a deleted function

**Comment by romainguy** [comment]
Are you sure it's related to Eigen? We don't use that library.

**Comment by YangYang129** [comment]
@romainguy Sorry, it was my fault and I have modified comment. It should be that this error C2280 appeared on unreleased VS and disappeared on released VS. Could you please help look at this issue? Thank you very much

**Comment by bejado** [comment]
Seems that in C++ 23 `std::string(nullptr)` is [unallowed](basic_string/basic_string):

```
constexpr basic_string( std::nullptr_t ) = delete; | (12) | (since C++23)
```

Filament should be setting the `/std:c++17` flag, so not sure why this is an error. That being said, @YangYang129 can you try replacing that line with:

```
std::string MockConfig::toString() const noexcept {
    //return nullptr;
    return {};
}
```

**Comment by YangYang129** [comment]
@bejado Thank you for investigating and reply. I changed “return nullptr;”  to “return {};” in MockConfig.cpp from unreleased VS, this error disappeared.
