### ISSUE TITLE
android logcat can not output c++ log

### ISSUE THREAD

**Issue by GGMU1987** [google/filament#5010]
**Describe the bug**
when i run the android demo , android studio logcat can not output c++ log, what should I do？

**Comment by romainguy** [comment]
You have to use Android's logging APIs from the NDK. For example: https://github.com/romainguy/pathway/blob/8e433461fe860985cedc1d62d0beaf0bbe198a80/pathway/src/main/cpp/pathway.cpp#L30

**Comment by GGMU1987** [comment]
@romainguy  I found the LogStream has deal with android log , why it did not work? 
![image](https://user-images.githubusercontent.com/90164629/147872988-2e877887-efe9-4fcf-9e34-e9904e9b35ba.png)

**Comment by romainguy** [comment]
It works fine. Make sure to use slog.d and flush lines with io::endl.

**Comment by GGMU1987** [comment]
@romainguy  the FEngine class has add log like this, but I did not see this log at logcat
![image](https://user-images.githubusercontent.com/90164629/147873178-ec21f1f5-bc80-4374-bc06-ad64533b0bc2.png)

**Comment by GGMU1987** [comment]
@romainguy I have another issue, i render a triangle in flutter texture, only see the skybox, no  triangle, no error logs output in logcat, any idear to debug this situation?
