### ISSUE TITLE
Fail to render demo hello-triangle in flutter

### ISSUE THREAD

**Issue by nevermore1993** [google/filament#5014]
**Describe the issue**
I was trying to display the demo hello-triangle using texture widget in flutter. First I initialize the model in surfaceTexture in Android, and then pass the textureId to flutter. However, in flutter, only the skybox successfully displayed, the triangle went missing.

I thought that the skybox and the triangle should both be able to show in flutter, because they were inside a same surface.

Are there any ideas on how to address this problem?

Or could you please inform me the correct way to render a model in flutter.

Thanks.

**Comment by romainguy** [comment]
If you are rendering into a surfacetexture using flutter shouldn’t matter unless flutter somehow doesn’t correctly dequeue new buffers. There’s not much actionable in this report unfortunately.
