### ISSUE TITLE
render target problem

### ISSUE THREAD

**Issue by pjinsinan** [google/filament#5015]
**Describe the bug**
when I render the scene use like this：
        app.offscreenRenderTarget = RenderTarget::Builder()
            .texture(RenderTarget::AttachmentPoint::COLOR, app.offscreenColorTexture)
            .texture(RenderTarget::AttachmentPoint::DEPTH, app.offscreenDepthTexture)
            .build(*engine);
i also have a sample property in depth texture
            .usage(Texture::Usage::DEPTH_ATTACHMENT | Texture::Usage::SAMPLEABLE)

then I read depth in the depth texture，I find the depth value is wrong，I find when I use rendertaget， setPostProcessingEnabled(bool) influence the depth texture

**To Reproduce**
1. render scene in the rendertarget
2. read depth in the  rendertarget depth texture

**Expected behavior**
the depth should be right

**Screenshots**
![image](https://user-images.githubusercontent.com/5959808/148192834-1a31676e-f599-4e54-91a7-9ed97d815bc6.png)

I use renderdoc find at the end of framegraph，i find at the end of framegraph, only color render in the renderTarget, the depth target is the fullscreen triangle depth

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by pixelflinger** [comment]
do you have a sample app I can use to reproduce the issue?

**Comment by pjinsinan** [comment]
yes，I have modify the gltf_viewer.cpp&nbsp; example, I modify this case like this: render model in the rendertarget, render backgroud in the another rendertarget, then render the fullscreen triangle with texture produced from rendertarget, the fullscreen triangle using the material called&nbsp;renderTargetBlend.mat, I put gltf_view.cpp and mat&nbsp; in the attachment, I also use&nbsp;
DamagedHelmet.glb&nbsp; for viewer




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/filament"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 凌晨5:56
***@***.***&gt;;
抄送:&nbsp;"smart ***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/filament] render target problem (Issue #5015)





 
do you have a sample app I can use to reproduce the issue?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pixelflinger** [comment]
Can you attach a git patch file with your changes please? Thank you!

**Comment by pjinsinan** [comment]
I use the branch origin/release and the last commit is 60d3638f150236d086bbd23e606596c7ec2e438d, I have two patch in the attachment, the first is 0001, the second is 0002, run the gltf_viewer example , the in the added renderTargetBlend.mat, we can find&nbsp; the depth is all equal 0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/filament"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 中午11:55
***@***.***&gt;;
抄送:&nbsp;"smart ***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/filament] render target problem (Issue #5015)





 
Can you attach a git patch file with your changes please? Thank you!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pixelflinger** [comment]
I'm not seeing an attachment?

**Comment by pjinsinan** [comment]
> sorry，I send it again



> I'm not seeing an attachment?

[patch.zip](https://github.com/google/filament/files/7850870/patch.zip)

**Comment by pixelflinger** [comment]
Okay so this is a limitation in our framegraph system as well in how rendertargets work. Basically if you have post processing enabled, you can loose the depth buffer of your custom rendertargets.

The solution is to always turn off post-processing with custom rendertargets.

The problem happens because the system cannot do the rendering into the custom rendertarget directly if post-processing is enabled, because it needs to run more passes after that. The color output of these passes *is* the custom rendertarget. So it can't be both the source and destination.

I will try to improve the documentation about this.

**Comment by pjinsinan** [comment]
> 

thans for explanation
