### ISSUE TITLE
How to access submeshes through FilamentAsset?

### ISSUE THREAD

**Issue by ninjz** [google/filament#5021]
I am using the [SceneView/sceneform-android](https://github.com/SceneView/sceneform-android) library and trying to access the submeshes of a loaded `.glb` model file within a `FilamentAsset` that is returned. However, it looks like all the functions like `getEntities()` returns `int[]` types which are not objects that provide access to anything useful.

How can I access the node hierarchy or sub meshes within the `.glb` file from a `FilamentAsset`?

Related:
SceneView/sceneform-android#118

**Comment by romainguy** [comment]
Please use the discussions tab. Entities are what you are looking for. You use those entities to access components via the managers (RenderableManager for instance to set/get materials, TransformManager for transforms etc.).
