### ISSUE TITLE
【IOS】crash when trying convert CVPixelBuffer to UIImage on `opengl` backend

### ISSUE THREAD

**Issue by dandingol03** [google/filament#5025]
**Describe the bug**
I use the **opengl** backend to run engine, but i can not get the correct `CVPixelBuffer` content and crashed when i try to call `CIContext* context = [CIContext contextWithOptions:@{kCIContextUseSoftwareRenderer : @(YES)}];`

**To Reproduce**
1. create CVPixelBuffer:
```
CGRect nativeBounds = [[UIScreen mainScreen] nativeBounds];  
NSDictionary *pixelAttributes = @{(id)kCVPixelBufferIOSurfacePropertiesKey : @{}};
CVReturn result = CVPixelBufferCreate(kCFAllocatorDefault,
                                      nativeBounds.size.width,
                                      nativeBounds.size.height,
                                      kCVPixelFormatType_32BGRA,
                                      (__bridge CFDictionaryRef)(pixelAttributes),
                                      &pb);
```
2.create engine
```
Engine::create(filament::Engine::Backend::OPENGL);
```
3.render frame
```
captureSwapChain = engine->createSwapChain(pb, backend::SWAP_CHAIN_CONFIG_APPLE_CVPIXELBUFFER);
if (renderer->beginFrame(captureSwapChain)) {
    renderer->render(view);
   // call to picture taken callback
    renderer->endFrame();
}
```
4.picture taken callback
```
CGRect nativeBounds = [[UIScreen mainScreen] nativeBounds];
CIImage* ciImage = [CIImage imageWithCVPixelBuffer:pb];
CIContext* context = [CIContext contextWithOptions:@{kCIContextUseSoftwareRenderer : @(YES)}]; 
CGFloat desiredHeight = nativeBounds.size.width * 1280 / 720; 
CGRect rect = CGRectMake(0, 0, nativeBounds.size.width, nativeBounds.size.height); 
CGImageRef videoImage = [context createCGImage:ciImage fromRect:rect];
UIImage* image = [UIImage imageWithCGImage:videoImage]; 
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES); 
[UIImagePNGRepresentation(image) writeToFile:instance.outputPath atomically:YES]; 
CGImageRelease(videoImage);
```

**Expected behavior**
convert CVPixelBuffer to UIImage successfully
 
**Logs**

> 2022-01-07 14:59:47.120667+0800 DuTProduct3DSpaceModule[29985:10123799] -[__NSCFType bounds]: unrecognized selector sent to instance 0x1220ea460
2022-01-07 14:59:47.121522+0800 DuTProduct3DSpaceModule[29985:10123799] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType bounds]: unrecognized selector sent to instance 0x1220ea460'
*** First throw call stack:
(0x18a492708 0x19ef9c7a8 0x18a395bfc 0x18a495260 0x18a497560 0x10472353c 0x1d6225758)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType bounds]: unrecognized selector sent to instance 0x1220ea460'
terminating with uncaught exception of type NSException

**Smartphone (please complete the following information):**
 - Device: [iphone 12]
 - OS: [ios 14.7.1]

**Additional context**
I want to implement the `screen capture` feature on ios device with  `CVPixelBuffer`. When i switch to metal backend, it works fine.  However i am not fimiliar with `metal`. Because we want to deploy filament on my app, i decide to change the backend to `opengl` which i am more fimiliar with~

**Comment by bejado** [comment]
The `SWAP_CHAIN_CONFIG_APPLE_CVPIXELBUFFER` flag is only supported by the Metal backend: https://github.com/google/filament/blob/ee9bfa26b1a1f630c7c9bb960258cf74af672c52/filament/include/filament/SwapChain.h#L171-L172

**Comment by dandingol03** [comment]
So there is no way i can use `opengl`backend to generate a video which record the filament view with `CVPixelBuffer` ?
