### ISSUE TITLE
vkGetInstanceProcAddr should not be initialized again

### ISSUE THREAD

**Issue by bbzy** [google/filament#5026]
https://github.com/google/filament/blob/2f3aac29da7e833378d75dd89fadcfc4bcb11623/libs/bluevk/src/BlueVK.cpp#L360
vkGetInstanceProcAddr should not be initialized again. It was initialized in function bluevk::initialize() and got NULL after reinitalizing. THEN CRASH!!!

**Comment by bejado** [comment]
Can you give more details about what platform you're on? I see where we set `vkGetInstanceProcAddr` twice, but I don't know why this would get set to `NULL` the second time.

**Comment by bbzy** [comment]
Sorry i'm late.
Detail shows below:
Platform: Mac OS X 12.1
XCode: 13.2.1
VulkanSDK: 1.2.198.0

**Comment by pixelflinger** [comment]
@prideout any idea on this one?

**Comment by prideout** [comment]
This looks like a good catch, the fix will be in bluevk-gen.py, I'll TAL.
