### ISSUE TITLE
【IOS】SEGV_ACCERR , crash in FEngine::loop -  MetalTexture::loadWithCopyBuffer

### ISSUE THREAD

**Issue by dandingol03** [google/filament#5027]
**Describe the bug**
Random crash in FEngine::loop, and the executed thread is not the main thread. There is only one code which is relavent about decoding image to texture, but i execute that code in the main thread. Please help me.
**To Reproduce**
1. create engine with `metal` backend
2. create texture on the main thread
3. decode image to texture with `CGImageGetDataProvider`
4. call Texture::setImage

**Expected behavior**
no crash

**Logs**
![image](https://user-images.githubusercontent.com/13013579/148531970-0548612f-5430-48c7-9764-6ba657093438.png)

```
0
libsystem_platform.dylib
_platform_memmove + 72
1
DUApp
filament::backend::metal::MetalTexture::loadWithCopyBuffer(unsigned int, unsigned int, MTLRegion, filament::backend::PixelBufferDescriptor&, filament::backend::metal::PixelBufferShape const&) + 108
```

**Smartphone (please complete the following information):**
![image](https://user-images.githubusercontent.com/13013579/148532093-fc55c04b-b1a0-4d71-b494-cf75d1dbeeda.png)

**Additional context**
Obviously `Metal::loadWithCopyBuffer` is called in other thread, but i create engine and texture in main thread. Is that ok?

**Comment by bejado** [comment]
Yes, Filament's API can be called from the main thread. The crashed thread is Filament's internal driver thread.

My guess is that you're releasing the `CGImage` memory too soon. The pixel buffer needs to remain valid until the `PixelBufferDescriptor`'s callback is called:

```
    void* buffer = /* allocate buffer */ ;

    Texture::PixelBufferDescriptor p(
            buffer,
            size,
            Texture::Format::RGBA,
            Texture::Type::UBYTE,
            [](void* buffer, size_t, void* data) {
                /* free buffer */
            }
    );
```

**Comment by dandingol03** [comment]
I will try it later, thanks

**Comment by dandingol03** [comment]
I didn't release the `CGImage` immediately, but i don't keep a reference to it. Is This the reason make `CGImage` invalid ?  I use `CFDataRef` to generate texture and release it in the `PixelBufferDescriptor` callback.  This texture-parse function is invoked on the main thread,  Here is my code:
```
Texture* parseTexture(Engine* engine, const char* path) {
    
    
    NSBundle *bundle = [NSBundle mainBundle];
    NSString* filePath = [[NSString alloc] initWithUTF8String:path];
    UIImage * img = [[UIImage alloc]initWithContentsOfFile:filePath];
    CGImageRef image = [img CGImage];
    size_t image_width = CGImageGetWidth(image);
    size_t image_height = CGImageGetHeight(image);
    size_t size_in_bytes = CGImageGetBytesPerRow(image) * image_height;
    CFDataRef data = CGDataProviderCopyData(CGImageGetDataProvider(image));
    
    const unsigned char * buffer = CFDataGetBytePtr(data);

    Texture* texture = Texture::Builder()
    .width(image_width)
    .height(image_height)
    .levels(0xff)
    .format(Texture::InternalFormat::SRGB8_A8)
    .build(*engine);
    
    Texture::PixelBufferDescriptor desc(
            buffer,
            size_in_bytes,
            backend::PixelDataFormat::RGBA,
            backend::PixelDataType::UBYTE,
                                              [](void* buffer, size_t n, void* user) {
        CFDataRef data = (CFDataRef)user;
        CFRelease(data);
        
    }, (void*)data);          
    
    texture->setImage(*engine, 0, 0, 0, image_width, image_height, std::move(desc));
    
    return texture;
   }
```
Looking forward to your reply.

**Comment by bejado** [comment]
Please see my response in https://github.com/google/filament/discussions/4904

**Comment by dandingol03** [comment]
@bejado I have read the answer you mentioned in #4904 , it seems right. But  there is no crash if i run that code and release `CFData` and `CGImage` in advance , the model is just rendered whole black as below:
![88CF81A3-146B-4BEC-931B-3E6D17BCED0C](https://user-images.githubusercontent.com/13013579/150763119-ff125e49-e626-40af-899d-ff65016f125a.png)

I am afraid that this crash still happen after i use the code you mentioned in #4904
