### ISSUE TITLE
MaterialInstance::setDepthCulling(<#bool enable#>)

### ISSUE THREAD

**Issue by noseeevil** [google/filament#5042]
Hello!

I trying to change "depthCulling" option in my custom material, but something is wrong

my material:
<img width="1232" alt="Снимок экрана 2022-01-12 в 18 14 02" src="https://user-images.githubusercontent.com/16321108/149167673-bd5d5ef4-cfcd-4560-b717-919a4702100b.png">

my code:
<img width="1232" alt="Снимок экрана 2022-01-12 в 18 21 14" src="https://user-images.githubusercontent.com/16321108/149169029-b12b2778-603b-47f3-a887-311b7d74fc17.png">

I can't change "depthCulling" option, its steel - FALSE

What's wrong?

**Comment by romainguy** [comment]
You are setting the *instance*'s depth culling but checking the *material*'s depth culling. Changing the value for an instance won't change it for the material.

**Comment by romainguy** [comment]
You can't, you can only do it on instances.
