### ISSUE TITLE
Missing Javascript enums

### ISSUE THREAD

**Issue by Stradi** [google/filament#5047]
Some enums are not implemented in `jsenums.cpp` file. I don't know the full list but here are the some enums missing in the View class.

Missing ones:
- View$AmbientOcclusionOptions
- View$BloomOptions
- View$DepthOfFieldOptions
- View$FogOptions
- View$VignetteOptions

**Comment by pixelflinger** [comment]
I just double checked and all these are implemented in `jsbindings.cpp`.
