### ISSUE TITLE
Transmission (SSR) broken since #4946

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#5050]
Since #4946 landed, transmission seem broken, even when screen-space reflections are disabled.
e.g.: screen shots from gltf_viewer:
![Screen Shot 2022-01-13 at 2 58 23 PM](https://user-images.githubusercontent.com/1240896/149422750-285ac882-47df-4c82-aef3-84b12268faef.png)
![Screen Shot 2022-01-13 at 3 01 18 PM](https://user-images.githubusercontent.com/1240896/149422796-ad5d2d91-9d15-4993-b70f-e220f10e1563.png)

**Comment by bejado** [comment]
Fixed by #5051
