### ISSUE TITLE
Turning off receiveShadows with VSM causes crash

### ISSUE THREAD

**Issue by tottero** [google/filament#5053]
**Describe the bug**
If a gltf lit shader has receiveShadows turned off when VSM is enabled, there is a consistent crash when rendering the scene.

**To Reproduce**
Turn off receiveShadows on an imported gltf model with the lit shader on while using VSM type shadows.

**Expected behavior**
Rendering without a crash.

**Logs**
```
Panic
in filament::backend::Program filament::FMaterial::getProgramBuilderWithVariants(uint8_t, uint8_t, uint8_t) const:434
reason: The material 'ubershader_lit_opaque' has not been compiled to include the required GLSL or SPIR-V chunks for the fragment shader (variant=0x41, filtered=0x41).
```
 - Backend: Metal

**Comment by bejado** [comment]
I'm able to reproduce with `gltf_viewer`. The relevant assertion is:

```
reason: ../../filament/src/Material.cpp:366: failed assertion `!Variant::isReserved(variantKey)'
```
