### ISSUE TITLE
Compute morphing on GPU #4999 breaks bones

### ISSUE THREAD

**Issue by RYDB3RG** [google/filament#5059]
hi,

#4999 breaks renderables with bones
`samplerBindings` has nullptr entries, which crashes when accessed later:
https://github.com/google/filament/blob/8d1402d37b0b87cc64ef64550b1f000b9b0a16fd/filament/backend/src/opengl/OpenGLProgram.cpp#L274

I can reproduce it with opengl backend on windows with unmodified `gltf_viewer` and an animated model from gltf sample repro, such as [BrainStem.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BrainStem/glTF-Embedded/BrainStem.gltf)

**Comment by daemyung** [comment]
Hi it will be fixed by #5036.

**Comment by pixelflinger** [comment]
> Hi it will be fixed by #5036.

Can we make a separate fix? I think #5036 might take some time to be merged.

**Comment by daemyung** [comment]
> > Hi it will be fixed by #5036.
> 
> Can we make a separate fix? I think #5036 might take some time to be merged.

No problem. #5060 is created.
