### ISSUE TITLE
Skinning breaks validation on Vulkan (unbound morphing sampler)

### ISSUE THREAD

**Issue by prideout** [google/filament#5085]
This error is seen with Vulkan but the fix will need to live in the Filament layer.  Note that Filament already binds dummy textures (e.g. a black reflection map) when a shader variant is activated that samples from a binding point that does not have a bound texture, even if it samples from it conditionally.

We can't correctly handle this in the backend because we don't know what type of image to create (cubemap, 3D, array).  That's why we currently see this error with skinned models:

```
Descriptor in binding #7 index 0 requires an image view of type VK_IMAGE_VIEW_TYPE_2D_ARRAY but got VK_IMAGE_VIEW_TYPE_2D.
```

**Comment by pixelflinger** [comment]
@daemyung, I thought this should have been fixed by #5062 ?

**Comment by prideout** [comment]
I think #5062 ensures a bound Weights UBO, but does not ensure a bound Targets Texture.

Side note: I feel we say "buffer" in some places where we should say "texture".    (e.g. the public facing `MorphTargetBuffer` thingie is actually a texture wrapper, not a buffer wrapper)

**Comment by pixelflinger** [comment]
> Side note: I feel we say "buffer" in some places where we should say "texture". (e.g. the public facing `MorphTargetBuffer` thingie is actually a texture wrapper, not a buffer wrapper)

Yes but we wanted to avoid exposing that to the public API. Conceptually this could be a SSBO for instance. I don't think this implementation detail leaks to the user facing API.

**Comment by daemyung** [comment]
> @daemyung, I thought this should have been fixed by #5062 ?

@pixelflinger No it's another issue... and @prideout already explained a solution.

**Comment by daemyung** [comment]
@prideout Could you tell me which model did you test? This error message isn't shown on `AnimatedTriangle.gltf`.

@pixelflinger Can we split `HAS_SKINNING_OR_MORPHING` to `HAS_SKINNING` and `HAS_MORPHING`.

**Comment by pixelflinger** [comment]
> @pixelflinger Can we split `HAS_SKINNING_OR_MORPHING` to `HAS_SKINNING` and `HAS_MORPHING`.

No because that would require a new variant, which we want to avoid at this time, for various reasons.

**Comment by prideout** [comment]
AnimatedTriangle does not use skinning.  Try the Fox model:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox

(also be sure to use a debug build)

**Comment by pixelflinger** [comment]
@prideout I tried the Fox and it displays correctly and I'm not getting the error message.

```
FEngine (64 bits) created at 0x12a000000 (threading is enabled)
FEngine resolved backend: Vulkan
DebugServer listening at http://localhost:8080
Validation layer not available; did you install the Vulkan SDK?
Please ensure that VK_LAYER_PATH is set correctly.
Vulkan device driver: MoltenVK 1.1.4
Selected physical device 'Apple M1' from 1 physical devices. (vendor 0x106b, device 0xa140, driver 0x2778, api 1.1)
Sampleable depth formats: VK_FORMAT_D16_UNORM VK_FORMAT_D32_SFLOAT VK_FORMAT_S8_UINT VK_FORMAT_D32_SFLOAT_S8_UINT 
vkCreateSwapchain: 1024x640, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 3, VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
```
