### ISSUE TITLE
Is it possible to create the same quality render image in the browser?

### ISSUE THREAD

**Issue by vinkovsky** [google/filament#5091]
![example_bistro1](https://user-images.githubusercontent.com/66293881/150722295-01c86807-7f32-4d6b-a45e-c86974332fa7.jpg)
![example_bistro2](https://user-images.githubusercontent.com/66293881/150722297-5e8b3ed9-8571-49c3-9835-3c8b00e7e7a3.jpg)

**Comment by vinkovsky** [comment]
Also would like to know if the APIs for android, ios, windows are the same for the js version? Does the API for js have the same toolkits as for Windows or Mac?

**Comment by romainguy** [comment]
The APIs and features are the same on all supported platforms.

**Comment by pixelflinger** [comment]
Please move this to a discussion. Thank you!
