### ISSUE TITLE
Can't use filament pkg in react

### ISSUE THREAD

**Issue by vinkovsky** [google/filament#5097]
Hi! When i try to import filament in my react component i get this error

`Module not found: Can't resolve 'fs'`

**Comment by prideout** [comment]
Thanks for the bug report.  Do you use a bundler like webpack or rollup?  In the past we tried to maintain a webpack example but it was difficult to maintain.  The model-viewer team uses rollup to import Filament. ([link](https://github.com/google/model-viewer/blob/5ba2844258ca596a057adf302bb09b8557fe32f7/packages/render-fidelity-tools/rollup.config.js
))

Help with JS bundling or modules is somewhat beyond the scope of the team.  Our JS package is generated by emscripten so it's tricky.

**Comment by pixelflinger** [comment]
Maybe move this to a discussion?

**Comment by prideout** [comment]
Yes, @vinkovsky please open a discussion if you have further information, and since the community might help out with this one.

**Comment by vinkovsky** [comment]
Thnaks for the response. I will
