### ISSUE TITLE
Shadows not displaying for certain GLTF models

### ISSUE THREAD

**Issue by MarkMurillo** [google/filament#5100]
**Describe the bug**
When rendering a model (in tandem with AR core for surface detection and positioning), certain GLTF models
(loaded with the `AssetLoader` class from gltfio) doesn't cast a shadow on the planes that are rendered.
Here are the different models used:

1. Non-shadow casting model: 
[trex.zip](https://github.com/google/filament/files/7928888/trex.zip)

2. Shadow casting model:
[scooter.zip](https://github.com/google/filament/files/7928890/scooter.zip)

**To Reproduce**
1. Load the gltf asset using AssetLoader.
2. Render a flat plane below the asset that will be loaded (set receive shadows to true)
3. Set directional lighting and cast shadows to true.
4. Place the gltf model on top of the plane
5. Assert that the scooter model renders a shadow but the trex model doesnt.

**Expected behavior**
Both models should be rendering shadows

**Screenshots**
![17e8de6a482 jpeg](https://user-images.githubusercontent.com/3269726/150865724-0e881995-79c9-4867-8172-bed1b4f5374f.png)
![17e8de6ff9a jpeg](https://user-images.githubusercontent.com/3269726/150865746-d0122cca-571d-4e83-8aad-07deab646544.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - OS: Android 12

**Additional context**
- The t-rex model itself is receiving shadows from the direct lighting, it just doesn't seem to want to cast shadows.

**Comment by romainguy** [comment]
Is the directional light oriented the same way in both cases?

**Comment by MarkMurillo** [comment]
> Is the directional light oriented the same way in both cases?

Yes, they both use the same parameters for the directional light:
intensity = 200_000f
dir = (0.0f, -5f, 0.0f)

**Comment by romainguy** [comment]
Could be related to issue #5088

**Comment by pixelflinger** [comment]
I have reverted #4939, which doesn't fix the problem -- so my guess was wrong.

**Comment by teub** [comment]
I had a look at the recent changes. I was wondering if the issue could be in [getters.vs ](https://github.com/google/filament/blob/main/shaders/src/getters.vs): 

mulBoneNormal(vec3 n, uint i) seems to be using bonesUniforms.bones[i].transform instead of cof for recomputing cof[2].z but I'm not sure ?

**Comment by pixelflinger** [comment]
I have reverted everything related to #4999 and that fixes the lighting issues (not sure about the shadows). I'm not sure where things went wrong yet.

**Comment by teub** [comment]
So maybe that could be a hint (or not) : I tried 1.17.0, and it looked like my tube test mesh wasn't using the normal map it was supposed to use. It seemed to use a normal map from another object in the scene whereas I'm pretty sure I used a default normal map.
This is getting weirder, now I'm wondering if the lighting problem I was seeing was also it using another (less obvious) map, like a white or black one.

(I also have some warnings in the log but they were here before : [entity=1765, primitive @ 0] missing required attributes (000000000000001F), declared=000000000000000F; maybe I should fix those first).

**Comment by pixelflinger** [comment]
@daemyung I investigated this a bit and it seems like skinned normals are broken since #4999 (I tried to revert everything but that change). Note that this is *skinning*, not *morphing* that is broken. It is strange because #4999 doesn't seem to change the code path for skinning.
I'm not sure yet what's going on with shadows, but normals are definitely broken on the dinosaure model above.

It would be great if you could have a look, as it's getting late here. Thank you.

**Comment by daemyung** [comment]
@pixelflinger Thanks I will look into.

**Comment by pixelflinger** [comment]
@daemyung thank you!

More data points:

@teub, I think the shadowing issue might be a problem with the asset, its bounding box is completely wrong, and shadowing is using it to compute the light frustum.

@daemyung, the issue with the normals happens only in OpenGLES, it works fine in both Metal and Vulkan.

**Comment by daemyung** [comment]
@pixelflinger Do you have some tips to render `bawanglong` is too big.

**Comment by pixelflinger** [comment]
> @pixelflinger Do you have some tips to render `bawanglong` well? It is too big.

Yes, use the `-s` option, it makes things better.

**Comment by pixelflinger** [comment]
@daemyung it is definitely a problem with the 2nd `SamplerInterfaceBlock`.
If I comment out Material.cpp:385:
```
//        addSamplerGroup(pb, BindingPoints::PER_RENDERABLE_MORPHING,
//                SibGenerator::getPerRenderPrimitiveMorphingSib(variant), mSamplerBindings);
```

The this model works.

This must be an existing bug that we never ran into before.

**Comment by daemyung** [comment]
@pixelflinger Hm.. strange... I can't see this issue. Are you testing on Android? 
<img width="885" alt="스크린샷 2022-01-25 오후 3 23 06" src="https://user-images.githubusercontent.com/7459074/150922372-88170209-fa46-4ded-ac1f-7444effeead3.png">

**Comment by pixelflinger** [comment]
No actually, I'm testing on a MacMini M1.

If you don't see the problem on Android, then it totally sounds like an opengl binding issue, because Marcos still uses GL4.1.

Thank you for investigating, I think I can fix this tomorrow. It's definitely an existing GL (not ES) bug.

**Comment by daemyung** [comment]
@pixelflinger Upper screenshot captured on MacbookPro Intel. I can't reproduce this issue.

```
FEngine resolved backend: OpenGL
[ATI Technologies Inc.], [AMD Radeon Pro 5500M OpenGL Engine], [4.1 ATI-4.7.101], [4.10]
Active workarounds: 
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_RENDERBUFFER_SIZE = 16384
GL_MAX_SAMPLES = 8
GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = 16.000000
GL_MAX_UNIFORM_BLOCK_SIZE = 65536
GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 256
OS version: 0
```

**Comment by pixelflinger** [comment]
I just tested on an Intel MacBook Pro and I definitely see the lighting/normal problem:
<img width="880" alt="Screen Shot 2022-01-24 at 11 02 55 PM" src="https://user-images.githubusercontent.com/1240896/150927503-4a4248d8-89d0-4bf3-827d-b040f0252a2f.png">

**Comment by pixelflinger** [comment]
I figured out the lighting problem, it was indeed an existing bug in OpenGLProgram, I'll fix it tomorrow.
The bug would happen when a SamplerInterfaceBlock was defined on a program but not used/set.

Thank you all for all the help!

**Comment by pixelflinger** [comment]
@teub I think the shadow problem is because the bounding box of this model is wrong. Can you try after adjusting the bounding box?

**Comment by MarkMurillo** [comment]
> I think the shadow problem is because the bounding box of this model is wrong. Can you try after adjusting the bounding box?

Is it possible to post this scaled down model?

**Comment by daemyung** [comment]
> @daemyung Is it possible to post this scaled down model?

No problem. Test [scaled.glb.zip](https://github.com/google/filament/files/7951368/scaled.glb.zip).
