### ISSUE TITLE
【IOS】SEGV_ACCERR , crash in filament::FMaterialInstance::duplicate(filament::FMaterialInstance const*, char const*) + 8

### ISSUE THREAD

**Issue by dandingol03** [google/filament#5194]
**Describe the bug**
This crash is happened randomly, and this crash ratio is **0.4%**. It seems that the `&mDefaultInstance` is nullptr or some invalid address. However, `filament` doesn't clean  the `Material::mDefaultInstance`,  why does this address invalid?

**To Reproduce**
``` 
 //setupFilamat is used to read filamt file, and create the relavant material
  app.mat = params->setupFilamat(filamat_path);
  app.backgroundMat = params->setupFilamat(filamat_path); 
  app.baseColorTexture = parseTexture(texture_path);   
  TextureSampler sampler;
  app.materialInstance = app.mat->createInstance();
```

**Screenshots**
![image](https://user-images.githubusercontent.com/13013579/153796032-f370f849-cbbc-42ca-a8ab-f4d522c6208b.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. IOS, all version]
 - Backend: [Metal]

**Additional context**
- io: i read the `filamat` file delivered by the server in program to initialize `Material` and `MaterialInstance`. If the file is missing,  i will not initialize `Material`. Here is my code :
```
    Material* SandboxParameters::setupFilamat(const char *path) {
        FILE* fp;
        fp = fopen(path, "rb");
        if (fp == NULL) return nullptr;
        fseek(fp, SEEK_SET, SEEK_END);
        long len = ftell(fp);
        fseek(fp, SEEK_SET, SEEK_SET);
        auto *data = new unsigned char[len];
        fread(data, len, 1, fp);
        fclose(fp);
        Material* material = Material::Builder().package(data, len).build(*engine);
        delete data;
        return material;
    }
```

 - crash scene:  This crash happened almost in the low-memory situation (about 100mb or 200mb available, the scene which use filament to render stuff uses about 400mb - 500mb) and crash immediately after first entering this scene or after some foreground - background switch.   I wonder if `apple`  does  some memory-clean making the `mDefaultInstance` invalid when there is no enough memory to initialize `filament` and `apple` will send memory warning to application to clear stuff . 
 - solution: I add some code to check if  the `&mDefaultInstance` is nullptr. However it may not work before i get to know the crash reason.

Thanks for your time~

**Comment by pixelflinger** [comment]
Please attach the full stack of the crash (please don't use a screenshot).

**Comment by pixelflinger** [comment]
It seems to me that you must be using objects that have been destroyed.  This looks like an app issue.

**Comment by dandingol03** [comment]
There is no complex logic in the app. By the way,  is there any way i can tell which `MaterialInstance` have been destroyed? @pixelflinger
