### ISSUE TITLE
Unable to create Vulkan instance

### ISSUE THREAD

**Issue by geroge-d** [google/filament#5201]
**Describe the bug**
The Filament was crashed with logs below, when we ran it in a Android 8.1.0 device with gpu render:PowerVR Rogue GE8320,vendor:Imagination Technologies,version:OpenGL ES 3.2 build 1.9@4971894
The filament version is : v1.16.1

02-15 14:41:50.885 I/Filament(12037): FEngine (64 bits) created at 0x7d05800000 (threading is enabled)
02-15 14:41:50.886 D/Filament(12037): FEngine resolved backend: Vulkan
02-15 14:41:50.894 E/vulkan  (12037): invalid vkGetInstanceProcAddr(VK_NULL_HANDLE, "vkEnumerateInstanceVersion") call

02-15 14:41:50.903 E/Filament(12037): Panic
02-15 14:41:50.903 E/Filament(12037): in filament::backend::VulkanDriver::VulkanDriver(filament::backend::VulkanPlatform *, const char *const *, uint32_t):229
02-15 14:41:50.903 E/Filament(12037): reason: Unable to create Vulkan instance.

**Comment by romainguy** [comment]
Is Vulkan properly supported on that device? Even if it is, I wouldn’t recommend it over OpenGL. Vulkan 1.0 was added in Android 7 and GL drivers, esp for older GPUs, will be more mature.

**Comment by geroge-d** [comment]
> Is Vulkan properly supported on that device? Even if it is, I wouldn’t recommend it over OpenGL. Vulkan 1.0 was added in Android 7 and GL drivers, esp for older GPUs, will be more mature.

yes, it is supported. because of opengl driver bugs of PowerVR Rogue series gpu,so we have to try vulkan backend for these device with gpu PowerVR.  please see another bugs reported by me [https://github.com/google/filament/issues/5118](url)

**Comment by prideout** [comment]
The message about `vkEnumerateInstanceVersion` might be a red herring because `vkGetInstanceProcAddr` should simply return null on 1.0 devices, which is not an exceptional situation.

I am guessing that your device does not support one of the extensions that we are requesting.  Can you check if your device supports `VK_KHR_get_physical_device_properties2`?

**Comment by geroge-d** [comment]
@prideout yes, the extension VK_KHR_get_physical_device_properties2 is not support. And i removed it ,and run it in the device,got the following crash
02-16 11:26:07.304 E/Filament(29251): Panic
02-16 11:26:07.304 E/Filament(29251): in void filament::backend::VulkanContext::selectPhysicalDevice():36
02-16 11:26:07.304 E/Filament(29251): reason: vkEnumeratePhysicalDevices count error.

**Comment by prideout** [comment]
Thanks for checking!  We should probably mention this extension in our README, or try to remove the requirement.  However for your device I would recommend OpenGL.  I think this is only the tip of the iceberg.  e.g. your driver seems to be listing 0 physical devices for some reason.

**Comment by pixelflinger** [comment]
@prideout the problem is that IMG GPUs have very buggy OpenGLES compilers which crash with filament's materials.

**Comment by romainguy** [comment]
I was just thinking about this this morning. I wonder if we could try to use the offline compilers IMG and ARM make available to try and repro some of those bugs. We could even add a `--validate` mode to `matc` to make it run every generated shader through IMG's and ARM's offline compilers to try and catch these issues ahead of time maybe?

**Comment by pixelflinger** [comment]
looks like this is not actionable at this time.
