### ISSUE TITLE
Android. Possibly missing public modifier

### ISSUE THREAD

**Issue by sdpopov-keyvariable** [google/filament#5210]
**Describe the bug**
It seems public modifier is missing for Texture.PixelBufferDescriptor.computeDataSize() method in filament/android/filament-android/src/main/java/com/google/android/filament/Texture.java.

**Expected behavior**
The method should be public. Also it's good to provide public instance (non static) method for Texture.PixelBufferDescriptor returning result of the static version with the descriptor's parameters.

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by pixelflinger** [comment]
Thanks. good catch!
