### ISSUE TITLE
Crash gltf_viewer after resizing window on Vulkan

### ISSUE THREAD

**Issue by daemyung** [google/filament#5217]
**Describe the bug**
Crash gltf_viewer after resizing window on Vulkan

**To Reproduce**
1. Run gltf_viewer with `--api vulkan`.
2. Crash.

**Expected behavior**
Crash never be happened.

**Logs**
```
VULKAN ERROR: (VUID-vkDestroyImage-image-01000) Validation Error: [ VUID-vkDestroyImage-image-01000 ] Object 0: handle = 0x7fcbd087da18, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf2d29b5a | Cannot call vkDestroyImage on VkImage 0x3d53e60000000a1f[] that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to image, either directly or via a VkImageView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.204.0/mac/1.3-extensions/vkspec.html#VUID-vkDestroyImage-image-01000)
```

**Desktop (please complete the following information):**
 - OS: macOS
 - GPU: AMD Radeon Pro 5500M
 - Backend: Vulkan

**Comment by romainguy** [comment]
I can't reproduce on macOS with tip of tree from the main branch. Note that Vulkan on macOS goes through Metal via MoltenVK. While it's useful for testing, it's better to use the Metal backend directly.

**Comment by prideout** [comment]
Interesting, I cannot reproduce either, I'll give it a try on Windows later today.  Potentially related bug is #2728.

**Comment by prideout** [comment]
I am also unable to reproduce on Windows with an NVIDIA GPU.

**Comment by prideout** [comment]
Ah thank you, I managed to reproduce.  Thanks for the bug report!

**Comment by prideout** [comment]
Re-opening, I think I found another way in which this can occur.

**Comment by prideout** [comment]
Unable to trigger the bug after the last few fixes.  Please re-open if you bump into this again.

**Comment by daemyung** [comment]
Thanks. It's fixed.
