### ISSUE TITLE
Crash VertexBuffer when loading glb model

### ISSUE THREAD

**Issue by August1996** [google/filament#5234]
**Describe the bug**
when i load this [glb model](https://github.com/August1996/filament-bugreport/raw/main/crash_model.glb), crash happens. but is ok with babylon.js and threejs.

**Logs**
`At least one buffer slot was never assigned to an attribute.`

**Comment by chx-code** [comment]
Some properties of the model are not resolved，such as uv or normal

**Comment by August1996** [comment]
> Some properties of the model are not resolved，such as uv or normal

how can i check these properties?

**Comment by prideout** [comment]
This model has a total of 8 skinning weights per skeleton node (i.e. two sets of weights).  Filament supports only a single set of weights per node (this conforms to the glTF minspec)

In the past we emitted a friendly error message in gltfio, I'll take a look.

**Comment by August1996** [comment]
> This model has a total of 8 skinning weights per skeleton node (i.e. two sets of weights). Filament supports only a single set of weights per node (this conforms to the glTF minspec)
> 
> In the past we emitted a friendly error message in gltfio, I'll take a look.

thanks, it works!
