### ISSUE TITLE
【MAC】ImGui::Image not compatible with filament::Texture

### ISSUE THREAD

**Issue by dandingol03** [google/filament#5245]
**Describe the bug**
Recently, i'm writing an material editor which is based from material_sandbox demo. However the `ImGui` GUI become a mess after i add an ImGui::Image the texture of which is created by `filament`.

**To Reproduce**
1. use `stbi_load` to load byte data from image file
2. create `filament::Texture` and `filament::TextureBuffer`. Call `setImage` to bind the byte data to texture
3. pass `filament::Texture*` to `ImGui::Image()`
4. click the image, and you will see random `ImGui::Text` become a mess.

**Expected behavior**

**Screenshots**
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/13013579/155358226-fcb4c803-77bd-4190-8a75-15fa0dab5b18.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MAC]
 - Backend: [OpenGL]
 - filament: 1.9.9

**Comment by romainguy** [comment]
What image format did you get from STB and what format did you describe in the filament texture? Images can be displayed with filagui.

**Comment by prideout** [comment]
Ah, I see you're using a very old version of Filament.  We fixed this issue long ago.
