### ISSUE TITLE
Morphing does not work anymore

### ISSUE THREAD

**Issue by AntonHolovin** [google/filament#5289]
**Describe the bug**
I used version `1.17.0` and applied morphing with the `setMorphWeights(i, weights)` method. This version threw some "Fatal signal 11" errors after several calls to `loadModelGlb()` so I updated to the latest one `1.20.1`. Performance is better and I don't see errors but morphing stopped working. Filament ignores `setMorphWeights` calls.  

**To Reproduce**
1. Implement morphing with version `1.17.0`
2. Update to `1.20.1`
3. Change `setMorphWeights(i, weights)` to `setMorphWeights(i, weights, 0)` to have successful compilation 
4. Morphing does not work anymore

**Expected behavior**
Morphing should work like before. 

**Desktop (please complete the following information):**
 - OS: Android
 - Backend: OpenGL

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 11

**Additional context**
I see that there's a new API – `MorphTargetBuffer` but I don't see any example regarding how to use it. All I need is a simple call that lets me morph a blend shape with a given value. `setMorphWeights(i, weights)` worked fine. 

Also, I see that it's possible to enable legacy morphing using `MaterialBuilder` but it's a part of the Filamat and I don't have this dependency.

**Comment by bejado** [comment]
If you're using gltfio it should handle setting up the `MorphTargetBuffer` for you. Can you share the glTF you're trying to load?

FYI you can also enable legacy morphing using the `legacyMorphing` material property.

```
material {
    legacyMorphing : true
}
```

**Comment by AntonHolovin** [comment]
I am trying to render a [VRM (GLB) file](https://www.dropbox.com/s/fgh953pclt4cao3/girl.glb) with `gltfio-android` dependency. `setMorphWeights(entity, weights, 0)` has no effect but the old version of this method worked on `1.17.0`. 

`weights` is a float array of weights for all targets. 

I don't use materials. I just want to apply morphing for a rendered model.

**Comment by bejado** [comment]
Strange, when I load the model into gltf_viewer, it doesn't recognize any morph targets (there should be a 'morphing' checkbox underneath 'receives shadows'). I see the  morph targets with https://gltf-viewer.donmccurdy.com/ and Blender, however. I'll continue investigating.

![Screen Shot 2022-03-07 at 7 17 46 PM](https://user-images.githubusercontent.com/5298046/157160525-243d4019-d738-45c0-8268-4507837e9b82.png)

**Comment by daemyung** [comment]
@AntonHolovin The last parameter of `setMorphWeights` is count. But you sets 0 for morph weight count like this `setMorphWeights(i, weights, 0)`. You need to pass proper count value. For instance `setMorphWeights(i, weights, 4)`.

**Comment by AntonHolovin** [comment]
@daemyung the last parameter is `offset`. I tried `setMorphWeights(i, weights, 0)`, `setMorphWeights(i, weights, 1)`, `setMorphWeights(i, weights, 4)`, `setMorphWeights(i, weights, weights.size)` but morphing does not work.

**Comment by bejado** [comment]
@daemyung I believe @AntonHolovin is using the Java API, where the third argument is an offset:

```
public void setMorphWeights(@EntityInstance int i, @NonNull float[] weights, @IntRange(from = 0) int offset)
```

**Comment by daemyung** [comment]
@AntonHolovin Oh... you are not using c++... then you are right.

**Comment by daemyung** [comment]
@AntonHolovin Please try #5297. I had changed getting the number of morph target before because glTF spec says that all primitives MUST have the same number of morph targets in the same order. So it will be enough just checking the number of morph weight. But in your model file, morph weight count is zero even if each primitive has morph targets.
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/7459074/157365342-4d54d668-ce54-418e-9d12-0960a444c9f6.png">

**Comment by AntonHolovin** [comment]
@daemyung sorry, I cannot build Filament at the moment. Do you have android artifacts (AAR)?

**Comment by romainguy** [comment]
@AntonHolovin The AARs will be available as soon as our post-submit builds finish (in a couple of hours maybe?)

**Comment by AntonHolovin** [comment]
Thanks! Now it works on my side with `setMorphWeights(faceEntity, weights, 0)` call.
