### ISSUE TITLE
How can I get skins in glTF?

### ISSUE THREAD

**Issue by daemyung** [google/filament#5290]
**Is your feature request related to a problem? Please describe.**
I need skins to do the inverse kinematics. However there is no way to get this at `FilamentAsset`.

**Describe the solution you'd like**
Supports getter function for skins at `FilamentAsset`.

**Describe alternatives you've considered**
Actually I only needs the skin name and joints for the inverse kinematics. So supporting skin name and joints gatter function will be enough.

**Comment by daemyung** [comment]
Please let me know your ideas. I will create a PR for this when I hear your thought.

**Comment by prideout** [comment]
Yes I think it's a good idea to add queries for this to FilamentAsset.  I think we are already storing the information you need, look for "SkinVector".

**Comment by prideout** [comment]
Thank you!  Be careful not to expose std::vector, we try not to use STL containers in public API's.  We will probably need two getter methods, one for the count.

**Comment by daemyung** [comment]
@prideout Skin's variables use `std::vector`so I make more getter functions.

**Comment by August1996** [comment]
@daemyung Can it be added to jni as well?thanks.

**Comment by daemyung** [comment]
@August1996 It will be fine because it's an internal bug.

**Comment by daemyung** [comment]
@August1996 Ok I will.

**Comment by August1996** [comment]
> @August1996 Ok I will.


Which version of the skin-related api will support jni? 😊

**Comment by daemyung** [comment]
@August1996 Check #5363 out.
