### ISSUE TITLE
Filament Library error

### ISSUE THREAD

**Issue by xeyalsherif** [google/filament#5292]
E/Filament: Panic
    in filament::MaterialParser *filament::createParser(filament::backend::Backend, const void *, size_t):69
    reason: Material version mismatch. Expected 17 but received 20.
E/Filament:

**Comment by jeanlemotan** [comment]
You updated the library and didn't recreate the binary materials.
Some filament updates require regenerating the materials and this is specified in the release notes like this:
[⚠️ Material breakage].

You just have to regen your materials with matc.

**Comment by xeyalsherif** [comment]
What do you mean by recovery with a matc?

**Comment by jeanlemotan** [comment]
If you have any materials that you generated with matc, you need to regenerate them.

**Comment by romainguy** [comment]
Looks like you are mixing versions of Filament somehow, or you are mixing Filament library versions (gltfio and filament itself for instance) when using SceneView.

**Comment by xeyalsherif** [comment]
What can I do as a solution to this?

**Comment by romainguy** [comment]
Well first we'd have to understand what you are doing to begin with. You should file that bug with the authors of https://github.com/SceneView/sceneform-android

**Comment by xeyalsherif** [comment]
Thank you, I want to watch a video in mp4 format instead of a 3d object on the screen by tracking at the picture
