### ISSUE TITLE
Bone pose not applied if glTF model doesn't have animations

### ISSUE THREAD

**Issue by hybridherbst** [google/filament#5299]
**Describe the bug**
Seems that when a glTF model has bones and those have transformations, those transformations are not applied when the model isn't also animated (e.g. it's only "pushed into pose" through bones).

**To Reproduce**
1. Open https://google.github.io/filament/viewer/
2. Drag in [BendyCylinder.zip](https://github.com/google/filament/files/8216673/BendyCylinder.zip)

**Expected behavior**
![image](https://user-images.githubusercontent.com/2693840/157492154-d47efdfd-a334-4544-a76e-9e275f5f1948.png)
(in modelviewer & babylon sandbox)

**Screenshots**
![image](https://user-images.githubusercontent.com/2693840/157492252-1127ba52-5f0a-434b-8374-83040091ed71.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11, Chrome]
 - GPU: [NVIDIA RTX 2070]

**Comment by prideout** [comment]
Our Android viewer properly calls `updateBoneMatrices` regardless of the presence of animation, but our web and desktop viewers do not.  So, it probably works as expected on Android, although `transformToUnitCube` probably doesn't work as expected.  That's something I need to to think about.

Incidentally this issue has given me merits an API tweak, which I proposed with #5301.
