### ISSUE TITLE
Punctual lights invisible with orthographic cameras

### ISSUE THREAD

**Issue by bejado** [google/filament#5318]
**Describe the bug**
When gltf_viewer loads a glTF file that contains some renderables, a point light, and an orthographic camera, the punctual light is invisible when viewed from the camera. Perspective cameras don't seem to be affected.

**To Reproduce**
1. Build gltf_viewer on main (19b0ad2605e).
2. Load the attached glTF file: [test-ortho-light.glb.zip](https://github.com/google/filament/files/8249159/test-ortho-light.glb.zip)
3. Turn off IBL and Sun.
4. Under Camera, select "Camera_Orientation"
5. Note that the light is no longer visible.

**Desktop (please complete the following information):**
Behavior reproduces on macOS and Windows across both Metal and OpenGL backends.

**Comment by bejado** [comment]
@pixelflinger FYI. I can look into this, but I think it's something to do with froxels.

**Comment by pixelflinger** [comment]
I'll have a look. This stuff breaks constantly :-)
