### ISSUE TITLE
Crash happens when rendering model which optimized by  gltfpack

### ISSUE THREAD

**Issue by August1996** [google/filament#5320]
**Describe the bug**
it is fine when i use gltf_viewer to render [gltfpack_test.glb](https://raw.githubusercontent.com/August1996/filament-bugreport/main/gltfpack_test.glb). 

but crash happens when i render  [gltfpack_test_proceed.glb](https://raw.githubusercontent.com/August1996/filament-bugreport/main/gltfpack_test_proceed.glb)  which optimized by  [gltfpack](https://meshoptimizer.org/gltf/).

**To Reproduce**
use the command to optimize gltf model
`gltfpack  -i gltfpack_test.glb -o gltfpack_test_proceed.glb -cc`

**Expected behavior**
no crash happens

**Desktop (please complete the following information):**
 - OS: Android、Mac

**Comment by bejado** [comment]
The optimized glTF file has an extension that we don't support: `EXT_meshopt_compression`. We should probably print an error message of some sort.

**Comment by August1996** [comment]
> The optimized glTF file has an extension that we don't support: `EXT_meshopt_compression`. We should probably print an error message of some sort.
> 
> Edit: looks like cgltf supports `EXT_meshopt_compression`, maybe we should be too.

i see, i thought filament supports `EXT_meshopt_compression` before because I see the [statement](https://github.com/google/filament/blob/251abf0545b9b4afcc49a21de5620e79a743ddad/third_party/cgltf/README.md) here.

**Comment by August1996** [comment]
> The optimized glTF file has an extension that we don't support: `EXT_meshopt_compression`. We should probably print an error message of some sort.
> 
> Edit: looks like cgltf supports `EXT_meshopt_compression`, maybe we should be too.

Does Filament have any plans to support `EXT_meshopt_compression`?

**Comment by romainguy** [comment]
cgltf only supports it because it parses that extension into a structure. The actual work is left to the app. I'd like to add support for meshopt but it's not a priority right now. We do support Draco compression though.

**Comment by August1996** [comment]
> cgltf only supports it because it parses that extension into a structure. The actual work is left to the app. I'd like to add support for meshopt but it's not a priority right now. We do support Draco compression though.

thanks, i will have a try on Draco compression.
