### ISSUE TITLE
Crash happens when more than 128 morph target are used

### ISSUE THREAD

**Issue by August1996** [google/filament#5327]
**Describe the bug**

the model have 245 morph targets, it renders fine with vesion 1.13.0. but crashs on vesion 1.20.2

the log is as follow:

```
W/Filament: WARNING: Exceeded max morph target count of 128
E/Filament: Panic
   in setTangentsAt:195
   reason: 128 target index must be < 128
E/Filament: --------- beginning of crash
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 30264 (com.demo.k3d), pid 30264 (com.demo.k3d)
```

**Comment by starccode** [comment]
`WARNING: Exceeded max morph target count of 128
Panic
in setTangentsAt:195
reason: 128 target index must be < 128`
-----
got the same crash

**Comment by pixelflinger** [comment]
As the warning indicates we have a limit to 128 targets. This is because we're using 2D arrays to store the data and we need two layers per morph target (position + data). Unfortunately OpenGLES minspec for 2D arrays is 256, so we can't assume more.

**Comment by pixelflinger** [comment]
@daemyung what do you think?

**Comment by starccode** [comment]
<img width="779" alt="企业微信截图_c42fe8b8-b4fb-4c49-a81d-5fce88a548bb" src="https://user-images.githubusercontent.com/17590947/158949893-9ae6b66e-472b-46d3-a108-4b92a1f12d35.png">
As the tag1.19.0 indicated, I thought the limitation is 256 targets. So actually, only 128 targets support.

**Comment by daemyung** [comment]
@pixelflinger Filament can support the number of morph target up to 256. Currently we can bind morph target normal and morph target position separately.

**Comment by daemyung** [comment]
@August1996 Could you share your model file? It's very tricky.

**Comment by August1996** [comment]
> @August1996 Could you share your model file? It's very strange.

[here is the model](https://github.com/August1996/filament-bugreport/raw/main/face_crash.glb)
