### ISSUE TITLE
Rendering frame rate is low with a lot of morph targets

### ISSUE THREAD

**Issue by August1996** [google/filament#5344]
**Describe the bug**
My model has 244 morph targets and the frame rate is very low when rendered with filament, but not with babylon.

At the same time I found that as the number of morph target increases, the filament performance gets worse.

**Comment by August1996** [comment]
such as [this model](https://github.com/August1996/filament-bugreport/blob/main/face_crash.glb)

**Comment by romainguy** [comment]
@prideout Shouldn't performance depend on the number of morph weights only? Do we apply a weight to ALL morph targets? If so that'd explain what the developer is seeing here (that would mean 244 texture fetches). If so can we at least check that we try to avoid reads for weights set to 0?
