### ISSUE TITLE
./build.sh -c -a debug  fail

### ISSUE THREAD

**Issue by Jomes** [google/filament#54]
Building C object CMakeFiles/cmTC_6a6bd.dir/CheckIncludeFile.c.o
FAILED: /usr/bin/cc    -fcolor-diagnostics -o CMakeFiles/cmTC_6a6bd.dir/CheckIncludeFile.c.o   -c /home/jomeslu/filament-master/out/cmake-debug/CMakeFiles/CMakeTmp/CheckIncludeFile.c
cc: error: unrecognized command line option ‘-fcolor-diagnostics’
ninja: build stopped: subcommand failed.

**Comment by Jomes** [comment]
Warning: JAVA_HOME is not set, skipping Java projects
Cleaning build directories...
Building debug in out/cmake-debug...
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /home/jomeslu/Tinybuild/sdk/android/cmake/3.6.3155560/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /home/jomeslu/Tinybuild/sdk/android/cmake/3.6.3155560/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /home/jomeslu/Tinybuild/sdk/android/cmake/3.6.3155560/share/cmake-3.6/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/libgtest/tnt/CMakeLists.txt:26 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by romainguy** [comment]
Thanks for the report. You are compiling with GCC, but we only support clang as per the instructions in the readme. Please switch to clang and file another issue if you run into more problems.
