### ISSUE TITLE
Filament's online demo is no longer working

### ISSUE THREAD

**Issue by cx20** [google/filament#5404]
**Describe the bug**
Filament's suzanne demo cannot be displayed

**To Reproduce**
1. Go to the suzanne demo page
https://google.github.io/filament/webgl/tutorial_suzanne.html

**Expected behavior**
Expected behavior is that Suzanne will be displayed.

**Logs**
reason: Material version mismatch. Expected 15 but received 20.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA GeForce RTX 2060
 - Browser: Chrome 100
 - Backend: WebGL

**Additional context**
Firefox outputs the same warning to the console and the model is not displayed.

**Comment by romainguy** [comment]
Thanks, we probably forgot to regenerate it again. We need to automate this.

**Comment by prideout** [comment]
Partially fixed with #5405 but there are still issues, working on it.  We definitely need to overhaul the web site and make it automated.

**Comment by prideout** [comment]
Should be fixed now, although you might need to refresh your cache.
