### ISSUE TITLE
discard fragment having alpha value greater than threshold

### ISSUE THREAD

**Issue by Sweenall** [google/filament#542]
Fragments can be discarded if alpha value is less than threshold value in .mat file as follows: 
material {
    blending : masked,
    maskThreshold : 0.5
}

Is there any way to discard fragment that has alpha value greater than threshold ?

**Comment by romainguy** [comment]
This can be achieved in the fragment code of the material. You can write something like:

```
if (getMaskThreshold() > baseColor.a) discard;
```

**Comment by Sweenall** [comment]
Thank you so much.. :)
