### ISSUE TITLE
podspec for iOS/macOS filament source dev/debug

### ISSUE THREAD

**Issue by Michael-Lfx** [google/filament#5424]
**Is your feature request related to a problem? Please describe.**
enhancement

**Describe the solution you'd like**
Officially provide a new podspec to support develop and debug filament source code in a Xcode project as "Developing Pod" which can live edit and build in the host app project.

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.](https://github.com/google/filament/discussions/3860) is inefficient because we need to build filament framework in terminal and then copy to host app specified directory and then click Xcode Run button.

**OS and backend**
iOS/macOS specific.

**Comment by romainguy** [comment]
As explained in the link you provided:

> Building Filament from source is more complicated than could be expressed in a Podspec.

Our build system is CMake and you can ask CMake to use its Xcode generator to build Filament from Xcode.
