### ISSUE TITLE
gltf-viewer with vulkan backend segmentation fault when opening a specific model

### ISSUE THREAD

**Issue by EYHN** [google/filament#5432]
**Describe the bug**
gltf-viewer with **vulkan backend** segmentation fault when opening a specific model.
I have tested with release build on macos and windows and both have segmentation fault.

**To Reproduce**
1. run command `gltf_viewer -a vulkan scaniverse-model.glb`

**Expected behavior**
It should render the model as same as using the opengl backend.

**Logs**
Debug Build Output on Windows
```
Assertion failed: allocator && allocation && ppData, file C:\Users\eyhn\rust-filament\filament-bindings\filament\third_party\vkmemalloc\src\vk_mem_alloc.h, line 17226
```

**Desktop:**
 - OS: Windows
 - GPU: NVIDIA GeForce RTX 3080
 - Backend: Vulkan

**Additional context**
file needed to reproduce [scaniverse-model.zip](https://github.com/google/filament/files/8486408/scaniverse-model.zip)

**Comment by pixelflinger** [comment]
@prideout it looks like `VulkanStagePool::acquireStage` returns an invalide `stage`. It looks like `vmaCreateBuffer` fails for some reason.

It looks like there is no allocation failure management here, e.g. a `stage` is returned even if there is a failure. There should at least be some assert I think.

My machine has tons of memory and this seems reproducible, so it's strange the allocation would fail in the first place.

**Comment by prideout** [comment]
Interesting, thanks Mathias, I'll TAL.

**Comment by pixelflinger** [comment]
btw, this seems to fail when allocating a 8K x 8K texture -- maybe there is a limitation in the allocator for texture sizes?

**Comment by prideout** [comment]
Our copy of the VMA lib is from Dec 2019, I believe there have been significant improvements since then, as a follow up I will likely try upgrading it.

**Comment by prideout** [comment]
Correction: we are using a recent VMA but there is a stale comment that indicates otherwise, will fix.  Also we have a workaround that is no longer necessary (https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/178).

**Comment by prideout** [comment]
Correction to correction: we (GitHub) ARE using an old VMA, but Google is using a new VMA.  Sorry for the spam, will fix.
