### ISSUE TITLE
a strange phenomenon when rendering

### ISSUE THREAD

**Issue by August1996** [google/filament#5438]
**Describe the bug**
i load 32 models and play animation, the framerate is very low. but after coming from background, it works well.

**you can refer to this video**
[video](https://raw.githubusercontent.com/August1996/filament-multi-model/main/video.mp4)

**source code**
[filament-multi-model](https://github.com/August1996/filament-multi-model)

**Comment by August1996** [comment]
i found that this method cost much time to compete.
![image](https://user-images.githubusercontent.com/15972489/163567277-9929008e-033c-4212-a89c-affd4d8508a5.png)

and i print the name of node is "Structure Pass".

so there may be some problems in this code

![image](https://user-images.githubusercontent.com/15972489/163567396-83687318-3284-4997-b7e3-73533521efd4.png)

**Comment by romainguy** [comment]
Thoughts: could be a clocking issue, or a driver issue.

**Comment by pixelflinger** [comment]
What platform is this on?

**Comment by August1996** [comment]
my phone is [android 10 xiaomi 9](https://www.gsmarena.com/xiaomi_mi_9-9507.php)

**Comment by August1996** [comment]
may be you can run the project [filament-multi-model](https://github.com/August1996/filament-multi-model), you can increase or decrease the number of model until the framerate declines. and then you switch to background for seconds, after coming from background, the framerate will be normal.

**Comment by pixelflinger** [comment]
@August1996 have you observed this behavior on the emulator?

**Comment by August1996** [comment]
> @August1996 have you observed this behavior on the emulator?

I haven't tried it on the emulator, I'm using a physical machine.

**Comment by pixelflinger** [comment]
how did you determine that "Structure Pass" was taking a lot of time? What tool did you use?

**Comment by August1996** [comment]
> how did you determine that "Structure Pass" was taking a lot of time? What tool did you use?

i add some code to calculate and then compile the sources.

**Comment by pixelflinger** [comment]
we never were able to observe this behavior. Re-open if you still see it.
