### ISSUE TITLE
Use half in metal shader for texture read/write

### ISSUE THREAD

**Issue by Michael-Lfx** [google/filament#5449]
**Is your feature request related to a problem? Please describe.**
Xcode suggest that we should use `half` instead of `float` to reduce ALU cost in some cases such as customize post processing passes or unlit materials. 
I have tried `precision` of `sampler2d ` but doesn't work. The translated MSL is still `texture2d<float>`.

**Describe the solution you'd like**
Maybe we should proper handle the `precision` of `samplerX` or  adding a new property in `samplerX` to indicate we want to use `half` and `float` to sample our texture image data.

**Describe alternatives you've considered**
No.

**OS and backend**
Is this feature OS/backend specific? If so, explain why.
Currently, Metal only.

**Comment by pixelflinger** [comment]
I believe spirvtools don't yet handle this properly.

**Comment by romainguy** [comment]
Indeed, we're waiting for spirv-cross to handle it correctly to support this.

**Comment by pixelflinger** [comment]
No, filament needs to support GLES3.0.

**Comment by bejado** [comment]
I believe spirv-cross does now handle this. It's been on my todo list for awhile to try it out—I'll prioritize it.
