### ISSUE TITLE
Restrict orbit angle for Manipulator

### ISSUE THREAD

**Issue by StevenMOG** [google/filament#5451]
**Is your feature request related to a problem? Please describe.**
I'd like to show a 3D model of a product and let the user orbit around it. As I also added a floor plane to the scene I'd like to prevent the user from orbiting through the floor.

**Describe the solution you'd like**
I'd like to be able to set some kind of minimum angle between the ground plane and the camera when creating the Manipulator instance using its builder.

**Describe alternatives you've considered**
I tried to set the y position of the camera to a positive value after applying the transformation changes from the Manipulator but it makes the orbit weird.

**Comment by Tnation87** [comment]
> CameraManipulator is part of our sample code, it's not a public filament API.

I'm not sure what you mean by it being sample code, but the [Manipulator class](https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java) is part of the Android Utils artifacts, and is directly accessible to anyone who includes the artifact in their project

**Comment by tomriddle25** [comment]
Hi @StevenMOG Were you able to get this working ? 
Any help would be appreciated, I am in a similar pickle.
