### ISSUE TITLE
gltfio (and friends) to support multiple scenes

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#5459]
gltf files can embed multiple scenes and we should handle that somehow.

gltf_viewer, ModelViewer etc, should also do something sensical when multiple scenes are present. Ideally, they would allow do display/hide individual scenes.

**Comment by prideout** [comment]
👍 One way of testing this is Intel Sponza and the merge feature in gltf-pipeline.

**Comment by prideout** [comment]
This was fixed with https://github.com/google/filament/pull/5524
