### ISSUE TITLE
Driver APIs execution immediate

### ISSUE THREAD

**Issue by Michael-Lfx** [google/filament#5475]
**Is your feature request related to a problem? Please describe.**
Currently DriverApis function calls are encoded into Command and then execute in the other thread. It makes debugging difficult.

**Describe the solution you'd like**
It's good to provide a direct/immediate graphics api calling version for debugging purpose.

**Describe alternatives you've considered**
Turn on `DEBUG_MARKER()` but not working as expected.

**OS and backend**
OpenGL (ES).

**Comment by romainguy** [comment]
You can compile filament in single threaded mode for this.
