### ISSUE TITLE
demo hello-pbr cannot work well in iphone 8 plus device

### ISSUE THREAD

**Issue by dandingol03** [google/filament#5485]
**Describe the bug**
the demo `hello-pbr` which use `[[UIScreen mainScreen] nativeBounds]` cannot get the device's width and height correctly, the filament view's size is not equal to the screen size.
**To Reproduce**
1. run demo `hello-pbr` on iphone 8 plus device

**Screenshots**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/13013579/165662660-9a70ec16-dfcf-4d86-b3bd-ac722ce106a0.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. iphone 8 plus]
 - OS: [e.g. ios 14.0.1]

**Comment by bejado** [comment]
@dandingol03 Can you verify that #5488 fixes the issue?

**Comment by dandingol03** [comment]
ok
