### ISSUE TITLE
green flickering and laggy camera stream in android

### ISSUE THREAD

**Issue by appletastesgood** [google/filament#5498]
**Describe the bug**
- same as the following past issues:
  - https://github.com/SceneView/sceneform-android/pull/150
  - https://github.com/SceneView/sceneform-android/issues/148
- Recently, the deprecation of Stream API was conducted in filament, which causes the above past issues to occur again:
  - https://github.com/google/filament/pull/5397

**To Reproduce**
- use following sample to simulate the bug
  - https://github.com/appletastesgood/arcore-filament-example-app
- note that this issue does not arise from old approach for stream rendering:
  - https://github.com/appletastesgood/arcore-filament-example-app/commit/2a8cf158d827aee19e076ec432e80f3eb9c7f7d5

**Expected behavior**
must not invoke green frame flickering

**Screenshots**
![green_frame_flickering](https://user-images.githubusercontent.com/24629696/166179181-348adaff-ad6a-4974-b871-c2bec5705bca.gif)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL, Samsung Galaxy S20 5G
 - OS: Android

**Comment by pixelflinger** [comment]
I think the problem is that you need to call `setCameraTextureNames` on ARCore with enough textures -- probably at least 4., the problem here is that there is only a single texture that is used at the same time for texturing and camera capture.

**Comment by appletastesgood** [comment]
![wow](https://user-images.githubusercontent.com/24629696/166409284-4172fee6-339e-4784-8a34-65a0ccc82bd9.gif)

works like a charm, thanks!

**Comment by khyati18** [comment]
@pixelflinger @romainguy after setting ids to 4 or more I am still getting green screen.

` val cameraTextureIds = IntArray(4) { createExternalTextureId() }
` 
`session.setCameraTextureNames(cameraTextureIds)
`
