### ISSUE TITLE
在构建方面不太适合新手，能否在构建上面在简单点吗

### ISSUE THREAD

**Issue by ly114kuang** [google/filament#5506]
能否在vs2022上面构建

**Comment by bejado** [comment]
Filament should work fine with Visual Studio 2022.

Follow the prerequisites [here](https://github.com/google/filament/blob/main/BUILDING.md#windows), but make sure you have CMake version 3.21 or newer installed. To create the project, run

```
mkdir out
cd out
cmake -G "Visual Studio 17 2022" ..
```

Then open TNT.sln inside Visual Studio 2022.
