### ISSUE TITLE
I want to get inverseBindMatrices to do dynamic bone animation.

### ISSUE THREAD

**Issue by Mrwrichard** [google/filament#5520]
**Is your feature request related to a problem? Please describe.**
I found that #5310 had already retrieved skin name and joints, but I need `inverseBindMatrices` to calculate `boneVector` for dynamic bone such as spring effect. Besides, for multi-instances rendering, I want to get skins at `FilamentInstance`.
![screen](https://user-images.githubusercontent.com/20150323/167102096-254c819f-a38e-4049-9134-f04c37e4480d.gif)

**Describe the solution you'd like**
Add more queries for skin information to `FilamentAsset` and `FilamentInstance`. 

**Describe alternatives you've considered**
`SkinVector` is already in both `FilamentAsset` and `FilamentInstance`, so I think just add functions like #5310 does should be enough. Something like 
```
size_t getMatrixCountAt(size_t skinIndex) const noexcept;

const filament::math::mat4f* getInverseBindMatricesAt(size_t skinIndex) const noexcept;
```

**Comment by prideout** [comment]
This seems like a reasonable request.  I love your gif.

**Comment by Mrwrichard** [comment]
> This seems like a reasonable request. I love your gif.

Thank you, hah. I'll add these functions and submit a pr.

**Comment by prideout** [comment]
@Mrwrichard gentle reminder that we are very open to a PR for this :)
