### ISSUE TITLE
Crashed when load model after destory model

### ISSUE THREAD

**Issue by starccode** [google/filament#5527]
![wecom-temp-45b2fd26107254a2917b3f8585bd405c](https://user-images.githubusercontent.com/17590947/167246208-f1756b6d-5d08-48ff-93b7-fb142cca3a28.png)

Load a glb model, and then destory the model, and load the glb model again. Crash happened when Load the glb model again.

**Comment by starccode** [comment]
The crash can be reproduced at the iOS demo "gltf-viewer"

**Comment by starccode** [comment]
it seems crashed also at OPENGL backend

**Comment by bejado** [comment]
@starccode I'll take a look this week.
