### ISSUE TITLE
turn FILAMENT_DISABLE_MATOPT off cause SSR's rendering result error

### ISSUE THREAD

**Issue by hammerLWA** [google/filament#5528]
when i turn FILAMENT_DISABLE_MATOPT off in cmakelist, i got a error rendering with screen space reflection which is right when i  open FILAMENT_DISABLE_MATOPT. 

**FILAMENT_DISABLE_MATOPT off:**
![1651917717834_CC62ABE8-E838-4d75-9A21-2B85E15F46D2](https://user-images.githubusercontent.com/13552551/167249606-225795b2-9967-47df-84a7-2b49404d5d53.png)

![1651917711364_04C11975-2878-47c8-B648-BCC096A87C38](https://user-images.githubusercontent.com/13552551/167249598-a2c16363-c62c-4f07-89ed-c4fd1597bfd3.png)

**FILAMENT_DISABLE_MATOPT on:**
![1651914957838_E7595B0E-D30F-45b3-A312-09618590E295](https://user-images.githubusercontent.com/13552551/167249582-111a5548-cb50-409b-89d3-97168378ca8e.png)
![1651914966236_663BE91A-E48F-4f7c-9CD5-9E70F42A5A0B](https://user-images.githubusercontent.com/13552551/167249586-85c275a6-83e9-40a1-9a2b-2719356d4091.png)

**Comment by bejado** [comment]
Which backend (OpenGL, Metal, Vulkan) / platform (macOS, Windows, etc) are you using?

**Comment by hammerLWA** [comment]
> Which backend (OpenGL, Metal, Vulkan) / platform (macOS, Windows, etc) are you using?

OpenGL with Nvidia GTX 2600, i found it is a similar case as  [issue](https://github.com/google/filament/issues/3027#issue-689161175. ),  scaleMatrix in light_reflections.fs cause a bad optimization by SPIR-V tool.
    
highp mat4 uvFromViewMatrix =
        scaleMatrix(res.x, res.y) *
        frameUniforms.ssrUvFromViewMatrix;

**Comment by pixelflinger** [comment]
I'm going to assume this is fixed because the spirv matrix assignment issue has been fixed.
