### ISSUE TITLE
Problem with Resource Loader

### ISSUE THREAD

**Issue by danielljc** [google/filament#5553]
**Bug Description**
Bug occurs when loading resources of glTF files.
More narrowly, the PNGs/JPGs linked by glTF files cannot parse to texture by current file system code.

**To Reproduce**
1. Load asset of `glTF` in `gltf_viewer.cpp`.
2. Error occurs when loading resources linked by glTF file. 
> Unable to create texture xxx.png: Unable to parse texture: unknown image type

**Temporary Solution**
Convert `glTF` to `glb` with `gltf-import-export`.

**Screenshots**
![image](https://user-images.githubusercontent.com/3369172/168244848-0bea869c-8136-4d13-8cad-1edf8c83f355.png)

**Possible Bug Fix**
The key of this bug is reading filestream.
Error reveal in Line 658 in `ResourceLoader.cpp`:
```
...
ifstream filest(fullpath);
vector<uint8_t> buffer;
filest.seekg(0, ios::end);
buffer.reserve((size_t) filest.tellg());
filest.seekg(0, ios::beg);
buffer.assign((istreambuf_iterator<char>(filest)), istreambuf_iterator<char>());
if ((texture = provider->pushTexture(buffer.data(), buffer.size(), mime.c_str(), flags))) {
    mFilepathTextureCache[uri] = texture;
}
...
```
Image files should be read in BINARY mode, so we need to add this mode when calling constructor.
`ifstream filest(fullpath, ifstream::in | ios::binary);`

**Desktop:**
 - OS: Windows 10
 - GPU: Intel UHD Graphics 630
 - Backend: OpenGL

**Comment by prideout** [comment]
Thanks!  Strange that I cannot repro but yes we should definitely add `ios::binary`, will fix.

**Comment by romainguy** [comment]
@prideout I've had that issue in the past in another code path and it was also on Windows. Windows seems to care deeply about `binary` being set, whereas Linux/macOS not so much.
