### ISSUE TITLE
Calculating the normal of morph targets looks wrong

### ISSUE THREAD

**Issue by daemyung** [google/filament#5584]
**Describe the bug**

Rendering with morphing looks very strange because of wrong normals. I suspect that calculating morph target's normal in `TangentJob` is incorrect.

**To Reproduce**

1. Download and unzip [normal_test_B.glb.zip](https://github.com/google/filament/files/8747831/normal_test_B.glb.zip)
2. Run gltf_viewer
3. Load normal_test_B.glb
4. Go to Hierarchy > Node > Cube.001 > Click morphing.
5. Change morph weight from 0.0 to 1.0

You can also test it with [normal_test_A.glb.zip](https://github.com/google/filament/files/8747855/normal_test_A.glb.zip)

**Expected behavior**

This video is recored with https://gltf-viewer.donmccurdy.com

https://user-images.githubusercontent.com/7459074/169657236-94abdeb8-668b-4a86-bbea-91203938de11.mov

After sphere morphs to cube, the face of cube looks flat and filament should be rendered like this.

**Screenshots**
This video is recored with filament.

https://user-images.githubusercontent.com/7459074/169657587-86b0a546-2ba7-4994-9fd6-bff98a0f76ba.mov

The face of cube, the face of cube looks not flat.

I had printed world normals. Normals are changed very little.

https://user-images.githubusercontent.com/7459074/169657903-fb04456a-3325-4a71-92bc-8a3dda8d44c3.mov

In this time, I recored with normal_test_A.glb and printed normals. The geometry is changed to sphere but cube is still remained in normals.

https://user-images.githubusercontent.com/7459074/169658054-8603faac-e74e-4fab-96a3-1a704265eeca.mov

**Desktop (please complete the following information):**
 - OS: Momentary 12.3.1
 - GPU: AMD Radeon Pro 5500M 4 GB
 - Backend: Metal

**Comment by prideout** [comment]
This is an excellent bug report.  :)  Is this related to PR #5583?  If so, the PR description should probably be improved.  Thank you for all your help.

**Comment by prideout** [comment]
@daemyung Also, are you already looking into this issue on your end, since you implemented the texture-based morphing stuff?  Just wondering before we take a look.

**Comment by daemyung** [comment]
@prideout PR #5583 is related with this issue but can't solve this issue. Originally calculating morphing normal never been happend and PR #5583 fixes this problem which is don't calculting morphing normal.

I'm digging more about this issue on my side... and uploading and reading of morph target's tangents looks fine. So my last suspection is that `TangentsJob` calculates morph target's tangents correctly. I'm reading and debugging `TangentsJob` but it's hard to me.

**Comment by daemyung** [comment]
@prideout I'm pretty sure that calculating morph target's normal is incorrect. What I have tested is reading morph target's normal from glTF and uploading it to MorphTargetBuffer and read normal in shader without `toTangentFrame`. With these changes, everything looks good. Please look at below a video.

https://user-images.githubusercontent.com/7459074/169945192-e7469cf3-c079-47e7-99a7-8402056ede41.mov

Below video shows the normal.

https://user-images.githubusercontent.com/7459074/169945221-a3518175-a9ea-4b6d-81e6-c19853ced555.mov

**Comment by daemyung** [comment]
@prideout BTW could you explain what's tangent frame exactly?

**Comment by prideout** [comment]
The tangent frame encodes not only the normal but also the binormal, thus it encodes the total surface orientation using only 4 values.  If we stored normals separately, then we'd need at 6 values (3 for normals, 3 for tangents).  Filament needs to know surface orientation in order to correctly handle anisotropic lighting and bump mapping.
