### ISSUE TITLE
Unable to build andoid project

### ISSUE THREAD

**Issue by cingelmarekmt** [google/filament#5591]
Unable to build filament, inside Android Studio.

1. Open Android project: ${FILAMENT_DIR}/andoid
2. Set sample.sample-gltf-viewer
3. Make project
4. Cannot find source file: ${FILAMENT_DIR}/out/android-release/filament/include/gltfio/resources/gltfresources_lite.h

**Logs**
CMake Error at ${FILAMENT_DIR}/filament/android/gltfio-android/CMakeLists.txt:104 (add_library):
Cannot find source file:
${FILAMENT_DIR}/out/android-release/filament/include/gltfio/resources/gltfresources_lite.h
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
.hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - GPU: NVIDIA GTX 980

**Smartphone (please complete the following information):**
 - Device: samsung SM-J730F
 - OS: last version

**Comment by romainguy** [comment]
Please refer to BUILD.md, it explains what you need to build first. Alternatively you can change the build.gradle files to depend on the artifacts published on maven instead of the local ones.
