### ISSUE TITLE
setScissors influences shadows

### ISSUE THREAD

**Issue by kpeeters** [google/filament#5607]
When I do a `setScissors` on all my material instances, the rendering is restricted to the rectangle set there, as expected. However, shadows are truncated in a region which is *smaller* than the rectangle fed to `setScissors`, so that parts of my scene no longer receive shadows. It looks like the scissor test is applied to some aspects of the shadow computations, instead of just preventing pixels from being drawn.

Does this ring any bells? If it doesn't, then I'll try to create a minimal example.

**Comment by pixelflinger** [comment]
yes this is the issue, the scissor is applied from the material instance when we're rendering the shadowmap. There is currently no trivial way to fix this, since this happens in the main rendering loop.

**Comment by pixelflinger** [comment]
@kpeeters could you provide a sample showing the issue?
