### ISSUE TITLE
the repeated multiplication of new by sizeof(FEngine) will lead to an increase in memory

### ISSUE THREAD

**Issue by caorm** [google/filament#5608]
![image](https://user-images.githubusercontent.com/5361593/171006867-f3c14344-df41-4821-8458-d027b614b535.png)

We are currently working on a project with filament to check for memory-related issues. We found that the repeated multiplication of new by sizeof(FEngine) will lead to an increase in memory. You can confirm whether it needs to be modified.

**Comment by pixelflinger** [comment]
Thanks, this is a very good catch!
