### ISSUE TITLE
Missing attribute values in wglCreateContextAttribs parameter

### ISSUE THREAD

**Issue by ennis** [google/filament#5611]
There is no value for the `WGL_CONTEXT_FLAGS_ARB` and `WGL_CONTEXT_PROFILE_MASK_ARB` attributes in the list passed to `wglCreateContextAttribs`:
https://github.com/google/filament/blob/cc51d478f815870ac1953a0790e33f92c0e512b9/filament/backend/src/opengl/platforms/PlatformWGL.cpp#L103-L108

According to https://www.khronos.org/registry/OpenGL/extensions/ARB/WGL_ARB_create_context.txt , `attribList` should be a sequence of <name,value> pairs.

**Comment by bejado** [comment]
@pixelflinger I think we can simply remove line 106. What do you think?
