### ISSUE TITLE
Trying to replicate Helmet Webgl.

### ISSUE THREAD

**Issue by cgraider** [google/filament#5634]
I cannot reproduce the Helmet example . 
which i get this error : 
Uncaught (in promise) TypeError: engine.createIblFromKtx1 is not a function
    at new App (helmet.html:46:49)
    at helmet.html:36:18
    at taskFinished (filament.js:78:17)
    at filament.js:102:9

**To Reproduce**
After cloning whole filament projects. i ran virtual server to view Helmet sample. helmet sample didnt have filamentjs + wasm and other resources so i copied them from the main files.

**Comment by romainguy** [comment]
@prideout Is this a tutorial or something we need to update with the new APIs?

**Comment by prideout** [comment]
It looks to me like the helmet example _is_ up to date, however the filamentjs + wasm that you're using is old, not sure where you got them from.
