### ISSUE TITLE
how to visualize skeleton animation from mixamo fbx?

### ISSUE THREAD

**Issue by jinfagang** [google/filament#5649]
how to visualize skeleton animation from mixamo fbx?

**Comment by bejado** [comment]
@jinfagang FYI you can import a mixamo fbx into Blender, then output a glTF file which should be compatible with our gltfio loader library.

**Comment by jinfagang** [comment]
@bejado Hi, thanks for the info.

I saw that filament using assimp as model file reader, why not add fbx directly support?
