### ISSUE TITLE
gltfio: support morphing for models with sparse accessors

### ISSUE THREAD

**Issue by prideout** [google/filament#5651]
Our recent [fix](https://github.com/google/filament/pull/5630) for non-packed morph data would be insufficient for models that have sparse accessors.  This is important but not urgent since neither the Blender exporter nor gltf-transform support sparse encoding:

https://github.com/donmccurdy/glTF-Transform/issues/351

Moreover, the glTF samples repo does not have sparsely morphed models that we could test with:

https://github.com/KhronosGroup/glTF-Sample-Models/issues/355

**Comment by rbsheth** [comment]
If it is helpful, you could pull a test avatar from our API and it will have sparse morph targets: https://bitmoji.api.snapchat.com/bitmoji-for-games/test_avatar?lod=0

**Comment by prideout** [comment]
Thanks that model indeed provokes the functionality, thank you!  Yay Snap.  :)
