### ISSUE TITLE
What is the minimum android version that filament supports？

### ISSUE THREAD

**Issue by caorm** [google/filament#5667]
I also have the same crash：

https://github.com/google/filament/issues/5426

the official model in the apk is fine，the crash info for sample-gltf-viewer which i replace my model.

thank you！

**Comment by romainguy** [comment]
Filament supports Android 21+.

**Comment by pixelflinger** [comment]
duplicate of #5426

**Comment by caorm** [comment]
> Filament supports Android 21+.

hello

the crash info for the official sample-gltf-viewer demo

vivo X9s Plus
OS: Android 7.1.1
Pixel: 1920x1080
Display: 5.87

2022/6/13 14:32:4914577F*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2022/6/13 14:32:4914577FBuild fingerprint: 'vivo/PD1635/PD1635:7.1.1/NMF26F/compil10251828:user/release-keys'
2022/6/13 14:32:4914577FRevision: '0'
2022/6/13 14:32:4914577FABI: 'arm64
'2022/6/13 14:32:4914577Fpid: 14527, tid: 14548, name: FEngine::loop >>> com.google.android.filament.gltf <<<
2022/6/13 14:32:49 14577 F signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x44
2022/6/13 14:32:49 14577 F x0 0000000000000bd0 x1 0000007f68ddeb40 x2 0000000000000001 x3 0000007f6411f000
2022/6/13 14:32:49 14577 F x4 0000000000000000 x5 0000007f77433000 x6 0000000000000000 x7 0000000000000004
2022/6/13 14:32:49 14577 F x8 0000000000000000 x9 0000000000000004 x10 0000000000000001 x11 0000007f64bb0a50
2022/6/13 14:32:49 14577 F x12 0000000000000000 x13 0000007f557b96a0 x14 0000000000000000 x15 0000000000000020
2022/6/13 14:32:49 14577 F x16 0000000000000030 x17 0000000000000038 x18 000000000000ffff x19 0000000000000010
2022/6/13 14:32:49 14577 F x20 0000007f77901800 x21 0000000000000001 x22 0000000000000000 x23 0000000000000000
2022/6/13 14:32:49 14577 F x24 0000007f68ddeb40 x25 0000000000000000 x26 0000000000000000 x27 0000000000000847
2022/6/13 14:32:49 14577 F x28 0000000000000001 x29 0000007f67307870 x30 0000007f77292894
2022/6/13 14:32:49 14577 F sp 0000007f67307870 pc 0000007f772a3a58 pstate 0000000060000000
2022/6/13 14:32:49 14577 F backtrace:
2022/6/13 14:32:49 14577 F x0 0000000000000bd0 x1 0000007f68ddeb40 x2 0000000000000001 x3 0000007f6411f000
2022/6/13 14:32:49 14577 F x4 0000000000000000 x5 0000007f77433000 x6 0000000000000000 x7 0000000000000004
2022/6/13 14:32:49 14577 F x8 0000000000000000 x9 0000000000000004 x10 0000000000000001 x11 0000007f64bb0a50
2022/6/13 14:32:49 14577 F x12 0000000000000000 x13 0000007f557b96a0 x14 0000000000000000 x15 0000000000000020
2022/6/13 14:32:4914577 F x16 0000000000000030 x17 0000000000000038 x18 000000000000ffff x19 0000000000000010
2022/6/13 14:32:4914577 F x20 0000007f77901800 x21 0000000000000001 x22 0000000000000000 x23 0000000000000000
2022/6/13 14:32:4914577 F x24 0000007f68ddeb40 x25 0000000000000000 x26 0000000000000000 x27 0000000000000847
2022/6/13 14:32:4914577 F x28 0000000000000001 x29 0000007f67307870 x30 0000007f77292894
2022/6/13 14:32:4914577 F sp 0000007f67307870 pc 0000007f772a3a58 pstate 0000000060000000
2022/6/13 14:32:4914577Fbacktrace:
2022/6/13 14:32:4914577F#00 pc 00000000001eaa58 /system/vendor/lib64/egl/libGLESv2_adreno.so (_ZN9EsxGfxMem15UpdateTimestampEPK10EsxContext13EsxAccessTypeP20EsxBucketIdReference+472)
2022/6/13 14:32:4914577F#01 pc 00000000001d9890 /system/vendor/lib64/egl/libGLESv2_adreno.so (_ZN9EsxCmdMgr16GfxMemReferencedEP9EsxGfxMem13EsxAccessType+48)
2022/6/13 14:32:4914577F#02 pc 00000000002cfd3c /system/vendor/lib64/egl/libGLESv2_adreno.so (_ZNK10A5xProgram25GenerateShaderCBSlotStateEP10A5xContext13EsxCmdBufType23EsxCompiledHwShaderTypejP20A5xShaderCBSlotState+1084)
2022/6/13 14:32:49 14577 F https://github.com/google/filament/pull/3 pc 00000000002cda08 /system/vendor/lib64/egl/libGLESv2_adreno.so (_ZN11A5xPipeline13WriteUboStateEP10A5xContext13EsxCmdBufType23EsxCompiledHwShaderTypejP14A5xStateBuffer+168)
2022/6/13 14:32:49 14577 F https://github.com/google/filament/issues/4 pc 00000000002f2664 /system/vendor/lib64/egl/libGLESv2_adreno.so (_ZN10A5xContext13ValidateStateEPK17EsxDrawDescriptor+2148)
2022/6/13 14:32:49 14577 F https://github.com/google/filament/pull/5 pc 00000000002f2d30 /system/vendor/lib64/egl/libGLESv2_adreno.so (_ZN10A5xContext18HwValidateGfxStateEPK17EsxDrawDescriptor+16)
2022/6/13 14:32:49 14577 F https://github.com/google/filament/pull/6 pc 00000000001364a0 /system/vendor/lib64/egl/libGLESv2_adreno.so (_ZN10EsxContext16ValidateGfxStateEPK17EsxDrawDescriptor+768)
2022/6/13 14:32:49 14577 F https://github.com/google/filament/pull/7 pc 0000000000128bdc /system/vendor/lib64/egl/libGLESv2_adreno.so (_ZN10EsxContext21DrawElementsInstancedE11EsxPrimTypej10EsxPixTypePKvji+444)
2022/6/13 14:32:49 14577 F https://github.com/google/filament/issues/8 pc 0000000000100118 /system/vendor/lib64/egl/libGLESv2_adreno.so (glDrawRangeElements+88)
2022/6/13 14:32:49 14577 F https://github.com/google/filament/pull/9 pc 0000000000115d38 /data/app/com.google.android.filament.gltf-1/lib/arm64/libfilament-jni.so
2022/6/13 14:32:49 4030 E vivo-add txpackets:39535 , tx_failed:31 , , tx_retry:6929 , rx_packets:2724063
2022/6/13 14:32:50 511 E Error writing /proc/14527/oom_score_adj; errno=
222022/6/13 14:32:50 2562 E Open /sys/touchscreen/app_name failed
2022/6/13 14:32:50 4441 E monitor view is null, no need to update fullscreen
2022/6/13 14:32:51 5514 E Unable to decode stream: java.io.FileNotFoundException: /oem/etc/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_cloudy.png (No such file or directory)
2022/6/13 14:32:51 5514 E Unable to decode stream: java.io.FileNotFoundException: /oem/etc/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_degree.png (No such file or directory)
2022/6/13 14:32:51 5514 E Unable to decode stream: java.io.FileNotFoundException: /oem/etc/theme/icons/dynamic_icon/com.vivo.weather/res/drawable-sw360dp-xxhdpi/dynamic_weather_minus.png (No such file or directory)
2022/6/13 14:32:52 4030 E vivo-add txpackets:39535 , tx_failed:31 , , tx_retry:6929 , rx_packets:27240632022/6/13 14:32:554577EgetConfigForPhoneId subId is invalid
