### ISSUE TITLE
How to control the display and hide of FilamentInstance, or to control rendering or not rendering

### ISSUE THREAD

**Issue by fuchao** [google/filament#5682]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
   I need to render a lot of FilamentInstance dynamically, sometimes according to the data to render or not to render a 
 FilamentInstance, how can I control their state, thank you.
**Describe the solution you'd like**
  
**Describe alternatives you've considered**
Can dynamically control rendering and not rendering a FilamentInstance
**OS and backend**
Is this feature OS/backend specific? If so, explain why.
Use on Android platform

**Comment by romainguy** [comment]
Please don't file issues for questions, use the Discussions tab instead.
