### ISSUE TITLE
Synchronization of 3D scene state and camera frames in ARCore

### ISSUE THREAD

**Issue by grassydragon** [google/filament#5683]
We are now trying to solve this issue:

> The positioning issue might come from ARCore latest version

It turns out that this is an issue with synchronization of the 3D scene state and camera frames.

Synchronization in the Filament `Stream` with an external texture was handled automatically by making a texture copy that corresponds to the frame being rendered: https://github.com/google/filament/blob/dab02e915e9ec0bc8dfe4436debcdd6e420c9f75/android/filament-android/src/main/java/com/google/android/filament/Stream.java#L69

However, when using multiple textures with ARCore how can we know when we can advance the texture index? The `FrameCompletedCallback` works only for Metal: https://github.com/google/filament/blob/347642985f7a796303c97602010b981975a40516/android/filament-android/src/main/java/com/google/android/filament/SwapChain.java#L121

Currently, we are selecting the next texture before scheduling each frame for rendering (calling the `Renderer.render()` method): https://github.com/SceneView/sceneview-android/blob/f00bcf5d04edc2977c42e36968c02aabda31b4bd/arsceneview/src/main/java/io/github/sceneview/ar/camera/ArCameraStream.kt#L254

_Originally posted by @grassydragon in https://github.com/google/filament/issues/5577#issuecomment-1153081356_

**Comment by bejado** [comment]
> However, when using multiple textures with ARCore how can we know when we can advance the texture index?

I don't think you need to manage the texture index yourself. Have you looked into [`ArFrame.getCameraTextureName`](https://developers.google.com/ar/reference/c/group/ar-frame#arframe_getcameratexturename)?

**Comment by grassydragon** [comment]
> I don't think you need to manage the texture index yourself. Have you looked into [`ArFrame.getCameraTextureName`](https://developers.google.com/ar/reference/c/group/ar-frame#arframe_getcameratexturename)?

That solves the synchronization issue :tada: Thank you for the hint!

**Comment by ThomasGorisse** [comment]
https://user-images.githubusercontent.com/6597529/174429924-113461a8-0b35-4122-b0b1-dce47f81f456.mp4
