### ISSUE TITLE
Build & installing filamentapp

### ISSUE THREAD

**Issue by sanghoon** [google/filament#5695]
**Is your feature request related to a problem? Please describe.**

I've built some demos for my project with FilamentApp.
I do understand that it's for your sample apps basically,
but it seems to be a good starting point for quick demos.

However, I found it's a bit inconvenient to keep the full codes of Filament and re-build them for the demos.

**Describe the solution you'd like**

I'd like to add an option flag in CMakeListst.txt.
If the flag is ON, FilamentApp library will be installed as well (along with its dependencies such as filagui, libsdl2, ...)
and then one can implement their own samples with pre-built libs and headers only.

I'm currently working on the solution for internal use.
https://github.com/google/filament/compare/main...sanghoon:feature/filamentapp

**Comment by romainguy** [comment]
The `filamentapp` library is nowhere near ready to become a public library, and probably not the kind of library we would like to provide since it mandates the use of specific libraries (SDL2 vs GLFW vs <insert whatever else>).
