### ISSUE TITLE
cmake or pkg info?

### ISSUE THREAD

**Issue by jiapei-nexera** [google/filament#5702]
**Is your feature request related to a problem? Please describe.**
I just had **filament-1.23.2** successfully built under Ubuntu 22.04. But, it seems it's just installed without **registration** ?? 
`ilament_DIR                     filament_DIR-NOTFOUND`

**Describe the solution you'd like**
`filament.pc` or `cmake` folder about `filament` info should be generated and copied into the system ?

**Describe alternatives you've considered**
`filament.pc` or `cmake` folder about `filament` info should be generated and copied into the system ?

**OS and backend**
Ubuntu 22.04 + clang-14

**Comment by romainguy** [comment]
How did you install Filament? Our `build.sh` script only ever installs locally in `out/filament` to not pollute the host system. You are however free to set your own `CMAKE_INSTALL_PREFIX` if you invoke CMake manually. We do not provide support for `pkg-config`, so we don't provide a .pc file.

**Comment by jiapei-nexera** [comment]
Hi, @romainguy 

I invoked `cmake` since you provided a `CMakeLists.txt`. And it seems only the static libraries are able to be built out.
What I mean is, **normally**, there is **cmake** folder while I install any other packages, which seems to register the package itself into Ubuntu, for instance: (otherwise, there is a corresponding package_name.pc). 

```console
➜  fmt pwd
/usr/local/lib/cmake/fmt
➜  fmt ll
total 16K
-rw-r--r-- 1 root root  999 Jun 10 11:02 fmt-config.cmake
-rw-r--r-- 1 root root 2.0K Jun 10 11:02 fmt-config-version.cmake
-rw-r--r-- 1 root root 3.9K Jun 15 15:26 fmt-targets.cmake
-rw-r--r-- 1 root root  799 Jun 15 15:26 fmt-targets-release.cmake
```


If there is **NO** such **cmake** or **.pc**, some times, when a package depends on **filament**, it would be inconvenient to find **filament** out....

**Comment by andre-caldas** [comment]
This was closed as "completed". **It is surely not completed.** Maybe it should be closed as "will not implement"... "not planed"... whatever.

The library is, for example, distributed by Debian. It is a shame there is no `.pc` file for it.

> [...] not pollute the host system.

An installed library is not pollution. There would be no shared libraries if library developers all had this mind set.

Even though filament does provide a `build.sh`, the decision on where to install should be given to the user, IMO. Also, not everybody uses `cmake`, and a `.pc` file is the easiest way to make the library available to any build system.

I hope this decision can be reverted... :-)

**Comment by andre-caldas** [comment]
Sorry... please, ignore my previous comment. I have tried to delete it, but it is "locked".
