### ISSUE TITLE
No Windows build for v1.23.2

### ISSUE THREAD

**Issue by Bartvhelvert** [google/filament#5719]
Looking at Github releases, it seems like there is no Windows build for [v1.23.2](https://github.com/google/filament/releases/tag/v1.23.2).

**Comment by bejado** [comment]
Sorry about that, we ran into some issues with the Windows build this week but I just kicked off a new build that should finish within a few hours.

**Comment by Bartvhelvert** [comment]
Looks like it is there now, thanks!
