### ISSUE TITLE
I have an Issue Building the Filament Repository in Android Studio

### ISSUE THREAD

**Issue by Tomlp14** [google/filament#5723]
**Describe the bug**
After I cloned https://github.com/google/filament.git in my Android studio, it gives me an error every time I try to build gtlfio-android. These are the the project errors:

 CMake Error at /Users/tomas/AndroidStudioProjects/06.Filament/android/gltfio-android/CMakeLists.txt:109 (add_library):
Cannot find source file:
/Users/tomas/AndroidStudioProjects/06.Filament/out/android-release/filament/include/gltfio/materials/uberarchive.h
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
.hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
CMake Error at /Users/tomas/AndroidStudioProjects/06.Filament/android/gltfio-android/CMakeLists.txt:109 (add_library):
No SOURCES given to target: gltfio-jni
CMake Generate step failed.  Build files cannot be regenerated correctly.
**Expected behavior**
It supposes to run.

**Screenshots**

![Screen Shot 2022-06-21 at 12 17 00 PM](https://user-images.githubusercontent.com/8157591/174880265-dad07848-7fb7-4a93-8c15-1e100f665c03.png)
![Screen Shot 2022-06-21 at 12 16 52 PM](https://user-images.githubusercontent.com/8157591/174880316-f1596af7-0339-43b1-9c15-7b97fabbba30.png)

**Desktop (please complete the following information):**
 - OS: iOS Monterey
 - GPU: Intel UHD Graphics 630 1536 MB

**Comment by romainguy** [comment]
Please follow the instructions in BUILDING.md. You first need to build Filament itself before building the Android modules.
