### ISSUE TITLE
Alpha Value Not Working Properly In Scenefrom GLB file

### ISSUE THREAD

**Issue by arun4fms** [google/filament#5736]
am using sceneform with modelrenderable where GLB is loaded from an external URL. I tried to change the opacity of the GLB with the given below method, but there is no change in alpha or opacity.

private void addHighlightToNode(Node node, ModelRenderable andyRenderablee) {
        MaterialInstance[] materialInstances = filamentAsset.getMaterialInstances();

        TextureSampler textureSampler = new TextureSampler();
        for(MaterialInstance materialInstance: materialInstances){
                    materialInstance.setParameter("baseColorFactor", Colors.RgbaType.SRGB, 0.0f,0.0f,0.0f,0.0f);
       }

**Comment by arun4fms** [comment]
@romainguy  Please do have a look into this. I just saw your few comments regarding blending mode but for materialInstances I haven't seen any option to set Bleningmode

**Comment by romainguy** [comment]
You need your gltf material to be defined as alpha blended. You can't override this at runtime after loading the gltf. You can however provide an override during loading.

**Comment by arun4fms** [comment]
@romainguy  how can i provide an override during loading
