### ISSUE TITLE
【Windows】some demo cannot be rendered correctly on windows

### ISSUE THREAD

**Issue by dandingol03** [google/filament#5737]
**Describe the bug**
I run some demos on windows. `suzanne` and `hellopbr` are  rendered incorrectly, but `gltf-viewer` and `hello triangle` are rendered correctly. I can't figure out why,  so i come here for some help. The version of filament is 1.23.2

**Screenshots**
![)97MW1D926P}SQ_B N (WLQ](https://user-images.githubusercontent.com/13013579/175823806-1f2bd36a-fd69-4e70-8a42-6de2793e0a96.png)

**Logs**
FEngine (64 bits) created at 0000020C3966AD60 (threading is enabled)
FEngine resolved backend: OpenGL
[Intel], [Intel(R) UHD Graphics 620], [4.1.0 - Build 27.20.100.9126], [4.10 - Build 27.20.100.9126]
Active workarounds:
vao_doesnt_store_element_array_buffer_binding
allow_read_only_ancillary_feedback_loop
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_RENDERBUFFER_SIZE = 16384
GL_MAX_SAMPLES = 16
GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = 16.000000
GL_MAX_UNIFORM_BLOCK_SIZE = 65536
GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 16
OS version: 0
CreateFile() Error: 5
CreateFile() Error: 5
Requested linear format but KTX contains a sRGB format.
Requested linear format but KTX contains a sRGB format.
Resolved format for albedo: SRGB8_A8
Resolved format for ambient occlusion: RGBA8
Resolved format for metallic: RGBA8
Resolved format for roughness: RGBA8

**Desktop (please complete the following information):**
 - OS: [Windows]
 - GPU: [Intel UHD Graphics 620]
 - Backend: [OpenGL]

**Comment by bejado** [comment]
I'm able to run both `suzanne` and `hellopbr` samples fine at the latest main with an Nvidia 3080. I'm wondering if this is an Intel GPU specific issue.

**Comment by mundak** [comment]
I can also confirm it happens on integrated Intel graphics.

**Comment by bejado** [comment]
This must also be specific to Windows, as I'm able to run the suzanne demo fine on my MacBook Pro even after forcing the integrated Intel GPU (Intel(R) UHD Graphics 630).
