### ISSUE TITLE
TPanic crash

### ISSUE THREAD

**Issue by starccode** [google/filament#5738]
![截屏2022-06-27 15 09 51](https://user-images.githubusercontent.com/17590947/175880400-e687aab5-3d42-459b-b3af-ce7400c1b7f6.png)

Above is the crashed thread stack and info which crash at FEngine::Loop. Is there clue the crash happen?

the crash happened:
![截屏2022-06-27 15 15 47](https://user-images.githubusercontent.com/17590947/175881457-bd57ed10-54a1-4a2b-9d46-e5ad0d28ad38.png)
![截屏2022-06-27 15 16 14](https://user-images.githubusercontent.com/17590947/175881540-74ab910e-353e-49c7-895c-4960d14c46d3.png)

**Comment by starccode** [comment]
![image](https://user-images.githubusercontent.com/17590947/175889335-6102e64f-5593-4c16-a9ed-8f1f684fad4f.png)
is the crash happened here?

**Comment by starccode** [comment]
![image](https://user-images.githubusercontent.com/17590947/175889416-70809900-f6bd-44a0-b0db-5348f8ffa289.png)
I checked the possible panic at FEngine::Loop，is the crash happened here？

**Comment by prideout** [comment]
Our panic macros emit messages, is it possible for you to obtain more complete log output?

**Comment by starccode** [comment]
yes, I've tried to print the emit messages to our app log, but I've found that sometimes it didn't invoke the panic function.
![截屏2022-06-30 10 53 17](https://user-images.githubusercontent.com/17590947/176582806-73d66d20-f3d5-419a-b264-01d7e79347ac.png)
If all panic will invoke the e.log()?

**Comment by bejado** [comment]
@starccode Are you able to show us the full log output of your program when it crashes?

**Comment by starccode** [comment]
> @starccode Are you able to show us the full log output of your program when it crashes?

no problem, I'm trying to collect the crash log, I will show the log as soon as I get them~

**Comment by starccode** [comment]
Recently, I've collected some TPanic crash macro output log, here it is:
1. Panic
in MetalTexture:474
reason: Could not create Metal texture. Out of memory?
2.Panic
in acquireDrawable:145
reason: Could not obtain drawable.

for the first crash log, I've checked the memory info log when crash happend, and it seems not "Out of memory".

**Comment by bejado** [comment]
Internally, Filament calls Metal API methods on a separate thread which is not set up to report asynchronous failures. If `newTextureWithDescriptor` is returning `nil`, then your app is most likely running out of memory. You could experiment with reducing the amount of texture allocations and/or their size/pixel format to reduce memory pressure. You could also see if iOS is sending your app [low memory warnings](https://developer.apple.com/documentation/xcode/responding-to-low-memory-warnings) and respond accordingly.

Closing for now, but feel free to reopen if you suspect there's a bug in Filament.
