### ISSUE TITLE
Faced with a problem "HandleAllocator arena is full, using slower system heap"

### ISSUE THREAD

**Issue by xarlammm** [google/filament#5758]
Everything worked great until I loaded a relatively heavy model. The 
"E/Filament: in allocateHandleSlow:82
    reason: HandleAllocator arena is full, using slower system heap. Please increase the appropriate constant (e.g. FILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB).
E/Filament: 
A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7776435000 in tid 13032 (ugmentedreality), pid 13032 (ugmentedreality)" 
error occurs with the loadGlb() function. What to do in such a situation? I'm adding the package to build.gradle. Using 3D Viewer on android.

**Comment by xarlammm** [comment]
1. Лог - [log.txt](https://github.com/google/filament/files/9070304/log.txt)
2. Xiaomi 11T ( Android 12, Miui 13.0.2)
3. Модель - [room.zip](https://github.com/google/filament/files/9070386/room.zip)

**Comment by pixelflinger** [comment]
Ah, the problem is actually this message:

```
E/Filament: Panic
    in flush:88
    reason: Backend CommandStream overflow. Commands are corrupted and unrecoverable.
    Please increase FILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB (currently 1 MiB).
    Space used at this time: 4761104 bytes
```

The model is just too big. We have a pending change that will allow you to configure this buffer at runtime -- however, I would strongly recommend to fix your model. These are mobile devices with limited resources, you shouldn't use models with so many draw calls. You need to use a library that optimizes your model geometry.

**Comment by pixelflinger** [comment]
I did a test incrementing FILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB from 1 to 3, and FILAMENT_RENDER_PASS_SIZE_IN_MB from 3 to 4 as well as FILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB from 2 to 3, and the model was displayed. It has over 600 draw calls.

**Comment by xarlammm** [comment]
Thank you for the answer, which library can you recommend for optimizing the glb model. It is desirable that it was under Android
