### ISSUE TITLE
Is there any reason why MeshAssimp loades textures only for gltf meshes? 

### ISSUE THREAD

**Issue by SC5Shout** [google/filament#5770]
**Is your feature request related to a problem? Please describe.**
I'd like to load a .fbx mesh with textures using the MeshAssimp class. Looking into the code it looks like only the `MeshAssimp::processGLTFMaterial` function processes `base map`, `normal map`, etc. Is there any reason why? Or do I miss something?

**Describe the solution you'd like**
`MeshAssimp` class to load a mesh texture assets also for (example) the FBX format.

**Describe alternatives you've considered**
none

**OS and backend**
none

**Comment by romainguy** [comment]
MeshAssimp is not a public API and only exists to support our samples. You could however start from it to add full support for FBX
