### ISSUE TITLE
Cloth sample - how to run?

### ISSUE THREAD

**Issue by cvetan5** [google/filament#580]
Hello, 

I'm trying to run sample_cloth on Linux by running:
`./sample_cloth -i ./envs/office assets/models/cloth/cloth.obj` and I don't see the model being loaded into the scene, along with warnings about missing textures.

Am I doing something wrong?

**Comment by prideout** [comment]
When we overhaul our samples, we should consider using resgen to embed textures and meshes to avoid issues like this.

**Comment by romainguy** [comment]
Maybe, depends on what the sample is trying to achieve.
