### ISSUE TITLE
createMaterialInstance is really slow

### ISSUE THREAD

**Issue by maudzung** [google/filament#5803]
Hello,

I'm using the Filament lib for 3D rendering in my application. I can render the 3D objects. However, the running time is quite slow.
I have tried to profile the program to find the bottleneck.
I have observed the step:

```C++
// filamat::MaterialBuilder builder = filamat::MaterialBuilder()...
...
...
...
filamat::Package const pkg {builder.build(engine->getJobSystem())};
```
takes 3-4 seconds on my mobile phone. This results in a slow rendering application.
How can I speed up my rendering application?

**OS and backend**
- Android device Samsung A22

**Comment by romainguy** [comment]
How are you creating materials? Are you using pre-compiled materials or are you assembling the material at runtime? If the latter, then this is more or less expected as this requires generating all the shader permutations, running a validator/optimizer, etc.

**Comment by maudzung** [comment]
Thanks for your quick response.
Do you mean that if I use pre-compiled materials, the above step `filamat::Package const pkg {builder.build(engine->getJobSystem())};` will be faster?

Can you please guide me more on pre-compiled materials? Are there any examples for it?
Thank you.

**Comment by romainguy** [comment]
Could you please show how you create your materials in your code?

**Comment by maudzung** [comment]
Hi @romainguy 

Please help me take a look at the below code:

```C++
filamat::MaterialBuilder builder = filamat::MaterialBuilder()
        .name(key_name.c_str())
        .targetApi(filamat::MaterialBuilder::TargetApi::OPENGL)
        .platform(filamat::MaterialBuilder::Platform::MOBILE)

        #ifndef NDEBUG
        .optimization(filamat::MaterialBuilderBase::Optimization::NONE)
        .generateDebugInfo(true)
        #endif

        .material(shader.value.c_str())
        .multiBounceAmbientOcclusion(true)
        .specularAmbientOcclusion(filamat::MaterialBuilder::SpecularAmbientOcclusion::BENT_NORMALS)
        .shading(filamat::MaterialBuilder::Shading::LIT);

if (shader.hasUV) {
    builder.require(filamat::MaterialBuilder::VertexAttribute::UV0);
}

for (auto& map: texMap) {
    if (map.enabled) {
        builder.parameter(filamat::MaterialBuilder::SamplerType::SAMPLER_2D, map.parameterName);
    }
}

filamat::Package const pkg {builder.build(m_engine->getJobSystem())};
filament::Material* const material{filament::Material::Builder().package(pkg.getData(), pkg.getSize()).build(*m_engine)};
filament::MaterialInstance* materialInstance{material->createInstance()};
```

Thank you so much.

**Comment by romainguy** [comment]
Yeah so that generates, compiles, optimizes, etc. the material at runtime which can be quite expensive. A more efficient way is to write a .mat file and compile it with our matc compiler. Then you can load the compiled file at runtime. All the samples in the directory android/samples use this solution.

Example of .mat file:

https://github.com/google/filament/blob/main/android/samples/sample-textured-object/src/main/materials/textured_pbr.mat

Example of loading the file:

https://github.com/google/filament/blob/9cc7fe97c5f3503e21e8d53249c540e90bdbd539/android/samples/sample-textured-object/src/main/java/com/google/android/filament/textured/MainActivity.kt#L194

**Comment by romainguy** [comment]
Here is an example in C++:

https://github.com/google/filament/blob/9cc7fe97c5f3503e21e8d53249c540e90bdbd539/samples/image_viewer.cpp#L168

(The compiled material in this case is included directly in the executable but you can also read it from a file)

**Comment by maudzung** [comment]
Thank you so much. I'll refer to the examples.
