### ISSUE TITLE
JS Bindings: IndirectLight.Builder() needs to be exposed

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#5805]
Currently, the only way to create an IndirectLight is with the **engine.createIblFromKtx1()** method.  We would like to be able to also create them using SH values.

Please expose a binding for IndirectLight.Builder() so we can create IndirectLights without the use of a cubemap.

**OS and backend**
JavaScript

**Comment by prideout** [comment]
This is already exposed as `IndirectLight$Builder` and the method you want is `irradianceSh`:

https://github.com/google/filament/blob/main/web/filament-js/filament.d.ts#L441

**Comment by BStringhamVRSK** [comment]
@prideout 
Maybe I'm doing this incorrectly, but IndirectLight doesn't follow the pattern of the other Builders.  For example, `ColorGrading` has this:

export class ColorGrading {
    `public static Builder(): ColorGrading$Builder;`
}

But, IndirectLight has no static Builder() function.
I get run-time errors if I try to use the new operator to create one:
**BindingError: IndirectLight$Builder has no accessible constructor**

      var light = new IndirectLight$Builder()
          .irradianceSh(9, harmonics)
          .build(engine);

If I try this syntax, I get this compiler error:
**error TS2339: Build:Property 'irradianceSh' does not exist on type 'typeof IndirectLight$Builder'**

      var light = IndirectLight$Builder
          .irradianceSh(9, harmonics)
          .build(engine);


I'm **expecting** to do this, but `Builder()` doesn't exist:

      var light = IndirectLight.Builder()
          .irradianceSh(9, harmonics)
          .build(engine);

**Comment by prideout** [comment]
It shouldn't be inaccessible, reopening.

**Comment by prideout** [comment]
Wait...apoligies.  @BStringhamVRSK your expectations are correct, this totally works for me:

```
    this.ibl = Filament.IndirectLight.Builder()
            .irradianceSh(3, [120000.0, 115200.0, 114000.0])
            .build(engine);
```

I just now tried adding this into the parquet demo and it worked.

( You should not access the constructor directly as I previously indicated. )

**Comment by prideout** [comment]
Note: I need to amend the TypeScript file since it's basically our best "documentation" right now.

**Comment by BStringhamVRSK** [comment]
Thanks!  I don't know why I didn't just try that.  I will give it a shot.

**Comment by BStringhamVRSK** [comment]
I think the reason it doesn't work for me is because I'm building from a .ts file, not .js.
I see you've added a commit with the fix, so I'll wait for that to release and I should be good.
Thanks for your help.
