### ISSUE TITLE
GNU or CLANG ??

### ISSUE THREAD

**Issue by jiapei100** [google/filament#5808]
My ENV:

```
OS: Ubuntu 22.04
CLANG: Ubuntu clang version 14.0.6-++20220622053133+f28c006a5895-1~exp1~20220622173215.107
GCC: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
```

It looks **filament** **ONLY** allows **CLANG** to build.

Around line 140 of [ashmem.cpp](https://github.com/google/filament/blob/main/libs/utils/src/ashmem.cpp), **mkstemp**.

1. I can **ONLY** find **mkstemp** in file `/usr/include/stdlib.h` - the **GNU header**.

2. There is **NO** definition of **mkstemp** in file `/usr/lib/llvm-14/include/c++/v1/stdlib.h` - the **CLANG header**, even under the entire folder `/usr/lib/llvm-14/include/c++/v1` by **grep**.

Noticed there is line 16:  `#include_next <stdlib.h>` in **CLANG** header `/usr/lib/llvm-14/include/c++/v1/stdlib.h` , but clearly, there is **NO** definition of **mkstemp** .

How did you guys manage to compile with **mkstemp**  ??

**Comment by pixelflinger** [comment]
can you see if it fixes to include ` <unistd.h>`?
