### ISSUE TITLE
expression must have class type but it has type "void"

### ISSUE THREAD

**Issue by jiapei100** [google/filament#5826]
[StbProvider.cpp](https://github.com/google/filament/blob/main/libs/gltfio/src/StbProvider.cpp)
line 112:

```c++
TextureInfo* info = mTextures.emplace_back(new TextureInfo).get();
```

I got the following **ERROR** message:

```console
expression must have class type but it has type "void"
```

**Comment by romainguy** [comment]
You are running into many compilation issues that have never surfaced in any of our compilation targets (Windows, Linux, macOS, iOS and Android). There is clearly a problem with your compilation setup but I unfortunately can't help you much since we don't use Ubuntu 22.
