### ISSUE TITLE
Add support for CommonJS packaging

### ISSUE THREAD

**Issue by woldie** [google/filament#583]
I'm on web and I'm trying to use Filament via the npm filament@1.0.0 package.  

I'm bundling filament.js with the rest of my code using webpack.  I'm running into headwinds trying to get Filament init'ed ...  

For starters, I don't have any assets to load, I am just trying to Filament.init with an empty assets array.

    Filament.init([], () => {
        this.filament = Filament.Engine.create(this.canvas);
        this.scene = this.filament.createScene();
        this.camera = this.filament.createCamera();
        const eye = [ 0, 0, 4], center = [ 0, 0, 0 ], up = [ 0, 1, 0 ];
        this.camera.lookAt(eye, center, up);

        console.log("GOT HERE!");  // never gets here
      });

Filament does call my callback, but Filament.Engine is undefined and my code does not continue.  I see some interesting warnings in my logs as well.

    14:27:21.347 wasm streaming compile failed: TypeError: Filament.Engine is undefined filament.js:6:20487
    14:27:21.347 falling back to ArrayBuffer instantiation

Looking through filament.js, I think there may be a race condition with the streaming WASM loading and the code expects a little delay created by assets being loaded.  I see these warnings on both Firefox and Chrome.  (This was a bad assumption on my part, keep reading ...)

So ... I got triangle.filamesh from one of the demos and added that to the assets array.

    Filament.init([ "assets/triangle.filamesh" ], () => {
        this.filament = Filament.Engine.create(this.canvas);
        ....
    });

I see triangle.filamat gets loaded in the Network console, and there are no "wasm streaming compile failed" messages, but I still get an error that Filament.Engine is undefined.  This happens on Firefox and Chrome.

Comparing npm's filament@1.0.0 bundle with what's on the samples on prideout.net, I see differences in filament.js especially around the Filament.Engine definition.  Please push a patch release update to npm containing the latest good filament.js and filament.wasm?  

Also, is gl-matrix-min important to running filament?  It might be nice to give me a way to supply that to filament, or maybe you could fork it and put a copy into filament directly?

[burned the rest of my day in the debugger at this point ...]

Ok, I think I'm getting a handle on what's going wrong.

At the top of my javascript module, I imported filament as such:

    import * as Filament from './filament';

And it seems that that creates some shadow root object or object proxy that runs afoul of Filament.init.  I kept seeing Filament.remainingInitializationTasks starting at 0 rather than 1 when I imported filament this way, and that was causing the Filament.Engine setup routine to be skipped.

I don't think you should be mutating the Filament object.  It would be better to have the filament module be stateless and have Filament.init construct and return the initialized Filament wasm+JS functions package.  Maybe you'd consider making this change to the API?

When I changed my filament import to the following, I finally saw my call to Filament.Engine.create() succeed.  (Whew!)

    let Filament = require('./filament');

With this change I found it was okay to have an empty assets array as well in Filament.init.

**Comment by romainguy** [comment]
Thank you for this detailed report. It seems we should take a closer look at what's going on. `glm-matrix` is optional.

**Comment by prideout** [comment]
We don't support the `import` workflow at the moment (which is why the tutorials don't use it), but it should be possible to do so, I'll look into it.

gl-matrix is not required for using FIlament.

**Comment by woldie** [comment]
super, thanks

**Comment by prideout** [comment]
I wrote a simple no-assets demo with import statements and webpack; it seems to work with the latest Filament.

I'm adding the demo to `web/samples` in #590.  Note however that we need to publish a new version of Filament to npm, which we will do soon.

**Comment by woldie** [comment]
@prideout Hi thanks for the rapid turnaround on this.

I see the new 1.1.0 version of filament on NPM, and I made an attempt to upgrade my code to point to it.  1.1.0 is not working for me, no errors in the logs, it just doesn't display my model.  I'm just going to go back to the copy of the libraries I originally downloaded from prideout.net for now.

Just for my information, am I expected to recompile my .filamesh and .filamat files every time you upgrade filament.js/filament.wasm?  I figured the binary layouts of those files could be very sensitive unless you're doing some forwards-compatible cleverness with protobufs for your binary serialization.  I did not recompile my .filamesh and .filamat files when I upgraded to 1.1.0.

If you will be expecting me to recompile my .filamesh and .filamat files to match the version of filament.js/filament.wasm, could you print a version mismatch error to the logs as appropriate?  Also,  may I suggest you post version-locked copies of all the filament-related file format generator tools to npm or some other distribution engine?  It's going to be too fiddly to have to download the exact versions needed for the sources for those tools to exactly match filament.js/filament.wasm.  

My first stumbling runs with filament are showing really impressive rendering performance.  Thanks again for Filament!

**Comment by prideout** [comment]
You don't need to recompile your filamesh files.  In general you *do* need to recompile your filamat files whenever we change Filament's middle version number, as described in the [versioning doc](https://github.com/google/filament/blob/master/filament/docs/Versioning.md).

You can get version-locked versions of the tools from Filament's [releases](https://github.com/google/filament/releases) page.  The releases that have vX.Y.Z style version numbers match with the releases that we publish to npm.

Does our new [webpack sample](https://github.com/google/filament/tree/master/web/samples/webpack) work for you?  It doesn't draw anything, it simply animates the background color.  I made it very simple in order to test the "zero assets" usage of `init` that you mentioned earlier.

**Comment by woldie** [comment]
@prideout the new webpack sample does work, I saw fadey, pulsey background color changes.

I will recompile my .filamat file and see if the 1.1.0 library on NPM works for me.

**Comment by woldie** [comment]
@prideout  I'm running webpack 4.8.3 and your webpack sample runs webpack 4.0, not sure if that has any bearing on my continuing issues using the copy of filament downloaded from npm.  I think there is some proxification going on with Getters or something that are making importing from node_modules different than including filament from my src folder.  

For whatever reason, (and I'm tired of chasing this down because it's $%^&* infuriating), that `remainingInitializationTasks` variable you are pre-setting to 1 near Filament.init is still showing 0 at the time I call Filament.init.  There's somehow a difference between the javascript object that webpack is constructing and the one it serves up to my import statement.  If you can't eliminate that `remainingInitializationTasks` state, could you at least have it initialize to 0 rather than 1 so it will just work for me?  :-D  God, how I hate how fiddly this stuff is....

**Comment by prideout** [comment]
I wonder if something in your project is causing `filament.js` to be executed twice.  Note that you can either use a `<script>` tag to execute filament.js (like the tutorials do) or you can use import (like the webpack sample does), but you cannot do both.  Can you point me to your project, or attach it as a zip?

**Comment by woldie** [comment]
Could be.  I'll just debug it on my local and make a PR for you when I get a free minute.
