### ISSUE TITLE
with constructor not allowed in anonymous aggregate

### ISSUE THREAD

**Issue by jiapei100** [google/filament#5854]
The **final** lib [filament](https://github.com/google/filament/tree/main/filament) to be built, 

A lot of **ERROR** messages

```console
......
....../filament/filament/src/fg/FrameGraphRenderPass.h:40:49: error: member ‘filament::FrameGraphId<filament::FrameGraphTexture> filament::FrameGraphRenderPass::Attachments::<unnamed union>::<unnamed struct>::depth’ with constructor not allowed in anonymous aggregate
   40 |                 FrameGraphId<FrameGraphTexture> depth;
      |                                                 ^~~~~
....../filament/filament/src/fg/FrameGraphRenderPass.h:41:49: error: member ‘filament::FrameGraphId<filament::FrameGraphTexture> filament::FrameGraphRenderPass::Attachments::<unnamed union>::<unnamed struct>::stencil’ with constructor not allowed in anonymous aggregate
   41 |                 FrameGraphId<FrameGraphTexture> stencil;
      |                                                 ^~~~~~~
......
```

Looks like **Line 40~41** of file [FrameGraphRenderPass.h](https://github.com/google/filament/blob/main/filament/src/fg/FrameGraphRenderPass.h#L40-L41)

**depth** and **stencil** needs to be initialised with some parameter...

**Comment by pixelflinger** [comment]
You're again the only person to have these issues, which also don't make sense.

Please take all these issues to the discussions, maybe someone in the community can help.

**Comment by jiapei100** [comment]
@pixelflinger 

Doublechecked... For **clang**, it built .... For **gcc**, the **ERROR**s are reported...
