### ISSUE TITLE
How to blend 2 different materials?

### ISSUE THREAD

**Issue by maudzung** [google/filament#5856]
Hi authors,

I can render 2 objects separately. Each object has its image textures and its mask (weighted from 0 to 1).
In the .mat file, I define as below:

```
material {
    name : BlendingSample,
    parameters : [
        {
            type : sampler2d,
            name : albedo
        },
        {
            type : sampler2d,
            name : mask
        }
    ],
    requires : [
        uv0
    ],
    shadingModel : unlit
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        float weight = texture(materialParams_mask, getUV0()).r;
        material.baseColor.rgb = texture(materialParams_albedo, getUV0()).rgb * weight;
    }
}

```

Can you please guide me on how to blend them with their weights?
Thank you so much!

**Comment by romainguy** [comment]
Please use discussions for questions like this.

**Comment by maudzung** [comment]
Ok @romainguy 
I posted my question [here](https://github.com/google/filament/discussions/5865)
Could you please guide me on it?
Thank you very much!
