### ISSUE TITLE
C/C++ style Struct and union initialization MIXED UP

### ISSUE THREAD

**Issue by jiapei100** [google/filament#5858]
1. According to [IBM Initialization of structures and unions](https://www.ibm.com/docs/en/zos/2.1.0?topic=initializers-initialization-structures-unions)
the C-style initialization of structures and unions should be **ONLY** in  **C** files, you **CAN'T** mix up using it in **CPP** files.

2. According to [cppreference Struct and union initialization](https://en.cppreference.com/w/c/language/struct_initialization), I tested with **CPP** and **C** style respectively, if named as **.c** file, the following piece of code builds. Otherwise, if named as **.cpp**file, the following code failed to build.

```C
#include <stdio.h>
typedef struct { int k; int l; int a[2]; } T;
typedef struct { int i;  T t; } S;
T x = {.l = 43, .k = 42, .a[1] = 19, .a[0] = 18 };
 // x initialized to {42, 43, {18, 19} }
int main(void)
{
    S l = { 1,          // initializes l.i to 1
           .t = x,      // initializes l.t to {42, 43, {18, 19} }
           .t.l = 41,   // changes l.t to {42, 41, {18, 19} }
           .t.a[1] = 17 // changes l.t to {42, 41, {18, 17} }
          };
    [printf](http://en.cppreference.com/w/c/io/fprintf)("l.t.k is %d\n", l.t.k); // .t = x sets l.t.k to 42 explicitly
                                    // .t.l = 41 would zero out l.t.k implicitly
}
```

3. For instance, **line 148~150** of file [PostProcessManager.cpp](https://github.com/google/filament/blob/main/filament/src/PostProcessManager.cpp#L147-L149)

Can you please give  me some suggestions?

Thank you

**Comment by jiapei100** [comment]
Looks there is an answer on [StackOverflow](https://stackoverflow.com/questions/11516657/c-structure-initialization) ??

**Comment by romainguy** [comment]
It's a C++20 feature supported by clang and msvc.

**Comment by jiapei100** [comment]
@romainguy 


Great... it seems there is a little progress... But, I still have that isse:

Take a look at line 40~42 of [FrameGraphRenderPass.h](https://github.com/google/filament/blob/main/filament/src/fg/FrameGraphRenderPass.h#L40-L42)


```console
In file included from ....../filament/src/fg/details/Resource.h:22,
                 from ....../filament/src/fg/Resource.cpp:17:
....../filament/src/fg/FrameGraphRenderPass.h:40:49: error: member ‘filament::FrameGraphId<filament::FrameGraphTexture> filament::FrameGraphRenderPass::Attachments::<unnamed union>::<unnamed struct>::depth’ with constructor not allowed in anonymous aggregate
   40 |                 FrameGraphId<FrameGraphTexture> depth;
      |                                                 ^~~~~
....../filament/src/fg/FrameGraphRenderPass.h:41:49: error: member ‘filament::FrameGraphId<filament::FrameGraphTexture> filament::FrameGraphRenderPass::Attachments::<unnamed union>::<unnamed struct>::stencil’ with constructor not allowed in anonymous aggregate
   41 |                 FrameGraphId<FrameGraphTexture> stencil;
```

**Comment by jiapei100** [comment]
It looks problem goes on??

1. For instance: **Line 145~148** of file [RendererUtils.cpp](https://github.com/google/filament/blob/main/filament/src/RendererUtils.cpp#L145-148)
```console
RendererUtils.cpp:145:42: error: no matching function for call to ‘filament::FrameGraph::Builder::declareRenderPass(const char [18], <brace-enclosed initializer list>)’
  145 |                 builder.declareRenderPass("Color Pass Target", {
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
  146 |                         .attachments = { .color = { data.color, data.output }, .depth = data.depth },
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  147 |                         .samples = config.msaa,
      |                         ~~~~~~~~~~~~~~~~~~~~~~~
  148 |                         .clearFlags = clearColorFlags | clearDepthFlags });
```

**Comment by jiapei100** [comment]
> It's a C++20 feature supported by clang and msvc.

Yeah... After having it activated, and use **CLANG**, it builds...
