### ISSUE TITLE
Windows OpenGL: Skybox cubemap fails to load on some machines

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#5872]
**Description**
One of our skybox cubemaps is failing on a couple of Windows machines.  When attempting to load, it generates this error:
`OpenGL error 0x500 (GL_INVALID_ENUM) in "createTextureR" at line 598`

As a result, those machines show a black skybox.
The error line apparently is in OpenGLDriver.cpp, line 598.  I have tried to get better detailed information, but the failing machines are not development machines, and I can't get any better debug information, unfortunately.

I suspect that some drivers may be sensitive to a specific combination of parameters being sent, causing the error.  Interestingly, one of the machines has run our software both as a Windows app and as a Web app.  The Web app shows the skybox (Chrome / ANGLE / DirectX backend, I believe?), but the Windows app gets a black background.

**System Info**
We've identified 3 machines that have the problem:
1.  An older MS Surface tablet running Windows 8
2. An older Mac Pro running Windows via Boot Camp.
3. A newer custom-built home machine with an AMD processor.  (Windows 10, I think)

**Additional Context**
- The skybox was built with **cmgen** from version 1.21.2
- It is in **KTX** format
- Compression format: **RGBA_ASTC_6x6**
- Cubemap is created using the **Ktx1Bundle** constructor
- The MS Surface tablet returns TRUE for both: 
        Texture::isTextureFormatSupported(engine, filament::Texture::InternalFormat::RGBA_ASTC_6x6) and
        Texture::isTextureSwizzleSupported(engine)

**Desktop (please complete the following information):**
 - OS: Windows 8 and 10
 - GPU: Windows 8 MS Surface tablet using Intel HD Graphics 5000 -- unsure of specifics on other systems
 - Backend: OpenGL

**Comment by pixelflinger** [comment]
I think it is likely that these machines don't support ASTC and that we don't detect support correctly.
In fact I quickly checked our code and AFAICT it's but checking for ASTC in the isSupported call.


Do you have a fallback for when ASTC is not supported?

**Comment by BStringhamVRSK** [comment]
We don't currently have a fallback.
However, on at least one of the machines, the Web version of the software works, and it uses the same ASTC skybox file that is failing when it runs the Windows/OpenGL version.  In that case, at least, the hardware supports it, but perhaps the OpenGL drivers are unhappy with it.

I will add a fallback option, but I need a way to detect the problem so I can use it :)
