### ISSUE TITLE
VSM shadow error on first frame

### ISSUE THREAD

**Issue by zbai-sc** [google/filament#5874]
**Describe the bug**
VSM shadows are not rendered correctly on first frame (subsequent frames work without issues).

**To Reproduce**
1. set up a scene with VSM shadows
2. capture the first frame

**Screenshots**
![test1](https://user-images.githubusercontent.com/75686421/182528389-24108c28-2ff7-4551-9916-3d6fb2d248fc.png)
First frame with VSM shadow error.

![test2](https://user-images.githubusercontent.com/75686421/182528407-7d357c2c-ee5d-420d-9065-444362d44b46.png)
Second frame without issue.

**Desktop (please complete the following information):**
 - OS: Linux/Ubuntu
 - GPU: NVIDIA RTX
 - Backend: OpenGL

**Additional context**
I tracked down the issue to this commit [cleaner handling of shadow related uniforms](https://github.com/google/filament/commit/be5b60f8951148a38d2e08d111e187596794a4a3#diff-a79b379500737b4817362d62c4de4b429cd97c7c6058c1eda4a9d7d03aaf5270)

It appears `view.prepareShadowMap()` inside `prepareShadowPass` happens after `view.commitUniforms(driver)` and this caused `vsmExponent` to not be set properly for the first frame

Adding `view.prepareShadowMap()` right before `view.commitUniforms(driver)` would be a quick fix for this.

BTW, do we really need `PerViewUniforms::prepareShadowMapping()` anymore? it's only setting `vsmExponent` which is actually hard-coded.

**Comment by pixelflinger** [comment]
@zbai-sc I believe you, but I don't understand yet how this can be happening. The `prepareShadowMap` pass is clearly executed before the `ShadowMap` pass which is where `view.commitUniforms(driver)` is called.

**Comment by pixelflinger** [comment]
@zbai-sc so if you revert just `ShadowMapManager.cpp` that solves your issue?
