### ISSUE TITLE
 error: invalid type argument of unary ‘*’ (have ‘int’)

### ISSUE THREAD

**Issue by jiapei100** [google/filament#5875]
Is this a bug??

**Line 70** of file [Engine.h](https://github.com/google/filament/blob/main/filament/include/filament/Engine.h#L70)

```console
filament/filament/include/filament/Engine.h:70:89: error: invalid type argument of unary ‘*’ (have ‘int’)
   70 | #    define FILAMENT_COMMAND_BUFFER_SIZE_IN_MB (FILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB * 3)
```

Can you please confirm?  I've already enabled **-std=c++20** .

**Comment by romainguy** [comment]
* is not a unary operator here, it looks like you are somehow missing the definition of FILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB
