### ISSUE TITLE
filagui's CMakeLists.txt won't build in variables in generated/resources/filagui_resouces.h

### ISSUE THREAD

**Issue by jiapei-nexera** [google/filament#5882]
Anyway, everything else built... Only except **viewer**.

```console
/usr/bin/ld: /usr/local/filament/lib/libfilagui.so: undefined reference to `FILAGUI_RESOURCES_PACKAGE'
/usr/bin/ld: /usr/local/filament/lib/libfilagui.so: undefined reference to `FILAGUI_RESOURCES_UIBLIT_OFFSET'
/usr/bin/ld: /usr/local/filament/lib/libfilagui.so: undefined reference to `FILAGUI_RESOURCES_UIBLIT_SIZE'
```

It seems the problem is from [filagui CMakeLists.txt](https://github.com/google/filament/blob/main/libs/filagui/CMakeLists.txt) .
Since all definitions are defined in the generated header `....../filament/libs/filagui/build/generated/resources/filagui_resources.h` , it seems to me: [filagui CMakeLists.txt](https://github.com/google/filament/blob/main/libs/filagui/CMakeLists.txt) does **NOT** build the generated header `....../filament/libs/filagui/build/generated/resources/filagui_resources.h` into the library **libfilagui.so** ...

Unlike [matdbg](https://github.com/google/filament/issues/5880), in [matdbg's CMakeLists.txt](https://github.com/google/filament/blob/main/libs/matdbg/CMakeLists.txt), it can generate a static resource library **libmatdbg_resources.a**, which seems have defined those resource variables, such as: **MATDBG_RESOURCES_PACKAGE** . This [filagui CMakeLists.txt](https://github.com/google/filament/blob/main/libs/filagui/CMakeLists.txt) does NOT have such a mechenism ...

**Comment by jiapei100** [comment]
Alright, **ALL** passed..

```console
➜  build git:(main) ✗ ./test_settings 
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from ViewSettingsTest
[ RUN      ] ViewSettingsTest.JsonTestDefaults
[       OK ] ViewSettingsTest.JsonTestDefaults (0 ms)
[ RUN      ] ViewSettingsTest.JsonTestSerialization
[       OK ] ViewSettingsTest.JsonTestSerialization (0 ms)
[ RUN      ] ViewSettingsTest.JsonTestMaterial
[       OK ] ViewSettingsTest.JsonTestMaterial (0 ms)
[ RUN      ] ViewSettingsTest.CustomAutomationSpec
[       OK ] ViewSettingsTest.CustomAutomationSpec (0 ms)
[----------] 4 tests from ViewSettingsTest (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 4 tests.
```

I have to build a static resource `filagui_resources.a`, for shared library `filagui.so` to use...
