### ISSUE TITLE
Crash   ASSERT_POSTCONDITION(!multisampled, "Multisampled cubemap faces not supported.");

### ISSUE THREAD

**Issue by ztb1122334455** [google/filament#5893]
Describe 

Hi, I checked the source code and found that it is unlikely to trigger the appeal issue, why is there this crash, Thanks

 crash info

0 libsystem_kernel.dylib 0x1bb82cbbc 0x1bb826000 + 27580
1 libsystem_c.dylib 0x18b58c6ac 0x18b56d000 + 128684
2 0x108453a9c utils::PostconditionPanic::PostconditionPanic(char const*, char const*, int, std::__1::basic_string, std::__1::allocator >) + 63273628 (Panic.h:405)
3 0x1083c2934 filament::backend::MetalTexture::MetalTexture(filament::backend::MetalContext&, filament::backend::SamplerType, unsigned char, filament::backend::TextureFormat, unsigned char, unsigned int, unsigned int, unsigned int, filament::backend::TextureUsage, filament::backend::TextureSwizzle, filament::backend::TextureSwizzle, filament::backend::TextureSwizzle, filament::backend::TextureSwizzle) + 62679348 (MetalHandles.mm:477)
4 0x1083c2e7c filament::backend::MetalTexture::MetalTexture(filament::backend::MetalContext&, filament::backend::SamplerType, unsigned char, filament::backend::TextureFormat, unsigned char, unsigned int, unsigned int, unsigned int, filament::backend::TextureUsage, filament::backend::TextureSwizzle, filament::backend::TextureSwizzle, filament::backend::TextureSwizzle, filament::backend::TextureSwizzle) + 62680700 (MetalHandles.mm:525)
5 0x1083b4944 filament::backend::ConcreteDispatcher::createTexture(filament::backend::Driver&, filament::backend::CommandBase*, long*) + 62622020 (DriverAPI.inc:182)
6 0x1083ad2e8 std::__1::__function::__func, void ()>::operator()() + 62591720 (functional:1732)
7 0x1083b9f20 filament::backend::MetalDriver::execute(std::__1::function const&) + 62644000 (MetalDriver.mm:167)
8 0x1083ad054 filament::backend::CommandStream::execute(void*) + 62591060 (CommandStream.cpp:86)
9 0x1083fd660 filament::FEngine::loop() + 62920288 (Engine.cpp:603)
10 0x1083ffea0 void* std::__1::__thread_proxy >, int (filament::FEngine::*)(), filament::FEngine*> >(void*) + 62930592 (thread:299)
11 libsystem_pthread.dylib 0x1dc335348 0x1dc332000 + 13128
12 libsystem_pthread.dylib 0x1dc333948 0x1dc332000 + 6472

iphone 10
15.6

**Comment by bejado** [comment]
Can you give more information on how to reproduce the issue? Are you running one of our sample apps?

Multisampled cubemaps aren't supported by graphics APIs. If Filament is trying to create one, then that would certainly be an issue on our end.

**Comment by bejado** [comment]
Closing for now, feel free to reopen with more information.
