### ISSUE TITLE
gltf_viewer flickers on Metal when changing window size

### ISSUE THREAD

**Issue by bejado** [google/filament#5897]
**Describe the bug**
Flickering inside of gltf_viewer when resizing the window with the Metal backend.

**To Reproduce**
1. Run `gltf_viewer --api metal`
2. Resize the window until the model starts to flicker.

Bisected, issue started with 646dfa8b70235e9c242fe9e4c523f712ca78a388.

https://user-images.githubusercontent.com/5298046/183358193-f350563a-5f98-4df0-8180-504e128edfa9.mov

**Comment by pixelflinger** [comment]
can't seem to reproduce.

**Comment by pixelflinger** [comment]
It's reproducible on the macbook main display (not external). Seems to be related to rendering time.
