### ISSUE TITLE
Issue with Renderer::setClearOptions call

### ISSUE THREAD

**Issue by Pankaj003** [google/filament#5898]
Hi @romainguy, @bejado 

I am facing one strange issue. I am trying to set background color of the 3D object by following calls:

    Renderer::ClearOptions::clearColor = filament::math::float4({ color[0], color[1], color[2], color.alpha });
    Renderer::ClearOptions.ClearOptions().clear = true;
    Renderer::setClearOptions(Renderer::ClearOptions);
	
The issue is, the color which I am selecting is not getting applied but some shade of it.
for example: if I chose rgb(142, 177, 85) then on checking the Window color using color picker tool I am getting value rgb(208, 213, 178).
The color can be verified by small color image on the color selection dialog.

Interesting part is, if I query  Renderer::ClearOptions::clearColor object then it shows rgb(142, 177, 85), the original intended color.

Looks like while rendering, the color is getting diluted, may be due to lighting setting or something else.

Is there a way I can either get to apply the intended color or can get the changed color value from some filament api?
This I am facing on both Windows and Mac OS.

Please check attached screen shot.

Thanks

![ColorIssue](https://user-images.githubusercontent.com/8086656/183398843-5159dcc9-b9ab-4ed2-9e47-ec1b41230bce.PNG)

**Comment by Pankaj003** [comment]
Also facing issues related to color bleeding while rendering
![ColorBleed](https://user-images.githubusercontent.com/8086656/183615032-7ca3da92-9d61-489a-90b6-0c2f0e9f305a.PNG)

Please suggest something for both the problems.

Thanks

**Comment by romainguy** [comment]
That's not color bleeding, that looks like Fresnel combined with anti-aliasing.

**Comment by Pankaj003** [comment]
@romainguy 
Hi Romain,

Thanks for looking into this, I am actually passing the linear color, below is the exact implementation in my code

void setBackgroundColor(const QColor& color)
{
    filament::LinearColor linearCorr = filament::Color::toLinear<filament::ACCURATE>({ color.redF(), color.greenF(), color.blueF() });
    RenderingEngine::Get().ClearOptions().clearColor = filament::math::float4({ linearCorr [0], linearCorr [1], linearCorr [2], color.alphaF() });
    RenderingEngine::Get().ClearOptions().clear = true;
    RenderingEngine::Get().Renderer()->setClearOptions(RenderingEngine::Get().ClearOptions());
}

I am converting rgb to linear and then passing to clearColor.
Also how can I un-tonemap the background color?

Thanks

**Comment by Pankaj003** [comment]
@romainguy
Hi Romain, any suggestion regarding this?

Thanks
