### ISSUE TITLE
Reset changed 3D model to its original state

### ISSUE THREAD

**Issue by whereisnothing** [google/filament#5914]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There's a common demand:First we load a 3D glb model,then we change some parts of the model to other materials or textures,and   at last we can reset all changes to the 3D model to the original state of the 3D model,that is,at last we can show an equal 3D model to when we first load it.
Could you please implement this api? We strongly appreciate it.

**Describe alternatives you've considered**

**OS and backend**

**Comment by whereisnothing** [comment]
Have found solution.

**Comment by rameshphilips** [comment]
@whereisnothing could you post the solution?
