### ISSUE TITLE
Dynamic resolution draws vertexDomain:device materials slightly incorrect

### ISSUE THREAD

**Issue by kpeeters** [google/filament#5917]
Somewhere between v1.21.3 and v1.22.0 a change was introduced which leads to weird behaviour with dynamic resolution. It all looks ok when I keep it on one setting, but when I switch between on/off from one frame to the next, materials which have their `vertexDomain` set to `device` jump a bit (or rather, they seem to get scaled slightly from the bottom-left, so the effect is more visible in the top & right). The frames with dynres on are the ones which are slightly incorrect.

By scanning the commits that went into v1.22.0 I suspect it was introduced with 657c25146342331aa31c1bdf7ac49a6a2bb139cf (e.g. some padding which is computed incorrectly) but I haven't yet had time to dig further.

**Comment by pixelflinger** [comment]
Can you share a sample that shows the problem?

**Comment by kpeeters** [comment]
I don't have anything small and isolated right now unfortunately :-(

**Comment by pixelflinger** [comment]
Ah yes, you're right the code above won't work because it requires the projection matrix to be applied, which `vertexDomain:device` skips.

Would you be able to test something for me?  Could you tell me if `TAA` works with your application using `vertexDomain:device`? I expect it wouldn't work because `TAA` also uses the projection to offset things.

**Comment by kpeeters** [comment]
I think your analysis is correct: with 1.22.0, dynamic resolution untouched from the default, but TAA turned on, I get weird redraw artifacts on the parts which are drawn with `vertexDomain:device` materials (e.g. after moving a quad from one position to another, it takes many frames for it to look normal again).

**Comment by pixelflinger** [comment]
@kpeeters would you be able to test this one and let us know? https://github.com/google/filament/pull/5925

**Comment by kpeeters** [comment]
Almost. It works fine now if I do not do anything in the vertex shader. However, I also have a vertex block of the form (stripped off the non-essential bits):

    vertex {
        void materialVertex(inout MaterialVertexInputs material) {
            material.clipSpaceTransform[0][0]=materialParams.zoom;
            material.clipSpaceTransform[1][1]=materialParams.zoom;
            material.clipSpaceTransform[3][0]=materialParams.pan.x;
            material.clipSpaceTransform[3][1]=materialParams.pan.y;        
        }
    }

As soon as `materialParams.zoom!=1` or `materialParams.pan!=(0,0)`, this gives the same type of weird rendering issue I had before. Should I do zoom/pan on `vertexDomain:device` materials in a different way now?

**Comment by pixelflinger** [comment]
I was afraid of that. Could you try this patch:

```
diff --git a/shaders/src/main.vs b/shaders/src/main.vs
index ddf6abeab..9c43ce600 100644
--- a/shaders/src/main.vs
+++ b/shaders/src/main.vs
@@ -152,8 +152,6 @@ void main() {
 #if defined(VERTEX_DOMAIN_DEVICE)
     // The other vertex domains are handled in initMaterialVertex()->computeWorldPosition()
     gl_Position = getPosition();
-    // Apply the clip-space transform which is normally part of the projection
-    gl_Position.xy = gl_Position.xy * frameUniforms.clipTransform.xy + (gl_Position.w * frameUniforms.clipTransform.zw);
 #else
     gl_Position = getClipFromWorldMatrix() * getWorldPosition(material);
 #endif
@@ -164,6 +162,11 @@ void main() {
 #endif
 #endif // !USE_OPTIMIZED_DEPTH_VERTEX_SHADER
 
+#if defined(VERTEX_DOMAIN_DEVICE)
+    // Apply the clip-space transform which is normally part of the projection
+    gl_Position.xy = gl_Position.xy * frameUniforms.clipTransform.xy + (gl_Position.w * frameUniforms.clipTransform.zw);
+#endif
+
 #if defined(VERTEX_DOMAIN_DEVICE)
     // GL convention to inverted DX convention (must happen after clipSpaceTransform)
     gl_Position.z = gl_Position.z * -0.5 + 0.5;
```

Thank you!

**Comment by kpeeters** [comment]
That does the trick, thanks! Much appreciated!

**Comment by pixelflinger** [comment]
@kpeeters after https://github.com/google/filament/pull/5925 merges, you will have to set `vertexDomainDeviceJittered : true` in your material. And this should fix both your issue and TAA.

**Comment by kpeeters** [comment]
@pixelflinger Ok, no problem, sorry for making things difficult...

**Comment by kpeeters** [comment]
I hate to re-open this, but that `vertexDomainDeviceJittered : true` does not seem to work for me. I have rebuilt filament (with #5925 included) from `./build.sh -c` state, and rebuilt my app from a clean checkout with that flag added to all `vertexDomain: device` materials, but it jitters again. Maybe the heat is finally getting to me...

**Comment by romainguy** [comment]
You want to set that to false if you don't want jittering.

**Comment by romainguy** [comment]
Are you applying transforms?

**Comment by kpeeters** [comment]
Yes, as in my original report above. The fix worked before @pixelflinger added the new material parameter; I suspect the parameter is simply not being applied.

**Comment by pixelflinger** [comment]
I will have a look. So you see no difference with and without the flag? I must have missed something.

**Comment by pixelflinger** [comment]
indeed the flag wasn't available in the vertex shaders

**Comment by kpeeters** [comment]
Thanks for digging that out, will try #5936 now.

**Comment by kpeeters** [comment]
All good now, thanks!
