### ISSUE TITLE
Filament crashes if you place the camera at {0, 0, -20} in a simple scene with a single model

### ISSUE THREAD

**Issue by lincolnfrog** [google/filament#5933]
**Describe the bug**
Filament crashes when the camera is placed at {0, 0, -20}

**To Reproduce**
1. Create a simple scene with a single model
2. Position the camera at {0, 0, -20}

**Expected behavior**
The camera can be placed anywhere in the scene.

**Logs**
*** SIGABRT received at time=1660689482 ***
PC: @     0x7ff8111bf00e  (unknown)  __pthread_kill
    @        0x100ae05b8  (unknown)  absl::WriteFailureInfo()
    @        0x100ae04bd  (unknown)  absl::AbslFailureSignalHandler()
    @     0x7ff81120adfd  (unknown)  _sigtramp
    @        0x1020881b4  (unknown)  absl::base_internal::munmap_replacement_
    @     0x7ff811140d24  (unknown)  abort
    @        0x100fe3176  (unknown)  utils::abort()
    @        0x100fe31ae  (unknown)  utils::panic()
    @        0x100f927ec  (unknown)  filament::ShadowMap::updateDirectional()
    @        0x100f964b7  (unknown)  filament::ShadowMapManager::updateCascadeShadowMaps()
    @        0x100f95d88  (unknown)  filament::ShadowMapManager::update()
    @        0x100fc2c9c  (unknown)  filament::FView::prepareShadowing()
    @        0x100fc31f3  (unknown)  filament::FView::prepare()
    @        0x100fb5cf1  (unknown)  filament::FRenderer::renderJob()
    @        0x100fb54e6  (unknown)  filament::FRenderer::renderInternal()
    @        0x100fb55e5  (unknown)  filament::FRenderer::render()
    @        0x100de2c47  (unknown)  imp::window::FilamentHost::RenderNextFrame()
    @        0x100c57243  (unknown)  imp::window::SdlVenue()
    @        0x100c5706b  (unknown)  imp::window::SdlVenue()
    @        0x100adfd1d  (unknown)  main
    @        0x202a1952e  (unknown)  start
    @        0x202a14000  (unknown)  0x0

**Desktop (please complete the following information):**
 - OS: OSX
 - GPU: M1 Macbook
 - Backend: OpenGL

**Comment by pixelflinger** [comment]
able to reproduce with gltf_viewer
