### ISSUE TITLE
error: allocating an object of abstract class type 'filament::backend::PlatformDummyGL'

### ISSUE THREAD

**Issue by yurivict** [google/filament#5948]
**Describe the bug**
Build fails:
```
/disk-samsung/freebsd-ports/graphics/filament/work/filament-1.25.5/filament/backend/src/Platform.cpp:173:24: error: allocating an object of abstract class type 'filament::backend::PlatformDummyGL'
            return new PlatformDummyGL();
                       ^
```

Version: 1.25.5
clang-14
FreeBSD 13.1

**Comment by yurivict** [comment]
The method ```setPresentationTime``` is abstract in OpenGLPlatform and isn't defined in PlatformDummyGL so PlatformDummyGL is abstract.

**Comment by yurivict** [comment]
Perhaps you meant ```#error Unsupported system"``` instead of ```return new PlatformDummyGL();```?

**Comment by pixelflinger** [comment]
yeah it's unclear why `PlatformDummyGL` exists, we can remove it.

**Comment by pixelflinger** [comment]
Note that with the change above, this will fail at runtime. We can't do a build time failure because some other backend might be supported.

Bottom line is, freebsd is not supported (at least for GL).

**Comment by yurivict** [comment]
I am able to build it on FreeBSD by adding ```|| defined(__FreeBSD__)``` to the ```#if defined(__linux__)``` clause above, GL works identically on FreeBSD.
