### ISSUE TITLE
Incorrect value in Normalized Basis Functions docs

### ISSUE THREAD

**Issue by kettle11** [google/filament#5963]
<img width="742" alt="Screen Shot 2022-08-19 at 11 14 04 PM" src="https://user-images.githubusercontent.com/4565191/185726932-7314b7f3-0666-449a-a17e-7f811868781e.png">

As far as I understand it the highlighted value for l = 2 m = 0 appears incorrect. It does not agree with other sources or Filament's own code.

The actual implementation in Filament is correct: https://github.com/google/filament/blob/24b88219fa6148b8004f230b377f163e6f184d65/libs/ibl/src/CubemapSH.cpp#L675

**Comment by pixelflinger** [comment]
The documentation is actually correct. This is because `xx + yy + zz == 1` (by definition, we're on a sphere), so `xx + yy == 1 - zz`

**Comment by kettle11** [comment]
Ah, I see. Sorry for the incorrect report!
