### ISSUE TITLE
Crash when we don't load asset on maint thread

### ISSUE THREAD

**Issue by MichaelOliveiraBx** [google/filament#5974]
**Describe the bug**
The library crash when we don't load asset on main thread 

**To Reproduce**
1. create and AssetLoader and an ResourceLoader 
2. load an glb from an ByteBuffer 

```
private val assetLoader: AssetLoader = AssetLoader(
        engine,
        UbershaderLoader(engine),
        EntityManager.get(),
)
private val resourceLoader: ResourceLoader = ResourceLoader( engine, true, true, false)
... 
private suspend fun loadModelGlb(buffer: Buffer): FilamentAsset = withContext(Dispatchers.Default) {
    assetLoader.createAssetFromBinary(buffer)!!.also {
        resourceLoader.loadResources(it)
    }
}
```
Here if you use the Dispatchers.Main, it isn't crash.
- `resourceLoader.loadResources(it)` on another thread, will crash immediatly, 
- but for `assetLoader.createAssetFromBinary(buffer)`is more tricky because the crash is more randomly 

Maybe add an assert or write it in the documentation. 
I can make an PR just what is the best way for you ? 

**Logs**
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 18614 (FEngine::loop), pid 18572 (zi3d.test.izi3d)
A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
A/DEBUG: Build fingerprint: 'google/sdk_gphone_arm64/emulator_arm64:11/RSR1.210722.003/7604015:user/release-keys'
A/DEBUG: Revision: '0'
A/DEBUG: ABI: 'arm64'
A/DEBUG: Timestamp: 2022-08-22 14:44:47+0200
A/DEBUG: pid: 18572, tid: 18614, name: FEngine::loop  >>> com.luni.library.izi3d.test.izi3d <<<
A/DEBUG: uid: 10277
A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
A/DEBUG: Cause: null pointer dereference
A/DEBUG:     x0  b4000073996fd4f0  x1  00000071d6501210  x2  00000071d41e0a38  x3  0000000000000000
A/DEBUG:     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
A/DEBUG:     x8  0000000000000000  x9  0000000000000002  x10 0000000000000001  x11 0000000000000000
A/DEBUG:     x12 00000000c60a8a10  x13 0000000000000066  x14 002b6466febd6100  x15 0000000029aaaaab
A/DEBUG:     x16 00000071de9eaf00  x17 00000074dd53f85c  x18 00000071d3fd8000  x19 00000071d6501210
A/DEBUG:     x20 b4000073996fd4f0  x21 00000071d41e0af0  x22 b4000071d69e8a18  x23 b40000734972e740
A/DEBUG:     x24 b40000734972e6c0  x25 b40000734972eab0  x26 00000071d41e0ff8  x27 00000000000fc000
A/DEBUG:     x28 00000071d40e8000  x29 00000071d41e0c70
A/DEBUG:     lr  00000071de95cc1c  sp  00000071d41e0a30  pc  0000000000000000  pst 0000000000001000
A/DEBUG: backtrace:
A/DEBUG:       #00 pc 0000000000000000  <unknown>
A/DEBUG:       #01 pc 000000000011cc18  /data/app/~~J0J4qneUApRRsw_M10hPiQ==/com.luni.library.izi3d.test.izi3d-2OJrDMrqjgDtw-1DXYqtyQ==/base.apk!libfilament-jni.so (offset 0x8477000) (BuildId: c9f429441a722e6f192d8147fa84bc8a392b27f1)

**Smartphone (please complete the following information):**
 - Device: Pixel 5 and some simulator 
 - OS: All Android api

**Comment by romainguy** [comment]
You can read data from any thread but asset parsing/decoding must be done on the Filament thread (it doesn't have to be the main thread, but always the same thread you initialized Filament on). This applies to ALL Filament APIs (and why we don't have asserts otherwise every single call would need to make the check and it's not worth it).

**Comment by MichaelOliveiraBx** [comment]
Ok I understand I must create my own dispatcher with only one thread, thanks for the information
