### ISSUE TITLE
C++20 compatibility...

### ISSUE THREAD

**Issue by jiapei100** [google/filament#5980]
**is_pod** deprecated in C++20. please refer to [stackoverflow](https://stackoverflow.com/questions/48225673/why-is-stdis-pod-deprecated-in-c20) .

Refer to [BinaryTreeArray.h](https://github.com/google/filament/blob/main/libs/utils/include/utils/BinaryTreeArray.h#L34) .

**Comment by pixelflinger** [comment]
note that we're not officially supporting C++20, we're on C++17 right now.
