### ISSUE TITLE
【iOS】1.25.0 podSpec does not include the uberarchive.h file 

### ISSUE THREAD

**Issue by liangjie90** [google/filament#5987]
**Describe the bug**
1.25.0 podSpec does not include the include/gltfio/materials/uberarchive.h file ,I'll get an error when I use pod to quote filament
**To Reproduce**
1. pod 'Filament', '1.25.0
2. Try to reference this file uberarchive.h

**Comment by clg456852** [comment]
I have the same problem on latest release: https://github.com/google/filament/blob/v1.25.6/ios/CocoaPods/Filament.podspec
The podspec doesn't inlcude `uberarchive.h` which is located in `include/gltfio/materials/uberarchive.h`.
![cvpCtbySs8](https://user-images.githubusercontent.com/7767634/186360661-b768235c-a3b3-45d2-80f4-50acfa974bb2.jpg)

**Comment by bejado** [comment]
Thanks for your patience. uberarchive.h was indeed added and wasn't reflected in the Podspec. I'll fix this for the next release, v1.27.0. For now as a workaround, you can simply copy the [contents of uberarchive.h](https://gist.github.com/bejado/416bd0bea171869109977120800c6d8e) into whichever compilation units need it (it's < 10 lines).
