### ISSUE TITLE
No member named createAsset() in gltfio::AssetLoader

### ISSUE THREAD

**Issue by kaustubh-seachange** [google/filament#6003]
**Describe the bug**
Built Filament project and then tried building project hello-gltf.xcodeproj for iOS platforms.`runMesh()` method in App.c raised issue of missing `gltfio::AssetLoader::createAsset()`

**To Reproduce**
1. Build Filament on mac
2. Build iOS Project hello-gltf

**Expected behavior** 
`gltfio::AssetLoader()` has two relevant methods named `createAssetFromJson()` & `createAssetFromBinary()` but in App.c `runMesh()` calls `createAsset()`. However changing it to `createAssetFromBinary()` build project but results in crash at runtime.

**Screenshots**
![createAsset](https://user-images.githubusercontent.com/5715330/187062498-3c37ac16-2f0d-4824-a074-8604a3f62e0e.png)

**Logs**

In file included from /Users/iosdev/Documents/rendering_engine/filament_sdk_ios/filament-main/ios/samples/hello-gltf/hello-gltf/FilamentView/App.cpp:23:
In file included from /Users/iosdev/Documents/rendering_engine/filament_sdk_ios/filament-main/ios/samples/hello-gltf/Pods/Headers/Public/Filament/ktxreader/Ktx1Reader.h:22:
/Users/iosdev/Documents/rendering_engine/filament_sdk_ios/filament-main/ios/samples/hello-gltf/Pods/Headers/Public/Filament/filament/Texture.h:500:10: warning: declaration is marked with 'deprecated' command but does not have a deprecation attribute [-Wdocumentation-deprecated-sync]
    /** deprecated */
        ~^~~~~~~~~~
/Users/iosdev/Documents/rendering_engine/filament_sdk_ios/filament-main/ios/samples/hello-gltf/Pods/Headers/Public/Filament/filament/Texture.h:330:59: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
        setImage(engine, level, 0, 0, 0, getWidth(level), getHeight(level), 1, std::move(buffer));
        ~~~~~~~~                                          ^~~~~~~~~~~~~~~~
/Users/iosdev/Documents/rendering_engine/filament_sdk_ios/filament-main/ios/samples/hello-gltf/Pods/Headers/Public/Filament/filament/Texture.h:330:42: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
        setImage(engine, level, 0, 0, 0, getWidth(level), getHeight(level), 1, std::move(buffer));
        ~~~~~~~~                         ^~~~~~~~~~~~~~~
/Users/iosdev/Documents/rendering_engine/filament_sdk_ios/filament-main/ios/samples/hello-gltf/hello-gltf/FilamentView/App.cpp:140:34: error: no member named 'createAsset' in 'filament::gltfio::AssetLoader'
    app.asset = app.assetLoader->createAsset(buffer.data(), static_cast<uint32_t>(size));
                ~~~~~~~~~~~~~~~  ^
3 warnings and 1 error generated.


Build failed    27/08/22, 23:48    667.0 seconds

**Desktop (please complete the following information):**
 - OS: macOS 11.6.2
 - GPU: Inbuilt
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.3.1

**Additional context**

**Comment by kaustubh-seachange** [comment]
Instead of `runMesh()` please read and refer to `setupMesh()` in `hello-gltf.xcodeproj`

**Comment by prideout** [comment]
The `createAsset` method was added to gltfio very recently, so I think you're using sample code from our main branch, while using using a gltfio that's not built from our main branch.
