### ISSUE TITLE
failed assertion `f > n'

### ISSUE THREAD

**Issue by lincolnfrog** [google/filament#6020]
@        0x100afe5a0  (unknown)  utils::abort()
    @        0x100afe5d8  (unknown)  utils::panic()
    @        0x100aaebd8  (unknown)  filament::ShadowMap::warpFrustum()
    @        0x100aad1e1  (unknown)  filament::ShadowMap::applyLISPSM()
    @        0x100aab3ab  (unknown)  filament::ShadowMap::updateDirectional()
    @        0x100ab050b  (unknown)  filament::ShadowMapManager::updateCascadeShadowMaps()
    @        0x100aafddc  (unknown)  filament::ShadowMapManager::update()
    @        0x100adda9e  (unknown)  filament::FView::prepareShadowing()
    @        0x100addff5  (unknown)  filament::FView::prepare()
    @        0x100ad0445  (unknown)  filament::FRenderer::renderJob()
    @        0x100acfc32  (unknown)  filament::FRenderer::renderInternal()
    @        0x100acfd31  (unknown)  filament::FRenderer::render()
    @        0x1007fad2e  (unknown)  imp::window::FilamentHost::RenderNextFrame()
    @        0x1004c0530  (unknown)  imp::window::SdlVenue()
    @        0x1004bfef1  (unknown)  imp::window::SdlVenue()
    @        0x1002a4a43  (unknown)  main
    @        0x20378c52e  (unknown)  start
    @        0x203787000  (unknown)  0x0

**Comment by romainguy** [comment]
Didn't we fix this recently?

@lincolnfrog What version of Filament are you using?

**Comment by pixelflinger** [comment]
@romainguy we did, but @lincolnfrog is still seeing this assert after patching the PR that was supposed to fix it.

**Comment by pixelflinger** [comment]
I think this should be fixed now.
