### ISSUE TITLE
In filament document, it has wrong sample code.

### ISSUE THREAD

**Issue by Muratam** [google/filament#603]
**Describe the bug**
https://google.github.io/filament/Filament.md.html#materialsystem/standardmodelsummary
In filament document , section 4.6 ,Listing 9, it mistakes `VOH` for `LOH` .

- `float LoH = clamp(dot(l, h), 0.0, 1.0);` will be `float VoH = clamp(dot(v, h), 0.0, 1.0);`
- `F_Schlick(LoH, f0);` will be `F_Schlick(VoH, f0);`

**Comment by romainguy** [comment]
`h` is the half vector between `l` and `v`, which means `LoH` and `VoH` are the same thing.

**Comment by Muratam** [comment]
ok,microfacet model ,ok .sorry.
