### ISSUE TITLE
[iOS] hello-gltf example crashes at loadResources.

### ISSUE THREAD

**Issue by kaustubh-seachange** [google/filament#6032]
**Describe the bug**
Post setting up the iOS Project hello-gltf sample, and running with DamagedHelmet.glb as asset App crashes.

**To Reproduce**
1. Build Filament project v1.26.0 as described in its Readme and iOS Readme file.
2. Build iOS Project hello-gltf.xcodeproj located under ios/samples for filament v1.26.0

**Expected behavior**
No Crash should be observed.

**Screenshots**
![hello_gltf_sample](https://user-images.githubusercontent.com/5715330/188153803-b130ca9e-7f6e-4e8a-9ea1-4f2253c1122f.png)

**Logs**
2022-09-01 18:43:52.583117+0530 hello-gltf[649:83044] Metal API Validation Enabled
FEngine (64 bits) created at 0x106027a00 (threading is enabled)
FEngine resolved backend: Metal
Selected physical device 'Apple A14 GPU'
FEngine feature level: 1
Missing texture provider for image/jpeg
Missing texture provider for image/jpeg
Missing texture provider for image/jpeg
Missing texture provider for image/jpeg
Missing texture provider for image/jpeg

**Desktop (please complete the following information):**
 - OS: iOS
 - GPU: Inbuilt
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.3.1

**Additional context**
- I also tried other glb and gltf files located in thirdparty/models folder AnimatedTriangle.gltf and lucy.glb, but similar issue persists.

**Comment by bejado** [comment]
Interesting, I'm able to load DamagedHelmet.glb without any issues. However, I don't see the missing texture provider warnings, which might be relevant. @kaustubh-seachange can you confirm [this line](https://github.com/google/filament/blob/41bd30f81d98d45de8bae6dd7cf7699608d45af7/ios/samples/gltf-viewer/gltf-viewer/FILModelView.mm#L140) is present in your build?

```
    _resourceLoader->addTextureProvider("image/jpeg", _stbDecoder);
```

**Comment by kaustubh-seachange** [comment]
Thanks @bejado for quick reply, this line doesnt exist in the Hello-gltf.xcodeprroj. `_resourceLoader->addTextureProvider("image/jpeg", _stbDecoder);`
