### ISSUE TITLE
【Android】There is a chromatic aberration between the origin texture and imported texture.Don't close this question immediately , I indeed need help!!!

### ISSUE THREAD

**Issue by dandingol03** [google/filament#6034]
**Describe the bug**
I have closed the tone mapping !!!!!There is a chromatic aberration between the origin texture and imported texture. I create an opengles context outside and init a texture which is specified to rgba format by `glTexImage2D`. I create a `filament::Texture` to import the opengles texture and draw it on the screen. However, there is a chromatic aberration between the origin texture and imported texture. Please ignore the wrong ratio of the imported texture, it is just a demo. 

**To Reproduce**
1. create an openlges texture, and specify its format to rgba
2. decode a png file and upload it to the opengles texture by using `texImage2D`
3. create a `filament::Texture` and import the opengles texture. Special its format to rgba
4. sample this filament::Texture` on a unlit mat file and  draw it on the screen
5. close tone mapping use this: `view.toneMapping = View.ToneMapping.LINEAR`

**Expected behavior**
no chromatic aberration 

**Screenshots**
the origin picture:
![image](https://user-images.githubusercontent.com/13013579/188159944-ac73a57c-3a68-4d11-ba1b-a6749bcd6d76.png)

**mat**
```
    vec4 color = texture(materialParams_videoTexture, uv);
    material.baseColor = color;
    material.baseColor.rgb = inverseTonemapSRGB(color.rgb);
```

the imported  texture:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/13013579/188190839-ebbc5eee-13cd-4874-9a4e-5bba0f8b5ea6.png">

**Smartphone (please complete the following information):**
 - Device: [Samsung S20]
 - OS: [Android]

**Comment by romainguy** [comment]
You are applying `inverseTonemapSRGB` with linear tone mapping, that's why the colors are different. `inverseTonemapSRGB` is meant to (approximately) undo tone mapping when it's enabled.
