### ISSUE TITLE
webgl samples which have bugs

### ISSUE THREAD

**Issue by unicomp21** [google/filament#6049]
look in the browser console for the errors

---animation.html---
Uncaught (in promise) RuntimeError: memory access out of bounds
    at filament.wasm:0xf0d55
    at filament.wasm:0xf34ca
    at filament.wasm:0xf5110
    at filament.wasm:0x136ce4
    at filament.wasm:0x89710
    at gltfio$AssetLoader.gltfio$AssetLoader$_createAsset [as _createAsset] (eval at new_ (filament.js:9:84838), <anonymous>:9:10)
    at Filament.gltfio$AssetLoader.createAsset (filament.js:858:29)
    at new App (animation.html:35:43)
    at animation.html:25:18
    at taskFinished (filament.js:78:17)
    
   ---helmet.html---
   Uncaught (in promise) BindingError {name: 'BindingError', message: 'Cannot pass deleted object as a pointer of type gltfio$ResourceLoader*', stack: 'BindingError: Cannot pass deleted object as a poin…8\n    at http://localhost:8000/filament.js:145:21'}
   
   ---[test-filament-viewer.html](http://localhost:8000/test-filament-viewer.html)---
   Uncaught (in promise) BindingError {name: 'BindingError', message: 'Cannot pass deleted object as a pointer of type gltfio$ResourceLoader*', stack: 'BindingError: Cannot pass deleted object as a poin…8\n    at http://localhost:8000/filament.js:145:21'}

**Comment by romainguy** [comment]
@prideout Weren't you/didn't you fix this issue yesterday?

**Comment by prideout** [comment]
Fixed by #6046
