### ISSUE TITLE
Image not freed in sample ImageViewer

### ISSUE THREAD

**Issue by nmfisher** [google/filament#6055]
**Describe the bug**

The Image pointer is not passed to the Texture::PixelBufferDescriptor constructor @ 
https://github.com/google/filament/blob/main/samples/image_viewer.cpp#L263, meaning the callback at https://github.com/google/filament/blob/5e128214fa1fc6812d50e02c6cdc519a02df05a8/samples/image_viewer.cpp#L255 is not actually freeing any data.

This causes a memory leak. To help those of us who copy/paste sample code into our own applications, this should be changed to:

```
Texture::PixelBufferDescriptor buffer(
            image->getPixelRef(),
            size_t(w * h * channels * sizeof(float)),
            channels == 3 ? Texture::Format::RGB : Texture::Format::RGBA,
            Texture::Type::FLOAT,
            freeCallback,
            image <-- add this here
    );
```

**To Reproduce**

1. Launch sample image_viewer and any tool for viewing process memory usage (e.g. Task Manager on Windows). Drag/drop the same image multiple times onto the viewer. Memory usage will increase each time without being freed/reclaimed [0].

[0] There also seems to be a separate issue with massive memory consumption when decoding PNG images? I just saw usage shoot up by more than 200mb for a 2000x3844 PNG, which seems way too high. 

**Expected behavior**
Memory usage should remain the same.

**Screenshots**
N/A

**Logs**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: Intel integrated
 - Backend: OpenGL

Filament built from commit efba9a636

**Additional context**

**Comment by romainguy** [comment]
Thanks, good catch! The memory usage more or less checks out: the image is loaded as a `float*` buffer, so 16 bytes per pixel, or ~128 MiB for a 2,000x3,884 image. The GPU texture is in RGBA16F so that's another ~64 MiB + mip maps. The image viewer is meant to display HDR images (HDR or OpenEXR format) and not optimized for 8-bit PNGs.
