### ISSUE TITLE
Possible bug in luminous power of a spot light.

### ISSUE THREAD

**Issue by querielo** [google/filament#6060]
**Describe the bug**
It looks like the third equation is not correct [here](https://google.github.io/filament/Filament.md.html#MathJax-Span-4149). And calculated luminous power is higher than it should be.

Suggested: 
<img width="505" alt="Screen Shot 2022-09-12 at 15 42 27" src="https://user-images.githubusercontent.com/104348270/189645160-de01741c-d6d6-4e5a-8ef5-bed1ebfac655.png">

**Why?**

[Here](https://www.desmos.com/calculator/4kcokjsz4q) is a plot for an angular falloff attenuation model with the linear falloff function.

<img width="532" alt="Screen Shot 2022-09-12 at 15 54 41" src="https://user-images.githubusercontent.com/104348270/189647047-4819355a-b74f-48e9-9367-7cf2d86cb3a6.png">

Dash lines show luminous intensity factor. As you can see, the purple area is equal to the blue area. So, the green area plus the purple area are equal to the green area plus the blue area, and whole area is area of the rectangle.

This is similar to the formula from [PBR book](https://www.pbr-book.org/3ed-2018/Light_Sources/Point_Lights#fragment-SpotLightMethodDefinitions-3).

**The issue place**

_Documentation_: https://github.com/google/filament/blob/7917f74bc8b016cab25b67fe4a995f03c5bfe303/docs/Filament.md.html#L1401
_Source code_: https://github.com/google/filament/blob/81c1d3ed1ab3018c41ee319f5e20458e9e448265/filament/src/components/LightManager.cpp#L318

**Comment by pixelflinger** [comment]
Thank you for pointing this out. We've discussed it and we're not sure if any of the solution is correct, both are approximations anyways.  Unless this is causing a noticeable problem, I'm more in favor of not changing this.
