### ISSUE TITLE
build report error: unknown type name 'streamsize'

### ISSUE THREAD

**Issue by huyunan496** [google/filament#6104]
**Describe the bug**
I executed this command `./build.sh -s -p ios -i debug`, and I got this error: unknown type name 'streamsize'

**Logs**
iOS simulator support enabled.
Warning: could not find ninja, using make instead
Building debug in out/cmake-debug...
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- DFG LUT size set to 128x128
-- Found Python3: /opt/homebrew/Frameworks/Python.framework/Versions/3.9/bin/python3.9 (found version "3.9.13") found components: Interpreter 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xxxx/Downloads/filament-main/out/cmake-debug
[  0%] Building CXX object third_party/spirv-cross/tnt/CMakeFiles/spirv-cross-msl.dir/__/spirv_msl.cpp.o
[  0%] Linking CXX static library libspirv-cross-msl.a
[  0%] Built target spirv-cross-msl
[  0%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/api_level.cpp.o
[  0%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/ashmem.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/debug.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/Allocator.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/CallStack.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/CString.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/CountDownLatch.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/CyclicBarrier.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/EntityManager.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/JobSystem.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/Log.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/NameComponentManager.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/ostream.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/Panic.cpp.o
[  4%] Building CXX object libs/utils/CMakeFiles/utils.dir/src/Path.cpp.o
In file included from /Users/xxxx/Downloads/filament-main/libs/utils/src/Path.cpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/sstream:184:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:180:5: error: unknown type name 'streamsize'
    streamsize __gc_;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:246:5: error: unknown type name 'streamsize'
    streamsize gcount() const {return __gc_;}
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:258:40: error: unknown type name 'streamsize'
    basic_istream& get(char_type* __s, streamsize __n)
                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:261:40: error: unknown type name 'streamsize'
    basic_istream& get(char_type* __s, streamsize __n, char_type __dlm);
                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:270:44: error: unknown type name 'streamsize'
    basic_istream& getline(char_type* __s, streamsize __n)
                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:273:44: error: unknown type name 'streamsize'
    basic_istream& getline(char_type* __s, streamsize __n, char_type __dlm);
                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:275:27: error: unknown type name 'streamsize'
    basic_istream& ignore(streamsize __n = 1, int_type __dlm = traits_type::eof());
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:277:42: error: unknown type name 'streamsize'
    basic_istream& read (char_type* __s, streamsize __n);
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:278:5: error: unknown type name 'streamsize'
    streamsize readsome(char_type* __s, streamsize __n);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:278:41: error: unknown type name 'streamsize'
    streamsize readsome(char_type* __s, streamsize __n);
                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:286:42: error: incomplete type 'std::ios_base' named in nested name specifier
    basic_istream& seekg(off_type __off, ios_base::seekdir __dir);
                                         ^~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from /Users/xxxx/Downloads/filament-main/libs/utils/src/Path.cpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/sstream:184:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:314:44: error: incomplete type 'std::ios_base' named in nested name specifier
        if (!__noskipws && (__is.flags() & ios_base::skipws))
                                           ^~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from /Users/xxxx/Downloads/filament-main/libs/utils/src/Path.cpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/sstream:184:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:317:19: error: no template named 'ctype'
            const ctype<_CharT>& __ct = use_facet<ctype<_CharT> >(__is.getloc());
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:317:51: error: use of undeclared identifier 'ctype'; did you mean 'wctype'?
            const ctype<_CharT>& __ct = use_facet<ctype<_CharT> >(__is.getloc());
                                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/cwctype:79:9: note: 'wctype' declared here
using ::wctype _LIBCPP_USING_IF_EXISTS;
        ^
In file included from /Users/xxxx/Downloads/filament-main/libs/utils/src/Path.cpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/sstream:184:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:324:31: error: incomplete type 'std::ios_base' named in nested name specifier
                __is.setstate(ios_base::failbit | ios_base::eofbit);
                              ^~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from /Users/xxxx/Downloads/filament-main/libs/utils/src/Path.cpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/sstream:184:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:324:51: error: incomplete type 'std::ios_base' named in nested name specifier
                __is.setstate(ios_base::failbit | ios_base::eofbit);
                                                  ^~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from /Users/xxxx/Downloads/filament-main/libs/utils/src/Path.cpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/sstream:184:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:329:23: error: incomplete type 'std::ios_base' named in nested name specifier
        __is.setstate(ios_base::failbit);
                      ^~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from /Users/xxxx/Downloads/filament-main/libs/utils/src/Path.cpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/sstream:184:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:357:5: error: incomplete type 'std::ios_base' named in nested name specifier
    ios_base::iostate __state = ios_base::goodbit;
    ^~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from /Users/xxxx/Downloads/filament-main/libs/utils/src/Path.cpp:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/sstream:184:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/istream:357:23: error: use of undeclared identifier '__state'; did you mean '__rotate'?
    ios_base::iostate __state = ios_base::goodbit;
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/rotate.h:141:1: note: '__rotate' declared here
__rotate(_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last,
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [libs/utils/CMakeFiles/utils.dir/src/Path.cpp.o] Error 1
make[2]: *** [libs/utils/CMakeFiles/utils.dir/all] Error 2
make[1]: *** [tools/matc/CMakeFiles/matc.dir/rule] Error 2
make: *** [matc] Error 2

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Xcode Version 13.4.1 (13F100)

**Comment by romainguy** [comment]
These errors show a problem with your command line tools install. Run xcode or xcode-select --install then a clean build of filament.

**Comment by huyunan496** [comment]
> 

I delate command line tools and reInstall it. It worked only once, when i repeat build，the error reappear
