### ISSUE TITLE
GLTF ao strength is applied directly as a scale factor (0 = black AO)

### ISSUE THREAD

**Issue by hillesland** [google/filament#6106]
**Describe the bug**
When setting occlusionTexture "strength" to zero, it turns the ambient term black instead of "off" (no AO map effect).

**To Reproduce**

1.  Find a GLTF file with occlusionTexture.  Add/change the "strength" to zero.
2. Load into gltf_viewer
3. Turn off sunlight (leave only ambient term)

**Expected behavior**

Should behave as if there is no AO map.   The darkening affect should go away.

Another way to put it, is that AO "strength" is an interpolent between the AO map and an all-white AO map. 

GLTF 2.0 spec excerpt:

> The texture binding for occlusion maps MAY optionally contain a scalar strength value that is used to reduce the occlusion effect. When present, it affects the occlusion value as 1.0 + strength * (occlusionTexture - 1.0).

**Screenshots**
Example loaded into vscode filament viewer.

<img width="300" alt="Screen Shot 2022-09-26 at 12 54 45 PM" src="https://user-images.githubusercontent.com/521420/192413336-f04c0051-688a-4d1e-a248-d2d83a1494d4.png">

**Logs**
NA

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1.
 - GPU:AMD Radeon
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: Some Android (happens there too)
 - OS: 

**Additional context**

**Comment by prideout** [comment]
Wow, this bug exists in both of our built-in material providers (Uber and Jit) and has been there since day zero.

I think there aren't many models that exercise the `strength` feature, that might be why this has gone unnoticed for so long.

Thank you for filing the bug!

**Comment by hillesland** [comment]
It only came up because we were using it for a slightly weird purpose.  Thanks for the fix.
