### ISSUE TITLE
[1.27.1] utils/generic/Mutex.h not getting staged

### ISSUE THREAD

**Issue by jwinarske** [google/filament#6115]
**Describe the bug**

When building app against Linux desktop build hits
```
.../out/debug/filament/include/utils/Mutex.h:23:10: fatal error: 'utils/generic/Mutex.h' file not found
#include <utils/generic/Mutex.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
```

`utils/generic/Mutex.h` is missing from staged install.

**Workaround**

```
mkdir -p out/debug/filament/include/utils/generic
mkdir -p out/release/filament/include/utils/generic
cp libs/utils/include/utils/generic/Mutex.h out/debug/filament/include/utils/generic
cp libs/utils/include/utils/generic/Mutex.h out/release/filament/include/utils/generic
```

**To Reproduce**
1. On Linux host run
```
CC=/usr/lib64/ccache/clang CXX=/usr/lib64/ccache/clang++ CXXFLAGS="-stdlib=libc++ -fno-builtin" ./build.sh -i debug release
```

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu 20.4
 - Backend: Vulkan

**Comment by romainguy** [comment]
Weird, we properly include it on macOS. Seems to be a Linux-specific problem.

@pixelflinger @bejado can you take a look please?

**Comment by bejado** [comment]
Looks like https://github.com/google/filament/pull/5929 broke this, but the fix is straightforward.
