### ISSUE TITLE
cmake should check architecture and fail with an appropriate message

### ISSUE THREAD

**Issue by yurivict** [google/filament#6131]
**Describe the bug**
filament fails on armv7:
```
/wrkdirs/usr/ports/graphics/filament/work/filament-1.27.0/libs/bluegl/src/BlueGLCoreLinuxImpl.S:15278:9: error: unexpected token in operand
    jmp *(%r11)
        ^
```

filament fails on i386 on assembly: unexpected token in operand - on the same assembly line.

It doesn't fail on arm64.

Please check architecture in cmake scripts and fail with an appropriate message.

FreeBSD 13.1

**Comment by romainguy** [comment]
arm7 is supported on Android only.
