### ISSUE TITLE
Max morph targets is limited to 256

### ISSUE THREAD

**Issue by Obg1** [google/filament#6142]
I cannot use models with higher morph targets.
Maybe you can add cpu to avoid this limit?

[Max morph targets 256 limit](https://github.com/google/filament/pull/5332)

**Comment by romainguy** [comment]
There is no plan to support more morph targets at this point.

**Comment by Obg1** [comment]
@romainguy looking at the code I see that each weight is passed using 4 floats and reading only the first one.
Looks like it can be changed to use all of the 4 floats to pass more data and increase the limit to 256*4 instead of 256.
What do you think? Am I missing something?
https://github.com/google/filament/blob/a64b1eccdf37dde0eb038606225cf69b13b8659d/shaders/src/getters.vs#L99

**Comment by Obg1** [comment]
I've submitted a PR:
https://github.com/google/filament/pull/6214
