### ISSUE TITLE
Textures aren't bounded properly in argument buffers

### ISSUE THREAD

**Issue by daemyung** [google/filament#6145]
**Describe the bug**
Rendering result is incorrect because argument buffers doesn't have proper textures

**To Reproduce**
1. Download [bella.glb.zip](https://github.com/google/filament/files/9703435/bella.glb.zip)
2. Run gltf_viewer bella.glb
3. Hiearachy > Node > Node > POLYWINK_Bella > morphing, enable it
4. Morphing > eyeBlankLeft, change value

**Expected behavior**

https://user-images.githubusercontent.com/7459074/193756260-de1b78b1-b246-4afe-b83a-2fa8e1b24b6a.mov

**Screenshots**

https://user-images.githubusercontent.com/7459074/193755790-97aad960-8dfd-440d-bfd3-a6f6f6a3b312.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Backend: Metal

**Additional context**
My company has NDA with Google. If you want to light model files to reproduce this issue, please let me know. I will send it to you.

**Comment by daemyung** [comment]
@bejado Will #6135 fix this issue?

**Comment by daemyung** [comment]
@bejado Sorry I have tested your PR but it's not a solution.

**Comment by bejado** [comment]
Will take a look

**Comment by atul161** [comment]
@bejado  @daemyung  still happening with me...setting morph weight cause this issue...
https://github.com/google/filament/issues/6462

**Comment by bejado** [comment]
@atul161 Argument buffers are specific to Metal. According to the bug you filed, you're seeing an issue on Android devices, so it must be something else.

**Comment by anliyuan** [comment]
@daemyung hi, did you fix this

**Comment by anliyuan** [comment]
@atul161 hi, did you fix this

**Comment by daemyung** [comment]
> @atul161 hi, did you fix this

Yes it is fixed.
