### ISSUE TITLE
Error when trying to build filament ios

### ISSUE THREAD

**Issue by n00ner** [google/filament#6151]
I use this guide https://github.com/google/filament/blob/main/ios/samples/README.md

xcode command line tools installed 

cmake and ninja installed from brew 

When I executed "./build.sh -p ios -i debug " I got this error: 

CMake Error at third_party/clang/iOS.cmake:60 (MESSAGE):
  SDKROOT could not be detected!
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:9 (project)
  

My computer macbook m1 
MacOS 12.5.1 (Monterey)

**Comment by bejado** [comment]
What does running this command print?

```
xcodebuild -version -sdk iphoneos Path
```

**Comment by n00ner** [comment]
tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by bejado** [comment]
Somehow your Xcode installation isn't properly set up. That command should return a path to the iPhone SDK:

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk
```

**Comment by zengchaojie** [comment]
I met the same problem, have you solved it?
