### ISSUE TITLE
Install filamentapp and filagui

### ISSUE THREAD

**Issue by daemyung** [google/filament#6154]
**Is your feature request related to a problem? Please describe.**
I want to create an application outside of filament and want to use filamentapp and filagui to accelerate building an application. But two libraries are not installed. So there is no way to do this.

**Describe the solution you'd like**
Install filamentapp and filagui.

**Comment by romainguy** [comment]
These are not libraries we wish to support as public APIs. Maybe filagui but definitely not filament app. At least not in its current form.

**Comment by daemyung** [comment]
@romainguy Ok I see. I will close this issue.
