### ISSUE TITLE
How can i use  "stencilWrite" in mat file

### ISSUE THREAD

**Issue by dandingol03** [google/filament#6158]
**Describe the bug**
I saw the the `MaterialInstance` api has support `stencil test`. But how can i use stencil property in mat file? When i add the `stencilWrite` property in mat file, the mat cannot identify it correctly.

**Logs**
 Ignoring` config entry (unknown key): "stencilWrite

**Desktop (please complete the following information):**
 - OS: [MAC]

**Comment by romainguy** [comment]
Please use Discussions for questions. Stencil writes are currently set by calling APIs on `MaterialInstance`.
