### ISSUE TITLE
How to successfully build  Filament  for  Android  and for Windows  on Windows  operating system？

### ISSUE THREAD

**Issue by ouyangpeng** [google/filament#6175]
# How to successfully build Filament for Android and for Windows on Windows operating system？

The following two blogs record the process of compiling Filament:

+ [How to building Filament for Windows?](https://blog.csdn.net/qq446282412/article/details/127106446)
+ [How to building Filament for Android on Windows?](https://blog.csdn.net/qq446282412/article/details/127208846)

# 如何成功的在Windows系统上编译Filament的Android版本和Windows桌面版本程序？

下面两篇博客记录了编译Filament的过程：

+ [【我的渲染技术进阶之旅】如何编译Filament的windows版本程序？](https://blog.csdn.net/qq446282412/article/details/127106446)
+ [【我的渲染技术进阶之旅】如何在Windows系统编译Filament的android版本程序？](https://blog.csdn.net/qq446282412/article/details/127208846)

**Comment by romainguy** [comment]
Please use Discussions for this.
