### ISSUE TITLE
Metal validateCommonDrawErrors triggered

### ISSUE THREAD

**Issue by kpeeters** [google/filament#6180]
With recent filament versions I am getting 

    -[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5252: failed assertion `Draw Errors Validation
    Fragment Function(main0): the offset into the buffer spvDescriptorSet3 that is bound at buffer index 29 
    must be a multiple of 256 but was set to 16.

Only seems to be happening on the iOS simulator, but that may simply be a consequence of the particular screen sizes I have tested with so far. Works fine when building "For my mac". Will do more digging tomorrow to see where this started happening.

**Comment by bejado** [comment]
Huh, I can reproduce. I thought I already [accounted for this](https://github.com/google/filament/blob/main/filament/backend/src/metal/MetalBuffer.h#L105-L112). Nowhere in the [Metal Feature Set Tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) do I see a constant offset requirement of 256, but it wouldn't surprise me that the simulator has a specific requirement that isn't reflected there..

**Comment by bejado** [comment]
Sure enough, if I run Apple's _own_ argument buffer sample and set the buffer to a constant buffer with offset < 256, I get the same error.

**Comment by bejado** [comment]
Aha, from [Developing Metal Apps that Run in Simulator](https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator?language=objc)

> When you set arguments for the render or compute command, align constant buffer offsets to 256 bytes. Normally, iOS requires an alignment of 4 bytes. This difference may mean that you might need to arrange your data differently when running in Simulator.
