### ISSUE TITLE
IBL packaged incorrectly for `gltf_viewer`?

### ISSUE THREAD

**Issue by will-ca** [google/filament#6193]
**Describe the bug**
Currently `gltf_viewer` crashes on startup for me. #6192 

However, before crashing it also outputs this line:
```
The specified IBL path does not exist: /home/User/filament/bin/assets/ibl/lightroom_14b
```

Currently `bin/assets` is structured as follows:

```Bash
$ tree bin/assets
bin/assets
├── fonts
│   ├── Roboto-License.txt
│   └── Roboto-Medium.ttf
└── lightroom_14b
    ├── lightroom_14b_ibl.ktx
    ├── lightroom_14b_skybox.ktx
    └── sh.txt

2 directories, 5 files
```

If I create the apparently missing `ibl` directory and then move `lightroom_14b` into it, then the "missing" message is not printed:

```Bash
$ mkdir bin/assets/ibl
$ mv bin/assets/lightroom_14b bin/assets/ibl/
$ tree bin/assets
bin/assets
├── fonts
│   ├── Roboto-License.txt
│   └── Roboto-Medium.ttf
└── ibl
    └── lightroom_14b
        ├── lightroom_14b_ibl.ktx
        ├── lightroom_14b_skybox.ktx
        └── sh.txt

3 directories, 5 files
```

**To Reproduce**
1. Download and extract `filament-v1.28.0-linux.tgz` from https://github.com/google/filament/releases.
2. Try to run `bin/gltf_viewer`.
3. Observe terminal output.

**Desktop (please complete the following information):**
 - OS: Linux
 - GPU: Intel UHD 620
 - Backend: No idea. The STDOUT/STDERR says "Vulkan"?

**Comment by prideout** [comment]
Thanks for the bug report!  I think this problem exists in all desktop release archives, it's likely to be a one-line fix to `samples/CMakeLists.txt`

Is #6192 the same issue?

**Comment by will-ca** [comment]
> Is #6192 the same issue?

I don't believe so. #6192 still happens when I manually fix this issue (I.E. with the second `tree` structure).
