### ISSUE TITLE
Fedora build problems

### ISSUE THREAD

**Issue by captcha1** [google/filament#62]
On Fedora 28 : 

CC=/usr/bin/clang CXX=/usr/bin/clang++ ./build.sh debug

... works (though bluegl doesn't work on 32 bit systems).

If I do : 

./build.sh debug

... I get "Could NOT find Threads (missing: Threads_FOUND)" .  Dunno why.

Also, if I do

./build.sh -m debug

... I get : c++: error: unrecognized command line option ‘-stdlib=libc++’

This is GNU 8.1.1

**Comment by romainguy** [comment]
Make sure you have pthread-dev installed. Note that we do not support building on desktop 32 bit systems, only 64 bit systems. We do support 32 bit systems for Android.

Which version of clang are you using? Could you please paste the output of cmake right after you run the build script?

**Comment by captcha1** [comment]
I don't see pthread-dev . I see /usr/include/pthread.h , which is part of glibc-headers

clang is 6.0.1

Here's the output of ./build.sh debug : 

Warning: JAVA_HOME is not set, skipping Java projects
Building debug in out/cmake-debug...
-- The C compiler identification is GNU 8.1.1
-- The CXX compiler identification is GNU 8.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindThreads.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/libgtest/tnt/CMakeLists.txt:26 (find_package)


-- Configuring incomplete, errors occurred!
See also "~/filament/out/cmake-debug/CMakeFiles/CMakeOutput.log".
See also "~/filament/out/cmake-debug/CMakeFiles/CMakeError.log".

**Comment by captcha1** [comment]
Oh wait ... looking at cmake-debug/CMakeFiles/CMakeError.log : 

cc: error: unrecognized command line option ‘-fcolor-diagnostics’

**Comment by romainguy** [comment]
-fcolor-diagnostics is only supported by clang, not gcc. We do not support building with gcc.

**Comment by captcha1** [comment]
OK ... I though you did both gcc & clang.  Now I see in the readme that you don't do gcc.

Thanks

**Comment by captcha1** [comment]
Is it possible to make  a cmake rule that clearly states that gcc is not supported (instead of obscure errors about pthreads) ?

**Comment by romainguy** [comment]
Yep, that would be wise :)
