### ISSUE TITLE
SSAO creates random black squares on screen in GLTF Viewer

### ISSUE THREAD

**Issue by Francois-Grassard** [google/filament#6216]
**Describe the bug**
We currently integrate Filament in our upcoming product "Autograph" and we sometimes have some strange artefacts.
So, I tested simple and more complex scenes in the GLFT viewer to be sure it wasn't a problem on our side.

**To Reproduce**

Here is a really simple scene, with just a cube on a plance :

[SimpleCubeandPlane.zip](https://github.com/google/filament/files/9849853/SimpleCubeandPlane.zip)

I used CC0 Autoshop_Engines.exr (converted to *.HDR) to light the scene, available here since the "HDRVault" website is down.

https://zenodo.org/record/1245790

**Expected behavior**
No black artefacts ;)

**Screenshots**
Here is a screencast for this scene

https://user-images.githubusercontent.com/7964475/197465939-a158e99c-a8d7-490a-a15e-68d232c36d23.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - GPU: [NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan (I tested both)]

Tested on 3 different (Win10) computers with different NVIDIA graphic cards.

I also tested with more complex scenes, like the NVIDIA Attic. You can see dark blocks on the celling :

![image](https://user-images.githubusercontent.com/7964475/197476435-e95bd8cf-00cd-44aa-ba35-da7e1e7f0377.png)

Thank you !

**Comment by romainguy** [comment]
We saw that bug recently ourselves.

**Comment by romainguy** [comment]
@bejado Does https://github.com/google/filament/pull/6221 fix this?

**Comment by bejado** [comment]
> @bejado Does #6221 fix this?

It's worth a try but I don't think so. #6621 was limited to the Metal backend from what I could tell.

**Comment by romainguy** [comment]
It would be worth testing with specular AO off as well. We enable it by default on glTF materials.

**Comment by pixelflinger** [comment]
of course this doesn't reproduce on our mac.

**Comment by pixelflinger** [comment]
@Francois-Grassard do any of the SSAO parameters affect the result?
What's the "minimum" configuration that causes the issue (most deactivated effects, lowest settings). e.g. no fxaa, msaa, bloom, screen-space reflections, 0-quality, 0-lowpass, no bent normals?

**Comment by OldSnake22** [comment]
I confirm this issue with the Vulkan backend. I have not found any settings combination that affect/reduce/solve this issue for now on my side.

**Comment by Nolram12345** [comment]
Can confirm on Vulkan backend, Windows 10, NV RTX 2060. Any updates on this ?

**Comment by Nolram12345** [comment]
> @Francois-Grassard do any of the SSAO parameters affect the result? What's the "minimum" configuration that causes the issue (most deactivated effects, lowest settings). e.g. no fxaa, msaa, bloom, screen-space reflections, 0-quality, 0-lowpass, no bent normals?

On my end, this problems occurs in any case where SSAO is on. Nothing else seems to affect it. Vulkan backend only.

**Comment by poweifeng** [comment]
Should have been addressed with #6617
