### ISSUE TITLE
There is a touch event that returns information?

### ISSUE THREAD

**Issue by xarlammm** [google/filament#6218]
Is there an event that returns information about a certain part of model, including the name or index of the animation, by clicking on the this part? 
Roughly speaking. There is a shelf with drawers. By clicking on one of the drawers, need to turn on its animation.
3D-viewer (kotlin)

**Comment by xarlammm** [comment]
Thanks for the answer! Yes, I understand that it is necessary to use the API on View. But can't you direct me a little deeper?

**Comment by romainguy** [comment]
The `PickingResult` will return the `Entity` that was clicked, any other information needs to be queried from that. For instance, `FilamentAsset::getName(Entity)` will give you the name of that `Entity` if it came from a glTF.
