### ISSUE TITLE
Picking API latency 

### ISSUE THREAD

**Issue by LionelMyFit** [google/filament#6219]
Hello,
**Describe the bug**
When i use the picking API on Android i have a serious latency (more than 10 seconds) , i call pick() method on each frame on ArCore to detect which renderable is at the center of the screen 

On the video, each triangle (a face) has a different renderable, i display the list of the faces that are detected

[Video](https://www.veed.io/view/f5cde369-d700-446a-8fbf-556dcc5bdd49)

here is my implementation : 

```
val executor = Executors.newSingleThreadExecutor()

            val center = getScreenCenter()

            arCore.filament.view.pick(center.x, center.y, executor, this)
```

**Comment by pixelflinger** [comment]
Do you have a sample app you could provide us with?

Does it happen on all devices? Which devices did you try on?

**Comment by romainguy** [comment]
No response in a while, closing this issue.
