### ISSUE TITLE
Support object picking

### ISSUE THREAD

**Issue by shartte** [google/filament#623]
**Is your feature request related to a problem? Please describe.**
I would like to know which of the entities Filament is rendering is under my cursor.

**Describe the solution you'd like**
I'd like to pass in a screen coordinate (x, y), an entity, and get back whether the visual representation of the given entity covers the given screen coordinate, and also an indication of how far it is away from the screen, so that I can figure out if multiple entities intersect, which one is on top.

**Describe alternatives you've considered**
This can be implemented outside of filament by keeping copies of bounding boxes and geometry around and performing the hit testing against those, but Filament already has the necessary info to speed this up greatly.

Some notes on this:
- Filament maintains AABB's for all entities for the purposes of frustum culling as far as I can tell. There seems no way of accessing these AABBs for the purposes of hit testing.
- There are other approaches for hit testing using separate render passes and assigning unique colors, but it's unclear to me whether that actually performs well or not.
- I'd understand if it's decided that this is outside scope for filament, but having access to the world aligned AABB would at least be nice, since that is already precomputed within filament.

**Comment by romainguy** [comment]
AABBs are a very poor choice for picking. In the past we've used Bullet's collision system for this purpose. I would highly recommend you pursue this solution instead. It will give you fine grained picking and it's easy to use. It also has the benefit of not requiring extra render passes.

**Comment by shartte** [comment]
In my own defense, I only wanted to use the AABB in world space to cull before running a more in-depth picker :)

**Comment by piusogs** [comment]
It is already a since this issue was created, I don't know if my input can still be useful to the author, but I am still going to drop it for the use of people who may have similar problem in the future.

My prefered way of doing object picking is using ray casting with glm library, here is a sample code I wrote while testing filament,
this test for a `Triangle`

`auto mouse_x =  mouseX;
auto mouse_y = h - mouseY;

        glm::vec3 ray_start = glm::unProject(glm::vec3{ mouse_x, mouse_y, 0.0 }, fromFilamentArray(view->getCamera().getModelMatrix().asArray()), fromFilamentArray(view->getCamera().getProjectionMatrix().asArray()), glm::vec4{0, 0, w, h});
        
        glm::vec3 ray_end = glm::unProject(glm::vec3{ mouse_x, mouse_y, 1.0 }, fromFilamentArray(view->getCamera().getModelMatrix().asArray()), fromFilamentArray(view->getCamera().getProjectionMatrix().asArray()), glm::vec4{ 0, 0, w, h });



        auto trans = tcm.getTransform(tcm.getInstance(app.renderable[0].first));
        glm::vec2 pos;
        float dist = 0; 
        glm::vec3 vert0 = glm::vec4{ 1.0f, 0.0f, 0.0f, 0.0f } * fromFilamentArray(trans.asArray());
        glm::vec3 vert1 = glm::vec4{ (float)cos(M_PI * 2 / 3), (float)sin(M_PI * 2 / 3), 0 , 0} * fromFilamentArray(trans.asArray());
        glm::vec3 vert2 = glm::vec4{ (float)cos(M_PI * 4 / 3), (float)sin(M_PI * 4 / 3), 0 , 0} * fromFilamentArray(trans.asArray());
        
        bool w_b = glm::intersectRayTriangle(ray_start, ray_end, vert0, vert1, vert2, pos, dist);

        if (w_b == true) {
            std::cout << "intersect\n";
        }
        else {
            std::cout << "does not intersect\n";
        }`

**Comment by getinfo2012** [comment]
> In my own defense, I only wanted to use the AABB in world space to cull before running a more in-depth picker :)

Hi. Have you found a solution.
I use filament to show gltf(Android & iOS) .  How can I pick up mesh and change the color of mesh?

**Comment by 100espressos** [comment]
@getinfo2012
For changing colors, some options common to renderers include: swap in a different material instance, change [material parameters](https://google.github.io/filament/Materials.html#materialdefinitions/fragmentblock/materialfragmentinputs), use [vertex attributes](https://google.github.io/filament/Materials.html#materialdefinitions/vertexblock/materialvertexinputs)..

To agree with @romainguy, Bullet raycast picking has worked well with other realtime renderers and is flexible and can be tuned, yet is surely one of many options.  If only box precision is needed, it looks like `RenderableManager::getAxisAlignedBoundingBox(instance)` could be part of a solution.

**Comment by MarxMc** [comment]
@romainguy i'm trying to get the "Bounding Box around the 3D Object " with length width and height measurement value.
Is RendereableManager.Builder(1).boundingBox(Box(x,y,z, x/2,y/2,z/2) is the correct  way to achieve that?
