### ISSUE TITLE
EXT_meshopt_compression broke a lot of gltf files

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#6238]
@daemyung it looks like the support for EXT_meshopt_compression broke all gltf exported from sketchfab.

e.g. that's "ship in a bottle"

![Screen Shot 2022-10-28 at 00 28 45](https://user-images.githubusercontent.com/1240896/198529453-32b0958c-f616-4bad-890e-447371557b83.png)

it should look like this:

![Screen Shot 2022-10-28 at 00 29 59](https://user-images.githubusercontent.com/1240896/198529663-8c5e0e1e-f5e5-4ba8-b627-e8be5c008f27.png)

Not sure if I can attach the models here. But it seems to me you can take any model from sketchfab and export as gltf and you'll have this issue.

**Comment by daemyung** [comment]
@pixelflinger Thanks I will also look into this issue.
