### ISSUE TITLE
Android - Filament engine with android.opengl.GLSurfaceView support? 

### ISSUE THREAD

**Issue by sarathsi** [google/filament#627]
Android filament sample apps, use android.view.SurfaceView.
code: uiHelper.attachTo(surfaceView)
Is there any possibility to use android.opengl.GLSurfaceView instead of SurfaceView?

I have tried to use GLSurfaceView, but in FrameCallback doFrame() 
mFilamentRenderer.beginFrame / render / endFrame calls are crashing with 
"A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x58 in tid 15391 (FEngine::loop)"

**Comment by romainguy** [comment]
It's not possible because GLSurfaceView does its own GL management and threading. There is no benefit in using GLSurfaceView with Filament. Did you have a particular reason for this request?

**Comment by sarathsi** [comment]
Thank you for info. I am trying to draw camera feed and few ARCore objects (planes etc) in the background and on top of that objects rendered by filament engine. Now I am trying with one separate GLSurfaceView and one SurfaceView on top. I have tried below things to make SurfaceView transparent, but no success.

In .java:
```
mSurfaceView.setZOrderOnTop(true);
SurfaceHolder sfhHolder = mSurfaceView.getHolder();
sfhHolder.setFormat(PixelFormat.TRANSPARENT);
```

In filament/android/filament-android/src/main/java/com/google/android/filament/Engine.java:
createSwapChain() with flag as transparent (in my understanding from filament/libs/filabridge/include/filament/driver/DriverEnums.h SWAP_CHAIN_CONFIG_TRANSPARENT)

```
    public SwapChain createSwapChain(@NonNull Object surface) {
        return createSwapChain(surface, 1);
    }
```

Please see the attached screenshot. On top (filament rendered triangle) filament’s SurfceView, but without transparency.
![screenshot_filament_arcore](https://user-images.githubusercontent.com/9916029/49898832-b31be500-fe62-11e8-8d77-8c92a09910cb.png)

I would like to know if we can make Filament’s SurfaceView as transparent, so that the background (GLSurfaceView) is visible. 

Also observed a default background color (gray-ish) on SurfaceView. Is it internally drawn by the filament engine?

**Comment by romainguy** [comment]
Let's back up for a bit: why don't you render everything with Filament? You could also use Sceneform (which uses Filament under the hood) to take care of the AR bits for you. Filament is meant to support transparent rendering, but you need to change the clear color to 0,0,0,0.

**Comment by sarathsi** [comment]
Filament.View.setClearColor(0.0f, 0.0f, 0.0f, 0.0f) makes background black. Also tried with other android filament samples. observed the same. Am I missing anything else here?
Need to think about rendering  everything with Filament. It might be less complex if View transparency works, i guess.

About Sceneform, yes we can use these APIs , but we think that Sceneform is not providing APIs to use Filament more extensively in the app.

**Comment by romainguy** [comment]
Sceneform hides Filament Indeed, but it does expose the material system. I'll take a look at transparency and see whether it's broken. It should work :)

**Comment by romainguy** [comment]
Note that you should be using `TRANSLUCENT`, not `TRANSPARENT`.

**Comment by romainguy** [comment]
And `setFormat()` and `setZOrderOnTop()` must be called before adding `SurfaceView` to the window btw. I just tested and it works fine.

**Comment by romainguy** [comment]
I'll write a new sample to show how to do it

**Comment by romainguy** [comment]
See https://github.com/google/filament/pull/629
