### ISSUE TITLE
gltf_viewer's auto scale feature has a bug

### ISSUE THREAD

**Issue by daemyung** [google/filament#6273]
**Describe the bug**
Model isn't rendered.

**To Reproduce**
1. Download [1659601873504btrvruybvkpmtem.glb.zip](https://github.com/google/filament/files/9582155/1659601873504btrvruybvkpmtem.glb.zip)
2. Run gltf_viewer with this file.

**Expected behavior**
Model should be rendered well.

**Screenshots**
<img width="393" alt="image" src="https://user-images.githubusercontent.com/7459074/199903779-c267e0ac-0545-432c-9ed0-140efa0bd5b6.png">

**Additional context**
If I use `--recompute-aabb` then this model is rendered well. I guess `fitIntoUnitCube` has a bug but not sure. Below image is the result that running gltf_view with `--recompute-aabb`.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/7459074/199904176-b429d017-e0e1-437e-b9ed-cc5cdba4eba4.png">

**Comment by romainguy** [comment]
This would happen with scaling if the aabb in the file are wrong (and why recomputing them works).

**Comment by daemyung** [comment]
@romainguy I don't think so. Because AABB in the file is same to the the result of recomputing bounding boxes. The different between two cases are the world matrix when the asset's bounding box is calculated.

**Comment by romainguy** [comment]
The AABBs in your screenshots are completely different though?

**Comment by daemyung** [comment]
> The AABBs in your screenshots are completely different though?

Yes because AABB in screenshots are multiplied with the world transform. I mean that AABBs(raw) in file are same.

**Comment by daemyung** [comment]
@romainguy Sorry you are right. This file has wrong AABB. Thanks.
