### ISSUE TITLE
【Android】gltf resource cannot be properly loading with asyncBeginLoad api on io thread

### ISSUE THREAD

**Issue by dandingol03** [google/filament#6278]
**Describe the bug**

**Gltf resource** cann't be asynchronously loading with `asyncBeginLoad` on a io thread, there is few minutes stuck before the gltf resouces being loaded comletely. Because I need to deal with some camera texture on the camera thread, so `filament` is created and rendered in io thread. I saw the comment in `ResourceLoader.java`, it seems like the `asyncUpdateLoad` is trying to  update an asynchronous load by performing any pending work that must take place on the main thread. So theses async api are only worked in the main thread? 

I open the android studio profiler to record the cpu cost. The `FEngine::loop ` takes nearly 1s to finish its job. I can't figure out why, need some help~

![image](https://user-images.githubusercontent.com/13013579/200533571-7754129f-2513-47b9-9900-65564cec7d19.png)

**To Reproduce**
1. call `asyncBeginLoad` and `asyncUpdateLoad` on io thread

**Expected behavior**
gltf resouce be asynchronously loaded

**Smartphone (please complete the following information):**
 - Device: [SAMSUNG 20]
 - OS: [e.g. Android 11]

**Comment by pixelflinger** [comment]
I am not sure I understand what the problem or question is.

**Comment by pixelflinger** [comment]
Please reopen with more information, maybe a sample case. I do not understand the problem as it is.
