### ISSUE TITLE
native crash on filament-android

### ISSUE THREAD

**Issue by arestory** [google/filament#6283]
**Describe the bug**
load glb model crash only happend in 64bits apks but not 32bits

**Logs**

11-09 14:35:55.235  6388  6388 E hwbr_engine_crashpad: ../../third_party/crashpad/crashpad/util/linux/scoped_ptrace_attach.cc:45: ptrace: Operation not permitted (1)
--------- beginning of crash
11-09 14:35:55.253  5855  6384 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7c27c4b2f4 in tid 6384 (FEngine::loop), pid 5855 (com.pp.pp)
11-09 14:35:55.282   799   799 E Thermal-daemon:hw_thermal: [mtk 4G pa] tempNew :29  tempOld :28
11-09 14:35:55.283   799   799 E Thermal-daemon:hw_thermal: Report temperature: [mtk 4G pa] temp :29  reportThreshold:1
11-09 14:35:55.283   799   799 E Thermal-daemon:hw_thermal: [mtk chg] tempNew :32  tempOld :33
11-09 14:35:55.283   799   799 E Thermal-daemon:hw_thermal: Report temperature: [mtk chg] temp :32  reportThreshold:1
11-09 14:35:55.344   812   851 E libprocessgroup: set_timerslack_ns write failed: Permission denied
11-09 14:35:55.345   812   851 E libprocessgroup: set_timerslack_ns write failed: Permission denied
11-09 14:35:55.358  6391  6391 E crash_dump64: failed to interrupt 5855 to detach: No such process
11-09 14:35:55.375  2024  2298 E SmartDualCardConfig: getSignalLevelPoorThreshold fail,invalid params
11-09 14:35:55.494  6391  6391 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-09 14:35:55.495  6391  6391 F DEBUG   : Build fingerprint: 'HONOR/NZA-AL00/HNNZA-M1:10/HONORNZA-AL00/4.0.0.160C00:user/release-keys'
11-09 14:35:55.495  6391  6391 F DEBUG   : Revision: '0'
11-09 14:35:55.495  6391  6391 F DEBUG   : ABI: 'arm64'
11-09 14:35:55.495  6391  6391 F DEBUG   : Timestamp: 2022-11-09 14:35:55+0800
11-09 14:35:55.495  6391  6391 F DEBUG   : pid: 5855, tid: 6384, name: FEngine::loop  >>> com.pp.pp <<<
11-09 14:35:55.495  6391  6391 F DEBUG   : uid: 10266
11-09 14:35:55.495  6391  6391 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7c27c4b2f4
11-09 14:35:55.496  6391  6391 F DEBUG   :     x0  0000007c07ebe210  x1  0000007c2d1f8500  x2  0000007c2d1f8400  x3  0000007c07ebe210
11-09 14:35:55.496  6391  6391 F DEBUG   :     x4  0000000000000001  x5  0000000000000001  x6  0000007c2d1f819c  x7  0000000000000000
11-09 14:35:55.496  6391  6391 F DEBUG   :     x8  0000007c07c97e00  x9  0000000007ffffff  x10 00000000ffffffff  x11 0000007c27c49ffc
11-09 14:35:55.496  6391  6391 F DEBUG   :     x12 0000000000000001  x13 0000000000000001  x14 6fffffffffffffff  x15 0000040000000001
11-09 14:35:55.496  6391  6391 F DEBUG   :     x16 0000000000000001  x17 0000007c06db1840  x18 0000007c0c904000  x19 0000007c07c4a000
11-09 14:35:55.496  6391  6391 F DEBUG   :     x20 0000000000000000  x21 0000007c72d33810  x22 00000000ffffffff  x23 0000007c2ddd2794
11-09 14:35:55.496  6391  6391 F DEBUG   :     x24 0000007c07ebe210  x25 0000000000000000  x26 0000007c72d33810  x27 0000007c08024390
11-09 14:35:55.496  6391  6391 F DEBUG   :     x28 0000000000000001  x29 0000007c2d1f8760
11-09 14:35:55.496  6391  6391 F DEBUG   :     sp  0000007c2d1f8260  lr  0000007cf6870260  pc  0000007cf68703c0
11-09 14:35:55.497  6391  6391 F DEBUG   :
11-09 14:35:55.497  6391  6391 F DEBUG   : backtrace:
11-09 14:35:55.497  6391  6391 F DEBUG   :       #00 pc 00000000000983c0  /vendor/lib64/libusc.so (BuildId: eb979b3c6d03c407e549912c4cb7e0a2)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #01 pc 00000000000aa678  /vendor/lib64/libusc.so (BuildId: eb979b3c6d03c407e549912c4cb7e0a2)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #02 pc 000000000009fe4c  /vendor/lib64/libusc.so (BuildId: eb979b3c6d03c407e549912c4cb7e0a2)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #03 pc 000000000009e2f0  /vendor/lib64/libusc.so (BuildId: eb979b3c6d03c407e549912c4cb7e0a2)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #04 pc 000000000000aa74  /vendor/lib64/libusc.so (PVRUniFlexCompileToHw+4552) (BuildId: eb979b3c6d03c407e549912c4cb7e0a2)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #05 pc 000000000008b898  /vendor/lib64/libglslcompiler.so (BuildId: 5e71df60de5ef3a5ba976a873ac94749)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #06 pc 000000000009f47c  /vendor/lib64/libglslcompiler.so (GLSLCompileToUniflex+1464) (BuildId: 5e71df60de5ef3a5ba976a873ac94749)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #07 pc 00000000000696fc  /vendor/lib64/egl/libGLESv2_mtk.so (BuildId: 0c8d568004cc66fec7f39297313f2b6f)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #08 pc 00000000000692bc  /vendor/lib64/egl/libGLESv2_mtk.so (BuildId: 0c8d568004cc66fec7f39297313f2b6f)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #09 pc 000000000007efec  /vendor/lib64/egl/libGLESv2_mtk.so (glCompileShader+124) (BuildId: 0c8d568004cc66fec7f39297313f2b6f)
11-09 14:35:55.497  6391  6391 F DEBUG   :       #10 pc 0000000000128130  /data/app/com.pp.pp-x4QlnYf8ooVvcnI_Cf8xsQ==/lib/arm64/libfilament-jni.so (BuildId: 566f8cb854d0326e1c1af97cea1dd2f3831c599b)
11-09 14:35:56.132  1407  1677 E WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.957) failed {.code = ERROR_NOT_SUPPORTED, .description = }
11-09 14:35:56.848  1407  6396 E ZrHung.AppEyeFocusWindow: NFW check!
 

**Smartphone (please complete the following information):**
 - Device: [honor 5T play]
 - OS: [android 10]

**Comment by romainguy** [comment]
The crash happens in the GPU driver, more specifically in its shader compiler. There isn't much we can do about this unfortunately.

**Comment by arestory** [comment]
> 

but why didn't crash in 32bits apk?

**Comment by arestory** [comment]
> The crash happens in the GPU driver, more specifically in its shader compiler. There isn't much we can do about this unfortunately.

but why didn't crash in 32bits apk?

**Comment by pixelflinger** [comment]
Please provide more information about which Android device / chipset / gpu this is.
