### ISSUE TITLE
cmake subdirectory support

### ISSUE THREAD

**Issue by jwinarske** [google/filament#6285]
**Is your feature request related to a problem? Please describe.**

When using the filament folder/project from an upper level CMake project, it looks for launch-c and launch-cxx in the root build folder.

```
add_subdirectory(filament)
```

**Describe the solution you'd like**
Path in CMake selecting the launch scripts needs adjusting.  Workaround is to copy scripts from binary subfolder to binary root, and mark for execution.

**Describe alternatives you've considered**
NA

**OS and backend**
Agnostic

**Comment by pixelflinger** [comment]
Are you able to put a PR up?
