### ISSUE TITLE
Skybox flickers, Android

### ISSUE THREAD

**Issue by sdpopov-keyvariable** [google/filament#6291]
When skybox background is provided, it flickers.

No renderables, only skybox and indirect light:
https://user-images.githubusercontent.com/63736629/201417148-4b0d37ca-7e80-4e6e-94d6-a4c6b40a7322.mov

Skybox, indirect light, single object:
https://user-images.githubusercontent.com/63736629/201417200-e6a52f23-04d2-4c89-89b9-efca2310916f.mov

Gray skybox:
```
Skybox.Builder()
    .color(color)
    .build(engine)
```

Image skybox:
```
Skybox.Builder()
    .environment(texture_R11F_G11F_B10F)
    .intensity(intensity)
    .build(engine)
```

**To Reproduce**
Just start an application with a skybox background on specific device and Filament 1.24.0+.

**Expected behavior**
No flickering of skybox background.

**Logs**
> Filament                I  FEngine resolved backend: OpenGL
> Filament                V  [Imagination Technologies], [PowerVR Rogue GE8322], [OpenGL ES 3.2 build 1.10@5187610], [OpenGL ES GLSL ES 3.20 build 1.10@5187610]
> Filament                V  Feature level: 2
> Filament                I  FEngine feature level: 2

**Smartphone (please complete the following information):**
 - Device: Prestigio GRACE 4791 4G (PMT4791_4G_D).
 - OS: Android 9, up to date.

**Additional context**
It's OK on Filament 1.23.1, 1.22.2. Bug is in Filament 1.24.0, 1.25.4, 1.28.2.

**Comment by pixelflinger** [comment]
This seems specific to PowerVR Rogue GE8322.

**Comment by pixelflinger** [comment]
@sdpopov-keyvariable could you try the vulkan backend and let us know if the problem presists?

**Comment by pixelflinger** [comment]
not really actionable at this point.
