### ISSUE TITLE
Docs: mistake in "Importance sampling for the IBL" section

### ISSUE THREAD

**Issue by htlpt** [google/filament#6294]
**Describe the bug**
Mistake in the Jacobian of transform between distributions (missing a reciprocal）

Maybe a terminology problem ?

**To Reproduce**
1. Go to [9.2 Importance sampling for the IBL](https://google.github.io/filament/Filament.html#toc9.2)
2. equation 126, 127

**Screenshots**
![image](https://user-images.githubusercontent.com/25838728/201461901-8775a549-2ee5-44b1-b9c8-f631a9336055.png)

**Expected behavior**
Eq.126 :
![image](https://user-images.githubusercontent.com/25838728/201461295-3f2550cf-5b07-4f13-aed4-13c449451262.png)

Eq.127:
![image](https://user-images.githubusercontent.com/25838728/201461648-e3c5e242-522c-4db8-a020-3f8103e59809.png)

**Additional context**
some references:

[1] Physically Based Rendering, Third Edition 13.5.1
![image](https://user-images.githubusercontent.com/25838728/201461228-8690542b-77c4-4988-a7a5-34f9eed51e90.png)

[2] Microfacet Models for Refraction through Rough Surfaces, EGSR 2007

Jacobian of transformation from l->h is shown, h->l should be the reciprocal

![3}4EGR~Q`7@@ 8%MGV`54PY](https://user-images.githubusercontent.com/25838728/201461566-f952ee59-6f56-488c-ae8e-fb0249841fdb.png)

**Comment by htlpt** [comment]
also in 5.3.4.2.2 "Discrete Domain", the pdf is missing a "4"
![image](https://user-images.githubusercontent.com/25838728/201475119-782994ab-6741-4eaa-bf01-c320364f2eac.png)

![image](https://user-images.githubusercontent.com/25838728/201475068-b4d026a2-7f7e-40d5-854a-de0710f1bdbc.png)

**Comment by romainguy** [comment]
Thanks, those look like omissions/typos indeed.
