### ISSUE TITLE
【IOS】Error when running ios demo on the simulator

### ISSUE THREAD

**Issue by dandingol03** [google/filament#6295]
**Describe the bug**
Compiling Ios demo failed with `./build.sh -i -s -p ios debug` when running on the simulator

**To Reproduce**
1. `./build.sh -i -p desktop  release`
2.   `./build.sh -i -s -p ios debug`
3.  run any ios demo on **MAC M1**

**Logs**
ld: warning: directory not found for option '-L../../../out/ios-debug/filament/lib/universal'
ld: in ../../../out/ios-debug/filament/lib/arm64/libimage.a(KtxBundle.cpp.o), building for iOS Simulator, but linking in object file built for iOS,
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Desktop (please complete the following information):**
 - OS: [MAC M1]
 - Backend: [Metal]

**Comment by bejado** [comment]
You need the `-l` flag when building for M1 devices:

```
    -l
        Build arm64/x86_64 universal libraries.
        For iOS, this builds universal binaries for devices and the simulator (implies -s).
        For macOS, this builds universal binaries for both Apple silicon and Intel-based Macs.
```
