### ISSUE TITLE
Shadows on unlit plane and contact shadows

### ISSUE THREAD

**Issue by midskavid** [google/filament#6304]
My setup has two overlapping unlit shadow receiver planes. The scene is lit by an IBL and a directional overhead light. When an object is placed on top, shadow is casted onto both the planes. 
![Screen Shot 2022-11-16 at 6 00 28 PM](https://user-images.githubusercontent.com/6920477/202506677-82b5da09-c27d-472c-85e7-f05f97f730eb.png)

Material for the unlit planes is as 

```
material {
  name : shadowRec,
  parameters : [ 
    {
      type : float,
      name : transparency
    }
  ],
  shadingModel : unlit,
  blending : transparent,
  shadowMultiplier: true,
  variantFilter : [ skinning ],
  depthWrite: false
}

fragment {
  void material(inout MaterialInputs material) {
    prepareMaterial(material);
    float alpha = saturate(1.0 - materialParams.transparency);
	material.baseColor = float4(0.0f, 0.0f, 0.0f, alpha);
  }
}
```
How can I avoid this? Ideally, I would want the shadow only on the plane on which the object resides.

Also, I was trying out contact shadows to see if this can be avoided, but I could not see any difference on the shadows being cast on the unlit planes. I set `setScreenSpaceContactShadows` for the instance and `screenSpaceContactShadows` for the directional light. Am I missing something or contact shadows do not work with unlit material?

**Comment by romainguy** [comment]
Contact shadows are not supported on unlit planes. And shadows will be cast on all unlit planes.
