### ISSUE TITLE
what causes the android app to crash

### ISSUE THREAD

**Issue by yygbruce** [google/filament#6309]
I AdrenoGLES-0: QUALCOMM build : 9b824c0bed, I6c7bff0fbd
I AdrenoGLES-0: Build Date : 10/09/21
I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.15
I AdrenoGLES-0: Local Branch :
I AdrenoGLES-0: Remote Branch :
I AdrenoGLES-0: Remote Branch :
I AdrenoGLES-0: Reconstruct Branch :
I AdrenoGLES-0: Build Config : S P 10.0.7 AArch64
I AdrenoGLES-0: Driver Path : /vendor/lib64/egl/libGLESv2_adreno.so
I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
E project.exampl: open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
I Filament: FEngine (64 bits) created at 0x71052ee000 (threading is enabled)
D Filament: Using ASurfaceTexture
I Filament: FEngine resolved backend: OpenGL
D DecorView[]: onWindowFocusChanged hasWindowFocus true
V Filament: [Qualcomm], [Adreno (TM) 618], [OpenGL ES 3.2 V@0502.0 (GIT@9b824c0bed, I6c7bff0fbd, 1633761551) (Date:10/09/21)], [OpenGL ES GLSL ES 3.20]
V Filament: Feature level: 2
V Filament: Active workarounds:
V Filament: dont_use_timer_query
V Filament: disable_sidecar_blit_into_texture_array
V Filament: split_easu
V Filament: invalidate_end_only_if_invalidate_start
V Filament: allow_read_only_ancillary_feedback_loop
V Filament: enable_initialize_non_used_uniform_array
I Filament: FEngine feature level: 2
F libc : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x91 in tid 11168 (FEngine::loop), pid 11113

**Comment by romainguy** [comment]
You are trying to load a library that's not there: dlopen failed: library "libmigui.so" not found

**Comment by yygbruce** [comment]
> You are trying to load a library that's not there: dlopen failed: library "libmigui.so" not found

I don't think so.Maybe this line cause the crash--"F libc : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x91 in tid 11168 (FEngine::loop), pid 11113".
