### ISSUE TITLE
The attachSkin model is disappeared sometimes 

### ISSUE THREAD

**Issue by TedHsieh7** [google/filament#6310]
Hi, I use the interface `attachSkin` in the `FilamentInstance` to bind the face renderable to the character model. However, I met some problems and need help on how to use `attachSkin` interface.

I have two `gltf` resources, one is the [character](https://drive.google.com/file/d/1GUyYZ_hYOLzGphnp62ljgybhi1IJQWr0/view?usp=share_link) and the other one is [face](https://drive.google.com/file/d/1nmjImK4EROsGMCERRuVdy1CCAwLZ8ovl/view?usp=share_link). They share some bones and I attach the renderable whose name is `Arachi_face_A_SHoff` of `face` model to the first skin of `character` model through the `ModelViewer` I modified to show multiple model with same `Engine` ,`View` , `Renderer`, `Camera` and `Scene`

**The Code Snippet**
```kotlin
        lifecycleScope.launch(Dispatchers.IO) {
            val modelViewer = modelViewer ?: return@launch
            val modelByteBuffer = loadModelAsset(MAIN_FOLDER, MODEL_NAME)

            val mainModelName = "main"
            val subModelName = "sub"

            val mainAsset = modelViewer.modelManager.loadModelGltfAsync(mainModelName, modelByteBuffer) { fileName ->
                loadModelAsset(MAIN_FOLDER, fileName)
            }

            val subByteBuffer = loadModelAsset(SUB_FOLDER, MODEL_NAME)
            val subAsset = modelViewer.modelManager.loadModelGltfAsync(subModelName, subByteBuffer) { fileName ->
                loadModelAsset(SUB_FOLDER, fileName)
            }

            withContext(Dispatchers.Main) {
                modelViewer.addModelToScene(mainAsset)
                modelViewer.transformModelToUnitCube(mainAsset)
                modelViewer.addModelToScene(subAsset)

                subAsset?.getFirstEntityByName("Arachi_face_A_SHoff")?.let { entity ->
                    mainAsset?.instance?.attachSkin(0, entity)
                }
            }
        }
```

**Describe the bug**
1. The `face` renderable may be disappeared while perform `Gesture.ORBIT` by `GestureDetector` and here is reference [video](https://drive.google.com/file/d/1zMqn-HvmD7J0fUIXFjJub1Ww4itbl_t4/view?usp=share_link)

**To Reproduce**

1. render the two gltf resources mentioned above2. 
2. attach the face to the first skin of the `character`
3. perform the `Gesture.ORBIT` by `GestureDetector`
 
**Expected behavior**
The face is always rendered on the screen.

**Logs**
```
2022-11-21 11:00:10.415 24097-24097/com.filament.sample I/Filament: FEngine (64 bits) created at 0x7bab7d4680 (threading is enabled)
2022-11-21 11:00:10.416 24097-28657/com.filament.sample D/Filament: Using ASurfaceTexture
2022-11-21 11:00:10.416 24097-28657/com.filament.sample I/Filament: FEngine resolved backend: OpenGL
2022-11-21 11:00:10.417 24097-28657/com.filament.sample V/Filament: [Qualcomm], [Adreno (TM) 660], [OpenGL ES 3.2 V@0530.0 (GIT@b25f720, I2fb6e682e6, 1631580237) (Date:09/14/21)], [OpenGL ES GLSL ES 3.20]
2022-11-21 11:00:10.417 24097-28657/com.filament.sample V/Filament: Feature level: 2
    Active workarounds: 
    dont_use_timer_query
    disable_sidecar_blit_into_texture_array
    split_easu
    invalidate_end_only_if_invalidate_start
    allow_read_only_ancillary_feedback_loop
    enable_initialize_non_used_uniform_array
2022-11-21 11:00:10.418 24097-24097/com.filament.sample I/Filament: FEngine feature level: 2

```

**Smartphone (please complete the following information):**
 - Device: [SAMSUNG S21]
 - OS: [Android 12]

**Comment by bejado** [comment]
The first thing that comes to mind is to check that the bounding boxes of the renderables are set correctly. Maybe the face is getting culled from some vantage points.

**Comment by TedHsieh7** [comment]
Hi @bejado , thanks for the hint. I found this issue seems to be fixed if apply `transformModelToUnitCube` on the `face` model first then attach it to the first skin of `character` model. Wondering if it implies there are some things wrong in the models or just miss this function call in the original code snippet.

**Code Snippet Works**
```Kotlin
lifecycleScope.launch(Dispatchers.IO) {
            val modelViewer = modelViewer ?: return@launch
            val modelByteBuffer = loadModelAsset(MAIN_FOLDER, MODEL_NAME)

            val mainModelName = "main"
            val subModelName = "sub"

            val mainAsset = modelViewer.modelManager.loadModelGltfAsync(mainModelName, modelByteBuffer) { fileName ->
                loadModelAsset(MAIN_FOLDER, fileName)
            }

            val subByteBuffer = loadModelAsset(SUB_FOLDER, MODEL_NAME)
            val subAsset = modelViewer.modelManager.loadModelGltfAsync(subModelName, subByteBuffer) { fileName ->
                loadModelAsset(SUB_FOLDER, fileName)
            }

            withContext(Dispatchers.Main) {
                modelViewer.addModelToScene(mainAsset)
                modelViewer.transformModelToUnitCube(mainAsset)
                // Add this line seems the issue fixed
                modelViewer.transformModelToUnitCube(subAsset)
                modelViewer.addModelToScene(subAsset)

                subAsset?.getFirstEntityByName("Arachi_face_A_SHoff")?.let { entity ->
                    mainAsset?.instance?.attachSkin(0, entity)
                }
            }
        }
```

**Comment by dandingol03** [comment]
there is  some bug after enable animation

**Comment by dandingol03** [comment]
@prideout Hi, Philip. Can you give a demo about how to use `attachskin` to achieve the bone-binding function? Thanks
