### ISSUE TITLE
android crash(enter background)

### ISSUE THREAD

**Issue by pjinsinan** [google/filament#6317]
**Describe the bug**
run the filament android app in the foreground, then enter background, the filament reports: 
"OpenGL error 0x505 (GL_OUT_OF_MEMORY) in "clearWithRasterPipe" at line 3089"
"KHR_debug ERROR: Error:glClearBufferfv::failed to allocate CPU memory"
and then the app crash

I guess when the app enter background, the android surface is destroyed, and the render thread still run for a while ? I also stop the filament update when the app enter background 

**To Reproduce**
1. ...

**Expected behavior**
not report gl errors

**Screenshots**
![image](https://user-images.githubusercontent.com/5959808/203462995-12e18539-e282-48e3-b549-6fd31683bcbd.png)

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: android
 - GPU:  [ARM], [Mali-G76], [OpenGL ES 3.2 v1.r18p0-01rel0.121c9f78148a7ea432bdcc66415bf8a1], [OpenGL ES GLSL ES 3.20]
 - Backend: opengl

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
The surface shouldn't be destroyed unless you app does so. Looks like it could be an actual OOM too.

**Comment by pjinsinan** [comment]
> 

sorry, I don't know how to make the android SurfaceView not be destroyed, as I know when the app enter the background,  the android SurfaceView will be destroyed by app automatically,  for example the function "public void surfaceDestroyed(@NonNull SurfaceHolder holder) " will be called automatically
