### ISSUE TITLE
Compiler command about "MATC_OPT_FLAGS" makes renderer texture low quality

### ISSUE THREAD

**Issue by zhangbo-0213** [google/filament#6344]
**Describe the bug**
when set the material compilation disable, the renderer texture looks normal:(see the floor and the edge of bricks)
![IMG_2439](https://user-images.githubusercontent.com/22340624/205212827-407fdeae-cffa-4712-881a-2f25a9aae934.jpg)

but when set the material compilation enable, texture looks blur and there is aliasing at the edge of bricks: 
![IMG_2440](https://user-images.githubusercontent.com/22340624/205213284-0233679d-2d63-42c4-85cd-103e042c461f.jpg)

is there any mistakes with material optimizations?  

**To Reproduce**
set MATC_OPT_FLAGS, enable optimization:
<img width="773" alt="截屏2022-12-02 12 16 28" src="https://user-images.githubusercontent.com/22340624/205213687-9b43196f-cadb-45fd-8440-d48ccc587262.png">

**Expected behavior**
after optimization, renderer texture should have higher quality

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.1
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: IOS 16.0

with Filament 1.28.0

**Comment by romainguy** [comment]
Material optimization has nothing to do with texture sampling. It looks like you are doing unfiltered sampling in the second screenshot? Also where are you setting those flags? In your own CMake?

**Comment by zhangbo-0213** [comment]
> 

yes, in the CmakeLists.txt at the root directory of source code , just change the here "494  set (MATC_OPT_FLAGS -gd)", and has the different results

**Comment by romainguy** [comment]
seems like a bug with spirv-opt.

**Comment by bejado** [comment]
@zhangbo-0213 can you try setting the texture sampler precision to `highp` (the default is `mediump`) and see if it fixes the issue you're seeing? See [my extended answer](https://github.com/google/filament/discussions/6353#discussioncomment-4470899) here for more information.

**Comment by zhangbo-0213** [comment]
> @zhangbo-0213 can you try setting the texture sampler precision to `highp` (the default is `mediump`) and see if it fixes the issue you're seeing? See [my extended answer](https://github.com/google/filament/discussions/6353#discussioncomment-4470899) here for more information.

Thanks, I try to set the texture sampler precision to highp and  get the same result  with disabled mat opt

**Comment by bejado** [comment]
@zhangbo-0213 Cool, so to confirm, this fixes the issue you're seeing?
