### ISSUE TITLE
KHR_debug PERFORMANCE error messages 

### ISSUE THREAD

**Issue by Theo-Y** [google/filament#6345]
**Describe the bug**

When running the sample on such an pixel3a or pocophone f1 in debug mode, the following error messages are displayed.
but no problem with rendering. Can I ignore these messages?

`KHR_debug PERFORMANCE: EsxBufferObject::Map - Ignoring EsxBufferMapUnsyncedBit`
`KHR_debug PERFORMANCE: Namespace collision detected, using slow path`

**To Reproduce**
If you run the android sample on pixel3a or pocophon F1 in debug mode, you may encounter this error messages.

**Expected behavior**
No error message.

**Screenshots**

**Logs**
`KHR_debug PERFORMANCE: EsxBufferObject::Map - Ignoring EsxBufferMapUnsyncedBit`
`KHR_debug PERFORMANCE: Namespace collision detected, using slow path`

**Desktop (please complete the following information):**
 - OS: Android
 - GPU: Adreno630, Adreno615
 - Backend: OpenGL

**Smartphone (please complete the following information):**
 - Device: Pixel3a, Pocophone F1
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
You can ignore those. Some of these messages were disabled in later driver versions, and some of the performance debug messages are incorrect.

**Comment by Theo-Y** [comment]
Thank you for answer @romainguy
