### ISSUE TITLE
Why are most third party libs not installed?

### ISSUE THREAD

**Issue by apriori** [google/filament#6350]
Hello, I checked out the latest release 1.29 under windows and was surprised that it did not contain many of the used third party libraries and headers. E.g. bluegl is available as a library, but not its headers. Or filagui is completely missing. Can these non-core libraries be added to the cmake install step among all its dependencies? Fishing them out of the source and build directory is cumbersome.

**Comment by romainguy** [comment]
Libraries like bluegl are installed without headers because they are not intended for use outside of Filament's internals. Libraries like filagui are not required by Filament itself and only used for internal development purposes and not intended to be used as public libraries.
