### ISSUE TITLE
Build fails on windows with clang 6.0 and visual studio 2015

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#637]
I followed the windows install instructions and the build fails with the latest source files with this error: 

"C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\TNT.sln" (material_sandbox target) (1) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\samples\material_sandbox.vcxproj.metaproj"
       (default target) (2) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\samples\common-resources.vcxproj.metaproj"
       (default target) (12) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\tools\filamesh\filamesh.vcxproj.metaproj" (
       default target) (43) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\libs\filameshio\filameshio.vcxproj.metaproj
       " (default target) (46) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\third_party\meshoptimizer\meshoptimizer.vcx
       proj.metaproj" (default target) (47) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\third_party\meshoptimizer\meshoptimizer.vcx
       proj" (default target) (66) ->
       (ClCompile target) ->
         clang-cl.exe : error : argument unused during compilation: '/Gm-' [-Werror,-Wunused-command-line-argument] [C:
       \Users\Sean\Documents\Projects\engines\filament\out\cmake-release\third_party\meshoptimizer\meshoptimizer.vcxpro
       j]

       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\TNT.sln" (material_sandbox target) (1) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\samples\material_sandbox.vcxproj.metaproj"
       (default target) (2) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\libs\filagui\filagui.vcxproj.metaproj" (def
       ault target) (15) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\tools\matc\matc.vcxproj.metaproj" (default
       target) (25) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\tools\matc\matc.vcxproj" (default target) (
       83) ->
       (Link target) ->
         filamat.lib(CodeGenerator.obj) : error LNK2019: unresolved external symbol SHADERS_PACKAGE referenced in funct
       ion "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl filamat::CodeGenerator::gen
       erateProlog(class std::basic_ostream<char,struct std::char_traits<char> > &,enum filament::driver::ShaderType,bo
       ol)const " (?generateProlog@CodeGenerator@filamat@@QEBAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV34@W
       4ShaderType@driver@filament@@_N@Z) [C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\tools\ma
       tc\matc.vcxproj]
         C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\tools\matc\Release\matc.exe : fatal error
       LNK1120: 1 unresolved externals [C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\tools\matc\
       matc.vcxproj]

    727 Warning(s)
    3 Error(s)

I tried clang 7 but cmake cant even detect clang compiler and chooses msvc compiler instead.  I also tried visual studio 2017 and get the same error. Please let me know how to fix this.

**Comment by romainguy** [comment]
It looks like the resgen step for the shaders didn't run. @bejado can you please take a look?

**Comment by thirdmenson** [comment]
Thanks for the quick response guys.  I will try to build with ninja tomorrow and let you know. However I have been using visual studio for a project and wanted to integrate your amazing renderer. It would be great if we could fix build on visual studio :)

**Comment by shartte** [comment]
@thirdmenson  You can build the lib with Ninja, and use the compiled libraries with your visual studio project.

**Comment by thirdmenson** [comment]
I tried building using Ninja but I get this error : 

`C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release>cmake ../.. -G Ninja -DCMAKE_CXX_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER:PATH="C:\Program Files\LLVM\bin\lld-link.exe" -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files/LLVM/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Sean/Documents/Projects/engines/filament/out/cmake-release/CMakeFiles/CMakeTmp

    Run Build Command:"C:/Project/Ninja/ninja.exe" "cmTC_70124"
    [1/2] Building C object CMakeFiles\cmTC_70124.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_70124.exe
    FAILED: cmTC_70124.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_70124.dir --manifests  -- C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo CMakeFiles\cmTC_70124.dir\testCCompiler.c.obj  /out:cmTC_70124.exe /implib:cmTC_70124.lib /pdb:cmTC_70124.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_70124.dir/manifest.res CMakeFiles\cmTC_70124.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:9 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Sean/Documents/Projects/engines/filament/out/cmake-release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Sean/Documents/Projects/engines/filament/out/cmake-release/CMakeFiles/CMakeError.log".`

However I do see you have a potential fix for the visual studio build issue. I will check it out once it is the master branch. Thanks guys !

**Comment by bejado** [comment]
@thirdmenson Make sure you're using a VS2015 x64 Native Tools Command Prompt, even though you're building with Ninja. That being said, yes, the fix will be merged in master soon. I prefer using Ninja though, seems to be significantly faster than Visual Studio.

Also, thought I'd point out that if you're working on a project that uses Filament and not Filament itself, you could also use our [pre-compiled binaries](https://github.com/google/filament/releases) so you don't need to compile Filament.

**Comment by bejado** [comment]
Fix is in master- feel free to reopen if you still experience problems.

**Comment by thirdmenson** [comment]
I may have to modify source code depending, hence need to be able to build filament. 
 
I got the latest source from master and now that specific error we saw before seems to be gone but build is still failing with this error:

clang-cl.exe : error : argument unused during compilation: '/Gm-' [-Werror,-Wunused-command-line-argument] [C:\U
       sers\Sean\Documents\Projects\engines\filament\out\cmake-release\third_party\meshoptimizer\meshoptimizer.vcxproj]


`  C:\Users\Sean\Documents\Projects\engines\filament\libs\filagui\src\ImGuiHelper.cpp(205,26): warning : unused v
       ariable 'required' [-Wunused-variable] [C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\libs
       \filagui\filagui.vcxproj]


       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\TNT.sln" (material_sandbox target) (1) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\samples\material_sandbox.vcxproj.metaproj"
       (default target) (2) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\samples\common-resources.vcxproj.metaproj"
       (default target) (12) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\tools\filamesh\filamesh.vcxproj.metaproj" (
       default target) (42) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\libs\filameshio\filameshio.vcxproj.metaproj
       " (default target) (44) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\third_party\meshoptimizer\meshoptimizer.vcx
       proj.metaproj" (default target) (45) ->
       "C:\Users\Sean\Documents\Projects\engines\filament\out\cmake-release\third_party\meshoptimizer\meshoptimizer.vcx
       proj" (default target) (65) ->
       (ClCompile target) ->
         clang-cl.exe : error : argument unused during compilation: '/Gm-' [-Werror,-Wunused-command-line-argument] [C:
       \Users\Sean\Documents\Projects\engines\filament\out\cmake-release\third_party\meshoptimizer\meshoptimizer.vcxpro
       j]

    741 Warning(s)
    1 Error(s)`
