### ISSUE TITLE
Readme outdated for VS 2017

### ISSUE THREAD

**Issue by Tenebralus** [google/filament#638]
Seems the readme has wrong information about creating a build for VS 2017. I'm talking about this part:
https://gyazo.com/fcce3c02e8c067e0479c929e058d2e85

Could you change requirements from Clang 6 to Clang 7 and change line
cmake -T"LLVM-vs2014" -G "Visual Studio 14 2015 Win64" ../..
to
cmake -T"LLVM" -G "Visual Studio 15 2017 Win64" ../..

Or just add separate 2017 instructions apart from the 2015 ones

It took me quite a while to figure out how to create the build for VS 2017 :)

**Comment by romainguy** [comment]
It should be an addition, not a replacement. We still rely on VS2015.

**Comment by Tenebralus** [comment]
Are you going to upgrade to VS 2017? 
Because when I try to download VS 2015 from the official website  I get the "Sorry, we couldn't find any downloads for you." message, so I think I would not be able to downgrade anymore. That and more and more people are using VS 2017 these days, so I think it would be useful to add a separate tutorial for VS 2017 or to upgrade to 2017.

**Comment by romainguy** [comment]
According to https://github.com/google/filament/issues/639#issuecomment-447593083 the README should say this for VS 2017:

```
cmake -T"LLVM" -G "Visual Studio 15 2017 Win64" -DCMAKE_CXX_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER:PATH="C:\Program Files\LLVM\bin\lld-link.exe" ../..
```
