### ISSUE TITLE
Using FinalizationRegistry to call delete() in JS samples

### ISSUE THREAD

**Issue by hanseuljun** [google/filament#6404]
**Is your feature request related to a problem? Please describe.**
In filament-js samples, delete() is being called manually for wasm-based instances. How about using FinalizationRegistry to make these delete() calls happen automatically?

ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry

In case FinalizationRegistry is not being used for a reason, it would be very helpful for me if I can learn why.

**Describe the solution you'd like**
When creating the wasm-based instances in JS samples, register them to a FinalizationRegistry.

**Describe alternatives you've considered**
Keep calling delete()s.

**OS and backend**
No.

**Comment by romainguy** [comment]
It's not used simply because our JavaScript (and Java) bindings closely mirror our C++ API. There's no reason not to make use of the finaliser registry though.

**Comment by romainguy** [comment]
Btw is there any reason why you can't use the registry on your end? We can certainly update our samples but it shouldn't be a blocker right?

**Comment by hanseuljun** [comment]
Thanks for your quick response! The more direct version of my question would be whether you recommend using the FinalizationRegistry with filament. Seems like your answer is yes.

There is no reason I cannot use the registry from my end. When checking the samples, I thought the lack of a FinalizationRegistry implied a recommendation against it. For clarification, I submitted this issue.  Again, thanks for the swift and clear answer!
