### ISSUE TITLE
sample-image-based-lighting contains nx.rgb32f in code

### ISSUE THREAD

**Issue by debdutta-yore** [google/filament#6416]
activity code
`val (w, h) = peekSize(assets, "$name/m0_nx.rgb32f")`
iblloader code
`ibl = loadIbl(assets, "envs/flower_road_no_sun_2k", engine)`
 
/m0_nx.rgb32f leads to crash the app. replacing it with .hdr remove the crash but environment not loaded.

What is it? What to do?

**Comment by romainguy** [comment]
These files are generated by the tool called cmgen. They are generated as part of the build using the filament Gradle plugin. You can so generate them manually by calling cmgen directly.

**Comment by romainguy** [comment]
Info about this can be found in this readme: https://github.com/google/filament/blob/main/BUILDING.md#running-the-native-samples
