### ISSUE TITLE
Model loads without skin texture in the initial phase 

### ISSUE THREAD

**Issue by ritik619** [google/filament#6420]
**Describe the bug**
When we try to load a GLB model frequently, After 3-4 iterations, it renders a skeleton or a skin-less model for some microseconds.
We are unable to eliminate it.
I've attached a video and a photo of  the same 

**To Reproduce**
1. Load a GLB model 
2. Again load the GLB model
3. It'll cause flickering ( skin-less,texture-less model to render)

**Expected behavior**
It was expected that the Model will load with texture properly every time.

**Screenshots**
<video src="https://user-images.githubusercontent.com/35389814/210236634-4a75ca4d-ef82-423a-9008-e669f8f8902a.mp4"  width=50% height=50% >

<img src="https://user-images.githubusercontent.com/35389814/210239956-a9f81495-93e4-448e-99e3-dea9c1b6cad6.jpg"   width=40% height=50% >

**Smartphone (please complete the following information):**
 - Device: [Realme 9 pro, Poco x3 pro, many devices]
 - OS: [ Android  12.0, 13]

**Additional Details**
Glb Size: 8-10MB

@romainguy and team

**Comment by poweifeng** [comment]
Can you post code to reproduce? 

Also please make sure you're using `com.google.android.filament.gltfio.ResourceLoader`'s `asyncGetLoadProgress` to guard against rendering before the resources are loaded into GPU memory.

**Comment by ritik619** [comment]
Thank you for the response , It worked
