### ISSUE TITLE
Multiple glft models were loaded and memory remained high

### ISSUE THREAD

**Issue by SiuyuenChow** [google/filament#6433]
**Describe the bug**
When I needed to load a large number of glft models, I found that memory kept increasing, even after rendering was complete, memory was still high. Try to remove Entities, resourceLoader-&gt; evictResourceData(), memory remains unchanged

eg.
for (int i = 0;i < array.count;i++) {
  // load asset & add to scence
 // set Transform position
}

**Screenshots**
![image](https://user-images.githubusercontent.com/12928929/211302591-49cc3124-4ca2-4245-b97e-a141b640e62e.png)
With about 80 models loaded,

When I used the emulator to load more models, I found that the temporary memory was much less than the real one
![image](https://user-images.githubusercontent.com/12928929/211319082-217b3153-9dea-46ac-b2dc-c2e153d8c2e6.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.1.1

**Comment by romainguy** [comment]
Could you please share your code to show us how you are attempting to free memory? Just removing entities from the scene will not free up memory. You need to destroy the entities and all their associate resources to free up memory.

**Comment by SiuyuenChow** [comment]
> Could you please share your code to show us how you are attempting to free memory? Just removing entities from the scene will not free up memory. You need to destroy the entities and all their associate resources to free up memory.

Hello,
---
Create a scene, add a lot of entities to it, the memory will be too large, causing a crash. Is there any way to load a lot of entities without having too much memory?
Entities are removed when certain conditions are triggered.

-----
Here is the code:

load gltf model

```
NSString *path = [[NSBundle mainBundle] pathForResource:model ofType:@"gltf"];
    NSData * buffer = [NSData dataWithContentsOfFile:path];
    asset = assetLoader -> createAsset(static_cast<const uint8_t*>(buffer.bytes),static_cast<uint32_t>(buffer.length));
    auto destroy = [](void*, size_t, void* userData) { CFBridgingRelease(userData); };
    const char* const* const resourceUris = asset -> getResourceUris();
    const size_t resourceUriCount = asset -> getResourceUriCount();
    
    for (size_t i = 0; i < resourceUriCount; i++) {
        const char* const uri = resourceUris[i];
        NSString *uriStr = [NSString stringWithCString:uri encoding:NSUTF8StringEncoding];
        NSData *data = [uriStr dataUsingEncoding:NSUTF8StringEncoding];

        filament::gltfio::ResourceLoader::BufferDescriptor b(data.bytes,data.length,destroy,(void*)CFBridgingRetain(data));

        resourceLoader -> addResourceData(uri, std::move(b));
    }

    resourceLoader -> loadResources(asset);

    asset -> releaseSourceData();
```

---
remove 

```
scene -> removeEntities(asset -> getEntities(), asset -> getEntityCount());
resourceLoader -> evictResourceData();
asset = nullptr;
```
--

**Comment by romainguy** [comment]
Removing entities from the scene doesn't free up their associated memory, and evictResourceData() only clears the data cached from a URI, but doesn't remove the GPU/CPU memory used by the decoded assets. To properly release the memory you need to delete the `FilamentAsset` objects create from the asset loader (you can't just set it to nullptr, you need to `delete` it).
