### ISSUE TITLE
Ambient Occlusion and Screen Space Reflection

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#644]
I was wondering if adding ambient occlusion and Screen space reflection is even in your guys road map as I didn't see it being mentioned in the readme file. 

Absent global illumination feature ( which is expensive), ambient occlusion does add realism to scene at a low cost.  Event though there is shadows due to light in the chess example image in the readme doc it still looks flat and lacking shadows. Ambient occlusion (ssao or hbao) would would help in that regard. 

Screen space reflection is another major feature that would be a great addition to the filament renderer  [example implementation](http://roar11.com/2015/07/screen-space-glossy-reflections/)

**Comment by romainguy** [comment]
We eventually want to add ambient occlusion, the key is to do it efficiently on mobile (and hopefully avoid the typical AO artifacts like black halos around objects in front of a wall for instance). I am however not fond of screen space reflections (nor is @pixelflinger), they usually lead to unstable images. I'd rather focus first on local probes and maybe planar reflections (although these would be expensive).

**Comment by thirdmenson** [comment]
Planar reflections would be even better!

**Comment by nxrighthere** [comment]
As for ambient occlusion, consider [GTAO](http://iryoku.com/downloads/Practical-Realtime-Strategies-for-Accurate-Indirect-Occlusion.pdf). Not sure about the mobile platforms but various implementations on the desktops works great. Blender is using it in their real-time renderer [EEVEE](https://www.youtube.com/watch?v=2hGSDD9-Tkc) for example, and [Amplify Occlusion](https://assetstore.unity.com/packages/vfx/shaders/fullscreen-camera-effects/amplify-occlusion-56739) for Unity.

**Comment by romainguy** [comment]
Yes, GTAO is on my list of potential solutions. The colored version of GTAO was too expensive for mobile if I remember correctly though (or at least seemed too expensive).

**Comment by romainguy** [comment]
Note that we're currently implementing a frame graph (see PR #727 for instance) which should make implementing more post-process passes easier.

**Comment by romainguy** [comment]
Work for an SSAO implementation is ongoing.

**Comment by pixelflinger** [comment]
Some early work here #1169, #1170 . Feedback welcome.

**Comment by nxrighthere** [comment]
This implementation is based on the ground truth approach (visually it doesn't look like GTAO), or it's something more traditional?

**Comment by romainguy** [comment]
It's traditional SSAO for now, we want to investigate SAO. We first want something that works well on mobile. We will however use the multibounce term from GTAO.

**Comment by nxrighthere** [comment]
Thanks for clarifying this. If you are interesting, here's the [source code](https://developer.blender.org/rB779c950098e46a34f89f1705be61b4b24be11568) of Blender's implementation.

**Comment by romainguy** [comment]
Folding into #1164 now that SSAO is available.
