### ISSUE TITLE
Error when creating fragment shaders

### ISSUE THREAD

**Issue by yavuz650** [google/filament#6443]
**Describe the bug**
While initializing the filament objects(engine, swapchain, renderer), an error is thrown with the following message

 `** ERROR ** [shader_util] Failed to get fragment_shader_handle: 0(11) : error C1115: unable to find compatible overloaded function "texture(sampler2DArray, vec2)`
`0(12) : error C1115: unable to find compatible overloaded function "texture(sampler2DArray, vec2)"`
`0(13) : error C1115: unable to find compatible overloaded function "texture(sampler2DArray, vec2)"`

**To Reproduce**
I suspect this error might be related to the environment(multi-threaded with shared GL context) I'm working in, so it might be difficult to reproduce.
Create filament objects
`engine = filament::Engine::create(filament::Engine::Backend::OPENGL);`
`swapChain = engine->createSwapChain(window);`
`renderer = engine->createRenderer();`

**Expected behavior**
No error should be thrown

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU: RTX3060 Laptop
 - Backend: OpenGL

**Additional context**
The error itself doesn't abort the program. However, the program exits abruptly later during execution, which I believe is caused by the fragment shader error.

**Comment by bejado** [comment]
I don't think this error is coming from a Filament material — Are you compiling any custom materials? `texture(sampler2DArray, vec2)` is not a valid use of the GLSL [`texture`](https://registry.khronos.org/OpenGL-Refpages/es3.0/html/texture.xhtml) function. The second argument should be a `vec3`.

**Comment by romainguy** [comment]
We have only one usage of `texture(sampler2DArray, vec3)` and it's correct. Otherwise we use `sampler2DArrayShadow`. Looks like an app issue indeed.
