### ISSUE TITLE
Camera->LookAt

### ISSUE THREAD

**Issue by SiuyuenChow** [google/filament#6447]
**Describe the bug**
hello,

I see a difference in orientation between what I see in blender and filament loads,

**In Blender**

<img width="994" alt="image" src="https://user-images.githubusercontent.com/12928929/211995669-ca1e358c-83b9-429e-9003-16c99d20ade8.png">

<img width="763" alt="image" src="https://user-images.githubusercontent.com/12928929/211995793-93c3bd34-a38a-441c-b3c0-2e075c7876b5.png">

**In App**

```
1. load glft model

2. set transform
 auto &tm = engine -> getTransformManager();
 auto transform = filament::math::mat4f::translation({0,0,0});
 tm.setTransform(tm.getInstance(entity),transform);

3.set look at
 camera->lookAt({0,0,2}, {0,0,0}, {0,1,0});
```

![image](https://user-images.githubusercontent.com/12928929/211996031-67544f01-eacc-4a51-be1e-062043bd56d3.png)

It seems that the visual orientation of APP loading is different from that of the first picture, which is the same as that of the second picture.

In my opinion, what you should see on the APP is the top view of the first image.

Did I set it wrong?

**Smartphone (please complete the following information):**
 - Device: iphone 12
 - OS: iOS 16

**Comment by romainguy** [comment]
The orientation of gltf and blender isn't the same. Blender uses Z up and gltf uses Y up. The transform is done at import/export in Blender. But this means you can't copy camera coordinates "as is". You can however export cameras as part of your gltf files.

**Comment by SiuyuenChow** [comment]
> The orientation of gltf and blender isn't the same. Blender uses Z up and gltf uses Y up. The transform is done at import/export in Blender. But this means you can't copy camera coordinates "as is". You can however export cameras as part of your gltf files.

i see,thanks.
