### ISSUE TITLE
App crash when release big gltf asset

### ISSUE THREAD

**Issue by zhangbo-0213** [google/filament#6448]
**Describe the bug**
release the gltf asset at running time. when the asset file is small (4.6Mb), it frees safely, however it crash when asset file is big.( 29Mb)
Here is the release code : 
```
mScene->removeEntities(asset->getEntities(), asset->getEntityCount());
mAssetLoader->destroyAsset(asset);
```
**To Reproduce**
1. load big gltf file in scene.
2. release the gltf asset.

**Expected behavior**
gltf asset free safely, no matter how big it is.

**Screenshots**
![截屏2023-01-12 15 08 30](https://user-images.githubusercontent.com/22340624/212000542-6496cda7-54f6-401f-b289-22914a3da8c5.png)

**Logs**
-[MTLDebugRenderCommandEncoder setVertexBytes:length:atIndex:]:1680: failed assertion  Set Vertex Bytes Validation
length(17289301308300324847) must be <= 4096.          
-[MTLDebugRenderCommandEncoder setVertexBytes:length:atIndex:]:1680: failed assertion  Set Vertex Bytes Validation
length(17289301308300324847) must be <= 4096.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6.1
 - GPU: Apple M1
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS 16.0

**Additional context**
Running at the iPhone, not the simulator

**Comment by romainguy** [comment]
The size of the asset probably isn't relevant (we've loaded much bigger assets). From the crash though it looks like there might be an overflow in tbe size/offset values maybe. Could you share the gltf file causing the problem? We also need to verify it's valid to begin with.

**Comment by zhangbo-0213** [comment]
> The size of the asset probably isn't relevant (we've loaded much bigger assets). From the crash though it looks like there might be an overflow in tbe size/offset values maybe. Could you share the gltf file causing the problem? We also need to verify it's valid to begin with.

Thanks for replay, Sure , here is the gltf file, it is not the 29Mb, but can make the same crash when release it.
[InSeat_4_Left_Rudde0.glb.zip](https://github.com/google/filament/files/10399389/InSeat_4_Left_Rudde0.glb.zip)

**Comment by romainguy** [comment]
I cannot repro the crash with Metal nor OpenGL on macOS (Apple M1). When are you executing those lines?

```
mScene->removeEntities(asset->getEntities(), asset->getEntityCount());
mAssetLoader->destroyAsset(asset);
```

**Comment by zhangbo-0213** [comment]
> I cannot repro the crash with Metal nor OpenGL on macOS (Apple M1) using our standard gltf_viewer. When are you executing those lines?
> 
> ```
> mScene->removeEntities(asset->getEntities(), asset->getEntityCount());
> mAssetLoader->destroyAsset(asset);
> ```

At the running time, release the asset but other assets still in the scene, not release all the assets and destroy the scene and engine.

**Comment by zhangbo-0213** [comment]
I release the asset in the demo : gltf_viewer, got this informations:
![info](https://user-images.githubusercontent.com/22340624/230347639-a3165fef-14f6-4766-81b4-d427bcbb8181.png)

**Comment by zhangbo-0213** [comment]
Here I have a doubt : 
when remove Asset, why not call the function : 
 mAssetLoader->destroyAsset(asset);
![01](https://user-images.githubusercontent.com/22340624/230527524-bc4172a5-e7c6-4916-9a45-939b5c2b6038.png)
