### ISSUE TITLE
Some file or directory is not found when run Gltf-viewer sample code in iOS

### ISSUE THREAD

**Issue by dabhoyajayzech** [google/filament#6458]
find: ../../../out/release/filament/bin: No such file or directory
No cmgen binary could be found in ../../../out/release/filament/bin.
Ensure Filament has been built/installed before building this app.

Command PhaseScriptExecution failed with a nonzero exit code
![Screenshot 2023-01-13 at 6 15 40 PM](https://user-images.githubusercontent.com/115521935/212323438-0b387bdc-541f-49c7-a170-306ab2bbb570.png)

**Comment by dabhoyajayzech** [comment]
And also give steps how to implement and use FILAMENT pod in iOS Swift

**Comment by romainguy** [comment]
You first need to build Filament itself or point to a directory that contains the binaries for the tools. See https://github.com/google/filament/blob/main/BUILDING.md on how to build Filament and its tools.
