### ISSUE TITLE
Cannot open include file DriverEnums.h

### ISSUE THREAD

**Issue by Tenebralus** [google/filament#646]
I tried to create a new filament Engine:
`filament::Engine* m_Engine = filament::Engine::create( );`
but I got this error:
`2>e:\brawler\external_projects\thirdparty\filament\include\filament\fence.h(24): fatal error C1083: Cannot open include file: 'filament/driver/DriverEnums.h': No such file or directory`
The folder indeed does not have DriverEnums.h, neither can I find it in the latest github branch.

**Comment by romainguy** [comment]
This header is part of the filabridge library: https://github.com/google/filament/tree/master/libs/filabridge/include/filament/driver

It's there because it's shared with tools and libraries. Make sure you link against that library.

**Comment by Tenebralus** [comment]
aah I see thank you

**Comment by Tenebralus** [comment]
Now I am getting an error in driverenums.h:
`2>e:\brawler\external_projects\thirdparty\filament\include\filament\driver\driverenums.h(110): error C2059: syntax error: 'constant'`
It's the ERROR enum in this class:
```
enum class FenceStatus : int8_t {
    ERROR = -1,                 //!< An error occured. The Fence condition is not satisfied.
    CONDITION_SATISFIED = 0,    //!< The Fence condition is satisfied.
    TIMEOUT_EXPIRED = 1,        //!< wait()'s timeout expired. The Fence condition is not satisfied.
};
```

**Comment by romainguy** [comment]
I imagine you're getting this error in Visual Studio right? I don't see anything wrong with this enum.

@bejado any idea?

**Comment by Tenebralus** [comment]
yes, Visual Studio 2017

**Comment by Tenebralus** [comment]
It seems renaming it to eERROR resolves the issue, not sure why, I searched for the ERROR enum in my solution, but found nothing, same goes for the NEAR and FAR enums in filament/Frustum.h, it seems they are defined in minwindef.h, which I think is a file from a windows 10 SDK

**Comment by romainguy** [comment]
Ah you're right we have a special include in our tree to work around that. 

@bejado could you make sure this include uses the Windows workaround please? Same for Frustum.h

**Comment by romainguy** [comment]
@Tenebralus An easy workaround is to just add `#include <utils/unwindows.h>` to any file causing problems. Sorry about this!

**Comment by Tenebralus** [comment]
that works 👍
