### ISSUE TITLE
Panic : set image called on stream texture.

### ISSUE THREAD

**Issue by atul161** [google/filament#6460]
Hi @romainguy @prideout  and the team,

Today I encountered a very weird error. I have some glbs. The size of glb is approx 10 mb. 

When i am loading the glb continuously(very fast) . After few times App crashes with an error saying . This happens on mobiles which have 4gb ram.

```
E/Filament: Panic
    in setImage:230
    reason: setImage() called on a Stream texture.
E/Filament:
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 15547
```

Note : I have a horizontal recyclerview . And on item click i am loading the glb on the same screen.

**Comment by atul161** [comment]
The combination of internal format=101 and {format=6, type=0} is not supported. Sometimes i am also getting this.


2023-01-14 06:17:13.460 18000-18000 DEBUG                   pid-18000                            A        #01 pc 000000000016fe70  /data/app/~~2Qkj09-R_5mf99tTF9roHQ==/com.yoyo.flam-iIdnSuX8cc25xYRpKdX6dg==/base.apk!libfilament-jni.so (utils::TPanic<utils::PreconditionPanic>::panic(char const*, char const*, int, char const*, ...)+192) (BuildId: 8568a16823add60c2469a2c8bde87089e5ceca3e)

**Comment by poweifeng** [comment]
Would it be possible to provide code to reproduce this issue?

**Comment by atul161** [comment]
@poweifeng , Thanks for recognising this issue.
I will give you a code for this. Another thing, the morphing still comes. I will update everything by today's end and will share the codebase.

**Comment by romainguy** [comment]
What I don't understand is why a stream texture is involved at all here.

**Comment by atul161** [comment]
> Would it be possible to provide code to reproduce this issue?
> 
> 

@poweifeng this is also happening with sample app gltf viewer.

**Comment by atul161** [comment]
@poweifeng Thanks a lot ! Is there any way or hack for now so that we can go ahead.

**Comment by poweifeng** [comment]
I am working on a fix in PR #6620. 

If you want a client-side workaround, you can try creating a new `ResourceLoader` every time you need to load a model.  But that is pretty expensive.  (Also you have to remember to destroy it once the model is loaded).

**Comment by atul161** [comment]
Hey @poweifeng , when should I expect this pull request going to be merged!

**Comment by poweifeng** [comment]
#6620 was just submitted.  Thanks!

**Comment by atul161** [comment]
@poweifeng Thanks for all the efforts and support!
