### ISSUE TITLE
Vulkan backend is excruciatingly slow on debug builds.

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#6466]
Repro:

Make a debug build of filament on MacOS and run gltf_viewer, notice that rendering is about 1fps. There must be some debugging code in the vulkan backend enabled only in debug that causes this. This is too much/not usable.

**Comment by poweifeng** [comment]
I'm unable to repro this on  my M1.  Any other info? 
Im on MoltenVK 1.2.1 for example.

**Comment by pixelflinger** [comment]
It doesn't happen with the default model, because it's too simple. I can reproduce easily with the sponza scene. I looked at it a but more, and it is definitely related to the validation layers being enabled. about 50% of the CPU time is spent in `BestPractices::ValidateBoundDescriptorSets`.

**Comment by poweifeng** [comment]
[`vk_layers_settings.txt`] can be used to customize (i.e. disable) parts of the validation if it's doing too much work. Alternatively, maybe using [`vkconfig`] from the VulkanSDK can be easier. 

[`vkconfig`]: https://github.com/LunarG/VulkanTools/blob/main/vkconfig/README.md
[`vk_layers_settings.txt`]: https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/layer_configuration.html
