### ISSUE TITLE
getWorldTransformAccurate - Crash in Android

### ISSUE THREAD

**Issue by atul161** [google/filament#6481]
Android Crash 
---------------------

Steps to reproduce:
 - https://github.com/atul161/multigltfpoc  
 -  In this demo project there is two screen. The first screen have one button . After
 clicking on button it forwarded to the another activity. In this acivity I have 2 glb. Once is box like cube glb
and another is avatar glb. I somehow managed to put my avatar glb inside that cube.

- When we go back to previous activity and again click on button continously.  Repeating the same steps multiple tiime can lead to crash.

`A  Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7d0d228bc0 in tid 29960 (yo.multigltfpoc), pid 29960 (yo.multigltfpoc)
2023-01-21 16:20:06.448 30191-30191 DEBUG                   pid-30191                            A  Cmdline: com.yoyo.multigltfpoc
2023-01-21 16:20:06.448 30191-30191 DEBUG                   pid-30191                            A  pid: 29960, tid: 29960, name: yo.multigltfpoc  >>> com.yoyo.multigltfpoc <<<
2023-01-21 16:20:06.449 30191-30191 DEBUG                   pid-30191                            A        #00 pc 00000000000d083c  /data/app/~~kC-G1cM-PCl_B5uDSydXPQ==/com.yoyo.multigltfpoc-OToSl0qcBTNMdZqBIOswiw==/lib/arm64/libfilament-jni.so (filament::TransformManager::getWorldTransformAccurate(utils::EntityInstance<filament::TransformManager, false>) const+28) (BuildId: 8568a16823add60c2469a2c8bde87089e5ceca3e)`

- There  is one more bug here. If you see the the model viewer , i have commented out look at code. When you uncomment this and if you repeat the same steps like above then automatically the placement of objects changed. Note: You need to click multiple times.

-   https://drive.google.com/file/d/1zNxYfB5ldD_77D3i4qsiqdA-zg-oKk6w/view?usp=sharing   [Video Link]

**Redmi Note 10 *
 - OS: Android 12]
 - 4gb ram

Please have a look on this.  @prideout  @romainguy .
If possible can you explain what should be reason for this.

**Comment by poweifeng** [comment]
I tried out your code.  The issue is passing an `Entity` into `getWorldTransform` when it expects an `Instance`.  Here's a diff that addresses your problem.

```
64a65,70
>     var loadedModel: Boolean = false
>         private set
> 
>     var loadedRoom: Boolean = false
>         private set
> 
250,254c256
<         assetForRoom?.let { asset ->
<             this.scene.removeEntities(asset.entities)
<             assetLoaderForRoom.destroyAsset(asset)
<             this.assetForRoom = null
<         }
---
>         Log.d("world", "end destroy model for room")        
280a283,305
> 
>         var skip = false;
>         if (resourceLoaderForModel.asyncGetLoadProgress() < 1) {
>             resourceLoaderForModel.asyncUpdateLoad()
>             skip = true;
>         } else {
>             if (!loadedModel) {
>                 assetForModel?.let { populateScene(it) }
>                 loadedModel = true;
>             }
>         }
>         if (resourceLoaderForRoom.asyncGetLoadProgress() < 1) {
>             resourceLoaderForRoom.asyncUpdateLoad()            
>             skip = true;
>         } else {
>             if (!loadedRoom) {
>                 assetForRoom?.let { populateScene(it) }                
>                 loadedRoom = true;                
>             }
>         }
> 
>         if (skip) return;
>         
282d306
<       /*  Log.d("World Transform", finalEntity.toString())*/
284,286c308,309
<         val hipsMovement: DoubleArray=  engine.transformManager.getWorldTransform( finalEntity, null as DoubleArray?)
<         resourceLoaderForModel.asyncUpdateLoad()
<         resourceLoaderForRoom.asyncUpdateLoad()
---
>         val inst = engine.transformManager.getInstance(finalEntity)
>         val hipsMovement: DoubleArray=  engine.transformManager.getWorldTransform( inst, null as DoubleArray?)
289,290d311
<         assetForModel?.let { populateScene(it) }
<         assetForRoom?.let { populateScene(it) }
375c396
<                 resourceLoaderForRoom.addResourceData(uri, buffer)
---
>                 resourceLoaderForModel.addResourceData(uri, buffer)
377c398
<             resourceLoaderForRoom.asyncBeginLoad(asset)
---
>             resourceLoaderForModel.asyncBeginLoad(asset)
422c443
< }
\ No newline at end of file
---
> }

```

**Comment by atul161** [comment]
@poweifeng We are going deeper down in filament every day! Thank you for your amazing support.

After destroying the assets still it has reference to the old entity. Getting an entity Instance a second time was not working for me. That's the reason I have hardcoded there. 

Thanks for addressing the issue.
