### ISSUE TITLE
On applying Morph Model's Texture gets distorted after multiple attempt 

### ISSUE THREAD

**Issue by ritik619** [google/filament#6482]
**Describe the bug**
 Hello Team,
 My model's texture gets distorted when I move back and forth on my phone.
 It loads properly for the first few times but after a few back-and-forth screen changes.
 This is an intermittent issue and happens on some device 
 
**To Reproduce**
Load model continuously  

**Expected behaviour**
The model's texture should not get distorted 

**Screenshots**

https://user-images.githubusercontent.com/35389814/214072045-7fe9ef46-5a8b-47ca-8625-db2d5b16d784.mov

<img src="https://user-images.githubusercontent.com/35389814/214073006-46c98a5b-e3ad-4812-af8a-c57e24eebcad.jpg" width="350"  height="700">  <img src="https://user-images.githubusercontent.com/35389814/214073013-6a6830e8-8fa3-4fb5-b764-207815725ea6.jpg" width="350"  height="700">

**Logs**
No Error or warning on 
 
**Smartphone (please complete the following information):**
 - Device: [e.g. Realme 9 pro+ , One plus 10 ,Samsung S10]
 - OS: [e.g. Android 13,Android 12]

**Additional context**
Is it due to the Normal Map not loading properly?

**Comment by bejado** [comment]
It looks like the model renders correctly at first, yes? Somehow the texture data is changing between loads.

**Comment by ritik619** [comment]
Yes @bejado 
It renders properly on the first attempt but after 1-2 attempts it starts distorting 
This happens only when we update morph targets

Here's how we get the Entity
`
asset: FilamentAsset

finalEntity` = asset.getFirstEntityByName(MorphRpm.Wolf3D_Avatar)
`
but this returns a different value each time we come back from another screen
Even though we're destroying the model and objects

**Comment by poweifeng** [comment]
Can you post a minimal example as in #6481 ?

**Comment by ritik619** [comment]
Sure @poweifeng 
https://github.com/atul161/multigltfpoc
I was able to replicate the same in the above repo but this is happening on some devices and is intermittent 
It happens sometime sometime it doesn't

 Steps to Reproduce:
1. Click on the button
2. Go back 
3. Repeat the same  
<img src="https://user-images.githubusercontent.com/35389814/215339484-fe705c03-fc2a-4986-9e25-49cf5dc95082.jpg" height="800" width="400">

Devices where it was replicated : Samsung M30 , Realme 9 pro , One plus CE 2, One plus 10r

**Comment by ritik619** [comment]
Have a close look at the face , there’s some distortion

**Comment by atul161** [comment]
@poweifeng do you able to replicate this? 
This is happening in almost all one-plus phones

**Comment by poweifeng** [comment]
Sorry, I've been looking at something else.  I'll try to give it a try sometime this week.

**Comment by poweifeng** [comment]
I was not able to repro, but looking at the code on line 114 of `MainActivity.kt` I think `build` expects an `Entity` and not an `Instance`.  Maybe try fixing that and trying again?

**Comment by atul161** [comment]
@poweifeng  ! do you have tried on one plus phone.. specially on these phone

- Samsung M30 
- Realme 9 pro  
- One plus CE 2 
- One plus 10r 

Note: It is working fine emulator .

**Comment by poweifeng** [comment]
Sadly I don't have access to those devices, and I wasn't able to repro on a pixel 4XL, which also has an Adreno gpu (like the Realme 9 above).

**Comment by atul161** [comment]
Thankyou for your attempt !

**Comment by poweifeng** [comment]
I was able to repro on pixel 6. Turns out the issue is the same as one of the issues of #6481.  You have to wait for the assets to be loaded before actually rendering or do any morphing.  Here's a diff that fixes the issue

```
Only in android/samples/sample-debug-test/src/main/java/com/yoyo/multigltfpoc/: change.diff
diff android/samples/sample-debug-test/src/main/java/com/yoyo/multigltfpoc/MainActivity.kt orig/MainActivity.kt
13d12
< import android.util.Log
30d28
<     private var hasRendered = false
58a57
> 
85,94c84,89
< 
<             if (hasRendered) {
<                 modelViewer.animatorForModel?.apply {
< //                    if (animationCount > 0) {
< //                        applyAnimation(0, seconds.toFloat())
< //                    }
<                     if (modelViewer.assetForModel !== null) {
<                         updateMorphTargets()
<                     }
<                     updateBoneMatrices()                        
---
>             modelViewer.animatorForModel?.apply {
> //                if (animationCount > 0) {
> //                    applyAnimation(0, seconds.toFloat())
> //                }
>                 if (modelViewer.assetForModel !== null) {
>                      updateMorphTargets()
96c91
<             }
---
>                 updateBoneMatrices()
98,106c93,99
<             hasRendered = modelViewer.render(currentTime);
< 
<             if (hasRendered) {
<                 modelViewer.assetForModel?.apply {
<                     modelViewer.transformToUnitCubeForModel()
<                 }
<                 modelViewer.assetForRoom?.apply {
<                     //modelViewer.transformToUnitCubeForRoom()
<                 }
---
>             }
>             modelViewer.render(currentTime)
>             modelViewer.assetForModel?.apply {
>                 modelViewer.transformToUnitCubeForModel()
>             }
>             modelViewer.assetForRoom?.apply {
>                 //modelViewer.transformToUnitCubeForRoom()
113d105
< 
121,125c113,114
<         if (finalEntity == 0) {
<             return;
<         }
<         
<         
---
>         RenderableManager
>             .Builder(1).morphing(2).build(modelViewer.engine, faceEntity)
226c215
< }
---
> }
\ No newline at end of file
Only in android/samples/sample-debug-test/src/main/java/com/yoyo/multigltfpoc/: MainActivity.kt~
diff android/samples/sample-debug-test/src/main/java/com/yoyo/multigltfpoc/NewModelViewer.kt orig/NewModelViewer.kt
65,67d64
<     var loadedModel = false
<     var loadedRoom = false
<     
122,127d118
<         camera.lookAt(
<             0.0, 2.0, -4.0,
<             0.0, 2.0, -5.0,
<             0.0, 1.0, 0.0
<         );
< 
286c277
<     fun render(frameTimeNanos: Long) : Boolean {
---
>     fun render(frameTimeNanos: Long) {
288,308c279
<             return false;
<         }
< 
<         var skip = false;
<         if (resourceLoaderForModel.asyncGetLoadProgress() < 1) {
<             resourceLoaderForModel.asyncUpdateLoad()
<             skip = true;
<         } else {
<             if (!loadedModel) {
<                 assetForModel?.let { populateScene(it) }
<                 loadedModel = true;
<             }
<         }
<         if (resourceLoaderForRoom.asyncGetLoadProgress() < 1) {
<             resourceLoaderForRoom.asyncUpdateLoad()            
<             skip = true;
<         } else {
<             if (!loadedRoom) {
<                 assetForRoom?.let { populateScene(it) }                
<                 loadedRoom = true;                
<             }
---
>             return
310,313c281
<         
<         if (skip) return false;
< 
< //        val finalEntity = assetForModel!!.getFirstEntityByName("Hips")
---
>         val finalEntity = assetForModel!!.getFirstEntityByName("Hips")
316c284
< //        val hipsMovement: DoubleArray=  engine.transformManager.getWorldTransform( finalEntity, null as DoubleArray?)
---
>         val hipsMovement: DoubleArray=  engine.transformManager.getWorldTransform( finalEntity, null as DoubleArray?)
336d303
<         return true
408c375
<                 resourceLoaderForModel.addResourceData(uri, buffer)
---
>                 resourceLoaderForRoom.addResourceData(uri, buffer)
410c377
<             resourceLoaderForModel.asyncBeginLoad(asset)
---
>             resourceLoaderForRoom.asyncBeginLoad(asset)
455c422
< }
---
> }
\ No newline at end of file
```

**Comment by atul161** [comment]
@poweifeng , I am pretty sure that I have implemented the same thing in our repo. 
We were still getting the same issue but the frequency was less.

**Comment by poweifeng** [comment]
I haven't been able to repro with the changes I added to the example you provided.

If you can somehow port a repro to the example (after applying my suggested changes), I can take another look.

**Comment by atul161** [comment]
@poweifeng ! Sure! Again Thanks a lot!

**Comment by ritik619** [comment]
@poweifeng 
This is happening on all devices with MALI gpu that too when we use OpenGL as backend(default )
I changed the backend to vulkan and Voila!! It fixed the morphing issue for me completely i tested on multiple mali gpu devices
But But 
When using vulkan as gpu on adreno powered devices i got ioctl errors and Engine Loop error

```
2023-02-10 15:20:52.775  6778-7026  libc                    com.yoyo.multigltfpoc                A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 7026 (FEngine::loop), pid 6778 (yo.multigltfpoc)
2023-02-10 15:20:53.397  7044-7044  DEBUG                   pid-7044                             A  Cmdline: com.yoyo.multigltfpoc
2023-02-10 15:20:53.397  7044-7044  DEBUG                   pid-7044                             A  pid: 6778, tid: 7026, name: FEngine::loop  >>> com.yoyo.multigltfpoc <<<
2023-02-10 15:20:53.397  7044-7044  DEBUG                   pid-7044                             A        #12 pc 000000000015a014  /data/app/~~XiRb5Qdi_BuZ5jPNkYvOrQ==/com.yoyo.multigltfpoc-U-H2Fxou5XuZD7sLY5p0Tw==/lib/arm64/libfilament-jni.so (BuildId: 2fdac65ee8041be2055de783d1f9d8ae4fca03c5)
```

**Comment by dandingol03** [comment]
How is the progress of problem. Does it solve @atul161 ?
