### ISSUE TITLE
Gltfio - Create Instance throws an AssertException

### ISSUE THREAD

**Issue by ThomasGorisse** [google/filament#6494]
Hi.

I have an issue with instance creation from a `FilamentAsset` on latest version (1.31.2):
```kotlin
val asset = assetLoader.createAsset(buffer)?.let {
    resourceLoader.loadResources(it)
}
...
val instance = assetLoader.createInstance()
```
throws
```
libgltfio-jni.so (BuildId: 1f80989e9281f45e9e1be04a9226cfdef6f2338b)
```
Note that it seems to work if I create the instance right after the model creation but the exception in throws in other cases (frame rendered, other resources loading,...?).
I precise that I'm not calling the `asset.releaseSourceData()` is not called before creating the instance.
Did I made anything wrong in the call or is it a bug?

Thanks

**Comment by poweifeng** [comment]
Can you post a more complete code example and maybe more detailed crash stack? Thanks.

**Comment by pixelflinger** [comment]
Pleas reopen with more info / repro case.
