### ISSUE TITLE
libsdl2.so: cannot open shared object file

### ISSUE THREAD

**Issue by captcha1** [google/filament#65]
On Fedora 28, if I try the samples, I get : 

samples/vk_hellotriangle: error while loading shared libraries: libsdl2.so: cannot open shared object file: No such file or directory

How is this supposed to work?  I can "work around" with : 

export LD_LIBRARY_PATH=third_party/libsdl2/tnt

... but it would be nice to have an option link against the Fedora package : SDL2-devel

For that matter, a lot of the stuff in third_party is already packaged in Fedora : 

spirv-tools , spirv-tools-libs , glslang , etc

**Comment by romainguy** [comment]
What does `ldd` say? On Debian I get this:

```
romainguy:filament master $ ldd out/cmake-release/samples/vk_strobecolor 
	linux-vdso.so.1 (0x00007ffd11bb9000)
	libsdl2.so => /usr/xxxxxx/home/romainguy/filament/out/cmake-release/third_party/libsdl2/tnt/libsdl2.so (0x00007fc6c07e6000)
```

We prefer hermetic builds because we rely on specific versions of the libraries. SDL2 would work but we often take fixes in `spirv-*` and `glslang` that won't be part of your system's versions.

**Comment by captcha1** [comment]
Hmmm... I get : 

libsdl2.so => /home/xx/filament/out/cmake-debug/third_party/libsdl2/tnt/libsdl2.so (0x00007f0fec2c2000)

The reason I had problems is that after the build, I was moving it : mv out out-build-clang

**Comment by romainguy** [comment]
Ah right, before moving it you should do a ninja install or pass -i to the build script.
