### ISSUE TITLE
How to use filament for AR or with ARcore 

### ISSUE THREAD

**Issue by hemantkadamata** [google/filament#650]
Hi,
I am using filament for rendering 3D content at runtime and have to render the same 3D content for AR on android device.
Does Filament provide API's to do or it connects with ARCore Internally for rendering AR content?
It will be helpful if any sample is shared.

**Comment by romainguy** [comment]
Filament provides all the required API to render AR content. The [Sceneform library](https://developers.google.com/ar/develop/java/sceneform/) from ARCore  actually uses Filament to do all the rendering internally. You could just use Sceneform directly as it lets you do AR and regular 3D.

**Comment by tellypresence** [comment]
Now that SceneForm has been archived, it would be helpful to have a sample of directly integrating ARCore with Filament

**Comment by FabianSchmiedlechner** [comment]
> Now that SceneForm has been archived, it would be helpful to have a sample of directly integrating ARCore with Filament

+1
