### ISSUE TITLE
TAA has  ghost in some Android device

### ISSUE THREAD

**Issue by zhangbo-0213** [google/filament#6504]
**Describe the bug**
when TAA enabled, some ghost shows in the Android phone. such as HUAWEI Mate 40 pro, OPPO reno 7 pro
and after test, we found in the  all Android 13 device, they show the ghost, and in some Android 12 device, they also show the ghost, and HUAWEI device whit harmony OS shows the ghost

**To Reproduce**
1. load scene 
2. enable the TAA
3. run in the Android device above 

**Expected behavior**
no  ghost with TAA enabled

**Smartphone (please complete the following information):**
 - Device: HUAWEI Mate40 pro.   OPPO reno 7 pro
 - OS: Harmony OS, Android 13.0/12.0

**Comment by pixelflinger** [comment]
@zhangbo-0213 please attach a few screenshots so we can see what you mean by "ghost".

**Comment by zhangbo-0213** [comment]
> @zhangbo-0213 please attach a few screenshots so we can see what you mean by "ghost".

@pixelflinger  sure, here is the running record:

https://user-images.githubusercontent.com/22340624/215648296-1d593802-7b6f-4eae-9dda-9a4a136c3e2e.mp4

**Comment by pixelflinger** [comment]
Can you confirm that this problem does not happen on some devices but happens on others?

**Comment by zhangbo-0213** [comment]
> Can you confirm that this problem does not happen on some devices but happens on others?

yes, I do not see the ghost in iOS device with TAA enabled, but it happened in the device above
