### ISSUE TITLE
Vulkan debug report : Input attachment descriptor image view is not a subpass input attachment

### ISSUE THREAD

**Issue by zy4944796** [google/filament#6513]
This error validation  occurs when calling vkCmdDrawIndexed function in VulkanDriver::draw:

VULKAN ERROR: (Validation) Validation Error: [ UNASSIGNED-input-attachment-descriptor-not-in-subpass ] Object 0:
 handle = 0x980f360000000011, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xe897be5f | Input attachment descriptor image view is not a subpass input attachment

**Comment by pixelflinger** [comment]
@zy4944796 please provide more information, such as which device is this on and repro steps

**Comment by zy4944796** [comment]
This problem was resolved. The reason for this error is that subpasses [1] is not used in VulkanFboCache: getRenderPass function, but the VkWriteDescriptorSet of the input attachment image view is created in VulkanPipelineCache:: createDescriptorSets .

**Comment by zy4944796** [comment]
This problem was resolved. The reason for this error is that subpasses [1] is not used in VulkanFboCache: getRenderPass function, but the VkWriteDescriptorSet of the input attachment image view is created in VulkanPipelineCache:: createDescriptorSets .

**Comment by poweifeng** [comment]
I saw this in an app.
Need to address this for filament proper.

**Comment by poweifeng** [comment]
Steps to repro.  From gltf_viewer defaults, disable MSAA and Bloom
