### ISSUE TITLE
opengl32.lib duplicate defines error

### ISSUE THREAD

**Issue by Tenebralus** [google/filament#652]
I am trying to build the filament libs into my own project, but my project already includes opengl for other libs and I am getting the following errors:
https://pastebin.com/aNCA9DEd

Do you guys have some sort of workaround for this just like the unwindows.h file?

**Comment by romainguy** [comment]
Which errors?

**Comment by Tenebralus** [comment]
accidentally pressed ctrl-enter, my bad

**Comment by bejado** [comment]
Can you show how you're compiling Filament into your own project?

**Comment by Tenebralus** [comment]
I add the libs in stdafx.cpp:
![image](https://user-images.githubusercontent.com/13809397/50186040-ec989880-0319-11e9-8f36-c5c97621a64f.png)

I decided to comment out the opengl libs used by bluegl, but it does not remove the errors:
![image](https://user-images.githubusercontent.com/13809397/50186982-ef48bd00-031c-11e9-9107-2f6cd13118de.png)

Then I try to create a filament engine in the next class, which includes the stdafx.h and the engine.h:
![image](https://user-images.githubusercontent.com/13809397/50186970-df30dd80-031c-11e9-8c2e-34b13b1fbec3.png)

I am not sure if this suffices, let me know if you need more information

**Comment by Tenebralus** [comment]
Well I am working with a team and we are creating a PC game at the moment, trying out filament to see if we can use it as the baseline for our graphics. We also use SFML, CEGUI, Voxelfarm along with some dependencies like glew and freeglut, which all use opengl.

Just got some help from one of my team members today and found the problem. Apparently we had to include the filament headers before any other library headers to make it work.

That leaves me with a question though: You mentioned in the tutorial that filament depends on SDL, but would it also work with SFML? I believe they pretty much do the same thing. Currently we only use SFML for the game screen and keyboard / mouse input.

**Comment by romainguy** [comment]
Filament doesn't use SDL, our samples do. Filament itself doesn't take dependencies like this.

**Comment by Tenebralus** [comment]
aha ok, because
`engine->createSwapChain( window );`
takes a window as input, that is why I am asking

**Comment by romainguy** [comment]
We get the native window pointer from SDL.

**Comment by Tenebralus** [comment]
alright, thanks for the heads up

**Comment by Tenebralus** [comment]
Since this issue is still open, I would like to go back to my duplicate defines errors, which was never solved, I just thought it was.
I have made a new project which recreates the same errors and I would like to see if you guys can figure out what I am doing wrong. My main.cpp:
```
#pragma once
#include "clsFilament.h"

int main( int argc, const char* argv[ ] )
{
	clsFilament* filament = new clsFilament( );
}
```

clsFilament.h:
```
#pragma once

#pragma comment(lib, "x64/Debug/Filament/lib/bluegl.lib")
#pragma comment(lib, "x64/Debug/Filament/lib/filabridge.lib")
#pragma comment(lib, "x64/Debug/Filament/lib/filaflat.lib")
#pragma comment(lib, "x64/Debug/Filament/lib/filament.lib")
#pragma comment(lib, "x64/Debug/Filament/lib/utils.lib")

#pragma comment(lib, "opengl32.lib")


class clsFilament
{
public:
	clsFilament( );
	~clsFilament( );

private:

};

```

clsFilament.cpp:
```
#pragma once
#include "clsFilament.h"

#include "x64/Debug/Filament/include/filament/Engine.h"

clsFilament::clsFilament( )
{
	filament::Engine* engine = filament::Engine::create( );
}

clsFilament::~clsFilament( )
{

}
```

Additional Include Directories:
![image](https://user-images.githubusercontent.com/13809397/50426826-0006af00-0898-11e9-859d-a7e130e7aad7.png)

Output:
https://pastebin.com/SssVAcxP

I use the latest Windows SDK version 1809 (servicing release 10.0.17763.132)
Same includes and libs from our last conversation

**Comment by bejado** [comment]
Somehow the `opengl32.lib` is still being passed to the linker before `bluegl.lib`. What would help is if I could see the full command-line arguments passed to the linker. Can you [enable verbose output](https://stackoverflow.com/questions/19822603/is-there-a-way-to-get-the-build-command-line-used-by-visual-studio), do a fresh rebuild, and paste the output?

**Comment by Tenebralus** [comment]
Ok, I changed the verbosity to Diagnostic
https://pastebin.com/xbqBPhqa

**Comment by bejado** [comment]
It looks like you're trying to use MSVC to compile / link, but we only support compiling against Filament with Clang. You'll need to select the `LLVM-vs2014` toolchain in your project settings. I don't think Clang supports `#pragma comment(lib, ...)`, so you'll need to set up the library dependencies in the project settings.

**Comment by Tenebralus** [comment]
Aha! Yes that seems to work.
I thought I only needed Clang for building the libraries, seems I misunderstood that part.

pragma comment seems to run fine, but there are some other build errors I need to have a look at now.

**Comment by meshula** [comment]
Note: linking the prebuilt libraries with MSVC doesn't work, because bluegl doesn't specify the wgl functions. Adding opengl32.lib doesn't help because of the conflicting symbols.

Without adding opengl32.lib:

```sh
C:\XXX\backend.lib(PlatformWGL.cpp.obj) : error LNK2001: unresolved external symbol __imp_wglGetProcAddress
C:\XXX\bluegl.lib(BlueGLWindows.cpp.obj) : error LNK2001: unresolved external symbol __imp_wglGetProcAddress
C:\XXX\backend.lib(PlatformWGL.cpp.obj) : error LNK2019: unresolved external symbol __imp_wglCreateContext referenced in function "public: virtual class filament::backend::Driver * __cdecl filament::PlatformWGL::createDriver(void * const)" (?createDriver@PlatformWGL@filament@@UEAAPEAVDriver@backend@2@QEAX@Z)
C:\XXX\backend.lib(PlatformWGL.cpp.obj) : error LNK2019: unresolved external symbol __imp_wglMakeCurrent referenced in function "public: virtual class filament::backend::Driver * __cdecl filament::PlatformWGL::createDriver(void * const)" (?createDriver@PlatformWGL@filament@@UEAAPEAVDriver@backend@2@QEAX@Z)
C:\XXX\backend.lib(PlatformWGL.cpp.obj) : error LNK2019: unresolved external symbol __imp_wglDeleteContext referenced in function "public: virtual class filament::backend::Driver * __cdecl filament::PlatformWGL::createDriver(void * const)" (?createDriver@PlatformWGL@filament@@UEAAPEAVDriver@backend@2@QEAX@Z)
```
with opengl32.lib included:

```sh
C:\XXX\bluegl.lib(BlueGLCoreWindowsImpl.S.obj) : error LNK2005: glIsEnabled already defined in opengl32.lib(OPENGL32.dll)
C:\XXX\bluegl.lib(BlueGLCoreWindowsImpl.S.obj) : error LNK2005: glPolygonMode already defined in opengl32.lib(OPENGL32.dll)
C:\XX\bluegl.lib(BlueGLCoreWindowsImpl.S.obj) : error LNK2005: glTexParameteri already defined in opengl32.lib(OPENGL32.dll)
etc
```

**Comment by romainguy** [comment]
@bejado Do you remember how it works on Windows?

**Comment by gpyalt** [comment]
@meshula could you not compile `BlueGLCoreWindowsImpl.S` into `bluegl.lib`, and link opengl32.lib which will provide the full OpenGL?

**Comment by romainguy** [comment]
It should work, our CI compiles a bunch of sample apps successfully, just need to figure out why :)

**Comment by bejado** [comment]
I'm surprised that ordering the libs differently doesn't fix the issue- MSVC might behave differently than Clang in that regard. I'll investigate further.

**Comment by bejado** [comment]
After fixing the header issues mentioned in #1274, I'm able to compile and link a simple test program against the `filament-20190423-windows` release using MSVC 2017. I have the dependencies specified as such:

```
filament.lib
backend.lib
bluegl.lib
filabridge.lib
filaflat.lib
utils.lib
geometry.lib
smol-v.lib
opengl32.lib
```

@meshula maybe you can give more details on how you're linking `opengl32.lib`?

**Comment by gpyalt** [comment]
@bejado, possibly there would be an issue if you made an OpenGL call in the sample program?

**Comment by bejado** [comment]
Got it, I see the issue now. A quick workaround is to add the [/force:multiple](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1169?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK1169)%26rd%3Dtrue&view=vs-2019) flag to the linker command line (Property Pages, Linker, Command Line, Additional Options). That might have unintended consequences though—I'd like to find a better solution.

**Comment by meshula** [comment]
The problem isn't that MSVC is ignoring link order.... I found the issue - opengl32 is linked indirectly by another library upstream that uses GLEW for it's OpenGL bindings, so trying to order opengl32 to come last is quite a puzzle. /force:multiple gets me linked. My application, not invoking filament, still works; so far so good.

**Comment by caibf** [comment]
@meshula How do you deal with it really? /force:multiple sounds not a good solution.

**Comment by romainguy** [comment]
Tracking this again in issue #3938.

**Comment by meshula** [comment]
@caibf Sorry, I put that Windows app on hold, so I haven't got anything new to report.
