### ISSUE TITLE
In vulkan backend,how can I set the gpu render mode to binning instead of direct?

### ISSUE THREAD

**Issue by zy4944796** [google/filament#6529]
I have got a GPU trace capture with snapdragon profiler.The results are represented in the fig below
![Screenshot from 2023-02-03 14-29-36](https://user-images.githubusercontent.com/8578753/216528649-9923805f-f981-424b-8ef6-d8b8921f1fb4.png)
The number of bins is 1,and the render mode is direct.I think that the render mode  should be binning .
How can I make it to binning?

**Comment by romainguy** [comment]
Adreno GPUs automatically decide whether to be direct or bin. There's nothing wrong with direct rendering. It means the GPU could do all its work in a single tile.
