### ISSUE TITLE
Lighting issues with skinned meshes

### ISSUE THREAD

**Issue by shartte** [google/filament#653]
**Describe the bug**
I am seeing lighting artifacts on a mesh when using skinning.
Rotating the mesh without skinning doesn't show any obvious lighting problems, suggesting that the tangent space is not completely borked. The tangent space in this case was created using mikkt.

**Expected behavior**
I would have expected to not see the completely black patches on the mesh.

**Screenshots**
The mesh (rotating) in T-Pose without any skinning applied (looks fine):
https://gfycat.com/SneakyBlissfulAdmiralbutterfly

The mesh (rotating) with skinning applied:
https://gfycat.com/EcstaticDependentBrownbear

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA GTX 1080 Ti
 - Backend: OpenGL

If you give me a hint on where the root cause could be, I could try looking into this myself.

**Comment by romainguy** [comment]
How do you encode the tangents frame when you create the filament mesh?

**Comment by shartte** [comment]
Since I am still testing, I am using FLOAT4, and use this to create the quaternion:

*tangentFrameOut = math::mat3f::packTangentFrame({
		*tangent,
		*bitangent,
		*normal
	});

Where tangentFrameOut is copied as is to the vertex buffer.

**Comment by romainguy** [comment]
And how are you passing the bone transforms? Maybe the bug is in how we handle them CPU side. I know @pixelflinger fixed a couple of issues there recently.

**Comment by shartte** [comment]
I am passing them as matrices.
```rm->setBones(i, matrices, boneCount, offset);```

The skinning itself seems to work pretty flawlessly, really. The animation playback looks totally ok.

**Comment by shartte** [comment]
Okay just to make sure I even switched over the shaders to use matrices directly rather than the decomposed matrices and I still get the same issue. I am assuming it must be something about either my transform matrices or my model. I'll look into this on my end.

**Comment by romainguy** [comment]
Skinning before world transforms sounds right indeed. Unless we expect the bone transforms to be in world space but that'd be weird.

**Comment by heitaoflower** [comment]
@shartte Hi , I just dig into skinning mesh animation, I wonder if you can share the demo with me?
