### ISSUE TITLE
【IOS】Error when running ios demo on the simulator of Mac M1

### ISSUE THREAD

**Issue by dandingol03** [google/filament#6532]
**Describe the bug**
Compiling Ios demo failed with ./build.sh -i -l -s -p ios debug when running on the simulator

**To Reproduce**
./build.sh -i -p desktop  release
./build.sh -i  -l  -s -p ios debug
run any ios demo on MAC M1

**Logs**
FAILED: libs/math/test_math 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -mios-version-min=11.0 -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -fcolor-diagnostics -fvisibility=hidden -DTNT_DEV -fembed-bitcode-marker -g -fstack-protector  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -Wl,-search_paths_first  -L/opt/homebrew/opt/llvm/lib -Wl,-dead_strip libs/math/CMakeFiles/test_math.dir/tests/test_fast.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_half.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_mat.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_vec.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_quat.cpp.o -o libs/math/test_math  libs/math/libmath.a  third_party/libgtest/tnt/libgtest.a && :
ld: in '/opt/homebrew/opt/llvm/lib/libunwind.dylib', building for iOS, but linking in dylib file (/opt/homebrew/opt/llvm/lib/libunwind.dylib) built for macOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[13/742] Linking CXX shared library libs/utils/libbenchmark_utils_callee.dylib
FAILED: libs/utils/libbenchmark_utils_callee.dylib 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -mios-version-min=11.0 -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -fcolor-diagnostics -fvisibility=hidden -DTNT_DEV -fembed-bitcode-marker -g -fstack-protector -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -dynamiclib  -L/opt/homebrew/opt/llvm/lib -Wl,-dead_strip -o libs/utils/libbenchmark_utils_callee.dylib -install_name @rpath/libbenchmark_utils_callee.dylib libs/utils/CMakeFiles/benchmark_utils_callee.dir/benchmark/benchmark_callee.cpp.o   && :
ld: in '/opt/homebrew/opt/llvm/lib/libunwind.dylib', building for iOS, but linking in dylib file (/opt/homebrew/opt/llvm/lib/libunwind.dylib) built for macOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[18/742] Linking CXX executable libs/utils/test_utils
FAILED: libs/utils/test_utils 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -mios-version-min=11.0 -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -fcolor-diagnostics -fvisibility=hidden -DTNT_DEV -fembed-bitcode-marker -g -fstack-protector  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -Wl,-search_paths_first  -L/opt/homebrew/opt/llvm/lib -Wl,-dead_strip libs/utils/CMakeFiles/test_utils.dir/test/test_algorithm.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_Allocators.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_bitset.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_CountDownLatch.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_CString.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_CyclicBarrier.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_Entity.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_FixedCapacityVector.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_Hash.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_JobSystem.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_QuadTreeArray.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_RangeMap.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_StructureOfArrays.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_sstream.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_string.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_utils_main.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_Zip2Iterator.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_BinaryTreeArray.cpp.o libs/utils/CMakeFiles/test_utils.dir/test/test_Path.cpp.o -o libs/utils/test_utils  third_party/libgtest/tnt/libgtest.a  libs/utils/libutils.a  libs/math/libmath.a && :
ld: in '/opt/homebrew/opt/llvm/lib/libunwind.dylib', building for iOS, but linking in dylib file (/opt/homebrew/opt/llvm/lib/libunwind.dylib) built for macOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Desktop (please complete the following information):**
OS: [MAC M1]
Backend: [Metal]

**Comment by dandingol03** [comment]
`filament version` : 1.29.0

**Comment by bejado** [comment]
I'm not able to reproduce on my M1, but I imagine it has something to do with the build script selecting the Homebrew version of LLVM (I see a bunch of references to `/opt/homebrew/opt/llvm`).

**Comment by bejado** [comment]
After looking into this some more, note that our build scripts do not currently support building for the iOS _Apple Silicon_ simulator. While Filament fully supports this from a technical standpoint, the build.sh script still makes the assumption that simulator means x86_64, which is no longer true.

**Comment by dandingol03** [comment]
First thing goes fist. Thanks you for taking  your time @bejado, this question make me stuck for a long time . However, I fix that as below:

- This question is relatived to the `LLVM` library on the M1 mac which is installed by `brew` for some reason. However this version of `LLVM` is not compatible. After i comment the path of `LLVM` in my environment file, the code compilation with `build.sh -i -s -p ios debug` goes fine.
-  However there is another question when i run the xcode project, it link the `arm64` library. After i link that to `x86_64` library manually, this question fixed.

**Comment by dandingol03** [comment]
Exclude Architectures add `arm64` when you want to run ios simulator
