### ISSUE TITLE
Shadows and ambient light in a scene

### ISSUE THREAD

**Issue by aleksey-chugaev** [google/filament#654]
Hi, a question about lights and shadows. I have a scene with 2 objects: cube and plane and a single directional light (I used lit-cube sample android app). 
My cube has:
```
RenderableManager.Builder(1)
                ...
                .castShadows(true)
                .receiveShadows(false)
                .build(engine, cubeRenderableEntity);
```
My plane has:
```
RenderableManager.Builder(1)
                ...
                .castShadows(false)
                .receiveShadows(true)
                .build(engine, planeRenderableEntity)
```
My light has:
```
LightManager.Builder(LightManager.Type.DIRECTIONAL)
                ...
                .castShadows(true)
                .build(engine, lightEntity)
```

The result looks like this:

![screenshot_20181220-121907](https://user-images.githubusercontent.com/4714043/50258231-d6422800-0452-11e9-9e1e-133e00702fe9.png)

The shaded area on the plane is completely black. **How do I make it partially lit?** 
Have some sort of ambient light in the scene?

I've tried adding the second directional light which doesn't cast shadows:
```
LightManager.Builder(LightManager.Type.DIRECTIONAL)
                ...
                .castShadows(false)
                .build(engine, lightAmbientEntity)
```
but that resulted in no shadow at all:

![screenshot_20181220-122152](https://user-images.githubusercontent.com/4714043/50258403-b2331680-0453-11e9-8db9-68366e57c733.png)

**Comment by romainguy** [comment]
The shadow appears completely black because you don't have an indirect light. For this you need to generate an IBL with cmgen and add it to the scene with the IndirectLight API. You can see the various C++ or Android samples. In the C++ samples look for IBL.cpp I believe.

Not that we currently support only 1 directional light. We pick the one of highest intensity.

**Comment by aleksey-chugaev** [comment]
Thanks @romainguy, that worked perfectly:

![screenshot_20181221-135209](https://user-images.githubusercontent.com/4714043/50322226-55556000-0528-11e9-971f-7e8d120fa560.png)
