### ISSUE TITLE
Fallback WebGL support when WebGL 2 is not available

### ISSUE THREAD

**Issue by Amit-Tomar-Inkarne** [google/filament#655]
**Is your feature request related to a problem? Please describe.**

While WebGL support is around 92% [https://caniuse.com/#feat=webgl]

Current WebGL 2 support is around 67% [ https://caniuse.com/#feat=webgl2 ]

Doesn't look like Apple is any soon going to support WebGL 2, they are already working on their own WebGPU, and may wanna push that. This restrict the Filament useage for web to quite restricted set of devices.

**Describe the solution you'd like**
Is there a possibility to fall back on WebGL based backend when WebGL 2 is not supported ? or in plan ?

**OS and backend**
This is specially relevant for Apple devices, however other browsers like Edge, Opera etc. don't support WebGL 2 at all as well.

**Comment by romainguy** [comment]
We are currently not planning to fall back to WebGL 1.0. It would require a lot of work and changes to the engine and I'd rather we focused on WebGPU. Note that WebGL 2 can be turned on on iOS in the system settings. It's not ideal though I agree :/
