### ISSUE TITLE
API picking returns no result

### ISSUE THREAD

**Issue by ThomasGorisse** [google/filament#6551]
Hi.
The `View.pick()` seems to always return 0 maybe since the move to FilamentInstance renderables (1.3.0, I think)

**Comment by romainguy** [comment]
Can you give more detail? You can test picking in the desktop gltf_viewer sample app and it works there (top left yellow label).
<img width="1020" alt="Screenshot 2023-02-13 at 9 07 03 AM" src="https://user-images.githubusercontent.com/869684/218524323-f659b81d-aaca-4001-85fe-1a0624517dae.png">

**Comment by pixelflinger** [comment]
please reopen with more details. The api is working with our samples.

**Comment by ThomasGorisse** [comment]
@romainguy @pixelflinger Sorry for the late answer.
I figured out that it's happening when populating the scene with the `asset.getInstance()` and not `asset.createInstance` renderables and not calling `asset.popRenderable()`
I don't see rendering differences when not calling `asset.popRenderable()` only the pick returning `renderable=0`

**Comment by ThomasGorisse** [comment]
Actually, I don't really see the meaning `asset.popRenderable()` anymore since renderable are coming from the instance
