### ISSUE TITLE
Filament incorrectly render glb files

### ISSUE THREAD

**Issue by geroge-d** [google/filament#6555]
Hi guys
Based on our latest test,we found  Filament (the latest source code) cannot render the glb file below correctly.

OS:
Windows 11  

[1.zip](https://github.com/google/filament/files/10720655/1.zip)

**Comment by romainguy** [comment]
Other glTF viewers render it the same way (https://gltf-viewer.donmccurdy.com/ for instance). It looks like your normals are inverted and/or you are using transparent materials improperly (I haven't looked a the file itself).
