### ISSUE TITLE
Compressed GLB files crashing in Android and gltf_viewer.

### ISSUE THREAD

**Issue by romainguy** [google/filament#6568]
### Discussed in https://github.com/google/filament/discussions/6567

<div type='discussions-op-text'>

<sup>Originally posted by **Mehequanna** February 16, 2023</sup>
Hello!

I've been playing around with compressed glbs and Filament on Android. When I try to use a compressed glb like the one attached, the Android app and Filament's gltf_viewer crash with the same errors:

Draco + KTX Compressed
```
FEngine (64 bits) created at 0x7f97c3872000 (threading is enabled)
FEngine resolved backend: Metal
Selected physical device 'Apple M1 Max'
FEngine feature level: 3
Missing texture provider for image\/ktx2
Missing texture provider for image\/jpeg
[1]    60697 segmentation fault  ./gltf_viewer 

```

Draco Compression
```
FEngine (64 bits) created at 0x7fce55855000 (threading is enabled)
FEngine resolved backend: Metal
Selected physical device 'Apple M1 Max'
FEngine feature level: 3
Missing texture provider for image\/jpeg
Missing texture provider for image\/jpeg
[1]    60725 segmentation fault  ./gltf_viewer 
```
[SHOE_CABINET_draco2.glb.zip](https://github.com/google/filament/files/10759459/SHOE_CABINET_draco2.glb.zip)

When I check the file with [Khronos GLTF Validator](https://github.khronos.org/glTF-Validator/), it says valid. So I'm wondering why Filament can't handle it. Does Filament support Draco and/or KTX compression?

Thanks for all the work you do!

</div>

**Comment by romainguy** [comment]
The attached glb file reproduces the issue in `gltf_viewer`.

**Comment by Mehequanna** [comment]
If it helps, here is a glb using KTX compression: 
[SHOE_CABINET_ktx.glb.zip](https://github.com/google/filament/files/10760243/SHOE_CABINET_ktx.glb.zip)

**Comment by bejado** [comment]
I think the root of the issue is here:

```
Missing texture provider for image\/jpeg
```

Looks like that glb has textures with a MIME type of `image\/jpeg` which is technically incorrect.

**Comment by Mehequanna** [comment]
Looks like it's a bug in the software I'm using to compress. I'll go file a bug over there. Thanks for looking into this so quickly!

**Comment by hshapley** [comment]
Would it be possible to go further with the fix and if it sees "image\/jpeg" it could actually be smart enough to turn that into "image/jpeg"? 
Oddly enough, we have a lot of models that worked in an older version of Filament that are now showing this issue after updating, so it will be a big undertaking to re-export all the models.

**Comment by bejado** [comment]
You have full control over the MIME types and could set up one for "image\\/jpeg" if you desire. Here's how gltf_viewer sets them up:

https://github.com/google/filament/blob/791437270797239e1822bcac15c55042aa6f8564/samples/gltf_viewer.cpp#L541-L543

**Comment by hshapley** [comment]
I'm not using Filament directly, I'm using the SceneView library which in turn uses Filament for rendering. I'm not sure if I can add custom texture providers. Thank you for the reply though; it's good to know the capability is there in Filament.
