### ISSUE TITLE
Build Failure for Samples on Windows

### ISSUE THREAD

**Issue by Raki** [google/filament#657]
**Describe the bug**
Build is failing on Windows (with vs2017) when we run 
msbuild  TNT.sln /t:material_sandbox /m /p:configuration=Release

with the following the error:

      "E:\FilamentSpace\filament-sceneform-1.7pr2\out\cmake-release\TNT.sln" (sample_full_pbr target) (1) ->
       "E:\FilamentSpace\filament-sceneform-1.7pr2\out\cmake-release\samples\sample_full_pbr.vcxproj.metaproj" (default target) (2) ->
       "E:\FilamentSpace\filament-sceneform-1.7pr2\out\cmake-release\samples\common-resources.vcxproj.metaproj" (default target) (12) ->
       "E:\FilamentSpace\filament-sceneform-1.7pr2\out\cmake-release\tools\filamesh\filamesh.vcxproj.metaproj" (default target) (29) ->
       "E:\FilamentSpace\filament-sceneform-1.7pr2\out\cmake-release\filament\filament.vcxproj.metaproj" (default target) (30) ->
       "E:\FilamentSpace\filament-sceneform-1.7pr2\out\cmake-release\tools\matc\matc.vcxproj.metaproj" (default target) (46) ->
       "E:\FilamentSpace\filament-sceneform-1.7pr2\out\cmake-release\tools\matc\matc.vcxproj" (default target) (83) ->
       (Link target) ->
         lld-link.exe : error : undefined symbol: SHADERS_PACKAGE [E:\FilamentSpace\filament-sceneform-1.7pr2\out\cmake-release\tools\matc\matc.vcxproj]

**To Reproduce**
1. open VS 2017: x64 Native Tools Command Prompt for VS 2017, navigate to build folder
2. execute
    > cmake ..\.. -T"LLVM" -G "Visual Studio 15 2017 Win64" ^
-DCMAKE_CXX_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" ^
-DCMAKE_C_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" ^
-DCMAKE_LINKER:PATH="C:\Program Files\LLVM\bin\lld-link.exe"

3. execute
   msbuild  TNT.sln /t:material_sandbox /m /p:configuration=Release

**Expected behavior**
 It should generate .exe for the corresponding project mentioned in above command.

**Desktop:**
 - OS: Windows 10
 - GPU:  NVIDIA GeForce GTX 1050 Ti
 - Backend: OpenGL

**Comment by romainguy** [comment]
Looks like an issue we saw before: the shader generation step didn't run.

Could you try compiling everything please?

**Comment by bejado** [comment]
@Raki please make sure you're on the latest master, and let us know if you still have issues.

**Comment by Raki** [comment]
@bejado In latest master this issue is not there. It was compiled normally without any errors. It is there in **filament-sceneform-1.7pr2**

Thank you @romainguy and @bejado for the quick response...!!!
