### ISSUE TITLE
Accessing Buffer view

### ISSUE THREAD

**Issue by vTimePhil** [google/filament#6573]
We are working with SceneView to enable AR applications, there is a related question there:

https://github.com/SceneView/sceneview-android/issues/206

Im just looking for a route into the GLB header, this is possible in JS but Im yet to find a route in Kotlin

**Comment by poweifeng** [comment]
Filament is not meant to be a generic gltf parser IMO. Your use case can be accomplished by parsing the gltf again (albeit inefficiently) with a library like [cgltf], which Filament uses.

[cgltf]: https://github.com/jkuhlmann/cgltf
