### ISSUE TITLE
reason: could not parse the material package

### ISSUE THREAD

**Issue by YassinELhadedy** [google/filament#6575]
Connected to the target VM, address: 'localhost:61505', transport: 'socket'
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/mentapplication: Late-enabling -Xcheck:jni
D/ActivityThread: setConscryptValidator
D/ActivityThread: setConscryptValidator - put
V/studio.deploy: Startup agent attached to VM
V/studio.deploy: No existing instrumentation found. Loading instrumentation from instruments-b5380c1f.jar
W/mentapplication: DexFile /data/data/com.example.testfilamentapplication/code_cache/.studio/instruments-b5380c1f.jar is in boot class path but is not in a known location
V/studio.deploy: Applying transforms with cached classes
W/mentapplication: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
W/mentapplication: Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10391; state: ENABLED
W/ActivityThread: Application com.example.testfilamentapplication is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1487)
W/ziparchive: Unable to open '/data/app/~~oglx1x-kRrIy1HnG5BTo3g==/com.example.testfilamentapplication-BrURwYiYw1uw081xIGSDFw==/base.dm': No such file or directory
W/ziparchive: Unable to open '/data/app/~~oglx1x-kRrIy1HnG5BTo3g==/com.example.testfilamentapplication-BrURwYiYw1uw081xIGSDFw==/base.dm': No such file or directory
D/nativeloader: Configuring classloader-namespace for other apk /data/app/~~oglx1x-kRrIy1HnG5BTo3g==/com.example.testfilamentapplication-BrURwYiYw1uw081xIGSDFw==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~oglx1x-kRrIy1HnG5BTo3g==/com.example.testfilamentapplication-BrURwYiYw1uw081xIGSDFw==/lib/arm64:/data/app/~~oglx1x-kRrIy1HnG5BTo3g==/com.example.testfilamentapplication-BrURwYiYw1uw081xIGSDFw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.example.testfilamentapplication
V/GraphicsEnvironment: ANGLE Developer option for 'com.example.testfilamentapplication' set to: 'default'
V/GraphicsEnvironment: ANGLE GameManagerService for com.example.testfilamentapplication: false
V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/OpenGLRenderer: RenderThread::requireGlContext()
I/AdrenoGLES-0: QUALCOMM build                   : e1ac91e, I2b3b5fbd00
    Build Date                       : 11/17/20
    OpenGL ES Shader Compiler Version: EV031.32.02.06
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
I/AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
D/OpenGLRenderer: RenderThread::setGrContext()
I/DecorView: [INFO] isPopOver=false config=true
I/DecorView: updateCaptionType: isFloating=false isApplication=true hasWindowDecorCaption=false this=DecorView@be6a25f[]
D/DecorView: setCaptionType = 0, this = DecorView@be6a25f[]
I/DecorView: getCurrentDensityDpi: from real metrics. densityDpi=420 msg=resources_loaded
I/DecorView: setWindowBackground: isPopOver=false color=ffffffff d=android.graphics.drawable.ColorDrawable@13fd575
I/Filament: FEngine (64 bits) created at 0xb40000789dc9b000 (threading is enabled)
D/Filament: Using ASurfaceTexture
I/Filament: FEngine resolved backend: OpenGL
V/Filament: [Qualcomm], [Adreno (TM) 618], [OpenGL ES 3.2 V@0502.0 (GIT@e1ac91e, I2b3b5fbd00, 1605635143) (Date:11/17/20)], [OpenGL ES GLSL ES 3.20]
V/Filament: Feature level: 2
    Active workarounds: 
    dont_use_timer_query
    disable_sidecar_blit_into_texture_array
    split_easu
    invalidate_end_only_if_invalidate_start
    allow_read_only_ancillary_feedback_loop
    enable_initialize_non_used_uniform_array
I/Filament: FEngine feature level: 2
E/Filament: Panic
    in createParser:57
    reason: could not parse the material package
E/Filament: 
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 29576 (mentapplication), pid 29576 (mentapplication)
Disconnected from the target VM, address: 'localhost:61505', transport: 'socket'

**Comment by romainguy** [comment]
This means you are trying to load an invalid file as your material. Make sure you properly compiled it with the matc tool.
