### ISSUE TITLE
WebGL examples broken on Safari / iOS 16.2 / iPhone 11

### ISSUE THREAD

**Issue by nmfisher** [google/filament#6576]
**Describe the bug**

In Safari / iOS 16.2 / iPhone 11:
https://google.github.io/filament/webgl/parquet.html loads, but animates with horrendously bad performance.
https://google.github.io/filament/webgl/suzanne.html does not load at all, leaving Safari with a blank screen
https://google.github.io/filament/webgl/helmet.html loads the skybox, displays the "Downloaded FlightHelmet.bin" (etc) messages, but then the model never loads.

All other apps/tabs were closed to rule out any memory issues.

**To Reproduce**

Open any of the above links in Safari on an iPhone 11 running iOS 16.2

**Expected behavior**

Should render the same as desktop (i.e parquet should rotate smoothly, suzanne and flight helmet should be visible)

**Screenshots**

helmet.html
![image](https://user-images.githubusercontent.com/7238578/220014609-475e85b2-0e43-4dff-b364-4a43d9692523.png)

suzanne.html
![image](https://user-images.githubusercontent.com/7238578/220014596-13b523cc-0e02-40e7-b91d-99f602874807.png)

**Logs**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.2

**Additional context**

**Comment by bejado** [comment]
Thanks for the report. I'm able to reproduce on my iPhone 14 Pro. The console logs from the Suzanne demo indicate we're having trouble loading some resources:

```
[Error] Failed to load resource: the server responded with a status of 404 () (normal.ktx2, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (metallic.ktx2, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (roughness.ktx2, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (ao.ktx2, line 0)
[Error] Unhandled Promise Rejection: Error: normal.ktx2
	promiseEmptyOnRejected (filament.js:139)
	promiseReactionJob
[Error] Unhandled Promise Rejection: Error: metallic.ktx2
	promiseEmptyOnRejected (filament.js:139)
	promiseReactionJob
[Error] Unhandled Promise Rejection: Error: roughness.ktx2
	promiseEmptyOnRejected (filament.js:139)
	promiseReactionJob
[Error] Unhandled Promise Rejection: Error: ao.ktx2
	promiseEmptyOnRejected (filament.js:139)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (albedo.ktx2, line 0)
[Error] Unhandled Promise Rejection: Error: albedo.ktx2
	promiseEmptyOnRejected (filament.js:139)
	promiseReactionJob
```

I'll take a closer look.
