### ISSUE TITLE
\external_projects\thirdparty\filament\include\math\mat4.h(536): warning C4346: 'math::details::TMat44<T>::Fov': dependent name is not a type

### ISSUE THREAD

**Issue by JoeyvGangelen** [google/filament#660]
**Describe the bug**
One of my teammates implemented the include headers and .lib files into the project, and ever since I've been getting this warning on both Debug and Release. It compiles fine for him:
2>\external_projects\thirdparty\filament\include\math\mat4.h(536): warning C4346: 'math::details::TMat44<T>::Fov': dependent name is not a type

Due to that, the following error crashes my build:
2>\external_projects\thirdparty\filament\include\math\mat4.h(536): error C2061: syntax error: identifier 'Fov'

**To Reproduce**
Unsure. I didn't implement filament and the code works fine for him.

**Expected behavior**
I expected the build to compile normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/20630529/50364892-4f846c80-0572-11e9-9a76-070d8d4242e5.png)
![image](https://user-images.githubusercontent.com/20630529/50364900-5317f380-0572-11e9-8710-bfdd55f6b12c.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - GPU: NVidia GTX 550
 - Backend: OpenGL

**Comment by shartte** [comment]
@JoeyvGangelen I don't have this particular issue when using Visual Studio.
Can you please report the actual site of the error? Is it where it's included or where a specific template function is called?
Also: What is the *exact* version of Visual Studio you are using. Is it with  MSVC or the Clang frontend?

**Comment by JoeyvGangelen** [comment]
@shartte it's caused by the line:
"#include "External_Projects/Thirdparty/Filament/include/filament/Engine.h""

**Comment by bejado** [comment]
@JoeyvGangelen are you using MSVC to build? At the moment we only support Clang on Windows.

**Comment by JoeyvGangelen** [comment]
> @JoeyvGangelen are you using MSVC to build? At the moment we only support Clang on Windows.

I am, but my teammate compiled it using Clang and added it to the MSVC solution. It works for him but doesn't for me?

**Comment by shartte** [comment]
@JoeyvGangelen I think you'll need to update your Visual Studio version. I am using 15.9.4 successfully with filament's headers.

**Comment by JoeyvGangelen** [comment]
An update didn't solve it. However, we've stepped away from trying to implement filament as it wasn't exactly integrating nicely when already having a framework of OpenGL present, so I stopped trying since.

**Comment by romainguy** [comment]
Out of curiosity are there features missing before you could do everything in Filament (assuming you had the will and time to rewrite existing code)?
