### ISSUE TITLE
Skybox color looks different after updating the Filament APIs

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#6603]
I have updated the Filament to the latest version. everything works fine except the Skybox colour rendering. 

So the issue is, I am setting up Skybox colour to change the background of the model viewer, and it's getting applied properly. but when I compare the old and new versions of the app with updated Filament APIs, there are visible differences in colours.  I have cross-checked the colour values and both values are exactly the same. did some research on it but did not find anything related to it. so any help from anyone would be appreciated. Attached Screenshot for reference.

Left one is after the update and the right one is before the update
 
<img width="1248" alt="Screenshot 2023-03-01 at 4 27 54 PM" src="https://user-images.githubusercontent.com/24297327/222120344-7ad0a12b-c07b-4c8c-a63c-e73424c34a63.png">

**Comment by romainguy** [comment]
Inspecting the values in the screenshots, both backgrounds are exactly the same (#E4E2DB in sRGB). There is a slight difference on the model itself, is that what you are talking about?

What version of Filament are/were you using?
What settings of ColorGrading are you using?

**Comment by chiragchauhan1073** [comment]
"There is a slight difference on the model itself, is that what you are talking about?" 
-> No I am talking about the white background. the model looks perfect in both versions but there is a slight difference in the background color. 
Like in the above images, the right side image is a bit lighter compared to the left one. 

"What version of Filament are/were you using?"
-> Older versions
- com.google.android.filament:filament-android:1.31.3
- com.google.android.filament:filament-utils-android:1.31.3
- com.google.android.filament:gltfio-android:1.31.3
- 
-> Newer version
- com.google.android.filament:filament-utils-android:1.8.0
- com.google.android.filament:gltfio-android:1.8.0
- com.google.android.filament:filament-android:1.8.0

-> What settings of ColorGrading are you using?
- All the settings are default.

**Comment by chiragchauhan1073** [comment]
Yes colour values are the same but they display slightly different

**Comment by romainguy** [comment]
The colors are exactly the same when I sample the screenshots, this means Filament is outputing the same values.

**Comment by chiragchauhan1073** [comment]
<img width="296" alt="Screenshot 2023-03-02 at 12 24 22 PM" src="https://user-images.githubusercontent.com/24297327/222353570-632d5eb9-4ed6-44d7-8ad7-3064aedd33dc.png">

<img width="307" alt="Screenshot 2023-03-02 at 12 24 37 PM" src="https://user-images.githubusercontent.com/24297327/222353604-0b8079bc-d91d-4962-93f9-4db6417ae514.png">

Thanks for your feedback! but These are the actual screenshot from the application and it looks a bit different to me. So I just want to know if is there any API through which I can manage the shading of the colour.?

**Comment by romainguy** [comment]
Those screenshots show different colors. Which one is the newer? I assume the top one? If you want to keep the old colors you can try to change the tone mapping to "Filmic".

**Comment by chiragchauhan1073** [comment]
The  Second one is a newer one. Let me try "Filmic". Thank you for your quick response.
