### ISSUE TITLE
Crash Happens when filament is trying to destroy its object and the creation will be called at the same time.

### ISSUE THREAD

**Issue by atul161** [google/filament#6604]
I have a horizontal recycler view. When any item will be clicked in recyclerview then the 3d object wll be changed.
For example: we need to load another 3d objects after item click happens.

This is working perfectly and there is no issue. But in low end phone when user clicks on recycler view item too fast then the scene creation and 
destroy happens to fastly and some times it crashed.

Is there any way to prevent this or do you guys provides an api through which we can get the status of destruction so we have more control over it.

**Comment by romainguy** [comment]
What is the crash and how can we test to reproduce it? You are not providing enough information.

**Comment by atul161** [comment]
Thanks for replying! The same thing happens with the model viewer example also! You can just double-tap on the model too frequently then the crash happens!

"Set image called on stream texture!" This is the message of the issue.

I will share the whole log here!

**Comment by atul161** [comment]
https://github.com/google/filament/issues/6460

I think there is a log. Sorry for the new issue. I forgot that I created the same issue a few months back.

**Comment by atul161** [comment]
Hi @pixelflinger ! I think this issue has been resolved by poweing yesterday!

https://github.com/google/filament/pull/6620
