### ISSUE TITLE
Documentation mentions "Static Lights" but doesn't explain what they are

### ISSUE THREAD

**Issue by shartte** [google/filament#661]
**Describe the bug**

The documentation for the LightManager states: 
` * 3. Use Type.Static Lights as much as possible.`

That type of light doesn't seem to exist though.

Furthermore, other methods state:

`* @note ignored for Mode.STATIC lights.`

I couldn't find any actual reference to "Mode" or "STATIC" in the code though.

Is this outdated information?

**Comment by romainguy** [comment]
It's outdated indeed

**Comment by shartte** [comment]
I opened a PR to make pixelflinger's life a bit easier ;-)
