### ISSUE TITLE
Wrong name for android sample Material Builder app

### ISSUE THREAD

**Issue by DanielRahme** [google/filament#6622]
**Describe the bug**
The name of the app is wrong for this sample. Currently named as "Image-Based Lighting" instead of "Material Builder".

The string needs to be changed to "Material Builder": 
https://github.com/google/filament/blob/ec48dfa45351b56c135f7485e29c45b8aa3a646c/android/samples/sample-material-builder/src/main/res/values/strings.xml#L2 

**To Reproduce**
Build for android with sample-material-builder.
Install on Android device.
See name of app on Android device.

**Expected behavior**
Expect to have an app named "Material Builder".

**Comment by poweifeng** [comment]
Thanks for letting us know.  I've made a change according to your suggestion.
