### ISSUE TITLE
Get rid of the hard-coded file blob in third_party/

### ISSUE THREAD

**Issue by Zyrsha** [google/filament#664]
This project should switch over to git submodules with tag #'s

Which revisions are these externals? Where did they come from? Oh, I have to go through the git history, searching for commit messages about a tag change? And I have to go searching on GitHub to figure out if one of the libs has a non-ambiguous name? And which fork did you use, exactly? And what is "environments"? Which repo is that from? It's like MSDOS folder of stuff thrown together.

If you have to manually copy and paste externals into a third_party directory in a way which loses information about the tag #, and does not retain linkage to remember the third parties, then it means there is a problem of modularity in the design of the engine.

**Comment by romainguy** [comment]
Thank you for the suggestion. We unfortunately would like to keep it this way for many reasons (some historical).
