### ISSUE TITLE
ubuntu 18.04 version(1.31.6 -1.32.0) compile failed

### ISSUE THREAD

**Issue by yygbruce** [google/filament#6643]
**Describe the bug**
filament-1.32.0/filament/src/HwRenderPrimitiveFactory.h:29:
/usr/lib/llvm-8/bin/../include/c++/v1/set:454:26: error: the specified comparator type does not provide a const call operator [-Werror,-Wuser-defined-warnings]
    static_assert(sizeof(__diagnose_non_const_comparator<_Key, _Compare>()), "");
filament-1.32.0/filament/src/HwRenderPrimitiveFactory.h:99:13: note: in instantiation of template class 'std::__1::set<filament::HwRenderPrimitiveFactory::Entry, std::__1::less<void>, utils::STLAllocator<filament::HwRenderPrimitiveFactory::Entry, utils::Arena<utils::PoolAllocator<64, 16, 0, utils::FreeList>, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked, utils::AreaPolicy::HeapArea> > >' requested here
            Set::const_iterator>;
            ^
/usr/lib/llvm-8/bin/../include/c++/v1/__tree:967:5: note: from 'diagnose_if' attribute on '__diagnose_non_const_comparator<filament::HwRenderPrimitiveFactory::Entry, std::__1::less<void> >':
    _LIBCPP_DIAGNOSE_WARNING(!std::__invokable<_Compare const&, _Tp const&, _Tp const&>::value,
    ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm-8/bin/../include/c++/v1/__config:1262:21: note: expanded from macro '_LIBCPP_DIAGNOSE_WARNING'
     __attribute__((diagnose_if(__VA_ARGS__, "warning")))
filament-1.32.0/filament/src/ShadowMap.h:99:9: error: default member initializer for 'csNearFar' needed within definition of enclosing class 'ShadowMap' outside of member functions
        SceneInfo() noexcept = default;
        ^
/home/bruce/Downloads/filament-1.32.0/filament/src/ShadowMap.h:99:9: note: in evaluation of exception specification for 'filament::ShadowMap::SceneInfo::SceneInfo' needed here
/home/bruce/Downloads/filament-1.32.0/filament/src/ShadowMap.h:103:22: note: default member initializer declared here
        math::float2 csNearFar = { -1.0f, 1.0f };
                     ^
2 errors generated.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Backend: [OpenGL/Vulkan]

**Comment by poweifeng** [comment]
This is a `clang-8` bug: https://reviews.llvm.org/D60540

Please update your `clang` and try again.  Thanks!
