### ISSUE TITLE
Culler out of bounds array access

### ISSUE THREAD

**Issue by shartte** [google/filament#665]
**Describe the bug**
When enabling the page heap using gflags to track down heap corruption, I noticed this out of bounds array access in ``Culler::intersects``:

![image](https://user-images.githubusercontent.com/1261399/50445001-fb7bde00-090b-11e9-9ce9-f1d702b38f6b.png)

I think the assumption that capacity is always a multiple of 8 is broken.
The data being passed in has both capacity and size of 1:

![image](https://user-images.githubusercontent.com/1261399/50445021-1cdcca00-090c-11e9-8e76-7724ccc9d9c5.png)

**Comment by romainguy** [comment]
If there's a bug it would be here then:

https://github.com/google/filament/blob/master/filament/src/Scene.cpp#L71

Or in setCapacity().

**Comment by shartte** [comment]
I am looking into this, I think it might be related to having a scene without lights which I maintain for the purposes of rendering only unlit UI primitives.

**Comment by romainguy** [comment]
That would be something we never tried I believe :)
