### ISSUE TITLE
Can filament bind the vertex buffer and index buffer only once in Vulkan backend?

### ISSUE THREAD

**Issue by DOUBLE-RHH** [google/filament#6658]
### Discussed in https://github.com/google/filament/discussions/6657

<div type='discussions-op-text'>

<sup>Originally posted by **DOUBLE-RHH** March 21, 2023</sup>
On lines 1715 to 1727 of the VulkanDriver.cpp : 

    // Next bind the vertex buffers and index buffer. One potential performance improvement is to
    // avoid rebinding these if they are already bound, but since we do not (yet) support subranges
    // it would be rare for a client to make consecutive draw calls with the same render primitive.
    vkCmdBindVertexBuffers(cmdbuffer, 0, bufferCount, buffers, offsets);
    vkCmdBindIndexBuffer(cmdbuffer, prim.indexBuffer->buffer.getGpuBuffer(), 0,
            prim.indexBuffer->indexType);

    // Finally, make the actual draw call. TODO: support subranges
    const uint32_t indexCount = prim.count;
    const uint32_t firstIndex = prim.offset / prim.indexBuffer->elementSize;
    const int32_t vertexOffset = 0;
    const uint32_t firstInstId = 0;
    vkCmdDrawIndexed(cmdbuffer, indexCount, instanceCount, firstIndex, vertexOffset, firstInstId);

Is the Api vkCmdDrawIndexed means filament support subranges ? If I use VK_PRIMITIVE_TOPOLOGY_TIRANGLE_LIST as the render primitive, can I bind the vertex buffer and index buffer only once?</div>

**Comment by pixelflinger** [comment]
let's keep this in discussions.
