### ISSUE TITLE
Static debug filament lib linker error 

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#669]
I was able to successfully build my sample app by importing the filament static .lib files and it compiles and links fine on release version, but when I build the debug lib from source successfully and add them to my project to enable debugging I get this linker error:

1>    lld-link.exe : error : undefined symbol: ?createDriver@PlatformNoop@filament@@MEAAPEAVDriver@2@PEAX@Z
1>    >>> referenced by filament.lib(Platform.obj):(??_7PlatformNoop@filament@@6B@)

As far as I can tell the symbol it's not finding is the createDriver method in PlatformNoop class which should be a part of filament.lib, which  I have added to my list of include libraries. Am I missing some library ? I am building on VS 2017 on windows btw.

**Comment by prideout** [comment]
This is strange because `PlatformNoop.cpp` defines that function.  Since our CMakeLists file includes it for debug builds, it should be included when invoking msbuild with `/p:configuration=Debug`.

Are you using clang to build both Filament and the client application, or are you using clang only for Filament?  Some more detail about your build process might be helpful.  @bejado might have thoughts.

**Comment by thirdmenson** [comment]
I was using Msvc but since filament was build using clang I am now building my project in Clang as well. 

I hope those files are included when I change to debug build and build using visual studio UI. I didnt try building using msbuild command line because the build compiles and links fine. Its just when linking this lib in my project get this error. Maybe for some reason it may not be picking those files when building through UI. Not sure

**Comment by bejado** [comment]
I remember seeing this issue before, but it should be fixed on the latest master. Can you confirm your repo is up to date?

**Comment by thirdmenson** [comment]
I got the latest and I was able to build debug version successfully. Thanks guys !

**Comment by romainguy** [comment]
Sorry for the trouble!
