### ISSUE TITLE
Fill out copyright notice for Apache 2.0 license

### ISSUE THREAD

**Issue by cpheinrich** [google/filament#6690]
We are currently in the process of providing attribution to third party libraries that we use in our product, and we would like to provide proper attribution to the Filament team on our page: https://learn.poly.cam/third-party-libraries

When reviewing your license I noticed that you have not filled in the Copyright notice on the license page
https://github.com/google/filament/blob/d00223332ea71322bb2eb6a0e79100da79bd83ff/LICENSE#L190

We plan to provide a link to the repo regardless, but if you would like us to reproduce the copyright notice please fill it in with the year and name of owner so we can provide proper credit. 

Thanks again for the great work on the project!

**Comment by romainguy** [comment]
Done, thanks!

**Comment by cpheinrich** [comment]
Thanks, we've updated our site with this info!
