### ISSUE TITLE
Bloom doesn't work with translucent rendertargets

### ISSUE THREAD

**Issue by dandingol03** [google/filament#6696]
**Describe the bug**
I render a gltf model  on offscreen view and use it as background to blend with other view. But there is no any bloom effect even after i set the `bloomoptions` to true and enhance the emissive factor to 100. 

**Here is the bloom material:**
```
material {
    name : ubershader_lit_border,
    requires : [ uv0, uv1, color ],
    shadingModel : lit,
    blending : fade,
    culling: front,
    transparency : twoPassesOneSide,
    doubleSided : false,
    depthWrite : true,
    flipUV : false,
    clearCoatIorChange : false,
    parameters : [

        { type : float3, name : specularFactor },
        { type : float, name : glossinessFactor },

        // Base Color
        { type : int, name : baseColorIndex },
        { type : float4, name : baseColorFactor },
        { type : sampler2d, name : baseColorMap },
        { type : mat3, name : baseColorUvMatrix, precision: high },

        // Metallic-Roughness Map
        { type : int, name : metallicRoughnessIndex },
        { type : float, name : metallicFactor },
        { type : float, name : roughnessFactor },
        { type : sampler2d, name : metallicRoughnessMap },
        { type : mat3, name : metallicRoughnessUvMatrix, precision: high },

        // Normal Map
        { type : int, name : normalIndex },
        { type : float, name : normalScale },
        { type : sampler2d, name : normalMap },
        { type : mat3, name : normalUvMatrix, precision: high },


        // Emissive Map
        { type : int, name : emissiveIndex },
        { type : float3, name : emissiveFactor },
        { type : sampler2d, name : emissiveMap },
        { type : mat3, name : emissiveUvMatrix, precision: high },
        { type : float, name : extraEmissiveFactor },

        // Reflectance
        { type : float, name : reflectance }
    ],
}

vertex {
void materialVertex(inout MaterialVertexInputs material) {

    material.worldPosition = material.worldPosition + vec4(material.worldNormal * 0.006, 0.0);

}
}

fragment {
    void material(inout MaterialInputs material) {
        highp float2 uvs[2];
        uvs[0] = getUV0();
        uvs[1] = getUV1();

        #if !defined(SHADING_MODEL_UNLIT)
            if (materialParams.normalIndex > -1) {
                highp float2 uv = uvs[materialParams.normalIndex];
                uv = (vec3(uv, 1.0) * materialParams.normalUvMatrix).xy;
                material.normal = texture(materialParams_normalMap, uv).xyz * 2.0 - 1.0;
                material.normal.xy *= materialParams.normalScale;
            }

        #endif

        prepareMaterial(material);
        material.baseColor = materialParams.baseColorFactor;

        if (materialParams.baseColorIndex > -1) {
            highp float2 uv = uvs[materialParams.baseColorIndex];
            uv = (vec3(uv, 1.0) * materialParams.baseColorUvMatrix).xy;
            material.baseColor *= texture(materialParams_baseColorMap, uv);
        }

        #if defined(BLEND_MODE_TRANSPARENT)

            if (materialParams.alphaIndex > 0) {
                 material.baseColor.rgb *= texture(materialParams_alphaMap, getUV0()).r;
                  material.baseColor.a = texture(materialParams_alphaMap, getUV0()).r;
            } else {
               material.baseColor.rgb *= material.baseColor.a;
            }
        #endif

        material.baseColor *= getColor();


        #if !defined(SHADING_MODEL_UNLIT)

            #if defined(SHADING_MODEL_LIT)
                material.roughness = materialParams.roughnessFactor;
                material.metallic = materialParams.metallicFactor;

            #endif

            material.emissive = vec4(materialParams.emissiveFactor.rgb, 0.0);


            if (materialParams.metallicRoughnessIndex > -1) {
                highp float2 uv = uvs[materialParams.metallicRoughnessIndex];
                uv = (vec3(uv, 1.0) * materialParams.metallicRoughnessUvMatrix).xy;

                #if defined(SHADING_MODEL_SPECULAR_GLOSSINESS)
                    vec4 sg = texture(materialParams_metallicRoughnessMap, uv);
                    material.specularColor *= sg.rgb;
                    material.glossiness *= sg.a;
                #else
                    vec4 mr = texture(materialParams_metallicRoughnessMap, uv);
                    material.roughness *= mr.g;
                    material.metallic *= mr.b;
                #endif
            }


            if (materialParams.emissiveIndex > -1) {
                highp float2 uv = uvs[materialParams.emissiveIndex];
                uv = (vec3(uv, 1.0) * materialParams.emissiveUvMatrix).xy;
                material.emissive.rgb *= texture(materialParams_emissiveMap, uv).rgb * materialParams.extraEmissiveFactor;

            }

        material.baseColor = vec4(0.0, 0.6, 0.6, 1.0);
        material.baseColor.a = 0.9f;
        material.baseColor = material.baseColor * material.baseColor.a;
        material.emissive.rgb = vec3(0.2, 0.7, 0.7) * 20.0;

        #endif
    }
}

```

**To Reproduce**
1. load the [gltf](https://drive.google.com/file/d/1lRqTk71s9QMPPySj41os1sf1m4dRse6l/view?usp=share_link) i proivide 
2. modify the default lit_fade material to the material i mentioned above.
3. add the entities of `gltf` to offscreen view, and set the bloom options of offscreen view to true. 
4. create a rendertarget, and set it to offscreenview
5.  render the offscreen color texture on screen

**Expected behavior**
the offscreen gltf has bloom effect

**Screenshots**
![image](https://user-images.githubusercontent.com/13013579/228750537-1a5bec1f-cba1-4e96-a1c2-79814543154b.png)

**Smartphone (please complete the following information):**
 - Device: [IOS]
 - Backend: [Metal]

**Additional context**
the version of filament is _1.12.5_

**Comment by dandingol03** [comment]
> Did you test that it blooms at all on screen?

i test it when i render the gltf which used by the material on screen has bloom effect

**Comment by romainguy** [comment]
What’s the offscreen camera exposure? Also, is your offscreen buffer transparent? I’m not sure but I think we may not support bloom on transparent render targets.

**Comment by dandingol03** [comment]
> What’s the offscreen camera exposure? Also, is your offscreen buffer transparent? I’m not sure but I think we may not support bloom on transparent render targets.

yes, the offscreen buffer is transparent.

**Comment by romainguy** [comment]
@pixelflinger can confirm but I believe that’s a limitation we have.

**Comment by dandingol03** [comment]
actually the effect i want to implement is `model stroke`, something is used to outstanding its outline with bloom effect. If the bloom effect with transparent render target is limited, how can i implement the` model stroke` in other way. The hierarchy of rendering has two levels:

1. the front level of rendering is cloth and person 
2. the lower level of rendering is ` model stroke`, and want to make it has bloom effect

the expected behavior i want as below:
![image](https://user-images.githubusercontent.com/13013579/228755991-71eadf7e-6712-4725-b8ce-df7351478b39.png)

**Comment by romainguy** [comment]
So it works as expected with OpenGL?

**Comment by dandingol03** [comment]
the android platform use other scheme to implement the bloom effect. I think if the opengl backend use the same scheme may also act like the metal backend

**Comment by dandingol03** [comment]
> I confirmed we don't support bloom on transparent render targets at the moment (for performance and code size reasons). However it seems like your effect doesn't need a separate render target?

I can't understand. I need to render three stuff:

1. first is the human glb
2. second is the cloth
3. the last is the model stroke.
If i choose not to render the mode stroke on the tansparent rendertarget, i need to use stencil function to pull out the cloth  outline. However i can't figure out some way to render these three stuff in one render pass
