### ISSUE TITLE
Support for triangle strips and fans

### ISSUE THREAD

**Issue by rawnsley** [google/filament#670]
Is there any reason GL_TRIANGLE_STRIP and GL_TRIANGLE_FAN are not available in the [default primitives](https://github.com/google/filament/blob/8fe11a067de6b5ecbce0fee8b003c33fa87250f0/libs/filabridge/include/filament/driver/DriverEnums.h#L129)?

**Comment by romainguy** [comment]
Strips and fans aren't really better than indexed triangles on modern hardware and can be easily converted to indexed triangles (I actually wouldn't be surprised if that's what some or many drivers do). We therefore decided to limit our API to the most flexible solution, indexed triangles.

There are many discussions available on this topic online if you're interested. Here's one for instance: http://hacksoflife.blogspot.com/2010/01/to-strip-or-not-to-strip.htm

Our preferred approach is therefore indexed triangles + an optimizer like meshopt (used by our filamesh tool for instance).
