### ISSUE TITLE
Filament AssetLoader createInstancedAsset API working example

### ISSUE THREAD

**Issue by gomtesh-amazon** [google/filament#6701]
**Problem**

I have a 3d sphere model stored in gltf file. I want to render 1000 instances of that sphere at different locations (x,y,z) in the space. I am trying to use AssetLoader->createInstancedAsset API ( attaching the code snippet below ). It creates the instances but, on the app, I can't see single instance of model rendered on the screen. 

Please note that, I am fairly new to Filament so apologies for silly mistakes if any. 

below is the code snippet I am using - 
`

        private fun loadGltf(name: String) {
              val points: List<Point> = generatePoints()
              var materialProvider = UbershaderProvider(modelViewer.engine)
              var assetLoader = AssetLoader(modelViewer.engine, materialProvider, EntityManager.get())
              var buffer = readAsset("models/greenColoredSphere.gltf")
              var filamentInstances: Array<FilamentInstance?> = arrayOfNulls(points.size)
              var filamentAsset = assetLoader.createInstancedAsset(buffer, filamentInstances)
      
              var i: Int = 0
              var size = 0.2f
              val tm = modelViewer.engine.transformManager
              var center = filamentAsset?.boundingBox?.center.let { v -> Float3(v?.get(0) ?: 0f,
                  v?.get(1) ?: 0f, v?.get(2) ?: 0f
              ) }
              val halfExtent =
                  filamentAsset?.boundingBox?.halfExtent.let { v -> Float3(v?.get(0) ?: 0f,
                      v?.get(1) ?: 0f, v?.get(2) ?: 0f) }
              val maxExtent = 2.0f * max(halfExtent)
              val translate = translation(Float3(maxExtent, 0f, 0f))
              for(i in 0..points.size - 1){
                  val instance = filamentInstances[i]
                  val transformRoot = instance?.let { tm.getInstance(it.root) }
                  val theta = i * 2.0 * Math.PI / points.size
                  val rotation = rotation(Float3(0f, 0f, 1f), theta.toFloat());
                  if (transformRoot != null) {
                      println("setting the transform") // gets printed for every instance
                      tm.setTransform(transformRoot, (rotation * translate).toFloatArray())
                  } else {
                      println("got the transform root as null")
                  }
                  if (instance != null) {
                      println("adding instance to scene") // gets printed for every instance
                      modelViewer.scene.addEntity(instance.root)
                  }
              }
        }`

**Describe the solution you'd like**
A working Kotlin example for rendering multiple instances of same model with demo image attached would be nice to have.

**Describe alternatives you've considered**
While writing above code, I referred sample CPP example provided here - [link](https://github.com/google/filament/blob/499c59aec5ebe7bfc0dd63a84f30a996f16c83bc/samples/gltf_instances.cpp)

**Comment by Qheb** [comment]
Hi,

Not sure that's the issue, but the main difference I see between your code, and the [ModelViewer.kt](https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt) example is that you do not call `resourceLoader.asyncBeginLoad(asset)`.
In the ModelViewer, this method is called after loading the glb file, and the renderable Entities are only added to the Scene when they are ready (see the [populateScene()](https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt#L309) method)
(Also, don't forget to call `resourceLoader.asyncUpdateLoad()` in the render loop)

**Comment by gomtesh-amazon** [comment]
That still didn't work. Based on your comment, for trial purpose, I modified loadGlb() method of ModelViewer.kt itself to create instanced asset like below. It covered all the points you mentioned above like `resourceLoader.asyncBeginLoad(asset)`, etc. 

```
     /**
     * Loads a monolithic binary glTF and populates the Filament scene.
     */
    fun loadModelGlb(buffer: Buffer) {
        destroyModel()

        val NUM_INSTANCES: Int = 10
        var filamentInstances: Array<FilamentInstance?> = arrayOfNulls(NUM_INSTANCES)
        asset = assetLoader.createInstancedAsset(buffer, filamentInstances)

        // Arrange all instances into a circle.
        val tcm = engine.getTransformManager()
        val halfExtent = asset?.boundingBox?.halfExtent.let { v -> Float3(v?.get(0) ?: 0f, v?.get(1) ?: 0f, v?.get(2) ?: 0f) }
        val maxExtent = 2.0f * max(halfExtent)
        val translation = translation(Float3(maxExtent, 0f, 0f))

        for (inst in 0 until NUM_INSTANCES) {
            val instance = filamentInstances[inst]
            val transformRoot = instance?.let { tcm.getInstance(it.root) }
            val theta = inst * 2.0f * Math.PI.toFloat() / NUM_INSTANCES.toFloat()
            val rotation = rotation(Float3(0f, 0f, 1f), theta);
            if (transformRoot != null) {
                tcm.setTransform(transformRoot, (rotation * translation).toFloatArray())
            }
            println("applied transformation to instance $inst") // gets printed 10 times which is NUM_INSTANCES 
        }

        asset?.let { asset ->
            resourceLoader.asyncBeginLoad(asset)
            animator = asset.getInstance().animator
            asset.releaseSourceData()
        }
    }
```
And, then from my MainActivity, I just called `modelViewer.loadModelGlb(buffer)`. It should have rendered multiple instances now, right ? But, it is still showing only 1 instance rendering on the screen.

**Comment by Qheb** [comment]
Yes it should work, with one little detail, your `theta` value is in radians, but the `rotation()` method takes degrees as input. So it might be that all your instances are stacked at the same place.

Please let me know if this works correctly for you, because I'm having [some issues with the translation() method](https://github.com/google/filament/discussions/6778), and I have the same problem when trying your code (but I do have the 10 instances created and added to the scene).

**Comment by Qheb** [comment]
I used the `degrees()` method from `com.google.android.filament.utils.Scalar` but it yes it should give the same result with `Math.toDegrees()`.

Unfortunately my code won't help you since, like I said, I have some issues with the translations, so I removed your translation matrix and only used the `val rotation = rotation(Float3(0f, 0f, 1f), degrees(theta))`.
But you are using a sphere as a model, so you won't see any difference after a rotation without translation.

I see that you want to arrange your instances as a circle. You have to do the rotation first, then the translation (once the x axis has been rotated).
But with matrix multiplication, you have to write the operation **from right to left** so you should try changing your code to

```kotlin
tcm.setTransform(transformRoot, (translation * rotation).toFloatArray())
```

I suspect that you current code translates all the spheres at the same place, then rotates it on themselves.

**Comment by gomtesh-amazon** [comment]
Yay, it worked. Thanks a lot. 
Just to summarize, not returning a row-major matrix using transpose method was the problem. 
Filament requires matrix to be in row-major format.

**Comment by Qheb** [comment]
Glad it helped :slightly_smiling_face: 

Just for clarity, Filament does require the matrices to be in column-major format, but `Mat4.toFloatArray()` is returning it in row-major format.

**Comment by gomtesh-amazon** [comment]
One follow up question on this - 
How to remove one of the FilamentInstance from the filament scene ? I have tried following - 
```
engine.renderableManager.destroy(engine.renderableManager.getInstance(filamentInstanceNumberOne.root))
```

**Comment by gomtesh-amazon** [comment]
@Qheb tagging you since missed in the last comment. Thank you in advance :)

**Comment by Qheb** [comment]
Hi @gomtesh-amazon ,

If you want to remove only one of your FilamentInstances from your scene, you can use `FilamentInstances.getEntities()` (`FilamentInstanceOne.entities` instead of `FilamentInstanceOne.asset.entities`).

This should only give you the entities of the instance instead of the entities of all the instances of the asset.
