### ISSUE TITLE
Missing function getWorldFromClipMatrix()

### ISSUE THREAD

**Issue by rawnsley** [google/filament#671]
Vertex shader function [getWorldFromClipMatrix](https://github.com/google/filament/blob/master/docs/Materials.md.html#L1324) is documented but not implemented.

I don't actually need it, but I was trying to work out why [this line](https://github.com/google/filament/blob/master/shaders/src/getters.vs#L103) didn't use it (assuming _worldFromClipMatrix = worldFromViewMatrix * viewFromClipMatrix_)

**Comment by romainguy** [comment]
Looks like we just forgot to add it :) Thanks for noticing!
