### ISSUE TITLE
Documentation for UV texture inversion behaviour

### ISSUE THREAD

**Issue by rawnsley** [google/filament#672]
Vertex texture coordinates [are inverted vertically](https://github.com/google/filament/blob/master/shaders/src/common_material.vs#L34) by default, but this behaviour is not explicitly documented.

I believe that this is done to match the top-down convention of bitmap images and therefore to make client code simpler and more intuitive. This may actually be a de facto standard for all modern graphics libraries and completely unsurprising to veterans, but as a newbie it caused me a little confusion. Perhaps a sentence in the [MaterialVertexInputs section](https://github.com/google/filament/blob/master/docs/Materials.md.html#L1164) would suffice?

In case it is relevant: my particular use case involves storing non-texture related values in the UV0 buffer such that the inversion of the Y coordinate makes no sense.

**Comment by romainguy** [comment]
Thanks for the feedback! Yes it would indeed be useful to document this behavior. Note that for non-texture related data I would recommend using the color attribute, it's a more common way to use data in vertex shaders. You can also use custom variables (interpolants).
