### ISSUE TITLE
Android Demo and Development api documentation

### ISSUE THREAD

**Issue by uncleheng** [google/filament#6733]
I generate the ‘out’ directory by executing the command .'out' The command contains "android-release", "cmaker-android-release-aarch64", "cmaker-android-release-arm7", "cmaker-android-release-x86", and "cmake- release" .How do I get my demo to run.

The second question：
Is there any documentation for android, such as api documentation

**Comment by romainguy** [comment]
Once you've built Filament, you need to open the `android/` folder as an Android Studio project.
