### ISSUE TITLE
Is the world coordinate system and model coordinate system of Diligent Engine left-handed or right-handed coordinate system

### ISSUE THREAD

**Issue by zhichangxuexi** [google/filament#6738]
Is the world coordinate system and model coordinate system of Diligent Engine left-handed or right-handed coordinate system

**Comment by romainguy** [comment]
It's right handed, see https://google.github.io/filament/Filament.html#imagingpipeline/coordinatessystems/worldcoordinatessystem

**Comment by zhichangxuexi** [comment]
![image](https://user-images.githubusercontent.com/40328051/231932283-3bda7d70-9fd1-42eb-8f6f-04b93530933e.png)

Look at these code in pic above, how does it feel like it's a left-hand coordinate system
