### ISSUE TITLE
【Android】ld: error: undefined symbol: dl_iterate_phdr

### ISSUE THREAD

**Issue by dandingol03** [google/filament#6744]
**Describe the bug**
Compiling Failed when compile android on mac intel chip

**To Reproduce**
1. build.sh -i -p desktop release
2. build.sh -i -p android release

**Logs**

FAILED: libs/math/test_math 
: && /Users/wangjunjie/Downloads/android-sdk-mac/ndk/22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++ -DANDROID -fPIE -mcpu=cortex-a57 -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -fexceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -frtti -fPIE -pie -static-libstdc++ -Wl,--gc-sections libs/math/CMakeFiles/test_math.dir/tests/test_fast.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_half.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_mat.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_vec.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_quat.cpp.o -o libs/math/test_math  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/math/libmath.a  third_party/libgtest/tnt/libgtest.a  -Wl,-Bdynamic  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic  -pthread && :
ld: error: undefined symbol: dl_iterate_phdr
>>> referenced by unwind-dw2-fde-dip.c:485 (/Volumes/Android/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-dw2-fde-dip.c:485)
>>>               unwind-dw2-fde-dip.o:(_Unwind_Find_FDE) in archive /Users/wangjunjie/Downloads/android-sdk-mac/ndk/22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/libgcc_real.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**
filament version: 1.12.5
mac os version: 13.2.1

**Comment by romainguy** [comment]
Your machine can't run the ndk itself. Make sure you've installed it properly.
