### ISSUE TITLE
Create custom Skybox with Image

### ISSUE THREAD

**Issue by Amitdygon** [google/filament#6766]
Hello

I want to create custom skybox from image i have used this png image. But i am getting error

**in KtxBundle:116
reason: KTX has unexpected identifier

Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 14826 (com.avatus), pid 14826 (com.avatus)
Cmdline: com.avatus
pid: 14826, tid: 14826, name: com.avatus >>> com.avatus <<<
https://github.com/SceneView/sceneform-android/pull/1 pc 0000000000171250 /data/app/~~5br1hx3y52s0b77rIs1mQQ==/com.avatus-7fE7oFl6uJNpLDv6zqqnzw==/base.apk!libfilament-jni.so (utils::TPanicutils::PreconditionPanic::panic(char const*, char const*, int, char const*, ...)+192) (BuildId: b0826f2754a95429ecf9e89c83684e184d383cff)
2023-04-25 15:31:59.218 18299-18329 FA com.avatus V onActivityCreated**

Here what i have used to create custom skybox.

         ` val sky = convertByte()
    binding.transparentSceneView.scene.renderer?.filamentRenderer?.engine?.let {
        KTXLoader.createSkybox(it, sky).apply {
            binding.transparentSceneView.scene.renderer?.filamentScene?.skybox = this
        }
    }

      private fun convertByte(): ByteBuffer {
    val stream = ByteArrayOutputStream()
    val bitmap = BitmapFactory.decodeResource(resources, R.drawable.test_img)
    bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
    return ByteBuffer.wrap(stream.toByteArray())
}`

**Comment by romainguy** [comment]
KtxLoader expects data in KTX format, not a PNG file.

**Comment by Amitdygon** [comment]
> KtxLoader

How i can create custom ktx file or how i set a custom image into skybox can you please refer me something.

**Comment by romainguy** [comment]
You can use the `cmgen` tool we provide to create those KTX files.

**Comment by Amitdygon** [comment]
> cmgen

is this work in android . i have search for android but not able to find any good document. can you please help me for this i am really stuck more than 15 days on it.
