### ISSUE TITLE
OpenGL driver readPixels crash on web (emscripten wasm)

### ISSUE THREAD

**Issue by MemomiAlexCherkashin** [google/filament#6780]
**Describe the bug**
There is a bug with memory allocation caused by wrong memory allocation to store temporary buffer for pixels

So it's not really necessary to reproduce the bug as you can ease see it in the code **OpenGLDriver.cpp**, lines **2800-2802** (under section `#if defined(__EMSCRIPTEN__)`): 
```
std::unique_ptr<uint8_t> clientBuffer = std::make_unique<uint8_t>(pboSize);
glGetBufferSubData(GL_PIXEL_PACK_BUFFER, 0, pboSize, clientBuffer.get());
vaddr = clientBuffer.get();
```
This code allocates single uint8_t value in the heap with value pboSize. But what it should do is to allocate array of  uint8_t  values with size pboSize. So expected fix is to replace these 3 lines by:
```
std::vector<uint8_t> clientBuffer(pboSize);
glGetBufferSubData(GL_PIXEL_PACK_BUFFER, 0, pboSize, clientBuffer.data());
vaddr = clientBuffer.data();
```

**To Reproduce**
1. Just use `renderer.readPixels(...)` for wasm (it's not exported with embind, so need to call add c++ code like:
```
   renderer->readPixels(renderTarget,
              grabRect[0],
              grabRect[1],
              grabRect[2] - grabRect[0],
              grabRect[3] - grabRect[1],
              std::move(buffer));
```

**Expected behavior**
It should not crash

**Desktop:**
 - OS: web
 - Backend: WebGL

**Comment by romainguy** [comment]
Thanks! Yes it's definitely a silly issue.
