### ISSUE TITLE
Fog affected by IBL rotation along X/Z axis since e2e5f7cee968872683d0fb8cdbe6dfc8bb4196fe

### ISSUE THREAD

**Issue by MrKepzie** [google/filament#6798]
**Describe the bug**

Since [this commit](https://github.com/google/filament/commit/e2e5f7cee968872683d0fb8cdbe6dfc8bb4196fe), the fog is rotated  by the rotation of the IBL.

**To Reproduce**

- Change the following line in  `filament/libs/viewer/src/Settings.cpp` to  see that the IBL rotation along X axis affects fog

From
`ibl->setRotation(math::mat3f::rotation(settings.iblRotation, math::float3 { 0, 1, 0 }));`

To
`ibl->setRotation(math::mat3f::rotation(settings.iblRotation, math::float3 { 1, 0, 0 }));`

- Compile gltf_viewer and run with an IBL

**Expected behavior**

The fog should not be rotated with the IBL

**Screenshots**

Compare the 2 screenshots below which just vary the IBL rotation

![Screenshot 2023-05-09 at 18 23 17](https://github.com/google/filament/assets/4058448/22adad52-6976-474c-98fe-365d787b11a2)
![Screenshot 2023-05-09 at 18 23 31](https://github.com/google/filament/assets/4058448/2e40104e-afdc-4012-83f4-e4a9aa44c772)

**Desktop (please complete the following information):**

All OS and backends

**Comment by pixelflinger** [comment]
@MrKepzie I think I agree that the fog shouldn't be rotated with the IBL, however, this behavior has always been there, as far as I can tell. I have sync'ed one change before the one you're pointing to (9d30233) and I can see this behavior. Note that there are two places where setRotation should be changed, in settings and viewergui.
Can you confirm?

**Comment by MrKepzie** [comment]
It was not there at least since our previous rebase (which was against 1.28 I think).
I confirm that this is fixed now
