### ISSUE TITLE
There exists a bug about SDL version when I run the hellopbr sample

### ISSUE THREAD

**Issue by YounthYue** [google/filament#6812]
**Describe the bug**
There exists a bug about SDL version when I run the hellopbr sample

**To Reproduce**
1.  ~/ge/filament$ ./build.sh debug
2.  ~/ge/filament$ ./out/cmake-debug/samples/hellopbr 

**Expected behavior**
show a window display the sample

**Screenshots**
![image](https://github.com/google/filament/assets/48077631/cc44e90b-b3c2-42cf-b305-3e4f41d64ca5)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - GPU: NVIDIA GTX 1060
 - Backend: OpenGL

**Additional context**
The output information as follows:

utils::PostconditionPanic
in void *getNativeWindow(SDL_Window *):27
in file filament/libs/filamentapp/src/NativeWindowHelperLinux.cpp
reason: SDL version unsupported!
#0      hellopbr                            0x7f445631776d (null) + 139931480586093
#1      hellopbr                            0x7f445632e32b (null) + 139931480679211
#2      hellopbr                            0x7f445632e0ef (null) + 139931480678639
#3      hellopbr                            0x7f445632dfc1 (null) + 139931480678337
#4      hellopbr                            0x7f4455dbc155 (null) + 139931474968917
#5      hellopbr                            0x7f4455dac1be (null) + 139931474903486
#6      hellopbr                            0x7f4455da8638 (null) + 139931474888248
#7      hellopbr                            0x7f4455d765bb (null) + 139931474683323
#8      libc.so.6                           0x7f44559e9d90 (null) + 139931470962064
#9      libc.so.6                           0x7f44559e9e40 __libc_start_main + 128

libc++abi: terminating due to uncaught exception of type utils::PostconditionPanic
Aborted (core dumped)

**Comment by romainguy** [comment]
```
    SDL_SysWMinfo wmi;
    SDL_VERSION(&wmi.version);
    ASSERT_POSTCONDITION(SDL_GetWindowWMInfo(sdlWindow, &wmi), "SDL version unsupported!");
```

Looks like we couldn't even get window info and/or create the window.

**Comment by poweifeng** [comment]
Are you running wayland?  (check with `echo $XDG_SESSION_TYPE`).

**Comment by YounthYue** [comment]
> Are you running wayland? (check with `echo $XDG_SESSION_TYPE`).
I am not running in wayland. And the result of the code `echo $XDG_SESSION_TYPE` is blank.
![image](https://github.com/google/filament/assets/48077631/bdbcf70c-98ae-4761-bddc-b636599974f6)

**Comment by poweifeng** [comment]
I see, then are you running WSL (Windows Subsystem for Linux)? I don't think this is a supported path for compilation. You can try the regular windows build: https://github.com/google/filament/blob/main/BUILDING.md#windows

**Comment by YounthYue** [comment]
> I see, then are you running WSL (Windows Subsystem for Linux)? I don't think this is a supported path for compilation. You can try the regular windows build: https://github.com/google/filament/blob/main/BUILDING.md#windows
The filament in windows running well. Maybe it is the WSL that occurs the problem. I will try run filament in a separate Linux.

**Comment by YounthYue** [comment]
Do not run filament in  WSL (Windows Subsystem for Linux). Because WSL lacks a lot of packages. 
<img width="794" alt="515646fb5b00a8e9e26a6eb750eb884" src="https://github.com/google/filament/assets/48077631/acd7bad0-0dc3-421b-a858-71b5dafcf8fc">
