### ISSUE TITLE
failed assertion `textureRequirements.layers <= CONFIG_MAX_SHADOW_LAYERS' with point light shadows

### ISSUE THREAD

**Issue by ennis** [google/filament#6821]
**Describe the bug**
In filament v1.36.0 compiled in debug mode, this assertion:
https://github.com/google/filament/blob/2c6f723317171b8c054af4ae44d7b91252ae0e0a/filament/src/ShadowMapManager.cpp#L144
is triggered  when there are multiple point lights with `castShadows(true)` in a scene.

**To Reproduce**
One way to reproduce the issue is to enable shadows for the point lights in the lightbulb sample (`void setup()`, L208):
<details><summary>Details</summary>
<p>
    
    g_lights.push_back(em.create());
    LightManager::Builder(LightManager::Type::POINT)
            .color(Color::toLinear<ACCURATE>(sRGBColor(0.98f, 0.92f, 0.89f)))
            .intensity(1000.0f, LightManager::EFFICIENCY_LED)
            .position({ 0.0f, -0.2f, -3.0f })
            .falloff(4.0f)
            .castShadows(true)
            .build(*engine, g_lights.back());
    
    g_lights.push_back(em.create());
    LightManager::Builder(LightManager::Type::FOCUSED_SPOT)
            .color(Color::toLinear<ACCURATE>(sRGBColor(0.98f, 0.12f, 0.19f)))
            .intensity(2000.0f, LightManager::EFFICIENCY_LED)
            .position({ 0.6f, 0.6f, -3.2f })
            .direction({ -1.0f, 0.0f, 0.0f })
            .spotLightCone(static_cast<float>(M_PI / 8), static_cast<float>((M_PI / 8) * 1.1))
            .falloff(4.0f)
            .castShadows(true)
            .build(*engine, g_lights.back());
    
    g_lights.push_back(em.create());
    LightManager::Builder(LightManager::Type::POINT)
            .color(Color::toLinear<ACCURATE>(sRGBColor(0.18f, 0.12f, 0.89f)))
            .intensity(1000.0f, LightManager::EFFICIENCY_LED)
            .position({ -0.6f, 0.3f, -3.2f })
            .falloff(2.0f)
            .castShadows(true)
            .build(*engine, g_lights.back());
    
    g_lights.push_back(em.create());
    LightManager::Builder(LightManager::Type::POINT)
            .color(Color::toLinear<ACCURATE>(sRGBColor(0.88f, 0.82f, 0.29f)))
            .intensity(1000.0f, LightManager::EFFICIENCY_LED)
            .position({ 0.0f, 1.5f, -3.5f })
            .falloff(2.0f)
            .castShadows(true)
            .build(*engine, g_lights.back());
    
    g_lights.push_back(em.create());
    LightManager::Builder(LightManager::Type::FOCUSED_SPOT)
            .color(Color::toLinear<ACCURATE>(sRGBColor(0.12f, 0.98f, 0.19f)))
            .intensity(2000.0f, LightManager::EFFICIENCY_LED)
            .position({ 0.0f, 0.6f, -3.2f })
            .direction({  1.0f, 0.0f, 0.0f })
            .spotLightCone(static_cast<float>(M_PI / 8), static_cast<float>((M_PI / 8) * 1.1))
            .falloff(4.0f)
            .castShadows(true)
            .build(*engine, g_lights.back());
</p>
</details> 

Then compile in debug mode, run the sample on any model with the `--more-lights` option, e.g.:

      .\lightbulb.exe --more-lights assets\models\monkey\monkey.obj

**Expected behavior**
No assert, or at least no assert with such a low number of point lights (3).

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - GPU: gtx 2070
 - Backend: OpenGL

**Comment by pixelflinger** [comment]
@ennis I followed the instructions in the bug, but couldn't reproduce the assertion.

Could you attach the exact diffs to lightbulb?

I checked the assert line and I get `textureRequirements.layers == 21` and `CONFIG_MAX_SHADOW_LAYERS == 64`

**Comment by ennis** [comment]
here's the patch that I used:

```diff
diff --git a/samples/lightbulb.cpp b/samples/lightbulb.cpp
index 5c5d7359a..eabd50e46 100644
--- a/samples/lightbulb.cpp
+++ b/samples/lightbulb.cpp
@@ -255,6 +255,7 @@ static void setup(Engine* engine, View* view, Scene* scene) {
                 .intensity(1000.0f, LightManager::EFFICIENCY_LED)
                 .position({ 0.0f, -0.2f, -3.0f })
                 .falloff(4.0f)
+                .castShadows(true)
                 .build(*engine, g_lights.back());
 
         g_lights.push_back(em.create());
@@ -274,6 +275,7 @@ static void setup(Engine* engine, View* view, Scene* scene) {
                 .intensity(1000.0f, LightManager::EFFICIENCY_LED)
                 .position({ -0.6f, 0.3f, -3.2f })
                 .falloff(2.0f)
+                .castShadows(true)
                 .build(*engine, g_lights.back());
 
         g_lights.push_back(em.create());
@@ -282,6 +284,7 @@ static void setup(Engine* engine, View* view, Scene* scene) {
                 .intensity(1000.0f, LightManager::EFFICIENCY_LED)
                 .position({ 0.0f, 1.5f, -3.5f })
                 .falloff(2.0f)
+                .castShadows(true)
                 .build(*engine, g_lights.back());
 
         g_lights.push_back(em.create());
```

I compiled in debug mode and then ran `lightbulb.exe -m assets\models\monkey\monkey.obj`

**Comment by ennis** [comment]
Looking over it again, I can't reproduce the issue anymore after a rebuild; I suspect that it might have been caused by a botched rebase on our end. Sorry for the noise and the wasted time.
