### ISSUE TITLE
Use precomputed Ki coefs

### ISSUE THREAD

**Issue by cfnptr** [google/filament#6825]
**Is your feature request related to a problem? Please describe.**

We can precompute Ki for common band count (1, 2, 3). And store them as coefs array.
In case of different band count fallback to the current runtime calculation.

https://github.com/google/filament/blob/3aa69135383abe2eb649ead7da0c95908d8e1a31/libs/ibl/src/CubemapSH.cpp#L77-L88

**Comment by pixelflinger** [comment]
why does it matter?

**Comment by cfnptr** [comment]
Because It will reduce computation time a bit, simplify code. If don't want as you want.
