### ISSUE TITLE
vulkan: revisit smart pointer/object ownership in backend

### ISSUE THREAD

**Issue by poweifeng** [google/filament#6838]
Right now we have uses of raw pointers and shared_ptr.  We should think about just raw pointers and unique_ptrs to avoid the overhead of shared_ptr and the danger of unclear ownerhsip.

**Comment by pixelflinger** [comment]
Also what I really don't like about shared_ptr, is that you don't know when/where the destructor will run. It could be at an inopportun time, or on the wrong thread, or within a critical section with a lock held, etc ...
