### ISSUE TITLE
Rendering on surface other than native window ?

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#684]
You guys might remember me asking about crash on integrating filament into after effects as a plugin. I have a another question. 

 When I click on the plugin button in my plugin I pop up the filament Suzanne sample window and on render before endframe() I copy back the rendered image( using renderer->readpixels()) to the after effects output buffer. The way you display image on the main after effects view is you just write to the ouput buffer that ae provides. So when I close the suzanne window the suzannne  image is displayed in the main after effects view. That seems to be working well, but I also need to able to control (for example I may want to move an object with effects parameters controls) and display the filament view in the main after effects view without opening the SDL window and I am not sure how to achieve that as the swapchain seems to be tied to a native window.  Perhaps If I could render to a buffer in memory instead of a window, that way I could copy the image to the after effects ouput buffer and display the image in the main after effects view. Is there such a feature or other ways I can achieve my goal ? 

Thanks,
Thirdmenson

**Comment by romainguy** [comment]
At least on Android, the native window is not a window in the sense of a visual window that the user can interact with. I assume it's the same on Windows. Under the hood we treat the native window we receive as an `HDC` type.

**Comment by thirdmenson** [comment]
Looks like creating a hidden SDL window works !
