### ISSUE TITLE
Shaders that can be compiled with Matc in lower versions, but errors are reported when compiling with higher versions

### ISSUE THREAD

**Issue by Haidiye00** [google/filament#6853]
![img_v2_31f822a7-78d1-49a9-8599-3cca15633edg](https://github.com/google/filament/assets/132528822/b0896da7-2d74-4c52-bfa1-35685a4efa8b)

I referenced an Open3D shader, which may have been compiled with a lower version of version 1.2, but I ported it to version 1.36 and compiled a warning. What is the problem? Can you help me take a look，thanks~

**Comment by romainguy** [comment]
Please don't post screenshots but attach the material causing the issue as well as the compilation logs.

**Comment by romainguy** [comment]
Those warnings are also likely harmless.

**Comment by Haidiye00** [comment]
material {
    name : defaultLit,
    shadingModel : lit,
    doubleSided : true,

    parameters : [
        { type : float3,    name : baseColor },
        { type : float,     name : baseMetallic },
        { type : float,     name : baseRoughness },
        { type : float,     name : reflectance },
        { type : float,     name : clearCoat },
        { type : float,     name : clearCoatRoughness },
        { type : float,     name : anisotropy },
        { type : float,     name : pointSize },
        { type : sampler2d, name : albedo },
        { type : sampler2d, name : ao_rough_metalMap },
        { type : sampler2d, name : normalMap },
        { type : sampler2d, name : reflectanceMap },
// NOTE: Disable clear coat textures to avoid Filament warning about exceeding
// 16 sampler limit. There is currently no supported standard format that
// supports these textures so they don't get used any way. Once the shader has
// been updated to combine roughness/metallic/reflectance/ao these textures
// will be reenabled.
// 
//        { type : sampler2d, name : clearCoatMap },
//        { type : sampler2d, name : clearCoatRoughnessMap },
        { type : sampler2d, name : anisotropyMap }
    ],
    requires : [
        color, uv0
    ]
}

vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        gl_PointSize = materialParams.pointSize;
    }
}

fragment {
    void material(inout MaterialInputs material) {
        // Modifications to normal must be done before prepareMaterial call
        material.normal = texture(materialParams_normalMap, getUV0()).xyz * 2.0 - 1.0;
        material.normal.y *= -1.0; // NOTE: including this line because Filament samples do
        // Flip normals for point clouds in case of inspection mode
        // if (dot(getWorldGeometricNormalVector(), getWorldViewVector()) < 0.0)
            // material.normal = -material.normal;
        prepareMaterial(material);

        material.baseColor.rgb = getColor().rgb * materialParams.baseColor * texture(materialParams_albedo, getUV0()).rgb;
        float3 ao_rough_metal = texture(materialParams_ao_rough_metalMap, getUV0()).rgb;
        material.metallic = materialParams.baseMetallic * ao_rough_metal.b;
        material.roughness = materialParams.baseRoughness * ao_rough_metal.g;
        material.ambientOcclusion = ao_rough_metal.r;
        //material.reflectance = materialParams.reflectance;
        //material.anisotropy = materialParams.anisotropy;
        material.reflectance = materialParams.reflectance * texture(materialParams_reflectanceMap, getUV0()).r;
        // See note above about following disabled textures
        material.clearCoat = materialParams.clearCoat;
        //material.clearCoat = materialParams.clearCoat * texture(materialParams_clearCoatMap, getUV0()).r;
        material.clearCoatRoughness = materialParams.clearCoatRoughness;
        //material.clearCoatRoughness = materialParams.clearCoatRoughness * texture(materialParams_clearCoatRoughnessMap, getUV0()).r;
        material.anisotropy = materialParams.anisotropy * texture(materialParams_anisotropyMap, getUV0()).r;
    }
}

**Comment by Haidiye00** [comment]
During compilation, the CPU memory will reach 100%, and it may take 10 minutes for the compilation to succeed. Can you analyze what the problem is? It seems to be closely related to ShadingModel: lit

**Comment by romainguy** [comment]
10 minutes for this single material?

**Comment by Haidiye00** [comment]
yes,you can try matc.exe(1.36 version)

**Comment by romainguy** [comment]
I don't have a Windows machine but on macOS this material compiles immediately and without warnings, even when compiling for all APIs and all targets. How do you invoke `matc`?

**Comment by pixelflinger** [comment]
Debug builds can be extremely slow on Windows. Make sure you're using a release build.

**Comment by pixelflinger** [comment]
no repro steps
