### ISSUE TITLE
Memory leak when reading pixel buffers

### ISSUE THREAD

**Issue by DianxinWang** [google/filament#6860]
**Describe the bug**

<img width="1905" alt="Pasted Graphic 2" src="https://github.com/google/filament/assets/36990568/2dda0f39-708d-4239-a9e8-3cfb93f4fc45">

**Comment by DianxinWang** [comment]
I would be glad to raise a pull request to contribute.

**Comment by DianxinWang** [comment]
`delete p;` should be called.

**Comment by bejado** [comment]
The `delete p` statement is [here](https://github.com/google/filament/blob/57424cc7e9ce040d966a414cd2ac25709a8b090c/filament/backend/src/metal/MetalDriver.mm#L1300).
