### ISSUE TITLE
rendering issue on gltf_viewer when flare enabled with some focal length and focus distance in arch linux

### ISSUE THREAD

**Issue by arduinocc04** [google/filament#6888]
**Describe the bug**
Small black boxes attached to reflected sunlight appear on gltf_viewer screen when flare enabled with some focal length and focus distance in arch linux with Vulkan

**To Reproduce**
1. `./gltf_viewer`
2. Enable Flare.
3. Change the Focal length of camera sufficiently.
4. Enable DoF
5. Change the Focus distance of DoF sufficiently.

However, changing Aperture of camera, Speed of camera, ISO of camera may make easier to reproduce this bug.

**Expected behavior**
The black boxes do not appear.

**Screenshots**
Aperture, Speed, ISO, Focal length, Focus distance changed
![image](https://github.com/google/filament/assets/27909137/25467a07-f183-428a-a327-6633291e3a2d)
![image](https://github.com/google/filament/assets/27909137/c8422040-b6cd-4be2-b81c-f6f343e9c02d)
![image](https://github.com/google/filament/assets/27909137/0c62201e-dcf5-4df3-990e-e0869bd2e80d)

Aperture, Focal length, Focus distance changed
![image](https://github.com/google/filament/assets/27909137/d842e30b-0cc9-453f-9584-88edf4291679)

Focal length, Focus distance changed
![image](https://github.com/google/filament/assets/27909137/c3057c6b-3fc9-47c5-9e8e-797083168261)

**Logs**
FEngine (64 bits) created at 0x55eda2730700 (threading is enabled)
FEngine resolved backend: Vulkan
Vulkan device driver: NVIDIA 530.41.03
Selected physical device 'NVIDIA GeForce RTX 3060' from 1 physical devices. (vendor 0x10de, device 0x2504, driver 0x848a40c0, api 1.3)
Backend feature level: 1
FEngine feature level: 1
vkCreateSwapchain: 1024x640, 44, 0, 3, 1

**Desktop (please complete the following information):**
 - OS: Arch Linux - 6.3.6-arch1-1
 - GPU: NVIDIA RTX 3060 (12GB) - NVIDIA 530.41.03
 - Backend: Vulkan

**Comment by poweifeng** [comment]
Are you able to reproduce this in the opengl backend?  (Add `-a opengl`) to your `gltf_viewer` command. 

Also, what version of Filament are you working with?

**Comment by arduinocc04** [comment]
With opengl, I failed to reproduce that bug. And I used v1.38.0

**Comment by arduinocc04** [comment]
I reproduced this in windows with same way
![image](https://github.com/google/filament/assets/27909137/2599ab1e-88da-48d8-a130-f1f6f25650eb)

**Comment by pixelflinger** [comment]
This does look like an overflow/infinity/nan -- it could be that vk is handling this differently. might still be a bug in the flare shader (we might need some clamping somewhere).  It could also be a mediump issue -- maybe nvidia honors it on vulkan?

**Comment by arduinocc04** [comment]
Is this bug needed to fixed fast? If not, can I fix this bug? I can start fixing next Wednesday. And since I'm completely first in this field, fixing it may take a long time.

**Comment by poweifeng** [comment]
Sure, we're open to you fixing it.  I'm unable to repro even on a similar NVIDIA/Linux setup (debian + RTX 3070). 
Feel free to assign it to yourself.

**Comment by arduinocc04** [comment]
Okay. Thanks!

**Comment by poweifeng** [comment]
> Sure, we're open to you fixing it. I'm unable to repro even on a similar NVIDIA/Linux setup (debian + RTX 3070). Feel free to assign it to yourself.

Actually I am able to repro now. It's independent of flare but just need to adjust dof focus distance and camera focal length.

I suggest looking into https://github.com/google/filament/blob/main/filament/src/materials/dof/dof.mat

**Comment by arduinocc04** [comment]
I think this bug happens when using [nvidia](https://archlinux.org/packages/extra/x86_64/nvidia/) library in linux.  
when I use [vulkan-intel](https://archlinux.org/packages/extra/x86_64/vulkan-intel/), I couldn't generate this bug.

**Comment by poweifeng** [comment]
Fixed in #6943
