### ISSUE TITLE
`setMaterialInstanceAt` doesn't update the entity material

### ISSUE THREAD

**Issue by victorbrndls** [google/filament#6890]
**Describe the bug**
I'm calling `RenderableManager.setMaterialInstanceAt` to change the entity material but nothing happens.

I'm creating the models in blender and exporting them using a GLB file. The file gets rendered correctly but I can't change the entity's colors.

The only warning I get is:
`setMaterialInstanceAt() on primitive 0 of Renderable at 136: declared attributes [] do no satisfy required attributes [POSITION, TANGENTS, COLOR, UV0, UV1]`

**To Reproduce**
The whole code is in this [gist](https://gist.github.com/victorbrndls/e75f3ac2a106a423dca47985efcfb3b9).
```
// Create ModelViewer
modelViewer = ModelViewer(surfaceView, uiHelper = uiHelper)

// Load GLB file
val buffer = surfaceView.context.assets.open("models/cube3.glb").use { input ->
	val bytes = ByteArray(input.available())
	input.read(bytes)
	ByteBuffer.wrap(bytes)
}

modelViewer.loadModelGlb(buffer)
modelViewer.transformToUnitCube()

// Get materials from GLB file
val materials = modelViewer.asset!!.instance.materialInstances

// Update the entity color
modelViewer.engine.renderableManager.setMaterialInstanceAt(
	modelViewer.asset!!.getFirstEntityByName("Cube24"),
	0,
	materials[0]
)
```

If I print the materials I get
```
val materials = modelViewer.asset!!.instance.materialInstances
materials.forEach { Logger.d("Color: ${it.name}") }

// Output
Color: Material.019
Color: Material.020
Color: Default GLTF material
```

If I print the entities I get
```
modelViewer.asset!!.entities.forEach { entity ->
	Logger.d("Entity: ${modelViewer.asset!!.getName(entity)}")
}

// Output
Entity: Cube24
Entity: Cube25
Entity: Cube26
Entity: Light-XY
Entity: Light-Xy
Entity: Light-xy
```

**Expected behavior**
Calling `setMaterialInstanceAt` should set the color of "Cube24" to Red (`Material-019`)

**Screenshots**
This is the model rendered on my phone. The first cube should be red too.
![1686596232090](https://github.com/google/filament/assets/11446530/1788748b-3779-4a95-9814-3d51cdd1ddd7)

This is the model on blender.
![image](https://github.com/google/filament/assets/11446530/f3109bc6-abb0-4c85-97f3-7e539a35fa7f)

**Logs**
All logs from Filament:
```
FEngine (64 bits) created at 0x7578710000 (threading is enabled)
Using ASurfaceTexture
FEngine resolved backend: OpenGL
[Qualcomm], [Adreno (TM) 512], [OpenGL ES 3.2 V@415.0 (GIT@389f9e1, I4b4012dc33, 1605186217) (Date:11/12/20)], [OpenGL ES GLSL ES 3.20]
Feature level: 2
	Active workarounds:
	dont_use_timer_query
	disable_sidecar_blit_into_texture_array
	split_easu
	allow_read_only_ancillary_feedback_loop
	enable_initialize_non_used_uniform_array
Backend feature level: 2
FEngine feature level: 1
```

**Smartphone:**
 - Device: Xiaomi Note 7
 - OS: Android Q 10

**Additional context**
- [GLB file](https://drive.google.com/file/d/1WEz7668V3elKb7vbWysTi0v5Qbpu59RV/view?usp=sharing)
- [GLTF file](https://gist.github.com/victorbrndls/4f638f986139b67115290f8297aeb139)

I'm using
```
implementation 'com.google.android.filament:filament-android:1.36.0'
implementation 'com.google.android.filament:filament-utils-android:1.36.0'
implementation 'com.google.android.filament:gltfio-android:1.36.0'
```

**Comment by pixelflinger** [comment]
`setMaterialInstanceAt` takes an `instance`, not an `Entity`. You need to call `getInstance(entity)` on the `RenderableManager`.
