### ISSUE TITLE
Triangle sample freeze with google browser for few seconds on mac

### ISSUE THREAD

**Issue by hammerLWA** [google/filament#6894]
Triangle sample freeze with google browser for few seconds on mac.

 - OS: [MAC]
 - GPU: []
 - Backend: [OpenGL]

**Comment by pixelflinger** [comment]
This is a known issue due to a bug in Chrome on MacOS.
https://crbug.com/1348017 Compiling GLSL is very slow with struct arrays
Duplicate of #6615
