### ISSUE TITLE
filament webgl build broken?

### ISSUE THREAD

**Issue by unicomp21** [google/filament#6895]
https://gist.github.com/unicomp21/d3e81d0a612dfd124b183bab6d8cf7b8

**Comment by unicomp21** [comment]
This seems to keep happening?  Should we get a vm image or dockerfile going as part of cicd?

**Comment by romainguy** [comment]
We already build webgl both as a pre and post submit step.

**Comment by unicomp21** [comment]
how are the images generated for the vm's being used?  are there packer, docker, or ansible files i can look at?

**Comment by romainguy** [comment]
We use GitHub's standard macos image: https://github.com/google/filament/blob/main/.github/workflows/web-continuous.yml

**Comment by unicomp21** [comment]
what about those of us using linux?

**Comment by romainguy** [comment]
We only build webgl using a macos image. The number of targets and ABIs we support already make pre and post submits quite long.

@pixelflinger could it be your recent changes to make we a separate platform that causes this issue btw?

**Comment by pixelflinger** [comment]
@romainguy no because It's not been submitted.

**Comment by unicomp21** [comment]
@pixelflinger with respect to dev laptops, I would agree, macos is pretty popular.  But for project level build systems, are we going to try and make the macos argument?  How many project level builds at google are based on macos?

Either way, can we agree it would be ideal for the webgl build to run on both linux and mac?

**Comment by poweifeng** [comment]
Build still works for linux.  I think you're missing a dep [here]. I added `libglu1-mesa-dev` and tested ok. Maybe works with just `libgl-dev`.

[here]: https://gist.github.com/unicomp21/d3e81d0a612dfd124b183bab6d8cf7b8#file-dockerfile-L8

**Comment by unicomp21** [comment]
Many thanks @poweifeng !

I put an updated emscripten build for filament, via dockerfile, here for posterity.

https://gist.github.com/unicomp21/e8aba59e1b75a769c3d705b2ca7bb514
