### ISSUE TITLE
mavenCentral version outdated?

### ISSUE THREAD

**Issue by chakflying** [google/filament#6908]
**Describe the bug**
Looks like mavenCentral is still stuck at `1.36` when the latest release is `1.38`.

**To Reproduce**
1. [maven.org](https://search.maven.org/artifact/com.google.android.filament/filament-android/) shows there is no newer version than `1.36`
2. Changing gradle script to `1.38` will fail to sync

**Expected behavior**
Release on maven should correspond to releases here.

**Screenshots**

**Logs**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 13

**Additional context**

**Comment by bejado** [comment]
Yes, there's been a delay in Maven releases. This will hopefully be up-to-date this week.

**Comment by bejado** [comment]
The latest Filament build on Maven is now 1.38.0.
