### ISSUE TITLE
Android do NOT support multiple(>=2) custom light

### ISSUE THREAD

**Issue by luoqii** [google/filament#6920]
**Describe the bug**
I want to add 5 lights to scene, but just one light make sense. 
if I add any one of these 5 lights , it's ok. 
if I add all, or 2, it does NOT work.

do this lib support multipple light in andorid (java)?

**Smartphone (please complete the following information):**
 - Device: vivo x90
 - OS: Android 13

**Comment by Qheb** [comment]
What kind (`Type`) of light are you using ?

According to the [LightManager](https://github.com/google/filament/blob/main/android/filament-android/src/main/java/com/google/android/filament/LightManager.java) doc:

> warning: Currently, only a single directional light is supported. If several directional lights are added to the scene, the dominant one will be used.

(Directional meaning `Type.DIRECTIONAL` or `Type.SUN`)

**Comment by luoqii** [comment]
Yes  I use this type: LightManager.Type.DIRECTIONAL .
thanks for you reply !

is there a plan to suport multipy directional lights in the future?
