### ISSUE TITLE
native memory leak cause by invoke `TextureHelper.setBitmap`

### ISSUE THREAD

**Issue by draty01** [google/filament#6936]
**Describe the bug**
native memory leak cause by invoke `TextureHelper.setBitmap` for when create texture  

**To Reproduce**
1. try to create texture object ,use code below：

```
fun loadTexture(
            engine: Engine,
            data: ByteBuffer,
            type: TextureType = TextureType.COLOR
        ): Texture? {
            val options = BitmapFactory.Options()
            // Color is the only type of texture we want to pre-multiply with the alpha channel
            // Pre-multiplication is the default behavior, so we need to turn it off here
            options.inPremultiplied = type == TextureType.COLOR
            val bitmap = BitmapFactory.decodeByteArray(data.array(), 0, data.array().size, options)
                ?: return null
            val texture = Texture.Builder()
                .width(bitmap.width)
                .height(bitmap.height)
                .sampler(Texture.Sampler.SAMPLER_2D)
                .format(internalFormat(type))
                // This tells Filament to figure out the number of mip levels
                .levels(0xff)
                .build(engine)

            // TextureHelper offers a method that skips the copy of the bitmap into a ByteBuffer
             TextureHelper.setBitmap(engine, texture, 0, bitmap, Handler(Looper.getMainLooper())) {
                 android.util.Log.i(TAG, "loadTexture Bitmap is released.")
             }
            texture.generateMipmaps(engine)
            return texture
        }
```

when use the code below ,native memory is low 

```
fun loadTexture(
            engine: Engine,
            data: ByteBuffer,
            type: TextureType = TextureType.COLOR
        ): Texture? {
           // some same code like above ...
             val buffer = ByteBuffer.allocateDirect(bitmap.byteCount)
             bitmap.copyPixelsToBuffer(buffer)
             // Do not forget to rewind the buffer!
             buffer.flip()

             val descriptor = Texture.PixelBufferDescriptor(
                 buffer,
                 format(bitmap),
                 type(bitmap),
             )
           
             texture.setImage(engine, 0, descriptor)
            texture.generateMipmaps(engine)
            return texture
        }
```
**Expected behavior**
native memory is low

**Screenshots**
**use TextureHelper.setBitmap**
![image](https://github.com/google/filament/assets/16647495/a01fef73-4799-46b4-a0c6-9ce8228c8488)

**NOT use  TextureHelper.setBitmap**
![image](https://github.com/google/filament/assets/16647495/378ad0de-9609-4402-806b-e696970fbd06)

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
- Device: [ xiaomi 10 ]
- OS: 【 Android 13】【 miui14】

**Additional context**

**Comment by romainguy** [comment]
If your bitmap is already inside a `ByteBuffer`, you shouldn't use `TextureBitmap`.

**Comment by romainguy** [comment]
Looking at the code involved in `TextureHelper` I don't see anything obvious. Worse, the code basically doesn't allocate. We keep a global ref to the source bitmap but that gets released. Maybe the ref isn't properly released?

**Comment by romainguy** [comment]
If I modify our sample-textured-object sample to add a button to load a texture every time I click it, native memory rises temporarily (as expected from loading a bitmap) but goes back down again after a (forced) GC:

<img width="437" alt="Screenshot 2023-07-06 at 2 47 11 PM" src="https://github.com/google/filament/assets/869684/6a0d5c3b-3ab2-46aa-a0be-95ce87b921df">

The bug doesn't reproduce on recent versions of Filament. However, I found another bug in the process causing the upload callback to not be invoked because of name shadowing. I'm uploading a fix.

**Comment by draty01** [comment]
I updated the filament version to 1.40.0 and loaded the texture with `TextureHelper.setBitmap` way, but I still have the same problem

Worse, when I load the texture that not use  `TextureHelper.setBitmap` way, I found that version 1.40.0 alloc more Natvie memory than version 1.38.0
version 1.40.0 :
![image](https://github.com/google/filament/assets/16647495/f2fac89c-c40c-4746-9e75-05c8af516750)

version 1.38.0 
![image](https://github.com/google/filament/assets/16647495/4619eb7b-4f85-42ba-8094-feb207f7f741)

**Comment by romainguy** [comment]
Can you share your project or APK? I can't reproduce the problem on our end.

**Comment by draty01** [comment]
here is my apk.
[Debug_filament.zip](https://github.com/google/filament/files/11999514/Debug_filament.zip)

1. launch app to render the model
2. modify the property  `ModelUtils#SKIP_BITMAP_COPY` in the file `app\src\main\java\com\example\debug_filament\utils\ModelUtils.kt` to switch use or not use TextureHelper.setBitmap 

you will find high native memory load when SKIP_BITMAP_COPY=true
and low  native memory load when SKIP_BITMAP_COPY=false

**Comment by draty01** [comment]
> Can you share your project or APK? I can't reproduce the problem on our end.

here is my apk.
[Debug_filament.zip](https://github.com/google/filament/files/11999514/Debug_filament.zip)

modify the property ModelUtils#SKIP_BITMAP_COPY in the file app\src\main\java\com\example\debug_filament\utils\ModelUtils.kt to switch use or not use TextureHelper.setBitmap
launch app to render the model
you will find high native memory load when SKIP_BITMAP_COPY=true
and low native memory load when SKIP_BITMAP_COPY=false
