### ISSUE TITLE
Add support for unpacked TBN

### ISSUE THREAD

**Issue by romainguy** [google/filament#695]
Normals, tangents and bitangents need to be supplied as an orientation (quaternion) to renderables. @tpsiaki has requested the ability to pass them unpacked. We need to figure out:
- Should it be a single attribute (2 vec4)?
- Should it be 2 attributes?
- Should we just do the conversion in Filament and keep the orientations in the shaders?

**Comment by Raki** [comment]
Hi @romainguy ,I was able to load custom .obj by compiling to .filamesh. I'm trying to load a procedurally  generated mesh into [https://github.com/google/filament/tree/master/android/samples/textured-object](url) sample .



I was able to build interleaved buffer with pos(3comp),norm(3comp),uv(2comp) order. 

`//vertexbuffer for dynamic mesh (right side output)`

`val vertexBufferBuilder = VertexBuffer.Builder()`
        `.bufferCount(1)`
       ` .vertexCount(vertexCount)`
        `.attribute(POSITION, 0, FLOAT3, 0, stride)`
        `.attribute(TANGENTS, 0, FLOAT3, 3*4, stride)`
        `.attribute(UV0, 0, FLOAT2, 6*4, stride)`

`vertexBufferBuilder.build(engine).apply { setBufferAt(engine, 0, data)  // data has interleaved vertex info `

But it is giving me improper output.
![filament d mesh](https://user-images.githubusercontent.com/824691/51472711-46203700-1da0-11e9-97ca-c33f80b934cc.png)

Im using the same textures and compiled material provided in the example to create above output.

From the above comments I understood that my tangents are not proper (not 4 comp or quaternion). How to prepare proper interleaved buffers ? I got struck for last 8 days, please throw some light...

**Comment by kpeeters** [comment]
There is a convenience function to turn normals into quaternions; do something like

        std::vector<math::short4> tangents;
        tangents.resize(normals.size());
        filament::VertexBuffer::populateTangentQuaternions(filament::VertexBuffer::QuatTangentContext {
			.quatType = filament::VertexBuffer::SHORT4,
			.quatCount = normals.size(),
			.outBuffer = tangents.data(),
			.outStride = sizeof(math::short4),
			.normals = normals.data()
			});

and then feed the `tangents.data()` to the vertex buffer.

**Comment by Raki** [comment]
Hey @kpeeters , my issue was solved with your input. Thank you again for the help :-) 👍

**Comment by rawnsley** [comment]
@kpeeters Is _populateTangentQuaternions_ available through the Java/Kotlin interface?

**Comment by prideout** [comment]
It is not yet exposed, should be easy to do though.  I'll look into it.
