### ISSUE TITLE
Question with ModelViewer.loadModelGltf when load gltf-embeded file on Android

### ISSUE THREAD

**Issue by luoqii** [google/filament#6975]
**Describe the bug**
when load gltf-embeded(such as https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/2CylinderEngine/glTF-Embedded/2CylinderEngine.gltf) file on Android, I write like this

```
        modelViewer.loadModelGltfAsync(buffer) { uri ->
                var bBuffer = ByteBuffer.allocate(0)
                bBuffer
        }
```
we expect than the model will NOT correctly loaded,
BUT to my surprise, the model is loaded successfully

I want to know the reason.

**Comment by romainguy** [comment]
Why wouldn't it load successfully? The lambda is used to load any URIs used inside the glTF, but that glTF has none. The mesh data is inside the glTF file (hence "embedded") and this model doesn't use any textures.

**Comment by luoqii** [comment]
@romainguy sorry the gltf file i used is this one https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/CesiumMan/glTF-Embedded/CesiumMan.gltf, I'm surce it contain a url-data data:image/jpeg;base64,.....
