### ISSUE TITLE
 fatal  error C1083 “bluevk/BlueVK.h”: No such file or directory

### ISSUE THREAD

**Issue by idclosed** [google/filament#6983]
The cmake file of filamentapp needs to include the bluevk Header file directory.

**Comment by romainguy** [comment]
What's the exact error? This library shouldn't include bluevk.

**Comment by romainguy** [comment]
It includes a file from libbackend though, that's probably the missing dependency.

**Comment by lconn-dev** [comment]
I actually just ran into the same issue when attempting to include "backend/platforms/VulkanPlatform.h" with the v1.40.2-windows build. I haven't made any progress trying to track down the cause yet though.

**Comment by romainguy** [comment]
Make sure you link against bluevk.

**Comment by idclosed** [comment]
After the git clone.. In the Windows environment, editing filamentapp with cmake will result in errors. There are two problems. One is that the backend Header file contains, and the other is that the bluevk Header file contains. VulkanPlatform. h is referenced in filamentapp. This file contains # include<bluevk/BlueVK. h>. Another issue is that when compiling gltfviewer.exe, an error will be reported as a link error in filamentapp, which should be an issue with the public link between filamentapp and backend.

**Comment by poweifeng** [comment]
I can take a look at this since I introduced the bluevk dependency. 

@idclosed , do you have any specific repro steps?  Just try compiling the filamentapp lib?

**Comment by idclosed** [comment]
git clone git@github.com:google/filament.git
mkdir out
cd out
cmake..

Then open TNT.sln, and the compiler will discover the compilation issue with filamentapp. lib. Alternatively, you can directly open cmakelists.txt in the root directory using vs2022, open the cmake project view, and compile directly to discover the problem. The compilation issue can be resolved by adding an include to bulevk in cmakelists.txt under filamentapp.

**Comment by lconn-dev** [comment]
With my setup I'm not using filamentapp. Here's the relevant lines from my CMakeLists

> target_include_directories(DLE PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/filament-v1.40.2-windows/include/)
> target_include_directories(DLE PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/filament-v1.40.2-windows/libs/)
> set(fiLibs backend bluegl bluevk vkshaders filabridge filaflat filament ibl utils geometry camutils smol-v)
> foreach(X IN LISTS fiLibs)
>     target_link_libraries(DLE PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/filament-v1.40.2-windows/lib/x86_64/mdd/${X}.lib)
> endforeach()

And the section of the header file I'm using: 

> #include <filament/Engine.h>
> #include <filament/Camera.h>
> #include <filament/ColorGrading.h>
> #include <filament/IndexBuffer.h>
> #include <filament/RenderableManager.h>
> #include <filament/Renderer.h>
> #include <filament/Scene.h>
> #include <filament/Skybox.h>
> #include <filament/TransformManager.h>
> #include <filament/VertexBuffer.h>
> #include <filament/View.h>
> #include <filament/RenderableManager.h>
> #include <filament/Material.h>
> #include <filament/IndexBuffer.h>
> #include <filament/Viewport.h>
> #include <filament/SwapChain.h>
> 
> //#include <backend/platforms/VulkanPlatform.h>

**Comment by poweifeng** [comment]
@lconn-dev , your issue might be different.  Since you're using your own `CMakeLists.txt`, please make sure that you're doing all the things guarded by `FILAMENT_SUPPORTS_VULKAN` in our root [`CMakeLists.txt`]

[`CMakeLists.txt`]: https://github.com/google/filament/blob/main/CMakeLists.txt

**Comment by idclosed** [comment]
Well done, Quickly fixed, this issue is already resolved.
