### ISSUE TITLE
SIGABRT being caused when disposing resources?

### ISSUE THREAD

**Issue by victorbrndls** [google/filament#6989]
**Describe the bug**
I'm getting `SIGABRT` crashes when Filament resources are being disposed.

On my home screen, I'm using `ModelViewer` to display a model I created in Blender. It's just a simple cube that has one of the sides painted blue.

![image](https://github.com/google/filament/assets/11446530/4a98be39-ec6a-4b21-b185-a8994b3d576e)

When I tap the cube icon on the bottom left corner of the screen, we show another screen that is using another `ModelViewer` to display a more complex cube.

![image](https://github.com/google/filament/assets/11446530/4f2e7603-a01c-46d3-9517-e1b7e0c872f0)

When I navigate to the 2nd screen from the 1st one, I usually get `SIGABRT` crashes (attached below) and I can't figure out how to fix it.

Here's how I'm creating the models
```
val buffer = assets.open("models/cube1x1_1.glb").use { input ->
	val bytes = ByteArray(input.available())
	input.read(bytes)
	ByteBuffer.wrap(bytes)
}

modelViewer.loadModelGlb(buffer)
modelViewer.transformToUnitCube()
```

I'm not disposing anything manually, I'm leaving it all for `ModelViewer` to dispose

**Logs**
Crash from Crashlytics: https://gist.github.com/victorbrndls/cd93f8ec4a2679956c64e32bfd719446
Crash from Logcat: https://gist.github.com/victorbrndls/82fe62f846a7c70fff876fe7b6129e87

I also noticed that most crashes show that the user had little RAM free. It usually ranges from 30mb to 130mb on Crashlytics.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7
 - OS: Android 10

**Comment by poweifeng** [comment]
Do you have the lines right before https://gist.github.com/victorbrndls/82fe62f846a7c70fff876fe7b6129e87 ?

**Comment by victorbrndls** [comment]
https://gist.github.com/victorbrndls/9e7c3acd6e09465d1fd7878be3379352

**Comment by victorbrndls** [comment]
This is the memory usage if I open the 2nd screen right after the 1st one is created. It crashes
![image](https://github.com/google/filament/assets/11446530/b3e683be-64df-4ab9-93d4-1cdd7b886b44)

This is the memory usage if I open the 2nd screen a few seconds after the 1st one is created. It doesn't crash
![image](https://github.com/google/filament/assets/11446530/6f0aca51-9ffc-4d2c-be44-a06113aaf764)

**Comment by pixelflinger** [comment]
We really don't have enough to go on here. This seems like a problem specific to this application or devices. Something is calling `abort()` it might be the runtime because its running out of heap space, or something else.

I think this is more appropriate for discussions than issues. You could try to attach a debugger and see what happens, you could also use a debug version of filament.
