### ISSUE TITLE
Rendering in different thread than the setup ?

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#699]

**Comment by romainguy** [comment]
All Filament apis must be called from the same thread. Why would you have to create/render/destroy every time After Effects calls render? You could just remember that global setup was called and create the Filament engine in the render callback when needed. A better solution would be to create your own thread and post messages to it from the various AE callbacks.

**Comment by thirdmenson** [comment]
Thanks for the suggestion. I'll give it a try.

**Comment by thirdmenson** [comment]
Is there a way to hide just ibl background with ibl effect still enabled?

**Comment by romainguy** [comment]
All you have to do is not add a Skybox to the scene (but keep the IndirectLight).

**Comment by thirdmenson** [comment]
Thanks !

**Comment by thirdmenson** [comment]
So like I said earlier I was able to read pixels from the filament renderer to the after effects output buffer, but there seems to be some noise at the bottom of the image.  To the right of the image is the after effects ouput which has noise at the bottom area and to the right is the filament window where there is no noise. Both of these window are 1024x640 px in size. Here is how I am reading the filament render:

```
int const winwidth = 1024;
int const winheight = 640;
int const area = winwidth * winheight;
std::array<PF_PixelRGBA, area> colorData;

Texture::PixelBufferDescriptor pb(colorData.data(), area * 4, Texture::Format::RGBA, Texture::Type::UBYTE);
renderer->readPixels(0, 0, winwidth, winheight, std::move(pb));
```

![image](https://user-images.githubusercontent.com/36080456/51094058-861b6480-1777-11e9-88ab-0b4957c2def3.png)


Just trying to make sure if there isn't a bug in readpixel or maybe I am reading it wrong.

**Comment by thirdmenson** [comment]
I did not, so I might be writing to ae buffer without readpixel is done reading? Is there example usage code for that callback?

**Comment by thirdmenson** [comment]
This is probably not the case, if the readpixel is asynchronous then I added a 3 sec delay after the readpixels  which would give is sufficient time to finish reading before I read it to ae buffer but I still get the artifacts. One way to go around this issue might be to create a window that is 5px or so bigger than ae layer but  I would rather work with same dimensions.

**Comment by romainguy** [comment]
Check how you create the window. I don't know if giving it a size takes decorations into account for instance.

**Comment by thirdmenson** [comment]
I actually measured measured the sdl window dimensions and it doesn't take decorations/ titlebar into account. If I set height = 640 px then just the rendered portion is 640px

**Comment by romainguy** [comment]
@pixelflinger Mathias, any idea why the `readPixels()` call would contain invalid data like this?

BTW do you have to use `readPixels()`, could you render directly in After Effect's window?

**Comment by thirdmenson** [comment]
I mean all we get is a pointer to buffer in ae where we have to copy our image data. So it's not a window per say.  That buffer pointer also seems to change per any parameter change or change in time line. So not sure rendering filament directly there is a good idea. Also the filament output is in rgba, and ae expects in argb so I have been converting pixel type while copying.

**Comment by romainguy** [comment]
This example here doesn’t seem to convert from rgba to argb: 
https://github.com/baku89/glslCanvas4AE/blob/master/GLSLCanvas.cpp

**Comment by thirdmenson** [comment]
I actually just tried that using memcpy to copy the entire row of image at once, it's the same example code in Glator.cpp that comes in AE sdk and yes that examples doesn't seem to convert it which puzzles me but in my case I get a black image.

 If you look at that example it does copy twice, once to the bufferP using glreadpixel and then again to ae buffer where it uses memcpy to copy entire row.

**Comment by romainguy** [comment]
Nevermind that example does swizzle to argb but it does it in the shader.

**Comment by bejado** [comment]
I don't see anything obviously wrong with the `readPixels` call. If you replace the call to `readPixels` with a loop that sets the pixel data to a debug color, say red, does it work correctly? My guess is you have AE-specific memory issues. Once you get that working, add the `readPixels` call below the debug color loop and see if's actually overriding the red pixels with black ones.

I'm not too familiar with AE's API but I think you might need a call to `AEGP_UnlockMemHandle` after you've finished with the memory.

**Comment by thirdmenson** [comment]
So I tried to set the image_data to red color in a loop and it indeed gets written correctly and shows up red in the AE window. However, if I add the read pixels call after the red color loop then the color remains red, so the readpixels doesn't write anything if I use AE allocated memory. I also tried the unlock mem handle and it doesn't change anything.

**Comment by bejado** [comment]
But the `readPixels` call works correctly if you allocate the memory without using AE's methods? Maybe you can step through `readPixels` and see if anything looks wrong.
