### ISSUE TITLE
Crashes on Adreno 30x

### ISSUE THREAD

**Issue by victorbrndls** [google/filament#6995]
**Describe the bug**
I'm getting many reports on Crashlytics from `filament::backend::Platform::pumpEvents()` crashes. This has been happening since we launched the app and it's affecting a considerable portion of our users.

We noticed that many people who were getting this crash also had PowerVR GPUs and we also read here that those GPUs are known for causing problem so we excluded them in Play Console.

![image](https://github.com/google/filament/assets/11446530/56a4b004-383e-41ad-bdc4-db38b0955f91)

Nonetheless, that's 4k devices that can't user the app, meaning we lost ~30% of our users because of this change. On the bright side it reduced `Platform::pumpEvents` a lot.

That happened a few days ago, now we're starting to get `Platform::pumpEvents` again but devices that don't have PowerVR GPUs.

We noticed that most of these devices are running Android 7 with OpenGL 3.0. It also appears that most of them have the Adreno 308 GPU.

Is there's a way for us to add those PowerVR GPU devices back? How can we fix it for the other devices?

**To Reproduce**
I don't know how to reproduce it.

**Screenshots**
![image](https://github.com/google/filament/assets/11446530/bd323975-f328-45c2-921e-d1ecedf01f9b)
![image](https://github.com/google/filament/assets/11446530/9c966812-b9ec-4db0-b735-9b9671bf97de)
![image](https://github.com/google/filament/assets/11446530/c7692efc-5b1f-4379-909a-bba1e22c0afb)

**Logs**
I'll paste what I have in Crashlytics
Huawei MediaPad T3 10, Android 7, OpenGL 3
https://gist.github.com/victorbrndls/090d9d1169a04408a60a256c8111b695

Redmi 5A, Android 7.1.2, OpenGL 3
https://gist.github.com/victorbrndls/c69d0e7f5482e36ab37f4557b1cc8c47

**Comment by romainguy** [comment]
That's a surprising crash since, as far as I can remember, `pumpEvents` is only implement for macOS and is a no-op everywhere else:

```
bool Platform::pumpEvents() noexcept {
    return false;
}
```

The actual crash must be somewhere else.

**Comment by pixelflinger** [comment]
@victorbrndls can you give us the actual stack trace as it appears in logcat? We can't symbolize these crashlytics logs.

**Comment by pixelflinger** [comment]
`pumpEvents` is definitely a red herring. The stack symbolization is just wrong.

The PowerVR drivers are a known issue for which we don't have a workaround, see (https://github.com/google/filament/issues/5118).

We have seen compiler drivers issues with some older Adreno as well. Me might have a workaround for that.

**Comment by victorbrndls** [comment]
@pixelflinger Unfortunately I don't have any Adreno device, I'm just getting these crashes from Crashlytics so I know something is not working but that's all I have.

**Comment by ngeeraldo** [comment]
> @victorbrndls can you give us the actual stack trace as it appears in logcat? We can't symbolize these crashlytics logs.

Is there a way to get stack traces from remote crashes? I do not own an Adreno device but have the same issues

**Comment by pixelflinger** [comment]
I think this is outdated at this point.
