### ISSUE TITLE
ModelViewer.pick stops working after 4x

### ISSUE THREAD

**Issue by victorbrndls** [google/filament#6997]
**Describe the bug**
I'm using `ModelViewer.pick` to know which node the user tapped, however if the `ModelViewer` is created 4x, it stops working on the 5th time.

**To Reproduce**
You can use a RecyclerView or multiple screens, it doesn't matter.

Just find a way for the same `ModelViewer` class to get instantiated 5x, it'll stop working on the 5th time.

Here's my picker code:
```
private val queryResult = OnPickCallback {
    Log.i("Picked ${it.renderable}")
    val name = modelViewer.asset!!.getName(it.renderable)
    if (name == null || name.startsWith("Cube")) return@OnPickCallback
    painter.onEntity(it.renderable)
}

private val tapGestureDetector by lazy {
    val listener = object : GestureDetector.SimpleOnGestureListener() {
	    override fun onSingleTapUp(event: MotionEvent): Boolean {
		    modelViewer.view.pick(
			    event.x.toInt(),
			    textureView.height - event.y.toInt(),
			    textureView.handler,
			    queryResult,
		    )
		    return true
	    }
    }
    GestureDetectorCompat(textureView.context, listener)
}
```

I'm using the same `Engine` for all `ModelViewers` but changing the code so it uses a new `Engine` doesn't fix the problem.

**Logs**
I'm using the following code to print which entities were created
```
modelViewer.loadModelGlb(buffer)
modelViewer.transformToUnitCube()

modelViewer.asset!!.entities.let { Log.d("entities: ${it.toList()}") }
```

and this one to know which node was picked
```
private val queryResult = OnPickCallback {
    Log.i("Picked ${it.renderable}")
}
```

1st time
entities: [276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356]
Picked 316

2nd time
entities: [632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712]
Picked 665

3rd time
entities: [988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068]
Picked 1033

4th time
entities: [1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379]
Picked 1337

5th time
entities: [131312, 131313, 131314, 131315, 131316, 131317, 131318, 131319, 131320, 131321, 131322, 131323, 131324, 131325, 131326, 131327, 131328, 131329, 131330, 131331, 131332, 131333, 131334, 131335, 131336, 131337, 131338, 131339, 131340, 131341, 131342, 131343, 131344, 131216, 131215, 131345, 131561, 131560, 131570, 131565, 131564, 131563, 131566, 131567, 131568, 131569, 131562, 131431, 131432, 131433, 131434, 131435, 131436, 131437, 131438, 131439, 131440, 131441, 131442, 131443, 131444, 131445, 131446, 131447, 131448, 131449, 131450, 131451, 131452, 131453, 131454, 131455, 131456, 131457, 131458, 131459, 131460, 131461, 131462, 131463, 131464]
Picked 381

You can see that on the 5th time, the ids for the entities are very different from the other times. The picked id also doesn't exist, that's why this is not working for me.

**Smartphone:**
 - Device: Redmi Note 7
 - OS: Android 10

**Additional context**
Filament 1.40.0

**Comment by victorbrndls** [comment]
Here's my custom ModelViewer https://gist.github.com/victorbrndls/420d2c73cfff992999ab83dfdf8b962d

**Comment by victorbrndls** [comment]
Here's a [video](https://drive.google.com/file/d/10NWHYiTaFkA4dDPu3Liiz_hv-rEnbf23/view?usp=sharing) of the bug. You can see that I open the cube 5x and paint it, The last time I try to paint it using orange, nothing happens because `modelViewer.pick` is returning an entity id that is not being rendered. Nonetheless the cube still renders correctly

**Comment by pixelflinger** [comment]
@victorbrndls what do you means by "it doesn't work"?  Is it just picking that doesn't work? does picking return something but it's not the right id?

**Comment by pixelflinger** [comment]
@victorbrndls Which device was this observed on?

**Comment by pixelflinger** [comment]
@victorbrndls could you try again with the latest filament? I have trying these repro steps and got the EntityManager to return entities in the 131000+ range, and picking is working fine. 
Can you reproduce this on the emulator? or on other devices?

**Comment by victorbrndls** [comment]
I'm using Filament 1.40.3 and it still didn't work. Here's the logs:

Entities: [276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356]
Picked entity: 279

Entities: [632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712]
Picked entity: 689

Entities: [988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068]
Picked entity: 1051

Entities: [1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379]
Picked entity: 1307

Entities: [131312, 131313, 131314, 131315, 131316, 131317, 131318, 131319, 131320, 131321, 131322, 131323, 131324, 131325, 131326, 131327, 131328, 131329, 131330, 131331, 131332, 131333, 131334, 131335, 131336, 131337, 131338, 131339, 131340, 131341, 131342, 131343, 131344, 131216, 131215, 131345, 131561, 131560, 131568, 131563, 131564, 131565, 131566, 131567, 131562, 131569, 131570, 131431, 131432, 131433, 131434, 131435, 131436, 131437, 131438, 131439, 131440, 131441, 131442, 131443, 131444, 131445, 131446, 131447, 131448, 131449, 131450, 131451, 131452, 131453, 131454, 131455, 131456, 131457, 131458, 131459, 131460, 131461, 131462, 131463, 131464]
Picked entity: 259

**Comment by victorbrndls** [comment]
If you want I can create a repo where you can run the app to reproduce the problem

**Comment by victorbrndls** [comment]
I tested this on a Galaxy S22 Android 13 and it crashed instead.

```
Crashed: Thread: SIGABRT  0x0000000000000000
#00 pc 0x53794 libc.so (BuildId: e278775533ac9a2eaf2d2fbf893a855f)
#01 pc 0x53764 libc.so (BuildId: e278775533ac9a2eaf2d2fbf893a855f)
#02 pc 0x6d28bc libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#03 pc 0x16ea8 libbase.so (BuildId: b77c57f68a484ed93d5a7eda59d83bf9)
#04 pc 0x16450 libbase.so (BuildId: b77c57f68a484ed93d5a7eda59d83bf9)
#05 pc 0x384118 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#06 pc 0x533c44 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#07 pc 0x5330d8 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#08 pc 0x5df970 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#09 pc 0xd3a24 libfilament-jni.so (Java_com_google_android_filament_View_nPick) (BuildId: 5b3cb03609ecae0f2ead20fd6421ecf4300392ef)
#10 pc 0x705ecef3c4
#11 pc 0x705f0a70eb
#12 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#13 pc 0x20a20c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#14 pc 0x705ecef3c4
#15 pc 0x705fb8c216
#16 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#17 pc 0x20a254 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#18 pc 0x705fb8c216
#19 pc 0x700fb0 boot-framework.oat (BuildId: 52f1dc1429fd457522555f53c65cfc0e7cbfad2c)
#20 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#21 pc 0x705edfea3c
#22 pc 0x705edfea3c
#23 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#24 pc 0x20a2b0 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#25 pc 0x705edfea3c
#26 pc 0x705edfeadc
#27 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#28 pc 0x20b074 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#29 pc 0x705edfeadc
#30 pc 0x705fb8c41e
#31 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#32 pc 0x20a254 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#33 pc 0x705fb8c41e
#34 pc 0x705fb8c3f0
#35 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#36 pc 0x209334 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#37 pc 0x705fb8c3f0
#38 pc 0x705fa9cc18
#39 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#40 pc 0x209334 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#41 pc 0x705e69268a
#42 pc 0x705fa9cc18
#43 pc 0x7b7b7c boot-framework.oat (BuildId: 52f1dc1429fd457522555f53c65cfc0e7cbfad2c)
#44 pc 0x85525c boot-framework.oat (BuildId: 52f1dc1429fd457522555f53c65cfc0e7cbfad2c)
#45 pc 0x85d0e8 boot-framework.oat (BuildId: 52f1dc1429fd457522555f53c65cfc0e7cbfad2c)
#46 pc 0x705e69268e
#47 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#48 pc 0x20a2b0 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#49 pc 0x705e69268e
#50 pc 0x705e6926d8
#51 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#52 pc 0x20a254 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#53 pc 0x705e6926d8
#54 pc 0x705e691f1c
#55 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#56 pc 0x20b074 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#57 pc 0x705e691f1c
#58 pc 0x705e691e80
#59 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#60 pc 0x20a254 libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
#61 pc 0x705e691e80
#62 pc 0x705e692a3a
#63 pc 0x20087c libart.so (BuildId: 97fdb979efb7d2b596fa4fceabaad95b)
```

**Comment by victorbrndls** [comment]
We tested this on a Galaxy S22 Android 13 and it worked fine so it appears that this is device/GPU related. I was able to reproduce this on A Redmi Note 7 using a Adreno 512 GPU

**Comment by pixelflinger** [comment]
The problem is due to a know bug in many Adreno drivers that ignore the precision qualifier in `struct`, unless they're used in a  UBO. That's such a PITA. I think we can workaround it.
