### ISSUE TITLE
【Android】rendering inconsistent when edit bone scale in different version

### ISSUE THREAD

**Issue by dandingol03** [google/filament#7002]
**Describe the bug**
The rendering effect are different between _1.12.5_ and _1.29.0_ when i edit the y component scale of cloth's shoulder bone. I list these rendering effect as below:

![image](https://github.com/google/filament/assets/13013579/d525c853-a04d-4a2b-a760-5013292acb33)
**The left one** is the rendered result of _1.12.5_ version `filament`, **the other one** is _1.29.0_. Please ignore the background and environment difference, let's focus on the length of cloth's sleeve. I edit the y component of scale to 1.4 on both different version engine and use the same boy model. However the older one behaves weried,  it seems that the engine of _1.12.5_ version just enlarge z component scale. But the engine of _1.29.0_ behaves right, it enlarge the length of sleeve correctly.

**To Reproduce**
1. download _1.12.5_ version of `filament`, compile and run gltf-viewer on mobile or pc
2. load this [cloth](https://drive.google.com/file/d/1rlZKX7TVnMp_FxRAHnR532PRi9EYbvvV/view?usp=sharing) glb model which has skeleton. 
3. edit the y component's scale value of shoulder bone

**Expected behavior**
enlarge or shorten cloth sleeve correctly

**Smartphone (please complete the following information):**
 - Device: [Samsung]
 - OS: [e.g. Android 11.0]

**Comment by pixelflinger** [comment]
I don't understand what the ask is. We fixed some problems and now it works well.

**Comment by dandingol03** [comment]
@pixelflinger the version of filament worked in our business is `1.12.5`, and there is some difficulties for us to upload `filament` to newest. if you have just know why `1.12.5` behaves so weried when i edit the y-component scale of the shoulder bone , can you tell me which commit fix this problem? i would like to pick the fixed commit instead of upgrading filament to newer version.

**Comment by dandingol03** [comment]
@prideout hi, can you give me some advice? This problem is relavant to bone's scale

**Comment by romainguy** [comment]
@dandingol03 Can't you upgrade to `1.29.0`? There are [1,385 commits](https://github.com/google/filament/compare/v1.12.5...v1.29.0) between `1.12.5` and `1.29.0` and it would be quite time consuming to go through them to figure out which ones fixes this particular issue (and that commit might not even be applicable directly to `1.12.5`).

**Comment by romainguy** [comment]
For instance one of the changes we made was [change how skinning data is stored](https://github.com/google/filament/commit/304ffe00491711b10f1e4d0773a7a29ef0302d06), so there's a cascading effect after this (you could try this commit btw as it's meant to fix things like skews, which is what you are introducing with a scale on a single axis).

**Comment by dandingol03** [comment]
> For instance one of the changes we made was [change how skinning data is stored](https://github.com/google/filament/commit/304ffe00491711b10f1e4d0773a7a29ef0302d06), so there's a cascading effect after this (you could try this commit btw as it's meant to fix things like skews, which is what you are introducing with a scale on a single axis).

Thanks for your replay and i agree with your opinion now. Upgrading filament is the best choice. There is some awkward job  we did when  we deploy `filament` to our business architecture, and i must admit these changes are seriously hindering the upgrade work now. I will take time fix that.
