### ISSUE TITLE
update indirectLight dynamically in android app

### ISSUE THREAD

**Issue by luoqii** [google/filament#7020]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
in my demo, i load indirectLight from ktx  file whick generated from cmgen util. it work perfectly.
but when i want change a different indirectLight at some later time, it do NOT work. 
by the way, i see a same solution in androd sample glft-viewer.  
this is my code:
```
    private fun loadIblKtx(buff: Buffer) {
        Log.d(TAG, "load ibl ktx")
        val engine = modelViewer.engine
        engine.destroyIndirectLight(modelViewer.scene.indirectLight!!)
        KTX1Loader.createIndirectLight(modelViewer.engine, buff)
            .apply {
                intensity = 100f
                modelViewer.scene.indirectLight = this
                viewerContent.indirectLight = this
            }
    }
```

**Smartphone (please complete the following information):**
 - Device: xiaomi red note
 - OS: android 11

**Comment by pixelflinger** [comment]
no repro steps
