### ISSUE TITLE
Describe how to enable logs in debug

### ISSUE THREAD

**Issue by victorbrndls** [google/filament#7021]
**Is your feature request related to a problem? Please describe.**
I built filament manually and I'm trying to enable logging/systraces so I can better understand what's going on however I can't find documentation describing how to do that.

**Describe the solution you'd like**
I think we should describe somewhere how to enable these things or to how debug filament.

Could you please also describe how to do that here?

I used
```
cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="..\android-debug\filament" -DCMAKE_TOOLCHAIN_FILE="..\..\build\toolchain-x86_64-linux-android.cmake" ..\..
```
and
```
gradlew -Pcom.google.android.filament.dist-dir=..\out\android-debug\filament -Pcom.google.android.filament.abis=x86_64 -Pcom.google.android.filament.skip-samples assembleDebug
```

**Comment by romainguy** [comment]
All you need to do is build a debug version of Filament with Cmake and make sure to point the Android build at it like you did. There's nothing else to do (note that Filament only logs on assertions, but it does generates systrace events).
