### ISSUE TITLE
When the backend is set to Vulkan, the cubes in the sample-multi-view example disappears.

### ISSUE THREAD

**Issue by zy4944796** [google/filament#7031]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
When the backend is set to Vulkan, the cubes in the sample-multi-view example disappears.

**To Reproduce**
1. Run the sample-multi-view demo in the pixcel4 phone:

![Screenshot from 2023-08-03 16-56-08](https://github.com/google/filament/assets/8578753/f6c2f6dd-b401-4b42-b4b0-e3a5f20167a9)

2,Set the engine backend to Vulkan:

![Screenshot from 2023-08-03 17-06-08](https://github.com/google/filament/assets/8578753/c4d496d6-9293-416c-8238-fcc6774a9ccf)
,then run it again:
![Screenshot from 2023-08-03 16-57-35](https://github.com/google/filament/assets/8578753/5f869f34-ca32-495d-86ad-bf0e58cfd4a9)

This issue also exists in the sample-lit-cube.

**Comment by poweifeng** [comment]
I'm unable to reproduce this on a Pixel4xl, which has the same GPU. 
Can you run `adb bugreport` after a run and attach it?  Thanks.

**Comment by zy4944796** [comment]
> I'm unable to reproduce this on a Pixel4xl, which has the same GPU. Can you run `adb bugreport` after a run and attach it? Thanks.

Thank you for your response. The issue has disappeared after I pulled the latest filament code and recompiled it. I will close this issue now.
