### ISSUE TITLE
create more camera crashed

### ISSUE THREAD

**Issue by lookangela** [google/filament#7043]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
crash at SingleInstanceComponentManager<Elements ...>::addComponent(Entity e)
...
 assert(ci != 0);
when crashed, i create the view index is 971 

**To Reproduce**
1. first create about 20  unit tests(google test), every tests has one  scene and one or more camera/view. 
2. then run tests repeat more  loops(about 69 loops) ,  every scene destroyed async delay new scene created,the camera/view also destoryed .

 

**Expected behavior**
I want it run always no crashed .

**Screenshots**
![AWLsnChm3T](https://github.com/google/filament/assets/5866830/4812aa76-ac59-4235-8f26-1f1438be15cb)
![c5BUtVZ9pt](https://github.com/google/filament/assets/5866830/410d1567-8bb4-4c8c-9ba9-1feda465048d)

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
utils/include/utils/SingleInstanceComponentManager.h:284: typename SingleInstanceComponentManager<Elements...>::Instance utils::SingleInstanceComponentManager<filament::FCamera *>::addComponent(utils::Entity) [Elements = <filament::FCamera *>]: Assertion `ci != 0' failed.

**Desktop (please complete the following information):**
 - OS:ubuntu20.4
 - GPU: rtx3060
 - Backend: OpenGL

**Comment by romainguy** [comment]
Please share your code as text. Don't share screenshots of the IDE.

**Comment by lookangela** [comment]
my   test code is based on  our company's  engine, not based on filament directly,  the engine is based on filament and not public.  also the test code is not used for you , the tests  create some camera ,view , light, material  , renderable entity, transform entity  and so on.   the issue is esay to see with with the screenshots ,the code on ShadowMap：
ShadowMap::ShadowMap(FEngine& engine) noexcept
        : mPerShadowMapUniforms(engine),
          mShadowType(ShadowType::DIRECTIONAL),
          mHasVisibleShadows(false),
          mFace(0) {
    Entity entities[2];
    engine.getEntityManager().create(2, entities);
    mCamera = engine.createCamera(entities[0]);
    mDebugCamera = engine.createCamera((entities[1]));
-----------------------------------------------------------------------------------------------------------------------
the code :
 engine.getEntityManager().create(2, entities);
The EntityManager create two entities, the first entities[0] create success,but the entities[1] failed.
 you can see the the entitys[0].mIdentity  is 131071 from the ide ,but the entities[1] .mIdentity is 0
This indicates that the EntityManager failed to create the 131072nd entity object. the entities[1]  is 0 cause the crash.
More importent, every time crashed , the entitys[0].mIdentity  is 131071,  the entities[1] .mIdentity is 0

**Comment by romainguy** [comment]
I understand but seeing your test would help understand why you are running out of entities.
