### ISSUE TITLE
filament::backend::Platform::retrieveBlob(void const*, unsigned long, void*, unsigned long)

### ISSUE THREAD

**Issue by victorbrndls** [google/filament#7046]
**Describe the bug**
I thought the `Platform::retrieveBlob` crash was solved in 1.40.4 by `opengl: fix b/290670707 : crash when using the blob cache
`, however there are still some users getting this crash.

I noticed that +95% of these crashes happen on Adreno 508 devices however I have no device with that GPU so I don't know exactly how to reproduce it.

**To Reproduce**
- Use `ModelViewer` to load a model
- It crashes a few seconds later

**Logs**
Logs from Crashlytics
```
null pointer dereference: SIGSEGV  0x0000000000000038
#00 pc 0x13cd14 libfilament-jni.so (filament::backend::Platform::retrieveBlob(void const*, unsigned long, void*, unsigned long)) (BuildId: 1d7a7caf26d6ef82dc8db9bfcd7c62c91779ceeb)
#01 pc 0x146cf4 libfilament-jni.so (filament::backend::Platform::retrieveBlob(void const*, unsigned long, void*, unsigned long)) (BuildId: 1d7a7caf26d6ef82dc8db9bfcd7c62c91779ceeb)
#02 pc 0x7a438 libc.so (BuildId: f24f65acf653c409ca4332aced817a71)
```
Logs from Play Console
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 20694 >>> io.opitas.moves <<<

backtrace:
  #00  pc 0x000000000013cd14  /data/app/~~KC7_Jxf66CbkI6fbz_mUEg==/io.opitas.moves-juHOP1o_DPVhVq4OPFJmUQ==/split_config.arm64_v8a.apk!libfilament-jni.so
```

**Additional context**
Filament 1.40.4

**Comment by pixelflinger** [comment]
we need full logs, as stated in the issue template.
