### ISSUE TITLE
Question:can i add customized material to a gltf model on Android plantform?

### ISSUE THREAD

**Issue by luoqii** [google/filament#7063]
**Describe the bug**
i have a demo to load & show gltf model like android sample gltf-viewer, meanwhile i see there is another demo-- hello-triangle, which load customized material from baked_colored.filamat which generated from baked_colored.mat. 
so my question is:
is there a way to add customized meatiral to my gltf model?

I have read all android sample apps, but have no idea.

THX

**Comment by romainguy** [comment]
Yes, the gltfio lets you specify your own MaterialProvider. You can also get the entities from your gltf to go change their materials directly.

**Comment by luoqii** [comment]
@romainguy 
THX for you reply, after 2 hours study, i found:
1, there is a MaterialProvider.java in the module gtftio-android  which used in ModelViewer.kt in module filament-utils-andrid, after adding log in UbershaderProvider.java (the only impl of MaterialProvider.java),  when i compile and run andrid demo glft-veiwer, there is no log output. so I think than when loading gltf file the MaterialProvider was NOT invoked, so there is on chance to provide a customized material. 
2,Yes, i can find the entity user for rendering, bug there is no interface to "get the entities from your gltf to go change their materials directly"

can U give me some clue or code-snippet to do? THX
