### ISSUE TITLE
Skybox in offscreen view

### ISSUE THREAD

**Issue by dcteris** [google/filament#7065]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
Skybox not rendered in offscreen views (rendertarget)

**To Reproduce**
In "rendertarget" sample,  I put a skybox in the offscreen view
in rendertarget.cpp

auto mIBL = FilamentApp::get().getIBL();
if (mIBL != nullptr) {
    mIBL->getSkybox()->setLayerMask(0x7, 0x4);
    app.offscreenScene->setSkybox(mIBL->getSkybox());
    app.offscreenScene->setIndirectLight(mIBL->getIndirectLight());
}

**Expected behavior**
the skybox should be rendered in both rendertarget and screen, but only screen skybox is rendered

**Screenshots**
![BXI7DZ6({8 DY0H88{3A_PD](https://github.com/google/filament/assets/8342122/7cbb6f3a-36ff-4bd2-9f49-730ecc034a4d)

**Logs**

**Desktop (please complete the following information):**
 - OS: win11
 - GPU: amd 6700xt
 - Backend: OpenGL

**Comment by romainguy** [comment]
You've set a layer mask on the skybox, does the offscreen view have a matching mask?
