### ISSUE TITLE
Probability of crash

### ISSUE THREAD

**Issue by draty01** [google/filament#7066]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
render the model , Probability of crash when invoke MaterialInstance#setParameter

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Logs**
18:40:30.009 23590-23654 libc                     A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x224 in tid 23654 (JNISurfaceTextu), pid 23590 (roidlibrarydemo)
18:40:30.957 23682-23682 DEBUG                    A  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
18:40:30.957 23682-23682 DEBUG                    A  Build fingerprint: 'Xiaomi/umi/umi:13/TKQ1.221114.001/V14.0.3.0.TJBCNXM:user/release-keys'
18:40:30.957 23682-23682 DEBUG                    A  Revision: '0'
18:40:30.957 23682-23682 DEBUG                    A  ABI: 'arm64'
18:40:30.957 23682-23682 DEBUG                    A  Timestamp: 2023-08-11 18:40:30.135774829+0800
18:40:30.957 23682-23682 DEBUG                    A  Process uptime: 14s
18:40:30.957 23682-23682 DEBUG                    A  ZygotePid: 444947730
18:40:30.957 23682-23682 DEBUG                    A  Cmdline: com.example.androidlibrarydemo
18:40:30.957 23682-23682 DEBUG                    A  pid: 23590, tid: 23654, name: JNISurfaceTextu  >>> com.example.androidlibrarydemo <<<
18:40:30.957 23682-23682 DEBUG                    A  uid: 10157
18:40:30.957 23682-23682 DEBUG                    A  signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000224
18:40:30.957 23682-23682 DEBUG                    A  Cause: null pointer dereference
18:40:30.957 23682-23682 DEBUG                    A      x0  b400006fc255c000  x1  0000006fba5fd6a0  x2  0000006fb51999e8  x3  0000000000000058
18:40:30.957 23682-23682 DEBUG                    A      x4  0000000000000002  x5  b400006fc2518280  x6  00000000000000c0  x7  0000000000000000
18:40:30.957 23682-23682 DEBUG                    A      x8  0000000000000224  x9  0000000000000008  x10 000000000000000c  x11 0000000000000000
18:40:30.957 23682-23682 DEBUG                    A      x12 0000000000000001  x13 0000000000000007  x14 0000000000000001  x15 00000000000000c3
18:40:30.957 23682-23682 DEBUG                    A      x16 00000000000000c3  x17 0000000000000000  x18 0000006fb4750000  x19 0000006fba5fd6a0
18:40:30.957 23682-23682 DEBUG                    A      x20 b400006fc255c000  x21 0000006fb5199a00  x22 0000000000000002  x23 b400007050cc9280
18:40:30.957 23682-23682 DEBUG                    A      x24 b400007050cc92a0  x25 0000006fb5199cb0  x26 0000006fb5199ff8  x27 00000000000fc000
18:40:30.957 23682-23682 DEBUG                    A      x28 00000000000fe000  x29 0000006fb5199c50
18:40:30.957 23682-23682 DEBUG                    A      lr  0000006fd4d606fc  sp  0000006fb51999e0  pc  0000000000000224  pst 0000000000001000
18:40:30.957 23682-23682 DEBUG                    A  backtrace:
18:40:30.957 23682-23682 DEBUG                    A        #00 pc 0000000000000224  <unknown>
18:40:30.957 23682-23682 DEBUG                    A        #01 pc 00000000001266f8  /data/app/~~n2afuc0yCq1amdWwQNvnEg==/com.example.androidlibrarydemo-Yk3lE1M-AHndABFWRLZzzA==/lib/arm64/libfilament-jni.so (BuildId: d655776db4ed37004fe00395861dd6561e64a62a)

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: xiaomi 10 pro
 - OS: android 13

**Additional context**

**Comment by romainguy** [comment]
You are most likely calling setParameter on an invalid instance/material
