### ISSUE TITLE
Reopened: Panic/crash in ShaderCompilerService.createProgram() on Windows OpenGL

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#7078]
Reopening #7071.  See that ticket for details.

That was found in version **1.40.5**.  We were asked to test again with **1.41.0**, which produces the same crash result.

**ALSO:** We tested using version 1.39.0, which had no problem.

**Comment by BStringhamVRSK** [comment]
@pixelflinger Just tried version **1.42.0** , and am getting the same crash in **runAtNextTick()** at the assert:
`assert_invariant(token->gl.program);`

**Comment by pixelflinger** [comment]
I wonder if it's that problem we've heard about before where shared contextes on windows have to be created on the same thread. If so, this could be an issue on all windows machines.
@bejado could you try a recent filament on windows? (e.g. just try gltf_viewer).

**Comment by bejado** [comment]
I will give it a try this week.

**Comment by bejado** [comment]
I'm unable to reproduce at the tip of main (https://github.com/google/filament/commit/3ab7780c381724ab1dfa8a2bc8d87bd0c39381a7), gltf_viewer runs fine for me on Windows.

OS: Windows 11 22621.2134
GPU: NVIDIA GeForce 3080
GPU Driver: NVIDIA Studio Driver 536.99

**Comment by MemomiAlexCherkashin** [comment]
Have same problem on my system.

OS: Windows 11 Enterprise 22H2 22621.2134
GPU: Intel(R) Iris(R) Xe Graphics
GPU Driver: 31.0.101.4146

**Comment by nmfisher** [comment]
Confirm the same problem exists on `5d30435620222a9ebfbc91cca47ddc919536fb5b` with Intel(R) HD Graphics 530.

**Comment by BStringhamVRSK** [comment]
@pixelflinger Is there any updates on this problem?  We are basically stuck at version 1.39.0 until this problem is fixed.

**Comment by pixelflinger** [comment]
No update on this, Windows support is not prioritized at the moment.  @MemomiAlexCherkashin workaround is fine in my opinion -- we can just turn this off for Windows for now.

**Comment by BStringhamVRSK** [comment]
> No update on this, Windows support is not prioritized at the moment. @MemomiAlexCherkashin workaround is fine in my opinion -- we can just turn this off for Windows for now.

Disabled for Windows would be fine.  We'll watch for that in a future update.  Thanks.

**Comment by nmfisher** [comment]
Any thoughts why this wasn't an issue on earlier versions of Filament?

**Comment by BStringhamVRSK** [comment]
> Any thoughts why this wasn't an issue on earlier versions of Filament?

As I understand it: Filament 1.40.0 introduced the ability to create multiple OpenGL contexts.  Many Windows drivers require that all contexts be created from a single thread.  Filament currently does not enforce that requirement, causing the problem.  I believe other Filament features (parallel shader compilation?) utilize multiple contexts and cause the problem to manifest, even if your app doesn't explicitly create multiple contexts.

**Comment by Alan-FGR** [comment]
This happens in all Windows multi-GPU laptops I've tried. As an alternative fix, hinting the OS/driver to use the "discrete" GPU worked for me. Just export these in your binary:
```
extern "C"
{
    __declspec(dllexport) uint32_t NvOptimusEnablement = UINT32_C(1);
    __declspec(dllexport) uint32_t AmdPowerXpressRequestHighPerformance = UINT32_C(1);
}
```

**Comment by Alan-FGR** [comment]
You're welcome! Just bear in mind that what that does is "hint" the OS/driver to use the non-integrated GPU (basically it forces that unless advanced system settings have been changed). While that's typically what you want, it's not 100% guaranteed to workaround this issue. I'm unsure about all the possible implications of just using that while leaving the `PlatformWGL::isExtraContextSupported` impl returning true. I think that might cause all kinds of other problems in hardware that's  less common, so for anything production I'd recommend returning false there and naturally exporting those symbols as well (unless for your use case you don't care about graphics performance, so using the integrated is better in terms of power (batt life), heat production, etc).
