### ISSUE TITLE
Applying a Geometry Shader on Existing Material in GLB Using Filament Android

### ISSUE THREAD

**Issue by testuser2112** [google/filament#7094]
I'm currently working on an Android project that involves rendering 3D models in GLB format using the Filament rendering engine. I have successfully managed to load and display models with their existing materials using Filament. However, I'm looking to take it a step further and apply a custom shader to an existing material to achieve specific visual effects, such as an airflow animation.

I understand that Filament offers a robust rendering framework, but I'm seeking guidance on the process to apply a custom shader to an already existing material. My goal is to modify various material properties, like base color, emissive factor, or normal mapping, to create dynamic effects that simulate airflow animation.

Could someone please provide guidance on the steps involved in achieving this? What are the key considerations and methods to create and apply a custom shader to an existing material within the Filament framework? If there are any illustrative examples or code snippets available, it would greatly help me understand the workflow better.

I'm open to insights and advice from fellow developers who have experience with Filament and have successfully integrated custom shaders onto existing materials. Your assistance would be highly appreciated.

**Comment by Qheb** [comment]
Hello,

You can take a look at the [Filament Materials Guide](https://google.github.io/filament/Materials.html), especially the sections about the [Vertex block](https://google.github.io/filament/Materials.html#materialdefinitions/vertexblock), [Fragment block](https://google.github.io/filament/Materials.html#materialdefinitions/fragmentblock) and the [Shader public APIs](https://google.github.io/filament/Materials.html#materialdefinitions/shaderpublicapis). This explains how to define materials with custom shaders in it.

As for examples, the [lit-cube](https://github.com/google/filament/blob/main/android/samples/sample-lit-cube) from the Android samples shows how to define a [basic material](https://github.com/google/filament/blob/main/android/samples/sample-lit-cube/src/main/materials/lit.mat) with 3 parameters, set them in the [Kotlin code](https://github.com/google/filament/blob/aa6e94a128035f3398102fad2bcda5354568a72f/android/samples/sample-lit-cube/src/main/java/com/google/android/filament/litcube/MainActivity.kt#L193) and use them in the `fragment` block.

**Comment by testuser2112** [comment]
Does it means filament Android doesn't support geometry shaders?

**Comment by romainguy** [comment]
We do not expose geometry shaders indeed and do not plan to do so. Vertex and fragment shaders are however available.

**Comment by romainguy** [comment]
A couple of notes:
- Metal doesn't support geometry shaders, which is one of the reasons we won't support them (they were added in OpenGL ES 3.2 btw, not 3.1)
- @testuser2112 based on the example you sent by email, it doesn't seem like you need geometry shaders, just vertex shaders?

**Comment by testuser2112** [comment]
Thank you for your response, can you please provide an example of it how can i achieve similar effect using a vertex shader?
