### ISSUE TITLE
not specifying maskThreshold doesn't give the same result as specifying the default value 0.5

### ISSUE THREAD

**Issue by teub** [google/filament#7099]
**Describe the bug**
Not specifying maskThreshold in my material doesn't get the same result as specifying 0.5.

**To Reproduce**
I guess the issue comes from other materials which specify other values and those values persist if not specified - but that's just a guess. Reproducing it would depend on the values set by other materials.
My other material params are : 

    shadingModel : lit,
    blending : masked,
    maskThreshold : 0.5, // if not specified,  gives another result
    transparentShadow : true,
    alphaToCoverage : false, 
    doubleSided : true,
    depthCulling: true,

**Expected behavior**
The doc says the default value should be 0.5

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Comment by bejado** [comment]
Our [materials doc](https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/blendingandtransparency:maskthreshold) has the default as 0.4. Where do you see 0.5?

**Comment by romainguy** [comment]
It should be 0.4 and the default value is indeed 0.4f in the code. Sounds like a docs issue potentially, the code does the right thing afaict.

**Comment by teub** [comment]
> Our [materials doc](https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/blendingandtransparency:maskthreshold) has the default as 0.4. Where do you see 0.5?

I totally misread. I read the usage sample as the default value :-) Time to buy new glasses I suppose, sorry for the false report !
