### ISSUE TITLE
Android sample gltf-viewer crashed when running in single thread mode

### ISSUE THREAD

**Issue by awkr** [google/filament#7113]
What I have changed is:
<img width="577" alt="image" src="https://github.com/google/filament/assets/1202134/1510f4de-6992-4fd5-8eb8-f460baa3b275">

and the crash log is:
<img width="1410" alt="image" src="https://github.com/google/filament/assets/1202134/947c122e-c92b-486c-bd59-b7e1b76e6540">

I've tried to fix this, but only got a black screen without crashing anymore. It seems Android gltf-viewer doesn't support single thread mode ...

**Comment by romainguy** [comment]
We only support this mode for we go.
