### ISSUE TITLE
https://google.github.io/filament/remote/ can NOT connect to sample/gltf-viewer app on Android

### ISSUE THREAD

**Issue by luoqii** [google/filament#7116]
**Describe the bug**
before 2023-08-28_15:00:00GMT+08:00 we can use  https://google.github.io/filament/remote/ connect to gltf-viewer app on Android phone,  but after this time, it stop working.
i see there is a [commit ](https://github.com/google/filament/commit/8d440cea17634506735d26cb8ec1fa523f2a2f44) to adjust some logit about web, but I have no idea what's the problem.

**To Reproduce**
1. open https://google.github.io/filament/remote/
2. adb forward tcp:8082 tcp:8082
3. change sth and view effect realtimely.

**Comment by romainguy** [comment]
I can reproduce the issue on tip of tree.

**Comment by poweifeng** [comment]
Suspect it is https://github.com/google/filament/commit/8d440cea17634506735d26cb8ec1fa523f2a2f44 due to the timing.
