### ISSUE TITLE
hard build at ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by louie-wh** [google/filament#7117]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

when I download the source , the project is error  ninja: error: '/home/huan.wang/AndroidStudioProjects/filament/out/android-release/filament/lib/arm64-v8a/libfilamat.a', needed by '../../../../build/intermediates/cxx/Debug/71h684d4/obj/arm64-v8a/libfilamat-jni.so', missing and no known rule to make it

so I build .a  by build.sh,  I update cmake version,  
still compile error, the error msg is huan.wang@U-PF3QQB9A:~/AndroidStudioProjects/filament$ ./build.sh -p android release
Building release in out/cmake-release...
ninja: error: loading 'build.ninja': No such file or directory

I still update clang version, but  I failed update clang version 10 to 14. 
AndroidStudio is good support Cmake,  Please  compile the .a directly at AS?

**Comment by pixelflinger** [comment]
not enough info. seems like user error.
