### ISSUE TITLE
ubuntu build for android 

### ISSUE THREAD

**Issue by louie-wh** [google/filament#7118]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I want to build project for android at ubuntu20.04. and refer to BUILDING.md 
first  install ubuntu dep
sudo apt-get install clang-14 libglu1-mesa-dev libc++-14-dev libc++abi-14-dev ninja-build libxi-dev libxcomposite-dev libxxf86vm-dev
then 

mkdir out/cmake-release
cd out/cmake-release
CC=/usr/bin/clang CXX=/usr/bin/clang++ CXXFLAGS=-stdlib=libc++     cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release/filament ../..
ninja

but some error happen:
the error message is 

FAILED: libs/utils/libbenchmark_utils_callee.so 
: && /usr/bin/clang++ -fPIC -stdlib=libc++ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -stdlib=libc++ -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -Wl,--gc-sections -Wl,-Bsymbolic-functions -shared -Wl,-soname,libbenchmark_utils_callee.so -o libs/utils/libbenchmark_utils_callee.so libs/utils/CMakeFiles/benchmark_utils_callee.dir/benchmark/benchmark_callee.cpp.o  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
/usr/bin/ld: cannot find -lc++abi
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[2/1256] Linking CXX executable libs/math/test_math
FAILED: libs/math/test_math 

I build a llvm.conf , so ldconfig can find the path 
huan.wang@U-PF3QQB9A:~/AndroidStudioProjects/filament/out/cmake-release$ cat /etc/ld.so.conf.d/llvm.conf 
/usr/lib/llvm-14/lib

but the error is still happen

so I manually  set the ld path 
sudo ln -s /usr/lib/llvm-14/lib/libc++abi.so  /usr/lib
sudo ln -s /usr/lib/llvm-14/lib/libc++abi.a   /usr/lib

some new  error happen:

[5/344] Building CXX object filament/backend/CMakeFiles/backend.dir/src/BackendUtils.cpp.o
FAILED: filament/backend/CMakeFiles/backend.dir/src/BackendUtils.cpp.o 
/usr/bin/clang++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_METAL_HANDLE_ARENA_SIZE_IN_MB=8 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=2 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=4 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=2 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=3 -DFILAMENT_SUPPORTS_OPENGL -DFILAMENT_SUPPORTS_X11 -DFILAMENT_SUPPORTS_XCB -DFILAMENT_SUPPORTS_XLIB -DSYSTRACE_TAG=2 -I/home/huan.wang/AndroidStudioProjects/filament/filament/include -I/home/huan.wang/AndroidStudioProjects/filament/out/cmake-release/filament -I/home/huan.wang/AndroidStudioProjects/filament/filament/src -I/home/huan.wang/AndroidStudioProjects/filament/filament/backend/include -I/home/huan.wang/AndroidStudioProjects/filament/filament/backend/src -I/home/huan.wang/AndroidStudioProjects/filament/out/cmake-release/filament/backend -I/home/huan.wang/AndroidStudioProjects/filament/libs/math/include -I/home/huan.wang/AndroidStudioProjects/filament/libs/utils/include -I/home/huan.wang/AndroidStudioProjects/filament/third_party/robin-map/tnt/.. -I/home/huan.wang/AndroidStudioProjects/filament/libs/bluegl/include -I/home/huan.wang/AndroidStudioProjects/filament/libs/bluevk/include -I/home/huan.wang/AndroidStudioProjects/filament/third_party/vkmemalloc/tnt/../include -I/home/huan.wang/AndroidStudioProjects/filament/third_party/smol-v/tnt/../source -stdlib=libc++ -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -Wno-deprecated-declarations -stdlib=libc++ -fPIC -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -Werror -ffast-math -fno-finite-math-only -ffp-contract=fast -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/backend/CMakeFiles/backend.dir/src/BackendUtils.cpp.o -MF filament/backend/CMakeFiles/backend.dir/src/BackendUtils.cpp.o.d -o filament/backend/CMakeFiles/backend.dir/src/BackendUtils.cpp.o -c /home/huan.wang/AndroidStudioProjects/filament/filament/backend/src/BackendUtils.cpp
In file included from /home/huan.wang/AndroidStudioProjects/filament/filament/backend/src/BackendUtils.cpp:17:
In file included from /home/huan.wang/AndroidStudioProjects/filament/filament/backend/include/private/backend/BackendUtils.h:20:
In file included from /home/huan.wang/AndroidStudioProjects/filament/filament/backend/include/backend/DriverEnums.h:29:
In file included from /home/huan.wang/AndroidStudioProjects/filament/libs/math/include/math/vec4.h:20:
/home/huan.wang/AndroidStudioProjects/filament/libs/math/include/math/half.h:163:35: error: identifier '_h' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
  163 | inline constexpr half operator "" _h(long double v) {
      |                       ~~~~~~~~~~~~^~
      |                       operator""_h
In file included from /home/huan.wang/AndroidStudioProjects/filament/filament/backend/src/BackendUtils.cpp:17:
In file included from /home/huan.wang/AndroidStudioProjects/filament/filament/backend/include/private/backend/BackendUtils.h:20:
/home/huan.wang/AndroidStudioProjects/filament/filament/backend/include/backend/DriverEnums.h:1130:94: error: missing field 'stencilOpStencilFail' initializer [-Werror,-Wmissing-field-initializers]
 1130 |             .stencilFunc = StencilFunction::A, .ref = 0, .readMask = 0xff, .writeMask = 0xff };
      |                                                                                              ^
/home/huan.wang/AndroidStudioProjects/filament/filament/backend/include/backend/DriverEnums.h:1134:94: error: missing field 'stencilOpStencilFail' initializer [-Werror,-Wmissing-field-initializers]
 1134 |             .stencilFunc = StencilFunction::A, .ref = 0, .readMask = 0xff, .writeMask = 0xff };
      |                                                                                              ^
3 errors generated.
[6/344] Building CXX object filament/backend/CMakeFiles/backend.dir/src/BlobCacheKey.cpp.o
FAILED: filament/backend/CMakeFiles/backend.dir/src/BlobCacheKey.cpp.o

**Comment by poweifeng** [comment]
Can you do a `clang --version` ?

**Comment by louie-wh** [comment]
huan.wang@U-PF3QQB9A:~/AndroidStudioProjects/filament/out/cmake-release$ clang --version 
Ubuntu clang version 18.0.0 (++20230828052900+3f00c7b2ab6f-1~exp1~20230828172916.745)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by louie-wh** [comment]
I  apt-get uninstall  clang-18  and 
$ update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100
$ update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100
$ update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
$ update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 10

**Comment by louie-wh** [comment]
It  build success. thanks
