### ISSUE TITLE
Support accurate boundingbox(AABB) after morphing

### ISSUE THREAD

**Issue by cjlong1213** [google/filament#7119]
**Is your feature request related to a problem? Please describe.**
We can get the primitive's AABB after model loaded which encompass all possible vertex positions, but in my case I would like to know the accurate aabb after blendshape is changed.
For example, what is the accurate aabb when my **blendshape** key is set to **0.5**

**Describe the solution you'd like**
As far as I know, there is a flag called recomputeBoundingBoxes in AssetLoader, it is used for refine the aabb of the input resources.
Would you please add a function in **RenderableManager** call like **getRuntimeBoundingBox()** which can get the all vertexs applied morphing.

**Describe alternatives you've considered**
Maybe the function called **computeAABB**  is useful for this issue, forgive me for being a newer to Filament, I dont know how to get the runtime **vertices** from driver api  :(

Looking forward to your reply.

**Comment by romainguy** [comment]
Morphing is applied on the GPU, `RenderableManager` wouldn't be able to give you that API.

**Comment by cjlong1213** [comment]
> Morphing is applied on the GPU, `RenderableManager` wouldn't be able to give you that API.

@romainguy Very excited to see your feedback.
Is there any chance to get the runtime vertex info from the **DriverApi** after appling morphing? that we can calculate the AABB by the function of 
_static Box computeAABB(VECTOR const* vertices, INDEX const* indices, size_t count, size_t stride = sizeof(VECTOR))

**Comment by romainguy** [comment]
Like I said, morphing is done on the GPU and the result of the morph is not stored for readback.

**Comment by romainguy** [comment]
What's your use case btw?

**Comment by pixelflinger** [comment]
I feel that kind of API belongs to the application or authoring tools, not the engine.

**Comment by cjlong1213** [comment]
> What's your use case btw?

We are going to use filament to render(off-screen) frames in our avatar case.
The avatar can not be center alignment(both horizontal and vertical) by using the AABB which are the same in different morphing.
As shown blew, the red rectangle represents AABB, the left visual "AABB" should smaller than the right.


![boundingbox](https://github.com/google/filament/assets/15936033/bf91f23e-d2a9-421b-9d73-3c31006cde4f)

**Comment by pixelflinger** [comment]
You can manage all of that in your app -- Filament, for better or worse, is not a game engine, but rather a renderer. We generally don't add features that are not needed for rendering.
