### ISSUE TITLE
TAA doesn't seem to work when there are multiple views of the same scene

### ISSUE THREAD

**Issue by teub** [google/filament#7134]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
When I use multiple views for the same scene, it looks like TAA doesn't work properly. I guess each view tries to use the other view as a previous frame.

**To Reproduce**
Use multiple views to render the same scene. I'm not sure if there's a sample with multiple views to reproduce the issue.

**Expected behavior**
TAA working the same if there's one or two views of the same scene.

**Screenshots**
[Here's how an edge looks like if there's another view of it](https://github.com/google/filament/assets/11277063/f6c249d9-7471-434f-843c-60762d6b5acb)

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Comment by romainguy** [comment]
A screenshot or a detailed description would be helpful. It seems to work fine when I enable TAA with multiple views:

<img width="2077" alt="Screenshot 2023-09-02 at 12 27 03 PM" src="https://github.com/google/filament/assets/869684/3f02da29-8c56-4fc5-9dd0-3c3500257874">

**Comment by teub** [comment]
I edited the report earlier to add a video of it. I'll try to reproduce the issue with the samples then

**Comment by teub** [comment]
I patched locally gltf_viewer to render 2 views and I can't reproduce the issue.
Either it's a problem on my side or it's something specific I'm using but I can't put my finger on it. Maybe best to close the bug and reopen if I find a repro for you to use ? Unless you have an idea about what could be going on.

**Comment by teub** [comment]
Well, it's very likely to be my fault as I'm re-using the same camera across views /o\

**Comment by teub** [comment]
It's definitely my fault, sorry !

**Comment by romainguy** [comment]
Note you don't need to patch gltf_viewer, you can pass -v to show multiple views.

**Comment by teub** [comment]
I wasn't sure the other views were using the same config as the main view so I created another "main view" just to be sure.
