### ISSUE TITLE
Error in initialize engine:

### ISSUE THREAD

**Issue by yicong123456** [google/filament#7137]
Hi, I just wanna add filament in my android project. 
I used it in my fragment as:

import com.google.android.filament.Engine;
class SecondFragment: Fragment() {
private var engine: Engine? = null;
override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
          engine = Engine.create()
        var view = super.onCreateView(inflater, container, savedInstanceState)
        return view
    }
and this error occurs: 
No implementation found for long com.google.android.filament.Engine.nCreateEngine(long, long) (tried Java_com_google_android_filament_Engine_nCreateEngine and Java_com_google_android_filament_Engine_nCreateEngine__JJ)

java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.filament.Engine.nCreateEngine(long, long) (tried Java_com_google_android_filament_Engine_nCreateEngine and Java_com_google_android_filament_Engine_nCreateEngine__JJ)

![图片](https://github.com/google/filament/assets/127708940/c5040594-a0ae-44c2-be81-6b2d575c866b)
![图片](https://github.com/google/filament/assets/127708940/20d26878-d0db-4b55-b4df-2b6582565c68)
I can link to the method through ctrl+click. May I know if I miss some step to use it in the android project? thanks so much

**Comment by romainguy** [comment]
You need to call Filament.init() first.
