### ISSUE TITLE
The camera.lookAt() method is invalid, and the cameraManipulator.getLookAt(eyePos, target, upward) method overrides camera.lookAt(), resulting in invalid settings

### ISSUE THREAD

**Issue by sunlunchang1994** [google/filament#7168]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
The camera.lookAt() method is invalid, and the cameraManipulator.getLookAt(eyePos, target, upward) method overrides camera.lookAt(), resulting in invalid settings

**Comment by pixelflinger** [comment]
"Issues not using this template will be systematically closed."
