### ISSUE TITLE
Is it possible to hook into the render thread?

### ISSUE THREAD

**Issue by roxlu** [google/filament#7172]
I've posted some issues in the past about integrating Filament into an existing application that has an OpenGL context and I'm currently once again looking into this. A couple of weeks ago I posted this issue https://github.com/google/filament/issues/7115. Creating a Filament instance with shared GL context seems to work well on Linux however the same setup doesn't work on Windows. The issue on Windows is that I get flickering when rendering the shared texture into which I render a scene using Filament. 

I was thinking that it might be worth taking a different approach. Instead of sharing a GL context I'm wondering if I can somehow hook into the render thread from Filament? If I can use the same context, then I can hopefully still render into a texture and use that with my own drawing calls. 

Is it possible to "hook" into the render thread with e.g. a callback?

**Comment by romainguy** [comment]
The render thread is kept private on purpose. We've ran into many issues in the past in other renderers when apps had access to the renderer's GL context. Filament does a lot of internal state tracking which makes this kind of "sharing" difficult. We also don't trust user code to not make mistakes and for instance delete the wrong resources (which has happened multiple times :).

**Comment by roxlu** [comment]
Thanks for the quick reply! 

Then I'm back to getting the shared context to work in such a way that the output doesn't flicker. On Linux this seems to work well, not so much on Windows.

**Comment by pixelflinger** [comment]
we're not really a "windows shop" and our focus is elsewhere frankly. We might get to it, but it's not a priority.
