### ISSUE TITLE
how to debug filament web version on ios Safari

### ISSUE THREAD

**Issue by pjinsinan** [google/filament#7186]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I find opengl render error on ipad （version 15.5）safari（or chrome）， webgl2.0，opengles 3.0,  I found the error line is glDrawRangeElements，the error is GL_INVALID_OPERATION，but on android，it is rendered fine，on higher ios version ， the ipad also render ok，  I found the reason lead to  GL_INVALID_OPERATION on official website is：“GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to an enabled array or the element array and the buffer object's data store is currently mapped”，but  I do not know how capture frame on ios Safari，so
I do not know how to debug this problem，please help

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by bejado** [comment]
Can you provide more information? Are you running one of our samples that's causing the `GL_INVALId_OPERATION` error?

**Comment by pixelflinger** [comment]
@suzp1984 @pjinsinan you're not even referencing filament in the repro steps. Please provide step-by-step repros. We need to know exactly what you did (If I read this bug report absolutely *nothing* tells me it is related to filament).

**Comment by suzp1984** [comment]
I don't know the bug details either, according to the title, the author only needs to know how to debug the safari on ios.

**Comment by pjinsinan** [comment]
> Connect your ios device with your mac, open mac's safari, the debug the ios safari web page. But before that you need to Enable Safari Developer Tools(search online).

I have try this method，but it can only debug what console print，it can not debug like renderdoc

**Comment by pjinsinan** [comment]
> Can you provide more information? Are you running one of our samples that's causing the `GL_INVALId_OPERATION` error?

I find some glb render ok in  ipad （version 15.5）safari, some report GL_INVALId_OPERATION, I use the filament version [ Mon Mar 21 11:36:43 2022], now, I will  compare the diff of those glb model, and try found the reason, but if there is method like renderdoc, I think it is more efficiency to find the reason
