### ISSUE TITLE
Build faiiled while trying to build aar file.

### ISSUE THREAD

**Issue by Arvind0005** [google/filament#7238]
⚠️ **Issues not using this template will be systematically closed.**

While im trying to render my 3d model using filament i faced an issue similar to [this](https://github.com/google/filament/issues/5785) so i cloned the filament repo and made changes to the bone count variable. and now i need to build the aar file to use it as android library.

im trying to build this in windows but while executing 

```
cmake ^
    -G Ninja ^
    -DCMAKE_INSTALL_PREFIX=..\release\filament ^
    -DFILAMENT_ENABLE_JAVA=NO ^
    -DCMAKE_BUILD_TYPE=Release ^
    ..\..
```
this in  cmd following the [Building Filament for Android on Windows](https://github.com/google/filament/blob/main/android/Windows.md#building-filament-for-android-on-windows) article i got this below error 

```
CMake Error at CMakeLists.txt:179 (message):
  Detected C compiler GNU is unsupported
```
i found a similar issue for linux but can i get the solution for windows.

**Comment by romainguy** [comment]
Make sure you have the msvc compiler or clang.
