### ISSUE TITLE
Transparent Rendering For Android Sample not Transparent

### ISSUE THREAD

**Issue by sebapian** [google/filament#7273]
Description of Bug:
As per title, transparent rendering for Android sample not coming up as transparent. No changes were made to any files. I'm hoping someone can look into this issue. See screenshot below.

Repro steps:
Just run transparent sample.

Expected behaviour:
As I am currently trying to solve an issue #7220, I'm resorting to trying out the samples. However, even the samples aren't showing transparent rendering but black instead.

Screenshots:
**Pixel 4**
<img width="418" alt="image" src="https://github.com/google/filament/assets/89761448/f65b7034-a140-4bfd-af58-2398e1c46ee7">
**Pixel 5**
<img width="437" alt="image" src="https://github.com/google/filament/assets/89761448/9c168882-6e2b-4a92-af37-c0c562a0bf3d">

Logs:
No logs as this is UI issue.

**Desktop (please complete the following information):**
 - OS: MacOS
 - GPU: M1 Max Pro

**Smartphone (please complete the following information):**
 - Pixel 4 Emulator (API 33)
 - Pixel 5 Emulator (API 33)

**Comment by romainguy** [comment]
Using different Pixel devices in the emulator doesn't matter, what matters is the API level. The device really only specifies the screen size, density, etc.

**Comment by romainguy** [comment]
@pixelflinger could be a clear issue maybe?

**Comment by pixelflinger** [comment]
this will be fixed by https://github.com/google/filament/pull/7283

**Comment by sebapian** [comment]
Hi @pixelflinger, just looking at the PR, will this only impact the transparent sample, or will it affect other apps implementing Filament library?

**Comment by pixelflinger** [comment]
This will affect all Android apps. I don't think it was broken on other platforms.
