### ISSUE TITLE
Random rendering errors on the OpenGL backend on heavy workloads (KHR_debug: `<texture> is not the name of an existing texture`)

### ISSUE THREAD

**Issue by ennis** [google/filament#7280]
**Describe the bug**
We use filament in our compositing application as a render delegate for animated USD scenes, and some frames of an animation did not render correctly (black frame).

**To Reproduce**
I did not have the time to create a minimal reproducible example. We managed to reproduce the bug only in release mode on a very specific (and heavy) workload.

**Expected behavior**
The scene is rendered correctly.

**Screenshots**
N/A

**Logs**
N/A

**Desktop (please complete the following information):**
 - OS: Windows x64
 - GPU: RTX 2070, among others
 - Backend: OpenGL

**Additional context**
With KHR_debug output enabled, the following messages are emitted by `glFramebufferTexture2D`, randomly during playback, in `OpenGLDriver::framebufferTexture`:
`GL_INVALID_OPERATION error generated. <texture> is not the name of an existing texture.`

I noticed that some of the texture names generated by glGenTextures in createTextureR are not recognized as a texture (nor a renderbuffer) at the end of the function (glIsTexture returns false). 
At a glance, it seems that there's a possible scenario where glGenTextures recycles a previously deleted texture name, that's still bound in the state cache used in `OpenGLContext::bindTexture`. In this case, `glBindTexture` is not called (because filament sees it as already bound), but some sources on the internet suggest that calling `glBindTexture` is required after `glGenTextures` (at least to define the dimensionality of the newly created texture). I'm not sure what the OpenGL spec says about that.

In any case, bypassing the state cache in `OpenGLContext::bindTexture` (forcing glBindTexture to be called every time) solved our issue.

**Comment by pixelflinger** [comment]
Thanks for the detailed analysis.

**Comment by pixelflinger** [comment]
Would you be able to provide a bit more info when `glIsTexture` fails, in particular what was the texture target used?
We do unbind the texture from all units when destroyed, so in first inspection I don't see how this scenario can happen.

**Comment by ennis** [comment]
IIRC the target was always GL_TEXTURE_2D; and the call to glFramebufferTexture2D that failed was always for GL_DEPTH_ATTACHMENT. Also, we could only reproduce the issue with ambient occlusion enabled, with the "bent normals" option.

**Comment by ennis** [comment]
I also forgot to mention that we did not use the latest version of filament, so the problem might be solved already on master; unfortunately we didn't have the time to upgrade recently

**Comment by pixelflinger** [comment]
Okay, thanks I will take a look.  By code inspection it doesn't seem possible to have a dangling texture in the state cache, so it's going to be difficult to fix without a repro case. I did try a very heavy scene with all these options enabled, without seeing this problem.

**Comment by ennis** [comment]
Are the textures unbinded here (in `OpenGLDriver::destroyTexture`)?
https://github.com/google/filament/blob/b62991d967dcabeb78baf896d26955bd5dc05ebb/filament/backend/src/opengl/OpenGLDriver.cpp#L1465
It seems that this is not called if the texture has the `imported` flag. We do happen to use a lot of imported textures in our pipeline (some objects in our scene have dynamic textures that are rendered with our composition engine, on a separate OpenGL context shared with filament's).

**Comment by pixelflinger** [comment]
> It seems that this is not called if the texture has the `imported` flag. We do happen to use a lot of imported textures in our pipeline (some objects in our scene have dynamic textures that are rendered with our composition engine, on a separate OpenGL context shared with filament's).

Ah, that's an important bit of information.
