### ISSUE TITLE
White borders with FXAA + Vulkan + Android

### ISSUE THREAD

**Issue by prideout** [google/filament#732]
To repro, build android/samples/hello-triangle with Vulkan enabled, see attached screenshot.  The white borders go away when disabling post-processing on the view.

![with_fxaa](https://user-images.githubusercontent.com/1288904/51564908-60602080-1e45-11e9-8ea3-174ed4d22e5b.png)

**Comment by romainguy** [comment]
FXAA needs an RGBA target, maybe that's the issue?

**Comment by prideout** [comment]
Hm I've confirmed that we're using VK_FORMAT_R8G8B8A8_UNORM for the swap chain and VK_FORMAT_R16G16B16A16_SFLOAT for the intermediary buffer, but you might be on the right track...

Visually, this reminds me of an old issue where the FXAA shader was using the wrong texel size due to a mismatch between viewport size and actual framebuffer size.

**Comment by romainguy** [comment]
Maybe it's a texel size mismatch but we should be doing FXAA at the same resolution as the HDR pass.

**Comment by romainguy** [comment]
glslang bug then maybe? We can use the workaround in the meantime.

**Comment by prideout** [comment]
After staring at a lot of spirv, I actually think this is a Qualcomm issue rather than a glslang or shader pipeline issue.

I have "good" and "bad" spirv dumps that are clearly semantically equivalent.  Let me dig up a Mali device and try it there...

**Comment by prideout** [comment]
I've confirmed that this issue does not occur with Mali.  For now I'll commit the workaround.
