### ISSUE TITLE
Using the Manipulator, the model cannot be rotated 360 along the X axis

### ISSUE THREAD

**Issue by dennyson-w** [google/filament#7324]
**Description error**
I ran the sample-gltf-viewer project on an Android device and found that when sliding horizontally on the screen, the model can rotate at any angle, but when sliding vertically, the model can only rotate up to 180 degrees.

**copy**
I ran the sample-gltf-viewer project on an Android device and found that when sliding horizontally on the screen, the model can rotate at any angle, but when sliding vertically, the model can only rotate up to 180 degrees.

**Expected Behavior**
I want to slide vertically and the model can be rotated at any angle

**screenshot**
It's hard to describe the problem so I'm adding the video below.

**Desktop (please fill in the following information):**
    - Operating System: [Android]

**Smartphone (please fill in the following information):**
    - Device: [SM_F9000]
    - Operating System: [Android 12]

**Additional context**

https://github.com/google/filament/assets/7814811/1b85cdba-1a2b-4fe3-9df7-822038bd6d16

**Comment by dennyson-w** [comment]
@prideout @m0rphtail

**Comment by romainguy** [comment]
This is done to avoid seeing the model upside down. You should probably build your own manipulator if you want more freedom.
