### ISSUE TITLE
Vulkan validation error output

### ISSUE THREAD

**Issue by maxiaoxr** [google/filament#7334]
When use headless mode in vulkan graphic.
Vulkan validation output:
VULKAN ERROR: (Validation) Validation Error: [ UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress ] Object 0: handle = 0xcfef35000000000a, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x76fdada900, type = VK_OBJECT_TYPE_QUEUE; Object 2: handle = 0x76fdada900, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xe825f293 | vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] is signaling VkQueue 0x76fdada900[] (VkSemaphore 0xcfef35000000000a[]) that was previously signaled by VkQueue 0x76fdada900[] but has not since been waited on by any queue.

**Comment by poweifeng** [comment]
Can you provide more information? Specifically platform, GPU, and code to repro?

**Comment by maxiaoxr** [comment]
Hi:
You can use the sample "rendertarget" and change the config as the following:
   App app{};
   app.config.title = "rendertarget";
   app.config.headless = true;
   app.config.backend = Engine::Backend::VULKAN;
Run the sample,then you can see the error output in the terminal.

Thanks a lot

**Comment by poweifeng** [comment]
Thanks, I'm able to repro.  Fix incoming.

**Comment by maxiaoxr** [comment]
Perfect!!
Thanks a lot.
