### ISSUE TITLE
abnormal memory in Android

### ISSUE THREAD

**Issue by August1996** [google/filament#7336]
Base on tag [v1.40.0](https://github.com/google/filament/releases?page=2), i revert two commits.
[the ShaderCompilerService handles async shader compilation](https://github.com/google/filament/commit/74f5d8a0668fdd7cf0cb81c21990447bab9b2fbf)
[fix error reporting with ShaderCompilerService](https://github.com/google/filament/commit/35c91827af1208f07aa0052c5ec9977fa0830059)

the memory of `sample-gltf-viewer` down to 642MB from 737MB, which is the same as v1.39.0

@pixelflinger @bejado

**Comment by August1996** [comment]
```
fix error reporting with ShaderCompilerService

when using the thread pool we were destroying the shaders immediately,
we need to defer this until we query the program link status, so that
in case of failure we can query each shader compile status.

we make the shader handles part of the promise/future so they can be
transferred to the main thread, just like the program id is.
```
The commit refers to defer  destroying the shaders until query the program link status, but i can not find the code to destroy shaders.

@pixelflinger

**Comment by August1996** [comment]
> ```
> fix error reporting with ShaderCompilerService
> 
> when using the thread pool we were destroying the shaders immediately,
> we need to defer this until we query the program link status, so that
> in case of failure we can query each shader compile status.
> 
> we make the shader handles part of the promise/future so they can be
> transferred to the main thread, just like the program id is.
> ```
> 
> The commit refers to defer destroying the shaders until query the program link status, but i can not find the code to destroy shaders.
> 
> @pixelflinger

https://github.com/google/filament/commit/35c91827af1208f07aa0052c5ec9977fa0830059

**Comment by pixelflinger** [comment]
I think this is the same issue as #7318.
