### ISSUE TITLE
KHR_XMP_JSON_LD extension support

### ISSUE THREAD

**Issue by PsycoTodd** [google/filament#7338]
**Is your feature request related to a problem? Please describe.**
We want to support KHR_XMP_JSON_LD extension in the form of exposing the json string at the potential components (asset, scene, node, mesh, material, image, animation). But in reality we may limit the access to a few components based on the filament design.

**Describe the solution you'd like**
* We first make sure we parse the information in cgltf.h and have code commit there. So cgltf.h contains the code to read this extension and also possible to write it out in cgltf_write.h

* then in filament/libs/gltfio/include/gltfio/FilamentAsset.h introduce function `std::vector<std::string> getKHRXmpJsonLd(Entity entity = {})` to expose the vector of the json_ld. Since it is possible to refer multiple index in the extension section of the component, the output is a vector.

* This change is similar to how extra is handled in filament right now.

* However, I notice that FilamentAsset is not designed to expose information on all the components. I cannot find way to expose, for example, `extra` for image, animation.  So how to expose the json_ld strings in all components for filament user to use need consider?

**Describe alternatives you've considered**

* An alternatives is to let user to deal with cgltf data themselves. So we do not expose this extension data at FilamentAsset level. 

**OS and backend**
This feature is not specific to a special backend/OS.

**Comment by pixelflinger** [comment]
Filament is a renderer, and not a generic gltf library. The alternative solution above seem more appropriate.
