### ISSUE TITLE
Depth problem: custom material with blending transparent

### ISSUE THREAD

**Issue by randylu** [google/filament#7355]
**Describe the bug**
I use the latest version in Sceneform for Android, and try to make an animal with some cube nodes.
I define a material for each cube node, and set blending to transparent, the problem is the leg may be covered by its body when rotating. It seems something wrong with depth test.
In addition, it's OK if set blending to opaque. But for some reason, i must use transparent.

**Expected behavior**
The leg should be in front of the animal's body, for it's closer to the screen.

**Screenshots**
![1699872759338](https://github.com/google/filament/assets/7234176/f829d7d8-b049-4b23-b597-ef04e9aeed2b)

the expected one is
![1699872759335](https://github.com/google/filament/assets/7234176/534e9794-d11c-45b6-b717-6af27df665ce)

**Logs**
The material definition:
material {
    name : "Textured material",
    
    doubleSided : true,

    parameters : [
        {
           type : sampler2d,
           name : texture
        },
        {
            type : float,
            name : alpha
        }
        
    ],
    requires : [
        uv0
    ],
    shadingModel : unlit,

    // ****** it's OK if change to opaque ******//
    blending : transparent
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = texture(materialParams_texture, getUV0());
        material.baseColor = material.baseColor * materialParams.alpha;
    }
}

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - Android Pie 9.0

**Comment by randylu** [comment]
I take a look at this issue #2838. It seems Filament doesn't support depth sorting of transparent fragments.
But my case is more simple, is it OK to use the depth sorting of opaque for transparent.

**Comment by romainguy** [comment]
You'd have to use a single model or avoid using blending in this case. Alternatively you could use renderable priority.

**Comment by randylu** [comment]
What do you mean by using renderable priority.

**Comment by romainguy** [comment]
See https://github.com/google/filament/blob/2bd48f58ff57c7757cf0c778708af7ce40f77de2/filament/include/filament/RenderableManager.h#L260 and https://github.com/google/filament/blob/2bd48f58ff57c7757cf0c778708af7ce40f77de2/filament/include/filament/RenderableManager.h#L482

**Comment by randylu** [comment]
Thanks very much.

**Comment by cindyloo** [comment]
this was a real challenge for me. I have a GLB model and wanted to render it along with ARCore objects. I got really frustrated trying to use gl_FragCoord.z, hich is logarithmic/hyperbolic and hence hard to compare with arDepth.  I also tried passing in virtualDepth from a second pass at filament render and that was too confusing to manage the various textures. For now, I am using
 ```        
        vec2 screenUV = gl_FragCoord.xy / getResolution().xy;
        vec2 rotatedUV = vec2(screenUV.y, 1.0 - screenUV.x);

         vec3 worldPos = getWorldPosition();
        vec3 cameraPos = getWorldCameraPosition();
        float virtualDepthMeters = distance(worldPos, cameraPos);


        // Transform for ARCore depth
        mat4 depthUvTransform = mat4(
            materialParams.uvTransformRow0,
            materialParams.uvTransformRow1,
            materialParams.uvTransformRow2,
            materialParams.uvTransformRow3
        );
        
        vec4 depthUV4 = depthUvTransform * vec4(rotatedUV, 0.0, 1.0);
        vec2 depthUV = clamp(depthUV4.xy / depthUV4.w, 0.0, 1.0);
        vec4 ardepthSample = texture(materialParams_depthTexture, depthUV);
        


        // Read virtual color
        vec4 virtualColor = texture(materialParams_colorTexture, screenUV);


        // Decode ARCore depth
        float arCoreDepthMm = ardepthSample.r * 255.0 + ardepthSample.g * 255.0 * 256.0;
        float arCoreDepthMeters = arCoreDepthMm * 0.001;

  // Use virtual color as base
        material.baseColor.rgb = virtualColor.rgb;
        material.roughness = materialParams.roughness;
        material.metallic = materialParams.metallic;

        // Simple occlusion test
        if (arCoreDepthMeters > 0.01 && 
            arCoreDepthMeters < (virtualDepthMeters - materialParams.occlusionBias)) {
            discard;
        }
        
        // Set material properties
        material.baseColor.rgb = texture(materialParams_colorTexture, screenUV).rgb;
        material.roughness = materialParams.roughness;
        material.metallic = materialParams.metallic;
    }



```
