### ISSUE TITLE
Add API to control the width of line primitives

### ISSUE THREAD

**Issue by wddl** [google/filament#7361]
in filament::gltfio::Wireframe class LINES are created , as follows:
`RenderableManager::Builder(1)
        .culling(false)
        .castShadows(false)
        .receiveShadows(false)
        .geometry(0, RenderableManager::PrimitiveType::LINES, mVertexBuffer, mIndexBuffer)
        .build(*engine, mEntity);`
but in android lines width is too  thin.  how to Increase line width? thanks!

_Originally posted by @wddl in https://github.com/google/filament/discussions/7354_

**Comment by pixelflinger** [comment]
The line width can be controlled in the material file with `glLineWidth` in the material used to draw them.

**Comment by wddl** [comment]
@pixelflinger thanks to helps. I try use the method
