### ISSUE TITLE
ColorGrading channel mixer is not working as expected. 

### ISSUE THREAD

**Issue by lxshao007** [google/filament#7364]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
we use channel mixer to do the color correction. the left image is the original image, the middle one is the result from applying channel mixer. the right one is the result from opencv after color correction. 
the color correction value is r: 1.146685 g: 1.0 b: 0.891054. 
in the channel mixer, we apply 
```
getRenderer().getFilamentView().setColorGrading(
                                new ColorGrading
                                        .Builder()
                                        .channelMixer(new float[]{1.146685f, 0, 0}, new float[]{0, 1, 0}, new float[]{0, 0, 0.891054f})
                                        .build(EngineInstance.getEngine().getFilamentEngine())
                        );
```

opencv result is by multiply the correction value. 

**To Reproduce**

**Expected behavior**
match with the result generated by opencv

**Screenshots**
![Screenshot 2023-11-14 at 11 44 46 AM](https://github.com/google/filament/assets/30398649/27d7849e-ddb6-4a73-9154-67e6c43ec701)

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
It's not going to match OpenCV because Filament does not operate in the same color space (Filament uses Rec.2020).
