### ISSUE TITLE
Depth prepass artifacts with NVIDIA GTX

### ISSUE THREAD

**Issue by baktery** [google/filament#737]
Originally I was writting this report:

### Old report ###

**Original Issue Title**
Indirect light artifacts when rotated

**Describe the bug**
When using an IBL and setting the rotation of the indirect light to a non-multiple of 90 degress some objects are rendered with artifacts depending on the object position, rotation and the camera position and rotation.

**To Reproduce**
The easier way I found to reproduce the issue is:

1. Start the material_sandbox sample. Make sure that a IBL file has been properly specified. Here tested with \models\sphere\sphere.obj as 3D object and envs\pillars as IBL.

2. Do some rotations and translation to the 3D object with the mouse (left/right buttons)

3. Set the light ibl rotation to a non-multiple of 90 degress value

4. Press the checkbox to enable and disable the light several times.

5. Some artifacts will appear when rendering the 3D object

Note: The issue can be reproduced just moving the camera but with the previous steps is easier to get a static image with the artifacts

**Expected behavior**
No artifacts when rendering 3D objects

**Screenshots**
![image](https://user-images.githubusercontent.com/7185257/51633779-bff82200-1f52-11e9-8357-83932e1a9493.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: GTX 1070
 - Backend: OpenGL

Before submiting the issue, I found this report from days ago:

https://github.com/google/filament/issues/645

My sources were about 4 weeks old so I decided to update to latest sources (master branch).

Now the reproduction case with the basic sample works fine, no more artifacts when rotating the IBL **BUT new artifacts appeared in my application using filament.**

I has been able to reproduce the new issue with the glft_viewer sample, here are the steps to reproduce it:

### New report ###

**To Reproduce**

1. Run the glft_viewer with a IBL and the attached glft model.

2. Move the camera, some artifacts will appear 

**Attached 3D Object**

[test.zip](https://github.com/google/filament/files/2790806/test.zip)

**Screenshots**

![image](https://user-images.githubusercontent.com/7185257/51665113-49dbd580-1fbb-11e9-969d-71c249ecea08.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: GTX 1070
 - Backend: OpenGL

**Comment by prideout** [comment]
Do the artifacts go away if you [disable the depth prepass](https://github.com/google/filament/blob/master/filament/include/filament/View.h#L171)?

**Comment by prideout** [comment]
If the issue goes away after disabling the depth prepass, can you do us a favor and double check that you have [this fix](https://github.com/google/filament/commit/91c946cfbd039ce8c3c19da831e6801db88d67c6) in your tree then do a clean build, just to be sure?

**Comment by baktery** [comment]
> Do the artifacts go away if you disable the depth prepass?

Disabling depth prepass fixes the issue.

> Do the artifacts go away if you disable the depth prepass?

Unfortunately the sources I'm using already contained the fix.

I doublechecked: did a clean clone of the repository, recreated the Visual Studio solution/project files and built them, artifacts are there.

If there's anything else I can do on my side please let me know.

**Comment by prideout** [comment]
Thanks!  I can't repro with your test model on my NVIDIA card, so let me ask you to do one more experiment for us.  Try syncing to the following branch and giving it a shot.  This makes it so that the depth prepass vertex shader is the exact same vertex shader as what's used in the color pass.

https://github.com/google/filament/compare/pr/experiment?expand=1

**Comment by bejado** [comment]
Hm, it’s possible but our CI should have picked up Windows compilation issues. How are you compiling?

**Comment by baktery** [comment]
I'm doing it the same way I did it yesterday:

1. Clone the repo
2. Create Visual Studio 2017 solution/project files with the following cmake command line arguments:

```
-T"LLVM" -G "Visual Studio 15 2017 Win64" -DCMAKE_CXX_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER:PATH="C:\Program Files\LLVM\bin\lld-link.exe"
```
3. Open TNT.sln and build it (Debug/x64)

**Comment by baktery** [comment]
Extra info:

``` 
C:\Program Files\LLVM\bin>clang --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by bejado** [comment]
Thanks for the info- I see the same errors on my machine. Will look into it.

**Comment by bejado** [comment]
@baktery Looks like the errors are only for Debug builds, so for the time being you can try to build in Release.

**Comment by skrat** [comment]
I'm seeing the same behavior on Linux/Intel HD3000, even with Release build

**Comment by nxrighthere** [comment]
GTX 950 same issue with the release build.

**Comment by nxrighthere** [comment]
Same problem on GTX 1660, no progress on this? 😢
