### ISSUE TITLE
add point light in scene when render, chrome crash when hardware acceleration open 

### ISSUE THREAD

**Issue by pjinsinan** [google/filament#7378]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I compile filament with emcripten,  and run the program in desktop chrome( 119.0.6045.160),  In scene, I only have a simple glb model and direct light, it render well,  when I add a point light in scene, the program crash (chrome surface go black one second and then recover) and it report error in following:
![image](https://github.com/google/filament/assets/5959808/76937760-f5ed-4adf-a1e7-f84b29630e56)
the error looks wild, it prints compile error and error reason is null,  then I close the hardware acceleration in chrome setting and refresh, it render success,  I feel confused and test several case(all test case with a glb model in scene):
1,  one point light in scene, open hardware acceleration in chrome setting, render crash
2,  one point light in scene, close hardware acceleration in chrome setting, render success
3,  no point light in scene, render success(no matter hardware acceleration  open or close)
4, one point light in scene, open hardware acceleration, edit shader in light_punctual.fs like this, render success: 
![image](https://github.com/google/filament/assets/5959808/2431e840-d3ab-4c1a-8ac8-83539066aeb9)
![image](https://github.com/google/filament/assets/5959808/03d72204-bf10-4e73-af7f-723f65e593b7)

finally, I found if I visit the data froxelRecordUniforms.records,  it crash,  I want to know is it any trick in hardware acceleration , why when visit froxelRecordUniforms.records data it crash? 

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - OS: [windows 10 , chrome 119.0.6045.160 ]
 - GPU: [amd radeon rx 6600]
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by pixelflinger** [comment]
Can you include the GLB that causes problems?

**Comment by pjinsinan** [comment]
> Can you include the GLB that causes problems?

thanks  a lot , here is my test glb model
[hair.zip](https://github.com/google/filament/files/13484623/hair.zip)
