### ISSUE TITLE
if Renderable is a manually generated model， use boudingbox compute shadow

### ISSUE THREAD

**Issue by bobo008** [google/filament#7380]
The problem could be the bounding box you set on the renderable. We use bounding boxes to compute tight shadow maps.
Is it possible to calculate shadows without using bounding boxes? Because sometimes the bounding boxes is not right

**Comment by romainguy** [comment]
Bounding boxes are used for culling and necessary for performance.

**Comment by bobo008** [comment]
I know bounding boxes is necessary， But it seems that bounding boxes are also used to calculate shadows.

**Comment by bobo008** [comment]
> Bounding boxes are used for culling and necessary for performance.


https://github.com/google/filament/assets/26623108/9174e215-8a21-4a16-b218-f2913bd7a154

built a {-10.5, 0, 10.5} {-17, 0, 17} plane, add a directional light of { -1, -1 ,0 },set bounding boxes {{-1, -1, -1 }, {1, 1, 1}}

**Comment by bobo008** [comment]
If you set the correct bounding boxes it will be correct, but sometimes Sometimes models are complex，I can't guarantee that boundingboxes are always correct， so can I set up not using boundingboxes to calculate shadows? @romainguy

**Comment by romainguy** [comment]
No, you need bounding boxes. To compute one take the min and max of all the vertices. It doesn't matter how complex the mesh is, the bounding boxes are computed the same way.

**Comment by bobo008** [comment]
> No, you need bounding boxes. To compute one take the min and max of all the vertices. It doesn't matter how complex the mesh is, the bounding boxes are computed the same way.

if bounding boxes is wrong， will the shadow be as weird as the video above?  Even if you use boundingboxes to calculate shadows, shadows shouldn't be so strange....

**Comment by romainguy** [comment]
Bounding boxes are used to focus shadows to provide higher quality

**Comment by bobo008** [comment]
> Bounding boxes are used to focus shadows to provide higher quality

Thank you, now I know that bounding boxes are not used to calculate shadows, but to focus(crop?) shadows, it is reasonable. So the above phenomenon is not because the bounding boxes are set wrong, but for another reason? @romainguy
