### ISSUE TITLE
GCC Compilation Errors

### ISSUE THREAD

**Issue by errissa** [google/filament#7386]
**Describe the bug**
As described in #4990 there are some using declarations that trigger a GCC error (-fpermissive). The PR that closed #4990 addressed some of the issues but compilation errors remain in `filament/include/filament/View.h` and `filament/include/filament/Material.h`. 

**To Reproduce**
The following minimal program should trigger the error when compiled with GCC 9.4.
```
#include <filament/Material.h>
#include <filament/View.h>

int main() {
    return 0;
}
```

**Expected behavior**
Program that includes the referenced Filament headers compiles successfully with gcc 9.4.

**Screenshots**
_NA_

**Logs**
_NA_

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU/PCIe/SSE2
 - Backend: OpenGL and Vulkan

**Smartphone (please complete the following information):**
_NA_

**Additional context**

**Comment by romainguy** [comment]
Unfortunately supporting GCC isn't one of our priorities.

**Comment by pixelflinger** [comment]
So this is interesting. According to GCC our code is actually wrong, but clang doesn't catch this case, meaning even if we fix it, we are bound to recreate that problem down the line.

gcc will only emit a warning when using `-fpermissive` is that not a solution? gcc13 has a new `-Wchanges-meaning` which can be used instead of `-fpermissive`

**Comment by rsepulveda-biocorellc** [comment]
@pixelflinger Thanks for accepting and merging #7387. For some `-fpermissive` could be a solution, but for Open3D we build with `-Werror` so we'd still get a compilation failure with `-fpermissive`.

**Comment by errissa** [comment]
@pixelflinger Thanks for accepting and merging #7387. For some, `-fpermissive` would get prevent the compilation failure but we build Open3D with `-Werror` so we'd still get a compilation error.
