### ISSUE TITLE
metal: After enabling MSAA and sunlight, black spots appear.

### ISSUE THREAD

**Issue by NewbyThebest** [google/filament#7393]
**Describe the bug**
When using Metal, after enabling MSAA and sunlight, black spots appear in certain areas of the model, as shown in the video. When switching to OpenGL, everything is normal.

**To Reproduce**
1.Build using version 1.45.0 of Filament.
2.Open the iOS example "gltf_viewer".
3.Manually add the MSAA code:
```
auto option = _view->getMultiSampleAntiAliasingOptions();
option.enabled = true;
option.sampleCount = 4;
option.customResolve = false;
_view->setMultiSampleAntiAliasingOptions(option);
```
4.Run the example on an iPhone.
5.Rotate the object, and you can see black spots appearing in certain areas

**Expected behavior**
There are no black spots.

**Screenshots**
<img width="382" alt="cad03ba9-b46d-4a02-9ccf-1394d4687886" src="https://github.com/google/filament/assets/26302373/3f335355-e965-4c19-8e50-fe627d6f0523">

https://github.com/google/filament/assets/26302373/03886cc4-db23-4c40-8108-29c423c7764e

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: iOS 17.0
 
**Additional context**
In my own iOS project, I encountered the same issue. When I tried disabling MSAA, the black spots turned into white spots, resembling specular reflections. When I further disabled post-processing, the white spots turned back into black spots. Finally, when I disabled sunlight, everything returned to normal.

**Comment by bejado** [comment]
I'm unable to reproduce on an iPhone 14 Pro with the [latest Filament](https://github.com/google/filament/commit/addae314b447a747dd850c7701fcfaac0a1af83e). Here's what I see:

![Screenshot 2023-12-26 at 12 46 47 PM](https://github.com/google/filament/assets/5298046/0ded739e-c275-4ca5-842b-cc8df57e6f58)

Feel free to re-open if the issue persists.

**Comment by NewbyThebest** [comment]
> I'm unable to reproduce on an iPhone 14 Pro with the [latest Filament](https://github.com/google/filament/commit/addae314b447a747dd850c7701fcfaac0a1af83e). Here's what I see:
> 
> ![Screenshot 2023-12-26 at 12 46 47 PM](https://private-user-images.githubusercontent.com/5298046/292913599-0ded739e-c275-4ca5-842b-cc8df57e6f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDIzNDIsIm5iZiI6MTcwNDQ0MjA0MiwicGF0aCI6Ii81Mjk4MDQ2LzI5MjkxMzU5OS0wZGVkNzM5ZS1jMjc1LTRjYTUtODQyYi1jYzhkZjU3ZTZmNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDgwNzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmVkYjcwOTM0ZDMzNmRkZWMwNTcxNzllNTE5YjlmZjJlY2RmOWI3NzM4MWY0ZWJhNDAzNzFiYzQ5YzZkZDYzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VDDAhr0vHh1z5WDcXc7HQPO2uUKw_7Qnq3-Ub-TxkJA)
> 
> Feel free to re-open if the issue persists.

I tried the new version you mentioned, and the issue still persists on the iPhone 13. No matter which version of filament I switch to, the problem occurs. By the way, the issue is also present on another device of mine, an iPhone XS, and it’s even more pronounced there. When I attempted to turn off MSAA, it turned into white spots. For now, the only workaround I have is to temporarily avoid the problem by turning off sun lighting.

**Comment by NewbyThebest** [comment]
> I'm unable to reproduce on an iPhone 14 Pro with the [latest Filament](https://github.com/google/filament/commit/addae314b447a747dd850c7701fcfaac0a1af83e). Here's what I see:
> 
> ![Screenshot 2023-12-26 at 12 46 47 PM](https://private-user-images.githubusercontent.com/5298046/292913599-0ded739e-c275-4ca5-842b-cc8df57e6f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDIzNDIsIm5iZiI6MTcwNDQ0MjA0MiwicGF0aCI6Ii81Mjk4MDQ2LzI5MjkxMzU5OS0wZGVkNzM5ZS1jMjc1LTRjYTUtODQyYi1jYzhkZjU3ZTZmNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDgwNzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmVkYjcwOTM0ZDMzNmRkZWMwNTcxNzllNTE5YjlmZjJlY2RmOWI3NzM4MWY0ZWJhNDAzNzFiYzQ5YzZkZDYzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VDDAhr0vHh1z5WDcXc7HQPO2uUKw_7Qnq3-Ub-TxkJA)
> 
> Feel free to re-open if the issue persists.

The first video below shows the situation where I didn't enable MSAA (Multisample Anti-Aliasing). As you can see, there is a relatively subtle white stripe. The second video demonstrates the scenario where I enabled MSAA, and the position of the white stripe has become a very noticeable black stripe. It's worth noting that this issue only occurs in examples with sunlight, and coincidentally, the gltf-viewer has sunlight enabled, which is why the problem arises.

https://github.com/google/filament/assets/26302373/85b47c80-9702-4a4d-8f71-77f919399fd3


https://github.com/google/filament/assets/26302373/f70851ba-76ec-4e43-a6b1-0215a375a6e7

**Comment by bejado** [comment]
Thanks for the videos, I'll take another look. Perhaps this is something specific to the iPhone 13.

**Comment by NewbyThebest** [comment]
> Thanks for the videos, I'll take another look. Perhaps this is something specific to the iPhone 13.

Fantastic! It perfectly solved the problem I encountered. Thank you very much.
