### ISSUE TITLE
ibl and skybox are not correctly when the scene world matrix is changed

### ISSUE THREAD

**Issue by wddl** [google/filament#7403]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
When the world matrix of the scene changes, the positions of ibl and skybox are not in the center

**To Reproduce**
1. Rotate and change the world matrix

**Expected behavior**
ibl and skybox change follow the scene matrix

**Screenshots**
![Screenshot_20231204_182711_org libsdl app](https://github.com/google/filament/assets/26518625/61e9ecb5-afb4-46d9-8bf5-84f0fed82243)

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - OS: android
 - GPU: 
 - Backend: opengles

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pixelflinger** [comment]
I need more info here.  What do you call the "world matrix"? Are you talking about `IndirectLight::rotation()`
Can I reproduce this with `gltf_viewer`?

**Comment by wddl** [comment]
> I need more info here. What do you call the "world matrix"? Are you talking about `IndirectLight::rotation()` Can I reproduce this with `gltf_viewer`?

@pixelflinger thanks to reply
I'm trying the IndirectLight::rotation() function, but does the skybox not have this feature?

**Comment by pixelflinger** [comment]
the skybox should be affected. You can see this in our gltf_viewer.

**Comment by wddl** [comment]
@pixelflinger I konw.thanks
