### ISSUE TITLE
Weird shadow clipping

### ISSUE THREAD

**Issue by kpeeters** [google/filament#742]
I'm experiencing a weird shadow clipping issue when generating geometry by hand. See the image below.

![clipped](https://user-images.githubusercontent.com/5918606/51744174-e7580780-2096-11e9-8827-c8cd3fa6f783.jpg)

If instead of generating the vertical square by hand, I read one in from an .obj using MeshAssimp, all is well,

![correct](https://user-images.githubusercontent.com/5918606/51744177-e7580780-2096-11e9-9f37-593e10e22640.jpg)

I have verified that the position, tangent and texture buffers are identical, and that these two objects use the same material, yet I keep seeing the clipped shadow in the first instance. The clipping changes when rotating around the scene.

I'm sure it's not a bug per se in filament, but perhaps someone has a clever idea about what I am overlooking?

**Comment by romainguy** [comment]
The problem could be the bounding box you set on the renderable. We use bounding boxes to compute tight shadow maps.

**Comment by kpeeters** [comment]
Already checked that; bounding boxes are identical in the two cases...

**Comment by romainguy** [comment]
@pixelflinger Any idea?

@kpeeters Would you mind showing how you create the renderable?

**Comment by kpeeters** [comment]
Aargh, this was a bounding box issue. I was simpy reading over the fact that when you do

    RenderableManager::Builder(1).boundingBox({ {a,b}, {c,d} }). ...

the `{a,b}` should be the center and `{c,d}` the halfExtent; not the minimum and maximum... Well, at least I'm now 100% sure there are no other bugs in my code ;-)

Are you guys taking pull requests for docstring updates? Having this spelled out in the docs would have probably saved me quite some time.

**Comment by romainguy** [comment]
I'm glad you figured it out! We do take PRs for docs of course. `Box` could indeed use documentation :)
