### ISSUE TITLE
Add relationship() support to TextColumn

### ISSUE THREAD

**Issue by somzoli** [google/filament#7432]
**Is your feature request related to a problem? Please describe.**
I have two models: 
- Rule
- Interface

Relations:
Rule: 
`public function IInterfaces()
    {
        return $this->belongsTo(IInterface::class, 'i_interface_id');
    }`
Interface:
`public function Rules()
    {
        return $this->HasMany(Rule::class);
    }`

But the interface model is usable as input interface and out interface. For this i have to add an extra foreign key to Rule table:

```
//IN
$table->foreignIdFor(Models\IInterface::class)->nullable()->cascadeOnDelete();
```
```
//OUT
$table->foreignIdFor(Models\IInterface::class, 'out_i_interface_id')->nullable()->cascadeOnDelete();
```

In Rule form, i can use this, which is working fine:
`Forms\Components\Select::make('out_i_interface_id')
                ->relationship('IInterfaces', 'name')
                ->label('OUT interface'),`

But in Columns on Rule list, the "OUT" column can not use, because i cant define the relation that i want to use
`Tables\Columns\TextColumn::make('out_i_interface_id')
                ->label('Out Interface')
                ->searchable()
                ->sortable(),`
**Describe the solution you'd like**
Maybe can port relationship() from Select?

Can you help with this?
Thanks!

BR,
Z

**Comment by romainguy** [comment]
Wrong filament project :)

**Comment by somzoli** [comment]
True, sorry
