### ISSUE TITLE
Using Android SDK 1.49.1, switching between front and back, the 3D model cannot be rendered.

### ISSUE THREAD

**Issue by dennyson-w** [google/filament#7442]
**Describe the bug**
Using Android SDK 1.49.1, switching between front and back, the 3D model cannot be rendered.

**Smartphone (please complete the following information):**
 - Device: 22041211AC
 - OS: Android 12

**Additional context**

https://github.com/google/filament/assets/7814811/6ae4038b-3764-4492-ab71-84d135c449fd

**Comment by romainguy** [comment]
The issue has been fixed already and will be part of the next update.
