### ISSUE TITLE
Support for 3d texture and volume rendering

### ISSUE THREAD

**Issue by DeckardZ46** [google/filament#7446]
Hi, we're trying to use filament as a rendering engine for an interactive scene, while we found there's only sampler2dArray supported in _Filament Materials Guide_ , that may cause some problems when rendering volume data because sampler2DArray is different from sampler3D, it may replace sampler3D in some cases but not all the situations are applicable, that troubled us when we wanted to create a customed .mat file to do some SDF rendering in fragment shader.
Is there any further plan for supporting volume data and SDF rendering stuffs? really looking forward to that.

**Comment by romainguy** [comment]
3D textures are supported, just use the sampler3d type.

**Comment by DeckardZ46** [comment]
> 3D textures are supported, just use the sampler3d type.

Got it, thanks
