### ISSUE TITLE
Rendering failed when turn off AntiAlias

### ISSUE THREAD

**Issue by DeckardZ46** [google/filament#7447]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I turned off FXAA using
`view->setAntiAliasing(filament::AntiAliasing::NONE)` 
and the view just turned into all black.

But if turn off FXAA and open MSAA instead, the view will rendered correctly

**To Reproduce**
1. When initializing a view, after engine->createView(), use above code to turn off default anti alias
2. And the view will turn into all black, rendering failed
3. After turning off default FXAA, turn on MSAA using
   `view->setMultiSampleAntiAliasingOptions(MultiSampleAntiAliasingOptions{  
.enabled = true,  
.customResolve = false,  
.sampleCount = 2});`   

4. the view will rendered correctly

**Expected behavior**
all the AntiAliasing closed while the view rendered correctly as it should be

**Screenshots**
when turn off all antialiasing method it's just all black, so there's no need for screenshots

**Logs**
there were no error occured

**Smartphone (please complete the following information):**
- OS: Android 12
 - GPU: Andreno 650
 - Backend: OpenGL

**Comment by pixelflinger** [comment]
I am not able to reproduce this problem. Please provide more detailed steps.
Which app did you use? Can you reproduce with our gltf-viewer sampler. Can you reproduce on the emulator or another device.
