### ISSUE TITLE
Namespacing in cmgen

### ISSUE THREAD

**Issue by MiiBond** [google/filament#746]
While integrating cmgen source into our glTF exporter for Adobe Dimension, I had issues with namespacing. Since cmgen isn't under its own namespace, I was getting collisions with the `math::` namespace and our own `math::` namespace.

**Comment by prideout** [comment]
Interesting, I assume it would also be useful to you if cmgen were a library rather than an executable?

**Comment by prideout** [comment]
We are considering nesting the `image`, `math`, and `utils` namespaces under `filament`.  They would still exist as independent libraries, this would be naming change only.
