### ISSUE TITLE
iOS View::Pick() cannot obtain the node info of gltf

### ISSUE THREAD

**Issue by machelel** [google/filament#7462]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
using View::Pick() method
iOS cannot obtain gltf nodes, but Android can directly obtain model nodes.

**To Reproduce**
1. In the Filament render method,
2. The calling method is as follows：
    self.filaEngine.view->pick(80, 80, [&self](View::PickingQueryResult const& result) {
        const char* name = self.filaAsset.asset->getName(result.renderable);
    }); 
3.  PickingQueryResult returns empty

**Expected behavior**
1. iOS can return correct results like Android
2. Does iOS not support this kind of call?

**Screenshots**
![image](https://github.com/google/filament/assets/145533933/80434cad-a815-467d-8498-eb9ed306cf9c)

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by bejado** [comment]
Picking works on iOS, but you have to be careful to convert UIKit coordinates into Filament's. See [my PR](https://github.com/google/filament/pull/7464) for example usage on iOS, in particular, [this code](https://github.com/google/filament/pull/7464/files#diff-a799b599deb17df63574d4dce199dd61e27ef647210be063d007baa490342422R184-R190) which converts from UIKit's coordinate system to what Filament expects (respecting the bottom-left origin and `contentScaleFactor`).
