### ISSUE TITLE
Make cmgen a library

### ISSUE THREAD

**Issue by MiiBond** [google/filament#747]
It would be nice if I could build the source used by cmgen into a library that could be included in my code rather than trying to include the source directly and get it to compile. I had quite a few issues getting the source to build in our Visual Studio project because of the reliance on clang.
If I could build a .lib and then just link to it in VS, that would be ideal.

**Comment by prideout** [comment]
This is a good idea.

**Comment by pixelflinger** [comment]
I think #972 addresses this issue.
