### ISSUE TITLE
Partial shadow disappears at VSM blur case

### ISSUE THREAD

**Issue by cjlong1213** [google/filament#7480]
https://github.com/google/filament/issues/7397#issue-2017805480

**Describe the bug**
part of the shadow disappears once the blur radius is increased at VSM shadow type

**To Reproduce**
1. set the shadow type VSM
2. render the avatar model with directional light(sun)

**Expected behavior**
correct shadow when avatar with glasses

**Screenshots**
![image](https://github.com/google/filament/assets/15936033/f454e22a-51cc-4545-bdf2-4367e274015f)

**Smartphone (please complete the following information):**
 - Device: [vivo V2056A]
 - OS: [Android 10.0]

**Comment by romainguy** [comment]
64 is a large radius and for a small feature like this I'm not surprised by the result. What is the resolution of your shadow map?

**Comment by cjlong1213** [comment]
> 64 is a large radius and for a small feature like this I'm not surprised by the result. What is the resolution of your shadow map?

The resolution of shadow map is 1024.
We are going to use **VSM+post blur** to  achieve soft shadow for performance reason suggested by @pixelflinger

**Comment by pixelflinger** [comment]
Yes I think we have a bug at the edge of the shadow map.

Can you share your model?

**Comment by cjlong1213** [comment]
> Yes I think we have a bug at the edge of the shadow map.
> 
> Can you share your model?

Please find the related models in the attachment@pixelflinger
[vsm_blur.zip](https://github.com/google/filament/files/13896830/vsm_blur.zip)

**Comment by pixelflinger** [comment]
@cjlong1213 it looks like you can significantly improve things by enabling:

`ShadowOptions::Vsm::elvsm = true`
`VsmShadowOptions::highPrecision = true`

I think this problem is due to us "cheating" (for performance) by using the lower resolution and disabling one layer. This will be, unfortunately, significantly slower.
