### ISSUE TITLE
incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1

### ISSUE THREAD

**Issue by yuxinabc** [google/filament#7492]
Current configuration of my project:
kotlin_plugin_version = 1.7.20
kotlin_version = 1.7.0
Android Gradle Plugin Version = 7.4.2
Gradle Version = 7.5
jdk = 11

How can I modify the configuration to integrate the three libraries:
Com. Google. Android. Filament: filament - android: 1.49.2
Com. Google. Android. Filament: gltfio - android: 1.49.2
Com. Google. Android. Filament: filament utils - android: 1.49.2

Currently, such a setting reports the following error：
![image](https://github.com/google/filament/assets/6195253/39a9f91d-45c5-4be0-a134-412e91102997)

Or which version of filament I can integrate with my current configuration

Thanks for answering

**Comment by romainguy** [comment]
Filament uses the most recent versions of Kotlin (1.9.21). We don't support older versions.
