### ISSUE TITLE
model jitter

### ISSUE THREAD

**Issue by yuxinabc** [google/filament#7498]
Describe the bug:
When I change the height of the SurfaceView to 300dp and modify the scaleFactor in the transformToUnitCube method to: val scaleFactor = 3.5f / maxExtent, the model exhibits jitter upon loading.

To Reproduce:
Simply run the program, exit, and run it again, and the issue will occur.

Expected behavior:
The model should not jitter.

Screenshots:
[image](https://github.com/google/filament/assets/6195253/ae71e4ea-e9ce-4209-9cff-1277b83dd0cf)
[video](https://github.com/google/filament/assets/6195253/7c8febb1-58bc-4836-ba50-0251303ac0a6)

Smartphone :
Device: OnePlus 9 5g
OS: Android 13.

**Comment by romainguy** [comment]
What program? I believe this could happen if the model is loaded twice in the same position.

**Comment by yuxinabc** [comment]
The sample-gltf-viewer program ran without issues the first time, but after exiting the app and re-entering, this problem occurs.

> What program? I believe this could happen if the model is loaded twice in the same position.

The sample-gltf-viewer program ran without issues the first time, but after exiting the app and re-entering, this problem occurs.

**Comment by poweifeng** [comment]
Do you see this with the default flying drone model?  If not, can you upload the model you used here?

**Comment by yuxinabc** [comment]
> default flying drone model

default flying drone model without jitter

**Comment by yuxinabc** [comment]
This is the model I am using [test_3.glb.zip](https://github.com/google/filament/files/13971839/test_3.glb.zip)

**Comment by pixelflinger** [comment]
Do you have dynamic resolution enabled?

**Comment by yuxinabc** [comment]
> Do you have dynamic resolution enabled? This looks like the kind of artifacts you'd get with dynamic resolution. Try to disable FXAA and MSAA and enable TAA instead.

```
  /*
         * Note: The settings below are overriden when connecting to the remote UI.
         */

        // on mobile, better use lower quality color buffer
        view.renderQuality = view.renderQuality.apply {
            hdrColorBuffer = View.QualityLevel.LOW
        }

        // dynamic resolution often helps a lot
        view.dynamicResolutionOptions = view.dynamicResolutionOptions.apply {
            enabled = true
            quality = View.QualityLevel.LOW
        }

        // MSAA is needed with dynamic resolution MEDIUM
        view.multiSampleAntiAliasingOptions = view.multiSampleAntiAliasingOptions.apply {
            enabled = false
        }

        // FXAA is pretty cheap and helps a lot
        view.antiAliasing = View.AntiAliasing.NONE

        // 启用 TAA
        view.temporalAntiAliasingOptions.enabled = true

        // ambient occlusion is the cheapest effect that adds a lot of quality
        view.ambientOcclusionOptions = view.ambientOcclusionOptions.apply {
            enabled = true
        }

        // bloom is pretty expensive but adds a fair amount of realism
        view.bloomOptions = view.bloomOptions.apply {
            enabled = true
        }
```
This setting will still jitter unless dynamic resolution is turned off

**Comment by pixelflinger** [comment]
yes, it is expected, unfortunately. Our best dynamic resolution option is based on FSR1 and it relies on a very well anti-aliased image. Your model has a lot of geometric high-frequency, and there is not much that can be done with the current upscaling tech.
