### ISSUE TITLE
Setting emissiveFactor results in abnormal display

### ISSUE THREAD

**Issue by yuxinabc** [google/filament#7509]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
When I set the emissiveFactor for the model, the model's self-illumination disappeared

**To Reproduce**
1. Loading a self-illuminating model.
2.  Setting the emissive intensity separately is effective.
3.  Setting both emissive color and intensity simultaneously.

**Expected behavior**
Setting the emissive color displays normally.

**Screenshots**

[Setting the emissive intensity](https://github.com/google/filament/assets/6195253/4e391a01-f17f-4c4b-89ce-13b4f97ba426)

[Setting the emissive color and intensity](https://github.com/google/filament/assets/6195253/ac592dfa-e4b2-4319-9655-028bc7104eba)

[light_1.glb.zip](https://github.com/google/filament/files/13987689/light_1.glb.zip)

**code**
```kotlin
private fun setLightBeadColor(
        materialInstance: MaterialInstance,
        red: Float,
        green: Float,
        blue: Float,
        alpha: Float
    ) {
        // Setting the color of the emissive light
        materialInstance.setParameter(
            "emissiveFactor", Colors.RgbaType.LINEAR, 1.0f, 0f, 0f,1f)
       // Setting the emissive intensity.
        materialInstance.setParameter("emissiveStrength",1f)
    }
```

**Smartphone (please complete the following information):**
 - Device: [OnePlus 9 5g]
 - OS: [Android 13]

**Comment by romainguy** [comment]
`emissiveFactor` is a `float3`, not a `float4`. The alpha value — for glTF — must be set to `0.0f` (see the filament materials documentation for an explanation of what the alpha channel means for emissive colors).

**Comment by yuxinabc** [comment]
> `emissiveFactor` is a `float3`, not a `float4`. The alpha value — for glTF — must be set to `0.0f` (see the filament materials documentation for an explanation of what the alpha channel means for emissive colors).

![image](https://github.com/google/filament/assets/6195253/ce24256b-3043-46cc-bf59-be49736a2ec4)
Setting the alpha to 0 doesn't work
The following setting is effective:
```
materialInstance.setParameter(
    "emissiveFactor", Colors.RgbaType.LINEAR, 1.0f, 0f, 0f, 8f)
```

**Comment by romainguy** [comment]
Please read about what the exposure weight means.

**Comment by yuxinabc** [comment]
> emissiveFactor

Thank you for your answer, but I still haven't found a way to make emissiveFactor effective by setting alpha=0.0

**Comment by romainguy** [comment]
What's your goal? If you set the weight to 0, the `emissiveFactor` color will look the same no matter what the camera exposure settings are. If your goal is make it bloom, you'll need to use the `emissiveStrength` to give it a higher value.
