### ISSUE TITLE
'transmission' : no such field in structure 'material'

### ISSUE THREAD

**Issue by yuxinabc** [google/filament#7519]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
Question 1：When executing the command ./matc -p mobile -a opengl -o tm.filamat tm.mat, **the error :'transmission' : no such field in structure 'material'** ; The matc version is 49.
Question 2：If I remove 'transmission', the compilation is successful, but when I adjust the 'roughness' value from 0 to 1, there is no change in the effect. However, adjusting the transparency does make a difference. What could be the reason for this?

**To Reproduce**
1. Writing a mat file
```
material {
    name : TransparentMaterial,
    shadingModel : lit,
    blending : transparent,
    transparency : twoPassesOneSide,
    doubleSided : false,
    depthWrite : false,
    parameters : [
        {
            type : "float3",
            name : "baseColor"
        },
        {
            type : "float",
            name : "roughness"
        },
        {
            type : "float",
            name : "ior"
        },
        {
            type : "float",
            name : "alpha"
        }
    ],
}
fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor.rgb = materialParams.baseColor; 
        material.baseColor.a = materialParams.alpha;
        material.roughness = materialParams.roughness;
        material.metallic = 0.0;
        material.ior = materialParams.ior; 
        material.reflectance = 0.5;
        material.transmission = 0.75;
    }
}
```
2. executing the command ./matc -p mobile -a opengl -o tm.filamat tm.mat

**Expected behavior**
No error

**Comment by romainguy** [comment]
Per the documentation, you need to choose a refraction mode:

https://google.github.io/filament/Materials.html#materialmodels/litmodel/transmission

**Comment by yuxinabc** [comment]
Thank you for your answer, I understand now.
