### ISSUE TITLE
Point light  is not effective

### ISSUE THREAD

**Issue by wddl** [google/filament#7536]
**Describe the bug**
Some point light has been set in the GLTF file, but there is no lighting effect in the rendering。But, in some other glTF files, the same point light  settings have an effect.  All point light settings is same。

**To Reproduce**
1. Load gltf file
2. View the point light effect

**Expected behavior**
The point light  is rendered correctly

**Screenshots**
this is gltf file that is not correctly：
![image](https://github.com/google/filament/assets/26518625/c46e97e7-aa29-46d1-a256-17ff1fc4bd0d)
this is gltf file that is correctly：
![image](https://github.com/google/filament/assets/26518625/65fbd9ff-2c4f-4e28-a9d6-e21629775fb4)

**Logs**

**Desktop (please complete the following information):**
 - OS: win11
 - GPU: [ NVIDIA GTX 2060]
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: [Android]

**Additional context**
This is a glTF file that is not displayed correctly：
[lululemon2.zip](https://github.com/google/filament/files/14098429/lululemon2.zip)
Thsi is a gltf file this is displayed  correctly:
[hshl1.zip](https://github.com/google/filament/files/14098971/hshl1.zip)

**Comment by pixelflinger** [comment]
I am not able to reproduce this problem:
![llulemon](https://github.com/google/filament/assets/1240896/6acd0001-0f5e-4b03-a334-8e0625198811)

**Comment by romainguy** [comment]
Works for me too

**Comment by wddl** [comment]
@pixelflinger @romainguy Thanks for reply！
@pixelflinger In your example, the camera aperture is set to 2.845 and the camera ISO is set to 800. However, in my example, the camera aperture and camera ISO are set to their default values of 16 and 100 respectively. The issue is that even with the same default camera settings and the same point light parameter settings in my example, why different glTF files exhibit different effects？Please refer to the another attached glTF file for comparison. Thanks！
![image](https://github.com/google/filament/assets/26518625/3667353f-6524-40f6-a55e-d47d0d25d1fd)

**Comment by pixelflinger** [comment]
I also didn't see that problem. With the default settings, the other gltf didn't show the lights either, because the camera settings were too dark.

In my tests I saw the same behavior with both gltf.

**Comment by wddl** [comment]
> I also didn't see that problem. With the default settings, the other gltf didn't show the lights either, because the camera settings were too dark.
> 
> In my tests I saw the same behavior with both gltf.

@pixelflinger In the another gltf .The lighting effect of the file after setting the following parameters is as follows. It can be seen that this gltf clearly has a lighting effect. Is your example the same?
![image](https://github.com/google/filament/assets/26518625/b57bc170-1cf0-4a42-81bc-335f015ca7b3)

**Comment by pixelflinger** [comment]
Yeah okay, this happens because gltf_viewer resizes the model to fit a 1x1 cube by default (unless you use the -s option). Because the two models don't have the same initial size, the models are resized by a different factor.

Unfortunately, this resizing doesn't affect the the light radius nor the light intensity.

So as you can imagine the same light source placed in a room size environment, vs, a model/toy size environment will not produce the same result.

To see the actual effect of a light as intended by the gltf model, you need to use the `-s` option.
