### ISSUE TITLE
Thread-safe CommandStream

### ISSUE THREAD

**Issue by vincentdchan** [google/filament#7544]
**Is your feature request related to a problem? Please describe.**
I am developing a game with filament. I need to create entity in multi-thread enviroment
and render in main thread. But the following segment of code blocks:

`filament/backend/include/private/backend/CommandStream.h`
```cpp
inline void* allocateCommand(size_t size) {
        assert_invariant(utils::ThreadUtils::isThisThread(mThreadId));
        return mCurrentBuffer.allocate(size);
    }
```

**Describe the solution you'd like**
Can we remove this assertion and make CommandStream thread safe?

**Describe alternatives you've considered**
No

**OS and backend**
MacOS

**Comment by romainguy** [comment]
Making the command stream thread safe isn't enough, all Filament APIs would have to be thread safe but that's not something we plan on doing.

**Comment by vincentdchan** [comment]
I don't think all the APIs should be thread-safe.
I think making all the `::build()` and `::destroy()` APIs thread-safe is enough.

**Comment by romainguy** [comment]
I don't think it would make sense for only some APIs to be thread-safe. It might be convenient for your use case, but it wouldn't be very consistent in terms of APIs. In addition this would require quite a bit of the internals to become thread-safe.

**Comment by vincentdchan** [comment]
@romainguy If there is no plan for thread-safe API. Would it be better to remove this assertion. I can add mutex in my app but this line of code assert the thread-id, which blocks multi-thread env.
