### ISSUE TITLE
Test shaders with Amber

### ISSUE THREAD

**Issue by andreperezmaselco** [google/filament#7546]
Use the [Amber](https://github.com/google/amber) shader test framework.
Instead of testing backend shaders in `.cpp` files, we could test them in isolated `.amber` files.
I believe that with this the backend shaders could be tested more rigorously and in a more orderly way.

**Comment by romainguy** [comment]
Can you expand a little bit on your request please?

**Comment by andreperezmaselco** [comment]
> Can you expand a little bit on your request please?

Done.

**Comment by pixelflinger** [comment]
No sure what problem this would solve.
