### ISSUE TITLE
Add the exposure fusion algorithm to tone map HDR scenes

### ISSUE THREAD

**Issue by andreperezmaselco** [google/filament#7548]
The [exposure fusion algorithm](https://www.tommertens.com/exposure_fusion) uses different exposures of the scene to compress the dynamic range.

**Comment by romainguy** [comment]
I already looked into this and other similar techniques but they don’t make sense for our use case. Rendering the scene multiple times would be expensive and… unnecessary since we don’t have the limitations of camera sensors.

**Comment by andreperezmaselco** [comment]
I was thinking about using it for static rendering.

**Comment by romainguy** [comment]
Right but that’s still unnecessary since we can produce and store more dynamic range than a camera (good consumer cameras can capture about 15 stops of DR, we can hold 30 stops without any changes, and we could go well beyond that with fp32 render targets).
