### ISSUE TITLE
Make shaders more dynamic

### ISSUE THREAD

**Issue by andreperezmaselco** [google/filament#7554]
Some parameters defined through macros could be uniform variables.
This way, the shaders would be more dynamic, avoiding recompiling them when reconfiguring the parameters.

**Comment by romainguy** [comment]
Which parameters are you talking about? We explicitly used variants to optimize shaders for mobile usage and reduce register pressure, etc.

**Comment by andreperezmaselco** [comment]
`BRDF`, `BLEND_MODE`, `FILAMENT_QUALITY`, etc.

Sure.
I mean there could be a dynamic option.
Macros continue for static cases targeting performance.

**Comment by romainguy** [comment]
That's already the case.

**Comment by andreperezmaselco** [comment]
It's not the case.
You will need to recompile the shaders.

**Comment by romainguy** [comment]
Macros are already used for static cases targeting performance. We will not offer each macro with a uniform alternative. There is little benefit and it would add a lot of complexity.
