### ISSUE TITLE
iOS 17.3 Filament render crash

### ISSUE THREAD

**Issue by machelel** [google/filament#7555]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
IOS 17.3 execution of Filament render method, crash occurred, non mandatory, crash message

**To Reproduce**
1. load resources
2. Filment starts executing the beginframe and render methods

**Expected behavior**

**Screenshots**
![image](https://github.com/google/filament/assets/145533933/a0f9898b-42ff-41eb-a6f8-d4d29e3b9eab)

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by pixelflinger** [comment]
There is nothing actionable here for us. Please provide more info and repro steps.
