### ISSUE TITLE
does filament support desktop app using Kotlin Multiplatform Mobile

### ISSUE THREAD

**Issue by M-R-007** [google/filament#7558]
I am facing issue when tried to use filament libraries in desktop app using KMM  composeApp desktopMain . have anyone used  it 
<img width="818" alt="image" src="https://github.com/google/filament/assets/144330704/e11e60db-3617-4d5a-ad45-b800e19b0803">
<img width="446" alt="image" src="https://github.com/google/filament/assets/144330704/4f47e3ca-9c11-459e-8690-3aa7685bc8e6">
<img width="501" alt="image" src="https://github.com/google/filament/assets/144330704/5c5ae4cf-190a-4bad-80d6-dbcdf99d6ca7">

**Comment by romainguy** [comment]
The Filament Android library is written in Java and is therefore not compatible with KMP.
