### ISSUE TITLE
Mobile render models tend to heat up

### ISSUE THREAD

**Issue by yuxinabc** [google/filament#7578]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
While rendering the model, the temperature continued to rise, with an increase of about 5 degrees within 10 minutes; I have tried my best to optimize the model size, and I have used `gltf-pipeline -i test.gltf -o test.gltf -d -s --keep-unused-elements` to optimize the model. Currently, the model size is only 85kb (gltf+bin), but the overheating issue has not improved.

**To Reproduce**
1. Replace `scene.gltf` with `test.gltf`, then run the `samples.sample-gltf-viewer` demo.
2. Continuously monitor the temperature changes of the phone

**Expected behavior**
The phone does not overheat.

**Smartphone (please complete the following information):**
 - Device: OnePlus 9  5g
 - OS: Android 13

**Additional context**
[model.zip](https://github.com/google/filament/files/14321436/model.zip)

**Comment by romainguy** [comment]
Reduce the rendering resolution, turn on dynamic resolution, reduce effects quality or turn them off, etc. Filament provides many APIs for this.

**Comment by yuxinabc** [comment]
> Reduce the rendering resolution, turn on dynamic resolution, reduce effects quality or turn them off, etc. Filament provides many APIs for this.



> Reduce the rendering resolution, turn on dynamic resolution, reduce effects quality or turn them off, etc. Filament provides many APIs for this.

However, with the same code, when I load scene.gltf, there is no overheating issue. When I open scene.gltf with Blender software, it gives an error. Are there other aspects of my model that need to be optimized?
