### ISSUE TITLE
Vulkan GPU Memory Leak and Crash

### ISSUE THREAD

**Issue by Nolram12345** [google/filament#7579]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
On Windows, when using Vulkan, on some GLTF scenes GPU memory usage increases constantly during execution, leading the application to crash due to running out of memory.

**To Reproduce**
1. Download the following scene as GLB file from sketchfab:
[Test Asset by Pixel](https://sketchfab.com/3d-models/medieval-fantasy-book-06d5a80a04fc4c5ab552759e9a97d91a)
2. Launch gltf_viewer.exe
3. Observe the application run out of memory and crash.

**Expected behavior**
The application memory should stay constant when no new data is created, and should not run out of memory and crash.

**Screenshots**
As seen in Task Manager:
![image](https://github.com/google/filament/assets/37701550/754f5bfc-d1ab-4aad-a655-fa7a7260b4d1)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - GPU: NVIDIA RTX 4080 OC
 - Backend: Vulkan

**Comment by Nolram12345** [comment]
In my brief testing, this issue does not seem to happen on the OpenGL backend.

**Comment by Nolram12345** [comment]
Any updates on this? Has this issue been reproduced?

**Comment by Nolram12345** [comment]
I'm still able to reproduce this issue in v1.50.4 - any updates?

**Comment by poweifeng** [comment]
Sorry for the delay.  I'll try to repro this week.  It's likely that I'll address this in an upcoming refactor, but it might take a little while more.

**Comment by jeanlemotan** [comment]
This might not be the case anymore after the Vulkan refactor, but last time I checked the pipeline cache, it was using the render target pointer or texture as a key, and if recreating the render target per frame the cache will invalidate per frame, causing it to grow a lot. I think a better option would be to use the RT/Texture descriptors (formats) instead as key, not the pointers directly.

**Comment by Nolram12345** [comment]
Is there any ETA for a fix for this problem? It's proving to be a massive issue in production.

**Comment by poweifeng** [comment]
Still in progress.  No hard ETA unfortunately, but I expect some result in these two weeks.

**Comment by Nolram12345** [comment]
This seems be resolved in the latest version - at least on my hardware!
Might be worth looking into further, but I think I can close this issue for now.

**Comment by poweifeng** [comment]
hmm, interesting.  So the cause might be this: https://github.com/google/filament/commit/d05c61fe9a982035caecfea179896b4111fb28f3

Thanks for the update!

**Comment by Nolram12345** [comment]
Might have been! It's definitely worth further testing. I'll keep my eye on future releases and re-open the issue if it comes up again.
