### ISSUE TITLE
Failed to asynchronously prepare wasm only on Safari browser

### ISSUE THREAD

**Issue by nestarz** [google/filament#758]
Hello I'm trying to make filament works in Safari, as it works both in Firefox and Chrome but I face this issue:

`
[Warning] failed to asynchronously prepare wasm: TypeError: undefined is not an object (evaluating 'Filament.ctx.getExtension') (filament.js, line 6)
`

`
Unhandled Promise Rejection: abort({"line":6,"column":299119,"sourceURL":"http://localhost:8000/html/filaments/filament-20190123-web/docs/filament.js"}). Build with -s ASSERTIONS=1 for more info.
`

To reproduce the issue, just copy the last release of filament (Sceneform 1.7-pr3 filament-20190123-web.tgz), put it on a server and start a demo file like demo_redball.html. 

Safari Version 12.0.2 (14606.3.4) on macOS Mojave 10.14.2 (18C54)

**Comment by prideout** [comment]
Filament requires WebGL 2.0, which only has "experimental" status in Safari 12 and must be enabled in the developer menu.

This particular error may be unrelated to WebGL, but we are generally not supporting Safari at the moment so we'll likely need to close this issue.
