### ISSUE TITLE
Chrome Version 122.0.6261.70 fails to initialize Filament

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#7598]
The recent Chrome browser update to version 122.0.6261.70 is causing Filament to fail to initialize.  It apparently cannot find the JS WebAssembly bindings.  I don't know if this is a Chrome failure or a problem with the bindings.  Previous versions of Chrome work without problem.

Chrome reports this error:
```
Uncaught (in promise) RuntimeError: null function or function signature mismatch
    at filament.wasm:0xbdc84
    at filament.wasm:0x16647b
    at filament.wasm:0x14ee7a
    at filament.wasm:0x259c2
    at Function.Engine$_create [as _create] (eval at new_ (filament.js:9:85911), <anonymous>:7:10)
    at Filament.Engine.create (filament.js:460:40)
    at CrashFilament.html:10:33
    at taskFinished (filament.js:78:17)
    at filament.js:102:9

```
**To Reproduce**
Open this HTML file in a http server:
```
<html>
    <head>
    </head>
    <body>
        <canvas></canvas>
        <script src="//unpkg.com/filament@1.49.2/filament.js"></script>
        <script src="//unpkg.com/gl-matrix@2.8.1/dist/gl-matrix-min.js"></script>
        <script>
            Filament.init([], () => {
                Filament.Engine.create(document.getElementsByTagName('canvas')[0]);
            })
        </script>
    </body>
</html>
```

Linking to this discussion, where I initially saw the issue:  #7595

**Comment by poweifeng** [comment]
I can repro this after the chrome update.  I'll do a quick investigation.

**Comment by BStringhamVRSK** [comment]
Thanks for looking into it.  We have an active online product that is essentially blocked by this, so we appreciate any help you can offer.

**Comment by poweifeng** [comment]
This is actually a known issue that was addressed in v1.49.3, the commit is 27fa8ab46d5c320d6576aefd3cf26e57b42debd4

So I think the solution is just to update to Filament v1.49.3

**Comment by BStringhamVRSK** [comment]
Thank you.  We will give that a try.

**Comment by atcha** [comment]
> Thank you. We will give that a try. UPDATE: We updated to 1.50.3 and that resolved the issue.

How did you update ? I can't find the package in npm.

**Comment by BStringhamVRSK** [comment]
> > Thank you. We will give that a try. UPDATE: We updated to 1.50.3 and that resolved the issue.
> 
> How did you update ? I can't find the package in npm.

I'm not sure why only some updates get posted on npm, but we download the .tgz archive file from the releases page, so we don't rely on that.
