### ISSUE TITLE
The blending mode rendering effect of the material is incorrect

### ISSUE THREAD

**Issue by wddl** [google/filament#7618]
**Describe the bug**
My custom material code is as follows：
 `filament::math::float2 QUAD_VERTICES_T[4] = {
	{-2, -2},
	{2 , -2},
	{2 , 2},
	{-2 , 2}
};
uint16_t QUAD_INDICES_T[6] = { 0, 1, 2 ,0 , 2 , 3 };
void GussianSplat::setup(Engine* engine, View* view, Scene* scene)
{
	filament::math::mat4f clipTran;
	clipTran[0] = { 0.25 , 0 , 0 , 0 };
	clipTran[1] = { 0 , 0.25 , 0  , 0 };
	clipTran[2] = { 0 , 0 , 0 ,0 };
	clipTran[3] = { 0 , 0 , 0  ,1 };
	MaterialBuilder::init();
	MaterialBuilder builder;
	builder.depthCulling(false);
	builder.blending(MaterialBuilder::BlendingMode::TRANSPARENT);
	builder.shading(MaterialBuilder::Shading::UNLIT);
	builder.instanced(true);
	builder.vertexDomain(MaterialBuilder::VertexDomain::DEVICE);
	builder.parameter("clipTran", MaterialBuilder::UniformType::MAT4);
	builder.variable(MaterialBuilder::Variable::CUSTOM0, "vColor");
	builder.variable(MaterialBuilder::Variable::CUSTOM1, "vPosition");
	std::string vertexShader = R"SHADER(
		void materialVertex(inout MaterialVertexInputs material) {
			material.vPosition = getPosition();	
			material.clipSpaceTransform = materialParams.clipTran;					
			material.vColor = vec4(1.0 , 0.0 , 0.0 , 1.0);			

		}
	)SHADER";

	std::string fragmentShader = R"SHADER(
		void material(inout MaterialInputs material) {			
			prepareMaterial(material);			
			float A = -dot(variable_vPosition, variable_vPosition);
			if (A < -4.0) discard;
			float B = exp(A) * variable_vColor.a;
			material.baseColor = vec4(B * variable_vColor.rgb, B);			
		}
	)SHADER";

	builder.materialVertex(vertexShader.c_str());
	builder.material(fragmentShader.c_str());
	Package const pkg = builder.build(engine->getJobSystem());
	filament::Material* pMat = Material::Builder().package(pkg.getData(), pkg.getSize()).build(*engine);
	pMat->getDefaultInstance()->setParameter("clipTran", clipTran);
	VertexBuffer* pVb = VertexBuffer::Builder()
		.vertexCount(4)
		.bufferCount(1)
		.attribute(VertexAttribute::POSITION, 0, VertexBuffer::AttributeType::FLOAT2, 0, 8)
		.build(*engine);
	pVb->setBufferAt(*engine, 0,
		VertexBuffer::BufferDescriptor(QUAD_VERTICES_T, 32, nullptr));
	IndexBuffer* pIb = IndexBuffer::Builder()
		.indexCount(6)
		.bufferType(IndexBuffer::IndexType::USHORT)
		.build(*engine);
	pIb->setBuffer(*engine,
		IndexBuffer::BufferDescriptor(QUAD_INDICES_T, 12, nullptr));
	Entity entity = EntityManager::get().create();
	RenderableManager::Builder(1)
		.boundingBox({ { -10, -10, -10 }, { 10, 10, 10 } })
		.material(0, pMat->getDefaultInstance())
		.geometry(0, RenderableManager::PrimitiveType::TRIANGLES, pVb, pIb, 0, 6)
		.instances(1)
		.culling(false)
		.receiveShadows(false)
		.castShadows(false)
		.build(*engine, entity);
	scene->addEntity(entity);
}`
When the blending mode is set to TRANSPARENT。The draw ellipse is flickering, and the effect is as follows：
![image](https://github.com/google/filament/assets/26518625/0bc4593f-0855-4ee4-9206-a05c454fcb72)
When the blending mode is set to OPAQUE。The drawing effect is correct，as follow:
![image](https://github.com/google/filament/assets/26518625/429e9b27-0efc-4dad-9bf8-498ff920de70)
I need to have the correct drawing effect with blending mode enabled. If I use OpenGL directly, the effect is correct as shown in Figure 2

**To Reproduce**
1. Load the code and run to view

**Expected behavior**
The above code have the correct effect when blending is enabled

**Screenshots**

**Logs**

**Desktop (please complete the following information):**
 - OS: [win11]
 - GPU: [gtx 2060]
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: [android]

**Additional context**

**Comment by pixelflinger** [comment]
I think the problem is that you're not clearing the background. You must have either a skybox or set the ClearOption in Renderer.
