### ISSUE TITLE
The maximum number of instances for drawing is restricted

### ISSUE THREAD

**Issue by wddl** [google/filament#7621]
**Is your feature request related to a problem? Please describe.**
"RenderableManager::Builder.instances() function"。the maximum number of instances allowed is 32767。Why is there this limitation, and what should I do if I need to render a larger number of point clouds?

**Describe the solution you'd like**
How to render point cloud data with more than 32767 instances?

**Describe alternatives you've considered**

**OS and backend**

**Comment by romainguy** [comment]
Are you trying to render more than 32k *points*? If so it's not instancing you should be using, but a renderable with all the vertices you need.

**Comment by wddl** [comment]
> Are you trying to render more than 32k _points_? If so it's not instancing you should be using, but a renderable with all the vertices you need.
@romainguy thanks to reply！
I am try to render point cloud data for Gaussian splatting, and the point count for these models exceeds 32676. When using OpenGL directly, the glDrawArraysInstanced function allows for drawing a larger number of instances. In this algorithm for rendering point clouds, the position of each instance is calculated in the shader code, requiring drawing in the manner of glDrawArraysInstanced. Is there a way to lift the limitation?

**Comment by pixelflinger** [comment]
if that's what you want to do, you will have to use multiple Renderables. The limit to 32767 cannot be changed currently.

**Comment by wddl** [comment]
@pixelflinger Thank you very much! I konw
