### ISSUE TITLE
libfilamat_combined.a":   No such file or directory.

### ISSUE THREAD

**Issue by Edanaw** [google/filament#7623]
windows x64 compile android platform library error：
CMake Error at libs/filamat/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "E:/2024-02-28-15-48-09-filament-v1.50.4/filament-1.50.4/out/cmake-android-release-aarch64/libs/filamat/libfilamat_combined.a":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:227 (include)

FAILED: CMakeFiles/install.util
cmd.exe /C "cd /D E:\2024-02-28-15-48-09-filament-v1.50.4\filament-1.50.4\out\cmake-android-release-aarch64 && D:\android-sdk_r24.4.1-windows\android-sdk-windows\cmake\3.22.1\bin\cmake.exe -P cmake_install.cmake"
ninja: build stopped: subcommand failed.

**Comment by Edanaw** [comment]
all module have .a library but don't have  "_combined.a" library

**Comment by pixelflinger** [comment]
our windows build is green. Not sure what the ask is here.
