### ISSUE TITLE
How to use the skinning apis ?

### ISSUE THREAD

**Issue by sohanjg** [google/filament#764]
Trying to use the skinning setBones api. Even though the uniforms are invalidated, and makeBones invoked. The model doesnt show-up :/

In FRenderableManager::create we make setSkinning as true, and mSkinningBoneCount as 4.
Any other configs which needs to be set ? Are there any samples to refer ?

The model is the simple skin in khronos. https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_019_SimpleSkin.md

Thanks.

**Comment by prideout** [comment]
In your vertex buffer, are you including VertexAttribute::BONE_INDICES and VertexAttribute::BONE_WEIGHTS?

I'm interested in creating a skinning sample but haven't gotten around to it yet.

**Comment by sohanjg** [comment]
Yes, we are setting that too,
        vertexBufferBuilder.attribute(VertexAttribute::BONE_INDICES, 4, VertexBuffer::AttributeType::UINT);
        vertexBufferBuilder.attribute(VertexAttribute::BONE_WEIGHTS, 5, VertexBuffer::AttributeType::FLOAT4); etc.

and the related handling. Anything else ?

**Comment by prideout** [comment]
That particular glTF model uses a component type of UNSIGNED_SHORT (5123) for the joints accessor, so maybe use USHORT4 instead of UINT for BONE_INDICES?

**Comment by sohanjg** [comment]
Just while checking, this came up, 
In glTF2Importer when we import animation the code seems to set the aiNodeanim based on joints, 
https://github.com/google/filament/blob/master/third_party/libassimp/code/glTF2Importer.cpp 
whereas in https://github.com/assimp/assimp/blob/master/code/glTF2Importer.cpp we do it based on samplers ? any reasons ? or just assimp versions ?

**Comment by prideout** [comment]
We probably need to update our version of assimp.  By the way, we're actually interested in transitioning away from assimp for our glTF sample code, in favor of a more lightweight library.

**Comment by sohanjg** [comment]
I see, thanks for the info. 
Just to confirm if i am using the setBones api in the right way, heres the snippet from the anim callback in gltf viewer.

for (auto renderable : g_meshSet->getRenderables()) {
            if (engine->getRenderableManager().hasComponent(renderable)) {
    	     for (uint i = 0 ; i < transforms.size() ; i++) {
                    engine->getRenderableManager().setBones(engine->getRenderableManager().getInstance(renderable), reinterpret_cast<mat4f const*>(&transforms[i]), 2, i);
                 }
            }
         }
  }
Will this be okay ? Or we need to setup a separate Renderable for the Bone Instance ?

**Comment by prideout** [comment]
We have a buffer overrun on our side (see above fix) but I also think you should not be passing "2" for your boneCount since you're setting only 1 at a time.  (The confusion might be coming from the fact that your model has 2 bone indices, but that's a per-vertex thing, not a per-renderable thing.)

**Comment by kimkulling** [comment]
HI,

read this and just want to let you know: you do not have to build the whole assimp-lib if you only want to use glTF2. I could prepare a pull request for you to optimize the size of the lib.

Kim

**Comment by romainguy** [comment]
Thanks for the offer. We already don't build all of Assimp, but it still remains a large library.

**Comment by prideout** [comment]
@sohanjg you might want to check for GL errors by using a debug variant of Filament or by removing lines 34-36 in GLUtils.h

The reason I'm suggesting that is that we see GL errors with skinning with the WebGL platform, you might be running into the same issue on your platform.

**Comment by prideout** [comment]
The skinning issue we see with WebGL is an INVALID_OPERATION due to an incorrect UBO size, you *might* be running into the same thing.  Let us know if you see GL errors per my previous comment.

**Comment by sohanjg** [comment]
prideout@, sorry was afk. Thanks a lot for the skinning demo.
Regarding the UBO size, we were not getting the INVALID_OP in linux (thats where we are working now, but need to check once we move to mobile drivers).
We were finally able to get something on screen, we found via RenderDoc that mesh_bone_indices and mesh_bone_weights were all 0's. Some how the vectors are not properly setting up the uniform buffer :/

**Comment by prideout** [comment]
@sohanjg , just to be clear, are you still running into issues with Filament itself after pulling #773?

**Comment by sohanjg** [comment]
Yes, the problem still exists. We were not facing the driver invalid op problem in linux.
Our problem seems to be the way assimp loads the bone info into the uniform Buffer.

**Comment by sohanjg** [comment]
Ok, looks like we got it working now, may not be 100% yet. Atleast for the simple skin.
With the bone info being initialized into the uniform, the setBones seems to be working all right.
We didnt need the UBO size patch though, atleast for Linux.

**Comment by sohanjg** [comment]
@prideout thanks for all your help in this. 
But seem like we cant make this work with higher bone count, we are seeing crippled "cesium man" :/
I have gisted our changes (and the output) in MeshAssimp here, https://gist.github.com/sohanjg/567855d3c914efe2f8e22d5d684405bb
Rest of the code is primarily based on http://ogldev.atspace.co.uk/www/tutorial38/tutorial38.html 

If you have time, would you please have a look, and let us know where we are going wrong.
We suspect its the matrices, but cant find what can be wrong.
Can, the way we do ProcessNode (position update, bounding box etc.) in MeshAssimp have some influence ?
Thanks.

**Comment by prideout** [comment]
The gist calls a `processSkinning` function but I don't see where it's defined.  I wonder if the `inverseBindMatrices` in the glTF file are being honored?

As a side note, we are actively working on a new lightweight glTF importer that does not use assimp.

**Comment by 0sakuh0** [comment]
"sohanjg" went to a trip, but I try to answer instead. "processSkinning" is very simple function that calls LoadBones (tutorial38) for each mesh. After inspecting the "simpleskin" that you were using in the animation example it seems possible that assimp is loading the inverseBindMatrices somehow wrong.

We get for bone 1 {1,0,0,0,  0,1,0,1,  0,0,1,0,   0,0,0,1} and I think it should be {1,0,0,-0.5,   0,1,0,-1,  0,0,1,0, 0,0,0,1}.

Also sum of some bone weights for "cesium man" is far below 1.

Do you think the inverseBindMatrix above is loaded wrong? I think we need to reprogram this in better way but I'm worried about assimp...
