### ISSUE TITLE
iOS 17.1.2  render error use Metal

### ISSUE THREAD

**Issue by xiamingwei-sudo** [google/filament#7649]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
Rendering error using metal, but rendering successfully using OPENGL

**To Reproduce**
same code and same texture, when use metal , render error, but use opengl render success. and if ios under ios 17, use ios 14 or 16, metal also  render success. only ios 17 render error. 
Hope to get a solution！！ thanks。

**Expected behavior**

**Screenshots**
use metal render error:
<img width="419" alt="iShot_2024-03-25_14 41 57" src="https://github.com/google/filament/assets/9984670/287c14f0-2452-40ea-8b86-4c2ed40a4c97">

use opengl or use under ios 17, render success:
<img width="406" alt="iShot_2024-03-25_14 42 11" src="https://github.com/google/filament/assets/9984670/21d8fbef-5bbd-4094-8703-063181bd9ee2">

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - OS: mac os 14.3.1
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: iphone 12
 - OS: 17.1.2

**Additional context**

**Comment by bejado** [comment]
What's the rendering error you're seeing? Is it this part of the model?

![Screenshot 2024-03-12 at 10 06 22 AM](https://github.com/google/filament/assets/5298046/fdec3bdd-2302-4b13-b96d-effe2f09c83a)

Is it a glTF model? How are you loading the model -- through our gltfio library? If you could provide the model or a way to reproduce the issue that would be helpful.

**Comment by xiamingwei-sudo** [comment]
thanks, when i update filament 1.50.2, there have no this issure.
then , I will hide the key information in this question for confidentiality reasons
