### ISSUE TITLE
The clipSpaceTransform matrix cannot fully transform the vertex position

### ISSUE THREAD

**Issue by wddl** [google/filament#7657]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I need to set gl_Position in the vertex shader. A workaround is to set the material.clipSpaceTransform matrix in the device domain. However, this matrix cannot affect the z component of the vertex; it can only transform x and y.

**To Reproduce**
1. set material use device domain
2. set the material.clipSpaceTransform matirx,but the matrix cannot affact  the z component of the vertex

**Expected behavior**
The material.clipSpaceTransform matirx can affect  the z component of the vertex

**Screenshots**

**Logs**

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - GPU: [ ]
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: [Android]

**Additional context**

**Comment by romainguy** [comment]
clip space transform can affect the Z component. In the device domain you can also use the world from clip transform matrix for this.
