### ISSUE TITLE
Some GLTF files do not render on Vulkan

### ISSUE THREAD

**Issue by Nolram12345** [google/filament#7674]
**Describe the bug**
Some GLTF and especially GLB model files cause intense glitches when rendered with Filament on the Vulkan backend.
This happens on a variety of GLB/GLTF models (about 25% of models tested).

**To Reproduce**
1. Download this example GLB by James Phan: [Sketchfab Link](https://sketchfab.com/3d-models/subway-car-abc21eee368448a4884376ef1fc444fa#download)
2. Load the model into filament's GLTF viewer. The HDRI is irrelevant, but in my testing I used [this free HDRI from PolyHaven](https://polyhaven.com/a/industrial_sunset_puresky).

**Expected behavior**
The model should render correctly, as it does on the OpenGL backend.

**Screenshots**
Here is the visual output on Vulkan:
![image](https://github.com/google/filament/assets/37701550/efa8a4a0-19d5-4281-ada4-0c1899f4f50c)

For reference, here is the exact same GLB loaded up in OpenGL:
![image](https://github.com/google/filament/assets/37701550/d5eadb38-2ba3-42bb-977f-c41bd55b4ab9)

**Logs**
The logs do not show anything extraordinary.
```
FEngine (64 bits) created at 000001C3D410F9F0 (threading is enabled)
Vulkan device driver: NVIDIA 551.61
Selected physical device 'NVIDIA GeForce RTX 4080' from 1 physical devices. (vendor 0x10de, device 0x2704, driver 0x89cf4000, api 1.3)
Backend feature level: 1
FEngine feature level: 1
vkCreateSwapchain: 1024x640, 44, 0, swapchain-size=3, identity-transform=true, depth=130
vkCreateSwapchain: 1920x1017, 44, 0, swapchain-size=3, identity-transform=true, depth=130
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - GPU: NVIDIA RTX 4080 OC
 - Backend: Vulkan
 
 **Extra notes**
 According to the Khronos GLTF validator, the model file is indeed a valid GLTF/GLB file without errors.

**Comment by romainguy** [comment]
I can reproduce on macOS with MoltenVK (except it just renders black). GL and Metal work fine.

**Comment by Nolram12345** [comment]
Any updates on this, such as diagnosis etc. would be much appreciated, as we are currently running into this problem in production quite a lot.

**Comment by poweifeng** [comment]
will take a look

**Comment by Nolram12345** [comment]
From my brief testing, I'm suspecting it may be related to transparency.

**Comment by poweifeng** [comment]
I'm able to repo as well.  Turning off MSAA made it go away, might serve as a temporary workaround.

**Comment by Nolram12345** [comment]
Just tried this on AMD, the issue does not occur there.
Also VRAM consumption on AMD with Vulkan is **MUCH** lower!
