### ISSUE TITLE
`TransparencyMode::TWO_PASSES_ONE_SIDE` showing back face for certain asset

### ISSUE THREAD

**Issue by hannojg** [google/filament#7688]
**Describe the bug**

I can see the back side / back face of an asset which uses "Alpha blend", although I configured `TransparencyMode::TWO_PASSES_ONE_SIDE` and the asset only is made out of one single mesh.

**To Reproduce**

1. Get the asset [coin.glb.txt](https://github.com/google/filament/files/14672645/coin.glb.txt)
2. Rename `coin.glb.txt` to `coin.glb`
3. Import the glb in blender:
![Screenshot 2024-03-20 at 22 04 43](https://github.com/google/filament/assets/16821682/83d9f1bc-3425-4449-ab13-5cbabf9c7c4f)
4. You see that it uses opaque blend mode. Change it to "alpha blend":
![Screenshot 2024-03-20 at 22 04 51](https://github.com/google/filament/assets/16821682/0d7ed20c-a272-4d88-bca7-ac89284b6fc3)
5. You may see the backface in blender as well. Uncheck the "Show backface" option
> [!NOTE]
> Interestingly setting this option doesn't change anything of the material specification in the gltf json file when exporting the asset with "show backface" activated vs deactivated. So either gltf isn't supporting it, or it's not an option that applies to the material / model but just to the rendering pipeline?
6. Now the coin should look correct in blender, export the glb:
![Screenshot 2024-03-20 at 22 04 56](https://github.com/google/filament/assets/16821682/0df2b015-82d6-4640-b884-3a3a56f08e13)
7. Import the model in Filament. You should get a similar result as shown in step (5), where you can see the backface (See screenshots below).
8. Consulting the documentation setting the transparency mode of all materials to `TransparencyMode::TWO_PASSES_ONE_SIDE` should fix the issue. However it doesn't for this asset, the render output stays the same.

Note: I verified that the code setting `TransparencyMode::TWO_PASSES_ONE_SIDE`  works, because it works for other assets. It just doesn't seem to work for this asset.
I checked the normals of the asset, and they look good to me.

**Expected behavior**

I expected the coin to show without the back face shining through (especially since alpha is set to value 1), as seen in image step (6). 

**Screenshots**

<table>
<tr>
 <td>
  **Expected**
 <td>
 <td>
  **Actual**
 <td>
<tr>
 <td>
<img src="https://github.com/google/filament/assets/16821682/9e355264-d60a-40a4-92ab-36f0a40b6697" />
 <td>
 <td>
<img src="https://github.com/google/filament/assets/16821682/ff2d1111-adf3-47f3-b1ea-f121986088df" />
 <td>
</table>

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

No logs.

**Desktop (please complete the following information):**
 - OS: MacOS
 - GPU: Apple M2 Pro
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - OS: 14

**Additional context**

Also happens on iOS

**Comment by romainguy** [comment]
I don't know how you modified Filament for this, but it works just fine when I use twoPassesOneSide. You probably modified Filament/gltiof in the wrong spot. Here it is with an alpha of 0.5:

<img width="1136" alt="Screenshot 2024-03-20 at 3 54 19 PM" src="https://github.com/google/filament/assets/869684/96c87ab6-d1c2-4cb2-9c68-cee45e258ca4">

(note that if your object is double sided, gltfio uses twoPassesTwoSides automatically).

**Comment by hannojg** [comment]
@romainguy I rendered it in the iOS gltf-viewer application, set doubleSided to false and transparency mode to `TransparencyMode::TWO_PASSES_ONE_SIDE`. Ifi t helps I can provide a branch with a full reproduction?

![Screenshot 2024-03-21 at 10 22 39](https://github.com/google/filament/assets/16821682/1b23b383-0bd8-4fa3-afa2-94e5a0d39e7e)

**Comment by romainguy** [comment]
It works when I do what you are doing in `gltf_viewer.cpp`, make sure there's no asynchronous loading happening. BTW you don't need to set the material instance again on the renderable primitive.

**Comment by hannojg** [comment]
Hm, I have not modified any other code than the one shown. If it's not asking too much do you mind trying again with this glb?

[coin_alpha.glb.txt](https://github.com/google/filament/files/14704310/coin_alpha.glb.txt)

This is the one I exported from blender with alpha blend, and its not working on iOS / android for me 🤔

**Comment by romainguy** [comment]
Using your asset, with the code changes shown below:
<img width="1136" alt="Screenshot 2024-03-21 at 9 38 15 AM" src="https://github.com/google/filament/assets/869684/d44da8b8-c658-4088-a292-79120fb0ce8f">

`gltf_viewer.cpp`
```c++
        RenderableManager const& rcm = app.engine->getRenderableManager();
        Slice<Entity> const renderables{
                app.asset->getRenderableEntities(), app.asset->getRenderableEntityCount() };
        for (Entity const e: renderables) {
            auto ri = rcm.getInstance(e);
            size_t const c = rcm.getPrimitiveCount(ri);
            for (size_t i = 0; i < c; i++) {
                MaterialInstance* const mi = rcm.getMaterialInstanceAt(ri, i);
                mi->setDoubleSided(false);
                mi->setTransparencyMode(MaterialInstance::TransparencyMode::TWO_PASSES_ONE_SIDE);
                Material* ma = const_cast<Material *>(mi->getMaterial());
                materials.insert(ma);
            }
        }
```

**Comment by hannojg** [comment]
![Screenshot 2024-03-21 at 19 15 44](https://github.com/google/filament/assets/16821682/bd05a3e0-55fc-414b-a1e5-f3ca678d2e3f)

Hm, so weird, I am on the latest changes, added exactly your changes but it's still broken. 

Is there any other way how I could check what's different between your and my environment?

**Comment by hannojg** [comment]
Ah wait I am so sorry, I ran the gltf_viewer app from the wrong directory!

I was on an older commit (a few weeks old). And on the latest main its actually working correctly 🥳 !

**Comment by hannojg** [comment]
Sorry for the early excitement @romainguy when I use the ubershader its showing the coin incorrectly:

![Screenshot 2024-03-21 at 19 39 05](https://github.com/google/filament/assets/16821682/2a0318ff-63cd-4ca4-a6a4-0a007c243fda)

**Comment by romainguy** [comment]
This feature is not handled by the material itself, so it doesn't matter whether it's the Uber shader or not.

**Comment by hannojg** [comment]
Are you able to reproduce the difference on your end using the -u parameter ?

To me it appears I get two different outputs depending on which material provider used:

<table>
<tr>
 <td>
  Enable ubershaders
 <td>
 </td>
  Disable ubershaders
 </td>
<tr>
 <td>

![Screenshot 2024-03-21 at 19 55 54](https://github.com/google/filament/assets/16821682/71f6f220-2b5a-4691-ab6a-4894b1b14b06)

</td>
 <td>
   
![Screenshot 2024-03-21 at 19 55 43](https://github.com/google/filament/assets/16821682/7b91a393-b24b-420e-b9ac-e61a0e59bb23)

 </td>
</table>
