### ISSUE TITLE
Are there any plans to support gltf extensions in 3dtiles 2.0?

### ISSUE THREAD

**Issue by ZhangGuangXin** [google/filament#7698]
I am currently implementing a 3D gis engine with filament for 3D rendering, this 3D gis engine needs to support gltf extensions in 3dtiles 2.0, such as: EXT_mesh_features, EXT_structural_metadata, EXT_instance_features. I wonder if the filament team has any plans to develop these gltf extensions?

**Comment by pixelflinger** [comment]
No such plans at this time.
