### ISSUE TITLE
core dumped gltf_viewer

### ISSUE THREAD

**Issue by HalanoSiblee** [google/filament#7708]
**Describe the bug**
executing gltf_viewer binary show window for second then close with _Aborted (core dumped)_

**To Reproduce**
1. Download [filament-v1.51.0-linux.tgz](https://github.com/google/filament/releases/download/v1.51.0/filament-v1.51.0-linux.tgz
)
2. Run gltf_viewer

**Expected behavior**
no crash or dependencies conflict 

**Logs**
```
[halano@archlinux bin]$ ./gltf_viewer
FEngine (64 bits) created at 0x57b7d8d90db0 (threading is enabled)
N5utils18PostconditionPanicE
in enumerate:79
reason: enumerate size error
#0      gltf_viewer                         0x57b7d5f717c0 (null) + 96447080372160
#1      gltf_viewer                         0x57b7d5eca2a2 (null) + 96447079686818
#2      gltf_viewer                         0x57b7d5e6b99b (null) + 96447079299483
#3      gltf_viewer                         0x57b7d5e6f45c (null) + 96447079314524
#4      libc.so.6                           0x7f5d4a5e955a (null) + 140038656398682


libc++abi: terminating with uncaught exception of type utils::PostconditionPanic
Aborted (core dumped)

```
**Desktop:**
 - OS: [Linux]
 - GPU: [NVS 315]
 - Backend: [OpenGL]

**Comment by pixelflinger** [comment]
@poweifeng "enumerate size error" is logged by the Vulkan backend.

**Comment by HalanoSiblee** [comment]
> @poweifeng "enumerate size error" is logged by the Vulkan backend.

oh btw my gpu doesn't support vulkan how do I use opengl backend ?

**Comment by romainguy** [comment]
@HalanoSiblee You can pass `-a opengl` to `gltf_viewer` to choose the GL backend.

**Comment by HalanoSiblee** [comment]
> @HalanoSiblee You can pass `-a opengl` to `gltf_viewer` to choose the GL backend.

you guys should document that,anyways thanks it works <3
![image](https://github.com/google/filament/assets/70325026/c260f234-23dc-44c3-87b1-7f1df8408873)

**Comment by romainguy** [comment]
It should be documented if you `--help` any of the samples, including `gltf_viewer`.
