### ISSUE TITLE
Detect clicked node of  GLTF model

### ISSUE THREAD

**Issue by lalit-iottive** [google/filament#7738]
Hi,

I have used GLTF model which shows the human body. I want to detect which part of model is clicked on single tap like hand, leg, back, etc. In short I want to fetch clicked child node name from model.

I have attached a model file and screenshot of model.

OS:Android

[man.zip](https://github.com/google/filament/files/14901733/man.zip)

![Screenshot_20240408_114614](https://github.com/google/filament/assets/98161227/c8956ccb-93d3-484e-b48d-b8468db90ff8)

**Comment by poweifeng** [comment]
Let's use the similar discussion topic for follow-up: https://github.com/google/filament/discussions/7745
