### ISSUE TITLE
Filament rendering is inconsistent with OpenGL

### ISSUE THREAD

**Issue by wddl** [google/filament#7742]
**Describe the bug**
As shown in the images below, the first image is rendered using OpenGL, while the second image is rendered using Filament. There are some differences between the two results. However, the shader code inputs are completely identical. The code is also provided below. May I ask why this is the case?
![opengl-render](https://github.com/google/filament/assets/26518625/e53eeb91-8abc-4247-a992-ef03ed435e2b)
![filament-render](https://github.com/google/filament/assets/26518625/23b387a6-428b-439b-bc2d-d70dcc5d3155)
[filament-code.txt](https://github.com/google/filament/files/14892311/filament-code.txt)
[opengl-code.txt](https://github.com/google/filament/files/14892312/opengl-code.txt)

**To Reproduce**

**Expected behavior**
The rendering is consistent with OpenGL

**Screenshots**

**Logs**

**Desktop (please complete the following information):**
 - OS: [windows11]
 - GPU: [GTX 2060]
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: [Android ]

**Additional context**

**Comment by romainguy** [comment]
Filament has post processing my default, including color grading. Filament will also work in linear sRGB which you may or may not be doing.
