### ISSUE TITLE
Is it possible to define transparency for an entity?

### ISSUE THREAD

**Issue by obeletski** [google/filament#777]
We would like loaded model gradually to appear in the scene by animating it transparency level over the time. What would be the best way to achieve that in Filament? 

Modifying material(s) to have transparency enabled is not a good option could expose inner parts of the model that is not visible otherwise.

**Comment by romainguy** [comment]
We have a special blend mode called "fade" for that very purpose. You can also use the transparency property and set it to twoPassesOneSide.

**Comment by obeletski** [comment]
I have been experimenting with "fade" blending mode. Unfortunately that is not what we are looking for. Similar to the transparent blending it will expose part of the model that are not visible in the opaque mode.That can be seen in material_sandbox for monkey model if you turn the head so that one ear is behind the head. Switching blending modes will make that ear visible.

We are looking for something that is close to normal opaque rendering and then applying alpha value for rendered results before compositing with the rest of the scene entities.

**Comment by romainguy** [comment]
Right which is why I mentioned the "transparency" property. Set it to "twoPassesOneSide". You can see pictures showing what it does in the materials documentation.

**Comment by obeletski** [comment]
The twoPassesOneSide value actually helped us to get the effect we were looking for, Thanks!

We have couple of more questions:

What is the performance impact (battery usage, frame rate) of different blending mode? Does transparency and twoPassesOneSide property contributes  potentially to higher power consumption?

Other question, while animating alpha value we are using now non opaque blending mode (transparent or fade) for materials that originally were designed as opaque. After animation is done we continue using blending in transparent mode but alpha is set to 1 to get rid of transparency. Do you foresee any problems with that approach (artifacts,  power usage...)? We can also change implementation that would recreate renderable  with opaque materials after animation if that is needed.

**Comment by romainguy** [comment]
Transparency is more expensive yes, particularly if you have multiple transparent objects in front of each other.

Using a transparent material with an opacity of 1 has effectively the same cost as using an opacity < 1. You won't (shouldn't :) get artifacts but it's more expensive. Note that you can swap material without creating a new renderable (see RenderableManager::setMaterialInstanceAt).
