### ISSUE TITLE
glTF-Sample-Models AnimatedMorphSphere seems wrong

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#7787]
```
gltf_viewer -u -a opengl ../shallow/glTF-Sample-Models/2.0/AnimatedMorphSphere/glTF/AnimatedMorphSphere.gltf     
```

at some point during the animation the sphere looks like the screenshot below:

![Screenshot 2024-04-22 at 15 05 52](https://github.com/google/filament/assets/1240896/14adaee8-6ff8-4bf9-a696-d96c67cb0d5f)

**Comment by poweifeng** [comment]
surprisingly, this seems like it's WAI: https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/AnimatedMorphSphere
