### ISSUE TITLE
Filament Android Samples - Blank Screen

### ISSUE THREAD

**Issue by Raki** [google/filament#780]
**The bug**
"textured-object" android sample is giving blank screen as output on Nexus 7 Tablet and Nexus 5 Mobile while it is working fine on other devices (Xiaomi Note 4, Samsung S6 edge, Samsung Tab S3)

**To Reproduce**
1. Add filament-20190131-android.aar module to 'textured-object' android sample
2. Build and run the app

**Expected behavior**
 shader_ball.obj should be loaded with pbr effects

**Screenshots**
![screenshot_20190205-124451](https://user-images.githubusercontent.com/824691/52258176-134f7480-2944-11e9-9b5b-25ccb895bfeb.png)

**Smartphone :**
 - Devices: Nexus 5 Mobile, Nexus 7 Tablet
 - OS: 6.01.

**Comment by Raki** [comment]
I didn't see any errors in the Logcat. I'm pasting what ever the messages in the verbose

02-05 13:12:57.357 15929-15929/? I/art: Late-enabling -Xcheck:jni
02-05 13:12:57.409 15929-15929/com.google.android.filament.textured W/ActivityThread: Application com.google.android.filament.textured is waiting for the debugger on port 8100...
02-05 13:12:57.420 15929-15929/com.google.android.filament.textured I/System.out: Sending WAIT chunk
02-05 13:12:57.577 15929-15935/com.google.android.filament.textured I/art: Debugger is active
02-05 13:12:57.624 15929-15929/com.google.android.filament.textured I/System.out: Debugger has connected
02-05 13:12:57.625 15929-15929/com.google.android.filament.textured I/System.out: waiting for debugger to settle...
02-05 13:12:57.825 15929-15929/com.google.android.filament.textured I/System.out: waiting for debugger to settle...
02-05 13:12:58.025 15929-15929/com.google.android.filament.textured I/System.out: waiting for debugger to settle...
02-05 13:12:58.225 15929-15929/com.google.android.filament.textured I/System.out: waiting for debugger to settle...
02-05 13:12:58.427 15929-15929/com.google.android.filament.textured I/System.out: waiting for debugger to settle...
02-05 13:12:58.627 15929-15929/com.google.android.filament.textured I/System.out: waiting for debugger to settle...
02-05 13:12:58.828 15929-15929/com.google.android.filament.textured I/System.out: waiting for debugger to settle...
02-05 13:12:59.028 15929-15929/com.google.android.filament.textured I/System.out: debugger has settled (1336)
02-05 13:12:59.126 15929-15929/com.google.android.filament.textured I/Filament: FEngine (32 bits) created at 0xa1a40000 (threading is enabled)
02-05 13:12:59.131 15929-15972/com.google.android.filament.textured D/Filament: FEngine resolved backend: OpenGL
02-05 13:12:59.132 15929-15972/com.google.android.filament.textured I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
02-05 13:12:59.546 15929-15980/com.google.android.filament.textured D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-05 13:12:59.592 15929-15980/com.google.android.filament.textured I/OpenGLRenderer: Initialized EGL, version 1.4

**Comment by Raki** [comment]
While debugging i found that,
the blank screen was displaying on Nexus device due to , `renderer.beginFrame(swapChain)` is constantly returning `false`. 

But if we keep break point in `doFrame `method and continue for a couple of frames, I am getting some weird output like the following

![screenshot_20190214-145630](https://user-images.githubusercontent.com/824691/52777489-f44e9200-3069-11e9-90fc-079c993a6ca5.png)


with the following error on the logCat : 

E/Filament: LINKING: --From Vertex Shader:
    --From Fragment Shader:
    Internal error.

**Comment by romainguy** [comment]
This looks like we're running into driver bugs. Unfortunately we do not have Nexus 7 and Nexus 5 devices to reproduce the issue.

**Comment by Raki** [comment]
@romainguy  Can we expect that this bug will be resolved soon ?

**Comment by romainguy** [comment]
I can't promise anything. Like I said we don't have devices to reproduce this issue and given how old these devices are we won't prioritize them over newer devices that also have issues.

**Comment by Raki** [comment]
Thank you @romainguy , that makes sense. :-)

**Comment by Raki** [comment]
Hi @romainguy , we are planning to include filament engine into our Android app. On most of the devices filament works so great. But it is not working properly on Nexus 5 and Nexus 7 devices as we knew and not sure on how many other devices this behavior is there.

So we tried to do a test to validate working of filament, but with no luck as the test case is giving random results.

So I am requesting you to point us to any code segment in filament that will help us achieve this.

Thank you.

**Comment by romainguy** [comment]
Hi @Raki, the main place where things might go wrong would be `OpenGLDriver.cpp`. Given that it's device specific it's very likely a driver bug. You might be able to find a workaround. The weird output from your last screenshot would be due to a missing clear or a background that's not being drawn (not sure if your test app has a skybox for instance). We avoid clearing on tilers but it could be that it's broken on those devices (we use `glInvalidateFramebuffer` to inform the GPU we're not clearing). It might be as simple as forcing a clear.
