### ISSUE TITLE
Automatically update vertex normals when morphing

### ISSUE THREAD

**Issue by cjlong1213** [google/filament#7876]
![normal222](https://github.com/google/filament/assets/15936033/54062e6e-16f9-451d-bde1-7cab753753f8)

**Is your feature request related to a problem? Please describe.**
As far as I know, the Filament would not update vertex normal(tangent) when morphing animation, it only calculate the normal at first loading, the dynamic normal can make more effect at avatar emoticon animation

**Describe the solution you'd like**
A API or solution which can update vertex normal at morphing

**Describe alternatives you've considered**
/

**OS and backend**
Android OpenGLES

Any suggestion? Thanks in advance.

**Comment by pixelflinger** [comment]
I don't understand the problem. Filament *does* update the normals when morphing if they are supplied in the MorphTargetBuffer.
