### ISSUE TITLE
After increasing CONFIG_MAX_BONE_COUNT ,the loading of the model crashes

### ISSUE THREAD

**Issue by wuyongxiang** [google/filament#7882]
I need to load a relatively complex GLB model, but its number of bones is greater than 256, about 400+. 
In the original state, the model cannot be displayed.

So I looked up the [issue](https://github.com/google/filament/issues/5785) and modified 

from:
constexpr size_t PROFIG-MAX-BONE.COUNT = 256;

to:
constexpr size_t PROFIG-MAX-BONE.COUNT = 512;

And  rebuild Filament. After loading the model again, a crash occurred **in Android**, Log display: 

Link error in "transmission_undershader":
L0005 Max uniform block size exceeded
“

What do I need to do to display this model?
[klee_f.zip](https://github.com/google/filament/files/15430489/klee_f.zip)
or
[bailu.zip](https://github.com/google/filament/files/15493050/bailu.zip)

**Comment by wuyongxiang** [comment]
> I need to load a relatively complex GLB model, but its number of bones is greater than 256, about 400+. In the original state, the model cannot be displayed.
> 
> So I looked up the issue and modified
> 
> constexpr size_t PROFIG-MAX-BONE.COUNT to 512; constexpr size_t CONFIG_MAX_MORPH_TARGET_COUNT = 512; constexpr size_t CONFIG_MINSPEC_UBO_SIZE = 32768;
> 
> After loading the model again, a crash occurred, Log display:
> 
> Link error in "transmission_undershader": L0005 Max uniform block size exceeded “
> 
> What do I need to do to display this model?
 [klee_f.zip](https://github.com/google/filament/files/15430489/klee_f.zip) 

The version used is 1.52.0

**Comment by romainguy** [comment]
> L0005 Max uniform block size exceeded

Your device doesn't support UBOs large enough to store that many bones. The limit of 256 was chosen to work across all Android devices. If you want to support more bones across more devices it would require changing how bones are stored and implemented in Filament, using textures for instance (which would have other issues).
