### ISSUE TITLE
Fix for normal generation does not work for UBERSHADER in gltf_viewer app

### ISSUE THREAD

**Issue by mbalajee** [google/filament#7905]
**Describe the bug**
[Fix](https://github.com/google/filament/pull/7776) for proper normal generation does not work for UBSERSHADER.  [This](https://github.com/google/filament/discussions/7851#discussioncomment-9441128) suggestion works for JITSHADER (default in gltf_viewer.cpp sample) but it doesn't work for UBERSHADER.  Reason I want this to work for ubsershader is because we want to apply the fix for Android which only has `Ubershader.java`.  Currently the [fix](https://github.com/google/filament/pull/7776) is supported only for desktop app.

Would the possible fix for Android be creating an equivalent `Jitshader.java`?  Not sure why android only has ubershader & the benefits of one over the other.  Any help to have the fix for proper normal generation in Android would be helpful.  I tried to [apply](https://github.com/google/filament/discussions/7851#discussioncomment-9463186) the fix for Android but not working

**To Reproduce**
Run the sample `gltf_viewer.cpp` app with [this](https://github.com/google/filament/discussions/7851#discussioncomment-9441128) suggested change

**Expected behavior**
Model should appear normally with UBERSHADER
<img width="1136" alt="Screenshot 2024-06-04 at 11 40 36 PM" src="https://github.com/google/filament/assets/17508872/34d3bb61-aff0-4f37-b481-2b70fef30157">

**Screenshots**
Actual behavior - Model appears all black with UBSERSHADER
<img width="1136" alt="Screenshot 2024-06-04 at 11 33 05 PM" src="https://github.com/google/filament/assets/17508872/43847128-670d-4c7b-8c75-d1a553a24300">

**Logs**
Model:  [walls.glb.zip](https://github.com/user-attachments/files/15572949/walls.glb.zip)

**Desktop (please complete the following information):**
 - OS: Mac (reproducible in any device)
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by pixelflinger** [comment]
I think this is a known problem of the previous fix.

**Comment by mbalajee** [comment]
> I think this is a known problem of the previous fix.

I see, haven't seen any mention of this being a known issue in the [PR](https://github.com/google/filament/pull/7776) description or anywhere in the code.  I was also [suggested](https://github.com/google/filament/discussions/7851#discussioncomment-9453369) to make some changes in Asset/Resource loader to make use of the desktop fix in Android so I thought this must be a bug

Also would it make sense to use JITSHADER in Android ?

**Comment by poweifeng** [comment]
You mentioned that it's not fixed for you even with #7917?  

I just tried your asset (`walls.glb`) on a macbook, and it looks fine (but did not look fine before the commit). How are you checking the result:
 - For example, are you building from source (`git log` to check the latest commit)? 
 - What platform/device are you testing on?

**Comment by poweifeng** [comment]
Here's some notes of what I did

I added the following to `samples/gltf_viewer.cpp`
```
diff --git a/samples/gltf_viewer.cpp b/samples/gltf_viewer.cpp
index 6b83316f1..4472cf948 100644
--- a/samples/gltf_viewer.cpp
+++ b/samples/gltf_viewer.cpp
@@ -747,7 +747,10 @@ int main(int argc, char** argv) {
                 createJitShaderProvider(engine, OPTIMIZE_MATERIALS) :
                 createUbershaderProvider(engine, UBERARCHIVE_DEFAULT_DATA, UBERARCHIVE_DEFAULT_SIZE);
 
-        app.assetLoader = AssetLoader::create({engine, app.materials, app.names });
+        AssetConfigurationExtended ext {""};
+        AssetConfiguration config = {engine, app.materials, app.names };
+        config.ext = &ext;
+        app.assetLoader = AssetLoader::create(config);
         app.mainCamera = &view->getCamera();
         if (filename.isEmpty()) {
             app.asset = app.assetLoader->createAsset(
```

I ran it with
```
./out/cmake-debug/samples/gltf_viewer -u walls.glb
```
The result is

![image](https://github.com/google/filament/assets/48371888/4c399c37-7814-4df7-9a99-0f9dfda475cc)

**Comment by mbalajee** [comment]
Clean build worked.  Also I modified `AssetConfigurationExtended::isSupported()` to allow Android and it works on Android too (model appears as expected)
