### ISSUE TITLE
Khronos Neutral tone mapper

### ISSUE THREAD

**Issue by shashwatsinha92** [google/filament#7907]
**Is your feature request related to a problem? Please describe.**
I am trying to use the new Khronos neutral tone mapper (https://www.khronos.org/news/press/khronos-pbr-neutral-tone-mapper-released-for-true-to-life-color-rendering-of-3d-products) What would be the most efficient way to use it?

**Describe the solution you'd like**
The ideal solution would be exposing it as one of the enums. Is there any other alternative I can use for now?

Thank you so much for the consideration

**Comment by romainguy** [comment]
It's already part of Filament.

**Comment by shashwatsinha92** [comment]
Ah you are absolutely right, I was on an older version. Thanks so much
