### ISSUE TITLE
compile  spirv-tools failed   use vs2019 

### ISSUE THREAD

**Issue by as010101** [google/filament#7921]
filament  code is latest release version., the error msg like this :
```
2>Generate language specific header for DebugInfo.
2>/usr/bin/python3: can't open file '/d/my_filament/filament-release/build/third_party/spirv-tools/source/D:/my_filament/filament-release/filament-release/third_party/spirv-tools/utils/generate_language_headers.py': [Errno 2] No such file or directory
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: “D:\my_filament\filament-release\build\CMakeFiles\f5b17b8c15546e24612543737b75be68\DebugInfo.h.rule;D:\my_filament\filament-release\build\CMakeFiles\89fb650eb6e9d6117e4ae00007f4db65\spirv-tools-header-DebugInfo.rule;D:\my_filament\filament-r``
```

**Comment by as010101** [comment]
> Your output looks kind of strange. Are you trying to use cygwin or similar tool to compile?

No,  I  will try it.

**Comment by as010101** [comment]
it looks like  `${spirv-tools_SOURCE_DIR}` exception, but I dont know how to set it.

**Comment by poweifeng** [comment]
Actually, cygwin and others like it (even WSL) are not officially supported, you should follow the instructions here: 
https://github.com/google/filament/blob/main/BUILDING.md#windows
https://github.com/google/filament/blob/main/android/Windows.md

**Comment by as010101** [comment]
> Actually, cygwin and others like it (even WSL) are not officially supported, you should follow the instructions here: https://github.com/google/filament/blob/main/BUILDING.md#windows https://github.com/google/filament/blob/main/android/Windows.md

Now  I dont need  Android support, and the compile step I follow this  https://github.com/google/filament/blob/main/BUILDING.md#windows ,but cant work. from the debug msg, the cmake configure and generate is done .
```
1>D:/filament_build/new1/filament/third_party/spirv-tools/source
1>-- Configuring done
1>-- Generating done
1>-- Build files have been written to: D:/filament_build/new1/build4
2>Update build-version.inc in the SPIRV-Tools build directory (if necessary).
2>/usr/bin/python3: can't open file '/d/filament_build/new1/build4/third_party/spirv-tools/source/D:/filament_build/new1/filament/third_party/spirv-tools/utils/update_build_version.py': [Errno 2] No such file or directory
```
