### ISSUE TITLE
Extended algorithm crashes the sample app

### ISSUE THREAD

**Issue by mbalajee** [google/filament#7930]
**Describe the bug**
Extended algorithm (from [this](https://github.com/google/filament/pull/7776) PR) drastically slows down the rendering.  When I [opt in](https://github.com/google/filament/discussions/7851#discussioncomment-9441128) to the extended algorithm the model which was loading fine before (if I don't opt in) takes a very very long time to load & it eventually crashes

**To Reproduce**
Follow [this](https://github.com/google/filament/discussions/7851#discussioncomment-9441128) step to opt in to extended asset loader

**Expected behavior**
There should be no difference in performance 

**Screenshots**
### Left - Opt in to extended algo | Without extended algo
https://github.com/google/filament/assets/17508872/c75adf99-f15a-47dc-85aa-0c0a70ce9fcd

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma
 - Backend: Metal

**Additional context**
Load a larger model to reproduce the degrade in performance & an eventual crash.  I couldn't attach the model here since it is sensitive but any larger model (> 8K entities) will be impacted

**Comment by poweifeng** [comment]
If you can point to a publicly available gltf with this issue, it'll help speed along the investigation. Also note that fixing any issues with the extended algo is not really prioritized at the moment since we really prefer to focus on exploring a better gltf loader overall.

**Comment by mbalajee** [comment]
> If you can point to a publicly available gltf with this issue, it'll help speed along the investigation. Also note that fixing any issues with the extended algo is not really prioritized at the moment since we really prefer to focus on exploring a better gltf loader overall.

I'll try to find some online but any glb with over 8 to 10K entities will be affected

**Comment by mbalajee** [comment]
@pixelflinger  @poweifeng In the extended asset loader, gltf buffer is [loaded for every primitive](https://github.com/google/filament/blob/3fbf3f711194d238390ff1137c7f68527c7013ed/libs/gltfio/src/extended/AssetLoaderExtended.cpp#L528) which is causing this issue.  When loaded just once, the issue is fixed.  Can we pls fix this as this is a blocker for our release ?  I can put up a PR if you would like, lemme know

@pirlande-fw
