### ISSUE TITLE
Android: GraphicBufferProducers counts keep increasing when app switches between the foreground and background

### ISSUE THREAD

**Issue by cui060417** [google/filament#7938]
**Describe the bug**
Such as: filament-gltf-viewer-v1.53.0-android.apk，(other sample apps are the same).
1. Installed in Android Phone
2. Opened the App
3. The app switches to the background, then switches back to the foreground, and repeats this cycle.

The counts of System GraphicBufferProducers keep increasing, and not reduce to the original counts.
If counts >= MaxCounts, The App will be crashed!!

    adb shell
    while true;do dumpsys SurfaceFlinger |grep GraphicBufferPro;sleep 1s;done 

**Expected behavior**
The count of GraphicBufferProducers does not increase.

**Logs**
GraphicBufferProducers: 25, max 4096
GraphicBufferProducers: 25, max 4096
GraphicBufferProducers: 25, max 4096
GraphicBufferProducers: 25, max 4096
GraphicBufferProducers: 26, max 4096
GraphicBufferProducers: 25, max 4096
GraphicBufferProducers: 27, max 4096
GraphicBufferProducers: 27, max 4096
GraphicBufferProducers: 28, max 4096
GraphicBufferProducers: 27, max 4096
GraphicBufferProducers: 30, max 4096
GraphicBufferProducers: 30, max 4096
GraphicBufferProducers: 30, max 4096
GraphicBufferProducers: 30, max 4096
GraphicBufferProducers: 30, max 4096
GraphicBufferProducers: 29, max 4096
GraphicBufferProducers: 29, max 4096
GraphicBufferProducers: 29, max 4096
GraphicBufferProducers: 31, max 4096
GraphicBufferProducers: 32, max 4096
GraphicBufferProducers: 31, max 4096
GraphicBufferProducers: 31, max 4096
GraphicBufferProducers: 31, max 4096
GraphicBufferProducers: 31, max 4096
GraphicBufferProducers: 31, max 4096
GraphicBufferProducers: 34, max 4096
GraphicBufferProducers: 34, max 4096
GraphicBufferProducers: 34, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 33, max 4096
GraphicBufferProducers: 36, max 4096
GraphicBufferProducers: 36, max 4096
GraphicBufferProducers: 35, max 4096
GraphicBufferProducers: 37, max 4096
GraphicBufferProducers: 37, max 4096
GraphicBufferProducers: 38, max 4096
GraphicBufferProducers: 37, max 4096

**Smartphone (please complete the following information):**
 - Device: phone and pad all have this issue
 - OS: Android 9.0, 10.0, 11.0

**Comment by pixelflinger** [comment]
I am not able to reproduce this. Can you give more details repro steps? How do you switch the app in the background/foreground? Do you use the Home button or the Back button?
Are you able to reproduce this in the Android Emulator?
Which specific Phone did you see it happen on?
Android 9.0 - 11.0 is very old now, does it reproduce on a more recent Android version?

**Comment by pixelflinger** [comment]
I am able to reproduce indeed with Android 11 in the Emulator.

**Comment by pixelflinger** [comment]
After some investigation, it looks like there was some GraphicBufferProducers leaks in the framework prior to Android 12. I don't think this can be fixed at the app level.

The problem persists even when the activity is destroyed; and in that case I have double-checked that we're succssfuly destroying all our EGL surfaces, contexts and calling eglTerminate() and elgReleaseThread(). Despite all that, the # buffer still increases.

**Comment by thrsmith** [comment]
@pixelflinger I just came across this issue while investigating a similar symptom in a different app I maintain, on Android 9 and 11. Do you have any references to an Android bug or AOSP changes in the framework / SurfaceFlinger relating to the leaks you mention?

Our code seems to release all the surfaces, EGL resources, etc, but we're also seeing a slow increase in GraphicBufferProducers count when the frontend part of our system is cycled between the foreground and background.

Thanks
