### ISSUE TITLE
Windows build fails with clang assertion failure

### ISSUE THREAD

**Issue by jdarpinian** [google/filament#8]
Following the build steps, when compiling sample-app.vcxproj (FilamentApp.cpp, IBL.cpp, IcoSphere.cpp, Image.cpp, and NativeWindowHelperWindows.cpp) I get a crash in clang:

Assertion failed: CXXInfo->BaseOffsets.count(Base) && "Did not find base!", file C:\src\llvm_package_336178\llvm\tools\clang\include\clang/AST/RecordLayout.h, line 225

It crashes both with the LLVM version linked in the README and the latest available.

**Comment by romainguy** [comment]
@bejado have you run into this on Windows?

The error occurs in clang's internal files, seems like a bug in the toolchain.

**Comment by bejado** [comment]
Yes, seems to be an bug in Clang. I believe I remember running into this issue on Windows when using Clang 7, so I switched to Clang 6. @jdarpinian, can you confirm which version you’re using?

**Comment by jdarpinian** [comment]
I am using 7 because that's the version recommended in the README. I will try 6 instead.

**Comment by evil84** [comment]
same problems with jdarpinian, i tried llvm6 but same.

**Comment by jdarpinian** [comment]
Clang 6 works, although it produces tens of thousands of warnings and the binaries crash because they can't find the assets directory.

**Comment by romainguy** [comment]
We'll try and fix the warnings. Issues have been reported about our Path class not working properly on Windows, that's most likely what you're running into. We'll also fix those. Thanks!
