### ISSUE TITLE
When rendering a large model (~7K individual renderables) on a mid range devices (2 to 3 years old) the performance degrades to the point it becomes unusable

### ISSUE THREAD

**Issue by mbalajee** [google/filament#8027]
When rendering a large model (~7K individual renderables) on a mid range devices (2 to 3 years old) the performance has been degraded to the point it becomes unusable.

**Affected devices:**
Samsung S6 Tab (2019)
Samsung A9+ tab (2023)
Samsung S22 Ultra (2022) - Surprised to see low performance on this device
OnePlus 6T (2018)

Have no problem on Pixel 8 & 7.  Even models with over 10K renderables perform smoothly without any dynamic resolution option.

Recording of a model with 7K renderables on Samsung S6 Tab (same result on all affected devices, worst on OnePlus) in the sample gltf viewer (modified dynamic resolution settings)
<video src="https://github.com/user-attachments/assets/0dc4eb58-c324-43ec-88ff-9fd91c110f76">

ModelView initialization,
**NOTE**:  On Pixel 8/7 I don't have to increase the memory configs, even larger models render just fine with the default config which makes me wonder if Filament increases the memory config (such as commandBufferSize) based on GPU ? 

```kotlin
 private val modelViewer: ModelViewer = ModelViewer(
     surfaceView = surfaceView,
     manipulator = cameraManipulator,
     engine = Engine.Builder().config(
         Engine.Config().apply {
             // Remember to change the configs in release/config file
             commandBufferSizeMB = 34 * 3 // to keep it 3 times larger than minCommand as per doc
             perRenderPassArenaSizeMB = 32 + 2 // keep it roughly 1MB larger per doc
             minCommandBufferSizeMB = 32
             perFrameCommandsSizeMB = 32
             driverHandleArenaSizeMB = 40
         }
     ).build()
 )
```

Dynamic resolution settings,
```kotlin
 private fun disablePostProcessing() {
     modelViewer.view.run {
        // I initially disabled post processing following the suggestion from https://github.com/google/filament/discussions/4965
        // but dynamicResolution is also part of post processing and wouldn't work if post processing is disabled.  So I disabled all set...Enabled functions in View class (only two as of now)
         // isPostProcessingEnabled = false
         setShadowingEnabled(false)
         setScreenSpaceRefractionEnabled(false)

         // on mobile, better use lower quality color buffer
         renderQuality = renderQuality.apply {
             hdrColorBuffer = View.QualityLevel.LOW
         }

         // dynamic resolution often helps a lot
         dynamicResolutionOptions = dynamicResolutionOptions.apply {
             enabled = true
             quality = View.QualityLevel.LOW
             minScale = 0.1f
             maxScale = 0.8f
             sharpness = 0.5f
         }
     }
 }
```

On Web we use XeoKit which also uses something like dynamicResolution. In addition to lowering the quality it doesn't render renderables that are far from camera & almost not visible, when interacting with the model and renders everything once we stop interacting.   Is there anything else I can do to improve performance?  Am not a graphics developer so sorry if my questions are silly 🙏 how about enabling face culling during the time of interaction or render only the entities that the camera can see (are these happening by default already ?)

_Originally posted by @mbalajee in https://github.com/google/filament/discussions/8026_

**Comment by pixelflinger** [comment]
Note that the recommended number of draw calls from *GPU Vendors* is 500 to 1000/frame and you're at 7000+; so you're way past the recommended budget. Regardless, the values you're setting for the Engine.Config are insanely high -- you don't need to go that high; this might hurt performance. Probably using 4MB minCommandBuffer should be way enough. SAme for driverHandleArenaSizeMB, 40MB is crazy. 

I think you need to be realistic about what these low-end CPU can render.

**Comment by mbalajee** [comment]
Thanks for the suggestion, yeah I wasn't sure what's the right value.  I was increasing them by 2 MB until I din't see the "mCircularBuffer.size() > requiredSize" panic.  

From a bit of a research on how to reduce the draw calls, found that occlusion culling reduces the draw calls by sending only those that are visible to the camera.  It looks like there is an [open issue](https://github.com/google/filament/issues/1201) for that. Is that still being worked on & will it help reduce the draw calls? 

In addition to the large number of renderables, we are also [opting in](https://github.com/google/filament/discussions/7851#discussioncomment-9441128) to the extended asset loader which I think duplicates (unshares) the shared vertices thereby increasing the vertex count.  This further affects the performance because of increased draw calls.
