### ISSUE TITLE
Windows ARM support request

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#8050]
We already support several platforms using Filament (Web, Windows x64, iOS, Android) and would like to add Windows ARM support to that list. Is this something that could be on the near horizon?

**Comment by pixelflinger** [comment]
What needs to happen? why is it not already "just working" ?

**Comment by BStringhamVRSK** [comment]
On Windows, we are currently consuming the release assets provided by the Filament team, which only provide an x86_64 version of the libraries.  Perhaps I am mistaken and these libraries contain binaries for both x64 and ARM processors?  I couldn't find any documented ARM support in the readme and build docs.

I will confirm this, but my understanding is that Filament fails to initialize on the ARM device tested (a MS Surface Pro 7, I believe).  I will have the device soon so I can thoroughly test and determine the precise issue.

Note: I will have more concrete details on this in the next few days, which I will provide.  If we have configured our project incorrectly, I am happy to own up to it.

**Comment by BStringhamVRSK** [comment]
@pixelflinger 
This was reported to me incorrectly.  My apologies.  Filament is working fine on the ARM hardware in question. 
I am closing this issue.
