### ISSUE TITLE
Unable to build the samples on macOS

### ISSUE THREAD

**Issue by luanbach** [google/filament#806]
**Describe the bug**
Tried to build the samples for macOS desktop by running cmake in the samples directory but got this error:
```
CMake Error at CMakeLists.txt:83 (get_resgen_vars):
  Unknown CMake command "get_resgen_vars".
```

**To Reproduce**
1. In the samples directory run: cmake .

**Expected behavior**
Build scripts for the samples to be generated.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2

**Comment by romainguy** [comment]
You cannot run CMake on the subdirectories, only in the root directory. To build a specific sample you can run make/ninja sample_name after running CMake.
