### ISSUE TITLE
Richeditor disabled on the validation fail in the tabs component

### ISSUE THREAD

**Issue by mileprogramer** [google/filament#8066]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I have a weird bug that is happening on the validation fail in the tab component, mine richeditors are disabled. I tried to solve this problem the solution is to remove function spa() then it works. I have already asked this question on the discord, github links are down below.
https://github.com/filamentphp/filament/discussions/14011
https://discord.com/channels/883083792112300104/1275429337180667945
https://discord.com/channels/883083792112300104/1275016507931492498

**To Reproduce**
1. On the first tab just do validation mistake and click save or create button.
2. Now the richeditors in the rest of the tabs are disabled

**Expected behavior**
I am expecting that richeditor is working normal, when validation error happened mine rich editors are not disabled.

**Comment by poweifeng** [comment]
I think you meant to create the issue for filamentphp: https://github.com/filamentphp/
