### ISSUE TITLE
Pre-built libraries for windows dynamic and debug (/MD, /MDd, /MTd)

### ISSUE THREAD

**Issue by huwpascoe** [google/filament#810]
**Is your feature request related to a problem? Please describe.**
The MSVCRT build version isn't included in pre-built libraries. Debug versions are also missing.
https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library

**Describe the solution you'd like**
The missing libraries provided
```
x86_64/static/filament.lib
x86_64/static/filament_d.lib
x86_64/dynamic/filament.lib
x86_64/dynamic/filament_d.lib
```
**Describe alternatives you've considered**
N/A

**OS and backend**
Windows

**Comment by romainguy** [comment]
Do you just need to know what version of MSVCRT was used? (Do we even use that? We compile with clang). Also why do you need debug libraries?

**Comment by huwpascoe** [comment]
Attempting to link with a default Visual C++ project causes this error:
```
Linking Static Library with Dynamic Library Error : LNK2038 Mismatch detected
```
Which is a problem because most if not all libraries on Windows are linked dynamically against the VC runtime as no one is going to use the exact same version in their development environment and libraries that do offer static linking, provide it as an option rather than the only choice.

/MTd and /MDd versions allows for debug builds of applications. The essential though is providing a pre-built /MD. Without it, Filament may as well have no pre-built binaries for Windows at all.

**Comment by romainguy** [comment]
A debug app can't link again a non debug library??

**Comment by bejado** [comment]
@romainguy no :(

> All modules passed to a given invocation of the linker must have been compiled with the same run-time library compiler option (/MD, /MT, /LD).

It's a really unfortunately limitation. I'd be okay with building additional Filament variants, at least `/MD` to start with. We even have a [CMake option](https://github.com/google/filament/blob/be181559961d20fcc9d435eb27ff77a09bcf36be/CMakeLists.txt#L29-L32) for this already. My only concern is that this increases CI build times, especially if we also include debug builds.

@romainguy thoughts?

**Comment by romainguy** [comment]
We only need to include those extra binaries in the post submit and release CI builds. We can keep presubmit fast.

**Comment by romainguy** [comment]
This release contains debug libraries: https://github.com/google/filament/releases/tag/sceneform-1.7pr6
