### ISSUE TITLE
Request for per-renderable post-processing enable/disable functionality

### ISSUE THREAD

**Issue by haneulkimdev** [google/filament#8116]
**Is your feature request related to a problem? Please describe.**
It seems that currently post-processing effects are applied globally to all renderables in a scene. This might be limiting in scenarios where we'd like to selectively apply post-processing to specific objects or groups of objects.

**Describe the solution you'd like**
If possible, it would be helpful to have a feature that allows enabling or disabling post-processing effects on a per-renderable basis. Perhaps this could be achieved by adding a flag or property to the Renderable component that determines whether post-processing should be applied to that specific object.

**Describe alternatives you've considered**
1. Using multiple render targets and compositing the results, but this might be more complex and potentially less performant.
2. Creating separate scenes for objects with and without post-processing, but this could complicate scene management.

**OS and backend**
This feature request isn't specific to any OS or backend, as it seems to be a core rendering functionality that shouldn't depend on platform-specific features. However, if there are any platform-specific considerations, please let me know.

**Comment by pixelflinger** [comment]
This is not feasible. 

However you can use Views do to this, since the post-process parameters are per-view.
