### ISSUE TITLE
math::mat4f::translate() -> math::mat4f::translation()?

### ISSUE THREAD

**Issue by AdrianAtGoogle** [google/filament#826]
This perfectly reasonable looking bit of code:

```
void my_fun(math::float3 position, math::quatf rotation) {
  math::mat4f view_matrix =
       math::mat4f(rotation).translate(position);
  ...
```

Doesn't do what you'd expect - `translate()` is a static method that returns a new matrix, not a member function that adds translation to an existing matrix.

Would it be possible to nounify (i.e. `translation()` instead of `translate()`) static methods like this?  My eye would catch `math::mat4f(rotation).translation(position);`

This would just be for readability - the more idiomatic version doesn't need this method anyway:
```
void my_fun(math::float3 position, math::quatf rotation) {
  math::mat3f rotation_matrix{rotation};
  math::mat4f view_matrix{rotation_matrix, position};
  ...
```

**Comment by romainguy** [comment]
@pixelflinger

That's be fine with me. We're uses to it because our math library doesn't rely on member functions really.

**Comment by pixelflinger** [comment]
I think the idea was that you could write something like:

```
auto m = mat4::rotate(...) * mat4::translate(...);
```

I think I would go further than this proposal, and rename to `mat4::makeTranslation()`, etc...

**Comment by prideout** [comment]
By the way we currently have a variant of `translate` that takes a scalar t and does a translation by t,t,t which I think is really weird, maybe we should it remove it, seems like copy-pasta from its "scale" counterpart.
