### ISSUE TITLE
[Android] Using EngineManager.create(n) method returns int array of 0-values

### ISSUE THREAD

**Issue by AbelToy** [google/filament#8278]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
Using `EntityManager.get().create(n)` to create multiple entities at once, returns an int array of size n where all values are 0.

**To Reproduce**
1. Use `EntityManager.get().create(n)`

**Expected behavior**
I would expect the entities to have non-0 values and to be created, akin to 
```
IntArray(n) {
    EntityManager.get().create()
}
```

**Screenshots**

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
Emulator

**Additional context**
N/A

**Comment by romainguy** [comment]
It's a simple fix and a dumb mistake in the code. I'll fix it.
