### ISSUE TITLE
Not able to set 3d Model background as transparent

### ISSUE THREAD

**Issue by JitendraKarma** [google/filament#8284]
I am using the `setZOrderOnTop(true) `API to make the background transparent, and it works as expected. However, my app includes a **DrawerLayout**, and when DrawerLayout open the 3D model appears on top of the it, which is not the intended behavior. To fix this, I tried setting `setZOrderOnTop(false)` when the DrawerLayout opens, but this causes the 3D model's background to turn black. How can I resolve this issue?

**Comment by romainguy** [comment]
`z-order on top` will do exactly that, move the 3D content above your UI, so what you are seeing is expected. To achieve what you want you will need to use a `TextureView` instead of a `SurfaceView`. It's the only way to proper "sandwich" 3D content between two layers of 2D content.
