### ISSUE TITLE
ktx format&type

### ISSUE THREAD

**Issue by ED-97** [google/filament#8297]
hello, 
  I have a problem ,in ktx group https://github.com/KhronosGroup/KTX-Software when ktx file'format is R11_G11_B10, the type should be this" case GL_R11F_G11F_B10F: return GL_UNSIGNED_INT_10F_11F_11F_REV;",https://github.com/KhronosGroup/KTX-Software/blob/main/lib/gl_format.h.
  but in filament,gltye is Ktx1Bundle::R11F_G11F_B10F, filament's ktx file is not standard ktx? or this is just a error?, the flament ktx file have other different from khronosGroup?
  Looking forward to your reply

**Comment by romainguy** [comment]
`Ktx1Bundle::R11F_G11_B10F` is an internal format that gets converted to `UINT_10F_11F_11F_REV` for rendering:

```
case Ktx1Bundle::R11F_G11F_B10F: return PixelDataType::UINT_10F_11F_11F_REV;
```

This follows the KTX spec.
