### ISSUE TITLE
Samples do not support 16bpc PNG textures

### ISSUE THREAD

**Issue by cdata** [google/filament#832]
**Describe the bug**
Filament uses an older version of `stb_image` that does not support 16bpc PNG loading. This results in failed texture loading for some types of models when using the `gltf_viewer` sample (and possibly others). An example of the error one will see in this case is:

> The texture /Users/.../glTF-Sample-Models/2.0/AntiqueCamera/glTF/camera_tripod_BaseColor.png could not be loaded

**To Reproduce**
 1. Build the Filament `gltf_viewer` sample
 2. View the [Khronos Antique Camera glTF model](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AntiqueCamera/glTF/AntiqueCamera.gltf) with it
 3. Note the texture loading errors reported to stdout

**Expected behavior**
The Khronos sample model should be loaded and rendered correctly by `gltf_viewer`.

**Screenshots**
Here is the result of loading the Khronos sample Antique Camera with `gltf_viewer`:

`stb_image` v2.10 | `stb_image` v2.12
-------------------|------------------
![filament-golden](https://user-images.githubusercontent.com/240083/52910487-df7e2400-324c-11e9-8dba-2e36dfa88124.png)|![filament-golden](https://user-images.githubusercontent.com/240083/52910415-fe2feb00-324b-11e9-928a-6d5b9d0ca533.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/240083/52910569-2f111f80-324e-11e9-9b64-bc30969a907f.png)

 - Backend: OpenGL

**Additional context**

Newer versions of `stb_image` have "experimental" 16bpc PNG support ([pr](https://github.com/nothings/stb/pull/225), [comment](https://github.com/socks-the-fox/stb/blob/master/stb_image.h#L150)).

**Comment by romainguy** [comment]
Thanks, we’ll update stb!
