### ISSUE TITLE
Building Filament for Android on Windows failed

### ISSUE THREAD

**Issue by 82157402** [google/filament#833]
**Describe the bug**
Building Failed Filament for Android on Windows

**To Reproduce**
 cmake  -G Ninja  -DCMAKE_CXX_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe"  -DCMAKE_C_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER:PATH="C:\Program Files\LLVM\bin\lld-link.exe"   -DCMAKE_INSTALL_PREFIX=..\release\filament -DENABLE_JAVA=NO -DCMAKE_BUILD_TYPE=Release  ..\..

![image](https://user-images.githubusercontent.com/12945580/52924299-2a8c5a00-3367-11e9-8cb3-14ad8c6ea1a0.png)

**Comment by romainguy** [comment]
According to the logs there seems to be an issue with your installation of clang.

**Comment by 82157402** [comment]
I download clang from
http://releases.llvm.org/7.0.0/LLVM-7.0.0-win64.exe
  
Window 7 64x OS.

**Comment by bejado** [comment]
Please make sure you're running the commands in an appropriate Visual Studio Command Prompt:
* VS 2015: VS2015 x64 Native Tools Command Prompt
* VS 2017: x64 Native Tools Command Prompt for VS 2017

**Comment by bejado** [comment]
Closing this for now, feel free to reopen if you still experience problems.
