### ISSUE TITLE
Spherical harmonics significantly different for 2 vs 3 bands

### ISSUE THREAD

**Issue by bejado** [google/filament#837]
**Describe the bug**
Using 2 spherical harmonics bands instead of 3 results in large visual differences.

**To Reproduce**
1. Change the [`SPHERICAL_HARMONICS_BANDS` define](https://github.com/google/filament/blob/de4abe32953d286014854dbc65b828603f97441f/shaders/src/light_indirect.fs#L14) from 3 to 2. This forces desktop to use only 2 SH bands.
2. Build `material_sandbox` for desktop.
3. Run:
```
samples/material_sandbox --api opengl --ibl=../samples/envs/pillars ../assets/models/material_sphere/material_sphere.obj
```

**Expected behavior**
The difference between 2 bands and 3 bands may be noticeable, but not this drastic.

**Screenshots**
The left image uses 2 bands, while the right uses 3:
![sh_comparison](https://user-images.githubusercontent.com/5298046/53055413-710fb080-345c-11e9-903f-3671f31aaa69.png)

Here's the same setup but with the `samples/envs/venetian_crossroads` IBL. Again, left image uses 2 bands, and the right 3:

![sh_comparison2](https://user-images.githubusercontent.com/5298046/53055920-59392c00-345e-11e9-9e05-3382dcb6f394.png)

**Comment by pixelflinger** [comment]
Unfortunately, what's happening here is that 2-bands SHs can't encode faithfully the irradiance of this environment. 3-bands and more are sufficient. 

A workaround is to use a environment with less contrast. I also found experimentally that computing the irradiance twice (i.e. filtering by the truncated cos twice), while mathematically completely wrong, gives more pleasing results in this case.

Maybe the best solution would be to let the user decide if they want to pay the cost of 3-bands in the shader on mobile.

**Comment by bejado** [comment]
Thanks for the update! Agreed that letting the user choose would be a nice feature for the future.
