### ISSUE TITLE
Cannot build the project on Linux

### ISSUE THREAD

**Issue by lukkio88** [google/filament#856]
Hello,

I've installed all the dependencies pointed out, but I've trouble building. I'm using the following command line:

`CC=/usr/bin/clang-7 CXX=/usr/bin/clang++-7 CXXFLAGS=-stdlib=libc++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release/filament -DFILAMENT_REQUIRES_CXXABI=true ../..
`

But I'm getting the error:

`[759/956] Building CXX object third_party/libassi....dir/__/code/Importer/StepFile/StepFileGen1.cpp.o
ninja: build stopped: subcommand failed`

Can you please help? The ninja version is the one you suggest to use (1.8) I don't think that's the issue.

**Comment by romainguy** [comment]
Is there more in the logs?

**Comment by prideout** [comment]
Could you attach a more complete build log?  Maybe with increased verbosity.

**Comment by lukkio88** [comment]
How do I make the output more verbose?

**Comment by prideout** [comment]
`cd out/cmake-release ; ninja -v`

**Comment by lukkio88** [comment]
Something like the following:

```
[1/186] : && /usr/bin/cmake -E remove libs/filamat/libfilamat.a && /usr/bin/ar qc libs/filamat/libfilamat.a  libs/filamat/CMakeFiles/filamat.dir/src/eiff/BlobDictionary.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/Chunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/ChunkContainer.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/DictionaryTextChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/DictionarySpirvChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/LineDictionary.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialTextChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialSpirvChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialInterfaceBlockChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/SimpleFieldChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/sca/ASTHelpers.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/sca/GLSLTools.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/shaders/CodeGenerator.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/shaders/ShaderGenerator.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/Enums.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/GLSLPostProcessor.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/MaterialBuilder.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/PostprocessMaterialBuilder.cpp.o && /usr/bin/ranlib libs/filamat/libfilamat.a && cd /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat && /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/build/linux/combine-static-libs.sh /usr/bin/ar /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat/libfilamat_combined.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/OGLCompilersDLL/libOGLCompiler.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/glslang/OSDependent/Unix/libOSDependent.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/SPIRV/libSPIRV.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-tools/source/libSPIRV-Tools.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/SPIRV/libSPVRemapper.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat/libfilamat.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/glslang/libglslang.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-core.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-glsl.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-msl.a
FAILED: libs/filamat/libfilamat.a 
: && /usr/bin/cmake -E remove libs/filamat/libfilamat.a && /usr/bin/ar qc libs/filamat/libfilamat.a  libs/filamat/CMakeFiles/filamat.dir/src/eiff/BlobDictionary.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/Chunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/ChunkContainer.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/DictionaryTextChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/DictionarySpirvChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/LineDictionary.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialTextChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialSpirvChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialInterfaceBlockChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/SimpleFieldChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/sca/ASTHelpers.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/sca/GLSLTools.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/shaders/CodeGenerator.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/shaders/ShaderGenerator.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/Enums.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/GLSLPostProcessor.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/MaterialBuilder.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/PostprocessMaterialBuilder.cpp.o && /usr/bin/ranlib libs/filamat/libfilamat.a && cd /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat && /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/build/linux/combine-static-libs.sh /usr/bin/ar /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat/libfilamat_combined.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/OGLCompilersDLL/libOGLCompiler.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/glslang/OSDependent/Unix/libOSDependent.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/SPIRV/libSPIRV.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-tools/source/libSPIRV-Tools.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/SPIRV/libSPVRemapper.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat/libfilamat.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/glslang/libglslang.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-core.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-glsl.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-msl.a
/bin/sh: 1: /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/build/linux/combine-static-libs.sh: not found
ninja: build stopped: subcommand failed.

```

**Comment by lukkio88** [comment]
By the way, everytime I run `cmake` first and then `ninja` I get kind of a different error. Now I'm getting:

`[1/188] : && /usr/bin/cmake -E remove libs/filamat/libfilamat.a && /usr/bin/ar qc libs/filamat/libfilamat.a  libs/filamat/CMakeFiles/filamat.dir/src/eiff/BlobDictionary.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/Chunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/ChunkContainer.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/DictionaryTextChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/DictionarySpirvChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/LineDictionary.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialTextChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialSpirvChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialInterfaceBlockChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/SimpleFieldChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/sca/ASTHelpers.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/sca/GLSLTools.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/shaders/CodeGenerator.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/shaders/ShaderGenerator.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/Enums.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/GLSLPostProcessor.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/MaterialBuilder.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/PostprocessMaterialBuilder.cpp.o && /usr/bin/ranlib libs/filamat/libfilamat.a && cd /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat && /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/build/linux/combine-static-libs.sh /usr/bin/ar /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat/libfilamat_combined.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/OGLCompilersDLL/libOGLCompiler.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/glslang/OSDependent/Unix/libOSDependent.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/SPIRV/libSPIRV.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-tools/source/libSPIRV-Tools.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/SPIRV/libSPVRemapper.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat/libfilamat.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/glslang/libglslang.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-core.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-glsl.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-msl.a
FAILED: libs/filamat/libfilamat.a 
: && /usr/bin/cmake -E remove libs/filamat/libfilamat.a && /usr/bin/ar qc libs/filamat/libfilamat.a  libs/filamat/CMakeFiles/filamat.dir/src/eiff/BlobDictionary.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/Chunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/ChunkContainer.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/DictionaryTextChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/DictionarySpirvChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/LineDictionary.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialTextChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialSpirvChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/MaterialInterfaceBlockChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/eiff/SimpleFieldChunk.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/sca/ASTHelpers.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/sca/GLSLTools.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/shaders/CodeGenerator.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/shaders/ShaderGenerator.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/Enums.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/GLSLPostProcessor.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/MaterialBuilder.cpp.o libs/filamat/CMakeFiles/filamat.dir/src/PostprocessMaterialBuilder.cpp.o && /usr/bin/ranlib libs/filamat/libfilamat.a && cd /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat && /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/build/linux/combine-static-libs.sh /usr/bin/ar /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat/libfilamat_combined.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/OGLCompilersDLL/libOGLCompiler.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/glslang/OSDependent/Unix/libOSDependent.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/SPIRV/libSPIRV.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-tools/source/libSPIRV-Tools.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/SPIRV/libSPVRemapper.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/libs/filamat/libfilamat.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/glslang/tnt/glslang/libglslang.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-core.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-glsl.a /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/third_party/spirv-cross/tnt/libspirv-cross-msl.a
/bin/sh: 1: /home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/build/linux/combine-static-libs.sh: not found
[2/188] /usr/bin/clang-7 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../samples/app -Isamples -O3 -DNDEBUG   -I/home/SERILOCAL/l.gagliano/Projects/simulator-assets/offline-renderer/filament/out/cmake-release/samples/generated/resources -arch x86_64 -MD -MT samples/CMakeFiles/suzanne-resources.dir/generated/resources/textures.S.o -MF samples/CMakeFiles/suzanne-resources.dir/generated/resources/textures.S.o.d -o samples/CMakeFiles/suzanne-resources.dir/generated/resources/textures.S.o -c samples/generated/resources/textures.S
clang: warning: argument unused during compilation: '-arch x86_64' [-Wunused-command-line-argument]
ninja: build stopped: subcommand failed.
`

**Comment by bejado** [comment]
It looks like the `combine-static-libs.sh` script can't be found. Can you check that it exists at

```
build/linux/combine-static-libs.sh
```

**Comment by lukkio88** [comment]
There's no build folder in the project.

**Comment by lukkio88** [comment]
Ok it built, dunno why I managed to make /build to disappear.
