### ISSUE TITLE
Add "SurfaceOrientation" class

### ISSUE THREAD

**Issue by prideout** [google/filament#858]
If there are no tangents available in the model, many glTF viewers look at UV coordinates to help generate reasonable tangents (which assimp does too, although a bit differently) however our `QuatTangentContext` struct does not include UV's.

This is a prep step for the new glTF loader that I'm working on.

As a side note, the bitangents computed by `populateTangentQuaternions` are flipped relative to what the glTF conformance suite seems to expect.

**Comment by prideout** [comment]
If we use UV's, then we'll also need positions and triangle indices to really do this correctly (sometimes known as mikktspace in honor of Morten Mikkelsen).  This is fairly different from the current implementation of `populateTangentQuaternions`, which is still useful for the case where tangents are already present in the asset.

I propose the following:

- Move the populateTangentQuats functionality from VertexBuffer into a new utils class called `SurfaceOrientation` which would have a nested Builder class for consuming normals, tangent vectors, etc.
- After construction via Builder, clients can extract quaternions from SurfaceOrientation by selecting one of three desired types (half-floats, normalized shorts, or full floats)
- Quats will be computed using the Mikkelsen method only if tangents are not present and uv's are present.

**Comment by romainguy** [comment]
SGTM

**Comment by prideout** [comment]
One side effect is that our utils lib will now have a dependency on our math lib.

**Comment by prideout** [comment]
After discussion with @pixelflinger we decided the aforementioned dependency would not be good and we've been contemplating a new "geometry" library anyway, so that's where this will go.  Not utils.

**Comment by roxlu** [comment]
Does Filament support meshes that only have `position` and `normals`?

**Comment by romainguy** [comment]
Yes it does.
