### ISSUE TITLE
gltf vertex position not as per mesh vertex.

### ISSUE THREAD

**Issue by hemantkadamata** [google/filament#860]
I am not sure of this issue fits in filament or sceneform-sdk.
Issue:  Sceneform autocenters the models and sets the y axis zero point at the bottom of it.
Do we have to manually set the vertex location for all meshes in GLTF's, to be the origin because their relative transforms are not being respected by Sceneform.

![screenshot_20190211-234534_rederingwithoutar](https://user-images.githubusercontent.com/30038341/53242299-62c6cc00-36ca-11e9-9709-2298fb0e0732.jpg)

**Comment by romainguy** [comment]
That would be a Sceneform issue. Looks like centering is done per mesh instead of for the union of all the meshes. Please report this issue on the Sceneform issue tracker.

Thanks!

**Comment by hemantkadamata** [comment]
thanks @romainguy
