### ISSUE TITLE
Support building filament as a nested project

### ISSUE THREAD

**Issue by millag** [google/filament#861]
**Describe the bug**
I would like to build _filament_ as part of my project i.e. as a nested one. However some of the _filament_'s sub-projects such as _filamat_ assume that _filament_ is at the top level of the source tree by explicitly relying on CMAKE_SOURCE_DIR to point to _filament_ repo root directory.

In general relying that CMAKE_SOURCE_DIR and CMAKE_BINARY_DIR will point to a specific location is a bad practice. I've been able to fix that locally by replacing ${CMAKE_SOURCE_DIR}  with ${TNT_SOURCE_DIR} inside filament/libs/filamat/CMakeLists.txt, however I haven't tested the build for all platforms and configurations so there might be other places that require such change.

**To Reproduce**
1. create dir third_party
2. checkout filament into third_party/filament
3. create CMakeLists.txt in the top level third_party dir with the following content:
cmake_minimum_required( VERSION 3.1 FATAL_ERROR )
project( third_party )
add_subdirectory( filament )
4. try building the top level project

**Expected behavior**
Being able to build filament as a nested project

**Comment by prideout** [comment]
Interesting, I think we can fix this by using paths that are relative to CMAKE_CURRENT_SOURCE_DIR rather than CMAKE_SOURCE_DIR.
