### ISSUE TITLE
In AR mode， part of 3D object is inside  the detected plane

### ISSUE THREAD

**Issue by yimo2015** [google/filament#869]
In AR mode, the filament engine places the local center of the object on the geometric center. This will  cause a part of the object to be “inside” the detected plane, 

**To Reproduce**
In AR mode, this problem occurs when the filament renders a 3D object.

**Expected behavior**
We expect filament can place the local origin of the three-dimensional object at the base of the object aligned horizontally with the geometric center.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by romainguy** [comment]
Filament is only a renderer and does not decide where to place objects. Please file this issue on the Sceneform bug tracker: https://github.com/google-ar/sceneform-android-sdk/issues

Thanks!
