### ISSUE TITLE
Make mesh/material tooling more accessible to the general populous

### ISSUE THREAD

**Issue by richardanaya** [google/filament#872]
Filament is super cool, but getting started with the tooling to create these custom mesh/material formats is complex.

It would be nice if binary versions of the tools were made available OR some kind of website where you could process your meshes online.

Alternatives are learning your build system, not that it's impossible, but some percentage of people will just never download your repo and figure out the details of building your system

Additionally, making these tools widely available as binaries might make it easier for people to put them into 3d modelers as exporters.

All operating systems.

**Comment by romainguy** [comment]
Thanks for the suggestion. Note that all the relevant tools are included in our release archives (`matc` and `filamesh` in particular). The tools are available for all supported operating systems as binaries in those release archives.
