### ISSUE TITLE
Build errors on Ubuntu 14.04

### ISSUE THREAD

**Issue by Neversrd** [google/filament#876]
I managed to build *debug* version of filament on Ubuntu 14.04 but failed to build *release* version by running the build.sh script. Got long error logs as follows:

> [58/1036]Linking CXX executable libs/math/test_math
>FAILED: libs/math/test_math 
: && /usr/local/bin/clang++  -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -Wl,--gc-sections   -rdynamic libs/math/CMakeFiles/test_math.dir/tests/test_fast.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_mat.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_vec.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_quat.cpp.o  -o libs/math/test_math  -static-libgcc -static-libstdc++ libs/math/libmath.a third_party/libgtest/tnt/libgtest.a -static-libgcc -static-libstdc++ -pthread && :
libs/math/CMakeFiles/test_math.dir/tests/test_fast.cpp.o: In function `__clang_call_terminate':
test_fast.cpp:(.text.__clang_call_terminate[__clang_call_terminate]+0x2): undefined reference to `__cxa_begin_catch'
test_fast.cpp:(.text.__clang_call_terminate[__clang_call_terminate]+0x7): undefined reference to `std::terminate()'
>etc...

I noticed that `__cxa_begin_catch` is a symbol of libc++abi and the CMakeLists.txt located in `FILAMENT_PATH/libs/math/` indeed didn't link libc++abi, so I modified line 43 (and some other instructions need to be modified) to `target_link_libraries(test_${TARGET} PRIVATE math gtest c++abi)
`. It works and the building process proceeds successfully.

I don't know whether the root cause of this issue is CMakeLists.txt or not, so I post it here.
Thank you in advance.

**Comment by romainguy** [comment]
Did you set the option `FILAMENT_REQUIRES_CXXABI` when invoking CMake? It's required on Ubuntu 14 and other distros. `README.md` mentions that you should add `-DFILAMENT_REQUIRES_CXXABI=true` to the CMake command if you run into issues with `libc++abi`.

**Comment by romainguy** [comment]
I was able to build properly on Ubuntu 14.04 (our CI is on this exact version of Ubuntu). Please open a new issue if `FILAMENT_REQUIRES_CXXABI` doesn't work.
