### ISSUE TITLE
Trouble viewing demos on iOS safari/chrome

### ISSUE THREAD

**Issue by richardanaya** [google/filament#878]
https://google.github.io/filament/webgl/suzanne.html

Just see a white page

**Comment by TimvanScherpenzeel** [comment]
Safari does not yet support WebGL2 though it is in development and supposedly supported in preview though last time I tried it did not work yet.

You can follow the development here: https://webkit.org/status/#specification-webgl-2 and the support table here: https://caniuse.com/#search=webgl2

**Comment by richardanaya** [comment]
Thank you @TimvanScherpenzeel , maybe this issue might be better as "keep an up to date list of which browsers Filament runs on" :)
