### ISSUE TITLE
Consider a web component interface to Filament

### ISSUE THREAD

**Issue by richardanaya** [google/filament#880]
This weekend I prototyped out a web component wrapper for filament https://github.com/richardanaya/pbr-scene maybe it's inspiration for something you all might want to make officially?  I would love for Filament to compete with A-Frame.

**Comment by prideout** [comment]
Interesting. However I think I see Filament as being lower-level than this, and I'm worried about the maintenance burden.  Filament is more parallel to ThreeJS than it is to A-Frame.
