### ISSUE TITLE
Bug in filament/android/Windows.md

### ISSUE THREAD

**Issue by NemoHzy** [google/filament#882]
**Describe the bug**
I think there maybe a bug in filament/android/Windows.md file，where the path “toolchains/Windows/**arm-linux-android-4.9**” is not match the build script whose path is “**arm-linux-androideabi-4.9**”

Toolchains
Generate a toolchain for each Android architecture you're interested in building for.
From Filament's root directory, run the NDK make_standalone_toolchain.py script for each 
....
architecture.python %ANDROID_HOME%\ndk-bundle\build\tools\make_standalone_toolchain.py ^
    --arch arm ^
    --api 21 ^
    --stl libc++ ^
    --force ^
    --install-dir "toolchains/Windows/**arm-linux-android-4.9**”
....
"
When I enter the next step build,  as below
"
cd out\cmake-android-release-arm7
cmake ^
    -G Ninja ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DCMAKE_INSTALL_PREFIX=..\android-release\filament ^
    -DCMAKE_TOOLCHAIN_FILE=..\..\build\toolchain-arm7-linux-android.cmake ^
    ..\..
"
the  CMakeError.log shows:

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: .../**arm-linux-androideabi-4.9**/bin/arm-linux-androideabi-clang.cmd 
Build flags: ;-mthumb;-march=armv7-a;-mcpu=cortex-a15;-mfloat-abi=softfp;-mfpu=neon-vfpv4;-DANDROID;-fPIE
Id flags: -c 

The output was:系统找不到指定的文件。

**Comment by bejado** [comment]
Thank you!
