### ISSUE TITLE
Modify `frame_generator` to read a file with different transformations

### ISSUE THREAD

**Issue by lukkio88** [google/filament#883]
Hi, I'm referring to [this discussion](https://github.com/google/filament/issues/859) for my question.

If I wanted to pre-specify a set of transformations to be applied per frame?
Ideally I'd like to load a set of poses from a file and use them to modify the transformation applied to the object rendered.

The bit you pointed out is before the actual rendering starts, at least this is what appears to me.
Should I modify either the `static void render(Engine*, View*, Scene*, Renderer*) ` or `static void postRender(Engine*, View* view, Scene*, Renderer* renderer)`?

**Comment by romainguy** [comment]
You should change the `render()` function.

**Comment by lukkio88** [comment]
What exactly would I need to modify?
