### ISSUE TITLE
ImGui broken on tip of tree

### ISSUE THREAD

**Issue by romainguy** [google/filament#887]
When I run an ImGui app on tip of tree, a bug happens when moving the mouse over a color picker:

<img width="1136" alt="screen shot 2019-02-25 at 5 28 10 pm" src="https://user-images.githubusercontent.com/869684/53380609-d5ca7f80-3922-11e9-826d-cc4dc6c6f387.png">

It should look like this:

<img width="1136" alt="screen shot 2019-02-25 at 5 28 13 pm" src="https://user-images.githubusercontent.com/869684/53380623-e67af580-3922-11e9-9dcf-ef888639fe69.png">

I tried to revert [Adrian's change](https://github.com/google/filament/commit/38a6d047c97823ee4bc379a350da73177244721c) but it's not causing the issue.

**Comment by romainguy** [comment]
@pixelflinger The bug is caused by your "Improve bind buffer range" change

**Comment by prideout** [comment]
@pixelflinger note that imgui mutates vertex buffers.  It also destroys & recreates the vertex buffers associated with a single long-lived renderable.
