### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by lukkio88** [google/filament#893]
Hi,

Is there any documentation available for the math library used in the several samples provided with the library?

There's a documentation in the docs folder, but it seems to more of an high level overview of what filament provides (I can't see any code related documentation).

**Comment by romainguy** [comment]
Filament's public APIs are mostly documented in the header files (and you can use doxygen to generate the docs). The math library isn't documented at the moment. It mostly follows GLSL.

**Comment by romainguy** [comment]
See issue #172
