### ISSUE TITLE
Windows build warning and shaders question

### ISSUE THREAD

**Issue by codeAPmind** [google/filament#901]
when building the meshoptimizer on windows with clang6.0 and VS2015, it shows “argument unused during compilation '/Gm-'”.. Aditionally, I want to know how to build shaders and see the changes of cloth without building all projects? Thank you in advance

**Comment by romainguy** [comment]
Argument unused isn't a problem unless it breaks your build. I'm not sure about what you're asking wrt shaders? Are you trying to modify the shaders/ directory or are you talking about material files?

**Comment by codeAPmind** [comment]
I want to modify the shaders, by which it may also affect the material files, but now I have to rebuild all projects then I can see the changes ; for example, I change some indirectional light shader and build the shader project, then in material_sanbox window, I cannot find any difference, it seems that I have to build mat and filamat ,  but only in that case that I build all the projects(ALL_BUILD) the cloth in material_sanbox window begin to change. 
Is there a simple way to modify the shader and show the graphic showing?

**Comment by romainguy** [comment]
You just need to rebuild material_sandbox. The materials, filamat and matc will get rebuilt automatically.

**Comment by codeAPmind** [comment]
Thank you for your patience!  I have tried that process several times.  I edited the material_sandbox related shaders ( for example,  return color*0.0 in cloth fragment shader) and rebuilt the project material_sandbox, but the showing in the material_sandbox window didn't change(it is still colorful, not black).  So, how your group debugs the shaders easily in this program.

**Comment by romainguy** [comment]
We just edit the shaders and rebuild the executable. The shaders are a dependency of `filamat`, itself a dependency of `matc` which in turn is a dependency of the material files we build for all the samples. We don't do anything special. Here's the most recent command I typed to test changes in cloth shaders (inside `out/cmake-release`):

```
$ ninja material_sandbox
$ ./samples/material_sandbox -i ~/Dropbox/Work\ in\ Progress/pbr/assets/env/river/ ./assets/models/cloth/cloth.obj
```
