### ISSUE TITLE
Basic set-up for building an app using filament.

### ISSUE THREAD

**Issue by lukkio88** [google/filament#902]
Hi,

Is there explained somewhere what do I need to set up / include if I wanted to implemented an app from scratch?

More specifically I'm hacking a bit some of your examples, there's a CMakeLists.txt in the sample folder but apparently it cannot be used stand alone, so I was wondering what would I need to modify to make it re-usable in general.

Thank you

**Comment by prideout** [comment]
I assume you use C++?  I'm considering writing a tutorial series similar to our [javascript tutorials](https://google.github.io/filament/webgl/) but for C++ developers.

**Comment by lukkio88** [comment]
Yep, C++.

**Comment by romainguy** [comment]
The easiest thing to do as a starter is to use the headers and libraries from the release archives. Some are optional (libfilamat for instance).

**Comment by lukkio88** [comment]
@romainguy You mean like explicitly find the dependencies and set up a CMakeLists.txt accordingly?

**Comment by bejado** [comment]
You don't need to use CMake- Make is probably simpler if you're just getting started. See [linking against Filament](https://github.com/google/filament/blob/master/filament/README.md#linking-against-filament) for instructions on how to link C++ with Filament using Make.

**Comment by lukkio88** [comment]
For few reason I'd prefer CMake, I'll ask a separate question.
