### ISSUE TITLE
Linking against filament + CMake

### ISSUE THREAD

**Issue by lukkio88** [google/filament#909]
Hi there,

I'm following [this page](https://github.com/google/filament/blob/master/filament/README.md#linking-against-filament) in order to understand how to link against filament.

Assuming I have the structure:
```
|-- README.md
|-- bin
|-- docs
|-- include
|-- lib
|-- main.cpp
```

And my `main.cpp` is simply:
```
#include <filament/FilamentAPI.h>
#include <filament/Engine.h>

using namespace filament;

int main(int argc, char** argv)
{
    Engine *engine = Engine::create();
    engine->destroy(&engine);
    return 0;
}
```

The page suggests I could use the following makefile:

```
FILAMENT_LIBS=-lfilament -lbluegl -lbluevk -lfilabridge -lfilaflat -lutils
CC=clang++

main: main.o
	$(CC) -Llib/x86_64/ main.o $(FILAMENT_LIBS) -lpthread -lc++ -ldl -o main

main.o: main.cpp
	$(CC) -Iinclude/ -std=c++14 -pthread -c main.cpp

clean:
	rm -f main main.o

.PHONY: clean
```

However I'm trying to set up a simple CMakeLists.txt with the same purpose. At the moment I have the folder structure:

```
|-- README.md
|-- bin
|-- docs
|-- include
|-- lib
|-- main.cpp
|-- CMakeLists.txt
```

(Essentialy the same as before, except for the `CMakeLists.txt` file).
My CMakeLists.txt looks like:

```
cmake_minimum_required(VERSION 3.11 FATAL_ERROR)
project(filament-test)

set(CMAKE_CXX_STANDARD 14)

set(SRC main.cpp)
link_directories(./lib/x86_64)

find_package (Threads)

add_executable(filament-test ${SRC})
target_link_libraries(filament-test filament bluegl bluevk filabridge filaflat utils pthread c++ dl)
target_include_directories(filament-test PUBLIC ./include)
```

the buiding using cmake goes fine, but when I run the line `make --j8` I get a bunch of linking errors:

```
In function `filaflat::SpirvDictionaryReader::unflatten(filaflat::Unflattener&, filaflat::BlobDictionary&)':
SpirvDictionaryReader.cpp:(.text._ZN8filaflat21SpirvDictionaryReader9unflattenERNS_11UnflattenerERNS_14BlobDictionaryE+0xb1): undefined reference to `smolv::GetDecodedBufferSize(void const*, unsigned long)'
SpirvDictionaryReader.cpp:(.text._ZN8filaflat21SpirvDictionaryReader9unflattenERNS_11UnflattenerERNS_14BlobDictionaryE+0x19f): undefined reference to `smolv::Decode(void const*, unsigned long, void*, unsigned long)'
collect2: error: ld returned 1 exit status
CMakeFiles/filament-test.dir/build.make:83: recipe for target 'filament-test' failed
make[2]: *** [filament-test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/filament-test.dir/all' failed
make[1]: *** [CMakeFiles/filament-test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

Can you help?

**Comment by lukkio88** [comment]
Just an update:

My CMakeLists.txt now is:
```

cmake_minimum_required(VERSION 3.11 FATAL_ERROR)
project(filament-test)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_COMPILER /usr/bin/clang-cpp-8)

set(SRC main.cpp)
link_directories(./lib/x86_64)

find_package (Threads)

add_executable(filament-test ${SRC})
target_link_libraries(filament-test filament bluegl bluevk filabridge filaflat utils pthread c++ dl)
target_include_directories(filament-test PUBLIC ./include)
```

After running `cmake` and later `make -j8` I get

```
[ 50%] Building CXX object CMakeFiles/filament-test.dir/main.cpp.o
[100%] Linking CXX executable filament-test
clang: warning: CMakeFiles/filament-test.dir/main.cpp.o: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -Wl,-rpath,/home/FilamentTest/filament/./lib/x86_64: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lfilament: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lbluegl: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lbluevk: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lfilabridge: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lfilaflat: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lutils: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lpthread: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lc++: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -ldl: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/home/FilamentTest/filament/./lib/x86_64' [-Wunused-command-line-argument]
[100%] Built target filament-test
```

All these warnings concern me a bit.

**Comment by bejado** [comment]
You need to set up the Filament dependencies as [`IMPORTED` targets](https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/Exporting-and-Importing-Targets) because you're using pre-built binaries:

```
add_library(filament STATIC IMPORTED)
set_target_properties(filament PROPERTIES IMPORTED_LOCATION path/to/libfilamat.a)
```

Then you can link against them: `target_link_libraries(filament-test filament)`.

**Comment by lukkio88** [comment]
At the moment I have this:

```
cmake_minimum_required(VERSION 3.11 FATAL_ERROR)
project(filament-test)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_COMPILER /usr/bin/clang-cpp-8)
set(CMAKE_VERBOSE_MAKEFILE on )

set(SRC main.cpp)
link_directories(./lib/x86_64)

find_package (Threads)

add_library(filament STATIC IMPORTED)
set_target_properties(filament PROPERTIES IMPORTED_LOCATION lib/x86_64/libfilamat.a)

add_executable(filament-test ${SRC})
target_link_libraries(filament-test filament bluegl bluevk filabridge filaflat utils pthread c++ dl)
target_include_directories(filament-test PUBLIC ./include)
```

But still, `cmake` goes fine but `make -j8` or `ninja` doesn't, specifically for ninja I simply get:

`ninja: error: 'lib/x86_64/libfilamat.a', needed by 'filament-test', missing and no known rule to make it`

**Comment by lukkio88** [comment]
Managed to get a different error:

```
cmake_minimum_required(VERSION 3.11 FATAL_ERROR)
project(filament-test)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_COMPILER /usr/bin/clang-cpp-8)
#set(CMAKE_VERBOSE_MAKEFILE on )

set(SRC main.cpp)
set(PREFIX ${CMAKE_SOURCE_DIR}/lib/x86_64/)

find_package(Threads)

add_library(filament STATIC IMPORTED)
add_library(bluegl STATIC IMPORTED)
add_library(bluevk STATIC IMPORTED)
add_library(filabridge STATIC IMPORTED)
add_library(filaflat STATIC IMPORTED)
add_library(utils STATIC IMPORTED)

set_target_properties(filament PROPERTIES IMPORTED_LOCATION ${PREFIX}libfilament.a)
set_target_properties(bluegl PROPERTIES IMPORTED_LOCATION ${PREFIX}libbluegl.a)
set_target_properties(bluevk PROPERTIES IMPORTED_LOCATION ${PREFIX}libbluevk.a)
set_target_properties(filabridge PROPERTIES IMPORTED_LOCATION ${PREFIX}libfilabridge.a)
set_target_properties(filaflat PROPERTIES IMPORTED_LOCATION ${PREFIX}libfilaflat.a)
set_target_properties(utils PROPERTIES IMPORTED_LOCATION ${PREFIX}libutils.a)

add_executable(filament-test ${SRC})
target_link_libraries(filament-test filament bluegl bluevk filabridge filaflat utils pthread c++ dl)
target_include_directories(filament-test PUBLIC ./include)
```

The error I get is:

```
[ 50%] Building CXX object CMakeFiles/filament-test.dir/main.cpp.o
[100%] Linking CXX executable filament-test
clang: warning: CMakeFiles/filament-test.dir/main.cpp.o: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lpthread: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -lc++: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: warning: -ldl: 'linker' input unused in cpp mode [-Wunused-command-line-argument]
clang: error: cannot specify -o when generating multiple output files
CMakeFiles/filament-test.dir/build.make:89: recipe for target 'filament-test' failed
make[2]: *** [filament-test] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/filament-test.dir/all' failed
make[1]: *** [CMakeFiles/filament-test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Apparently using the absolute path make a difference, but I still get errors.

**Comment by bejado** [comment]
Replace libfilamat.a with libfilament.a. Sorry, that was a typo on my part.

**Comment by lukkio88** [comment]
Done that, still it doesn't work (see my last CMakeLists.txt file).

**Comment by lukkio88** [comment]
Also, I don't know if this is normal, If I use `gcc` instead of `clang` I get a bunch of errors, like the following:

```error: assignment of read-only location ‘(& lhs)->filament::math::details::TVec3<T>::operator[]<float>(i)’
             lhs[i] -= v[i];
                    ^
error: body of constexpr function ‘constexpr VECTOR<T>& filament::math::details::TVecAddOperators<VECTOR, T>::operator-=(const VECTOR<T>&) const [with VECTOR = filament::math::details::TVec3; T = float]’ not a return-statement
     }
     ^
 error: invalid static_cast from type ‘const filament::math::details::TVecAddOperators<filament::math::details::TVec3, float>’ to type ‘filament::math::details::TVec3<float>&’
         VECTOR<T>& lhs = static_cast<VECTOR<T>&>(*this);```

I don't know if this is expected.

**Comment by lukkio88** [comment]
I figured... You need to add:

`FILAMENT_LIBS=-lfilament -lbluegl -lbluevk -lfilabridge -lfilaflat -lutils -lsmol-v`

And it worked for me.

**Comment by romainguy** [comment]
`gcc` isn't a support compiler for Filament unfortunately.

**Comment by lukkio88** [comment]
Hi, since this is still open, is it possible to modify the `CMakeLists.txt` of the examples example to build only the `frame_generator.cpp` example?

I'd like to factor that specific example out of the filament build so I can modify it.
Thank you

**Comment by lukkio88** [comment]
Maybe the right question, since I managed to build using the binaries is... suppose I clone filament and I build it from scratch, and I want to use it as dependency for my personal app/project. What do I need to do to build against it?

**Comment by lukkio88** [comment]
Hi again, I would really appreciate any sort of directions here.

**Comment by faisalkalim** [comment]
> I figured... I needed to add:
> 
> `FILAMENT_LIBS=-lfilament -lbluegl -lbluevk -lfilabridge -lfilaflat -lutils -lsmol-v`
> 
> And it worked for me.

Stupid question, can you please write the entire line as added in cmakelists.txt file. Thanks

**Comment by lukkio88** [comment]
There's no stupid question. If you have a CMakeLists I can tell you what's wrong probably.

**Comment by faisalkalim** [comment]
Thank you. 
I am just trying out the same example as probably you did. Here is the cmakelists.txt 
cmake_minimum_required(VERSION 3.1)
project(filament-test)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_COMPILER /usr/bin/clang-cpp-7)
set(CMAKE_VERBOSE_MAKEFILE on )

set(SRC main.cpp)
link_directories(./lib/x86_64)


find_package (Threads)


add_library(filament STATIC IMPORTED)
set_target_properties(filament PROPERTIES IMPORTED_LOCATION lib/x86_64/libfilament.a)

add_executable(filament-test ${SRC})
target_link_libraries(filament-test filament bluegl bluevk filabridge filaflat utils pthread c++ dl)
target_include_directories(filament-test PUBLIC ./include)

**Comment by lukkio88** [comment]
what errors do you get when you run this?

**Comment by faisalkalim** [comment]
Here is the complete list, when I try to run make command: 

/usr/bin/cmake -H/home/faisal/Desktop/filament -B/home/faisal/Desktop/filament/build --check-build-system CMakeFiles/Makefile.cmake 0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/faisal/Desktop/filament/build
/usr/bin/cmake -E cmake_progress_start /home/faisal/Desktop/filament/build/CMakeFiles /home/faisal/Desktop/filament/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/faisal/Desktop/filament/build'
make -f CMakeFiles/filament-test.dir/build.make CMakeFiles/filament-test.dir/depend
make[2]: Entering directory '/home/faisal/Desktop/filament/build'
cd /home/faisal/Desktop/filament/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/faisal/Desktop/filament /home/faisal/Desktop/filament /home/faisal/Desktop/filament/build /home/faisal/Desktop/filament/build /home/faisal/Desktop/filament/build/CMakeFiles/filament-test.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/faisal/Desktop/filament/build'
make -f CMakeFiles/filament-test.dir/build.make CMakeFiles/filament-test.dir/build
make[2]: Entering directory '/home/faisal/Desktop/filament/build'
[ 50%] Building CXX object CMakeFiles/filament-test.dir/main.cpp.o
/usr/bin/clang-cpp-7   -I/home/faisal/Desktop/filament/./include  -std=gnu++14 -o CMakeFiles/filament-test.dir/main.cpp.o -c /home/faisal/Desktop/filament/main.cpp
make[2]: *** No rule to make target 'lib/x86_64/libfilament.a', needed by 'filament-test'.  Stop.
make[2]: Leaving directory '/home/faisal/Desktop/filament/build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/filament-test.dir/all' failed
make[1]: *** [CMakeFiles/filament-test.dir/all] Error 2
make[1]: Leaving directory '/home/faisal/Desktop/filament/build'
Makefile:87: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lukkio88** [comment]
Kindly also the folder structure, relative to the CMakeLists.txt

**Comment by faisalkalim** [comment]
Here is it: 

|-- README.md
|-- bin
|-- build
|-- docs
|-- include
|-- lib
|-- main.cpp
|-- CMakeLists.txt

**Comment by lukkio88** [comment]
I think there's something wrong with how you link your libraries. To solve this error:

`make[2]: *** No rule to make target 'lib/x86_64/libfilament.a', needed by 'filament-test'. Stop`

Change the line:
`set_target_properties(filament PROPERTIES IMPORTED_LOCATION lib/x86_64/libfilament.a)`
With
`set_target_properties(filament PROPERTIES IMPORTED_LOCATION {CMAKE_SOURCE_DIR}/lib/x86_64/libfilament.a)$`

**Comment by lukkio88** [comment]
Also I link all the other libraries (`bluegl bluevk filabridge filaflat utils`) in a similar way (i.e. I don't use `link_directories`, for some reason it wasn't working for me)

**Comment by lukkio88** [comment]
This works for me:

```
cmake_minimum_required(VERSION 3.1)
project(filament-test)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_COMPILER /usr/bin/clang++-7)
set(CMAKE_VERBOSE_MAKEFILE on )

set(SRC main.cpp)
set(LIB_PATH ${CMAKE_SOURCE_DIR}/lib/x86_64/)

find_package (Threads)

set(LIBS filament bluegl bluevk filabridge filaflat utils smol-v)
add_executable(filament-test ${SRC})

foreach(lib ${LIBS})
        add_library(${lib} STATIC IMPORTED)
        set_target_properties(${lib} PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/lib/x86_64/lib${lib}.a)
        target_link_libraries(filament-test ${lib})
endforeach()

target_link_libraries(filament-test pthread c++ dl)
target_include_directories(filament-test PUBLIC ./include)
```
