### ISSUE TITLE
Building for Android on Linux fails

### ISSUE THREAD

**Issue by kpeeters** [google/filament#911]
I built filament on a Linux host as per the instructions. After that, I tried

    ./build.sh -p android release

which, unfortunately, bails out with

    [1/177] : && /usr/bin/cmake -E remove third_party/libgtest/tnt/libgtest.a && "" qc third_party/libgtest/tnt/libgtest.a  third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/src/gtest-all.cc.o && :
    FAILED: third_party/libgtest/tnt/libgtest.a 
     : && /usr/bin/cmake -E remove third_party/libgtest/tnt/libgtest.a && "" qc third_party/libgtest/tnt/libgtest.a  third_party/libgtest/tnt/CMakeFiles/gtest.dir/__/src/gtest-all.cc.o && :
    /bin/sh: 1: : Permission denied

It's probably something trivial, but if it rings any bells with anyone, please let me know.

**Comment by romainguy** [comment]
This is due to a CMake bug. You need a more recent version of CMake (3.13 works for us).
