### ISSUE TITLE
how to do skinned mesh rendering

### ISSUE THREAD

**Issue by heitaoflower** [google/filament#922]
**Describe the bug**

Hi guys!

Right now I am trying to complete a demo which rendering an animated mesh with bones.
I just reference the demo of ogldev 38-course content. 
The first step is ok, the mesh parse and present were ok.  demonstrated as the following figure.

![no bones](https://user-images.githubusercontent.com/26708932/53734269-74745480-3ebe-11e9-813d-63334fd9333a.png)

The second step I am trying to submit bones data something like weights and indices of bones. 
at the same time, I also increase the buffer and submit the bones data.
![with bones](https://user-images.githubusercontent.com/26708932/53734699-af2abc80-3ebf-11e9-9ff5-f2cb7feb4592.png)

the snippet of code as following.

`vertexBufferBuilder.attribute(VertexAttribute::BONE_INDICES, 4, VertexBuffer::AttributeType::UINT, 0, sizeof(VertexBoneData));
	vertexBufferBuilder.attribute(VertexAttribute::BONE_WEIGHTS, 4, VertexBuffer::AttributeType::FLOAT4, sizeof(unsigned int) * 4, sizeof(VertexBoneData));`

`	vertexBuffer_->setBufferAt(*filamentEngine, 4,
		VertexBuffer::BufferDescriptor(bs->data(), bs->size(), State<VertexBoneData>::free, bs));`

`if (rcm.getPrimitiveCount(instance) > 0)
			{
				rcm.setBones(instance, &transforms[0], g_model->getBoneCount(), 0);
			}`

`	RenderableManager::Builder builder(mesh->parts_.size());
		builder.boundingBox(mesh->aabb_);
		builder.skinning(boneCount_);`

by the way, the shader I used was default *LIT* shader, I think that it enabled SKINNED feature.

I hope you guys give me some hints or guides, is there any operation I lost? thank you very much.

**Comment by prideout** [comment]
Your code seems reasonable although I'd use UINT4 instead of UINT for BONE_INDICES.  See also our [JavaScript skinning demo](https://github.com/google/filament/blob/master/web/samples/skinning.html) and our [gltfio](https://github.com/google/filament/blob/master/libs/gltfio/src/Animator.cpp#L320) library.  What does your VertexBoneData struct definition look like?

**Comment by heitaoflower** [comment]
thank you for your rely.
my *VertexBoneData* looks like this:
`struct VertexBoneData
	{
		unsigned int boneIds[4];
		float weights[4];

		VertexBoneData()
		{
			reset();
		}

		void reset()
		{
			ZERO_MEM(boneIds);
			ZERO_MEM(weights);
		}

		void addBoneData(unsigned int boneId, float weight);
	};`

Actually, I have a tiny question about shader or material, I have not found any info about bones or skinning settings with the default LIT shader.

so do I need to write a new material shader that supports skin bones ?

**Comment by prideout** [comment]
Hm that looks fine.  You do not need to do anything special in your material, Filament will automatically enable skinning in the vertex shader when you set the bone count on the `RenderableBuilder` using the `skinning` method.

**Comment by heitaoflower** [comment]
Thank you very much.

I will try, by the way, is there any demo or prototype program to test gltfio library? 
Maybe I should debug it, learn it.

**Comment by romainguy** [comment]
What kind of issues are you running into? We're preparing a new, cleaner gltf viewer with much easier  code to read that will show how to do skinning.

**Comment by heitaoflower** [comment]
@romainguy Hi,  Very excited to see your feedback. I just referring a branch of gltfio to write a demo.
however, my personal demo always encounter some issures, I have no idea, maybe you are right, if you guys could offer a cleaner , simple demo will be a big help for me  or someone else to write skinned animation by filament.

**Comment by prideout** [comment]
The [JavaScript skinning demo](https://github.com/google/filament/blob/master/web/samples/skinning.html) is very simple, does not a load glTF file, and is fairly 1:1 with C++.
