### ISSUE TITLE
Building for Android on Mac fails

### ISSUE THREAD

**Issue by shanysheng** [google/filament#926]
**Describe the bug**
I built android version filament on a Mac host . using ninja

`./build.sh -p android release`

**Screenshots**

![image](https://user-images.githubusercontent.com/2736286/53787458-e5b51580-3f59-11e9-93c2-42f31753fcbf.png)

unfortunately, it always fail. Could we compile android version filament on a Mac host? thanks.

**Comment by romainguy** [comment]
Hi, building Android on macos is supported (I use macos myself). This error happens because your version of CMake has a known bug. You need to upgrade CMake (I use CMake 3.13 and the bug doesn't happen). Make sure you have NDK 19 too.

**Comment by shanysheng** [comment]
Great! It works. Thanks a lot.
