### ISSUE TITLE
Bound SamplerGroup refers to a destroyed Texture

### ISSUE THREAD

**Issue by prideout** [google/filament#935]
After the FrameGraph landed, the backend started to see SamplerBuffers that refer to destroyed textures. The GL backend is robust against this, but it triggers an assertion in VulkanDriver::draw.

Initially I thought that this was a Vulkan backend bug -- it should be robust like the GL backend, which is smart enough to ignore unused samplers in the SamplerBuffer.  However when I tried to fix this, I added complexity to SamplerBindingMap, which makes me uneasy.

It might be better to prevent this from occurring in the FrameGraph or PostProcessManager. Mathias what do you think?  To summarize, the issue occurs with the following sequence of events:

- The `execute` functor for FXAA calls `setSource` with texture 73, thus adding it to the SamplerBuffer.
- The`execute` functor for FXAA then makes a successful draw call within a renderpass.
- The FrameGraph then calls `Resource::destroy` for texture 73, but does not remove it from the SamplerBuffer.
- The subsequent draw call then asserts in Vulkan because Vulkan tries to bind texture 73 which is destroyed.

**Comment by pixelflinger** [comment]
@prideout okay, that seems reasonable, I will have a look.
What are the repro steps?

**Comment by prideout** [comment]
To repro simply run the `samples/suzanne` demo with no command line arguments.
