### ISSUE TITLE
GL errors with Chrome Canary

### ISSUE THREAD

**Issue by prideout** [google/filament#939]
The GLES spec requires the comparison mode to be COMPARE_REF_TO_TEXTURE when sampling from a depth texture using a shadow sampler. We are setting this up correctly in `ShadowMap::prepare`, however we are somehow losing this state by the time we make a draw call.

Many GL implementations seem to allow this without erroring, but WebGL in Chrome Canary has extra validation that triggers an error.  **To repro: add `builder.castShadows(true)` to MeshReader.cpp and launch the helmet or suzanne demos in Canary.**

Theory: the texture is bound but not actually sampled by the shader, which is why there is no apparent error on most platforms.

Possibly related to #935

CC @AdrianAtGoogle

**Comment by romainguy** [comment]
Are we losing the GL state or the Filament sampler state? (`compareMode` in `SamplerParams`)

**Comment by pixelflinger** [comment]
@prideout I tracked `SamplerParams` from the shadowmap code to the gl draw calls using material_sandbox and didn't see this problem. Is it specific to this test?

**Comment by prideout** [comment]
You're right, I added some prints and it looks like the sampler is properly using COMPARE_REF_TO_TEXTURE.  I'll set up a repro page so that the Chrome team can investigate.

**Comment by prideout** [comment]
Hack workaround: adbdfeb21bae854d43cc69d046f0d7f8a2c2d56f

**Comment by prideout** [comment]
The Chrome team has acknowledged a bug on their end but are unlikely to get it in before Chrome 73, so I'll leave this open in case we need to do a temporary workaround such as adbdfeb.

**Comment by romainguy** [comment]
The parquet and flighthelmet demos don't work for me on Chrome 72. Parquet shows a black frame, FlightHelmet shows nothing (just a white background).

**Comment by prideout** [comment]
`parquet` and `helmet` are now fixed on Chrome 72, there were files in Friday's web update that didn't get merged.   Note that helmet is our only demo with shadows, so it will regress when Chrome 73 lands unless we have a workaround.  I'm not sure if it's worth adding a workaround to Filament given Chrome's frequent update schedule.

**Comment by prideout** [comment]
We confirmed through experimentation that the Chrome team has fixed this in the next version, meanwhile our helmet demo has been upgraded to use gltfio, and it now has a workaround in place.
