### ISSUE TITLE
Point light doesn't work with the lit shading model?

### ISSUE THREAD

**Issue by tsuyoshimishina** [google/filament#94]
Set true to the g_moreLights variable in lightbulb.cpp, build the project, and then run it with the VS debugger. It throws an exception which displays the following message in the output window:

> Debug Assertion Failed!
> Program: C:\WINDOWS\SYSTEM32\MSVCP140D.dll
> File: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility
> Line: 1769
> Expression: array iterator not decrementable

I also tried to change the directional light to a point light in the material_sandbox example, and it caused exactly the same problem (exception) above.

My testing environment is:
 - OS: Windows 10 Pro 
 - GPU: NVIDIA GeForce GTX 1050 Ti
 - Backend: OpenGL

**Comment by romainguy** [comment]
Do you have a full stack trace? It looks like a debug assert is triggered inside MS implementation. Poinr lights do work fine on other platforms. You can run the lightbulb sample with -m instead of changing the code BTW.

**Comment by tsuyoshimishina** [comment]
The full stack trace is following (run with the '-m' option): 
> msvcp140d.dll!00007ffa4e29f886()	不明
> lightbulb.exe!std::_Array_const_iterator<utils::BufferRange,4>::operator--() 行 1770	C++
> lightbulb.exe!std::_Array_iterator<utils::BufferRange,4>::operator--() 行 1982	C++
> lightbulb.exe!std::_Array_iterator<utils::BufferRange,4>::operator--(int) 行 1988	C++
> lightbulb.exe!utils::RangeSet<4>::vector<utils::BufferRange,4,void>::insert(std::_Array_iterator<utils::BufferRange,4> pos, const utils::BufferRange & value) 行 89	C++
> lightbulb.exe!utils::RangeSet<4>::set(unsigned int offset, unsigned int count) 行 144	C++
> lightbulb.exe!filament::GPUBuffer::invalidate(unsigned __int64 row, unsigned __int64 count) 行 147	C++
> lightbulb.exe!filament::GPUBuffer::invalidate() 行 143	C++
> lightbulb.exe!filament::details::Froxelizer::froxelizeAssignRecordsCompress() 行 706	C++
> lightbulb.exe!filament::details::Froxelizer::froxelizeLights(filament::details::FEngine & engine, const math::details::TMat44<float> & viewMatrix, const utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator,utils::LockingPolicy::NoLock,utils::TrackingPolicy::Untracked>,math::details::TVec4<float>,math::details::TVec3<float>,utils::EntityInstance<filament::LightManager,0>,unsigned char> & lightData) 行 524	C++
> lightbulb.exe!filament::details::FView::froxelize(filament::details::FEngine & engine) 行 595	C++
> lightbulb.exe!filament::details::FRenderer::ColorPass::renderColorPass::<unnamed-tag>::operator()(utils::JobSystem &, utils::JobSystem::Job *) 行 545	C++
> lightbulb.exe!utils::JobSystem::createJob<`lambda at C:\mishina\projects\filament\filament\src\RenderPass.cpp:545:13'>::stub::call(void * user, utils::JobSystem & js, utils::JobSystem::Job * job) 行 212	C++
> lightbulb.exe!utils::JobSystem::execute(utils::JobSystem::ThreadState & state) 行 228	C++
> lightbulb.exe!utils::JobSystem::wait(const utils::JobSystem::Job * job) 行 340	C++
> lightbulb.exe!filament::details::FRenderer::ColorPass::beginRenderPass(filament::CommandStream & driver, const filament::Viewport & viewport, const filament::details::CameraInfo & camera) 行 485	C++
> [インライン フレーム] lightbulb.exe!filament::details::RenderPass::render(filament::details::FEngine & engine, utils::JobSystem & js, const utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator,utils::LockingPolicy::NoLock,utils::TrackingPolicy::Untracked>,utils::EntityInstance<filament::RenderableManager,0>,math::details::TMat44<float>,filament::details::FRenderableManager::Visibility,filament::Handle<filament::HwUniformBuffer>,filament::Handle<filament::HwUniformBuffer>,math::details::TVec3<float>,unsigned char,unsigned char,math::details::TVec3<float>,utils::Slice<filament::details::FRenderPrimitive,unsigned int>,unsigned int> & soa, utils::Range<unsigned int> vr, unsigned int commandTypeFlags, unsigned char renderFlags, const filament::details::CameraInfo & camera, const filament::Viewport & viewport, utils::GrowingSlice<filament::details::RenderPass::Command,unsigned int> & commands)	C++
> lightbulb.exe!filament::details::FRenderer::ColorPass::renderColorPass(filament::details::FEngine & engine, utils::JobSystem & js, filament::Handle<filament::HwRenderTarget> rth, filament::details::FView * view, const filament::Viewport & scaledViewport, utils::GrowingSlice<filament::details::RenderPass::Command,unsigned int> & commands) 行 584	C++
> lightbulb.exe!filament::details::FRenderer::renderJob(utils::ArenaScope<utils::Arena<utils::LinearAllocator,utils::LockingPolicy::NoLock,utils::TrackingPolicy::HighWatermark> > & arena, filament::details::FView * view) 行 192	C++
> lightbulb.exe!filament::details::FRenderer::render(const filament::details::FView * view) 行 106	C++
> lightbulb.exe!filament::Renderer::render(const filament::View * view) 行 370	C++
> lightbulb.exe!FilamentApp::run(const Config & config, std::function<void (filament::Engine *, filament::View *, filament::Scene *)> setupCallback, std::function<void (filament::Engine *, filament::View *, filament::Scene *)> cleanupCallback, std::function<void (filament::Engine *, filament::View *)> imguiCallback, unsigned __int64 width, unsigned __int64 height) 行 335	C++
> lightbulb.exe!SDL_main(int argc, char * * argv) 行 422	C++
> lightbulb.exe!main_utf8(int argc, char * * argv) 行 126	C
> lightbulb.exe!main_getcmdline() 行 159	C
> lightbulb.exe!main(int argc, char * * argv) 行 171	C
>

**Comment by romainguy** [comment]
Thanks!

**Comment by tsuyoshimishina** [comment]
I pulled the latest commit and tested again, and got an assertion failure at another line of xutility.

> Debug Assertion Failed!
> Program: C:\WINDOWS\SYSTEM32\MSVCP140D.dll
> File: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility
> Line: 1794
> Expression: array iterator + offset out of range

The full stack is following:

> msvcp140d.dll!00007ffa4980f886()	不明
> lightbulb.exe!std::_Array_const_iterator<utils::BufferRange,4>::operator+=(__int64 _Off) 行 1795	C++
> lightbulb.exe!std::_Array_iterator<utils::BufferRange,4>::operator+=(__int64 _Off) 行 1995	C++
> lightbulb.exe!std::_Array_iterator<utils::BufferRange,4>::operator-=(__int64 _Off) 行 2006	C++
> lightbulb.exe!std::_Array_iterator<utils::BufferRange,4>::operator-(__int64 _Off) 行 2012	C++
> lightbulb.exe!utils::RangeSet<4>::set(unsigned int offset, unsigned int count) 行 153	C++
> lightbulb.exe!filament::GPUBuffer::invalidate(unsigned __int64 row, unsigned __int64 count) 行 147	C++
> lightbulb.exe!filament::GPUBuffer::invalidate() 行 143	C++
> lightbulb.exe!filament::details::Froxelizer::froxelizeAssignRecordsCompress() 行 706	C++
> lightbulb.exe!filament::details::Froxelizer::froxelizeLights(filament::details::FEngine & engine, const math::details::TMat44<float> & viewMatrix, const utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator,utils::LockingPolicy::NoLock,utils::TrackingPolicy::Untracked>,math::details::TVec4<float>,math::details::TVec3<float>,utils::EntityInstance<filament::LightManager,0>,unsigned char> & lightData) 行 524	C++
> lightbulb.exe!filament::details::FView::froxelize(filament::details::FEngine & engine) 行 595	C++
> lightbulb.exe!filament::details::FRenderer::ColorPass::renderColorPass::<unnamed-tag>::operator()(utils::JobSystem &, utils::JobSystem::Job *) 行 545	C++
> lightbulb.exe!utils::JobSystem::createJob<`lambda at C:\mishina\projects\filament\filament\src\RenderPass.cpp:545:13'>::stub::call(void * user, utils::JobSystem & js, utils::JobSystem::Job * job) 行 212	C++
> lightbulb.exe!utils::JobSystem::execute(utils::JobSystem::ThreadState & state) 行 228	C++
> lightbulb.exe!utils::JobSystem::wait(const utils::JobSystem::Job * job) 行 340	C++
> lightbulb.exe!filament::details::FRenderer::ColorPass::beginRenderPass(filament::CommandStream & driver, const filament::Viewport & viewport, const filament::details::CameraInfo & camera) 行 485	C++
> [インライン フレーム] lightbulb.exe!filament::details::RenderPass::render(filament::details::FEngine & engine, utils::JobSystem & js, const utils::StructureOfArraysBase<utils::Arena<utils::HeapAllocator,utils::LockingPolicy::NoLock,utils::TrackingPolicy::Untracked>,utils::EntityInstance<filament::RenderableManager,0>,math::details::TMat44<float>,filament::details::FRenderableManager::Visibility,filament::Handle<filament::HwUniformBuffer>,filament::Handle<filament::HwUniformBuffer>,math::details::TVec3<float>,unsigned char,unsigned char,math::details::TVec3<float>,utils::Slice<filament::details::FRenderPrimitive,unsigned int>,unsigned int> & soa, utils::Range<unsigned int> vr, unsigned int commandTypeFlags, unsigned char renderFlags, const filament::details::CameraInfo & camera, const filament::Viewport & viewport, utils::GrowingSlice<filament::details::RenderPass::Command,unsigned int> & commands)	C++
> lightbulb.exe!filament::details::FRenderer::ColorPass::renderColorPass(filament::details::FEngine & engine, utils::JobSystem & js, filament::Handle<filament::HwRenderTarget> rth, filament::details::FView * view, const filament::Viewport & scaledViewport, utils::GrowingSlice<filament::details::RenderPass::Command,unsigned int> & commands) 行 584	C++
> lightbulb.exe!filament::details::FRenderer::renderJob(utils::ArenaScope<utils::Arena<utils::LinearAllocator,utils::LockingPolicy::NoLock,utils::TrackingPolicy::HighWatermark> > & arena, filament::details::FView * view) 行 192	C++
> lightbulb.exe!filament::details::FRenderer::render(const filament::details::FView * view) 行 106	C++
> lightbulb.exe!filament::Renderer::render(const filament::View * view) 行 370	C++
> lightbulb.exe!FilamentApp::run(const Config & config, std::function<void (filament::Engine *, filament::View *, filament::Scene *)> setupCallback, std::function<void (filament::Engine *, filament::View *, filament::Scene *)> cleanupCallback, std::function<void (filament::Engine *, filament::View *)> imguiCallback, std::function<void (filament::Engine *, filament::View *, filament::Scene *, filament::Renderer *)> preRender, std::function<void (filament::Engine *, filament::View *, filament::Scene *, filament::Renderer *)> postRender, unsigned __int64 width, unsigned __int64 height) 行 349	C++
> lightbulb.exe!SDL_main(int argc, char * * argv) 行 422	C++
> lightbulb.exe!main_utf8(int argc, char * * argv) 行 126	C
> lightbulb.exe!main_getcmdline() 行 159	C
> lightbulb.exe!main(int argc, char * * argv) 行 171	C
>
