### ISSUE TITLE
Build failure on Fedora 29

### ISSUE THREAD

**Issue by nitronoid** [google/filament#946]
**Describe the bug**
Compilation failure on Fedora 29

**To Reproduce**
I followed the README build instructions, using the cmake for linux set. 
CMake correctly produces the build files with no errors, however when building with the ninja command,
the linker complained:
```
/usr/bin/ld: cannot find -lc++abi
/usr/bin/ld: cannot find -lc++
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Solution**
The README specified that we need to install the `libcxx-devel` dependency, however to fix my issue I also needed to install:
```
libcxx-static
libcxxabi-static
```
I think this should be added to the README

**Comment by romainguy** [comment]
Thanks, I've update the README!
