### ISSUE TITLE
Working with geometry normals in web

### ISSUE THREAD

**Issue by John-DeCorato-HZ** [google/filament#959]
I'm writing a GTLF loader for web and I'm getting stuck working with normal data. I've noticed there are utility functions to calculate the tangents in the C++ code. But when messing with the web bindings these have either not been documented well or are missing. Is there a way to use Filament's helper functions for this on web or do I have to replicate them?

**Comment by romainguy** [comment]
@prideout can explain how to use the `SurfaceOrientation` API. Philip, is that API exposed in JS yet?

**Comment by prideout** [comment]
SurfaceOrientation is not yet exposed to JS, I'll look into that.

**Comment by John-DeCorato-HZ** [comment]
Thanks!

**Comment by prideout** [comment]
Note to self: as a prep step, the SurfaceOrientation builder will need to consume BufferDescriptors rather than raw pointers.

**Comment by prideout** [comment]
See implementation of `Filament.IcoSphere` for a usage example.

**Comment by John-DeCorato-HZ** [comment]
Excellent! Thanks for handling this so quickly.
