### ISSUE TITLE
Allow mutation of culling and doubleSided.

### ISSUE THREAD

**Issue by prideout** [google/filament#963]
To make it easier to create ubershader-style materials, I propose adding the following methods:

1) `MaterialInstance::setMaskThreshold`
        - prints warning if BlendingMode is not MASK
2) `MaterialInstance::setBackfaceCulling`
3) `MaterialInstance::disableDoubleSided`
        - prints warning if doubleSided is not enabled on the Material
        - implemented in fragment shader by adding an if inside the #if

Additionally, but more tentatively:

4) `MaterialBuilder::blendingCapability` and `MaterialInstance::setBlendingMode`
        - `setBlendingMode` prints warning if `blendingCapability` is not enabled on the Material
        - the existing `MaterialBuilder::blending` method keeps its current semantics (it automatically enables the capability)
        - implemented in fragment shader by adding if's inside #if's

**Comment by romainguy** [comment]
The mask threshold can already be changed.

**Comment by romainguy** [comment]
Not sure we should change blending though.

**Comment by romainguy** [comment]
Why disableDoubleSided instead of setDoubleSided?

**Comment by prideout** [comment]
Changing the double-sided property won't work if it wasn't originally enabled in the MaterialBuilder (we want to keep the simple case small and keep our #if), and I feel that this behavior is better implied by "disable" than "set". 

Allowing mutable blending would be super useful but yeah it would an intrusive change.

**Comment by romainguy** [comment]
What I had in mind was if you specify `doubleSided: false` it would enable the capability, allowing you to set (same thing if you set it to true in the material).

**Comment by prideout** [comment]
Ok that makes sense.

**Comment by romainguy** [comment]
So the way `maskThreshold` works is that it creates an implicit material parameter called `maskThreshold` that you can access through `materialParams`. You can also call `getMaterialThreshold()`. The getter is generated by `ShaderGenerator.cpp` but this doesn't seem necessary. It should just be in `getter.fs` and surrounded by `#if defined(BLEND_MODE_MASKED)`. Would you mind making that change too?

**Comment by prideout** [comment]
My proposal didn't include adding setters to `Material` because the mutation semantics are less obvious there (e.g. users might think that changing something on a material automatically changes it on all its child instances) whereas it is straightforward with `MaterialInstance`.

**Comment by romainguy** [comment]
Yeah but mask threshold is different as it's a material parameter. It would just be adding convenience functions for a built-in uniform.
