### ISSUE TITLE
filament materials and obj + mtl files

### ISSUE THREAD

**Issue by lukkio88** [google/filament#964]
Hi there, do I need to compile the `.mtl` files using the `matc` tool if I wanted to render the mesh say using the `frame_generator` example?

Though it seems that the only format that the `matc` accepts as input is the filament `.mat` format.
despite the obj I'm using reference the right material file it doesn't seem to do anything, I can view the mesh without texture.

Do I need to modify the `.mat` somehow and then recompile it?

**Comment by prideout** [comment]
Sounds like you're using MeshAssimp which doesn't necessarily honor the mtl files associated with obj models.  In the future we would like to provide a library for loading OBJ files.

In the mean time you may with to consider an alternative model format such as glTF instead of OBJ.

**Comment by prideout** [comment]
Our assimp-based samples like frame_generator do not necessarily honor the mtl files associated with OBJ models.  We plan on replacing assimp with our own OBJ loader.  In the mean time you may wish to consider an alternative model format such as glTF.

**Comment by romainguy** [comment]
matc does not compile .MTL files. Those files are partially supported by MeshAssimp (no textures, constants work). There's already a feature request open to add support for .MTL files, I'll close this one.

**Comment by lukkio88** [comment]
Is there any converter or tutorial I can follow you can point out? Does `frame_generator` support the glTF format?

**Comment by lukkio88** [comment]
Is there any tutorial or converter obj to glTF you can point out? I've never heard of such format until today.

**Comment by sugatmankar** [comment]
@prideout any update on obj loader?
