### ISSUE TITLE
filament + glTF file

### ISSUE THREAD

**Issue by lukkio88** [google/filament#967]
Hi, following [this](https://github.com/google/filament/issues/964#issuecomment-472043469) discussion.
I was wondering if anyone could quickly tell me the necessary steps to convert from an obj + mtl + maps to glTF, there're tools online but as far as I've seen it seems only the mesh is processed.

Thank you

**Comment by romainguy** [comment]
You can try Blender 2.80 beta. It comes with a glTF exporter.

**Comment by prideout** [comment]
Filament is a renderer with some accompanying utility libraries, I'm not sure if this is the right place for pipeline questions.
