### ISSUE TITLE
frame-generator example doesn't render materials in .gltf

### ISSUE THREAD

**Issue by lukkio88** [google/filament#973]
Hi there,

As suggested in [this question](https://github.com/google/filament/issues/964#event-2197440349), I've been converting one of my `.obj`s using `obj2gltf` as a conversion tool. I can see the material nodes in the `.gltf` are assigned (but I'm not an expert with this format).

Using the example `frame-generator` when I provide my `.gltf` as input I'm unable to visualize the actual material, which I think is overwritten by the `.mat` file compiled using the matc generator.

Could you please point out if there's a way around this problem?

Do I need (how?) to disable the `.mat` used by the sample? Do I need to hack the code somewhere to use the materials provided by the `.gltf`?

**Comment by romainguy** [comment]
`frame_generator` is designed to generate multiple frames with varying values for the parameters of a supplied material. What are you expecting `frame_generator` to do with your glTF file and its built-in materials?
