### ISSUE TITLE
Shader failure on Mali GPU

### ISSUE THREAD

**Issue by rawnsley** [google/filament#974]
I'm certain this is a GPU driver bug that is merely exposed by Filament, but I wanted to steal 10 seconds of your attention in case you've seen anything like it before. Feel free to close this as "not our problem".

If I take the lit cube demo project and make it split-screen, with two cameras and two views side-by-side, I get a curious problem on my RK3288 with a Mali-T760 GPU (driver versions 11 or 14) [as shown in this video](http://avn.pub/NUARRg). Basically the first view that gets rendered (the left) has all black pixels. My Pixel 1 shows both cubes fine and the Intel-based device shown on the right in the video also works perfectly.

I think I've narrowed it down to a silent crash in the fragment shader whenever it tries to read FrameUniforms or LightsUniforms. For example, a shader that should just draw red or green depending on the value of frameUniforms.time will draw black. If I extend to four cameras and four views, only the last one is drawn and the first three are all black.

I suspect that during the various uniform buffer allocations some sort of synchronization guarantee is not being honoured by the driver and previous allocations become corrupt. I'm trying to make the simplest reproduce possible independent of Filament, but in the meantime I wondered if anyone has seen anything like it before?

**Comment by romainguy** [comment]
Thank you. This looks very similar to an issue we've had in the past on Mali GPUs. We have a workaround but it may just not be enabled for your particular variant of Mali. @pixelflinger is checking what the workaround is right now.

**Comment by pixelflinger** [comment]
We ran in a problem that looks very similar on Mali GPU before. It affected only the Mali-T series.
The workaround we found at the time was to disable "early fragment test" in the shaders. It had something to do with optimizations in the compiler.

However, since then, we have removed that feature (early_fragment_tests) from all our shaders because we ran into other problems. So, the workaround for Mali-T became obsolete. It looks like you found a new way to trigger this problem :-\

**Comment by rawnsley** [comment]
Do you have a suitable target device for testing? I can attach the repo project if it would help. Either way I can try and confirm the issue here.

**Comment by rawnsley** [comment]
[Here's the modified version](https://github.com/google/filament/files/2965554/MainActivity.kt.zip) of sample file /filament/android/samples/lit-cube/app/src/main/java/com/google/android/filament/litcube/MainActivity.kt

Note that the problem is only present when _isPostProcessingEnabled_ is **false**. There is [a known issue](https://github.com/google/filament/issues/651) with the depth buffer not being allocated in this state and coupled with what @pixelflinger said about the early_fragment_tests it's possible that the GPU is bug is depth related.

Obviously I would prefer to always run with post-processing enabled, but the Mali GPU is just too slow.

**Comment by rawnsley** [comment]
I believe I have narrowed it down now and I finally have a 
[small repo project](https://github.com/google/filament/files/2967234/MaliBugDemo.zip) that is independent of Filament. 

The problem is buffer related and occurs only when several buffers are mapped to uniforms. The problem appears to go away if you don't call _glFlush()_ until the very end of the draw cycle.

I'll post the repo project to ARM for comment and for now I've just removed the call to _glFlush()_ in the OpenGL driver in my local copy of Filament. Opinions are welcome on whether this is safe and/or if I should still flush after all render calls are complete (perhaps in _endFrame_).

**Comment by romainguy** [comment]
Thank you for investigating. We use flushes to kick off GPU tasks as early as possible to maximize concurrent work, but it's not necessary. That could be the workaround on specific Mali GPUs.

**Comment by pixelflinger** [comment]
Wow. Thank you for the repro.  I will make more tests for this as well as implement the workaround -- however, in the meantime, would you be able to try to replace the glFlush() with a glReadPixels() of just 1x1? -- this should cause a flush too --.

Also, is the viewport call needed after the flush for the problem to happen?

**Comment by rawnsley** [comment]
@pixelflinger Thanks for the quick responses to this (as always from Team Filament)

I substituted the _glFlush_ call for this:
```
val pixelBuffer = ByteBuffer.allocateDirect(4).order(ByteOrder.nativeOrder())
GLES20.glReadPixels(0, 0, 1, 1, GLES20.GL_RGB, GLES20.GL_UNSIGNED_BYTE, pixelBuffer)
```
and the problem went away.

Removing the _glViewport_ calls made no difference though: the first triangle was still black.

FYI: I've [posted the question to ARM](https://community.arm.com/developer/tools-software/graphics/f/discussions/12793/render-bug-on-mali-t760) now.

**Comment by pixelflinger** [comment]
Okay, one more thing to try -- I promise :-) What about glFinish() instead?  (glReadPIxels is going to be more similar to a glFinish() than a glFlush()).

**Comment by rawnsley** [comment]
_glFinish_ instead of _glFlush_ also works.

**Comment by pixelflinger** [comment]
Okay great. I'm going to implement the "don't call glFlush" workaround for now. Thanks!

**Comment by rawnsley** [comment]
I've pulled those changes down and they work fine. Thanks again!
