### ISSUE TITLE
Android C++ example

### ISSUE THREAD

**Issue by kpeeters** [google/filament#980]
Am I looking in the wrong place or is there indeed no sample program yet for using filament purely on the C++ side (that is, using the C++ bindings directly, not the Java wrappers).

**Comment by romainguy** [comment]
We have one internally but its code is horrible and messy :) Is there anything in particular you need to know? The code is very similar to our desktop C++ samples.

**Comment by kpeeters** [comment]
No worry, I'll put something together myself and ask again if I run into problems. It's all in principle visible in the filament Java wrappers, though they do a lot more than I need (I just need to pass a Surface to the C++ side and then all the rest is handled there).

**Comment by kpeeters** [comment]
It looks like in my JNI_Onload I am supposed to call the JNI_OnLoad function defined in `filament/src/driver/opengl/PlatformEGL.h`, is that correct? But that header is not a public header. Is that what you meant with 'messy'? ;-)

**Comment by kpeeters** [comment]
The key thing I am trying to figure out is how to get the engine up and initialised with a Surface which I pass from Java, and preferably in such a way that it also gets shut down properly in a pause/resume cycle. The Java bindings are kinda jumping around all over the place for this, so if you have some pointers that would be much appreciated (I can provide a clean sample program in return if I get this to work).

**Comment by romainguy** [comment]
You don't need to call the other `JNI_OnLoad` no. You should simply call `Filament.init()` on the Java side to make sure everything is properly initialized on the Filament side.

For Surface management I recommend starting from `UiHelper.java` from the Java library and replace the references to `Engine` and `Renderer` with your own JNI bindings.

Here's the source of the sample I mentioned earlier. Hasn't been tested in a while, and it doesn't contain assets, etc.

[Archive.zip](https://github.com/google/filament/files/2967566/Archive.zip)

**Comment by kpeeters** [comment]
Brilliant, thanks, will submit a clean example when I get this all to run.

**Comment by konovalov-k** [comment]
@kpeeters Greetings. Can you share your results please?

**Comment by konovalov-k** [comment]
@kpeeters Well, I did it. Thx for the highlighted ways.
Everyone who need pure Android Filament C++ on Android can check [my repo](https://github.com/konovalov-k/Android-Filament-C-Example).
