### ISSUE TITLE
Quaternion Vector product does unexpected work

### ISSUE THREAD

**Issue by nitronoid** [google/filament#991]
**Describe the bug**
Not sure this is a bug, looks intended, however mathematically it's not correct.
Quaternion vector product is actually performing  Quaternion * vector * Inverse Quaternion.
This looks like it's intended to simplify rotations using quaternions.

**To Reproduce**
```
filament::math::quatf q (4.f, 0.f, 0.f, 0.f);
filament::math::float3 p (1.f, 1.f, 1.f);
auto r = q*p;
printf("%f, %f, %f\n", r.x, r.y, r.z);
// 1.000000, 1.000000, 1.000000
```

**Expected behavior**
I expected the vector to be simply treated as an imaginary quaternion, below is what I think should be equivalent.
```
filament::math::quatf q (4.f, 0.f, 0.f, 0.f);
filament::math::quatf p (0.f, 1.f, 1.f, 1.f);
auto r = q*p;
printf("%f, %f, %f\n", r.x, r.y, r.z);
// 4.000000, 4.000000, 4.000000
```

**Additional context**
This was unexpected for me, I think it would be more appropriate to have an explicit rotation function, rather than an operator overload here.

**Comment by romainguy** [comment]
Vectors should not be treated as quaternions, that's why we have two different types in the first place. Now whether multiplication between a vector and a quaternion should be exposed, that's a different question. This operation seems pretty common given how useful it is (like you said to implement vector rotations).

**Comment by pixelflinger** [comment]
Yes, I think transforming a vector (by a quat) is fairly common. Also there are precedent for using math operators for "invalid" math operations -- e.g opertor+ on strings! 
The main raison we have the quat class in the first place is to encode transforms and it is useful to have the same syntax than we have for matrices.
