### ISSUE TITLE
Building of material-builder sample fails for Android

### ISSUE THREAD

**Issue by obeletski** [google/filament#992]
I was interested in trying out material-builder and building failed because of
- missing /shader_ball.obj
- missing out/android-release/filament/lib/x86_64/libfilamat.a

See details below:

1: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':app:compileMesh'.
> File '/home/o00336023/open/filament/third_party/shader_ball/shader_ball.obj' specified for property 'inputFile' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':filamat-android:externalNativeBuildRelease'.
> Build command failed.
  Error while executing process /home/o00336023/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/o00336023/open/filament/android/filamat-android/.externalNativeBuild/cmake/release/x86_64 --target filamat-jni}
 
  ninja: error: '/home/o00336023/open/filament/out/android-release/filament/lib/x86_64/libfilamat.a', needed by '../../../../build/intermediates/cmake/release/obj/x86_64/libfilamat-jni.so', missing and no known rule to make it

**Comment by romainguy** [comment]
Thanks. We recently moved that file in a different directory, this will be an easy fix.
