### ISSUE TITLE
FilamentCanvas error

### ISSUE THREAD

**Issue by gdm-tts** [google/filament#994]
When using **FilamentCanvas** we got the following error:
```
in virtual void filament::PlatformWGL::makeCurrent(Platform::SwapChain *, Platform::SwapChain *):184
reason: wglMakeCurrent() failed. hdc = FFFFFFFFA7011C12
```

Using **FilamentPanel** works fine.

 - OS: Windows
 - GPU: NVIDIA GeForce GT 750M
 - Backend: OpenGL
 - Java: 1.8.0_151; Java HotSpot(TM) 64-Bit Server VM 25.151-b12
 - Filament: filament-sceneform-1.9pr1

**Comment by bejado** [comment]
Is there any additional error message? And is this reproducible 100% of the time?

**Comment by gdm-tts** [comment]
It happens every time, i.e. it is not possible to use FilamentCanvas, while wit FilamentPanel the exact same source code works. The window remains blank and no other errors are shown.

The attached simple example can be used to reproduce the bug (it is a NetBeans 8.2 project but the application structure is simple enough that I hope it can be opened in any IDE).
Commenting/uncommenting lines 82/83 can switch the use of FilamentCanvas/FilamentPanel.

[FilamentJavaExample.zip](https://github.com/google/filament/files/2972490/FilamentJavaExample.zip)

**Comment by bejado** [comment]
Can you try with an older release of Filament, say [Sceneform 1.7pr6](https://github.com/google/filament/releases/tag/sceneform-1.7pr6) and see if it still errors? Curious if this is a recent regression.

**Comment by gdm-tts** [comment]
I've done some tests with **pre-built binaries**, and the error happens with every version I've tested:
- **Sceneform-1.9pr1**
- **Sceneform 1.7pr6**
- **Sceneform 1.6pr3**

The pre-built binaries don't show any error message, they just crash.

The library used in my initial report was **Sceneform-1.9pr1** built with ninja 1.9.0 and LLVM/clang 7.0.1.

**Comment by bejado** [comment]
Thank you. I've been able to reproduce on my side and will continue looking into it.

**Comment by bejado** [comment]
@gdm-tts This should be fixed now in latest master.

**Comment by gdm-tts** [comment]
@bejado Yes, it now works for me. Thanks!
