### ISSUE TITLE
Trouble including headers for new `ibl` library

### ISSUE THREAD

**Issue by MiiBond** [google/filament#995]
**Describe the bug**
I grabbed the latest Sceneform-1.9pr1 build for Windows today to see if I could include the `ibl` lib in my Visual Studio project (so, no clang). However, it seems like the `utils/JobSystem.h` header is missing (referenced from CubemapUtils.h). And, if I include this file from the source, I end up needing to include a ton of other missing headers.
These additional headers include lots of `__restrict__` specifiers which Visual Studio complains about.

**To Reproduce**
1. Create a Visual Studio project that includes the `ibl` headers and links against the `ibl` lib.

**Expected behavior**
I was hoping to be able to use the `ibl` library by itself in a Visual Studio project without having to use clang.

**Desktop (please complete the following information):**
 - OS: Windows 10, Visual Studio 2017

**Comment by romainguy** [comment]
`ibl` depends on the `utils` library.

**Comment by MiiBond** [comment]
Thanks. I can easily link to `utils` as well but I still need the missing headers, don't I?

**Comment by romainguy** [comment]
You need the libutils headers yes. We could see about limiting how much of libutils is required in the public ibl headers too.

**Comment by MiiBond** [comment]
As far as I can see, `JobSystem.h` isn't included in the `utils` folder or anywhere else in the `Sceneform-1.9pr1` package.
I can copy the needed headers from the repo, of course, but I still end up with what I think is clang-specific code in these headers that Visual Studio errors out on. It would be wonderful if I could use these libs in a non clang project since it's already compiled code.

**Comment by pixelflinger** [comment]
Ah yes JobSystem.h isn't part of the "public" libutils headers, until now. Okay let me think about this some more. I'll look at the `__restrict__` stuff too.

**Comment by romainguy** [comment]
There is definitely an issue here then. @pixelflinger

**Comment by pixelflinger** [comment]
@MiiBond okay, these two issues should be fixed. Let us know if there are other road blocks.

**Comment by MiiBond** [comment]
Okay, I just tried this with release v1.2.0 and am running into another compile issue:
```
Error | C1189 | #error:  Compiler does not support the packed attribute.
include\utils\compiler.h | 43
```

**Comment by prideout** [comment]
Filament requires clang 7.
